### ISSUE TITLE
Marker on the line does not match with the appropriate grid line

### ISSUE THREAD

**Issue by Riim** [highcharts/highcharts#5232] opened 2016-04-20 13:48 UTC
#### Expected behaviour
https://yadi.sk/i/Z9k1DBILr9jEW

#### Actual behaviour
https://yadi.sk/i/sT_Zy5PIr9i5X
Appears not on all points and the value of existence depends on the width of the browser window.

#### Live demo of the issue
http://jsfiddle.net/u5td7sc6/2/

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment] 2016-04-21 09:21
Thanks for reporting! I'm afraid I can't see the issue in your live demo. Can you set a fixed chart width, and possibly say exactly what range we need to zoom in to to see the issue? Also, you should check if it's already fixed in the latest release.

**Comment by Riim** [comment] 2016-04-21 12:40
Highcharts version: 1.3.10.
Browsers: Chromium 50.0.2628.0 (64-bit), Yandex Browser 16.3.0.7847 (64-bit), FireFox 45.0.1
MacBook Pro, OS X 10.11.2 (15C50)
Video: https://monosnap.com/file/jaql5tqy8rM571SpBU5ObXFtbmlbS0

**Comment by TorsteinHonsi** [comment] 2016-04-21 13:36
Thanks, I've got a reliable reproduction at http://jsfiddle.net/highcharts/u5td7sc6/3/. Hover the `05.11.2015 15` point to set the offset from the xAxis label.

The problem is that the point value is not actually the same as the grid line. Apparently, your X axis is a linear (non-datetime) axis that is hacked into showing an offset date through formatters. We see this if we disable the formatters for axis labels and tooltip: http://jsfiddle.net/highcharts/u5td7sc6/4/, hover the  `14 450 450M` grid line.

So the question is why you are not using a standard datetime axis? See http://jsfiddle.net/highcharts/u5td7sc6/5/.

**Closed by TorsteinHonsi** 2016-04-21 13:36 UTC
Labels: Cant reproduce
