### ISSUE TITLE
plotLines.label.align/plotLines.label.verticalAlign works incorrectly in polar mode

### ISSUE THREAD

**Issue by Freywar** [highcharts/highcharts#6829] opened 2017-06-13 08:59 UTC
#### Expected behaviour
{align: 'right', verticalAlign: 'bottom'} places label in right bottom corner of line's BBox

#### Actual behaviour
Label is placed in seemingly random position

#### Live demo with steps to reproduce
http://jsfiddle.net/LLExL/7627/

#### Affected browser(s)
Any

The problem is in BBox calculation line - https://github.com/highcharts/highcharts/blob/9efbb0e5ae56f398924bc3cee9d077e203cdc810/js/parts/PlotLineOrBand.js#L207 - it assumes that plotLine's SVG path always consists of line's start and end points, but it's not correct for polar charts.

**Comment by pawelfus** [comment] 2017-06-13 15:58
Hi @Freywar 

Thank you for reporting!

I'm closing this as a duplicate of #6270

**Closed by pawelfus** 2017-06-13 15:58 UTC
