### ISSUE TITLE
Wrong position of text in data labels on errorbar chart after resizing chart block

### ISSUE THREAD

**Issue by alex1kirch** [highcharts/highcharts#5399] opened 2016-06-13 14:35 UTC
#### Expected behaviour
Position of text in data labels stay correct on errorbar chart after resizing chart block

#### Actual behaviour
Position of text in data labels becomes incorrect after after resizing chart block.

#### Live demo with steps to reproduce

jsfiddle.net/g31xhhh9/

#### Affected browser(s)
All

**Comment by pawelfus** [comment] 2016-06-13 14:42
Duplicate of #4133.

**Closed by pawelfus** 2016-06-13 14:42 UTC
