### ISSUE TITLE
stacked column chart tooltip issue

### ISSUE THREAD

**Issue by anisar200** [highcharts/highcharts#5511] opened 2016-07-20 10:29 UTC
when a category name contains '<' it should display the complete name along with <

but it only shows data before < if any. for example i have modified the default example of highcharts column chart and replaced Apples with <Apples and Oranges with Or<anges. Tooltip label for <Apples  is empty while tooltip for Or<anges contains Or and its display label displays Or<anges instead of Or<spannges

http://jsfiddle.net/e2fw9mod/1/

google chrome

**Comment by pawelfus** [comment] 2016-07-21 08:13
Hi @anisar200 ,

Thank you for reporting the issue, as for the workaround you can use `&lt;` instead of `<`, see: http://jsfiddle.net/e2fw9mod/2/

Closing as duplicate of #2379.

**Closed by pawelfus** 2016-07-21 08:13 UTC
Labels: Duplicate
