### ISSUE TITLE
Scrolling + zooming in/out on maps

### ISSUE THREAD

**Issue by cstambula** [highcharts/highcharts#16048] opened 2021-07-14 11:27 UTC
#### Expected behaviour
When the cursor meets the map while scrolling through a page, the map should zoom in and out by clicking on mouse scroll. Also when the cursor moves down to the end of the map, the page should continue to scroll to the below page sections.

#### Actual behaviour
When I move the cursor over the map I can't scroll the page. Zooming in / out on the map doesn't work either. 

The bug is visible on your demo chart:
https://www.highcharts.com/demo/maps/all-maps

Or on our website here: 
https://gvl.de/en/gvl/international-exchange/international-representation-agreements

Product version: 9.1.0

Affected browser(s): Firefox

**Comment by KacperMadej** [comment] 2021-07-14 15:34
Hi @cstambula 

Thank you for reporting the problem.

Are you using a Windows OS? This issue looks like a duplicate of https://github.com/highcharts/highcharts/issues/15656

**Comment by cstambula** [comment] 2021-07-14 15:36
Hi,

no, we are all using MAC.
Sorry for not mentioning that.

Kind regards,
Christina




publicgarden GmbH - Natürlich Lust auf Medien

Christina Stambula
Projektmanagement

Reinhardtstr. 27c
D-10117 Berlin

Tel.:  +49 30 629 322 - 050

URL: www.publicgarden.de <https://www.publicgarden.de/>
E-Mail: ***@***.*** ***@***.***> 

Geschäftsführer: Martina Murtfeld, Jörg Rennerich, Katja Karina Kapelle

Amtsgericht Charlottenburg, Berlin
Registernummer: HRB 95017 B

Diese E-Mail enthält vertrauliche oder rechtlich geschützte Informationen. Wenn Sie nicht der beabsichtigte Empfänger sind, informieren Sie bitte sofort den Absender und löschen Sie diese E-Mail. Das unbefugte Kopieren dieser E-Mail oder die unbefugte Weitergabe der enthaltenen Informationen ist nicht gestattet. Diese E-Mail wurde von uns beim Ausgang auf Viren geprüft, wegen der Gefahr auf den Übertragungswegen raten wir jedoch zu einer Eingangskontrolle. Eine Haftung auf Virenfreiheit schließen wir aus.

**Comment by cstambula** [comment] 2021-07-21 14:15
This is a different bug than here #16048.
We are using Mac and the bug is a browser issue...try to zoom with mouse wheel in Firefox with this map here: https://jsfiddle.net/wL6j9ten/
It does not work.

**Comment by KacperMadej** [comment] 2021-07-21 15:13
The issue was recreated on a Mac using a mouse. It is labeled as a bug.

> This is a different bug than here #16048.
Assuming you wanted to link a different issue than the one we are currently in - yes, the issue from my last comment is different from this one.

Unfortunately, there is no workaround at this moment for the problem.

**Comment by kuangchou** [comment] 2021-09-07 14:52
This error might be able to workaround by overwrite the onContainerMouseWheel function in Pointer.prototype as below:
    var` totalWheelDelta = 0;
    var totalWheelDeltaTimer;
    extend(H.Pointer.prototype, {
      // The event handler for the mouse scroll event
      onContainerMouseWheel: function (e) {
        var chart = this.chart;
        e = this.normalize(e);
        // Firefox uses e.deltaY or e.detail, WebKit and IE uses wheelDelta
        var delta = -(e.deltaY || e.detail || e.wheelDelta) / 120;  // Fixed Bug after the highcharts 9.0.1
        // Wheel zooming on trackpads have different behaviours in Firefox vs
        // WebKit. In Firefox the delta increments in steps by 1, so it is not
        // distinguishable from true mouse wheel. Therefore we use this timer
        // to avoid trackpad zooming going too fast and out of control. In
        // WebKit however, the delta is < 1, so we simply disable animation in
        // the `chart.mapZoom` call below.
        if (Math.abs(delta) >= 1) {
          totalWheelDelta += Math.abs(delta);
          if (totalWheelDeltaTimer) {
            clearTimeout(totalWheelDeltaTimer);
          }
          totalWheelDeltaTimer = setTimeout(function () {
            totalWheelDelta = 0;
          }, 50);
        }
        if (totalWheelDelta < 10 && chart.isInsidePlot(e.chartX - chart.plotLeft, e.chartY - chart.plotTop)) {
          chart.mapZoom(Math.pow(chart.options.mapNavigation.mouseWheelSensitivity, delta),
              chart.xAxis[0].toValue(e.chartX), chart.yAxis[0].toValue(e.chartY), e.chartX, e.chartY,
          // Delta less than 1 indicates stepless/trackpad zooming, avoid
          // animation delaying the zoom
          Math.abs(delta) < 1 ? false : void 0);
        }
      }
    });

**Comment by KacperMadej** [comment] 2021-09-09 10:47
@kuangchou 
Thank you for sharing the workaround.
There is a recently merged into master branch fix for mouse wheel event - could you check if using the code from the next release candidate works instead of your workaround?
Loading the code from the master GitHub branch is described on [code.highcharts.com](http://code.highcharts.com/).

_Please note that the code on the master branch (the next release candidate) is unstable, might change at any point, and might break at any point, so should be used only for testing and with caution._

**Comment by KacperMadej** [comment] 2022-02-03 17:01
Works fine on the current version. Closing as resolved,

**Closed by KacperMadej** 2022-02-03 17:01 UTC
Labels: Type: Bug, Product: Highcharts Maps, Status: Inbox
