### ISSUE TITLE
Set lineWidth for single marker in series

### ISSUE THREAD

**Issue by samb8s** [highcharts/highcharts#5896] opened 2016-10-27 12:31 UTC
#### Expected behaviour
var subject1 = [20,22,24,28,24, { marker: {
                                    fillColor: 'green',
                                    lineWidth: 3,
                                    lineColor: "#f39c12"
                                 }, y:29}];

Series should have one point with an orange border around it

#### Actual behaviour
There is no orange border, although it is barely visible when you mouseover

#### Live demo with steps to reproduce
http://jsfiddle.net/081e9sLy/4/

#### Affected browser(s)
Chrome is the only one tested

**Comment by sebastianbochan** [comment] 2016-10-28 14:23
Duplicate of #5897

**Closed by sebastianbochan** 2016-10-28 14:23 UTC
