### ISSUE TITLE
Bad spline rendering on shallow curves

### ISSUE THREAD

**Issue by hawaiikaos** [highcharts/highcharts#10634] opened 2019-04-29 10:29 UTC
#### Expected behaviour
A spline should draw a smooth line at any given thickness

#### Actual behaviour
Spline draws a weird shape closing fill on line thicknesses greater than 1 (which is why some people have previously reported it happening on hover). Is this bug that seems to come up time-to-time:
https://www.highcharts.com/forum/viewtopic.php?f=9&t=40941

#### Live demo with steps to reproduce
Live demo: https://jsfiddle.net/Lkegfazc/

Steps: create a shallow curve with a solid line style, with at least 2 line width.

I was able to correct the issue in the SVG by changing the stroke-linejoin to "bevel"  instead of the default "miter". All previous solutions seem to have been, 'wait for a new Chrome version to come out'. Changing this to bevel might be a more resilient solution.

#### Product version
Highcharts, but version seems irrelevant; this is a Chrome issue

#### Affected browser(s)
Currently Version 73.0.3683.103  of Chrome only.

**Comment by pawelfus** [comment] 2019-04-29 10:58
Hi @hawaiikaos 

Thanks for reporting the issue. It looks like a duplicate of #10514 - as you said, it's chrome-only issue, reported to chrome-devs. Issue was fixed ~9 days ago, now we need to wait for the new release :)

**Comment by pawelfus** [comment] 2019-06-04 09:11
Closing as duplicate of #10514.

**Closed by pawelfus** 2019-06-04 09:11 UTC
Labels: Status: Backlog
