### ISSUE TITLE
"Today" label in present in Internet Explorer but not in other browsers

### ISSUE THREAD

**Issue by douglasaraujotempo** [highcharts/highcharts#16038] opened 2021-07-13 20:23 UTC
#### Expected behaviour
Show "Today" label in all browsers, this way the plugin will have the same behavior in all browsers.

#### Actual behaviour
The "Today" label is only shown in Internet Explorer.

#### Screenshots with the error
Firefox: 
![image](https://user-images.githubusercontent.com/87393397/125518586-be1e9b8f-a7f7-44b7-bd28-d4c4c256ea01.png)

Internet Explorer:
![image](https://user-images.githubusercontent.com/87393397/125518634-18e83633-6565-4c76-9d88-9e9db66b691a.png)

#### Product version
v4.2.5 (2016-05-06)

#### Affected browser(s)
Chrome/ Firefox/ Edge

**Comment by KacperMadej** [comment] 2021-07-14 16:19
Hi @douglasaraujotempo 

Please add a live demo for the problem.

**Comment by douglasaraujotempo** [comment] 2021-07-14 18:30
Hi @KacperMadej sorry. Here it's is : [Live demo](https://jsfiddle.net/douglasaraujotempo/fjLn19ty/1).

When you open this in any browser the label defined in xAxis plotline is not shown, in Internet Explorer is shown.

**Comment by khlieng** [comment] 2021-07-15 08:58
It looks like this is a duplicate of #8477, it has been fixed since 6.1.1, theres a workaround posted in the other issue.

**Closed by khlieng** 2021-07-15 08:58 UTC
Labels: Type: Duplicate
