### ISSUE TITLE
stock tools - dragging segment line issue

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#14944] opened 2021-01-15 12:35 UTC
The segment line (or arrow or any other...) losts proper coordinates and finally disappears when is dragged on the left side of the chart. The image expresses more than a thousand words, so there is a video: 

https://hnet.com/video-to-gif/viewimage/20210114-23-T2sJfk43t9D8uHUf-Z4KI8o-HNET

#### Live demo with steps to reproduce

Demo: https://jsfiddle.net/BlackLabel/cnosa15L/

**Comment by khlieng** [comment] 2021-01-15 14:18
This is probably related to #2406.

**Comment by pawelfus** [comment] 2021-01-18 10:28
This is correct, setting `ordinal=false` resolves the issue: https://jsfiddle.net/BlackLabel/cnosa15L/1/

**Comment by ivan0071** [comment] 2021-01-21 12:37
@pawelfus setting `ordinal=false` resolves the issue with drawing indeed, but it also exposes the missing data periods to show as empty space on the axis (https://api.highcharts.com/highstock/xAxis.ordinal). So these two things are in conflict one with another and therefore I can not use he solution you suggested, as I don't want to show these gaps.

**Comment by PaulDalek** [comment] 2021-01-21 14:59
Hi @ivan-stojanov 

Thank you for contacting us. As for now this the solution for the problem that is described more in #2406. I’m closing this issue as a duplicate of it.

**Closed** 2021-01-21 15:00 UTC
Labels: Product: Highcharts Stock, Type: Bug, Type: Duplicate

**Comment by ivan-stojanov** [comment] 2021-01-22 08:58
Hello @PaulDalek, maybe the issues are connected in a way that probably the same bug in the source code is causing them, but I don't see a described solution for the concrete problem which is described above.

If you are referring to https://github.com/highcharts/highcharts/issues/2406#issuecomment-27385751 I see this is using renderer for drawing a lines using the hard-coded values, while the issue above is for drawing annotations with the `stock-tools` (and not only lines, the issue is valid for all type of the annotations).

Anyway thanks, I will subscribe to the ticket you pointed and will track if it will be resolved (as I don't see any solution for the issue in the comments).

**Comment by PaulDalek** [comment] 2021-01-25 13:42
@ivan-stojanov

The initial problem reported in this issue concerns the incorrect coordinates of a created line annotation when moving it on a chart. In a nutshell, it results from the missing ranges (hidden by the default value of the [`ordinal`](https://api.highcharts.com/highstock/xAxis.ordinal) option) where points aren’t present (which is explained in the #2406). The solution which concerns forcing displaying is a couple comments above ( setting the `ordinal` to false).

**Comment by pawelfus** [comment] 2021-01-27 09:10
> @pawelfus setting `ordinal=false` resolves the issue with drawing indeed, but it also exposes the missing data periods to show as empty space on the axis (https://api.highcharts.com/highstock/xAxis.ordinal). So these two things are in conflict one with another and therefore I can not use he solution you suggested, as I don't want to show these gaps.

My apologies for not being clear enough! My post was answering @khlieng that he is right, it's the same bug under the hood (bug caused by `ordinal` axis and rendering something outside the existing extremes).
