### ISSUE TITLE
Highcharts Column Not Showing Both Series When Visible Set To True

### ISSUE THREAD

**Issue by KoltonG** [highcharts/highcharts#5356] opened 2016-05-30 14:52 UTC
#### Expected behaviour
The expected behaviour is that all series should be shown when their visibility is set to true. 

In the example below, the graph shows x days of the week and only the first day, Saturday, has data. Therefore when both series visibility is set to true, both the red and green column should be shown.

Example image of the expected behaviour.
![screen shot 2016-05-30 at 11 39 38 am](https://cloud.githubusercontent.com/assets/3606121/15652258/4f0ff524-265b-11e6-920f-a6c807817a60.png)

#### Actual behaviour
The behaviour that is experienced is that only one of the two series, always the last series, is shown when there is 1 day out of the x days that has data. See image below.

![screen shot 2016-05-30 at 11 43 55 am](https://cloud.githubusercontent.com/assets/3606121/15652324/d0567a18-265b-11e6-8aef-e1bf75b1d2fe.png)
#### Live demo with steps to reproduce
When you click the JS Fiddle you should see only one column, lime green, even though there is two series that have a true visibility. When you uncomment line 59-60 and 68-69 you will see that both columns are shown when there are 2 out of the x days of data
https://jsfiddle.net/KoltonG/ovz6yuqc/

#### Affected browser(s)
All Browsers

**Comment by pawelfus** [comment] 2016-05-31 07:37
It's another example where Highcharts are unable to calculate `pointRange`, when using only one point (and extremes in this case). 

*Workaround:*
Set `pointRange: 24 * 3600 * 1000`
Demo: https://jsfiddle.net/ovz6yuqc/1/

**Comment by jon-a-nygaard** [comment] 2016-05-31 09:09
Closing this issue because it is a duplicate of #5219.

**Closed by jon-a-nygaard** 2016-05-31 09:09 UTC
Labels: Duplicate
