### ISSUE TITLE
Gantt, xAxis with set units, not displays headers even tho it has space

### ISSUE THREAD

**Issue by dragoshzava** [highcharts/highcharts#16627] opened 2021-11-10 07:45 UTC
#### Expected behaviour
To display the xAxis labels when it has space.

#### Actual behaviour
Does not display headers.

#### Live demo with steps to reproduce
https://jsfiddle.net/Resems/v8p93srL/3/

#### Product version
9.3.0

#### Affected browser(s)
N/A

**Comment by raf18seb** [comment] 2021-11-15 22:18
Hi @dragoshzava!

When there is a little space for label, the "November" is shortened to "Nov" (defined in `lang.shortMonths`).
Here is a demo showing it: https://jsfiddle.net/BlackLabel/bL0a1mzg/

You can define your own strings or even empty strings. Do you still think this is a bug or the ticket can be closed?

**Comment by dragoshzava** [comment] 2021-11-16 07:38
@raf18seb 

To elaborate on the issue, which has multiple ramifications.
In the first case, the displayed months should be October + November, October is not shown ( and the yAxis line is missing at the start )
![image](https://user-images.githubusercontent.com/3819194/141933714-5f71d682-696a-414b-bd45-86d6477aae24.png)

Depending on the screen size, and on the available space, sometimes it doesn't display even those.

https://jsfiddle.net/Resems/hwmt3Lo9/1/ This also displays only December, previous month is not available
![image](https://user-images.githubusercontent.com/3819194/141934912-13e43ea7-fbfb-4868-9d4b-793dcb463f45.png)

Year is displayed before or overlaps with the yAxis 
https://jsfiddle.net/Resems/3hbwaysu/
![image](https://user-images.githubusercontent.com/3819194/141935980-cb96b811-2e6f-4aee-ab46-c3011ef30912.png)

The biggest issue we are currently having with the labels, is that, when we try to customize, they do not display entirely.
We need the customization tho because we allow label translation depending on the language selected in our tool, the aggregation selected, etc.

So the end user can change dynamically from days to week to month to quarter, to year.
And depending on that, we translate the labels.

#### Examples Week
https://jsfiddle.net/Resems/3hbwaysu/9/ - Unit Week with null
https://jsfiddle.net/Resems/3hbwaysu/10/ - Unit week with values
![image](https://user-images.githubusercontent.com/3819194/141938825-c9b16e5d-9dc0-4a6c-b309-0b2689f763da.png)
![image](https://user-images.githubusercontent.com/3819194/141939762-0c641b67-793e-4f77-8bb2-67db873fab77.png)

#### Examples Quarter
https://jsfiddle.net/Resems/3hbwaysu/11/ - Does not display
https://jsfiddle.net/Resems/3hbwaysu/12/ - Works

On quarters, we cannot even set the lang option from hchart due to the fact that we can have on the same page, multiple month/quarter charts.

I hope this makes it more clear.

**Comment by raf18seb** [comment] 2021-11-17 15:31
@dragoshzava,

thanks for providing more info.

It looks like a duplicate of https://github.com/highcharts/highcharts/issues/15720, probably also related to https://github.com/highcharts/highcharts/issues/11899

**Comment by SMH110** [comment] 2022-07-18 15:52
any update on this?

**Comment by raf18seb** [comment] 2022-07-19 13:55
Hi @SMH110, unfortunately, we didn't have time to take care of this ticket because of some other more important tickets. Sorry, but we don't have ETA for it at this moment.

**Comment by karolkolodziej** [comment] 2023-11-17 14:42
Closing as a duplicate.

**Closed by karolkolodziej** 2023-11-17 14:42 UTC
Labels: Type: Duplicate, Product: Highcharts Gantt
