### ISSUE TITLE
Highstock Demos spline can't scroll horizontal in Android browser

### ISSUE THREAD

**Issue by jackgreentemp** [highcharts/highcharts#5351] opened 2016-05-27 10:55 UTC
Open the url below in android default browser, I can't scroll horizontal the chart.

http://www.highcharts.com/stock/demo/spline

I tried set pinchType: 'x' in my own demo, the chart still couldn't scroll horizontal.

What should I do to make it right?

**Comment by jackgreentemp** [comment] 2016-05-27 11:19
I found that if you scale the chart with two finger then you could scroll the chart horizontal.

How to make it work once the chart is loaded rather than not after scaling manually?

**Comment by TorsteinHonsi** [comment] 2016-05-30 08:33
This is a feature by design, see [these lines](http://jsfiddle.net/zkenuwu2/1/):

```js
		// Don't initiate panning until the user has pinched. This prevents us from
		// blocking page scrolling as users scroll down a long page (#4210).
		if (touchesLength > 1) {
			self.initiated = true;
		}
```

The rationale here is that in long pages, where the end user is scrolling down using one finger, we don't want to trap the touch event and prevent scrolling the page. So we don't initiate the scrolling feature until the user has touched with two fingers. But I admit that this functionality is not optimal if we're not in a website setting. For example, in a web app where the chart is the only page content, it could be disabled. 

Perhaps we should add an option for it?

**Comment by jon-a-nygaard** [comment] 2016-06-30 06:41
Closing this since it considered as not a bug, and pending a reply.

**Closed by jon-a-nygaard** 2016-06-30 06:41 UTC
Labels: Not a bug, Pending reply
