### ISSUE TITLE
Stack area with nulls and without connectNulls shows lines and markers not aligned

### ISSUE THREAD

**Issue by DK-Unit4** [highcharts/highcharts#9985] opened 2019-01-24 18:42 UTC
Sorry if it is a duplicate and we should use connectNulls  always
#### Expected behaviour
line connect to markers

#### Actual behaviour
markers and lines are not connected, i.e. markers are way out from lines

#### Live demo with steps to reproduce
https://jsfiddle.net/Kumlander/o52h0387/2/

#### Product version
Highcharts latest

#### Affected browser(s)
![capture2](https://user-images.githubusercontent.com/38954233/51701026-2f384980-2019-11e9-9fed-4b662930a438.PNG)
Chrome

**Comment by KacperMadej** [comment] 2019-01-24 18:44
@DK-Unit4 
Please add missing required info from the issue template - you could add new comment, edit your comment or even open a new issue - for a fresh start.
Here's it unclear what is your problem.

**Comment by DK-Unit4** [comment] 2019-01-24 18:48
Sorry

**Comment by KacperMadej** [comment] 2019-01-24 19:32
@DK-Unit4 
Thank you for all the info and for reporting about the problem.

As a workaround you could use `connectNulls` - https://jsfiddle.net/BlackLabel/213fnuxy/

At first it looks like a bug, but if you would consider how a chart looks with two points surrounded by nulls you will notice that other areas are moved up. https://jsfiddle.net/BlackLabel/213fnuxy/1/
So, if we were to have a single pixel line going down from the "floating" point from the original demo then it will look consistent. 

IMHO a single point has no area under it, but this topic is discussed here: https://github.com/highcharts/highcharts/issues/7161

This issue looks like a duplicate of the https://github.com/highcharts/highcharts/issues/7161
Please add any info you would like to add into the discussion to help us decide the issue #7161 
and please let me know if this issue could be closed as a duplicate or is there a difference between the issues that you could elaborate on?

**Comment by KacperMadej** [comment] 2019-03-24 08:17
Closing as a duplicate of #7161

**Closed by KacperMadej** 2019-03-24 08:17 UTC
Labels: Pending reply
