### ISSUE TITLE
Tooltip ignores  after change transform: scale

### ISSUE THREAD

**Issue by balkarov** [highcharts/highcharts#13468] opened 2020-05-08 09:03 UTC
![2](https://user-images.githubusercontent.com/6030335/81390086-8c2f1480-9123-11ea-91a0-1e7ceba5e88f.gif)

#### Expected behaviour
Tooltip has incorrect position

#### Actual behaviour
Tooltip has correct position (as mouse position)

#### Live demo with steps to reproduce
http://jsfiddle.net/a3rconxu/

#### Product version
Highcharts 8.1

#### Affected browser(s)
Google chrome 81.0.4044.129

**Comment by balkarov** [comment] 2020-05-08 09:09
Works only with workaround
https://github.com/highcharts/highcharts/issues/2405#issuecomment-132638603
http://jsfiddle.net/3hq9aoxL/

**Comment by Llorx** [comment] 2020-05-08 10:51
https://github.com/highcharts/highcharts/issues/12489

**Comment by sebastianbochan** [comment] 2020-05-11 07:48
Hi @balkarov,
Im closing the ticket as duplicate of https://github.com/highcharts/highcharts/issues/12489 and https://github.com/highcharts/highcharts/issues/2405

**Closed by sebastianbochan** 2020-05-11 07:48 UTC
