### ISSUE TITLE
Reproducible 4-year old bug: Highstock gapUnit breaks navigator

### ISSUE THREAD

**Issue by stroobandt** [highcharts/highcharts#7521] opened 2017-12-12 23:25 UTC
I was able to reproduce a Highstock `navigator` bug, first [reported on StackExchange](https://stackoverflow.com/q/46731201/2192488) 4 years ago by someone else.

#### Expected behaviour
I set `gapUnit = 'value'` in order to specify a `gapSize` in milliseconds.
This was done like this:    

    plotOptions: {
         series: {
                    dataGrouping: {enabled: true},
                    showInNavigator: true
                },
                line: {
                    gapSize: 15 * 60 * 1000,
                    gapUnit: 'value'
                }
            }

#### Actual behaviour
Setting `gapUnit` breaks the navigator at the bottom. It remains empty.

#### Live demo with steps to reproduce
Here is an [official working example](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/plotoptions/series-gapsize/).

It [no longer works](https://jsfiddle.net/stroobandt/f57qs9a4/) when changing the `gapUnit` to `'value'`.

See: https://jsfiddle.net/stroobandt/f57qs9a4/

#### Affected browser(s)
All.

**Comment by KacperMadej** [comment] 2017-12-13 11:32
Hi,

The behavior might look strange at first, but all seems to be working correctly.

If you set gapSize and gapUnit then all grouped data with point interval larger than 1 day (for your options) will fall into a gap. It's visible in your demo if you enable markers and select 'all' button in rangeSeletor: https://jsfiddle.net/BlackLabel/f57qs9a4/2/

Data in navigator is grouped and markers are disabled, so there's nothing to show there. You could enable markers to see that it's working fine: https://jsfiddle.net/BlackLabel/f57qs9a4/3/

This is not a bag, so I am closing the issue. If you have more info or would like to have the issue reopened, then please add a comment.

**Comment by stroobandt** [comment] 2017-12-13 16:52
Thank you for your quick reply, Kacper.

You very well explained the reason for this unexpected `navigator` behaviour; namely `dataGrouping`.

However, your proposed remedy changes the navigator. By default it comes without markers.
On the other hand, disabling `dataGrouping` for the `navigator` restores the default behaviour.
https://jsfiddle.net/stroobandt/e6k3h550/

Nevertheless, I keep thinking this is odd, unexpected behaviour. Apparently, I am not alone in doing so. At the very least, you should add a comment line to the Highstock `gridUnit` documentation.
As it currently stands, you built yourself a nice fly trap for developers ;-)

PS: I did my part, by answering the question on [StackExchange](https://stackoverflow.com/a/47794316/2192488).

**Comment by KacperMadej** [comment] 2017-12-14 12:05
Thank you for help with SO.

I'm adding the `Docs` tag and this issue should be resolved through improving API documentation.

**Comment by TorsteinHonsi** [comment] 2017-12-19 10:27
It may be that the best solution would be that the navigator series didn't inherit these options at all, to avoid the confusion. But there are two arguments against that:
 * Implementers who actually want this to happen to the navigator similar to the base series, would have to set it twice, so we're back creating something counter-intuitive.
 * The issue is not only with the navigator. In the [provided demo](https://jsfiddle.net/highcharts/f57qs9a4/4/), the same thing happens to the _base series_ when clicking the _All_ button.

So I agree with Kacper, we should resolve this through the documentation.

**Comment by stroobandt** [comment] 2017-12-19 11:44
Dear Torstein,
I am perfectly fine with resolving this through a small documentation improvement.

**Comment by pawelfus** [comment] 2018-07-26 12:08
Closing as it's resolved in the documentation.

**Closed by pawelfus** 2018-07-26 12:08 UTC
Labels: Docs
