### ISSUE TITLE
Heatmaps go all black and have messed up axes with a lot of data

### ISSUE THREAD

**Issue by dlopuch** [highcharts/highcharts#4174] opened 2015-05-07 23:28 UTC
I have a large heatmap (>1000 data points) that gets a messed up y-axis and has all points being black:

![screen shot 2015-05-07 at 4 24 19 pm](https://cloud.githubusercontent.com/assets/1427329/7527912/c4f685ea-f4d5-11e4-8fee-1efbe491bb0d.png)

The data array is represented as the turboThreshold-compatible x-y-value tuple form.

http://jsfiddle.net/2xa31Lda/4/

Fiddle contains stats (console-logged) proving tuple x-y references are valid to xAxis and yAxis categories.

The problem gets fixed when you filter out some of the data points (see end of fiddle)... seems to be caused only the quantity of data being large.

**Comment by highslide-software** [comment] 2015-05-08 09:47
Workaround: Set `turboThreshold` to 0.

**Comment by pawelfus** [comment] 2016-03-11 14:48
Duplicate of #4174

**Closed by pawelfus** 2016-03-11 14:48 UTC
Labels: Bug
