### ISSUE TITLE
Importing highcharts/modules/export-data and highcharts/modules/offline-exporting via Typescript broken in 11.4.4

### ISSUE THREAD

**Issue by hamfastgamgee** [highcharts/highcharts#21446] opened 2024-07-02 15:28 UTC
#### Expected behaviour
Importing the export-data or offline-exporting module from typescript should still work in 11.4.4.

#### Actual behaviour
Getting an error using importing code that I had been using for years in our Angular app.  Here is the error my compiler is throwing:
‌[Error] Module not found: Error: Can't resolve 'modules/exporting' in '<rootDir>\node_modules\highcharts\modules' 
[Error] @ ./node_modules/highcharts/modules/export-data.js, 
[Error] @ ./src/app/common/chart/highcharts.module.ts,

highcharts.module.ts looks like this:

```
import * as Highcharts from 'highcharts';
import highchartsExporting from 'highcharts/modules/exporting';
import highchartsExportData from 'highcharts/modules/export-data';
import highchartsAccessibility from 'highcharts/modules/accessibility';

highchartsExporting(Highcharts);
highchartsExportData(Highcharts);
highchartsAccessibility(Highcharts);

export { Highcharts };
```

It appears from looking at the source in node_modules that the define() statements in export-data.js (and also offline-exporting.js, although we don't use that) changed "highcharts/modules/exporting" to "modules/exporting" and that's what's causing the complaint.  If there is a better coding pattern to use in my import module, I'm happy to switch, but as-is it broke and I'm not sure if I am able to fix it.  I have downgraded to 11.4.3 for now.

#### Product version

11.4.4

**Comment by moisesbramirez** [comment] 2024-07-02 19:26
We're seeing similar errors when building our Ember app for `offline-exporting` and `solid-gauge`. Here's some of the output:

```
ERROR in ../node_modules/.pnpm/highcharts@11.4.4/node_modules/highcharts/modules/offline-exporting.js
Module not found: Error: Can't resolve 'modules/exporting' in 'workspace/node_modules/.pnpm/highcharts@11.4.4/node_modules/highcharts/modules'
resolve 'modules/exporting' in 'workspace/node_modules/.pnpm/highcharts@11.4.4/node_modules/highcharts/modules'
  Parsed request is a module
  using description file: workspace/node_modules/.pnpm/highcharts@11.4.4/node_modules/highcharts/package.json (relative path: ./modules)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      workspace/node_modules/.pnpm/highcharts@11.4.4/node_modules/highcharts/modules/node_modules doesn't exist or is not a directory
...

ERROR in ../node_modules/.pnpm/highcharts@11.4.4/node_modules/highcharts/modules/solid-gauge.js
Module not found: Error: Can't resolve 'highcharts-more' in 'workspace/node_modules/.pnpm/highcharts@11.4.4/node_modules/highcharts/modules'
resolve 'highcharts-more' in 'workspace/node_modules/.pnpm/highcharts@11.4.4/node_modules/highcharts/modules'
  Parsed request is a module
  using description file: workspace/node_modules/.pnpm/highcharts@11.4.4/node_modules/highcharts/package.json (relative path: ./modules)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      workspace/node_modules/.pnpm/highcharts@11.4.4/node_modules/highcharts/modules/node_modules doesn't exist or is not a directory
      workspace/node_modules/.pnpm/highcharts@11.4.4/node_modules/highcharts/node_modules doesn't exist or is not a directory
...
```

**Comment by karolkolodziej** [comment] 2024-07-03 06:12
Hi @hamfastgamgee! 
I've tested `"highcharts": "^11.4.4",` with the latest Angular 18 and I don't get any errors on compilation and I'm able to render the chart correctly.

Could please explain how to recreate it? Maybe it's worth sharing `tsconfig` or the whole simplified repo somewhere.

**Comment by YoannChabert** [comment] 2024-07-03 06:27
I don't know if that can help because I have more or less the same error when I upgrade Highcharts from 11.4.3 to 11.4.4

I'm on a Symfony Framework (PHP) with Webpack Encore, and I got this when I launch a `yarn dev`

```
ERROR  Failed to compile with 1 errors
08:22:15

Module build failed: Module not found:
"./node_modules/highcharts/modules/export-data.js" contains a reference to the file "modules/exporting".
This file can not be found, please check it for typos or update it if the file got moved.
```

I'm using js file (common-highcharts.js)
```
import Highcharts from 'highcharts/highcharts';
import Heatmap from 'highcharts/modules/heatmap';
import Map from 'highcharts/modules/map';
import Accessibility from 'highcharts/modules/accessibility';
import Exporting from 'highcharts/modules/exporting';
import Export from 'highcharts/modules/export-data';

window.Highcharts = Highcharts;

Heatmap(window.Highcharts);
Map(window.Highcharts);
Accessibility(window.Highcharts);
Exporting(window.Highcharts);
Export(window.Highcharts);
```

Called in my webpack.config.js like this : 
```
...
Encore.addEntry('common-highcharts', './assets/js/common-highcharts.js')
...
```

**Comment by taniyasurvey** [comment] 2024-07-03 10:55
It is not working in nextjs as well with typescript. Getting the below error
./node_modules/highcharts/modules/export-data.js
Module not found: Can't resolve 'modules/exporting' in '/usr/src/app/node_modules/highcharts/modules'

**Comment by imukeshsoni** [comment] 2024-07-03 11:47
@hamfastgamgee For me downgrading to 11.4.3 worked. Looks like there is some issue with the latest version.

**Comment by SeanDKendle** [comment] 2024-07-03 17:31
I can confirm this bug in 11.4.4 in a WordPress environment, building with NPM in VS Code, as well as building on our server in a Bitbucket pipeline

**Comment by hamfastgamgee** [comment] 2024-07-03 19:41
My tsconfig is:

...
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "downlevelIteration": true,
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "ES2022",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "ES2022",
    "lib": ["ES2022", "dom"],
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "useDefineForClassFields": false
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true,
    "strictTemplates": true,
    "strictInputAccessModifiers": true
  }
}
...

There's not really anything interesting there.  It's pretty much all stock more or less.  I'm honestly surprised given everyone else's comments about how this is broken using typescript across several different frameworks that you can't reproduce it. :)

**Comment by hamfastgamgee** [comment] 2024-07-03 19:42
tsconfig.app.json adds:

```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/app",
    "types": []
  },
  "files": ["src/main.ts"],
  "include": ["src/**/*.d.ts"]
}
```

**Comment by neclimdul** [comment] 2024-07-03 19:49
No type script here. There's a number of things in our project but I think the important parts are this laravel mix config:

```
mix.js('js/chartthing.js', 'js/chartthing.dist.js');
```

And this part of the javascript:
```

**Comment by TorsteinHonsi** [comment] 2024-07-04 06:01
Thanks for your patience! I've committed a fix. Will run a new release ASAP.

**Closed** 2024-07-04 09:35 UTC
