### ISSUE TITLE
Column type series bars overlap with vertical grid line when pointPlacement is "between" and another series is present.

### ISSUE THREAD

**Issue by andreyp-pragma** [highcharts/highcharts#16674] opened 2021-11-18 17:55 UTC
#### Expected behaviour
Column type series bars should be placed between vertical grid lines.

#### Actual behaviour
Column type series bars overlap with vertical grid line

#### Live demo with steps to reproduce
Live demo: https://jsfiddle.net/f0sk792u/128/

Steps to reproduce:

1. Comment out "Series 2" data
2. The "Series 1" columns will be properly placed between vertical grid lines.
3. Uncomment "Series 2" data.
4. The "Series 1" columns will overlap with vertical grid line.

#### Product version
v9.3.1 (2021-11-05)

#### Affected browser(s)
Chrome

**Comment by KacperMadej** [comment] 2021-11-23 10:07
Hi @andreyp-pragma 

Thank you for reporting the problem.

Axis point range is calculated from all axis series so the line series with a smaller point x difference between points than the column series is affecting axis and the column series points placement (widths to be precise - you could see it with pointWidth commented or removed). To avoid this you could set [`pointRange`](https://api.highcharts.com/highcharts/series.column.pointRange) for the column series - https://jsfiddle.net/BlackLabel/9kbxrw5d/

This behavior is by design and doesn't look like a bug. If you don't have any further comments or questions I would like for the issue to be closed as resolved.

**Closed** 2023-01-25 11:32 UTC
Labels: Status: Pending reply, Type: Question
