### ISSUE TITLE
Legend broken in HighCharts 6.0 when useHTML=true

### ISSUE THREAD

**Issue by mjmckp** [highcharts/highcharts#7252] opened 2017-10-11 01:02 UTC
#### Expected behaviour
Legend appears normally.

#### Actual behaviour
Legend text appears outside legend box, in upper RHS of chart, with all labels on top of one another.

#### Live demo with steps to reproduce
http://jsfiddle.net/gmfrje2L/
Note: changing `useHTML: false` in the `legend`, or using HighCharts 5 works fine.

#### Affected browser(s)
Only tried on Chrome

**Comment by pawelfus** [comment] 2017-10-11 10:07
Hi @mjmckp 

Thanks for reporting! It's a duplicate of #7224

**Closed by pawelfus** 2017-10-11 10:07 UTC
