### ISSUE TITLE
Hovering on stacked column shows mismatched column and wrong info in tooltip

### ISSUE THREAD

**Issue by vaticancameo** [highcharts/highcharts#6738] opened 2017-05-16 22:17 UTC
#### Expected behaviour
hovering on one portion of a stacked column should highlight both portion of the same column

when mouse is on the blue portion of September, all good
<img width="170" alt="screen shot 2017-05-16 at 3 11 01 pm" src="https://cloud.githubusercontent.com/assets/6611549/26130501/eac95228-3a49-11e7-88e7-00981767e323.png">

#### Actual behaviour
hovering on one portion of the a stacked column sometimes highlight a portion in another category

when mouse is on the black portion of September, the tooltip show august and blue portion in august is highlighted
<img width="199" alt="screen shot 2017-05-16 at 3 10 29 pm" src="https://cloud.githubusercontent.com/assets/6611549/26130486/d43b7266-3a49-11e7-9143-442b3a036614.png">

#### Live demo with steps to reproduce
seems to be a problem when tooltip is shared and there are a lot of columns
trying hovering over blue and black portion across the columns, you'll see bug
http://jsfiddle.net/ej58cg7c/

#### Affected browser(s)
Chrome Version 58.0.3029.110 (64-bit) is the one i'm currently using

**Comment by zhy1stgg** [comment] 2017-05-17 01:51
+1, I have the same issue.

**Comment by topcnm** [comment] 2017-05-17 04:30
we have just ran into this problem, finally we use type "line" instead .

**Comment by saygiselim** [comment] 2017-05-17 08:18
similar problem here : http://jsfiddle.net/saygiselim/6v4zuL8L/

if you hover on stacked colums, every part shows different values on tooltip when there is any zero value in data.

**Comment by pawelfus** [comment] 2017-05-17 09:02
Thank you for your reports! It's already fixed on our master branch and will be part of the next release. 

Duplicate of #6687

**Closed by pawelfus** 2017-05-17 09:02 UTC
Labels: Duplicate
