### ISSUE TITLE
removing parent point in gantt chart does not work as expected

### ISSUE THREAD

**Issue by brettk-dev** [highcharts/highcharts#15196] opened 2021-02-22 13:39 UTC
#### Expected behaviour
I expect the row for the data point to be removed and everything else shifted up/redrawn correctly.

#### Actual behaviour
It depends on how you remove the data point.

- If you do a `chart.update(newOptions);` the row is removed, but the collapse icon (the small triangle in the first column) is still shown on a non-parent data point.
- If you remove the point using any other method I could find (`series.removePoint()`, `point.remove()`, `series.setData()`, and `series.update()`), the rectangle in the gantt chart is removed, but the rest of the row's data, including the dependency arrows, remains.

#### Live demo with steps to reproduce
I have commented out the various other methods I have tried.

https://codepen.io/brettk-dev/pen/yLVzvxB

#### Product version

Highgantt 9.0.1

#### Affected browser(s)

- Firefox 85.0.2
- Chrome 88.0.4324.182 (Official Build) (x86_64)
- Safari 14.0.3 (16610.4.3.1.4)

**Comment by KacperMadej** [comment] 2021-02-23 12:54
Hi @brettk-dev 

Thank you for reporting the problem.

A general issue is that series data is copied and later altered with internal Highcharts properties after passing into a chart constructor. If you need to reuse the data use a copy of it to avoid errors or unexpected behavior. The copy of data is not done automatically due to performance reasons.

After removing a parent task all point with property `parent` set to the id of the parent will be broken - as if you were to set `parent` to id that is not existing, so I am not sure that this data change should work without fixing the children point options.

If I will remove the parent task and its children then the update runs fine and there is no error in the browser console.

Working demo: https://codepen.io/Blacklabel/pen/MWbObMY?editors=0010

**Comment by brettk-dev** [comment] 2021-02-23 13:10
Maybe the issue is that in my project I'm not making a deep copy first. There are some data structure changes that I need to make today anyway, so I'll run through how the data is being updated and make sure I'm making a clean copy.

I used lodash to make a deep copy in my example before altering the options data and it works as expected. Thanks for the help.

**Comment by KacperMadej** [comment] 2021-02-24 08:24
Closing as answered and resolved.
To reopen please add a comment with a request about it.

**Comment by brettk-dev** [comment] 2021-02-24 14:00
I've updated the example with the sample data that I'm using in my project. I've created two separate options datasets; one from before the removal and one from after. There should be nothing in the second option set that still references anything from the first object. I'm still getting the triangle artifacts.

https://codepen.io/brettk-dev/pen/yLVzvxB

**Comment by KacperMadej** [comment] 2021-02-24 15:27
Looks like a bug - reopening.

Workaround - recreate the chart. Demo: https://codepen.io/Blacklabel/pen/RwoxWee?editors=0010

_Internal note:_
I am unable to avoid the axis issue even with additional updates that would remove series or data - maybe something is not rebuild correctly in the axis.

**Comment by TorsteinHonsi** [comment] 2023-09-06 11:16
_Internal note_

The first part of resolving this bug will be to deal with missing parents in a static chart. This is what happens if we take our Project Management demo and re-id the `relocate` node to `_relocate`. There are children that are supposed to point to `relocate`, but this situation creates a JS error. In this scenario we need to decide whether it makes more sense to a) Not show the child nodes at all, or b) show the orphaned child nodes on the root level.

**Comment by oysteinmoseng** [comment] 2023-09-11 09:25
Comment on Torstein's comment: Would vote for a) - as the use case is probably that you want to hide all child nodes?

**Comment by MarkusBarstad** [comment] 2023-09-13 13:57
@TorsteinHonsi @oysteinmoseng 

Regarding missing parents in static chart;

From reading the code it seems to me, if i am reading it correctly, that the original intention is [to hoist the children up to the root node](https://github.com/highcharts/highcharts/blob/df2e564b8b19633a7b24dbe0156c3ecf2a2e7823/ts/Gantt/Tree.ts#L93).

Changing the ensuing `forEach` like this will put the children in the right place: 
`
parents.forEach(node => {
        if (node !== root && ids.indexOf(node) === -1) {

            listOfParents[root] = [
                ...listOfParents[root],
                ...listOfParents[node]
            ];

            delete listOfParents[node];
        }
    });
`

Using the project management demo and the "relocation" parent as described by @TorsteinHonsi above, we can see that children are now correctly placed.
![Skjermbilde 2023-09-13 kl  15 41 52](https://github.com/highcharts/highcharts/assets/110829288/40ec3446-9909-45d4-92e0-0ad69608f748)


But it still throws an error. `A11y`-module is looking for `names` which does not exist, I assume because we have not altered HCs main internal data-representation (not unlike what @KacperMadej is describing above)
![Skjermbilde 2023-09-13 kl  15 39 42](https://github.com/highcharts/highcharts/assets/110829288/54f7a345-66c6-435c-9c43-02c795229054)

How best to handle it? 
- Make/Merge TreeNode with a proper point object?
- Reference series in Tree.ts so that we may hide points there? (feels a bit messy maybe)
- Handle it in `Update`-function of whatever uses `Tree.ts`?

**Comment by TorsteinHonsi** [comment] 2023-09-14 06:56
> Changing the ensuing forEach like this will put the children in the right place

@MarkusBarstad Can you show us?  I agree that the original intension was to hoist orphaned elements to the root of the tree, so we should stick to that so we don't break anything. Except it is already breaking for the case I described: https://jsfiddle.net/highcharts/dyo1sekz/

**Comment by MarkusBarstad** [comment] 2023-09-14 14:55
> > Changing the ensuing forEach like this will put the children in the right place
> 
> @MarkusBarstad Can you show us? I agree that the original intension was to hoist orphaned elements to the root of the tree, so we should stick to that so we don't break anything. Except it is already breaking for the case I described: 




[Here is a fiddle](https://jsfiddle.net/mkb93/0sx9u7pz/4/), click on `document` to change `"relocated"` to `"_relocated"` .
Not entirely sure why the a11y screenreader failed on me yesterday 🤔 but this does not throw an error at least.

I have not looked thouroughly over `series/points` yet, will do so.

`Gantt/Tree.ts` has no interface nor prototype, and I could not find any way of overriding it 🤔  
I therefore made a branch + [draft PR](https://github.com/highcharts/highcharts/pull/19761)

**Comment by MarkusBarstad** [comment] 2023-09-15 13:11
@TorsteinHonsi 
Just an update on this:

Series functions fine from what I can tell. 

One thing to note is that the parent-property of the orphans stay the same. As far as I can see, this is akin to the previous behavior, but maybe it makes more sense to alter it to their new parent i.e. the root-node.

Putting draft in PR-mode.

**Comment by TorsteinHonsi** [comment] 2023-09-21 08:18
@MarkusBarstad 

Yes, I think the series is working fine. I believe the remaining issues are with the tree grid.

**Comment by MarkusBarstad** [comment] 2023-09-21 08:54
> @MarkusBarstad
> 
> Yes, I think the series is working fine. I believe the remaining issues are with the tree grid.

Yeah, I

**Closed** 2023-11-20 06:58 UTC
Labels: Type: Bug, Product: Highcharts Gantt
