### ISSUE TITLE
Map of India is not up to date

### ISSUE THREAD

**Issue by sagargurtu** [highcharts/highcharts#7723] opened 2018-01-24 13:53 UTC
#### Expected behaviour
A new state of Telangana has been formed from the state of Andhra Pradesh in India. Refer:
https://en.wikipedia.org/wiki/File:Political_map_of_India_EN.svg

#### Actual behaviour
The above change has not been reflected in the Map Collection.

**Comment by KacperMadej** [comment] 2018-01-25 10:13
Hi @sagargurtu 

Thank you for reporting about the problem.

**Comment by oysteinmoseng** [comment] 2018-01-29 13:20
Closing as duplicate of #3277.

We should try to fix this for the next version of the map collection, as several users have reported this.

**Closed by oysteinmoseng** 2018-01-29 13:20 UTC
Labels: Map collection
