### ISSUE TITLE
showEmpty axis option not working when zoomed

### ISSUE THREAD

**Issue by Llorx** [highcharts/highcharts#6190] opened 2016-12-30 10:46 UTC
#### Expected behaviour
When I zoom in, `yAxis` with `showEmpty: false` and any linked series should dissapear.

#### Actual behaviour
When I zoom in, `yAxis` without series are still visible.

#### Live demo with steps to reproduce
http://jsfiddle.net/qwnvmub2/

1. Press the `Toggle axis` button. Notice how `showEmpty` works.
2. Show all axes again and drag and drop any part of the chart to zoom in.
3. Press `Toggle axis` button. See how `yAxis` are still visible.

#### Affected browser(s)
All, I guess.

**Comment by pawelfus** [comment] 2016-12-30 12:30
Thank you for reporting, @Llorx 

This is a limitation when using `showEmpty` - if series has defined extremes, then it's not considered as an empty one. I suggest to use [`yAxis.visible`](http://api.highcharts.com/highcharts/yAxis.visible), for example: http://jsfiddle.net/qwnvmub2/1/

**Comment by Llorx** [comment] 2016-12-30 17:22
Yes, that's what I was using before I discovered `showEmpty`, but, as always, I prefer an internal way of doing the things rather than adding code around the chart.

I've checked the `hasData()` method and I thought that it only checked against linked series. I think that when someone thinks about an axis with data, thinks about an axis that has data linked (series) and not thinking about axis limits. Is there a reason to declare an axis "with-data" just because it has `min` and `max` defined? Can we change that or is a big change?

Thank you for your reply :P

**Comment by oysteinmoseng** [comment] 2017-01-12 10:26
I would consider this a bug

**Comment by pawelfus** [comment] 2018-09-11 08:34
Actually it's a duplicate of #705

**Comment by KacperMadej** [comment] 2018-10-10 15:54
Closing as a duplicate

**Closed by KacperMadej** 2018-10-10 15:54 UTC
Labels: Bug, Duplicate
