### ISSUE TITLE
Flag series in Highstock 

### ISSUE THREAD

**Issue by hopest** [highcharts/highcharts#6820] opened 2017-06-09 12:14 UTC
#### Expected behaviour
When you hover the bears on the **flag**, we see the **text**
http://jsfiddle.net/highcharts/2BGSK/

#### Actual behaviour
It's unclear why all the examples with https://www.highcharts.com/docs/chart-and-series-types/flag-series do not display **text** when you hover over the **flag** label

#### Live demo with steps to reproduce

http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/flags-general/

**Comment by pawelfus** [comment] 2017-06-09 12:55
Hi @hopest 

It's an issue with `tooltip.shared`. If it's set to true, flags' tooltip is broken, otherwise it works fine, please take a look: http://jsfiddle.net/snhd3x5k/

Closing as duplicate of #6764

**Closed by pawelfus** 2017-06-09 12:55 UTC
