### ISSUE TITLE
xAxis.startOnTick doesn't work with xAxis.categories

### ISSUE THREAD

**Issue by rdp1414** [highcharts/highcharts#16559] opened 2021-10-27 14:34 UTC
#### Expected behaviour
When setting xAxis `startOnTick: false` and `minPadding: 0`, then the first category `'a'` should coincide with yAxis.
```
  xAxis: {
    categories: ['a', 'b', 'c'],
    startOnTick: false,
    minPadding: 0,
  },
```
Similarly, when setting xAxis `endOnTick: false`, `maxPadding: 0`, then the last category `'d'` should coincide with right-most xAxis point.

#### Actual behaviour
The first category and last category are not placed at xAxis extremes.

#### Live demo with steps to reproduce
For bug reproducer, see [fiddle](https://jsfiddle.net/68ysmLdn/3/).

#### Product version
Highcharts `v9.1.2`

#### Affected browser(s)
Chrome

**Comment by raf18seb** [comment] 2021-11-02 10:53
Hi @rdp1414! Thanks for creating the ticket and sorry for the late reply.

You can set the [series.pointPlacement](https://api.highcharts.com/highcharts/plotOptions.series.pointPlacement) to `'on'`. This should resolve all your issues.

Demo: https://jsfiddle.net/BlackLabel/re7b6zdt/

Closing as not a bug, but feel free to ask/share any other insight if you think there's still a bug.

**Closed by raf18seb** 2021-11-02 10:53 UTC
