### ISSUE TITLE
Highcharts piechart does not render values less than 0.25%

### ISSUE THREAD

**Issue by pagangil** [highcharts/highcharts#7947] opened 2018-03-02 09:59 UTC
#### Expected behaviour
The piechart should show values which are less than 0.25%

#### Actual behaviour
Values are not being rendered if they are less than 0.25%. For eg. I was trying to render two values in a piechart (sector1 : 600,sector2 : 1). But this renders only the sector1 and it appears that sector1 is 100% which confuses the viewer.

#### Affected browser(s)
Verified on Chrome

**Comment by pawelfus** [comment] 2018-03-02 10:35
Hi @pagangil 

Thank you for reporting the issue. Is this the same issue as #7907 ? Dense data labels are hidden because of the available space on the chart according to the [`labelRank`](https://api.highcharts.com/highcharts/series.pie.data.labelrank) or, if not defined, to the value.

**Comment by pagangil** [comment] 2018-03-02 10:42
@pawelfus No, I think my issue is not to rendering of labels but related to rendering of sectors in the pie/ donut chart itself. In my use case there are mainly two fields: passed and failed. I am using donut chart for this. When the passed percentage is anything above 99.75%, the failed field stops being rendered in the donut chart. 
For eg, value of one sector is 600 and value of other sector is 1, then the sector with value 1 does not even gets rendered.
Please ask if you need anymore details on this. Thanks

**Comment by pawelfus** [comment] 2018-03-02 10:59
Hi @pagangil - I edited my previous message when I realized my mistake. See my demo above. Sorry for the confusion! In your case, I think you should enable dataLabels and/or legend, or consider changing type of a chart (for example `column`/`bar` types where you can set minimum length, or change yAxis type to logarithmic).

Compare charts: http://jsfiddle.net/Lvhvbcxb/12/

**Comment by pagangil** [comment] 2018-03-02 12:13
@pawelfus Thanks, this is a good workaround. Unfortunately for me, I can't go with either of enabling datalabels or changing the graph type to column/ bar :(

**Comment by pawelfus** [comment] 2018-03-05 10:34
Another solution could be to simply modify dataset before passing it to the Highcharts (http://jsfiddle.net/BlackLabel/Lvhvbcxb/20/) or simply disable border (http://jsfiddle.net/BlackLabel/Lvhvbcxb/22/). Disabled border won't solve this problem if you decide to render points e.g. 100 000 vs 1.

**Comment by TorsteinHonsi** [comment] 2018-03-07 09:45
As I understand this, it is just a case of the pie slice being smaller than the border width. So setting the `borderWidth` to 0 would fix it. 

> Disabled border won't solve this problem if you decide to render points e.g. 100 000 vs 1.
That's what I would expect, because the slice would be just a fraction of a pixel.

I'm closing this, please reopen if you disagree.

**Closed by TorsteinHonsi** 2018-03-07 09:45 UTC

**Comment by kanchijain** [comment] 2022-11-23 08:34
It is still not working for me even after setting borderWidth to 0 and the other solutions are not applicable in my case as well. Any other possible workaround?

**Comment by pawellysy** [comment] 2022-11-23 08:36
Hello @kanchijain, thanks for reaching out. Could you share the demo, where the issue is reproduced?

**Comment by kanchijain** [comment] 2022-11-23 08:38
Sure @pawellysy , here is the demo : http://jsfiddle.net/eqnrscth/

**Comment by pawellysy** [comment] 2022-11-24 07:59
As you can read here 
>Disabled border won't solve this problem if you decide to render points e.g. 100 000 vs 1.
So this is your example. We decided to make this decision, because that point wouldn't be visible either way. 
What you could do, is parse a value to be higher than some threshold, or use some other series type, better suited for showing big differences in the dataset.

**Comment by kanchijain** [comment] 2022-11-24 10:47
@pawellysy Those solutions are not applicable in my scenario, I wanted to have a solution with pie chart only. Anyway, thanks for your response.
