### ISSUE TITLE
Navigator: adaptToUpdatedData on Inverted Chart Unexpected Behavior

### ISSUE THREAD

**Issue by mfiot** [highcharts/highcharts#8957] opened 2018-09-13 20:44 UTC
#### Expected behaviour
Same behavior as when not inverted, follows the new data added if at the end of the navigator, but are still able to move the navigator to previous data without having it jump with the updates.
http://jsfiddle.net/v3z6T/20/

#### Actual behaviour
The navigator always resets the view to all. 
http://jsfiddle.net/v3z6T/23/

#### Product version
Highstock 6.1.3

**Comment by pawelfus** [comment] 2018-09-14 09:07
Hi @mfiot 

Thank you for reporting this bug. It's already fixed and will be a part of the next release: http://jsfiddle.net/BlackLabel/o40dj8eq/

Closing as duplicate of #8884.

**Closed by pawelfus** 2018-09-14 09:07 UTC
Labels: Bug, Highstock
