### ISSUE TITLE
How to change the ‘useUTC’ to false globally？（iOS Framework）

### ISSUE THREAD

**Issue by yjjwxq** [highcharts/highcharts#9090] opened 2018-09-30 12:20 UTC
hioptions.time = [HITime new];
    hioptions.time.useUTC = @NO;
(It doesn't work!!)

**Comment by pawelfus** [comment] 2018-10-01 09:28
Closing as duplicate of https://github.com/highcharts/highcharts-ios/issues/132

**Closed by pawelfus** 2018-10-01 09:28 UTC
