### ISSUE TITLE
Accessibility module: depending on direction of tabbing through (tab or shift+tab) first or last point is being highlighted

### ISSUE THREAD

**Issue by rajeswariaddepalli** [highcharts/highcharts#9188] opened 2018-10-16 14:26 UTC
#### Expected behaviour

If user tabs/shift tabs, created rect should have same **X and Y coordinates and its width and height rect should be same** so that rect will be visible on the Pie at exact location.

#### Actual behaviour

1.  When user **tabs/Shift+tab , X and Y** that gets generated are on the pie chart are as below
and event width and height gets varied.

rect x="**94.98503112792969**" y**="-1.5000000298023224**" width="**77.51493835449219**" height="**148.47654724121094**" fill="none" rx="3" ry="3" class="highcharts-focus-border" stroke="#335cad" stroke-width="2"></rect>

2. For the same Pie chart when user makes **Shit+tab, X and Y** that gets generated are on the pie chart are as below
rect x="21.4999942779541" y="-1.4999330639839172" width="96.52298736572266" height="150.99993896484375" fill="none" rx="3" ry="3" class="highcharts-focus-border" stroke="#335cad" stroke-width="2"></rect>

**Comment by KacperMadej** [comment] 2018-12-12 17:36
Closing due to inactivity.

**Comment by RajeswariAddepalli23** [comment] 2019-01-07 13:16
Please find the demo in the below URL
http://jsfiddle.net/Rajeswaritest/ocsbnhp9/

**Comment by KacperMadej** [comment] 2019-01-07 20:57
Thank you for the demo.
On going down (tab) first slice/point is highlighted and when going back (shift+tab) the last slice/point is highlighted.

The problem is not restricted to pie series type - it a general issue, so I'll rename the issue name. Demo for line series type: http://jsfiddle.net/BlackLabel/gwhterzx/

fyi @oysteinmoseng a11y module issue, but not sure if a bug

**Comment by oysteinmoseng** [comment] 2019-01-08 09:13
This is by design, as it seems more intuitive to highlight the last point of the chart when tabbing backwards.

@RajeswariAddepalli23 Do you believe there should be an option to change this behavior? It is of course already possible to disable the focus border, if that is the issue: https://api.highcharts.com/highcharts/accessibility.keyboardNavigation.focusBorder.enabled.

**Comment by oysteinmoseng** [comment] 2019-02-26 12:53
Closing this for now, feel free to reopen if this is still an issue.

**Closed by oysteinmoseng** 2019-02-26 12:53 UTC
Labels: Pending reply, Undecided
