### ISSUE TITLE
Using Highcharts.Chart.update breaks chart when changing chart type

### ISSUE THREAD

**Issue by rubenlagus** [highcharts/highcharts#8303] opened 2018-05-09 08:41 UTC
#### Expected behaviour
Update method should update everything that is provided in the configuration

#### Actual behaviour
After upgrading from Area chart to Activity gauge (i.e), chart is broken

#### Live demo with steps to reproduce
https://jsfiddle.net/8myotzzo/ - Example to update a chart to gauge and back to area using buttons
https://jsfiddle.net/towerdr8/ - Working example of the area chart
https://jsfiddle.net/8zd3bdeb/ - Working example of the activity gauge
#### Product version
>6.0.3

#### Affected browser(s)
Chrome, Firefox, IE

**Comment by pawelfus** [comment] 2018-05-10 13:53
Hi @rubenlagus 

Thank you for reporting this issue. It looks like a duplicate of #7746 - updating to solid gauge generates an error (or, just like in your case, series is not visible). 

Just in case, creating new chart with all options works fine: https://jsfiddle.net/BlackLabel/8myotzzo/2/

**Comment by rubenlagus** [comment] 2018-05-14 08:45
@pawelfus It also work in a wrong way the other way around, from solid gauge to area one for example

**Comment by sebastianbochan** [comment] 2018-05-14 11:37
Hi @rubenlagus,
Could you point me out which elements are wrong in the Pawel's demo: https://jsfiddle.net/BlackLabel/8myotzzo/2/ ?

**Comment by rubenlagus** [comment] 2018-05-18 11:44
@sebastianbochan There is no issue in that demo because there is no update, just creating a new chart.

**Comment by KacperMadej** [comment] 2018-10-05 14:15
Workaround was suggested - https://github.com/highcharts/highcharts/issues/8303#issuecomment-388059861
Closing as duplicate of #7746

**Closed by KacperMadej** 2018-10-05 14:15 UTC
