### ISSUE TITLE
Segment line not working properly when the navigator axis is not on full axis

### ISSUE THREAD

**Issue by haroldlatina** [highcharts/highcharts#16208] opened 2021-08-17 05:03 UTC
#### Expected behaviour
Editing a segment line would be working as expectedly when trying to resize / move the line. 

#### Actual behaviour
It doesn't work as expected, Moving / resizing a segment line doesnt follow the cursor. 

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/eb7qsf63/
1. Move the navigator 
![image](https://user-images.githubusercontent.com/51808505/129666490-1f36bef8-c65c-40dd-b6a4-60a79817a35d.png)
2. click add line
3. create a line
4. click the created line and try resizing it.

**Comment by raf18seb** [comment] 2021-08-17 15:10
Hi @haroldlatina, thanks for creating the ticket.

It's already reported and fixed on master.
Closing as a duplicate of https://github.com/highcharts/highcharts/issues/15970

**Closed by raf18seb** 2021-08-17 15:10 UTC
