### ISSUE TITLE
'areaspline' area drawn wrong when shift & animation enabled 

### ISSUE THREAD

**Issue by DK82** [highcharts/highcharts#6037] opened 2016-11-25 09:13 UTC
#### Expected behaviour
Area should always cover the whole area below the line. 

#### Actual behaviour
When adding point the area baseline is drawn from the right x(max)y(min) intersect to the left **x(min)y(newvalue)** intersect and then after animation to the **x(min)y(min)** which causes and ugly area redraw.
In addition when the **last point** is shifted out it creates a spline line with the **second to last point** and only disappears when the **second to last point** becomes the **last point**.

#### Live demo with steps to reproduce
I've slowed this down to 2000ms to make it easier to observe
http://jsfiddle.net/23hLy3f1/1/

#### Affected browser(s)
Chrome, Firefox

**Comment by oysteinmoseng** [comment] 2016-11-25 09:35
Worked in `5.0.3`: http://jsfiddle.net/23hLy3f1/2/

**Comment by oysteinmoseng** [comment] 2016-11-25 09:36
Duplicate of #6036.

**Closed by oysteinmoseng** 2016-11-25 09:36 UTC
Labels: Duplicate, Regression
