### ISSUE TITLE
Crosshairs wrong position with OHLC series on point.update()

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#6349] opened 2017-02-07 15:48 UTC
#### Expected behaviour
Crosshair should be in a position of hovered point.

#### Actual behaviour
When point is updated in OHLC series, the current crosshair position is moved to wrong place. 

#### Live demo with steps to reproduce
http://jsfiddle.net/77awgha7/6/

To reproduce this issue move your crosshair to some position on a chart and wait for point.update()

You can find an example of this issue in a gif below:
![issue](https://cloud.githubusercontent.com/assets/15050812/22698499/03bd0762-ed55-11e6-81cf-44757b4247c1.gif)

May be related to https://github.com/highcharts/highcharts/issues/4752

**Comment by ddotlic** [comment] 2017-02-08 09:00
I was the one who found the issue and reported it to support.
The company I am consulting for uses the Highstock in several products some of which support realtime updates.
A lot of financial instruments trade quite a bit (dozens if not hundreds of times per second) and even though we throttle the redrawing of the chart, it gets redrawn quite a bit - much more than in the contrived example above (where I've deliberately set the interval to every 3 seconds).

What I'm trying to say is that this bug is extremely irritating to the user as the "carpet moves under them" while they are using the application.

I'm hoping this is an easy fix...

**Comment by ddotlic** [comment] 2017-03-22 10:52
@TorsteinHonsi Could you please let us know if someone is gonna tackle this one day? It's been more than a month and for those like us who have charts updating in realtime this is really, really aggravating... Thanks in advance for any info!

**Comment by TorsteinHonsi** [comment] 2017-03-23 13:41
Sorry for the delay @ddotlic, I'll attend to it right away.

**Comment by ddotlic** [comment] 2017-03-23 13:42
@TorsteinHonsi Great! Thanks for understanding.

**Comment by TorsteinHonsi** [comment] 2017-03-23 13:51
Actually it looks like this has been fixed in the latest release: http://jsfiddle.net/highcharts/77awgha7/17/

Though version 5.0.9 has another bug where the tooltip doesn't move until it is actually on the markers, but that has been fixed too in the master: http://jsfiddle.net/highcharts/77awgha7/18/

Please verify.

**Comment by ddotlic** [comment] 2017-03-23 13:57
@TorsteinHonsi We have to fix that fiddle - the point update changes timestamp such that Highstock generates error 15, so it's not clear if the issue is fixed or not. I'll be fixing the example shortly.

**Comment by ddotlic** [comment] 2017-03-23 14:01
@TorsteinHonsi I've fixed the fiddle by using the last timestamp available and indeed the error is gone. 🍾 Though the issue with crosshair not moving until pointer is on the bar is even more visible, so we prefer to wait for the 5.0.10. Why do you talk about 5.0.9 - it hasn't been released yet - did you already branch the code preparing for release?

**Comment by ddotlic** [comment] 2017-03-23 14:04
@TorsteinHonsi Differently put for us the crosshair not moving unless mouse pointer is on a bar is of highest possible priority (simply because everyone will notice this). That said, we are still on 5.0.7 seeing various small regressions in .8 and apparently .9, so we're waiting for the next release in any case.
If you could put that in .9 we'd move to it as soon as it is available but I don't know what your release procedure is.

**Comment by TorsteinHonsi** [comment] 2017-03-23 14:14
v5.0.9 was released the same day as v5.0.8. I see now that it was not added to the [changelog](http://www.highcharts.com/documentation/changelog), probably because of its hasty nature. It only applies to 3D charts.

We'll run a release for v5.0.10 as soon as we get the tooltip regressions sorted out. @jon-a-nygaard .

**Closed by TorsteinHonsi** 2017-03-23 14:14 UTC
Labels: Bug, Highstock

**Comment by ddotlic** [comment] 2017-03-23 14:17
@TorsteinHonsi Great, we have several items pending the release of the next version.

Still, if we had to choose between a fast and a good quality release, we'd take the latter (at the expense of the former), so please do take the time to make sure that the release is good rather than fast. Thanks!
