### ISSUE TITLE
Navigator with custom series

### ISSUE THREAD

**Issue by clarghi** [highcharts/highcharts#16614] opened 2021-11-08 15:53 UTC
#### Expected behaviour
Adding a serie only to the navigator is developed by setting its axes (xAxis:1, yAxis:1).

#### Actual behaviour
Error "Script error" settings the below properties. Without these the new serie is added to the chart.

#### Live demo with steps to reproduce
These are two of many demos I have founded that doesn't work with actual release:
http://jsfiddle.net/PjHaJ/
https://jsfiddle.net/d_paul/m1jo4uqL/3/

#### Product version
Latest version.

#### Affected browser(s)
Tested with Chrome (but I think all).

**Comment by raf18seb** [comment] 2021-11-10 10:06
Hi @clarghi, thanks for reporting a bug.

Simplified demo: https://jsfiddle.net/BlackLabel/nu4r7mg0/

`Internal note:`
Worked fine in 9.0.1, broken since 9.1.0
Looks like a regression of https://github.com/highcharts/highcharts/commit/2b28996a79ec74f8f84297336681ae374e075d44

**Comment by kamil-musialowski** [comment] 2023-06-07 06:50
Fixed in `v11.1.0`, https://jsfiddle.net/BlackLabel/0zvwxp9j/

FYI @pawelfus

**Comment by pawelfus** [comment] 2023-06-07 08:17
Confirmed, thank you!

**Closed by pawelfus** 2023-06-07 08:17 UTC
Labels: Product: Highcharts Stock, Type: Regression
