### ISSUE TITLE
errorbar alignment - regression

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#21329] opened 2024-06-14 12:00 UTC
#### Expected behaviour

As used to work in previous versions: https://jsfiddle.net/BlackLabel/kh7fL1qr/

#### Actual behaviour

Errorbar is misaligned.

#### Live demo with steps to reproduce

Demo: https://jsfiddle.net/BlackLabel/c706bvz8/

**Comment by hubertkozik** [comment] 2024-06-17 06:41
This issue is already fixed on master branch: https://jsfiddle.net/BlackLabel/70myq4r3/

Closing as duplicate of https://github.com/highcharts/highcharts/issues/21245.

**Closed by hubertkozik** 2024-06-17 06:41 UTC
Labels: Duplicate
