### ISSUE TITLE
Highcharts drilldown module is not working well when more than 50 data in a serie

### ISSUE THREAD

**Issue by kyrillos52** [highcharts/highcharts#6618] opened 2017-04-20 13:49 UTC
#### Expected behaviour
When using a chart with more than 50 data in a category chart with a drilldown, when I click on the back button after having drilldown a column, it should go back to the initial state.

#### Actual behaviour
If I use more than 50 data in the serie, when I click on a column in order to drilldown, when I click back, the x Axis is not displayed as before.

#### Live demo with steps to reproduce
http://jsfiddle.net/e7tL9y1o/

Click on a column and then "Back to Column". The x-axis will not be displayed properly. If I remove 2 data in the serie, it works well.

#### Affected browser(s)
Google Chrome 57.0.2987.133

Thank you,

Cyril

**Comment by sebastianbochan** [comment] 2017-04-20 14:29
Duplicate of https://github.com/highcharts/highcharts/issues/5857

**Closed by sebastianbochan** 2017-04-20 14:29 UTC
