### ISSUE TITLE
Option to have marker in arearange series type

### ISSUE THREAD

**Issue by simdevmon** [highcharts/highcharts#6983] opened 2017-07-20 12:24 UTC
#### Expected behaviour
Have an option for marker in plotOptions for 'arearange' series type.

#### Actual behaviour
There is no option for marker in 'arearange' series type, but only for line series for example. 
To display markers some workarounds must be done like having additional min/max line series (https://stackoverflow.com/questions/33270505/highcharts-of-type-area-range-not-displaying-markers-like-circles), but this does not work well with data grouping, so a native option would be preferred.

#### Live demo with steps to reproduce
http://jsfiddle.net/8pm9rohu/1/

#### Affected browser(s)
Chrome 59

**Comment by pawelfus** [comment] 2017-07-20 12:39
Hi @simdevmon 

It's already implemented in our master branch and will be included in next, 5.0.13 version. Pre-release demo: http://jsfiddle.net/rdrqh6x9/

Closing as duplicate of #6736

**Closed by pawelfus** 2017-07-20 12:39 UTC

**Comment by simdevmon** [comment] 2017-07-20 13:25
Great thank you, I am looking forward to 5.0.13.
