### ISSUE TITLE
Treemap: weird tooltip behavior

### ISSUE THREAD

**Issue by bitsm** [highcharts/highcharts#5656] opened 2016-09-06 05:04 UTC
Treemap tooltips are getting overlapped by point labels.

Here's a fiddle:

https://jsfiddle.net/9fqb3yqq/

**Comment by jon-a-nygaard** [comment] 2016-09-06 08:03
This is caused by the dataLabels.useHTML. [Simplified demo](https://jsfiddle.net/jon_a_nygaard/9fqb3yqq/2/)

@bitsm In your case it seems that it might be unnecessary to use `useHTML`, and if so your issue would solve itself by setting `useHTML: false`.

**Comment by pawelfus** [comment] 2016-09-06 09:55
Related [documentation](http://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting#html) page.

**Comment by jon-a-nygaard** [comment] 2016-09-06 10:54
I will close this since it is not considered a bug.  As it says in the documentation (linked to in the comment above) when `useHTML: true` the element will be rendered on top of the svg. `useHTML` should only be used in special cases when the need for a HTML element is absolutely necessary. 
@bitsm As mentioned before; in your case it seems that `useHTML` is unnecessary, should this not be the case please let us know and we will try to help you.

**Closed by jon-a-nygaard** 2016-09-06 10:54 UTC
Labels: Not a bug

**Comment by bitsm** [comment] 2016-09-06 14:01
Thanks @jon.

Didn't notice that! you rock!
