### ISSUE TITLE
In Bubble chart with multi series, data point with z value as 0 is not plotting correctly on the chart

### ISSUE THREAD

**Issue by gs-hbaba** [highcharts/highcharts#17555] opened 2022-08-03 06:31 UTC
#### Expected behaviour
In Bubble chart data points should be plotted correctly with multi series data,

#### Actual behaviour
In Bubble chart data points with z value as 0 is not plotted correctly.
One of the series has a data point with z value as 0, this is point is being plotted wrongly

#### Live demo with steps to reproduce
http://jsfiddle.net/9dygmeo6/5/

the data point `[1, 1, 0]` in `size by area` series is plotted wrongly in chart.

#### Product version
Highcharts - 9.3.3

#### Affected browser(s)
chrome, firefox

<img width="1642" alt="Screenshot 2022-08-03 at 11 56 44 AM" src="https://user-images.githubusercontent.com/105642820/182539434-9cb25f98-ca1f-473b-9cbd-0713dda57e6b.png">

**Comment by gs-hbaba** [comment] 2022-08-03 10:30
Hi @pawellysy,
There is one more use case i forgot to mention.
if there is only one series it works as expected,
this issue comes only when there is multi series.

However below are the use cases i have:
1. only one series with z value 0.  -    works as expected.
2. multi series : 
- first series has a z value 0 -  there is issue with plotting.
- first series has non zero z values, other series has z value 0 -   plotting is fine - no issue
- all series has z value 0 - plotting is fine - no issue

In all above cases only with multi series , first series having z value 0 case behaviour is different.

for your question : "What is your view, on how this should work? Maybe the marker size should not be taken into consideration if the z-value is defined for the bubble chart?"
answer: the marker size should be considered if the z value is less than or equals to 0 or there is no z value.

**Comment by raf18seb** [comment] 2022-08-04 12:30
Hi @gs-hbaba!

The `bubble.marker.radius` property is not documented thus not supported and you should never use it because it may lead to unexpected behaviors (like e.g. the one described above).
https://api.highcharts.com/highcharts/series.bubble.marker

If you'd like to set `marker.radius` option in `plotOptions.series` for all series types, you should disable it for `bubble` series like this:
```js
plotOptions: {
    series: {
        marker: {
            enabled: true,
            radius: 4
        }
    },
    bubble: {
        marker: {
            radius: null
        }
    }
},
```

Working demo: https://jsfiddle.net/BlackLabel/Loxyw8cv/

Closing as not a bug.

**Closed by raf18seb** 2022-08-04 12:30 UTC
Labels: Status: Pending reply
