### ISSUE TITLE
Boost Module: Issues hiding series on firefox

### ISSUE THREAD

**Issue by vmlopezr** [highcharts/highcharts#17443] opened 2022-06-27 17:33 UTC
#### Expected behaviour
When hiding a series on the chart the appropriate series should be hidden, with the other series visible

#### Actual behaviour
If firefox with boost mode on, it looks like the chart is not repainted. The chart is updated, but you can still see the hidden series. This issue happens with zooming in as well.

![image](https://user-images.githubusercontent.com/35988895/176000685-def6d4cf-3e72-4628-9686-a93876693761.png)

#### Live demo with steps to reproduce

Load this fiddle on firefox, and click on the legend to hide a series.
https://jsfiddle.net/qro10x46/2/
#### Product version

highcharts: 10.0.0
#### Affected browser(s)
Firefox (101.0.1)

**Comment by raf18seb** [comment] 2022-06-27 18:53
Duplicate of https://github.com/highcharts/highcharts/issues/17182
Fixed on master. Will work fine in the next release.

**Closed by raf18seb** 2022-06-27 18:53 UTC
