### ISSUE TITLE
Destroy() doesn't seem to remove from Highcharts.charts

### ISSUE THREAD

**Issue by cthrax** [highcharts/highcharts#6779] opened 2017-05-30 22:30 UTC
#### Expected behaviour
When calling "destroy()" on a chart, the chart is removed from the "charts" collection.

#### Actual behaviour
An undefined reference, or in some cases, a defined reference with undefined properties is still in the charts array.

#### Live demo with steps to reproduce
http://jsfiddle.net/cthrax/yg0gy6fv/4/

#### Affected browser(s)
Chrome is all I tested.

**Comment by pawelfus** [comment] 2017-05-31 08:39
Hi @cthrax 

This is the expected result, from our [docs](http://api.highcharts.com/highcharts/Highcharts.charts):

> An array containing the current chart objects in the page. A chart's position in the array is preserved throughout the page's lifetime. When a chart is destroyed, the array item becomes undefined.


Closing as a duplicate of #2431

**Closed by pawelfus** 2017-05-31 08:39 UTC
