### ISSUE TITLE
Google Sheets Data Update

### ISSUE THREAD

**Issue by RFForg** [highcharts/highcharts#14040] opened 2020-08-13 11:19 UTC
#### Expected behaviour
We are using Google Sheets to supply data to a line chart, using ` data: {
            googleSpreadsheetKey: sheetKey }`. The spreadsheet has multiple tabs, each of which we wish to be able to call on button clicks. We are using `chart.update` to call a new worksheet like this:

```
chart.update({ 
          data: {
            googleSpreadsheetKey: sheetKey,
            googleSpreadsheetWorksheet: 2,
         }
        });
```

#### Actual behaviour

Doing the above only deletes the first row of data from the chart, rather than updating the chart to display the new worksheet.

#### Live demo with steps to reproduce
This jsfiddle example (not mine; submitted last year by another user on your forum) illustrates exactly the problem we're experiencing: https://jsfiddle.net/Iron_Fossil/b4ar1xo2/1/

#### Product version
Tried various Highcharts js versions, but have primarily been using 8.1.2

#### Affected browser(s)
Doesn't seem browser-specific. Have been in Chrome.

Is there a way of fixing this or is there a known workaround if we want to continue to use Google Sheets? Thank you for your help!

**Comment by pawelfus** [comment] 2020-08-14 09:11
Hi @RFForg 

Thank your for reporting this issue. We have this bug reported here #9274

Closing as a duplicate of #9274.

**Closed by pawelfus** 2020-08-14 09:11 UTC
Labels: Type: Duplicate
