### ISSUE TITLE
Two charts within a custom element with mediaQueryList EventListeners which update the charts' label formatter crash the tab when the print preview is generated in Chromium based browsers

### ISSUE THREAD

**Issue by tim-hitchins-ekkosense** [highcharts/highcharts#21416] opened 2024-06-27 18:19 UTC
#### Expected behaviour

The print preview is rendered

#### Actual behaviour

The tab crashes with a STATUS_BREAKPIOINT error

#### Live demo with steps to reproduce

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <title></title>
    <meta charset="utf-8">

    <script src="https://github.highcharts.com/master/highcharts.js"></script>

    <script>
        customElements.define("custom-element", class CustomElement extends HTMLElement {});
    </script>
</head>

<body>
    <custom-element>
        <div id="chart1"></div>
        <div id="chart2"></div>
        <script>
            const chart1Object = Highcharts.chart('chart1', {
                chart: {
                    type: 'line',
                    events: {
                        load: function () {
                            const mediaQueryList = window.matchMedia('print');
                            mediaQueryList.addEventListener('change', () => { handlePrintEvent(this) });
                        },
                    },
                },
                series: [{
                    data: [1],
                }],
            });

            const chart2Object = Highcharts.chart('chart2', {
                chart: {
                    type: 'line',
                    events: {
                        load: function () {
                            const mediaQueryList = window.matchMedia('print');
                            mediaQueryList.addEventListener('change', () => { handlePrintEvent(this) });
                        },
                    },
                },
                series: [{
                    data: [1],
                }],
            });
        </script>
    </custom-element>
    <script>
        function handlePrintEvent(chart) {
            chart.update({
                legend: {
                    labelFormatter: () => 'a',
                }
            })
        }
    </script>
</body>

</html>
```

1. Load the HTML file in a Chromium based browser
2. Press Ctrl+P (Windows) / Cmd+P (macOS) or right click and click "Print..."
3. The print modal will briefly show, but the tab will crash before the print preview appears
4. See the STATUS_BREAKPOINT ERROR:
  ![image](https://github.com/highcharts/highcharts/assets/61007360/c46bce55-53ab-4f24-b1e0-658aa47acf32)

#### Product version

Latest `master` - baced054799e4a6490b0dffbe68e0e1d8346869c as of posting

#### Affected browser(s)

Chromium based, tested in Edge 128.0.2661.0 (Official build) dev (64-bit), Chrome 126.0.6478.116 (Official Build) (64-bit) (cohort: Control), Chrome 126.0.6478.127 (Official Build) (64-bit) (cohort: Stable Installs & Version Pins)

**Comment by hubertkozik** [comment] 2024-07-01 10:37
Hi @tim-hitchins-ekkosense! We tested your Chart configuration in multiple browsers on multiple machines and we cannot reproduce your issue. I've copy-pasted your configuration into an attached file to test it and there is no error related to printing.
[index.zip](https://github.com/user-attachments/files/16051572/index.zip)

Are you sure that this error is related to Highcharts in your project?

**Comment by tim-hitchins-ekkosense** [comment] 2024-07-01 16:44
Hmm - that file you provided does crash in Chrome (126.0.6478.127) but not Edge (128.0.2661.0).

I notice your zip contains a MACOS file - I'm on Windows 11 Pro 23H2 22631.3737. I wonder if it's also an OS thing?

Tim
________________________________

**Comment by tim-hitchins-ekkosense** [comment] 2024-07-01 16:51
Here's a video of it happening with the included file, downloaded and extracted directly from here 

Uploading Screen Recording 2024-07-01 174352 trim.mp4…

**Comment by tim-hitchins-ekkosense** [comment] 2024-07-01 16:54
I think I was wrong about my test file crashing in Edge, it does seem to be Chrome only - sorry about that.

**Comment by tim-hitchins-ekkosense** [comment] 2024-07-01 17:07
Can confirm it's not crashing with Chrome on macOS

**Comment by hubertkozik** [comment] 2024-07-04 13:33
Thank you for your answer. Indeed, my colleague was able to reproduce the issue on Windows, Chrome, but only for printing horizontally. The ticket is added to our backlog now.

**Comment by hubertkozik** [comment] 2024-08-19 08:16
Hi @wahbadb94! The issue is now prioritised at the top of our backlog. The work will start soon!

**Comment by KacperMadej** [comment] 2024-08-20 15:46
I was able to recreate the problem without Highcharts, so this looks like a browser issue.
The fastest fix seems to be to change the default display of the custom element from inline to block:
`<custom-element style="display: block;">`.

However, I crashed my Chrome over 50 times now, so it would be great if you could verify it this helps @wahbadb94 @tim-hitchins-ekkosense 
In the meantime I will work on a smallest stable demo and report this as a chromium bug.

<details>
  <summary>So far I was able to get a minimal crashing code like this.</summary>

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <title></title>
    <meta charset="utf-8">
    <script>
        customElements.define("custom-element", class CustomElement extends HTMLElement {
            constructor() {
                super();
            }
        });
        
        function handlePrintEvent() {
            document.getElementById('plainSVG').appendChild(
                document.createElementNS('http://www.w3.org/2000/svg', 'text')
            );
        }
        window.matchMedia('print').addEventListener('change', handlePrintEvent );
    </script>
</head>

<body>
    <custom-element>
        <svg id="plainSVG" xmlns="http://www.w3.org/2000/svg" width="100" height="100">
            <circle cx="50" cy="50" r="40" stroke="green" stroke-width="4" fill="red" />
        </svg>
        
        <div>
            <svg xmlns="http://www.w3.org/2000/svg" width="676" height="400" viewBox="0 0 676 400"
                role="img">
            </svg>
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="676" height="400" viewBox="0 0 676 400"
                role="img">
            </svg>
        </div>
    </custom-element>

</body>

</html>
```
</details>

**Comment by tim-hitchins-ekkosense** [comment] 2024-08-21 08:50
@KacperMadej Confirmed that the minimum example crashes for me, testing my actual use case

**Comment by tim-hitchins-ekkosense** [comment] 2024-08-21 09:01
@KacperMadej confirmed the display: block fixes it in my application. Thanks so much for that investigation!

**Comment by tim-hitchins-ekkosense** [comment] 2024-08-21 09:36
Looks like setting `display` to anything directly within the HTML `style` attribute works, not just `block`.

**Comment by KacperMadej** [comment] 2024-08-21 15:39
Right, `block` is not the only one fixing the problem - `display: inline;` leads to the crush for sure. Thank you for pointing this out. This allows for the problem to be reduced even more - a custom element is not needed.

The Chrome bug report: https://issues.chromium.org/issues/361256055
You can add relevant comments for the problem over there and vote with +1 ("vote: I am impacted").

I am closing this issue as not planned because this is a browser with workaround, but if you feel like this issue should be reëvaluated and reopened please leave a comment.

**Closed by KacperMadej** 2024-08-21 15:39 UTC
Labels: Type: Bug, Product: Highcharts
