### ISSUE TITLE
Drill down pie chart colors are not updating dynamically

### ISSUE THREAD

**Issue by chakrabortysaptarshi** [highcharts/highcharts#6040] opened 2016-11-27 09:10 UTC
#### Expected behaviour
On clicking a drill down pie chart, the color of the different sections should be updated automatically. 

#### Actual behaviour
After clicking on a particular drill down section, the color of the drill down pie chart remains unchanged. It only changes after hovering on that particular section of the pie chart. 

#### Live demo with steps to reproduce

Step 1 - In the chart below, click on the "Firefox" section of the pie chart and it will show the different versions of "Firefox".
Step 2 - Most of the drill down sections are initially of green color and then on mouse hovering over different section changes the color of the respective sections.   

Previously, it used to update the different colors automatically. No mouse hovering was required.

http://jsfiddle.net/gh/get/jquery/3.1.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/pie-drilldown/

#### Affected browser(s)
Chrome, Firefox

**Comment by TorsteinHonsi** [comment] 2016-11-28 07:51
Duplicate of #6023

**Closed by TorsteinHonsi** 2016-11-28 07:51 UTC
