### ISSUE TITLE
Holes in highstock chart when dataGrouping enabled

### ISSUE THREAD

**Issue by kaeruB** [highcharts/highcharts#15609] opened 2021-04-29 08:55 UTC
#### Expected behaviour
Zoomed out chart without holes.

#### Actual behaviour
When I use:
* stock chart,
* chart.type: 'area',
* plotOptions.series.dataGrouping.enabled: true,
* plotOptions.area.stacking: 'normal

I get the following behaviour:
* completely zoomed out chart has a hole around 18:10  (seems like series with name 'a' makes a hole in series 'c'), while zoomed in data doesn't have any holes but one-timestamp-long series 'a' is not displayed,
* partly zoomed in chart (for example try to zoom in to 'from 16:20 to 18:50') have many holes (seems like series with name 'b' makes holes in series 'c'), but when zoomed in (for example try to zoom in to 'from 17:38 to 17:40') the data is displayed correctly.

The holes are visible when the data is grouped.
plotOptions.series.dataGrouping.forced: true would fix the issue but the performenced on zoomed in data is too bad to use this solution.

#### Live demo with steps to reproduce
http://jsfiddle.net/ataga/5fky7q9z/3/
![Holes 2](https://user-images.githubusercontent.com/33574996/116525652-07f81300-a8d9-11eb-9d46-9d632db13bb1.jpg)
![Holes 1](https://user-images.githubusercontent.com/33574996/116525657-09294000-a8d9-11eb-8fe0-a4f549f524c4.jpg)

#### Product version
Highstock

In the fiddle I use: <script src="https://code.highcharts.com/stock/highstock.js"></script>
In my code I tried:
highcharts-react-official: 3.0.0 
and 
highcharts-react-official: 2.2.2

#### Affected browser(s)
Chrome, Safari

**Comment by raf18seb** [comment] 2021-05-04 22:55
Closing as a duplicate of https://github.com/highcharts/highcharts/issues/6765

**Closed by raf18seb** 2021-05-04 22:55 UTC
