### ISSUE TITLE
Highstock - error after legend click with enabled data grouping and disabled UTC

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#16351] opened 2021-09-16 07:47 UTC
#### Expected behaviour
There should not be any error.

#### Actual behaviour
Error: `Uncaught TypeError: Cannot read properties of null (reading '0')`

Works fine below v9.2: http://jsfiddle.net/BlackLabel/52xpuej3/

#### Live demo with steps to reproduce
1. Open jsfiddle: http://jsfiddle.net/BlackLabel/yn3t58mr/
2. Click on Total legend item and check browser console

#### Product version
Highstock v9.2

#### Affected browser(s)
All

**Comment by KacperMadej** [comment] 2021-09-16 07:55
Works correctly on master - http://jsfiddle.net/BlackLabel/yn3t58mr/1/
Based on the error - duplicate of https://github.com/highcharts/highcharts/issues/16255
Closing as resolved.

**Closed by KacperMadej** 2021-09-16 07:55 UTC
