### ISSUE TITLE
Charts with embedded SVG images fail to export in IE11

### ISSUE THREAD

**Issue by mjsteichen** [highcharts/highcharts#5562] opened 2016-08-03 17:43 UTC
#### Expected behaviour

Exporting of screenshot in IE11 does not fail.
#### Actual behaviour

Export fails
#### Live demo with steps to reproduce

http://jsfiddle.net/msteichen/cL7spvLp/

Note: For my project, falling back to the export server is not an option.
#### Affected browser(s)

IE11 only

**Comment by jon-a-nygaard** [comment] 2016-08-04 07:44
Duplicate of #5410. Please follow the mentioned issue to get more information and update status.

**Comment by aaronogan** [comment] 2016-08-04 14:28
@jon-a-nygaard: I'm not sure that this is truly a duplicate of #5410, but are you thinking that the fix for it should cover this case?

**Comment by oysteinmoseng** [comment] 2016-08-10 09:07
This is not quite a duplicate, as the issue here is specifically that exporting to SVG with embedded SVG images does not work in IE11 (also not IE10 it seems), while embedded PNG works.

Internally, in either case the embedded image is converted to a PNG data URI using canvas.

Maybe we can find a way to embed the actual SVG source of the image, rather than referencing it as a data URI.

**Comment by oysteinmoseng** [comment] 2016-11-28 09:56
Closing this as it seems to be a cross-domain issue only. IE11 now seems to behave as documented here: http://www.highcharts.com/docs/export-module/client-side-export.

**Closed by oysteinmoseng** 2016-11-28 09:56 UTC
Labels: Bug, Undecided
