### ISSUE TITLE
Line Chart with scrollablePlotArea - Markers Disappear

### ISSUE THREAD

**Issue by MathiasSchwarzhans** [highcharts/highcharts#22011] opened 2024-10-16 06:43 UTC
#### Expected behaviour

All markers on the line chart are visible and not flickering on hover.

#### Actual behaviour

Line markers on the right of the graph disappear and flicker on hovering the line.

#### Live demo with steps to reproduce

https://jsfiddle.net/ysxev3Lw/

![image](https://github.com/user-attachments/assets/6a5975fb-acaa-45da-8c58-948b1b00342e)

In the live demo, hover over the line at values over 50. Markers are disappearing at 68 on my system.

#### Product version

Affected Version: v11.4.8 

Last known working version according to my testing: v11.4.1

#### Affected browser(s)

 Chrome (129.0.6668.101), 
 Firefox (131.0.3), 
 Edge (129.0.2792.89)

**Comment by hubertkozik** [comment] 2024-10-16 08:25
Hi @MathiasSchwarzhans! This issue is a duplicate of https://github.com/highcharts/highcharts/issues/21701. Let's close this one and keep discussion there.

**Closed by hubertkozik** 2024-10-16 08:25 UTC
Labels: Duplicate
