### ISSUE TITLE
Markers position a bit off when rendered

### ISSUE THREAD

**Issue by Llorx** [highcharts/highcharts#12614] opened 2019-12-11 12:29 UTC
#### Expected behaviour
Markers stays at the same position and correctly positioned over the series line.

#### Actual behaviour
Markers are rendered a bit off but when you mouseover them, they change position to be at the desired one.

#### Live demo with steps to reproduce
https://jsfiddle.net/ko6g52ft/1/
Steps:
- On first render see how markers are a bit off.
- Mouseover them and see how they are not correctly positioned.

I guess that is because markers are rendered at full pixels, but when you mouseover the markers are rendered at the partial pixel for whatever reason. I like how it looks when is drawn at partial pixels so maybe an option to disable "draw only at full pixels" will be fine, specially when a [scaling is applied](https://github.com/highcharts/highcharts/issues/12489) to the entire chart, full pixels at 2.5x are not the same full pixels at 1x.

See how the markers are stair-like:
![image](https://user-images.githubusercontent.com/702490/70621448-e8941380-1c19-11ea-8121-81284094eeec.png)

but when I mouseover they are fixed:
![2019-12-11_13-27-44](https://user-images.githubusercontent.com/702490/70621506-0f524a00-1c1a-11ea-960b-0d7e81f05bb9.gif)

#### Product version
Latest.

#### Affected browser(s)
Chrome over win7

**Comment by sebastianbochan** [comment] 2019-12-11 13:22
Hi @Llorx,
Thank you for reporting about the problem. This is known issue reportied here: https://github.com/highcharts/highcharts/issues/12579.

Im closing this ticket as duplicate of https://github.com/highcharts/highcharts/issues/12579

**Closed by sebastianbochan** 2019-12-11 13:22 UTC

**Comment by Llorx** [comment] 2019-12-11 13:46
Yeah, I saw it (forgot to link to it) but I was not sure if it was the "full pixels" thing, so I created a new issue just in case there's another reason.
