### ISSUE TITLE
Map point in Norway appears 

### ISSUE THREAD

**Issue by htveit** [highcharts/highcharts#17379] opened 2022-06-10 10:43 UTC
#### Expected behaviour
Wanted to create a point map showing where Sunnmørsposten AS is located. 
The address is: Keiser Wilhelmsgate 22 and lat/lon coordinates are: 62.4712525  / 6.1578843 

Searching on a Google Map, the needle using lat/lon coordinates appear correctly:

https://www.google.com/maps/place/62%C2%B028'16.5%22N+6%C2%B009'28.4%22E/@62.4712525,6.1556956,17z/data=!3m1!4b1!4m5!3m4!1s0x0:0x4b1d861356cd665f!8m2!3d62.4712525!4d6.1578843

#### Actual behaviour
When using the Norway maps in Highmaps, this position is placed in the ocean

Same is happening with the municipality map: https://code.highcharts.com/mapdata/countries/no/no-mr-all.topo.json

#### Live demo with steps to reproduce

Live demo here: https://jsfiddle.net/BlackLabel/n7e8h0to/
Zoom in and notice that point appears in the ocean.

![image](https://user-images.githubusercontent.com/23310742/173057419-3f81a3ce-570a-4787-900d-efcf3e5a68df.png)

#### Product version
Highmaps 10.1.0

**Comment by htveit** [comment] 2022-06-10 10:44
Screenshot after zooming to highlight the bug

![image](https://user-images.githubusercontent.com/42646002/173048941-b8449ad0-8ab7-4930-8cfb-6189d54c51e7.png)

**Comment by raf18seb** [comment] 2022-06-10 14:46
Hi @htveit, thank you for writing to us about your issue.

Unfortunately, the defined coordinates and the point's position are correct, but the problem is with island shapes that do not reflect the real island shape but only approximate polygon with a few vertices. In other words, the resolution of a map (shapes) is too low.

This is caused by a fact that the size of our generated maps should be as small as possible. Note that most of our maps are based on admin1 or admin2 level, so they are designed to show countries and provinces' details, not cities or even more - specific streets/addresses/buildings.

I'm afraid there's no general solution for that and it's not something we can fix on our end.
As a workaround, you can edit your map source: find the array with island shapes coordinates and add more polygon vertices. For example, the island polygon on the image you provided has 5 vertices, so the array's length is 5. You can add more vertices to make the shape look closer to a real island shape.

For example, let's take the Monako map and change its simple shape as I've done it by replacing line 60 with line 61 here: https://jsfiddle.net/BlackLabel/zrf4t2Ly/

**Comment by raf18seb** [comment] 2022-06-14 06:40
Closing as not a bug and won't be fixed. In case of any further related questions, please contact us on one of our dedicated support channels (https://www.highcharts.com/blog/support/).

**Closed by raf18seb** 2022-06-14 06:40 UTC
Labels: Status: Won't fix, Type: Not a bug, Product: Highcharts Maps
