### ISSUE TITLE
Ja[kb] is undefined

### ISSUE THREAD

**Issue by arnabk** [highcharts/highcharts#5018] opened 2016-02-08 21:21 UTC
We are seeing lot of "Ja[kb] is undefined" errors in trackjs.com

What could generate such errors?

[webtrader.binary.com/beta](url)

<img width="638" alt="screen shot 2016-02-08 at 2 21 20 pm" src="https://cloud.githubusercontent.com/assets/446864/12899599/40534ffc-ce6f-11e5-9a17-b11ff840fa5e.png">

<img width="666" alt="screen shot 2016-02-08 at 9 11 40 pm" src="https://cloud.githubusercontent.com/assets/446864/12907435/a23e7906-cea8-11e5-9c6b-d5857d0397ad.png">

**Comment by TorsteinHonsi** [comment] 2016-02-09 08:57
Duplicate of #4998

**Closed by TorsteinHonsi** 2016-02-09 08:57 UTC
Labels: Duplicate
