### ISSUE TITLE
Issue when applying Boost.js

### ISSUE THREAD

**Issue by vutienthinh** [highcharts/highcharts#7009] opened 2017-07-26 08:20 UTC
Hi,

The reason I apply Boost.js is exporting CSV file with big data as well as improving the performance.

I have a problem when using boost and the number of series more than 9. The barchart displays incorrectly. Therefore I try the workaround approach by increasing the the threshold to deactivate the Boost. It's also cause of CSV exporting possibility which I really concern.

Do we have any official update about this problem from the Highcharts Team?

**Comment by KacperMadej** [comment] 2017-07-26 09:10
Hi,

Thank you for reporting. This is a duplicate of #6600.
Related issue: https://github.com/highcharts/highcharts/issues/6602

**Closed by KacperMadej** 2017-07-26 09:10 UTC
