### ISSUE TITLE
Zones doesn't work when the series data is an array of objects

### ISSUE THREAD

**Issue by aditya-padhi-kbl** [highcharts/highcharts#16749] opened 2021-12-02 14:43 UTC
#### Expected behaviour
Zones should work when the series data is an array of objects

#### Actual behaviour
Zones doesn't work when the series data is an array of objects

#### Live demo with steps to reproduce
http://jsfiddle.net/njgapedm/3/
You will notice that the zones are not working

#### Product version
9.2.2

#### Affected browser(s)
All the browsers

**Comment by raf18seb** [comment] 2021-12-07 00:17
Hi @aditya-padhi-kbl, thank you for contacting us with your issue.

The zones are working fine with data as an array of objects, but there are small issues with your chart's config.
You are using xAxis as your zone axis:
```js
zoneAxis: 'x',
```
If you change it to `'y'` and fit your data, it's working fine, see a demo: https://jsfiddle.net/BlackLabel/uyzgqpvh/

But I think the `'x'` zoneAxis type was defined in purpose - I assume you wanted to color the series beyond the "2011" category.
Setting the `category` type on an xAxis doesn't change the points' coordinates - they are still `x: 0`, `x: 1`, `x: 2` etc. (first category, second category, third category etc.). Here is a demo showing it: https://jsfiddle.net/BlackLabel/yqzt36vp/

I hope this is what you've been trying to achieve. I'm closing the ticket now as it's not a bug, but feel free to reopen if I misunderstood something.

**Closed by raf18seb** 2021-12-07 00:17 UTC

**Comment by aditya-padhi-kbl** [comment] 2021-12-07 05:51
Thank-you @raf18seb for the details.  When we use category (as in the second jsfiddle example) & set zoneAxis to x, can we make it possible to pass the zone value by category instead of actual x axis value.  In this way zones property will be easy to use.  This is just a suggestion though

**Comment by raf18seb** [comment] 2021-12-07 10:16
@aditya-padhi-kbl,

Thank you for your suggestion. The problem with strings is that they might be duplicated and the computer will not know which category exactly we point to. With numbers, the xAxis is always ordered ascending and the number values are not duplicated.

In your demo, to search the value by category string, you can use e.g. `Array.indexOf`: https://jsfiddle.net/BlackLabel/Lw0r8py3/
You can also define your categories and data this way: https://jsfiddle.net/BlackLabel/rLdf84kn/

In case of any further questions, please contact our support team on dedicated support channels (GitHub is our bugs/features tracker only).
More info: https://www.highcharts.com/blog/support/
