### ISSUE TITLE
Overlapping points click event

### ISSUE THREAD

**Issue by majuansari** [highcharts/highcharts#4698] opened 2015-10-29 07:26 UTC
Hi,

I have a situation where two line chart A and B has a coordinate at same (x,y) location

I have click event associated with each line graph coordinates. When ever i click the coordinates only Bs click event is triggered? How can I trigger separate click event for both A and B ?

Thanks

**Comment by pawelfus** [comment] 2015-10-30 11:17
Well, the problem is the same with simple HTML, consider example: http://jsfiddle.net/zmm442be/

I think of several possible solutions:

- implement some jittering ([Wiki: Jitter](https://en.wikipedia.org/wiki/Jitter)) to add noise to the data. The idea behind that is to provide data in this format: `{x: timestamp, y: jittered_value, val: true_value}`, so later in `tooltip.formatter` you could use `point.val`, so user would see real value.
- in `point.events.click` find all points from all series with the same x-value. Then compare y-values and if two points are exactly the same by value, then decide which point (or both) should take an action
- use different `marker.radius` for different series, for example series with the lowest `z-index` will get highest radius etc.

**Comment by majuansari** [comment] 2015-10-30 14:29
Is there anyway for highchart to determine this ? Increasing the radius based on the z index value ?

Or can you provide me with a jsfiddle example ?

**Comment by pawelfus** [comment] 2015-10-30 14:49
Mi idea was like this: http://jsfiddle.net/h5ozpfj2/ - it looks like only first series receives an event (Mar-case), since marker radius isn't used to determine closest point (only plotX and plotY). 

Looks like connected to #4679.

**Comment by majuansari** [comment] 2015-11-02 18:41
So does it mean that marker radius also wont work now ? I also tried your example but not sure how it help.Hover shows one series and click event is triggered for another in my case

**Comment by pawelfus** [comment] 2015-11-03 10:00
Sorry for not being clear - I created demo to show you how could this work, but, well, it doesn't work. 

However, it is possible to achieve the same result by using `scatter`-type series with `lineWidth=2` and without shared tooltip, see: http://jsfiddle.net/h5ozpfj2/4/

**Comment by majuansari** [comment] 2015-11-04 04:19
Thanks a lot .But will this work for spline type series ?

**Comment by pawelfus** [comment] 2015-11-04 10:44
I'm sorry, but my solution is for `scatter` series, not `spline`. 
If you need to use `spline` type, then I suggest to use first or the second solution I suggested.

**Comment by pawelfus** [comment] 2015-11-05 10:17
Connected [UserVoice](http://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/9523164-uniquely-display-multiple-points-at-the-same-coord) ticket.

**Comment by pawelfus** [comment] 2018-03-12 10:33
Hi @andriikoval23 

Could you contact with our support? See: https://www.highcharts.com/support

**Comment by pawelfus** [comment] 2018-07-18 08:10
@SnekkySnek - you can set higher [zIndex](https://api.highcharts.com/highcharts/series.line.zIndex) for a series in the background. Alternatively, use CSS (`pointer-events: none`) for shapes that overlap your point.

**Comment by KacperMadej** [comment] 2019-03-10 17:58
Possible workarounds are in this topic.
The issue is about an enhancement that has related UserVoice ides reported here: 
https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/9523164-uniquely-display-multiple-points-at-the-same-coord

Closing to avoid duplication. Vote on UserVoice is you have the same issue or contact technical support if your issue is only similar. https://www.highcharts.com/blog/support/

**Closed by KacperMadej** 2019-03-10 17:58 UTC
