### ISSUE TITLE
Multiply series - rangeselector

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#1402] opened 2012-12-13 10:12 UTC
When we have two series (or more) and use two xAxis, rangeselector or setting range by navigator, change range only for first serie.

example: http://jsfiddle.net/tTWTW/1/

**Comment by oysteinmoseng** [comment] 2018-04-30 08:06
Closing as not a bug.

**Closed by oysteinmoseng** 2018-04-30 08:06 UTC
Labels: Highstock, Not a bug
