### ISSUE TITLE
highcharts.js:42 Uncaught TypeError: Cannot read properties of undefined (reading 'indexOf')

### ISSUE THREAD

**Issue by daxdevd** [highcharts/highcharts#17149] opened 2022-04-03 06:05 UTC
#### Expected behaviour

No error should be display
#### Actual behaviour
Getting error on console

#### Live demo with steps to reproduce

![image](https://user-images.githubusercontent.com/75841739/161413971-a945954a-dcad-428d-a12b-b9c7628548bc.png)

#### Product version

highcharts: 7.1 to 10
node: 16.13.9
webpack: 5

**Comment by pawellysy** [comment] 2022-04-04 08:11
Hi @daxdevd, thanks for creating an issue!
 However, it is hard to work something out with the amount of data you provided. Could you share the demo, where the issue is reproduced? You can start here: https://jsfiddle.net/BlackLabel/9b1p5vkn/

**Comment by daxdevd** [comment] 2022-04-04 11:43
Thank you @pawellysy.
I am using highcharts in my reactjs project and it is installed using yarn package manager.
Now, Existing versions in my project is :
"highcharts": "^7.0.0",
"highcharts-react-official": "^2.0.0",

and Now I have upgraded node versions in my project so, I thought I also need to upgrade highchart package so I have upgraded it to latest version i.e. 10.0.0 now by using it I am getting above mentioned error.
Moreover here, now I am trying to downgrade it to the version where originally was i.e. 7.0.0 using yarn add highcharts@7.0.0 it goes hang and not able to install the respective version.
![image](https://user-images.githubusercontent.com/75841739/161536338-eefef051-1a92-4265-bb0c-3771740ad7d7.png)

I am not able to understand why this is happening.

And Is there any document available where I can check that which highcharts version work with supported node version and webpack.

I am really very stucked here since a week, and I am not getting any solution for this issue.

**Comment by pawellysy** [comment] 2022-04-05 08:53
Hi again @daxdevd, So your issue occurs without any highcharts configuration on the page?
Highcharts library works with the newest node versions, so in my opinion, there must be something that changed in the API. 
The error says otherwise, probably one of the options that you defined is not an array and it should be. 
Could you replicate your error in the online editor? Here is working example: https://stackblitz.com/edit/react-nwseym?file=index.js

If not, could you paste the code configuration of the chart? Thanks

**Comment by pawellysy** [comment] 2023-01-28 12:01
Closing - No reproduction steps

**Closed by pawellysy** 2023-01-28 12:01 UTC
Labels: Status: Can't reproduce, Status: Pending reply
