### ISSUE TITLE
Combining arearange and multiple line series leads to broken charts with boost module

### ISSUE THREAD

**Issue by rstrietzel** [highcharts/highcharts#7385] opened 2017-11-09 10:19 UTC
#### Expected behaviour
Multiple arearange and line Charts can be combined in one chart when the boost module is enabled.

#### Actual behaviour
If more than one line series is added to a chart containing two arearange series the chart is not displayed correctly anymore:
* Arearange is not displayed as area anymore
* Tooltip behaves strange (different x-Positions on different series)
* navigator is missing

This was working fine in Highcharts 5.0.7 with boost enabled.
#### Live demo with steps to reproduce
Chart with two arearange series and one line series is displayed correctly:
http://jsfiddle.net/9g44frpy/

If a second line is added (tried with different ones, even the same as the first line), the chart displays not corectly anymore:
http://jsfiddle.net/9g44frpy/1/

#### Affected browser(s)
Tested in Firefox, Chrome

**Comment by pawelfus** [comment] 2017-11-09 13:17
Hi @rstrietzel 

Thank you for reporting. In Highcharts 5.0.8 new version of boost was released. You can also recreate the issue in your first demo by setting `boostThreshold` to a very small value. Your first demo doesn't use `boost` at this moment (you can see SVG elements in DOM).

Demo with 5.0.7: http://jsfiddle.net/9g44frpy/2/

Minified demo: http://jsfiddle.net/68yez6q6/ - this looks like a duplicate of #7247

I found also additional issue in http://jsfiddle.net/9g44frpy/1/: 
- use navigator to zoom in, to the moment we see SVG elements (correct chart)
- slowly zoom out, at some point we will see duplicated series

**Comment by TorsteinHonsi** [comment] 2017-11-15 08:40
It seems to be related to how the area range is drawn. If we take the official arearange boost sample and reduce the number of points, it reveals that it is composed of simple lines between points: http://jsfiddle.net/highcharts/xp42ggLx/

@cvasseng Can you share some insight here?

**Comment by cvasseng** [comment] 2017-11-15 09:07
@TorsteinHonsi that's correct - arearange is drawn as lines. So it doesn't work very well if the point density is low. A combination of a low point threshold, high series threshold, and `boost.allowForce = false` should give better results. The latter stops the whole chart from entering boost mode if all series are supported by boost, _and_ one or more of the series crosses its threshold.

**Comment by TorsteinHonsi** [comment] 2017-11-15 09:09
![skjermbilde 2017-11-15 kl 10 04 33](https://user-images.githubusercontent.com/227836/32827433-7a3b6c2a-c9ec-11e7-9ee0-58a99ca65fc1.png)

Apparently these lines go between the `high` value of one point to the `high` value of the next, then there's a gap, then repeat. So the `low` values aren't drawn at all. Probably the intention was to draw lines from `high` to `low` on each point. That would also explain why the 500k arearange demo seems to be missing data in the low end.

**Comment by TorsteinHonsi** [comment] 2017-11-16 13:13
On a side note, lines from `high` to `low` would make the arearange identical to the columnrange, so while looking at this we might as well make columnrange work as well.

**Comment by cvasseng** [comment] 2017-11-16 13:19
Sounds good. 

I would like to do real tessellation at some point as well, rather than rendering just as lines. It may be more performant that way, as we'd likely get away with fewer total vertices.

**Comment by KacperMadej** [comment] 2017-12-21 13:49
+1

**Comment by cvasseng** [comment] 2018-01-22 11:52
I have added a fix for the erroneous rendering (high -> high), with a pending pull request: http://jsfiddle.net/xp42ggLx/1/

In terms of the original issue, the navigator now works as it should when using master. Also note that area ranges being rendered as lines/bars is a current limitation of the boost module, but it does look considerably better with the rendering fix: http://jsfiddle.net/6a8jfq8w/

**Comment by pawelfus** [comment] 2019-04-05 12:53
Issue is fixed since v6.0.5: http://jsfiddle.net/BlackLabel/v9L0bhge/4/

**Closed by pawelfus** 2019-04-05 12:53 UTC
Labels: Fix suggested, Type: Bug
