### ISSUE TITLE
In touch screen device y axis pan,zoom does not work

### ISSUE THREAD

**Issue by rohit-hannainst** [highcharts/highcharts#10824] opened 2019-05-27 13:24 UTC
#### Expected behaviour
ln line chart with multiple  y-axis series graph should pan and zoom(for both x and y axis) 

#### Actual behaviour
graph is not panning and zooming smoothly and  y-axis panning is not working properly
in touch screen devices.
#### Product version

Highcharts JS v7.1.1 (2019-04-09)
#### Affected browser(s)
All

**Comment by sebastianbochan** [comment] 2019-05-28 08:45
Hi @rohit-hannainst,
Thank you for reporting about the problem. Could you update my demo: https://jsfiddle.net/BlackLabel/6nu489eb/ with your options and data? It will allow me to reproduce the issue and debug.

**Comment by rohit-hannainst** [comment] 2019-06-28 10:07
Hi @sebastianbochan 
Thanks for reply , i updated my code at  https://jsfiddle.net/9ms60bt3/2/ 
so please check it.

**Comment by sebastianbochan** [comment] 2019-07-01 08:13
Hi @rohit-hannainst,
Thank you for the feedback.

Do you mean that during panning, the line of chart is "outside" and "new line" is draw when your fingers are out of the screen?

**Comment by rohit-hannainst** [comment] 2019-07-03 12:43
yes

**Comment by sebastianbochan** [comment] 2019-07-04 07:53
Thank you for the feedback. The issue is related with our known case, reported here: https://github.com/highcharts/highcharts/issues/5270.

Im closing this ticket as duplicate of https://github.com/highcharts/highcharts/issues/5270

**Closed by sebastianbochan** 2019-07-04 07:53 UTC
