### ISSUE TITLE
Datalabels functions for point and series conflict causing point to disappear

### ISSUE THREAD

**Issue by mdhari** [highcharts/highcharts#5668] opened 2016-09-07 21:51 UTC
#### Expected behaviour
1. Add a dataLabel to point 4 only.
2. Toggle the entire line's datalabels by clicking on any point.
3. Point 4's datalabel should be set to whether we are enabling or disabling the datalabels for the entire line via series.update. (can be argued that points settings are independent)
#### Actual behaviour
1. Add a datalabel to point 4 only.
2. Toggle the entire line's datalabels by clicking any point.
3. **Point 4 disappears** 

![screen shot 2016-09-07 at 2 46 38 pm](https://cloud.githubusercontent.com/assets/810521/18329743/ece5f7f6-7509-11e6-9b33-47f285cecdd5.png)
#### Live demo with steps to reproduce

http://jsfiddle.net/bj2q94rm/2/
1. Click Step 1 button.
2. Click on any point on the line
#### Affected browser(s)

Currently testing on Chrome Version 52.0.2743.116 (64-bit)
#### Additional Notes:

In case you were wondering, I have two requirements to fulfill here:
1. Allow the user to activate the datalabels for the entire line by clicking on any point
2. Allow the user to vertically activate datalabels across series when they click on a xAxis label. (hence, I'm trying to accomplish this via point datalabels versus series datalabels)

**Comment by jon-a-nygaard** [comment] 2016-09-08 08:36
Thanks for reporting, we will try to fix this as soon as possible.

_Internal Note: [Simplified demo](http://jsfiddle.net/jon_a_nygaard/bj2q94rm/5/)_

**Comment by pawelfus** [comment] 2016-09-08 09:25
I think we have reported the same (or similar at least) issue. Workaround is to update point with providing `y` value. Problem is with updating point, which change format from simple value, to object.

**Workaround:**   
  
        point.update({
          y: point.y,
          dataLabels: {
            enabled: true
          }
        });

http://jsfiddle.net/bj2q94rm/6/

**Comment by pawelfus** [comment] 2016-09-08 09:28
Related to #4916

**Comment by pawelfus** [comment] 2017-04-25 15:50
Closing as duplicate of #4916 - original demo works fine too.

**Closed by pawelfus** 2017-04-25 15:50 UTC
Labels: Bug
