### ISSUE TITLE
Missing first few X-axis points after panning right, because unable to drag back to reveal the missing points

### ISSUE THREAD

**Issue by jackytanjq** [highcharts/highcharts#17426] opened 2022-06-22 01:49 UTC
#### Expected behaviour
The chart should allow the user to pan the chart freely while being able to view all X-axis points.

#### Actual behaviour
While viewing the first few points in the chart then dragging the chart to the right, the chart is not able to drag back to the left.
Causing the first few X-axis points to be missing.

If the navigator exists, it can be used to reveal the missing first few X-axis points.

#### Live demo with steps to reproduce

![Highcharts_MissingFirstPtAfterDragging](https://user-images.githubusercontent.com/7489622/174925430-92e89557-bb1b-4d8a-9aaa-f97f476a6750.gif)

Steps to reproduce:
1) Reduce the range of the datetime (eg. 1m timeframe).
2) Using the navigator, drag the chart all the way to the left and take note of the first point (eg. 18 June in the above example).
3) Using the chart above, drag the chart to the right then drag back to the left as much as possible.
4) Take note of the first point in comparison to the first point in Step 2.

#### Product version
Highstock v10.1.0

#### Affected browser(s)
N/A

**Comment by raf18seb** [comment] 2022-06-22 21:39
Hi @jackytanjq, thank you for reporting the issue.

Looks like a duplicate of https://github.com/highcharts/highcharts/issues/4076, never resolved. I'll reopen that ticket.

**Comment by karolkolodziej** [comment] 2023-11-17 14:40
> Fixed in v11.1.0: https://jsfiddle.net/BlackLabel/e2rsm39a/1/

**Closed by karolkolodziej** 2023-11-17 14:40 UTC
Labels: Product: Highcharts Stock, Type: Duplicate
