### ISSUE TITLE
Highcharts set visible redraw with second parameter false

### ISSUE THREAD

**Issue by royigoldi** [highcharts/highcharts#6896] opened 2017-06-25 10:20 UTC
Expected: the chart doesn't redraw on setVisiblie

Actual:
when i call setVisible with second parameter false (to do the redraw manually in the end), when i debug in chrome i see that the series add/remove in the chart in each iteration (depend on the first parameter to setVisible) 

Highcart version from npm:
5.0.12

Browser:
Chrome

when i used before 2-3 monthes older versions of highcharts it work fine (My code doesn't change)

**Comment by TorsteinHonsi** [comment] 2017-06-26 11:49
See http://jsfiddle.net/5yhau4bt/.

The series is removed immediately, but the rest of the chart is not redrawn around it. If we set the `redraw` parameter to true, you'll see that the other series redraws to fill in the gaps.

Can you demonstrate how this has changed from an earlier version?

**Comment by royigoldi** [comment] 2017-06-26 16:29
Ok,

but why i didn't know why i  have poor performance on hide all and show all
:

implement like this for hide all for example:
.setVisible(false, false); //for each series

chart.redraw()

can you help me, i have 20 series..



2017-06-26 14:49 GMT+03:00 Torstein Hønsi <notifications@github.com>:

**Comment by pawelfus** [comment] 2017-07-03 12:18
I assume this is the problem: http://jsfiddle.net/5yhau4bt/4/

Without boost, it works much faster: http://jsfiddle.net/5yhau4bt/5/

**Comment by royigoldi** [comment] 2017-07-04 07:22
It's not strange that with boost, it is work slower (hit the performance)???

**Comment by rrdnd** [comment] 2017-10-10 16:40
@TorsteinHonsi @pawelfus  I have noticed the redraw event (chart.events.redraw) is triggered when the second parameter for series.setVisible is set to false. Can you confirm this is not a bug?

I prepared a fiddle to illustrate this:
https://jsfiddle.net/rredondo/x8pzoqtv/

**Comment by pawelfus** [comment] 2017-10-11 10:16
Hi @rrdnd 

It is a bug, but only in Highstock, because `setVisible()` hides also the navigator series. Navigator series doesn't care about the `redraw` param, using `hide()` (should be `setVisible(false, false)` there):

https://github.com/highcharts/highcharts/blob/22390e8b26cb33b286d0306c569cdce7261c2fea/js/parts/Navigator.js#L1784

**Comment by rrdnd** [comment] 2017-10-11 11:00
Hi @pawelfus,
Should I open a new issue for this bug? Thanks for everything!!

**Comment by pawelfus** [comment] 2017-10-11 11:26
Yes, please open a new issue :) You will get notifications when it will be fixed then.

**Comment by pawelfus** [comment] 2019-04-03 15:07
Bug with slow hiding series has been fixed in Highcharts v6, demo: http://jsfiddle.net/BlackLabel/0uo97Lgx/

**Closed by pawelfus** 2019-04-03 15:07 UTC
