### ISSUE TITLE
setData corrupts previous data when switching to dataset of same size

### ISSUE THREAD

**Issue by jugaltheshah** [highcharts/highcharts#5772] opened 2016-10-03 22:51 UTC
#### Expected behaviour
When I use setData to update a data set, I expect it to load the correct data and not write to the object.

#### Actual behaviour
When I use setData to update data set, it seems to corrupt the previous data set when they are of the same size.

#### Live demo with steps to reproduce
Demo: http://jsfiddle.net/cb49mv4a

Steps to reproduce:
1) Notice initial state - firstDataSet loaded into chart (also observe "Current data set: first" under chart)
2) Press the "Toggle dataset" button - chart correctly loads secondDataSet into chart ("Current data set" also updates to 'second')
3) Press the "Toggle dataset" button again - chart does **_not_** load previous (initial) data set. ("Current data set" correctly updates to 'first')

#### Additional Note
Works properly if call setData with updatePoints set to false. I believe this should work in either case - I'm _not_ loading in the same data set, and Highcharts should not write over a totally different set of data!

#### Affected browser(s)
All

**Comment by pawelfus** [comment] 2016-10-04 09:01
Hi @jugaltheshah - actually this is a duplicate of #4259.

**Closed by pawelfus** 2016-10-04 09:01 UTC

**Comment by jugaltheshah** [comment] 2016-10-04 15:52
Hi @pawelfus - yes I'd found that issue, but the workaround presented there does not work here (myData.splice(0)), which led me to believe it may not be exactly the same. As mentioned, it does work for me with updatePoints set to false, but I lose out on animation and optimization, so it would be nice to get it resolved.

Thanks though!

**Comment by TorsteinHonsi** [comment] 2016-10-05 07:23
Apparently the problem is not with the array itself getting corrupted, but each configuration object. So the [equality check](https://github.com/highcharts/highcharts/blob/v5.0.0/js/parts/Series.js#L512) gives a false positive because the original config object has been mutated. But that's not the whole truth, for even when removing this check, it fails...

**Comment by pawelfus** [comment] 2016-10-05 09:25
@jugaltheshah 

`splice()` method works fine only for arrays of primitives, not for an array of objects. In case of objects, a deep copy is better solution, for example using jQuery: `$.extend(true, [], arrayOfObjects)`. Demo: http://jsfiddle.net/cb49mv4a/1/

**Comment by jugaltheshah** [comment] 2016-10-05 10:59
@TorsteinHonsi: yes, this is what I was experiencing... The original data store was being modified.

@pawelful: ahhh I see, ty again!
