### ISSUE TITLE
Columns overlap the zero line when chart includes both positive and negative values

### ISSUE THREAD

**Issue by hughess** [highcharts/highcharts#16424] opened 2021-09-29 14:45 UTC
#### Expected behaviour
Expect positive columns to sit above the line they start from:
![CleanShot 2021-09-29 at 10 20 10](https://user-images.githubusercontent.com/12602440/135292117-f14c18c6-c532-4af8-9b32-a977022a8c75.png)

#### Actual behaviour
When positive and negative values are included in a column chart, positive columns overlap with the line they start from. Negative column behave as expected:
![mixed-chart-zero-overlap](https://user-images.githubusercontent.com/12602440/135292099-3ebbbd8d-a7db-4a7d-a2cc-38030b9de31c.png)

#### Live demo with steps to reproduce

https://jsfiddle.net/dfonra94/11/

#### Product version

Highcharts 9.2.2

**Comment by KacperMadej** [comment] 2021-09-30 16:10
Hi @hughess 

The ticker line on the bottom is an axis line that has its width used to calculate the column series plot offset.
(Technical details: clip rect is adjusted for the axis line width)
Demo: https://jsfiddle.net/BlackLabel/5sm6nquh/2/

If you will look closely at the -4 value in this demo: https://jsfiddle.net/BlackLabel/5sm6nquh/3/
you should be able to see that the bottom side of the column is on -4 and the top side is just under the gridline of 0. The same is for the positive values - the bottom side sits on top of the line and the top is just below.

This doesn't look like a bug.

**Comment by hughess** [comment] 2021-10-01 14:34
That makes sense, thanks for your reply @KacperMadej - I assumed that it might be expected behaviour, but wanted to check.

Is there any option in the config to use the gridline at y=0 as the axis line? I am hoping to replicate something like the chart below:

![CleanShot 2021-10-01 at 10 30 00](https://user-images.githubusercontent.com/12602440/135637694-134d1462-edd4-420a-a862-687535b7fbc5.png)

**Comment by KacperMadej** [comment] 2021-10-04 09:54
@hughess 
Yes, the option is called `plotLines` - works just as you need it to work.
Demo: https://jsfiddle.net/BlackLabel/ctvq1ae6/
API reference: https://api.highcharts.com/highcharts/yAxis.plotLines

Closing for now as a `not a bug` and a `question`, but if you have further questions we can continue here.

**Closed by KacperMadej** 2021-10-04 09:54 UTC
Labels: Status: Pending reply
