### ISSUE TITLE
Built in (Globe) Projection Export does not work

### ISSUE THREAD

**Issue by dropweb** [highcharts/highcharts#16567] opened 2021-11-01 09:14 UTC
#### Expected behaviour

Export to jpg/ png/ pdf & svg using the context menu produce a representation of the current globe projection in the selected format.

#### Actual behaviour

The export executes but the globe projection part is blank.

#### Live demo with steps to reproduce

Select any one of the export options from the export context menu:

https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/demo/topojson-projection

Just to note that the same (failed) behaviour is also present on the Hightcharts website demo:

https://www.highcharts.com/demo/maps/topojson-projection

#### Product version

9.3.0

#### Affected browser(s)

Tested in Chrome and Firefox.

**Comment by KacperMadej** [comment] 2021-11-01 13:37
Hi @dropweb,

Thank you for reporting the problem.

The problem is already fixed on the pre-release code build. Closing as resolved.
Demo: https://jsfiddle.net/BlackLabel/szpdtxo9/
Please note that the code on the GitHub master branch (the pre-release) is unstable and should be used with caution.

**Closed by KacperMadej** 2021-11-01 13:37 UTC
