### ISSUE TITLE
Null values alowed on exponential scale but error 10 still thrown

### ISSUE THREAD

**Issue by frontendplace** [highcharts/highcharts#5187] opened 2016-04-06 11:35 UTC
Error message:
http://www.highcharts.com/errors/10
example:
```js
$(function () {
    $('#container').highcharts({
        xAxis: {
            categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
        },
        yAxis: {
            type: 'logarithmic'
        },
        series: [{
            data: [null, 2, 45, 1001, 200, 0.33, 10000]
        }]
    });
});
```

**Comment by TorsteinHonsi** [comment] 2016-04-06 11:48
No error thrown here: http://jsfiddle.net/vxawreyq/. 

Can you modify this to reproduce the issue?

**Comment by jon-a-nygaard** [comment] 2016-04-26 08:36
Closing this issue due to: We are not able to reproduce the issue, and it is pending reply. 
Should anyone have further information on this issue, please add a comment and reopen.

**Closed by jon-a-nygaard** 2016-04-26 08:36 UTC
Labels: Cant reproduce, Pending reply
