### ISSUE TITLE
Treemap - update issue for point's with declared parent

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#11829] opened 2019-09-02 10:42 UTC
The update feature doesn't work for points with declared parent property. 

Last working version is 6. 

#### Live demo with steps to reproduce

[Demo](https://jsfiddle.net/BlackLabel/mvbwjroc/)

#### Product version

versions > 6

**Comment by pawelfus** [comment] 2019-10-11 14:44
Duplicate of #11738

**Closed by pawelfus** 2019-10-11 14:44 UTC
Labels: Type: Regression
