### ISSUE TITLE
Zoom with mouse does not work. Zoom selector sticks to mouse

### ISSUE THREAD

**Issue by WolfWalter** [highcharts/highcharts#15865] opened 2021-06-08 13:11 UTC
#### Expected behaviour
When I use the mouse to zoom the line chart, the zoom should be performed after mouse up

#### Actual behaviour
After mouse up the zoom selector sticks to the mouse and no zooming is performed. 

#### Live demo with steps to reproduce
![zoom-behaviour](https://user-images.githubusercontent.com/2098069/121189470-6e723880-c86a-11eb-8c7a-d6b6bac59bb5.gif)

https://stackblitz.com/edit/highcharts-angular-basic-line-9bbehm?file=src/app/app.component.ts

After upgrading to Highcharts 9.1.0 or 9.1.1 in my Angular/Ionic webapp, 8 out of 10 times I am not able to zoom. I was able to reproduce the same behavior as shown in the gif in stackblitz, after making changes to the code.

#### Product version
Highcharts > 9.0.1

#### Affected browser(s)
Only tested on current Chrome

**Comment by khlieng** [comment] 2021-06-09 06:54
Fixed by #15850, duplicate of 15845.

**Closed by khlieng** 2021-06-09 06:54 UTC
Labels: Type: Duplicate
