### ISSUE TITLE
Updating chart with new series events leads to unexpected behaviour

### ISSUE THREAD

**Issue by Elektropepi** [highcharts/highcharts#11088] opened 2019-06-18 15:30 UTC
#### Expected behaviour
Create chart with `plotOptions.series.events.mouseOver` set, then calling `chart.update()` with `plotOptions.series.events.mouseOver` set should replace the old mouse over events. On series mouse over only the function supplied in `chart.update()` should be called.

#### Actual behaviour
Create chart with `plotOptions.series.events.mouseOver` set, then calling` chart.update()` with `plotOptions.series.events.mouseOver` doesn't remove the initial mouse over, thus on series mouse over the old `mouseOver` is called too.

This is especially annyoing, since in highstock.src.js:32879 `series.hcEvents[eventType].indexOf(event) === -1` checks if the event already exists. But this call doesn't work for anonymous functions returned by other functions, thus the same event is called multiple times!

#### Live demo with steps to reproduce
https://jsfiddle.net/elektropepi/mhqop7zy/20/

#### Product version
Highstock 7.1.1

#### Affected browser(s)
Firefox 67.0

**Comment by TorsteinHonsi** [comment] 2019-06-19 08:45
Thanks for reporting!

Simplified demo: http://jsfiddle.net/7vj5g9o6/

**Comment by TorsteinHonsi** [comment] 2019-06-19 09:31
Duplicate of #10861

**Closed by TorsteinHonsi** 2019-06-19 09:31 UTC
