### ISSUE TITLE
Highcharts dataLabel not working on Safari using Dark Unica theme

### ISSUE THREAD

**Issue by tgl-dogg** [highcharts/highcharts#5613] opened 2016-08-23 13:12 UTC
#### Expected behaviour
The highcharts.plotOptions.dataLabel, when enabled, should show the labels for every point of data with every (provided) theme in every supported browser.

#### Actual behaviour
The labels with the data values are missing when using Dark Unica theme using Safari.
With other themes it works as expected on Safari, also works in other browsers with every theme.

#### Live demo with steps to reproduce
Can be seen in the line-labels demo:
http://www.highcharts.com/demo/line-labels/dark-unica

EDIT: sorry if steps to reproduce were unclear, you are supposed to open this demo in Safari and see that the data labels are not showing. Switch to another theme within the demo and see that labels are now visible.

#### Affected browser(s)
Safari 5.1.7 (7534.57.2) for Windows

**Comment by TorsteinHonsi** [comment] 2016-08-24 09:32
I'm sorry, I can't reproduce this, see the screenshot. Your Safari version is very old, have you tried a newer version?

![skjermbilde 2016-08-24 kl 11 32 13](https://cloud.githubusercontent.com/assets/227836/17925743/74a78f28-69ee-11e6-81bf-ce9545689730.png)

**Comment by tgl-dogg** [comment] 2016-08-24 23:58
Thanks for replying! Yes, it works on newer versions of Safari, I tested it today. The Windows version of Safari (5.1.7) is the only one I've seen with this problem. 

In my application we decided to do not support Safari on Windows because Apple ceased to provide support, but since Highcharts supports Safari 4.0+ I decided to file a issue.

**Comment by jon-a-nygaard** [comment] 2016-08-30 07:52
I can can confirm that this works with Safari 5.1.7 on both Windows 8, 8.1 and 10.
![Screenshot from Windows](https://s12.postimg.io/it6cqmhel/screenshot.png)

I will close this since we are unable to reproduce this issue in the specified environments. Should anyone have further information about this issue, please give us a comment.

**Closed by jon-a-nygaard** 2016-08-30 07:52 UTC
Labels: Cant reproduce
