### ISSUE TITLE
Flag series not showing the tooltip to view the text

### ISSUE THREAD

**Issue by kingmohd** [highcharts/highcharts#6916] opened 2017-07-03 17:24 UTC
#### Expected behaviour
To show a tooltip to display the text

#### Actual behaviour
doesn't show the tooltip.
I have explicitly added tooltip property; still didn't change the end result

#### Live demo with steps to reproduce

http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/flags-shapes/
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/flags-placement/
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/flags-general/
#### Affected browser(s)
I have tested on Chrome, Safari, and Firefox

**Comment by pawelfus** [comment] 2017-07-04 09:36
Hi @kingmohd 

This is bug in the current version, already fixed on our master branch, please take a look: http://jsfiddle.net/h1tu8c9j/

Closing as duplicate of #6764

**Closed by pawelfus** 2017-07-04 09:36 UTC
