### ISSUE TITLE
Pie charts not round in Safari, JSFiddle included

### ISSUE THREAD

**Issue by DanielVF** [highcharts/highcharts#1713] opened 2013-04-11 14:03 UTC
When repeatedly updating a pie chart, the chart looses its circular shape in Safari.

![image](https://f.cloud.github.com/assets/837/367517/60095398-a2ab-11e2-9780-c532a2714074.png)

I've created a JS fiddle of this behavior against the highcharts master js.

![image](https://f.cloud.github.com/assets/837/367631/5a358a10-a2ae-11e2-85d5-10f5e9ad3a30.png)

http://jsfiddle.net/EVPyu/

Click start, and around redraw 17 it will stop being round.

I'm running OS X 10.7.5 with Safari 6.0.2. I'm also getting reports of users seeing this in Safari as well.
- Behavior appears related to total number of slice draws - if you change the data generation to have more slices in each pie, the bug shows on an earlier pie redraw. If you change it to have less slices, then the bug shows later. ( if you change the data to have three slices, then the bug shows at around display number 25, rather than the 17 redraws with 5 slices).
- Time interval between redraws does not seem to affect Behavior
- Behavior does not happen when animation is true (in the fiddle, still breaks on my main site)
- Behavior does not happen when spacingTop and spacingBottom are removed (Actually, this is depends on something else. Removing spacingTop and/or spacingBottom has no effect on my real site, only on the fiddle)
- This behavior **does not show up if the dev console is open**, however, if the dev console is open, then closed while the chart is repeatedly redrawing, the behavior shows up after some redraws.

**Comment by oysteinmoseng** [comment] 2018-05-08 11:52
Could not reproduce this with current Safari and Highcharts. Closing for now.

**Closed by oysteinmoseng** 2018-05-08 11:52 UTC
Labels: Bug
