### ISSUE TITLE
Initializing annotations in responsive rules doesn't work

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#10713] opened 2019-05-13 14:14 UTC
Reopening https://github.com/highcharts/highcharts/issues/8680

Annotations don't work with responsive rules

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/sxw9eb7j
Click **Small** button - annotations are not added.

#### Product version
7.1.1

#### Affected browser(s)
All

**Comment by raf18seb** [comment] 2019-05-13 14:16
#8680

**Comment by raf18seb** [comment] 2019-05-13 14:45
Workaround: create annotations when chart inits with **visible: false** and show specific annotations in responsive rules: https://jsfiddle.net/BlackLabel/1tkadspc

**Comment by sebastianbochan** [comment] 2019-05-14 08:52
Duplicate of #8680

**Comment by pawelfus** [comment] 2019-05-14 09:25
It's very similar, I asked to open separate ticket.

**Comment by pawelfus** [comment] 2019-05-15 15:34
It seems to be general issue with responsive rules and not creating elements from array. The same issue with series: https://jsfiddle.net/BlackLabel/sxw9eb7j/11/

**Closed** 2019-05-16 07:23 UTC
Labels: Status: Pending review, Type: Bug

**Comment by arquib** [comment] 2020-06-13 17:11
I think this has broken again. See the original fiddle, when the chart is *initialised* with the relavent screen width, the applied annotations don't render.

It only works when you open it in the larger screen size and then reduce with width.

**Comment by pawelfus** [comment] 2020-06-15 10:36
Thanks for pointing this out @arquib 

Created separate ticket for this issue: #13716. Please try and let us know if you find any issues with the workaround posted in #13716.
