### ISSUE TITLE
Graph disappears ( fails to render / crashes ) randomly on update.

### ISSUE THREAD

**Issue by rorykoehler** [highcharts/highcharts#4744] opened 2015-11-16 11:55 UTC
I'm using datatables data and ajax to update a highcharts graph using highcharts rails gem version 4.1.5 (also tried 4.1.8). Everything works fine until, after changing the data set to display an unspecified number of times, it seemly randomly (I can't deduce any specific patterns) crashes. There are two things that happen:

- It stops rendering new data in the graph area but the previous data is still on display
- It renders a blank container with no graph inside

The data in the JSON arrays is however being updated when inspected in dev tools. This is happening on both Chrome and Firefox. In my JSFiddle example I have omitted the update using setData() as I have experienced this issue when only updating the data and also when rendering the whole chart fresh each time.

JSFiddle:

http://jsfiddle.net/6xkgyw8o/2/

**Comment by highslide-software** [comment] 2015-11-16 17:04
What steps do we follow to make the demo crash? You're describing updating over AJAX - can you demonstrate this crashes in your jsFiddle by using local data? I'm afraid we can't do anything about it without a live reproduction.

**Comment by rorykoehler** [comment] 2015-11-22 22:38
Ye I didn't have my hopes up. It will be hard to give you a live reproduction without letting you into our system. I was hoping you may have come across similar behaviour before. I have been unable to get any further insight into this issue. Seems to be happening totally randomly. If I figure something out I will post back here.

**Comment by pawelfus** [comment] 2015-11-23 09:26
I have two suggestions:

- try to remove additional code for aligning y-axes, there may be certain condition when it fails 
- since `setData()` and new chart prudces the same issue, maybe it is somehow connected to the data? Make sure you have proper format for data (without strings for values) and check if data is always sorted ascending by x-values (timestamps in your case)

**Comment by jon-a-nygaard** [comment] 2016-04-26 09:34
Closing this issue due to: We are not able to reproduce the issue, and it is pending reply. 
Should anyone have further information on this issue, please add a comment and reopen.

**Closed by jon-a-nygaard** 2016-04-26 09:34 UTC
Labels: Cant reproduce, Pending reply
