### ISSUE TITLE
Merging axis array with global options fails

### ISSUE THREAD

**Issue by ppcmetrics-thp** [highcharts/highcharts#21155] opened 2024-05-13 14:02 UTC
#### Expected behaviour
The axis options should be merged with the related global options.

#### Actual behaviour
When using an array for multiple axis support in the global options they get added a level deeper instead of getting merged. E.g.
```javascript
{
  xAxis: [{
    // Options from Highcharts.chart() call
    0: {
      // Global Options from Highcharts.setOptions()
    }
  }]
}
```

#### Live demo with steps to reproduce
- Faulty example with axis as array: https://jsfiddle.net/ppcmetrics/ob48gc0u/61/
- Working example without axis as array: https://jsfiddle.net/ppcmetrics/ugw52po7/6/

#### Product version
Highcharts `v11.4.1`  
(the bug didn't occur on `v10`)

#### Affected browser(s)
Chrome

**Comment by karolkolodziej** [comment] 2024-05-14 07:04
Hi @ppcmetrics-thp Thank you for reporting the issue! 

_Internal note:_
Bisected to: https://github.com/highcharts/highcharts/commit/999f29cce6386948e471e0756754cd0e48e01f88
@TorsteinHonsi is this an intended change?

**Comment by TorsteinHonsi** [comment] 2024-05-14 11:08
> is this an intended change?

Yes, the default options can no longer be arrays of axes. We may not have communicated it clearly, but since the refactor, DefaultOptions can only have a single axis config, while the resolved chart Options can have arrays:

https://github.com/highcharts/highcharts/blob/ae8c9973716153273898fc9163d0429e19373c9d/ts/Core/Axis/AxisOptions.d.ts#L41-L50

The `setOptions` take a DefaultOptions config.

The reason for the change among other things was that it didn't work consistently before. It worked in some cases.

**Comment by karolkolodziej** [comment] 2024-05-14 12:07
Thank you for the explanation. If it is intended I'm going to close it as not a bug.

**Closed by karolkolodziej** 2024-05-14 12:07 UTC
Labels: Product: Highcharts, Type: Not a bug
