### ISSUE TITLE
yAxis display out of pane after setExtremes

### ISSUE THREAD

**Issue by zhy1stgg** [highcharts/highcharts#7711] opened 2018-01-23 09:40 UTC
#### Live demo with steps to reproduce
http://jsfiddle.net/b62tdy3w/

click the button (set yAxis[0]'s extremes)

![snipaste_2018-01-23_17-38-56](https://user-images.githubusercontent.com/6829290/35268512-48cd3002-0064-11e8-8b93-bc0343164bab.png)

#### Product version
Highstock 6.0 +

**Comment by sebastianbochan** [comment] 2018-01-23 10:34
Hi @zhy1stgg 
Thank you for the reporting.

_Internal note_
It looks like an issue with candlestick and OHLC, cause line /area work fine.

**Comment by zhy1stgg** [comment] 2018-01-24 07:33
Hi @sebastianbochan line /area also have this issue, 
![snipaste_2018-01-24_15-32-58](https://user-images.githubusercontent.com/6829290/35319677-db2b3b62-011b-11e8-8d70-a9c923f97830.png)

**Comment by KacperMadej** [comment] 2018-01-24 12:46
Minimal demo for line: http://jsfiddle.net/BlackLabel/b62tdy3w/4/
and for column (wrong initial animation): http://jsfiddle.net/BlackLabel/b62tdy3w/5/

**Comment by sebastianbochan** [comment] 2018-01-25 10:14
@zhy1stgg problem with halo is related with known bug  https://github.com/highcharts/highcharts/issues/7650

**Comment by pawelfus** [comment] 2018-10-03 11:59
Related to #7711

**Comment by jon-a-nygaard** [comment] 2019-08-01 07:39
Could you @KacperMadej and @sebastianbochan confirm if this issue is fixed by #11531?

**Comment by KacperMadej** [comment] 2019-08-05 14:12
@jon-a-nygaard 
The good news is that the issue is resolved.
A bad news is below:

Assuming that current master branch code behavior is caused by the fix for the #11531 the column issue seems to be worse - no tooltip at all for the visible points. Demo: http://jsfiddle.net/BlackLabel/ke7nphqu/

For the line chart it also doesn't look perfect - demo: http://jsfiddle.net/BlackLabel/4auLorb7/
When you hover over a plot series are getting inactive state after hovering a pane with visible tooltip, single tooltip is frozen, crosshair is out of sync with tooltip.

**Comment by jon-a-nygaard** [comment] 2019-08-07 08:22
> no tooltip at all for the visible points

> For the line chart it also doesn't look perfect

Hmm, this is strange. Will look into what is causing these regressions.

**Closed** 2019-08-09 08:14 UTC
Labels: Product: Highstock, Type: Bug
