### ISSUE TITLE
Highstock addPoint animation wrong sometimes

### ISSUE THREAD

**Issue by borisyankov** [highcharts/highcharts#5314] opened 2016-05-13 13:04 UTC
#### Expected behaviour
When calling addPoint on a series and animation is enabled, it visually moves to the left

#### Actual behaviour
The line 'morphs' into the new values - each point moves vertically to represent the new value

#### Steps to reproduce the behaviour
This happens only sometimes, in more complicated code I have

**Comment by TorsteinHonsi** [comment] 2016-05-18 13:18
Duplicate of #5294

**Closed by TorsteinHonsi** 2016-05-18 13:18 UTC
Labels: Duplicate
