### ISSUE TITLE
On Zoom High chart does not scrolls to visible area

### ISSUE THREAD

**Issue by VHpriya** [highcharts/highcharts#9435] opened 2018-11-19 11:10 UTC
#### Actual behavior
On Zooming (ex: 225% or  200%)
(Affects power blind users)
Focus to goes the inside the chart, but it is not visible on the page(though the focus is going to element)
It does not scrolls down , so that part comes to visible area.
Similarly, if chart contains different section, this section also gets disappears. Focus is going to section 
but it is not in visible area.

#### Live demo with steps to reproduce

https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/funnel/

#### Affected browser(s)
Edge and Chrome

![image](https://user-images.githubusercontent.com/45167633/48703430-b207e700-ec19-11e8-8299-e60ffe80797f.png)
On Zoom (Web visits going out of visible area)
![image](https://user-images.githubusercontent.com/45167633/48703449-c3e98a00-ec19-11e8-99cf-2bdd282b21f7.png)

**Comment by KacperMadej** [comment] 2018-11-19 16:38
Hi @VHpriya 

This is caused by `min-width` in CSS. Reduce the limit and chart will be resized further.
Demo: https://jsfiddle.net/BlackLabel/8q7hbe6d/

**Comment by KacperMadej** [comment] 2018-12-31 01:36
Closing due to inactivity and as not a bug.

**Comment by SummerLi** [comment] 2019-05-09 00:24
Hi @KacperMadej,

The issue is not fixed. 

The ask here is for Chart Accessibility. Basically when user zooms in a log, and the chart cannot fit in the viewport -- this is fine. However, when user tries to tab through each of the chart data point, it should scroll the browser page, so that the data point hidden below can be brought back to the view port.

**Comment by sebastianbochan** [comment] 2019-05-09 08:17
Hi @SummerLi,
Thank you for reporting about the problem.

FYI @oysteinmoseng

**Comment by oysteinmoseng** [comment] 2019-05-09 08:34
I'll reopen this. We are currently setting browser focus on tab navigation, but we can see if it is possible to force a scroll as well.

**Comment by oysteinmoseng** [comment] 2020-01-30 10:25
With the latest a11y code this no longer seems to be an issue, as the browser is correctly bringing items into view when focused.

Closing for now, but feel free to reopen if we can reproduce with the latest code.

**Closed by oysteinmoseng** 2020-01-30 10:25 UTC
Labels: Status: Inbox, Type: Enhancement
