### ISSUE TITLE
PlotLines label text doesn't show up in new Chrome (Version 69.0.3497.100 )

### ISSUE THREAD

**Issue by rubiks-cube** [highcharts/highcharts#9057] opened 2018-09-26 05:54 UTC

**Comment by hwesterbeek** [comment] 2018-09-26 07:07
It actually happens in Safari, Firefox and IE as well. Guess it's not a browser issue.

Expected behaviour: text label shows next to plot line.
Actual behaviour: text label does not show next to plot line.
Demo: http://jsfiddle.net/vro0wfkL/1/
Product version: all versions prior to 6.1.1 (as far as i have tested)
Affected browsers: Chrome, Safari, Firefox, IE

**Comment by sad-xu** [comment] 2018-09-26 07:32
v6.0.7 in Chrome(67): ok
v6.0.7 in Chrome(69): text label does not show
v6.1.1 in Chrome(69): ok

**Comment by pawelfus** [comment] 2018-09-26 09:48
Hi 

This is duplicate of #8477 - please update your Highcharts version or use workaround posted in #8477.

**Closed by pawelfus** 2018-09-26 09:48 UTC
