### ISSUE TITLE
Heatmap breaks when boost module is imported

### ISSUE THREAD

**Issue by aditya3434** [highcharts/highcharts#21472] opened 2024-07-08 06:51 UTC
Heatmap fails to render when boost module is called and both min/max are set in `yAxis`.

#### Live demo with steps to reproduce
[jsFiddle reproducer](https://jsfiddle.net/gtm46nj7/)

#### Product version
Highcharts v11.4.1

**Comment by hubertkozik** [comment] 2024-07-08 07:10
Hi @aditya3434! Closing as a duplicate of https://github.com/highcharts/highcharts/issues/20456. Let's continue the discussions in the mentioned ticket.

**Closed by hubertkozik** 2024-07-08 07:10 UTC
Labels: Duplicate
