### ISSUE TITLE
Getting Below warning when trying to use download document as pdf option

### ISSUE THREAD

**Issue by Ayushk93** [highcharts/highcharts#16561] opened 2021-10-28 11:47 UTC
#### Getting Below warning when trying to use download document as pdf option.

DevTools failed to load source map: Could not load content for https://code.highcharts.com/9.1.2/lib/svg2pdf.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILUR

using Highcharts version 9.1.2 with Angular 10.

Please provide a solution for above warning.

**Comment by raf18seb** [comment] 2021-11-02 12:07
Closing as a duplicate of https://github.com/highcharts/highcharts/issues/16552

**Closed by raf18seb** 2021-11-02 12:07 UTC
