### ISSUE TITLE
Navigator series is not respecting disabled turboThreshold 

### ISSUE THREAD

**Issue by alvarezguille** [highcharts/highcharts#6058] opened 2016-11-30 13:53 UTC
#### Actual behaviour
If stock chart has lot of data defined as JSON object array and turboThreshold is disabled then navigator series is not rendered

#### Expected behaviour
Navigator series is rendered

#### Live demo with steps to reproduce

http://jsfiddle.net/alvarezg/q94nkykw/

**Comment by pawelfus** [comment] 2016-11-30 14:09
Hi @alvarezguille 

Thanks for reporting. It is a duplicate of #1905 - navigator series is a line series, and line series require `y`-values to be rendered (when using point-objects). When adding `y` value (which can be one of: open/high/low/close) it renders fine: http://jsfiddle.net/q94nkykw/1/ (the second workaround in #1905).

**Closed by pawelfus** 2016-11-30 14:09 UTC
Labels: Duplicate

**Comment by alvarezguille** [comment] 2016-12-01 09:42
Hi @pawelfus
Thanks for quick answer, now I understand what's happening.
Does this mean that when using array data by default it's always using 'open' value as 'y' because it's the second value in the point coordinates array?

**Comment by pawelfus** [comment] 2016-12-01 10:07
Yes, you are right :)
