### ISSUE TITLE
Angular & Highcharts

### ISSUE THREAD

**Issue by gidon-handler** [highcharts/highcharts#14299] opened 2020-10-04 08:37 UTC
While using Highcharts in our Angular project, The Angular cli (and webpack) complain that they prefer ES modules (mainly for tree shaking), as opposed to AMD or UMD modules. As I understand, Highcarts npm package is using the  UMD format and thus the issue. I later saw that Highcharts supports pure ES modules (without module bundlers) through CDN, so the Highcarts library is already written in ESM format.

Is there a way to use the ESM format (also known as harmony in webpack) when importing from npm,   and thus allowing Angular and webpack to eliminate dead code (and not warning).  

Thank you
Gidon @ HP

**Comment by pawelfus** [comment] 2020-10-05 08:36
Hi @gidon-handler 

Thanks for choosing Highcharts! We are working on that, see progress in #12738 

For an example, see this: https://github.com/highcharts/highcharts/issues/8667#issuecomment-660951981

Closing as duplicate of #12738

**Closed by pawelfus** 2020-10-05 08:36 UTC
