### ISSUE TITLE
Legend Items with proximate layout

### ISSUE THREAD

**Issue by Sdavletshina** [highcharts/highcharts#16265] opened 2021-08-27 16:58 UTC
#### Expected behaviour

 When proximate, the legend items should be placed as close as possible to the graphs they're representing

#### Actual behaviour

Proximate legend layout doesn't work as expected under these three conditions:
1. Styled mode should be ON
2.  Some legend labels should be multiline
3. Last data points should be close to each other

#### Live demo with steps to reproduce

1. Open the example https://jsfiddle.net/hjvod7bc/
2. Notice `styledMode` is `true`, legend `layout` is `proximate` and `width` is set to `30%` to ensure multiline labels
3. In this example series are ordered by last data point for demonstrating purposes, usually data doesn't come that way. 
4. Legend labels **expected** to come in the following order (if reading from top to bottom) - **`[Installation, Manufacturing, Sales & Distribution, Project Development, Other]`** however result is `[Sales & Distribution, Project Development, Installation, Manufacturing, Other]`.
5. If you remove `30% width setting` labels will order the right way. 

Please see a [visual](https://i.stack.imgur.com/Fe5IU.png) for more clarity.
[Link](https://stackoverflow.com/questions/68911148/legend-order-for-proximate-layout/68935950) to stackoverflow question.
Appreciate If someone can give a temp workaround. Thank you! 

#### Product version
Highcharts v9.2.2

#### Affected browser(s)
Chrome Version 92.0.4515.159 (Official Build) (x86_64)
Firefox 91.0.1
Safari Version 14.1.2 (14611.3.10.1.5)

**Comment by raf18seb** [comment] 2021-08-31 11:17
Hi @Sdavletshina,

I am not sure which of your 5 listed things are issues and which are just steps helping reproduce the issues.
I found one issue (number 4.) about the legend items order. This is intended behavior. If you want to disable it, please use this plugin:
```js
(function(H) {
  var {
    distribute,
    find,
    isNumber
  } = H;

  H.Legend.prototype.proximatePositions = function() {
    var chart = this.chart,
      boxes = [],
      alignLeft = this.options.align === 'left';
    this.allItems.forEach(function(item) {
      var lastPoint,
        height,
        useFirstPoint = alignLeft,
        target,
        top;
      if (item.yAxis) {
        if (item.xAxis.options.reversed) {
          useFirstPoint = !useFirstPoint;
        }
        if (item.points) {
          lastPoint = find(useFirstPoint ?
            item.points :
            item.points.slice(0).reverse(),
            function(item) {
              return isNumber(item.plotY);
            });
        }
        height = this.itemMarginTop +
          item.legendItem.getBBox().height +
          this.itemMarginBottom;
        top = item.yAxis.top - chart.plotTop;

        if (item.visible) {
          target = lastPoint ? lastPoint.plotY : item.yAxis.height;
          //target += top - 0.3 * height;
          target += top;
        } else {
          target = top + item.yAxis.height;
        }

        boxes.push({
          target: target,
          size: height,
          item: item
        });
      }
    }, this);

    distribute(boxes, chart.plotHeight).forEach(function(box) {
      if (box.item._legendItemPos) {
        box.item._legendItemPos[1] =
          chart.plotTop - chart.spacing[0] + box.pos;
      }
    });
  };
})(Highcharts)
```

Demo: https://jsfiddle.net/BlackLabel/drymwavg/

Is there any other issue bothering you?

**Comment by Sdavletshina** [comment] 2021-08-31 18:38
Thank you Rafat for your reply!
 
I  see it perfectly works in the demo, however when I wrap highcharts with a proposed solution, the result of the `distribute` function `distribute(boxes, chart.plotHeight)` is undefined for me.  I cannot reproduce error in the demo and don't see why that would work differently for me since the change has been applied to the `target` variable only, right? So I wanted to know if you can help me to find the case when the `distribute` function call can return undefined. Thank you!
<img width="1411" alt="Screen Shot 2021-08-31 at 2 36 48 PM" src="https://user-images.githubusercontent.com/34147944/131557820-193aa780-63c7-4a8c-a28f-a6a47d9e51a4.png">
<img width="796" alt="Screen Shot 2021-08-31 at 2 37 07 PM" src="https://user-images.githubusercontent.com/34147944/131557821-fa2c53ea-f90a-4b07-bf3d-c49ec061b511.png">
?

**Comment by raf18seb** [comment] 2021-09-01 09:27
@Sdavletshina,

>  I cannot reproduce error in the demo and don't see why that would work differently for me since the change has been applied to the target variable only, right?
Yes, only the `target` variable has been changed, so it's strange you're getting an error. Maybe the `distribute` method I assigned to a variable from `Highcharts.distribute` is changed somewhere on the fly.

Are you able to reproduce your issue in a live demo?

You can also defend yourself like this:
```js
(distribute(boxes, chart.plotHeight) || []).forEach(function(box) {
...
```
but we have no guarantee that the positions of the items will be correct. (it's hard to tell without seeing an error in a live demo and testing it)

**Comment by karolkolodziej** [comment] 2023-11-03 07:30
Closing due to inactivity

**Closed by karolkolodziej** 2023-11-03 07:30 UTC
Labels: Status: Pending reply, Type: Question
