### ISSUE TITLE
Boxplots: empty data point messes up showing of good data

### ISSUE THREAD

**Issue by wbazant** [highcharts/highcharts#7380] opened 2017-11-08 14:44 UTC
#### Expected behaviour

A chart with a boxplot shows up after passing an empty point for no boxplot, like in e.g. 
http://jsfiddle.net/munrx43m/1/

#### Actual behaviour
No boxplot, only sadness

#### Live demo with steps to reproduce
http://jsfiddle.net/munrx43m/

#### Affected browser(s)
Google Chrome

**Comment by pawelfus** [comment] 2017-11-09 11:45
Hi @wbazant 

It looks like the same issue as #4939 (just different default format: `null` vs `[]`). If you use solution mentioned in #4939 ticket, it will work fine: 
```
    data: [{
      x: 0,
      low: null,
      q1: null,
      median: null,
      q3: null,
      high: null
    }, {
      x: 1,
      low: 714,
      q1: 762,
      median: 817,
      q3: 870,
      high: 918
    }]
  }]
```
Demo: http://jsfiddle.net/munrx43m/2/

**Comment by TorsteinHonsi** [comment] 2017-11-15 08:04
Duplicate of #4939.

**Closed by TorsteinHonsi** 2017-11-15 08:04 UTC
