### ISSUE TITLE
Area chart is not shown correctly with boost module

### ISSUE THREAD

**Issue by am-username** [highcharts/highcharts#18284] opened 2023-01-12 08:55 UTC
#### Expected behaviour
![image](https://user-images.githubusercontent.com/122521250/212020959-0dfc4e13-b367-49ea-81e7-005614c93899.png)

#### Actual behaviour
Serie is displayed with opacity and is hardly visible. The same applies when zooming a chart
![image](https://user-images.githubusercontent.com/122521250/212021438-6d6154cb-e60e-4d5f-be5c-00b67bc8c79f.png)

#### Live demo with steps to reproduce
Just set true on line 183 to reproduce this

https://jsfiddle.net/8jyw4oe3/

#### Product version
9.1.2+
(not tried for previous versions)

#### Affected browser(s)
Chrome, FF, Edge

**Comment by bm64** [comment] 2023-01-12 09:39
Hello @am-username and thanks for reporting the issue.
Closing this ticket as a duplicate of #17854

**Closed by bm64** 2023-01-12 09:39 UTC
