### ISSUE TITLE
Dynamic chart type update display bug

### ISSUE THREAD

**Issue by Kamforka** [highcharts/highcharts#8507] opened 2018-06-21 09:19 UTC
#### Expected behaviour
A seamless change between Pie<->Bar<->Column<->Pie chart representations.

#### Actual behaviour
The display bugs when switching between representations. Pie->Column is partially working, Bar<->Column not working at all. 

#### Live demo with steps to reproduce
You can click on the buttons to change the chart type, unfortunately it breaks during the changes:
https://jsfiddle.net/tj04e5cs/5/

#### Product version
Highcharts - latest

#### Affected browser(s)
Tried on Chrome Version 66.0.3359.139 (Official Build) (32-bit)

**Comment by TorsteinHonsi** [comment] 2018-06-21 12:54
Duplicate of #8481.

It's fixed in the master, see https://jsfiddle.net/tj04e5cs/10/.

**Closed by TorsteinHonsi** 2018-06-21 12:54 UTC
Labels: Duplicate

**Comment by Kamforka** [comment] 2018-06-21 14:21
@TorsteinHonsi Thanks for the reply.

I can confirm that your fiddle works fine (except that the pie chart keeps the line of the column charts x axis, and the Values title of the y axis).

Way better than it was, so still very much appreciate your efforts!

**Comment by Kamforka** [comment] 2018-06-25 06:47
@TorsteinHonsi Is it possible that the npm [package](https://www.npmjs.com/package/highcharts) is not using the most up to date version from master? 

Asking it because, I'm using highcharts within Angular, and a wrapper around it called [angular-highcharts](https://www.npmjs.com/package/angular-highcharts) and no matter if I install the most up to date version of both, I still experience the buggy behavior.

Any thoughts?

**Comment by TorsteinHonsi** [comment] 2018-06-25 07:53
> Is it possible that the npm package is not using the most up to date version from master?

Yes, the npm package uses the latest official release, and the fix is not released yet.

**Comment by Kamforka** [comment] 2018-06-25 07:59
Is there a known release date for the upcoming fix?

**Comment by TorsteinHonsi** [comment] 2018-06-25 08:00
It should be released within to or three weeks.
