### ISSUE TITLE
Gantt chart missing x axis labels when changing the navigator selected period

### ISSUE THREAD

**Issue by AndriiMakar** [highcharts/highcharts#16118] opened 2021-07-29 15:53 UTC
#### Expected behavior
When changing the navigator selected period the month number labels need to fit the space, maybe change the font size.

#### Actual behavior
Month number labels are not shown or completely disappear.

#### Live demo with steps to reproduce
https://jsfiddle.net/as42reb1/
Try changing the navigator selected period
![1](https://user-images.githubusercontent.com/11467328/127524347-9e05941d-fdc0-4aa5-b4bb-f8ee8ab2b3e0.png)
![2](https://user-images.githubusercontent.com/11467328/127524430-a7d479ac-7eb7-4855-a7ad-6bdb27cc41d1.png)
![3](https://user-images.githubusercontent.com/11467328/127524524-2e6abf9f-f845-477d-b35c-e5d2645f8e15.png)

#### Product version
Highcharts Gantt JS v9.1.0

#### Affected browser(s)
Version 91.0.4472.106 (Official Build) (64-bit)

**Comment by raf18seb** [comment] 2021-07-30 15:04
Closing as a duplicate of https://github.com/highcharts/highcharts/issues/15720

**Closed by raf18seb** 2021-07-30 15:04 UTC
