### ISSUE TITLE
Highcharts Gantt - Plot tooltip missalign

### ISSUE THREAD

**Issue by rajasekar-pb** [highcharts/highcharts#18698] opened 2023-03-21 07:23 UTC
#### Expected behaviour
Tooltip to be placed with in the plot area

#### Actual behaviour
Tooltip is overlapping with the axis label, which looks broken

#### Live demo with steps to reproduce
https://jsfiddle.net/u5fgs4md/
Mouse over on the plot line 'Start prototype' and see the tooltip breaks

#### Product version
highcharts: 10.2.1
highcharts-angular: 3.0.0

#### Affected browser(s)
Google Chrome
Version 111.0.5563.65 (Official Build) (64-bit)

Firefox
Version 111.0 (64-bit)

**Comment by jakubjanuchta** [comment] 2023-03-21 11:00
Closing as a duplicate of #18435

**Closed** 2023-03-21 11:00 UTC
