### ISSUE TITLE
Zooming AreaRangeSeries demo multiple times keeps markers from previous zooms

### ISSUE THREAD

**Issue by GaryGen** [highcharts/highcharts#7644] opened 2018-01-10 15:26 UTC
#### Expected behaviour
Zooming AreaRangeSeries demo should erase markers from previous zoom.

#### Actual behaviour
Zooming AreaRangeSeries demo to a point where markers are visible and then zooming further leaves markers on screen from first zoom with markers.

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/arearange/
1. Zoom to display one month. Display should now include markers.
2. Zoom from there to display one week. Markers from previous zoom level are still displayed.
3. Note: Zooming further will keep additional markers, but shifting center of zoom will erase markers from most recent zoom (but keep leftover markers from original zoom).

#### Product version
Highcharts version currently referenced by demos as of January 10, 2018.

#### Affected browser(s)
Tested on Windows 10 64-bit, Chrome Version 64.0.3282.71 (Official Build) beta (64-bit)

**Comment by KacperMadej** [comment] 2018-01-10 15:32
Hi @GaryGen 

Thank you for reporting.
The problem is already resolved in next release candidate code version - demo: http://jsfiddle.net/BlackLabel/zz13y01j/

**Closed by KacperMadej** 2018-01-10 15:32 UTC

**Comment by GaryGen** [comment] 2018-01-10 21:16
Excellent, thanks!
