### ISSUE TITLE
legendItemClick event not working correctly with dual axis chart

### ISSUE THREAD

**Issue by IgorFIE** [highcharts/highcharts#13514] opened 2020-05-13 16:19 UTC
#### Expected behaviour
Given:
I have a chart with multi charts (different charts as series 1) column 2) spline).
And I override the event legendItemClick.

When:
I click on the second legend item.

Then:
My event legendItemClick should be called.

#### Actual behaviour
When we click on the second item legend item because it's a different chart type it doesn't call the event legendItemClick.

If I actually have both charts as the same it works.

#### Live demo with steps to reproduce
https://jsfiddle.net/panintelligence/2Luotk3v/3/

![highcharts_dual_axis_Legend_Item_click](https://user-images.githubusercontent.com/17085338/81838148-a743bf00-953d-11ea-91a1-61f51285f860.gif)

#### Product version
old versions and Latest version

**Comment by KacperMadej** [comment] 2020-05-13 17:02
Hi @IgorFIE 

Thank you for reporting about the problem.

You have set the event option in
```
plotOptions: {
      column: {
```

so this is only for `column` type series. If you want this to work for any series type use

```
plotOptions: {
      series: {
```

Demo: https://jsfiddle.net/BlackLabel/xg6rdv4m/

Closing as not a bug, but if you disagree please leave more info and the issue could be reopened.

**Closed by KacperMadej** 2020-05-13 17:02 UTC
