### ISSUE TITLE
allowPointSelect not working in Bubble Chart

### ISSUE THREAD

**Issue by sagargurtu** [highcharts/highcharts#6685] opened 2017-05-05 07:21 UTC
#### Expected behaviour
"allowPointSelect" should work correctly for Bubble Chart.

#### Actual behaviour
When "allowPointSelect" is set to true for Bubble Chart, selection effect is not seen when bubbles are clicked.

#### Live demo with steps to reproduce
http://jsfiddle.net/9jgw9pwm/

#### Affected browser(s)
Chrome

**Comment by stpoa** [comment] 2017-05-05 10:27
Also another example here:
http://jsfiddle.net/c2fj47gm/ - Does not work with 5.0.11
http://jsfiddle.net/c2fj47gm/1/ - Works with 5.0.10

**Comment by pawelfus** [comment] 2017-05-05 12:33
Thank you for the report!

It's a regression from https://github.com/highcharts/highcharts/commit/3cb21d3

**Comment by pawelfus** [comment] 2017-05-22 11:42
Already fixed on the master branch: http://jsfiddle.net/9jgw9pwm/1/

Closing as duplicate of #6705.

**Closed by pawelfus** 2017-05-22 11:42 UTC
Labels: Duplicate, Regression
