### ISSUE TITLE
Series color gradient not showing correct result on line chart having same data values

### ISSUE THREAD

**Issue by amruta30** [highcharts/highcharts#18538] opened 2023-02-20 13:33 UTC
#### Expected behaviour
All lines in line chart should show proper gradient effect ( linear gradient as per first color and second color). As per findings, line series having same data values is not showing the series color gradient.

#### Actual behaviour
Refer the JS fiddle. It is observed that linear gradient is applied correctly to the line 'Margin' series, whereas its not correctly applied to 'Profit' series.

#### Live demo with steps to reproduce
https://jsfiddle.net/amrutaJgtp/be10t2Ln/

#### Product version
v10.3.3

#### Affected browser(s)
All

**Comment by bm64** [comment] 2023-02-20 16:31
Closing as a duplicate of https://github.com/highcharts/highcharts/issues/1677. Related feature request https://github.com/highcharts/highcharts/issues/17029.

**Closed by bm64** 2023-02-20 16:31 UTC

**Comment by amruta30** [comment] 2025-01-09 04:39
Hi,
Please provide a solution for this issue.

**Comment by hubertkozik** [comment] 2025-01-09 08:21
Hi @amruta30! As my colleague said, this is a duplicate https://github.com/highcharts/highcharts/issues/1677 If needed, please continue the discussion there.
