### ISSUE TITLE
Drilldown and Up behaviour BROKEN in 5.0.0 (I wrote a fix)

### ISSUE THREAD

**Issue by avdaredevil** [highcharts/highcharts#5781] opened 2016-10-05 00:35 UTC
#### Expected behaviour
> Actually go up and down in Drill {up/down}, like it works in 4.2.5

#### Actual behaviour
>
- Drill down does not work!
  - `options of undefined` error in console
- Drill up does not work!
  - `type of undefined` error in console

#### Fix for it (_I debugged it to it's root_)
> ### Find it:
- If you pretty print `modules/drilldown.js` in Chrome Dev Tools:
   - Drill Down
      - Goto line *__123__*
      - `this.addSeries(a, !1)` returns `NULL` in `addSingleSeriesAsDrilldown` // Which is not the expected behavior
   - Drill Up
      - Goto line *__173__*
      - `b.addSeries(a, !1)` returns `NULL` in `q.prototype.drillUp` // Which is not the expected behavior

> ### FIX:
   - You could fix addSeries in `Highstock.js`
   - OR change the addSeries lines to do this:
     - **Drill Down**: `f = f.lowerSeries = (this.addSeries(a, !1),this.series.slice(-1)[0]);` on line *__123__*
     - **Drill Up**: `c = c || (b.addSeries(a, !1),b.series[0]);` on line *__173__*

#### Live demo with steps to reproduce
>
- Make a highchart using **Highstocks.js** as your base library, with _2 drillable column charts_
- Click any one of them
- On the drill down event, have the callback `addSeriesAsDrilldown` to add another sub column chart.
- At This point the first error should've thrown, and no sub chart would be visible.
- If you apply the aforementioned **Drill Down fix**, you should see the child view
- Now Drill up again
- At this point you should hit the Drill Up error
- Apply the fix and everything's A-OK! 

#### Affected browser(s)
> Chrome, though, it should be all of them

---
_**PS.** I manage the [highcharts-chart](https://github.com/avdaredevil/highcharts-chart) library_

**Comment by TorsteinHonsi** [comment] 2016-10-05 05:54
Thanks for writing!

This is a duplicate of #5764, fixed in master.

PS: For your convenience, it is much easier debugging on the source files, for example `highstock.src.js`.

**Comment by jon-a-nygaard** [comment] 2016-10-06 07:56
Closing this since it is a duplicate of #5764

**Closed by jon-a-nygaard** 2016-10-06 07:56 UTC
Labels: Duplicate
