### ISSUE TITLE
Tooltip does not display for bubble

### ISSUE THREAD

**Issue by elmoro666** [highcharts/highcharts#5867] opened 2016-10-24 13:51 UTC
#### Expected behaviour
Tooltip should display when hovering over bubble.

#### Actual behaviour
Tooltip only displays over line, not bubble. Note that this is only an issue in a mixed chart with both a line and bubble. Maybe this is related to issue #5831  ?

#### Live demo with steps to reproduce

https://jsfiddle.net/aqjq90be/

Replace with version 4.2.4 to see the difference in behaviour.

#### Affected browser(s)
tested in Chrome and Firefox

**Comment by oysteinmoseng** [comment] 2016-10-24 14:34
Throws errors in console using latest code from `master`: http://jsfiddle.net/aqjq90be/1/

**Comment by pawelfus** [comment] 2016-10-25 11:12
**Internal note:**

After fixing issue with radius (error in js), there will be different (original one is fixed on the master) issue (demo: http://jsfiddle.net/aqjq90be/6/ ): hover any point, then try to hover point in another series with the same `x`: point won't be highlighted and tooltip won't show up. It's caused by d228fa0 - not really helpful, though.

**Closed** 2016-10-26 13:10 UTC
Labels: Regression

**Comment by pawelfus** [comment] 2016-10-26 13:13
Issue with error is reported as #5887

When using workaround from #5887, then the bug is fixed in 5.0.1 version: https://jsfiddle.net/aqjq90be/7/ (the same behaviour as in 4.2.4). 

Do you agree @elmoro666 ?

**Comment by elmoro666** [comment] 2016-10-27 15:48
Agree! Thanks a lot


Thomas
