### ISSUE TITLE
Not possible to scroll site on mobile, when touching legend items.

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#9682] opened 2018-12-17 11:11 UTC
#### Expected behaviour

Site should be able to scroll when touching legend item, and legend item should be disabled only after touch end (as it is in the case of handling standard mouse events).

#### Actual behaviour

When touching the legend on mobile devices, and want to scroll down/up a site, it's `legendItemClick` default event called, just on start touch.

#### Live demo with steps to reproduce
[Official basic line demo](https://www.highcharts.com/demo/line-basic)
Try to swipe the screen on mobile, touching any legend item.

#### Affected browser(s)
Mobile Chrome v71.0.3578.98

**Comment by alexpazzo** [comment] 2019-07-25 13:14
Mee too, i need to know if this bug will be fixed.
Thx

**Comment by pawelfus** [comment] 2019-07-31 14:35
The easiest solution is to remove `preventDefault()` from on-click event, like this:
Demo: https://jsfiddle.net/BlackLabel/zhogy5vj/
```js
(function(H) {
  H.SVGElement.prototype.on = function(
    eventType,
    handler
  ) {
    var svgElement = this,
      element = svgElement.element;

    // touch
    if (H.hasTouch && eventType === 'click') {
      element.ontouchstart = function(e) {
        svgElement.touchEventFired = Date.now(); // #2269
        // e.preventDefault(); // removed
        handler.call(element, e);
      };
      element.onclick = function(e) {
        if (H.win.navigator.userAgent.indexOf('Android') === -1 ||
          Date.now() - (svgElement.touchEventFired || 0) > 1100) {
          handler.call(element, e);
        }
      };
    } else {
      // simplest possible event model for internal use
      (element)['on' + eventType] = handler;
    }
    return this;
  };
})(Highcharts);
```

I'm not sure the origin of this - seems to be there with us since 2011 :) Added in this commit 8fe1d4c9002474e8260d964224c9ba1060033bdc

**Comment by alexpazzo** [comment] 2019-08-01 08:21
It's working now! thanks you so much @pawelfus !!
Have a nice day!

**Comment by jarski** [comment] 2020-01-23 08:53
Hello. This issue is still 'Open' but based on the comments you have a fix for it. Is it so that the fix is not yet released?

**Comment by pawelfus** [comment] 2020-01-23 10:18
Yes, fix is not released. Fix must be first tested against regressions etc. Let us know if you find any issues with the workaround above.

**Comment by jarski** [comment] 2020-01-27 11:11
It seems the fix is not enough in our case. We have also a custom function on 'legendItemClick' and that is immediately called when user starts touching the item with or without the workaround here. That should be also disabled to let the user scroll. Similar behavior is in the demo jsfiddle above. The item is immediately hidden when user starts touching the legend.

**Closed** 2020-03-06 10:25 UTC
Labels: Product: Highcharts, Status: Pending review, Type: Bug
