### ISSUE TITLE
Broken Encoding in JS Maps

### ISSUE THREAD

**Issue by kcabel-vendavo** [highcharts/highcharts#20111] opened 2023-11-10 09:22 UTC
#### Expected behaviour
Javascript maps should have correct national characters in labels and names.

#### Actual behaviour
Source code from https://code.highcharts.com/mapdata/countries/cz/cz-all.js have broken characters.
For example there is a source name "St?edo?eskĂ˝" that should be "Středočeský" in Czech language.
Other countries are broken as well.

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/cz/cz-all

#### Product version
Latest

#### Affected browser(s)
All

**Comment by bm64** [comment] 2023-11-13 13:08
Hello @kcabel-vendavo and thanks for reporting the issue. 

It appears that the issue has already been reported and resolved. The fix should be included in the next release, which is scheduled for the coming weeks. For more information please see: https://github.com/highcharts/map-collection-dist/issues/118

Closing as a duplicate of https://github.com/highcharts/map-collection-dist/issues/118

**Closed by bm64** 2023-11-13 13:08 UTC
