### ISSUE TITLE
Can't remove yAxis

### ISSUE THREAD

**Issue by ibedek** [highcharts/highcharts#5411] opened 2016-06-17 11:33 UTC
When creating chart dynamically and assigning different yAxis to different series (eg you have 3 series which share same y-axis, and you want one of them to have unique y-axis, or, you have 3 series, each with its own y-axis and you want them to share one y-axis), it is not possible to remove yAxis which doesn't have series assigned/linked to. Noticed on v4.2.5

**Comment by TorsteinHonsi** [comment] 2016-06-20 12:05
Thank for reporting! I tried to set up a reproduction based on your description, but it seems to work well: http://jsfiddle.net/highcharts/5gks6dp5/. Can you do any modifications to this to demonstrate the problem?

**Comment by ibedek** [comment] 2016-06-21 07:48
I did some research.. It seems it's error on my end, since erase function in HC compares entire object before removal, and in my code, I first add new yAxis, then rebuilding title for it (title should contain name of each series axis is assigned to), assigning series to new axis and in the end, cleanup and redraw..
Every operation is without redraw (pretty big dataset and each point usually has additional properties)

**Comment by TorsteinHonsi** [comment] 2016-06-21 08:20
Can you show that in jsFiddle?

**Comment by jon-a-nygaard** [comment] 2016-07-22 07:45
Closing this issue since we are unable to reproduce, and it is pending a reply. Should anyone have further information on this issue, please comment and reopen.

**Closed by jon-a-nygaard** 2016-07-22 07:45 UTC
Labels: Cant reproduce, Pending reply
