### ISSUE TITLE
Pie chart animation fails with drilldown

### ISSUE THREAD

**Issue by emiltorlen** [highcharts/highcharts#6042] opened 2016-11-28 12:09 UTC
#### Expected behaviour
Animation freezes when drilling up/down in the chart. 
The pie slices gets stuck and is visible after animation is completed.

#### Actual behaviour
Pie slices should not sustain in the chart.

#### Live demo with steps to reproduce

http://www.highcharts.com/demo/pie-drilldown

Steps:
 1. Click "Microsoft Internet Explorer" slice
 2. Click button "Back to Brands"
 3. Click "Chrome" slice
 4. Pie slice "Microsoft Internet explorer is still visible in the background"

#### Affected browser(s)
Chrome: Version 54.0.2840.99 m
Internet Explorer: 11.0.9600.18098
Firefox: 43.0.1

### Other notes
If animation is disabled,
series.animation = false
this is not reproducible.
![image](https://cloud.githubusercontent.com/assets/5057918/20667866/dbabbb68-b56b-11e6-95b4-d03e3f7167af.png)

**Comment by henrikskar** [comment] 2016-11-28 12:33
Duplicate of #6023

**Closed by henrikskar** 2016-11-28 12:33 UTC
