### ISSUE TITLE
Issue with drilldown (ver 4.2.6)

### ISSUE THREAD

**Issue by hmalekar** [highcharts/highcharts#5629] opened 2016-08-27 11:02 UTC
Ver 4.2.6
1. Click on the first column, drills down fine.
2. Go Back
3. Click on the second column, shows addtional labels from the drilldown of the first column

**Change the Ver to 4.2.5 and it works as expected.**

#### Expected behaviour
Should drilldown as per configuration and show respective points only.

#### Actual behaviour
As mentioned above, clicking on the second column shows points from the previous drilldown(column 1)

#### Live demo with steps to reproduce
Ver 4.2.6
1. Click on the first column, drills down fine.
2. Go Back
3. Click on the second column, shows addtional labels from the drilldown of the first column
**Change the Ver to 4.2.5 and it works fine.**

[http://jsfiddle.net/46ku3muh/]

Trying changing the version of the scripts from 4.2.6 to 4.2.5 to see expected behaviour.

**Comment by sebastianbochan** [comment] 2016-08-29 08:00
The issue is already fixed in the master branch.

Demo:
   - http://jsfiddle.net/xLkn1wcq/

**Closed** 2016-08-29 08:00 UTC
