### ISSUE TITLE
Issue with x-Panning and data-grouping

### ISSUE THREAD

**Issue by maximenicot74** [highcharts/highcharts#3825] opened 2015-02-17 09:56 UTC
Hi there,

I'm observing a strange behavior when using x-panning in my charts.
When it is zoomed-out enough to trigger data-grouping, (for example, grouping data month by month) the x-panning don't behave as expected.
Drag-and-drop the chart from left to right change correctly the dates, but from right to left, the dates still changing day by day.

http://jsfiddle.net/906du3fz/1/

**Comment by KacperMadej** [comment] 2016-03-24 13:57
+1 

http://forum.highcharts.com/highstock-usage/issue-with-panning-datagrouping-and-value-in-data-t35216/

**Comment by TorsteinHonsi** [comment] 2016-03-29 10:57
I don't see any problems with the panning... Are there any more specific reproduction steps?

**Comment by pawelfus** [comment] 2016-03-29 11:14
Better demo: http://jsfiddle.net/xzr3k4bo/

Steps:

  1. Pan to the left: we have panning point-by-point.
  2. Pan to the right: we have panning, where first and last points are updated with new value 

Example:
![paning](https://cloud.githubusercontent.com/assets/1453926/14106221/15d5a230-f5b0-11e5-818f-aac9a1661eda.gif)

**Comment by maximenicot74** [comment] 2016-03-29 11:17
If you follow the link of my initial post, zoom out the chart until data are grouped month by month.
Then, when panning to the left, the problem happens.

**Comment by yournitin** [comment] 2019-01-08 15:03
any update on this issue? me too waiting for the fix.

**Comment by KacperMadej** [comment] 2019-01-08 22:35
Hi @yournitin 

The problem was resolved by adding [`groupAll`](https://api.highcharts.com/highstock/series.line.dataGrouping.groupAll) option.
Demo: http://jsfiddle.net/BlackLabel/bew10x54/

Closing as resolved since v6.1.0

**Comment by yournitin** [comment] 2019-01-09 05:13
Hi @KacperMadej 
The issue still persists. Below are the reproducible steps in Demo which you provided.
[http://jsfiddle.net/BlackLabel/bew10x54/](http://jsfiddle.net/BlackLabel/bew10x54/):

1) After page load, (while default 1y is selected) move navigator as it is to the center so that range (on x axis) appears approx Jan'13 to Jan'14.

2) Forget the navigator now. On graph, try to pan (move cursor while pressing mouse left click) from extreme left to right and note the speed or amount of data which is panned. You will note that range (on x axis) after panning will come to approx Jan'12 to Dec'12. Meaning data is panned by 1 year.

3) Now repeat same step above but from extreme right to left and note the speed or amount of data which is panned.  This time you will note that data is panned by hardly few days. Not even a month.

**Actual Result**: Theres is huge difference between amount of data panned in step 2 and step 3.
**Expected Result**:  Amount of data panned in step 2 and step 3 should be identical.

Please verify again.

**Comment by sebastianbochan** [comment] 2019-01-09 11:36
Im reoping the issue, because after setting the `groupAll` problem still appears.

**Comment by KacperMadej** [comment] 2019-01-09 13:37
Right, the problem is about speed of panning and not about grouped columns. My bad - surely this is not resolved.

**Comment by yournitin** [comment] 2019-01-09 15:35
sorry for being impatient but is there any timeframe in which I can expect the fix?

**Comment by KacperMadej** [comment] 2019-01-10 21:04
Unfortunately there's no ETA for the fix at this moment, but we'll be working on resolving the problem.

The problem is caused by ordinal axis panning logic, because when ordinal is set to `false` the chart works well: http://jsfiddle.net/BlackLabel/bew10x54/2/

As a workaround please set xAxis.oridnal to false.

**Comment by yournitin** [comment] 2019-01-11 15:45
Unfortunately **in my case**, problem persists even after setting xAxis.oridnal to false.
I could not create jsfiddle as my data file is huge (having around 250K records), therefore below are the glimpses of options and data:

data:
[
	[ 0, 14.9716796875 ],
	[ 0.0006380517818225158, 16.08984375 ],
	[ 0.0012761035636450317, 16.93359375 ],
	[ 0.0019141553454675476, 16.994140625 ],
	[ 0.0025522071272900634, 16.3154296875 ],
	.
	. <250K records>
	.
	[ 159.96532416918544, 0.1826171875 ],
	[ 159.96596222096727, 4.6826171875 ]
]

options:
{
  navigator: {
	enabled: true,
	xAxis: {
	  labels: {
		formatter: function () {
		  return this.value;
		}
	  }
	}
  },
  rangeSelector: {
	enabled: false,
	inputEnabled: false,
  },
  plotOptions: {
	series: {
	  dataLabels: {
		enabled: false
	  },
	  lineWidth: 1,
	  states: {
		hover: {
		  enabled: false
		}
	  },
	  dataGrouping: {
		smoothed: true,
		units: [
		  ['millisecond', [0.2]]
		]
	  }
	}
  },
  credits: {
	position: {
	  align: 'left',
	  x: 20
	},
  },
  yAxis: {
	title: {
	  text: ' yAxis '
	},
	gridLineWidth: 1,
	type: 'linear',
	crosshair: true
  },
  xAxis: {
	title: {
	  text: ' xAxis '
	},
	crosshair: true,
	pointStart: 0,
	labels: {
	  formatter: function () {
		return this.value;
	  }
	},
	allowDecimals: true,
	gridLineWidth: 1,
	ordinal: false
  },
  series: [
	{
	  data: data,
	  color: 'black',
	}
  ],
  chart: {
	zoomType: 'x',
	panKey: 'ctrl'
  }
}

**Comment by KacperMadej** [comment] 2019-01-13 23:02
I'm unable to recreate the problem - here's a smaller data set that works well: http://jsfiddle.net/BlackLabel/bew10x54/6/
Maybe I'm missing something - please try with the above demo after changing dummy data set size if you are able to recreate the problem there.

With big data it's better to use server side data grouping (a.k.a. [lazy loading](https://www.highcharts.com/blog/news/48-loading-millions-of-points-in-highcharts/)). I'm unable to create a demo with 250k points that will work smooth, but the limitations are caused by client side machine, so I'll check tomorrow using a more powerful computer. However, since I'll need to this shows that your current approach might not be the best for all cases.

**Comment by mateuszkornecki** [comment] 2020-02-05 08:06
+1

**Comment by pawelfus** [comment] 2021-01-20 16:59
*Internal note:*
This bug can be observed only with enabled `ordinal` and `dataGrouping`. When panning with these two, fake axis and series are created. Those are created on-demand to create available `ordinalPositions` (when for example data is cropped). Newly calculated positions are incorrect: while original xAxis holds grouped positions, fake axis contains ungrouped positions. This means when viewing monthly data, we pan to one of the sides with grouping by 1 day. That creates this effect of slow panning.

This happens to one side only, because when panning we keep the range (`fixedRange`). When we pan to the right side, we "add" one day to MAX (one day comes from the fake axis) and one month to MIN. When we pan to the left side, we "subtract" one month from MAX and one day from MIN (one day comes from the fake axis). And if the range was one year, but has changed (in comparison to `fixedRange`) we use MAX value as the reference to modify MIN here:

https://github.com/highcharts/highcharts/blob/1671b3875eea1385ea02df42d219f154212f760f/ts/Core/Axis/NavigatorAxis.ts#L123-L129

In a potential workaround, if `fixedMin` and `fixedMax` are defined, we can subtract from both values half of the change. However, this will hide the real culprit here: why the "fake" axis returns ungrouped positions. This:
```
Highcharts.charts[1].xAxis[0].ordinal.getExtendedPositions();
console.log(Highcharts.charts[1].xAxis[0].ordinal.index);
console.log(Highcharts.charts[1].xAxis[0].ordinal.positions);
```
Should have similar number of points (`ordinal.index` contains ungrouped points, while `positions` are fine). Demo: http://jsfiddle.net/BlackLabel/bew10x54/11/

**Comment by luu4** [comment] 2021-02-18 11:15
Hello, is there update on this issue?

**Comment by pawelfus** [comment] 2021-02-18 15:32
> Hello, is any update on this issue?

Hi @luu4, we plan to fix this issue in the upcoming weeks

**Comment by pawelfus** [comment] 2021-02-18 15:39
*Internal note:*
Test and fix should focus on this part: 
```
  Highcharts.charts[0].xAxis[0].ordinal.getExtendedPositions();
  console.log(Highcharts.charts[0].xAxis[0].ordinal.index);
  console.log(Highcharts.charts[0].xAxis[0].ordinal.positions);
```
`ordinal.index` returns always all, 1000+ points, unrelated to `ordinal.positions` (these are correct). Distance between two points in `ordinal.index` should be the same as used dataGrouping (e.g. 1month in the demo above)

**Comment by luu4** [comment] 2021-02-23 08:22
> 
> 
> > Hello, is any update on this issue?
> 
> Hi @luu4, we plan to fix this issue in the upcoming weeks

Thank you @pawelfus,
It looks, the issue is not solved couple of years (the artical was started in feb 2015), are you sure it will be repaired?

**Comment by pawelfus** [comment] 2021-02-23 11:20
Nothing changed in the last few days, we want to fix it in the next few weeks and make the fix available in v9.0.2. We don't know what exactly causes this bug, we have only some insights, so if anything changes we will let you know

**Comment by luu4** [comment] 2021-02-23 17:57
@pawelfus,
thank you for your response. 
We believe success,.

**Comment by pawelfus** [comment] 2021-03-10 13:18
Hi @luu4 

I bring some good news. We were able to pinpoint the issue and resolve it. If you would like to test it before we release it, check this demo: http://jsfiddle.net/BlackLabel/dqpxvan7/

You can also test this in your application using this Highcharts Stock script: http://github.highcharts.com/bugfix/3825-panning-data-grouping/highstock.js

Note: Don't use `github.highcharts.com` URL in the production env

**Comment by luu4** [comment] 2021-03-14 09:14
Hi @pawelfus,
thank you for the feedback and correction.
It looks that you will achieve the goal.
Unfortunately, I found out some issues:
-During scrolling in all zoom options with various scroll ranges...the chart is frozen sometimes and you can't pan to left or right.
-Some times I can not pan the chart to the end of the left.

**Comment by pawelfus** [comment] 2021-03-15 09:41
> During scrolling in all zoom options with various scroll ranges...the chart is frozen sometimes and you can't pan to left or right.

Thanks! We noticed this too, working on that 👍 

> Some times I can not pan the chart to the end of the left.

Nice catch! Thank you for reporting this!

**Comment by pawelfus** [comment] 2021-03-16 13:13
1) Fixed issue with the frozen ranges sometimes: http://jsfiddle.net/BlackLabel/dqpxvan7/5/ 

2) Panning to the left: Something is wrong here, but unrelated to this issue. Created separate ticket for that bug: https://github.com/highcharts/highcharts/issues/15331

**Closed** 2021-03-16 14:10 UTC
Labels: E: 13, Product: Highcharts Stock, Status: Review in progress, Type: Bug

**Comment by luu4** [comment] 2021-03-18 21:50
Hi @pawelfus,
it looks that works nice.
I found another problem, I will create new issue for it.
Thanks.
Luu
