### ISSUE TITLE
Downloaded SVG image is corrupted when accessibility.js script included

### ISSUE THREAD

**Issue by ressbill** [highcharts/highcharts#16836] opened 2021-12-28 15:17 UTC
#### Expected behaviour
Downloaded svg image opens successfully

#### Actual behaviour
When accessibility.js script is included then generated svg image contains an error and cannot be opened.
**Error msg:** This page contains the following errors:
error on line 1 at column 284: Extra content at the end of the document

#### Live demo with steps to reproduce
Reproduced on the official site:
https://www.highcharts.com/demo/bar-basic

Jsfiddle:
https://jsfiddle.net/9028bjxh/
#### Product version
latest v9.3.2 versions

**Comment by raf18seb** [comment] 2021-12-29 09:09
Closing as a duplicate of https://github.com/highcharts/highcharts/issues/16589

**Closed by raf18seb** 2021-12-29 09:09 UTC
