### ISSUE TITLE
Gradient on straight (horizontal) lines doesn't get plotted

### ISSUE THREAD

**Issue by inad9300** [highcharts/highcharts#5589] opened 2016-08-16 12:52 UTC
#### Expected behaviour
When plotting a straight line on a `'line'` type of chart, giving it a gradient as a color, the line should be plotted with the given options no matter the direction of the line.

#### Actual behaviour
If you give a gradient as a color, only the markers get plotted, but not the line. This works differently (as it should) for solid colors.

#### Live demo with steps to reproduce

Please find an example in http://jsfiddle.net/inad9300/ue5qhe9b/. The actual JSFiddle is showing the problem. It is interesting to see the behavior when the color property equals (e.g.) `'#AAA'`, and (separately) when the data property equals (e.g.) `[20, 20, 20, 21]`.

#### Affected browser(s)
All of them: Chrome, Firefox, Opera, Edge, IE 11.

**Comment by pawelfus** [comment] 2016-08-16 14:55
I think this is a problem with SVG, please take a look: http://jsfiddle.net/dgA9n/2/ - horizontal line is not rendered. 
I think this is duplicate of #1677

**Comment by inad9300** [comment] 2016-08-27 07:59
It seems so; and it seems to be a duplicate of #1677 indeed, sorry for that.

**Closed** 2016-10-17 11:53 UTC
Labels: Duplicate
