### ISSUE TITLE
Pyramid chart while using HighStock

### ISSUE THREAD

**Issue by naeemshaikh27** [highcharts/highcharts#6079] opened 2016-12-02 14:52 UTC
Hi,
I was trying to generate a pyramid chart which works fine when I use highcharts, but breaks in Highstock
I am using following scripts

> <script src="https://code.highcharts.com/stock/highstock.js"></script>
> <script src="https://code.highcharts.com/modules/funnel.js"></script>
> <script src="https://code.highcharts.com/modules/exporting.js"></script>

and code

> 
>     Highcharts.chart('container', {
>         chart: {
>             type: 'pyramid',
>             marginRight: 100
>         },
>         title: {
>             text: 'Sales pyramid',
>             x: -50
>         },
>         plotOptions: {
>             series: {
>                 dataLabels: {
>                     enabled: true,
>                     format: '<b>{point.name}</b> ({point.y:,.0f})',
>                     color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black',
>                     softConnector: true
>                 }
>             }
>         },
>         legend: {
>             enabled: false
>         },
>         series: [{
>             name: 'Unique users',
>             data: [
>                 ['Website visits',      15654],
>                 ['Downloads',            4064],
>                 ['Requested price list', 1987],
>                 ['Invoice sent',          976],
>                 ['Finalized',             846]
>             ]
>         }]
>     });

I cant hover or see the labels on chart when I use Highstocks-  http://jsfiddle.net/t6m8kLjc/
While it looks fine with Highcharts http://jsfiddle.net/gh/get/jquery/3.1.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/pyramid/

**Comment by pawelfus** [comment] 2016-12-02 15:12
Thanks for reporting!

Actually it's a duplicate of #5950

FYI @TorsteinHonsi

**Closed by pawelfus** 2016-12-02 15:12 UTC
