### ISSUE TITLE
Heatmap overlaps on labels after zooming

### ISSUE THREAD

**Issue by hotohoto** [highcharts/highcharts#7004] opened 2017-07-25 09:45 UTC
#### Expected behaviour
Zoomed heat map image should stay in the content container.

#### Actual behaviour
Zoomed heat map image overlaps on X label area.
![image](https://user-images.githubusercontent.com/5404902/28566178-57ab2ed8-7169-11e7-9125-0511f976bcbd.png)

#### Live demo with steps to reproduce

http://jsfiddle.net/hotohoto/r0310mp8/

#### Affected browser(s)
Version 59.0.3071.115 (Official Build) (64-bit) (Mac OS)

**Comment by sebastianbochan** [comment] 2017-07-25 10:23
Duplicate of https://github.com/highcharts/highcharts/issues/6594

**Closed by sebastianbochan** 2017-07-25 10:23 UTC
