### ISSUE TITLE
Scatter plot with 5000 points is displayed as blank

### ISSUE THREAD

**Issue by vinuthakaranth** [highcharts/highcharts#19118] opened 2023-06-08 00:13 UTC
#### Expected behaviour
Scatter plot with 5000 rows should be displayed properly.

#### Actual behaviour
Scatter plot with 5000 points is displayed as blank
![image](https://github.com/highcharts/highcharts/assets/33799331/d29f6784-589e-491d-918e-57bc5a6a9691)

#### Live demo with steps to reproduce

I am not able to provide code pen because of big data with 5000 points. I am getting below codepen error.
_This Pen is larger than the 1 megabyte limit. Try removing data from this Pen and trying again._

I will share the repro steps:
1. open scatter plot in codepen - https://www.highcharts.com/demo/scatter
2. replace js script with the code attached in file jsscript5000Points.txt.
3. run the code
[jsscript5000Points.txt](https://github.com/highcharts/highcharts/files/11682813/jsscript5000Points.txt)

Script with 970+ points is displayed properly.
[jsscript970Points.txt](https://github.com/highcharts/highcharts/files/11682811/jsscript970Points.txt)

![image](https://github.com/highcharts/highcharts/assets/33799331/09eac520-61f9-418a-be64-17205f76f52c)

#### Product version

   "highcharts": "^10.1.0"

#### Affected browser(s)
Microsoft Edge
Google Chrome

**Comment by bm64** [comment] 2023-06-08 09:45
Hello @vinuthakaranth

I've tried to recreate the issue using the demo from our page and your provided data. Everything seems to be working correctly on my end: https://jsfiddle.net/BlackLabel/co3k5n2y/

Could you please provide more details or steps on how to reproduce this issue?

**Comment by vinuthakaranth** [comment] 2023-06-08 16:20
@bm64 looks like you used txt file with 970+ points. Please use [jsscript5000Points.txt](https://github.com/highcharts/highcharts/files/11682813/jsscript5000Points.txt) file attached.

**Comment by vinuthakaranth** [comment] 2023-06-13 18:23
@bm64 Thanks for the workaround, it works! A warning would definitely help in identifying the issue.

**Comment by MarkusBarstad** [comment] 2023-07-04 11:46
Hey guys, trying to replicate this, I still receive warning #12

**Steps i took attempting to replicate**:
- Opened the scatter-plot demo (but in jsfiddle)
- Switched the js for the code found int he 5k points text file, as per described by the user
- fiddle can be found [here](https://jsfiddle.net/p6gdsx1a/1/) (warning: it can be a bit laggy since it has a lot of stuff)

Could this be codepen-related?

**Comment by bm64** [comment] 2023-07-07 01:07
Hi @MarkusBarstad! You're right. I likely had warnings disabled in dev tools during my testing. The error does indeed show up, so we can go ahead and close this issue. Thanks for verifying it.

**Closed by bm64** 2023-07-07 01:07 UTC
Labels: Product: Highcharts, Type: Regression, Type: Good for beginners
