### ISSUE TITLE
Highmaps - plotOptions.series.point.events - returning false does not prevent default action

### ISSUE THREAD

**Issue by cristiancalara** [highcharts/highcharts#5032] opened 2016-02-11 20:03 UTC
Returning false in the events handlers in plotOptions.series.point.events doesn't prevent the initial action. Looking into this, I think the issue is found in _fireEvent_ method in highmaps.src.js. More exactly at line 1295, where _defaultPrevented_ is set to _true_.

From what I can see on https://developer.mozilla.org/en-US/docs/Web/API/Event the _defaultPrevented_ property is read-only, so setting it to true has no effect.

**Comment by TorsteinHonsi** [comment] 2016-02-12 09:42
Thanks for reporting! I think what happens on [that line](https://github.com/highcharts/highcharts/blob/v4.2.3/js/parts/Utilities.js#L1169) only applies to non-DOM events, so it may not necessarily be where it goes wrong.

@oysteinmoseng Check if this applies also to a vanilla Highcharts chart. It may be an old bug from the Standalone Framework, that surfaced after we removed adapters.

**Comment by oysteinmoseng** [comment] 2016-04-13 08:35
Duplicate of #5112

**Closed by oysteinmoseng** 2016-04-13 08:35 UTC
Labels: Duplicate
