### ISSUE TITLE
Stock chart zoom issue with ordinal true and flags series

### ISSUE THREAD

**Issue by magdalena-gut** [highcharts/highcharts#16912] opened 2022-01-24 11:07 UTC
#### Expected behaviour
Zooming the chart should show the relevant range of data.

Working v9.1.1 demo: https://jsfiddle.net/BlackLabel/b2fgka1r/

#### Actual behaviour
Manual zooming cause data range to jump to the unexpected range.
- If we remove the flag series completely there is no issue.
- If we leave the flag series and set the xAxis ordinal to false, there is no issue except for the gaps from weekends/holidays.

#### Live demo with steps to reproduce
Select manually a range Jan 26, 2020 - Oct 26, 2020, and next Jul 1, 2020 - Sept 1, 2020. It jumps to Jan 2022.
Select above data using buttons - it seems to works correctly with setExtremes.

v9.1.2 Demo: 
https://jsfiddle.net/BlackLabel/e2wyLt8c/

Bisected to https://github.com/highcharts/highcharts/commit/9ea0e0b875add19c4d223200ff27d340dca73715

#### Product version
v9.1.2

#### Affected browser(s)
N/A

**Comment by pawelfus** [comment] 2022-03-11 15:29
@magdalena-gut could you update the demo with the relevant dataset?

> Select manually a range Jan 26, 2020 - Oct 26, 2020, and next Jul 1, 2020 - Sept 1, 2020.

By manually, do you mean RangeSelector or Navigator?

Thanks!

**Comment by AleNegrini** [comment] 2022-04-05 12:44
Hi @pawelfus,
the issue seems affecting also the version `10.0.0`. 

**Live demo with steps to reproduce**
1. Select the period **Apr 2021, 1st** to **Sept 2021, 1st** by using the **navigator** or the **range selector** (in the top right corner)
2. Select the period **Jun 2021, 1st** to **Jun 2021, 15th** by selecting the area directly in the chart.
3. You'll see the zoom period selected is wrong and it is from **Sep 2021, 20th** to **Sep 2021, 30th**

v10.0.0 Demo:
[https://jsfiddle.net/6w5q39a7/13/](https://jsfiddle.net/6w5q39a7/13/)

Product version
v10.0.0

Affected browser(s)
I spot it in Chrome

**Comment by karolkolodziej** [comment] 2022-04-05 13:49
Thank you for contacting us and providing this demo and steps to recreate it.
Closing as a duplicate of: https://github.com/highcharts/highcharts/issues/17128

**Closed by karolkolodziej** 2022-04-05 13:49 UTC
Labels: Product: Highcharts Stock, Type: Regression
