### ISSUE TITLE
Crosshair intersect x & y values on multiple series did not display simultaneously

### ISSUE THREAD

**Issue by Juniuz** [highcharts/highcharts#6728] opened 2017-05-15 23:00 UTC
**Expected Behaviour**
![multipleseries_crosshair](https://cloud.githubusercontent.com/assets/4703222/26082794/dad56862-3a25-11e7-8570-b845f93813b4.png)

Is there an easy way to interpolate the x and y values on a multiple series simultaneously?

**Actual Behavior**
Based on the screenshot above; the x and y values did not simultaneously display of where the crosshair line intersects on a multiple line series.

**Live demos**
I have posted a [fiddle](http://jsfiddle.net/uj0dnwmt/9/) to show what I want to achieve.

**Comment by pawelfus** [comment] 2017-05-16 10:14
Let me close this issue as duplicate of #4686 (it's still open).

**Closed by pawelfus** 2017-05-16 10:14 UTC
