### ISSUE TITLE
Labels show numbers instead string after drilldown

### ISSUE THREAD

**Issue by balkarov** [highcharts/highcharts#9125] opened 2018-10-04 11:26 UTC
Labels show numbers instead string after drilldown

![default](https://user-images.githubusercontent.com/6030335/46471067-74720a80-c7e1-11e8-9509-e31f4a5b2564.PNG)

#### Expected behaviour
Show normal names

#### Actual behaviour
Show some numbers

#### Live demo with steps to reproduce
https://jsfiddle.net/3eoq4prv/

#### Product version
Highcharts version 6.1.4

#### Affected browser(s)
Chrome 69.0.3497.100

**Comment by pawelfus** [comment] 2018-10-04 12:09
Hi @balkarov 

Thanks! It's a bug related to `cropThreshold` option. Please increase this value and everything will work fine: https://jsfiddle.net/BlackLabel/3eoq4prv/1/

Closing as duplicate of #5857

**Closed by pawelfus** 2018-10-04 12:09 UTC
