### ISSUE TITLE
Graph data is copied by reference, not cloned

### ISSUE THREAD

**Issue by quasipickle** [highcharts/highcharts#8015] opened 2018-03-14 14:46 UTC
#### Expected behaviour
When creating a chart, the series data becomes a separate copy of what was passed.

#### Actual behaviour
The data is not deep-copied and maintains a reference to passed objects

[The documentiation](https://api.highcharts.com/class-reference/Highcharts.Series.html#.data) states series data is read-only.  However, if I pass in an array of objects, say `temps`, as series data in the chart initialization object, those objects are passed by reference.  Subsequent calls to `series.setData()` will update my original `temps` array.

I'm not sure if this is expected behaviour that isn't documented the way I think it should, or if this is an actual bug.  I'd guess the former, but if it's the latter I can create an example test case if necessary.

**Comment by pawelfus** [comment] 2018-03-14 15:47
Hi @quasipickle 

Thank you for reporting the issue. It's a duplicate of #4259 - see discussion there.

**Closed by pawelfus** 2018-03-14 15:47 UTC
