### ISSUE TITLE
categoryInCategory: Highcharts is not defined

### ISSUE THREAD

**Issue by shashank1010** [highcharts/highcharts#13722] opened 2020-06-15 16:38 UTC
#### Expected behaviour
categoryInCategory should work when highcharts is called as a module instead of loading it with a script tag

#### Actual behaviour
ERROR ReferenceError: Highcharts is not defined
    at e.adjustForMissingColumns (highcharts.src.js:37159)
    at eval (highcharts.src.js:37260)
    at Array.forEach (<anonymous>)
    at e.translate (highcharts.src.js:37220)
    at eval (highcharts.src.js:26579)
    at Array.forEach (<anonymous>)
    at C.renderSeries (highcharts.src.js:26578)
    at C.render (highcharts.src.js:26685)
    at C.firstRender (highcharts.src.js:26891)
    at C.eval (highcharts.src.js:25296)

#### Live demo with steps to reproduce
https://stackblitz.com/edit/highcharts-centerincategory

#### Product version
8.1.1

#### Affected browser(s)
All browsers when Highcharts has been added by npm.
using **require('highcharts')** or **import * as Highcharts from 'highcharts'**

**Comment by sebastianbochan** [comment] 2020-06-16 07:59
Hi @shashank1010,
Thank you for reporting. The issue has been already reported and fixed on the master branch.

Im closing the ticket as duplicate of https://github.com/highcharts/highcharts/issues/13710

**Comment by shashank1010** [comment] 2020-06-19 14:03
@sebastianbochan  The issue still exists in the above usecase.
Please have a look. I have updated the Highcharts dependency in the demo.

@raf18seb Request you to follow this if you can.

**Comment by raf18seb** [comment] 2020-06-19 14:27
@[shashank1010](https://github.com/shashank1010) we are aware of it, it is already being handled. This is a duplicate of #13710, please subscribe and follow in there so we can keep all the comments in one issue.

**Comment by goransle** [comment] 2020-06-30 13:57
@shashank1010 A fix is now on the way. In the mean time, here is a workaround if you prefer not to use 8.1.0:

```js
// Workaround for https://github.com/highcharts/highcharts/issues/13722
(function(H) {
  H.seriesTypes.column.prototype.adjustForMissingColumns = function(
    x,
    pointWidth,
    point,
    metrics
  ) {
    var _this = this;
    var stacking = this.options.stacking;
    if (!point.isNull && metrics.columnCount > 1) {
      var indexInCategory_1 = 0;
      var totalInCategory_1 = 0;

      H.objectEach(this.yAxis.stacking && this.yAxis.stacking.stacks, function(
        stack
      ) {
        if (typeof point.x === "number") {
          var stackItem = stack[point.x.toString()];
          if (stackItem) {
            var pointValues = stackItem.points[_this.index],
              total = stackItem.total;
            if (stacking) {
              if (pointValues) {
                indexInCategory_1 = totalInCategory_1;
              }
              if (stackItem.hasValidPoints) {
                totalInCategory_1++;
              }
            } else if (H.isArray(pointValues)) {
              indexInCategory_1 = pointValues[1];
              totalInCategory_1 = total || 0;
            }
          }
        }
      });
      var boxWidth = (totalInCategory_1 - 1) * metrics.paddedWidth + pointWidth;
      x =
        (point.plotX || 0) +
        boxWidth / 2 -
        pointWidth -
        indexInCategory_1 * metrics.paddedWidth;
    }
    return x;
  };
})(Highcharts);
```
[Workaround applied on stackblitz](https://stackblitz.com/edit/highcharts-centerincategory-88z2b1)

**Closed** 2020-07-01 10:15 UTC
