### ISSUE TITLE
Data label been cut off for funnel chart

### ISSUE THREAD

**Issue by hitlcy** [highcharts/highcharts#6228] opened 2017-01-11 00:31 UTC
draw a funnel chart in a container with height and width specified. 
#### Expected behaviour
chart should auto resize and fit the data labels within the container. 

#### Actual behaviour
data labels has been cut off. 

#### Live demo with steps to reproduce

https://jsfiddle.net/hitlcy/Lfd8m016/4/

**Comment by TorsteinHonsi** [comment] 2017-01-11 08:23
Currently Highcharts has no automatic way of fitting the funnel data labels into the box, so you have to make sure that either the chart width is great enough, the funnel is positioned to the side, or the data labels are short or wrapped.

**Comment by KacperMadej** [comment] 2018-05-24 14:14
In general this is a duplicate of #2564 so closing in favor of that issue.

**Closed by KacperMadej** 2018-05-24 14:14 UTC
Labels: Enhancement
