### ISSUE TITLE
Histogram- unable to properly format the axis

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#14330] opened 2020-10-09 08:29 UTC
#### Expected behaviour
Being able to format the whole axis.

#### Actual behaviour
1. After setting the `tickInterval` it applies only for the first column. Other formating properties also don't work correctly.
The possible explanation of that behaviour is that the axis max is equal to the second column `x` value (coordinate of the left border of that column) and ticks won't apply to the area over the max.
2. After adding the `max` property, the ticks apply to the second column, but some extra space is generated on the right.
#### Live demo with steps to reproduce
1. https://jsfiddle.net/BlackLabel/kbL412ew/
2. https://jsfiddle.net/BlackLabel/58kerzs1/

#### Product version
Highcharts JS v8.2.0

#### Affected browser(s)
All

**Comment by pawelfus** [comment] 2020-10-12 08:27
Duplicate of #12933 - closing this issue

**Closed by pawelfus** 2020-10-12 08:27 UTC
Labels: Product: Highcharts, Type: Bug
