### ISSUE TITLE
Highmaps : Mouse wheel zoom not working on v9.2.2

### ISSUE THREAD

**Issue by amruta1eq** [highcharts/highcharts#16335] opened 2021-09-14 03:23 UTC
#### Expected behaviour
Mouse wheel zoom should work on Highmaps.

#### Actual behaviour
It is observed that on v9.2.2, mouse wheel zoom does not work on Highmaps.

#### Live demo with steps to reproduce
v8.2.2 : https://jsfiddle.net/7uecsxLp/ and v9.2.2 : https://jsfiddle.net/7uecsxLp/1

#### Product version
v9.2.2

#### Affected browser(s)
All

**Comment by KacperMadej** [comment] 2021-09-15 08:57
Duplicate of https://github.com/highcharts/highcharts/issues/15656

**Closed by KacperMadej** 2021-09-15 08:57 UTC
