### ISSUE TITLE
Some bars disappear if scrollable plot area is enabled

### ISSUE THREAD

**Issue by kamilkulig** [highcharts/highcharts#10763] opened 2019-05-20 07:19 UTC
#### Expected behaviour
All bars should be visible: https://jsfiddle.net/BlackLabel/obgjndta/

#### Actual behaviour
Some bars are missing event though chart's container is 200px higher. It happens only if scrollable plot area is enabled.
![image](https://user-images.githubusercontent.com/13188589/58002973-082de800-7ae0-11e9-915b-ad0caed9921e.png)

#### Live demo
https://jsfiddle.net/BlackLabel/87ojrLfq/

#### Product version
v7.1.1

**Comment by sebastianbochan** [comment] 2019-05-20 08:26
Hi @kamilkulig 
You should set [cropThreshold](https://api.highcharts.com/highcharts/series.column.cropThreshold) parameter.

Demo:
- https://jsfiddle.net/BlackLabel/y6jcwgv1/

Duplicate of #7688

**Closed by sebastianbochan** 2019-05-20 08:26 UTC

**Comment by kamilkulig** [comment] 2019-05-20 09:59
Some bars are still not visible in your demo: 
![image](https://user-images.githubusercontent.com/13188589/58013298-a167f900-7af6-11e9-8fe5-142f432041ff.png)
