### ISSUE TITLE
Black tooltip marker when useHTML is true

### ISSUE THREAD

**Issue by h11a** [highcharts/highcharts#16792] opened 2021-12-15 14:17 UTC
#### Expected behaviour
When i use the following code to draw a chart with a pattern I get a black marker in the tooltip.

```
Highcharts.chart('container', {
    series: [{
    	type: 'column',
        data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6],
       "color": {
                "pattern": {
                    "color": "red",
                    "backgroundColor": "pink",
                    "path": {
                        "d": "M 0 0 L 10 10 M 9 -1 L 11 1 M -1 9 L 1 11",
                        "strokeWidth": 1
                    },
                    "width": 10,
                    "height": 10,
                    "opacity": 1
                }
            },
    }],
    
  "tooltip": {
        "shared": true,
        "useHTML": true,
        "valueDecimals": 2
    },
});

```
![image](https://user-images.githubusercontent.com/52792193/146202053-673e667d-2118-4757-a56f-82ac8b1d3611.png)

If I set the useHTML to false it then works properly.

![image](https://user-images.githubusercontent.com/52792193/146202237-3fa40f0d-f97d-4373-ae3f-4393170069c1.png)

I need useHTML as my tooltips on certain charts are dynamic.... is this a bug in highcharts or is there something wrong with my json?

#### Actual behaviour
see above

#### Live demo with steps to reproduce
Please see the live demo here: https://jsfiddle.net/fgh11/adwyhuc4/1/

#### Product version
Highcharts JS v9.3.2 (2021-11-29)

#### Affected browser(s)
chrome

**Comment by raf18seb** [comment] 2021-12-16 13:06
Hi @h11a, thank you for contacting us with your issue!

The SVG pattern works only for SVG elements. If you set `tooltip.useHTML: true`, the tooltip will be rendered as an HTML element and the SVG pattern fill will no longer be supported.

You can color your tooltip symbols manually using e.g. `tooltip.formatter`, see demo: https://jsfiddle.net/BlackLabel/L0mbewhj/
API Reference: https://api.highcharts.com/highcharts/tooltip.formatter

Please, let me know if you have any further questions or the ticket can be closed.

**Comment by h11a** [comment] 2021-12-16 14:43
Hi @raf18seb 

Thanks for the fast response. I had a go at modifying the tooltip formatter to print the svg and as you said the fill no longer works :(

```
  "tooltip": {
    //"shared": true,
    "useHTML": true,
    "valueDecimals": 2,
    formatter: function() {
      const point = this.point,
        series = this.point.series;
        console.log(this.point);
        
    const pattern = '<svg fill="red" stroke="pink" stroke-width="3" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">\n' +
            '  <path d="' + this.point.series.color.pattern.path.d + '"' + '</svg><span>lkjh</span>';
            
            console.log(pattern);

      return  pattern;
    }
  },
```

I dont know a lot about svgs but I am interested in understand why the fill disappears. I have seen examples of fill working online, is it getting overriden by something else in the tooltip?

For example the following works correctly:
```
  "tooltip": {
    //"shared": true,
    "useHTML": true,
    "valueDecimals": 2,
    formatter: function() {
      const point = this.point,
        series = this.point.series;

          const pattern = '<svg height="100" width="100">\n' +
            '  <circle cx="50" cy="50" r="40" stroke="black" stroke-width="3" fill="red" />\n' +
            '  Sorry, your browser does not support inline SVG.  \n' +
            '</svg> ';
            return pattern;
    }
  },
```

![image](https://user-images.githubusercontent.com/52792193/146392631-3628d3e6-f6f3-460d-936b-bf379db81798.png)


Thanks

**Comment by raf18seb** [comment] 2021-12-20 15:14
Hi @h11a, here is a working demo of SVG with a pattern fill in the tooltip with `useHTML: true` flag: https://jsfiddle.net/BlackLabel/a3snw7ec/

However, it will never be added to the Highcharts' core because it's still SVG, and the idea of `tooltip.useHTML: true` is to display the tooltip **without** any SVG elements.
Of course, with `tooltip.useHTML: false` it's working fine.

**Comment by raf18seb** [comment] 2022-01-12 12:42
Hi @h11a,

You can find a specific series in `this.series`, see demo: https://jsfiddle.net/BlackLabel/nfc29vzw/
```js
formatter: function() {
      const legendSymbol = this.series.legendSymbol.renderer.defIds[this.series.index];
      const pattern =
        '<svg height="10" width="13">' +
        '  <text x="0"  y="10" style="font-size:16px;">' +
        '    <tspan height="40" width="80">' +
        '      <tspan style="fill:url(#' + legendSymbol + ')">\u25CF</tspan>' +
        '    </tspan>' +
        '  </text>' +
        '</svg>';
      return pattern;
    }
```

**Comment by raf18seb** [comment] 2022-01-12 12:44
As your questions are more support-related now, and this ticket is not a bug or feature request, I'm closing it here on GitHub.
In case of any further support needed, please contact us on one of our dedicated support channels.
More info: https://support.highcharts.com/

Happy New Year!

**Closed by raf18seb** 2022-01-12 12:44 UTC
Labels: Status: Pending reply, Type: Not a bug

**Comment by h11a** [comment] 2022-01-12 15:35
Thanks for all the help @raf18seb.  I got the behavior I was looking for working!
