### ISSUE TITLE
DrillDown 

### ISSUE THREAD

**Issue by mjnasir** [highcharts/highcharts#6679] opened 2017-05-04 13:51 UTC
#### Expected behaviour
It should work as it used to work in previos versions like you can drilldown after drilling up

#### Actual behaviour

DrillDown works once. Upon drilling up its not working with clicking on e.g clicking on column

**Comment by sebastianbochan** [comment] 2017-05-08 12:05
I run the scenario:
1. Demo: http://jsfiddle.net/ghgp4a7a/
2. Click on a column
3. Click Back button
4. I am still able to click on a column / label

Could you update my demo with your code for introducing the issue?

**Comment by amit1911** [comment] 2017-05-18 11:13
facing the same issue....this is an issue in 5.0.11 release. I switched to 5.0.9 and it works smoothly.

**Comment by pawelfus** [comment] 2017-05-18 11:33
Hi @amit1911 
Could you recreate issue in jsFiddle? I have a feeling it's already fixed on our master branch, could you also try this source: http://github.highcharts.com/highcharts.js ? 

Thanks!

**Comment by amit1911** [comment] 2017-05-18 11:36
i am using npm to install highcharts and use it in my project as shown below:-
```
import Highcharts from 'highcharts';
require('highcharts/modules/drilldown')(Highcharts);
```
I tested that the issue is not there if i use the source: http://github.highcharts.com/highcharts.js directly. So this might be due to the highcharts node package.

**Comment by TorsteinHonsi** [comment] 2017-05-19 09:37
Most likely a duplicate of #6704. Please reopen if the problem appears again.

**Comment by amit1911** [comment] 2017-07-06 00:56
is this issue fixed in the current deployed version (5.0.12) ?

**Comment by pawelfus** [comment] 2017-07-06 14:10
Yes, it is. Version 5.0.12 was released 2017-05-24 (a week after your previous comment). If you have an example when it fails, please let us know.

**Comment by amit1911** [comment] 2017-07-07 03:11
It still doesn't work properly. https://jsfiddle.net/amit1911/0xzd102v/
#### Steps to reproduce
1. Drilldown
2. Drillup
3. Drilldown (now it won't work)

**Comment by pawelfus** [comment] 2017-07-07 09:34
Thank you, you are right, your demo used to work in 5.0.9: https://jsfiddle.net/tgzynvcL/

**Comment by wraitii** [comment] 2017-08-09 12:39
Encountered this too. It still works when clicking on the xAxis label, but not on a point in the demo above (and I confirm the behaviour).

The issue is that some functions you can call during drillUp result in _hadTracking being set to true for the new series, which leads to the series not getting the highcharts-tracker class in the end. If you manually unset that, things work correctly.

**Comment by TorsteinHonsi** [comment] 2017-08-10 07:43
Thanks for the input! In this case, calling `series.show()` from the `drillup` event causes the problem.

**Comment by RupprechJo** [comment] 2017-08-30 15:07
Still not working on 5.0.14. When will you release a fix? It is open since May!

**Comment by TorsteinHonsi** [comment] 2017-08-31 11:51
Sorry, I'm on it. Fails since caf870e02.

**Closed** 2017-08-31 12:20 UTC
Labels: Regression
