### ISSUE TITLE
Bar and column chart incorrectly positioned on initial load when not active on current tab

### ISSUE THREAD

**Issue by HarishSha** [highcharts/highcharts#9975] opened 2019-01-23 14:42 UTC
#### Expected behaviour
The column chart should be on the axis.

#### Actual behaviour
Column chart's rendering is destorted. It is rendering below the axis. 

#### Live demo with steps to reproduce
This can be replicated by reloading the page and during reloading switch the tab. Then come back to the original tab once you noticed that the page loaded completely. you will see the chart rendered outside.

I'm attaching a video to reproduce the same and temporary fix [**here**](https://drive.google.com/file/d/1CpGdldZ5Cr7FVTlHj4Gikfe6WU9Fe_50/view?usp=sharing)

[JsFiddle](http://jsfiddle.net/harishk3499/htmkmoh5/37/)

#### Product version
Highcharts v7.0.2, 
Highstock v6.0.3

#### Affected browser(s)
Chrome
Safari
Firefox

**Comment by sebastianbochan** [comment] 2019-01-23 14:51
Hi @HarishSha,
Thank you for reporting. The issue is already fixed in the master branch (next candidate to release).

Duplicate of https://github.com/highcharts/highcharts/issues/9957

**Closed by sebastianbochan** 2019-01-23 14:51 UTC
