### ISSUE TITLE
treemap is rendered as lines on chart update with changed size properties 

### ISSUE THREAD

**Issue by pulbere** [highcharts/highcharts#11953] opened 2019-09-12 15:37 UTC
#### Expected behaviour
The treemap chart should be rendered correctly with new size

#### Actual behaviour
The treemap chart is rendered a bunch of connected lines

#### Live demo with steps to reproduce
https://jsfiddle.net/pulbere/5sp9tha7/
1. Open link
2. wait 2 seconds for the update 

#### Product version
Highcharts JS  7.1.2, 7.1.3

#### Affected browser(s)
Tested on Chrome

**Comment by pawelfus** [comment] 2019-09-13 09:32
Thanks for reporting this regression @pulbere !

Simplified demo: https://jsfiddle.net/BlackLabel/L70qkmey/1/

*Internal note:*
Bisected to commit d94c64d17f

**Comment by pawelfus** [comment] 2019-09-16 14:54
Closing as duplicate of #11829

**Closed by pawelfus** 2019-09-16 14:54 UTC
Labels: Type: Regression
