### ISSUE TITLE
Unexpected position of stacking column with alignThresholds

### ISSUE THREAD

**Issue by js-yo** [highcharts/highcharts#17732] opened 2022-09-15 09:07 UTC
#### Live demo with steps to reproduce

[https://jsfiddle.net/fxhnk96t/2/](https://jsfiddle.net/fxhnk96t/2/)

As shown in the demo, setting `chart.alignThresholds` to `true`, stacking column display  with unexpected position.

<img width="1242" alt="image" src="https://user-images.githubusercontent.com/108983555/190364356-f5b96689-8a17-4948-b631-123a7336f20b.png">

and just call `chart.reflow` method, everything is fine.

#### Product version

Highcharts 10.0.0 +

#### Affected browser(s)

All

**Comment by pawellysy** [comment] 2022-09-16 09:10
Closing as a duplicate of https://github.com/highcharts/highcharts/issues/17314

**Closed by pawellysy** 2022-09-16 09:10 UTC
