### ISSUE TITLE
Higcharts on iOS crashes and stops other running scripts

### ISSUE THREAD

**Issue by erikgus** [highcharts/highcharts#7767] opened 2018-01-31 11:00 UTC
#### Expected behaviour
Working like on every other platform.

#### Actual behaviour
Something about using cumulative charts crashes highcharts on iOS and stops other scripts also running on the page.

#### Live demo with steps to reproduce
https://www.ssb.no/329630/test

#### Product version
Highcharts 6.0.3

#### Affected browser(s)
Browsers on iOS (safari, chrome)

**Comment by pawelfus** [comment] 2018-01-31 14:31
Hi @erikgus 

Thank you for reporting the issue. Could you update Highcharts to v6.0.5 and let us know the result? We improved performance for charts with categories.

Tested on iOS v11.2.2:
Safari is broken, but Chrome v64.0.03282.112 works fine.

**Comment by TorsteinHonsi** [comment] 2018-02-02 11:49
Also, as a best practice, I would recommend using linear axis (not categories), for year-based data. This improves readability of the chart and the ticks don't have to be placed so close. This applies to for example _Konsumprisindeksen, årlig endring_.

**Comment by pawelfus** [comment] 2018-02-02 16:57
I found the reason: http://jsfiddle.net/BlackLabel/zwnphzLd/33/ (or: http://jsfiddle.net/BlackLabel/zwnphzLd/32/ )

It looks like `<td>1065671</td>` is translated to a phone number and placed inside `<a>` tag and data module can not translate `<a href="....">value</a>` to a proper number. 

@erikgus - could you disable this auto-translation for Safari? Related issue on SO: https://stackoverflow.com/questions/226131/how-to-disable-phone-number-linking-in-mobile-safari

@TorsteinHonsi - in case that value is first in the array, we check the type and throw error: https://www.highcharts.com/errors/14 but if it's not in a first place, then error message won't show up.

**Comment by erikgus** [comment] 2018-02-05 14:44
Ah, okay, I will disable the phone number linking.
Thanks for the help :)

**Comment by KacperMadej** [comment] 2018-12-31 01:14
Based on info on SO and related official Safari docs the problem was caused by the browser and is possible to be resolved through disabling the format detection.

Closing as resolved.

**Closed by KacperMadej** 2018-12-31 01:14 UTC
