### ISSUE TITLE
Bubbles chart re-render changes the initial bubble radius 

### ISSUE THREAD

**Issue by daniel-tabarcea** [highcharts/highcharts#17161] opened 2022-04-06 08:30 UTC
When updating the config to the same config the bubble chart radius grows unexpectedly.

#### Expected behaviour
Bubble chart size should stay consistent 

#### Actual behaviour
Bubble chart size grows with the same data

#### Live demo with steps to reproduce
click config 1 -> config 2 -> config 2 again -> config 1
http://jsfiddle.net/BlackLabel/oejnw60s/

#### Product version
Highcharts 10.0.0

#### Affected browser(s)
Google Chrome latest

**Comment by karolkolodziej** [comment] 2022-04-07 09:06
Thank you for reporting that issue.

Please don't set the `keys` array in the `plotOptions` while updating the data.
Because of that, points are not being correctly updated which is why you get this strange behaviour.
When you remove that, everything works as expected.

Demo: http://jsfiddle.net/BlackLabel/aekj68dh/

Closing as not a bug.

**Closed by karolkolodziej** 2022-04-07 09:06 UTC
