### ISSUE TITLE
Chart not showing in Angular 2/4 Modal after upgrade to 5.0.14 (Caused by #5783)

### ISSUE THREAD

**Issue by shadowkrusha** [highcharts/highcharts#7104] opened 2017-08-27 18:26 UTC
#### Expected behaviour
Chart should display in modal dialog.

#### Actual behaviour
The chart element is missing when using highcharts > 5.0.12
It appears to have been broken by the fix for #5783 

#### Live demo with steps to reproduce

By changing the version of highcharts in package.json, you can reproduce the issue.

https://github.com/shadowkrusha/highcharts-issue

5.0.12 is fine
5.0.13, 5.0.14 are broken.

#### Affected browser(s)
chrome 60

**Comment by TorsteinHonsi** [comment] 2017-08-28 08:58
Thanks for reporting!

It seems to be a duplicate of #7024. The extra check for `!node.parentNode` resolves your case too.

**Closed by TorsteinHonsi** 2017-08-28 08:58 UTC
