### ISSUE TITLE
min/max missing in legend of heatmap

### ISSUE THREAD

**Issue by Tinoooo** [highcharts/highcharts#8369] opened 2018-05-23 08:54 UTC
Sometimes, when a heatmap is drawn with the options min and/or max set in colorAxis, the minimum and/or maximum is not showing up in the legend of the chart.
![image](https://user-images.githubusercontent.com/17991193/40413806-0c55364e-5e77-11e8-8452-893d4cd17115.png)

Of course I could use startOnTick or endOnTick, but this is not exactly the behavior I want to achieve.

Is there any way to make the values show up?

I am using Highcharts 6.1.0.

**Comment by jon-a-nygaard** [comment] 2018-06-05 11:57
Closing due to unable to reproduce and pending reply.
Should anyone have further information on this issue please give us a comment, and we will consider reopening it.

**Closed by jon-a-nygaard** 2018-06-05 11:57 UTC
Labels: Cant reproduce, Pending reply
