### ISSUE TITLE
boost canvas scatter plot is filled when joining points with a line

### ISSUE THREAD

**Issue by duncanrussell** [highcharts/highcharts#4992] opened 2016-02-03 10:18 UTC
The option fill=true (boost.js L:543) is set, and then scatter points are drawn filled. However, this is also acts on lines drawn in the scatter plot and creates a large filled area instead of points connected by lines.

I would like to use the scatter plot to draw 100,000 point graph with the points connected by lines. If I force the fill parameter to false, the line is correctly drawn without the area, but the points are not filled.

Is there a way to fill the points, but still retain the line drawing in a scatter plot when using boost canvas plotting?

**Comment by pawelfus** [comment] 2016-02-03 11:52
I think you refer to [this note](https://github.com/highcharts/highcharts/blob/master/js/modules/boost.src.js#L32). 

The best workaround I can think of, is to use two series. However that sounds wrong: doubling number of points to get markers. Anyway, here is a demo: http://jsfiddle.net/2y9uo0q3/1/

**Comment by TorsteinHonsi** [comment] 2016-02-04 14:22
Reproduction of a scatter series with `lineWidth` set: http://jsfiddle.net/kuovc84z/

**Comment by Rashaine** [comment] 2017-06-02 19:03
Any updates on this? I'm running into the same issue

**Comment by pawelfus** [comment] 2017-06-05 08:21
It looks like the current version doesn't support `lineWidth` for scatter type: http://jsfiddle.net/kuovc84z/3/

**Comment by Rashaine** [comment] 2017-06-05 12:41
Right, but I need to show lines on the scatter chart.

**Comment by pawelfus** [comment] 2017-06-05 12:49
Unfortunately, in the current boost module it's one of the limitations, see [details](https://github.com/highcharts/highcharts/blob/d542b6c4e67a435177c41c6135e4116e43118f9d/js/modules/boost.src.js#L24).

**Comment by HetWipro** [comment] 2019-03-15 03:43
Hey, any update for this issue. I am facing the same issue. 
I am currently using v6.0.7. Is it resolved by the latest version 7.0.3?

**Comment by pawelfus** [comment] 2019-03-15 10:57
Hi @HetWipro 

Current boost module does not support lineWidth in scatter series (so issue is kind of resolved). Line series doesn't fill the plot, so it's safe to use it: http://jsfiddle.net/BlackLabel/pwns2eu6/

**Comment by HetWipro** [comment] 2019-03-25 07:19
Thank you @pawelfus.
I tried the solution. The lines are coming now using Line series. But I am facing one more small problem.
The Markers of line points are not coming. 
I have prepared the demo version here:
https://jsfiddle.net/finisher001/v695fuzh/36/
In the example ( http://jsfiddle.net/BlackLabel/pwns2eu6/) also markers are not coming.
Is there any work around for it?

**Comment by pawelfus** [comment] 2019-03-25 10:58
@HetWipro - don't forget to set `marker.enabled = true`, take a look: http://jsfiddle.net/BlackLabel/pwns2eu6/2/

**Comment by HetWipro** [comment] 2019-03-25 11:02
Thanks once again @pawelfus ..

**Comment by pawelfus** [comment] 2019-04-02 12:00
Closing the issue since original issue is resolved (no fill for scatter/line series since v5).

**Closed by pawelfus** 2019-04-02 12:00 UTC
