### ISSUE TITLE
Series options default colours are not valid

### ISSUE THREAD

**Issue by bholtbholt** [highcharts/highcharts#17051] opened 2022-03-03 20:37 UTC
#### Expected behaviour
When I use the default settings in Highcharts
My graphs should have coloured points

#### Actual behaviour
The graphs are all black because the compiled CSS values are not valid CSS.

This is from `highcharts/css/highcharts.scss#279`:
```scss
/* Default colors */
@for $i from 1 through length($colors) {
  $color: nth($colors, $i);
  .highcharts-color-#{$i - 1} {
    fill: $color;
    stroke: $color;
  }
}
```

#### Live demo with steps to reproduce
This is what the CSS outputs:
```css
/* Series options */
/* Default colors */
.highcharts-color-0 {
  fill: "blue" #007bff;
  stroke: "blue" #007bff;
}

.highcharts-color-1 {
  fill: "indigo" #6610f2;
  stroke: "indigo" #6610f2;
}

…etc ("name" hex)
```

This is what it should output:
```css
.highcharts-color-0 {
  fill: #007bff;
  stroke: #007bff;
}

.highcharts-color-1 {
  fill: #6610f2;
  stroke: #6610f2;
}

…etc (hex only)
```
#### Product version
Highcharts 9.3.2
sass 1.38.0
webpack 4.46.0
css-loader 3.6.0
Bootstrap 4.5.3

#### Affected browser(s)
All -- it's a compiler issue.

**Comment by raf18seb** [comment] 2022-03-04 14:42
Hi @bholtbholt, thank you for reporting the issue!

Could you provide a small demo with a live example of the above behavior? Thank you in advance!

**Comment by bholtbholt** [comment] 2022-03-04 20:29
@raf18seb here you go! https://replit.com/join/tcokxxrowg-bholtbholt

I've generated a build so you can look. The issue can be seen around `dist/main.css#10143`.

If you haven't used Repl.it before, you can generate builds by switching to the Shell tab, then running `npm run build`, just like you would in the terminal.

**Comment by raf18seb** [comment] 2022-03-08 12:06
@bholtbholt,

no problem, I created an account. I can see a problem now. As you said, it's a naming collision and can be fixed by changing the `$colors` variable name to e.g. `$highcharts-colors`.

**Comment by raf18seb** [comment] 2022-04-27 13:41
Closing as a duplicate of https://github.com/highcharts/highcharts/issues/17051

**Closed by raf18seb** 2022-04-27 13:41 UTC
Labels: Type: Bug
