### ISSUE TITLE
iOS / show tooltip on click event issue

### ISSUE THREAD

**Issue by morganfree** [highcharts/highcharts#5744] opened 2016-09-29 11:37 UTC
#### Expected behaviour

Tooltip is shown on the first point's click
#### Actual behaviour

On iOS mobile device when the chart is rendered, first touch highlights the series and the second touch shows the tooltip. This behaviour does not occur in desktop devices or if the the chart is rendered in iframe tag.
#### Live demo with steps to reproduce

Use only code from jsfiddle - since jsfiddle uses iframe, the issue will not occur
http://jsfiddle.net/2swEQ/2/
#### Affected browser(s)

iPad 2, iOS 9.3.5, Safari 601.1
iPhone 5s, iOS 9.3.5;

**Comment by TorsteinHonsi** [comment] 2016-09-30 08:41
Thanks for reporting!

@morganfree, as a general tip, you can reproduce this on jsFiddle by first logging in with your user account, then run the fiddle, then head over to http://jsfiddle.net/draft . The draft runs without an iframe.

**Comment by pawelfus** [comment] 2019-03-22 10:43
Closing as duplicate of #5841.

**Closed by pawelfus** 2019-03-22 10:43 UTC
Labels: Bug
