### ISSUE TITLE
Series selected doesn't work in line charts

### ISSUE THREAD

**Issue by geraldo** [highcharts/highcharts#13525] opened 2020-05-14 17:54 UTC
#### Expected behaviour
Serie with **selected** set to **false** should be hidden initially in documentation example at https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/series-selected/

#### Actual behaviour
Both series are visible, even if checkbox is unselected by default.

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/series-selected/

#### Product version
Highcharts JS v8.1.0

#### Affected browser(s)
Firefox, Chrome

**Comment by sebastianbochan** [comment] 2020-05-15 09:37
Hi @geraldo,
Thank you for reporting. The issue is related with two known problems, reported here:
- https://github.com/highcharts/highcharts/issues/3345
- https://github.com/highcharts/highcharts/issues/1178

Im closing the bug as a duplicate.

**Closed by sebastianbochan** 2020-05-15 09:37 UTC
