### ISSUE TITLE
Reopening issue  MouseOut event #182

### ISSUE THREAD

**Issue by babblu** [highcharts/highcharts#5023] opened 2016-02-09 12:50 UTC
Reopening the below issue 

https://github.com/highcharts/highcharts/issues/182

Browser hangs;  reaches maximum stack size when we have tooltip{enabled:false}

Demo: http://jsfiddle.net/6sqL0zam/16/

**Comment by pawelfus** [comment] 2016-02-09 14:10
**Workaround:**

Instead of disabling tooltip, enable it, but in formatter return `false`. Demo: http://jsfiddle.net/6sqL0zam/18/

**Comment by babblu** [comment] 2016-02-09 15:37
I need my formatter function to trigger the tooltip with different UI treatment for each point upon the click event on a series. 
myTooltip.refresh(pointId);

So i cant return false there. Also I am showing useHTML  tooltip upon calling refresh method.

**Comment by pawelfus** [comment] 2016-02-16 14:02
How can you use `tooltip.refresh()` when you certainly disabled it before?

**Comment by rlsz** [comment] 2017-12-01 12:35
oops, this bug is still here, highcharts version 6.0.2.
I just play a delay trick on the parent element for now.

**Comment by KacperMadej** [comment] 2017-12-06 13:11
Hi @rlsz ,

I ma unable to recreate the problem - please provide a live demo.

**Comment by rlsz** [comment] 2017-12-06 14:16
@KacperMadej ,
http://jsfiddle.net/rlsz/e5e2o9me/
here is a example

**Comment by KacperMadej** [comment] 2017-12-08 16:10
@rlsz Thank you for the demo.

I'm not seeing the maximum stack size reached error - should I use a selected browser + OS combination?
A lot of events are being called, but this is normal for a small chart with multiple points.

**Comment by rlsz** [comment] 2017-12-08 16:27
@KacperMadej
The problem is that too many events are called. With chrome + win10, a normal div will trigger mouse over one time and mouse out one time, when crossed by a mouse icon. But with a highcharts content, the div will trigger countless mouse over and mouse out when crossed by a mouse icon.

**Comment by pawelfus** [comment] 2017-12-11 11:08
Hi @rlsz 

You are right, if there is only the container, then we have only one event, but when you have nested elements, mouseover and mouse out are continuously fired, take a look: http://jsfiddle.net/e5e2o9me/6/ - and hover red box

Maybe you should use `mouseenter` and `mouseleave` events? Demo: http://jsfiddle.net/e5e2o9me/7/

**Comment by rlsz** [comment] 2017-12-11 11:53
@pawelfus
For some reason, I have to use a outdated chrome core, which doesn’t support mouseenter and mouseleave.

**Comment by pawelfus** [comment] 2017-12-11 15:35
@rlsz - in that case you need to use your workaround. I mean, this is how `mouseover` and `mouseout` events work, so there's not much we can do..

**Comment by rlsz** [comment] 2017-12-15 01:39
@pawelfus 
Right. I just realize my problem is different from babblu'. Sorry for my misunderstand.

**Comment by pawelfus** [comment] 2017-12-15 10:57
@rlsz don't worry! 

Ok, closing this issue then:

- original demo works fine (6.0.3 and 6.0.4): http://jsfiddle.net/BlackLabel/sjdzsyt1/
- issue with multiple `mouseover` and `mouseout` call is not a bug - that's how these events are implemented in browsers

**Closed by pawelfus** 2017-12-15 10:57 UTC
Labels: Cant reproduce, Pending reply
