### ISSUE TITLE
Treemap legend labels are truncated  

### ISSUE THREAD

**Issue by martinknox** [highcharts/highcharts#5257] opened 2016-04-27 23:40 UTC
When using tree maps  with a color axis legend , if the displayed values are large the chart display does not allow enough space for the text labels to display on screen.

We cannot set a legend item width as our data is dynamic 

Example here:

https://jsfiddle.net/mwknox/5c300t0h/

**Comment by TorsteinHonsi** [comment] 2016-04-28 08:24
Duplicate of #3463.

Currently the color axis legend uses a fixed with, it doesn't take the actual rendered label size into account. A (suboptimal) workaround is to set a fixed width: https://jsfiddle.net/highcharts/5c300t0h/1/.

**Closed by TorsteinHonsi** 2016-04-28 08:24 UTC
Labels: Duplicate
