### ISSUE TITLE
Area series & boost module

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#14207] opened 2020-09-10 13:06 UTC
#### Expected behaviour

Series should be rendered as an `area` series type.

#### Actual behaviour

The boost module breaks the chart and the `area` series and renders series as a `column`.

#### Live demo with steps to reproduce

Demo: https://jsfiddle.net/BlackLabel/nuajc4r7/

#### Product version

Highcharts JS v8.2.0 (2020-08-20)

**Comment by pawelfus** [comment] 2020-09-14 12:59
That's not a bug, it's expected behaviour - area (and arearange) series is rendered as 1px wide bars. This should be explained in our docs (used to be, probably lost during docs migration): https://www.highcharts.com/docs/advanced-chart-features/boost-module#caveats

**Comment by khlieng** [comment] 2021-01-18 14:39
Fixed in #14533.

**Closed by khlieng** 2021-01-18 14:39 UTC
Labels: Product: Docs, Type: Bug
