### ISSUE TITLE
Highcharts issue related to panning and xAxis categories.

### ISSUE THREAD

**Issue by Ty4ka** [highcharts/highcharts#7548] opened 2017-12-18 07:54 UTC
#### Expected behaviour
When you add categories to the xAxis, and activate panning, you can pan between the first and last categories. Version 6.0.3

#### Actual behaviour
For some reason when categories are activated, you can pan infinitely to the left or right of the chart.

#### Live demo with steps to reproduce
http://jsfiddle.net/1oqmmhex/

#### Affected browser(s)
Tested only on Chrome.

**Comment by TorsteinHonsi** [comment] 2017-12-18 09:01
Duplicate of #7451, fixed in v6.0.4: http://jsfiddle.net/highcharts/1oqmmhex/1/

**Closed by TorsteinHonsi** 2017-12-18 09:01 UTC
