### ISSUE TITLE
Exporting error

### ISSUE THREAD

**Issue by jojoviaje** [highcharts/highcharts#1929] opened 2013-06-10 07:57 UTC
I get the instance of the chart(chart.highStockChartInstance) and called the exportChart() function and i'm getting this error:  "Unexpected call to method or property access" on highstock.js line 41 character 37. It is pointing to this line of code: e=g.getElementsByTagName("title")[0]. This used to work but I have no idea why it's not working now.

**Comment by jon-a-nygaard** [comment] 2016-04-26 11:02
Closing this issue due to: We are not able to reproduce the issue, and it is pending reply. 
Should anyone have further information on this issue, please add a comment and reopen.

**Closed by jon-a-nygaard** 2016-04-26 11:02 UTC
Labels: Cant reproduce, Pending reply
