### ISSUE TITLE
StockToolsGuiOptions declaration error in highcharts.d.ts

### ISSUE THREAD

**Issue by daniele-moretti** [highcharts/highcharts#14413] opened 2020-10-23 10:32 UTC
#### Expected behaviour
in my Angular Application
i want customize the button to show in the stocktools gui.

**in the api doc : https://api.highcharts.com/highstock/stockTools.gui**
buttons: Array.<string>Since 7.0.0
A collection of strings pointing to config options for the toolbar items. Each name refers to a unique key from the definitions object.
Defaults to [ 'indicators', 'separator', 'simpleShapes', 'lines', 'crookedLines', 'measure', 'advanced', 'toggleAnnotations', 'separator', 'verticalLabels', 'flags', 'separator', 'zoomChange', 'fullScreen', 'typeChange', 'separator', 'currentPriceIndicator', 'saveChart' ].

#### Actual behaviour
wrong declaration of button element in file node_modules/highcharts/highcharts.d.ts 
i get this error if i run my project

`error TS2322: Type 'string[]' is not assignable to type 'string'.

    319             buttons: ['indicators', 'separator', 'currentPriceIndicator','fullScreen'],
                    ~~~~~~~

      node_modules/highcharts/highcharts.d.ts:113075:5
        113075     buttons?: string;
                   ~~~~~~~
        The expected type comes from property 'buttons' which is declared here on type 'StockToolsGuiOptions'`

#### Live demo with steps to reproduce
https://stackblitz.com/edit/highcharts-angular-stock-gui-erroroptions?file=src/app/app.component.ts

#### Product version
"highcharts": "^8.2.0",

#### Affected browser(s)
All

**Comment by pawelfus** [comment] 2020-10-23 14:26
Hi @daniele-moretti 

Thank you for reporting this bug. It was already reported (#14389) and should be fixed in the v8.2.2 version. Please, update your Highcharts

Closing as duplicate of #14389

**Closed by pawelfus** 2020-10-23 14:26 UTC
