### ISSUE TITLE
Highcharts stripping spaces out of text

### ISSUE THREAD

**Issue by kai2468** [highcharts/highcharts#15736] opened 2021-05-17 20:24 UTC
#### Expected behaviour
HTML should not have its spaces removed. Was working fine in v8.2.2, maybe something to do with the whole AST thing?

#### Actual behaviour
Spaces are removed from my HTML

#### Live demo with steps to reproduce
Hover over a point to see the tooltip, you'll see that there are no spaces in it even though I've added some in the code.

Doesn't work:
https://jsfiddle.net/c732xmj1/

Works (8.2.2)
https://jsfiddle.net/c732xmj1/1/

#### Product version
Latest

**Comment by khlieng** [comment] 2021-05-18 07:08
Duplicate of #15235.

**Closed by khlieng** 2021-05-18 07:08 UTC
Labels: Type: Duplicate
