### ISSUE TITLE
Error bar visibility is not changing based on series visibility if series is set hidden by default

### ISSUE THREAD

**Issue by vbinithyanandamv** [highcharts/highcharts#7989] opened 2018-03-12 08:16 UTC
#### Expected behavior
Error bar should be hidden automatically based on series visibility even if we set series hidden by default.

#### Actual behavior 
Error bar is showing up irrespective of series visibility. (same feature works fine if we use legend toggle to hide/show series, not working if we set series visibility by default).

#### Live demo with steps to reproduce

http://jsfiddle.net/9vemgf6g/6/

#### Product version

 v6.0.7

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment] 2018-03-12 11:15
Hi @vbinithyanandamv 

Thank you for reporting this issue. This is caused by setting `series.visible = true` for some of the series. Visibility will be inherited from the main series, unless you set otherwise: http://jsfiddle.net/BlackLabel/9vemgf6g/11/ (simply removed `visible: true` from all errorbar series).

**Closed by pawelfus** 2018-03-12 11:15 UTC
