### ISSUE TITLE
The line does not lie on the position during panning

### ISSUE THREAD

**Issue by PaulJaker** [highcharts/highcharts#15674] opened 2021-05-07 07:47 UTC
#### Expected behaviour
The line segment should lie on the same position of yAxis in the chart view after panning in xAxis.

#### Actual behaviour
The line segment changed the position in yAxis, after pan the chart left/right.
The line visible change the position, probably because one of the line point  is outside of Chart 
![Line_OK](https://user-images.githubusercontent.com/82182068/117415967-326d5000-af19-11eb-8676-28366e21c5d6.JPG)
![GAP](https://user-images.githubusercontent.com/82182068/117415963-31d4b980-af19-11eb-8bdb-67cc50404b17.JPG)
![Overlap the candles](https://user-images.githubusercontent.com/82182068/117415969-3305e680-af19-11eb-9628-a4a249dcf543.JPG)

area.

#### Live demo with steps to reproduce
https://jsfiddle.net/PaulJaker/mrgk5s19/38/

#### Product version
Highstock

#### Affected browser(s)
all

**Comment by khlieng** [comment] 2021-05-07 08:22
Duplicate of #2406.

**Closed by khlieng** 2021-05-07 08:22 UTC
Labels: Type: Duplicate
