### ISSUE TITLE
Scrolling right and left should be symmetry after datagrouping

### ISSUE THREAD

**Issue by janckerchen** [highcharts/highcharts#7240] opened 2017-10-08 14:41 UTC
#### Expected behaviour

Scrolling right and left should be symmetry.  

#### Actual behaviour

it's hard to scroll right

#### Live demo with steps to reproduce

Official demo  https://www.highcharts.com/stock/demo/intraday-candlestick

1. ranger selector to D1
2. move navigator to middle
3. scroll candlestick chart left and right
4. it's hard to scroll right(click and  move  left) 

#### Affected browser(s)

chrome v61.0.3163.100

**Comment by pawelfus** [comment] 2017-10-09 09:37
Hi @janckerchen 

Thank you for reporting. It looks like a duplicate of #3825 - do you agree?

**Comment by pawelfus** [comment] 2017-12-28 12:39
Closing as a duplicate.

**Closed by pawelfus** 2017-12-28 12:39 UTC
Labels: Duplicate, Highstock
