### ISSUE TITLE
Pie Chart Labels not center aligned in Chrome

### ISSUE THREAD

**Issue by NamishM** [highcharts/highcharts#15242] opened 2021-03-02 13:55 UTC
#### Expected behaviour
Pie chart labels should adjust itself in arc according to the width defined inside arc and center-aligned whether the labels are wrapped in multiple lines or not. It happens in Mozilla Firefox which is expected behavior.

#### Actual behaviour
But in Google Chrome(latest version or any other), when labels start wrapping in two or more lines, they shift towards the left. We have to manually adjust them and pull them to the center with startOffset property in dataLabels.textPath. 
However we don't need to do anything in Mozilla Firefox, all labels adjust nicely according to the width defined in the center of Pie.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/Lv0wadh8/

#### Product version
highcharts: ^9.0.0
react-highcharts: ^16.1.0

#### Affected browser(s)
Google Chrome

**Comment by KacperMadej** [comment] 2021-03-02 18:49
Hi @NamishM 

Thank you for reporting the problem.

Are you able to recreate the problem without the custom code? If something is wrong in the custom code added to the chart then we are not able to fix Highcharts code to make this work - the custom code should be fixed in such a case.
In general, a minimal demo showing the problem is better.

**Comment by NamishM** [comment] 2021-03-12 12:13
Hi @KacperMadej ,

We have tried to recreate a scenario but by removing the custom code, we are losing the arc shape for labels which is critical for us. The custom code was provided to us by the HighCharts team only last year when we approached them which enabled us to show labels in a curved shape in pie chart. So, removing it makes no sense to us but at the same time I feel that there is something in that piece of code only which is fine for Firefox but chrome is not responding to that. If you can help us with that code only to make labels in curved shape, that will be great help to us.

**Comment by KacperMadej** [comment] 2021-03-16 16:39
I am unable to provide any details as I do not know the source of the custom code. A problem with custom code should be resolved by the custom code author and could be continued as a part of technical support, so the best option would be for you to contact the code author(s) and ask for help. We are using GitHub issues for bug reports and feature requests while you are looking for support for a custom code that is not a part of the library. Please contact technical support and the author(s) of the custom code to get more info.

The problems seem to be with `text-anchor` and how Chrome and Firefox are rendering both, so a solution might require a browser-specific code or fixing the inconsistency in the browser by reporting a bug to one or both of them.

**Closed** 2021-03-16 16:39 UTC
Labels: Type: Not a bug, Type: Question
