### ISSUE TITLE
Cannot find name 'Fullscreen'.

### ISSUE THREAD

**Issue by danieldavidraj** [highcharts/highcharts#16065] opened 2021-07-18 15:54 UTC
Error: node_modules/highcharts/modules/full-screen.d.ts:17:21 - error TS2304: Cannot find name 'Fullscreen'.

17         fullscreen: Fullscreen;
                       ~~~~~~~~~~

**Comment by khlieng** [comment] 2021-07-18 17:40
Duplicate of #15275.

**Closed by khlieng** 2021-07-18 17:40 UTC
Labels: Type: Duplicate
