### ISSUE TITLE
Pie chart label distribution changed after upgrade from 9.0.1to 9.3.2

### ISSUE THREAD

**Issue by Teju-S** [highcharts/highcharts#16716] opened 2021-11-30 07:43 UTC
#### Expected behaviour
pie chart connectors should work as shown in below fiddle 
http://jsfiddle.net/34anors9/5/

#### Actual behaviour

We had this issue in 7.0.2 Highstock version n Overrided Distribute function provided by Highstock support team But now after upgrading it to 9.3.2  and overriding distribute function doesn't seem to work. here is fiddle
http://jsfiddle.net/34anors9/4/

#### Product version
9.3.2

**Comment by Teju-S** [comment] 2021-11-30 07:55
@wchmiel @TorsteinHonsi  can u please check this issue?

**Comment by TorsteinHonsi** [comment] 2021-11-30 10:31
This happened because of our rewrite to ES modules. The pie data labels module is no longer loading the `distribute` function from the global `Highcharts` object, but directly from the new `RendererUtilities` module.

https://github.com/highcharts/highcharts/blob/af8977bafd322c170f435c3872a179de9105694c/ts/Series/Pie/PieDataLabel.ts#L29-L30

Unfortunately we now don't have a good way to override the `distribute` function. In order to do that you probably need to build your own Highcharts from source.

That said, the behaviour that you want to achieve, looks to me like a bug. The connectors are crossing each other, making it impossible to track the data labels to the slices. This is what we fixed in the first place.

**Comment by Teju-S** [comment] 2021-11-30 11:54
Is this only solution to this?

**Comment by raf18seb** [comment] 2021-12-01 21:08
@Teju-S,

As @TorsteinHonsi said, there's no a good way to overwrite the `distribute` function, but you can overwrite the `drawDataLabels` method and change the `maxDistance` in the `distribute` call.
You can find this workaround here in this thread: https://github.com/highcharts/highcharts/issues/16622

Closing as a duplicate of https://github.com/highcharts/highcharts/issues/16622

**Closed by raf18seb** 2021-12-01 21:08 UTC

**Comment by ashishwin8** [comment] 2021-12-06 12:49
It should behave as version 5.0.9

New property should be added for 9.x.x, so that it would behave as 5.x.x

http://jsfiddle.net/gd5nh0t4/

![image](https://user-images.githubusercontent.com/71814824/144848750-57c43c2d-aff0-4151-8390-29ac4ca19aad.png)

**Comment by ashishwin8** [comment] 2021-12-07 10:25
Workaround has no meaning, as it does not work across version upgrades

**Comment by raf18seb** [comment] 2021-12-07 11:24
@ashishwin8,
What version are you using? Maybe I'll be able to create a workaround for a targeted version.
In case of any further questions, please let's continue a conversation in an [open original thread](https://github.com/highcharts/highcharts/issues/16622).
