### ISSUE TITLE
Incorrect crosshair position on column chart with pointPlacement: "between"

### ISSUE THREAD

**Issue by LokiMan** [highcharts/highcharts#4142] opened 2015-04-28 08:09 UTC
Example: http://jsfiddle.net/y3qx9Luw/
Description: If in series option exists pointPlacement: "between" then when you hover mouse pointer on right half of column then the crosshair point to next column in series.
By steps:
1. Hover column
2. If pointer on left part then all ok
3. If pointer on right part then crosshair shifts to next column in series.
Screenshots that explain problem:
http://take.ms/Lywvf
http://take.ms/9KVtT
http://take.ms/QQAoa

**Comment by dandaka** [comment] 2015-04-28 08:25
May be related https://github.com/highslide-software/highcharts.com/issues/4122

**Comment by pawelfus** [comment] 2016-10-17 12:38
Duplicate of #5518

**Closed by pawelfus** 2016-10-17 12:38 UTC
