### ISSUE TITLE
Pie Chart - The chart does not display the original size after exiting full screen mode

### ISSUE THREAD

**Issue by madepiet** [highcharts/highcharts#13222] opened 2020-03-30 09:30 UTC
#### Actual behaviour
The initial demo version of the pie chart is displayed as with the given sizes.

After running "View full screen" / "Exit full screen" note that the size of the chart changes (it has been reduced or increased).

#### The problem occurs in the official Highcharts demo:
https://www.highcharts.com/demo/pie-basic

#### As well as in the editor with a simplified code:
https://jsfiddle.net/BlackLabel/weo19uvy/

#### Product version
Highcharts v8.0.4

#### Affected browser(s)
Chrome 80.0.3987.149

**Comment by madepiet** [comment] 2020-03-30 09:32
FYI @raf18seb

**Comment by raf18seb** [comment] 2020-03-30 10:56
Thanks for reporting @madepiet 
This is a known issue. After exiting from the fullscreen, some browsers restore the original height (height before calling fullscreen) but others don't.

You can define the container's height rigidly ([see the updated demo](https://jsfiddle.net/BlackLabel/8e0x2pwn/)), but then some browsers (like IE11) don't display container in 100% height of fullscreen mode but only with the height that was defined (which is not really a fullscreen).

Maybe we could write the logic that would remember the original height and restore it after exiting from the fullscreen. @sebastianbochan what do you think?

**Comment by sebastianbochan** [comment] 2020-03-30 14:28
As a wrokaround you can set width/height in CSS styles. (Works only with values in px, not percents).

Demo:
- https://jsfiddle.net/BlackLabel/qsguhm28/

@raf18seb its good idea and I think that is not also very complicated solution. However we need to verify if (after exit of fullscreen) `chart.setSize` is not called multiple times. We would like to avoid many re-renders.

**Comment by gkemp94** [comment] 2020-05-07 15:06
Hi, we're seeing this in our usage of lines charts and it's actually happening in the demo below on 
https://www.highcharts.com/demo/line-basic

We can't set width/height to be static because the chart needs to be responsive with in it's container. 

Browser & Operating System
https://www.whatsmybrowser.org/b/D78K2

**Comment by v-abkhot** [comment] 2020-05-13 11:37
![image](https://user-images.githubusercontent.com/63849538/81807441-add13700-953b-11ea-838c-76c9df65a11e.png)
after setting up fix height to container still issue is not resolved issue. issue is not with the container height it is with SVG height is not reformed.

Please see the attachment

**Comment by v-abkhot** [comment] 2020-05-18 05:11
can some body provide inputs on this ?

**Comment by sebastianbochan** [comment] 2020-05-18 07:33
@v-abkhot 
How about the workaround from the post above?
- https://jsfiddle.net/BlackLabel/qsguhm28/

**Comment by v-abkhot** [comment] 2020-05-18 07:37
this is no working that only i have reported

**Comment by v-abkhot** [comment] 2020-05-18 07:43
because the issue is not about the container height it is about svg. height

**Comment by sebastianbochan** [comment] 2020-05-18 09:50
Please share your live demo i.e reproduced in [jsfiddle.net](http://jsfiddle.net)

**Comment by v-abkhot** [comment] 2020-05-18 10:11
i have already share screen shot of it what is happening after adding fix width to that container

**Comment by v-abkhot** [comment] 2020-05-18 10:29
i have identified the issue... there is issue with svg height

**Comment by v-abkhot** [comment] 2020-05-18 10:48
and this need to be fixed.

**Comment by v-abkhot** [comment] 2020-05-18 11:51
so can some body actually look into this ?

**Comment by sebastianbochan** [comment] 2020-05-18 12:11
Hi @v-abkhot,
The screenshot does not allow us to reproduce the problem, because of missing informations like chart options, CSS styles etc. Please update this demo: https://jsfiddle.net/BlackLabel/0t6necqd/ with your simplified code for the further debugging.

ps. please use edit instead of sending so many short messages.

**Comment by v-abkhot** [comment] 2020-05-18 12:32
https://codepen.io/v-abkhot/pen/vYNQxQg?editors=1100


in this second graph when you open in full screen and exit to normal it is modified size

**Comment by v-abkhot** [comment] 2020-05-18 12:46
![image](https://user-images.githubusercontent.com/63849538/82214540-a216b380-9933-11ea-9996-69a24d16f949.png)

after applying fix height to container

**Comment by v-abkhot** [comment] 2020-05-18 12:49
![image](https://user-images.githubusercontent.com/63849538/82214791-fb7ee280-9933-11ea-8915-0953cbae7212.png)

there is height automatic set to SVG in above screen you can see that

**Comment by v-abkhot** [comment] 2020-05-18 13:32
i am using react wrapper

**Comment by sebastianbochan** [comment] 2020-05-18 14:25
Hi @v-abkhot,
Let me explain how our github issues work.

1. Please, please use the EDIT mode of your messages, it allows us to keep the readability.
2. Always share live demo, if problem is related with native highcharts, report on Highcharts repo, if related **only** with wrapper, report on wrapper's repo.
3. We have 24h for an answer according to our internal rules. You can find more informations here: [http://www.highcharts.com/support](http://www.highcharts.com/support)
4. Creating many topics and duplicates like: https://github.com/highcharts/highcharts-react/issues/218 or https://github.com/highcharts/highcharts/issues/13470 increase amount of threads, messages etc. As a result instead of debugging and solve problem, we close and "clean" our repo. Its really time-consuming for all of us in our team.

**Comment by v-abkhot** [comment] 2020-05-19 05:19
@raf18seb you work around is not working for hichart- react

**Comment by raf18seb** [comment] 2020-05-19 07:41
Hi @v-abkhot, could you provide a simplified online demo of your chart so I can debug it?

**Comment by v-abkhot** [comment] 2020-05-19 07:56
Hi @raf18seb  i have added to code pen in that for direct highchart if we set height then it is working fine but if we use it in hichart-react-officials as above screen shot issue with the svg height  

https://codepen.io/v-abkhot/pen/vYNQxQg?editors=1100

**Comment by v-abkhot** [comment] 2020-05-19 08:17
Hi @raf18seb can you please try this same with hichart-react-officials

**Comment by raf18seb** [comment] 2020-05-19 10:46
@v-abkhot Please, use edit button if you wish to add something to your previous post. Writing many posts makes our GitHub messy.

I tested it with `highcharts-react-official` wrapper and my workaround works fine. Have you defined styles on your both chart components using `containerProps` component property?  
Docs: https://github.com/highcharts/highcharts-react#options-details  
  
This works fine for me:

```
render() {
    return (
      <div>
        <div>
            <HighchartsReact
                constructorType={"chart"}
                ref={this.chartComponent}
                highcharts={Highcharts}
                options={this.state.options}
                containerProps = {{ style: {height: '400px'} }}
            />
        </div>
        <div>
            <HighchartsReact
                constructorType={"chart"}
                ref={this.chartComponent}
                highcharts={Highcharts}
                options={this.state.options}
                containerProps = {{ style: {height: '400px'} }}
            />
        </div>
      </div>
    );
  }
```

**Comment by v-abkhot** [comment] 2020-05-19 10:55
yah this works thank you so much

**Comment by dharmatv** [comment] 2020-07-27 08:33
I am also getting the same issue, please check the following screenshot

Before clicking on option(view in full screen)
https://snipboard.io/WRNQSZ.jpg
After clicking on option(exit in full screen)
https://snipboard.io/7HY3Js.jpg

Could u please help me, anyone

**Comment by raf18seb** [comment] 2020-07-27 08:50
Hi @dharmatv, have you tried the solution from the above comments?

**Comment by dolanmiu** [comment] 2020-07-27 13:06
> Hi @dharmatv, have you tried the solution from the above comments?

lol it's a bit of a stretch calling it a "solution"

Could we have an official fix?

In the app I am working on, the chart can't have fixed dimensions because it depends on the screen size and the dynamic changing nav bar. Essentially the chart is on the bottom half of the page, taking up the remaining space.

**Comment by dharmatv** [comment] 2020-07-28 07:19
@raf18seb, I tried CSS solution but it didn't work and remaining solutions are related to react-js but I am from Vue js. Could u please provide any solution for this
@dolanmiu You are right

**Comment by Jakartoine** [comment] 2020-09-15 15:50
Hey Highcharts Team (@raf18seb ),

Could you please take the time to resolve this bug?

It's been more than a year since the bug was reported:
https://www.highcharts.com/forum/viewtopic.php?t=43608

Thank you in advance.

**Comment by raf18seb** [comment] 2020-09-16 09:49
Hi! I will take a closer look at it and let you know about the status within the next few days.

**Comment by raf18seb** [comment] 2020-10-07 13:05
Here's a workaround snippet working on all browsers except IE: https://jsfiddle.net/BlackLabel/warvx6b5/
I'll investigate IE further

```js
(function(H) {
  var addEvent = H.addEvent,
    isMS = H.isMS,
    wrap = H.wrap;

  H.Fullscreen.prototype.open = function() {
    var fullscreen = this,
      chart = fullscreen.chart,
      originalHeight = chart.chartHeight;

    if (!isMS) {
      chart.setSize(void 0, screen.height, false);
      fullscreen.originalHeight = originalHeight;
    }

    // Handle exitFullscreen() method when user clicks 'Escape' button.
    if (fullscreen.browserProps) {
      fullscreen.unbindFullscreenEvent = addEvent(chart.container.ownerDocument, // chart's document
        fullscreen.browserProps.fullscreenChange,
        function() {
          // Handle lack of async of browser's fullScreenChange event.
          if (fullscreen.isOpen) {
            fullscreen.isOpen = false;
            fullscreen.close();
            if (!isMS) {
              chart.setSize(void 0, originalHeight, false);
            }
          } else {
            fullscreen.isOpen = true;
            fullscreen.setButtonText();
          }
        });
      var promise = chart.renderTo[fullscreen.browserProps.requestFullscreen]();
      if (promise) {
        // No dot notation because of IE8 compatibility
        promise['catch'](function() {
          alert( // eslint-disable-line no-alert
            'Full screen is not supported inside a frame.');
        });
      }
      addEvent(chart, 'destroy', fullscreen.unbindFullscreenEvent);
    }
  };

  wrap(H.Fullscreen.prototype, 'close', function(proceed) {
    proceed.apply(this, Array.prototype.slice.call(arguments, 1));
    var fullscreen = this;

    if (!isMS) {
      fullscreen.chart.setSize(void 0, fullscreen.originalHeight, false);
    }
  });

})(Highcharts)
```

**Comment by haor3** [comment] 2020-10-07 19:49
hi @raf18seb, how can I use this script in react?

**Comment by pawelfus** [comment] 2020-10-08 08:35
@haor3 - right after importing Highcharts:
```js
import Highcharts from 'highcharts';

(function(H) {
...
})(Highcharts);
```

**Comment by haor3** [comment] 2020-10-08 16:18
@pawelfus thanks but the issue still occurs

**Comment by siropkin** [comment] 2020-10-18 15:27
@raf18seb thanks for your example, works for me!

i did some changes, mostly add this:
```
// @see https://github.com/highcharts/highcharts/issues/13220
chart.pointer.chartPosition = null;
```

because i have problems with mouse position after enter in fullscreen mode.
my version:
```
export const fullscreenEventListener = (H) => {
  if (!H.Fullscreen) {
    return;
  }

  const { addEvent, wrap } = H;

  H.Fullscreen.prototype.open = function () {
    const fullscreen = this;
    const { chart } = fullscreen;
    const originalWidth = chart.chartWidth;
    const originalHeight = chart.chartHeight;

    // eslint-disable-next-line no-restricted-globals
    chart.setSize(screen.width * 0.91, screen.height * 0.91, false);
    // @see https://github.com/highcharts/highcharts/issues/13220
    chart.pointer.chartPosition = null;

    fullscreen.originalWidth = originalWidth;
    fullscreen.originalHeight = originalHeight;

    // Handle exitFullscreen() method when user clicks 'Escape' button.
    if (fullscreen.browserProps) {
      fullscreen.unbindFullscreenEvent = addEvent(chart.container.ownerDocument, // chart's document
        fullscreen.browserProps.fullscreenChange,
        () => {
          // Handle lack of async of browser's fullScreenChange event.
          if (fullscreen.isOpen) {
            fullscreen.isOpen = false;
            fullscreen.close();
            chart.setSize(originalWidth, originalHeight, false);
            chart.pointer.chartPosition = null;
          } else {
            fullscreen.isOpen = true;
            fullscreen.setButtonText();
          }
        });
      const promise = chart.renderTo[fullscreen.browserProps.requestFullscreen]();
      if (promise) {
        // No dot notation because of IE8 compatibility
        promise['catch'](() => {
          // eslint-disable-next-line no-alert
          alert('Full screen is not supported inside a frame.');
        });
      }
      addEvent(chart, 'destroy', fullscreen.unbindFullscreenEvent);
    }
  };

  wrap(H.Fullscreen.prototype, 'close', function (proceed) {
    // eslint-disable-next-line prefer-rest-params
    proceed.apply(this, Array.prototype.slice.call(arguments, 1));
    const fullscreen = this;
    fullscreen.chart.setSize(fullscreen.originalWidth, fullscreen.originalHeight, false);
    fullscreen.chart.pointer.chartPosition = null;
  });
};
```

**Comment by siropkin** [comment] 2020-10-19 13:09
And one more thing i want to tell about - workaround of scatter plot mouse positioning problems in fullscreen mode.

![image](https://user-images.githubusercontent.com/39134915/96454927-322f9080-1225-11eb-882c-327fdb6c447b.png)

I thought that I fixed this problem with:

```
// @see https://github.com/highcharts/highcharts/issues/13220
chart.pointer.chartPosition = null;
```

But I found out, that this solution not working for a scatter plot.
For  scatter you need to add this:

```
  Highcharts.Pointer.prototype.getChartPosition = function () {
    const { chart } = this;
    const { container } = chart;
    // eslint-disable-next-line no-return-assign
    return (this.chartPosition = Highcharts.offset(container));
  };
```

**Comment by amiram** [comment] 2020-12-20 22:04
I used the code from @siropkin comment. It worked partially. I have `class="d-block"` on the chart so it takes 100% of the width. However, this is causing the chart width to be as the screen width after exiting full screen. The patch makes the chart itself be in the correct width but its container, the `<highcharts-chart>` element still has the screen width. I'm using angular.
BTW, if you get that H.Fullscreen is undefined add this code before the function:
```
import Exporting from 'highcharts/modules/exporting';
Exporting(Highcharts);
```

**Comment by Blackbaud-TylerGreen** [comment] 2021-01-20 15:37
Are we going to have an official fix for this? It's very odd that fullscreen is allowed to be in a state like this.

**Comment by PaulDalek** [comment] 2021-01-22 14:28
Hi @Blackbaud-TylerGreen 

Thank you for contacting us. I have marked the issue with the `Inbox` label which means it will be raised at the next meeting. Until then, try to use one of the workarounds mentioned earlier.

**Comment by Waqar06** [comment] 2021-01-31 01:30
> `Here's a workaround snippet working on all browsers except IE. I'll investigate IE further`
> **edit**: `screen.height` works fine for IE so no browsers excluded: https://jsfiddle.net/BlackLabel/6vpgLje5/
> 
> ```js
> (function(H) {
>   var addEvent = H.addEvent,
>     isMS = H.isMS,
>     wrap = H.wrap;
> 
>   H.Fullscreen.prototype.open = function() {
>     var fullscreen = this,
>       chart = fullscreen.chart,
>       originalHeight = chart.chartHeight;
> 
>     chart.setSize(void 0, screen.height, false);
>     fullscreen.originalHeight = originalHeight;
> 
>     // Handle exitFullscreen() method when user clicks 'Escape' button.
>     if (fullscreen.browserProps) {
>       fullscreen.unbindFullscreenEvent = addEvent(chart.container.ownerDocument, // chart's document
>         fullscreen.browserProps.fullscreenChange,
>         function() {
>           // Handle lack of async of browser's fullScreenChange event.
>           if (fullscreen.isOpen) {
>             fullscreen.isOpen = false;
>             fullscreen.close();
>             chart.setSize(void 0, originalHeight, false);
>           } else {
>             fullscreen.isOpen = true;
>             fullscreen.setButtonText();
>           }
>         });
>       var promise = chart.renderTo[fullscreen.browserProps.requestFullscreen]();
>       if (promise) {
>         // No dot notation because of IE8 compatibility
>         promise['catch'](function() {
>           alert( // eslint-disable-line no-alert
>             'Full screen is not supported inside a frame.');
>         });
>       }
>       addEvent(chart, 'destroy', fullscreen.unbindFullscreenEvent);
>     }
>   };
> 
>   wrap(H.Fullscreen.prototype, 'close', function(proceed) {
>     proceed.apply(this, Array.prototype.slice.call(arguments, 1));
>     var fullscreen = this;
> 
>     fullscreen.chart.setSize(void 0, fullscreen.originalHeight, false);
>   });
> 
> })(Highcharts)
> ```

But using this snippet when you click full-screen view. It only displays a chart on the half screen.

**Comment by KacperMadej** [comment] 2021-02-01 17:33
@Waqar06 

To test a fix before it gets merged into the master branch you could use the commit hash like in this demo:
https://jsfiddle.net/BlackLabel/6vpgLje5/1/

**Closed** 2021-02-08 13:41 UTC
Labels: Product: Highcharts, Status: In progress, Type: Undecided

**Comment by stroypet** [comment] 2021-02-10 17:15
Sorry to comment here if not appropriate.

I notice this was fixed 2 days ago and I'm having the same problem right now using the React package.

Is this pushed to the latest npm package yet?

**Comment by khlieng** [comment] 2021-02-11 15:00
@stroypet no, it will probably be a few weeks until the next release.
