### ISSUE TITLE
For line chart with first value of zero, first point plotted incorrectly in some situations

### ISSUE THREAD

**Issue by rachelfreya** [highcharts/highcharts#10796] opened 2019-05-22 16:04 UTC
#### Expected behaviour
For a line chart with a first value of zero, the first point should be plotted at zero.

#### Actual behaviour
In certain cases (for example when the second value is negative but later values are positive), the first point is incorrectly plotted slightly above the zero line.

#### Live demo with steps to reproduce
https://jsfiddle.net/xyv9fg71/

#### Product version
Highcharts 7.1.1

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment] 2019-05-23 08:17
Hi @rachelfreya,
Thank you for reporting about the bug. When I run your demo I see that the point is vertically aligned in zero value.

See my screenshot below.

![Zrzut ekranu 2019-05-23 o 10 16 29](https://user-images.githubusercontent.com/2115686/58236752-dd43ce00-7d43-11e9-8b4f-8a623edcde4b.png)
![Zrzut ekranu 2019-05-23 o 10 16 25](https://user-images.githubusercontent.com/2115686/58236753-dd43ce00-7d43-11e9-9ad9-20cb82f549ff.png)


Could you take a screenshot too and post here?

Please let me know which version of OS / Chrome you have.

**Comment by rachelfreya** [comment] 2019-05-31 18:03
Chrome Version 74.0.3729.169
macOS High Sierra Version 10.13.6

![Screen Shot 2019-05-31 at 1 58 53 PM](https://user-images.githubusercontent.com/25542481/58725335-df91d200-83ac-11e9-9774-56bae1914efc.png)

**Comment by KacperMadej** [comment] 2019-06-03 15:04
Zero value position on axis as well as the series plot needs to be approximated to be displayed on a screen using pixels.

For sharp image Highcharts are rounding SVG image to full pixels, so sometimes small difference caused by those approximations are unavoidable.

Plot of the line is generated by browser and it has a positive thickness, so cannot be plotted on a mathematical zero point on a numeric scale because it has no slot width (height in case of vertical axis).

It's possible to change how ends of lines in SVG are rendered using [linecap](https://api.highcharts.com/highcharts/plotOptions.line.linecap) option.

However, the options that you might be looking for (`'butt'`) is not working - here's a workaround demo: https://jsfiddle.net/BlackLabel/ayjbc2Ls/

Please let us know if this is the option you are looking for or add an image showing how should the expected by you chart look like.

**Comment by sebastianbochan** [comment] 2019-07-04 08:41
Im closing this ticket due to inactvitation.

Please reopen if live demo and additional details will be available.

**Closed by sebastianbochan** 2019-07-04 08:41 UTC
Labels: Status: Pending reply
