### ISSUE TITLE
New highchart 7.1.0 version not worked in angular 6 project

### ISSUE THREAD

**Issue by anilshinde23** [highcharts/highcharts#10481] opened 2019-04-03 07:01 UTC
I am trying highcharts. I created new angular app via cli and installed highcharts and highcharts-angular. I copied code from their github page. In the first run i am getting following errors.

ERROR in node_modules/highcharts/highcharts.d.ts(128972,17): error TS2304: Cannot find name 'PlotNetworkDataLabelsFormatterCallbackFunction'.
node_modules/highcharts/highcharts.d.ts(128982,21): error TS2304: Cannot find name 'PlotNetworkDataLabelsFormatterCallbackFunction'.
node_modules/highcharts/highcharts.d.ts(128987,19): error TS2304: Cannot find name 'PlotNetworkDataLabelsTextPath'.
node_modules/highcharts/highcharts.d.ts(128992,15): error TS2304: Cannot find name 'PlotNetworkDataLabelsTextPath'.
node_modules/highcharts/highcharts.d.ts(136653,17): error TS2304: Cannot find name 'PlotPackedBubbleDataLabelsFormatterCallbackFunction'.
node_modules/highcharts/highcharts.d.ts(136658,15): error TS2304: Cannot find name 'PlotPackedBubbleDataLabelsTextPath'.node_modules/highcharts/highcharts.d.ts(237720,14): 
error TS2304: Cannot find name 'SeriesOrganizationNodesLayoutValues'.
I installed highcharts from npm using

npm install highcharts-angular --save

and

npm install highcharts --save

then i imported HighchartsChartModule in app.module.ts and imports array from highcharts-angular. in app.component.ts and app.component.html i added example code from their github page.

I am getting above error. Am i supposed to install any plugins or dependencies?

**Comment by TorsteinHonsi** [comment] 2019-04-03 07:28
Duplicate of #10463

**Closed by TorsteinHonsi** 2019-04-03 07:28 UTC
