### ISSUE TITLE
Rendered button with allowed HTML is not fully clickable.

### ISSUE THREAD

**Issue by magdalena-gut** [highcharts/highcharts#16808] opened 2021-12-20 17:57 UTC
#### Expected behaviour
The button click should execute a callback function.

#### Actual behaviour
The button click works only in rendered rectangle area. If a click happens in the HTML tag place (f.e. icon), the function will not be executed.

#### Demo:
https://jsfiddle.net/BlackLabel/s8mnvk0w/

**Comment by raf18seb** [comment] 2021-12-20 21:18
Hi @magdalena-gut, thanks for creating the ticket!

In my opinion it's not a bug - it's enough to set the `pointer-events` styles to `none` :
```css
div.highcharts-button span {
  pointer-events: none;
}
```

Closing as not a bug and resolved.

**Closed by raf18seb** 2021-12-20 21:18 UTC
Labels: Product: Highcharts

**Comment by magdalena-gut** [comment] 2021-12-22 08:51
Thank you @raf18seb for clarifying!
