### ISSUE TITLE
time.useUTC can only be updated once

### ISSUE THREAD

**Issue by javolio** [highcharts/highcharts#14270] opened 2020-09-25 14:25 UTC
#### Expected behaviour
Calling `chart.update({ time: { useUTC: true }})` or `chart.update({ time: { useUTC: false }})` to modify `time.useUTC` should change how the chart displays data and axes.

#### Actual behaviour
The first time that `time.useUTC` is modified, whether from true to false or false to true, the chart updates appropriately. However, subsequently updating back to the original value does not work, even though other updated changes apply.

So, if you have a chart that's initialized with `time.useUTC` as `true`, after `chart.update({ time: { useUTC: false }}); chart.update({ time: { useUTC: true }});` the chart will behave as if `time.useUTC` is `false`.

Likewise, if the chart is initialized with `time.useUTC` as `false`, after `chart.update({ time: { useUTC: true }}); chart.update({ time: { useUTC: false }});` the chart will behave as if `time.useUTC` is `true`.

There is no console output or error message.

#### Live demo with steps to reproduce
Demos:
* Demo with `time.useUTC` `true` to start: https://jsfiddle.net/msc238op/
* Demo with `time.useUTC` `false` to start: https://jsfiddle.net/2zpLk8ye/

Use the buttons below the chart to call `chart.update()`. Note that the axis and tooltips update with the first modification, but not with any subsequent modifications. The updates also modify the title so that we can see that they are going through.

#### Product version
Highcharts JS v8.2.0

#### Affected browser(s)
Chrome, Firefox, and Safari; others not tested

**Comment by pawelfus** [comment] 2020-09-25 14:32
Thanks for reporting the issue @javolio 

It's actually a duplicate of #14230 - which now is fixed and will be part of the next release.

Closing as duplicate of #14230

**Closed by pawelfus** 2020-09-25 14:32 UTC
