### ISSUE TITLE
TypeError: scroller.baseSeries is undefined (highstock v4.2.5)

### ISSUE THREAD

**Issue by LastDragon-ru** [highcharts/highcharts#5446] opened 2016-06-29 09:12 UTC
#### Expected behaviour
No error message.

#### Actual behaviour
TypeError: scroller.baseSeries is undefined

#### Live demo with steps to reproduce
http://jsfiddle.net/yk8hu4wc/

**Comment by pawelfus** [comment] 2016-06-29 10:35
Hi,

thank you for reporting the issue. It looks like it's already fixed in our master branch: http://jsfiddle.net/yk8hu4wc/1/ - fix will be included in the next release.

**Comment by jon-a-nygaard** [comment] 2016-06-29 11:26
Closing as it is a duplicate of #5323

**Closed by jon-a-nygaard** 2016-06-29 11:26 UTC
