### ISSUE TITLE
Datetime-XAxis exporting is not same as the page

### ISSUE THREAD

**Issue by Amanda949** [highcharts/highcharts#17310] opened 2022-05-19 09:02 UTC
**Steps:**
I use reflow = true to make sure my chart fit the width of the container div on resizing the window, so the XAxis will also change. But when export, different size charts exported the same XAxis, which is not same as the page shown.
For example:

1. Full-screen, my XAxis is (4.Dec, 20.Dec, 3.Jan, 31.Jan, 14.Feb, 28.Feb) [Full-screen](https://i.stack.imgur.com/GZwdf.png)

2. When export as PNG(or whatever), my XAxis is (4.Dec, 20.Dec, 3.Jan, 31.Jan, 14.Feb, 28.Feb), that's what I want. [Full-screen-export](https://i.stack.imgur.com/KaPCb.png)

3. When I zoom out of the browser, the size of the chart will also decrease, my XAxis is (Dec'21, Jan'22, Feb'22) [small-size](https://i.stack.imgur.com/uagrU.png)

4. When export as PNG(or whatever), my XAxis is (4.Dec, 20.Dec, 3.Jan, 31.Jan, 14.Feb, 28.Feb), that's not what I want, I want (Dec'21, Jan'22, Feb'22). [small-size-export](https://i.stack.imgur.com/xhcZA.png)

#### Expected behaviour
(Dec'21, Jan'22, Feb'22) type XAxis should export as  (Dec'21, Jan'22, Feb'22)

#### Actual behaviour
(Dec'21, Jan'22, Feb'22) type XAxis is exported as  (4.Dec, 20.Dec, 3.Jan, 31.Jan, 14.Feb, 28.Feb)

#### Live demo with steps to reproduce
https://jsfiddle.net/094h5wb3/

#### Product version
9.3.0

**Comment by raf18seb** [comment] 2022-05-19 14:45
Hi @Amanda949, thanks for creating the issue!

The tickPositions depend on the chart's width which is different in your browser the in the exported image generated on the server.
If you want to force displaying the same ticks, you must force the exported image's width to be the same as your chart's, see demo: https://jsfiddle.net/BlackLabel/q5k2wyz4/

Closing as not a bug. If you have any further questions, e.g. how to make it more automatic, please contact our Support Engineers on one of our dedicated support channels: https://www.highcharts.com/blog/support/

**Closed by raf18seb** 2022-05-19 14:45 UTC
