### ISSUE TITLE
Flag series markers do not display text with the latest release(v5.0.12)

### ISSUE THREAD

**Issue by bb-jessePinkman** [highcharts/highcharts#6764] opened 2017-05-24 15:56 UTC
Hey everyone, I'm currently using react-native-highcharts component to create interactive charts(Timeseries using highstocks), we were making use of flags/flag-series/flag-markers to display some information, as of today, they weren't displaying anything on click. The component react-native-highcharts uses online libraries, i.e from code.highcharts.com , and I noticed after changing the src to point to older release(4.2.2), the flags displayed the text fine.

I checked the change logs, might have missed something, please update if its a bug or something has been changed. Thanks.

#### Expected behaviour
Should display text when clicked upon.

#### Actual behaviour
Nothing is display when clicked upon.

**Comment by pawelfus** [comment] 2017-05-25 08:35
Hi @bb-jessePinkman 

Our demo works fine, take a look: http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/flags-general/ Could you update this demo to recreate issue? Otherwise it may be issue in react-native-highcharts component.

**Comment by pawelfus** [comment] 2017-05-25 08:40
Sorry, the title was misleading. I assume you mean tooltip doesn't show up. 

Demo with this issue: http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/flags-general/

**Comment by h3adache** [comment] 2017-05-25 15:59
Hi @pawelfus. I noticed this as well but why is this marked as `Can't reproduce`? The fiddle you linked shows the exact issue. Flag series text don't show up.

**Comment by h3adache** [comment] 2017-05-25 16:04
Dropping to 5.0.11 makes them appear again.

**Comment by pawelfus** [comment] 2017-05-26 09:08
Hi, it's not marked as `Can't reproduce`. Flag was added and removed, my mistake, sorry.

**Comment by h3adache** [comment] 2017-05-26 11:48
Apologies, my fault. Read it wrong.

**Comment by pldilley** [comment] 2017-05-26 15:59
The mouse events are broken too in 5.0.12.

**Comment by pawelfus** [comment] 2017-05-26 16:11
You are right. For now, please use v5.0.11.

**Comment by ff-sgupta** [comment] 2017-06-01 06:04
When is the next  release for this fix?

**Comment by pawelfus** [comment] 2017-06-05 10:31
Hi @ff-sgupta 

We don't have ETA for this issue, but I think it will be fixed in the next release.

**Closed** 2017-06-15 08:03 UTC
Labels: Fix suggested, Regression

**Comment by ff-skundalkar** [comment] 2017-06-20 05:26
Can you please let us know when can we get this fix ? This is impacting us and have an feature in escalation currently. Can you provide a hot fix to us ?

**Comment by TorsteinHonsi** [comment] 2017-06-20 08:32
The new release will be out within a few weeks. Until then, you can apply this to the source code: https://github.com/highcharts/highcharts/commit/46738ea80e9754b93417a38d565aebe1edb96844

**Comment by FlorianBurgevin** [comment] 2017-08-03 14:23
Version 5.0.14 is here but this bugs seems to be still there :(

**Comment by KacperMadej** [comment] 2017-08-03 14:54
@FlorianBurgevin Looks fine for me: http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/flags-general/

Do you have another demo that could show the problem?

Please try to make sure that newer version of Highcharts is loaded.

**Comment by FlorianBurgevin** [comment] 2017-08-03 14:56
My bad sorry !
The newer version was not loaded correctly
