### ISSUE TITLE
stock-tools-gui demo: Indicators button not working after toolbar has been toggled

### ISSUE THREAD

**Issue by cordulegaster** [highcharts/highcharts#9851] opened 2019-01-10 12:41 UTC
#### Expected behaviour
The Indicators button should always open the indicators dialog window.

#### Actual behaviour
The indicators dialog window does not open if the tool bar has been toggled at least once.

#### Live demo with steps to reproduce
https://www.highcharts.com/stock/demo/stock-tools-gui

#### Product version
Highstock 7

#### Affected browser(s)
Only tested in Chrome, Firefox

**Comment by Phazzer** [comment] 2019-01-10 13:14
Same issue with the full-screen button. Probably some/all of the other buttons too.

**Comment by KacperMadej** [comment] 2019-01-10 22:58
Hi @cordulegaster 

Thank you for reporting about the problem.

_Internal note:_
On master branch buttons don't even hide and the problem is visible.
https://jsfiddle.net/BlackLabel/ase26gfL/

**Comment by sebastianbochan** [comment] 2019-01-11 12:20
The issue is already fixed on master branch:
- https://jsfiddle.net/BlackLabel/d9w4mkhg/

Duplicate of https://github.com/highcharts/highcharts/issues/9740

**Closed by sebastianbochan** 2019-01-11 12:20 UTC
Labels: Bug, Highstock
