### ISSUE TITLE
Heatmap with Interpolation - throws uncaught RangeError: offset is out of bounds

### ISSUE THREAD

**Issue by BotanicalGarden** [highcharts/highcharts#20022] opened 2023-10-27 21:08 UTC
#### Expected behaviour
The data we are plotting on the heatmap is always sparse (there is whitespace).  Expect for the heatmap interpolation feature to work and not cause the chart render to fail.  

#### Actual behaviour
Enabling interpolation results in the following exception:
heatmap.src.js:1749  Uncaught RangeError: offset is out of bounds
    at Uint8ClampedArray.set (<anonymous>)
    at C.drawPoints (heatmap.src.js:1749:33)
    at C.render (highcharts.src.js:33499:21)
    at C.redraw (highcharts.src.js:33549:17)
    at highcharts.src.js:35561:25
    at Array.forEach (<anonymous>)
    at ea.redraw (highcharts.src.js:35559:17)
    at C.update (highcharts.src.js:34225:21)
    at HTMLInputElement.<anonymous> (show/?editor_console=:422:21)

#### Live demo with steps to reproduce

1. Load this example: https://jsfiddle.net/nv7hwe2u/2
2. Click on the interpolation checkbox and observe the exception.

#### Product version
Highcharts v11.1.0

#### Affected browser(s)
Google Chrom 11.8.0.5993.89 (Official Build) *64-bit)

**Comment by bm64** [comment] 2023-10-30 00:13
Hello @BotanicalGarden 

The bug has already been fixed on master branch and will be available with next Highcharts release. Until then, if you use Highcharts CDN, feel free to use this https://jsfiddle.net/BlackLabel/Lfqry4kv/

Closing as a duplicate of #https://github.com/highcharts/highcharts/issues/19309

**Closed by bm64** 2023-10-30 00:13 UTC
