### ISSUE TITLE
Funnel module not working with Highstock

### ISSUE THREAD

**Issue by whatthewhat** [highcharts/highcharts#6004] opened 2016-11-21 12:29 UTC
#### Expected behaviour

Funnel module works with Highstock the same way it does with Highcharts.

#### Actual behaviour

The chart does not finish rendering, an exception is raised:

![](https://d3vv6lp55qjaqc.cloudfront.net/items/3e371q3Z2h0v1y350T2L/Image%202016-11-21%20at%203.26.45%20PM.png)

#### Live demo with steps to reproduce

This is the jsfiddle from the docs where highcharts was replaced with highstock:

http://jsfiddle.net/tuxubb9j/1/

#### Affected browser(s)

Tested in Chrome 54.0.2840.98 and Safari 10.0.1

*Thanks! :)*

**Comment by pawelfus** [comment] 2016-11-21 13:17
Thanks @whatthewhat  for reporting the issue!

It's actually a duplicate of #5950.

**Closed by pawelfus** 2016-11-21 13:17 UTC
Labels: Duplicate
