### ISSUE TITLE
Series does not hide when boost module is applied

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#7089] opened 2017-08-22 13:56 UTC
#### Expected behaviour
Toggling series visibility by clicking on a legend item while boost module is applied should work.

#### Actual behaviour
Disabling series visibility by clicking on a legend item while boost module is applied does not hide series.

#### Live demos
https://jsfiddle.net/0f4rczbd/ - v5.0.12 (works)
https://jsfiddle.net/fsmkergL/ - v5.0.14 (does not work)

**Comment by KacperMadej** [comment] 2017-08-22 14:57
Duplicate of #7088

**Closed by KacperMadej** 2017-08-22 14:57 UTC
