### ISSUE TITLE
Data from one series is not combined with mapData from other series on a map chart

### ISSUE THREAD

**Issue by agrinko** [highcharts/highcharts#21647] opened 2024-08-11 18:20 UTC
#### Summary

The issue concerns "combined maps" feature mentioned in this doc: https://www.highcharts.com/docs/maps/map-collection#combine-maps

I wanted to combine USA and Canada maps, so I added two series: one with `mapData` for Canada, another one - for USA. It worked fine. But then I wanted to add a third series object with data for all states combined (including USA and Canada states). And I couldn't achieve that.

#### Expected behaviour

Data from the third series should be projected onto the map objects from the previous series, provided that `joinBy` option is set properly.

#### Actual behaviour

It shows an empty map.

#### Live demo with steps to reproduce

https://jsfiddle.net/AGrinko/th7fxwa4/7/

Created it based on JSFiddle from the aforementioned document.

Try removing the first or second series object - it doesn't affect anything.
Then try adding `chart: { map: ca }` to the chart options, and you'll see British Columbia (in Canada) being highlighted.

I also tried adding `allAreas: false` to the last series object, as well as specifying `index` option to make sure grey areas are not just covering highlighted areas - no difference.

So it appears like `joinBy` only joins data with the global map in the chart options (or with `mapData` in the same series object), but not with `mapData` from other series. But there's no way to provide multiple maps in `chart.map` object, is there?

#### Product version
Highmaps v11.4.6

#### Affected browser(s)
Google Chrome.
Although it doesn't seem to be browser-specific.

**Comment by hubertkozik** [comment] 2024-08-12 08:27
Hi @agrinko! Thanks for contacting us. As you said, `joinBy` option only joins data with the global map and the map from `mapData` from the same series.  You cannot set data in third series, when `mapData` is set only in the first and second series. 

If you want to use only one data for multiple series, you can use the same data like in this demo: https://jsfiddle.net/BlackLabel/yt4752bv/ 

I don't see any issue here, this is how `joinBy` and handling `mapData`s logic is implemented, closing as not a bug.

**Closed by hubertkozik** 2024-08-12 08:27 UTC
Labels: Type: Not a bug

**Comment by agrinko** [comment] 2024-08-12 09:17
@hubertkozik , ok, thanks for confirmation. I thought `joinBy` would merge map areas across all series.

But that means there's no convenient way to provide multiple map sources for multiple series. 

Imagine this totally-real-life scenario: we have data for many states across countries, and those states are split into series by some business rule. E.g. we have **3 tiers,** and each state belongs to one of the tiers. We want to show 3 series on the map - one for each tier. And we have separate state maps for USA, Canada, Mexico, etc. 

As `mapData` for each series can contain only one Topology object, we can't provide multiple map sources for each series. That would mean that we either have to create more series (one for each country+tier combination), or we have to create a custom topo JSON which would combine all states on a single map.

I would like to have flexibility to set multiple map sources in `mapData` (as an array of Topology objects) for each series, or for the `chart.map` configuration. In that case I wouldn't worry about splitting series by country, and could focus on splitting series logically (by tiers); each series would pick up the corresponding geographical object from the array of topologies.

Does it sound like a valid feature request? I can post it separately in that case.

**Comment by KacperMadej** [comment] 2024-08-14 15:22
Hi @agrinko 

> As mapData for each series can contain only one Topology object, we can't provide multiple map sources for each series.

Multiple map sources can be merged and all should be joined just fine as long as the properties are unique.

```js
    const map = Highcharts.geojson(ca).concat(Highcharts.geojson(us));
```

https://jsfiddle.net/BlackLabel/4stpv19y/1/

> Does it sound like a valid feature request? I can post it separately in that case.

Yes, it does.
