### ISSUE TITLE
Tickpositions - zoom prints labels out of plotarea

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4086] opened 2015-04-10 08:46 UTC
Example: http://jsfiddle.net/ascholz81/173cnqn3/2/

If we remove tickPositions or minRange, then all works properly.

**Comment by highslide-software** [comment] 2015-06-09 14:02
It also happens when minRange is not set - http://jsfiddle.net/highcharts/mx5jh9mx/1/.

**Comment by highslide-software** [comment] 2015-06-10 06:53
A possible fix would be to strip out all ticks in the trimTicks method: http://jsfiddle.net/highcharts/mx5jh9mx/2/

But even then, we get the same problems when we set `startOnTick` or `endOnTick` to true. The problem is basically that we expect the ticks to be trimmed at the time of generation.

The original example can be resolved by using a simple `tickInterval` option: http://jsfiddle.net/highcharts/173cnqn3/3/

More complex cases can be resolved by a `tickPositioner` callback, that takes the axis.min and axis.max into consideration: http://jsfiddle.net/highcharts/173cnqn3/4/

**Comment by ascholz81** [comment] 2015-07-08 15:47
Sorry for the delay in response.  I implemented the tick positioner solution and the ticks are no longer rendering at the extremes of the chart area.

**Comment by sebastianbochan** [comment] 2015-10-09 13:14
+1

**Comment by kzoon** [comment] 2016-01-04 14:20
I just ran into this problem. I rely heavily on tickPositions to control my tick marks and just noticed that axis labels are rendered to the right of the plot arera when I apply zoom:
http://jsfiddle.net/vgyoss6k/2/

I really hope this issue is resolved soon.
In the mean time I will try to create a workaround based on tickPositioner,

**Closed** 2016-01-05 11:49 UTC
Labels: Bug
