### ISSUE TITLE
Highcharts Annotations Not Rendering Correctly Given 'Distance' parameter

### ISSUE THREAD

**Issue by terryaney** [highcharts/highcharts#8373] opened 2018-05-23 19:41 UTC
#### Expected behaviour

When the chart renders, the little blue cross should have a top of 297px.

#### Actual behaviour

The first time the chart renders, it has a top of 310px;

#### Live demo with steps to reproduce

http://jsfiddle.net/jxpvrjta/13/

1. If you open a new window and paste in fiddle, you'll get a top of 310.
2. If you then click in the address bar and press Enter key to issue a GET again, the top 'fixes' itself and you will then have 297.

Try this without opening inspection window first and just notice the difference between x-axis and the annotation.  I can't pinpoint the behavior exactly and when highcharts fixes the top rendering.  Resizing the browser window fixes it sometimes.  Sometimes, clicking the 'Run' button in fiddle fixes it.
 
#### Product version

Latest stable versions from code.highcharts.com

#### Affected browser(s)

All.

**Comment by sebastianbochan** [comment] 2018-05-24 07:47
Hi @terryaney,
Thank you for reporting.

@morganfree any comments?

**Comment by kamilkulig** [comment] 2018-05-24 09:01
Duplicate of: https://github.com/highcharts/highcharts/issues/7468

**Closed by kamilkulig** 2018-05-24 09:01 UTC
