### ISSUE TITLE
Trendline is not a straight line

### ISSUE THREAD

**Issue by K009** [highcharts/highcharts#19809] opened 2023-09-21 08:42 UTC
#### Expected behaviour
Trendline should be a straight line.

#### Actual behaviour
Trendline is not a straight line.

#### Live demo with steps to reproduce
https://jsfiddle.net/4cwobzrv/1/

#### Product version
Highcharts v11.1.0

#### Affected browser(s)
All

**Comment by bm64** [comment] 2023-09-21 23:58
Closing as a duplicate of https://github.com/highcharts/highcharts/issues/19793

**Closed by bm64** 2023-09-21 23:58 UTC
Labels: Type: Bug, Product: Highcharts Stock
