### ISSUE TITLE
cannot read property 'series' of undefined 

### ISSUE THREAD

**Issue by ashritha-singu** [highcharts/highcharts#16903] opened 2022-01-20 02:33 UTC
I keep getting 'series' undefined error while hovering over the char. It is exactly happening where I try to update state values in the component in mouse event handle function

Unable to reproduce in JSBin

```
plotOptions: {
      column: {
        point: {
          events: {
            mouseOver: eventsMouseOverHandler,
          },
        },
        states: {
          hover: {
            color: highchartsThemeColors.columnHoverColor,
          },
        },
      },
    },
```
```
const eventsMouseOverHandler: Highcharts.PointMouseOverCallbackFunction = React.useCallback((event: Event) => {
    const { x: pointX = null, y: pointY = null } = (event.target as unknown as HighchartsPoint) || {};
        setX(pointX);
        setY(pointY);
   }, [setX, setY]);
```

**Comment by raf18seb** [comment] 2022-01-20 12:45
Closing as a duplicate of https://github.com/highcharts/highcharts-react/issues/353

**Closed by raf18seb** 2022-01-20 12:45 UTC
