### ISSUE TITLE
Cannot read property 'charAt' of undefined

### ISSUE THREAD

**Issue by olton** [highcharts/highcharts#5215] opened 2016-04-14 12:57 UTC
Cannot read property 'charAt' of undefined

**hightcharts.js line 11391**

change

alignment = options.align.charAt(0) + options.verticalAlign.charAt(0) + options.layout.charAt(0);

to 

alignment = (options.align != undefined ? options.align.charAt(0) : "c") + (options.verticalAlign != undefined ? options.verticalAlign.charAt(0) : "c") + (options.layout != undefined ? options.layout.charAt(0) : "c");

#### Affected browser(s)
Chrome, Firefox, IE, Edge

**Comment by pawelfus** [comment] 2016-04-14 13:11
Thank you for reporting! Could you post jsfiddle with the issue?

**Comment by billystalnaker** [comment] 2016-05-10 15:53
Yes, this should be fixed. But a way to get around it is to use legend:{enabled:false} instead of legend:false

**Comment by olton** [comment] 2016-05-10 16:15
@billystalnaker  I agree, but then the error should be more elaborate. Otherwise it is not clear where and what to fix in project.

**Comment by billystalnaker** [comment] 2016-05-10 16:30
Totally, it took me a while to debug. And usually highcharts is good about giving you error messages that you can view on their site. And your code does fix the issue, I tried it as well.

**Comment by TorsteinHonsi** [comment] 2016-05-11 06:58
Thanks for your comments guys, note that this issue is tagged "pending reply" because we couldn't reproduce it. So it turns out `legend: false` is the problem.

#### Live demo
http://jsfiddle.net/highcharts/qkvkdhr3/

Under any circumstance, `false` is not a valid setting for the legend option, it should be an object. So strictly speaking it is a misconfiguration. But since it's a bit harsh to crash over a misconfiguration, we'll provide a fix.

**Closed** 2016-05-11 07:02 UTC
Labels: Bug

**Comment by billystalnaker** [comment] 2016-05-11 13:11
Awesome! Thanks @TorsteinHonsi and @olton !!
