### ISSUE TITLE
HighchartsReact: ReferenceError: Highcharts is not defined

### ISSUE THREAD

**Issue by besrezen90** [highcharts/highcharts#13721] opened 2020-06-15 15:01 UTC
#### Actual behaviour

Hi! Please help me solve the problem. Errors started appearing when rendering React components with graphs (only type "Pie"):

`
ReferenceError: Highcharts is not defined 2 highcharts.js:473:473
    drawEmpty highcharts.js:473
    redrawPoints highcharts.js:474
    render highcharts.js:408
    renderSeries highcharts.js:332
    forEach self-hosted:225
    renderSeries highcharts.js:331
    render highcharts.js:334
    firstRender highcharts.js:337
    init highcharts.js:308
    fireEvent highcharts.js:32
    init highcharts.js:306
    getArgs highcharts.js:306
    C highcharts.js:306
    chart highcharts.js:338
    React 9
    commitRootImpl self-hosted:948
    unstable_runWithPriority scheduler.development.js:653
    React 4
    performSyncWorkOnRoot self-hosted:891
    flushSyncCallbackQueueImpl React
    unstable_runWithPriority scheduler.development.js:653
    React 2
    workLoop scheduler.development.js:597
    flushWork scheduler.development.js:552
    performWorkUntilDeadline scheduler.development.js:164
`

#### Product version
`        "highcharts": "^8.1.1",
        "highcharts-react-official": "^3.0.0",
`

#### Affected browser(s)
FF: 77.0.1,
Chrome:  83.0.4103.97

**Comment by sebastianbochan** [comment] 2020-06-16 07:53
Hi @besrezen90,
Thank you for reporting. The issue has been already reported and fixed on the master branch.

Im closing the ticket as duplicate of https://github.com/highcharts/highcharts/issues/13710

**Closed by sebastianbochan** 2020-06-16 07:53 UTC
