### ISSUE TITLE
Not Aligning Label Component in Bar Chart Rendering via Portal

### ISSUE THREAD

**Issue by Satyam7Jha** [highcharts/highcharts#19877] opened 2023-10-05 05:19 UTC
## Description

In the provided [example](https://codesandbox.io/s/highcharts-react-demo-forked-56crg6?file=/demo.jsx:1026-1044), we implemented a column chart where the `label component` was rendered with proper alignment. However, when we switched the chart type from column to bar, the label component no longer aligned correctly.

## Steps to reproduce

1. Set up a column chart as described in the [linked example](https://codesandbox.io/s/highcharts-react-demo-forked-56crg6?file=/demo.jsx).
2. Observe how the `label component` is correctly aligned.
3. Change the chart type from column to bar.
4. Note that the `label component` fails to align properly [exapmle](https://codesandbox.io/s/highcharts-react-demo-forked-8slsh8?file=/demo.jsx). 

## Expected Behavior

When changing the chart type from column to bar, the `label component` should remain properly aligned, similar to the column chart rendering.

## Actual Behavior

In the bar chart rendering, the `label component` is not properly aligned.

## Relevant Screenshots 
Aligned in Column
<img width="707" alt="image" src="https://github.com/highcharts/highcharts-react/assets/75986382/759f8bbe-ff4a-456d-8af8-e9e2c0df019b">
NotAligned in Bar
<img width="433" alt="image" src="https://github.com/highcharts/highcharts-react/assets/75986382/5a625bac-0737-4586-ad8e-fb39572804c1">

**Comment by bm64** [comment] 2023-10-05 22:34
Closing as a duplicate of https://github.com/highcharts/highcharts-react/issues/435
Solution: https://codesandbox.io/s/highcharts-react-demo-1-9s7pyq?file=/demo.jsx

**Closed by bm64** 2023-10-05 22:34 UTC
