### ISSUE TITLE
Zoom issue in Multi Panes with Stack

### ISSUE THREAD

**Issue by shafaqkazmi** [highcharts/highcharts#10236] opened 2019-03-01 07:18 UTC
#### Expected behaviour
When a multiple panes with stack is zoomed, it does not zoom precisely and go out of bound for max and min values.

#### Actual behaviour
Zooming a multiple bar graph should zoom all graphs to zoom for only that scale.

#### Live demo with steps to reproduce
http://jsfiddle.net/Lkm0qxb3/1/
In fiddle when user uses zoom functionality it broke other graphs view completely. I am currently using highcharts with angular.

#### Product version
highcharts: 6.2.0
angular-highcharts: 5.2.13

#### Affected browser(s)
All

**Comment by khan8698** [comment] 2019-03-01 07:18
+1

**Comment by sebastianbochan** [comment] 2019-03-01 07:49
Hi @shafaqkazmi,
Thank you for reporting.

Simplified demo:
- http://jsfiddle.net/BlackLabel/ewmj8r1f/

**Internal note:**
Looks like related with the bug: https://github.com/highcharts/highcharts/issues/1289

**Comment by pawelfus** [comment] 2019-03-01 10:27
This is a duplicate of #1289 - fixed on the master branch: http://jsfiddle.net/BlackLabel/xdeawczu/ - selecting range on a specific pane zooms only in that yAxis, not affecting others.

Note, there's still another issue (#7711) - that causes points (candles, columns, ohlc) to render outside the pane.

**Closed by pawelfus** 2019-03-01 10:27 UTC
Labels: Bug
