### ISSUE TITLE
Highcharts-more.js with highstock Error

### ISSUE THREAD

**Issue by bc150400212** [highcharts/highcharts#6092] opened 2016-12-06 07:55 UTC
When i try to use highcharts-more.js with highstocks.js its comes with this error

`Uncaught TypeError: seriesType is not a function`

Sources are like:

  ```
  <script src="{% static 'vendor/highstock.src.js' %}" type="text/javascript"></script>
    <script src="http://code.highcharts.com/highcharts-more.src.js"></script>
    <script src="{% static 'vendor/highcharts-ng.js' %}"></script>
```

**Comment by oysteinmoseng** [comment] 2016-12-06 08:48
Using stock with highcharts-more seems to work here. http://jsfiddle.net/1qunLb4d/

Can you reproduce this in a jsFiddle?

**Comment by TorsteinHonsi** [comment] 2016-12-06 10:29
Also make sure you are running the same version of the two files.

**Comment by sebastianbochan** [comment] 2016-12-06 11:45
Tested with highcharts-ng and still works: http://jsfiddle.net/yo85vkap/

**Comment by TorsteinHonsi** [comment] 2016-12-12 11:49
I'm closing this due to lack of preproduction steps. Please reopen if necessary.

**Closed by TorsteinHonsi** 2016-12-12 11:49 UTC
Labels: Cant reproduce, Pending reply
