### ISSUE TITLE
HighStock stockchart YTD does not work properly 

### ISSUE THREAD

**Issue by dkodedara** [highcharts/highcharts#13417] opened 2020-05-03 09:24 UTC
#### Expected behaviour
Data should be shown from start of the current year to current date.

#### Actual behaviour
clicking on YTD shows past year data in zommed in chart.

#### Live demo with steps to reproduce
https://jsfiddle.net/dkodedara/hbwkgemz/

**Comment by dkodedara** [comment] 2020-05-03 09:26
AdjustForMinRange gets the correct date as 1 Jan 2020 but there is an issue in calculation logic inside function adjustForMinRange, this only happens when current year data is less than 5..
in my example above in jsfiddle it has only two data for 2020.

**Comment by sebastianbochan** [comment] 2020-05-04 10:49
Hi @dkodedara,
Thank you for reporting about the problem. The YTD sets extremes based on minRange param on xAxis. The minRange is calculated according to your data points differences. 

When you declare "smaller" minRange which is i.e 1 month, then the YTD works properly.

Demo:
- https://jsfiddle.net/BlackLabel/rq95t28j/

Docs:
- https://api.highcharts.com/highstock/xAxis.minRange

Im closing the ticket as not a bug.

**Closed by sebastianbochan** 2020-05-04 10:49 UTC
Labels: Type: Not a bug

**Comment by dkodedara** [comment] 2020-05-04 12:51
@sebastianbochan Thanks for your quick reply. My apologies I missed below quoted part in API docs as well as while debugging function adjustForMinRange :(

> "The default minRange for the x axis is five times the smallest interval between any of the data points."

**Comment by sebastianbochan** [comment] 2020-05-04 13:38
You're welcome.
