### ISSUE TITLE
The chart description text display incomplete when the text is longer

### ISSUE THREAD

**Issue by charpty** [highcharts/highcharts#6864] opened 2017-06-19 07:44 UTC
#### Expected behaviour
Even if the pie chart description text longer also complete display the text

#### Actual behaviour
The text is not fully displayed

#### Error scene screenshot
![textdisplayincomplete](https://user-images.githubusercontent.com/8869963/27274470-03f5ef5a-5506-11e7-8e03-a859eb37d6fb.png)

#### Affected browser(s)
iphone

**Comment by sebastianbochan** [comment] 2017-06-19 08:17
Hi @charpty 

Duplicate of https://github.com/highcharts/highcharts/issues/1581

**Workaround**
Set [useHTML](http://api.highcharts.com/highcharts/plotOptions.series.dataLabels.useHTML) parameter as true and declare width of labels.

**Closed by sebastianbochan** 2017-06-19 08:17 UTC

**Comment by charpty** [comment] 2017-06-19 08:20
@sebastianbochan ok, then I will try.
Thanks for reminding.
