### ISSUE TITLE
Missing ticks for DST time change.

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#7170] opened 2017-09-20 14:01 UTC
#### Expected behaviour
Highcharts should display ticks for whole xAxis during a DST time change. 

#### Actual behaviour
Highcharts is not displaying correct ticks during a DST time change. 

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/Lpp1u8ts/3/

![screen shot 2017-09-20 at 16 00 29](https://user-images.githubusercontent.com/15050812/30647849-dac90be8-9e1c-11e7-9157-2972fdc624b4.png)

**Comment by TorsteinHonsi** [comment] 2017-09-25 13:25
It's a regression since v5.0.11 (d8905421c). Related to #6636 and #6278 which both deal with the same problem in various ways.

**Comment by mcapewell** [comment] 2018-01-10 17:25
Is there any update on this bug?

**Comment by TorsteinHonsi** [comment] 2018-01-15 10:35
Thank you for your patience! I'm refactoring the time handling and this case is now resolved internally. Expect the changes to be published with the next maintenance release.

**Comment by TorsteinHonsi** [comment] 2018-01-15 14:49
Fixed with #7666.

Demo with the fix applied: https://jsfiddle.net/highcharts/Lpp1u8ts/4/

**Closed by TorsteinHonsi** 2018-01-15 14:49 UTC
Labels: Bug, Regression
