### ISSUE TITLE
Javascript Error in WKHTMLTOPDF/QT Browser

### ISSUE THREAD

**Issue by petewulf** [highcharts/highcharts#13535] opened 2020-05-15 16:52 UTC
Hi guys,

since the last update of the CDN to 8.1.0 Highcharts in WkhtmltoPdf stopped working and only shows a blank area due to the following javascript error (reproducable in QT Webbrowser):

**highcharts.js:264
TypeError: 'undefined' is not a function (evaluating 'this.onContainerMouseDown.bind(this)')**

Switching back to Version 7.x solved the problem temporarily.

#### Product version
Highcharts V 8.1.0  (Latest CDN)

#### Affected browser(s)
WKhtmltoPdf / QTWeb

Thanks!

**Comment by sebastianbochan** [comment] 2020-05-18 07:37
Hi @petewulf,
Thank you for reporting. The issue has been already reported and is a bug in wkhtmltopdf.

Im closing the case as duplicate of https://github.com/highcharts/highcharts/issues/13457

**Closed by sebastianbochan** 2020-05-18 07:37 UTC
