### ISSUE TITLE
Column chart spacing isn't consistency 

### ISSUE THREAD

**Issue by ncoquelet** [highcharts/highcharts#5447] opened 2016-06-29 09:31 UTC
I have a series chart that show the evolution of two values in to a column chart.
With lots of values, ~50, We can see that spacing of columns inside a group is not the same into each group and is not the same between each group.

The result is little ugly.

We can play with borderWidth, pointPadding or groupPadding, to try to find an acceptable renderring, but the problem still the same

Demo : http://jsfiddle.net/cxLojhfm/embedded/result/
same spacing problem without group : http://jsfiddle.net/7u7L33hc/

All browsers are affected
Thanks

**Comment by jon-a-nygaard** [comment] 2016-06-29 11:17
Closing this as it is a duplicate of #2690

**Closed by jon-a-nygaard** 2016-06-29 11:17 UTC
Labels: Undecided

**Comment by ncoquelet** [comment] 2016-06-29 11:35
I searched this issue without find it.
Thanks
