### ISSUE TITLE
Treegraph: TypeError: Cannot read properties of undefined (reading 'x')

### ISSUE THREAD

**Issue by artzub** [highcharts/highcharts#19638] opened 2023-08-28 12:44 UTC
#### Actual behaviour
I crossed with a problem that sometimes Treegraph chart crashes after `setData`

```
Uncaught TypeError: Cannot read properties of undefined (reading 'y')
    at TreegraphSeries.onSeriesAfterGeneratePoints (highstock.src.js:45856:1)
    at highstock.src.js:1748:1
    at Array.forEach (<anonymous>)
    at fireEvent (highstock.src.js:1745:1)
    at TreegraphSeries.generatePoints (highstock.src.js:32552:1)
    at TreegraphSeries.generatePoints (highstock.src.js:47125:1)
    at TreegraphSeries.<anonymous> (highstock.src.js:914:1)
    at TreegraphSeries.h (boost.src.js:2976:1)
    at obj.<computed> (highstock.src.js:912:1)
    at TreegraphSeries.translate (highstock.src.js:32693:1)
```

After digging around the problem, I found that `series.points` has empty items: `[TreegraphPoint, empty x 5, TreegraphPoint]`

![image](https://github.com/highcharts/highcharts/assets/134249/45243a1a-d309-4476-ab90-12848916cc3e)

In the screenshot, the array's length is 56, but really, the array has only 44 not empty items.

#### Live demo with steps to reproduce
[Reproduce bug](https://jsfiddle.net/3fcvyu1o/)  
Uncomment line 53 to apply the workaround.

#### Workaround
I add my `onSeriesAfterGeneratePoints` in the first position to events array of `afterGeneratePoints` in order to clear `series.points` array from empty items.
```javascript
const onSeriesAfterGeneratePoints = function () {
  if (this.type !== 'treegraph' || !this.points?.length) {
    return;
  }

  this.points = this.points.filter(Boolean);
  this.data = this.data.filter(Boolean);
};

const fixEmptyPointsTreegraphSeries = (H) => {
  H.addEvent(
    H.Series.prototype,
    'afterGeneratePoints',
    onSeriesAfterGeneratePoints,
    { order: -1 },
  );
};

fixEmptyPointsTreegraphSeries(Highcharts);
```

But the workaround doesn't work clearly, because some artifacts appear on the chart, e.g. dead links.

#### Product version
Highcharts: 11.1.0

**Comment by pawellysy** [comment] 2023-08-30 07:27
Hi @artzub Thanks for reporting the issue!

There seems to be a problem with updates, and correctly deleting the points from the array. For now, your workaround does the job, thanks for the idea! We'll search for a permanent solution.

**Comment by MarkusBarstad** [comment] 2024-01-23 09:13
I cannot seem to reproduce this issue in 11.3.0 🤔  The demo does not crash on me so I assume this is fixed and I close this issue.

**Closed** 2024-01-23 12:25 UTC
Labels: Type: Bug, Product: Highcharts, Status: Has workaround
