### ISSUE TITLE
Stacks label misplaced on bar charts

### ISSUE THREAD

**Issue by Glenfiddish** [highcharts/highcharts#8265] opened 2018-05-02 12:04 UTC
#### Expected behavior
stack label show in correct position

#### Actual behaviour
stack label show misplaced

#### Live demo with steps to reproduce
template: http://jsfiddle.net/EdwinLai927/evfkzs0g/2/

#### Product version
Version: 6.1.0

#### Affected browser(s)
all

**Comment by KacperMadej** [comment] 2018-05-02 18:09
Hi @Glenfiddish ,

Thank you for reporting about the regression.

As a temporary workaround you could:
* use version 6.0.7 (lest working version): http://jsfiddle.net/BlackLabel/evfkzs0g/6/
* or set the categorized axis on the opposite side: http://jsfiddle.net/BlackLabel/evfkzs0g/5/

_Internal notes:_ 
Regression caused by https://github.com/highcharts/highcharts/commit/558e667 
Inverted chart uses horizontal space to adjust vertical position for stackLabels - http://jsfiddle.net/BlackLabel/xxv98qrn/

**Comment by ppotaczek** [comment] 2018-05-04 05:49
Duplicated of #8187.
This problem is already fixed on master branch.

**Closed** 2018-05-04 05:53 UTC
Labels: Duplicate, Regression

**Comment by Glenfiddish** [comment] 2018-05-07 04:19
thanks for helping and explanation @KacperMadej @ppotaczek
