### ISSUE TITLE
Unable to zoom the map with the mouse wheel.

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#16180] opened 2021-08-11 09:33 UTC
#### Expected behaviour
Being able to zoom using the mouse wheel.

#### Actual behaviour
Unable to zoom the map with the mouse wheel.
The last working version is 9.0.1.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/jnvxrcL5/

#### Product version
From 9.1.0 version

#### Affected browser(s)
All

**Comment by raf18seb** [comment] 2021-08-11 17:07
Hi @karolkolodziej, thanks for reporting! Could you please check whether this is a mac/Windows issue? Probably related to https://github.com/highcharts/highcharts/issues/15656

**Comment by raf18seb** [comment] 2021-08-12 08:50
Closing as a duplicate of https://github.com/highcharts/highcharts/issues/15656

**Closed by raf18seb** 2021-08-12 08:50 UTC
Labels: Product: Highcharts Maps, Type: Duplicate
