### ISSUE TITLE
400 Bad Request Error When Using export.highcharts.com with Valid JSON Data

### ISSUE THREAD

**Issue by lustmordtheblackpost** [highcharts/highcharts#20478] opened 2024-01-19 11:35 UTC
The export.highcharts.com service should process the provided JSON configuration for a pie chart and return a chart image or a success response without any errors.

When sending a valid JSON configuration to the export.highcharts.com service, it returns a 400 Bad Request error, suggesting an issue with the request format or the JSON data. However, the JSON data is structured correctly and adheres to the Highcharts format requirements.

Prepare the following JSON configuration for a Highcharts pie chart:
```
{
  "chart": {
    "type": "pie"
  },
  "title": {
    "text": "Traffic Distribution"
  },
  "series": [{
    "name": "Traffic",
    "data": [
      ["Direct", 58.9],
      ["Social Media", 13.29],
      ["Search Engines", 13],
      ["Referrals", 4.78],
      ["Advertisements", 10.03]
    ]
  }]
}
```
Send this JSON to the export.highcharts.com service.
Observe the response, which is a 400 Bad Request error.

The issue is specifically with the export.highcharts.com service.

The issue seems to be related to a server-side error and is not browser-specific. Tested on Chrome 120.0.6099.217

**Comment by derhecht** [comment] 2024-01-19 12:59
btw it looks like this error is occurring since days...

**Comment by iceteabottle** [comment] 2024-01-22 09:25
<img width="662" alt="Bildschirmfoto 2024-01-19 um 09 49 43" src="https://github.com/highcharts/highcharts/assets/13260952/87e5cbfc-6011-4b5f-a121-dcdee2a65d3d">

Btw. that error seems to be related. I always get this error or with changed data the 400 bad request error...

**Comment by karolkolodziej** [comment] 2024-01-22 12:17
We are currently experiencing instability issues with the export server. This leads to an abundance of 400 returns when attempting exports from either the data module in Highcharts, or when doing exports using the API. We are analyzing logs attempting to find the root cause of the issues. 

We apologize for the inconvenience and are doing everything we can to get this resolved ASAP. 

As a workaround for now (if possible) you can use the offline exporting- [docs](https://www.highcharts.com/docs/export-module/client-side-export).

**Comment by vishal-Sharma-netomi** [comment] 2024-01-25 10:22
Hi @karolkolodziej Are we planning to fix  this issue? When can we expect fixes of this.
Thanks alot.

**Comment by sergei-lobanov** [comment] 2024-01-25 12:52
Hi all, any updates on this issue? export stopped to work, its a critical issue for us, any ETA to fix it?

![ScreenShot 25012024--at 13 50 07@2x](https://github.com/highcharts/highcharts/assets/61283963/604e2cc1-e55e-4c62-ad52-1b3eb7fa6dc8)

If you check https://export.highcharts.com/ it doesn't work there is well, its affecting all users.
The temporary solution doesn't work for us, its required more time to implement and configure offline export tool.

**Comment by jakubSzuminski** [comment] 2024-01-25 20:10
Thanks for reporting and you're absolutely right.

We're working hard to get rid of all the issues related to exporting. We have redeployed our Export Server today and it seems to be working well again. We're doing our best to make it stable so that these issues do not appear again.

Apologies for the inconvenience.

**Comment by oysteinmoseng** [comment] 2024-01-26 15:32
Closing this one as duplicate of #20376 for now, but happy to reopen if one does not cover the other.

**Closed by oysteinmoseng** 2024-01-26 15:32 UTC
Labels: Type: Bug, Product: Highcharts
