### ISSUE TITLE
UI seems to be broken on resize.

### ISSUE THREAD

**Issue by AnanditaP** [highcharts/highcharts#10805] opened 2019-05-23 09:38 UTC
Please find detailed information inside attached document. Here, trying to set height of rows of chart by setting chartHeight. 

[HighGanttPOCIssue3.docx](https://github.com/highcharts/highcharts/files/3211344/HighGanttPOCIssue3.docx)

**Comment by raf18seb** [comment] 2019-05-23 14:38
Hi @AnanditaP, 

It's actually duplicate (additional info) of #10781 
I will add a comment to that thread. In case of any questions, please continue in a mentioned ticket to avoid further duplications.

**Comment by raf18seb** [comment] 2019-05-23 14:39
Duplicate of #10781

**Closed** 2019-05-23 14:40 UTC
Labels: Type: Duplicate
