### ISSUE TITLE
Drag the map vertically

### ISSUE THREAD

**Issue by christjohannes** [highcharts/highcharts#13093] opened 2020-03-05 14:46 UTC
In Highmaps the user can click and drag the map horizontally but not vertically as expected: https://medien.lb.madsack.de/rnd/jchrist/coronaeuropakarte.html

**Comment by sebastianbochan** [comment] 2020-03-05 15:02
Hi @chetansastry,
Thank you for the reporting about the problem. The issue has been already reported and is in process of testing and verification.

Im closing the ticket as duplicate of https://github.com/highcharts/highcharts/issues/12671

**Closed by sebastianbochan** 2020-03-05 15:02 UTC
