### ISSUE TITLE
Error in rendering drilldown map

### ISSUE THREAD

**Issue by RishJ08** [highcharts/highcharts#16866] opened 2022-01-08 08:09 UTC
Getting the following error, when performing the drilldown action. It comes out with this error and the UI displays a blank screen.
The same piece of code has been working since the April 2020. Only from the past few weeks or so, it has become an issue.

Uncaught TypeError: Cannot read properties of undefined (reading 'setAttribute')
    at b.step (highmaps.src.js:51700)
    at k.update (highmaps.src.js:7339)
    at k.step (highmaps.src.js:7439)
    at Array.e (highmaps.src.js:7361)
    at x (highmaps.src.js:7367)

**Comment by raf18seb** [comment] 2022-01-10 13:10
Hi @RishJ08, thank you for contacting us.

Could you provide more info about your issue? Online jsFiddle demo showing the problem would be perfect. Thank you in advance.

**Comment by liux** [comment] 2022-01-27 06:14
Hi @raf18seb ,
I had the same problem. Please see below, I use the stackblitz online demo to demonstrate this problem.
This problem appeared after I upgraded highcharts to version 9.3.2. But v9.2.2 of highcharts is fine.
[https://stackblitz.com/edit/angular-9-20200529-ku4ekw?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-9-20200529-ku4ekw?file=src/app/app.component.ts)

**Comment by liux** [comment] 2022-01-27 06:22
If I turn off the animation, it works fine in version 9.3.2.

**Comment by raf18seb** [comment] 2022-01-31 12:05
Hi, could you simplify and reproduce your issue in pure JavaScript, please? You can base on this demo (basic drilldown is working fine): https://jsfiddle.net/BlackLabel/bpan0fyq/

**Comment by asiddh** [comment] 2022-11-18 13:22
> https://stackblitz.com/edit/angular-9-20200529-ku4ekw?file=src/app/app.component.ts

thanks very much, i wasted too much time only to find out it can be fixed by turning animation off.

**Comment by KacperMadej** [comment] 2022-12-30 15:40
Unable to recreate. Closing due to inactivity.

**Closed by KacperMadej** 2022-12-30 15:40 UTC
Labels: Status: Can't reproduce, Status: Pending reply
