### ISSUE TITLE
Navigator ignore min and max data

### ISSUE THREAD

**Issue by 4epToB** [highcharts/highcharts#17398] opened 2022-06-16 07:20 UTC
#### Expected behaviour
This is most likely not a bug, but I expected it to work.

I have set еру data from 2007 to 2014 year ,but graph and navigator has min date 2002 year. 
I was expecting the plot to be wider than data with  whitespace at the start (from 2002 to 2007), but the  plot and navigator's width became equal to the data. I need it to place the remaining data from 2002 to 2007 later.

How can i do this?

P.S. Cant register on your forum, he said that i am marked as spammer. Don't know where else to ask. Thank you!

#### Live demo with steps to reproduce

https://jsfiddle.net/4erptob/qd5voj87/2/

#### Product version

seems it any versions, but i use "highcharts": "7.1.1", "highcharts-vue": "1.3.2" + stock

**Comment by raf18seb** [comment] 2022-06-17 12:59
Hi @4epToB, thanks for contacting us with your question.

If you have problems with our Forum, you can ask your questions on StackOverflow (add the `highcharts` tag and our support engineers will answer), or you can email us. More info: https://www.highcharts.com/blog/support/

I agree, this is not a bug. You can achieve this effect by adding a fake, unvisible point in 2002, see demo: https://jsfiddle.net/BlackLabel/ru9k4y5e/
However, if you want the gap to be shown, you must disable `ordinal`.

Closing as a question and resolved for now. If you have any further questions on this matter, please use StackOverflow, email, or Skype. Thanks for understanding!

https://jsfiddle.net/BlackLabel/thxrdzq5/

**Closed by raf18seb** 2022-06-17 12:59 UTC
