### ISSUE TITLE
The wrapPointPos method from highcharts-more does not properly check for undefined values (11.3.0 regression)

### ISSUE THREAD

**Issue by cascornelissen** [highcharts/highcharts#20588] opened 2024-02-05 20:54 UTC
#### Expected behaviour
Highcharts with highcharts-more (and highcharts-react-official) does not crash when setting the extremes of an xAxis.

#### Actual behaviour
It crashes, assumingly due to some sort of race condition. The thrown error refers to `chart` not being accessible on `undefined` and points to [this line](https://github.com/highcharts/highcharts/blame/6c03ea03430900cc816b14a60ea802d95a499037/ts/Series/PolarComposition.ts#L1427). Both `chart` and `series` are `undefined` at that point in time and I feel like there should be some proper checking for cases where this happens?

As an example, making the following change to `node_modules/highcharts/highcharts-more.src.js` (L1066) also fixes the issue.

```diff
-            const { plotX, series } = this, { chart } = series;
+            const { plotX, series = {} } = this, { chart = {} } = series;
```

I hope it's ok to tag @KamilKubik as he is the author of this piece of the codebase according to `git blame`.

#### Live demo with steps to reproduce
I'm not able to recreate this in a JSFiddle, we use Highcharts in a big application with a lot of data. In this specific case additional (higher-fidelity) data is being fetched after changing the xAxis extremes which takes a while (i.e. the browser actually hangs for a bit, which we should also improve on our side) and my gut feeling says it is related to that, some scenario where the chart gets destroyed and then at a later point in time it still reaches this piece of code.

#### Product version
Highcharts 11.3.0, it does work correctly with 11.2.0.

#### Affected browser(s)
N/A

**Comment by hubertkozik** [comment] 2024-02-06 07:34
Hi @cascornelissen!
I am sorry, but without any piece of code, I am unable to tell you if is it a bug, regression, or some misconfiguration of Highcharts. Also, the developer wouldn't be able to fix it, because we don't know how to reproduce it. Maybe there is a way to use some `setTimeout` and fill your data after a while?

**Comment by cascornelissen** [comment] 2024-02-06 08:45
Hi @hubertkozik,

Thanks for the response, I understand it's hard to do anything about it without a reproduction. I've been trying to come up with a minimal reproduction for a couple of hours but wanted to already share what I had found so far.

It's not so much a timing issue, it's more of a performance issue (unfortunately) which makes this hard to reproduce. I'll give it another shot if I find some time, no promises though ❤️

**Comment by tbjerknes** [comment] 2024-02-06 15:04
@cascornelissen : I see the same issue here, and it happens seemingly at ramdom. Question: My hunch is that it happens only in bubble charts, in the case when I remove existing series to replace them with new series. Before I start digging, is it a bubble chart in your case also?

**Comment by cascornelissen** [comment] 2024-02-06 15:39
Glad we’re not the only one! I’m afraid we do not use bubble charts, it’s a combination of line and arearange charts for us.

@hubertkozik, I do think it is a regression since it is working in 11.2.0 but I guess it’s a discussion about what a regression means semantically so I’ll leave that discussion alone 😊

**Comment by tbjerknes** [comment] 2024-02-07 08:56
I think my issue is related to the one in this #20572 , as I am getting the same messages.

**Comment by hubertkozik** [comment] 2024-02-07 09:59
Thanks @tbjerknes! It seems, that this issue is a duplicate of the one mentioned by you. Can you confirm @cascornelissen?

**Comment by cascornelissen** [comment] 2024-02-08 14:14
This seems like the same underlying issue indeed, well-illustrated with the use of `setTimeout` to destroy the chart I must say... 👍🏼

**Comment by hubertkozik** [comment] 2024-02-12 07:40
Thank you for discussion. Let's continue with the mentioned ticket.

**Closed by hubertkozik** 2024-02-12 07:40 UTC
Labels: Type: Duplicate
