### ISSUE TITLE
Info error in segments, when dataGrouping is forced

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5095] opened 2016-03-03 12:29 UTC
**Steps:**
1. Example http://jsfiddle.net/oq4f5xky/
2. Move left handle to right side, until small range
3. Error appears in the console
![zrzut ekranu 2016-03-03 o 13 29 31](https://cloud.githubusercontent.com/assets/2115686/13494362/fc824ce6-e143-11e5-8474-3b7f548e53f6.png)

**Comment by pawelfus** [comment] 2016-03-03 13:14
Duplicate of #5078.

**Closed by pawelfus** 2016-03-03 13:14 UTC
