### ISSUE TITLE
Dynamically added title / subtitle overlaps

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#6148] opened 2016-12-15 10:15 UTC
#### Expected behaviour
Titles should not overlap

#### Actual behaviour
Dynamically added title / subtitle overlaps

#### Live demo with steps to reproduce
Example:
- http://jsfiddle.net/gsr0gjj8/

Steps:
1. add title
2. add subtitle

#### Affected browser(s)
All

**Comment by ddotlic** [comment] 2016-12-15 12:23
I sent the bug initially to support, a few more observations:

The `floating` settings works for both `title` and `subtitle` _independently_, the issue is **only** when you set it for the `title` and then (regardless of secondary floating) you _also_ set `subtitle`.

Also, this is an issue regardless of the fact that we're adding `title/subtitle` dynamically - the same problem manifests itself if one uses configuration (aka we set values during initialization)

**Comment by pawelfus** [comment] 2016-12-16 12:48
I am not sure if this is a bug. Let me explain: when you set `title.floating` to true, then title is not considered when calculating any necessary space. Title and subtitle are separate elements, just like legend is (another demo: http://jsfiddle.net/gsr0gjj8/1/). Floating means no collision detection between elements.

However, it does make sense for title and subtitle to keep the distance between them: it's intuitive, but it will be inconsistent between floating options..

**Comment by ddotlic** [comment] 2016-12-16 17:07
@pawelfus I see your point, though then this means we cannot have both title and subtitle shown without "eating into" the vertical space (which is the most precious on most landscape screens) - they work fine when `floating: false`.

OTOH, maybe with a multi line HTML `title` we can achieve multi-line of text?

If so, what would be the point of `subtitle` then 😄 ?

**Comment by TorsteinHonsi** [comment] 2016-12-19 11:25
> If so, what would be the point of subtitle then 😄 ?

It's a convenience for the default usage, where the title is on one line, then there's a second line with smaller fonts below it. 

But there's nothing wrong with putting it all in the title: http://jsfiddle.net/highcharts/gsr0gjj8/2/

**Closed by TorsteinHonsi** 2016-12-19 11:25 UTC
Labels: Not a bug
