### ISSUE TITLE
Downloaded Chart does not render `Latex`

### ISSUE THREAD

**Issue by nishikantparmariam** [highcharts/highcharts#21765] opened 2024-09-02 13:27 UTC
#### Expected behaviour

Downloaded chart should render LaTeX like live chart.

#### Actual behaviour

Downloaded chart does not respect LaTeX.

#### Live demo with steps to reproduce
See - https://jsfiddle.net/6y07Lgr2/ 

We can notice that in title the LaTex 1/2 is appearing properly but the downloaded image does not have it properly even after adding workaround from https://github.com/highcharts/highcharts/issues/8764#issuecomment-414941900.

Live:
![image](https://github.com/user-attachments/assets/b57cdd6b-3f26-48fc-ab5a-df0d96fd3d1b)

Downloaded:
![frac12 (2)](https://github.com/user-attachments/assets/1856df70-48e7-4af5-b663-3d361dd0a7d9)

#### Product version
Highcharts **10.3.3**

#### Affected browser(s)
Chrome: Version 127.0.6533.120 (Official Build) (64-bit)

**Comment by hubertkozik** [comment] 2024-09-03 07:11
Hi @nishikantparmariam! This ticket is a duplicate of https://github.com/highcharts/highcharts/issues/8764. Sadly, there is no workaround for now. Let's continue the discussion there, in the old topic.

**Closed by hubertkozik** 2024-09-03 07:11 UTC
Labels: Duplicate
