### ISSUE TITLE
Panning the `stockChart` doesn't work smoothly on mobile

### ISSUE THREAD

**Issue by jakubSzuminski** [highcharts/highcharts#18498] opened 2023-02-15 07:56 UTC
#### Expected behaviour
Panning the `stockChart` on mobile should work smoothly as it does in web browser here: https://www.highcharts.com/demo/stock/cumulative-sum

#### Actual behaviour
Panning the `stockChart` on mobile doesn't work smoothly - instead of smooth panning, it loads in chunks, sometimes zooms in using a single finger pan.

#### Live demo with steps to reproduce
Try panning the chart on mobile:
https://jsfiddle.net/BlackLabel/jd7b9n2x/

#### Product version
Highcharts 10.3.3

**Comment by bm64** [comment] 2023-02-15 10:31
Thanks @jakubSzuminski for reporting the issue.

Zoom problem is caused by `ordinal` option and can be prevented by simply setting ordinal to false: https://jsfiddle.net/BlackLabel/evnf3pa9/

**Comment by et1983** [comment] 2023-03-14 16:02
Same bug. Wanted to try highcharts on mobile devices, it does not work.

**Comment by bm64** [comment] 2023-03-23 10:50
Hello @TTMSE 

There are two different issues mentioned in the ticket and I'm not sure to which you refer to:
1) Panning on mobile devices doesn't work smoothly
2) Sometimes chart zooms in during the mobile panning

Currently I can't suggest any workaround for the first one, but second one can be fixed by setting `ordinal` option to false: https://jsfiddle.net/BlackLabel/evnf3pa9/

**Comment by TTMSE** [comment] 2023-03-23 12:07
Thanks for the reply.
The jsfiddle solution is not suitable for using the stock chart.

Just a stock chart that does not work on mobile devices is not suitable for work.

Your chart is very good and easy to integrate. But the impossibility of work on mobile versions does not allow to use it.

**Comment by TTMSE** [comment] 2023-03-24 03:49
Hi, @pawelfus 

Thanks for the solution.
The chart is now scrolling!

But the zoom doesn't work correctly. The chart breaks after the zoom.

**Comment by pawelfus** [comment] 2023-03-24 09:16
Thanks! Regarding this:

> But the zoom doesn't work correctly. The chart breaks after the zoom.

Could you describe the issue? I simply zoomed in and tried to scroll: works fine. Zoomed out and tried to scroll - again, no problems. Does it happen in the demo above, or in your app?

**Comment by kamil-musialowski** [comment] 2023-05-31 11:40
Looks like the issue got fixed with the #19055. 

Demo with code from the branch to check on mobile view in chrome dev tools: https://jsfiddle.net/BlackLabel/ygb1pf9z/show

Could you please confirm @pawelfus before we close it?

**Comment by pawelfus** [comment] 2023-05-31 12:30
Confirmed, works fine, thank you!
Closing this issue.

**Closed by pawelfus** 2023-05-31 12:30 UTC
Labels: Type: Bug, Product: Highcharts Stock, Status: Has workaround, Flow: Inbox

**Comment by soeasyjx** [comment] 2024-01-27 14:45
How did you finally solve this problem

Panning on mobile devices doesn't work smoothly？？

**Comment by soeasyjx** [comment] 2024-01-29 05:03
Using the above method, in ios Settings in the translation is not smooth, very lag, data volume is only 365

**Comment by pawelfus** [comment] 2024-01-29 08:58
Could you check if you use the latest version? It should be fixed. If that's not the case, please recreate the issue in jsFiddle, we will check this. Thank you!
