### ISSUE TITLE
It does not work when set 'textOverflow: ellipsis' for dataLabels format in packed split bubble chart

### ISSUE THREAD

**Issue by Mokaffe** [highcharts/highcharts#14422] opened 2020-10-26 02:04 UTC
# Description of the feature
For packed split bubble chart, I set " allowOverlap: true" to see all the data label in the circle, It looks not well, So I want use "textOverflow:ellipsis" to make the data label in the circle, but this config does not work.

So, Did I wrong set this config? Or Is there another way to make it work?

![image](https://user-images.githubusercontent.com/9446480/97126514-0a36b480-1772-11eb-940c-329a031d319c.png)

![image](https://user-images.githubusercontent.com/9446480/97126679-7e715800-1772-11eb-840d-7d05bb22ba59.png)

`const options = {
  chart: {
    type: 'packedbubble',
    height: '100%',
  },
  title: {
    text: 'APIs Governance Map By Category',
  },
  tooltip: {
    useHTML: true,
    pointFormat: '<b>{point.name}</b>',
  },
  legend: {
    enabled: false,
  },
  credits: {
    enabled: false,
  },
  plotOptions: {
    packedbubble: {
      minSize: '30%',
      maxSize: '80%',
      pointStart: 100,
      zMin: 0,
      zMax: 1000,
      layoutAlgorithm: {
        gravitationalConstant: 0.05,
        splitSeries: true,
        seriesInteraction: false,
        dragBetweenSeries: false,
        parentNodeLimit: true,
        parentNodeOptions: {
          bubblePadding: 30,
        },
      },
      dataLabels: {
        enabled: true,
        format: '{point.name}',
        parentNodeFormat: '<span style="font-size: 1.3em">{series.name}</span>',
        allowOverlap: true,
        style: {
          color: 'black',
          textOverflow: 'ellipsis',
        },
      },
    },
  },
  series:[
    {name: 'parent node ## Num.1', data:[{name: 'to long word in the circle in one', value: 1}, {name: 'It is to long word in the circle in one', value: 1},{name: 'to long word in the circle in one', value: 1}, {name: 'It is to long word in the circle in one', value: 1},{name: 'to long word in the circle in one', value: 1}, {name: 'It is to long word in the circle in one', value: 1},{name: 'to long word in the circle in one', value: 1}, {name: 'It is to long word in the circle in one', value: 1} ]},
    {name: 'empty parent node#1', data:[]},
    {name: 'empty parent node#2', data:[]},
  ]
};`

**Comment by PaulDalek** [comment] 2020-10-26 10:10
Hi @Mokaffe

Thank you for reporting this issue. This enhancement has already been suggested before.

Closing as a duplicate of the #12527.

**Closed** 2020-10-26 10:10 UTC
Labels: Type: Duplicate, Type: Feature Request
