### ISSUE TITLE
[colorAxis] [colorKey] colorAxis don't use colorKey values when calculating its extremes

### ISSUE THREAD

**Issue by lekarsenten** [highcharts/highcharts#17617] opened 2022-08-18 09:46 UTC
#### Expected behaviour
If colorAxis extremes (min/max) aren't set explicitly 
    and colorKey set, 
then extremes should be calculated according to Series colorKey values.

#### Actual behaviour
colorAxis extremes are calculated based on Series x/y axis extremes.

#### Live demo with steps to reproduce
[https://jsfiddle.net/py9710n2/](https://jsfiddle.net/py9710n2/)

(It's HC colorAxis template [https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/coloraxis/custom-color-key](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/coloraxis/custom-color-key)
with removed colorAxis.min and colorAxis.max)

#### Product version
Latest (10.2.0)

#### Affected browser(s)
All

**Comment by raf18seb** [comment] 2022-08-23 13:33
Hi @lekarsenten!

Thank you for writing to us and sorry for the late reply.

This is not a bug and we know about this limitation. The info about it is in the API: https://api.highcharts.com/highcharts/series.line.colorKey
```Requires to set min and max if some custom point property is used```

Closing as not a bug but an intended and known behavior.

**Closed by raf18seb** 2022-08-23 13:33 UTC

**Comment by lekarsenten** [comment] 2022-08-23 16:58
Hi @raf18seb 
Thank you for answer, missed it.
