### ISSUE TITLE
Graph disappears from navigator in stockChart when using boost mode

### ISSUE THREAD

**Issue by wvhn** [highcharts/highcharts#22022] opened 2024-10-16 22:24 UTC
#### Expected behaviour
Navigator should show the entire graph if graph is zoomed or scrolled

#### Actual behaviour
If boost mode is enabled and dataGrouping is disabled in order to allow boost mode to kick in, the graph in navigator disappears as soon as zoom level is changed. It reappears only when zoom level is below 5000 points (i.e. boost mode kicked out).
Behaviour was still OK in v11.0.1 (where the live movement froze under similar conditions). 

#### Live demo with steps to reproduce
https://jsfiddle.net/wvhn_/7rqejbv1/
- zoom in or scroll using the navigator. See the graph disappearing and then reappearing if zoom range is below 5000 points. 
- switch dataGrouping on/off to see the difference

#### Product version
Highcharts Stock v11.4.8

#### Affected browser(s)
Firefox, Edge, Safari

**Comment by hubertkozik** [comment] 2024-10-21 06:19
Hello @wvhn! This issue is a duplicate of mentioned #21131 . Let's close this one and keep the discussion there.

**Closed by hubertkozik** 2024-10-21 06:19 UTC
Labels: Duplicate
