### ISSUE TITLE
lineWidth and dashStyle are not working 

### ISSUE THREAD

**Issue by ronvit** [highcharts/highcharts#6975] opened 2017-07-17 18:50 UTC
dynamically updating lineWidth and dashStyle are not working 

in the fiddle there two buttons to change lineWIdth and style. the changes reflect in the legend but not in series
https://jsfiddle.net/5j8w5e6t/

**Comment by sebastianbochan** [comment] 2017-07-18 08:08
Thank you for reporting. The issue is related with the case: https://github.com/highcharts/highcharts/issues/6922

**Comment by TorsteinHonsi** [comment] 2017-07-24 10:16
Duplicate of #6922.

**Closed by TorsteinHonsi** 2017-07-24 10:16 UTC
Labels: Undecided

**Comment by Nijadas** [comment] 2018-01-19 07:59
is this issue resolved..In my case when a line chart is drawn and updating the dashstyle first it appears that it is not updated but when it is scrolled it is showing dashed line
![pic1](https://user-images.githubusercontent.com/18435792/35140311-ba908914-fd1c-11e7-8897-c50bf2e32a5e.png)

**Comment by sebastianbochan** [comment] 2018-01-19 09:30
Hi @Nijadas 
Could you simplify your example and share as a live demo? It will allow us to debug it.

**Comment by Nijadas** [comment] 2018-01-19 10:59
we are using 9994 data for plotting the chart.so it is difficult to make a
sample

**Comment by pawelfus** [comment] 2018-01-19 12:57
Hi @Nijadas - in that case, please contact with out support: https://www.highcharts.com/support - they will help you with setting the demo.

**Comment by Nijadas** [comment] 2018-01-20 06:16
the dashstyle problem occurs when large datasets are loaded

**Comment by sebastianbochan** [comment] 2018-01-23 09:34
For the support cases, please use email / stackoverflow or forum, cause github is used for bugs.
