### ISSUE TITLE
addPoint animation broken for arearange data series

### ISSUE THREAD

**Issue by bstrasser** [highcharts/highcharts#3103] opened 2014-05-27 11:13 UTC
When adding points to an 'arearange' data series, the update animation looks broken:
Instead of just adding the new point and animating the x position, the whole chart morphs somehow to display the new data point.

For an example have a look at the following JS fiddle: http://jsfiddle.net/4UT8Q/

**Comment by KacperMadej** [comment] 2016-12-21 12:13
Duplicate of  #1841

**Closed by KacperMadej** 2016-12-21 12:13 UTC
