### ISSUE TITLE
Chrome can't handle csv date data properly

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#9565] opened 2018-11-30 09:56 UTC
Chrome is not able to handle date from csv.

#### Live demo with steps to reproduce
Open in Chrome (Edge/Firefox work as expected)
[jsFiddle](https://jsfiddle.net/BlackLabel/a4xqyLw8/)

#### Product version
Highcharts 6.2.0

#### Affected browser(s)
Chrome v70.0.3538.110 x64 Win10

**Comment by TorsteinHonsi** [comment] 2018-11-30 10:04
Probably our data module falls back to `Date.parse`. Chrome interprets this as American upside-down MM-DD-YYYY dates, while the others assume DD-MM-YYYY. But I believe this should be determined by our own logic _before_ reverting to Date.parse @cvasseng ?

**Comment by cvasseng** [comment] 2018-12-04 21:10
The issue is the date delimiter, it only supports `-` or `/` (working: https://jsfiddle.net/u5q3fxoa/). So what happens is that the code that figures out the date won't kick in, and it'll revert to `Date.parse` which rarely returns what one would expect. 

I'm not entirely sure how involving it is to add support, but I think it's enough to add a replace like [this](https://github.com/highcharts/highcharts/blob/master/js/modules/data.src.js#L851) for `.` as well. I'll try it out tomorrow, and hopefully we can have it be part of the V7 release.

**Comment by cvasseng** [comment] 2018-12-05 10:05
Fixed in 065f25a.

[Pull request](https://github.com/highcharts/highcharts/pull/9604) submitted.

Demo of fix: https://jsfiddle.net/BlackLabel/a4xqyLw8/

**Closed** 2018-12-06 13:37 UTC
Labels: Bug, Fix suggested, Review
