### ISSUE TITLE
Highcharts drilldown with react.js

### ISSUE THREAD

**Issue by anton19870803** [highcharts/highcharts#6777] opened 2017-05-29 17:01 UTC
#### Expected behaviour
The same as in https://www.highcharts.com/demo/pie-drilldown demo

#### Actual behaviour
In first drilldown everything is fine. After several drilldowns some artefacts from previous piecharts are visible:

![drilldown](https://cloud.githubusercontent.com/assets/21318008/26557084/dd268d78-44af-11e7-936d-9f08f92f9f2c.png)

Also colors are the same:

![drilldown_color](https://cloud.githubusercontent.com/assets/21318008/26557276/04657eac-44b1-11e7-978d-8ca5c6ddce73.png)

#### Live demo with steps to reproduce

To boostrap app I used create-react-app.
Here is my package.json

```
{
  "name": "drilldown",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "highcharts": "^5.0.12",
    "highcharts-drilldown": "^0.1.2",
    "react": "^15.5.4",
    "react-dom": "^15.5.4"
  },
  "devDependencies": {
    "react-scripts": "1.0.7"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
```

Here is src/index.js
```
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
import registerServiceWorker from './registerServiceWorker';
import './index.css';

ReactDOM.render(<App />, document.getElementById('root'));
registerServiceWorker();
```

Here is src/App.js

```
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';

import drilldown from 'highcharts-drilldown';
import Highcharts from 'highcharts';
drilldown(Highcharts);

class HighchartsDrilldown extends Component {

    componentDidMount() {
        // Create the chart
        Highcharts.chart('container', {
            chart: {
                type: 'pie'
            },
            title: {
                text: 'Browser market shares. January, 2015 to May, 2015'
            },
            subtitle: {
                text: 'Click the slices to view versions. Source: netmarketshare.com.'
            },
            plotOptions: {
                series: {
                    dataLabels: {
                        enabled: true,
                        format: '{point.name}: {point.y:.1f}%'
                    }
                }
            },

            tooltip: {
                headerFormat: '<span style="font-size:11px">{series.name}</span><br>',
                pointFormat: '<span style="color:{point.color}">{point.name}</span>: <b>{point.y:.2f}%</b> of total<br/>'
            },
            series: [{
                name: 'Brands',
                colorByPoint: true,
                data: [{
                    name: 'Microsoft Internet Explorer',
                    y: 56.33,
                    drilldown: 'Microsoft Internet Explorer'
                }, {
                    name: 'Chrome',
                    y: 24.03,
                    drilldown: 'Chrome'
                }, {
                    name: 'Firefox',
                    y: 10.38,
                    drilldown: 'Firefox'
                }, {
                    name: 'Safari',
                    y: 4.77,
                    drilldown: 'Safari'
                }, {
                    name: 'Opera',
                    y: 0.91,
                    drilldown: 'Opera'
                }, {
                    name: 'Proprietary or Undetectable',
                    y: 0.2,
                    drilldown: null
                }]
            }],
            drilldown: {
                series: [{
                    name: 'Microsoft Internet Explorer',
                    id: 'Microsoft Internet Explorer',
                    data: [
                        ['v11.0zzzzzzzzzzzzzzzz', 24.13],
                        ['v8.0', 17.2],
                        ['v9.0', 8.11],
                        ['v10.0', 5.33],
                        ['v6.0', 1.06],
                        ['v7.0', 0.5]
                    ]
                }, {
                    name: 'Chrome',
                    id: 'Chrome',
                    data: [
                        ['v40.0zzzzzzzzzzzzzz', 5],
                        ['v41.0', 4.32],
                        ['v42.0', 3.68],
                        ['v39.0', 2.96],
                        ['v36.0', 2.53],
                        ['v43.0', 1.45],
                        ['v31.0', 1.24],
                        ['v35.0', 0.85],
                        ['v38.0', 0.6],
                        ['v32.0', 0.55],
                        ['v37.0', 0.38],
                        ['v33.0', 0.19],
                        ['v34.0', 0.14],
                        ['v30.0', 0.14]
                    ]
                }, {
                    name: 'Firefox',
                    id: 'Firefox',
                    data: [
                        ['v35qqqqqqqqqqqqqqqq', 2.76],
                        ['v36', 2.32],
                        ['v37', 2.31],
                        ['v34', 1.27],
                        ['v38', 1.02],
                        ['v31', 0.33],
                        ['v33', 0.22],
                        ['v32', 0.15]
                    ]
                }, {
                    name: 'Safari',
                    id: 'Safari',
                    data: [
                        ['v8.0', 2.56],
                        ['v7.1', 0.77],
                        ['v5.1', 0.42],
                        ['v5.0', 0.3],
                        ['v6.1', 0.29],
                        ['v7.0', 0.26],
                        ['v6.2', 0.17]
                    ]
                }, {
                    name: 'Opera',
                    id: 'Opera',
                    data: [
                        ['v12.x', 0.34],
                        ['v28', 0.24],
                        ['v27', 0.17],
                        ['v29', 0.16]
                    ]
                }]
            }
        });
    }

  render() {
    return (
      <div id="container">
      </div>
    );
  }
}

class App extends Component {
  render() {
    return (
      <div className="App">
        <div className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h2>Welcome to React</h2>
        </div>
        <HighchartsDrilldown />
      </div>
    );
  }
}

export default App;
```

**Comment by oysteinmoseng** [comment] 2017-05-30 08:35
Thank you for reporting. Are you using the latest version of Highcharts and the drilldown module? This seems like a duplicate of https://github.com/highcharts/highcharts/issues/6042, which is fixed.

**Comment by anton19870803** [comment] 2017-05-30 09:00
"highcharts": "^5.0.12",
    "highcharts-drilldown": "^0.1.2",

Here is a repo to reproduce error:
https://github.com/anton19870803/drilldown/tree/master

To start application use commands:

```
npm install
npm start
```

**Comment by oysteinmoseng** [comment] 2017-05-30 09:27
Internal Note: Is `0.1.2` the latest drilldown version?

**Comment by pawelfus** [comment] 2017-05-30 12:57
I think "highcharts-drilldown" is some kind of unofficial package, not our. "drilldown" module is included in Highcharts package.

**Comment by jon-a-nygaard** [comment] 2017-05-30 14:02
Hi @anton19870803 To load Highcharts and its drilldown module in React you should try the following:
```javascript
import drilldown from 'highcharts/modules/drilldown.js';
import Highcharts from 'highcharts';
drilldown(Highcharts);
```

**Comment by anton19870803** [comment] 2017-05-30 14:34
Guys, sorry, my fault. With built-in module everything works just fine.
Thanks for guiding me.

**Closed** 2017-05-30 14:35 UTC
Labels: Not a bug

**Comment by jon-a-nygaard** [comment] 2017-05-30 18:57
No problem @anton19870803 . Glad to be of help :simple_smile:

**Comment by kopax-polyconseil** [comment] 2021-05-01 00:42
Hi, I ended up here because I want to use drill down.

Can't find a solution, how to do with the newest `import drilldown from 'highcharts/modules/drilldown';` ?

That's the desired result. Thanks

**Comment by KacperMadej** [comment] 2021-05-04 12:21
For technical support see https://www.highcharts.com/blog/support/
