### ISSUE TITLE
Initial x-axis labels are missing in the plot of datatime chart

### ISSUE THREAD

**Issue by KamalDeka** [highcharts/highcharts#13430] opened 2020-05-04 15:31 UTC
In a datatime chart when plotted with highcharts 8.0.4 first 1-3 x-axis labels are missing from start. The issue is seen in non-UTC time zone or timezoneOffset is non 0 in UTC timezone. The behavior or Issue is not seen in highcharts 7.2.1

#### Expected behaviour
The x-axis labels should be present from start. 

#### Actual behaviour
Some of the x-axis labels from start are missing.

#### Live demo with steps to reproduce
To repro the issue use following link and increase the width of frame where chart is drawn and then run the code.
**Buggy version live demo** https://jsfiddle.net/xdkhs18p/
**Working Version with 7.2.1** https://jsfiddle.net/kamaldeka/6r2m97zd/

#### Product version
highcharts 8.0.4
#### Affected browser(s)
Chrome, Safari, Microsoft Edge, Firefox.

**Comment by sebastianbochan** [comment] 2020-05-05 10:30
Hi @KamalDeka,
Thank you for reporting about the problem. Could you elaborate which size of container allow to reproduce the problem? I tested 300 / 600 / 1000px and still have the same tick amount in both cases.

**Comment by KamalDeka** [comment] 2020-05-06 04:36
hi @sebastianbochan ,

It is not reproducible in UTC + 0 time zone. I have updated the fiddle and added timezoneOffset to repro the issue. Now I hope issue will be seen in container size of 600+
8.0.4: https://jsfiddle.net/kamaldeka/w5s24b3h/3/
7.2.1: https://jsfiddle.net/kamaldeka/6r2m97zd/4/

Thanks,
Kamal

**Comment by sebastianbochan** [comment] 2020-05-06 08:45
Hi @KamalDeka,
When I run your cases I see the output like below:

<img width="987" alt="Screenshot 2020-05-06 at 10 36 28" src="https://user-images.githubusercontent.com/2115686/81156840-a5e72500-8f86-11ea-8376-d61b0076d5f0.png">

Could you confirm that the problem is related with "gap" on the left side of the chart? If yes, in both versions of Highcharts I see the same result.

**Comment by KamalDeka** [comment] 2020-05-06 09:55
FOR 8.0.4
![Screenshot 2020-05-06 at 3 24 12 PM](https://user-images.githubusercontent.com/6670545/81164313-c4ace200-8fad-11ea-9f9d-6e4997b778fc.png)

For 7.2.1
![Screenshot 2020-05-06 at 3 23 13 PM](https://user-images.githubusercontent.com/6670545/81164361-db533900-8fad-11ea-8fbb-071d3c5ff052.png)

**Comment by sebastianbochan** [comment] 2020-05-06 12:12
Could you hardcode the width in which problem appear? I tested with 800 and 1000px, no luck.

**Comment by KamalDeka** [comment] 2020-05-06 12:24
I have hardcoded container width to 1000px.
Chrome version: 81.0.4044.129
https://jsfiddle.net/kamaldeka/w5s24b3h/5/
https://jsfiddle.net/kamaldeka/6r2m97zd/6/

Could you please share the complete browser screenshot for JSfiddle using 7.2.1 highcharts? Also the screenshot you shared you can see there are some missing labels in the left.

**Comment by sebastianbochan** [comment] 2020-05-07 08:41
The gap is visible at the beginning of the chart (see my screenshot above), which should not be, when the timezone offset is set. I think that we can consider it as a bug.

**Comment by wchmiel** [comment] 2020-07-01 07:23
+1

After the zoom, ticks are not plotted properly.
Demos:
-> timezone set: https://jsfiddle.net/BlackLabel/f12pg45e/
-> without timezone: https://jsfiddle.net/BlackLabel/ekgpmb1s/

**Comment by khlieng** [comment] 2021-01-25 14:55
Fixed on master (#14731).

**Closed by khlieng** 2021-01-25 14:55 UTC
Labels: Type: Bug
