### ISSUE TITLE
Drilldown seems to require unique names for each datapoint

### ISSUE THREAD

**Issue by laopunk** [highcharts/highcharts#5708] opened 2016-09-20 14:16 UTC
#### Expected behaviour
Graph should show the right categories

#### Actual behaviour
Graph mixes up values from different points when your drill down and up

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/drilldown/basic/

This is the "Basic drilldown" fiddle from documentation, the only change made was to change "Apples" into "Cats" (which is already used in the "animals" category).
1- Click on "animals" => looks good
2- drill back to upper level (Back to things)
3- Click on "Fruits" => all messed up

I have tried to give a unique id to the points that have the same name but the issue remains.
I can appreciate that within a level you may only have unique names, but we should be allowed to have duplicates when it is in a different level or a different category.

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment] 2016-09-20 14:45
Duplicate of: https://github.com/highcharts/highcharts/issues/5565

**Closed by sebastianbochan** 2016-09-20 14:45 UTC
