### ISSUE TITLE
Drilldown from data with null value throws error

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#4777] opened 2015-11-27 16:20 UTC
Drilldown from data with null y value to another series will throw errors. 

example: 
http://jsfiddle.net/e24o60Le/2/

**Comment by TorsteinHonsi** [comment] 2015-12-01 11:21
The shape args for the null point contains NaN for y and height, therefore the animation fails.

**Comment by pawelfus** [comment] 2016-09-06 08:27
Duplicate of #3169

**Closed by pawelfus** 2016-09-06 08:27 UTC
Labels: Duplicate
