### ISSUE TITLE
Tooltips bigger that chart container cannot be displayed

### ISSUE THREAD

**Issue by MiroLiska** [highcharts/highcharts#6658] opened 2017-04-28 15:01 UTC
#### Expected behaviour
The tooltip should not be limited to the chart container size. It should be always displayed.

#### Actual behaviour
The tooltips are cropped if they are bigger than the chart container. There is unofficial plugin at http://jsfiddle.net/gh/get/jquery/1.7.2/highcharts/highcharts/tree/master/samples/highcharts/studies/tooltip-outside-box/  but it is not part of standard and is buggy. See attachment: 
[TooltipsOutsideBox.docx](https://github.com/highcharts/highcharts/files/964704/TooltipsOutsideBox.docx)

#### Live demo with steps to reproduce
http://jsfiddle.net/mwf6mc6y/  

#### Affected browser(s)
All.

**Comment by pawelfus** [comment] 2017-05-22 11:39
It looks like a duplicate of #5784

**Comment by MiroLiska** [comment] 2017-05-22 12:00
It is a slightly different problem but could be probably solved by one common standard code as proposed in http://jsfiddle.net/gh/get/jquery/1.7.2/highcharts/highcharts/tree/master/samples/highcharts/studies/tooltip-outside-box/

However, the solution presented is causing the web page to get horizontal scrollbars even when it should not. Open http://jsfiddle.net/1nb34yb6/show/ and make your browser window narrow:

[cid:image001.png@01D2C030.047D9D30]

Now move your mouse to the last point in the second chart – you will get a scrollbar which has a very disturbing effect:
[cid:image002.png@01D2C030.752507D0]

**Closed** 2017-05-24 10:33 UTC

**Comment by MiroLiska** [comment] 2017-05-24 13:04
Hello

The solution presented has a bug. See here : http://jsfiddle.net/7f6yv05m/  - there are three charts under each other. Make the window that high that only one (and half) chart appears. The scroll down. Try to get any tooltips on the third chart - it will not work. A possible solution can be seen here: http://jsfiddle.net/7f6yv05m/1/

Moreover, the code may crash in some Chrome versions. The value of this.chart.pointer.chartPosition is sometimes null if you scroll through the page with the mouse wheel and have the luck to hit a chart data point immediately after the mouse move. Chrome will set the chartPosition to null by leaving one chart container and then it gets immediately onMouseOver for a data point before onMouseMove for chart arrives.

Any chance that this out-of-box study ever gets into standard highcharts code?

Miro

**Comment by TorsteinHonsi** [comment] 2017-05-26 10:42
Thanks for the fix! It may eventually end up in production, but we need to at least get rid of the jQuery dependency and also test it in different conditions.
