### ISSUE TITLE
Heatmap with Styled 5.0.5

### ISSUE THREAD

**Issue by garybrain** [highcharts/highcharts#6059] opened 2016-11-30 15:05 UTC
#### Expected behaviour

Heatmap should reflect colour range.

#### Actual behaviour

Heatmap shows singel colour for all boxes.

#### Live demo with steps to reproduce

Single colour for all boxes because of the class assignment **.highcharts-color-0**

http://jsfiddle.net/6u2u15yf/1/

Comment out the class and the colours show correct output.

http://jsfiddle.net/6u2u15yf/

**Comment by pawelfus** [comment] 2016-11-30 15:33
Thanks for reporting!

It's already fixed on our master branch, please take a look: http://jsfiddle.net/6u2u15yf/3/

Closing as duplicate of #6049.

**Closed by pawelfus** 2016-11-30 15:33 UTC
Labels: Duplicate

**Comment by garybrain** [comment] 2016-11-30 16:31
Hi thanks for the update.

_note : must remember to check master branch before raising :)_
