### ISSUE TITLE
Highcharts Tooltip is cut off if chart container width is limited

### ISSUE THREAD

**Issue by SummerLi** [highcharts/highcharts#7514] opened 2017-12-11 23:11 UTC
#### Expected behaviour
When chart container width is limited, Highcharts tooltip is cut off. We should be able to display the entire tooltip on top of container.

#### Actual behaviour
highcharts tooltip is cut off.

#### Live demo with steps to reproduce
https://jsfiddle.net/47s0pm8r/1/

#### Affected browser(s)
Chrome, Edge, IE, (Highly possible Firefox and Safari as well, I didn't test them)

**Comment by pawelfus** [comment] 2017-12-12 14:55
Hi @SummerLi 

Thank you for reporting this bug. It's a duplicate of #5784

**Closed by pawelfus** 2017-12-12 14:55 UTC
