### ISSUE TITLE
Missmatch between tooltip and Y axis value for normal stacking area

### ISSUE THREAD

**Issue by smokir** [highcharts/highcharts#10820] opened 2019-05-24 18:08 UTC
#### Expected behaviour

Tooltip value matches Y axis value or Y axis behaves as tooltip and picks first or last value

#### Actual behaviour

Tooltip value doesn't fit Y axis

#### Live demo with steps to reproduce
https://jsfiddle.net/ho6wqbsk/

#### Product version
Highcharts

#### Affected browser(s)
FF 66.0.3, Safari 12.1.1, YandexBrowser 19.4.0

**Comment by KacperMadej** [comment] 2019-05-28 10:59
Hi @smokir 

Thank you for contacting us about the problem.

Points in the same series have the same x values and this is not correct.
Stacking is designed for multiple series.
Line and line based series do not support multiple points with the same x values.

This doesn't look like a bug.

**Comment by smokir** [comment] 2019-05-28 21:41
@KacperMadej thank you for your reply.

It is not right that words you said could not be found in the documentation and there is no `Highcharts error #` message in a console for such a case.

**Comment by KacperMadej** [comment] 2019-05-29 10:30
This should be fixed - we should improve documentation.
I will add correct labels for this case.

**Comment by pawelfus** [comment] 2019-06-14 11:28
It's not considered as a bug anymore: https://jsfiddle.net/BlackLabel/6nowb3dL/ - this can be controlled by setting [`series.findNearestPointBy`](https://api.highcharts.com/highcharts/plotOptions.series.findNearestPointBy) option. Closing the issue then.

**Closed by pawelfus** 2019-06-14 11:28 UTC
Labels: Product: Docs, Type: Enhancement

**Comment by smokir** [comment] 2019-06-17 10:43
> It's not considered as a bug anymore: https://jsfiddle.net/BlackLabel/6nowb3dL/ - this can be controlled by setting [`series.findNearestPointBy`](https://api.highcharts.com/highcharts/plotOptions.series.findNearestPointBy) option. Closing the issue then.

@pawelfus thank you, `findNearestPointBy` works.

But with `tooltip: {shared: true}` there is only one value in tooltip.

**Comment by pawelfus** [comment] 2019-06-17 12:00
Good point, @smokir 

I'm not sure if this is a bug, in shared/split tooltip only one point per series is displayed by design. From a different perspective, all points with the same x-value should be displayed in the tooltip. Would you like to open new issues for this case @smokir ?
