### ISSUE TITLE
Column chart labels overlap bars after drilldown

### ISSUE THREAD

**Issue by marklofdahl** [highcharts/highcharts#8042] opened 2018-03-19 20:14 UTC
#### Expected behaviour
On column chart, vertical position of labels should be consistent, and not overlap bars.

#### Actual behaviour
The vertical position of the labels is a bit quirky. Sometimes they are positioned correctly. Most of the time after a drilldown/drillup, they are too high, and overlap the bars, or too low. If you use the scrollbar at all, the labels will redraw into the correct position.
Is there a way to get the labels to render in the correct position without having to move the scrollbar?

#### Live demo with steps to reproduce
https://jsfiddle.net/marklofdahl/d3omtjys/

#### Product version
Highstock 6.0.7

#### Affected browser(s)
Firefox
Chrome

**Comment by Denyllon** [comment] 2018-03-21 15:57
Thank you for reporting the issue. At the time, there are a couple of changes on the `master` branch, and it solves some problems with aligning labels too. You can use the latest version from our repository by changing the script source to `https://github.highcharts.com/stock/highstock.js` for example.
After that, your chart should look better. However, it isn't all what you need to do in order to avoid problem. You could also use the simple **workaround** to force wrapping of the axis labels. To do that, you need to call `redraw()` function inside `chart.load()`event function, just like that:
```js
chart: {
  events: {
    load: function() {
      this.redraw()
    }
  }
}
```
**Live example:**
[https://jsfiddle.net/afebz7u0/](https://jsfiddle.net/afebz7u0/)

**Comment by marklofdahl** [comment] 2018-03-21 16:27
Thanks for the workaround; it is helpful. Any idea when this will make it into the next official version?

**Comment by sebastianbochan** [comment] 2018-03-22 09:46
We release new version each few weeks, so new Highcahrts will be soon.

**Comment by Denyllon** [comment] 2018-03-23 14:42
At the time we don't have any specific date of publishing new release, but we should do this within a few weeks.

**Comment by KacperMadej** [comment] 2018-03-26 10:58
Closing since the problem is resolved in the next release candidate version of code. Please reopen if the problem will show up in a next version.

**Comment by Denyllon** [comment] 2018-03-27 11:32
Sorry for my understatement. I meant that a lot of issues related to your request will be fixed in upcoming release, but at the time still there are some problems with aligning axis labels and my workaround doesn't solve all of them unfortunately, so I reopen this issue and work on complete solution.

**Closed** 2018-04-20 12:14 UTC
Labels: Bug
