### ISSUE TITLE
Sankey / minPointLength not working

### ISSUE THREAD

**Issue by RHCautomation** [highcharts/highcharts#7318] opened 2017-10-25 13:06 UTC
If I use links with big differences in weight, it happens, that the lower ones are shown with a linkHeight lower than 1px and so they become invisible. Unfortunately the parameter **minPointLength** isn't working, respectively it is not implemented.

As a workaround I've added following code to the source:

`linkHeight = (point.weight != null && linkHeight < 1) ? 1 : linkHeight;	`

With this hack, all valid links will be shown with a minimal linkHeight of 1px.

It would be nice, if I could use the parameter **minPointLength** for that instead of the hack!

**Comment by pawelfus** [comment] 2017-10-26 13:52
Thank you for sharing!

Related lines:

https://github.com/highcharts/highcharts/blob/b1c642fa0a483dd4cda1e77fb3cc70e9c4708b86/js/modules/sankey.src.js#L456-L459

**Comment by KacperMadej** [comment] 2018-09-20 13:37
Closing as a duplicate of #8927

**Comment by RHCautomation** [comment] 2019-05-24 07:38
Hi,

the request of #8927 wasn't the same as my request and for that reason this issue should be reopened. 

My problem is, that links are becoming invisible, if the value of weight is 0. I would like to define a minimum linkHeight for all links via parameter (for example 1px, so that a link with weight=0 persists visible). It works with my workaround of my first post, but I don't want to change the sourcecode of sankey.js after every update to a new version.

**Comment by slesarevns** [comment] 2019-07-18 14:33
Hi @KacperMadej any info when will see the enhancement?

**Comment by sebastianbochan** [comment] 2019-07-22 13:15
Hi @slesarevns,
I prepared the enhancement and just waiting for review from other developers.

**Comment by slesarevns** [comment] 2019-07-23 06:47
Hi @sebastianbochan, thanks  👍

**Closed** 2019-07-24 12:54 UTC
Labels: Product: Highcharts, Type: Enhancement

**Comment by RHCautomation** [comment] 2020-04-10 13:59
Hi,

I have to reopen this issue, because nodes with weight 0 are not shown anymore since fix #12453. For me, the main reason for using the parameter **minLinkHeight** was the possibility to make links with weight 0 visible. 

So, please make the behavior of displaying 0-weights at least configurable!

**Comment by sebastianbochan** [comment] 2020-04-14 10:35
Thank you for details. Its a regression. I created a new ticket here: https://github.com/highcharts/highcharts/issues/13308

As I see you posted the case here: https://github.com/highcharts/highcharts/issues/11917.

Please do not duplicate of comments in multiple thread. We would like to keep consistency and avoid confusing.

**Comment by RHCautomation** [comment] 2020-08-31 17:11
Hi,

my problem is still not solved. Up to version 8.0.0 the behavior of **minLinkHeight** was correct in my opinion:

https://jsfiddle.net/3kbmrtjc/ (**v8.0.0** - link to node "Test1" is shown, although it's value is 0)

https://jsfiddle.net/3kbmrtjc/1/ (**actual version** - link to node "Test1" is not shown - but I need to show links with value 0)

**Comment by pawelfus** [comment] 2020-09-01 09:41
I agree with you, we should at least make this configurable @RHCautomation - created ticket #14150
