### ISSUE TITLE
Point update - marker color not applied

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4622] opened 2015-10-05 08:34 UTC
Example: 
http://jsfiddle.net/yPT73/1/

Seems that is related with https://github.com/highslide-software/highcharts.com/issues/4267

**Comment by dawidgorus** [comment] 2015-10-05 09:47
+1

**Comment by sebastianbochan** [comment] 2015-10-13 11:28
Doesn't work since 4.1.8 (in 4.1.7 is fine).

Extra demo: http://jsfiddle.net/yb5f6rsL/4/

**Comment by sebastianbochan** [comment] 2015-10-28 14:54
Fixed in the master branch.
Ref: http://jsfiddle.net/yb5f6rsL/5/

**Comment by sebastianbochan** [comment] 2015-11-20 10:59
Seems that problem is still with pie chart: 

http://jsfiddle.net/59ss9nm2/2/

**Comment by pawelfus** [comment] 2015-11-20 12:17
Fixed on the bugfix branch, probably connected to #4704.

See: http://jsfiddle.net/59ss9nm2/4/

**Comment by dawidgorus** [comment] 2015-12-09 15:22
I've found one more bug, update color works on pie slice, but color doesn't change in legend

http://jsfiddle.net/59ss9nm2/7/

**Comment by pawelfus** [comment] 2015-12-09 15:27
Thanks!

**Comment by KacperMadej** [comment] 2015-12-10 11:17
The issue is also present when using funnel or pyramid - http://jsfiddle.net/f1xbvgxw/2/

**Comment by pawelfus** [comment] 2015-12-10 11:42
*Internal note:*

1) Legend item isn't updated. In fact, `colorizeItem()` is called only when creating item (or when hiding/showing series/slice).

2) Funnel - indeed, still broken (the same fix as for other series should be applied), also issue with legend item exists: http://jsfiddle.net/f1xbvgxw/3/

**Comment by TorsteinHonsi** [comment] 2016-02-01 11:03
Continue on #4759

**Closed by TorsteinHonsi** 2016-02-01 11:03 UTC
Labels: Regression

**Comment by Audhut** [comment] 2019-09-26 12:20
this issue still persists on xRange chart where i am changing the color on  point click event.
I am using 
pointEvent.point..update({ color: "pink", pointWidth: 40 }, true, false);
pointEvent.point.series.redraw();

however one observation is that if i click on another point, then the color of the first point changes

**Comment by pawelfus** [comment] 2019-09-26 15:02
Hi @Audhut 

Could you provide a live demo of the issue? The basic demo seems to be fine: https://jsfiddle.net/BlackLabel/puwk6arg/ Thanks!
