### ISSUE TITLE
Treemap - drilldown is not working if the top-level has a single node

### ISSUE THREAD

**Issue by wchmiel** [highcharts/highcharts#14212] opened 2020-09-11 07:28 UTC
#### Expected behaviour
Drilldown should work with a single node.

#### Actual behaviour
Drilldown doesn't work with a single node.

#### Live demo with steps to reproduce
v8.1.1 regression (click on the root level): https://jsfiddle.net/BlackLabel/r4uvxg0t/
v8.1.0 work as expected (click on the root level): https://jsfiddle.net/BlackLabel/oLhdyqfe

#### Product version
Highcharts v8.1.1

Workaround: use version v8.1.0 -> https://jsfiddle.net/BlackLabel/oLhdyqfe

**Comment by pawelfus** [comment] 2020-09-14 13:25
*Internal note:*
Bisected to commit 6db37ec3ed
It seems there's a bug in `isDrillAllowed` - it's checking for number of children, which is correct for sunburst, but not for treemap.

**Comment by andi1984** [comment] 2020-09-25 08:19
What is the status of this? I can confirm that since 8.1.1 our columnchart drilldowns are also broken.

**Comment by pawelfus** [comment] 2020-09-25 10:17
Hi @andi1984 - issue is open, not assigned, no ETA at this moment.

Cna you provide demo with column series? The more info we have, the better fix we can provide. Thanks!

**Comment by andi1984** [comment] 2020-09-28 11:10
@pawelfus Hi, you can see the bug I mean on https://app.dimensions.ai/analytics/publication/for/barchart when you drill down on the first entry for example.

![Screenshot 2020-09-28 at 13 08 00](https://user-images.githubusercontent.com/1077917/94425152-b6917500-018b-11eb-990e-fac01b4eb415.png)

It seems to me that further axis labels are created with ongoing index numbers of the labels as text.

Funnily in a separated demo with exact same settings it does not happen:

https://ehwen.csb.app/

**Comment by pawelfus** [comment] 2020-09-29 09:03
Could you explain what is broken? What should I do? It seems fine (testing: https://app.dimensions.ai/analytics/publication/for/barchart ):
![drilldown](https://user-images.githubusercontent.com/1453926/94537081-3b8b9580-0243-11eb-9c11-9f1b49d6713c.gif)

**Comment by andi1984** [comment] 2020-09-29 17:11
@pawelfus When you scrolldown on the drilldowned data, you see the following:

![Uploading Screenshot_2020-09-29 Bar Chart - Fields of Research in Publications - Dimensions.png…]()

Well at least you can see it broken until tomorrow 30.09.2020 as we are going to provide a new release where we roll-back Highcharts to v8.1.0, the last version until which this is not broken.

I will try to further examine what exactly is the reason that causes this issue as my isolated demo with the exact same chart works totally fine. All I can tell by now that <= 8.1.0 it works fine and from >8.1.1 on it is broken.

**Comment by khlieng** [comment] 2020-11-27 09:17
Fixed since 8.2.2 (#14257), duplicate of #12286.

**Closed by khlieng** 2020-11-27 09:17 UTC
Labels: Type: Duplicate, Type: Regression

**Comment by andi1984** [comment] 2020-12-10 10:17
@khlieng I tried with 8.2.2 but for whatever reason it is still happening on our side, but maybe also something wrong on our code. Can anyone else approve that the issue is _really_ fixed for them which would indicate that our internal issue is caused by something else maybe?

**Comment by pawelfus** [comment] 2020-12-10 12:12
Hi @andi1984 

Just realized that we were discussing here column-drilldown and treemap-drilldown. If you tested v8.2.2 and it's still broken, then this might be a completely different issue. OP's demo is fine. Could you try recreating this once again? In a clean demo env? Perhaps you did not load unnecessary modules in the demo, which may affect the chart?

PS: My apologies for not answering sooner, GitHub did not notify me about your post...
