### ISSUE TITLE
Incorrect yAxis.labels positions when using the gridLineInterpolation equal to "polygon" and categories axis type.

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#8350] opened 2018-05-17 15:02 UTC
#### Expected behaviour

Y Axis labels should be aligned to polygon grid lines, not to circle ones.

#### Actual behaviour

Y Axis labels aren't aligned to grid lines, and their positions are calculated in the same way like when `yAxis.gridLineInterpolation` is set to 'circle', but they shouldn't.

#### Live demo with steps to reproduce
1. https://jsfiddle.net/4oktb19y/ - `gridLineInterpolation` set to `polygon`.
2. https://jsfiddle.net/yh4y7qzc/ - `gridLineInterpolation` set to `circle`.

As you can see, in both cases labels positions are calculated in the same way.

#### Product version
All versions

**#### Workaround**
Adjust the xAxis extremes so that it rotate to the yAxis labels, then it looks better.
For example:
```
  "xAxis": {
    // Add empty category as last array position to avoid showing its index on the chart.
    "categories": ['Cat1', 'Cat2', 'Cat3', 'Cat4', 'Cat5', ''], 
    "min": 0.5,
    "max": 5.5,
  },
```
Live example: https://jsfiddle.net/a5ohz6yn/

**Comment by pawelfus** [comment] 2018-05-29 10:07
Closing as duplicate of #4953

**Closed by pawelfus** 2018-05-29 10:07 UTC
Labels: Bug
