### ISSUE TITLE
Errorbar: not aligned perfectly - sometimes has 1 pixel offset

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5334] opened 2016-05-23 11:24 UTC
#### Behaviour

Miss-aligned lines e.g. are not placed in center of linkedTo scatter markers.
#### Live demo with steps to reproduce

http://jsfiddle.net/zkenuwu2/
Plot lines added for reference, but also very much visible in compare to scatter markers.
#### Affected browser(s)

More visible in Chrome (at least for this demo).

**Comment by TorsteinHonsi** [comment] 2016-05-25 13:17
@jon-a-nygaard Check the rounding used for the error bar stem. Error bar inherits certain features, check that the issue is fixed as high up in the inheritance chain as possible.

**Comment by jon-a-nygaard** [comment] 2016-05-27 06:23
It also seems that the markers for the scatter series is a little bit skewed towards left.

**Comment by TorsteinHonsi** [comment] 2016-05-27 07:01
If you remove the error bars, the scatter series markers seem to be quite well aligned to the grid lines. The grid lines are rounded to the nearest full pixel. The error bars are also rounded, but seem to be consequently 1px more to the right, so it may be that we are running `Math.ceil` in one place and `Math.floor` in another place, or `Math. round/Math.ceil`. Look for "crisp" in the error bar/box plot code.

**Comment by jon-a-nygaard** [comment] 2016-05-27 07:46
@TorsteinHonsi Thanks, looking at it right now.

The scatter markers are not centered on the grid line, but starts drawing on the beginning of the grid line, which can be seen from this image. But I guess there is a logical reason for it.
![marker](https://cloud.githubusercontent.com/assets/3284659/15600697/e5d4ccd6-23eb-11e6-86cc-92169b0e1869.png)

**Comment by jon-a-nygaard** [comment] 2016-05-27 14:25
Internal Note: The shapeArgs values have already been corrected for crispness, and are therefore not so good for use in calculations.
Tried to subtract the crispCorr in BoxPlotSeries.drawPoints instead of adding it. In this case it looked better, but in cases with the same chart but a different width it could look equally bad. Therefore not a solution to the issue.

**Comment by TorsteinHonsi** [comment] 2016-05-30 07:53
Problably the crisping logic of the grid lines is also buggy, so that they are not always crisped to the closest full pixel. So a fix for this issue would require that the grid lines are fixed, which will create a lot of diffs in the visual pixel-by-pixel tests.

**Comment by KacperMadej** [comment] 2016-09-13 09:43
+1
The issue is the same with column type series: http://jsfiddle.net/m4nwwsfo/
Pixel alignment is not the same as for gridLines of xAxis.

**Comment by ucare-wuh** [comment] 2017-12-06 01:46
Any progress on this? I recently get the same problem.

**Comment by paulo-raca** [comment] 2018-07-01 04:28
+1, pretty annoying

**Comment by Andriy-Kulak** [comment] 2018-07-16 14:55
If you add a `pointRange: 0` and desired `pointWidth` to errorbar series, this seems to fix the issue per fiddle: http://jsfiddle.net/da1mpchj/1/

The workaround solution was actually provided by @paulo-raca in this ticket: https://github.com/highcharts/highcharts/issues/8558

**Comment by paulo-raca** [comment] 2018-07-16 15:06
@Andriy-Kulak -- Thanks for looking into it, but that was a workaround to a different problem (The weird spacing and extra passing applied to x-axis when there is a errorbar series).

Looking at your example, it continues a little bit off-center.
E.g., examining the SVG, the first point is centered at x=5 and the first error bar is centered at x=5.5

**Comment by Andriy-Kulak** [comment] 2018-07-16 15:16
@paulo-raca in any case this solution made my the bug much less noticeable in my chart. I attached before and after images
**BEFORE:**
![before](https://user-images.githubusercontent.com/12179976/42766879-8ff77fc4-88e9-11e8-83d9-a75e76261986.png)
**AFTER:**
![after](https://user-images.githubusercontent.com/12179976/42766883-920e927a-88e9-11e8-9aa2-9d7d2698da8b.png)

**Comment by paulo-raca** [comment] 2018-07-16 15:21
Wow, I'm puzzled.
Do you have a jsfiddle with this chart?
Thanks!

**Comment by jedrzejruta** [comment] 2024-02-12 12:28
unstale

**Comment by tnafele** [comment] 2024-02-12 20:03
Other example of the issue with latest Highcharts and errorbars overlays with scatter (zoomed in):
![Screenshot from 2024-02-12 09-47-05](https://github.com/highcharts/highcharts/assets/7112769/1dd9f200-b6c5-4472-b54c-98597700043a)
You find the Fiddle [here](https://jsfiddle.net/Lowxab96/7/).

Please fix this bug, this issue seem to be known for a very long time.

**Comment by karolkolodziej** [comment] 2024-02-13 07:38
Recreated with the `boxplot` series- [demo](https://jsfiddle.net/BlackLabel/rqk2bp3x/).
Looks like the `drawPoints` round it quite aggressively:
https://github.com/highcharts/highcharts/blob/04577452a895e04135fcb99f5a8d23da020eef9c/ts/Series/BoxPlot/BoxPlotSeries.ts#L158-L165

**Closed** 2024-05-21 16:58 UTC
Labels: Type: Bug, Product: Highcharts
