### ISSUE TITLE
Highcharts dateFormat Note working correctly in latest version

### ISSUE THREAD

**Issue by eklein-cddep** [highcharts/highcharts#5551] opened 2016-07-31 02:02 UTC
#### Expected behaviour
Should produce a formatted date in the tooltip formatter function

#### Actual behaviour
Is returning a blank space

#### Live demo with steps to reproduce

Version 4.2.4: https://jsfiddle.net/eklein21/q1zdtuna/8/
Version 4.2.5: https://jsfiddle.net/eklein21/q1zdtuna/7/

The only difference between the two is the version of highcharts. 

#### Affected browser(s)
Didn't work in Firefox (47.0) or Chrome (51.0.2704.103 m). Didn't try IE/Opera

**Comment by jon-a-nygaard** [comment] 2016-08-01 08:42
@eklein-cddep Thanks for reporting. This is a duplicate of #5302, and it will be fixed in the upcoming maintenance release. While you wait, the dateFormat function does currently not work with date objects, but you can [change to milliseconds](https://jsfiddle.net/jon_a_nygaard/q1zdtuna/9/) instead and it will work fine.

**Closed by jon-a-nygaard** 2016-08-01 08:42 UTC
Labels: Bug
