### ISSUE TITLE
Boost module does not render areaspline in canvas

### ISSUE THREAD

**Issue by ghost** [highcharts/highcharts#8288] opened 2018-05-07 07:33 UTC
The boost module does not boost areaspline, although it is supporting it internally.

Example: https://jsfiddle.net/7ss4um2q/1/

**Comment by Jaibharath** [comment] 2019-03-20 20:06
Is this resolved. I am using the areaspline type with (zones, dash styles)

**Comment by Jaibharath** [comment] 2019-03-20 20:10
Please let me know, as I need to show more then 1000 points in areaspline chart. rendering is too slow even after using the boost module. I tried checking with type 'line' with boost module, it worked, but it is not working for areasplin type.

**Comment by sebastianbochan** [comment] 2019-03-21 06:54
Hi @Jaibharath,
At this moment areasplines are still not supported, but could you simplify your demo and post here? It will allow me to verify if any workaround or different solution is possible (like dataGrouping, lazy loading etc).

**Comment by Jaibharath** [comment] 2019-03-21 13:09
Ok, We are using angular 6 with highcharts, I conffigured the datagrouping with different zones for each point. Once the series of data is ready through the scripting then I configured the config options with type of chart, series and axis, zoom options, We are using the areaspline type relating which related to our design, It worked until like 300 - 400  xaxis label, Once the labels increasing, chart loading taking more memory. Then I tried using the  Boost module which did not work. I tried with type 'line' boost module worked. But with line also once I zoomed in chart is not removing after I zoomed out.

**Comment by Jaibharath** [comment] 2019-03-21 19:08
Also when trying with spline+boost module not working. with line+boost module. on reset zoom the chart is not hiding.  Its showing the dense line chart and also the zoomed chart on reset zoom

**Comment by pawelfus** [comment] 2019-03-22 13:13
At this moment, `spline`-type is not supported (list of supported types is available in our docs: https://www.highcharts.com/docs/advanced-chart-features/boost-module ). If series on reset zoom does not hide, please recreate issue in jsFiddle (without angular). Thanks!

**Comment by Jaibharath** [comment] 2019-03-25 16:40
Hi @pawelfus I dont have the jsfiddle, please replace js below code in below jsfiddel link(https://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/boost/line/)




function getData(n) {
var dataObj = {};
dataObj.arr = [];
dataObj.zones = [];
    
        var i;
        var a;
       	var b;
        var c;
        var color;
        var spike;
    for (i = 0; i < n; i = i + 1) {
        if (i % 100 === 0) {
            a = 2 * Math.random();
        }
        if (i % 1000 === 0) {
            b = 2 * Math.random();
        }
        if (i % 10000 === 0) {
            c = 2 * Math.random();
        }
        if (i % 50000 === 0) {
            spike = 10;
        } else {
            spike = 0;
        }
        if(spike > 10) {
        	color = 'yellow'
        } else if (spike < 10 && spike >= 8) {
        	color = 'orange';
        } else if (spike < 8 && spike >= 6) {
        	color = 'red';
        } else if (spike < 6 && spike >= 4) {
        	color = 'red';
        } else if (spike < 4 && spike >= 0) {
        	color = 'green';
        }
        
        dataObj.zones.push({
         color: color,
         value: i
        })
        
        dataObj.arr.push([
            i,
            2 * Math.sin(i / 100) + a + b + c + spike + Math.random()
        ]);
    }
    return dataObj;
}
var n = 5000;
   var dataObj = getData(n);
   var data = dataObj.arr;
   var zones = dataObj.zones;


console.time('line');
Highcharts.chart('container', {

    chart: {
        zoomType: 'x',
        panning: true,
        panKey: 'shift'
    },

    boost: {
        useGPUTranslations: true
    },

    title: {
        text: 'Highcharts drawing ' + n + ' points'
    },

    subtitle: {
        text: 'Using the Boost module'
    },

    tooltip: {
        valueDecimals: 2
    },

    series: [{
        data: data,
        lineWidth: 0.5,
        zones: zones
    }]

});
console.timeEnd('line');

**Comment by Jaibharath** [comment] 2019-03-25 16:43
After updating the js, Right now in code I kept 5000 points, and tried to zoom in and did reset zoom. I am getting graph as

![image](https://user-images.githubusercontent.com/17460532/54937832-91b7a400-4efb-11e9-8569-12952c02d31d.png)

**Comment by Jaibharath** [comment] 2019-03-25 16:51
This is the intial screen after loading. when we zoom, I am able to see two charts as shown above, 

![image](https://user-images.githubusercontent.com/17460532/54938356-9892e680-4efc-11e9-8ed5-5b5580ddd980.png)

**Comment by Jaibharath** [comment] 2019-03-25 16:52
Also while using the boost, is there any way not to show the default blue color and give some zones.

**Comment by sebastianbochan** [comment] 2019-03-26 12:19
@Jaibharath zones are not supported by the boost module. 

As a workaround you can create multiple series.

**Comment by pawelfus** [comment] 2019-03-26 13:15
Note: Zones in boost issues is already reported here #9124

**Comment by Jaibharath** [comment] 2019-03-26 14:34
Will this issue will be resolved, as its the same requirement I need to implement either with line chart or areaspline with zones in same chart without multiple series.

**Comment by KacperMadej** [comment] 2019-03-28 09:31
@Jaibharath 

The issue is open and labeled as a bug, so we will be working on resolving the problem. There's no ETA for the fix right now. As a workaround you could try to describe what's required and maybe multiple series is not that bad solution if it will be processed from a single series.

**Comment by cvasseng** [comment] 2019-03-28 12:30
As @pawelfus mentioned, spline types in general is not currently supported by the boost module. `area` or `arearange` is the closest match at this point. 

I added zone support just now however, in f7afccd which is currently under review. Here's a demo of how it works: https://jsfiddle.net/o5vp02ab/

**Closed** 2021-12-06 09:49 UTC
Labels: Type: Bug, Type: Feature Request, Status: Review in progress
