### ISSUE TITLE
Rapidly setting series of a chart results in oldData[i]?.destroy is not a function error

### ISSUE THREAD

**Issue by tylersalminen** [highcharts/highcharts#21903] opened 2024-09-25 14:08 UTC
#### Expected behaviour
Should be able to rapidly update series

#### Actual behaviour
Rapidly updating series errors on attempting to destroy points of prior series that has not yet rendered

#### Live demo with steps to reproduce

Following code in Series.prototype.setData does not account for fact that oldData may not be instances of Point but instead are just plain objects thus throwing oldData[i]?.destroy is not a function error

```javascript
// Destroy old points
  i = oldDataLength;
  while (i--) {
      oldData[i]?.destroy();
  }

```

Could fix by simply doing 
```javascript
// Destroy old points
  i = oldDataLength;
  while (i--) {
      if(isFunction(oldData[i]?.destroy)){
        oldData[i]?.destroy();
};
  }

```

or there may be a more efficient way like just testing the first point and assuming rest of points are points
```javascript
// Destroy old points

if(oldData?.[0] instanceof Point){
    i = oldDataLength;
    while (i--) {
          oldData[i]?.destroy();
        
    }
  
}

```

#### Product version
Highcharts core 14.4.8 and earlier versions to 11.* (for what i tested)

#### Affected browser(s)
Tested in Chrome

**Comment by hubertkozik** [comment] 2024-09-26 08:03
Hi @tylersalminen! Thank you for reporting the ticket. Do you have any demo with Highcharts usage, where the problem of rapidly setting series takes place?

**Comment by tylersalminen** [comment] 2024-09-26 11:17
I am unable to reproduce an isolated example even when trying to reproduce the steps I achieve it exactly in a fiddle. I can only reproduce it in my framework's unit tests. I suspect that this is because of some race condition in the highcharts library that is difficult to reproduce outside of the context of the timing that I utilize it within my framework.

Nevertheless here is a fiddle of my attempt to reproduce it. I tried to imitate the calls my application is making to the library (including animation frames)

https://jsfiddle.net/tylero2/m6gfzbdq/28/

Here is the associated log i am producing from my unit test from my framework that is logging calls to the highcharts library. I used these to construct the fiddle. the "Frame" logs are beginnings of animation frames from my framework. Note the (1, ... and (2, ... are different charts and the error occurs for chart (1, ... in this example, I highlighted the relevant logs in the image below

![image](https://github.com/user-attachments/assets/336dfb87-66f0-47ed-b246-be1cb009776d)

I hope this is enough information. like i pointed out in my original post I was able to manually fix the issue by modifying the source library at the specified lines in the Series.prototype.setData method though this is a very naive fix and there are perhaps other issues / context I am not accounting for.

**Comment by hubertkozik** [comment] 2024-09-27 07:27
It is hard to decide for me. @TorsteinHonsi can I ask for your opinion?

**Comment by TorsteinHonsi** [comment] 2024-09-30 06:18
@hubertkozik I think it is a bit risky for us to provide a fix for this as long as we can not reproduce it, because we don't know where it's coming from. Some questions arise:

* In what scenario is `oldData` an array of plain objects?  I would expect it to always be Point instances. In fact, all our tests pass even if we drop the question mark and run `oldData[i].destroy()`.
* If `oldData[i].destroy` were nullish, it should have been stopped by the `?.` operator. So if it is not nullish and not a function, what is it, and where does that property come from?

**Comment by tylersalminen** [comment] 2024-09-30 14:11
Here is some more context of the issue that I can produce in my unit test, I know it is perhaps not useful for debugging the issue but it perhaps provides some proofing of what is going on. You can see that indeed the oldData array is indeed holding plain objects:

![image](https://github.com/user-attachments/assets/c6b2ea51-ba83-4cc5-84f5-021c8de41f58)

**Comment by tylersalminen** [comment] 2024-09-30 15:29
Also I noticed, when the issue occurs, if I have my added logic that ignores destroying the prior points if they are not of a type Point then the series gets drawn twice. Note, however, that no other error is ever thrown

![image](https://github.com/user-attachments/assets/cedcc765-821e-4c4b-8be6-e8db7c38be0a)

**Comment by hubertkozik** [comment] 2024-10-07 07:21
Sadly, without clear reproduction, it's hard to find any root cause of your issue. I'll close this topic for now, but if you can reproduce the issue in some online editor feel free to reopen it.

**Closed by hubertkozik** 2024-10-07 07:21 UTC
Labels: Status: Can't reproduce
