### ISSUE TITLE
RangeSelector date change unresponsive

### ISSUE THREAD

**Issue by findoo** [highcharts/highcharts#4710] opened 2015-11-02 16:51 UTC
When clicking into a range selector, changing the date, and then clicking off the input box to lose focus - the changed date is not reflected on the chart and the input reverts to its previous value. 

This behaviour is exhibited in both Chrome and IE11 on the demo JSFiddle - http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/stock/rangeselector/styling/ 

I've also found the range picker is capable of removing a day from the date typed in when it does work, but unable to replicate in JSFiddle.

**Comment by pawelfus** [comment] 2015-11-03 09:50
Just tested, works fine, see:
![range_selector_v2](https://cloud.githubusercontent.com/assets/1453926/10905140/9dccd520-8218-11e5-82c5-a06e62052ccf.gif)

Make sure you are choosing proper dates (from < to and you don't want to view data for 2050year etc.)

**Comment by findoo** [comment] 2015-11-03 10:34
You must be hitting enter on the keyboard after typing in those changes. Type the changes and then just click off the box.

**Comment by pawelfus** [comment] 2015-11-03 11:20
Oh right, then looks like duplicate of #4606

**Comment by primerano** [comment] 2018-11-08 19:09
People we have been testing with run into this problem constantly.  They edit the date and then click in the chart, which causes the date to revert.    Hitting enter or clicking outside the chart (after editing the date) is not something that many users are doing.  Most of them edit and then click somewhere in the SVG.    We have considered removing the range selector altogether (to avoid this confusion) but some people will need granular control of the dates.

**Closed** 2018-11-09 12:08 UTC
Labels: Highstock

**Comment by TorsteinHonsi** [comment] 2018-11-09 12:09
Thanks for sharing your user test results! We have fixed this issue, please see the demo with the fix applied: http://jsfiddle.net/highcharts/z0hrqg7y/2/.

**Comment by primerano** [comment] 2018-11-09 12:29
Thank you, this works great.  Will this be in the 6.2.1 release?

**Comment by TorsteinHonsi** [comment] 2018-11-09 13:57
Great! Yes it will be in the next release.
