### ISSUE TITLE
support scroll-bar in legend 

### ISSUE THREAD

**Issue by kim-spotinst** [highcharts/highcharts#15643] opened 2021-05-04 15:10 UTC
Highcharts in the past has provided the legend.style API, which provided an option to use scrollbar instead of the arrows navigation thats supported today

In our product, UX team requires to have a **scrollbar if there is not enough space for all the legends.**
So I would like to have an option to add the scroller manually or (better option) to have a proper configuration on the legend
options

**Example:** legend.scroller API/ legend.navigator.scrollerEnable

**Mock:**
![image](https://user-images.githubusercontent.com/48174844/117019392-06c24e00-acfe-11eb-8e51-873d3bc996e4.png)

**Comment by webpig** [comment] 2021-05-07 01:53
Can arrows navigation be arranged horizontally?

**Comment by raf18seb** [comment] 2021-05-07 12:35
Hi! Thanks for creating the ticket.

Seems like a good feature. Here is a small code snippet allowing scrolling with a mouse scroll: https://jsfiddle.net/BlackLabel/oLpsv96n/

We'll think about implementing it in the future depending on how many voted does it get.

**Comment by webpig** [comment] 2021-05-07 15:57
> Hi! Thanks for creating the ticket.
> 
> Seems like a good feature. Here is a small code snippet allowing scrolling with a mouse scroll: https://jsfiddle.net/BlackLabel/oLpsv96n/
> 
> We'll think about implementing it in the future depending on how many voted does it get.

How to arrange legend and navigation horizontally?

**Comment by raf18seb** [comment] 2021-05-09 11:13
@webpig

Sorry, we do not provide this feature yet. You can vote for this by adding a thumb up here in this ticket: https://github.com/highcharts/highcharts/issues/7513

**Comment by webpig** [comment] 2021-05-09 15:09
> @webpig
> 
> Sorry, we do not provide this feature yet. You can vote for this by adding a thumb up here in this ticket: #7513

OK, I voted.

**Comment by HRworksKra** [comment] 2023-07-06 07:45
Hey, I can see here didn't happen anything for a long while, is there any chance we can get this feature in the near future?

**Comment by KacperMadej** [comment] 2023-07-06 17:02
Here are some rough PoC demos based on [chart.scrollablePlotArea](https://api.highcharts.com/highcharts/chart.scrollablePlotArea) idea:
- [demo for a vertical scroll](https://jsfiddle.net/BlackLabel/aev928w3/)
- [demo for a horizontal scroll](https://jsfiddle.net/BlackLabel/au0kgrc5/)

Please leave a 👍 reaction if this is going in the direction you expected or a comment below with your feedback.

---
@HRworksKra 

> is there any chance we can get this feature in the near future?

Yes, but this heavily depends on your definition of "any" in "any chance" and "near" in "near future". But seriously, the issue is being estimated and investigated, and we should have more details and a potentially the ETA within the next few weeks or sooner.

**Comment by HRworksKra** [comment] 2023-07-06 17:34
> 

Thats definetly the direction! What is a very important that it is possible to style the scroller (for instance like in the mockup from @kim-spotinst) as otherwise it's again not usable because of the design.

> Here are some rough PoC demos based on [chart.scrollablePlotArea](https://api.highcharts.com/highcharts/chart.scrollablePlotArea) idea:
> 
> * [demo for a vertical scroll](https://jsfiddle.net/BlackLabel/aev928w3/)
> * [demo for a horizontal scroll](https://jsfiddle.net/BlackLabel/au0kgrc5/)
> 
> Please leave a 👍 reaction if this is going in the direction you expected or a comment below with your feedback.

**Comment by TorsteinHonsi** [comment] 2023-07-07 06:05
Thumbs up for Kacper's solution! Doing this with native HTML/CSS scrolling is compact and provides a great UX.

> What is a very important that it is possible to style the scroller

There are some options for styling native scrollbars, see https://css-tricks.com/the-current-state-of-styling-scrollbars-in-css/ . This should be checked in detail. 

If it turns out HTML/CSS does not provide the required styling capabilities, we must consider plugging in our own Scrollbars module. But that would probably mean a lot more modifications, and is not guaranteed to work that smoothly.

**Closed** 2023-10-20 09:05 UTC
Labels: Type: Feature Request
