### ISSUE TITLE
boost library breaks the category inside the tooltip

### ISSUE THREAD

**Issue by vohtaski** [highcharts/highcharts#6095] opened 2016-12-06 10:53 UTC
#### Expected behaviour
Tooltip should show the category name with and without boost library.
Highcharts version is 5.0.5.

#### Actual behaviour
When boost is disabled, tooltip shows category (411.062).
When boost is enabled, it shows a different number (71661),
that looks like an index of the xAxis but outside of the actual range (max index is 71590).

#### Live demo with steps to reproduce
Without boost:
![screen shot 2016-12-06 at 11 46 36 am](https://cloud.githubusercontent.com/assets/158421/20922974/865ffe5e-bbaa-11e6-93d6-2cbb0df430d5.png)
With boost:
![screen shot 2016-12-06 at 11 45 47 am](https://cloud.githubusercontent.com/assets/158421/20922984/9398305a-bbaa-11e6-868c-04754bdffa7c.png)

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment] 2016-12-07 12:19
Looks like a duplicate of #5672

@vohtaski Could you try out the workaround suggested in #5672 ? Or recreate issue in jsFiddle?

**Comment by pawelfus** [comment] 2018-01-04 16:06
Closing due to inactivity. If someone has more info (appreciated live demo) please let us know and we will reopen the issue.

**Closed by pawelfus** 2018-01-04 16:06 UTC
Labels: Pending reply
