### ISSUE TITLE
allowDecimals: false ignored with flat data

### ISSUE THREAD

**Issue by drmrbrewer** [highcharts/highcharts#6274] opened 2017-01-20 11:41 UTC
#### Expected behaviour

Setting `allowDecimals: false` on the `yAxis` should result in integer axis labels.

#### Actual behaviour

With flat high-precision data, this doesn't work.

#### Live demo with steps to reproduce

http://jsfiddle.net/xhs3fonh/2/

#### Affected browser(s)

Any, I assume.

**Comment by pawelfus** [comment] 2017-01-20 11:48
**Workaround:**
Use [`yAxis.minRange`](http://api.highcharts.com/highstock/yAxis.minRange), demo: http://jsfiddle.net/xhs3fonh/4/ 

Short explanation: it's not caused by high precision as in the title, but it's related to all points having the same value. If only one value will be a bit different, it will work correctly: http://jsfiddle.net/xhs3fonh/5/

**Comment by drmrbrewer** [comment] 2017-01-20 11:55
@pawelfus OK.  So this is recognised as a bug that will be fixed... hence no need for the workaround in future version?

**Comment by pawelfus** [comment] 2017-01-20 12:08
I think this should be closed as duplicate of #5956. I know this is the report for `allowDecimals`, but under the hood it's issue with extremes for flat data. Also workaround from #5956 works for this issue: http://jsfiddle.net/xhs3fonh/2/

I think it should be configurable, so we can choose if we want to get flat data in the middle of a chart, with just one tick, or we want to generate N-ticks anyway.

**Comment by TorsteinHonsi** [comment] 2017-01-23 12:29
> It should be configurable, so we can choose if we want to get flat data in the middle of a chart, with just one tick, or we want to generate N-ticks anyway

It looks like we've already got that option - by setting `minRange`. Do you think that's enough? In that case we just need to communicate it better, add it to the docs in appropriate places etc.

**Comment by pawelfus** [comment] 2017-01-23 12:45
It depends if we talk about `allowDecimals` or general solution? For `allowDecimals` it's perfectly fine, as we know the minimum range (one unit, without decimals), but not when considering extremes for a flat data. User may not know which `minRange` will be fine, let's consider these two examples:

- http://jsfiddle.net/xhs3fonh/7/ (minRange: 1 is fine here)
- http://jsfiddle.net/xhs3fonh/8/ (minRange: 1 won't work nicely)

Both examples can be created using the same config etc. on the same page (just data from backend can be different).

**Comment by TorsteinHonsi** [comment] 2017-01-24 08:01
> User may not know which minRange will be fine

The point with flat data is that there is no way that Highcharts can _guess_ what the preferred scale is, that's why we chose to present it with one single tick in the first place. (Previously we added integer ticks if I remember correctly). But with using `minRange`, we offer the user an option to take some control and add a scale.

**Comment by drmrbrewer** [comment] 2017-01-24 08:18
Referring to my original post, my surprise was that with `allowDecimals` set to `false` and yet I was still seeing decimals on the axis label.  At least where `allowDecimals` is set to `false`, you know that instead of just a single `1.3333333` as in my original example, you just put two ticks at `1` and `2` either side.  With `allowDecimals` set to `true` I wouldn't have been surprised at the lack of scale (just a single tick), and if it bothered me I would probably have found `minRange` as the solution.  So for me, the only issue that needs fixing relates to ensuring that `allowDecimals = false` always has the expected effect... i.e. no decimals on the axis, ever... shouldn't need the `minRange` workaround because `allowDecimals = false` should already impose that workaround.

**Comment by TorsteinHonsi** [comment] 2017-01-24 10:19
Yes, I agree to that conclusion.

**Closed** 2017-01-24 11:13 UTC
Labels: Bug

**Comment by pawellysy** [comment] 2022-05-05 08:20
Hello @ereticor, could you provide the live demo, where the issue is reproduced? Thanks!
