### ISSUE TITLE
[highstock] 3d bar - distance from bottom of chart computed incorrectly

### ISSUE THREAD

**Issue by late-warrior** [highcharts/highcharts#4995] opened 2016-02-03 11:49 UTC
(happens in highstock only)

In a 3d bar chart, the bars that are plotted in the latter half of the xaxis do not have their distance from the bottom from the chart calculated correctly.  The 3d effect is therefore lost.  This seems to have been present in the 2.1.8 version as well.  However the 2.0.3 version does not have this bug.

Fiddle that demonstrates this - http://jsfiddle.net/1jh56bpp/5/ . Uncomment the script tags on top to run it against older versions.
![chart 3](https://cloud.githubusercontent.com/assets/1673739/12781417/46302d06-ca9a-11e5-80b2-5f56ccaac637.png)

I tried a couple of things like disabling the navigator, switching off the xAxis labels etc to make sure they are not responsible, but doesn't seem to work. 

(I tried searching for similar open 3d issues but couldn't find something similar)

Thanks !

**Comment by TorsteinHonsi** [comment] 2016-02-03 14:14
Another case of #4933

**Comment by pawelfus** [comment] 2016-02-04 13:58
Unfortunately, this is a separate issue. This one is connected to clipping rect, which is updated in Highstock [here](https://github.com/highcharts/highcharts/blob/16bcfc9a918b8c485d92bc7194bb5dc04718357d/js/parts/StockChart.js#L591), but not in Highcharts (so [this setting](https://github.com/highcharts/highcharts/blob/master/js/parts-3d/Chart.js#L45) works fine).

**Comment by KacperMadej** [comment] 2016-11-28 12:15
Fixed since 4.2.6.
Duplicate of #2939

**Closed by KacperMadej** 2016-11-28 12:15 UTC
Labels: Bug, Highstock
