### ISSUE TITLE
dependencywheel dislocation of connection point

### ISSUE THREAD

**Issue by wjhcc2018** [highcharts/highcharts#13054] opened 2020-03-03 08:49 UTC
#### Expected behaviour
It's like the red box
![QQ图片20200303164726](https://user-images.githubusercontent.com/6789138/75758235-bb658600-5d6e-11ea-8281-eadc6fe629e9.png)

#### Actual behaviour
It's like the red box
![QQ图片20200303164706](https://user-images.githubusercontent.com/6789138/75758297-d0421980-5d6e-11ea-9271-0f0659ce7d31.png)

#### Live demo with steps to reproduce

https://jshare.com.cn/temp/MBGGQg
#### Product version

"highcharts": "8.0.0",
"highcharts-3d": "^0.1.7",
"highcharts-grouped-categories": "^1.1.3",
"highcharts-regression": "^2.0.1",
"highcharts-vue": "^1.3.5",

**Comment by pawelfus** [comment] 2020-03-03 09:34
Thanks for reporting @wjhcc2018 - it's already reported: #12456

Closing as duplicate of #12456

**Closed by pawelfus** 2020-03-03 09:34 UTC
