### ISSUE TITLE
Flickering column on mouse hover when crosshair is enabled

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#6747] opened 2017-05-19 11:35 UTC
#### Expected behaviour
Column should change color on hover.

#### Actual behaviour
In current Highcharts version (5.0.11) column is flickering on mouse hover when crosshair is enabled

#### Live demo with steps to reproduce
http://jsfiddle.net/3ce975f8/1/

gif example:
![ie11_win10](https://cloud.githubusercontent.com/assets/15050812/26246129/ca5729de-3c97-11e7-8fe4-b3fdf35e6e61.gif)

#### Affected browser(s)
IE11/Win10

Issue was implemented in 5.0.0 Highcharts version

**Comment by TorsteinHonsi** [comment] 2017-05-22 07:22
A simple fix could be to set pointer-events: none on the crosshair.

**Comment by MiroLiska** [comment] 2017-05-25 06:32
How exactly should I apply that fix? I tried to add .highcharts-crosshair, .highcharts-crosshair-thin, .highcharts-xaxis-category
{
  pointer-events: none;
}, but this is not helping.
Do you plan any real fix? I hoped this to be fixed in 5.0.12, but it was not :(
It is not only about flickering, the hand-cursor for drilldowns flickers as well - see http://jsfiddle.net/avtLone9/9/ .

**Comment by KacperMadej** [comment] 2017-05-25 12:08
@TorsteinHonsi This fix/workaround doesn't help on IE11. Demo: http://jsfiddle.net/3ce975f8/2/ The problem is still visible. This issues also causes tooltip to hide on each flick seen in the gif above. If you jump with cursor from one place to another inside of a column you might end up with no tooltip.

**Closed** 2017-05-26 08:12 UTC

**Comment by MiroLiska** [comment] 2017-05-26 09:53
Works fine. Thank you very much.
