### ISSUE TITLE
xAxis labels step

### ISSUE THREAD

**Issue by pliasetski** [highcharts/highcharts#6102] opened 2016-12-07 12:27 UTC
Hello,
When you add step option to xAxis labels, there is no dots when label outside chart area.

#### Live demo with steps to reproduce
http://jsfiddle.net/rqf54y8f/1/
![image](https://cloud.githubusercontent.com/assets/2900934/20967660/a6e42da2-bc91-11e6-8730-48e8c714115b.png)

#### Affected browser(s)
Latest chrome version

**Comment by pawelfus** [comment] 2016-12-08 11:51
Hi @pliasetski - could you set fixed width for the container? I can not recreate this issue (it always translates text to the left, so it's not cut off).

**Comment by pliasetski** [comment] 2016-12-08 12:38
Hi @pawelfus 
I've updated demo: http://jsfiddle.net/Pashe4ka/rqf54y8f/3/
Please click on "6m" button in zoom to observe this issue.

![image](https://cloud.githubusercontent.com/assets/2900934/21010293/5501a3c2-bd5c-11e6-8503-d2d470048a85.png)

**Comment by oysteinmoseng** [comment] 2016-12-08 14:30
@pliasetski I still can not reproduce your issue from the demo. For me the label is shifted to stay within the plot area.

**Comment by sebastianbochan** [comment] 2016-12-09 10:39
Demo: http://jsfiddle.net/zb4ku27q/

The issue is caused by step parameter, without it, all works properly.

**Comment by sebastianbochan** [comment] 2018-05-28 13:56
Fixed in since 6.1.0.

**Closed by sebastianbochan** 2018-05-28 13:56 UTC
Labels: Bug
