### ISSUE TITLE
centerInCategory makes secondary yAxis columns stack

### ISSUE THREAD

**Issue by vitaliy-kretsul** [highcharts/highcharts#18473] opened 2023-02-10 10:04 UTC
#### Expected behaviour
Secondary yAxis columns displayed side-by-side

#### Actual behaviour
Secondary yAxis columns displayed one in front of another

#### Live demo with steps to reproduce
https://jsfiddle.net/Cortez/o8xrw47f/

#### Product version
Highcharts 10.3.3

#### Affected browser(s)
Google Chrome 110.0.5481.77

**Comment by bm64** [comment] 2023-02-11 00:34
Hello @vitaliy-kretsul. I'm closing this one as a duplicate of #14921. Feel free to continue discussion in the original ticket.

**Closed by bm64** 2023-02-11 00:34 UTC
