### ISSUE TITLE
Wrong tooltip when tooltip.shared = true on a 3d chart

### ISSUE THREAD

**Issue by rja71** [highcharts/highcharts#5954] opened 2016-11-09 13:35 UTC
#### Expected behaviour

Correct display for tooltips on a 3d chart.

#### Actual behaviour

Wrong display for tooltips on a 3d chart when tooltip.shared = true

#### Live demo with steps to reproduce

http://jsfiddle.net/7nwrth66/6/

Move the mouse over the chart to see the tooltip, from left to right and right to left.
 - when tooltip.shared = false, everything seems ok
 - when tooltip.shared = true, the tooltip positioning is unexpected (wrong position or value, and the tooltip appear when the mouse is over the background.

The issue is more visible when moving the mouse backward (rigth to left) to the first categories.

#### Affected browser(s)

Tested only in Firefox 49.0.2 and Edge

Best regards,

**Comment by pawelfus** [comment] 2016-11-09 14:34
Hi @rja71 

Thank you for reporting! Actually it's a duplicate of #3242.

Kind Regards,
Paweł

**Closed by pawelfus** 2016-11-09 14:34 UTC
Labels: Duplicate
