### ISSUE TITLE
The BoxAndWhisker Chart doesn't display correctly

### ISSUE THREAD

**Issue by lingyufei** [highcharts/highcharts#21385] opened 2024-06-24 05:42 UTC
#### Expected behaviour
The BoxAndWhisker Chart doesn't display correctly in v11.4.3. (See the image below).
<img width="1443" alt="image" src="https://github.com/highcharts/highcharts/assets/49775184/f3a83f38-e5d6-4239-ab8d-762c02e99473">

However, it works fine in v11.4.1
<img width="1252" alt="image" src="https://github.com/highcharts/highcharts/assets/49775184/64b0380b-2cbc-42ac-8596-f2872e5cb483">

#### Product version
11.4.3

**Comment by hubertkozik** [comment] 2024-06-24 07:14
Hi @lingyufei! The issue is already fixed on the master branch: https://jsfiddle.net/BlackLabel/q2g8m6ab/

Closing as duplicate of https://github.com/highcharts/highcharts/issues/21245.

**Closed by hubertkozik** 2024-06-24 07:14 UTC
Labels: Duplicate
