### ISSUE TITLE
Chart not rendering with 1k points with x, y 

### ISSUE THREAD

**Issue by govinda18** [highcharts/highcharts#15020] opened 2021-02-01 09:51 UTC
#### Expected behaviour
Chart should render just fine similar to https://jsfiddle.net/4phc512g/1/

#### Actual behaviour
Chart does not render when the data is passed in the format `{x: pointX, y: pointY}`

#### Live demo with steps to reproduce
https://jsfiddle.net/4phc512g/

#### Product version
Highcharts JS v8.2.2 (2020-10-22)

#### Affected browser(s)
Chrome

**Comment by KacperMadej** [comment] 2021-02-01 12:41
Hi @govinda18 

Please see an error in the browser console and the link provided in there: https://www.highcharts.com/errors/12/

Closing as not a bug.

**Closed by KacperMadej** 2021-02-01 12:41 UTC
