### ISSUE TITLE
Datalabels not correctly aligned in 3D mode.

### ISSUE THREAD

**Issue by scottszb1987** [highcharts/highcharts#5499] opened 2016-07-18 02:46 UTC
#### Expected behaviour
With column type, 3D enabled, grouping set to false, Datalabels should align in the center on top of each column

#### Actual behaviour
Datalabels align on the right on top of each column

#### Live demo with steps to reproduce

https://jsfiddle.net/scottszb1987/yn8wccdd/

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment] 2016-07-18 09:16
Hi @scottszb1987 

Thank you for your report. Issue is connected to #4834 (if not a duplicate). Minimized example: http://jsfiddle.net/nb67aL5p/

**Comment by jon-a-nygaard** [comment] 2016-07-18 10:34
Closing this issue since it is a duplicate of #4834. Please follow the referenced issue to get updates on comments and progress.

**Closed by jon-a-nygaard** 2016-07-18 10:34 UTC

**Comment by jon-a-nygaard** [comment] 2016-07-18 14:38
Also a duplicate of #4160.
