### ISSUE TITLE
Zoom - issue while zooming on one/two points 

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#11648] opened 2019-08-09 13:37 UTC
It seems that zooming doesn't work properly while zooming on (hovering) one or two points.
User video showing the issue: https://www.youtube.com/watch?v=hATK0lPfWQ0&feature=youtu.be

The last version when this feature used to work properly is 5.0.14 - [Demo](https://jsfiddle.net/BlackLabel/f9wk6Le8/)

Setting min and max on yAxis could be used as a temporary solution: 
[Demo](https://jsfiddle.net/BlackLabel/teL421wh/)

#### Live demo with steps to reproduce

[Current version](https://jsfiddle.net/BlackLabel/4Lvbpaec/)

#### Product version

Highcharts JS v7.1.2 (2019-06-03)

#### Affected browser(s)

All

**Comment by pawelfus** [comment] 2019-08-16 14:14
Bisected to commit b91477777e

**Comment by sebastianbochan** [comment] 2020-04-07 12:36
Should we consider it as a bug in case of unsorted data (by x ascending) ?

ps. We are notified about incorrect data by error HC#15 in the console.

**Comment by sebastianbochan** [comment] 2020-04-08 13:55
Sorted data works properly.

Demo:
- https://jsfiddle.net/BlackLabel/amqsxkuz/

Closing it as not a bug.

**Closed by sebastianbochan** 2020-04-08 13:55 UTC
Labels: Type: Regression
