### ISSUE TITLE
minPointLength not working properly

### ISSUE THREAD

**Issue by shaneshen-okta** [highcharts/highcharts#17056] opened 2022-03-04 14:49 UTC
#### Expected behaviour
If the summed values of the points are the same, we should get the same length for each point, no matter how big `minPointLength` is set

#### Actual behaviour
We get different length for the points if the `minPointLength` is set and the **small values is in the first series**.
<img width="802" alt="Screen Shot 2022-03-03 at 10 00 52 AM" src="https://user-images.githubusercontent.com/89863577/156784238-34150cc9-d2ce-41ee-81f8-7e75f60013a2.png">

#### Live demo with steps to reproduce
https://jsfiddle.net/2860ntfa/

#### Product version
highcharts: 9.3.2

**Comment by shaneshen-okta** [comment] 2022-03-14 20:53
@raf18seb  Shall we hide the bar if the value is 0 even if the `minPointLength` is set?

**Comment by raf18seb** [comment] 2022-03-15 21:36
@shaneshen-okta,

Unfortunately, we don't have a workaround for this bug at this moment.

I'm not even sure which of the above behaviors is correct. I think it's a matter of opinion. I assume that, in your opinion, the first 2 top bars are correct, and the ones with a question mark are wrong, am I right?
In my opinion, the bars with a question mark are correct, because a bar with a value of 200 has a real length of 200, and a bar with a value of 0 has `minPointLength` set, so both bars in total should be longer than 200 on the yAxis.

**Comment by shaneshen-okta** [comment] 2022-03-16 14:24
@raf18seb 

Thanks for the update.

To me, 
Firstly, there should be same behavior no matter value `0` is at first series or last series.
<img width="787" alt="Screen Shot 2022-03-16 at 10 22 28 AM" src="https://user-images.githubusercontent.com/89863577/158611818-c7f484a3-f7c7-4310-ac7e-cbced9ffd36e.png">

Secondly, it will be desired that we can get same total length, no matter `minPointLength ` is set or not, which make more sense to end-user `equal total values, equal total length`.

**Comment by raf18seb** [comment] 2022-03-16 21:48
Thanks for sharing your thought, @shaneshen-okta!

I totally agree with first. It is a bug/inconsistency and must be fixed.
However, I don't agree (but it's just my private opinion) with your second thought (see my explanation in my [previous comment](https://github.com/highcharts/highcharts/issues/17056#issuecomment-1068496256)).

What about a new API option that would allow choosing desired behavior? If we go this way, which one should be a default behavior? Let's get some others' opinions.

**Comment by raf18seb** [comment] 2022-03-17 10:18
I'm changing my opinion. I don't think it's a bug anymore and I think it shouldn't be fixed/changed. I missed one crucial fact: those 0 points do not affect 200 bars length - they just overlap. And it makes sense - let me explain why...

Let's say we have 10 points with `y: 20` and `minPointLength: 150`. They start on yAxis exactly where they should, based on stacked values: first point at 0, second at 20, third point at 30, fourth point at 40 etc.
See this demo and GIF: https://jsfiddle.net/BlackLabel/hfL3us8m
![stacked-minpointlength](https://user-images.githubusercontent.com/23310742/158786340-d55aa7d1-5472-48a8-9fcf-87a8fb1d6043.gif)


The situation in your image is also clear: in your red rectangle, both blue and dark points with `y: 200` have the same length, but the first blue bar is covered and overlapped by dark `y: 0` point. And the position of that dark `y: 0` point is correct - it should start from 0 on the yAxis. The position of `y: 200` blue point is also correct, because it starts from 0 - it's just not visible because dark point overlaps (you can hover it to change opacity and see)
![image](https://user-images.githubusercontent.com/23310742/158786525-83c671da-ddfb-4462-bc98-c64216bdae50.png)



Summarizing: only points with positive y values affect the stack positions regardless of `minPointLength`. Every other behavior either changes the real bar's length (the ones without `minPointLength`) or stacks' positions, which messes with a chart even more.

I'm leaving a final decision for @TorsteinHonsi

**Comment by pawellysy** [comment] 2023-01-29 10:50
duplicate of #1776.

**Closed by pawellysy** 2023-01-29 10:50 UTC
Labels: Type: Undecided
