### ISSUE TITLE
HTML DataLabels and refreshing without any cause javascript exception

### ISSUE THREAD

**Issue by Dunge** [highcharts/highcharts#6418] opened 2017-02-27 20:35 UTC
Me again with another obscure issue.

I use a conditional HTML dataLabels to display an image depending on the value of a point.

Sometimes, when I pass from a chart with dataLabels present to a chart without any, I get a javascript exception:

> TypeError: Cannot set property 'onmouseover' of undefined

This only happens on these conditions:
- DataLabel is set to useHTML: true
- We had a chart rendered with at least one dataLabels present followed to a "setData()" call changing the values so that no dataLabels is present.
- We call .update() on the series properties (even if the properties to merge are empty).

#### Expected behavior
No error

#### Actual behavior
Exception thrown

#### Live demo with steps to reproduce
http://jsfiddle.net/gts29eq7/1/

Click the button.

#### Affected browser(s)
All

#### Workaround
I know I can return an empty string instead of null in the dataLabels, but this cause massive slowdown with many points.
I can also disable useHTML, but then I can't display pictures.

As a side note, your github new issue template have a typo in "behavior" (behaviour)

**Comment by jon-a-nygaard** [comment] 2017-02-28 11:44
@Dunge Thanks for reporting, we will fix this as soon as possible.

_Internal Note: Fails on [Html.js L320](https://github.com/highcharts/highcharts/blob/master/js/parts/Html.js#L320) because there is a `series.dataLabelGroup` but no div element_

**Comment by jgunderson-IAS** [comment] 2017-06-20 15:46
@jon-a-nygaard Any updates on a fix for this? Thanks!

**Comment by TorsteinHonsi** [comment] 2017-06-22 08:51
The root cause is that the SVG group has a HTML counterpart, and while the HTML counterpart is deleted, the SVGWrapper's overridden `on` function is not. The same thing theoretically happens with `translateXSetter` and `translateYSetter`. I'll fix this by simply checking for `parents[0].div`, but a complete fix would require that we restore the original functions when deleting the div in [SvgRenderer.js](https://github.com/highcharts/highcharts/blob/v5.0.12/js/parts/SvgRenderer.js#L1460-L1463).

**Closed** 2017-06-22 08:57 UTC
Labels: Bug
