### ISSUE TITLE
Highstock Stacked Column in Navigator

### ISSUE THREAD

**Issue by gmueller-ewerk** [highcharts/highcharts#7057] opened 2017-08-15 10:56 UTC
#### Expected behaviour
When adding two series as stacked columns to a chart the Highstocks navigator should also stack both columns.

#### Actual behaviour
Both series are displayed as single columns and the option
`stacking: 'normal'` to the navigator series seems not to affect the navigator in the expected behaviour.

#### Live demo with steps to reproduce
http://jsfiddle.net/t5apmp9y/

**Comment by pawelfus** [comment] 2017-08-16 08:19
Hi @gmueller-ewerk 

It should be `navigator.series.stacking`, but unfortunately it's broken: http://jsfiddle.net/t5apmp9y/1/

Closing as duplicate of #7033

**Closed by pawelfus** 2017-08-16 08:19 UTC
