### ISSUE TITLE
Highcharts.Net wrapper generates improper data setting name

### ISSUE THREAD

**Issue by schutze** [highcharts/highcharts#6869] opened 2017-06-19 13:56 UTC
#### Expected behaviour

Highcharts.NET wrapper (Highcharts.Web.Mvc.dll) Version 5.0.6360.17139 with this VB.NET code:

Dim mChart As Highcharts = New Highcharts()
mChart.Data.Table = "datatable"

should generate JSON like below:

"data":{"table":"datatable"},

I would imagine that similar C# code would probably do the same.

#### Actual behaviour

The JSON below is generated instead:

"Data_DefaultValue":{"table":"datatable"},

"Data_DefaultValue" should be "data".

#### Affected browser(s)
Browser does not matter

**Comment by sebastianbochan** [comment] 2017-06-20 09:33
Thank you for the reporting.

**Comment by schutze** [comment] 2017-06-23 14:50
@sebastianbochan Any updates on this issue? If confirmed, it seems serious enough that it should be fixed sooner than later.

**Comment by sebastianbochan** [comment] 2017-06-27 09:25
Im just waiting for reply from our .NET developer. I will let you know about details as soon as possible.

**Comment by sebastianbochan** [comment] 2017-06-28 08:20
I have the feedback from our .NET developer. The new release will be in next two days and problem will be solved.

**Comment by schutze** [comment] 2017-07-05 13:53
This issue should have a "Bug" label.

How are new wrapper releases announced?  There should be a change log [like the other products](https://www.highcharts.com/documentation/changelog).

Considering there is an example that [demonstrates the data option](http://dotnet.highcharts.com/Highcharts/Demo/Gallery?demo=ColumnParsed&theme=default), I'm surprised this issue was not caught before the .NET wrapper was released in December 2016.

**Comment by sebastianbochan** [comment] 2017-07-07 08:08
The issue is already fixed in the newest 5.0.6397.2889 version. If problem will come again, please reopen the ticket.

**Closed by sebastianbochan** 2017-07-07 08:08 UTC

**Comment by schutze** [comment] 2017-07-07 13:54
@sebastianbochan This has been corrected!

It would still be helpful to have a change log like the other products and it is odd that this wasn't caught during testing before the initial release.

**Comment by sebastianbochan** [comment] 2017-07-10 08:45
Thank you for the suggestion, I will let us our developers know about it.
