### ISSUE TITLE
Redrawing charts twice

### ISSUE THREAD

**Issue by Tesnim** [highcharts/highcharts#6237] opened 2017-01-12 14:14 UTC
#### Expected behavior
Charts should appear without redrawing.

#### Actual behaviour
Charts appear, and charts are drawn twice on every refresh.

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/jquery/3.1.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/line-basic/

#### Affected browser(s)
Chrome, Firefox

**Comment by oysteinmoseng** [comment] 2017-01-16 15:12
It looks to me like the chart is only drawn once: http://jsfiddle.net/gg4jjn6g/1/. Both `series.drawPoints` and `chart.render` are only called once. Do you have an example of a chart that is drawn multiple times?

**Comment by TorsteinHonsi** [comment] 2017-01-18 11:48
I've also noticed this recently - I think it's an issue with jsFiddle. I can see it in the OP's demo but not in @oysteinmoseng 's. Probably it happens when jsFiddle loads content from GitHub. 

Reported to jsFiddle: https://github.com/jsfiddle/jsfiddle-issues/issues/956

**Comment by Tesnim** [comment] 2017-01-23 12:02
Dear,
Thank you for replying.

No, it is not just jsFiddle issue. I am using highchart library on my ruby on rails project and I have the same issue, it is redrawing the chart twice on every second refresh.

Thanks

**Comment by TorsteinHonsi** [comment] 2017-01-24 08:02
Okay, then we need to see it live in order to find out why.

**Comment by KacperMadej** [comment] 2017-06-02 15:30
The JSFiddle issue is fixed and the problem is not visible on http://jsfiddle.net/gh/get/jquery/3.1.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/line-basic/

I am closing the issue, but in case the problem is still there please post a live demo and the issue could be reopened.

**Closed by KacperMadej** 2017-06-02 15:30 UTC
Labels: Not a bug, Website
