### ISSUE TITLE
Annotation Text disappears sometime after adding text

### ISSUE THREAD

**Issue by raghavakrishnab** [highcharts/highcharts#13326] opened 2020-04-16 09:16 UTC
#### Expected behaviour

Annotation text should not disappear.
#### Actual behaviour
Annotation Text disappears sometime's

#### Live demo with steps to reproduce

https://jsfiddle.net/BlackLabel/3cqjn7bz/
#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment] 2020-04-23 10:55
Hi @raghavakrishnab,
Thank you for reporting about the problem. Could you elaborate step by step how can I reproduce the issue? When I add a new text, its always visible.

**Comment by raghavakrishnab** [comment] 2020-04-23 11:47
Hi Sebastian,

PFB the updated jsfiddle example
https://jsfiddle.net/raghava_2121/5mLue6xv/24/

1) while adding text in second axis doesnt appear
![image](https://user-images.githubusercontent.com/61841873/80095762-5c4b1300-8560-11ea-8dfb-fb38862d8379.png)

2) after adding circle changes position always when zoom in and doesnt appear after zoomin
3) rectangle to some extent expands while zoom in but circle doesnt.


Thannks,
Raghava

**Comment by sebastianbochan** [comment] 2020-04-23 12:30
Hi @raghavakrishnab,
Thank you for details.

> while adding text in second axis doesnt appear
At this moment annotations work only with the the first axis. 
Related issue: https://github.com/highcharts/highcharts/issues/12268

> 2. after adding circle changes position always when zoom in and doesnt appear after zoomin
> 3. rectangle to some extent expands while zoom in but circle doesnt.

By default the only rectangle is scalable.

The full explanation you can find here: https://github.com/highcharts/highcharts/issues/11175

Im closing this bug as duplicate of both above.

**Closed by sebastianbochan** 2020-04-23 12:30 UTC
Labels: Status: Pending reply
