### ISSUE TITLE
Zooming in shows no data with descending ordered x axis for line chart

### ISSUE THREAD

**Issue by serkan-inci** [highcharts/highcharts#16706] opened 2021-11-26 14:06 UTC
#### Expected behaviour
We have some data where x axis is descending ordered with around 1000 data points. Line chart renders things fine but when zoomed in, plot gets blank.

#### Actual behaviour
When zooming in, show the zoomed part of the chart correctly. Interestingly, if the number of data points are less or equal to 300, things work fine.

#### Live demo with steps to reproduce
https://codepen.io/serkan-inci/pen/zYdgroM

#### Product version
Highcharts 9.3.0

#### Affected browser(s)
All browsers

**Comment by raf18seb** [comment] 2021-12-01 00:27
Hi @serkan-inci, thanks for creating the ticket!

There are 2 solutions to your problem.

1. There is a warning thrown in the console saying that Highcharts expects the data to be sorted. Unsorted data may lead to many unexpected behaviors and this is one of them.
It's enough to reverse your data (so the x data is in ascending order).
Like this: https://jsfiddle.net/BlackLabel/gyo12d7s/
Or like this: https://jsfiddle.net/BlackLabel/v8bgcafq/

Because it's working fine with correctly ordered data, I will not consider this as a bug.

2. Another solution is to increase the series.cropThreshold (the default value for a line series is 300), see API: https://api.highcharts.com/highcharts/series.line.cropThreshold
and demo: https://jsfiddle.net/BlackLabel/2k7h0v8c/

Let me know if you have any further questions.
I'm closing the ticket as not a but resolved.

**Closed by raf18seb** 2021-12-01 00:27 UTC

**Comment by serkan-inci** [comment] 2021-12-01 11:39
That's great thanks for your suggestions Rafal. I already went the option #1 you provided but #2 also seems interesting. I'll definitely give it a shot.

Thanks for your help
Serkan
