### ISSUE TITLE
toPixels and toValues not working when out of visible range

### ISSUE THREAD

**Issue by kimbrowne** [highcharts/highcharts#8753] opened 2018-08-09 06:44 UTC
#### Expected behaviour
Pixel value for an x value that is outside the visible range should be correct and convertible back to its original value.
If you take a value and apply toPixels and apply toValues to the result you should get the original value.
This works fine on values that are on the visible range but not when outside the range.
I believe toPixels is providing incorrect values and causes havoc when drawing items that cross into the range that is not visible

#### Actual behaviour
values converted by toPixels are not the same as the values converted back by toValues when outside the visible range

#### Live demo with steps to reproduce
Run the code at. There is a div above the chart that shows the results
https://jsfiddle.net/kimcb/ty1nsofa/6/

#### Product version
Highstock JS v6.1.1 (2018-06-27)

#### Affected browser(s)
Tested with Firefox  61.0.1 (64-bit)  and Chromium 68.0.3440.75

**Comment by pawelfus** [comment] 2018-08-09 12:28
Hi @kimbrowne 

Thank you for reporting this issue. You are it's broken when trying to find positions outside the current range. This is duplicate of https://github.com/highcharts/highcharts/issues/2406 - this is direct result of `ordinal` option.  Compare results: https://jsfiddle.net/BlackLabel/ty1nsofa/9/

Closing as duplicate of #2406

**Closed by pawelfus** 2018-08-09 12:28 UTC
