### ISSUE TITLE
Column chart: Xaxis not aligned to 0, even though all data is 0

### ISSUE THREAD

**Issue by amruta30** [highcharts/highcharts#19455] opened 2023-07-27 10:15 UTC
#### Expected behaviour
Xaxis should be aligned to 0

#### Actual behaviour
Observe the column chart plotted on the attached JS fiddle. Data values are all 0. Xaxis is shown below, not aligned with 0

#### Live demo with steps to reproduce
https://jsfiddle.net/82j3zfqp/

#### Product version
v11.1.0

#### Affected browser(s)
All

**Comment by karolkolodziej** [comment] 2023-07-28 07:08
HI @amruta30! 

I'm not sure if I get correctly the issue so let's clarify:
If your series has just one value through all the points (in case this is `0`) and the `yAxis` doesn't have declared `min` and `max` the chart is going to center the series in the plot area (as shown in the screenshot below). 
![Screenshot 2023-07-28 at 09 04 06](https://github.com/highcharts/highcharts/assets/57004120/443e6964-804b-4024-9b86-5514c7a308d7)
This is the desired behaviour, but you can easily change that by setting some fixed value as `yAxis` max- [demo](https://jsfiddle.net/BlackLabel/fgtwd18r/).

If I get that wrong, please elaborate on what the issue is.

**Comment by amruta30** [comment] 2023-08-02 11:37
We cannot set max as our data can vary in different scenarios. Is there any other way to achieve this?

**Comment by karolkolodziej** [comment] 2023-08-03 06:28
You can also set fixed `tickAmount`- [demo](https://jsfiddle.net/BlackLabel/kjvmq4ft/).

I'm going to close this since this is the intended behaviour. But if you have anything to add or ask about feel free to do it.

**Closed by karolkolodziej** 2023-08-03 06:28 UTC
Labels: Product: Highcharts, Status: Pending reply
