### ISSUE TITLE
Country borders become thicker on map chart when map is zoomed.

### ISSUE THREAD

**Issue by PohlodSlavik** [highcharts/highcharts#8474] opened 2018-06-14 10:04 UTC
Looks like Chrome v67 doesn't respect "vector-effect: non-scaling-stroke;" used by Highcharts for country borders on maps. Is there any workaround for this issue?
#### Expected behaviour
Border width shouldn't change when map is zoomed.

#### Actual behaviour
Border width scales together with chart zoom.

#### Live demo with steps to reproduce
Could be reproduced on Highcharts demo:
https://www.highcharts.com/maps/demo/all-maps
https://www.screencast.com/t/BLEYoYmfE

#### Product version
Latest Highmaps.js (v6.1.0)

#### Affected browser(s)
Google Chrome v67

**Comment by pawelfus** [comment] 2018-06-14 12:10
Hi @PohlodSlavik 

Thank you for reporting this bug. You are right, it's bug in Chrome, we have added workaround for this, which will be part of the next release (2-3 weeks). Take a look: https://jsfiddle.net/BlackLabel/82q9dcoj/ (demo has file loaded: http://github.highcharts.com/maps/highmaps.js ).

Closing as duplicate of #8442

**Closed by pawelfus** 2018-06-14 12:10 UTC
