### ISSUE TITLE
Organization chart tooltips on click instead of on hover

### ISSUE THREAD

**Issue by silviabalu** [highcharts/highcharts#14915] opened 2021-01-12 16:37 UTC
#### Expected behaviour
I am working on this org chart: https://jsfiddle.net/sylkitt/rs7th5q3/ and would like to have the tooltip information shown on click (click on the blue rectangle) and in a large (full-width) box below the nodes, instead of on hover. And have it disappear when moved off the rectangle.
Highcharts forum response: It should be possible by disabling tooltip (tooltip.enabled: false), and then enabling tooltip on point.events.click function and disabling it on point.events.mouseOut function. Like in this demo: https://jsfiddle.net/BlackLabel/7Lqnsg1e/

#### Actual behaviour
Something doesn't work properly: https://jsfiddle.net/BlackLabel/2e83ngw1/

**Comment by KacperMadej** [comment] 2021-01-13 12:18
Hi @silviabalu 

Thank you for contacting us about the problem.

Please elaborate on the **something** (from "Something doesn't work properly).
The demo seems to be working fine for me. 

Also, a link to the forum would be nice to get a better view of the case.

**Comment by silviabalu** [comment] 2021-01-14 16:44
Hi @KacperMadej, thank you for your reply! Sure, I'll be happy to provide additional information.

Here is the link to the Highcharts forum: https://www.highcharts.com/forum/viewtopic.php?f=9&t=45682

This is a screenshot of the actual behavior ("something" doesn't work properly), from this demo: https://jsfiddle.net/BlackLabel/2e83ngw1/. When clicking on each rectangle, instead of showing the tooltip text in a box below, the other blue rectangles disappear:
![demo on click](https://user-images.githubusercontent.com/10178475/104620157-b050d700-565c-11eb-9edc-ac5b47808222.png)

And here is a screenshot from this demo: https://jsfiddle.net/sylkitt/rs7th5q3/ showing the tooltip text on hover:

![demo on hover](https://user-images.githubusercontent.com/10178475/104620445-01f96180-565d-11eb-8354-9d6dfd9cf9b9.png)

My boss would like to have the tooltip text appear in a box below the blue rectangles when clicking on each rectangle, not when hovering over them. Is this possible?

Thank you,
Silvia

**Comment by KacperMadej** [comment] 2021-01-15 18:20
Thank you for the detailed information @silviabalu 

Click is causing a mouseOut and nested chart updated fails. This could be resolved by blocking the tooltip through the formatted (returning false prevents tooltip from showing) instead of running an update with tooltip enable: true/false. Demo: https://jsfiddle.net/BlackLabel/2e83ngw1/1/

Please let me know if the issue is resolved or are there any more problems with the case.

Technical details and source of the problem:
On click, the chart is updated (to enable tooltip) and it triggers all series update to rebuild them. The series rebuild removes points. When a hovered point is removed it executes a mouseOut event on the point. This triggers another chart update during the first chart update and throws an error - it is not expected nor supported to run another chart update while running a chart update.

**Comment by silviabalu** [comment] 2021-01-18 16:02
Thank you @KacperMadej, it works fine now! Would it be possible to have the box appear below the blue rectangles instead of over them like it is now?

**Comment by KacperMadej** [comment] 2021-01-19 16:11
@silviabalu 
Yes, this could be done using [tooltip.positioner](https://api.highcharts.com/highcharts/tooltip.positioner).
Demo: https://jsfiddle.net/BlackLabel/2e83ngw1/2/

I am closing the issue as this is not a bug but a support case, but feel free to continue here in case you have more questions about this case.

**Closed by KacperMadej** 2021-01-19 16:11 UTC
Labels: Status: Can't reproduce, Status: Pending reply

**Comment by silviabalu** [comment] 2021-01-21 16:59
Thank you @KacperMadej, this works great! I have another question, as I discovered that the tooltips have a y value of 300px that determines how far from the top of the screen they are. On the page that the chart will be, there will be more space from the top, and I need to increase that value. Can you please advise where in the code and how to adjust that value? How can I manually define it in the CSS? Thank you!

**Comment by silviabalu** [comment] 2021-01-21 17:50
@KacperMadej Never mind, I got it to work by increasing the pos.y of the tooltip. Thank you again for your help!
