### ISSUE TITLE
Shared tooltip values not aligned on mixed-series charts

### ISSUE THREAD

**Issue by ErikSwan** [highcharts/highcharts#6749] opened 2017-05-19 15:51 UTC
#### Expected behaviour
The shared tooltip will always show values from the same x-axis category for each series (at least, as long as the series points have the same x-axis values).

#### Actual behaviour
Depending on mouse positioning, the shared tooltip will occasionally show a value for some series that is off by one or more on the x-axis, even though the x-axis label in the shared tooltip remains the same. This is potentially very misleading, as the only indication that a wrong point is being chosen is the hover animation on the point marker for that series.

#### Live demo with steps to reproduce
This is reproduceable on the API demo for shared tooltips on mixed-type charts:
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/tooltip/shared-true-mixed-types/

1. Hover over the 'May' category, with your mouse near the middle of the column. The tooltip displays:

        May
        Series 1: 144
        Series 2: 71.5

    However, the value for Series 2 is actually from **June**, not May!

2. Move your mouse down near the May point for Series 2. Once your mouse gets close enough, the May point is 'selected' and the tooltip now displays the correct values:

        May
        Series 1: 144
        Series 2: 29.9

The behaivor for when this occurs is somewhat inconsistent. It seems that if your mouse enters from the top of the chart, the correct value for Series 2 is chosen the first time that the tooltip is displayed. But it's easy to reproduce the buggy behaivor by just moving your mouse around a bit to back and forth between x-axis categories.

#### Affected browser(s)
I have not found a browser that is not affected by this. From my limited testing, I can confirm the following are affected on Windows:
- Firefox 53.0
- Chrome 58.0
- IE 11

**Comment by jon-a-nygaard** [comment] 2017-05-22 06:47
Duplicate of #6687. Will be fixed in the upcoming maintenance release.

**Closed by jon-a-nygaard** 2017-05-22 06:47 UTC
