### ISSUE TITLE
Tooltip value for step serie

### ISSUE THREAD

**Issue by fgalgau** [highcharts/highcharts#19080] opened 2023-06-02 08:18 UTC
#### Expected behaviour
I have a step serie (step: left) on a chart which shows a crosshair (snap: false) for the X-axis and and the tooltip for the serie value. The tooltip value shoud remain the same for an entire step. 

#### Actual behaviour
The tooltip value will change at the middle of a step. So when the user moves the crosshair above the same step, it will show 2 different values on the same step, depending on the mouse position.

#### Live demo with steps to reproduce
https://jsfiddle.net/felixg/vyq4kesz/32/

#### Product version
Highcharts 11.0.1, Highstock 11.0.1

#### Affected browser(s)
All

**Comment by bm64** [comment] 2023-06-02 23:50
Hello @fgalgau and thanks for contacting us.

I'm closing this one as a duplicate of https://github.com/highcharts/highcharts/issues/17347 Feel free to continue discussion in the original ticket

**Closed by bm64** 2023-06-02 23:50 UTC
