### ISSUE TITLE
Misaligned titles when allowHTML is enabled

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5123] opened 2016-03-15 13:17 UTC
The problem is that title / subtitle has smaller size and is misaligned, when we set useHTML and allowHTML options.

Example:
- http://jsfiddle.net/x6soe88w/

**Comment by TorsteinHonsi** [comment] 2016-03-16 08:20
Duplicate of #4648.

**Closed by TorsteinHonsi** 2016-03-16 08:20 UTC
