### ISSUE TITLE
Regression issue with Multiple KPI gauge

### ISSUE THREAD

**Issue by narlack** [highcharts/highcharts#21578] opened 2024-07-26 08:33 UTC
Hello, i found one regression bug with Multiple KPI gauge,
When inner gauge plot rich the 100 by some reason they change position, i attached two examples
one for lastest version with bug and second for Highcharts version 10 without bug

#### Expected behaviour
When gauge never changes the position
![image](https://github.com/user-attachments/assets/06133abc-5c1c-4d36-b365-6f54467544ff)

#### Actual behaviour
When inner gauge rich 100 they move position
![image](https://github.com/user-attachments/assets/35edd577-d5f4-445d-9f3e-71cd25243d1d)

#### Live demo with steps to reproduce
Highcharts v11  (with issue): https://jsfiddle.net/toyzc2wL/3/
Highcharts v10 (without issue): https://jsfiddle.net/b4w96nfu/1/

#### Product version
Highcharts version 11

#### Affected browser(s)
Latest Chrome

**Comment by karolkolodziej** [comment] 2024-07-26 08:53
Hi @narlack!
Thank you for reporting the issue. 

Closing as a duplicate of: https://github.com/highcharts/highcharts/issues/21429

**Closed by karolkolodziej** 2024-07-26 08:53 UTC
