### ISSUE TITLE
Boost - some points are ignored in tooltip when is shared

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#8836] opened 2018-08-24 08:57 UTC
#### Expected behaviour
Points should be visible in the tooltip, when its shared

#### Actual behaviour
Some points are missed, when tooltip is shared.

#### Live demo with steps to reproduce
Too big date to create jsfiddle.

[bigdata.zip](https://github.com/highcharts/highcharts/files/2317700/bigdata.zip)

1. Run demo and observe that in some places, points are ignored in the tooltip.
2. When we zoom area (with potentionally missed point), points are generated and are visible in the tooltip.

![zrzut ekranu 2018-08-24 o 10 55 52](https://user-images.githubusercontent.com/2115686/44575476-65cd1800-a78c-11e8-9e57-e1736d09ae1a.png)

#### Product version
6.1.1

#### Affected browser(s)
Chrome  68.0.3440.106

**Internal note**
The bug can be related with https://github.com/highcharts/highcharts/issues/8166. As a result when point is invisible, is ignored in tooltip.

The `useGPUTranslations` parameter, also does not solve the issue.

@cvasseng

**Comment by TorsteinHonsi** [comment] 2018-08-27 07:53
It's a duplicate of #8818, related to how k-d-tree points (used for tooltip) were generalized.

However it's unlikely that it is related to #8166, as the WebGL rendering uses separate downsampling from the k-d-tree.

**Closed by TorsteinHonsi** 2018-08-27 07:53 UTC
Labels: Duplicate

**Comment by CaptBli** [comment] 2019-02-26 15:05
So I would suggest that you use a different method for obtaining the data.  

In the value-in-legend module, the hoverPoints are used to get the data to be displayed.  Instead I think that if you simply use the single hoverPoint to get the index then use the data in the series like the following code:

(function (H) {
	H.Series.prototype.point = {}; // The active point
	H.Chart.prototype.updateLegendValues = function () {
		if (chart.legend.display) {
			var legendOptions = chart.legend.options,
				hoverPoints;// = chart.hoverPoints;

			if (!hoverPoints && chart.hoverPoint) {
				hoverPoints = [chart.hoverPoint];
			}
			if (hoverPoints) {
				//H.each(hoverPoints, function (point) {
				//	point.series.point = point;
				//});
				H.each(chart.series, function (series) {
					var point = chart.hoverPoint;
					if (series.isSeriesBoosting) {
						series.point = jQuery.extend(true, {}, point);
						series.point.x = series.xData[point.index];
						series.point.y = series.yData[point.index];
					} else {
						series.point = series.data[point.index];
					}
				});
				H.each(chart.legend.allItems, function (item) {
					item.legendItem.attr({
						text: legendOptions.labelFormat ?
							H.format(legendOptions.labelFormat, item) :
							legendOptions.labelFormatter.call(item)
					});
				});
				chart.legend.render();
			}
		}
	};

This made all of the data show up.
