### ISSUE TITLE
Value indicators not drawn when equal to max value

### ISSUE THREAD

**Issue by chka73** [highcharts/highcharts#3792] opened 2015-02-05 13:36 UTC
Under specific conditions the value indicators don't get plotted in the chart.

In the example at http://jsfiddle.net/03swogse/ they won't show. But if you change the div height to any value **other** than 315px it will work.

**Comment by pawelfus** [comment] 2015-07-23 11:00
It looks like working fine in 4.1.7 ? I'm not sure what do you mean by "value indicators" - markers (circles)?

**Comment by jon-a-nygaard** [comment] 2016-06-16 07:11
Closing this issue due to we are not able to reproduce the issue, and it is pending reply. 
Should anyone have further information on this issue, please add a comment and/or reopen.

**Closed by jon-a-nygaard** 2016-06-16 07:11 UTC
Labels: Cant reproduce, Pending reply
