### ISSUE TITLE
zooming by using mouse scroll

### ISSUE THREAD

**Issue by nv-maya-greber** [highcharts/highcharts#18169] opened 2022-12-19 12:40 UTC
zooming can be achieved using mouse scroll, i.e., by scrolling the mouse, more or less bars will be shown within the same window
in chart line not stockChart

**Comment by bm64** [comment] 2022-12-20 00:15
Closing as a duplicate of https://github.com/highcharts/highcharts/issues/16658

**Closed by bm64** 2022-12-20 00:15 UTC
Labels: Type: Feature Request

**Comment by nv-maya-greber** [comment] 2022-12-20 04:49
@bm64 where can i see the original request and follow the progress?

**Comment by bm64** [comment] 2022-12-20 10:54
@nv-maya-greber here is the original feature request: https://github.com/highcharts/highcharts/issues/16658
You can use that thicket to follow the progress and feel free to leave your feedback there.
