### ISSUE TITLE
Inconsistent handling of xAxis / yAxis format

### ISSUE THREAD

**Issue by qoalu** [highcharts/highcharts#14210] opened 2020-09-10 18:27 UTC
#### Expected behaviour
From the docs it is expected that you may provide an object config or an array of objects for xAxis config:
> The X axis or category axis. Normally this is the horizontal axis, though if the chart is inverted this is the vertical axis. In case of multiple axes, the xAxis node is an array of configuration objects.

the Axis config is also supported by `exporting` config and as the second parameter of the `exportChartLocal`/`exportChart` functions ([chartOptions](https://api.highcharts.com/class-reference/Highcharts.Chart%23exportChart))

> Additional chart options for the exported chart. For example a different background color can be added here, or dataLabels for export only

When using the export function the order of overrides is expected to be:
1. chartOptions in Highcharts.chart config
2. chartOptions in exporting config
3. chartOptions in exportChart function call.

later overrides the former.

It is expected that the objects are **deeply merged**, similar to `lodash.merge` function.

#### Actual behaviour
chartOptions **in exporting config** (2) and exportChart **function call** (3) do not support the single object version of config. They only support the array.

when using array the merge does not work and the config specified in 2 or 3 replaces the one in 1 completely.

#### Live demo with steps to reproduce

https://jsfiddle.net/boleg/95g4sv2u/18/
rotation not kept and title not shows because of (3) overriding the (1) completely

https://jsfiddle.net/boleg/95g4sv2u/19/
custom formatter is not applied, because object config not supported
 

Click Export in both versions. 

#### Product version
 
Highcharts 8.1.2

#### Affected browser(s)
N/A

**Comment by PaulDalek** [comment] 2020-09-14 10:09
Hi @qoalu 

Thank you for reporting this issue.

**Comment by pawelfus** [comment] 2020-09-14 12:54
Duplicate of #2022 - it's a general, deep problem with handling arrays in core.

Workaround from #2022: http://jsfiddle.net/BlackLabel/ad5f6rmb/ - applied in the demo above: https://jsfiddle.net/BlackLabel/4bkcdvmp/

**Comment by qoalu** [comment] 2020-09-14 19:47
@pawelfus thank you for the workaround. this is similar to what I went with. Merging the config myself before giving it to Highcharts, overriding the full config completely

**Comment by pawelfus** [comment] 2020-09-15 08:09
Forget to close this ticket. Closing as duplicate of #14210

**Closed by pawelfus** 2020-09-15 08:09 UTC
Labels: Type: Bug, Type: Duplicate
