### ISSUE TITLE
[Docs] Few options for dataLables are missing

### ISSUE THREAD

**Issue by KrishnaKumarHariprasannan** [highcharts/highcharts#12492] opened 2019-11-25 12:02 UTC
#### Expected behaviour
Possible options for dataLabels are specified in https://api.highcharts.com/highcharts/ and https://api.highcharts.com/highcharts/tree.json

#### Actual behaviour
Options such as enabled, format, etc,. are missing

#### Live demo with steps to reproduce
Take the case for Line chart as an example: https://api.highcharts.com/highcharts/plotOptions.line.dataLabels does not list enabled or format but they both seem to work - https://jsfiddle.net/fo48ck3a/

#### Product version
highcharts@7.2.1

#### Affected browser(s)
**N/A**

**Comment by sebastianbochan** [comment] 2019-11-25 13:19
Hi @KrishnaKumarHariprasannan,
The issue has been already fixed and is available in master branch. Will be available in stable version in the next release.

Duplicate of https://github.com/highcharts/highcharts/issues/11803

**Closed by sebastianbochan** 2019-11-25 13:19 UTC
