### ISSUE TITLE
highchart graph download using jspdf

### ISSUE THREAD

**Issue by nitin0708** [highcharts/highcharts#4299] opened 2015-06-18 10:56 UTC
Hi 

How to convert a highchart graph to pdf using jspdf? highchart generating a svg image.

Thanks
Nitin

**Comment by nitin0708** [comment] 2015-06-18 11:46
![screenshot from 2015-06-18 17 11 44](https://cloud.githubusercontent.com/assets/10219173/8230405/8a69d444-15dd-11e5-9747-481b71ca57b5.png)

I am trying 3 graph in a row but they overlap to each other.
Is there any solution for this one?
Thanks
Nitin

**Comment by highslide-software** [comment] 2015-06-22 13:33
This is not a Highcharts bug, rather a support request. In the future, please see www.highcharts.com/support.

We have actually tried jspdf with Highcharts, but with poor result. There's a plugin, [http://www.highcharts.com/plugin-registry/single/37/highcharts-export-clientside](Client side export), that implements jspdf, and you can study that implementation. However, it only exports a rasterized version of the chart, and in our opinion the only reason to export to PDF would be to get a vectorized file. So we have tried to do the same with a jspdf plugin, https://github.com/CBiX/svgToPdf.js/, but it doesn't work riably.

**Comment by TorsteinHonsi** [comment] 2016-08-09 06:52
Duplicate of #5278.

**Closed by TorsteinHonsi** 2016-08-09 06:52 UTC
