### ISSUE TITLE
Tooltip occures error after re-creating chart while mouseover the old one

### ISSUE THREAD

**Issue by uaoleg** [highcharts/highcharts#4013] opened 2015-03-19 21:41 UTC
1. We have instantiated chart
2. We set mouse over the chart so we can see a tooltip
3. We destroy current chart and create a new one (at the same place)
4. Now if we set mouse over the new chart tooltips are shown correctly but an errors appear in developer console (on each mouse move): `Uncaught TypeError: object is not a function`

![image](https://cloud.githubusercontent.com/assets/1773775/6741583/70e36f5a-ce91-11e4-9faf-d88c27b11977.png)

**Comment by highslide-software** [comment] 2015-03-20 14:42
I failed to reproduce this. See http://jsfiddle.net/highcharts/9num0d57/. Click the chart to destroy and re-generate when the tooltip is visible.

**Comment by jon-a-nygaard** [comment] 2016-04-26 09:41
Closing this issue due to: We are not able to reproduce the issue, and it is pending reply. 
Should anyone have further information on this issue, please add a comment and reopen.

**Closed by jon-a-nygaard** 2016-04-26 09:41 UTC
Labels: Cant reproduce, Pending reply
