### ISSUE TITLE
If specified the "column" for each node, the links between nodes are not drawn correctly

### ISSUE THREAD

**Issue by zlateskud** [highcharts/highcharts#8865] opened 2018-08-30 14:51 UTC
Hello,

We have a problem with the sankey diagram.

If specified the "column" for each node, the links between nodes are not drawn correctly.
Besides that, in Internet Explorer 11 compatibility mode 7, using oldie.js the graphic isn't showing at all if is specified the column. Without it everything looks ok.

In attachment you find the code example

Some images on different browsers:
1)With no colun in Chrome

![normal_chrome](https://user-images.githubusercontent.com/7415552/44859451-da1c2580-ac7c-11e8-9684-e2f98311555c.jpg)

2)With no colun in IE11/CM7

![normal](https://user-images.githubusercontent.com/7415552/44859464-e2746080-ac7c-11e8-9bcb-23efc8b3e93e.jpg)

3)Column specified in Chrome

![cs_chrome](https://user-images.githubusercontent.com/7415552/44859484-ec965f00-ac7c-11e8-98c9-0025d30aa9e4.jpg)

4)Column specified in IE11/CM7

![cs_oldie](https://user-images.githubusercontent.com/7415552/44859505-f5873080-ac7c-11e8-8870-63d81f0adc44.jpg)

#### Live demo with steps to reproduce
http://jsfiddle.net/0j8hds9u/4/

#### Product version
Highcharts JS v6.1.1 (2018-06-27)

#### Affected browser(s)
Chrome 68 and IE11 Compatibility mode 7

Thank you.

**Comment by KacperMadej** [comment] 2018-08-31 10:33
Hi @zlateskud 

Thank you for reporting about the bug.

After debugging in IE7 looks like there's a problem with `forEachPolyfill`.
It should:

>  executes the provided callback once for each element present in the array in ascending order. **It is not invoked for index properties that have been deleted or are uninitialized**

but it runs for all array indexes from 0 to length-1

```js
		    H.forEachPolyfill = function (fn, ctx) {
		        var i = 0,
		            len = this.length;
		        for (; i < len; i++) {
		            if (fn.call(ctx, this[i], i, this) === false) {
		                return i;
		            }
		        }
		    };
```

#### As a workaround:
use this code after loading `oldie` module, but before creating any charts:
```js
Highcharts.forEachPolyfill = function (fn, ctx) {
    var i = 0,
        len = this.length;
    for (; i < len; i++) {
        if (
            this[i] !== undefined && // added check
            fn.call(ctx, this[i], i, this) === false
        ) {
            return i;
        }
    }
};
```

**Comment by zlateskud** [comment] 2018-09-03 06:40
Hi @KacperMadej ,
this solves the problem in IE11/CM7, but remain the problem with the column.
If specified the "column" for each node, the links between nodes are not drawn correctly.

![a1](https://user-images.githubusercontent.com/7415552/44971178-49379980-af5d-11e8-8162-a9cb3e819c0d.png)


Thank you.

**Comment by TorsteinHonsi** [comment] 2018-09-05 13:32
I think the problem with the badly drawn columns is that you start by assigning nodes to column 1, and there are not nodes assigned to column 0. When starting from 0, it looks correct: http://jsfiddle.net/highcharts/0j8hds9u/18/

**Closed** 2018-09-05 13:51 UTC
Labels: Bug

**Comment by tynorton** [comment] 2018-09-26 15:13
This change appears to have broken our `column` chart plotlines.

![image](https://user-images.githubusercontent.com/811086/46089670-e3a58a00-c163-11e8-8e7d-0aaba9c6222d.png)

Is there a case tracking this regression?

**Comment by tynorton** [comment] 2018-09-26 18:15
Maybe not this issue, definitely part of 6.1.4.

**Comment by keeslinp** [comment] 2018-09-26 20:33
I think 6.1.4 broke stuff for us as well. Our tests started failing with an error `m.getSpanWidth is not a function` in highcharts. highcharts is a transitive dependency of react-highcharts which doesn't have its dependencies locked down so we were updated unexpectedly.

**Comment by KacperMadej** [comment] 2018-09-27 08:03
@keeslinp Seems to be a `react-highcharts` issue, so you should probably report this to the authors of that software - it's an official react wrapper. Without a live demo there's nothing for us to debug, identify and fix, so please provide a way for us to work with a demo showing the problem.

**Comment by keeslinp** [comment] 2018-09-27 13:54
Sounds good, I'll report it to them. It is worth noting though that forcing
high charts back down a version fixes the problem.

**Comment by TorsteinHonsi** [comment] 2018-09-28 11:49
> Our tests started failing with an error m.getSpanWidth is not a function in highcharts.

See #9058, it seems that the react tests run jsdom in the background, and jsdom doesn't support `tspan.getSubStringLength`.

**Comment by maljones** [comment] 2018-09-28 18:02
@tynorton's issue looks somewhat similar to mine. Since the 6.1.4 fix, line charts have filled areas: https://www.ecosresults.org/states/alabama/. Rolling back to 6.1.3 gives the lines back there proper dimensions (although it's ignoring my series styling when I do that).

<img width="598" alt="ecosresults-linechart-err" src="https://user-images.githubusercontent.com/3082939/46225399-1350bf80-c327-11e8-9fc9-df25692fe2a4.png">

Browsers:

Chrome Mac: Version 69.0.3497.100 (Official Build) (64-bit)
Firefox Mac: 62.0 
Client reported it on iOS Safari: Unsure which version

**Comment by KacperMadej** [comment] 2018-10-01 08:13
Hi @maljones 

If you would like to report a bug please open a new issue - your last comment doesn't look like related to the original issue reported here, so it would be more readable if it were a separate issue. If you have a problem, but are not sure if it's a bug please contact technical support first to confirm - https://www.highcharts.com/support
