### ISSUE TITLE
3D column dataLabels alignment issue

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#4834] opened 2015-12-11 15:55 UTC
Using beta parameter in 3D column chart is leading to missalignment of dataLabels. DataLabels are positioned in regard to size of whole chart, when chart is resizing to smaller width dataLabels are moving and finally they can be in the right position.

example: http://jsfiddle.net/2ty5ex58/13/

**Comment by KacperMadej** [comment] 2015-12-11 16:02
Looks like tooltip is misplaced too.

**Comment by jon-a-nygaard** [comment] 2016-07-18 14:39
Closing this since it is a duplicate of #4160. Please follow the referenced issue to see comments and updates on the issue.

**Closed by jon-a-nygaard** 2016-07-18 14:39 UTC
Labels: Bug
