### ISSUE TITLE
On charts higher than 1000 pixels hidden labels appear shifted up by 999 pixels

### ISSUE THREAD

**Issue by ynagorny** [highcharts/highcharts#3883] opened 2015-02-24 23:04 UTC
It appears that the code is using the technique of moving hidden labels to -999 y position to hide them. In charts that are higher than 1000 pixels this results in the label remaining on the screen.

Here's an example: http://jsfiddle.net/r16q8yu9/

Note the label 0.734 displayed at the top disconnected from its axis. If you move the date slider you will see different labels appear at the top.

**Comment by KacperMadej** [comment] 2018-05-29 11:27
Duplicate of closed and resolved #4768

**Closed by KacperMadej** 2018-05-29 11:27 UTC
