### ISSUE TITLE
Shared tooltip is not working with non grouping bar chart.

### ISSUE THREAD

**Issue by djhahe** [highcharts/highcharts#14705] opened 2020-11-30 04:52 UTC
#### Expected behaviour
I got an issue during upgrade highchart from v4 to v8. 
In v4, when grouping is false and shared tooltip config is true, the tooltip was showing value of all series.

#### Actual behaviour
However in v8, only hovered bar was showing on the tooltip. 

#### Live demo with steps to reproduce
v8: https://jsfiddle.net/Lktrjmf2/6/
v4: https://jsfiddle.net/7jw94Lkm/

#### Product version
Highcharts 8.2.2

**Comment by PaulDalek** [comment] 2020-11-30 12:39
Hi @djhahe 

Thank you for reporting this issue. This is not a bug. In fact, the previous behavior was incorrect as the `clientX` property of points was compared (which is the pixel position on axes) and not the actual timestamps. For more information visit this issue: #5832 (and the commit wich closed it: f3bc93d672321da91534cdda141ee43e1b506c7f).

**Closed** 2020-11-30 12:39 UTC
Labels: Type: Not a bug
