### ISSUE TITLE
Bar.dataLabels performance

### ISSUE THREAD

**Issue by clementbalestrat** [highcharts/highcharts#2509] opened 2013-12-05 14:21 UTC
I need to load a bar chart in my application, with a large amount of data. I found this chart took too much time to be generated so I started to investigate on this performance issue. It appears that this is because of dataLabels I use in front of each bar. Without this option

```
bar: 
  dataLabels:
    enabled: true
```

(so without the data labels), the chart's loading is 2 times faster.
According to you, is it a normal behavior ? Does the dataLabels option can lead to a performance issue ?

**Comment by oysteinmoseng** [comment] 2018-05-25 13:07
Closing this as it is not a bug.

For performance tips in Highcharts, including the Boost module, see https://www.highcharts.com/docs/getting-started/frequently-asked-questions#optimize-performance.

**Closed by oysteinmoseng** 2018-05-25 13:07 UTC
