### ISSUE TITLE
Secondary y axis scales weirdly in case there is only a single data point below 1

### ISSUE THREAD

**Issue by HuXiKa** [highcharts/highcharts#14940] opened 2021-01-15 08:29 UTC
#### Expected behaviour
Secondary y axis scale is reasonable for a series where the single value is lower than 1

#### Actual behaviour
The axes always seem to have 0-10 as min/max values, even if the number is really small and ceiling seems to be not working

#### Live demo with steps to reproduce
https://jsfiddle.net/06j7q8re/

Please see that in case the series mapped to the secondary axis contains a value between 0 and 1 the axes max value seem to be always set to 10. In the starting point of the example the series value is set to 0.7, if you

- change it to 70 it works as "expected", the data point resides close to the center
- change it to 0.07 the problem is even more prominent
- setting the ceiling option to 1 seems to be disregarded and not having any effect

#### Product version
8.1.2, seems to be affecting latest version as well

#### Affected browser(s)
Verified in Chrome, didn't check other browsers

**Comment by sebastianbochan** [comment] 2021-01-15 12:29
Hi @HuXiKa,
Thank you for reporting. By default, axes and ticks are aligned, but you can disable it by the option: [alignTicks](https://api.highcharts.com/highcharts/chart.alignTicks).

Demo:
- https://jsfiddle.net/BlackLabel/rxt2f15o/

**Comment by HuXiKa** [comment] 2021-01-15 12:55
Hey @sebastianbochan, thanks for the quick turnaround! My expectation would be that no matter what the single value is (70, 0.7, 0.07) the axes should behave the same way as it does when the value is 70 (which I think is the correct behavior) - meaning that for 0.7 I would expect all of the ticks to be the same, just tenth of the value for each tick, and for 0.07 it should be one hundreth, and so on. Your suggestion of using alignTicks seems to work, however we would like to still see more than just one tick for our scenario.
Also if you change the example, and include another value for the secondary series, for example 0.7 and 0.8 the axis calculation seem to be producing the proper result. I think the problem is for some reason with the use case of having just one value, and having that value to be smaller than 1.

**Comment by HuXiKa** [comment] 2021-01-18 09:12
Hi @KacperMadej your solutions does what I expect partially - I'm still a bit confused still about the min and max values for the axis. Also, I'm not sure why, but if I change the series type from line to bar, `softThreshold` seems to be doing the exact opposite of what I would expect (if it is set to `false`, the max value is 10, however if I set it to `true` it becomes 0.96, so the flag behaves the completely opposite compared to the line case).

In theory we could add a check for this, however I still think that in the original case the series should have the same min and max values, with the same ticks, no matter how the series is rendered (line or bar). I know I'm asking a lot of question here, so if you prefer I can create multiple tickets, but basically what I'm after is consistent secondary axes scaling with a single datapoint.

**Comment by HuXiKa** [comment] 2021-01-18 13:29
Thanks @KacperMadej for the detailed explanation, appreciated! It make perfect sense, and it also seems to be working on the latest version. However setting threshold to 0 on version 8.1.2 doesn't work, and the problem still persist. Is there a workaround for that version perhaps?

**Comment by KacperMadej** [comment] 2021-01-18 16:52
Maybe setting `softThreshold` to `false` could help? https://jsfiddle.net/BlackLabel/auq967nf/1/

**Comment by HuXiKa** [comment] 2021-01-18 17:18
That seems to solve it for 8.1.2, but has the opposite effect in the latest version. I guess this is fine for now, however it is a bit confusing and hard to wrap ones head around. I'm happy with the resolution, you may close this ticket or keep it open for a tactical fix, not sure if this can be classified as a bug or not. 

Thanks for your insights and help, appreciated!

**Comment by KacperMadej** [comment] 2021-01-19 16:02
Happy to see your problem resolved.

The issue is fixed in the newest code version, so I am closing this as resolved.
The solution for 8.1.2 is to update to 8.2.2+ or use the workaround.

**Closed by KacperMadej** 2021-01-19 16:02 UTC
Labels: Status: Pending reply
