### ISSUE TITLE
Responsive attribute

### ISSUE THREAD

**Issue by hn1** [highcharts/highcharts#14057] opened 2020-08-16 21:35 UTC
If you set the resposive attributes, when you resize browse, all click events on the xAxis are nuked and will not function.

**Comment by pawelfus** [comment] 2020-08-17 08:35
Hi @hn1 

Thank you for reporting the issue. We don't provide click events on xAxis. You either use 3rd party plugin or have some custom code to do that. Probably on responsive change you need to add click events to new xAxis again.

Closing as not a bug.

**Closed by pawelfus** 2020-08-17 08:35 UTC
Labels: Type: Not a bug

**Comment by hn1** [comment] 2020-08-17 17:48
Hi
That's strange. So why does this code provide click events for the xAxis:

xAxis: {
                    categories: data.categories,
                    labels: {
                        rotation: 75,
                        style: {
                            cursor: "pointer"
                        },
                        formatter: function () {

                             var tick = this.axis.ticks[this.pos]

                             var val = this.value

                             if (tick) {
                                 tick.label.element.onclick = function () {
                                     window.open("
https://localhost:44369/Search/StatsDiscovery/" + val);
                                 }
                             }
                             return 'Listing ' + this.value + ' Discover '
+ ' ► '

                        }
                    }
                },

**Comment by pawelfus** [comment] 2020-08-18 07:55
This does not work: https://jsfiddle.net/BlackLabel/e9kgso14/1/ - this works only after rendering xAxis again (e.g. calling `xAxis[0].update()`, after resizing window or showing/hiding series from legend). Instead, did you consider using [custom-events](https://github.com/blacklabel/custom_events/) plugin?
