### ISSUE TITLE
xAxis.labes.useHTML makes labels overlapping tooltip while tooltip.shared = true

### ISSUE THREAD

**Issue by grzesiekgs** [highcharts/highcharts#4855] opened 2015-12-16 11:41 UTC
http://jsfiddle.net/dhrLhmmt/8/

Try to keep mouse cursor on xAxis, so tooltip will position somewhere on the bottom.

As you can see, labels are being draw over tooltip.

I've temporaily fixed this by changing tooltip.getPosition function. Now it checks if calculated tooltip position is outside plotArea, if true - readjust it.
But I would realy like some real fix. 

Any tips?

**Comment by pawelfus** [comment] 2015-12-16 11:57
Duplicate of #2528.
Please, read [labels and string formatting](http://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting). In short, HTML elements are always on top of SVG, so you have two solutions:

- use [`tooltip.positioner`](http://api.highcharts.com/highcharts#tooltip.positioner) (no need to change `getPosition` method)
- enable `useHTML` for the tooltip. Disable default SVG styling (like [backgroundColor](http://api.highcharts.com/highcharts#tooltip.backgroundColor) or [borderWidth](http://api.highcharts.com/highcharts#tooltip.borderWidth)), and apply them in [`tooltip.formatter`](http://api.highcharts.com/highcharts#tooltip.formatter).

**Closed** 2016-10-17 14:11 UTC
Labels: Duplicate
