### ISSUE TITLE
Cannot read property 'mouseIsDown' of undefined

### ISSUE THREAD

**Issue by arnabk** [highcharts/highcharts#5019] opened 2016-02-09 04:04 UTC
Around 20000 issues reported by trackjs with this message. Not sure where it is getting triggered. Any idea why this would show up in production whereas it does not show any issues in our development/testing?

[webtrader.binary.com/beta](url)

<img width="676" alt="screen shot 2016-02-08 at 9 04 25 pm" src="https://cloud.githubusercontent.com/assets/446864/12907359/99c1af4c-cea7-11e5-9938-1dcf5e635dc4.png">

**Comment by TorsteinHonsi** [comment] 2016-02-09 08:28
Thanks for reporting, this is a duplicate of #4998. It was fixed and published with yesterday's release, v4.2.3.

**Closed** 2016-02-15 00:43 UTC
