### ISSUE TITLE
el.style bug on IE 10 touch

### ISSUE THREAD

**Issue by ghost** [highcharts/highcharts#2767] opened 2014-03-03 16:50 UTC
Hi.
I have an intermittent bug on line 355 of higcharts.src.js version 3.0.9 (`extend(el.style, styles);`). Seems that sometimes el is null running on windows touch devises. I had this particularly on IE10 of a surface device.

I applied this code and it seems to work ok, Doesn't seem to be missing nothing but I'm still not sure of side effects.

        if(el != null && el !== UNDEFINED) {
    	    extend(el.style, styles);
	}

**Comment by jon-a-nygaard** [comment] 2016-04-26 09:53
Closing this issue due to: We are not able to reproduce the issue, and it is pending reply. 
Should anyone have further information on this issue, please add a comment and reopen.

**Closed by jon-a-nygaard** 2016-04-26 09:53 UTC
Labels: Cant reproduce, Pending reply
