### ISSUE TITLE
Issue- When we download stacked bar graph with color gradient of lighter shades by default its taking black shades.

### ISSUE THREAD

**Issue by vidyaflorency** [highcharts/highcharts#16868] opened 2022-01-10 15:56 UTC
#### Stacked bar graph is not taking lighter gradient colors in colored formate when we export the graph in pdf.

The below graph should download with exact colors but instead of a lighter shade, it's taking black color. 
Real graph with color gradient expected to download with same colors:
![image](https://user-images.githubusercontent.com/68862993/148796412-53a3937e-905f-4d2a-b08a-5ff70b87a601.png)

Current behavior:
[manpowerReport_pscAdminUserId_100120221055276790834519839761132.pdf](https://github.com/highcharts/highcharts/files/7840086/manpowerReport_pscAdminUserId_100120221055276790834519839761132.pdf)

**Comment by vidyaflorency** [comment] 2022-01-11 20:34
Hi @raf18seb  

I have created one stacked bar graph with linear gradient colors. It looks like below attachment. 
![image](https://user-images.githubusercontent.com/68862993/149016506-04311bec-962c-41fa-8d9c-3b3eebffe646.png)

The gradient starts with a color and ends with an incremented color in a single stacked bar. This is the code for stops- 

  const massageWithColor = (dataSet) => {
    var increment = 1 / (dataSet.length + 1);
    var start = 1 - increment * dataSet.length;

    var massagedData = dataSet.map((dataItem) => {
      var dataStart = start;
      start = dataStart + increment;
      return {
        ...dataItem,
        color: {
          linearGradient: { x1: 0, x2: 0, y1: 0, y2: 1 },
          stops: [
            [0, `rgba(0, 51, 153, ${dataStart}`],
            [1, `rgba(0, 51, 153, ${dataStart + increment}`]
          ]
        }
      };
    });
    return massagedData;
  };


When I export this graph in pdf, it was exporting in black instead of colors.

**Comment by raf18seb** [comment] 2022-01-12 11:08
@vidyaflorency,

I was supposed to tag it as a bug, fortunately I found the cause! You're missing the closing bracket in `rgba(`
It looks like Chrome doesn't care about brackets that much and it's working fine in a standard browser, however, a missing bracket fails in the export server environment.

Closing as resolved.

**Closed by raf18seb** 2022-01-12 11:08 UTC
Labels: Status: Can't reproduce, Status: Pending reply
