### ISSUE TITLE
Version 5.0.11 - missing charts

### ISSUE THREAD

**Issue by sobhaduvvuri** [highcharts/highcharts#6693] opened 2017-05-05 18:25 UTC
#### Expected behaviour
We are using this javascript library and using the default meaning without any particular version seems to break charts. We are not seeing any charts. 
We fixed it by using the older version 5.0.10.
Earlier, we were using <script src=“https://code.highcharts.com/highcharts.js”></script> and now, we switched to <script src=“https://code.highcharts.com/5.0.10/highcharts.js”></script> and that seemed to bring our charts back.

**Comment by TorsteinHonsi** [comment] 2017-05-08 08:32
Thanks for reporting! Where can we see this live?

**Comment by SeqviriouM** [comment] 2017-05-12 13:59
We have the same problem. In our project we are rendering charts in containers, that has property `display: none` by default. I think this line https://github.com/highcharts/highcharts/blob/master/js/parts/Chart.js#L816 breaks detecting correct chart's size at the future (`getChartSize()`)

**Comment by TorsteinHonsi** [comment] 2017-05-15 08:45
In what browser did you see this? I can't reproduce it in http://jsfiddle.net/highcharts/tos43bhr/1/, however I see that the container height of 300px is not respected, which is because the height is set to 0 and then defaults to 400. I'll upload a fix for that. 

If you can help me replicate the problems where the chart goes completely missing, I'll be able to inspect further.

**Comment by SeqviriouM** [comment] 2017-05-15 08:55
I was an inaccurate: in my case all charts has default height 400px instead of its actual size. 

Thanks for fixing!

**Comment by TorsteinHonsi** [comment] 2017-05-16 13:34
You're welcome. I'll close this issue now. If @sobhaduvvuri can help us reproduce missing charts, we'll open it again.

**Closed by TorsteinHonsi** 2017-05-16 13:34 UTC
Labels: Cant reproduce
