### ISSUE TITLE
Organisational Chart child of a hanging node layout issues

### ISSUE THREAD

**Issue by jethas-bennettjones** [highcharts/highcharts#14054] opened 2020-08-14 19:17 UTC
#### Expected behaviour
When there is a hanging node with a child whose layout is set to hanging, all nodes should be visible.

#### Actual behaviour
When the node's layout is set to hanging, the nodes are hidden behind the parent's sibling nodes.
When the node's layout is set to normal, the nodes are shifted off into another column.

#### Live demo with steps to reproduce
https://jsfiddle.net/gma7etru/1/

#### Product version
Highchart v: 8.1.2

#### Affected browser(s)
Chromium-based (Tested only in New Edge).

**Comment by sebastianbochan** [comment] 2020-08-17 08:46
Hi @jethas-bennettjones,
Thank you for reporting. The issue has been already reported.

Im closing the ticket as duplicate of https://github.com/highcharts/highcharts/issues/13915

**Closed by sebastianbochan** 2020-08-17 08:46 UTC
