### ISSUE TITLE
MouseTracking not working properly on chrome

### ISSUE THREAD

**Issue by pmilitowski** [highcharts/highcharts#20094] opened 2023-11-07 08:19 UTC
#### Expected behaviour
The chart does display correctly

#### Actual behaviour
The chart does not display correctly

#### 
![Zrzut ekranu z 2023-11-07 09-11-05](https://github.com/highcharts/highcharts/assets/34986327/4d458adf-2a0c-4a89-8dd9-66eb4421287f)
Live demo with steps to reproduce
https://jsfiddle.net/api/post/library/pure/

#### Product version
highcharts 11.1.0

#### Affected browser(s)
Chrome 117.0.5938.149

**Comment by bm64** [comment] 2023-11-07 18:30
Hello @pmilitowski 

The provided link seems to be broken. Could you provide me with working one?

**Comment by pmilitowski** [comment] 2023-11-07 18:48
The chart is an example from
https://www.highcharts.com/demo/highcharts/pie-chart opened in
JSFiddle.

The problem only occurs in chrome on linux.

**Comment by pmilitowski** [comment] 2023-11-08 06:13
The problem disappears when you turn off hardware acceleration in Chrome

**Comment by bm64** [comment] 2023-11-09 08:26
@pmilitowski I have tested it on Asahi Linux, Chrome v119.0.6045.59, both with hardware acceleration enabled and disabled but everything seem to work correctly. If we're unable to reproduce the issue, we may be unable to provide a solution. Could you please provide more details such as your Linux distribution, chrome version and anything relevant?

**Comment by pmilitowski** [comment] 2023-11-09 09:24
System is Debian 11
Chrome 117.0.5938.149 (64-bit)

**Comment by pmilitowski** [comment] 2023-11-09 09:38
On Chrome 119.0.6045.123 (64-bit) the error still occurs.

**Comment by pmilitowski** [comment] 2023-11-09 09:42
I checked on another computer with the same configuration and there is no problem there.
Perhaps there is no point in looking for it.

**Comment by bm64** [comment] 2023-11-09 10:14
@pmilitowski thanks for double checking that! In that case I'm closing the issue for now, but if anything new regarding this comes up, do not hesitate to reopen.

**Closed by bm64** 2023-11-09 10:14 UTC
Labels: Status: Can't reproduce, Status: Pending reply
