### ISSUE TITLE
No text when print chart on Chrome

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#10132] opened 2019-02-13 16:40 UTC
#### Actual behaviour
When I want to print the chart and click "export" button then **Print chart**, the words are displayed incorrectly:
![printchrome](https://user-images.githubusercontent.com/23310742/52727870-71b8ca80-2fb6-11e9-93fa-f80f0bae39dd.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/nyh6z092
Export button -> Print chart

#### Product version
Highcharts 7.0.3

#### Affected browser(s)
Chrome 72.0.3626.96 (x64) Windows 10

**Comment by KacperMadej** [comment] 2019-02-13 17:43
Closing as a duplicate of https://github.com/highcharts/highcharts/issues/10092

**Closed by KacperMadej** 2019-02-13 17:43 UTC
