### ISSUE TITLE
stickyTracking weird behaviour with tooltip

### ISSUE THREAD

**Issue by Metzlmane** [highcharts/highcharts#5740] opened 2016-09-28 15:35 UTC
#### Expected behaviour
I think the tooltip should stick to the closest point, next to the mouse

#### Actual behaviour
It jumps up and down and sometimes somewhere else even if i'm not close to the line. 
I tried different options but no effect.
Sometimes whole lines are not highlighted/slectable.

#### Live demo with steps to reproduce

http://jsfiddle.net/ex9rwn0k/

Move the mouse  top where the peak downwards is. On top of the lines, the tooltip for the lowest line appears. 
#### Affected browser(s)
all browsers

**Comment by oysteinmoseng** [comment] 2016-09-29 09:25
Seems to be a regression in 4.2.7. Worked fine in 4.2.6.

**Comment by oysteinmoseng** [comment] 2016-09-29 09:27
Actually fixed in bugfix branch: http://jsfiddle.net/ex9rwn0k/1/
Probably duplicate of #5721.

**Closed by oysteinmoseng** 2016-09-29 09:27 UTC
Labels: Bug, Regression
