### ISSUE TITLE
getSVGForExport incorrectly parses svg and circle to text and tspan

### ISSUE THREAD

**Issue by martinkrulltott** [highcharts/highcharts#17136] opened 2022-03-29 10:07 UTC
#### Expected behaviour
Using `getSVGForExport` should output the same format (same DOM elements) as the input. e.g. input `svg` and `circle` should be outputted as `svg` and `circle`.

#### Actual behaviour
The function `getSVGForExport` incorrectly processes `svg` within the input from `svg` and `circle` to `text` and `tspan`.

E.g. if the input to `getSVGForExport` contains the following:
```
<div style="display: flex; align-items: center; margin-bottom: 4px;" class="myClass1”>
  <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" version="1.1"  style="margin-right:5px" class="myClass2">
    <circle cx="6.5" cy="6.5" r="6.5" fill="#a8bf24"></circle>
    </svg>
  <span class="data-test-series-key-item-name">Some name</span>
</div>
```

the output will then contain the following incorrect transformation:

```
<text x="5.001" style="color:#212934;cursor:pointer;font-size:13px;font-weight:normal;font-style:normal;fill:#212934" text-anchor="start" data-z-index="2" y="16”>
  <tspan style="display:flex;align-items:center;margin-bottom:4px" class="myClass1”>
     <tspan width="13" height="13" style="margin-right:5px" class="myClass2”>
        <tspan cx="6.5" cy="6.5" r="6.5" fill="#a8bf24"/>
        </tspan>
     <tspan class="data-test-series-key-item-name">Some name</tspan>
  </tspan>
</text>
```

When in turn the output svg above is parsed in a browser, the "circle" / "bullet point" (look for class="myClass2” above) is effectively missing in the rendered result, as adding a `width` and `height` to a `tspan` has no effect.

#### Live demo with steps to reproduce
Here's a demo of my Highcharts config. However it doesn't contain the `getSVGForExport` part as I haven't figured out how to use that in a demo instance.
https://jsfiddle.net/martinkrulltott/gua2jyvs/4/

#### Product version
Highcharts 9.1.2

#### Affected browser(s)
Chrome

**Comment by raf18seb** [comment] 2022-03-29 13:29
Hi @martinkrulltott, thanks for creating a ticket!

You need to set exporting.allowHTML to `true`, see updatek demo: https://jsfiddle.net/BlackLabel/h4xcn2jy/

Remember to add your tags to the white list, see warnings in the console and docs: https://www.highcharts.com/docs/chart-concepts/security

Simplified demo: https://jsfiddle.net/BlackLabel/4rp1sf0n/

Closing as not a bug and resolved.

**Closed by raf18seb** 2022-03-29 13:29 UTC
