### ISSUE TITLE
[Bug]: Data label for last item disappears if there are more than ~30 data points.

### ISSUE THREAD

**Issue by zachdtaylor** [highcharts/highcharts#17070] opened 2022-03-09 22:57 UTC
#### Expected behaviour
The last data label is visible above the last data point.

#### Actual behaviour
The last data label is in the DOM, but its `y` attribute is set to `-9999` so it's not visible, as in this example:

![Screen Shot 2022-03-09 at 3 56 56 PM](https://user-images.githubusercontent.com/19400680/157553080-d891d1fd-9c7c-42bd-9b98-01816a076b43.png)

#### Live demo with steps to reproduce
1) Turn on dataLabels and rotate labels to 270.
2) Add more than ~30 data points. Sometimes 31 triggers it, sometimes I have to do 33 or so.

https://jsfiddle.net/e6tpL091/7/

#### Product version
Highcharts v10.0.0

#### Affected browser(s)
Brave is the only one I've confirmed.

**Comment by raf18seb** [comment] 2022-03-11 15:00
Closing as a duplicate of https://github.com/highcharts/highcharts/issues/9687

**Closed by raf18seb** 2022-03-11 15:00 UTC
Labels: Type: Bug, Product: Highcharts, Status: Has workaround
