### ISSUE TITLE
Highcharts not unsetting xAxis events

### ISSUE THREAD

**Issue by govinda18** [highcharts/highcharts#15565] opened 2021-04-23 05:41 UTC
#### Expected behaviour
Should update xAxis events

#### Actual behaviour
Adds the events handlers at the top

#### Live demo with steps to reproduce
https://jsfiddle.net/Layqw7cs/

#### Product version
Highcharts v9.0.1

#### Affected browser(s)
Chrome

**Comment by khlieng** [comment] 2021-04-23 06:25
Duplicate of #6943.

**Closed by khlieng** 2021-04-23 06:25 UTC
Labels: Type: Duplicate
