### ISSUE TITLE
Highcharts hidden information is getting read by jaws where the graph is implemented, tried with accessibility attributed hidden-aria etc. 

### ISSUE THREAD

**Issue by himnigam** [highcharts/highcharts#20341] opened 2023-12-21 10:33 UTC
#### Expected behavior
excess/hidden information should not be read in jaws or screen reader

#### Actual behavior
excess/hidden information is getting read in jaws or screen reader

#### Live demo with steps to reproduce
open highcharts page where graph is implemented, start screen reader or jaws

#### Product version
"highcharts": "10.1.0",
"highcharts-react-official": "3.1.0",

#### Affected browser(s)
chrome & edge

**Comment by oysteinmoseng** [comment] 2024-01-26 16:29
Hi @himnigam, this is by design and comes from user testing with screen reader users. For complex structures like interactive charts users found it not practical to convey all the required information by marking up visible elements.

It is possible to configure what screen readers will read out, however. See the [Advanced accessibility configuration](https://www.highcharts.com/docs/accessibility/configure-the-accessibility-module) documentation article for more information.

I am closing this issue for now, but feel free to comment with more information if you would like it reopened.

**Closed by oysteinmoseng** 2024-01-26 16:29 UTC
Labels: Product: Highcharts, a11y
