### ISSUE TITLE
Column chart shifts columns outside of their corresponding xAxis data labels

### ISSUE THREAD

**Issue by umkoksal** [highcharts/highcharts#16131] opened 2021-08-02 22:14 UTC
#### Expected behaviour
The column chart values are contained within their respective xAxis regions

#### Actual behaviour
We have a chart with 3 series, and when all of them have some data that falls on the same date point in the xAxis, some of the columns are shifted and they actually end up spilling over into other dates, causing confusion as at a first glance the data points appear in wrong dates.

Here is a screenshot of the precise issue, where the data point with August 2nd appears to the right of the xAxis label with August 3rd

![image](https://user-images.githubusercontent.com/61870580/127890100-ee0c4738-04a0-407e-9022-5334e45d1246.png)

#### Live demo with steps to reproduce
Below jsfiddle demonstrates the issue and it contains the chart configuration that we're using
https://jsfiddle.net/6v7d3zy1/

#### Product version
9.1.2

#### Affected browser(s)
Chrome, Chromium Edge

**Comment by raf18seb** [comment] 2021-08-03 13:02
Hi @umkoksal!

You can use the [series.centerInCategory](https://api.highcharts.com/highcharts/plotOptions.column.centerInCategory) option to center columns when some points of the other series are missing, see demo: https://jsfiddle.net/BlackLabel/c1kmhorp/

However, the columns usually are not exactly over the tick mark. Highcharts, when calculating the tick positions, always tries to place them on a rounded date. For example, if the exact point's `x` is `Monday, 2 August 2021 13:11:55`, then the tick is placed on **day** which is `Monday, 3 August 2021 00:00:00`.

In your demo, you have `x: 1627909915917` which is exactly `Monday, 2 August 2021 13:11:55.917` - your column will never be over the tick, unless you specify the exact tick position using e.g. [xAxis.tickPositions](https://api.highcharts.com/highcharts/xAxis.tickPositions)

This is a support question, not a bug, so I am closing the ticket now. If you have any further questions, please use our dedicated support channels. More info: https://www.highcharts.com/blog/support/

**Comment by raf18seb** [comment] 2021-08-03 13:22
Hi @umkoksal! Thanks for creating the ticket and sorry for the confusion!

You can set the `series.pointRange` property to be the same as `xAxis.tickInterval`, see demo: https://jsfiddle.net/BlackLabel/6fds7n4h/

Is this what you wanted to achieve?

**Comment by karolkolodziej** [comment] 2023-11-03 07:33
Closing due to inactivity.

**Closed by karolkolodziej** 2023-11-03 07:33 UTC
Labels: Status: Pending reply, Type: Question
