### ISSUE TITLE
Unexpected chartOptions in exporting

### ISSUE THREAD

**Issue by zhy1stgg** [highcharts/highcharts#9784] opened 2019-01-03 12:52 UTC
#### Expected behaviour

red xAxis labels in exported file as configuration in `exporting.chartOptions`

```javascript
exporting: {
  chartOptions: {
    xAxis: [{
      labels: {
        style: {
          color: 'red'
        }
      }
    }]
  }
}
```
#### Actual behaviour

xAxis label show as data index instead of category.

#### Live demo with steps to reproduce

[https: //jsfiddle.net/04vguh8t/](https: //jsfiddle.net/04vguh8t/)

(click export button to exporting the chart)

#### Product version

Highcharts 7.0 .1

#### Affected browser(s)
all

#### more information

I just want to change the xAxis labels color while exporting, the `exporting.chartOptions` should run out same as `chart.update`
  
**exporting.chartOptions**

```javascript
exporting: {
  chartOptions: {
    xAxis: {
      labels: {
        style: {
          color: 'red'
        }
      }
    }
  }
}
```

**chart.update**

```javascript
chart.update({
  xAxis: {
    labels: {
      style: {
        color: 'red'
      }
    }
  }
})
```

**Comment by KacperMadej** [comment] 2019-01-03 20:18
Hi @zhy1stgg 

Thank you for reporting about the problem.
This issue is a duplicate of #2439

**Workaround:**
Since `chart.update` works and export (due to being based on `merge` function), then use the working function - https://jsfiddle.net/BlackLabel/wy78d29u/

About the demo: `chart.renderer.forExport` used in `load` event will be `true` only for a chart created for export and is internal member of Render, so it's not documented.

**Closed by KacperMadej** 2019-01-03 20:18 UTC
