### ISSUE TITLE
Enabling mouse events don't take effect until you move the mouse

### ISSUE THREAD

**Issue by Blewin** [highcharts/highcharts#14172] opened 2020-09-03 18:55 UTC
#### Expected behaviour
When the user has pointer over a line and "enableMouseTracking" is turned on for that line, it should be hovered and clicks should be attributed to it, without moving the mouse pointer.

#### Actual behaviour
When enableMouseTracking is turned on, user need to move the mouse for the change to take effect.

#### Live demo with steps to reproduce
https://jsfiddle.net/4er1m57x/12/

1. Hover over one of datapoints
2. Click on it.
3. Label should be shown, without user having to move the mouse
4. Further clicks without moving the mouse should be attributed to that series.

#### Product version
Highcharts ` "version": "8.1.0",`

#### Affected browser(s)
Newest Chrome.

The actual fix could be hard, so I'd be grateful for any workaround, or a way to attribute the click to a given series. (click is more important for me than hover)

**Comment by KacperMadej** [comment] 2020-09-04 13:11
Hi @Blewin ,

Thank you for contacting us about the problem.

After the click, there is no event that would trigger the hover, so it is not changing the point state and the tooltip is now showing.

Here's a **workaround** and some info: 
After the chart update, you could call the function responsible for showing the tooltip and changing the points state.
Demo: https://jsfiddle.net/BlackLabel/p2quzgLd/2/
The internal option of series `kdNow` must be used. It is an option the is used for tests and works the same as if the chart was viewed on a mobile / touch device, so changes the asynchronous way of building a kdTree that allows finding points.

I'm not sure if this issue is a bug.

**Comment by Blewin** [comment] 2020-09-09 13:47
Thank you for the workaround!

I'm a little wary of using undocumented flag - how stable this flag is, and what will happen if it gets removed?

I can understand not tagging it as a bug, since this is how most event-based mouse systems work.

**Comment by pawelfus** [comment] 2020-09-14 11:12
> I'm a little wary of using undocumented flag - how stable this flag is, and what will happen if it gets removed?

Do you mean `Undecided` flag? That means we are unsure if we want to change this, as this is natural behaviour of mouse events flow. If in future we will get more similar reports we might change this flag to Feature request (or something similar) and implement this. If we don't get any similar requests in future, ticket will be closed without changes in core (so we won't increase the package size with features that are unlikely to be used).

**Comment by Blewin** [comment] 2020-09-15 14:04
Sorry, I meant the `kdNow` flag that Kacper included in his workaround.

Thank you for the explanation  though, it was helpful too.

**Comment by pawelfus** [comment] 2020-09-15 15:04
That flag is with us since ~v4 and probably will stay for a long time, but as any undocumented feature, may change or disappear.

Using official API, you can call [`point.onMouseOver(event)`](https://api.highcharts.com/class-reference/Highcharts.Point#onMouseOver) and should be fine: https://jsfiddle.net/BlackLabel/aexn2Lr1/1/ - of course, first you need to find point that is closest to the mouse pointer.

**Comment by pawelfus** [comment] 2020-10-01 08:33
Afer internal discussion decided to flag this as `not a bug` - please use API method (`point.onMouseOver`) to achieve this. If you find any issues with the solution provided above, let us know

**Comment by KacperMadej** [comment] 2021-01-22 18:39
Closing as not a bug.

**Closed by KacperMadej** 2021-01-22 18:39 UTC
Labels: Type: Not a bug
