### ISSUE TITLE
piechart drilldown breaks when rerenders

### ISSUE THREAD

**Issue by GrishaDev** [highcharts/highcharts#14784] opened 2020-12-09 13:06 UTC
#### Expected behaviour
piechart with drilldown should work normally

#### Actual behaviour
piechart with drilldown breaks when changing theme or i guees any state in react while drilled down

#### Live demo with steps to reproduce
https://codesandbox.io/s/react-highcharts-theme-bug-12ikj?

#### Product version
Highcharts, piechart drilldown, highcharts-react-official

"highcharts": "^8.2.2",
 "highcharts-react-official": "^3.0.0",

#### Affected browser(s)
Recent chrome

In the demo, everything works fine with any theme.
however if you click on something1 to drilldown, and then change theme, it fully breaks and requires page restart( it resets but back button stays and drilling down again does nothing)

**Comment by pawelfus** [comment] 2020-12-10 12:58
Thank you for reporting this bug @GrishaDev 

Simplified demo:
- https://jsfiddle.net/BlackLabel/nqf3uxpb/

Under the hood, this is a duplicate of #8839 - updating series in a chart when drill down has already happened.

For a workaround in React wrapper, you can set `immutable={true}`, take a look: https://codesandbox.io/s/react-highcharts-theme-bug-forked-c2txt?file=/src/Chart/index.jsx

Closing as duplicate of #8839

**Closed by pawelfus** 2020-12-10 12:58 UTC
