### ISSUE TITLE
Chart Context Menu Cut Off if Div is Shorter than Menu Length

### ISSUE THREAD

**Issue by amber-cd** [highcharts/highcharts#9800] opened 2019-01-04 15:35 UTC
#### Expected behaviour
The full context menu should always be visible on click, either via a scrollbar or via z-indexing solutions.

#### Actual behaviour
The context menu is cut off at the height of the div, making selecting any options below that point extremely difficult.

#### Live demo with steps to reproduce
https://jsfiddle.net/o04wnu3c/

Click on the "Context Menu" in the upper right hand corner.

Obviously, the chart in this demo is very short, but when accessibility options are included, it's pretty easy for the context menu to get cut off.

#### Product version
Highcharts (newest version)

#### Affected browser(s)
Google Chrome

**Comment by sebastianbochan** [comment] 2019-01-07 08:35
Hi @amber-cd,
Thank you for reporting. The bug is duplicate of https://github.com/highcharts/highcharts/issues/7671.

You can fix it by CSS styles (edited version to support HC +7.0):
```
#container, #container > .highcharts-container {
  overflow: visible!important;
}
```

**Closed by sebastianbochan** 2019-01-07 08:35 UTC

**Comment by TorsteinHonsi** [comment] 2019-01-07 08:45
The menu is handled here, where it is inserted into `chart.container`:

https://github.com/highcharts/highcharts/blob/7b45e8bbb11bff1eace2a14868ca1c1a432a5c71/js/modules/exporting.src.js#L1434-L1443

#### Workaround
Instead of inserting the menu in the chart container, move it to the body:

```js
Highcharts.wrap(Highcharts.Chart.prototype, 'contextMenu', function(proceed) {
    proceed.apply(this, Array.prototype.slice.call(arguments, 1));

    // Correct for chart position
    var pos = Highcharts.offset(this.container);
    this.exportContextMenu.style.top = (parseInt(this.exportContextMenu.style.top) + pos.top) + 'px';
    this.exportContextMenu.style.right = (parseInt(this.exportContextMenu.style.right) + pos.left) + 'px';

    // Move it to the body
    Highcharts.doc.body.appendChild(this.exportContextMenu);
});
```

[View it live on jsFiddle](https://jsfiddle.net/highcharts/7dg1fn2j/).

**Comment by sebastianbochan** [comment] 2019-01-07 11:14
@TorsteinHonsi maybe we should consider support it by default? The same problem was with the tooltip.

**Comment by amber-cd** [comment] 2019-01-08 14:33
Unfortunately, the provided workaround results in... comparable problems... in many circumstances in our setup:

![image](https://user-images.githubusercontent.com/30151077/50836902-5d830d00-1328-11e9-8fc7-ad425cc857bd.png)

This may be due to an interaction with Bootstrap styling, or with a React grid setup we use to allow for elements to be dragged and dropped/repositioned on the page; I'm trying to replicate the circumstances in a JSFiddle and will update this thread when I am able to do so.

**Comment by clarghi** [comment] 2020-07-10 14:32
Same problem.
Setting to .highcharts-container overflow: visible !important; doesn't resolve the issue because is into the container and is hidden by below tags.
Using Highcharts.wrap doesn't work, the issue is reproduced by @amber-cd .
I have also tried to set to .highcharts-container position: unset !important;: this seems to resolve the issue, but some features (e.g. the title centered with donut) are broken.

Have you found a way?

Attach an image with the problem.
b.r.
Cristiano Larghi
![image](https://user-images.githubusercontent.com/2656871/87165746-db7ff580-c2ca-11ea-8eef-3ecd77a52259.png)

**Comment by clarghi** [comment] 2020-07-13 07:34
> The menu is handled here, where it is inserted into `chart.container`:
> 
> https://github.com/highcharts/highcharts/blob/7b45e8bbb11bff1eace2a14868ca1c1a432a5c71/js/modules/exporting.src.js#L1434-L1443
> 
> #### Workaround
> Instead of inserting the menu in the chart container, move it to the body:
> 
> ```js
> Highcharts.wrap(Highcharts.Chart.prototype, 'contextMenu', function(proceed) {
>     proceed.apply(this, Array.prototype.slice.call(arguments, 1));
> 
>     // Correct for chart position
>     var pos = Highcharts.offset(this.container);
>     this.exportContextMenu.style.top = (parseInt(this.exportContextMenu.style.top) + pos.top) + 'px';
>     this.exportContextMenu.style.right = (parseInt(this.exportContextMenu.style.right) + pos.left) + 'px';

The right is wrong. I think that we must calculate the right respect of the container position in the screen.
Without horizontal scrolling should be

this.exportContextMenu.style.right=$(window).width() - (parseInt(pos.left)+$(this.container).width()-parseInt(this.exportContextMenu.style.right))+'px';

With horizontal scrolling must be added the scroll measure (I have not tested because I have no X-scroll).

**Comment by pawelfus** [comment] 2020-07-13 11:24
Do you have demo where workaround does not work? This one looks good: https://jsfiddle.net/highcharts/7dg1fn2j/ We will check it. Thanks!

**Comment by clarghi** [comment] 2020-07-13 11:36
> Do you have demo where workaround does not work? This one looks good: https://jsfiddle.net/highcharts/7dg1fn2j/ We will check it. Thanks!

The right seems ok because is total right  aligned ... set e.g. a width and/or a float and the problem appears.

https://jsfiddle.net/2Lrvsz6h/

**Comment by pawelfus** [comment] 2020-07-14 12:11
Good point, thanks! I didn't test the scrolling issue here, but here is simplified demo: https://jsfiddle.net/BlackLabel/0ek1ovt8/

Updated plugin:
```js
Highcharts.wrap(Highcharts.Chart.prototype, 'contextMenu', function(proceed) {
  proceed.apply(this, Array.prototype.slice.call(arguments, 1));

  // Correct for chart position
  var pos = Highcharts.offset(this.container);
	var defaultPadding = 5 * 2; // default from menuStyle option: https://api.highcharts.com/highcharts/navigation.menuStyle
  this.exportContextMenu.style.top = (parseInt(this.exportContextMenu.style.top) + pos.top) + 'px';
  this.exportContextMenu.style.left = (pos.left + this.chartWidth - this.exportMenuWidth - parseInt(this.exportContextMenu.style.padding) - defaultPadding) + 'px';
  this.exportContextMenu.style.width = this.exportMenuWidth + 'px';

  // Move it to the body
  Highcharts.doc.body.appendChild(this.exportContextMenu);
});
```

**Comment by clarghi** [comment] 2020-07-14 12:30
> Good point, thanks! I didn't test the scrolling issue here, but here is simplified demo: https://jsfiddle.net/BlackLabel/0ek1ovt8/
> 
> Updated plugin:
> 
> ```js
> Highcharts.wrap(Highcharts.Chart.prototype, 'contextMenu', function(proceed) {
>   proceed.apply(this, Array.prototype.slice.call(arguments, 1));
> 
>   // Correct for chart position
>   var pos = Highcharts.offset(this.container);
> 	var defaultPadding = 5 * 2; // default from menuStyle option: https://api.highcharts.com/highcharts/navigation.menuStyle
>   this.exportContextMenu.style.top = (parseInt(this.exportContextMenu.style.top) + pos.top) + 'px';
>   this.exportContextMenu.style.left = (pos.left + this.chartWidth - this.exportMenuWidth - parseInt(this.exportContextMenu.style.padding) - defaultPadding) + 'px';
>   this.exportContextMenu.style.width = this.exportMenuWidth + 'px';
> 
>   // Move it to the body
>   Highcharts.doc.body.appendChild(this.exportContextMenu);
> });
> ```

Seems ok in the example but in my context doesn't work, the left is "too left". I use bootstrap 3.7 and I can't reproduce the issue in the example:

![image](https://user-images.githubusercontent.com/2656871/87425745-76841280-c5de-11ea-8234-59208532ef05.png)


My solution posted above works in my context with bootstrap, but applied to your solution the top is wrong and I don't know why :-/

https://jsfiddle.net/x24j65bt/

**Comment by sebastianbochan** [comment] 2020-07-15 07:23
Hi @clarghi,
It looks like the general problem with exporting icon position.

The demo https://jsfiddle.net/BlackLabel/q9ethzwg/ can be fixed by setting the 0 value for the top param.

Could you try to apply all your css styles of charts / containers of charts (from bootstrap too) in jsfiddle? Maybe it will be possible to reproduce the problem.

**Comment by raf18seb** [comment] 2022-06-02 13:31
Hi @TjeneBen, could you provide a live demo showing your issuse? Maybe I'll be able to find a workaround for that.

**Comment by TjeneBen** [comment] 2022-06-02 21:38
@raf18seb thank you for the quick response,
https://stackblitz.com/edit/react-qy9gho?file=src/App.js

I couldnt get it work on stackblitz, but I was able to track down the issue.
As soon as we append the dropdown to the body, in the accessibility module, accessibility.src.js line 289 failing when its checking if the element has aria-hidden attribute, but since the nodelist contains #text which in not an html element the code fails.

**Comment by optyler** [comment] 2024-02-14 10:00
> [clarghi](/clarghi)

This solution works well with mui, thanks
