### ISSUE TITLE
Scrollbar is not responding in mobile browser from 7.2.1 versions 

### ISSUE THREAD

**Issue by kalandher** [highcharts/highcharts#14942] opened 2021-01-15 08:56 UTC
it works with older version but not with the latest versions from 7.2.1. Try to open below links on mobile browser. Scrollbar is not responding can only click on arrows on left and right sides of scroll bar.

below link is older version - 6.1.1
https://jsfiddle.net/wnk1ba2r/3/show

#### Expected behaviour
Scroll bar should work as its in below link
https://jsfiddle.net/wnk1ba2r/3/show

#### Actual behaviour
Scroll bar is not responding when try to drag, only arrows are working. on click of arrows left or right scroll bar moves little and content aswell  

below link is newer version - 7.2.1
https://jsfiddle.net/wnk1ba2r/4/show

below link is current version
https://jsfiddle.net/wnk1ba2r/5/show

#### Live demo with steps to reproduce
https://jsfiddle.net/wnk1ba2r/5/show

#### Product version
curretly im using 7.2.1 but its not working in latest either

#### Affected browser(s)
Chrome

**Comment by khlieng** [comment] 2021-01-15 10:22
Sounds like a duplicate of #14193 which was fixed by #14688, so this should be fixed in the next release :)

**Closed by khlieng** 2021-01-15 10:22 UTC
Labels: Type: Duplicate

**Comment by kalandher** [comment] 2021-01-15 11:25
> Sounds like a duplicate of #14193 which was fixed by #14688, so this should be fixed in the next release :)

Thank you @khlieng, may i know when is the next release?

**Comment by khlieng** [comment] 2021-01-15 11:31
Should be in the near future.
