### ISSUE TITLE
Range selector overlap export button + don't wrap if too large

### ISSUE THREAD

**Issue by Kurairaito** [highcharts/highcharts#7328] opened 2017-10-27 18:55 UTC
#### Expected behavior
When using range selector, if the width to display it is too small, display it on 2 or more rows.
at least be able to use all the button in the range selector + the export button.

#### Actual behavior
Range selector is 1 line only and if it is too large, it overlap the export button instead of splitting it in two rows.

#### Live demo with steps to reproduce
http://jsfiddle.net/56az0axj/
Open it in full screen and resize the windows. When space becomes low, date range selection go on a new row. Continue to reduce the size and you will not be able to use the export button nor the last buttons in range selection row (out of window) .

#### Affected browser(s)
Chrome and Firefox at least have the bug.
Note the issue is mainly visible on mobile browsing in a responsive website.

best regards,
Kurairaito.

**Comment by pawelfus** [comment] 2017-10-30 10:12
Thank you for reporting the issue. 

FYI @sebastianbochan - we need improvements in responsiveness for range selector

**Comment by BuyOwnEx** [comment] 2019-08-16 19:27
Can it be fixed by css at mobile divices?

**Comment by sebastianbochan** [comment] 2019-08-19 12:50
Hi @BuyOwnEx,
The problem is really complex and related with a few other functionalities. 

I prepared your a really simple and limited solution, based on moving buttons to the next line.

Demo:
- http://jsfiddle.net/BlackLabel/fonpt1wz/

**Comment by khlieng** [comment] 2021-01-12 13:51
Fixed on master (#14717).

**Closed by khlieng** 2021-01-12 13:51 UTC
Labels: Type: Enhancement
