### ISSUE TITLE
gradient as chart.backgroundColor doesn't work in the new window

### ISSUE THREAD

**Issue by mateuszkornecki** [highcharts/highcharts#13881] opened 2020-07-10 12:37 UTC
#### Expected behaviour
Background color should be the same regardless of the window location. 

#### Actual behaviour
Gradient is not applied. It seems that there is a problem with the fill url in the new window (`<rect fill="url(...)...>`).

_Note:_
I wasn't able to reproduce the issue with the vanillaJS.

#### Live demo with steps to reproduce
Steps: 
1/ Click on the "New window" button.
https://stackblitz.com/edit/angular-ivy-hft1ug?file=src%2Fapp%2Ftheme.ts

#### Product version
8.1.2

#### Affected browser(s)
All

**Comment by pawelfus** [comment] 2020-11-17 10:01
Additional demo: https://stackblitz.com/edit/angular-ivy-sz7epr

**Comment by pawelfus** [comment] 2020-11-17 10:58
Closing as duplicate of #5244

Workaround is the same as in #5244 but I'm unable to call `afterHistoryPush()` in the new window, only in the original app.. https://stackblitz.com/edit/angular-ivy-19lcse - some CDK expert needed, I guess.

**Closed by pawelfus** 2020-11-17 10:58 UTC
Labels: Type: Bug
