### ISSUE TITLE
 The oridinal axis is ignored, when navigator disabled.

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#6275] opened 2017-01-20 12:13 UTC
#### Actual behaviour
The oridinal axis is ignored, when navigator disabled.

#### Live demo with steps to reproduce
Demo:
- http://jsfiddle.net/d1qbxe8e/

#### Affected browser(s)
All

**Comment by KacperMadej** [comment] 2017-01-23 11:57
Duplicate of #1183

**Closed by KacperMadej** 2017-01-23 11:57 UTC
Labels: Bug
