### ISSUE TITLE
Highcharts becomes distorted with same input fed multiple times

### ISSUE THREAD

**Issue by AbckSinha** [highcharts/highcharts#10831] opened 2019-05-28 05:56 UTC
#### Expected behaviour
Highcharts should not be distorted since same data is given as input
#### Actual behaviour
Highcharts becomes distorted when same data is given as input

#### Live demo with steps to reproduce

Steps to reproduce : 
1. make an ajax call to get the data and give it as a input to Highcharts
2. Repeat above step a few times.
3. The highcharts becomes distorted.

#### Product version
 Highcharts V7.0.3 

#### Affected browser(s)
Google Chrome

**Comment by sebastianbochan** [comment] 2019-05-28 08:43
Hi @AbckSinha,
Thank you for reporting about the problem. At this moment I am not able to reproduce the issue due to lack of informations.

Could you update our simple demo: https://www.highcharts.com/demo/line-basic with your AJAX request and chart's option. 

It will allow us to debug the reason of the problem.

**Comment by AbckSinha** [comment] 2019-06-10 03:45
Hi,
This looks similar to this issue .
https://github.com/highcharts/highcharts/issues/9074.

Can you help in solving this issue.
Note:- The same jsfiddle can be used for producing this issue.

Thanks,
AbckSinha

**Comment by pawelfus** [comment] 2019-06-12 08:12
Hi @AbckSinha 

The issues you mentioned is about browser limits for inactive tab. Do you encounter this issue **only** with inactive tabs too? If that's not the case, then we really need a live demo to help you. Thanks!

**Comment by AbckSinha** [comment] 2019-06-12 09:20
Hi @pawelfus ,

Yes, I have encountered this issue with inactive tab only. For others scenarios, it works fine.
Please suggest how to fix the issue.

Thanks,
AbckSinha

**Comment by pawelfus** [comment] 2019-06-12 10:54
I suggest to contact browser developers to change/fix that. Your interval does not provide data to Highcharts with regular timestamps thus displayed is what you provide. 

You still haven't posted a demo, so I can not suggest anything else - I don't know what you have in your app. 

Closing ticket as duplicate of #9074. In case of further questions, please contact with our support: https://www.highcharts.com/blog/support/

**Closed by pawelfus** 2019-06-12 10:54 UTC
Labels: Type: Duplicate
