### ISSUE TITLE
bad redraw for 3d pie

### ISSUE THREAD

**Issue by coelhoricardo** [highcharts/highcharts#7325] opened 2017-10-27 11:31 UTC
#### Expected behaviour
After many "setData/redraw", a 3d pie should always have a good display.

#### Actual behaviour
The 3d pie is wrong since the second "setData/redraw".

#### Live demo with steps to reproduce

http://jsfiddle.net/50jpg8t2/

#### Affected browser(s)
Tested on Chrome 62, Firefox 56, IE 11, Edge 16

Thanks in advance

**Comment by pawelfus** [comment] 2017-10-30 10:21
Thank you for reporting the bug @coelhoricardo 

It's caused by `updatePoints` param in `setData(redraw, animation, updatePoints)`. That param adds an animation when number of points is exactly the same: http://jsfiddle.net/50jpg8t2/1/

It used to work in v5, broken since v6.0.0: http://jsfiddle.net/50jpg8t2/2/

*Internal note:*
Issue-by-commit leads to c4fef24

**Comment by ChiggerChug** [comment] 2017-11-22 13:41
Hi guys, any idea when this might be pushed to the bower release version? I've just updated to 6.0.3 and I'm experiencing this issue also.

**Comment by pawelfus** [comment] 2017-11-22 14:07
Hi @ChiggerChug, this bug is open :)

**Comment by TorsteinHonsi** [comment] 2017-12-06 07:45
Fixed in 29648268b359a2754688e72da06ca734e2b7e8ee.

Demo with the fix applied: http://jsfiddle.net/highcharts/50jpg8t2/3/

**Closed by TorsteinHonsi** 2017-12-06 07:45 UTC
Labels: Regression
