### ISSUE TITLE
The chart.update function does not handle chart.inverted appropriately

### ISSUE THREAD

**Issue by aazhari** [highcharts/highcharts#5987] opened 2016-11-16 21:49 UTC
#### Expected behaviour

After creating a new chart:
```
  var chart = Highcharts.chart('container', {
    series: [{
      name: 'Tokyo',
      data: [7.0, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6]
    },
    ....
}
```
![image](https://cloud.githubusercontent.com/assets/7737331/20367154/f1380a2e-ac13-11e6-8700-9f2bc6aec076.png)

After updating the inverted property using chart.update:
```
chart.update({
    chart : {
        inverted: true
    }
})

```
The chart should look how it does when initially drawing it with the property chart.axisInverted set as true:
![image](https://cloud.githubusercontent.com/assets/7737331/20367206/281af682-ac14-11e6-8bb8-d625936cbb8f.png)

#### Actual behaviour

After calling:
```
chart.update({
    chart : {
        inverted: true
    }
})
```
The axis are not inverted properly:
![image](https://cloud.githubusercontent.com/assets/7737331/20367177/00a6d01c-ac14-11e6-8223-e4594ad0a29a.png)

#### Live demo with steps to reproduce
[Link to jsfiddle example](https://jsfiddle.net/86g8fco4/)

#### Affected browser(s)
All browsers

**Comment by jon-a-nygaard** [comment] 2016-11-17 06:57
Thanks for reporting, we will try to fix this as soon as possible.

**Comment by jon-a-nygaard** [comment] 2016-11-17 09:28
This issue is a duplicate of #5938, which is fixed and will be released in the next maintenance.

**Closed by jon-a-nygaard** 2016-11-17 09:28 UTC
Labels: Bug
