### ISSUE TITLE
0 value data points are not getting restored when y axis type changed from logarithmic to linear

### ISSUE THREAD

**Issue by crohit7** [highcharts/highcharts#16879] opened 2022-01-13 11:38 UTC
#### Expected behaviour
0 value data points should get restored as per the linear scale

#### Actual behaviour
0 value data points are not getting restored. points remain broken

#### Live demo with steps to reproduce
http://jsfiddle.net/hstfm5o4/1/

In above demo the by default scale is linear.
When axis type is changed to logarithmic then 0 or sub zero value points got broken.
After changing axis type from logarithmic to linear the broken points are not restored.

#### Product version
Created with Highcharts 9.3.2

**Comment by raf18seb** [comment] 2022-01-17 08:52
Hi @crohit7, thank you for reporting!

I think this is a duplicate of https://github.com/highcharts/highcharts/issues/16785

**Closed by raf18seb** 2022-01-17 08:52 UTC
