### ISSUE TITLE
SolidGauge y axis labels misplaced/missing for min != 0 and max<100

### ISSUE THREAD

**Issue by BookSwapSteve** [highcharts/highcharts#5525] opened 2016-07-23 01:10 UTC
#### Expected behaviour
Expect y axis labels to be at the ends of the solid gauge curve showing max/min value as per samples (http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/gauge-solid/)

#### Actual behaviour
using: yAxis: {min: 5, max: 25}
no min Y axis label shown.
max y axis label value is 20 and is part way across the y axis curve.
setting a value to 15 for the data results in the correct display of the value so it's only the y-axis display that is off.

using: yAxis: {min: -5, max: 30}
min y axis value is 0 and shown part way across the y axis curve.
max y axis label value is 25 and is part way across the y axis curve.

using: yAxis: {min: -5, max: 40}
min y axis value is 0 and shown part way across the y axis curve.
max y axis label value is not shown.

using: yAxis: {min: 0 , max: 110}
min y axis value shown as expected.
max y axis value is 100 shown part way across the y axis.

#### Live demo with steps to reproduce
Modify sample to use yAxis: {min: 5, max: 25} for the speed dial gives: http://jsfiddle.net/ktppagqw/

modify min/max as per above to see the other issues.

#### Affected browser(s)
Chrome/FireFox/IE/(untested on others)

**Comment by jon-a-nygaard** [comment] 2016-07-25 06:28
@BookSwapSteve  What you can do is to set your own custom yAxis.tickPositioner which returns two tick positions, the min and max value of the yAxis. I believe what you are looking for is a solution like in [this example](http://jsfiddle.net/3w9gtcxy/2/)

**Comment by jon-a-nygaard** [comment] 2016-07-25 06:29
Duplicate of #5505

**Closed by jon-a-nygaard** 2016-07-25 06:28 UTC

**Comment by TorsteinHonsi** [comment] 2016-07-25 07:51
@BookSwapSteve It seems setting `tickAmount` to 2 is an easy way of achieving the same. We'll change that in the demo to encourage its use. http://jsfiddle.net/highcharts/ktppagqw/3/
