### ISSUE TITLE
Window resizing increases chart size indefinitely

### ISSUE THREAD

**Issue by inad9300** [highcharts/highcharts#9620] opened 2018-12-07 09:59 UTC
#### Expected behaviour
Not sure.

#### Actual behaviour
When the window size increases, the chart size increases. When the window size decreases, the chart size keeps increasing!

#### Live demo with steps to reproduce
https://codepen.io/TorsteinHonsi/pen/KMNbRN
Move the middle separator up and down and see the chart increase and increase.

#### Product version
6.2.0

#### Affected browser(s)
Chrome and Firefox. Seems browser-independent.

**Comment by pawelfus** [comment] 2018-12-07 10:47
Hi @inad9300 

Thank you for reporting the issue. You are right it's broken, but only in this demo. When you use current release CSS, it works fine: https://codepen.io/anon/pen/jXNEgG

It's actually a duplicate of #7494

@TorsteinHonsi - could you update your demo here: https://www.highcharts.com/docs/chart-design-and-style/style-by-css ? In this line: `To experiment with this live, see our example with SCSS parsing on Codepen.`

**Comment by TorsteinHonsi** [comment] 2018-12-10 11:12
Thanks, it's updated now.

**Closed by TorsteinHonsi** 2018-12-10 11:12 UTC
Labels: Docs

**Comment by inad9300** [comment] 2018-12-10 11:45
Wonderful work, guys. Your responsiveness never disappoints!
