### ISSUE TITLE
chart synchronisation showing console error while using highstock.js

### ISSUE THREAD

**Issue by hakkim** [highcharts/highcharts#10775] opened 2019-05-21 07:16 UTC
**Chart synchronisation showing console error while using highstock.js**
If I change highchart.js to highstock.js while hovering the chart it shows a console error

#### Expected behaviour
The chart must be working fine without any error

#### Actual behaviour
Showing console error while hovering the chart

#### Live demo with steps to reproduce
https://codepen.io/abdulhakkim/pen/EzwrEd

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment] 2019-05-21 08:34
Hi @hakkim,
Thank you for reporting about the problem. When I run your demo, I was not able to reproduce your issue.

![sync](https://user-images.githubusercontent.com/2115686/58080658-e30aa980-7bb3-11e9-976b-7e707c537420.gif)

MacOSX: 10.12.4
Chrome: 74.0.3729.157 

Could you share your browser / OS details? It will be helpful for the further debugging.

**Comment by hakkim** [comment] 2019-05-21 08:55
It was fixed,
**This error occurs because tooltip.refresh() method in Highstock needs to get an array of points, while Highcharts needs just a single point.**

```
Highcharts.Point.prototype.highlight = function (event) {
    event = this.series.chart.pointer.normalize(event);
    this.onMouseOver(); // Show the hover marker
    this.series.chart.tooltip.refresh([this]); // Show the tooltip
    this.series.chart.xAxis[0].drawCrosshair(event, this); // Show the crosshair
};
```

**Comment by sebastianbochan** [comment] 2019-05-21 08:57
Thank you for feedback. Im closing the ticket.

**Closed by sebastianbochan** 2019-05-21 08:57 UTC
Labels: Status: Can't reproduce, Status: Pending reply
