### ISSUE TITLE
Two yAxis, centerInCategory, point misaligned

### ISSUE THREAD

**Issue by K009** [highcharts/highcharts#19893] opened 2023-10-06 09:04 UTC
#### Expected behaviour
Points shouldn't overlap

#### Actual behaviour
Points overlap

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/L3q0z8kf/
![image](https://github.com/highcharts/highcharts/assets/18682376/def12503-3262-42fe-b319-8ce402eccf5a)

**Comment by karolkolodziej** [comment] 2023-10-09 08:04
Simplified demo: https://jsfiddle.net/BlackLabel/mrjzwb6n/

**Comment by TorsteinHonsi** [comment] 2023-10-09 11:43
Duplicate of #17764

Demo with fix applied: https://jsfiddle.net/highcharts/oLjh5b8u/

**Closed by TorsteinHonsi** 2023-10-09 11:43 UTC
Labels: Type: Bug, Product: Highcharts, Type: Duplicate
