### ISSUE TITLE
Markers on line charts move up when leaving hovering

### ISSUE THREAD

**Issue by tqdo** [highcharts/highcharts#16563] opened 2021-10-29 21:06 UTC
#### Expected behaviour
The marker does not move up when leaving hovering

#### Actual behaviour
The marker moves up when leaving hovering (I am using a plug-in to use Font Awesome as markers.

#### Live demo with steps to reproduce
https://jsfiddle.net/vf0g4u5k/12/

#### Product version
9.1.2

#### Affected browser(s)
Chrome

**Comment by raf18seb** [comment] 2021-11-02 16:43
Hi @tqdo,

You edited the code in the plugin (missing `translate` attributes in the `attr()` method).
It's working fine with an official plugin code: https://jsfiddle.net/BlackLabel/n0wb4p1j/

GitHub is our bugs/features tracker only, so, if you have any further questions related to this plugin (it's not core code), please contact our support on our other support channels.
More info: https://www.highcharts.com/blog/support/

Closing as not a bug.

**Closed by raf18seb** 2021-11-02 16:43 UTC
