### ISSUE TITLE
Boost mode does not hide markers when a series is disabled

### ISSUE THREAD

**Issue by benzmarkus** [highcharts/highcharts#7885] opened 2018-02-19 15:12 UTC
#### Expected behaviour
Markers get hidden when a series is disabled in the legend.

#### Actual behaviour
Markers still visible but the chart is disabled.

#### Live demo with steps to reproduce
template: https://jsfiddle.net/jyj4xg4y/2/

This is the millions points example from highcharts extended by 2 additional series. In a realy zoom the markers are visible on the series and then we disable 1 series by another.

1) zoom into the chart so the markers are visible on the lines.
2) disable one series by clicking on the legend (series should have markers visible so check the zoom)
3) markers stays but the line chart is hidden this behaviour is not reproduceable with boost mode disabled.

#### Product version
Highcharts 6.0.7

#### Affected browser(s)
Firefox, Chrome could be in IE too

**Comment by KacperMadej** [comment] 2018-02-20 14:28
Hi @benzmarkus 

I have tried to recreate the problem. I fully zoomed in, but markers were not visible in your demo.
You can test markers better with them enabled - demo: https://jsfiddle.net/jyj4xg4y/15/
With the above demo I can see the markers and they are well hidden on legend item click, so I'm not able to recreate the problem.

**Comment by benzmarkus** [comment] 2018-02-20 14:44
https://pasteboard.co/H8wH2pH.png

Here you can see the problem. My chrome browser is up2date.

**Comment by KacperMadej** [comment] 2018-02-21 12:16
@benzmarkus 
I was able to recreate the problem. Thank you for reporting about this.

As a workaround you could disable markers by forcing the boost to work at any zoom level - e.g. by setting [`seriesThreshold`](https://api.highcharts.com/highcharts/boost.seriesThreshold). Demo: https://jsfiddle.net/BlackLabel/jyj4xg4y/22/

@cvasseng fyi: boost module issue

**Comment by cvasseng** [comment] 2018-02-21 12:33
@KacperMadej I'm unable to reproduce this as a boost issue - I can only see the issue when the chart is zoomed into svg mode. Also, when it happens the makers are SVG elements, so it doesn't seem like it's a boost thing. How did you go about reproducing it? Just want to make sure before I say for certain that it's not related to boost.

**Comment by pawelfus** [comment] 2018-02-21 13:08
@cvasseng - you are right, something is wrong when you zoom into the SVG mode, compare:

- with boost: https://jsfiddle.net/BlackLabel/jyj4xg4y/30/
- without boost: https://jsfiddle.net/BlackLabel/jyj4xg4y/31/

So it looks like a boost issue.

**Comment by cvasseng** [comment] 2018-02-21 13:38
I think the problem is related to the shared marker group when boosting on chart level - which will happen in this demo as all series can be boosted. Not sure what the best approach of fixing it is yet.

@benzmarkus the workaround is to set `boost.allowForce = false`, and make sure to always boost on series level (e.g. make sure `boost.seriesThreshold` is set to a higher number the the number of series in your chart.  Demo: https://jsfiddle.net/fqtwgdkb/

**Comment by benzmarkus** [comment] 2018-02-21 13:48
Thx i will try this asap.

**Comment by benzmarkus** [comment] 2018-10-22 13:48
Version 6.2 is out now but the bug is still open. When is the bug going to be fixed?

**Comment by KacperMadej** [comment] 2018-10-22 16:13
@cvasseng ☝️

**Comment by pawelfus** [comment] 2019-04-02 11:53
It looks we received another report about the same issue. Let me close this issue as duplicate and let's follow #10013 from now on.

**Closed by pawelfus** 2019-04-02 11:53 UTC
Labels: Type: Bug
