### ISSUE TITLE
Axis.toPixels returning abrupt value on live Highstock chart

### ISSUE THREAD

**Issue by HaiderAtPlero** [highcharts/highcharts#4702] opened 2015-10-30 08:08 UTC
We have a live Highstock chart and we also show some lines of our own using the chart renderer.
We keep xAxis dates and yAxis prices of two points for each line to redraw them later.
On each redraw event of chart we redraw the lines by calling Axis.toPixels to get their new locations.
Everything works good.

Except that sometimes the Axis.toPixels returns an abrupt value. And on next redraw it is good again. So there is a jerk in movement of line.

Annotations library by BlackLabel also has this issue:
http://blacklabel.github.io/annotations/

I guess the key here is that our chart is live?

**Comment by pawelfus** [comment] 2015-10-30 09:48
Could you setup jsfiddle with the issue? Some dummy data should be enough for updating. It looks very similar to #2406 issue.

**Comment by HaiderAtPlero** [comment] 2015-11-10 14:33
@pawelfus 
JSFiddle: http://jsfiddle.net/uv4ne1uu/5/
Video: https://www.dropbox.com/s/0m7ws4fo17u0q24/issue-highstock-Axis.toPixels.mov
If you see the video, you can see a small jerk at 00:15, a big jerk at 00:20, and a very big one at 00:24.

**Comment by highslide-software** [comment] 2015-11-11 13:58
Is it because of the default ordinal X axis? When I set ordinal to false it looks good: http://jsfiddle.net/highcharts/uv4ne1uu/6/

**Comment by HaiderAtPlero** [comment] 2015-11-12 05:03
@highslide-software Definitely seems to be the case.

**Comment by highslide-software** [comment] 2015-11-12 09:21
Okay, then I'm closing this as not a bug. Please shout out if you disagree.

**Comment by HaiderAtPlero** [comment] 2015-11-12 09:45
I disagree. Setting ordinal to false is just a workaround. People used to looking at stock charts are not used to look at empty spaces for holidays. So this should work good even if ordinal is true.

**Comment by highslide-software** [comment] 2015-11-12 10:18
The issue case claims that xAxis.toPixels returns the wrong value, but is that really the case? Or is the problem that the lines should also reflect the breaks in the axis?

**Comment by HaiderAtPlero** [comment] 2015-11-12 10:35
Axis.toPixels is returning wrong value. At least it is not conforming to its inverse function Axis.toValue.

xAxis values stored for two points per line never contain any date for a holiday. How? Because if you look inside the 'finishTrendLineDrawing' function on jsFiddle, you will see that those values are computed using Axis.toValue function.

If Axis.toValue is reflecting the breaks in axis, so should Axis.toPixels.

**Comment by highslide-software** [comment] 2015-11-13 13:16
Okay, I tried to break your explanation down to a demo as simple as possible. In [this jsFiddle], I compute back and forth inside an ordinal break, but the result is as expected. Can you change that simple test into something that breaks?

**Comment by jon-a-nygaard** [comment] 2016-08-02 12:50
Closing this since it is considered not a bug, and it is pending a reply. Should anyone have further information on the issue, please give us a comment.

**Closed by jon-a-nygaard** 2016-08-02 12:50 UTC
Labels: Not a bug, Pending reply

**Comment by nagin** [comment] 2018-07-12 12:38
Axis.toPixels breaks if X cordinate is outside extremes

**Comment by KacperMadej** [comment] 2018-07-13 08:49
Hi @nagin 

The questions still remains: "Can you change that simple test into something that breaks?", so please provide a live demo or another way for us to debug the problem and test possible solutions.

**Comment by nagin** [comment] 2018-07-14 05:53
if You see JSFiddle given by @HaiderAtPlero .
One of the Initial x coordinates or both coordinates  (Date coordinates) when line is initially drawn goes out of X axis extremes, then slope of line drawn changes. This is because coordinate to pixels conversion (here extrapolation is done) is not correct.

**Comment by nagin** [comment] 2018-07-15 06:44
Another example from Highstock demo itself.
In this demo https://www.highcharts.com/stock/demo/advanced-stock-chart
if you draw line near right end of chart and then move chart toward right. then you will notice change of slope and point of intersection with any one of candle.  This starts happening  as soon as one of endpoint of line goes out of x axis extreme.

**Comment by nagin** [comment] 2018-07-16 10:44
#2406 is not fixed even after about 5 years. Does this mean Highcharts team does not consider it as important one?

**Comment by pawelfus** [comment] 2018-07-16 10:49
No, now the issue will be considered with a higher priority - otherwise, annotations in Highstock will cause visual errors (like wrong slope in a trendline).
