### ISSUE TITLE
Gantt Chart - After enabling "scrollablePlotArea" z-index of tooltip and plotlines are not working as expected

### ISSUE THREAD

**Issue by rajasekar-pb** [highcharts/highcharts#18535] opened 2023-02-20 13:05 UTC
#### Expected behaviour
Plot line should come above the timeline ...

#### Actual behaviour
After enabling scroll feature, plot line hides behind the floating timeline...

#### Live demo with steps to reproduce
https://jsfiddle.net/jxnyrsfu/

#### Product version
highcharts: 10.2.1
highcharts-angular: 3.0.0

#### Affected browser(s)
Google Chrome
Version 110.0.5481.104 (Official Build) (64-bit)

Firefox
Version 109.0.1 (64-bit)

**Comment by bm64** [comment] 2023-02-20 16:15
Hello @rajasekar-pb 

Unfortunately not much can be done about that, because in case of SVG elements, "z-index" is based on the order of the elements within the same svg group. In this case plot lines group and scrollable plot area overlay are two completely different groups and thus zIndex property doesn't have any effect between those two. Same rule applies to the tooltip. 

There is a related feature request, so I'm closing this one as a duplicate of #15398

**Closed by bm64** 2023-02-20 16:15 UTC
