### ISSUE TITLE
Heatmap PDF offline-export is broken since v9

### ISSUE THREAD

**Issue by DAdq26** [highcharts/highcharts#19041] opened 2023-05-24 08:27 UTC
Hi team,

#### Expected behaviour
Well formed Highcharts treemap with heatmap when exporting in pdf format

#### Actual behaviour
Values not well positionned in pdf squares 
Heatmap legend with black background (expected gradient)

#### Live demo with steps to reproduce
Click export pdf on export button
Latest v11.0.1
https://jsfiddle.net/uqbf8zjx/

Also in v9.0.0
https://jsfiddle.net/2w3dsoyt/

Good in v8.2.2
https://jsfiddle.net/5umefzph/

#### Product version
v10.2.1

#### Affected browser(s)
All

**Comment by DAdq26** [comment] 2023-05-25 06:07
Any news  dear dev ?

**Comment by bm64** [comment] 2023-05-29 11:03
Hello @DAdq26 and thanks for reporting the issue.

The issue is caused by bug in `svg2pdf` lib, which is used by offline exporting module. Here is a related ticket: https://github.com/yWorks/svg2pdf.js/issues/192

When it comes to workaround, you can disable shadows for data labels to make them export correctly: https://jsfiddle.net/BlackLabel/4fdy6m7n/
Unfortunately I can't provide any workaround for incorrectly rendered legend yet.

Related ticket: https://github.com/highcharts/highcharts/issues/17170

**Comment by DAdq26** [comment] 2023-05-30 06:45
Hi and many thanks for your reply,

I understand your answer and the dependency with svg2pdf.
Your workaround for heatmap values is ok.

The thing i can't explain is why so much changes between 8.22 and current verrsion for offline pdf export ? Because in 8.22 job is ok

Best

**Comment by TorsteinHonsi** [comment] 2023-05-30 10:43
@bm64 

Can you make that workaround into a fix in the offline-exporting module? The appropriate fix would probably be to just remove all `.highcharts-text-outline` elements.

There's a [code block where we do hacks and workarounds on the SVG](https://github.com/highcharts/highcharts/blob/46577eab1a0e28043fe2060ca1e0ed55e648e84e/ts/Extensions/OfflineExporting/OfflineExporting.ts#L346-L396) for the PDF export, it would probably fit in there.

**Comment by bm64** [comment] 2023-05-30 11:22
@TorsteinHonsi sure, I'm on it 👍

**Comment by TorsteinHonsi** [comment] 2023-06-12 06:47
Duplicate of #17170

**Closed by TorsteinHonsi** 2023-06-12 06:47 UTC
Labels: Type: Bug, Type: Good for beginners
