### ISSUE TITLE
Overlapped links in organisation Highcharts

### ISSUE THREAD

**Issue by RachanaRAcharya** [highcharts/highcharts#13356] opened 2020-04-22 13:34 UTC
Hi,
I am working on organisation high charts and i see 2 issues which i am unable to solve.

1. can not set height of each node
2.  links  are overlapped due to which relationship between nodes are not identifiable.

![image](https://user-images.githubusercontent.com/46247073/79988295-193f6000-84cc-11ea-870f-01021dd930f3.png)

In the above image.. links between['Canidae', 'Panthera pardus'] are not identifiable clearly and also due to the overaping links , it looks like all nodes in level 3 is linked with all nodes in level 4. How can this be avoided ?

jsfiddle : https://codepen.io/Rachanaacharya/pen/pojNmrZ

**Comment by sebastianbochan** [comment] 2020-04-23 07:38
Hi @RachanaRAcharya,
Thank you for suggestions. At this moment you can use only offset and modeWidth params in horizontal layout.

I would consider your ideas as a feature request, which should be possible to apply on "node" level (not only series). Moreover it should work in both layouts (vertical and horizontal).

**Comment by RachanaRAcharya** [comment] 2020-04-23 11:25
Thanks. What about the overlapping links ?  I know there is property allowOverlap :true/false but those are for datalabels only not for links right so is there a way to avoid this overlapping of links so as to clearly identify which child node belongs to which parent

**Comment by sebastianbochan** [comment] 2020-04-24 11:48
At this moment we do not have any-collistion algorithms for paths. I think that it should be a part of the feature request, commented above.

**Comment by pawelfus** [comment] 2020-05-04 12:14
It looks like a duplicate of #11009 - should this be closed @sebastianbochan ?

**Comment by sebastianbochan** [comment] 2020-05-04 13:38
Correct. 

Closing the ticket as duplicate of #11009

**Closed by sebastianbochan** 2020-05-04 13:38 UTC
Labels: Type: Feature Request
