### ISSUE TITLE
DrilldownLevels property is missing or has wrong number of level

### ISSUE THREAD

**Issue by kjm** [highcharts/highcharts#3862] opened 2015-02-19 20:44 UTC
On first chart load there's no drilldownLevels property on chart object.
After first press drill down, property is added with drilldownLevels.levelNumber = 0, but level should be equal 1.
After drill up to level 0, drilldownLevels gets empty array.
This causes that levelNumber not exist at level 0.

Here's example based on highcharts.com demo
http://jsfiddle.net/0Lyuazr8/

Tested on version 4.1.1
Browsers:
FF 35.0.1 Ubuntu 14.10
Chrome 40.0.2214.111 (64-bit) Ubuntu 14.10

Best regards
Konrad Mazurkiewicz

**Comment by KacperMadej** [comment] 2019-02-04 22:52
`levelNumber` is not a part of API. It's internal / private.
Closing as not a bug

**Closed by KacperMadej** 2019-02-04 22:52 UTC
