### ISSUE TITLE
Datalabels break on error bar after zooming

### ISSUE THREAD

**Issue by smithk58** [highcharts/highcharts#4827] opened 2015-12-10 18:28 UTC
Hi,

After you zoom on an error bar the top datalabel of the errorbar is moved down next to the bottom datalabel. It's also not restored to the correct position after you reset the zoom.

Here's a jsfiddle (http://jsfiddle.net/hr9athrf/2/) demonstrating it. Just zoom in to reproduce the issue.

**Comment by pawelfus** [comment] 2015-12-11 14:01
Duplicate of #4133

**Closed by pawelfus** 2015-12-11 14:01 UTC
