### ISSUE TITLE
When changing the URL, the areaspline graph fill should not disappear

### ISSUE THREAD

**Issue by gewisser** [highcharts/highcharts#14145] opened 2020-08-31 09:00 UTC
#### Expected behaviour
When changing the URL, the **areaspline** graph fill should not disappear

#### Actual behaviour
Any url change leads to the wrong path to the fill style

#### Live demo with steps to reproduce
https://codepen.io/gewisser/pen/NWNgWwb
https://h.sga-book.ru/

#### Product version
Highcharts JS v8.2.0 (2020-08-20), Highstock JS v8.2.0 (2020-08-20) 

#### Affected browser(s)
Google Chrome 85.0.4183.83

**Comment by gewisser** [comment] 2020-08-31 09:17
In the sources of highcharts, I found lines that the presence of the "**base**" tag can lead to a full path indication in the fill ...
This tag is present in my markup

```html
<base href="/">
```

**Comment by gewisser** [comment] 2020-08-31 09:52
The example was still reproduced

https://codepen.io/gewisser/pen/NWNgWwb
https://h.sga-book.ru/

**Comment by pawelfus** [comment] 2020-08-31 12:05
Thank you for reporting the issue @gewisser 

This is caused by `history.push()` and SVG URLs that are used to define some parts of the chart (gradients, filters, clip-paths etc). Basically this is the same issue as #5244 - and using workaround posted there resolves the issue: https://codepen.io/pawelfus/pen/rNezePL

**Comment by gewisser** [comment] 2020-08-31 14:32
Thanks, help. The solution works. Are you planning to make improvements related to this problem in highcharts?

**Comment by pawelfus** [comment] 2020-09-01 09:45
#5244 is still undecided, but given the popularity of the issue, we might reconsider implementing this in the core

Closing this issue as duplicate of #5244 - if you have any related questions, let's continue in #5244, okay?

**Closed by pawelfus** 2020-09-01 09:45 UTC
Labels: Type: Duplicate
