### ISSUE TITLE
Not showing tooltip after update from null

### ISSUE THREAD

**Issue by sebastienpattyn93** [highcharts/highcharts#11618] opened 2019-08-06 14:02 UTC
#### Expected behaviour
Tooltip shown properly on every datapoint

#### Actual behaviour
After updating to other series, the tooltip is only shown on datapoints where there was no null vlaue before the update

#### Live demo with steps to reproduce
https://jsfiddle.net/sebastienpattyn/bjkdms8w/13/

#### Product version
Highcharts 7.1.2

#### Affected browser(s)
- Firefox 68.01, Google Chrome 75.0

**Comment by pawelfus** [comment] 2019-08-06 14:53
Hi @sebastienpattyn93 

Thanks for reporting this issue. It's fixed on our master branch, take a look: https://jsfiddle.net/BlackLabel/vwkcgbqm/ - the fix should be part of the next release (v7.1.3).

Duplicate of #11258

**Closed by pawelfus** 2019-08-06 14:53 UTC

**Comment by sebastienpattyn93** [comment] 2019-08-07 07:20
@pawelfus Thank you very much for this, any idea on when 7.1.3 will be available?

**Comment by pawelfus** [comment] 2019-08-07 15:09
New version should be released this/next week
