### ISSUE TITLE
No unicode support in offline PDF generation

### ISSUE THREAD

**Issue by gedrox** [highcharts/highcharts#7629] opened 2018-01-09 07:58 UTC
#### Expected behaviour
Unicode characters should be exported correctly

#### Actual behaviour
PDF is generated using ANSI fonts, effectively braking unicode characters.

#### Live demo with steps to reproduce
https://jsfiddle.net/fhhm3jm1/2/
Export as PDF. Title "glāžšķūņrūķīši" is displayed as "gl  žš 7 k F k 7 +ši" in PDF.

#### Affected browser(s)
Google Chrome

**Comment by pawelfus** [comment] 2018-01-09 09:36
Hi @gedrox 

Thank you for reporting this issue. svg2pdf module is broken, use-case without Highcharts: https://jsfiddle.net/qw9uzyvf/ - which leads me to https://github.com/yWorks/svg2pdf.js/issues/19 issue and even further: https://github.com/MrRio/jsPDF/issues/12#issuecomment-328687102 issue was closed a few months ago, but it doesn't look like fixed.. 

Duplicate of #6417

**Comment by oysteinmoseng** [comment] 2018-01-15 10:10
Closing as duplicate, follow up on the other issue.

**Closed by oysteinmoseng** 2018-01-15 10:10 UTC
Labels: Duplicate
