### ISSUE TITLE
Sunburst doesn't drilldown after re-rendered (with multiple charts on the same page)

### ISSUE THREAD

**Issue by bmvantunes** [highcharts/highcharts#12959] opened 2020-02-13 13:47 UTC
#### Expected behaviour
We should be able to keep drilling down in all charts after we have a re-render

#### Actual behaviour
The sunburst chart doesn't "drilldown" after it's re-rendered with more than one chart in the page.
If only one sunburst is in isolation it works even after re-render.
After a re-render, only the last sunburst one keeps "working".

#### Live demo with steps to reproduce
https://codesandbox.io/s/silent-surf-yxi5i

#### Product version
8.0.0

#### Affected browser(s)
All

I also opened the same issue on highcharts-react (don't know where is the "best" place)
https://github.com/highcharts/highcharts-react/issues/200

**Comment by sebastianbochan** [comment] 2020-02-13 14:04
Hi @bmvantunes,
Thank you for reporting.

@ppotaczek can you take look at this?

**Comment by ppotaczek** [comment] 2020-02-13 14:54
Looks like a Highcharts regression bug. 

Simplified example: http://jsfiddle.net/BlackLabel/6m4e8x0y/4873/

Working with v6.2: http://jsfiddle.net/BlackLabel/6m4e8x0y/4872/

**Comment by Basts** [comment] 2020-02-13 15:09
I think that it is a treemap drilldown issue: https://jsfiddle.net/BlackLabel/un4xLo2t/

**Comment by Denyllon** [comment] 2020-07-21 14:35
This issue is directly related with https://github.com/highcharts/highcharts/issues/13937, and caused by the fact, that all of those charts are having the same reference to `eventsToUnbind` array.

You can temporarily apply the below fix into the `app.js` file, which will resolve the issue until the official patch will be released.
```js
(function(H) {
  H.seriesTypes.sunburst.prototype.init = function(chart, options) {
    var series = this,
      colorMapSeriesMixin = H.colorMapSeriesMixin;

    series.eventsToUnbind = [];
    // If color series logic is loaded, add some properties
    if (colorMapSeriesMixin) {
      this.colorAttribs = colorMapSeriesMixin.colorAttribs;
    }
    // Handle deprecated options.
    series.eventsToUnbind.push(H.addEvent(series, "setOptions", function(event) {
      var options = event.userOptions;
      if (
        H.defined(options.allowDrillToNode) &&
        !H.defined(options.allowTraversingTree)
      ) {
        options.allowTraversingTree = options.allowDrillToNode;
        delete options.allowDrillToNode;
      }
      if (
        H.defined(options.drillUpButton) &&
        !H.defined(options.traverseUpButton)
      ) {
        options.traverseUpButton = options.drillUpButton;
        delete options.drillUpButton;
      }
    }));
    H.Series.prototype.init.call(series, chart, options);
    // Treemap's opacity is a different option from other series
    delete series.opacity;
    if (series.options.allowTraversingTree) {
      series.eventsToUnbind.push(H.addEvent(series, "click", series.onClickDrillToNode));
    }
  };
})(Highcharts);
```
Live example: https://codesandbox.io/s/quizzical-mccarthy-g41tv

Kind regards!

**Closed** 2020-07-28 11:23 UTC
Labels: Status: In progress, Type: Regression
