### ISSUE TITLE
chart.redraw() produces different animations between different chart types

### ISSUE THREAD

**Issue by gabe-bergstrom** [highcharts/highcharts#14962] opened 2021-01-20 17:32 UTC
#### Expected behaviour
Using chart.redraw() should produce the same animation across all chart types

#### Actual behaviour
When using chart.redraw() the animation for line and area charts is very jagged compared to column charts

Something to note: The goal I am trying to achieve is the ability to update a given chart with new data with the click of a button. I would like to avoid having to destroy or generate a new chart when new data is available. 

#### Live demo with steps to reproduce
[line chart example](https://stackblitz.com/edit/highcharts-addseries-linev2)
[column chart example]( https://stackblitz.com/edit/highcharts-addseries-column)

#### Product version
"highcharts": "8.0.4"

#### Affected browser(s)
All

**Comment by gabe-bergstrom** [comment] 2021-01-22 14:29
Okay that makes sense. Thank you for the response!

**Comment by Blackbaud-TylerGreen** [comment] 2021-02-01 18:36
Can we reopen this ticket? I'm confused a little. We are having issues animating a line chart, and have a stack blitz that shows the line appearing without animating. We then show a bar graph animating how would be expected. Could I get a use case explanation of why a developer or UI/UX would want a line chart line, that has a series added, to appear without animation. To have a work-around is nice, but calling it a work around would inherently be saying this is a bug/undesired behavior. It is a little expensive to run through all the series, set them to 0, and then set them back to their value. It's even more expensive to have it animate every point with every series. 

We've implemented a work around, but would rather have a fix to linechart animation that would would allow new lines to be animated, or current lines for that matter, on a single redraw as series are added with a false redraw boolean.

**Comment by KacperMadej** [comment] 2021-02-02 09:42
@Blackbaud-TylerGreen 

Yes, we can open the ticket - opening right now.

If I understand you correctly the problem is with a lack of animation on `chart.addSeries`, so this would make the issue a duplicate of https://github.com/highcharts/highcharts/issues/4406

Please see the issue linked above and let me know if we could close this ticket as a duplicate or provide more details about the differences between those two tickets.

**Comment by Blackbaud-TylerGreen** [comment] 2021-02-02 14:06
I think it is the lack of animation when removing all series, trying to add new series, and then redrawing at the end, and no animation appears. @gabe-bergstrom's stack blitz does show this problem. It looks like you made a working version for animation on addSeries, in that other thread, but I think this is a little different.

**Comment by KacperMadej** [comment] 2021-02-02 18:39
Highcharts version 9.0.0 seems to be resolving this problem: https://jsfiddle.net/BlackLabel/msdr1ohx/2/

**Comment by Blackbaud-TylerGreen** [comment] 2021-02-02 19:26
Changing the stackblitz @gabe-bergstrom made to use highcharts 9.0.0 fixes the issue! Let me try that with our project and see if it fixes the issue!

**Comment by Blackbaud-TylerGreen** [comment] 2021-02-02 21:38
This can be closed out. Upgrading our Highcharts to 9.0.0 fixed the animation issue. Thank you so much @KacperMadej

**Closed** 2021-02-03 17:27 UTC
