### ISSUE TITLE
ignoreHiddenSeries, wrong redraw after series hidden

### ISSUE THREAD

**Issue by juliangut** [highcharts/highcharts#3809] opened 2015-02-13 10:18 UTC
# Problem

using

```
ignoreHiddenSeries: true
```

When hiding all series and showing them back again:
First column gets a bigger width and later columns get bad positioned.
To revert them to the initial positions and widths (correct situation) you have to show them all and then hide and reshow one by one again.

Problem seems to be the redraw of the second shown column, when drawing this column first one is not redraw and thus consecutive columns get bad positioned
# Example

http://jsfiddle.net/qeg35hau/

**Comment by pawelfus** [comment] 2018-02-21 16:17
Fixed since v5.0.12: http://jsfiddle.net/BlackLabel/qeg35hau/5/ (duplicate of #4921)

**Closed by pawelfus** 2018-02-21 16:17 UTC
