### ISSUE TITLE
axis label wrong format when using logarithmic and integer 

### ISSUE THREAD

**Issue by laopunk** [highcharts/highcharts#6696] opened 2017-05-08 08:21 UTC
#### Expected behaviour
Axis should display an integer when the values in the series are integer only

#### Actual behaviour
it displays a float

#### Live demo with steps to reproduce
http://jsfiddle.net/38u2amh8/
toggle the logartithmic option off and the label will display the value correctly.
Alternatively, if you add a value >0 in the second series it also works fine.

#### Affected browser(s)
Chrome on OSX

**Comment by pawelfus** [comment] 2017-05-08 12:15
Hi @laopunk 

It's an edge case when yAxis has only one point: it's hard to calculate correct extremes with nice rounded labels. It's a duplicate of #5956 - could you try to use my workaround and let us know about the results? Thanks!

**Closed by pawelfus** 2017-05-08 12:15 UTC
