### ISSUE TITLE
Incorrect and erratic click behavior on heatmap cells

### ISSUE THREAD

**Issue by rdp1414** [highcharts/highcharts#17018] opened 2022-02-19 18:16 UTC
#### Expected behaviour
Click and ctrl+click should happen smoothly on heatmap cells without script errors being logged on console. 

#### Actual behaviour
1. Cells in row-0 become white upon click (or ctrl + click).
2. After clicking on row-0 cells, all other cells become un-clickable i.e. cells don't appear with black border.
3. Also, error is raised in console while trying to click other cells.

#### Live demo with steps to reproduce
https://jsfiddle.net/cvqnxeup/

#### Product version
Highcharts `v9.1.2`

#### Affected browser(s)
Chrome

**Comment by raf18seb** [comment] 2022-02-21 17:46
Hi @rdp1414, thank you for creating the ticket.

While selecting a point, you're updating the chart with data, so all the points are destroyed and recreated again. Then, after the points are recreated and the old clicked point is gone, you're trying to continue selecting on it - that's why an error occurs, because the point is no longer there.

I don't know what is the purpose of updating the chart with all the same options while selecting a point, but it's working fine without updating the data, see demo: https://jsfiddle.net/BlackLabel/rjLh4e61/

If you're trying to achieve something specific and you have any further questions, please contact our support engineers on one of our other support channels, more info here: https://www.highcharts.com/blog/support/

I'm closing this ticket here as not a bug.

**Closed by raf18seb** 2022-02-21 17:46 UTC
