### ISSUE TITLE
weird behavior with xAxis labels

### ISSUE THREAD

**Issue by omryr** [highcharts/highcharts#10608] opened 2019-04-24 09:06 UTC
I am experiencing a weird behavior where the xaxis lables are sometimes duplicated and the duplicates are rendered on the top left of the chart stacked on eachother

has anyone encountered this issue and maybe knows how to solve it? if i inspect the element i see the list of the xlables mostly in position and when i see duplicated or out of range labels they are rendered at the top left corner of my chart (where you would expect maybe a yAxis last label if the yAxis is on the left side of the chart)

check this image to see what i mean https://i.imgur.com/RhUmUyg.png

the black part at the top is what i mean, it doesnt look like labels but when i inspect it its clear that it is

thanks for the help

**Comment by sebastianbochan** [comment] 2019-04-24 09:55
Hi @omryr,
Thank you for reporting about the problem. Could you post live demo of your chart? It will allow us to debug and find a solution.

**Comment by omryr** [comment] 2019-04-25 14:54
it seems it was an issue with my render function which kept getting config every time it rendered instead of only once

**Comment by sebastianbochan** [comment] 2019-04-26 07:59
Hi @omryr,
I guess that the problem is solved right now or am I wrong?

**Comment by omryr** [comment] 2019-04-28 10:48
yes it was solved thanks

**Comment by pawelfus** [comment] 2019-04-29 10:24
Thanks for the info! Closing the issue.

**Closed by pawelfus** 2019-04-29 10:24 UTC
Labels: Status: Pending reply
