### ISSUE TITLE
Stacked Area pointer filling bug when concatting series?

### ISSUE THREAD

**Issue by Ritorna** [highcharts/highcharts#8189] opened 2018-04-17 11:27 UTC
When concatting multiple series on each end point there are some misbehaviours on the series drawing. 
Expected should be something like this, i guess: 
![image](https://user-images.githubusercontent.com/10747768/38866123-260eeccc-4240-11e8-8d71-251368b662d2.png)
This Behavior occcurs wen using the `chart--type: "area"` and `plotOptions-series--stacking: "normal"`, as well as the `plotOptions-series-dataLabels--enabled: true`. 

Expected should be that the Area fills up to where the point is displayed. 

Live sample: 
https://jsfiddle.net/Ritorna/5zb2t88k/6/

Used with Highcharts 6.0.7, still appears in highcharts 6.1

**Comment by pawelfus** [comment] 2018-04-17 13:49
Hi @Ritorna 

Thank you for reporting the issue. I think you are right, points with the same x-values should stack on each other. 

*Internal note:*
Related to #5169 but here points have the same x-values, but somehow stacks are not calculated properly.

**Comment by TorsteinHonsi** [comment] 2018-05-03 09:09
As far as I can see, this rendering is by design. On the drawing above, there is no data to the left of point 103 on the dark-gray series, so drawing a blue area up to the upper 103 label would make the area too large. You can see a similar situation here, where the single top point has no are below it: https://jsfiddle.net/5zb2t88k/8/.

I think your data should be structured differently, for example by not applying stacking at all - https://jsfiddle.net/5zb2t88k/9/ or https://jsfiddle.net/5zb2t88k/10/

**Comment by TorsteinHonsi** [comment] 2018-05-03 09:09
Closing this, please reopen if necessary!

**Closed by TorsteinHonsi** 2018-05-03 09:09 UTC
