### ISSUE TITLE
data grouping is not considering all the values while zooming

### ISSUE THREAD

**Issue by pratapgowda007** [highcharts/highcharts#7935] opened 2018-02-27 20:57 UTC
#### fiddle link
[http://jsfiddle.net/7hymw04f/184/](http://jsfiddle.net/7hymw04f/184/)

[https://stackoverflow.com/q/49007983/2742156](https://stackoverflow.com/q/49007983/2742156)

I am grouping data for each hour. As you can see all the columns are having same length. Now zoom and you can see some of the columns are not having same height.

![without_zoom](https://user-images.githubusercontent.com/12915303/36754289-dca595e8-1c08-11e8-8040-76c7691ea0a3.png)
![with_zoom](https://user-images.githubusercontent.com/12915303/36754298-e3c7794a-1c08-11e8-96c4-097e0cd07b85.png)

**Comment by pawelfus** [comment] 2018-02-28 12:55
Hi @pratapgowda007 

Thank you for reporting the issue, as you noticed this is a duplicate of #2957. 

You can work around the issue by setting [`series.getExtremesFromAll`](https://api.highcharts.com/highcharts/series.column.getExtremesFromAll) to `true`: http://jsfiddle.net/BlackLabel/7hymw04f/185/ In general, only points in the visible range are grouped, points that are outside the extremes are not taken into calculations. In the docs we mention only yAxis extremes, but it affects dataGrouping too.

**Closed by pawelfus** 2018-02-28 12:55 UTC

**Comment by pratapgowda007** [comment] 2018-02-28 12:58
Thanks.. it solved my issue

**Comment by pawelfus** [comment] 2018-03-20 16:12
Related ticket: #5344 and PR: #8049
