### ISSUE TITLE
Cannot assign to read only property 'target' of object '#<MouseEvent>'

### ISSUE THREAD

**Issue by litera** [highcharts/highcharts#8169] opened 2018-04-12 13:00 UTC
### Expected behaviour
Error should not be thrown

### Actual behaviour
Error is thrown preventing execution of any subsequent code.

### Live demo with steps to reproduce
[Supersimplified JSFiddle](https://jsfiddle.net/eyv3x7k8/8/)
This demo doesn't use Highcharts per se, but shows the problem that Highcharts are doing in `fireEvent` function at [this line](https://github.com/highcharts/highcharts/blob/88c0013b0d8a1447fe477af151e64002f59f0ecf/js/parts/Utilities.js#L1816).

**The main outcome:** if code runs in strict mode, this line will throw an exception when we're dealing with the actual `Event` object. This call should be put in the try/catch block for this purpose, so it will fail silently when assignment isn't possible and in case an event object was created by object assignment, then it will simply assign the target.

### Product version
Highcharts < v5.

### Affected browser(s)
All?

**Comment by pawelfus** [comment] 2018-04-13 09:32
Duplicate of #5617, copy-pase answer: 

> Hi @litera
> 
> Thank you for the demo, we understand the issue, but we can not recreate it in Highcharts. We add target only for custom events (chart.redraw, Axis.setExtremes, etc.) which don't have target property and is not MouseEvent type. Please, recreate issue in jsfiddle using Highcharts, we will take a look - maybe there is a case when it's broken. Thanks!

**Closed** 2018-04-13 11:24 UTC
Labels: Cant reproduce, Pending reply
