### ISSUE TITLE
Chart width (and height) are too large if container is defined using subpixels

### ISSUE THREAD

**Issue by Artur-** [highcharts/highcharts#6528] opened 2017-03-30 09:01 UTC
#### Expected behaviour
Charts is as wide as the parent container, even if the parent container uses sub pixel widths

#### Actual behaviour
Charts is 101px wide if the parent container is 100.5px wide, causing different kind of issues

#### Live demo with steps to reproduce
http://jsfiddle.net/9w8w9obw/

When width is 601px, the charts are incorrectly below each other (301+301 > 601). When width is 600px, the charts are correctly beside each other (300+300=600)

#### Affected browser(s)
All

#### Possible solution
Use `getComputedStyle(el).width`(returns sub pixel size)  instead of `el.offsetWidth` (rounds up to nearest integer) in js/parts/Utilities.js to get the correct width (and the same for height). 

Setting `overflow: hidden` works around the problem in some cases but is not really a reliable solution

**Comment by Artur-** [comment] 2017-03-30 09:04
Possibly the same as #5153

**Comment by Artur-** [comment] 2017-03-30 09:23
`el.getBoundingClientRect().width`should work also with the downside that it will take transforms into account

**Comment by KacperMadej** [comment] 2017-11-24 13:36
Thank you for reporting. You are right - this looks like a duplicate of #5153

**Closed by KacperMadej** 2017-11-24 13:36 UTC
