### ISSUE TITLE
Functions missing from gauge Axis

### ISSUE THREAD

**Issue by hpihkala** [highcharts/highcharts#2779] opened 2014-03-07 11:49 UTC
Hi,

Gauge chart axis objects do not seem to have many of the functions listed in the API docs, for example get/setExtremes(), addPlotBand(), etc.

Best regards,
Henri

**Comment by jon-a-nygaard** [comment] 2016-04-26 09:52
Closing this issue due to: We are not able to reproduce the issue, and it is pending reply. 
Should anyone have further information on this issue, please add a comment and reopen.

**Closed by jon-a-nygaard** 2016-04-26 09:52 UTC
Labels: Cant reproduce, Pending reply
