### ISSUE TITLE
Panning: unable to pan to beginning of x axis

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4076] opened 2015-04-08 13:11 UTC
Using panning it is not possible to scroll to beginning of x axis.

Demo: http://www.highcharts.com/stock/demo/basic-line
Steps: 
1. Pan to beginning of x axis (only near the end panning is important, so no need to pan through all chart)
2. For first visible point tooltip will show May 16 (or even May 17 sometimes). Previous point can be hovered, but is outside plot area.

**Comment by pawelfus** [comment] 2015-06-16 09:32
Minified demo: http://jsfiddle.net/ne1xwc2n/2/

Steps

- zoom-in by navigator
- try to pan to the left side of the grap

Result:
![screen shot 2015-06-16 at 11 31 39 am](https://cloud.githubusercontent.com/assets/1453926/8180027/525dbdf4-141b-11e5-9e6c-687a9d2cd5e6.png)

In general, navigator "jumps" instead of smooth movements when panning on the main pane.

**Comment by highslide-software** [comment] 2015-06-16 09:43
When `xAxis.ordinal` is false, the problem doesn't occur.

The jumpy scrolling is probably due to the fact that in an ordinal axis, the extremes are clipped to the outermost point. So there isn't a smooth transition between points.

**Comment by pawelfus** [comment] 2015-10-22 09:47
Another test case: http://jsfiddle.net/j0dqtknz/1/ - `xAxis.ordinal` doesn't resolve the issue. To reproduce:

- drag left
- drag right
- last column (tick=13) isn't displayed

**Comment by edubskiy** [comment] 2015-10-22 12:17
Do you plan to fix it any time soon?

**Comment by sebastianbochan** [comment] 2015-12-07 12:31
Seems that it doens't work also when we scroll range into left and back to start position. The last edge point (in the right side) is missing.

http://www.highcharts.com/stock/demo/basic-line

**Comment by TorsteinHonsi** [comment] 2015-12-09 12:24
Reliable reproduction: 
1. Open http://jsfiddle.net/a2o6dx8v/
2. Observe that the end date is January 1, 2016
3. Drag the scrollbar first a bit left, then right to the edge.
4. The end date is changed.

@sebastianbochan Remember in order to reproduce issues this reliably we need a static chart width and also static data that doesn't update every day.

**Comment by raf18seb** [comment] 2022-06-22 21:44
Seems like the problem has never been resolved. The issue is still visible in v10.1.0

Simplified demo: https://jsfiddle.net/BlackLabel/e2rsm39a/

![first-points-ordinal](https://user-images.githubusercontent.com/23310742/175144161-873b7450-4a09-4b3f-b081-57ca768f0f23.gif)


Works fine with `ordinal` disabled.

**Comment by pawelfus** [comment] 2023-06-15 10:50
Fixed in v11.1.0: https://jsfiddle.net/BlackLabel/e2rsm39a/1/

**Closed by pawelfus** 2023-06-15 10:50 UTC
Labels: Type: Bug, Product: Highcharts Stock
