### ISSUE TITLE
Sankey chart is not seen properly on resize

### ISSUE THREAD

**Issue by amruta1eq** [highcharts/highcharts#16827] opened 2021-12-27 07:00 UTC
#### Expected behaviour
Sankey chart should be displayd properly as expected.

#### Actual behaviour
Only data labels are seen after chart result window resize.

#### Live demo with steps to reproduce
https://jsfiddle.net/9kwuqfy1/

#### Product version
All

#### Affected browser(s)
All

**Comment by raf18seb** [comment] 2021-12-28 11:40
Hi @amruta1eq, thank you for creating the ticket!

This happens because the Sankey chart doesn't support `a -> b -> a` pattern, and your data contain similar values (values that go back).

Closing as a duplicate of https://github.com/highcharts/highcharts/issues/8218

**Closed by raf18seb** 2021-12-28 11:40 UTC
