### ISSUE TITLE
Chrome RENDER WARNING: Render count or primcount is 0.

### ISSUE THREAD

**Issue by BartBM** [highcharts/highcharts#9047] opened 2018-09-24 09:10 UTC
#### Expected behaviour
Using zoom or pan does not create render warnings when boost is enabled.

#### Actual behaviour
Zoom or pan does create render warnings in Chrome when boost is enabled.
<img width="514" alt="screen shot 2018-09-24 at 11 05 50" src="https://user-images.githubusercontent.com/9977712/45952997-0707f200-c009-11e8-8e65-ab19d292b99a.png">

#### Live demo with steps to reproduce
https://jsfiddle.net/BartBM/k7d8s2mr/

#### Product version
Latest Highcharts, boost and maps version, currently 6.1.3

#### Affected browser(s)
Chome 67, 68 & 69

**Comment by burakkp** [comment] 2019-01-31 09:17
> #### Expected behaviour
> Using zoom or pan does not create render warnings when boost is enabled.
> 
> #### Actual behaviour
> Zoom or pan does create render warnings in Chrome when boost is enabled.
> <img alt="screen shot 2018-09-24 at 11 05 50" width="514" src="https://user-images.githubusercontent.com/9977712/45952997-0707f200-c009-11e8-8e65-ab19d292b99a.png">
> 
> #### Live demo with steps to reproduce
> https://jsfiddle.net/BartBM/k7d8s2mr/
> 
> #### Product version
> Latest Highcharts, boost and maps version, currently 6.1.3
> 
> #### Affected browser(s)
> Chome 67, 68 & 69

I have the same warning.

**Comment by cvasseng** [comment] 2019-02-01 09:52
I'm unable to reproduce this on 71.0. @burakkp, which version of chrome are you on?

**Comment by burakkp** [comment] 2019-02-04 08:36
> I'm unable to reproduce this on 71.0. @burakkp, which version of chrome are you on?

Hi, I get the same warning on the node.js project. We use CEF (Chromium Embedded Framework) Version is 61

**Comment by soetji** [comment] 2019-11-25 19:34
Here's an example.
https://jsfiddle.net/soetji/01rn4xy5/

**Comment by pawelfus** [comment] 2019-11-26 11:27
Thanks!

Simplified demo: https://jsfiddle.net/BlackLabel/pLt9xhge/ - seems to be related to null points in the datasets (e.g. this is fine sometimes: https://jsfiddle.net/BlackLabel/ysau3k82/ ).

**Comment by soetji** [comment] 2021-06-04 13:32
This is still an open issue, correct?

**Comment by KacperMadej** [comment] 2021-06-11 12:14
I am unable to recreate the problem using the current version of Highcharts and Chrome.
Should a specific version be used or maybe you could update the latest simplified demo to show the issue? @soetji

**Comment by BartBM** [comment] 2021-06-14 14:04
If you run this fiddle: https://jsfiddle.net/BlackLabel/pLt9xhge/ which uses the most recent highcharts library in Chrome you get the warnings.

**Comment by KacperMadej** [comment] 2021-06-15 15:25
The problem seems to be unstable or dependent on an unknown variable (maybe OS+Chrome version?).

Windows 10 - Chrome (x64) 91.0.4472.106: no issue;
Catalina - Chrome (x86_64) 91.0.4472.101: no issue;

macOS Big Sur (11.2.3) - Chrome (x86_64) 91.0.4472.77: able to recreate;

If you are able to provide a stable way to recreate the problem then it would help with resolving it.

**Closed** 2021-06-17 13:51 UTC
Labels: Status: Pending reply, Status: Review in progress, Type: Undecided
