### ISSUE TITLE
Custom width, height for marker.

### ISSUE THREAD

**Issue by svatok13** [highcharts/highcharts#5149] opened 2016-03-23 14:48 UTC
There is an issue, when i`m setting some custom values to height and width of marker. The size changes not relatively on center of shape. Also another problem is that after hover on marker, his size changes to default value of radius, ignoring my height and width values. Here is an example: 
http://jsfiddle.net/9pastdcc/1/

**Comment by pawelfus** [comment] 2016-03-24 11:40
Thanks for reporting. 

I think the bug is that `width` and `height` are applied for a symbol which should not happen ( [API](http://api.highcharts.com/highcharts#plotOptions.scatter.marker.width) reference). 

Workaround: http://jsfiddle.net/o5nkeup7/2/

    (function(H) {
      var UNDEFINED;
      H.wrap(H.Point.prototype, 'setState', function(p) {
        p.apply(this, [].slice.call(arguments, 1));

        if (this.marker && this.graphic && this.marker.width !== UNDEFINED && this.marker.height !== UNDEFINED) {
          this.graphic.attr({
            x: this.plotX - this.marker.width / 2,
            y: this.plotY - this.marker.height / 2,
            width: this.marker.width,
            height: this.marker.height
          });
        }
      });

      H.wrap(H.Series.prototype, 'drawPoints', function(p) {
        p.apply(this, [].slice.call(arguments, 1));

        H.each(this.points, function(p) {
          if (p.marker && p.graphic && p.marker.width !== UNDEFINED && p.marker.height !== UNDEFINED) {
            p.graphic.attr({
              x: p.plotX - p.marker.width / 2,
              y: p.plotY - p.marker.height / 2,
              width: p.marker.width,
              height: p.marker.height
            });
          }
        });
      });
    })(Highcharts);

**Comment by svatok13** [comment] 2016-03-24 16:01
@pawelfus, thanks for your reply. I though that if this feature works with custom images, than it must work for deault symbols too. Your code example did not work for me. My code example with data: http://jsfiddle.net/o5nkeup7/6/

**Comment by pawelfus** [comment] 2016-03-25 13:23
Thanks for the detailed demo. My previous example expects that each of the points will have `width` and `height` set on it's level. In your second demo, that options are set per series, here you can find updated workaround: http://jsfiddle.net/o5nkeup7/7/

**Comment by TorsteinHonsi** [comment] 2016-03-29 11:45
Yes, the width and height settings are supposed to work only for image symbols. For other symbols, the `radius` setting should be used. 

Why are you using width and height rather than radius on the scatter markers?

**Comment by jon-a-nygaard** [comment] 2016-04-26 08:37
Closing this issue due to: Seems to be not a bug, and it is pending reply. 
Should anyone have further information on this issue, please add a comment and reopen.

**Closed by jon-a-nygaard** 2016-04-26 08:37 UTC
Labels: Not a bug, Pending reply
