### ISSUE TITLE
Tooltip useHTML not working Internet Explorer 11

### ISSUE THREAD

**Issue by Santhoshkumar-M** [highcharts/highcharts#7950] opened 2018-03-02 11:36 UTC
#### Expected behavior
My requirement is to display the HTML designed tooltip for map area and when clicking on any country should redirect to a page. It works fine in all other browsers except IE 11.

I used useHTML option in tooltip.

#### Actual behaviour
In IE 11 when we hover out the country the tooltip is hidden immediately but when clicking on any country the tooltip is popping out without any issue.

Also, the click event is not working in IE11 instead it works when double clicking on the country.

If useHTML is set to false then all working as expected, kindly advice on this.

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/tooltip/usehtml/

#### Product version
 Highmaps JS v6.0.7 (2018-02-16)

#### Affected browser(s)
Internet Explorer 11

**Comment by pawelfus** [comment] 2018-03-05 16:12
Hi @Santhoshkumar-M 

Thank you for reporting the issue. This is a duplicate of #6957.

**Comment by pawelfus** [comment] 2018-04-30 10:05
@Maks-Yaremenko - try to avoid HTML tooltip by setting `useHTML: false`. 

Closing as duplicate of #6957.

**Closed by pawelfus** 2018-04-30 10:05 UTC
Labels: Duplicate
