### ISSUE TITLE
 Export data to CSV/XLS does align data structure in heatmap

### ISSUE THREAD

**Issue by lingyun1010** [highcharts/highcharts#10550] opened 2019-04-12 14:51 UTC
#### Expected behaviour
Exporting data to CSV/XLS file should has the same data structure/shape as heatmap.

#### Actual behaviour
Clicking on any of options provided by export-data module (CSV/XLS/Show table) shows a series of output data but the structure/shape is not aligned as how it displayed in heatmap.

#### Live demo with steps to reproduce
Try: https://jsfiddle.net/lingyun/pu90mzr8/1/

**Comment by pawelfus** [comment] 2019-04-12 15:17
Hi @lingyun1010 

Thanks for your suggestion. I think this should be optional (for example data-format, or display-format). At this moment, exporting is based on data (`series.data`), not on SVG output. 

Note that this was already reported, see #7980.

Closing as duplicate of #7980

**Closed by pawelfus** 2019-04-12 15:17 UTC
Labels: Type: Duplicate
