### ISSUE TITLE
tooltip is wrong position when zoom out chart by css

### ISSUE THREAD

**Issue by CaptainHoangLe** [highcharts/highcharts#16106] opened 2021-07-27 02:01 UTC
I am using highchart 9.1.2 and react highchart ver 3.0.0
I want to zoom out map chart to responsive in my web page .However, when i using props "zoom" in html , tooltip in my chart is broken . It is showed in wrong position.
So Please anyone can help me fix this problem. Thanks all !
This is my demo in pure JS
https://jsfiddle.net/BlackLabel/znhm49f6/

**Comment by khlieng** [comment] 2021-07-27 08:18
Duplicate of #2299, it would be preferable to use `transform: scale()` if possible.

**Closed by khlieng** 2021-07-27 08:18 UTC
Labels: Type: Duplicate
