### ISSUE TITLE
Array.prototype.filter called on null or undefined

### ISSUE THREAD

**Issue by adrianwilson** [highcharts/highcharts#5116] opened 2016-03-11 15:57 UTC
There seems to be a timing problem that mouse events are sometime captured after .destroy() is called. I am unable to sandbox the issue on jsfiddle, so am reaching out here to see if anyone else has run into this. If mouse events are captured after destroy getValidPoints calls grep with null this.points, and throws the following exception: `"Uncaught TypeError: Array.prototype.filter called on null or undefined"`.

    getValidPoints: function (points) {
	    return grep(points || this.points, function (point) {
		  return !point.isNull;
        });
    }

A proposed fix would be to add a null check to the grep method:

    grep = function(elements, callback) {
      //add following if condition
      if (elements === undefined || elements === null) {
        return;
      }
      return [].filter.call(elements, callback);
    };

Has anyone else run into this issue? Thanks!

**Comment by TorsteinHonsi** [comment] 2016-03-14 13:30
The proposed fix would work in general on modern browsers, but a similar fix would have to be added to [VML browsers](https://github.com/highcharts/highcharts/blob/v4.2.3/js/parts/Utilities.js#L1354).

However, in cases like this we try to find the cause of the bug, so that we never pass an empty array to functions like grep, each and map. If you are able to isolate it, please let us know, and we will fix it.

**Comment by pmalouin** [comment] 2016-03-14 21:04
Here's the stack trace I get, if it may help:
```
grep (highstock-4.2.3.src.js:1103)
Series.getValidPoints (highstock-4.2.3.src.js:14356)
startRecursive (highstock-4.2.3.src.js:15348)
setTimeout (async)
syncTimeout (highstock-4.2.3.src.js:567)
Series.buildKDTree (highstock-4.2.3.src.js:15353)
Series.searchKDTree (highstock-4.2.3.src.js:15406)
Series.searchPoint (highstock-4.2.3.src.js:15310)
(anonymous function) (highstock-4.2.3.src.js:10133)
each (highstock-4.2.3.src.js:1158)
Pointer.runPointActions (highstock-4.2.3.src.js:10128)
Pointer.onContainerMouseMove (highstock-4.2.3.src.js:10562)
container.onmousemove (highstock-4.2.3.src.js:10649)
```
The `this.points` attribute is undefined when breaking in the code in the `Series.getValidPoints()` method.

**Comment by pmalouin** [comment] 2016-03-14 21:10
Ok, my problems seems to be a duplicate of issue #5029...

**Comment by TorsteinHonsi** [comment] 2016-03-15 08:23
Looks like it's already fixed then, see https://github.com/highcharts/highcharts/blob/66e3599e/js/parts/Series.js#L803.

I'm closing this, please reopen if you can reproduce the issue with the latest code from http://github.highcharts.com/highcharts.js.

**Closed by TorsteinHonsi** 2016-03-15 08:23 UTC
Labels: Cant reproduce

**Comment by adrianwilson** [comment] 2016-03-15 15:53
Tested the new code, and it fixes the initial Array.prototype.filter error. Now it fails on this.xAxis.len, throwing "Uncaught TypeError: Cannot read property 'len' of undefined". Tough to reproduce since it's a timing issue, but thought I would pass on if it helps guide future fixes, thanks!

**Comment by TorsteinHonsi** [comment] 2016-03-16 08:25
Okay, that makes sense. I added a test for `this.xAxis`.

**Comment by adrianwilson** [comment] 2016-03-16 16:05
That worked, thanks for your help!

**Comment by bgity** [comment] 2018-03-24 18:40
I am working on Highcharts highmaps rich information on click chart.First time load the information by json array and its working fine.But when I am filter data using filter and load chart again its give me same error at below lines.What is solution for this?

Highcharts.wrap(Highcharts.Point.prototype, 'select', function (proceed) {
  proceed.apply(this, Array.prototype.slice.call(arguments, 1));
  var points = mapChart.getSelectedPoints();
