### ISSUE TITLE
Highcharts wordcloud archimedean spiral and version 6.1.1

### ISSUE THREAD

**Issue by msunils** [highcharts/highcharts#10644] opened 2019-04-30 13:59 UTC
#### Expected behaviour
I have developed a wordcloud which uses the custom archimedean spiral, during development i used generic reference to refer to hicharts and wordcloud module so didnt find and issues. However later realized that we are using 6.1.1 for most of the other charts and upgrading to 7.x is breaking some of the other charts. 
Here is a fiddle for your reference https://jsfiddle.net/5Lfdogxp/7/ this uses 7.1.1 and works fine, however when i change to 6.1.1 it breaks. 

Can you please advise if something can be done to make it work with 6.1.1. 
Any help is much appreciated.

#### Actual behaviour
Please change the highcharts version to 6.1.1 in the fiddle
Breaking with version 6.1.1

#### Affected browser(s) 
Tested only on chrome.

**Comment by pawelfus** [comment] 2019-04-30 14:48
Thanks for reporting the issue @msunils !

It's probably caused by infinity loop that crashes (for me at least). Since v6.1 we have improved archimedean spiral, and it's a part of the core. This is how it works now: https://jsfiddle.net/BlackLabel/gptc1we4/

Implementation:
```js
        /**
         * Gives a set of cordinates for an Archimedian Spiral.
         *
         * @private
         * @function archimedeanSpiral
         *
         * @param {number} attempt
         *        How far along the spiral we have traversed.
         *
         * @param {object} params
         *        Additional parameters.
         *
         * @param {object} params.field
         *        Size of field.
         *
         * @return {boolean|object}
         *         Resulting coordinates, x and y. False if the word should be dropped
         *         from the visualization.
         */
        function archimedeanSpiral(attempt, params) {
            var field = params.field,
                result = false,
                maxDelta = (field.width * field.width) + (field.height * field.height),
                t = attempt * 0.8; // 0.2 * 4 = 0.8. Enlarging the spiral.

            // Emergency brake. TODO make spiralling logic more foolproof.
            if (attempt <= 10000) {
                result = {
                    x: t * Math.cos(t),
                    y: t * Math.sin(t)
                };
                if (!(Math.min(Math.abs(result.x), Math.abs(result.y)) < maxDelta)) {
                    result = false;
                }
            }
            return result;
        }
```

@jon-a-nygaard - shouldn't we update docs to reflect these changes? Here: https://www.highcharts.com/docs/chart-and-series-types/word-cloud-series#custom-placement-strategies

**Comment by msunils** [comment] 2019-04-30 15:10
@pawelfus 
Thank you very much for the quick response and pointing me in the right direction. 
Yes, the browser was crashing because of an infinite loop.
You have saved me a lot of rework. 
Hadn't you pointed me at the change in the implementation of Spiral, it would have been very difficult for me to figure out.

Much appreciated and many thanks!

Cheers,
Sunil

**Comment by pawelfus** [comment] 2019-04-30 15:30
Thanks! Great to hear that you were able to solve the issue. We definitively should update our docs to prevent further confusion.

**Comment by jon-a-nygaard** [comment] 2019-05-27 10:23
Thanks again for reporting.

I have updated the section on [`Custom Placement Strategies`](https://www.highcharts.com/docs/chart-and-series-types/word-cloud-series#custom-placement-strategies) to remove the "bad" archimedean algorithm, and also highlight which algorithms has built in support in Highcharts.

I will consider this issue solved and close it. Should there be anything else, please let us know by giving us a comment.

**Closed by jon-a-nygaard** 2019-05-27 10:23 UTC
Labels: Product: Docs, Status: In progress, Type: Enhancement
