### ISSUE TITLE
Grid axis' cells are too wide

### ISSUE THREAD

**Issue by kamilkulig** [highcharts/highcharts#10888] opened 2019-06-05 09:14 UTC
#### Expected behaviour
The grid should adjust to the size of the labels.

#### Actual behaviour
It doesn't - there's a lot of unused space:
![image](https://user-images.githubusercontent.com/13188589/58944813-d628b100-8782-11e9-9994-90b7031e23fa.png)

#### Live demo
https://jsfiddle.net/BlackLabel/ny1qd94o/

#### Product version
Gantt 7.1.2

**Comment by sebastianbochan** [comment] 2019-06-05 10:37
Hi @kamilkulig,
Im closing this bug as duplicate of https://github.com/highcharts/highcharts/issues/10281

**Closed by sebastianbochan** 2019-06-05 10:37 UTC
Labels: Product: Highcharts Gantt, Type: Bug
