### ISSUE TITLE
Issue with large heatmap chart using boost module

### ISSUE THREAD

**Issue by ff-tushar** [highcharts/highcharts#6981] opened 2017-07-20 06:34 UTC
#### Expected behaviour
When we upgraded to the High Chart 5.0.11 we have used the Boost module for rendering the large Heatmap chart. It should render the chart properly with the colors we provide.

#### Actual behaviour
The heatmap chart does not draw properly. It does not plot the expected colors on the chart. Added question for the same on the High chart forum https://forum.highcharts.com/highcharts-usage/canvas-solution-for-long-heatmap-chart-t38375/

#### Live demo with steps to reproduce
template: http://jsfiddle.net/d_paul/ozv1to3t/ 
In the mentioned JSFiddle. We are seeing the issue that color plotted for the points are not correct.
If you mouse over on the blue point value is 70.13 and shows high lighting correctly on the legend but on chart it has plotted  in blue color.
It looks like the plotting color for the point is wrong.

**Comment by pawelfus** [comment] 2017-07-20 10:54
Color does plot correctly, but it looks like tooltip is rendered for a wrong point. In your screenshot you can see in tooltip: 70.13 -> so it's correct color, but wrong point. Short gif:

![v9agcquqaf](https://user-images.githubusercontent.com/1453926/28414019-03521892-6d4a-11e7-83b5-5d8c2b58c206.gif)

**Comment by ff-tushar** [comment] 2017-07-20 11:04
See the following JS Fiddle which behaves correctly which has same code but only difference is boost module is not included. You can see clear difference in the color plotted on charts with respect to mentioned JS Fiddle in issue. 
Withput Boost Module:- https://jsfiddle.net/tushar412/mvk4c6e1/1/. 
 Also mentioned JSFiddle in the ticket if you mouse over on the chart with blue line you can see the legands over is on different color. Legand color is correct but chart plotting color is wrong.

**Comment by cvasseng** [comment] 2017-07-25 07:10
Internal note: The issue is with inverted heatmaps. When removing `inverted`, the boosted and non-boosted fiddles are identical.

**Comment by ff-tushar** [comment] 2017-07-26 09:57
Is this scheduled for upcoming release? If yes, can you please share the same when this will be available.

**Comment by ff-rboutotte** [comment] 2017-07-26 20:45
We are also facing the same issue....do you have a fix we can apply before it is officially fixed? We have a release next week and this is a blocker for us due to performance of the chart, without the boost module it takes 2-3 times longer to render the chart.

**Comment by ff-cviradiya** [comment] 2017-07-27 05:53
boost module is really making things snappy. We are not able to include boost and take the performance benefit because of this issue. The fix for this would greatly help. 

Please expedite this if possible.

**Comment by cvasseng** [comment] 2017-07-27 11:39
This has now been fixed in the `hc5-fixes` branch (https://github.highcharts.com/hc5-fixes/modules/boost.js).

It will be merged into master for the next release, until then, you could copy the module from the `hc5-fixes` branch and use it that way.

**Closed** 2017-07-27 12:58 UTC
Labels: Bug, Fix suggested

**Comment by ff-tushar** [comment] 2017-07-28 06:46
After updating the boost module code. This is not working in Chrome. We are getting 
"Cannot create property 'moveTo' on boolean 'false'" JS error and due to that it does not render the chart.
Please Re-open this.

**Comment by cvasseng** [comment] 2017-07-28 07:08
@ff-tushar: I'm not seeing any errors in Chrome 59.0.3071.115 on macos. 

Are you getting the error in [this fiddle](http://jsfiddle.net/d_paul/ozv1to3t/) too? 

Could you paste the console log (or post a screenshot)?

**Comment by ff-tushar** [comment] 2017-07-28 10:16
@cvasseng 
After doing the investigation I have found that it does not work with the 5.0.12 version of High Chart.
Here is the JS Fiddle of for the same:- https://jsfiddle.net/tushar412/j10r66x8/3/
Do we have to upgrade to version 5.0.13?

**Comment by cvasseng** [comment] 2017-07-28 10:36
An updated has been pushed to `hc5-fixes` now.

The fix will be included in `5.0.14` which is a hotfix release arriving later today.

**Comment by ff-tushar** [comment] 2017-07-28 10:40
Let me try out.
