### ISSUE TITLE
Graphs sometimes not drawn in chrome when disabling some series with jquery

### ISSUE THREAD

**Issue by marcogallotta** [highcharts/highcharts#2114] opened 2013-08-07 21:44 UTC
Since version 1.3.3 of highstock, some of our graphs sporadically fail to render (specifically, all the series; the axes and legend are present) in Chrome (works in Firefox). This seems to be restricted to graphs with series of flags, and sometimes disabling those makes it work. Note that we disable some series via jquery.

**Comment by jon-a-nygaard** [comment] 2016-08-18 10:33
Closing this issue since we are unable to reproduce, and it is pending a reply. Should anyone have further information about the issue, please give us a comment.

**Closed by jon-a-nygaard** 2016-08-18 10:33 UTC
Labels: Cant reproduce, Pending reply
