### ISSUE TITLE
Issue with the 3d-chart library - since change the version 10 to 11

### ISSUE THREAD

**Issue by Davicito81** [highcharts/highcharts#18902] opened 2023-04-28 07:59 UTC
#### Expected behaviour
I'm using the 3d pie and the 3d line charts for a long time since the version change `from` 10 to 11. on April 26, 2023, my charts are no longer displayed 

For that I used the two libraries:
highchart.js and highcharts-3d.js via CDN

#### Actual behaviour
Now I found that on the browser console output I could identify the following issue

<Code>
Uncaught TypeError: w.pushUnique is not a function
    compose highcharts-3d.src.js:3019
    <anonymous> highcharts-3d.src.js:5006
    C highcharts-3d.src.js:26
    <anonymous> highcharts-3d.src.js:5000
    <anonymous> highcharts-3d.src.js:19
    <anonymous> highcharts-3d.src.js:21
</Code>

To fix the issue I Installed the older version 10..3.2 via node locally to my web application to prevent such kind of error from external dependencies.  

#### Live demo with steps to reproduce
Look at the same demo charts on highcharts.com, here you can find the same issue as with my 3d charts:
 https://www.highcharts.com/demo/3d-pie-donut
 https://www.highcharts.com/demo/3d-pie

#### Product version

The Issue has to do with the 3d highcharts library: highcharts-3d.js  (since version 11 changed on April 26, 2023)

#### Affected browser(s)
The issue is shown on all type of browsers and of course on the some demo page of highcharts.com under the 3d charts

**Comment by TorsteinHonsi** [comment] 2023-04-28 10:27
This occurs because the old version of `highcharts.js` is cached, while `highcharts-3d.js` loads the new version. The issue does not occur in our offices, but I suspect it may have to do with regional CloudFlare cache. Will investigate.

**Comment by TorsteinHonsi** [comment] 2023-04-28 10:30
Duplicate of #18893

**Closed by TorsteinHonsi** 2023-04-28 10:30 UTC

**Comment by TorsteinHonsi** [comment] 2023-04-28 10:58
@Davicito81 I purged the CloudFlare cache again, can you try a hard refresh now?

**Comment by Davicito81** [comment] 2023-05-02 14:27
@TorsteinHonsi Ok I checked that. Now It's woking fine and I can see all my 3d charts perfectly.  Thank you for the support.
