### ISSUE TITLE
Numbers between 1000-9999 doesn't show thousand separator even after it is set 

### ISSUE THREAD

**Issue by dev-song** [highcharts/highcharts#17296] opened 2022-05-16 01:45 UTC
#### Expected behaviour
When a thousand separator is set, separators should be seen on numbers that have 4 digits.
e.g. 1000, 1000k, 1000M -> 1,000, 1,000k, 1,000M, ...

#### Actual behaviour
Even after the separator is set, separators don't appear on numbers between 1000-9999.
(numbers with units display separators properly)

#### Live demo with steps to reproduce
[CodeSandbox Draft](https://codesandbox.io/s/bug-reproduction-highcharts-thousand-separator-wiipll)
1. Click number range buttons in the draft.
2. Check the bug in cases of `Around 1,000`, `Around 5,000`, `Around 10,000`
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/52951039/168502661-51d97090-1edd-4faa-ad58-d60da67a166d.png">

#### Product version

Latest release, v10.1.0

#### Affected browser(s)
Google Chrome, Microsoft Edge, ...
regardless of OS

**Comment by raf18seb** [comment] 2022-05-17 08:04
Hi @dev-song, thanks for creating the ticket!

It's not a bug. We decided that it would be better not to add thousands separator for 4-digits numbers, mostly because years should not have thousands separator.

See an original ticket here: https://github.com/highcharts/highcharts/issues/2466
And a part of the code responsible for using thousands separator only for numbers >= 10000
https://github.com/highcharts/highcharts/blob/c7eddb1219cf6ba0f547bdbc2140b5aa735eeff6/ts/Core/Axis/Axis.ts#L664-L668

If you want to add a thousands separator anyway, you can use e.g. `formatter` callbacks, see demo: https://jsfiddle.net/BlackLabel/h6ogvapt/

Closing as not a bug and resolved.

**Closed by raf18seb** 2022-05-17 08:04 UTC

**Comment by dev-song** [comment] 2022-05-17 08:23
omg, I searched issues with `open` filters on, so I didn't notice closed relevant issues.
Thanks for providing the explanation and how to solve it, @raf18seb!
Clearly understood with the case of years.
