### ISSUE TITLE
Not showing the right values when scrolling right (using highstock scrollbar)

### ISSUE THREAD

**Issue by igimenez** [highcharts/highcharts#6714] opened 2017-05-11 00:22 UTC
#### Expected behaviour

Scrollbar should work and show data series in order

#### Actual behaviour

When scrolling right the values get messed up

#### Live demo with steps to reproduce

http://jsfiddle.net/fdr77fv5/1/

1 - Click on Product B (Label, not chart series)

-> When scrolling right the values are not right (when extremes are less than the total number of values displayed in the series), if I set the extremes to more, for instance more than the number of values in the series (no scrolling) it works fine. (http://jsfiddle.net/x6c0oLk2/)

**Comment by pawelfus** [comment] 2017-05-11 14:20
Hi @igimenez 

Thank you for reporting the issue. Workaround is to set `cropThreshold` for all series, for example: http://jsfiddle.net/fdr77fv5/3/
```
plotOptions: {
  series: {
    cropThreshold: 500
  }
}
```

*Internal note:*
It's not related to the scrollbar, but `category` type axis. Simple demo: http://jsfiddle.net/fdr77fv5/2/ - looks similar to, or even duplicate of #5857

**Comment by igimenez** [comment] 2017-05-11 15:42
Thanks @pawelfus. Btw, is there a way to only add scrollbar in the drilldown only if the drilldown has more than x number of values?

**Comment by pawelfus** [comment] 2017-05-11 15:47
Not exactly, but setting [`scrollbar.showFull`](http://api.highcharts.com/highstock/scrollbar.showFull) to false is probably what you are looking for :)

**Comment by igimenez** [comment] 2017-05-11 16:50
@pawelfus Genius!

**Closed** 2017-07-26 15:50 UTC
