### ISSUE TITLE
annotations outside plot area issue (overflow regression)

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#12897] opened 2020-02-05 10:46 UTC
#### Expected behaviour

Overflow set to 'allow' should allow rendering annotation outside the plot area.
Demo (Highcharts v 6): https://jsfiddle.net/BlackLabel/1cr98bkp/

#### Actual behaviour

In the current version, annotations disappear when is render outside the plot area. 

#### Live demo with steps to reproduce

Demo: https://jsfiddle.net/BlackLabel/p2xh5kba/
Demo with useHTML, where only the text is displayed: https://jsfiddle.net/BlackLabel/f2kgr5xe/

#### Product version

Highcharts JS v8.0.0 (2019-12-10)

**Comment by Sdavletshina** [comment] 2020-02-05 13:55
Thanks so much @Basts. Can someone suggest me a temporary workaround?

**Comment by pawelfus** [comment] 2020-02-06 12:02
**Workaround:**
Snippet:
```js
Highcharts.Annotation.prototype.addClipPaths = function () {};
```
Demo: https://jsfiddle.net/BlackLabel/2yras9Lq/

*Internal note:*
It's caused by implementing clipping in annotations, but we didn't provide an option to disable this (similar to `series.clip` that allows to control that).

**Comment by AdamMescher** [comment] 2020-08-02 03:23
After acknowledging the following:
1. The workaround worked exactly like I needed it to
2. A global pandemic happened
3. I'm not a paying user

I do see that this was moved from `To do` to `In Progress` on March 27. Any update on when this will be fixed?

**Comment by sebastianbochan** [comment] 2020-08-03 08:34
We decided to redesign the solution, so at this moment its not in progress (I apologize for the confusion about the status). I updated to the correct.

Currently, we do not have ETA for this ticket.

**Comment by pawelfus** [comment] 2022-02-03 15:54
Closing as duplicate of #15399 - since v9.3.0 it's possible to disable cropping by setting [`annotations.crop`](https://api.highcharts.com/highcharts/annotations.crop) to false.

**Closed by pawelfus** 2022-02-03 15:54 UTC
Labels: Type: Regression, Status: Inbox
