### ISSUE TITLE
axis.getExtremes reporting incorrect dataMin/Max values

### ISSUE THREAD

**Issue by mgalvey** [highcharts/highcharts#1043] opened 2012-06-12 20:19 UTC
**EDIT**: Forgot to add - I'm using Highstock 1.1.6 for these tests.

I've been having an issue with the Y axis on my stock charts: certain datasets and x-ranges were producing a graph with a much too large Y axis range.  I started playing with my series data - disabling some, enabling others, and I finally identified what I think is the issue.  Refer to http://jsfiddle.net/nkvqx/2/.  

Note that from December 2011 to January 2012, there is a steep spike downward.  Now press the YTD range selector button, which should change the date range to Jan 1, 2012 to May 1, 2012.  There's an awful lot of extra space at the top of the plot area where no data lives.  I decided to drop into my browser's console and check on the getExtremes values for the Y axis, and I found that the maximum number was far greater than the highest point displayed on the graph at the time.  Going off of this information, I started looking in the Highstock code for the axis scaling functionality, and I've discovered a workaround.

Line 6362 of highstock.src.js: **for (i = 0; i < yDataLength; i++) {**

I changed my copy of the code to start i at a value of 1, and the result seems to confirm what I suspected was going on: I think that series.processedYData (and possibly processedXData - referenced starting at line 6357) has at least one extra element which is throwing off axis scaling.  Going a bit further still, I checked the values of series.processedYData, and this was my result:

[2.9318181818182, 0.8780487804878, 0.96385542168675, 0.96385542168675, 0.60843373493976, 0.6441717791411]

Note that there are 6 elements here, rather than the expected 5 (Jan-May).

Here is the same chart, using my modified code: http://jsfiddle.net/YKvBp/.  This time, pressing the YTD button will show a result more like what I expected in the first place.  I should point out that I haven't really gone any further to diagnose this issue, and I haven't attempted to track down the root cause of processedYData having more than the expected number of elements.

**Comment by vickychijwani** [comment] 2015-05-21 12:41
Having the same issue with `xAxis.getExtremes()` on Highcharts 4.1.5. Sometimes when I zoom in too much, the `min` and `max` in extremes are equal to the tiny selected region of the chart, rather than the actual extremes of the axis.

**Comment by highslide-software** [comment] 2015-05-22 07:42
@vickychijwani Do you have a reproduceable demo of this?

**Comment by vickychijwani** [comment] 2015-05-22 11:58
Sorry, I'm using Highstock 2.1.5 (I incorrectly stated Highcharts 4.1.5). I'll try to make a live demo.

**Comment by jon-a-nygaard** [comment] 2016-04-26 11:17
Closing this issue due to: We are not able to reproduce the issue, please provide a live demo of it. To do this you can use [JSFiddle](https://jsfiddle.net) 
Should anyone have further information on this issue, please add a comment and reopen.

**Closed by jon-a-nygaard** 2016-04-26 11:17 UTC
Labels: Cant reproduce, Pending reply
