### ISSUE TITLE
HighStock Series superposition when we zoom in with the Time Slider

### ISSUE THREAD

**Issue by Lazghab-Slim** [highcharts/highcharts#5432] opened 2016-06-24 09:25 UTC
![before](https://cloud.githubusercontent.com/assets/20125232/16333854/d36730e8-39fd-11e6-8243-edc61d7ef1d4.png)

![after](https://cloud.githubusercontent.com/assets/20125232/16333853/d347ac82-39fd-11e6-8511-33ccf8d3a1a7.png)

when we zoom in using the Time slider, at a certain point we have all the series superposing with the first Serie.

**Comment by pawelfus** [comment] 2016-06-24 09:31
Hi, thank you for contacting us. Could you recreate issue on jsFiddle? We will check this.

**Comment by Lazghab-Slim** [comment] 2016-06-24 09:51
Hello,
i'm generating the Chart Dynamically With MVC/Razor, So it will  be Hard to reproduce the problem on JSFiddle but This is the JavaScript Code Responsible of the generation:
ForEach(...)
{.....
 $('#@graphConfigurationModel.Id').highcharts('StockChart', {
                    credits: {
                        enabled: false
                    },
                    rangeSelector: {
                        enabled: false
                    },

                    title: {
                        text: '@graphConfigurationModel.GraphTitle',
                        style: { fontSize: '14px' }
                    },
                    subtitle: {
                        text: ''
                    },
                    legend: {
                        enabled: true
                    },
                    yAxis: [{
                        labels: {
                            format: "{value} GWh",
                            style: {
                                color: "#000000"
                            }
                        },
                        title: {
                            text: "Volume",
                            style: {
                                color: "#000000"
                            }
                        },
                        offset: 0,
                        lineWidth: 2
                    }, {
                        labels: {
                            format: "{value} Deals",
                            style: {
                                color: "#000000"
                            }
                        },
                        title: {
                            text: "Deals Number",
                            style: {
                                color: "#000000"
                            }
                        },
                        offset: 0,
                        lineWidth: 2,
                        opposite: false
                    }],
                    plotOptions: {
                        area: {
                            marker: {
                                enabled: false,
                                symbol: 'circle',
                                radius: 2,
                                states: {
                                    hover: {
                                        enabled: true
                                    }
                                }
                            }
                        }
                    },
                    series: @Html.Raw(@graphConfigurationModel.GetChartsData())
                });
....
}

For The Data Sent: it's a List<Dictionary<string, object>> in which i define:
for every Serie which is a Dictionary<string, object>
["name"] = chart.Title,
["type"] = chart.ChartType,
 ["turboThreshold"] = pointList.Count + 1,
["yAxis"] = axisType,
["data"] = pointList
 and then i use the Newtonsoft.Json.JsonConvert.SerializeObject
to Serialize Data

**Comment by jon-a-nygaard** [comment] 2016-06-28 10:09
Hi @Lazghab-Slim I am sorry but I am not able to reproduce this issue from the description you have given us, here is an [example of what I have tried so far](http://jsfiddle.net/uetcq2sr/1/). 
Could you perhaps use this as a base to recreate the issue?

**Comment by jon-a-nygaard** [comment] 2016-07-22 07:44
Closing this issue since we are unable to reproduce it, and it is pending a reply. Should anyone have further information on this issue, please comment and reopen.

**Closed by jon-a-nygaard** 2016-07-22 07:44 UTC
Labels: Cant reproduce, Pending reply
