### ISSUE TITLE
NextJs[^14.2.3] dev/build error: Cannot read properties of undefined (reading 'hasOwnProperty')

### ISSUE THREAD

**Issue by niralivasoya** [highcharts/highcharts#21307] opened 2024-06-10 18:50 UTC
#### Expected behaviour

I am using the Highcharts in my Application for various purposes. I get the `Cannot read properties of undefined (reading 'hasOwnProperty')` typescript error whenever I compile and build the code. 

I saw a few issue tickets related to this issue but didn't get any solution from them. To be more specific if I remove the exporting module imports `import exporting from 'highcharts/modules/exporting'` it compiles successfully. I get this type of errors specially when I import modules like exporting, x-range and other charts. 

#### Actual behaviour

It should compile and build the code successfully.

#### Live demo with steps to reproduce
https://codesandbox.io/p/devbox/highchart-build-issue-n6ftvp?file=%2Fapp%2Fpage.tsx%3A7%2C1

#### Product version

```
"highcharts": "^11.1.0",
"highcharts-react-official": "^3.2.1",
 "next": "^14.2.3",
```

#### Affected browser(s)

I am checking it on Brave/Chrome browser. 

Please help me to fix this error.

**Comment by hubertkozik** [comment] 2024-06-11 09:19
Hi @niralivasoya! Sadly, I cannot check your demo in CodeSandbox due to the wrong permissions. Can you check it and send the correct link?

**Comment by niralivasoya** [comment] 2024-06-11 13:57
@hubertkozik Oh my bad, it was in draft. Now you can access it. Thanks

**Comment by hubertkozik** [comment] 2024-06-12 11:14
@niralivasoya thank you for providing the demo. The problem is related to the NextJS, which executes code twice - on the server-side and then the client-side, not to the Highchart library. To fix it, you should add these lines of code:
> if (typeof Highcharts === 'object') {
    HighchartsExporting(Highcharts)
}

Please, check the demo below and some docs reference.
**Live demo:** https://codesandbox.io/p/devbox/highchart-build-issue-forked-h8yclh?file=%2Fapp%2Fpage.tsx%3A7%2C1&workspaceId=07b5692a-7c9d-48a7-b810-62e1833b90d4
**API Reference:**  https://github.com/highcharts/highcharts-react?tab=readme-ov-file#highcharts-with-nextjs

Closing as not a bug.

**Closed by hubertkozik** 2024-06-12 11:14 UTC
Labels: Type: Not a bug
