### ISSUE TITLE
TypeError: Cannot read property 'parts/Globals.js' of undefined

### ISSUE THREAD

**Issue by ivanakimov** [highcharts/highcharts#10588] opened 2019-04-19 12:46 UTC
#### Expected behaviour

Highcharts loads.

#### Actual behaviour

Highcharts doesn't load.

#### Live demo with steps to reproduce

It's hard to give a live demo as this is happening in our [Next.js](https://github.com/zeit/next.js/) repo.
This is the code we use:

```javascript
import Highcharts from 'highcharts/highstock';
import HighchartsExporting from 'highcharts/modules/exporting';
import HighchartsReact from 'highcharts-react-official';

HighchartsExporting(Highcharts);
```

Pretty much exactly what the `README` says to do (with the addition of `highcharts-react-official`). The error we get is:

```
TypeError: Cannot read property 'parts/Globals.js' of undefined
    at /project/node_modules/highcharts/modules/exporting.js:10:408
```

#### Product version

```
"highcharts": "^7.1.1",
"highcharts-react-official": "^2.1.3",
```

I also noticed this similar issue, but both Highcharts and Exporting module is coming from the same repo, so not sure if this affects us: https://github.com/highcharts/highcharts/issues/10465

#### Affected browser(s)

Error shows up in the server console log & browser, since Next.js is a universal app.

**Comment by pawelfus** [comment] 2019-04-19 13:15
Hi @ivanakimov 

Thanks for reporting the issue. As you found out, this is caused by mismatching versions (e.g. Highcharts v7.0 and modules for v7.1) - for example one file is cached, other was updated properly. Nothing else comes to my mind. Could you make sure that installed version of Highcharts is v7.1.1? 

```js
import Highcharts from 'highcharts/highstock';
import HighchartsExporting from 'highcharts/modules/exporting';
import HighchartsReact from 'highcharts-react-official';

console.log(Highcharts.version);

HighchartsExporting(Highcharts);
```

If the version is the same, then could you perhaps setup a git repo with simplified demo of the issue? Anything that helps us debug the issue is more than welcome.

**Comment by ivanakimov** [comment] 2019-04-19 13:34
Hi @pawelfus,

Thanks for the quick response. For some reason I get `undefined` when doing `console.log(Highcharts.version);` but here's a quick repo to reproduce:

https://github.com/ivanakimov/next-highcharts

**Comment by pawelfus** [comment] 2019-04-19 15:21
Thanks for the demo! It's broken for me too.

@jon-a-nygaard - could you take a look?

**Comment by ivanakimov** [comment] 2019-04-23 09:33
@pawelfus @jon-a-nygaard I very much appreciate the insane amount of free open-source work going into this project, but wanted to see if you guys had any rough estimate for how long patching something like this might take? :sweat_smile:

**Comment by jon-a-nygaard** [comment] 2019-04-24 07:48
Hi, for me it seems to be something wrong with the documentation for highcharts-react.

Highcharts waits until it has access to a window and document before it constructs itself, and it can not be extended with modules until this is done as it does not exist. A suitable place for this may be in the `componentDidMount`, but that unfortunately happens after HighchartsReact has rendered the chart.
I tested with earlier version v7.0.0 as well, and it seems that this usage pattern did not work then either.

@pawelfus Do you know if this worked properly before? I can not find a demo of this.

@ivanakimov Unfortunately I can not give a good estimate yet as I am still unsure what actions we need to resolve the issue, but I hope we can have this clear soon.

**Comment by ivanakimov** [comment] 2019-04-24 10:24
@jon-a-nygaard I see, got it. Please let me know if you'd like me to do/test anything else once you guys figure out a bit more.

**Comment by KacperMadej** [comment] 2019-04-24 11:15
@ivanakimov 
The problem was previously reported and solved in here: https://github.com/highcharts/highcharts-react/issues/76#issuecomment-446408078

In short: the code runs twice and we don't want it to initialize the modules on server side, so add a check and all should be fine. This code for `index.js` runs fine in your app:
```js
import React, { Component } from 'react';
import Highcharts from 'highcharts/highstock';
import HighchartsExporting from 'highcharts/modules/exporting';
import HighchartsReact from 'highcharts-react-official';


if (typeof Highcharts === 'object') {
    HighchartsExporting(Highcharts)
}

export default class Chart extends Component {

  render() {
    return (
      <HighchartsReact highcharts={Highcharts}  options={{}} />
    );
  }

}
```

I would like to close the issue as a duplicate and resolved, but I'll wait first for your replies.

**Comment by jon-a-nygaard** [comment] 2019-04-24 11:27
Thanks @KacperMadej!

For me it makes sense to close it as a duplicate unless there is more to add to this issue.
Although the readme in highcharts-react should probably be updated to avoid similar issues being reported in the future.

**Comment by ivanakimov** [comment] 2019-04-24 11:31
@KacperMadej confirmed -- thank you all for taking a look!
I think adding anything to the readme to mention this Next.js quirk would help others :muscle:

**Comment by sebastianbochan** [comment] 2019-04-24 12:06
@ppotaczek can you update docs in README ?

**Comment by ppotaczek** [comment] 2019-04-24 12:19
@sebastianbochan,

Sure, I think that is a good idea. Maybe it is worth to add that information to the other wrapper docs as well? @Denyllon, @KacperMadej

**Comment by Denyllon** [comment] 2019-04-25 09:26
I've just added a reference to this thread inside of related `highcharts-vue` wrapper issue, and attached the same solution there. I think that's enough, because the problem currently exists just on this one case, so it's not necessary to extend the documentation with any additional informations.
In my opinion, the 'Issues' section is the best place to keep informations like that.

What do you think @KacperMadej?

**Comment by KacperMadej** [comment] 2019-04-25 10:01
All people responsible for the wrappers know the problem now, so we'll be able to answer similar cases fast through support channels. The problem was never before reported successfully in context of any other environment that React, so adding this to docs or even FAQ for Vue or Angular wrappers might be an overkill. I'll ensure that the info will added to Knowledge Base on Freshdesk.

**In short:** I agree with Daniel. KB in Freshdesk case will be created soon (after or even before the official launch of Highcharts Freshdesk).

**Closed by KacperMadej** 2019-04-25 10:01 UTC
Labels: Type: Bug

**Comment by richardeschloss** [comment] 2020-05-12 04:08
Hi @KacperMadej (and all), I think I just came up with a much simpler solution that both you and your users may like more. It's captured in [PR #137](https://github.com/highcharts/highcharts-vue/pull/137).

So, rather than updating all the docs and FAQs (which is a chore probably no one wants to do), I just stuffed a ".use" method into the wrapper, and let the wrapper register any supported feature with options. The ".use" method captured the bulk of the solutions described in this thread so that users of the HighchartsVue wrapper can simply do:

```
import HighchartsVue from 'highcharts-vue' 
HighchartsVue.**use**('stockChart') 
```

In the PR, I also updated the README which was able to be reduced because of this. Going forward, it may be more adaptable if the wrapper also exposed a "supportedFeatures" to perhaps be used by an IDE's intellisense.

I'll happy to hear your feedback.

**Comment by KacperMadej** [comment] 2020-05-12 12:18
Hi @richardeschloss 

Thank you for the PR. Highcharts Vue wrapper developers and maintainers will be taking care of the PR and should provide more info there when available.

Updating docs and FAQs are not a problem. It is more important for us that all developers and maintainers of the wrappers know the issue because technical support very often must provide answers even for the questions already answered in docs and FAQs. BTW Next.js removed the relevant FAQ entry about the problem, so maybe it was resolved.

**Comment by richardeschloss** [comment] 2020-05-12 18:57
Hi! I appreciate your response and perspective! For me, I was using the Nuxt framework (which is like Next.js, but for Vue), and I was encountering this issue too. I realized that while the "highcharts is object" check worked, it was even easier to configure Nuxt to only have the highcharts run client-side (example [here](https://github.com/richardeschloss/covid19-spc/blob/master/plugins/globals.client.js)). (In Nuxt, the framework respects the naming convention of plugin files ending in ".client.js" and ".server.js"; so simply naming my plugin "globals.client.js" was a simple fix for me).
