### ISSUE TITLE
Inconsistency while updating text annotation using `annotation.update`

### ISSUE THREAD

**Issue by nishikantparmariam** [highcharts/highcharts#20175] opened 2023-11-22 19:07 UTC
#### Expected behaviour
For an annotation while doing `annotation.update()` if an option is not passed, it should remain as is, and provided options should be updated. (Let me know if this is incorrect expectation from the API)

#### Actual behaviour
In below reproducer, my use-case is to update just the color of text annotation without changing any of its options (including position), but when I do -

 `chart.annotations[0].update({labels: [{style: {color: 'yellow'}}]})` 

the label annotation moves to its original position if I had dragged it before. Weirdly other annotation properties like background color etc. remain as is.

A workaround I found is to merge all existing options and then update - 

`chart.annotations[0].update({labels: [_.merge({}, chart.annotations[0].labels[0].options, {style: {color: 'yellow'}})]})`

but wanted to check if this is a bug or is there better way to do this. In general, I want to update any option under `labels[0]`.

#### Live demo with steps to reproduce

https://jsfiddle.net/xmou0463/

Reproducer:

![text-annotation-position](https://github.com/highcharts/highcharts/assets/7736252/42d9954c-62da-4155-b8b5-912563a7366f)

#### Product version
11.2.0 (Latest)

#### Affected browser(s)
Chrome

**Comment by karolkolodziej** [comment] 2023-11-27 07:42
HI @nishikantparmariam!  Apologies for my late reply.

I agree with you. If you only change one option (like font colour), the position should not be changed. 
However, your workaround seems to do the trick.

**Comment by Vazonik** [comment] 2024-02-14 17:35
Hi @nishikantparmariam,
updating the annotation for now resets all options and creates it again based on `userOptions`. For this reason, any changes to `options` not saved in `userOptions` will be reset after `update`. If you want to keep the position, you should also update `userOptions` when needed. See the `drag` and `positioner` options in [this demo](https://jsfiddle.net/BlackLabel/85u4yd31/).

You can see more here (e.g. lines 80-81):
https://github.com/highcharts/highcharts/blob/13b8a578aba1b1f16a0895898ccd0d42f1fc414e/ts/Extensions/Annotations/Types/BasicAnnotation.ts#L71-L83

For this reason, I am closing this issue as not a bug, although it is worth considering in the future whether the annotation update should destroy and redraw it or just update only affected attributes.

**Closed by Vazonik** 2024-02-14 17:35 UTC
Labels: Type: Bug, Product: Highcharts, Priority: Normal, Type: Good for beginners
