### ISSUE TITLE
Highmaps mapData doesn't update

### ISSUE THREAD

**Issue by sidx1024** [highcharts/highcharts#16033] opened 2021-07-13 06:07 UTC
#### Expected behaviour
- Changing options and mapData doesn't update the map

Example: 
<img width="724" alt="Screenshot 2021-07-13 at 11 36 27 AM" src="https://user-images.githubusercontent.com/11299391/125399688-91928980-e3ce-11eb-9036-390d846d8ad9.png">

Here I'm switching the series mapData from US Map to World Map and back to US again, the older chart doesn't get destroyed and newer one overlaps on it.

#### Actual behaviour
- Changing options and mapData should update the map

#### Live demo with steps to reproduce
https://codesandbox.io/s/amazing-heisenberg-810jm

#### Product version
highcharts - 9.1.2

#### Affected browser(s)
All browsers

**Comment by KacperMadej** [comment] 2021-07-14 15:38
Thank you for reporting.

Duplicate of https://github.com/highcharts/highcharts/issues/11636

See the above link for a workaround.

**Closed by KacperMadej** 2021-07-14 15:38 UTC
