### ISSUE TITLE
Null values in area charts

### ISSUE THREAD

**Issue by karellm** [highcharts/highcharts#2069] opened 2013-07-25 21:35 UTC
Hi,

I'm a little bit confused with this behaviour and I don't know if it is expected or a bug. Let's consider the following serie of values : 
`70000, null, 50000, null, null, 50000, 60000`

I would expect that Highcharts doesn't draw any line/area at all for the 5 first points and would draw one between the last two values. The first and third values should get a point each but no line/area.

This is what happens for line charts, but not for area charts. I've put together a JSFiddle to show this: http://jsfiddle.net/3qZFS/1/

Thanks

**Comment by tristil** [comment] 2015-01-21 06:44
You can solve the problem Slggamer mentions by starting a new set of series on the other side of the gap FYI, although this will mess up the legend.

**Comment by mcr222** [comment] 2015-01-26 17:05
Is there any way of making the default behavior of missing points as null? Currently missing points in a line chart are ignored and chart connects them with a line.

With the example, I would like the black line behave as the blue line:
http://jsfiddle.net/Ld7vxxns/

Thanks!

**Comment by highslide-software** [comment] 2015-01-27 09:10
@mr222 Highstock has this feature. You can set the `gapSize` in terms of multiples of the distance between the two closest points, and Highstock will treat it as a gap: http://jsfiddle.net/highcharts/Ld7vxxns/1/

**Comment by mcr222** [comment] 2015-01-28 17:05
Cool! That works for non-stacked charts and stacked charts without filled area, very useful.

Just missing stacked area case: http://jsfiddle.net/Ld7vxxns/2/

thanks a lot!

**Comment by onemenny** [comment] 2015-02-03 10:31
+1 i thinks that null values should not be treated as zero and be ignored altogether

**Comment by thedarkdestructor** [comment] 2015-03-26 13:36
Hi. We are also having this issue and it is quite critical for us: customers complain about this strange behavior. I have created two fiddle to reproduce an example of the problem (they are similar to the one posted by the other users). The first one http://jsfiddle.net/6vbque4y/ and the second one http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/area-missing/ .

The use of connectNulls only hide the null points at the end of the graph. Any ETA, news about this issue?

**Comment by KacperMadej** [comment] 2015-03-27 11:00
Possible workaround: use zones with color 'none'
Example: http://jsfiddle.net/eghjj4be/1/

**Comment by blacktail** [comment] 2015-04-15 03:11
Hey, Guys, I have written a plugin for resolving this issue, you can try this:
https://github.com/blacktail/highcharts-stack-null

**Comment by karellm** [comment] 2015-04-29 13:29
@highslide-software can we expect a resolution for this soon? It's been almost 2 years now and is apparently blocking more and more people.

**Comment by highslide-software** [comment] 2015-04-30 07:04
I strongly regret that... Twice we have set in resources for finding a
final solution, but both times it created new problems. We will try to work
through this as soon as possible.​

**Comment by thedarkdestructor** [comment] 2015-04-30 16:11
It would be greatly appreciated.

**Comment by japepper88** [comment] 2015-05-04 09:26
Im also having this as a problem. I guess at the end of the day if there are two seperate ideas about this behaviour, then a flagged option to select desired behaviour would solve this problem without you having to decide what is right or wrong.

**Comment by highslide-software** [comment] 2015-05-04 12:24
I've done some more work on this project now. See http://jsfiddle.net/highcharts/esuqko5v/2/. When `connectNulls` is true and the area series is stacked, we can't simply connect the line to the next level, because it will give the wrong impression of the intermediate data series. So we treat the null as a zero, expect the graph line itself is broken and the marker is missing. Please let me know what you think. 

The only cases I can see where we could make it behave like a line series, is where a stack consists of only null values, or there are not nulls below the series.

**Comment by onemenny** [comment] 2015-05-04 13:02
@highslide-software IMO I disagree with your approach, when there are null values they shouldn't be treated as zero nor be connected to the next level.
Consider that you have a chart with scale (min point value) > 1bil - setting null to zero will cause the series to not be readable…

**Comment by highslide-software** [comment] 2015-05-04 13:32
@onemenny Keep in mind that connectNulls is false by default, so the _default behaviour_ will be this: http://jsfiddle.net/highcharts/esuqko5v/5/. However, as you can see from the discussion above, there are cases where our users want null points to be connected. And since interpolating a line across an underlying null point poses a logical problem (we don't know what value should be there), my suggestion is that in this case, we pinch the area down to zero width.

**Comment by karellm** [comment] 2015-05-04 15:04
@highslide-software I think it is a fair solution to the problem. I agree that with `connectNulls`, null could be treated as 0. 

I personnaly don't rely on it so as long as when it is set to false you do not draw a line to 0 as it seems to be the case in your last example, it would work for me!

**Comment by thomdask** [comment] 2015-05-04 15:06
I would consider the proposed solution acceptable

**Comment by raghits** [comment] 2015-05-14 04:45
@highslide-software Thanks for pointing this out to me. This seems like acceptable solution. When is this expected to be part of a release?

**Comment by highslide-software** [comment] 2015-05-15 10:39
We're currently working on it. The only remaining problem now is null
points in stacked areasplines. If we are able to work that out, this should
be released within some weeks.​

**Comment by japepper88** [comment] 2015-06-11 08:20
Any update on this?

Theres also still the issue of null being rendered as 0 (without the tooltip) on stacked area too (see below)


![screen shot 2015-03-11 at 10 41 05](https://cloud.githubusercontent.com/assets/11678092/8102777/235d0876-1023-11e5-83e0-46ae4110fc61.png)

**Comment by envision** [comment] 2015-10-03 15:20
Problem verified with Highstock 2.1.5 / Highcharts 4.1.5

![nullaszero](https://cloud.githubusercontent.com/assets/1790545/10263562/5a53ded6-69fb-11e5-9779-1425e883ab53.jpg)

**Comment by envision** [comment] 2015-11-22 10:35
Problem still exists in 4.1.9 / 2.1.9 – where's the fix? Please reopen this issue @highslide-software

**Comment by envision** [comment] 2015-11-22 10:39
Areaspline:

![nayttokuva 2015-11-22 kello 12 36 12](https://cloud.githubusercontent.com/assets/1790545/11323226/076008d4-9116-11e5-872f-30a20b2e6b26.jpg)

Area:

![nayttokuva 2015-11-22 kello 12 37 51](https://cloud.githubusercontent.com/assets/1790545/11323234/0d7eb4ea-9116-11e5-88f5-0d1da106c09f.jpg)

**Comment by karellm** [comment] 2015-11-22 14:53
@envision The issue is not close. 

That said I'm really confused that more than 2 years later it is not fixed, especially with the attention this issue is getting.

**Comment by jenoe** [comment] 2015-11-22 21:21
@karellm i agree
it is definitely an issue for us here too for a big project.

**Comment by envision** [comment] 2015-11-22 21:31
Oh, you are right @karellm – all the more reasons to get it fixed.

We have now about 12 - 14k lines of chart configurations. As area looks better than arespline on some uses, we have gone to lengthy hacks with adding several other series to circumvent this issue like hiding series behind black "gap series" – but it only works when there is no grid behind.

(Another issue which has needed circumventing is that when having a line series, if there are null values before and after a point, it won't be drawn! If anyone knows an official way around that one we would be grateful to hear. We have created another scatter series for such lone wanderer points.)

**Comment by karellm** [comment] 2015-11-22 23:41
@envision AFAIK there is no official way to do that. We structure our time series as arrays of objects: `[{x:x, y:y, marker: true}]`. It gives us full flexibility and most importantly the option to show a marker if the data point is surrounded by two null values.

**Comment by sebastianbochan** [comment] 2016-01-05 11:19
Seems that this kind of chart http://jsfiddle.net/bbs3buc0/3/ is also printed incorrectly.

**Comment by japepper88** [comment] 2016-01-05 12:00
@envision, @karellm - I also cannot believe this issue is still outstanding and with little acknowledgement.. 

Considering the price of this software at 'OEM' level it really is about time this issue was properly fixed. 

We also have a product dependant on HighCharts and at the moment it's simply misleading to represent null and zero in the same manner. We are having to use a number of hacks to circumvent this and display the data properly..

@TorsteinHonsi - do you have any plans or information regarding this issue? or are you still happy to pretend it doesn't exist?

**Comment by TorsteinHonsi** [comment] 2016-01-06 08:53
@japepper88 Thanks for pushing. Just want to remind you it currently works like in Excel. But I'll see what we can do with the issue. As I commented above, the remaining issue now is null values in areasplines, but we shouldn't let that stop us.

**Comment by TorsteinHonsi** [comment] 2016-01-06 11:52
Just to sum things up, we have a brach, `nosegments`, where we do development on this issue. The changes are so deep that I haven't had the guts to merge it into the master yet, but it's probably about time now. 

Summing up some of the latest comments above:

@japepper88, @envision: Your charts will now look something like this: http://jsfiddle.net/highcharts/z870x3ne/

> As area looks better than arespline on some uses, we have gone to lengthy hacks with adding several other series to circumvent this issue like hiding series behind black "gap series"

With the current Highcharts version (v4.2.1), you can add two prototype properties to make the area stack like the areaspline: http://jsfiddle.net/highcharts/z870x3ne/1/

> Another issue which has needed circumventing is that when having a line series, if there are null values before and after a point, it won't be drawn!

That's because a single point has no extent (it's a singularity), so consequently there is no area below it. This is a case where you need to enable the marker explicityly: http://jsfiddle.net/highcharts/z870x3ne/2/.

> Seems that this kind of chart http://jsfiddle.net/bbs3buc0/3/ is also printed incorrectly.

With the nosegments branch it prints like this: http://jsfiddle.net/highcharts/bbs3buc0/4/

**Comment by envision** [comment] 2016-01-06 12:03
Thanks @TorsteinHonsi !

About that singularity / single point issue. I was hoping you could add a new prototype property for drawing single points in a line but not all markers. That would give us more visual flexibility as you know – at times a straight solid line looks the best... Adding unnecessary markers there would be visual noise. Without such a feature we have needed to resort to lengthy hacks of adding another series with processed dataset... When it could be just one prototype property.

**Comment by TorsteinHonsi** [comment] 2016-01-06 12:18
What about extending the `drawPoints` method [like this](http://jsfiddle.net/highcharts/vo19ev8j/)?

PS: Maybe you should create a separate issue for this, as it is not related to the drawing of null points in areas.

**Comment by FelixWagner** [comment] 2016-01-06 13:34
@TorsteinHonsi 


>>    Seems that this kind of chart http://jsfiddle.net/bbs3buc0/3/ is also printed incorrectly.
>
> With the nosegments branch it prints like this: http://jsfiddle.net/highcharts/bbs3buc0/4/

This is not what I would expect this chart to look like.
Neither series has null values so they shouldn't be interrupted just because another series is more detailed. Series 1 is not missing a point. The existing points are enough to accurately describe the series... unless it's stacked. 
What I'd expect is a stacking of the lines/areas, not just the point values.

**Comment by TorsteinHonsi** [comment] 2016-01-06 13:46
Yes I agree. We would expect Series 1 to be draped over Series 2. What currently happens is that missing points are treated exactly like null points. What we are considering is to keep that, but to add an option, `connectNulls: 'interpolate'`.

**Comment by TorsteinHonsi** [comment] 2016-02-04 10:01
Fixed with Highcharts 4.2.2.

**Comment by sebastianbochan** [comment] 2016-02-05 09:34
Looks like cause an other issue: https://jsfiddle.net/wyx1k8hy/

**Comment by TorsteinHonsi** [comment] 2016-02-05 09:39
Filed at #5004

**Comment by sebastianbochan** [comment] 2016-02-17 13:50
Next demo: http://jsfiddle.net/ofwoq6j3/

**Comment by TorsteinHonsi** [comment] 2016-02-26 12:19
This is how it is intended - Series 1 is missing data for 03:39:30, so it is treated as a null point.

**Comment by FelixWagner** [comment] 2016-02-26 12:42
Well, here is a counter example: http://jsfiddle.net/ofwoq6j3/2/ - Series 1 is defined completely, it's definitely not missing points.

The additional x value in series 2 should not result in series 1 being interrupted.
The problem stems from specifying a stacking type. If that setting is removed, series 1 gets drawn as a single area.
This should not make such a severe difference when stacking series. At least there should be an interpolation option to make it look like http://imgur.com/zYmNUYB

**Comment by TorsteinHonsi** [comment] 2016-02-29 12:49
Yes, I see what you mean. Currently you can set [connectNulls to true](http://jsfiddle.net/highcharts/ofwoq6j3/3/), which makes the null points behave like zeroes except they don't have a line, and there is connectNulls = false, which gives the default behaviour. We should probably have something like `connectNulls: 'interpolate'` that would give the behaviour from your screenshot.

**Comment by NickolasLapp** [comment] 2016-07-25 22:09
+1 for the idea of a connectNulls: 'interpolate' option. My dataset has series which are sampled at different intervals and then parsed to .csv. Currently have to manually interpolate the data which leads to the appearance of higher sampling than is actually being done.

Would prefer to be able to specify an interpolation type (a really fancy implementation might look like http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.interpolate.html) so that we don't give the impression that we are sampling more often than we actually are, but the line maintains continuity.

**Comment by kindy-aa** [comment] 2016-08-23 08:50
create a new option "hideNulls" for area chart, demo: http://jsfiddle.net/vzcth45q/4/ .
screenshots:
![image](https://cloud.githubusercontent.com/assets/7110895/17885822/82cb8fb6-6951-11e6-9f9a-38f1508a32ea.png)

**Comment by carlosmorantes** [comment] 2016-09-08 12:43
Is this already solved? Despite that I have installed higcharts v4.2.4, when the area is stacked, it connects wrong the points:
 
![highcharts](https://cloud.githubusercontent.com/assets/12380268/18349597/6e396252-75d2-11e6-8a50-54be68087800.png)

**Comment by rchzh** [comment] 2016-09-08 13:15
http://imageshack.com/i/pnDxo2Okp in case I unselect serie that is above serie with NULL value, I can see this empty place... Does anybody else has this problem?

**Comment by andrei-gheorghiu** [comment] 2017-03-21 11:47
I'm not much of an expert and have only been using Highcharts for a short while. 

However, it looks to me like the most appropriate behavior would be not to map `null`/missing values as 0, but to not draw them at all. Or draw them invisible (color:transparent), if that makes more sense from a technical point of view. If they are drawn invisible, care must be taken in tooltips so the values shown for points with `null` values are printed in tooltip as `null`/empty string rather than the interpolated value from nearby existing points. 

Does this make sense?

**Comment by TorsteinHonsi** [comment] 2017-03-22 09:39
Yes, but in the current versions, null points are not drawn as zeroes: http://jsfiddle.net/highcharts/htas7o9v/

**Comment by sebastianbochan** [comment] 2018-10-15 07:54
It looks like the issue in `stacking` when yAxis is the logarithic type.

Demo:
- http://jsfiddle.net/49u3mtrs/

Related topic: 
- https://github.com/highcharts/highcharts/issues/9170

**Comment by smokir** [comment] 2019-07-23 17:46
Another example of incorrect `area` with `stacking: percent` and `connectNulls: false`: https://jsfiddle.net/q5bepj8x/ However it looks like markers are correct. Maybe it's possible to reuse their logic.
![Снимок экрана 2019-07-23 в 20 41 37](https://user-images.githubusercontent.com/2204174/61734555-ce50ba80-ad8a-11e9-8534-801a6c49a264.png)

**Comment by benjamin-feron** [comment] 2020-11-11 18:23
Can we know if there is someting new with this bug ?

As you can see, [this fiddle](https://jsfiddle.net/beufeu/1ujc9p6o/) highlights this issue.

**Comment by pawelfus** [comment] 2020-11-12 11:03
Hi @benjamin-feron - please check my comment in #14132 - your fiddle shows the same issue as #14132

**Closing this mega thread with many different issues. If anyone find an issue with area or areaspline stacking, please create a new one.**
**Thank you**

*Internal note:*
I'm closing the issue, since what was requested originally here is implemented (different behaviour for nulls, depending on the `connectNulls` option). Reopened issue with logarithmic axis.

**Closed by pawelfus** 2020-11-12 11:03 UTC
Labels: Type: Bug
