### ISSUE TITLE
Highmaps datalabel glow duplicating

### ISSUE THREAD

**Issue by findoo** [highcharts/highcharts#5929] opened 2016-11-04 10:05 UTC
Hi, 

We are noticing that the "glow" effect around data labels isn't rendering correctly upon export on maps. 

#### Expected behaviour
Data labels in exported image look identical to pre-exported version.

#### Actual behaviour
Data labels displaying graphical defect. 

#### Live demo with steps to reproduce
http://jsfiddle.net/w7r2c2h0/1/

![defect](https://cloud.githubusercontent.com/assets/3541918/20001916/25ba124e-a276-11e6-96b9-62d70aa83f0f.png)

Export burger menu -> Download PNG Image -> Exported image shows defect. 

#### Affected browser(s)
Mac OSX Chrome, not tested others.

**Comment by sebastianbochan** [comment] 2016-11-04 11:19
Duplicate of https://github.com/highcharts/highcharts/issues/5849

**Closed by sebastianbochan** 2016-11-04 11:19 UTC
