### ISSUE TITLE
Stacked Waterfall columns bug on window resize

### ISSUE THREAD

**Issue by rosegauthier** [highcharts/highcharts#14949] opened 2021-01-18 17:07 UTC
#### Expected behaviour
Data represented in Stacked Waterfall columns has high fidelity to data source, even after screen resize.

#### Actual behaviour
Stacked Waterfall columns are drawn correctly on page load, but on screen resize the columns re-render incorrectly. This only happens the first time, if the browser window is resized again the original (correct) columns are drawn. 

It seems that the Y axis scale changes, and the cascade/waterfall get misaligned from there.

#### Live demo with steps to reproduce

1. We have this issue in our application, but even in example jsfiddle from [documentation](https://api.highcharts.com/highcharts/plotOptions.waterfall)  this issue can be reproduced 
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/waterfall-stacked/
2. Notice stacking of columns and lines connecting columns
3. Resize browser window
4. Notice columns have adjusted and their position relative to each other has changed (for example, top of first column is no longer connected/aligned with bottom of second column)

Rarely, on resize the columns do this for a split second and then fix themselves.

#### Product version

Highcharts 8.2.2 (including highcharts-more module)

#### Affected browser(s)
Chrome, Firefox and Edge (all tested on Windows)

Thank you!

**Comment by khlieng** [comment] 2021-01-19 07:24
This appears to have been fixed on master since #14414: https://jsfiddle.net/msaL1xkf/

**Comment by KacperMadej** [comment] 2021-01-19 14:20
Hi @rosegauthier 

Thank you for reporting the problem.

The problem is fixed in the next release candidate code version. You could check and test it with the demo linked in the above comment. The issue will be closed as resolved. If you are still able to recreate the problem when using the pre-release code please add a live demo (you could start from editing the working demo) and the issue will be reopened.

**Closed by KacperMadej** 2021-01-19 14:20 UTC

**Comment by rosegauthier** [comment] 2021-01-19 14:23
great, thank you so much! The new demo appears to be working, will keep my eyes peeled for the next official release.
