### ISSUE TITLE
Area below single point

### ISSUE THREAD

**Issue by manusabarros** [highcharts/highcharts#17185] opened 2022-04-14 11:12 UTC
#### Expected behaviour
In an area chart, I want to be able to draw the area below the point when it's a single point.

#### Actual behaviour
No area is being rendered when the series has only one point.

##### Description
Hi. Is there a way to draw the area below the point when the series contains only that point? So the series' object it's something like:
```
{
    series: [
        {
            data: [1],
            type: "area",
        },
    ],
}
```

The data array can contains other points but a particular point is always separated from the others by nulls, eg:
`[5, 3, 12, null, 7, null, null, 9, 15]`
(In this case 2 areas are being rendered, one between the first element (5) and the third (12) and another area between the 8th element (9) and the 9th (15), but no area below the 5th (7))

I understand that because it's a single point, an area shouldn't appear, but I was thinking on adding padding or something to make the area visible. Is that possible?

**Comment by raf18seb** [comment] 2022-04-15 08:59
Hi @manusabarros, thanks for creating the ticket!

I'm afraid this option is not available and will not be added to the core.
However, you can preprocess your data and add fake points to imitate that area, see a simple demo with fake points added: https://jsfiddle.net/BlackLabel/9u4earyx/

Closing as not a bug. In case of any further similar questions (not bugs), please contact us on one of our dedicated support channels. More info: https://www.highcharts.com/blog/support/

**Closed by raf18seb** 2022-04-15 08:59 UTC
