### ISSUE TITLE
Doesn't recognize parent div container's width if there are more than one parent divs

### ISSUE THREAD

**Issue by adam1x** [highcharts/highcharts#5118] opened 2016-03-12 06:49 UTC
When a chart has more than 1 parent divs, it seems unable to determine its correct size and overflows out of its parent container. [See it here on JSFiddle](https://jsfiddle.net/axis1egend/Lq5jxz1z/). I modified [this JSFiddle](https://jsfiddle.net/highcharts/9Lvvyvbk/) from the developers and broke it.

Please fix and thanks!

**Comment by pawelfus** [comment] 2016-03-14 10:20
This is caused by using percentage width in the hidden container. In that case browser returns width = 0px, so Highcharts uses default width (600px). Duplicate of #1979

**Workaround:**

Use `chart.reflow()` when showing the container.

**Closed by pawelfus** 2016-03-14 10:20 UTC
