### ISSUE TITLE
Timeseries column chart not showing last label

### ISSUE THREAD

**Issue by govinda18** [highcharts/highcharts#17525] opened 2022-07-20 12:24 UTC
#### Expected behaviour
All the xaxis labels should be displayed

#### Actual behaviour
The last label is missing - not sure if there is something incorrect on the data

#### Live demo with steps to reproduce
http://jsfiddle.net/0vu8ozp4/

#### Product version
Highstock 10.2.0

#### Affected browser(s)
Chrome

**Comment by pawellysy** [comment] 2022-07-21 15:52
Hi @govinda18, thanks for contacting us with your question!
The last label is missing because your data points are in uneven positions. The min and max values depend on your first and last point and the labels on the xAxis are designed to have even values, like the beginning of the day, month, year, etc. 

Closing since this is not a bug. 


PS: GitHub is our issues/features tracker, so please get in touch with us on dedicated support channels with these kinds of questions. Thanks!
https://www.highcharts.com/blog/support/

**Closed by pawellysy** 2022-07-21 15:52 UTC
