### ISSUE TITLE
Hover failing on mouse move

### ISSUE THREAD

**Issue by neo87cs** [highcharts/highcharts#5491] opened 2016-07-15 07:53 UTC
Hover should be  activated all the times the mouse pass trought a point but, with sticky tracking enabled or disabled, but if the mouse pointer is moving slowly near a point, the graph begin to lost the hover effect. This behaviour affect even the point listener, because while the hover is lost, click will not work to open the tooltip

A simple fiddle (i found it over internet) will demonstrate what i am meaning http://jsfiddle.net/neo87cs/vh2uer6n/

The use case we are using is the same: disabled default tooltip and it will be shown only when a point is clicked.

**Comment by oysteinmoseng** [comment] 2016-07-15 08:55
Thank you for reporting.

The behavior I'm seeing is that hovering over the same point twice fails when tooltip is disabled, and `stickyTracking` is off. Is this what you are referring to?

http://jsfiddle.net/whutocct/

**Comment by neo87cs** [comment] 2016-07-15 08:58
Thanks for your fast reply and sorry for my worst english. Yes, you got the point, the log shown how Highcharts lost mouse tracking over points

**Comment by pawelfus** [comment] 2016-07-15 09:19
**Workaround:**

Clear `chart.pointer.prevKDPoint` in `mouseOut` event, for example: http://jsfiddle.net/vh2uer6n/2/

**Comment by neo87cs** [comment] 2016-07-15 14:30
The workaround seems to work pretty good, but sometimes can be noticed some little bad behaviors. I tried to use workaround even in Point->MouseOut listener, but i got a big regression with

**Comment by pawelfus** [comment] 2016-07-18 07:57
@neo87cs - you message was cut, could you update your post? Anyway, `point.events.mouseOut` works for me too: http://jsfiddle.net/vh2uer6n/5/ (after small modification of course).

**Comment by pawelfus** [comment] 2016-10-17 12:02
It should be fixed in 5.0.0 version: http://jsfiddle.net/e0m1pgLh/ - @neo87cs could you confirm it also works for you?

**Comment by Avuthless** [comment] 2017-02-23 15:34
This is still an open issue. Can be seen in last fiddle provided by @pawelfus

**Comment by pawelfus** [comment] 2017-02-23 15:37
Thanks for pointing this out! It used to work in 5.0.0: http://jsfiddle.net/e0m1pgLh/2/

**Comment by Avuthless** [comment] 2017-02-23 15:39
Yes i can confirm that in version 5.0.0 it was OK

**Comment by Avuthless** [comment] 2017-02-23 15:42
Few notes: If you hover between different points it is OK. Also if you hover outside the graph area before coming back to your last hovered point it is also OK.

**Comment by KacperMadej** [comment] 2017-04-12 14:29
Seems to be working since version 5.0.8 - http://jsfiddle.net/e0m1pgLh/3/
and is working in the current (5.0.10) - http://jsfiddle.net/e0m1pgLh/4/

Please reopen in case of regression.

**Closed by KacperMadej** 2017-04-12 14:29 UTC
Labels: Bug
