### ISSUE TITLE
Stacked area chart with multiple series having negative and positive values in each series not plotting properly

### ISSUE THREAD

**Issue by ismusidhu** [highcharts/highcharts#8517] opened 2018-06-22 15:32 UTC
Scenario-
Stacked area chart.
Multiple series.
Each series may have positive as well as negative values  

#### Expected behaviour
For a given timestamp or an X axis point, all series having negative value on that point, should start stacking from zero separately than all series having positive value on that point. 

#### Actual behaviour
Highcharts attempts to stack negative values as well as positive values above each other. 

#### Live demo with steps to reproduce
https://codesandbox.io/s/o1v968m76

#### Product version
Highstock JS v6.1.0 (2018-04-13)

#### Affected browser(s)
Reproduces on Chrome and Safari. But should be unrelated to browser

**Comment by ismusidhu** [comment] 2018-06-22 17:19
[I was able to workaround](https://codesandbox.io/s/13rxlqryn3) it with the help of [this stackoverflow answer](https://stackoverflow.com/a/41107037/148271), though in my workaround at June, 19 14:40 and June, 19 16:20, there is a single negative point of Con with positives before and after it. This can cause issue when you have multiple series of such kind i.e. which one to stack above the other will be a question.

**Comment by pawelfus** [comment] 2018-06-25 09:30
Hi @ismusidhu 

Thanks for reporting the issue. You are right, our stacks are rendered where the previous one has ended. Solution, to render chart the same as for example Excel is to use separate stacks (separate negative and positive data). Column series does it out of the box: https://codesandbox.io/s/zqy03kmx0p

It's actually a duplicate of #5671 - area and areaspline are similar series sharing the same stacking logic.

**Comment by pawelfus** [comment] 2018-06-29 09:55
Closing as duplicate of #5671.

**Closed by pawelfus** 2018-06-29 09:55 UTC
