### ISSUE TITLE
https://jshare.com.cn/temp/9CGGvw There is no negative value in the series data, but the value of -5 is displayed on the Y-axis

### ISSUE THREAD

**Issue by weixingcai** [highcharts/highcharts#13116] opened 2020-03-11 07:08 UTC

**Comment by weixingcai** [comment] 2020-03-11 07:08
There is no negative value in the series data, but the value of -5 is displayed on the Y-axis

**Comment by sebastianbochan** [comment] 2020-03-11 09:26
Hi @weixingcai,
Im closing the ticket as duplicate of https://github.com/highcharts/highcharts/issues/13117.

ps. Please do not report the same problem multiple times.

**Closed by sebastianbochan** 2020-03-11 09:26 UTC
