### ISSUE TITLE
Incorrect position of stackLabels in a bar chart

### ISSUE THREAD

**Issue by morganfree** [highcharts/highcharts#8282] opened 2018-05-04 13:04 UTC
#### Actual behaviour
Stacklabels are misplaced in a bar chart. It is a regression bug between 6.0.7 and 6.1.0 versions.

#### Live demo with steps to reproduce
Open the fiddles and see the differences between stack labels positions.
6.1.0: http://jsfiddle.net/vt1rLopb/
6.0.7: http://jsfiddle.net/vt1rLopb/1/

**Comment by pawelfus** [comment] 2018-05-04 17:02
Duplicate of #8187 - already fixed on master branch: http://jsfiddle.net/BlackLabel/vt1rLopb/2/

**Closed by pawelfus** 2018-05-04 17:02 UTC
Labels: Regression
