### ISSUE TITLE
Ticks missing in Histogram

### ISSUE THREAD

**Issue by AlissonRS** [highcharts/highcharts#15911] opened 2021-06-16 07:59 UTC
#### Expected behaviour
The ticks should be displayed all the way to the end of the histogram axis.

#### Actual behaviour
As you can see, the ticks on the bottom stop in 27k, even though the last bin ranges from 27699 to 30777. It should display at least up to 30k as there is enough space in the axis.

#### Live demo with steps to reproduce
https://jsfiddle.net/fkh4cen1/1/

#### Product version
Highcharts JS v9.1.1 (2021-06-03)

#### Affected browser(s)
Chrome

**Comment by KacperMadej** [comment] 2021-06-16 18:55
Hi @AlissonRS 

Thank you for reporting the problem.

Minimal demo: https://jsfiddle.net/BlackLabel/5pnvhxgu/1/

**Comment by AlissonRS** [comment] 2021-06-16 21:06
Hi @KacperMadej 

Thanks, I have updated the minimal demo, just added the data array, please find below.

https://jsfiddle.net/rhbqzLxd/

In addition, even if you provide the "binsNumber" in the histogram series, you'll notice the ticks will always be missing over the last bin column for any binsNumber.

https://jsfiddle.net/rhbqzLxd/1/

**Comment by KacperMadej** [comment] 2021-06-18 13:34
Thank you for the additional demos. The problem is visible in every one of them.

My minimal demo is already showing the problem you have reported, so I am not sure if adding anything there is necessary. Surely doesn't seem required to me because the problem is visible, but in case I have missed anything please let me know.

**Comment by AlissonRS** [comment] 2021-06-18 13:58
@KacperMadej you're right, the problem is visible even in your minimal demo. I just provided other examples to show this happens with different scenarios.

**Comment by raf18seb** [comment] 2021-06-22 09:51
Closing as a duplicate of https://github.com/highcharts/highcharts/issues/12933

**Closed by raf18seb** 2021-06-22 09:51 UTC
Labels: Type: Bug
