### ISSUE TITLE
Data points with uneven time distribution will not display markers

### ISSUE THREAD

**Issue by usernameGao** [highcharts/highcharts#16655] opened 2021-11-16 05:35 UTC
#### Expected behaviour
 The x-axis is a time line graph. When the time of the data points is not evenly spaced, the marker can be adaptively displayed 
 according to the amount of data.
       
#### Actual behaviour
The x-axis is a time line chart. When the time of the data points is not evenly spaced, no matter the number of data points, the  marker will not be displayed.

#### Live demo with steps to reproduce
https://jsfiddle.net/fom1xvpb/2/

#### Product version
"highcharts": "^7.2.1"

#### Affected browser(s)
Chrome 95

**Comment by raf18seb** [comment] 2021-11-16 15:49
Hi @usernameGao!

I think you're looking for a [marker.enabledThreshold](https://api.highcharts.com/highcharts/plotOptions.spline.marker.enabledThreshold) option.

I'm closing the ticket, but feel free to correct me or reopen if you meant something else.

**Closed by raf18seb** 2021-11-16 15:49 UTC

**Comment by usernameGao** [comment] 2021-11-17 06:36
Thanks for your answer. I tried it. You mentioned enabledThreshold, but I don't think it can solve my problem. In my demo, the number of points on the two lines is the same. Why does one show the style of dots and the other is not displayed? How to make their styles always consistent. I have tried to manually disable or enable the marker according to the style of the most numerous lines, but when I use the reset zoom function, the style is not adaptive. Is there a better solution? Thanks Rafał

**Comment by raf18seb** [comment] 2021-11-22 16:19
@usernameGao,

In the first series, the points are evenly spaced every each 10.000 milliseconds on the xAxis:
```js
for (i = -19; i <= 0; i += 1) {
    data.push({
        x: time + 10000 * i,
        ...
```

However, in the second series, they are not evenly spaced and the distance between the 2 closest points (for i=0 and i=-1) is only 500 milliseconds:
```js
for (i = -19; i <= 0; i += 1) {
    data.push({
        x: time + 500 * (i * i),
        ...
```

The API for `enabledThreshold` says:
```The number indicates the horizontal distance between the two closest points in the series...```
Where in the first series that distance is `10000` and in the seconds series only `500`.
That's why markers are visible in the first series, but hidden in the second.

To make all markers visible, you can set the `enabledThreshold` to `0` in `plotOptions`, see updated demo: https://jsfiddle.net/BlackLabel/6v4bpj9t/

**Comment by usernameGao** [comment] 2021-11-23 05:24
@raf18seb
Thank you for your reply. Setting enabledThreshold to 0 can indeed keep the two styles the same (both display points), but its function is equivalent to forcing the marker attribute to be enabled. This will cause more data points, it will still display points, which will be ugly , May also have an impact on performance.

Like this:
https://jsfiddle.net/pLm92jkr/

Thanks。

**Comment by raf18seb** [comment] 2021-11-24 10:23
@usernameGao,

You can set the `enabledThreshold` to any number you want. By default it's `2`. You can set it to, e.g. `0.2` - then, in the first demo, all markers will be visible, however, in the last demo you provided, when the markers are too close, they will be hidden.

You don't have to set it on `plotOptions` for all the series together, but you can set it on the series level with a different `enabledThreshold` value for each series.

With the above, you have full control and you can show/hide your markers whenever you like depending on the data you have.
If you don't have any further questions, I would like to close the ticket as it's not a bug and it's resolved.

**Comment by usernameGao** [comment] 2021-11-26 02:41
@raf18seb
If my data is static, such a solution is definitely feasible, but my data is dynamically refreshed. How can I change the style according to the current amount of data?

Thanks

**Comment by raf18seb** [comment] 2021-11-29 20:07
@usernameGao,

You can calculate the `enabledThreshold` depending on your data and all other factors, and update its value using the `update` method, e.g.
```js
series.update({
    marker: {
        enabledThreshold: value
    }
});
```

GitHub is our bugs/features tracker only. As the issue you reported is not considered a bug, can be controlled by the official API option and is closed, your questions are more of the support nature now.
Could you please contact our support on one of our dedicated support channels? Thank you for understanding!
https://www.highcharts.com/blog/support/

**Comment by usernameGao** [comment] 2021-11-30 08:32
OK.

raf18seb,
Thank you very much.
