### ISSUE TITLE
highcharts.js (line 184, col 192) TypeError: T[ha] is undefined

### ISSUE THREAD

**Issue by shishir99111** [highcharts/highcharts#5002] opened 2016-02-05 07:38 UTC
```js
...function(a){var b=this.chart;if(!q(ha)||!T[ha].mouseIsDown)ha=b.index;a=this.nor...
```
checkbox not functioning properly.Not responding while trying to check or uncheck for some values. showing error on mouse hover to xLabel.
```js
 $scope.Display = function(value, xLabel, xAxisName) {
        for(i=0 ; i< xLabel.length ; i++)    
            $scope.checkboxValue[i] = true;
        var a = 0;
        $scope.chartConfig_StarRate = {
            options: {
                legend: {
                    enabled: true
                },
                chart: {
                    type: 'bar'
                },
                xAxis: {
                    tickColor: '#fff',
                    categories: xAxisName,
                    labels: {
                        style: {
                            width: '80px',
                            'min-width': '80px',
                            'text-align': 'right',
                        },
                        series: {
                            pointWidth: 50//width of the column bars irrespective of the chart size
                        },
                        formatter: function() {
                            // if(a==value.length){
                            //     a=0;
                            // }
                            // console.log("a value")
                            // console.log(a)

                            // if($scope.data[a++]){
                            //     if($scope.ExclamationMFlag[a]){
                            //         var val = a -1;
                            //         return '<a href="" style="cursor:pointer;" ng-click=ClickIndex('+a+','+'"'+$scope.cateArr[val]+'"'+')>'+this.value+'</a>';
                            //         return this.value;
                            //     }else{
                            //         return '<a href="" ng-click=ClickIndex('+a+','+'"'+$scope.cateArr[a]+'"'+')>'+this.value+'</a>';
                            // //         return this.value;
                            //     }
                            // }else{
                            //     var val = a -1;
                            //     return '<a href="" style="cursor:pointer;" ng-click=ClickIndex('+a+','+'"'+$scope.cateArr[val]+'"'+')>'+this.value+'<sup class="ExClamationMark"></sup></a>';
                            // //     return this.value+'<sup class="ExClamationMark"></sup>';
                            // }
                            if (a == $rootScope.ExclamationMFlag.length) {
                                a = 0;
                            }
                            if ($rootScope.ExclamationMFlag[a++]) {
                                // if($scope.AssessmentDtl.control_seq == 0){
                                // return this.value;
                                var val = a - 1;
                                // return this.value+'<sup class="ExClamationMark"></sup>'+$scope.AssessmentDtl.cover_seq;
                                return '<input type="checkbox" ng-checked="'+$scope.checkboxValue[val]+'" value="h'+val+'" id="check'+val+'" onclick="checkthis('+val+')"><a href="" title="' + this.value + '" style="cursor:pointer;color:#606060;" ng-click=ClickIndexs(' + a + ',' + '"' + $scope.cateArr[val] + '"' + ')>' + this.value + '</a>';

                                // }else{
                                // return this.value+'<sup class="ExClamationMark"></sup>'+$scope.AssessmentDtl.cover_seq;
                                // return '<a href="" style="cursor:pointer;" ng-click=ClickIndexs('+a+','+'"'+$scope.cateArr[a]+'"'+')>'+this.value+'</a>';

                                // }
                            } else {
                                // return this.value;
                                var val = a - 1;
                                if ($scope.AssessmentDtl.control_seq) {
                                    return '<input type="checkbox" ng-checked="'+$scope.checkboxValue[val]+'" value="h'+val+'" id="check'+val+'" onclick="checkthis('+val+')"><a href="" title="' + this.value + '" style="cursor:pointer;color:#606060;" ng-click=ClickIndexs(' + a + ',' + '"' + $scope.cateArr[val] + '"' + ')>' + this.value + '<sup class="ExClamationMark"></sup></a>';
                                } else {
                                    return '<input type="checkbox" ng-checked="'+$scope.checkboxValue[val]+'" value="h'+val+'" id="check'+val+'" onclick="checkthis('+val+')"><a href="" title="' + this.value + '" style="cursor:pointer;color:#606060;" ng-click=ClickIndexs(' + a + ',' + '"' + $scope.cateArr[val] + '"' + ')>' + this.value + '</a>';
                                }
                            }
                        },
                        useHTML: true
                    },
                },
                // tooltip: {
                //     followPointer: true
                // },
                tooltip: {
                    followPointer: true,
                    formatter: function() {
                        return this.point.category + '<br/> Rating : ' + parseInt(this.point.y);
                    }
                },
                // plotOptions: {
                //     column: {
                //         stacking: 'normal'
                //     }
                // }
                plotOptions: {
                    column: {
                        stacking: 'normal',
                        pointPadding: 0.2,
                        size: '95%',
                        borderWidth: 0,
                        events: {
                            legendItemClick: function() {
                                return false;
                            }
                        }
                    },
                    allowPointSelect: false,
                },
            },
            series: [{
                    data: value,
                    name: 'Areas',
                    color: $scope.Client_Color /*'#6cccfc'*/,
                    allowDecimals: false
                }],
            title: {
                text: null,
                style: {
                    display: 'none'
                }
            },
            yAxis: {
                title: {
                    text: 'Rating'
                },
                tickInterval: 1,
                max: 10,
                min: 0
            },
        };
        $timeout(function() {
            var element = document.getElementById("chart1");
            $compile(element)($scope)
        });
        $scope.DisplayHighchart = true;
    }
 ```

**Comment by TorsteinHonsi** [comment] 2016-02-05 07:55
Thanks for reporting, but for us to be able to reproduce we need more information and steps to reproduce. Also, your configuration has some code that looks like React.

**Comment by jon-a-nygaard** [comment] 2016-04-26 09:31
Closing this issue due to: We are not able to reproduce the issue, and it is pending reply. 
Should anyone have further information on this issue, please add a comment and reopen.

**Closed by jon-a-nygaard** 2016-04-26 09:31 UTC
Labels: Cant reproduce, Pending reply
