### ISSUE TITLE
Drilldown sometimes called twice in stacked column chart

### ISSUE THREAD

**Issue by hcdaj3255** [highcharts/highcharts#15937] opened 2021-06-18 16:22 UTC
#### Expected behaviour
In a stacked column chart where the x-axis labels **and** the columns are drillable, I expect event drilldown() to be called once per click, regardless of whether I clicked the label or the column.

#### Actual behaviour
When I click a column, the drilldown event is called once but when I click the x-axis label, the event is called twice. 

Am I missing an option so that drilldown() is called only once per click rather than once per series (which is what I suspect is happening)?

#### Live demo with steps to reproduce
[Demo in jsFiddle](https://jsfiddle.net/L1bjy0hz/1/)

Open the jsFiddle console or browser console to be able to see the console output, then click anywhere in a column. Notice the message is printed once. Now click any x-axis label (e.g. Red, Orange, Yellow, et al) and notice the message from within drilldown() is printed twice. I'm guessing it's called once per series. Not sure if this is a bug or if I'm missing a highcharts option setting.

#### Product version
Highcharts 9.1.1

#### Affected browser(s)
Tested in Chrome

**Comment by raf18seb** [comment] 2021-06-22 11:48
Hi @hcdaj3255,

thank you for posting an issue.

You are right, it's not a bug and it's intended - it's called twice because there are 2 points each from separate series in a category you are clicking. I renamed your points so you can see a difference now.
When clicking on a point, you drilldown only into one series. When clicking on the xAxis category label, you drilldown into all series from this category.

If you would like to fire an event only once, you can fire it e.g. in the `H.Axis.prototype.drilldownCategory` method like in this demo: https://jsfiddle.net/BlackLabel/7bh5ekua/ (I added a path to a new `customDrilldown` in chart's options.

Please, check the console - you will find more info there.
I am closing the ticket as it's not a bug.

**Closed by raf18seb** 2021-06-22 11:48 UTC

**Comment by hcdaj3255** [comment] 2021-06-23 13:53
That makes sense to me, especially since in your example the series are not stacked. The two series are visually treated separately. But in my case, the two series are stacked, the tooltip is shared, and stacking = "percent", meaning the context of each column in the chart depends on each series being read with the other. In other words, they don't mean much by themselves. In my opinion, when stacking = "percent" is applied, drilldown() should be called only once by default. Or at the very minimum, there should be an option to call drilldown() only once even when click occurs on the column.

**Comment by raf18seb** [comment] 2021-06-24 08:44
@hcdaj3255, yes, that option might be good for you in case of `percent` stacking. But it still fires an event twice (on each series separately), so the solution here would be using the above custom event I provided.
