### ISSUE TITLE
yAxis update breaks the scrollablePlotArea

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#14323] opened 2020-10-08 13:52 UTC
Like in the title - the yAxis update breaks `scrollablePlotArea` feature.

#### Live demo with steps to reproduce

Demo: https://jsfiddle.net/BlackLabel/a367g9uv/

#### Product version

Highcharts JS v8.2.0 (2020-08-20)

**Comment by pawelfus** [comment] 2020-10-12 09:56
Closing as duplicate of #8862

**Closed by pawelfus** 2020-10-12 09:56 UTC
Labels: Type: Bug
