### ISSUE TITLE
Wrong pointer position after transform scale

### ISSUE THREAD

**Issue by itsvodoo** [highcharts/highcharts#11975] opened 2019-09-16 11:19 UTC
Scaling a rendered chart will not update the pointer/tooltip position. Hovering over data points will show wrong information based on different (unscaled?) data points. The more right of the chart you try to hover the worse the problem gets. Problem doesn't appear in Highcharts v6.2.0 and also doesn't seem to affect the legend.

#### Live demo with steps to reproduce
https://jsfiddle.net/v9375tuj/

1. Render chart
2. Scale any parent
3. Try to hover over the rightmost data point

#### Product version
Highcharts v7.2.0

#### Workaround
render() after any scaling

**Comment by pawelfus** [comment] 2019-09-16 11:24
Thanks for reporting the issue @itsvodoo 

Tried v6.2.0: https://jsfiddle.net/BlackLabel/6yo54Lwf/ - works the same as v7.2.0, do you agree?

@oysteinmoseng - FYI

**Comment by itsvodoo** [comment] 2019-09-16 11:51
You're right the example with v6.2.0 has the same problem as v7.2.0.

I've modified both versions to better illustrate the problem that I saw in a test project.

Works fine
v6.2.0 - https://jsfiddle.net/vg0my7bj/1/

Pointer is all over the place
v7.2.0 - https://jsfiddle.net/vg0my7bj/

**Comment by oysteinmoseng** [comment] 2019-09-17 13:59
The issue seems to be that you are setting scaling on the container after the chart has been created. You can either set the scaling before creating the chart, or force the chart to update. To update the internal scale handling in Highcharts, try running `chart.render()` after setting the scale. Example: https://jsfiddle.net/a93fpsn8/

I am closing this as not a bug for now, as there is not much we can do in Highcharts about this. Feel free to comment and request a reopen if you still encounter problems.

Internal note: We might consider calling `chart.updateContainerScaling()` in `chart.reflow()`, to let users deal with only one function to call after making modifications to the DOM.

**Comment by kzoon** [comment] 2020-06-30 11:53
@sebastianbochan, I think this issue should be reopened. In https://github.com/highcharts/highcharts/issues/11329 Highcharts provided a drop-in on 6.2.0, which **_DID_** handle changes in transform - scale after render correctly:

The 6.2.0 + drop-in  fiddle: http://jsfiddle.net/kzoon/eq6y0sgr/

In 7.2.1 and higher versions without the drop-in setting the scale afterwards is no longer handled correctly:
http://jsfiddle.net/kzoon/5npf3wLd/

So, Highcharts can handle scale changes after rendering, but somehow the functionality got changed when it was included in the main Highcharts code. My knowledge of your code is insufficient to pinpoint the problem, but you probably can :-)

I have already installed versions at customers with 7.2.1, so again I am anxious to solve/work around this issue.

**Comment by pawelfus** [comment] 2020-06-30 12:00
For now it's necessary to call `chart.render()` after changing the transformation of the chart's container: http://jsfiddle.net/BlackLabel/309crzep/

Reopening as requested. FYI @oysteinmoseng

**Comment by kzoon** [comment] 2020-06-30 12:06
Thanks for reopening. 
I will try to call chart.render() as a workaround for now. But the tricky part for me is to get the transformation change event to the chart. The transformation change happens many levels higher in the DOM as a result of user interaction...

**Comment by oysteinmoseng** [comment] 2020-06-30 13:03
@kzoon The issue here is performance. For the drop in fix you link to, we are updating the scaling every time the tooltip moves. Because this calculation is relatively expensive (relying on `getBoundingClientRect`) this is not an optimal solution. The way it works now is that the calculation is only done on render.

Thoughts @TorsteinHonsi ? I think adding the calculation to `chart.reflow` would make sense as mentioned above, but for @kzoon's use case this won't make any difference.

**Comment by TorsteinHonsi** [comment] 2020-06-30 13:36
I agree checking the scale for each tooltip move may be too expensive, especially since this is an edge case. We do have similar considerations in the `chart.pointer.chartPosition`, that is cached once the mouse enters the chart, and voided when the mouse leaves. An approach like that would probably work for the scale too.

The cheapest solution, both in terms of file size and performance, may actually be to combine the two, so that `getChartPosition` returns an object including the scale. Then we can remove `chart.updateContainerScaling` and the `chart.containerScaling` cache.

```ts
interface ChartPositionObject {
    left: number;
    scaleX: number;
    scaleY: number;
    top: number;
}
```

**Comment by kzoon** [comment] 2020-06-30 13:39
I have the drop-in running at multiple customers, without any reports of performance degradation. But elsewhere that could be a consideration. Maybe  there are ways for not doing this calculation too often?

**Closed** 2021-01-05 14:15 UTC
Labels: Type: Undecided
