### ISSUE TITLE
flags on the left edge cut-off

### ISSUE THREAD

**Issue by jegli** [highcharts/highcharts#10260] opened 2019-03-05 16:39 UTC
#### Expected behaviour
When I place a flag on the first date in a chart with a datetime-axis, I expect the flag to be fully visible just like with the last date. As described in the [API allowOverlapX](https://api.highcharts.com/highstock/plotOptions.flags.allowOverlapX), the flags should be moved if there is enough space available.

#### Actual behaviour
The left half of the flag is cut-off.

#### Live demo with steps to reproduce
Please have a look at this example: https://jsfiddle.net/cop0t871/5/
I think the problem is that I use the shape 'circlepin' instead of 'flags'. Flags always take space towards the right. 'circlepin' and 'squarepin' don't. Thanks for looking into this issue. 👍 

#### Product version
Highstock JS v7.0.3 (2019-02-06)

#### Affected browser(s)
browser-independent

**Comment by sebastianbochan** [comment] 2019-03-06 08:50
Hi @jegli,
Thank you for reporting about the problem. The issue is known bug reported here: https://github.com/highcharts/highcharts/issues/9726, so Im closing this ticket to avoid duplicates.

**Closed by sebastianbochan** 2019-03-06 08:50 UTC
