### ISSUE TITLE
Highmaps (Geo) : legends are reset when zoom in/out

### ISSUE THREAD

**Issue by ii02735** [highcharts/highcharts#20428] opened 2024-01-11 22:57 UTC
#### Expected behaviour

When I deactivate legends and zoom in/out my map, I expect my legends' settings to be preserved.

#### Actual behaviour

My settings are reset every time when I zoom in/out : the legends I had deactivated are reactivated.

#### Live demo with steps to reproduce

I'm using the following example : https://www.highcharts.com/demo/maps/geoheatmap-orthographic
Which already have a jsfiddle link.

Steps to reproduce :

- I click on a legend to deactivate it

- I zoom in on my map

#### Product version
Highmaps JS v11.3.0

#### Affected browser(s)

All

**Comment by bm64** [comment] 2024-01-14 20:09
Hello @ii02735 and thanks for reporting the issue.

**Comment by oysteinmoseng** [comment] 2024-01-22 12:04
Closing as duplicate of https://github.com/highcharts/highcharts/issues/20441

**Closed by oysteinmoseng** 2024-01-22 12:04 UTC
Labels: Type: Bug, Product: Highcharts Maps, Type: Duplicate
