### ISSUE TITLE
Need Padding between Series Value for Data Labels

### ISSUE THREAD

**Issue by sachinmishra-gep** [highcharts/highcharts#12999] opened 2020-02-20 15:23 UTC
#### Expected behaviour
Hi,

We need the padding between the series datalabels as mentioned value dynamically for multiple series.
Could you please suggest how can we achieve it ?

#### Actual behaviour
There should be data labels for all the series values should be displayed without overlaping

![image](https://user-images.githubusercontent.com/39190638/74948410-4d41ca80-5422-11ea-97a4-3578dd2b4a8e.png)

#### Live demo with steps to reproduce

https://jsfiddle.net/nitapatil/1dmyz9k8/4/

#### Product version

Highcharts : 8.0.0
#### Affected browser(s)

@NitaPatil-GEP

**Comment by sebastianbochan** [comment] 2020-02-21 09:07
Hi @sachinmishra-gep,
Thank you for reporting. The issue is known problem which has been already reported here: https://github.com/highcharts/highcharts/issues/9376

Im closing the ticket as duplicate of https://github.com/highcharts/highcharts/issues/9376.

ps. you can use one of our limited workarounds:
- http://jsfiddle.net/menXU/6/
- http://jsfiddle.net/menXU/1/

**Closed by sebastianbochan** 2020-02-21 09:07 UTC
Labels: Type: Duplicate
