### ISSUE TITLE
API reference: the main search is not searching through classes

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#7239] opened 2017-10-06 13:58 UTC
#### Enhancement suggestion
Using the search input it's not possible to find chart.addSeries or series.addPoint. Classes tab is something new and searching there is not as easy. Maybe it would be possible to enable serach through all API reference?

#### Live demo with steps to reproduce
http://api.highcharts.com/highcharts/

**Comment by pawelfus** [comment] 2019-06-14 11:17
Closing as duplicate of #7882

**Closed by pawelfus** 2019-06-14 11:17 UTC
Labels: Product: Docs, Type: Enhancement
