### ISSUE TITLE
Misaligned Bar-Chart X-Axis Label (custom font + image) on first render

### ISSUE THREAD

**Issue by thplat** [highcharts/highcharts#16090] opened 2021-07-21 12:12 UTC
#### Expected behaviour
When using HTML Labels with a text (with an arbitrary custom webfont) + image the labels should be aligned on one line vertically across the x-axis when drawing the chart for the first time.

<img width="156" alt="Bildschirmfoto 2021-07-21 um 14 05 35" src="https://user-images.githubusercontent.com/6587997/126486119-dd969aa8-b3ad-434f-a079-86baf93c92cb.png">

#### Actual behaviour
The first render of the chart misplaces the labels randomly and the labels are not aligned to each other. On subsequent reloads, the labels are positioned correctly, when clearing the cache it occurs again. I assume it has something to do that a fallback font is used for the first time the labels are rendered and thus the size of the label different with the new font.

<img width="167" alt="Bildschirmfoto 2021-07-21 um 14 05 40" src="https://user-images.githubusercontent.com/6587997/126486136-9cfc401b-8372-4ee5-90ba-72316addd7ba.png">

#### Live demo with steps to reproduce
https://jsfiddle.net/hvd4g2zu/5/

- First page load: Labels are misaligned
- Reload: Labels are positioned correctly
- Clear Cache + Refresh (CMD/CTRL + Shift + R): Labels are misaligned 

#### Affected browser(s)
Every

**Comment by KacperMadej** [comment] 2021-07-21 15:19
Hi @thplat 

Thank you for reporting the problem.

This is caused by fonts loading after the chart is created (at least after the space for the text is calculated). This is why everything works fine after the font is being loaded from the cache.

This could be resolved by creating the chart after the font is loaded. You could use some build-in browser functionality for this (if you don't care about IE): https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet/load

**Comment by pawellysy** [comment] 2022-12-05 11:46
Closed due to inactivity

**Closed by pawellysy** 2022-12-05 11:46 UTC
Labels: Status: Pending reply, Type: Not a bug, Type: Question
