### ISSUE TITLE
Circle annotation does not resize when chart resized

### ISSUE THREAD

**Issue by jasonclg** [highcharts/highcharts#15050] opened 2021-02-04 01:58 UTC
#### Expected behaviour
Circle annotation should resize when chart resized

#### Actual behaviour
Circle annotation does not resize

#### Live demo with steps to reproduce
https://jsfiddle.net/2o05xg78
1. Run the code
2. Find the circle annotation in the jsfiddle
3. Click small or auto buttons to resize the chart
4. Observe that the circle annotation does not resize

However, it's working for rectangle annotation in the same use case.
https://jsfiddle.net/BlackLabel/mb17nt5d

#### Product version
Highcharts: 9.0.0
Annotations: 9.0.0

#### Affected browser(s)
Google Chrome (Version 88.0.4324.146)

**Comment by KacperMadej** [comment] 2021-02-04 10:00
Hi @jasonclg 

Thank you for contacting us with the problem.

Circle annotation has a constant radius based on pixel length and only the center is connected to axes values.

Closing as a duplicate of https://github.com/highcharts/highcharts/issues/14997
See also: https://github.com/highcharts/highcharts/issues/15008

**Closed by KacperMadej** 2021-02-04 10:00 UTC
