### ISSUE TITLE
afterSetExtremes event repeating continuously

### ISSUE THREAD

**Issue by lienbcn** [highcharts/highcharts#3582] opened 2014-11-12 21:10 UTC
I have a simple StockChart with the range buttons and the event to detect when the x zoom changes, so that it can request new values to the server to get more "resolution" in that specific area.
The issue is that after getting the data, it resets the data with chart.series[0].setData and then the event is triggered again, but the zoom didn't change. It's like when printing data the zoom changes but it doesn't. This is a simplified code:

http://jsfiddle.net/wz9tprfm/1/

Does it exist a solution for that? Thanks

**Comment by pawelfus** [comment] 2018-01-22 11:50
Hi @dandv 

Could you show your full config for the chart? Maybe you have set `navigator` option twice and `adaptToUpdatedData` is not changed? For example you use `chart.get(id)` but I don't see ID's set in your config so I assume it's a minified example.

Official demo (with your config) doesn't show this issue: http://jsfiddle.net/BlackLabel/b4ne51ta/

**Comment by dandv** [comment] 2018-01-22 12:11
Sorry, I had trimmed too much from the chart config, but I've updated my post above with the full configuration. `navigator` is set only once.

I was able to reproduce (partially) afterSetExtremes being called multiple times in the official demo; please see the very end of the screencast below.

![highstock aftersetextremes repeated calling](https://user-images.githubusercontent.com/33569/35220180-3d89021a-ff2a-11e7-9c37-f6a4da84e318.gif)

**Comment by pawelfus** [comment] 2018-01-22 12:22
@dandv - could you update my demo with the issue? I'm still unable to recreate the issue.. Maybe chart's width should be fixed?

PS: Dev-tools on the right side: 👍

**Comment by dandv** [comment] 2018-01-22 13:05
@pawelfus: The issue isn't easy to reproduce. You need to zoom in about 10 times and watch the console for multiple log statements after the mouse button is released. If you've reached maximum zoom and haven't seen the issue, then you need to start again. But I do manage to to reproduce by selecting random portions of the chart, within 1-2 minutes.

I've added some logging of timestamps, hoping it can help automate the zooming in process: http://jsfiddle.net/b4ne51ta/3/. Below is the console output from a sequence of zooms that led to `afterSetExtremes` being called 6 times in a row, from 13:01:42.816Z to 13:01:43.599Z. It's humanly impossible to zoom in with a mouse 6 times within ~800ms :)


```
[Violation] 'load' handler took 204ms
(index):60 2018-01-22T13:01:29.482Z afterSetExtremes 1207936800000 1235371680000
(index):73 loaded
[Violation] Forced reflow while executing JavaScript took 35ms
(index):60 2018-01-22T13:01:31.243Z afterSetExtremes 1227636960000 1231904880000
(index):73 loaded
(index):60 2018-01-22T13:01:32.611Z afterSetExtremes 1230615360000 1231823520000
(index):73 loaded
(index):60 2018-01-22T13:01:35.936Z afterSetExtremes 1231506480000 1231769510000
(index):73 loaded
(index):60 2018-01-22T13:01:38.123Z afterSetExtremes 1231754080000 1231763670000
(index):73 loaded
(index):60 2018-01-22T13:01:41.348Z afterSetExtremes 1231757316250 1231760916250
(index):73 loaded
(index):60 2018-01-22T13:01:42.816Z afterSetExtremes 1231758472708.3335 1231762072708.3335
(index):60 2018-01-22T13:01:42.986Z afterSetExtremes 1231758420000 1231762020000
(index):60 2018-01-22T13:01:43.014Z afterSetExtremes 1231758472708.3335 1231762072708.3335
(index):73 loaded
(index):60 2018-01-22T13:01:43.128Z afterSetExtremes 1231758420000 1231762020000
(index):73 loaded
(index):60 2018-01-22T13:01:43.198Z afterSetExtremes 1231758472708.3335 1231762072708.3335
2(index):73 loaded
(index):60 2018-01-22T13:01:43.599Z afterSetExtremes 1231758420000 1231762020000
2(index):73 loaded
```

**Comment by pawelfus** [comment] 2018-01-23 12:16
Yes, it took me a while, but I was able to reproduce the issue. 

*Internal note:*
Somehow, the extremes are changed (as pointed out, probably it's a case when zooming below `minRange`).

**Comment by pawelfus** [comment] 2018-01-30 16:45
It looks like this is the root of the issue:

```javascript
      chart.series[0].setData(data);
      chart.series[1].setData(data);
```

In short, chart is rendered twice, but following best practices, multiple changes should be applied in one redraw:

```javascript
      chart.series[0].setData(data, false, false);
      chart.series[1].setData(data);
```

@dandv - could you check if this also fixes the issue in your application? 

@TorsteinHonsi - there is also small problem with current implementation:
```javascript
// extremes taken empirically from manual zooming
var e = { min: 1212068495285.623, max: 1212072095285.623 }; 

console.log(
  'requested range:',
  1212072095285.623 - 1212068495285.623 // equals to one hour, 3 600 000
);
$.getJSON('https://www.highcharts.com/samples/data/from-sql.php?start=' + Math.round(e.min) +
    '&end=' + Math.round(e.max) + '&callback=?', data => {
    console.log(
      'dataset range:',
      data[data.length - 1][0] - data[0][0] // last point - first point, equals to 3 540 000
    );
});
```
When zooming to minimum range, server returns one point less than required. I think our demo should normalize extremes to the lowest available granularity: 

```javascript
  var minute = 60 * 1000;
  $.getJSON('https://www.highcharts.com/samples/data/from-sql.php?start=' + Math.round(e.min / minute) * minute +
    '&end=' + Math.round(e.max / minute) * minute + '&callback=?', function () { ... });
```

Tomorrow I will check if we can safeguard somehow this case in the library itself.

**Comment by dandv** [comment] 2018-02-02 11:15
@pawelfus: good point about passing `false` to setData() to prevent redrawing. That helped avoid the recursive call during user zooms, but I still see them if I call the chart drawing code for a particular portion of the data, meaning that afterSetExtremes() is called from setData():

```js
async function drawChart(chart, startTime, endTime) {
  chart.showLoading('Loading data from server...');
  const { ohlc, volume} = await getData(startTime, endTime);
  chart.get('contract').setData(ohlc, false, false);
  chart.get('volume').setData(volume, false, false);
  chart.redraw(false);
  chart.hideLoading();
}

async function afterSetExtremes(e) {
  await drawChart(e.target.chart, e.min, e.max);
}
```

The chart creation code is the same as in my initial comment, but without the `minRange` option. Zooming with the mouse works fine - no repeated calls. But if I start drawing this particular range, afterSetExtremes gets called repeatedly:

    await drawChart(chart, '2018-01-22T07:42:17.000Z', '2018-01-23T17:18:25.000Z');

**Comment by pawelfus** [comment] 2018-02-07 15:23
@dandv thank you for the details, however that particular range doesn't exist on our chart: http://jsfiddle.net/BlackLabel/b4ne51ta/16/ and I'm still unable to recreate the issue when redraw is set to false for the first `setData()` (no `'================== Repeated calls ================='` entries in the console).

**Comment by dror3go** [comment] 2018-06-20 20:31
I'm seeing a similar infinite loop behaviour using Highstock 6.1.0.
Trying to find the root cause of this issue: am I supposed to pass a specific amount of series data to the `chart.series[0].setData()` method in the `afterSetExtremes` function? Should it be the same amount of points as set initially when setting the chart?
Any other things I need to make sure are configured properly?

Thanks a lot

**Comment by sebastianbochan** [comment] 2018-06-21 08:14
Hi @dror3go,
Could you add a live demo of your chart and data?

**Comment by dror3go** [comment] 2018-06-21 09:59
@sebastianbochan Unfortunately I can't, since it's not live yet.
If it worth anything, he's a fiddle of the JavaScript itself, without any server-side related code: http://jsfiddle.net/z6ostnrm/
I might be able to provide with a URL for live demo in private, though. Please let me know if that's an option.

I forgot to mention it in my initial comment, but the repeated requests are being made on every zoom, not after specific amount of zoom interactions or anything like that.

**Comment by pawelfus** [comment] 2018-06-21 15:48
Hi @dror3go 

Your code looks ok, could you try to disable `dataGrouping`? That's the only thing that is missing, I think. If this won't resolve the issue, please contact us by email: https://www.highcharts.com/support

**Comment by dror3go** [comment] 2018-06-22 12:11
@pawelfus Thanks, that did the trick!

**Comment by pawelfus** [comment] 2019-07-12 14:17
Closing the issue. If anyone will be able to recreate issue in a stable env (by stable I mean fixed extremes that particularly call multiple `afterSetExtremes` event, where only last `setData()` forces redraw) please share and I will reopen this.

**Closed by pawelfus** 2019-07-12 14:17 UTC
Labels: Product: Highstock, Type: Bug

**Comment by krishhnaa** [comment] 2021-09-03 15:59
@pawelfus it is happening for me it is calling three times and I have created a ticket in highcharts support https://www.highcharts.com/forum/viewtopic.php?f=9&t=47262&p=170100#p170100

**Comment by pawelfus** [comment] 2021-09-06 07:10
Hi @krishhnaa 

Thank you for letting us know. Unfortunately, we need a live demo, just like Mateusz asked on the forum.
