### ISSUE TITLE
[Highstock] yAxis crosshair label formatter this.value undefined

### ISSUE THREAD

**Issue by KillerKiwiJuice** [highcharts/highcharts#17235] opened 2022-04-30 06:22 UTC
#### Expected behaviour
According to the [docs](https://api.highcharts.com/highstock/yAxis.crosshair.label.formatter) for the label formatter, the label should display the correct this.value on the side.

#### Actual behaviour
this.value is undefined

#### Live demo with steps to reproduce

https://jsfiddle.net/1exmnuw2/

#### Product version

Highstock Latest (10.1.0)

#### Affected browser(s)
All

When I console.log(this) in the formatter there is no crosshair value to use...

**Comment by pawellysy** [comment] 2022-05-02 08:57
Hello @KillerKiwiJuice, thanks for creating the issue. 
The `value` is passed as an argument to the formatter function and is not a part of the context.

Check this demo: https://jsfiddle.net/BlackLabel/mLvchj06/2/

Closing since this is not a bug.

**Closed** 2022-05-02 08:57 UTC
Labels: Type: Not a bug
