### ISSUE TITLE
Setting alternateGridColor in yAxis using themes affects colorAxis.

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#5569] opened 2016-08-09 10:15 UTC
#### Expected behaviour
Setting alternateGridColor in yAxis should not affect colorAxis

#### Actual behaviour
Right now when using alternateGridColor in yAxis, the colour blocks are visible in the chart. I am posting image showing this issue: 

![screen shot 2016-08-09 at 12 11 27](https://cloud.githubusercontent.com/assets/15050812/17512979/bbd0536e-5e2a-11e6-99fa-cdf79a081998.png)

#### Live demo with steps to reproduce
Here you can find the demo showing this issue: 
http://jsfiddle.net/tpo8n3bL/4/

As a workaround you can add alternateGridColor in colorAxis (to see the changes uncomment it from the example I gave you).

**Comment by pawelfus** [comment] 2016-08-10 12:51
Used to work in 4.1.7 version: http://jsfiddle.net/tpo8n3bL/5/

Fails since: d84d598

Related ticket: #3379

**Comment by TorsteinHonsi** [comment] 2016-08-11 09:26
In 4.1.7 and before, the same problem existed, but with the xAxis: http://jsfiddle.net/highcharts/jjy0wkLq/.

It can be discussed whether it is a regression, it is more a bug that has moved. 

So the issue is not new, and it is not related to `alternativeGridColor`. The same thing happens with some other options, like [gridLineColor](http://jsfiddle.net/highcharts/ua8vbjoq/1/). It has to do with how options are merged into the color axis.

**Comment by pawelfus** [comment] 2016-08-11 09:46
Good point! I agree, it's a bug, let change label.

**Closed** 2016-08-11 09:55 UTC
Labels: Bug
