### ISSUE TITLE
Switching from "column" to "bar" chartType , Axises gets interchanged

### ISSUE THREAD

**Issue by mohan-mu** [highcharts/highcharts#13363] opened 2020-04-23 14:10 UTC
Is there something i need to do inorder to keep Axis labels intact 

When i selected `column` chart i'm hiding `XAxis`  
```javascript
Highcharts.chart('container', {
  chart: {
    type: 'column'
  },

  xAxis: {
  visible:false, //HERE
  },

  series: seriesData
});

```
![image](https://user-images.githubusercontent.com/20799929/80107761-21190600-8599-11ea-9eeb-c3f074861518.png)

----
BUT ....
When i set chartType to `bar`  Why is it reflecting to `YAxis`  
```javascript
Highcharts.chart('container', {
  chart: {
    type: 'bar'
  },

  xAxis: {
  visible:false, //HERE
  },

  series: seriesData
});

```
![image](https://user-images.githubusercontent.com/20799929/80107804-2fffb880-8599-11ea-94d7-6e995183e221.png)

**Comment by sebastianbochan** [comment] 2020-04-24 07:42
Hi @mohan-mu,
Thank you for reporting. In `inverted` charts (i.e bar or when you use the option `inverted`) axes are swapped by default. 

Part of our docs:

> inverted: boolean
Whether to invert the axes so that the x axis is vertical and y axis is horizontal. When true, the x axis is reversed by default.

Ref:
- https://api.highcharts.com/highcharts/chart.inverted

Closed this ticket as not a bug.

**Closed by sebastianbochan** 2020-04-24 07:42 UTC
Labels: Type: Not a bug

**Comment by mohan-mu** [comment] 2020-04-24 08:44
Hi @sebastianbochan  

Well i tried with `inverted` option 

but didn't worked

**Comment by mohan-mu** [comment] 2020-04-24 08:47
But in docs it says 

> The bar chart is exactly the same as a column chart only the x-axis and y-axis are switched.

Ref: https://www.highcharts.com/docs/chart-and-series-types/bar-chart

**Comment by sebastianbochan** [comment] 2020-04-24 09:07
Bar chart is `column` chart with enabled `inverted` option.

Its correct, so it means that axis are switched and chart is "rotated".

**Comment by mohan-mu** [comment] 2020-04-24 09:13
But in my above example you can see , its not switching axis , but its rotated.

if i say for `bar` chartType  , `xAxis`  visibility is set to `false` it should hide `xAxis` not `yAxis`

**Comment by sebastianbochan** [comment] 2020-04-24 09:32
In bar chart xAxis = yAxis and yAxis = xAxis, its a definition of "rotation" and "switch axes".

**Comment by mohan-mu** [comment] 2020-04-24 10:58
@sebastianbochan , that's correct

 i've no problem with chart. It's plotted in a right way , but  my concern is why isn't the axis consistent across different chart types. 

suppose imagine i wanna hide `xAxis` , since `bar` chart is invert of `column` . i have to following stuff: 
```javascript
// For all Column Charts 
xAxis: {
  visible:false,
  },
//For all Bar charts
yAxis: {
  visible:false, 
  },
```
well above works , but imagine we are storing axises config and we wanted to be consistent across all chart types.

**Comment by sebastianbochan** [comment] 2020-04-24 11:31
Hi @mohan-mu,
You can use one of solutions:

1. merge function and combine your options with current chart.
Demo:
- https://jsfiddle.net/BlackLabel/7mx9wsq2/

2. use event.load() and update 
Demo:
- https://jsfiddle.net/BlackLabel/jeLo236x/

3. use callbacks
- https://jsfiddle.net/BlackLabel/zqtLxas3/

ps. The github is our bug tracker, so for general [support](https://www.highcharts.com/support) questions please use stackoverflow / email or forum.
