### ISSUE TITLE
Tab order on zoom

### ISSUE THREAD

**Issue by GMUDuckman** [highcharts/highcharts#9720] opened 2018-12-18 19:38 UTC
#### Expected behaviour
When zooming then tabbing, you would expect that after the zoom when you tab it would tab to the elements inside the displayed area

#### Actual behaviour
When zooming then tabbing, it still selects the first element in the series, regardless of if its displayed at current zoom level or not.

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/chart/zoomtype-x/

**Comment by KacperMadej** [comment] 2018-12-19 01:30
Hi @GMUDuckman

Thank you for reporting about the problem.
A demo with accessibility module loaded: http://jsfiddle.net/BlackLabel/Lj1bh78u/

@oysteinmoseng a11y issue

**Comment by GMUDuckman** [comment] 2018-12-19 01:46
@KacperMadej Thanks! I've been making use of the accessibility option and it does help a LOT with section 508 compliance, its just a little short (at least according to our 508 compliance officer).  I actually wrote some javascript to allow for keyboard only zooming and panning. I've submitted it to highcharts for hopefully better implementation.

**Comment by oysteinmoseng** [comment] 2018-12-19 14:17
@GMUDuckman Great to hear that you are using our accessibility module! And please feel free to file issues or get in touch with us if you have any feedback. We are continuously working to improve it.

I will look into creating a more proper fix for this after the holidays. Until then you should be able to set `series.cropThreshold` to 1 as a workaround ([example](http://jsfiddle.net/v7zxsah4/)).

**Comment by GMUDuckman** [comment] 2018-12-19 16:13
@oysteinmoseng - just implemented the workaround and got... weird results. When I zoom  then tab it does indeed tab to the first point in the zoom, but when I try to navigate the points with my arrow keys my data chart gets completely messed up (moves data points to different spots and adds 13 null data points) and it throws a console error: 
` accessibility.js:43 Uncaught TypeError: Cannot read property 'series' of undefined
    at m (accessibility.js:43)
    at f.c.Series.highlightFirstValidPoint (accessibility.js:50)
    at u.init (accessibility.js:58)
    at u.move (accessibility.js:47)
    at u.run (accessibility.js:46)
    at HTMLDivElement.<anonymous> (accessibility.js:68)
m @ accessibility.js:43
c.Series.highlightFirstValidPoint @ accessibility.js:50
init @ accessibility.js:58
move @ accessibility.js:47
run @ accessibility.js:46
(anonymous) @ accessibility.js:68
`
Maybe this is happening because I am using a csv for the data?

**Comment by GMUDuckman** [comment] 2018-12-19 16:43
So turns out what is breaking it is the custom function i wrote to do custom panning and zooming with keyboard only. Guess I have to rethink the function I wrote for that.
`$("#container").bind('keydown', function () {
    let chart = $("#container").highcharts().xAxis[0];
    var min = chart.getExtremes().min;
    var max = chart.getExtremes().max;
    if (event.keyCode == 107 || event.keyCode == 187) {
        //zoom in
        min++;
        max--;
    }
    if (event.keyCode == 109 || event.keyCode == 189) {
        //zoom out
        if (min > chart.dataMin) {
            min--;
        }
        if (max < chart.dataMax) {
            max++;
        }
        
    }
    if (event.keyCode == 39) {
        //right arrow
        if (max < chart.dataMax) {
            min++;
            max++;
        }
    }
    if (event.keyCode == 37) {
        //left arrow
        if (min > chart.dataMin) {
            min--;
            max--;
        }
    }
    chart.setExtremes(min, max);`

**Comment by oysteinmoseng** [comment] 2018-12-20 09:12
@GMUDuckman Weird. Are you able to reproduce this in a jsFiddle so I can debug it?

**Comment by GMUDuckman** [comment] 2018-12-20 17:07
@oysteinmoseng trying to, but the fiddle doesn't seem to want to load the sample CSV.  Here is what my options look like (except for the data options).

http://jsfiddle.net/yec13u5n/

**Comment by oysteinmoseng** [comment] 2019-02-20 12:05
Is this still an issue for you?

**Comment by GMUDuckman** [comment] 2019-02-20 14:09
I was still having this issue but the site had to go into production so I
just disabled tab stops on it for now. We'll be doing round 2 of
development relatively soon, I can get back to you with more detail once we
are knee deep in dev again.

**Comment by sebastianbochan** [comment] 2019-04-18 11:30
Closed due to inactivity. Please reopen when new details will be available.

**Closed by sebastianbochan** 2019-04-18 11:30 UTC
Labels: Status: Pending reply
