### ISSUE TITLE
Highstock - incorrect position of zoom rectange

### ISSUE THREAD

**Issue by mateuszkornecki** [highcharts/highcharts#13266] opened 2020-04-07 06:39 UTC
#### Expected behaviour
The zoom rectangle should be drawn from the cursor location.

#### Actual behaviour
If we increase the element height after the chart render, the zoom rectangle will not be drawn from the cursor location. It was working correctly in highstock v.7.2.0. It seems it is happening in highstock only.
#### Live demo with steps to reproduce

1. Click at the expansion panel.
2. Draw zoom rectangle.
3. Step out from the chart container.
4. Draw a zoom rectangle again (now it should be drawn correctly).

Live demo: https://jsfiddle.net/BlackLabel/f6Lgxzwo/

#### Related forum thread
https://www.highcharts.com/forum/viewtopic.php?f=12&t=43666

#### Product version
From 7.2.1

#### Affected browser(s)
All

**Comment by mateuszkornecki** [comment] 2020-04-07 06:40
_internal note:_ bisected to commit 8359afc222

**Comment by pawelfus** [comment] 2020-05-19 11:00
Closing as duplicate of #12868

Demo with workaround from #12868 : https://jsfiddle.net/BlackLabel/f6Lgxzwo/1/

**Closed by pawelfus** 2020-05-19 11:00 UTC
Labels: Product: Highcharts Stock, Type: Regression
