### ISSUE TITLE
Stock Tools: Adding and removing panes misplaces yAxis with `top` predefined

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#15735] opened 2021-05-17 16:01 UTC
#### Expected behaviour
Correctly positioned first/main yAxis

#### Actual behaviour
yAxis is translated to the top (negative `yAxis.top` value)

#### Live demo with steps to reproduce
[Demo](https://jsfiddle.net/BlackLabel/kam2zwbg/1/)

- initial yAxis has `yAxis.top` defined.
- add 2 indicators with separate yAxes (for example 2x ATR)
- remove the first of them -> yAxis height is calculated incorrectly:

![Zrzut ekranu 2021-05-17 o 18 00 00](https://user-images.githubusercontent.com/1453926/118519790-b7d2da80-b739-11eb-8fc4-40fb16deaf77.png)

#### Product version
Highcharts Stock

**Comment by jackytanjq** [comment] 2022-02-28 10:20
Hello,
Can I know if there is a fix for this to solve the broken secondary indicators on deletion?

Kindly refer to the duplicate issue below that requires the secondary indicators to be able to delete:
#16969

A workaround fix for this is much appreciated due to the negative impact it has on my project.
Thank you.

**Comment by karolkolodziej** [comment] 2022-02-28 10:37
Thank you @[jackytanjq](https://github.com/jackytanjq) for contacting us!

As you can see there is a discussion above on how this might be implemented. 
It will be highly appreciated if you could look at the suggested solution and answer those two questions.
This might help us in the future to properly implement that feature.

In the meantime, we will take a closer look at that issue and we will try to find some workaround.

**Comment by jackytanjq** [comment] 2022-03-01 01:42
Hello @karolkolodziej,
In my humble opinion, please find my comments to the above mentioned questions below:
> -Where the new indicators should be added when the fixed axis is positioned at the bottom?
If this refers to the primary Y-axis _(main stock data)_ is at the very bottom of the chart, meaning the current chart's behavior is inverted _(plot from bottom to the top)_.
Then I believe the new indicators should be added at the very top of the chart.

> -How many fixed axes should be allowed per chart?
There should not be a limit for as long as the total height of each axis is 100%.
However if it does exceed, will all the fixed axis's height be scaled down evenly to a total height of 100%?


I have a question regarding the main stock's axis height:
If the user adds many secondary indicators, I noticed that the main stock's axis height will reduce to provide sufficient space for the new secondary indicators.

Is this the expected behavior? 
Or is there a way to fix the height and only allow other axis to scale accordingly?

As per what I understand at the moment, there is a default minimum height for each system defined secondary indicator set to about 10% of the plot's height area that scales accordingly.

**Comment by pawellysy** [comment] 2022-03-18 16:39
**Internal Note**

The issue was caused by rounding problem

### Workaround

switch `top <= allAxesHeight` to `top < allAxesHeight || (Math.abs(top - allAxesHeight) < 0.001)`

https://jsfiddle.net/BlackLabel/kam2zwbg/3/

**Closed** 2022-03-30 08:38 UTC
Labels: Type: Bug, Product: Highcharts Stock, Status: Has workaround
