### ISSUE TITLE
PDF exporting doesn't work at all when using offline-exporting [IE11, IE10]

### ISSUE THREAD

**Issue by stpoa** [highcharts/highcharts#6256] opened 2017-01-17 16:53 UTC
#### Expected behaviour
Chart should be exported to PDF after clicking export button. (It should fallback to online exporting)

#### Actual behaviour
Chart doesn't get exported to PDF at all

#### Live demo with steps to reproduce
http://jsfiddle.net/p1Lf1enc/

1. Click menu icon
2. Click "Download PDF document"
3. Notice, nothing is happening

#### Affected browser(s)
IE11
IE10

**Comment by TorsteinHonsi** [comment] 2017-01-18 08:30
Observation: 

* v5.06 => Nothing happens
* v5.0.7 => Exporting to PDF in IE11 fails with an error message, "Fallback to server is disabled".

**Comment by TorsteinHonsi** [comment] 2017-01-18 08:32
It's the expected outcome based on the compatibility table at http://www.highcharts.com/docs/export-module/client-side-export.

**Comment by Glenruben** [comment] 2017-01-18 08:58
in v5.0.7 => with "fallbackToExportServer: true" the fallback option works in IE11.

**Comment by tarunchopra91** [comment] 2018-02-02 13:29
I am still facing exporting issue in IE 11 browser. Tried to fix it by using offline-exporting, but still failed to export in PDF.

Hence I feel this issue needs to be reopened.
Use this [fiddle ](http://jsfiddle.net/nbcqcfxq/) in IE 11

**Comment by oysteinmoseng** [comment] 2018-02-02 14:28
@tarunchopra91 Interesting, I was not able to reproduce the issue with IE 11.0.9600.18349. Offline exporting just falls back to the online export server for PDF export on IE11, so it won't help in this case. What happens when you export? Have you tried not setting filename?

**Comment by KacperMadej** [comment] 2018-02-05 16:14
I was able to recreate the problem with basic exporting - not the offline-exporting, just exporting module. It looks like the form is not submitted correctly when called from an iframe. In the JSFiddle a demo is not working, but exporting works well with the same chart placed on highcharts.com/demo.

Nothing happens when trying to export. When debugging - all runs fine, no error, submitting the form does nothing.

**IE11.125.16299.0 / Win 10**

**Comment by tarunchopra91** [comment] 2018-02-07 05:00
In my case the chart is in an iFrame. And with basic exporting, nothing is working and no error is there. When I tried offline-exporting PNG/JPEG/SVG export is working fine, but PDF export is still not working.

@oysteinmoseng I tried not setting filename, but still exporting is not working.
@KacperMadej I am facing similar problem. Following warning is displayed in my browser console. 
"DOM7011 : The code on this page disabled back and forward caching. For more information, see: [http://go.microsoft.com/fwlink/?LinkID=291337](http://go.microsoft.com/fwlink/?LinkID=291337)"

**Comment by KacperMadej** [comment] 2018-02-07 12:32
@tarunchopra91 
PDF export in client side exporting is not supported for IE11 (see the table at https://www.highcharts.com/docs/export-module/client-side-export)

Disabled caching shouldn't be a problem - file will load and cache will be ignored.

**Comment by tarunchopra91** [comment] 2018-02-08 05:08
Yes, but it would be good if we can please fix this in basic exporting on high priority.

**Comment by oysteinmoseng** [comment] 2018-02-08 10:01
Closing this as it is not an offline exporting issue. Let's follow up at #7824.

Can you look into it @KacperMadej since you could reproduce it?

**Closed by oysteinmoseng** 2018-02-08 10:01 UTC
