### ISSUE TITLE
Map format legend values

### ISSUE THREAD

**Issue by pliasetski** [highcharts/highcharts#6090] opened 2016-12-05 14:30 UTC
Impossible to format legend values, because they overlap each other.

#### Expected behaviour
Legend labels do not overlap each other.

#### Actual behaviour
Legend labels overlap each other.

#### Live demo with steps to reproduce
http://jsfiddle.net/Pashe4ka/5ctxc9q9/

#### Affected browser(s)
Chrome latest version

**Comment by pawelfus** [comment] 2016-12-07 12:55
Thanks for reporting!
I'm closing this as a duplicate of #4816

**Closed by pawelfus** 2016-12-07 12:55 UTC
Labels: Duplicate

**Comment by TorsteinHonsi** [comment] 2016-12-12 13:54
See your fiddle after fixing #4816 : http://jsfiddle.net/highcharts/5ctxc9q9/1/
