### ISSUE TITLE
treemap.js crashing on 4.2.6

### ISSUE THREAD

**Issue by jmonkfish** [highcharts/highcharts#5597] opened 2016-08-17 22:16 UTC
#### Expected behaviour
Working treemap

#### Actual behaviour
TypeError: c.shapeArgs is undefined
https://code.highcharts.com/modules/treemap.js
Line 26

#### Live demo with steps to reproduce

Issue started with 4.2.6, 4.2.5 continues to work.

https://jsfiddle.net/jmonkfish/f6a1qna9/

If you uncomment the 4.2.5 js src url it works.

#### Affected browser(s)
Chrome, Firefox, Safari

**Comment by jon-a-nygaard** [comment] 2016-08-18 07:17
Hi @jmonkfish 
This seems to be a duplicate of #5563, which is fixed in our master branch.  Please follow the mentioned issue to find more information and updates.

**Closed by jon-a-nygaard** 2016-08-18 07:17 UTC
