### ISSUE TITLE
Highcharts is not defined

### ISSUE THREAD

**Issue by Dr34nn** [highcharts/highcharts#18121] opened 2022-12-09 12:46 UTC
cdn error

**Comment by pawellysy** [comment] 2022-12-09 13:56
Any details?

**Comment by pawellysy** [comment] 2022-12-09 14:05
maybe use the correct URL? https://code.highcharts.com/10.2.1/highcharts.js

**Comment by pawellysy** [comment] 2022-12-09 15:02
Closing, not a bug

**Closed by pawellysy** 2022-12-09 15:02 UTC
Labels: Status: Can't reproduce, Status: Pending reply
