### ISSUE TITLE
Venn chart displayed incorrectly for 3 overlapping sets

### ISSUE THREAD

**Issue by gtanczyk** [highcharts/highcharts#9768] opened 2018-12-31 10:22 UTC
#### Expected behaviour
![image](https://user-images.githubusercontent.com/1281113/50558388-386e1900-0cee-11e9-9c6c-73f95c006ee5.png)

#### Actual behaviour
![image](https://user-images.githubusercontent.com/1281113/50558399-5471ba80-0cee-11e9-9a60-c424538d6fe2.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/k2xvL7y6/

#### Product version
Highmaps 7.0.1

#### Affected browser(s)
Latest google chrome.

**Comment by sebastianbochan** [comment] 2018-12-31 10:42
Hi @gtanczyk,
Thank you for reporting about the problem.

@jon-a-nygaard

**Comment by KacperMadej** [comment] 2018-12-31 12:44
Looks like a duplicate of #9718
I'll close this issue as a duplicate for now, but if this is a different issues pleases leave a comment and this issue could be reopened.

**Comment by gtanczyk** [comment] 2018-12-31 12:48
@KacperMadej both issues are related to this function https://github.com/highcharts/highcharts/blame/master/js/modules/venn.src.js#L50, however #9718 is a bug in already supported case (2 circles), while #9768 is a not supported case (more than 2 circles) - please see the TODO in source.

I suggest to reopen.

**Comment by gtanczyk** [comment] 2018-12-31 12:53
I was wondering if it would make sense to add dependency on https://github.com/benfred/venn.js/blob/master/src/circleintersection.js to highcharts and make use of that implementation, which apparently solves the problem already.

**Comment by KacperMadej** [comment] 2018-12-31 13:38
@gtanczyk 
Thank you for the info. Reopening.

**Closed** 2019-01-07 14:17 UTC
Labels: Bug, Review
