### ISSUE TITLE
Tooltip doesn't show up if I mouse over and  mouse out on Highcharts 

### ISSUE THREAD

**Issue by keshavkuruva** [highcharts/highcharts#4977] opened 2016-01-30 00:29 UTC
I have this snippet of code in my js that loads highcharts. 
    plotOptions: {
				series: {
					stickyTracking: true,
					events: {
						click: function(evt) {
							this.chart.myTooltip.refresh(evt.point, evt);
						},
						mouseOut: function() {
							this.chart.myTooltip.hide();
						}                       
					}           
				},

Instead of clicking, if I first mouseOver and mouseOut, the tooltip doesn't show up anymore. But when I click, the tooltip shows up.  

I am not sure what the problem is , but would appreciate if some one can suggest what am I doing wrong.  I have seen a js fiddle posted on stackoverflow that reproduces the same problem. 

http://jsfiddle.net/ncdysafk/1/

Please advise. 

Thanks,
Keshav.

**Comment by TorsteinHonsi** [comment] 2016-02-01 08:32
You have used the Tooltip prototype to generate your own custom tooltip, I am not sure how that will work. It is not covered by our API, so it is not a bug per se.

I am closing this issue, for general tech support, please see www.highcharts.com/support.

**Closed by TorsteinHonsi** 2016-02-01 08:32 UTC
Labels: Not a bug
