### ISSUE TITLE
Zoom issue after tooltip.refresh (Bootstrap modal)

### ISSUE THREAD

**Issue by msmeza** [highcharts/highcharts#12601] opened 2019-12-10 11:16 UTC
Consider a chart with following (very specific) requirements:

1. The chart needs to be shown at the bottom of a long Bootstrap modal
2. The chart needs to have zooming enabled
3. The chart needs to show the tooltip for a specific data point as soon as it's loaded (even before the user hovers over the chart)
4. The tooltip needs to always be visible, regardless of whether the mouse pointer is over the chart or not
5. The tooltip needs to be positioned right below the x-axis and its ticks and labels

#### Expected behaviour

It should be possible to zoom into an area of the chart immediately after the chart is first scrolled into view.

#### Actual behaviour

No area can be selected which means no zoom event is triggered.

The reason for the issue seems to be that calling `chart.tooltip.refresh` in the load event of the chart sets the position of the chart, but the position is no updated when the chart is scrolled into view. This means that the call to `isInsidePlot` in the function `drag` returns false (until the chart's position is updated by some event, such as hovering over other elements in the modal).

For a more detailed description of the issue please take a look at the forum topic that resulted in this bug report: https://www.highcharts.com/forum/viewtopic.php?f=9&t=42984

#### Live demo with steps to reproduce
The issue can be reproduced here: https://jsfiddle.net/8z5m2oh4/

The steps to reproduce the issue are:

- Click the button to open the modal
- Scroll to the bottom of the modal (preferably keeping the mouse pointer outside of the modal while scrolling)
- Try to zoom into any part of the chart once it's in view

Please keep in mind that, because of the way jsfiddle works, the issue is only visible right after the jsfiddle page has been loaded or right after the jsfiddle has been run or re-run (the issue is not present after closing the modal and opening it again)

#### Product version
Highcharts 7.2.1

#### Affected browser(s)
I've reproduced the issue on Chrome and Firefox on Windows and on Chrome and Safari on OSX

**Comment by raf18seb** [comment] 2019-12-10 11:28
Simplified demo: https://jsfiddle.net/BlackLabel/n0pg8mk4
Looks like a regression - works fine in 7.2.0

**Comment by pawelfus** [comment] 2019-12-11 11:14
*Internal note:*
Bisected to commit 8359afc222

**Comment by pawelfus** [comment] 2020-03-26 09:58
Most likely duplicate of #12868

**Comment by khlieng** [comment] 2021-01-11 14:33
Fixed since 8.2.0 (#13835).

**Closed by khlieng** 2021-01-11 14:33 UTC
Labels: Type: Regression
