### ISSUE TITLE
Highcharts 7 does not with transform scale

### ISSUE THREAD

**Issue by balkarov** [highcharts/highcharts#10990] opened 2019-06-14 07:32 UTC
Hello.
Highcharts 7 does work with transform scale.
But highcharts 6.2.0 worked.

#### Expected behaviour
![image](https://user-images.githubusercontent.com/6030335/59491462-7a031280-8e8f-11e9-8d36-19de75c6bc27.png)

#### Actual behaviour
![image](https://user-images.githubusercontent.com/6030335/59491388-4c1dce00-8e8f-11e9-9e6f-161067d9a879.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/h7nLecgq/ (higcharts 7 does not work)
https://jsfiddle.net/uow2yms5/ (highchart 6.2.0 works)

#### Product version
7.0 - 7.1.4

#### Affected browser(s)
Google Chrome 74.0.3729.169

**Comment by pawelfus** [comment] 2019-06-14 08:35
Thanks for reporting @balkarov 

This is actually a duplicate of #10498.

**Comment by sebastianbochan** [comment] 2019-06-14 08:35
Related also with: https://github.com/highcharts/highcharts/issues/10782

**Closed by pawelfus** 2019-06-14 08:35 UTC
