### ISSUE TITLE
boost-canvas fails when chart has more than one series

### ISSUE THREAD

**Issue by achin** [highcharts/highcharts#7670] opened 2018-01-15 19:58 UTC
#### Expected behaviour
boost-canvas (Boost's Canvas fallback for browsers that don't support WebGL) should work the same way as regular boost. When your chart has multiple series, it should work the same way as when it has one.

#### Actual behaviour
If you disable WebGL and load boost-canvas, then you get the following error when charting more than one series.

```
Uncaught TypeError: Cannot read property 'width' of undefined
    at l.renderCanvas (https://code.highcharts.com/modules/boost-canvas.js:16:349)
    at l.c (https://code.highcharts.com/modules/boost.js:50:42)
    at l.a.(anonymous function) [as render] (https://code.highcharts.com/highcharts.js:19:363)
    at https://code.highcharts.com/highcharts.js:253:346
    at Array.forEach (<anonymous>)
    at a.each (https://code.highcharts.com/highcharts.js:29:308)
    at a.Chart.renderSeries (https://code.highcharts.com/highcharts.js:253:304)
    at a.Chart.render (https://code.highcharts.com/highcharts.js:255:217)
    at a.Chart.firstRender (https://code.highcharts.com/highcharts.js:258:338)
    at a.Chart.init (https://code.highcharts.com/highcharts.js:234:5)
```

#### Live demo with steps to reproduce
The `window.WebGLRenderingContext = undefined;` line simulates disabling WebGL without having to play with browser settings.

https://jsfiddle.net/alexbachin/ck0s9q2e/

#### Product version
Highcharts 6.0.4

#### Affected browser(s)
Chrome 61/63, Firefox 43/47/56/57

**Comment by sebastianbochan** [comment] 2018-01-16 11:51
Hi @achin
Thank you for the reporting.
Duplicate of https://github.com/highcharts/highcharts/issues/7610.

**Closed by sebastianbochan** 2018-01-16 11:51 UTC
