### ISSUE TITLE
Redraw chart before reset zoom will get no data 

### ISSUE THREAD

**Issue by mofeiwlj** [highcharts/highcharts#5483] opened 2016-07-13 08:12 UTC
#### Expected behaviour

Redraw my chart

#### Actual behaviour

Give me no data info.

#### Live demo with steps to reproduce

1.zoom a chart
2.redraw my chart via ajax

when I zoom a chart and then I click a button to refresh my data and redraw my chart before reset zoom,then it will give me no data info.Actually however it has new datas.So I think it's a Bug.

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment] 2016-07-13 08:25
Hi @mofeiwlj 

Could you recreate issue on jsFiddle? Without live demo we can only flag this as `Can't reproduce`. Personally, I don't think it's a bug - it sounds more like a problem with AJAX request or  data format.

Thanks,
Paweł

**Comment by jon-a-nygaard** [comment] 2016-08-02 12:46
Closing this since we are unable to reproduce, and it is pending a reply. Should anyone have further information on the issue, please give us a comment.

**Closed by jon-a-nygaard** 2016-08-02 12:46 UTC
Labels: Cant reproduce, Pending reply
