### ISSUE TITLE
x-Axis labels position bug when useHtml: true with drilldown 

### ISSUE THREAD

**Issue by SaleemDiab** [highcharts/highcharts#8809] opened 2018-08-19 11:23 UTC
#### Expected behaviour
x-Axis label aligned in the correct position under the relevant column after drilldown and drillup

#### Actual behaviour
x-Axis labels incorrect position when drillup 

case:
I found the issue reproduces only when the label is long (few words).
in the live demo please click on the column 'All patches average dE' to drilldown and then make sure that there is enough width to see all the columns in the drilled chart then drill up and you will see that the labels are in incorrect position.

![image](https://user-images.githubusercontent.com/9072934/44308286-43698200-a3bb-11e8-9093-c0638744512d.png)

if you drilldown again, few labels will be lost in the drilled chart.

![image](https://user-images.githubusercontent.com/9072934/44308292-63994100-a3bb-11e8-8578-f2aebdc4834c.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/xu2oh1yr/9/

#### Product version
Highcharts v6.1.1

#### Affected browser(s)
Chrome only tested

**Comment by sebastianbochan** [comment] 2018-08-20 08:59
Hi @SaleemDiab,
Thank you for reporting. When I run your demo, unfortunately I was not able to reproduce the issue. 

![resize](https://user-images.githubusercontent.com/2115686/44330736-11fac000-a468-11e8-8869-3e1cee2ebf7a.gif)


Chrome: 68.0.3440.106
MacOSX: 10.12.4

Could you point me out which version of Chrome / OS you have ?

**Comment by SaleemDiab** [comment] 2018-08-20 09:10
hi @sebastianbochan, you have to drill down and up again 
![awesomescreenshot-2018-08-20t09-06-07-710z](https://user-images.githubusercontent.com/9072934/44331375-001e1a80-a472-11e8-8fcb-94e3fa703aff.gif)

**Comment by SaleemDiab** [comment] 2018-08-20 09:16
Chrome Version 68.0.3440.106
Windows 10
width 960px is enough I think

Thanks,

**Comment by pawelfus** [comment] 2018-08-20 10:16
Thanks @SaleemDiab  for reporting this bug. Actually, we have two regressions here:


- v6.0.4 -> v6.0.5 -> broken first three labels after drill down (demo: http://jsfiddle.net/BlackLabel/xu2oh1yr/87/). Responsible commit: 6bf7ff5c8
- v6.0.7 -> v6.1.0 -> broken first three labels after drill up (demo: http://jsfiddle.net/BlackLabel/xu2oh1yr/87/). Responsible commit: cef5aed50


Last working version: v6.0.4: http://jsfiddle.net/BlackLabel/xu2oh1yr/84/

**Comment by SaleemDiab** [comment] 2018-08-20 12:16
any suggested workaround ?

**Comment by pawelfus** [comment] 2018-08-21 08:29
@SaleemDiab Could you try `xAxis.labels.rotation = 0` ? This should resolve the issue, please take a look: http://jsfiddle.net/BlackLabel/xu2oh1yr/107/

**Comment by SaleemDiab** [comment] 2018-08-21 08:41
@pawelfus, thaknk you very much it really solved the issue for me :)

**Comment by SaleemDiab** [comment] 2018-08-21 09:03
@pawelfus, sorry to disappoint you again but I found another issue :
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/9072934/44392131-2c9d6980-a53a-11e8-80ce-8f1acf7fb818.gif)

**Comment by pawelfus** [comment] 2018-08-21 09:40
@SaleemDiab I don't see any better workaround than disabling `useHTML` or downgrading to v6.0.4.

**Comment by TorsteinHonsi** [comment] 2018-08-23 11:31
I think I have found the underlying source of the problem, it has to do with internal cache not being cleared after unsetting width by CSS. The fix will be committed in a minute and release with the next maintenance release, targeted next week.

Here's a drop-in **workaround** you can use in the meantime:
```js
// Drop-in workaround for #8809
Highcharts.SVGElement.prototype.htmlCss = function (styles) {
    var wrapper = this,
        element = wrapper.element,
        textWidth = styles && element.tagName === 'SPAN' && styles.width;

    // When setting or unsetting the width style, we need to update
    // transform (#8809)
    if (textWidth || (wrapper.textWidth && !textWidth)) {
        delete styles.width;
        wrapper.textWidth = textWidth;
        wrapper.htmlUpdateTransform();
    }
    if (styles && styles.textOverflow === 'ellipsis') {
        styles.whiteSpace = 'nowrap';
        styles.overflow = 'hidden';
    }
    wrapper.styles = Highcharts.extend(wrapper.styles, styles);
    Highcharts.css(wrapper.element, styles);

    return wrapper;
};
```

View it live: http://jsfiddle.net/highcharts/xu2oh1yr/115/

**Closed** 2018-08-23 13:26 UTC
Labels: Regression
