### ISSUE TITLE
Data label misalignment in 3D Highcharts

### ISSUE THREAD

**Issue by rahul051296** [highcharts/highcharts#10808] opened 2019-05-23 11:11 UTC
#### Expected behaviour
Data labels should be properly positioned appropriate to series data values.It should not go out of chart for extremely low values of series data.

#### Actual behaviour
I’m using 3D Highcharts. Data labels works fine for 2D charts but I’m facing issue with data label positioning after 3D projection.I’ve attached the screenshot and code snippet here for your reference.

![Screenshot1](https://i.stack.imgur.com/AtFMT.jpg)
options3d = {
        enabled: true,
        alpha: 15,
        beta: 15,
        depth: 40
    };

I'm looking for a proper fix in highcharts(without changing alpha and beta values of 3D options) that will enable data labels to be positioned properly.
Thanks in advance!

**Comment by Izothep** [comment] 2019-05-23 11:42
Hi @rahul051296!

Thank you for reporting your problem. It looks that your issue is a duplicate of #5508

To avoid further duplications, please continue on mentioned topic.

**Closed by Izothep** 2019-05-23 11:42 UTC
