### ISSUE TITLE
Duplicate attribute being specified on an SVG element

### ISSUE THREAD

**Issue by smithk58** [highcharts/highcharts#5575] opened 2016-08-09 21:06 UTC
#### Expected behaviour
Adding a rgba color to the list of colors the chart uses shouldn't add duplicate attributes to SVG elements. Attributes should be unique per element.

#### Actual behaviour
For area charts, if you have a custom set of colors for the chart that contain a rgba color, highcharts ends up adding a fill-opacity attribute to a path element in the charts SVG data. The path element it adds it to has another fill opacity attribute on it already (appears to be the default one). The old fill opacity attribute should be overriden/removed.

I believe it only occurs on area charts because you're adding your own opacity to them since they overlap, but you probably aren't doing that on other charts?

#### Live demo with steps to reproduce
template: http://jsfiddle.net/dqtf48ot/1/

Steps to recreate the issue on your own:
1. Create a generic chart that is an area chart
2. Add a custom set of colors for the chart to use. Include an RGBA color in this set.
3. Use getSVG() on the chart to see that it includes the default opacity of 0.75 and the opacity of the RGBA color on two separate fill-opacity attributes on the same <path> element.

Steps to see the issue in the outputted SVG:
1. Run the js fiddle
2. Check the console for the result of getSVG()
3. Paste into your favorite text editor and ctrl + f for "fill-opacity".
4. You'll see that one particular <path> element has a fill-opacity=0.75 and a fill-opacity=0.80. They're separated by a fair bit of data, but they're definitely on the same <path> tag.

#### Affected browser(s)
Affects all browsers, but I only noticed it blowing up on area charts.

**Comment by jon-a-nygaard** [comment] 2016-08-10 11:13
@smithk58 This seems like a duplicate of https://github.com/highcharts/highcharts/issues/5366. Please follow the mentioned issue number to get more information and updates.

**Closed by jon-a-nygaard** 2016-08-10 11:13 UTC
