### ISSUE TITLE
plotBand zIndex doesn't work as expected (relative to series zIndex)

### ISSUE THREAD

**Issue by drmrbrewer** [highcharts/highcharts#6336] opened 2017-02-05 19:18 UTC
As commented in the fiddle below, setting a zIndex for a `plotBand` that is less than the `zIndex` of a line doesn't always place it under that line:

http://jsfiddle.net/r3Lzjjz6/

**Comment by drmrbrewer** [comment] 2017-02-05 19:20
This seems to be a duplicate of [this issue](https://github.com/highcharts/highcharts/issues/3321) which has be "undecided" for over two years.  (Freaky but even the example jsFiddle is almost exactly the same as mine.)

Surely one would expect the zIndex of any feature to work as expected relative to any other feature, whether between lines or between a line and a plotBand?

Is this still "undecided"?

**Comment by TorsteinHonsi** [comment] 2017-02-07 13:43
Thanks for writing. Marking this a duplicate of #3321, see my drop-in workaround there.

**Closed** 2017-02-07 13:43 UTC
Labels: Duplicate
