### ISSUE TITLE
Sunburst - DataLabels position after `F5`

### ISSUE THREAD

**Issue by Wolf2323** [highcharts/highcharts#17053] opened 2022-03-04 09:22 UTC
The DataLabel is of the center of the sunburst chart is not at the right position after pressing `F5`

#### Expected behaviour
The expected behaviour is that the DataLabel is in the center of the chart:
![image](https://user-images.githubusercontent.com/4036106/156734698-01af06fa-618f-4703-a427-055efccf8a4c.png)

#### Actual behaviour
The DataLabel of the center item is at the left side of the chart
![image](https://user-images.githubusercontent.com/4036106/156734856-7b5bbafd-d17d-44aa-b165-10487b144dcf.png)

#### Live demo with steps to reproduce
I was not able to reproduce it in jsfiddle, i think it could be related to my setup.
I am using `Quasar Framework` with `Vue`, but i can share my class that created this chart

```java
<template>
  <q-card>
    <highcharts :options="chartOptions" />
  </q-card>
</template>

<script>
import Highcharts from "highcharts";
import HighchartsSunburst from "highcharts/modules/sunburst";
import { Chart } from "highcharts-vue";
import { Dark } from "quasar";
import { format } from "quasar";
const { humanStorageSize } = format;

HighchartsSunburst(Highcharts);

export default {
  components: {
    highcharts: Chart,
  },
  props: {
    folderName: String,
  },

  computed: {
    chartData: function () {
      const folderNames = this.$store.getters["store/getFolderNames"];
      const data = [];
      data.push({
        id: "0",
        parent: "",
        name: folderNames.length + "<br>" + this.$t("Folders"),
        color: "transparent",
      });
      for (const folderNumber in folderNames) {
        const folderName = folderNames[folderNumber];
        const folder = this.$store.getters["store/getFolderByName"](folderName);

        data.push({
          id: folderName,
          parent: "0",
          name: folderName,
          tooltipMeta: {
            folderName: this.folderName,
            name: folderName,
            size: this.getHumanStorageSize(folder.size),
            files: folder.files + " " + this.$t("File"),
          },
          color: Highcharts.getOptions().colors[folderNumber % Highcharts.getOptions().colors.length],
        });

        if (this.folderName == undefined || this.folderName !== folderName) {
          const avgFileSize = folder.size / folder.files;
          for (var i = 0; i < folder.files; i++) {
            data.push({
              id: folderName + "." + i,
              parent: folderName,
              name: " ",
              value: avgFileSize,
              tooltipMeta: {
                folderName: this.folderName,
                name: folderName,
                size: this.getHumanStorageSize(folder.size),
                files: folder.files + " " + this.$t("Flies"),
              },
            });
          }
        } else {
          const files = this.$store.getters["store/getActiveFolderFiles"];
          if (files) {
            for (var fileKey in files) {
              const file = files[fileKey];
              data.push({
                id: folderName + "." + fileKey,
                parent: folderName,
                name: file.id,
                value: file.size,
                tooltipMeta: {
                  folderName: this.folderName,
                  name: file.id,
                  size: this.getHumanStorageSize(file.size),
                },
              });
            }
          }
        }
      }
      return data;
    },
    chartOptions: function () {
      let darkColor;
      if (Dark.isActive) {
        darkColor = "#1d1d1d";
      }
      return {
        chart: {
          plotBackgroundColor: null,
          plotBorderWidth: null,
          plotShadow: false,
          backgroundColor: darkColor,
        },
        title: { text: "" },
        credits: { enabled: false },
        series: [
          {
            rootId: this.folderName == "" ? "0" : this.folderName,
            type: "sunburst",
            data: this.chartData,
            events: {
              click: this.switchFolderView,
            },
            allowTraversingTree: true,
            cursor: "pointer",
            dataLabels: {
              format: "{point.name}",
              rotationMode: "circular",
            },
            levels: [
              {
                level: 1,
                levelIsConstant: false,
                levelSize: {
                  unit: "percentage",
                  value: 30,
                },
                dataLabels: {
                  style: {
                    textOverflow: undefined,
                  },
                },
              },
              {
                level: 2,
                colorByPoint: true,
                dataLabels: {
                  filter: {
                    property: "outerArcLength",
                    operator: ">",
                    value: 32,
                  },
                },
                levelSize: {
                  unit: "weight",
                  value: 1,
                },
              },
              {
                level: 3,
                colorVariation: {
                  key: "brightness",
                  to: 0.3,
                },
                levelSize: {
                  unit: "percentage",
                  value: 20,
                },
              },
            ],
          },
        ],
        tooltip: {
          formatter: function () {
            const point = this.point;
            if (point.id == 0) {
              return false;
            }
            const meta = point.tooltipMeta;
            if (!meta.folderName) {
              return "<b>" + meta.name + "</b><br>" + meta.size + "<br><i>" + meta.files + "</i>";
            }
            if (meta.folderName == point.name) {
              return false;
            }
            return "<b>" + meta.name + "</b><br>" + meta.size + "<br>";
          },
        },
      };
    },
  },
  methods: {
    switchFolderView(event) {
      const point = event.point.name;
      const pointId = event.point.id;
      if (!this.folderName && pointId != 0 && point != " ") {
        this.$router.push("/folders/" + point);
      } else if (this.folderName == point) {
        this.$router.push("/folders");
      }
    },
    getHumanStorageSize(size) {
      if (size) {
        return humanStorageSize(size);
      }
      return "";
    },
  },
};
</script>

<style scoped>
*::v-deep .highcharts-drillup-button {
  display: none;
}
</style>

```

#### Product version
highcharts `9.3.3`
highcharts-vue `1.4.0`
vue `3.2.30`
quasar `2.3.3`

#### Affected browser(s)
We tested it in `Chrome`, `Firefox` and `Edge`

**Comment by raf18seb** [comment] 2022-03-04 10:38
Hi @Wolf2323, thanks for reporting a problem!

Unfortunately, I wasn't able to reproduce it either in Vue and pure JS. Could you provide more info or try to somehow reproduce it in an online code editor, e.g. codesandbox? You can base on this: https://codesandbox.io/s/highcharts-vue-demo-ttner

**Comment by Wolf2323** [comment] 2022-03-04 13:18
During a longer try of reproducing the issue, i could find out the problem:

I use VueX to store my data, and the data is changing live ( hard to reproduce in codesandbox ). When i did `F5` there is first no data, so my method  `chartData` only returns an array with the root point. When the data changes in the VueX store the chart automatically load this data. But as the data before was not valid, the bug above appeared.

My opinion is, that my input for Highchart was not 100% valid, and so it makes sens, and i was able to fix it by returning an empty array if no data exist. At the same time i think Highchart should be able to handle this.

I am fine if this gets closed, but i leave the decision to you.


If you still want more information, i would also be opened to still help.

**Comment by pawellysy** [comment] 2022-03-07 12:04
Closing, since this issue is not highcharts related. Thanks!

**Closed by pawellysy** 2022-03-07 12:04 UTC
Labels: Status: Can't reproduce, Status: Pending reply
