### ISSUE TITLE
Highcharts distorsion with Chrome

### ISSUE THREAD

**Issue by gberengueras** [highcharts/highcharts#16608] opened 2021-11-08 08:05 UTC
#### Expected behaviour
Resize without distorsion.

#### Actual behaviour
When the graph is enlarged or loaded to width 1727px or more the graph starts to distort.
[Image](https://i.imgur.com/kWJxnud.png)

#### Live demo with steps to reproduce
[What i see](https://i.ibb.co/xzJFLqK/chrome-capture-3.gif)
[JSFiddle](https://jsfiddle.net/wqdhk1x3/)

#### Product version
Highcharts: I tested from 5.0.9 to last version (js fiddle is with last version)

#### Affected browser(s)
I'm working with Highcharts and JQuery. 
Using a 16-inch MacBook Pro and Chrome version 95.0.4638.54 (Official Build) (x86_64). 
This error occurs with Google Chrome. However Safari and Firefox work well.

**Comment by raf18seb** [comment] 2021-11-09 12:01
Hi @gberengueras, thanks for reporting the issue!

I actually don't see it all the time (like on the video you provided), but I can see unexpected flickering
![flicker-bug2](https://user-images.githubusercontent.com/23310742/140893663-744b48f2-5e69-4761-bba0-c6e048848b7a.gif)

Simplified demo: https://jsfiddle.net/BlackLabel/9t5pweqh/
Simplified demo with SVG only: https://bugs.chromium.org/p/chromium/issues/detail?id=1268368

Looks like a Chromium bug. I reported it here: https://bugs.chromium.org/p/chromium/issues/detail?id=1268368

**Comment by jlally21** [comment] 2021-11-10 00:34
Any updates or workarounds for this?  Experiencing a similar issue, but difficult to reproduce.

**Comment by jlally21** [comment] 2021-11-10 00:52
I found a similar issue reported here in the past: https://github.com/highcharts/highcharts/issues/7662
Based off the discussion and suggested workarounds in issue [7662](https://github.com/highcharts/highcharts/issues/7662), I recently added the following:
`linecap: square`  to `plotOptions.line.linecap`

https://api.highcharts.com/class-reference/Highcharts#.SeriesLinecapValue

**Comment by raf18seb** [comment] 2021-11-10 12:06
Looks like a duplicate of https://github.com/highcharts/highcharts/issues/16452

This is more a browser SVG bug, not Highcharts itself. As far as I know, it will be fixed in the next Chrome v96 version

**Comment by KacperMadej** [comment] 2021-11-15 18:02
Fixed since Chrome v96

**Closed by KacperMadej** 2021-11-15 18:02 UTC
Labels: Type: Bug, Type: Duplicate
