### ISSUE TITLE
highstock.chart.series set to null on initialization

### ISSUE THREAD

**Issue by dbasner** [highcharts/highcharts#5678] opened 2016-09-12 18:30 UTC
When a highstock chart is initialized with a chart configuration object, chart.series is set to null after the chart is created, even if there is series data there.  This becomes an issue when you want to update the chart objects data and then redraw it, because you need to create a copy of the data every time instead of just re-using the same (updated) object.

if we have functions that look like these, the issue arises.

```
var resizeChart = function(size){
scope.highchartConfig.chart.height=calcNewSize(size,chartType);
createChart();
}

var createChart() = function(){
//.....
element.find('div').highcharts('StockChart', scope.highchartConfig);
}
```

If we first call createChart to draw the chart, but later call resizeChart to modify the charts configuration and redraw it, the series object inside highchartConfig is set to null.  When it then tries to redraw it, the chart is blank since there is no series data.

Why do highstock charts set the value of series to null after configuration.

**Comment by pawelfus** [comment] 2016-09-13 08:41
Hi @dbasner  - thank you for reporting the issue! This is a duplicate of #636. Please, try out http://github.highcharts.com/bugfix/highstock.src.js and let us know about the results.

**Closed by pawelfus** 2016-09-13 08:41 UTC

**Comment by miguel-orange** [comment] 2016-12-09 17:31
@pawelfus,
I'm using version 5.0.6 and highmaps has the same behavior.
