### ISSUE TITLE
Subtitle positioning with useHtml -- something broke in 6.0.5

### ISSUE THREAD

**Issue by drmrbrewer** [highcharts/highcharts#7795] opened 2018-02-05 08:56 UTC
Subtitle (with `useHTML` set to `true`) positions as expected in 6.0.4 : http://jsfiddle.net/w00mpqd5/

But not in 6.0.5 : http://jsfiddle.net/kqabuqxw/

According to the [changelog](https://www.highcharts.com/documentation/changelog) it looks like there were a few `useHTML`-related changed in 6.0.5, and this seems this might have broken things (or at least caused a change in behaviour I don't yet understand).

**Comment by DCIP** [comment] 2018-02-05 10:28
This is also happening with the main title.  It is most obvious when using align right, as the title goes partly of the right side.  [http://jsfiddle.net/yzutksz9/](http://jsfiddle.net/yzutksz9/)

**Comment by pawelfus** [comment] 2018-02-05 11:07
Hi @drmrbrewer  and @DCIP - thank you for reporting the issue. It's a duplicate of #7787

**Closed by pawelfus** 2018-02-05 11:07 UTC
