### ISSUE TITLE
Behavior oh column chart with datagrouping/datetime xAxis on setExtremes

### ISSUE THREAD

**Issue by LouisonGitzinger** [highcharts/highcharts#5531] opened 2016-07-25 16:27 UTC
Hi, first, thank you for making Highchart such an amazing tool
#### Expected behaviour

I'm collecting events on irregular times. An event can appear at any second in a period.
Each event is a point on my column chart. 
On my chart, it is possible to set the XAxis extremes from included highchart mouse zoom, or manually with two input datepickers.
It has to be possible to see an entire year on the chart, but also, a month, a week, a day, an hour, a minute, a second.
So datagrouping option is great for doing the job.
#### Actual behaviour

When i'm zooming on the chart and one of the extremes is on a column (hard to explain that, when a column is cropped by the zoom), the new column processed has the same size as other columns, but it doesn't contain all the point of the actual datagrouping units.

For example, datagrouping is set to : units [['day', [1]], if I zoom between the two extremes of a column, I will still have a column of one day, but only the points selected in my zoom into it.

Here is a fiddle : https://jsfiddle.net/hp8zn4f3/
1. check number of 'passed' values on the right column,
2. Zoom on half the right column, 
3. Check again the number of passed values

All browsers affected

thank in advance for your answer, 
best

**Comment by TorsteinHonsi** [comment] 2016-07-27 06:57
Thanks for writing!
I suspect that results are clipped away when you zoom in, so that if you zoom in the half the day, the group column will only show runs for that half. Does that match what you see?

**Comment by LouisonGitzinger** [comment] 2016-07-27 10:04
Yes exactly !
So the new result column contains only half of the points of the day, but it still takes an entire day on the chart (even if grouped points into this column are in the first half of the day). 

Even if the rendering is not false in itself, after a zoom on half a column, i can't be sure there are all the points of the day (represented by the column) grouped in this column.

I tried to set a minRange on x axis (like a one day minRange), but it is still possible to zoom on half column.
I wonder if it would not be a problem of regular tick intervals..


Thank you for replying quickly !

**Comment by pawelfus** [comment] 2018-03-20 16:36
Related ticket: #5344 and PR: #8049

Closing as duplicate of #5344

**Closed by pawelfus** 2018-03-20 16:36 UTC
