### ISSUE TITLE
bug in drillgown when using highstock

### ISSUE THREAD

**Issue by smj-hosseini** [highcharts/highcharts#7846] opened 2018-02-12 07:47 UTC
hi
i reported this bug at  #7817 with highcharts and now i faced again this bug when i use highstock
when using both highstock and drilldown together, extra data that not exist in data series shows in chart. but when i click again on same bar, extra data  not exist again.
go to this jsfiddle link and follow the below steps to see the bug:
jsfiddle link: http://jsfiddle.net/cjjm3xjL/
first: click on "microsoft internet explorer" bar and go back,
second: click on "safari" bar, and now you see this bug
my issue is after click on "safari" bar there is a extra and unusable data on "safari" chart. this extra data mark as '4' on x-axis that not in data series for "safari" chart.

Highstock version: Highstock JS v6.0.6 
browser name(s) and version: firefox quantum 58.0.1(64bit)

**Comment by pawelfus** [comment] 2018-02-12 11:13
Hi @smj-hosseini 

It's a duplicate of #7817 : http://jsfiddle.net/BlackLabel/cjjm3xjL/1/ (v6.0.4 works fine).

**Closed by pawelfus** 2018-02-12 11:13 UTC
