### ISSUE TITLE
0 values cut off on splie chart

### ISSUE THREAD

**Issue by mbaudry** [highcharts/highcharts#6604] opened 2017-04-18 07:32 UTC
It's a duplicate of old tickets https://github.com/highcharts/highcharts/issues/2148 and https://github.com/highcharts/highcharts/issues/1687 where we can see that "0" values are cut off on a spline chart. I tried all the suggested solutions, but none worked... (xAxis to 0, clip to false remove the animation, etc.).

http://jsfiddle.net/NkV5b/8/ a fiddle to illustrate the problem.

Does anyone have a solution for this issue ?

Thanks a lot !

**Comment by pawelfus** [comment] 2017-04-18 10:13
Solution with `series.clip` works fine, please take a look: http://jsfiddle.net/NkV5b/9/

**Comment by mbaudry** [comment] 2017-04-18 10:26
Hi,

Yes it works, but it removes the animation when we create the chart, and I need it.

**Comment by pawelfus** [comment] 2017-04-18 12:31
Right, my apologies I misread your post. Simple workaround for you: http://jsfiddle.net/NkV5b/11/

Snippet:
```javascript
Highcharts.wrap(Highcharts.Chart.prototype, 'setChartSize', function(proceed) {

  proceed.apply(this, Array.prototype.slice.call(arguments, 1));

  this.clipBox.height += 1; // increase height of the clip box by 1px
});
```

**Comment by mbaudry** [comment] 2017-04-18 12:35
Ok thanks a lot !

But, just for information, will the problem be corrected for the next version ??

**Comment by pawelfus** [comment] 2017-04-18 12:39
I don't think so. I just found it's a duplicate of #6225.

**Closed** 2017-04-18 12:39 UTC
Labels: Duplicate
