### ISSUE TITLE
Highmaps - Updating the series in allAreas: false results in the wrong area being rendered

### ISSUE THREAD

**Issue by zoltan-makranczi-anaplan** [highcharts/highcharts#17013] opened 2022-02-17 17:12 UTC
#### Expected behaviour
Setting a new series for HighCharts should be reflected correctly in the browser.

#### Actual behaviour
The dataLabels are updated, but the actual shape of the area remains the same.
Note: this works, if the count in the series changes (hence, in the linked CodeSandbox, switching to/from "USA + Mexico" works, but any switch that doesn't involve that, will fail)

#### Live demo with steps to reproduce
https://codesandbox.io/s/hc-map-switching-countries-16lqxl?file=/src/Demo.jsx

#### Product version
* highcharts@9.3.2 & highcharts-react-official@3.1.0 (for example)
Note: this used to work in highcharts@9.0.1

#### Affected browser(s)
All

**Comment by raf18seb** [comment] 2022-03-03 10:39
Hi @zoltan-makranczi-anaplan, thank you for reporting a bug. I apologize for the late reply, we missed this ticket in notifications.

Simplified pure JS demo: https://jsfiddle.net/BlackLabel/o21L8w4m/
Broken since 9.3.0, works fine in 9.2.2

Possible duplicate or related to https://github.com/highcharts/highcharts/issues/16782 (not closing as a duplicate yet)

**Comment by TorsteinHonsi** [comment] 2022-05-18 07:56
Status as of today: It looks like the data itself is handled correctly, but the bounds are not. When clicking any of the buttons, apparently the bounds are influenced by the previously viewed country. By clicking the same button twice, the bounds are correct.

**Comment by raf18seb** [comment] 2022-05-18 08:16
So it's more like a duplicate of https://github.com/highcharts/highcharts/issues/17012, isn't it?

**Comment by TorsteinHonsi** [comment] 2022-05-18 08:51
Yes, actually they may be the same issue.

**Closed** 2022-05-19 07:48 UTC
Labels: Product: Highcharts Maps, Type: Regression
