### ISSUE TITLE
Zones with steps produces overlapping lines

### ISSUE THREAD

**Issue by cargarn** [highcharts/highcharts#10095] opened 2019-02-08 09:39 UTC
#### Expected behaviour

I would like to avoid the overlapping lines when using zones in a "line" chart with steps ("right" or "left").

#### Actual behaviour

![image](https://user-images.githubusercontent.com/9210767/52470260-ee4e4200-2b8d-11e9-8a6d-67ca08fecb23.png)

**Comment by pawelfus** [comment] 2019-02-08 10:16
Hi @cargarn 

Thank you for reporting the issue. Please check #4503 ticket - it's a general issue with current zones implementation. 

Demo: https://jsfiddle.net/BlackLabel/67w3va1y/2/

Closing as duplicate of #4503.

**Closed by pawelfus** 2019-02-08 10:16 UTC
Labels: Duplicate
