### ISSUE TITLE
Drilldown event doesn't work in bubble chart

### ISSUE THREAD

**Issue by stpoa** [highcharts/highcharts#6748] opened 2017-05-19 13:56 UTC
#### Expected behaviour
After clicking you should see drilldown message in console.

#### Actual behaviour
After clicking there is no message in js console.

#### Live demo with steps to reproduce
http://jsfiddle.net/9hzb8L6u/ - 5.0.11
http://jsfiddle.net/9hzb8L6u/1 - 5.0.10 (Works as expected)

1. Click on any bubble
2. Notice there is no message in your browsers console

Could be related to: https://github.com/highcharts/highcharts/issues/6695

**Comment by pawelfus** [comment] 2017-05-22 08:18
It's a duplicate of #6705

Already fixed on them aster branch: http://jsfiddle.net/9hzb8L6u/2/

**Closed by pawelfus** 2017-05-22 08:18 UTC
