### ISSUE TITLE
Highcharts-more and map module

### ISSUE THREAD

**Issue by vipera** [highcharts/highcharts#6819] opened 2017-06-09 09:49 UTC
Hi,

it seems that including highcharts-more and the highmaps map module on the same page causes an error saying that the bubble series type is already defined (mislabeled as error 27).

This started happening with the new 5.0.12 version.

#### Live demo with steps to reproduce
https://jsfiddle.net/cpbfuhx2/

Check out the browser console for the error log message.

Removing either modules/map.js or highcharts-more.js from the fiddle prevents the problem.

#### Affected browser(s)
Chromium 58

**Comment by pawelfus** [comment] 2017-06-09 10:13
Hi @vipera 

Thank you for reporting. This error will be removed in 5.0.13 version.

Duplicate of #6686 ( https://github.com/highcharts/highcharts/issues/6686#issuecomment-303679281 )

**Closed by pawelfus** 2017-06-09 10:13 UTC
