### ISSUE TITLE
Narrator + Edge in Scan Mode requires pressing Down twice before first chart element is focused

### ISSUE THREAD

**Issue by JllyGrnGiant** [highcharts/highcharts#9411] opened 2018-11-15 09:46 UTC
#### Expected behaviour
First press of down should focus on first element of chart

#### Actual behaviour
A rectangle is displayed around the y-axis and Narrator says "blank".
![repro](https://user-images.githubusercontent.com/1325800/48544026-9ac2a580-e877-11e8-8014-3babd79a4ee9.png)

#### Live demo with steps to reproduce
Used the highcharts accessible line chart demo (at version 6.2.0 at the time this issue was filed)
https://www.highcharts.com/samples/highcharts/accessibility/accessible-line/

1. Navigate to the demo
2. Turn on Narrator
3. Tab to the chart focus
4. Ensure Narrator is in scan mode (CAPS LOCK + Space bar if Narrator isn't already in scan mode)
5. Press "down" arrow key once

#### Product version
Highcharts 6.2.0

#### Affected browser(s)
Edge

**Comment by JllyGrnGiant** [comment] 2018-11-15 09:58
This might also be related to a second issue.
When you press the "up" arrow key the focus square doesn't change, but the announced data is the data point that comes before the focused point.

**Comment by KacperMadej** [comment] 2018-11-15 15:19
Hi @JllyGrnGiant 

Thank you for reporting about the problem.

@oysteinmoseng - accessibility module issue

**Comment by oysteinmoseng** [comment] 2018-12-19 14:00
This looks to be a duplicate of #8637. @JllyGrnGiant, could you verify if the workaround from that issue helps with your use case?

**Comment by oysteinmoseng** [comment] 2019-02-21 17:17
Seems to be fixed with upcoming v7.1 release.

**Closed by oysteinmoseng** 2019-02-21 17:17 UTC
Labels: Pending reply
