### ISSUE TITLE
[Accessibility] Reading order is not as expected while using a screen reader on Heatmap.

### ISSUE THREAD

**Issue by magdalena-gut** [highcharts/highcharts#16758] opened 2021-12-06 10:08 UTC
#### Expected behaviour
Reading should start from the first point (0,0) and continue in the correct order.

#### Actual behaviour
The screen reader ignores the first square at (0,0), starts at square (0,1), and continues reading in the correct order. Once it hits the last square, it goes back and finally reads the first square as though it is the last data point in the series.

#### Demo
https://www.highcharts.com/demo/heatmap

#### Product version
Highcharts 9.3.2

#### Affected screen readers
VoiceOver
(NVDA with Google Chrome and Firefox work correctly.)

**Comment by oysteinmoseng** [comment] 2021-12-06 14:56
Internal note: Caused by https://github.com/highcharts/highcharts/issues/13049

**Comment by oysteinmoseng** [comment] 2021-12-07 08:56
Will close this as duplicate, follow #13049 for updates

**Closed by oysteinmoseng** 2021-12-07 08:56 UTC
Labels: Type: Bug, a11y
