### ISSUE TITLE
Zooming broken after exporting via context menu

### ISSUE THREAD

**Issue by mediafreakch** [highcharts/highcharts#15886] opened 2021-06-11 06:59 UTC
#### Expected behaviour

Zooming works even after exporting

#### Actual behaviour

Zooming is broken after exporting

![5c2eb47350562f65ed3cc669a1c10854](https://user-images.githubusercontent.com/777093/121644453-4c0f3380-ca93-11eb-8009-339ff46fd04e.gif)

#### Live demo with steps to reproduce

https://jsfiddle.net/1zjs8Lpt/1/

1. Zoom into the any area of the chart
2. Export as jpg (or any other) via context menu
3. Zoom into a different area on the chart

#### Product version

9.1.1

#### Affected browser(s)

Chrome 91

**Comment by khlieng** [comment] 2021-06-11 08:23
Fixed by #15850, duplicate of #15845.

**Closed by khlieng** 2021-06-11 08:23 UTC
Labels: Type: Duplicate
