### ISSUE TITLE
Error while Dragging and updating series containing records of same values

### ISSUE THREAD

**Issue by mahesha-perpetualny** [highcharts/highcharts#13414] opened 2020-05-01 09:22 UTC
#### Expected behaviour
Should be able to move items And update series of a bubble chart regardless of its values

#### Actual behaviour
On moving item of a series containing item of same X OR Y co-ordinates on Drag Event, getting errors while updating a series and also while moving cursor inside a chart after that.
![image](https://user-images.githubusercontent.com/60252612/80795239-9009e680-8bb9-11ea-96ba-8952d6859ff9.png)

#### Live demo with steps to reproduce
Student 7 and student 8 is having same X Coordinate Value.
**getting Error when we move the item for 'student 8' directly and also unable to move that item.** (See the console)
not getting error when we move 'Student 7' first and then 'Student 8'
http://jsfiddle.net/maheshauti_00/9hu5gbjw/17/

**Comment by sebastianbochan** [comment] 2020-05-01 11:57
Hi @mahesha-perpetualny,
Thank you for reporting about the problem.

Could you elaborate what is the reason of duplicate points in drag? 

In the update `...serie` is not "native" array of points, but references to existing points.

**Comment by mahesha-cuelogic** [comment] 2020-05-01 12:42
@sebastianbochan My use case Example,  I want the student to set a target position for their next semester in a class.
For that, When the first drag event is triggered, I want to keep a copy of the dragged bubble/point to its old position and let the user move the original bubble to another position .
that why my drag event is
`drag: function (e)
{
const copiedObj = chart.userOptions.series[0].data.find(
  (i) => i.copied && i.name === e.target.name
);
if (!copiedObj) {
  chart.update(
    {
      series: [
        {
          color: {
            linearGradient: {
              x1: 0,
              x2: 0,
              y1: 0,
              y2: 1,
            },
            stops: [
              [0, "#FED840"],
              [1, "#FFB351"],
            ],
          },
          type: "bubble",
          cursor: "move",
          data: [
            ...JSON.parse(JSON.stringify(series)),
            {
              x: e.target.x,
              y: e.target.y,
              z: e.target.z,
              name: e.target.name,
              copied: true,
            },
          ],
        },
      ],
    },
    true,
    true
  );
}
}`

It's working when points have unique X and Y values. as you can see other points in my code http://jsfiddle.net/maheshauti_00/9hu5gbjw/17/
except (Student 7 and student 8 having the same X value = 0).

when X or Y value gets the same value those points (except 1st from that set of items) are not dragging to another position. they are throwing error while dragging. (Student 8 in my example)

**Comment by mahesha-perpetualny** [comment] 2020-05-01 12:59
@sebastianbochan My use case Example,  I want the student to set a target position for their next semester in a class.
For that, When the first drag event is triggered, I want to keep a copy of the dragged bubble/point to its old position and let the user move the original bubble to another position .
that why my drag event is
`drag: function (e)
{
const copiedObj = chart.userOptions.series[0].data.find(
  (i) => i.copied && i.name === e.target.name
);
if (!copiedObj) {
  chart.update(
    {
      series: [
        {
          color: {
            linearGradient: {
              x1: 0,
              x2: 0,
              y1: 0,
              y2: 1,
            },
            stops: [
              [0, "#FED840"],
              [1, "#FFB351"],
            ],
          },
          type: "bubble",
          cursor: "move",
          data: [
            ...JSON.parse(JSON.stringify(series)),
            {
              x: e.target.x,
              y: e.target.y,
              z: e.target.z,
              name: e.target.name,
              copied: true,
            },
          ],
        },
      ],
    },
    true,
    true
  );
}
}`

It's working when points have unique X and Y values. as you can see other points in my code http://jsfiddle.net/maheshauti_00/9hu5gbjw/17/
except (Student 7 and student 8 having the same X value = 0).

when X or Y value gets the same value those points (except 1st from that set of items) are not dragging to another position. they are throwing error while dragging. (Student 8 in my example)

pasting a video link here if in case you are not able to reproduce the exact problem:
https://www.loom.com/share/cbdbec9953944f8b89850c5196c21633

**Comment by sebastianbochan** [comment] 2020-05-04 09:41
Hi @mahesha-perpetualny,
Thank you for the feedback. The problem here is really complex, let me list all issues below:
- the used module is not up-to-date, so you need to use the newest: 
    - https://code.highcharts.com/modules/draggable-points.js
- you should use [`addPoint`](https://api.highcharts.com/class-reference/Highcharts.Series#addPoint), instead of creating multiple references to a new point on update.
- the `chart.update()` and "duplicate of point" should be called once, not multiple time like the `drag event` is called. The solution is the [dragStart](https://api.highcharts.com/highcharts/series.line.point.events.dragStart)

Demo:
- http://jsfiddle.net/BlackLabel/9q5pvykm/

Im closing the ticket as not a bug.

**Closed by sebastianbochan** 2020-05-04 09:41 UTC
Labels: Status: Pending reply
