### ISSUE TITLE
Solid gauge doesn't max out

### ISSUE THREAD

**Issue by tomsommer** [highcharts/highcharts#6973] opened 2017-07-17 14:35 UTC
Setting `min: 0`, `max: 1024` and `value: 1024` doesn't max out the graph

http://jsfiddle.net/8xyrfoxw/

**Comment by sebastianbochan** [comment] 2017-07-17 14:48
Duplicate of https://github.com/highcharts/highcharts/issues/6971

**Closed by sebastianbochan** 2017-07-17 14:48 UTC

**Comment by tomsommer** [comment] 2017-07-17 15:27
Are you sure? It's a different issue - through the root cause could be the same.

**Comment by pawelfus** [comment] 2017-07-18 09:17
I don't think it's a bug. As you can see in your demo, max for yAxis is 1200. Simply Highcharts algorithm for tick positions calculates ticks with base=10. I mean 1024 is not a round number, so it will not be rendered unless we tell Highcharts to do that, for example using [`tickPositioner`](http://api.highcharts.com/highcharts/yAxis.tickPositioner) or [`tickPositions`](http://api.highcharts.com/highcharts/yAxis.tickPositions), demo with tickPositions: http://jsfiddle.net/on9ggz9n/

**Comment by tomsommer** [comment] 2017-07-18 09:23
This should be a default with `solidgauge` then?

**Comment by pawelfus** [comment] 2017-07-18 10:00
I think the current solution works pretty good and resolves most of the cases with an opportunity to change in other cases (like yours). Additionally, I think its more important to keep docs consistent, not making them harder with exceptions.

**Comment by tomsommer** [comment] 2017-07-18 10:06
A gauge would always want to go to the max and not round the ticks? It makes no sense not being able to 'fill' the gauge to the set limit by default.
