### ISSUE TITLE
Zoom on waterfall chart breaks with large dataset

### ISSUE THREAD

**Issue by KevinShiCA** [highcharts/highcharts#8459] opened 2018-06-12 14:19 UTC
#### Expected behaviour
Zoom works the same as other chart types.

#### Actual behaviour
- Bars sometimes disappear
- Only the connecting dots are left in random order
- Resetting zoom sometimes restores the bars in an incorrect order

#### Live demo with steps to reproduce
Fiddle: https://jsfiddle.net/fnq2bx4s/1/
Reproduce by zooming twice in any area.

#### Product version
Highcharts version 6.1.0.

#### Affected browser(s)
Chrome, Firefox, Edge

**Comment by sebastianbochan** [comment] 2018-06-13 09:07
Hi @KevinShiCA,
Thank you for reporting.

The issue is related with missing `cropThreshold` parameter.

Fixed demo:
- https://jsfiddle.net/5o97sqw2/

Duplicate of https://github.com/highcharts/highcharts/issues/6926

**Closed by sebastianbochan** 2018-06-13 09:07 UTC
