### ISSUE TITLE
Highstocks series.data not working with objects

### ISSUE THREAD

**Issue by Trivette1** [highcharts/highcharts#11177] opened 2019-06-26 12:28 UTC
#### Expected behaviour
Highstocks series is valid in the following format:

series: [{
  name: 'Test',
  data: [
{x: 1, y: 2}, {x: 2, y: 7}]
}]

What I want to do is setting the marker radius for each point.
eg:
series: [{
  name: 'Test',
  data: [
{x: 1, y: 2, marker: {radius: 5}}, {x: 2, y: 7, marker: {radius: 2}}]
}]

#### Actual behaviour
With this data format, nothing is shown.

The chart is only working with following data format:
series: [{
  name: 'Test',
  data: [
[1,2], [2,7]]
}]

#### Product version

v 7.0.3 highstocks combined with angular-highcharts v7.1.0
#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment] 2019-06-26 13:16
Hi @Trivette1 

Thanks for reporting the issue. With your options, chart is rendered correctly for me, please take a look: https://jsfiddle.net/BlackLabel/sr2oeuc8/ 

Markers are not rendered because you need to first enable them: https://jsfiddle.net/BlackLabel/egnqbcm6/

If you still encounter the issue, please provide **Live demo with steps to reproduce**. Thanks!

**Comment by Trivette1** [comment] 2019-06-27 06:54
Hi pawelfus,
I tried your solution and now it works as expected. Don't know, why it wasn't working before. 
Thanks for your support

**Comment by pawelfus** [comment] 2019-06-27 08:51
Ok, thanks for the confirmation! Closing the issue then.

**Closed by pawelfus** 2019-06-27 08:51 UTC
Labels: Status: Can't reproduce, Status: Pending reply
