### ISSUE TITLE
Update xAxis tooltip

### ISSUE THREAD

**Issue by bharatnagdev** [highcharts/highcharts#9133] opened 2018-10-05 11:21 UTC
#### Expected behaviour
In scatter chart type on the xAxis tooltip it should display datetime as other chart types if xAxis is set to datetime format or else there should be an editable option for the xAxis tooltip same as other tooltip options.

#### Actual behaviour
displays series name on xAxis tooltip

#### Product version
Highcharts 6.1

**Comment by pawelfus** [comment] 2018-10-05 11:30
Hi @bharatnagdev 

Thank you for your suggestion! It's already reported on as #3552

Closing as duplicate of #3552

**Closed by pawelfus** 2018-10-05 11:30 UTC
