### ISSUE TITLE
chart.destroy() crashes if actively moving cursor over the chart during destruction. Error happens when using line and arearange on a single chart.

### ISSUE THREAD

**Issue by EmigrantDolphin** [highcharts/highcharts#20919] opened 2024-03-26 10:45 UTC
#### Expected behaviour
Should be able to move my cursor over the chart while it is being destroyed without crashing.

#### Actual behaviour
![image](https://github.com/highcharts/highcharts/assets/47285942/6be603e8-bcfd-41c8-adf2-c8479265bafa)

#### Live demo with steps to reproduce
I've created a loop for creation and destruction of the chart.
To reproduce the error, move your mouse cursor horizontally over the chart somewhat quickly. (A chart popup with info should be visible.)
It seems it only crashes when line and arearange series are used, but might also be crashing with other series. (It works with line/line, arearange/arearange)

https://jsfiddle.net/f2e03odr/

#### Product version
Highcharts, highcharts-more

#### Affected browser(s)
Chrome

**Comment by Erbenos** [comment] 2024-03-26 19:59
I can imagine setting pointer-events: none on the chart before attempting to destroy it could work.

**Comment by hubertkozik** [comment] 2024-03-28 07:57
Hi @EmigrantDolphin!
Indeed, this is a bug. You should be able to fully destroy the chart even, when any point is hovered. I've prepared a workaround for this issue. If you want to use it in your project before the official fix, all you have to do is copy-paste the IIFE function from the demo below.

**Workaround:** https://jsfiddle.net/BlackLabel/3mfjkLan/

**Comment by EmigrantDolphin** [comment] 2024-03-28 08:34
Thank you @hubertkozik !
This is a pleasant workaround since it can be encapsulated in the module where the problematic chart resides in. It will be so much easier to undo once the official fix is released :)

**Comment by hubertkozik** [comment] 2024-04-11 11:41
I've found that this issue has the same root cause as this one: https://github.com/highcharts/highcharts/issues/20560 I am closing this one as a duplicate, let's continue in the older GitHub issue.

**Closed by hubertkozik** 2024-04-11 11:41 UTC
Labels: Duplicate
