### ISSUE TITLE
PackedBubble craches with single datapoint

### ISSUE THREAD

**Issue by TonyHopland** [highcharts/highcharts#10231] opened 2019-02-28 11:36 UTC
#### Expected behaviour
PackedBubble should show a single bubble if only one datapoint is available

#### Actual behaviour
Highchart craches with message:
```
Uncaught TypeError: Cannot read property '3' of null
    at p.translate (highcharts-more.src.js:6760)
    at highcharts.src.js:28499
    at Array.forEach (<anonymous>)
    at a.Chart.renderSeries (highcharts.src.js:28498)
    at a.Chart.render (highcharts.src.js:28639)
    at a.Chart.firstRender (highcharts.src.js:28860)
    at a.Chart.<anonymous> (highcharts.src.js:26955)
    at a.fireEvent (highcharts.src.js:2634)
    at a.Chart.init (highcharts.src.js:26821)
    at a.Chart.getArgs (highcharts.src.js:26792)
```

#### Live demo with steps to reproduce
https://jsfiddle.net/tonyhopland/ahnLx87t/

#### Product version
7.0.3

#### Affected browser(s)
Tested in Chrome and Edge

**Comment by pawelfus** [comment] 2019-02-28 13:08
Hi @TonyHopland 

Thanks for reporting the issue. Actually it's a duplicate of #9700.

Closing as a duplicate.

**Closed by pawelfus** 2019-02-28 13:08 UTC
