### ISSUE TITLE
StickyTracking: false not resolved problem of ToolTip open new tooltip when we go to click link in tooltip in touch devices in line chart

### ISSUE THREAD

**Issue by khushahal-sharma** [highcharts/highcharts#12072] opened 2019-09-26 11:36 UTC
#### Expected behaviour
The chart should not open new tooltip(nearest series point)  on click/Hover of the tooltip area in line chart.

#### Actual behaviour
After Adding **stickyTracking: false**   
The line chart is opening new tooltip when going to click the link on tooltip area in touch devices.

#### Live demo with steps to reproduce

http://jsfiddle.net/4sfn8qhr/1/

#### Product version

 V 7.2.0 
#### Affected browser(s)
Chrome

@TorsteinHonsi @activist @goransle @pawelfus .

![HighChartIssue](https://user-images.githubusercontent.com/33281012/65686518-689eda00-e02a-11e9-8c39-23841a8dd3ed.gif)

**Comment by pawelfus** [comment] 2019-09-26 16:07
Hi @khushahal-sharma 

Thanks for reporting the issue. Is that issue any different from #5722? I'm not sure why `stickyTracking=false` should help here. What you achieve by setting this option is when tooltip should hide (which you definitively don't want - you won't be able to click on a tooltip that is hidden).

There is an alternative solution: instead of showing tooltip on mouseover, show it on click, take a look: http://jsfiddle.net/BlackLabel/h7j4cbgx/

**Comment by khushahal-sharma** [comment] 2019-09-27 06:07
@pawelfus Thanks for the suggestion. Yes it was same as #5722 .  The stickyTracking: false property was working differently on 4.2 vs 7.2 version that's why I tried to implement this.

**Comment by pawelfus** [comment] 2019-09-27 09:33
Ok, thanks for clarifying!

Closing as duplicate of #5722.

**Closed by pawelfus** 2019-09-27 09:33 UTC
