### ISSUE TITLE
Offline exporting: some unicode characters are incorrectly exported (PDF-only)

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#15454] opened 2021-04-07 08:23 UTC
#### Expected behaviour
All characters exported correctly (PNG/SVG/JPG versions) - see chart's title:

![downarrowbar-uparrowbar](https://user-images.githubusercontent.com/1453926/113834430-1dbb6200-978b-11eb-9c1b-12d96979320e.png)

#### Actual behaviour
Incorrect characters in PDF - see chart's title:

<img width="1063" alt="Zrzut ekranu 2021-04-7 o 10 22 43" src="https://user-images.githubusercontent.com/1453926/113834540-3af03080-978b-11eb-946e-de2655714db2.png">

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/jwsu2c49/

#### Product version
v9

**Comment by saurabh47** [comment] 2021-06-03 15:34
Facing same issue for **series data labels** on **PDF export**
JPEG , PNG & SVG export working correctly.
![image](https://user-images.githubusercontent.com/15173289/120670591-32c42100-c4ae-11eb-80f3-80911c20f870.png)
PDF export . see chart's data labels :
![image](https://user-images.githubusercontent.com/15173289/120670902-80408e00-c4ae-11eb-80cb-769110f9489c.png)

**Live demo with steps to reproduce**
https://jsfiddle.net/5rtckg39/16/

**Product version**
V9.1.0 

Is there any alternate version without this issue ?
or work around to fix this issue ?

Thanks

**Comment by KacperMadej** [comment] 2021-06-15 16:01
Workaround - disable shadows - demo: https://jsfiddle.net/BlackLabel/Lszop6m1/

**Comment by Aliaksandrsen** [comment] 2021-07-07 09:35
> Workaround - disable shadows - demo: https://jsfiddle.net/BlackLabel/Lszop6m1/


This solves the problem of duplicate outlined text. But invalid characters remain!
When disabled <script src = "https://code.highcharts.com/9.1.0/modules/offline-exporting.js"> </script>
no such problem is observed.

**Comment by khlieng** [comment] 2021-07-16 11:09
Is this perhaps a duplicate of #6417?

**Closed** 2022-04-08 10:17 UTC
Labels: Type: Bug

**Comment by TorsteinHonsi** [comment] 2022-04-08 10:18
Closed as duplicate of #6417. On order to use special characters, a TTF font file must be loaded through https://api.highcharts.com/highcharts/exporting.pdfFont, because the fonts built into PDF only contains a limited set of characters.
