### ISSUE TITLE
Including the exporting module causes a memory leak when calling [chart.update]

### ISSUE THREAD

**Issue by mben-romdhane** [highcharts/highcharts#14785] opened 2020-12-09 17:58 UTC
#### Expected behaviour
When including the exporting module, calling [chart.update] should not change the number of destroy event listeners according to [chart.hcEvents.destroy].

#### Actual behaviour
The number of event listeners increases when [chart.update] is called. It doesn't appear to matter what exporting options are used (including enabled : false).

#### Live demo with steps to reproduce
https://jsfiddle.net/fxzcwgyj/3/
Click the "update config" button to run chart.update and see the new count.

#### Product version
Confirmed in Highcharts 8.2.2

#### Affected browser(s)
Google Chrome

**Comment by khlieng** [comment] 2020-12-10 08:39
This was fixed in #14393, duplicate of #13277.

**Closed by khlieng** 2020-12-10 08:39 UTC
