### ISSUE TITLE
Some data is not displayed on xrange graph with min and max on X axis

### ISSUE THREAD

**Issue by BrunoCARADEC** [highcharts/highcharts#21792] opened 2024-09-05 15:21 UTC
#### Expected behaviour
Data exists for each Y value from 0 to 4. Declaring the min and max values ​​of the X axis allows you to limit the display to this period. 

#### Actual behaviour
Since version Highcharts 11.4.2 to 11.4.8 Data for Y>0 are not displayed if min and max values ​​are declared on the X axis.
If we remove min and max déclaration, data are displayed

#### Live demo with steps to reproduce
https://jsfiddle.net/BrunoCARADEC/to9m12xf/3/

#### Product version
11.4.1

**Comment by pawellysy** [comment] 2024-09-10 07:23
Hello @BrunoCARADEC, thanks for reporting the bug!

`internal note`
this is a regression. Bisected to ->  https://github.com/highcharts/highcharts/commit/00d57e6488b641c2d5c9110d5cb83ed1e933ddbc 
FYI @TorsteinHonsi

**Comment by TorsteinHonsi** [comment] 2024-09-30 07:38
Duplicate of #21267

**Closed by TorsteinHonsi** 2024-09-30 07:38 UTC
Labels: Product: Highcharts, Type: Regression, Duplicate
