### ISSUE TITLE
Highstock timeseries doesn't show line

### ISSUE THREAD

**Issue by kumaresanm** [highcharts/highcharts#5102] opened 2016-03-07 07:27 UTC
I have an highstock timeseries chart. The data is present in the chart it is seen in the navigator, but the line is not seen only points are seen on hover.
![issue_732](https://cloud.githubusercontent.com/assets/5888338/13563030/07127c6c-e464-11e5-8822-e98920a88a0d.JPG)
In the image there is same data on the line.

**Comment by TorsteinHonsi** [comment] 2016-03-07 14:06
Thanks for reporting! As always it is hard to debug an image, but I tried replicating what I see in [this fiddle](http://jsfiddle.net/highcharts/t113ep7s/).

Are you sure you're not seeing the line, but that it is thinner than in my reproduction? If not, please modify my attempt at a reproduction, or provide your own demo.

**Comment by jon-a-nygaard** [comment] 2016-04-26 09:29
Closing this issue due to: We are not able to reproduce the issue, and it is pending reply. 
Should anyone have further information on this issue, please add a comment and reopen.

**Closed by jon-a-nygaard** 2016-04-26 09:29 UTC
Labels: Cant reproduce, Highstock, Pending reply
