### ISSUE TITLE
Series merged grouping

### ISSUE THREAD

**Issue by likwifi** [highcharts/highcharts#6105] opened 2016-12-07 13:35 UTC
#### Actual behaviour
After series separate grouping tooltip is showing only value of line serie instead of both.

#### Live demo with steps to reproduce

http://jsfiddle.net/gu4p6d9c/1/

**Comment by pawelfus** [comment] 2016-12-07 13:44
Thanks for reporting!

Actually, it's a duplicate of #4874

Changing order of series, resolves issue with tooltip, but rendering changes: http://jsfiddle.net/gu4p6d9c/5/

**Closed by pawelfus** 2016-12-07 13:44 UTC
Labels: Duplicate
