### ISSUE TITLE
With 8.0.4, 3D pie/3D doughnut charts position rendering error

### ISSUE THREAD

**Issue by ma1990213** [highcharts/highcharts#13122] opened 2020-03-12 07:14 UTC
#### Expected behaviour
Correct position

#### Actual behaviour
Fault position

#### Live demo with steps to reproduce
![1](https://user-images.githubusercontent.com/17824026/76495402-c35dae00-6471-11ea-88be-374ad0420831.png)
![2](https://user-images.githubusercontent.com/17824026/76495454-de302280-6471-11ea-9a03-168331be4f9e.png)

I'm not going to provide links of demo.
You can use any data to create a 3D pie or 3D doughnut chart with 8.0.4.
This bug has nothing to do with data, and any data can reproduce the problem.
Looking forward to your reply. Thank you.

#### Product version
    "highcharts": "8.0.4",
    "highcharts-3d": "^0.1.7",
    "highcharts-grouped-categories": "^1.1.3",
    "highcharts-regression": "^2.0.1",
    "highcharts-vue": "^1.3.5"

#### Affected browser(s)
Google Chrome 80.0.3987.132

**Comment by sebastianbochan** [comment] 2020-03-12 09:20
Hi @ma1990213,
Thank you for reporting. Our official demo just works properly: https://jsfiddle.net/BlackLabel/dq20vg1o/. Could you update the example with your simplied chart's options and data? It will allow us to reproduce and debug.

**Comment by ma1990213** [comment] 2020-03-12 09:37
Is highcharts version of your official demo 8.0.4？
Version 8.0.2 is correct，but version 8.0.4 is not work.

**Comment by sebastianbochan** [comment] 2020-03-12 09:48
Our demo uses the newest 8.0.4 version.

**Comment by pawelfus** [comment] 2020-03-12 11:35
It's actually a duplicate of #11928

**Closed by pawelfus** 2020-03-12 11:35 UTC
Labels: Status: Pending reply
