### ISSUE TITLE
Incorrect dates ranges when using 3 months button on highchart (Maybe this happens due to quantity of days in February)

### ISSUE THREAD

**Issue by silverenio** [highcharts/highcharts#6536] opened 2017-03-30 12:48 UTC
#### Expected behaviour
When we click on 3months button we see the ranges on selectors at the top right corner (for example for today date 2017-03-30): 2016-12-30 - 2017-03-30
The range on graph should be: 2016-12-30 - 2017-03-30

#### Actual behaviour
When we click on 3month button we see the ranges on selectors at the top right corner (for example for today date 2017-03-30): 2016-12-30 - 2017-03-30
But the range on graph is: 2016-12-31 - 2017-03-30

#### Affected browser(s)
Chrome, FireFox

**Comment by sebastianbochan** [comment] 2017-03-30 14:39
Duplicate of 6537

**Closed by sebastianbochan** 2017-03-30 14:39 UTC
