### ISSUE TITLE
packedbubble event drop

### ISSUE THREAD

**Issue by mdabagh** [highcharts/highcharts#19432] opened 2023-07-25 10:28 UTC
Hi
Please explain how I can record in the drop log what item was transferred from where to where?
console.log('item ' + event.point.name + ' from series ' + event.point.series.name + ' to series ' + event.series.name + ' moved.');

```
function logAfterDragDrop(event) {
    console.log('item ' + event.point.name + ' from series ' + event.point.series.name + ' to series ' + event
        .series.name + ' moved.');
}

var data = [{
    name: 'Europe',
    data: [{
            name: 'Germany',
            value: 767.1
        }, {
            name: 'Croatia',
            value: 20.7
        },
        {
            name: 'Belgium',
            value: 97.2
        }
    ]
}, {
    name: 'Africa',
    data: [{
            name: 'Senegal',
            value: 8.2
        },
        {
            name: 'Cameroon',
            value: 9.2
        }
    ]
}];

var options = {
    chart: {
        type: 'packedbubble',
        height: '100%'
    },
    tooltip: {
        useHTML: true,
        pointFormat: '<b>{point.name}:</b> {point.value}'
    },
    plotOptions: {
        packedbubble: {
            minSize: '20%',
            maxSize: '100%',
            zMin: 0,
            zMax: 1000,
            layoutAlgorithm: {
                gravitationalConstant: 0.05,
                splitSeries: true,
                seriesInteraction: true,
                dragBetweenSeries: true,
                parentNodeLimit: true
            },
            point: {
                events: {
                    drop: function (event) {
                        logAfterDragDrop(event)
                    }
                }
            }
        }
    },
    series: data
};

var chart = Highcharts.chart('container', options);
(function (H) {
    H.wrap(H.seriesTypes.packedbubble.prototype, 'onMouseUp', function (proceed, point, event) {
        if (point.fixedPosition && point.inDragMode) {
            H.fireEvent(point, 'drop');
        }
        proceed.apply(this, Array.prototype.slice.call(arguments, 1));
    });
})(Highcharts);
```

**Comment by bm64** [comment] 2023-07-25 13:35
Hello @mdabagh 

it looks like you have already asked this question in another ticket, so I'm closing this one as a duplicate of https://github.com/highcharts/highcharts/issues/12495

Also this is a general question, and we use github strictly as a feature request / bug tracking tool, so for any futher similar question, please use our [other support channels](https://www.highcharts.com/blog/support/), for example Highcharts Forum: https://www.highcharts.com/forum/

**Closed** 2023-07-25 13:35 UTC
Labels: Type: Question

**Comment by mdabagh** [comment] 2023-07-26 10:02
Hi @bm64 
This piece of code got me working.
```
Highcharts.wrap(Highcharts.seriesTypes.packedbubble.prototype, 'onMouseUp', function (proceed, point, event) {
    const lengths = this.chart.series.map(s => s.points.length);
    let newSeries;
    const name = point.name;
    const oldSeries = point.series.name;

    if (point.fixedPosition && point.inDragMode) {
        Highcharts.fireEvent(point, 'drop');
    }

    proceed.apply(this, Array.prototype.slice.call(arguments, 1)); // bubble is moved here

    this.chart.series.forEach((s, i) => {
        if (s.points.length > lengths[i]) {
            newSeries = s;
        }
    });

    console.log(name);
    console.log('Point moved from: ', oldSeries);
    console.log('point moved to: ', newSeries.name);
});
```
