### ISSUE TITLE
Interactive legend and Y Axis scale calculation

### ISSUE THREAD

**Issue by pawanvjadhav** [highcharts/highcharts#4306] opened 2015-06-19 08:07 UTC
if we dont set max property of Y Axis and if we hide all series plotted on that Y Axis using iteractive legend, highchart automatically hides Y axis. Same doesn't happen when we set max property of Y Axis and if we hides all series plotted on that Y Axis using interactive legend.

Any reason for keeping this difference?

**Comment by pawelfus** [comment] 2015-06-19 09:10
See #705 ticket.

**Comment by pawanvjadhav** [comment] 2015-06-19 13:09
Ok got it.

 are you going to add this as configuration?

**Comment by pawanvjadhav** [comment] 2015-06-23 11:01
Any comment / update?

**Comment by KacperMadej** [comment] 2018-10-10 15:52
Closing as a duplicate of #705

**Closed by KacperMadej** 2018-10-10 15:52 UTC
