### ISSUE TITLE
Text outline of a data label rendered incorrectly if width is specified

### ISSUE THREAD

**Issue by adamcbuckley** [highcharts/highcharts#6072] opened 2016-12-01 15:58 UTC
#### Expected behaviour
The text and the textOutline of data labels should be correctly aligned

#### Actual behaviour
The text and the textOutline of data labels is not correctly aligned

#### Live demo with steps to reproduce
http://jsfiddle.net/2bgd6eho/

#### Affected browser(s)
Chrome v54

**Comment by adamcbuckley** [comment] 2016-12-01 16:00
I note that the text outline is rendered correctly when the style.width attribute is removed

	pie: {
		dataLabels: {
			distance: -30,
			format: '{point.name} {point.percentage}%',
			style: {
				width: '50px'
			}
		},
	}

**Comment by adamcbuckley** [comment] 2016-12-01 16:01
Screenshot showing incorrectly aligned text outline

![image](https://cloud.githubusercontent.com/assets/6066058/20801003/5a4c765e-b7df-11e6-8a92-2c17f57a79af.png)

**Comment by adamcbuckley** [comment] 2016-12-01 16:04
Zooming in shows that the outline is incorrectly aligned because the word order (for the outline) is wrong.

Foreground text reads:

North-
East
Australian
Lesser
Spotted
Kumquat
40%


Whereas the outline text reads:

North-
40%
Kumquat
Spotted
Lesser
Australian
East


![image](https://cloud.githubusercontent.com/assets/6066058/20801142/c81e196c-b7df-11e6-9b8d-d56e38b4742e.png)

**Comment by adamcbuckley** [comment] 2016-12-01 16:26
Current workaround is to include highcharts.js version 4.1.5 in my project.

![image](https://cloud.githubusercontent.com/assets/6066058/20802141/f865c284-b7e2-11e6-8b6d-e2d23b7c6d31.png)

**Comment by adamcbuckley** [comment] 2016-12-01 16:28
I note that the text outline effect is actually more beautiful in version 4.  What's with that?  :-)

![image](https://cloud.githubusercontent.com/assets/6066058/20802185/234a5384-b7e3-11e6-8a19-3621677ea4f3.png)

**Comment by TorsteinHonsi** [comment] 2016-12-05 11:14
Thanks for reporting!

This is a duplicate of #6065, which has been fixed in the master.

> I note that the text outline effect is actually more beautiful in version 4. What's with that? :-)

More beautiful perhaps, but it was less readable. While the old `textShadow` property added a blurred shadow, the new `textOutline` property draws a sharp, 1px line around the characters. It works better with text that is not fully black or white. 


![skjermbilde 2016-12-05 kl 12 13 33](https://cloud.githubusercontent.com/assets/227836/20883041/4cf5c69c-bae4-11e6-915f-40a19516448d.png)

**Closed by TorsteinHonsi** 2016-12-05 11:14 UTC

**Comment by xgqfrms-gildata** [comment] 2018-01-12 04:19
me too!

https://github.com/gildata/RAIO/issues/280#issuecomment-357125296

**Comment by KacperMadej** [comment] 2018-01-15 14:57
@xgqfrms-gildata Please provide more info for your problem. Demo based on your code looks fine: http://jsfiddle.net/BlackLabel/2bgd6eho/3/

**Comment by xgqfrms-gildata** [comment] 2018-01-16 01:08
@KacperMadej 
Thanks for your time. I had fixed that problem.

**Comment by KacperMadej** [comment] 2018-01-16 11:51
Thank you for the info, good to hear it's working now.

The issue will remain closed as there's no unresolved problem left.
