### ISSUE TITLE
IE and Edge problem with forEach on http://api.highcharts.com/highcharts/

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#7290] opened 2017-10-18 12:57 UTC
#### Behaviour
Error in console when trying to hover on any item listed on the left side.

#### Live demo with steps to reproduce
http://api.highcharts.com/highcharts/

#### Affected browser(s)
IE11/Win10, Edge

**Comment by cvasseng** [comment] 2017-10-18 13:21
Caused by #7285, so this is a duplicate.

**Comment by cvasseng** [comment] 2017-10-18 13:22
This has been fixed in `api-docs`, and will be pushed live asap.

**Comment by sebastianbochan** [comment] 2018-01-10 12:14
Problem fixed, when will come again. Please reopen the ticket.

**Closed by sebastianbochan** 2018-01-10 12:14 UTC
Labels: Bug, Docs
