### ISSUE TITLE
Polar chart - data point selection for multiple series issue

### ISSUE THREAD

**Issue by rajeshdanabal** [highcharts/highcharts#9760] opened 2018-12-27 11:44 UTC
#### Expected behaviour
Xaxis has multiple series and when we select a data point on different series but on same xaxis, only it should get selected and other previously selected data points should get deselected.

#### Actual behaviour
Data point gets selected/deselected irrespective of series but based on xaxis that it shares.

#### Live demo with steps to reproduce
https://jsfiddle.net/rajeshdanabal/82batfd9/15/

On the above examples you can see when we click on Series1 of X1 and then Series2 of X1, Instead of selecting Series2 of X1 only Series1 gets deselected.  Even if we use ctrl button to select, it did not help.

#### Product version
Highcharts V7.0.1

#### Affected browser(s)
Tested on Google chrome - Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by pawelfus** [comment] 2018-12-27 13:19
Hi @rajeshdanabal 

Thank you for reporting this bug. It's actually a duplicate of #7743 - series with the highest `zIndex` always gets all click/select events.

Closing as duplicate of #7743

**Closed by pawelfus** 2018-12-27 13:19 UTC
