### ISSUE TITLE
Event target bug: t.getAttribute is not a function

### ISSUE THREAD

**Issue by royalone** [highcharts/highcharts#19944] opened 2023-10-17 04:07 UTC
#### Expected behaviour
No expected behaviour. Symptoms are just console errors. 

#### Actual behaviour
Logs showing occasional errors "t.getAttribute is not a function" 
All instances have been in Firefox so far.

#### Live demo with steps to reproduce
Cannot reproduce, at least in js fiddle. 
In my own environment, can reproduce by:
- Refresh Firefox with the debugger's mobile emulation enabled.
- Enable touch emulation
- move my mouse over the very edge of my app
- error usually occurs. if not, swap between enabled/disabled touch emulation and keep hovering over the same area

Digging into the source file, the problem seems to be that the `Document` itself has a `mouseMove` event it is listening to. This event is passed around, where later it's `.target` is accessed, and the `.getAttribute()` method is called. Because this event target was the `Document` not an `Element`, the method doesn't exist and the error is thrown. 

This event is registered at line ~27084 in [the source](https://code.highcharts.com/stock/11.1.0/highstock.src.js)

Not sure exactly the purpose of the document listening to the event. To fix the errors, i've just commented out that whole block registering the `unDocMouseMove` listener, and it doesnt seem to affect my app. 

I believe this closed issue #18859 is referencing the same error, and perhaps this one too #19628
 
#### Product version
Highstock v11.1.0 

#### Affected browser(s)
Firefox 118.0.2

**Comment by karolkolodziej** [comment] 2023-10-18 08:22
Hi @royalone!

Thank you for sharing the tip about removing the `unDocMouseMove`.

If you could somehow find a reliable way to reproduce this issue that would be great! 
Without that, it will be really hard to pinpoint the source of the issue.

Also, if you find anything that could narrow down the search, please let us know.

**Comment by royalone** [comment] 2023-10-19 01:19
Ok well like I said, I cant reproduce in jsFiddle, but I can pretty easily in my own very basic page containing just a default chart

Also seems to have something to do with tooltips showing?

in the video below:
- I'm in firefox with mobile emulation enabled. 
- I make sure touch simulation is enabled.
- I click on a point to make a tooltip show
- I move my mouse over the edge of the page
- I can consistently get the error 

https://github.com/highcharts/highcharts/assets/50619029/b812fd70-26dd-49b5-a529-f73800ccac07

I'd guess that this could happen in real life on laptops with both a mouse and touch capability?

As for narrowing down the search, I'm pretty sure I more or less identified what/where it's going wrong in the original post above.

Thanks :)

**Comment by karolkolodziej** [comment] 2023-10-24 13:21
Thanks for the update! 

I was able to recreate what you've got with:
- Angular 16
- Highcharts `v.11.1.0` without `highchart-angular` 
- Only visible on Firefox

**Comment by KacperMadej** [comment] 2023-11-13 15:23
Recreated without Angular. Open a minimal HTML file:
```html
<!DOCTYPE html>
<html>
    <head>
        <script src="https://code.highcharts.com/highcharts.src.js"></script>
    </head>
    <body>
        <div id="container"></div>
        <script>
            Highcharts.chart('container', {
                series: [{
                    data: [1,2,3]
                }]
            });
        </script>
    </body>
</html>
```
in Firefox, in Responsive Design Mode with Enabled touch simulation. Click the last point and then mouse drag out of the emulated window in the upward direction. Error should show in the console - if not, drag around the edge (up and down) until it shows.

_Internal note:_
This might be a Firefox bug (touch-simulator) because it happens only there and mouse move fires only on leaving the inner window. However, it seems possible to resolve this issue quite easily in [`onDocumentMouseMove`](https://github.com/highcharts/highcharts/blob/310c141b3fd35edf78ae8ad9708ddacf7245181e/ts/Core/Pointer.ts#L1306) with additional conditional like:
```ts
            ) &&
            (
                pEvt.target === chart.container.ownerDocument ||
                !this.inClass(pEvt.target as any, 'highcharts-tracker')
            )
```

Is this a bug that should be fixed in Highcharts? @TorsteinHonsi

**Comment by xiaoxiaosaohuo** [comment] 2024-05-21 04:36
I have encountered this bug in production as well, the sentry reported it. When the error occurred, the event's args is 
`
{
chartX: 1644,
chartY: 1388,
currentTarget: [object HTMLDocument],
isTrusted: true,
target: [object Text],
type: mousemove
}
`

**Comment by karolkolodziej** [comment] 2024-05-22 06:02
Thank you @xiaoxiaosaohuo for the input!

**Comment by TorsteinHonsi** [comment] 2024-05-22 07:58
I am able to run @KacperMadej 's reproduction, and the fix seems to work. However I'm curious to know why we need `pEvt.target === chart.container.ownerDocument`. Intuitively, I would think that `this.inClass` would return false when `pEvt.target` equals the `ownerDocument`? Because the owner document obviously shouldn't have the `highcharts-tracker` class.

**Comment by MarkusBarstad** [comment] 2024-05-26 19:32
@TorsteinHonsi I could be wrong because I am not 100% on how `attr` works, but essentially when when we call `inClass` on the document we end up, through `attr`, to try to do `document.getAttribute` which does not work, and this is why we avoid the error when we don't call `inClass` for documents.

**Comment by TorsteinHonsi** [comment] 2024-05-27 08:44
@MarkusBarstad Yes, but I expected this line to return false when `pEvt.target === chart.container.ownerDocument`:

`this.inClass(pEvt.target as any, 'highcharts-tracker')`

Because `pEvt.target` is obviously not inside a `highcharts-tracker` element.

**Closed** 2024-06-04 12:53 UTC
Labels: Type: Bug, Product: Highcharts
