### ISSUE TITLE
ZigZag Indicator not working with incremental data update

### ISSUE THREAD

**Issue by chartwizard** [highcharts/highcharts#7955] opened 2018-03-03 22:23 UTC
#### Expected behaviour
ZigZag indicator should give the same results whether the data is added all at once or incrementally.

#### Actual behaviour
Does not give same results, see attached pdf's, one is where all the data is added at once and the other is where the last 20 points where added one at a time.

#### Live demo with steps to reproduce

[chart_zigzag_all_at_once.pdf](https://github.com/highcharts/highcharts/files/1777957/chart_zigzag_all_at_once.pdf)
[chart_zigzag_incremental_last_20_points.pdf](https://github.com/highcharts/highcharts/files/1777958/chart_zigzag_incremental_last_20_points.pdf)

#### Product version

Highstock v6.07

**Comment by pawelfus** [comment] 2018-03-05 11:14
Hi @chartwizard 

Thank you for reporting this bug. 

**Live demo with steps to reproduce:**
http://jsfiddle.net/BlackLabel/8jox422q/20/

**Comment by KacperMadej** [comment] 2018-03-05 11:33
Hi @chartwizard 

Thank you for reporting about the problem.

_Internal note:_
The dynamically added points causes the indicator to render wrongly, but after debugging the zig zag is looks like the data is correct, but points are not redrawn.

Correct with static data: http://jsfiddle.net/BlackLabel/p1j56mwn/3/
Wrong with dynamic: http://jsfiddle.net/BlackLabel/p1j56mwn/2/

Any ideas @pawelfus , @sebastianbochan ?

**Comment by pawelfus** [comment] 2018-09-14 13:31
It's fixed in v6.1.2

(most probably fixed by #8572).

**Closed by pawelfus** 2018-09-14 13:31 UTC
Labels: Bug, Highstock
