### ISSUE TITLE
VMLRendererExtension isIE8 returns false for IE8 running in browser compatibility mode

### ISSUE THREAD

**Issue by oriondean** [highcharts/highcharts#2890] opened 2014-04-08 15:01 UTC
VMLRendererExtension uses the following condition to determine whether a browser is IE8 or not: ```isIE8: userAgent.indexOf('MSIE 8.0') > -1```

As a result, when ```IE8``` is running in browser compatibility mode its user agent contains ```MSIE 7.0``` rather than ```MSIE 8.0```. 

This failing condition causes issues such as plot lines not appearing on the chart when hovering.

An easy solution would be to replace the userAgent check with the ```docMode8``` boolean that is based on the documentMode of the browser.

**Comment by jon-a-nygaard** [comment] 2016-04-26 09:52
Closing this issue due to: We are not able to reproduce the issue, and it is pending reply. 
Should anyone have further information on this issue, please add a comment and reopen.

**Closed by jon-a-nygaard** 2016-04-26 09:52 UTC
Labels: Cant reproduce, Pending reply
