### ISSUE TITLE
The same data is plotted differently

### ISSUE THREAD

**Issue by 99899899998** [highcharts/highcharts#17463] opened 2022-07-05 10:10 UTC
#### Expected behaviour
I want the stacked diagram to draw properly

#### Actual behaviour
I noticed something wrong with the stack diagram when there were integers and negative numbers at one point，
but when I adjust the order of the data it's normal to draw it
In the actual scenario, the data is dynamic ， I can't adjust the order at will
So how do I fix it

hope the reply,thanks

#### Live demo with steps to reproduce

demo1： https://jshare.com.cn/public/r0GLyg
demo2： https://jshare.com.cn/public/V0GLyX

**Comment by raf18seb** [comment] 2022-07-05 10:54
Hi @99899899998, thank you for contacting us with your issue.

This is intended behavior and can be controlled by the `yAxis.reversedStacks` property: https://api.highcharts.com/highcharts/yAxis.reversedStacks

See
demo1: https://jsfiddle.net/BlackLabel/04get5p1/
demo2: https://jsfiddle.net/BlackLabel/o58shpyk/

Closing as not a bug (question) and resolved.

**Closed by raf18seb** 2022-07-05 10:54 UTC

**Comment by 99899899998** [comment] 2022-07-06 01:41
> Hi @99899899998, thank you for contacting us with your issue.
> 
> This is intended behavior and can be controlled by the `yAxis.reversedStacks` property: https://api.highcharts.com/highcharts/yAxis.reversedStacks
> 
> See demo1: https://jsfiddle.net/BlackLabel/04get5p1/ demo2: https://jsfiddle.net/BlackLabel/o58shpyk/
> 
> Closing as not a bug (question) and resolved.



> Hi @99899899998, thank you for contacting us with your issue.
> 
> This is intended behavior and can be controlled by the `yAxis.reversedStacks` property: https://api.highcharts.com/highcharts/yAxis.reversedStacks
> 
> See demo1: https://jsfiddle.net/BlackLabel/04get5p1/ demo2: https://jsfiddle.net/BlackLabel/o58shpyk/
> 
> Closing as not a bug (question) and resolved.

thanks your reply
I kown the `yAxis.reversedStacks` and i tryed, it just changing up and down without solving the real problem
There will still be cases where the graph is overwritten
It looks like the overlay is not stacked
like this:

demo: https://jshare.com.cn/public/r0GLyg

**Comment by 99899899998** [comment] 2022-07-06 01:43
> > Hi @99899899998, thank you for contacting us with your issue.
> > This is intended behavior and can be controlled by the `yAxis.reversedStacks` property: https://api.highcharts.com/highcharts/yAxis.reversedStacks
> > See demo1: https://jsfiddle.net/BlackLabel/04get5p1/ demo2: https://jsfiddle.net/BlackLabel/o58shpyk/
> > Closing as not a bug (question) and resolved.
> 
> thanks your reply I kown the `yAxis.reversedStacks` and i tryed, it just changing up and down without solving the real problem There will still be cases where the graph is overwritten It looks like the overlay is not stacked like this:
![image](https://user-images.githubusercontent.com/45654766/177449158-98e82ec0-229e-4442-94fb-82b134b0d88b.png)

> demo: https://jshare.com.cn/public/r0GLyg

**Comment by 99899899998** [comment] 2022-07-06 09:24
> Could you describe which one is working incorrectly in your opinion and describe what exactly is wrong?

First of all, both 1 and 2 must be wrong because they only show the negative part and not the positive part，
then we see 3 and 4,they have the same problem.
Let's look at a graph of each data individually, 
`A`：fillArea matches the data `[-100,500,-200,200,-500,550]`
![image](https://user-images.githubusercontent.com/45654766/177513329-fef59c4d-762f-4353-8f97-841010fab98e.png)

`B`:  fillArea is not matches the data `[-5020,-1060, -107, -1110, -133]`,the data is all negative
![image](https://user-images.githubusercontent.com/45654766/177514609-fb17028c-e29f-4e0a-b952-a642207a10ac.png)
demo: https://jshare.com.cn/public/r0GLyg

I think the logic of stacking is that the areas are independent of each other， but now A's data area is filled with B's color

I expect the drawing area blocks to be independent of each other,data is all positive or all negative it draw normal,like this:
![image](https://user-images.githubusercontent.com/45654766/177516898-44992589-09f7-4e53-a396-6a5ed13fce07.png)
demo: https://jshare.com.cn/public/40GL06

**Comment by raf18seb** [comment] 2022-07-07 08:44
@99899899998,

> First of all, both 1 and 2 must be wrong because they only show the negative part and not the positive part

Remember that you have a `series.stacking` enabled - this means that your data is stacked (added) and drawing starts either from the first series' point or the last series' point. If `yAxis.reversedStacks` is `true`, then drawing starts from the last series.
For example:
- -100 and -5020, the series starts drawing from -5020 and goes -100 units down
- 500 and -1060, the series starts drawing from -1060 and goes 500 units up
etc.

That's why all area is negative (except the last point which is the only positive point within x: 5).
![image](https://user-images.githubusercontent.com/23310742/177730834-d7defd41-93c9-42ee-9ddc-8873ea555aab.png)


Let's move on:

>  fillArea is not matches the data [-5020,-1060, -107, -1110, -133],the data is all negative

In this image you provided 
![image](https://user-images.githubusercontent.com/23310742/177728485-1944f503-371b-4865-b168-5a993f8f761e.png)

`yAxis.reversedStacks` is set to `false` which means that drawing starts from the first series.
Let's consider points 500 and -1060 (with x: 1). The series starts from 500 and goes down to -560 (500 + (-1060) = -560). So the filled area between 500 and -560 is correct.


If you're expecting something else, then I think you shouldn't use `stacking`.

Instead of saying what, in your opinion, is wrong, could you describe and provide a simple draw of what you're actually expecting when drawing area graph with negative data? Then I will be able to find another solution for you.

When it comes to `series.stacking` and `yAxis.reversedStacks`, everything seems to be working fine. So you're probably looking for something else (something different than `stacking`).
