### ISSUE TITLE
NodeJS require/exporting fails

### ISSUE THREAD

**Issue by tuytuy** [highcharts/highcharts#6611] opened 2017-04-19 15:11 UTC
#### Expected behaviour
Able to draw a chart using the readme example

#### Actual behaviour
```
    TypeError: Cannot read property 'prototype' of undefined
    api-pumaportal-62 (err):     at /home/git/apps/api-pumaportal/node_modules/highcharts/modules /exporting.js:9:319
    api-pumaportal-62 (err):     at /home/git/apps/api-pumaportal/node_modules/highcharts/modules/exporting.js:27:31
    api-pumaportal-62 (err):     at Object.<anonymous> (/home/git/apps/api-pumaportal/routes/reports/index.js:6:40)
    api-pumaportal-62 (err):     at Module._compile (module.js:570:32)
    api-pumaportal-62 (err):     at Object.Module._extensions..js (module.js:579:10)
    api-pumaportal-62 (err):     at Module.load (module.js:487:32)
    api-pumaportal-62 (err):     at tryModuleLoad (module.js:446:12)
    api-pumaportal-62 (err):     at Function.Module._load (module.js:438:3)
    api-pumaportal-62 (err):     at Function._load (/usr/lib/node_modules/pod/node_modules/pmx/lib/transaction.js:92:21)
    api-pumaportal-62 (err):     at Module.require (module.js:497:17)
```

#### Sample code in NodeJS:
```js
var Highcharts = require('highcharts');
require('highcharts/modules/exporting')(Highcharts);

    var chart = highcharts.chart('container', {
        series: [{
            data: [1, 3, 2, 4]
        }],
    });

    console.log("chart: " + chart);

```

**Comment by jon-a-nygaard** [comment] 2017-04-24 09:23
Hi @tuytuy 
Thanks for reporting.
From what I can see you are using [pod](https://www.npmjs.com/package/pod) to serve your application, but I do not know how your app is actually setup.
It would be very helpful if you provide some information on if you are using any type of bundler or framework in your application, or a simple example of your usage of Highcharts.

**Comment by jon-a-nygaard** [comment] 2017-05-26 08:38
Closing issue due to unable to reproduce and pending reply. Should anyone have further information, please give us a comment.

**Closed by jon-a-nygaard** 2017-05-26 08:38 UTC
Labels: Cant reproduce, Undecided
