### ISSUE TITLE
Heat map color axis labels

### ISSUE THREAD

**Issue by pliasetski** [highcharts/highcharts#7608] opened 2018-01-03 16:10 UTC
Hello,
When I add custom format for color axis labels, they do not fit in the heat map plot area.

#### Live demo with steps to reproduce
http://jsfiddle.net/Pashe4ka/dp6htf6e/

#### Affected browser(s)
Chrome latest version

**Comment by pawelfus** [comment] 2018-01-04 10:11
Hi @pliasetski 

Thanks for reporting this issue. It's a duplicate of #3463 (a title may be misleading, but reserved space for colorAxis is miscalculated: http://jsfiddle.net/dp6htf6e/1/ )

**Closed by pawelfus** 2018-01-04 10:11 UTC
