### ISSUE TITLE
rangeSelector buttons overwrite series dataGrouping options when selected by default

### ISSUE THREAD

**Issue by cebamps** [highcharts/highcharts#16759] opened 2021-12-06 10:25 UTC
#### Expected behaviour
When rangeSelector buttons do not specify an approximation method ([`rangeSelector.buttons.dataGrouping.approximation`](https://api.highcharts.com/highstock/rangeSelector.buttons.dataGrouping.approximation)) and one button is selected by default ([`rangeSelector.selected`](https://api.highcharts.com/highstock/rangeSelector.selected)) the approximation method defined in each Series should be preserved ([`series.line.dataGrouping.approximation`](https://api.highcharts.com/highstock/series.line.dataGrouping.approximation)).

#### Actual behaviour
The expected behaviour is already present when `rangeSelector.selected` is `undefined`: the button `dataGrouping` options are used to patch the series, so any missing property in the button is preserved in the series' `dataGrouping` options.

However, when a button is selected initially through `rangeSelector.selected`, the button's entire `dataGrouping` object *replaces* the series' instead of patching it. The demo below illustrates this inconsistency.

My use case is to dispaly multiple series with different data grouping options in the same chart. To this end, I need to specify those options in the series' `dataGrouping` options, but this can not work if the range selector buttons override them.

#### Live demo with steps to reproduce
https://jsfiddle.net/tx1582qp/1/

#### Product version
Highstock 9.3.2 (latest)

#### Affected browser(s)
n/a

**Comment by raf18seb** [comment] 2021-12-08 13:48
Hi @cebamps, thank you for contacting us.

This is expected behavior - click on the rangeSelector button sets the dataGrouping for all the series.
If you'd like to change this behavior, you can use the [buttons.click](https://api.highcharts.com/highstock/rangeSelector.buttons.events.click) event to add your own custom logic and return `false` to stop the current, default behavior.

For more information or help, please contact us on one of ours dedicated support channels. GitHub is our bugs/features tracker only, so I'm closing the ticket here as not a bug.
More info: https://www.highcharts.com/blog/support/

**Comment by cebamps** [comment] 2021-12-08 14:21
Hello @raf18seb. Thanks for your response.

It seems surprising to me that this would be expected behaviour. As I show in my demo, the behaviour of `rangeSelector.buttons.dataGrouping` is inconsistent between a range selector with default selection and one without. If anything, the present issue is reporting this inconsistency as a bug.

Reading the source code, it also seems clear to me that there is at least some intent to merge data grouping options into existing series, rather than discarding existing options in the series altogether: https://github.com/highcharts/highcharts/blob/v8.2.2/ts/Extensions/DataGrouping.ts#L1091-L1107

Thanks also for the suggestion of a workaround. Unfortunately, I had already considered setting a `buttons.click` handler as you suggest, but it did not seem like a workable solution for me because:

* Returning `false` cancels everything about the handling of the range selector, which does quite a few things that I would likely still care to preserve: https://github.com/highcharts/highcharts/blob/v8.2.2/ts/Extensions/RangeSelector.ts#L774-L941
  As an example, this includes styling the button as active after it was clicked, which I don't believe I am able to do in my own handler, since the button objects are not exposed. 
* To circumvent that, I could have `buttons.click` schedule a task to store the Series' data grouping options and restore them after the default click handler has run, but then I would have to redraw the chart again.
* There is another more minor inconvenience, which is that the button event handler does not have access to the chart instance through its arguments or "`this`" context, so I would instead have to include the instance in a closure.

Unfortunately, this leads me to think that the suggestion of handling button clicks does not solve my problem. I might resort to monkey-patching `Axis.prototype.setDataGrouping` instead.

**Comment by raf18seb** [comment] 2021-12-09 16:27
@cebamps,

My apologies, you are absolutely right. I misunderstood you yesterday.

Yes, the dataGrouping options should be definitely merged with already defined series.dataGrouping options.
Workaround: https://jsfiddle.net/BlackLabel/vqtcun8h/

Reopening as a bug :)

**Comment by cebamps** [comment] 2021-12-09 18:18
Thank you for reconsidering, and thank you for the workaround as well! :)

**Closed** 2021-12-17 12:48 UTC
Labels: Type: Bug, Product: Highcharts Stock, Type: Good for beginners, Status: Review in progress
