### ISSUE TITLE
Exported image does not match chart in browser when series have been added in load (styled mode)

### ISSUE THREAD

**Issue by andiger** [highcharts/highcharts#6790] opened 2017-06-02 15:18 UTC
#### Expected behaviour
The exported image should match the chart in the browser.
More specifically:
1. Only one of the area series should be visible in the legend.
2. The area series in the plot area should be green.

#### Actual behaviour
The exported image shows both area series in the legend.
The exported image shows the area series with the wrong colors.

#### Live demo with steps to reproduce
1. Go to http://jsfiddle.net/adgadg/t3y051a8/
2. Export image as PNG from chart menu.

Same chart, but series are added in the options object (works as expected)
http://jsfiddle.net/adgadg/Lhnpkc48/ 

#### Affected browser(s)
Firefox 53.0.3
Highcharts 5.0.12 (styled mode)

**Comment by pawelfus** [comment] 2017-06-02 15:26
Hi @andiger 

Thank you for reporting this issue. It's a duplicate of #5888 - callback is executed when exportin chart too, so series are duplicated. Fixed demo: http://jsfiddle.net/716rwb7o/

**Closed** 2017-06-02 15:26 UTC
Labels: Duplicate
