### ISSUE TITLE
Bug with spiderweb chart

### ISSUE THREAD

**Issue by GabrieleT0** [highcharts/highcharts#17519] opened 2022-07-18 10:32 UTC
#### Expected behaviour
When go on the chart,  next to the values it should come out the tooltip.

#### Actual behaviour
Now the tooltip is not shown, and in the javascript console I have a loop of error.

#### Live demo with steps to reproduce

This is the live demo on the official highchart webpage. 
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/polar-spider
Also on this example the tooltip no longer works, and in the console when we go near the chart and the tooltip should be shown, we get a loop of error in the console and the tooltip is not shown.

**Comment by pawellysy** [comment] 2022-07-18 11:44
Duplicate of: https://github.com/highcharts/highcharts/issues/17472

**Closed by pawellysy** 2022-07-18 11:44 UTC
