### ISSUE TITLE
Drill up breaks bar chart xAxis when large number of bars

### ISSUE THREAD

**Issue by janM37** [highcharts/highcharts#11646] opened 2019-08-09 10:53 UTC
#### Expected behaviour
I'm currently working on a large bar chart with many layers. Some layers can have a few hundred points (bars). Drilling up and down between those layers should not break the graph

#### Actual behaviour
If you drill down between two layers with many bars, drilling up to the intial layer will break the graph. It seems that the dataMin and dataMax properties of xAxis[0] are not updated correctly.

#### Live demo with steps to reproduce
https://jsfiddle.net/janM37/xcwv2p0t/39/

#### Product version
 Highcharts JS v7.0.1 (2018-12-19)

#### Affected browser(s)
Firefox, Chrome

**Comment by pawelfus** [comment] 2019-08-12 13:25
Hi @janM37 

Thanks for reporting the issue. 

**Workaround:**
Set `bar.cropThreshold` to a value higher than number of points (e.g. 1M). Demo: https://jsfiddle.net/BlackLabel/qwy0c68j/

Marking as duplicate of #11561

**Closed by pawelfus** 2019-08-12 13:25 UTC
Labels: Type: Duplicate
