### ISSUE TITLE
Recent update to the highcharts.js causes init error - v8.0.2 (2020-03-03)

### ISSUE THREAD

**Issue by timothymarois** [highcharts/highcharts#13083] opened 2020-03-04 14:45 UTC
Since the release yesterday, it now causes an error: https://code.highcharts.com/highcharts.js

`Uncaught TypeError: this.init is not a function`

![Screenshot 2020-03-04 09 44 43](https://user-images.githubusercontent.com/2489333/75890744-c8c95180-5dfc-11ea-890a-af28a7313e31.png)

Found the CDN for the specific versions, I rolled back to 7.0.2 since that was the last version that was working as intended. (This legacy project doesn't have the ability for NPM so at the moment its a manual process) https://code.highcharts.com/

**Comment by cnrudd** [comment] 2020-03-04 18:19
We found that locking Highcharts to v8.0.0 resolved this issue.

**Comment by RigidCollision** [comment] 2020-03-04 18:34
I have the same issue. You mentioned locking to an earlier version. How do you lock a version?

**Comment by cnrudd** [comment] 2020-03-04 18:40
@RigidCollision I lock to an earlier version in my package.json file by changing my Highcharts dependency from 
`"highcharts": "~8.0.2"`
to
`"highcharts": "8.0.0"`

HOWEVER....
After reading the Highcharts changelog, I understand that this is NOT  a bug, but a BREAKING change in v8.0.1.  See: https://www.highcharts.com/blog/changelog/#highcharts-v8.0.1
Upgrade Notes:

> The Highcharts.Color constructor will not work without the new keyword. Use either new Highcharts.Color or the Highcharts.color factory.

Following this tip did indeed fix the issue and I have reverted our package.json file to use 
`"highcharts": "~8.0.2"`

I now call the Highcharts.Color constructor with `new Highcharts.Color(...`

**Comment by RigidCollision** [comment] 2020-03-04 19:13
Well spotted! Just goes to prove that release notes are a right riveting read.
Code amended and back on the latest release with no errors.

I owe you a beer for that one!

**Comment by sebastianbochan** [comment] 2020-03-05 08:49
Hi everyone, 
The case is known bug and has been already reported.

Im closing the ticket as duplicate of https://github.com/highcharts/highcharts/issues/13053

**Closed by sebastianbochan** 2020-03-05 08:49 UTC
