### ISSUE TITLE
TypeError: null is not an object (evaluating 'b.body') - Highcharts/wkhtmltopdf

### ISSUE THREAD

**Issue by peppe7119** [highcharts/highcharts#15072] opened 2021-02-08 14:05 UTC
#### Expected behaviour
Hightcharts generation using wkhtmltopdf from html page.

#### Actual behaviour
With version 9.0.0 during the generation of a pdf, from html page, the graphs are not correctly generated, they are missing.

I encounter the following error:

```
Loading page (1/2)
Warning: https://code.highcharts.com/highcharts.js:46 TypeError: null is not an object (evaluating 'b.body')
Warning: https://code.highcharts.com/highcharts.js:46 TypeError: null is not an object (evaluating 'b.body')
Warning: https://code.highcharts.com/highcharts.js:46 TypeError: null is not an object (evaluating 'b.body')
Warning: https://code.highcharts.com/highcharts.js:46 TypeError: null is not an object (evaluating 'b.body')
Warning: https://code.highcharts.com/highcharts.js:46 TypeError: null is not an object (evaluating 'b.body')
Printing pages (2/2)
QPainter :: begin (): Returned false
Done

```
While the html page is generated correctly without any problem, the graphics are present.

The command I use is the following:

`mywkhtmltopdf13a.sh --javascript-delay "1000" --debug-javascript "http://localhost:8080/report" "highcharts_test.pdf"`

I also tried to insert: `--enable-javascript --javascript-delay "3000"` but the output is the same

Using the previous version (8.2.2) I have no problem, the graphs are present both on html and on the resulting pdf.

#### Product version
Highcharts release 9.0.0

#### Affected browser(s)
All.

**Comment by KacperMadej** [comment] 2021-02-08 14:27
Hi @peppe7119 

Thank you for reporting the problem.

Please add a live demo for the issue (the chart's minimal configuration at very least) so we could debug the problem and test possible solutions.

Please use library files ending with `.src.js` instead of `.js` so the errors will point to the code that is not minified and easier to work with.

**Comment by peppe7119** [comment] 2021-02-08 14:44
Hi @KacperMadej ,
I currently use the following library files:

```
<script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/highcharts-more.js"></script>
    <script src="https://code.highcharts.com/highcharts-3d.js"></script>
    <script src="https://code.highcharts.com/modules/accessibility.js"></script>
```

To solve the problem I had to use the previous version, for example:

  `<script src = "https://code.highcharts.com/8.2.2/highcharts.js"> </script>`


Below you will find the code of my html page. I have included a simple Hightcharts as an example.

```
<html xmlns:th="http://www.thymeleaf.org" 
    xmlns:layout="http://www.ultraq.net.nz/thymeleaf/layout"
    xmlns:yada="http://www.yadaframework.net"
    >
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/highcharts-more.js"></script>
    <script src="https://code.highcharts.com/highcharts-3d.js"></script>
    <script src="https://code.highcharts.com/modules/accessibility.js"></script>
</head>

<body class="pdf">

  <div id="container" style="width: 1000px;height: 370px;margin-top: 10px;margin-left: auto;margin-right: auto;"></div>
  <script type="text/javascript" th:inline="javascript">
        /*<![CDATA[*/
        Highcharts.chart('container', {
    chart: {
        plotBackgroundColor: null,
        plotBorderWidth: null,
        plotShadow: false,
        type: 'pie'
    },
    title: {
        text: 'Browser market shares in January, 2018'
    },
    tooltip: {
        pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
    },
    accessibility: {
        point: {
            valueSuffix: '%'
        }
    },
    plotOptions: {
        pie: {
            allowPointSelect: true,
            cursor: 'pointer',
            dataLabels: {
                enabled: false
            },
            showInLegend: true
        }
    },
    series: [{
        name: 'Brands',
        colorByPoint: true,
        data: [{
            name: 'Chrome',
            y: 61.41,
            sliced: true,
            selected: true
        }, {
            name: 'Internet Explorer',
            y: 11.84
        }, {
            name: 'Firefox',
            y: 10.85
        }, {
            name: 'Edge',
            y: 4.67
        }, {
            name: 'Safari',
            y: 4.18
        }, {
            name: 'Other',
            y: 7.05
        }]
    }]
});
        /*]]>*/ 
        </script>
    
</body>    
```

In this case using the latest version (9.0.0) by executing the commands wkhtmltopdf (0.13 alpha) there is no graph in the generated pdf file, while in the corresponding html the graph is generated.

Using the previous version instead the graphs are correctly displayed in both (html - pdf)

Below is an example of what is generated:

![no-graph](https://user-images.githubusercontent.com/26764954/107234831-5dccc580-6a24-11eb-80c7-3f74339437b1.JPG)

![graph](https://user-images.githubusercontent.com/26764954/107234844-632a1000-6a24-11eb-9796-f39683d6ded6.JPG)

**Comment by KacperMadej** [comment] 2021-02-08 16:54
**The error:**
About the error `Warning: https://code.highcharts.com/highcharts.js:46 TypeError: null is not an object (evaluating 'b.body')` that you have - this is from a code part that is related to DOMParser. If I understand correctly how wkhtmltopdf works then it is based on QT browser that might have some issues with DOMParser. Here's a related issue - https://github.com/highcharts/highcharts/issues/15037. It's already fixed on the master branch, so you could check if this helps by loading Highcharts from `https://github.highcharts.com/master/highcharts.js`.

**Struggling with debugging:** 
I have used the latest stable build of wkhtmltopdf `0.12.6 (with patched qt)` and I am unable to render a chart with Highcharts 8.2.0, 8.2.2, or 9.0.0.

When testing I got that: Highcharts library is loaded correctly (it is an object and Highcharts.chart is a function), a JS script runs, the waiting time for JS run is correct, the callback for the chart build is not executed as the code fails somewhere in between.

I have a warning `Warning: undefined:0 TypeError: 'undefined' is not a function` - it seems to be an error and not a warning. This shows when executing `Highcharts.chart` function.

I wish to continue investigating the problem, but it seems I am stuck with the above error and cannot properly debug JS - if you have any info that could be helpful please share.

As a **workaround**, I am suggesting [exporting](https://www.highcharts.com/docs/export-module/export-module-overview) the chart images and using them instead.

**Comment by peppe7119** [comment] 2021-02-09 07:40
If it helps you to better investigate the problem you can try to use the 0.13 alpha version that I also use, and with which I have no problems with version 8.2.2, and earlier, in generating the graphics on pdf

[https://github.com/wkhtmltopdf/obsolete-downloads/releases](https://github.com/wkhtmltopdf/obsolete-downloads/releases)


Meanwhile, I try to run some tests too and if I have more details I'll update you!

**Comment by KacperMadej** [comment] 2021-02-09 12:13
Thank you for pointing me to the 0.13-alpha version.
The issue seems to be fixed on the master branch (next release candidate) - probably by the related issue linked in my last comment.
You could test this by loading Highcharts from `https://github.highcharts.com/master/highcharts.js`.

Please double-check (as I have checked and it works fine for me) and we should be able to close this issue as a duplicate of the related fixed issue.

**Comment by peppe7119** [comment] 2021-02-09 13:10
Hi,
I tried using Highcharts from `https://github.highcharts.com/master/highcharts.js.`

But I get the following warning:

```
Warning: https://github.highcharts.com/master/highcharts.js:18714 SyntaxError: Expected an identifier but found 'addEvent' instead
Warning: http://http://localhost:8080/report:88 ReferenceError: Can't find variable: Highcharts
```

What kind of problem is it? I always use the same settings of the graphs used up to now

**Comment by KacperMadej** [comment] 2021-02-09 15:00
The code on the master is changing frequently (and might be unstable from time to time), so we might have been testing different code versions.
Please try with a code build right after the relevant commit - `https://github.highcharts.com/3731958/highcharts.js`.

**Comment by peppe7119** [comment] 2021-02-09 15:17
I confirm that with the release you indicated to me, the generation of the graphs with wkhtmltopdf is successful without some kind of problem. This release contains the fix for the issue in question.

It will be integrated in the future release is this correct?

Thank You.

Kind Regards

**Comment by KacperMadej** [comment] 2021-02-09 16:28
Thank you for checking this.
Yes, the fix is currently a part of the next release candidate code version, so should be released in the next version.

Closing as a duplicate of https://github.com/highcharts/highcharts/issues/15037

**Closed by KacperMadej** 2021-02-09 16:28 UTC
Labels: Status: Pending reply
