### ISSUE TITLE
Legend scrolling does not work at all on IE

### ISSUE THREAD

**Issue by vardhini** [highcharts/highcharts#2126] opened 2013-08-09 15:45 UTC
If I have a chart with a large legend (pie or stacked column) and I paginate it, the page page navigation works fine on Chrome and firefox but just does not work on IE (Tested on IE9, IE8, and IE6).

**Comment by jon-a-nygaard** [comment] 2016-04-26 10:59
Closing this issue due to: We are not able to reproduce the issue, and it is pending reply. 
Should anyone have further information on this issue, please add a comment and reopen.

**Closed by jon-a-nygaard** 2016-04-26 10:59 UTC
Labels: Cant reproduce, Pending reply
