### ISSUE TITLE
Performance drops by factor of 10-20

### ISSUE THREAD

**Issue by alecmocatta** [highcharts/highcharts#2381] opened 2013-10-20 19:40 UTC
I have an entirely ajax site. After going back and forth between pages, rendering a graph on one of the pages a few times, there is a sudden and dramatic slowdown.

I'm going to continue looking into it. In the meantime, here are some Chrome cpu profiles of it running in ~236ms:
https://gist.github.com/alecmocatta/7074124/raw/0f69a9ab652fb252883e2af221129dbd26cedf17/CPU-20131020T201033.cpuprofile

And in ~2274ms.
https://gist.github.com/alecmocatta/7074124/raw/c507bd55cfa2b760a57fa37c783ab713d1eed384/CPU-20131020T201019.cpuprofile

I have a feeling it's Chrome being very slow in doing the layout during offsetWidth and offsetHeight.

**Comment by jon-a-nygaard** [comment] 2016-04-26 10:04
Closing this issue due to: We are not able to reproduce the issue, and it is pending reply. 
Should anyone have further information on this issue, please add a comment and reopen.

**Closed by jon-a-nygaard** 2016-04-26 10:04 UTC
Labels: Cant reproduce, Pending reply
