### ISSUE TITLE
Tooltip stops working when another chart is hidden

### ISSUE THREAD

**Issue by hugopeixoto** [highcharts/highcharts#5949] opened 2016-11-09 10:59 UTC
This only occurs on the css version.

#### Expected behaviour
With multiple charts on the same page, when hiding one of them, the tooltip of the visible ones should still work

#### Actual behaviour
The tooltip stops working on the visible charts if the last action was hiding a chart.
For example, with 3 charts:
- hide(1): tooltips of 2 and 3 don't work;
- hide(1), show(1): tooltips of 1, 2, and 3 work;
- hide(1), hide(2), show(2): tooltips of 2 and 3 work;
- hide(2), show(2), hide(1); tooltips of 2 and 3 don't work;

#### Live demo with steps to reproduce
http://jsfiddle.net/LLExL/6718/

#### Affected browser(s)
Only tested on chrome

**Comment by pawelfus** [comment] 2016-11-09 12:42
Hi @hugopeixoto 

Thank you for reporting. Actually it's a duplicate of #5859.

Workaround: http://jsfiddle.net/LLExL/6719/

**Closed by pawelfus** 2016-11-09 12:42 UTC
Labels: Duplicate
