### ISSUE TITLE
Accessibility module breaks legend's navigation

### ISSUE THREAD

**Issue by kamilkulig** [highcharts/highcharts#12090] opened 2019-09-27 11:59 UTC
#### Expected behaviour
Legend navigation should work.

#### Actual behaviour
It doesn't because of accessibility module. Everything works well if the module is not imported.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/1d5qarn9/ 
Click legend navigation arrow.

#### Product version
Highcharts 7.2.0

**Comment by oysteinmoseng** [comment] 2019-09-30 12:07
Internal note: Proxy buttons are overlaying page navigation arrow. Should be hidden when the button is not visible on the current page.

**Comment by wergeld** [comment] 2019-10-07 18:14
In our cases this bug also causes the .NET page the chart is on to reload. It affects:
Clicking on legend series item
Clicking on legend navigation arrows (as described in OP)
Clicking on Stock Tools GUI elements that add items to a chart (not caused by opening the Stock Tools menu items, but on "Add" button for example)

Only solution we have found is to remove the accessibility.js module - a non-starter for our requirements.

**Comment by oysteinmoseng** [comment] 2019-10-08 11:46
@wergeld This issue has been fixed in dev code. The fix will be released with Highcharts 8 within a few weeks.

For now the simplest workaround would be to disable accessibility on the legend with the `legend.accessibility.enabled` option: https://jsfiddle.net/3faw6v4c/. This hides the legend from screen reader users, and does not allow keyboard or voice input interaction with the legend, but the rest of the chart keeps the accessibility features enabled.

**Comment by wergeld** [comment] 2019-10-08 11:51
@oysteinmoseng I will have to review or license to see if we get HC v8 (we had just renewed and upgraded this year to highcharts/highstock/highmaps) because disabling accessibility is a non-starter for us due to contract requirements for our clients.

**Comment by oysteinmoseng** [comment] 2019-10-08 12:33
I would highly recommend the HC8 upgrade as there will be many new features and improvements. If you are not able to get this, however, we can look into the possibility of making a drop-in fix for HC7 on this particular issue.

**Comment by wergeld** [comment] 2019-10-08 12:40
@oysteinmoseng I believe we should get it as we have the Highcharts Suite license and we purchased in February of this year - online states we should get 12 months of all releases from purchase date.

**Closed** 2019-11-08 14:14 UTC
Labels: Type: Bug
