### ISSUE TITLE
Line chart opacity not applied until first chart interaction

### ISSUE THREAD

**Issue by Philzen** [highcharts/highcharts#13581] opened 2020-05-24 20:10 UTC
#### Expected behaviour

According to [the docs](https://api.highcharts.com/highcharts/series.line.opacity) setting opacity on a line series should render line, fill (e.g. area) and dataLabels of that series with the given opacity.

#### Actual behaviour

The line chart is rendered as if opacity was still set to `1`. However, upon first interaction with the chart (i.e. hovering over it with the mouse) the opacity is correctly applied.

#### Live demo with steps to reproduce

https://jsfiddle.net/fqz7xhco/

#### Product version

Highcharts v8.1.0

#### Affected browser(s)

Firefox 76.0.1 (64-Bit)
Chromium Version 81.0.4044.138 Arch Linux (64-Bit)

**Comment by Philzen** [comment] 2020-05-24 20:14
BTW - setting opacity via 'rgba(...)' color setting works like a charm, so this is a workaround for now.

**Comment by sebastianbochan** [comment] 2020-05-25 07:59
Hi @Philzen,
Thank you for reporting. It looks like a bug, also when we disable the inactive state.

Demo:
- https://jsfiddle.net/BlackLabel/hbueqdy8/

**Comment by sebastianbochan** [comment] 2020-05-28 08:36
The issue has been already fixed on master by commit: https://github.com/highcharts/highcharts/pull/13290/commits/ed566b8c8b5559ece34e8e1c6919fb40c8fe96e5

Duplicate of: https://github.com/highcharts/highcharts/issues/11750

**Closed by sebastianbochan** 2020-05-28 08:36 UTC
Labels: Status: Has workaround, Status: Inbox, Type: Bug, Type: Good for beginners

**Comment by Philzen** [comment] 2020-06-19 00:12
Now i see that it was pretty much described in #12092 already... sorry, that must have slipped when i entered the issue. Still, thanks for your efforts!
