### ISSUE TITLE
Highcharts area point selection is wrong when rotated vertically

### ISSUE THREAD

**Issue by pengiundev** [highcharts/highcharts#13211] opened 2020-03-26 15:35 UTC
#### Expected behaviour
When CSS `transform: rotate(-90deg)` is applied on an area chart container, when hovering over the chart, selected points' expected behavior is a point to be selected when moving mouse up/down(Y coordinates).

#### Actual behaviour
When hovering over the chart, selected points' actual behavior is that a point is selected when moving mouse left/right(X coordinates) which is not intuitive and confusing. In addition, hovering over the asks series, actually makes the bids series active.

#### Live demo with steps to reproduce
https://jsfiddle.net/yqp6o9f2/

#### Product version
Highcharts JS v8.0.4 (2020-03-10)

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment] 2020-03-27 08:37
Hi @pengiundev,
Thank you for reporting about the problem.  It's a general issue with rotation of a chart via CSS transform. Mouse events are not properly handled. You can see that tooltip is not properly displayed either.

Closing as duplicate of https://github.com/highcharts/highcharts/issues/3617 (issue's name is a bit different, but under the hood it's the same problem - mouse events).

**Closed by sebastianbochan** 2020-03-27 08:37 UTC
