### ISSUE TITLE
Rendering breaks after setting axis labels `x` value in responsive options

### ISSUE THREAD

**Issue by gilmoreorless** [highcharts/highcharts#11458] opened 2019-07-23 00:51 UTC
#### Expected behaviour

Setting `chartOptions.yAxis.labels.x` in `responsive.rules[]` should use the custom `x` value when the rule matches, and the default value when no rules match.

#### Actual behaviour

The custom `x` value is used when the rule matches. But once the rule has stopped matching, the chart rendering breaks and console errors are thrown:

```
Error: <text> attribute x: Expected length, "NaN".
```

This only happens with `x`; setting `y` works fine.

#### Live demo with steps to reproduce

https://jsfiddle.net/gilmoreorless/hq7edm5z/

Click "Toggle width" twice and the rendering will break.

This also appears on the ["Responsive chart"](https://www.highcharts.com/demo/responsive) demo on the Highcharts site (click "Small" then "Large").

After digging into it, I've found this also happens when just setting the `x` value to `undefined` directly in the options: https://jsfiddle.net/gilmoreorless/8brtqwpv/

#### Product version

Highcharts 7.1.2

#### Affected browser(s)

All

#### Potential cause & solution

From what I can tell, there are 2 parts to this bug:

##### 1. Setting `chartOptions.yAxis.labels.x` in `responsive.rules[]`

* When the `x` property hasn't been provided at all in the base options, it falls back to a default value.
* When the `x` property is provided in a responsive rule, and that rule matches, it overrides the default value. But before applying it, a snapshot is taken of the previous **user-defined** values of the defined properties: https://github.com/highcharts/highcharts/blob/91df181bb32a3d8235d9e83ea527893d55d9df17/ts/parts/Responsive.ts#L266
* Because the snapshot is of the user-defined properties, it saves `x` as `undefined` rather than the applied default value (this makes sense).
* When the responsive rule no longer matches, the previous snapshot of values is applied. This passes `x: undefined` into the `update` methods, which hits part 2...

##### 2. Setting `chartOptions.yAxis.labels.x` to `undefined` breaks rendering

The error is in the calculation of `labelOffsetPadded` in `Axis.ts`: https://github.com/highcharts/highcharts/blob/91df181bb32a3d8235d9e83ea527893d55d9df17/ts/parts/Axis.ts#L6661

* When `y` is `undefined`, the `pick()` call will fall back to `axis.tickRotCorr.y + directionFactor * 8`.
* When `x` is `undefined`, that value is directly multiplied by `directionFactor`, resulting in a value of `NaN` which is passed on to further calculations.

My suggested fix is to wrap the accessor in `pick()` with a fallback number, to stop the calculation returning `NaN`. (But there may be more consequences of this that I'm not aware of.)

**Comment by pawelfus** [comment] 2019-07-23 08:59
Thanks for reporting the issue and all of the details @gilmoreorless ! 

In theory 
> Setting `chartOptions.yAxis.labels.x` to `undefined`
Is just a misconfiguration - `x` value should be a number, just like API defines: https://api.highcharts.com/highcharts/yAxis.labels.x

Of course, the issue with responsive rules should be fixed. The problem here is different `x` value for left/right axis which is handled when `labels.x` is not defined.

Bisected to commit 7aefc37131 - marking as regression.

**Internal note:**
This happens in `Axis.setOptions`, where we merge `default[Side]AxisOptions` with `userOptions`. By the nature of `merge` we have: `Highcharts.merge({x: 1}, {x: undefined})` => `{x: undefined}` which is expected. So either try solution suggested by OP, or consider improving `Axis.setOptions`, or improve fix in 7aefc37131.

**Comment by PaulDalek** [comment] 2021-01-20 12:52
Unstale.

**Comment by khlieng** [comment] 2021-03-24 09:09
Fixed since 7.1.3.

**Closed by khlieng** 2021-03-24 09:09 UTC
Labels: Type: Regression
