### ISSUE TITLE
Tooltip's date format for milestone type points wrong format.

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#10383] opened 2019-03-21 13:25 UTC
#### Expected behaviour
The date of milestone points should be presented as the "Day Month, Hour" format by default.

#### Actual behaviour
Currently, there is no information about the day and month of milestone points, only the time is shown in tooltip. 

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/gantt/gantt/milestones
Take a look on the date format of milestone point's tooltip, and compare it with range point. For range type points, always the day and the month are available, but on milestones only the time.

_Internal note:_
_Within `tooltip.pointFormatter` definition, the `formats` object shouldn't be actually taken from tooltip options instead of xAxis options?_
https://github.com/highcharts/highcharts/blob/c6cfe0e0000ce75f8f0b87f832cc5af01d7841f2/js/parts-gantt/GanttSeries.js#L78-L79

https://jsfiddle.net/BlackLabel/zwdp8kyg/

**Comment by raf18seb** [comment] 2019-04-16 13:16
+1

I have a similar issue. Milestone's tooltip doesn't display the content of tooltip.pointFormat.
It's visible here in this simplified demo: https://jsfiddle.net/BlackLabel/4sgnhfvk

Worked fine in 7.0.3 but stopped since 7.1.0.

@TorsteinHonsi any comment?

**Comment by tlkvastad** [comment] 2019-04-23 07:59
Same problem. Hope it will be fixed soon

**Comment by TorsteinHonsi** [comment] 2019-04-24 08:46
Sorry for the delay.

Apparently we have two issues now.
* A regression in v7.1 causes the `pointFormat` to be lost on milestones.
* The original issue with time formatting.

I will work on it now.

**Comment by TorsteinHonsi** [comment] 2019-04-24 10:18
> Within tooltip.pointFormatter definition, the formats object shouldn't be actually taken from tooltip options instead of xAxis options?

@Denyllon Nice catch, thanks!

**Closed** 2019-04-24 10:19 UTC
Labels: Product: Highcharts Gantt, Type: Bug
