### ISSUE TITLE
Highcharts always executes the "initial version" of my event handler function, resulting in stale values being used

### ISSUE THREAD

**Issue by srmagura** [highcharts/highcharts#19479] opened 2023-08-01 15:54 UTC
Here's a quick summary of the issue — see my [GitHub repo](https://github.com/srmagura/highcharts-event-handler-repro) for the full code and steps to reproduce. Thank you in advance!!

I do not think there is anything React-specific about this issue, but it is easiest for me to explain within the context of React. I can create a non-React minimal repro if desired.

My React code:

```tsx
function App() {
  // A datetime that represents when the `App` component last rendered
  const [renderDate, setRenderDate] = useState(() => new Date());

  // Rerender the component each second
  //
  // (This is very artificial and just for the minimal repro. In a real
  // application, rerenders would likely be caused by updates to the data, not a
  // timer.)
  useEffect(() => {
    const interval = setInterval(() => {
      setRenderDate(new Date());
    }, 1000);

    return () => {
      clearInterval(interval);
    };
  }, []);

  const mySeries: Highcharts.SeriesOptionsType = { /* ... */ };

  const handlePointSelect: Highcharts.PointSelectCallbackFunction = () => {
    // This _should_ always print a datetime that's within the last second (in
    // my opinion). It actually prints the datetime when that particular point
    // was first selected.
    console.log(`Point selected: ${renderDate.toISOString()}`);
  };

  const options: Highcharts.Options = {
    series: [mySeries],

    plotOptions: {
      series: {
        allowPointSelect: true,

        point: {
          events: {
            select: handlePointSelect,
          },
        },
      },
    },

    /* ... */
  };

  return (
    <main>
      <HighchartsReact highcharts={Highcharts} options={options} />
    </main>
  );
}
```

#### Expected behaviour

When a point is selected, Highcharts executes the "latest version" of the `handlePointSelect` event handler.

#### Actual behaviour

When a point is selected for the second/third/.etc time, Highcharts executes the "initial version" of the `handlePointSelect` event handler.

**Here's why this is a problem:** In my real application, my event handler updates the UI based on variables that are captured within the event handler function's closure. For my application to work correctly, the event handler must "see" the latest values of those variables. In reality, my event handler sees stale values of the variables (from when the event handler was first executed).

#### Live demo with steps to reproduce

https://github.com/srmagura/highcharts-event-handler-repro

#### Product version

Highcharts 11.1.0
highcharts-react-official 3.2.0

#### Affected browser(s)

This probably affects all browsers. I tested it in Chrome.

**Comment by karolkolodziej** [comment] 2023-08-04 11:01
Hi @srmagura! 

Are you sure that this issue isn't connected to React at all?
I've tried to recreate the issue in JS but accessing a global variable `renderDate` always results in the correct time displayed in the console- [demo](https://jsfiddle.net/BlackLabel/z51vdfn6/).

Will you be able to modify the demo to recreate the issue? If not we are going to dive deeper into your React demo 😉

**Comment by srmagura** [comment] 2023-08-04 16:55
Hey @karolkolodziej, thanks for encouraging me to create a non-React version of the minimal repro. Here it is: https://jsfiddle.net/srmagura/rewsv4gc/4/

An essential part of the repro is that `chart.update()` is called several times, with a new `handleSelect` event listener each time. Your jsfiddle did not do this, which is why you didn't see the stale event handler issue. Thanks!

**Comment by srmagura** [comment] 2023-08-07 18:21
Here's a workaround for the problem! https://jsfiddle.net/srmagura/nsh850wj/5/

**Comment by karolkolodziej** [comment] 2023-08-14 06:11
Thank you @srmagura for sharing this! 
With that, I will close this issue as not a bug. It's more related to how the JS works than something wrong with the library.

**Closed by karolkolodziej** 2023-08-14 06:11 UTC
Labels: Status: Pending reply
