### ISSUE TITLE
Tooltips shows last known point when data is missing

### ISSUE THREAD

**Issue by kennydp** [highcharts/highcharts#6496] opened 2017-03-22 10:40 UTC
#### Expected behaviour

I have a chart with different series in them. It's possible that one of these series only has data up to a certain point. So when I hover over a part of the chart that does not have data for this series, it should just show nothing for that series.

#### Actual behaviour

You can sometimes see the data for the last point you have for that series in the tooltip, instead of nothing.

#### Live demo with steps to reproduce

https://jsfiddle.net/y4zg6x06/1/
In the fiddle you can see that when you hover over one of the columns, when the data for series 1 is missing, you can sometimes see the data of the last point of series 1 in the tooltip. This only seems to happen when the tooltip gets positioned at the top of the chart.

#### Affected browser(s)

I have tested this in chrome, firefox and safari.

**Comment by TorsteinHonsi** [comment] 2017-03-23 13:23
Regression since v5.0.8 - v5.0.7 works correctly: http://jsfiddle.net/highcharts/y4zg6x06/4/

**Comment by TorsteinHonsi** [comment] 2017-03-23 13:28
It's a duplicate, fixed now in master: http://jsfiddle.net/highcharts/y4zg6x06/5/

**Closed by TorsteinHonsi** 2017-03-23 13:28 UTC
Labels: Regression
