### ISSUE TITLE
Exception in Chrome when calling chart.reflow from beforeprint event

### ISSUE THREAD

**Issue by RandScullard** [highcharts/highcharts#16931] opened 2022-01-27 21:39 UTC
#### Expected behaviour
No exception is thrown when calling `chart.reflow` from the `beforeprint` event in Chrome.

#### Actual behaviour
Exception is thrown in Chrome:
```
Error: Failed to execute 'invoke' on 'CreateHTMLCallback': The provided callback is no longer runnable.
    at h.parseMarkup (https://code.highcharts.com/highcharts.js:59:245)
    at new h (https://code.highcharts.com/highcharts.js:57:140)
    at k.buildSVG (https://code.highcharts.com/highcharts.js:118:367)
    at L.buildText (https://code.highcharts.com/highcharts.js:132:447)
    at a.css (https://code.highcharts.com/highcharts.js:79:320)
    at a.<anonymous> (https://code.highcharts.com/highcharts.js:373:370)
    at Array.forEach (<anonymous>)
    at a.layOutTitles (https://code.highcharts.com/highcharts.js:373:161)
    at a.setSize (https://code.highcharts.com/highcharts.js:382:502)
    at Number.<anonymous> (https://code.highcharts.com/highcharts.js:381:169)
```

#### Live demo with steps to reproduce

1. Load this demo in Chrome: https://codepen.io/RandScullard/pen/abVOZvW
2. Open Chrome's dev tools.
3. Click the Print button below the chart. (**Note:** Do not use the browser's native print command, such as Ctrl+P -- for some reason, the exception is only thrown when you click the Print button.)
4. The exception will immediately be thrown.

#### Product version

Highcharts 9.3.2

#### Affected browser(s)
Chrome 97.0.4692.99

**Comment by raf18seb** [comment] 2022-01-31 16:06
Hi @RandScullard, thanks for creating the ticket!

We recommend printing Highcharts chart using our internal methods and event callbacks:
https://api.highcharts.com/class-reference/Highcharts.Chart#print
https://api.highcharts.com/highcharts/chart.events.beforePrint
https://api.highcharts.com/highcharts/chart.events.afterPrint

Working demo: https://jsfiddle.net/BlackLabel/Lqwm5hnj/

Closing as resolved on Highcharts's side.

**Comment by RandScullard** [comment] 2022-01-31 16:09
@raf18seb My requirement is to print an entire report page which includes several Highcharts charts. I don't think I can meet that requirement using the Highcharts methods. Please let me know if there is an alternative way to do this.

**Comment by raf18seb** [comment] 2022-02-01 11:54
Hi @RandScullard,

My apologies, I investigated a problem closer and it seems it's actually a problem with our code. Thank you for your comment.

`Internal note:`
Working fine in 9.3.1, fails since 9.3.2.
Looks like a regression of https://github.com/highcharts/highcharts/commit/eac591a24b7c9ada59f9090c9362978097e8be75

Simplified demo: https://jsfiddle.net/BlackLabel/u0Locegd/
Problem is visible when a series' label is hidden when there's no space for it (in this case "Project Development").

**Comment by RandScullard** [comment] 2022-02-01 16:02
@raf18seb That's great news, thanks for taking another look! Hopefully it's a quick and easy fix...

**Comment by vddastranger** [comment] 2022-07-12 10:10
Have the same issue after upgrading the version 9.1.2 -> 10.1.0. Pretty much the same requirements as @RandScullard 's

**Comment by Techn1x** [comment] 2022-10-20 14:36
This is still not working :( chart printing has been broken for a year now.

Does highcharts need to fix how it is using Trusted Types? Or is this something on chromium's end? The related bug tickets seem to be stale / resolved ?
https://bugs.chromium.org/p/chromium/issues/detail?id=956832
https://bugs.chromium.org/p/chromium/issues/detail?id=1101344

**Comment by karolkolodziej** [comment] 2022-10-24 09:12
There were a few Chrome updates from the originally reported one.
I'm currently using `106.0.5249.119` and I do not get that exception. 
I am also unable to recreate Rafal's issue.

Could you please @Techn1x elaborate on what your example looks like?

**Comment by Techn1x** [comment] 2022-10-24 09:48
Using current latest highcharts 10.2.1

current latest chrome
![Screenshot from 2022-10-24 19-43-51](https://user-images.githubusercontent.com/1049837/197498126-5ed11525-8730-4bf4-a21a-b1f85a468c88.png)

My code looks like this, with some added comments about how flipping annoying it already is to print on the web even without the issue in this ticket;
```js
  const reflowHandler = (mediaQueryEvent) => {
    /* In both cases we just reflow the chart. But if you wanted to do something different here (eg set the chart to
     * black and white, or some other chart option), you could.
     */
    const isPrint = mediaQueryEvent.matches
    if (isPrint) {
      chart?.reflow()
    } else {
      chart?.reflow()
    }
  }

  /* Note: match media print does not fire on Firefox and IE
   * https://bugzilla.mozilla.org/show_bug.cgi?id=774398
   *
   * This still seems to be the best way to do it. beforeprint and afterprint events can be listened to, but beforeprint
   * fires before the document has been resized to the print media, so isn't useful to us.
   *
   * Highcharts have had this as an open issue since 2013, but there has been some recent work on it
   * https://github.com/highcharts/highcharts/issues/2284
   * https://github.com/highcharts/highcharts/pull/15112
   */
  const printMedia = window.matchMedia('print')
  printMedia?.addEventListener?.('change', reflowHandler)

  return () => {
    printMedia?.removeEventListener?.('change', reflowHandler)
  }
```

you can see the chart has not resized for print, and an error is produced in the console.
![Screenshot from 2022-10-24 19-45-35](https://user-images.githubusercontent.com/1049837/197498432-c756d4ae-ebef-4073-9b28-b0d1bdd50535.png)

**Comment by RandScullard** [comment] 2022-10-24 13:56
FWIW, I just reproduced the error using the CodePen sample from my original bug report (see above). I am using Chrome 106.0.5249.119 on Windows.

**Comment by raf18seb** [comment] 2022-10-25 11:35
Something has changed since the last time I checked this. I was able to reproduce this error only for a certain label from the `series-label.js` module. Now it fails for each string displaying on a chart (chart title, axis title, series name...) regardless of a Highcharts version (but 9.3.2+). I suspect it depends on a browser version (probably one of the above Chromium fixes changed something).
We're able to reproduce the issue only on Chromium on Windows (Chrome 106.0.5249.119 and Opera 92.0.4561.21)

I think the next step would be to ensure whether it's a Highcharts issue or a Chromium bug.
@TorsteinHonsi could you take a closer look at it?

**Comment by TorsteinHonsi** [comment] 2022-10-26 11:40
Apparently it is a [Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1316315).

The folks at DOMPurify are [having the same issue](https://github.com/cure53/DOMPurify/issues/529), and like them, I am reluctant to monkey patch the code for broken browsers. 

Is it suffient for you to wrap the error in a try-catch? Or does it actually break some behaviour? See https://jsfiddle.net/highcharts/4e91ka2q/ . 

One peculiar detail i noticed while testing on Mac/Chrome v106, is that when I remove the `figure` element surrounding the container div, the error doesn't happen.

**Comment by Techn1x** [comment] 2023-01-17 01:55
Still exists on ubuntu/chrome 108 

> Is it suffient for you to wrap the error in a try-catch? Or does it actually break some behaviour? See

Wrapping in a try/catch catches the error but the charts do not resize - you can see in the jsfiddle you linked that is also the case
![Screenshot from 2023-01-17 11-39-15](https://user-images.githubusercontent.com/1049837/212791101-d3c48f31-ef6a-4e45-a982-08d6bbac8724.png)

> One peculiar detail i noticed while testing on Mac/Chrome v106, is that when I remove the figure element surrounding the container div, the error doesn't happen.

I think that might be a red herring - to me it looks like it just doesn't throw the error multiple times (but it does still fail to reflow every time)

**Comment by Techn1x** [comment] 2023-01-17 01:58
There's also a very good jsfiddle from this PR https://github.com/highcharts/highcharts/issues/17533 demonstrating the issue
http://jsfiddle.net/t0pn9c27/

**Comment by tzar** [comment] 2023-05-22 02:34
It looks like you can work around this by disabling the use of trusted types in highcharts - maybe an option to turn them off would be handy until chromium is fixed? I don't think it breaks anything having them off, firefox doesn't support `TrustedHTML` anyway so it's already off for firefox afaik

**Comment by Techn1x** [comment] 2024-06-26 02:54
I tried out my jsfiddle repro again, on latest highcharts and chromium. Still an issue in 2024 (though works fine in Firefox). My repos are still stuck on 9.3.1

Doesn't seem like there's any movement on the chromium bug tickets.

Kind of a sucky situation all around. Even though it's "chromium's fault", I feel like Highcharts isn't giving us many options here for dealing with it. Is there anything that Highcharts can do?

**Comment by karolkolodziej** [comment] 2024-06-27 06:31
@Techn1x thank you for bringing our attention to this once again! 
We will discuss it internally and let you know what we can do.

**Comment by ruby-clarifruit** [comment] 2024-07-23 14:09
We are also stuck on a very old version due to this bug. Any chance for a fix soon?

**Comment by karolkolodziej** [comment] 2024-07-25 12:48
We have this on our list but with the holiday season, we are short-staffed. We will get back to you soon!

**Comment by ruby-clarifruit** [comment] 2024-08-30 06:40
Just adding that now (since version 128, released in the last few days) it also crashes on Edge, so both Chrome and Edge crash in the same way, when "reflow" is called to re-align charts for printing.

**Comment by KacperMadej** [comment] 2024-08-30 07:12
When the event is fired the changes are not passed to the print preview. If I change some styles it doesn't show up.
![image](https://github.com/user-attachments/assets/d7e121d0-f4db-4e98-b8e0-760ec5d6b253)
This the code I changed in the demo linked in the top comment:
```js
function onPrint(e)
{
	document.body.style.minWidth = (e.type === "beforeprint") ? "7.5in" : "";
	chart.container.style.backgroundColor = 'red';
	//chart.reflow()
}

window.addEventListener("beforeprint", onPrint)
window.addEventListener("afterprint", onPrint)


var chart = Highcharts.chart('container', {
	chart: {
  	backgroundColor: 'rgba(255, 0, 255, 0.1)'
  },
```

Because of this, it seems like even if the reflow was not throwing an error, it would still have no visible effect on the print and print preview. If you have a newer demo that should be tested or anything to elaborate on with regards to this please share.

Tested on: Windows 10 / Chrome (128)

**Comment by KacperMadej** [comment] 2024-09-05 09:53
Is this related to https://github.com/highcharts/highcharts/pull/15112#issuecomment-781256635 ? @TorsteinHonsi

**Comment by ruby-clarifruit** [comment] 2024-09-05 11:25
@KacperMadej here's an updated example: https://codepen.io/ruby-clarifruit/pen/YzoRgjg
It uses the old-working version of highcharts, 9.3.1, and reflows well when printing.
If you use the latest (you can update the script imports) then you'll see that when printing it doesn't reflow well (there's an exception in the console.log).

**Comment by TorsteinHonsi** [comment] 2024-09-06 11:51
## Workaround

Someone asked above if there is a way to turn off trusted types for Highcharts. Actually it seems that we can pretty easily disable it at the time the library is loaded, then restore it afterwards:

```html
<script>
window.trustedTypesCopy = window.trustedTypes;
delete window.trustedTypes
</script>
<script src="http://localhost:3031/highcharts.js"></script>
<script>
window.trustedTypes = window.trustedTypesCopy;
</script>
```

It's quite ugly, but it highjacks the [test in Highcharts](https://github.com/highcharts/highcharts/blob/59d54ca0af14446dee39b0e3b7e3dc04c8bf9190/ts/Core/Renderer/HTML/AST.ts#L39-L58) and seems to do the trick . View it [live on jsFiddle](https://jsfiddle.net/highcharts/y4mrpk0b/1/).

**Comment by TorsteinHonsi** [comment] 2024-09-06 12:36
I added (or rather re-used) a try-catch block around the DOMParser so that the failing browsers fall back to reading `innerHTML`.

Those of you who want to test with your own setup can try out https://github.highcharts.com/460e07d1cd6b4022ce9af70dfb6f15ec9cd61088/highcharts.js . It comes without uptime guarantee, so don't use it in production. View a live test case in https://jsfiddle.net/highcharts/h9z6ye4p/.

**Comment by Techn1x** [comment] 2024-09-06 13:06
Oooh thanks, will give it a go first thing Monday!

**Closed** 2024-09-10 16:31 UTC
Labels: Product: Highcharts, Status: Pending reply, Type: Regression

**Comment by Techn1x** [comment] 2024-09-11 09:21
That demo seems to work really nicely
I'm not able to check the JS there, but I'll be sure to update and check the fix in the latest highchart version on next release- thanks!

**Comment by Techn1x** [comment] 2024-11-06 01:17
I am very excited for the highcharts v12 release. Refreshing the changelog page every day 😄 
https://www.highcharts.com/blog/changelog/

**Comment by ruby-clarifruit** [comment] 2024-11-20 07:16
Anyone knows if tehre's an ETA for v12 release with this fix in it?

**Comment by karolkolodziej** [comment] 2024-11-20 08:32
We are doing some final tests and the v12 should be released within a week.

**Comment by Techn1x** [comment] 2024-11-29 06:10
This is working great. Many, many thanks
