### ISSUE TITLE
Highcharts Stock charts navigation months are showing twice

### ISSUE THREAD

**Issue by pratheeshkumarrd** [highcharts/highcharts#15968] opened 2021-06-28 07:39 UTC
Expected: We are showing a period of one year for stock charts (12 months) using navigation bars. Whatever time zone user selected it should be same.

Actual: When we select PST/ EST time zone, November month alone showing twice as the formatter function is triggering twice for November month. Whereas for IST it's working fine

When we try from IST

<img width="1575" alt="112005443-c2f9f780-8b48-11eb-826e-29ff80d9e410" src="https://user-images.githubusercontent.com/16553075/123598640-baa5fe00-d7c2-11eb-94d7-da0a3663f7f4.png">

Formatter function (console) when we try from IST
<img width="97" alt="112005953-40be0300-8b49-11eb-8808-7100b0169f67" src="https://user-images.githubusercontent.com/16553075/123598697-c72a5680-d7c2-11eb-93ac-ca7d5ad5d461.png">

When we try from PST/EST
<img width="1571" alt="112004406-cb056780-8b47-11eb-831a-49e650ede2fd" src="https://user-images.githubusercontent.com/16553075/123598726-cf829180-d7c2-11eb-99b5-d5454c8d99a0.png">

Formatter function (console) when we try from PST/ EST
<img width="125" alt="112005234-93e38600-8b48-11eb-9ecf-766bdfa494ee" src="https://user-images.githubusercontent.com/16553075/123598752-d6a99f80-d7c2-11eb-90b0-27285925cbb5.png">

**Comment by khlieng** [comment] 2021-06-28 07:55
Duplicate of #15372.

**Closed by khlieng** 2021-06-28 07:55 UTC
Labels: Type: Duplicate
