### ISSUE TITLE
Stock tools annotation doesn't work on mobile touch devices.

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#10886] opened 2019-06-05 08:17 UTC
#### Actual behaviour
Like in the title. Annotation gui works on Android, but it's really hard to use it. Saying 'it's really hard to use it' I mean that I need to click many times on, let's say, circle annotation to draw it, and even if I manage to draw it, it appears in a random place and it's not possible to set its size.

It doesn't work at all on IOS. When I click annotation, let's say circle again, and I try to draw it, nothing happens.

#### Live demo with steps to reproduce
https://www.highcharts.com/stock/demo/stock-tools-gui

#### Product version
Highstock 7.1.2

#### Affected browser(s)
All

**Comment by pawelfus** [comment] 2019-11-07 16:01
Closing as duplicate of #12216

**Closed by pawelfus** 2019-11-07 16:01 UTC
Labels: Product: Highstock, Type: Bug, Type: Duplicate
