### ISSUE TITLE
Tooltip does not show if there are multiple charts and one is hidden

### ISSUE THREAD

**Issue by jakubSzuminski** [highcharts/highcharts#18928] opened 2023-05-03 09:38 UTC
#### Actual behaviour
If there is more than one chart, and `display: none` is set for one of the charts, the tooltip shows only for the first chart.

#### Live demo with steps to reproduce
**Demo:** https://jsfiddle.net/BlackLabel/jr82ognp/
1. Switch tabs
2. Hover over a series (there's no tooltip).

#### Product version
Regression from Highcharts 11 (everything worked well for <= 10.3.3)

**Comment by TorsteinHonsi** [comment] 2023-05-03 12:31
I think this is a duplicate of #18920. I'll have a look.

**Closed** 2023-05-04 10:54 UTC
Labels: Type: Bug, Product: Highcharts, Priority: Blocker, Type: Regression, Flow: Review in progress
