### ISSUE TITLE
problems with dataLabels on bar chart, when set dataLabels.useHTML = true

### ISSUE THREAD

**Issue by stormitornado** [highcharts/highcharts#7480] opened 2017-12-03 16:50 UTC
Hi,
I have a problem with dataLabels on bar chart, when set dataLabels.useHTML = true
Last label has css classes from labels container (highcharts-data-labels)
and accordingly don't receive  css class from dataLabels.className and code from dataLabels.formatter.
Events also aren't binding with last element.

![default](https://user-images.githubusercontent.com/29771000/33527334-d91d6fdc-d85f-11e7-9add-30f2808ce4f4.png)

options object:
```
options: {
	chart: {
		type: 'bar'
	},
	xAxis: {
		visible: false
	},
	yAxis: {
		visible: false
	},
	legend: { enabled: false },
	tooltip: { enabled: false },
	plotOptions: {
		bar: {
			minPointLength: 2,
			dataLabels: {
				enabled: true,
				x: 20, y: -4,
				padding: 0,
				align: 'left',
				inside: true,
				crop: false,
				defer: false,
				useHTML: true,
				overflow:"none"
			},
			colorByPoint: true,
			pointPadding: 0,
			groupPadding: 0,
			grouping: false,
			connectNulls: true
		}
	},
	series: [{
		name: 'servicesProblemsSolved',
		data: [],
		dataLabels: {
			className: 'analytics_horiz-bar-label_combined ',
			formatter: function () {
				return '<span>' + this.point.name + '</span> <span>' + this.point.full + ' отправлено / ' + this.y + ' решено</span>';
			}
		}
	}, {
		name: 'servicesProblemsTotal',
		data: []
	}]
}
```
data was appended further in a code before invoke new Highcharts() 

#### Affected browsers
any
#### Affected versions
5, 6 with last subversions

**Comment by KacperMadej** [comment] 2017-12-03 19:51
Hi,

Thank you for notifying us about the problem.
The issue was already reported, investigated and a fix is suggested.
Duplicate of #7287

**Closed by KacperMadej** 2017-12-03 19:51 UTC
