### ISSUE TITLE
Update in stock does not update series clip rect correctly.

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#14345] opened 2020-10-13 13:15 UTC
#### Behaviour
Series or chart update that will cause the plot area size change is not triggering series clip rect recalculation or is not calculating the rect correctly as some points are clipped away.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/4wyb9t8k/2/

After the update the series looks like this:
![stockBadClipAfterUpdate](https://user-images.githubusercontent.com/8960408/95864754-23993300-0d66-11eb-8363-0947463751f0.jpg)

Resizing the chart (if the width is not fixed like in the attached demo) is resolving the problem - the clip rect is updated to the correct size and the series is looking ok.

#### Product version
8.2.0

#### Affected browser(s)
Probably all. Tested only on Chrome and FF.

**Comment by pawelfus** [comment] 2020-10-14 09:49
Duplicate of #13751

Will be fixed in the next release, demo: https://jsfiddle.net/BlackLabel/4wyb9t8k/3/

**Closed by pawelfus** 2020-10-14 09:49 UTC
Labels: Product: Highcharts Stock, Type: Bug
