### ISSUE TITLE
Synchronised charts demo doesnt show proper tooltip with multiple series in 1 chart

### ISSUE THREAD

**Issue by Arthedian** [highcharts/highcharts#20512] opened 2024-01-24 11:29 UTC
#### Expected behaviour
Show full tooltip (value for every serie) if using synchronised charts for every chart.

![image](https://github.com/highcharts/highcharts/assets/5776865/06291061-f3f3-4543-9e09-9d69f0dc1def)

#### Actual behaviour

In this example [here](https://www.highcharts.com/demo/highcharts/synchronized-charts) every chart has 1 series in each chart. The tooltip is fine. But when I Add additional series into 1 chart, than the tooltip still show value for 1 serie not all series.

![image](https://github.com/highcharts/highcharts/assets/5776865/790f3952-3612-4c1b-a9f3-71d802a48e31)

#### Live demo with steps to reproduce
the problem can be seen in the second chart

https://jsfiddle.net/Arthedian/t4b98ahy/1/

#### Product version
11.3.0

#### Affected browser(s)
all

**Comment by Arthedian** [comment] 2024-01-24 11:33
I noticed that in code below you are selection point from first series, but I am not sure how to highlight all points with pointIndex
```
             const point = chart.series[0].data[pointIndex];
              if (point) {
                point.highlight(e);
              }
```

**Comment by karolkolodziej** [comment] 2024-01-26 12:08
Hi @Arthedian!

The [refresh method](https://api.highcharts.com/class-reference/Highcharts.Tooltip#refresh) should take an array of points.
With a couple of tweaks, you can achieve it- [demo](https://jsfiddle.net/BlackLabel/09Ls57xn/).

At that point, I can also recommend checking our Dashboards product where this functionality is available out of the box.
[Read more in the documentation.](https://www.highcharts.com/docs/dashboards/synchronize-components)

For now, I'm closing as not a bug.

**Closed by karolkolodziej** 2024-01-26 12:08 UTC
