### ISSUE TITLE
Error: Cannot read property 'navigator' of undefined

### ISSUE THREAD

**Issue by chuakc92** [highcharts/highcharts#10102] opened 2019-02-11 03:35 UTC
npm version: '6.7.0'
highchart version: '7.0.3'

I'm getting the following error:
```

TypeError: Cannot read property 'navigator' of undefined
    at /Users/kc/dev18 ios/functions/node_modules/highcharts/modules/exporting.js:10:220
    at /Users/kc/dev18 ios/functions/node_modules/highcharts/modules/exporting.js:34:36
    at Object.<anonymous> (/Users/kc/dev18 ios/functions/index.js:10:40)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:659:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

on the following line:
```
var Highcharts = require('highcharts');
require('highcharts/modules/exporting')(Highcharts);   <---------
```

I'm not doing anything else highcharts-related and I'm trying to deploy to Firebase Functions.

**Comment by pawelfus** [comment] 2019-02-12 12:56
Hi @chuakc92 

Could you check issue #8091 ? Try solutions posted there.

Closing as a duplicate of #8091, please continue discussion in one thread, thanks!

**Closed by pawelfus** 2019-02-12 12:56 UTC
