### ISSUE TITLE
TypeError: wrapper.renderer is undefined

### ISSUE THREAD

**Issue by iweindesmedt** [highcharts/highcharts#2600] opened 2014-01-14 21:58 UTC
cannot reproduce it
```
TypeError: wrapper.renderer is undefined	
...ToClean = wrapper.renderer.isSVG && element.nodeName === 'SPAN' && wrapper.paren...
highstock.src.js (line 2626)
```

maybe changing
```parentToClean = wrapper.renderer.isSVG && element.nodeName === 'SPAN' && wrapper.parentGroup```
to
```parentToClean = wrapper.renderer && wrapper.renderer.isSVG && element.nodeName === 'SPAN' && wrapper.parentGroup```
is enough?

**Comment by jon-a-nygaard** [comment] 2016-04-26 10:01
Closing this issue due to: We are not able to reproduce the issue, and it is pending reply. 
Should anyone have further information on this issue, please add a comment and reopen.

**Closed by jon-a-nygaard** 2016-04-26 10:01 UTC
Labels: Cant reproduce, Pending reply

**Comment by kajyr** [comment] 2017-06-22 10:38
Hi, I am experiencing this issue with the heatmap module, when updating the colorAxis with new custom dataClasses.

**Comment by jon-a-nygaard** [comment] 2017-06-22 11:17
Hi @kajyr , could you a live demo of the issue? JSFiddle is great for this purpose, here's a [quick setup with Highcharts](https://jsfiddle.net/highcharts/llexl/)

**Comment by kajyr** [comment] 2017-06-22 12:21
Thanks @jon-a-nygaard , I am trying to isolate the behaviour in a simple isolated context.

My current setup is based on gulp and requirejs

*  Highcharts + heatmap module are required by requirejs
*  On a mouse event I load data from a server and update with new dataClasses

This alone works. What I am able to reproduce so far is: if another requirejs module is requiring Highcharts + maps module (even if I'm not instantiating a map), when I do the two previous steps I got the error where `a.renderer.isSVG` crashes because `a.renderer` is undefined.

Unfortunately this is not trivial to reproduce in jsfiddle, I will probably try to create a repository with a requirejs + gulp setup to reproduce the issue.

**Comment by kajyr** [comment] 2017-06-22 13:41
Here's a demo: http://jsfiddle.net/kajyr/qs87poms/2/

**Comment by kajyr** [comment] 2017-06-23 10:04
I have tried to reopen and change tags but I'm not allowed. Can some collaborator do that please?

Thanks

**Comment by oysteinmoseng** [comment] 2017-06-23 10:26
@kajyr Heatmap is included in Highmaps and should not be included twice: http://jsfiddle.net/qs87poms/3/. Does this solve your problem?

**Comment by kajyr** [comment] 2017-06-23 11:30
Yes! Thanks! I didn't found out that from the docs! :)

**Comment by nzayatz14** [comment] 2017-08-16 22:50
Hi, I am also experiencing this issue with the arearange series. I am trying to remove the series with a button click and I keep getting this error.

JSFiddle: http://jsfiddle.net/dgddhg1o/

NOTE: I only get the error if the tooltip is displayed/my mouse has dragged through the chart. I do not get this error if my mouse does not enter the chart.

**Comment by TorsteinHonsi** [comment] 2017-08-17 08:22
This latest issue is a duplicate of https://github.com/highcharts/highcharts/issues/7021. It is fixed in the master and will be part of the next maintenance release.
