### ISSUE TITLE
bar: tooltip not follow when xAxis is crosshair and mouse move on empty part of chart

### ISSUE THREAD

**Issue by zhangciwu** [highcharts/highcharts#6517] opened 2017-03-28 08:17 UTC
#### Expected behaviour
when xAxis is crosshair, chart tooltip should be follow mouse when moving around empty part

#### Actual behaviour
when mouse moving on empty part

Wrong: tooltip is frozen, until hover on some bar
(at 5.0.9)

Right: tooltip follows mouse, showing at right bar
(at 5.0.7)

#### Live demo with steps to reproduce
Wrong (5.0.9): https://jsfiddle.net/ussn7b0j/1/
Right (5.0.7): https://jsfiddle.net/ms4gu522/

#### Affected browser(s)
Seems all

### P.S.
Empty part means such area like below
![qq20170328-161611](https://cloud.githubusercontent.com/assets/3340597/24395401/26dcb6ae-13d2-11e7-88e5-bd4e76bb0807.png)

**Comment by TorsteinHonsi** [comment] 2017-03-28 11:42
Fixed on the master branch: http://jsfiddle.net/highcharts/ussn7b0j/2/

We will release this with v5.0.10 within a few weeks.

**Comment by pawelfus** [comment] 2017-05-08 09:26
It's broken again in 5.0.11: http://jsfiddle.net/ussn7b0j/4/

**Comment by jon-a-nygaard** [comment] 2017-05-22 07:37
[Simplified demo](http://jsfiddle.net/jon_a_nygaard/nfrcwteh/)

**Comment by zhangciwu** [comment] 2017-05-22 07:42
@jon-a-nygaard You used a ".local" domain
fixed with ".com" 
http://jsfiddle.net/nfrcwteh/1/

**Comment by jon-a-nygaard** [comment] 2017-05-22 09:00
**Internal Note:** _Was done deliberately in 13cfbe1 due to #6586.
Considering that bar is a series type with `directTouch: true`, this is actually intended behaviour. 
Must be able to differentiate between these two behaviours in a logical way._

**Comment by zhangciwu** [comment] 2017-05-23 08:18
1. wrong context for click callback  (#6586)
2. hover blank area, expect to see tooltip for corresponding column, but not (this issue)
In theory, these two issues seem to be irrelevant, so I think they should be all solved.
Maybe some share code has bind them together, I'll spend some spare time to see if I can help this.

**Closed** 2017-05-23 08:40 UTC
