### ISSUE TITLE
dateTimeLabelFormats ignored in Highstock's tooltip

### ISSUE THREAD

**Issue by mungerj** [highcharts/highcharts#13432] opened 2020-05-05 02:26 UTC
#### Expected behaviour
Tooltip header should respect the dateTimeLabelFormats options

#### Actual behaviour
The tooltip header reverts to the default value and cannot be set.

#### Live demo with steps to reproduce
http://jsfiddle.net/jmunger/8137wrbs/6/

#### Product version
Highstock 8.0.4

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment] 2020-05-05 07:55
Hi @mungerj,
Thank you for reporting about the problem. The tooltip header uses the `xDateFormat` for dates:

>The format for the date in the tooltip header if the X axis is a datetime axis. The default is a best guess based on the smallest distance between points in the chart.

Example of edit:
- http://jsfiddle.net/BlackLabel/hd6v7c5o/

Docs:
- https://api.highcharts.com/highstock/tooltip.xDateFormat

The `tooltip.dateTimeLabelFormats` is used for formatting points.

Im closing the ticket as not a bug.

**Closed by sebastianbochan** 2020-05-05 07:55 UTC

**Comment by mungerj** [comment] 2020-05-05 11:09
Thanks Sebastian. How can I translate the "Week from" string then, in this
situation?

**Comment by mungerj** [comment] 2020-05-05 11:42
OK, I found out how. Since I am using datagrouping the dateTimeLabelFormats must be set at this level. I don't think it's in the documentation though.

Exemple: http://jsfiddle.net/jmunger/8137wrbs/7/

**Comment by pawelfus** [comment] 2020-05-05 11:53
>  I don't think it's in the documentation though.

It is :) See: https://api.highcharts.com/highstock/series.line.dataGrouping.dateTimeLabelFormats
