### ISSUE TITLE
Series click event not fired

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#4353] opened 2015-07-03 13:40 UTC
Example: http://jsfiddle.net/0yxy6pwb/2/

Try to click on the line, nothing happens. Only when clicking on the edges (points) of the lines.

Used to work with previous logic for tooltip: http://jsfiddle.net/0yxy6pwb/3/ (however, not always).

**Comment by Elarcis** [comment] 2015-07-03 17:19
I think the issue is that the click event on a line is only handled if the current selected point is belonging to the same serie.

Haven't looked much into the code, but a more logical behavior would be to just get the clicked line and THEN retrieve the nearest point on it, instead of getting the hoverred point then check if the clicked line is the right one?

**Comment by mikedaly** [comment] 2015-08-07 18:37
I am experiencing this as well. The click logic doesn't seem to be right.

**Comment by highslide-software** [comment] 2015-08-11 12:10
_Internal note_

It seems that since the scatter points are more dense than the line points, the `chart.hoverPoint` is set to a scatter point on mouse over, then undefined on mouse out. And on mouse over the line, it is not updated.

**Comment by pawelfus** [comment] 2016-07-04 14:29
**Workaround:**

Set `tooltip.shared` to true, demo (4.2.5): http://jsfiddle.net/0yxy6pwb/4/

**Comment by jon-a-nygaard** [comment] 2017-08-03 13:24
Closing this issue as it seems to have been fixed, and working since at least v5.0.0.

**Closed by jon-a-nygaard** 2017-08-03 13:24 UTC
Labels: Bug
