### ISSUE TITLE
Axis breaks can cause axis labels to be hidden

### ISSUE THREAD

**Issue by moses-seeq** [highcharts/highcharts#6870] opened 2017-06-19 14:22 UTC
Although I expected axis labels to display regardless of the presence of axis breaks, when the breaks span the time that is automatically calculated for the axis ticks, no axis labels are displayed.  This can be seen in the following fiddle: http://jsfiddle.net/moses_seeq/k75j6a3f/.  This is a contrived example to display the issue, but it is expected that when tick marks are dynamically selected that ticks outside of the breaks would be selected and displayed.

**Comment by KacperMadej** [comment] 2017-06-20 11:12
Thank you for reporting about the problem. 

You could prevent hiding ticks from breaks, but all ticks from a break will be placed in the same place. Demo: http://jsfiddle.net/a0jtz7nf/

**Comment by moses-seeq** [comment] 2017-06-20 14:37
Interesting, but I don't think that is an acceptable solution for me at this point.  Please let me know if a better solution is found.

**Comment by KacperMadej** [comment] 2017-06-20 14:54
@moses-seeq Please describe what is the expected solution. If there's a break from 4 to 6 then there's no 5 on axis and where should the tick be placed? How about break from 4 to 60 - where should be placed all ticks that are in the break?

**Comment by meibegger** [comment] 2019-03-19 15:42
I also had this problem with ticks not being displayed within breaks. I use breaks to eliminate non-work-days (sat & sun), and for instance if i show a chart for 1 year, all ticks for the months which start in a break are gone.

Although the above solution does work, it leads to the strange behavior, that the tick is moved to before the break (so the tick shows month X and the value is from the previous month). Also for other intervals the moved tick can lie exactly on a previous tick, so the labels are shown above each other).

I now want to use the xAxis.tickPositioner function to move the ticks to the next workday (if the current day is in a break).
```
tickPositioner: function(this: Highcharts.Axis) {
  const tickPositions = this.tickPositions
  for (let i = 0; i < tickPositions.length; i++) {
    tickPositions[i] = nearestNextWorkdayTimestamp(tickPositions[i])
  }
  return tickPositions
},
```
This will need some refinement to prevent overlaps, but in general it works.

I only have problems with the types. `tickPositioner` has the type `Highcharts.AxisTickPositionerCallbackFunction` (https://api.highcharts.com/highcharts/xAxis.tickPositioner) and `this` should be of type `Highcharts.Axis` (https://api.highcharts.com/class-reference/Highcharts#.AxisTickPositionerCallbackFunction).

But i get the error
```
TS2339: Property 'tickPositions' does not exist on type 'Axis'.
```

Any ideas?

**Comment by pawelfus** [comment] 2019-03-19 16:43
Thanks for reporting @meibegger 

This is caused by missing `Axis.tickPositions` definition in our TS: https://api.highcharts.com/class-reference/Highcharts.Axis

@bre1470 - could you take a look?

**Comment by bre1470** [comment] 2019-03-19 16:54
It looks inconsistent in the API documentation as well. We have...
- getLinearTickPositions(tickInterval, min, max)
- getMinorTickPositions()
- renderMinorTick(pos)
- renderTick(pos, i)
- setTickPositions()

@TorsteinHonsi , should `Axis#tickPositions` be public? Is the format only `Array<number>`? Can it be `undefined`?
https://github.com/highcharts/highcharts/blob/hc71/master/js/parts/Axis.js#L4683

**Comment by meibegger** [comment] 2019-03-19 17:04
hi @pawelfus @bre1470 - it might be "related" ...

Before using the `tickPositioner` i tried to adapt the above demo  http://jsfiddle.net/a0jtz7nf/

When doing 
```
 Highcharts.wrap(Highcharts.Axis.prototype, 'setTickPositions', function(this: Highcharts.Axis, proceed?) {
  const temp = this.options.breaks
  ...
```
i got
```
TS2339: Property 'options' does not exist on type 'Axis'
```
Not sure, what type `this` should be though ... all sorts of props (options, ticks, tickPositions, ...) don't exist on Axis, but i couldn't find a proper type for `this`

**Comment by bre1470** [comment] 2019-03-19 17:13
@meibegger 
You probably get to it via `this.chart.options`. The `ticks` and `tickPositions` are not there yet (you have to call the wrapped function first). But we do not support wrap for TypeScript anyway and in general do not recommend to use `wrap` anymore.

Instead you should listen to `afterSetTickPositions` event like this:
```
Highcharts.addEvent(Highcharts.Axis, 'afterSetTickPositions', function () {
    console.log(Object.keys(this)); // Axis
});
```

**Comment by bre1470** [comment] 2019-03-20 16:16
We will make `Highcharts.Axis#tickPositions` public readonly as `Array<string>|undefined`.

**Comment by TorsteinHonsi** [comment] 2019-03-21 10:32
You mean `Array<number>|undefined` right?

**Comment by bre1470** [comment] 2019-03-21 10:34
Yes. Sorry for the confusion.

**Comment by bre1470** [comment] 2019-03-29 16:31
Merged in the master for next update release.

**Closed by bre1470** 2019-03-29 16:31 UTC
Labels: Product: Docs, Product: TypeScript

**Comment by raf18seb** [comment] 2020-03-05 10:22
What about setTickPositions()? Shouldn't it be private?
https://api.highcharts.com/class-reference/Highcharts.Axis#setTickPositions
