### ISSUE TITLE
Gantt with yAxis max and scroll, sometimes doesn't render yAxis lines that separate the labels

### ISSUE THREAD

**Issue by dragoshzava** [highcharts/highcharts#16641] opened 2021-11-12 11:12 UTC
#### Expected behaviour
![image](https://user-images.githubusercontent.com/3819194/141457809-261b86d2-e6c8-4e87-af24-f7dca3523e98.png)

#### Actual behaviour
![image](https://user-images.githubusercontent.com/3819194/141458165-7c2a699c-8e11-44fe-90b4-403c67dcf268.png)

#### Explanation
It depends on how fast you scroll, if you scroll slowly it does not work.
If you scroll fast, it works.

#### Attached Repro Video
https://user-images.githubusercontent.com/3819194/141458072-1a89a6f1-cd32-49dc-b0e6-d9a8abcbb73f.mp4

#### Live demo with steps to reproduce
https://jsfiddle.net/Resems/rfa4k35s/1/

#### Product version
9.3.0

#### Affected browser(s)
N/A

**Comment by KacperMadej** [comment] 2021-11-12 19:47
Hi @dragoshzava 

Thank you for reporting.
Duplicate of https://github.com/highcharts/highcharts/issues/13898

**Closed by KacperMadej** 2021-11-12 19:47 UTC
