### ISSUE TITLE
useHtml in title - shifts position

### ISSUE THREAD

**Issue by klodoma** [highcharts/highcharts#7855] opened 2018-02-13 10:10 UTC
The version 6.0.6 has a bug. If one uses `"useHTML": true` in the title, the title gets shifted down. See examples. This works well in 6.0.4.

#### Expected behaviour
The title is in the same position. 

#### Actual behaviour
The title is shifted down, when `useHTML: true`

#### Live demo with steps to reproduce
http://jsfiddle.net/klodoma/u8xx0vuj/

#### Product version
Highcharts 6.0.6

#### Affected browser(s)

![screenshot_57](https://user-images.githubusercontent.com/944350/36144476-6bada386-10ae-11e8-85d4-f717f361863d.png)

**Comment by KacperMadej** [comment] 2018-02-13 11:41
Hi @klodoma 

Thank you for reporting about the problem.

_Internal note:_
The difference is in setting y and how it's calculated for HTML and non-HTML title.
Demo: http://jsfiddle.net/u8xx0vuj/2/

**Comment by TorsteinHonsi** [comment] 2018-02-13 11:43
Duplicate of #7787 .

**Closed by TorsteinHonsi** 2018-02-13 11:43 UTC
Labels: Bug
