### ISSUE TITLE
xAxis labels have wrong position after opening drilldown and returning back

### ISSUE THREAD

**Issue by KatyaGunko** [highcharts/highcharts#5535] opened 2016-07-26 10:52 UTC
#### Expected behaviour
after opening drilldown for FIRST column in bar chart and returning back the alignment of xAxis labels remain the same for the main chart

#### Actual behaviour
after opening drilldown for FIRST column in bar chart and returning back the alignment of xAxis labels brakes down

**Before opening drilldown**
![2016-07-26_1349](https://cloud.githubusercontent.com/assets/8654417/17135331/f69aa3da-5337-11e6-9a7c-370e6e99072c.png)

**After opening drilldown and closing it**
![2016-07-26_1350](https://cloud.githubusercontent.com/assets/8654417/17135347/06a11232-5338-11e6-868a-c8fa93b24cbd.png)

Thanks!

**Comment by TorsteinHonsi** [comment] 2016-07-27 07:08
Can you show us a live demo of this? It doesn't happen in our [column drilldown demo](http://jsfiddle.net/gh/get/jquery/1.7.2/highcharts/highcharts/tree/master/samples/highcharts/demo/column-drilldown/).

**Comment by jon-a-nygaard** [comment] 2016-08-18 07:34
Closing this issue since we are unable to reproduce, and it is pending a reply. Should anyone have further information about this issue, please give us a comment.

**Closed by jon-a-nygaard** 2016-08-18 07:34 UTC
Labels: Cant reproduce, Pending reply
