### ISSUE TITLE
Settings from `<...>.states.hover.animation.duration` do not apply chart animations

### ISSUE THREAD

**Issue by Radullus** [highcharts/highcharts#18187] opened 2022-12-21 11:26 UTC
#### Expected behaviour

1. Animation duration is changing according to the settings.

OR

2. Remove mention about it in the documentation pags:
   - https://api.highcharts.com/highcharts/plotOptions.series.states.hover.animation.duration
   - https://api.highcharts.com/highcharts/series.column.states.hover.animation
   - posibly some more ...

#### Actual behaviour
The animation duration is default 50ms.

#### Live demo with steps to reproduce
[Simple example for column chart](http://jsfiddle.net/Radullus/0wot6yL9/2/)

#### Product version
 Highcharts JS v10.3.2 (2022-11-28)

#### Affected browser(s)
Chrome v.108.0.5359.125 
Microsoft Edge v.108.0.1462.54
Firefox 108.0.1
Opera 93.0.4585.37

**Comment by pawellysy** [comment] 2022-12-21 12:31
Thanks @Radullus for reporting the bug!
Indeed there are some problems with animation duration.
However, in the API there is a statement that `Animation setting for hovering the graph in line-type series.`
So maybe there is some problem with columnSeries API. Needs further invastigation.

Some other demos where the error is reproduced: 
https://jsfiddle.net/BlackLabel/5q4L7h6c/

**Comment by pawelfus** [comment] 2023-05-11 14:39
It works fine @Radullus @pawellysy 

Two things to mention here:
- [colors handling in Highcharts](https://www.highcharts.com/docs/chart-design-and-style/colors#solid-colors), demo with hex: http://jsfiddle.net/BlackLabel/j0wmgL3r/
- https://jsfiddle.net/BlackLabel/5q4L7h6c/ -> you just have to wait ~3s to see the difference

Closing as not a bug

**Closed by pawelfus** 2023-05-11 14:39 UTC
Labels: Type: Bug
