### ISSUE TITLE
Order of data changes the chart

### ISSUE THREAD

**Issue by aryanbhatt-clvt** [highcharts/highcharts#19790] opened 2023-09-20 07:28 UTC
#### Expected behaviour
![image](https://github.com/highcharts/highcharts/assets/114740120/7e4f05f4-77b8-483d-986d-eae7426f13a3)

#### Actual behaviour
![image](https://github.com/highcharts/highcharts/assets/114740120/1a8952d4-f94a-4689-8504-11b2c6f54a8f)

#### Live demo with steps to reproduce

https://jsfiddle.net/x7p40e1r/16/

#### Affected browser(s)

The difference in both the images above comes if the data variable doesn't have the data in a certain order. That was manually generated, however I want to see the same graph.
Just to be clear, if we change the order of objects in the data variable the appearance of the chart changes. How to avoid that?

**Comment by bm64** [comment] 2023-09-21 23:55
Hello @aryanbhatt-clvt 

The behavior you're observing is currently by design. The nodes' order in the Sankey chart is determined by the order of the points' data objects.

To ensure that your chart looks the same every time, regardless of the data order, you can sort your data before passing it to the chart. Here's a demo example: https://jsfiddle.net/BlackLabel/dn0qfcuy/.

I'm closing this issue since there's an existing feature request to allow custom ordering in Sankey charts: https://github.com/highcharts/highcharts/issues/11527

**Closed by bm64** 2023-09-21 23:55 UTC
