### ISSUE TITLE
Tooltip disappears on Edge

### ISSUE THREAD

**Issue by EstelleDoreau** [highcharts/highcharts#9403] opened 2018-11-13 16:03 UTC
#### Expected behaviour
When hovering over the histogram, the tooltip appears and remains visible as long as you fly over the element

#### Actual behaviour
By hovering over the histogram, the tooltip appears and then disappears, on Edge.
I encounter this problem in 90% of cases.  

#### Live demo with steps to reproduce
http://jsfiddle.net/104ufw89/

#### Product version

version of Highcharts : latest stable version or 6.1.1
version of Edge : Microsoft EdgeHTML 17.17134
version of Windows : Windows  10 Entreprise 17134.345

#### Affected browser(s)
Microsoft Edge

**Comment by EstelleDoreau** [comment] 2018-11-15 10:55
Hello @KacperMadej  

I was able to contact support before opening my ticket. 
@kamilkulig also has the problem, which he reproduces. 

I don't have any errors in the console, not even a warning.
I do not have any unusual settings enabled on my browser or operating system.

I have a video of the problem, I can send it to you if you give me your email address.

thank you

**Comment by KacperMadej** [comment] 2018-11-16 16:58
@EstelleDoreau 
Kamil informed me about the case.

Another demo: http://jsfiddle.net/BlackLabel/d1wLfjy7/1/
Steps:
0. use Edge browser
1. hover over black column
2. move to blue column (fast single mouse motion)
3. if tooltip is not hiding after a moment go back to step 1
4. do the same with open console to see that code will be stopped by debugger on mouseover and without any mouse movement followed by mouseout

I do not understand what is the source of the mouseout event - this might be a browser or OS bug.

**Comment by EstelleDoreau** [comment] 2018-11-22 16:29
Bonjour @KacperMadej,


je vois bien le problème.

J'ai plus l'impression qu'il ne détecte pas le mouseOver plutôt qu'il effectue un mouseOut. 

Je ne comprend pas non plus...

Thanks

**Comment by jamesalmond** [comment] 2019-09-18 10:37
@KacperMadej any update on this? 30% of the time I don't get tooltips on the latest version of Edge with the above JSFiddles. The mouseover doesn't appear to fire.

The issue is intermittent and if you click around a bit on the chart, or resize/move your window etc then the tooltips do eventually appear. Perhaps after a redraw?

Is there anything I can do to help you diagnose this?

**Comment by KacperMadej** [comment] 2019-09-18 13:53
It looks like HTML tooltip might be animated under the cursor when hovering over the chart, and cause unwanted events. This shouldn't be happening as `pointer-events: none;` in CSS is set for the tooltip. If you are able to check why this happens only in Edge then it could be decided if the problem is visible only in Edge or is an Edge browser bug.

**Comment by SriramSubramaniam** [comment] 2020-01-02 21:33
This issue only happens in MS Edge. It works on other browsers like Chrome, safari and firefox

**Comment by KacperMadej** [comment] 2020-01-22 16:33
Looks like the new Edge based on Chromium is free of this problem.
Closing for now, but if you are able to recreate the problem please leave a comment and the issue could be reopened.

**Closed by KacperMadej** 2020-01-22 16:33 UTC
Labels: Type: Undecided
