### ISSUE TITLE
Responsive rule does not update chart.events

### ISSUE THREAD

**Issue by stpoa** [highcharts/highcharts#6285] opened 2017-01-23 15:29 UTC
#### Expected behaviour
After resizing chart to 300px and then clicking on chart it should fire a click event.

#### Actual behaviour
After resizing chart to 300px and then clicking on chart it does not fire a click event.
_Note: updating events for plotOptions.series.events works_

#### Live demo with steps to reproduce
https://jsfiddle.net/x3cy73j4/

1. Click `300px` button
2. Notice, that there is no alert on render
3. Click on chart
4. Notice, the click event doesn't work

**Comment by KacperMadej** [comment] 2018-09-13 09:46
Responsive rules are using chart.update, so the problem is a duplicate of 6538
(marking this as a duplicate, because the other issue has more info)

**Closed by KacperMadej** 2018-09-13 09:46 UTC
