### ISSUE TITLE
meteogram displays all icons

### ISSUE THREAD

**Issue by meteoDaniel** [highcharts/highcharts#6578] opened 2017-04-07 17:23 UTC
#### Expected behaviour
meteogram shows one icon per hour in the chart

#### Actual behaviour
on the right side are all icons in the chart

#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/combo-meteogram/

#### Affected browser(s)
chrome and firefox

**Comment by pawelfus** [comment] 2017-04-10 08:42
Hi @meteoDaniel 

Thanks for reporting this issue! We have already fixed this on our master branch, please take a look: #6550

Closing as duplicate of #6550

**Closed by pawelfus** 2017-04-10 08:42 UTC
