### ISSUE TITLE
node_modules/highcharts/highcharts.d.ts is too large

### ISSUE THREAD

**Issue by dartess** [highcharts/highcharts#20136] opened 2023-11-15 08:50 UTC
#### Expected behaviour

WebStorm can open highcharts.d.ts not in read-only mode.

#### Actual behaviour

WebStorm can open highcharts.d.ts only in read-only mode. This makes navigating the file difficult. Perhaps the file can be split into several?

<img width="714" alt="image" src="https://github.com/highcharts/highcharts/assets/15047511/8315d90d-ae4f-4d3f-94cc-a979677f77cb">

#### Product version

highcharts@11.2.0

**Comment by karolkolodziej** [comment] 2023-11-15 09:12
Hi @dartess! 

Thank you for reporting the issue! It might be somewhat related to the issue: https://github.com/highcharts/highcharts/issues/20124

FYI @bre1470

**Comment by ravindUwU** [comment] 2024-02-19 06:36
VSCode also chokes on this file (which is is 22MB as of `11.1.0`) and disables editor features by default 😬.

![](https://github.com/highcharts/highcharts/assets/7352580/f103070a-16ee-45cb-b710-075c73a61bce)

**Comment by karolkolodziej** [comment] 2024-02-19 07:24
Hi @ravindUwU! Thank you for contacting us!

We are aware of this and we've started an investigation into what can be improved here- more information https://github.com/highcharts/highcharts/issues/18980

**Comment by TorsteinHonsi** [comment] 2024-03-21 06:53
Duplicate of #18980

**Closed by TorsteinHonsi** 2024-03-21 06:53 UTC
Labels: Product: Highcharts, Type: Undecided, Product: TypeScript
