### ISSUE TITLE
Tooltip is displayed over line series instead of bubble

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5476] opened 2016-07-11 13:17 UTC
#### Expected behaviour
Tooltip should be printed over the current point

#### Actual behaviour
When we hover over the mouse to Bubble points, It is forcing nearest line point to get focused and showing the tooltip. 

#### Live demo with steps to reproduce
http://jsfiddle.net/hy2cbgLo/

![tooltiptrackerbuggit](https://cloud.githubusercontent.com/assets/2115686/16731841/84ea736e-477a-11e6-963f-c8dc3f76844c.gif)

**Comment by pawelfus** [comment] 2016-07-12 14:18
**Workaround:**

Force `bubble` series to call events only on direct mouse event:

    Highcharts.seriesTypes.bubble.prototype.directTouch = true;

Demo: http://jsfiddle.net/a30tcyvb/

**Comment by TorsteinHonsi** [comment] 2016-08-15 08:51
This issue is related to #5533, so a solution there will probably fix it.

**Comment by pawelfus** [comment] 2016-08-16 08:20
Closing as duplicate of #5533.

**Closed by pawelfus** 2016-08-16 08:20 UTC
Labels: Bug
