### ISSUE TITLE
Overlapping data labels and legend labels in exporting chart in ppt or pdf

### ISSUE THREAD

**Issue by MangeshPimprikar** [highcharts/highcharts#7928] opened 2018-02-27 03:29 UTC
#### Expected behaviour
Labels should not overlap on each other

#### Actual behaviour
data labels and legend labels overlap in exporting chart in ppt or pdf

**Comment by MangeshPimprikar** [comment] 2018-02-27 03:30
Overlapping data labels and legend labels in exporting chart in ppt or pdf

**Comment by sebastianbochan** [comment] 2018-02-27 10:09
Hi @MangeshPimprikar 
The default exporting module does not allow to export to ppt. Could you elaborate what kind of converting module, do you use?

**Comment by oysteinmoseng** [comment] 2018-05-29 13:30
Closing as unable to reproduce with PDF, and PPT is not supported.

**Closed by oysteinmoseng** 2018-05-29 13:30 UTC
Labels: Pending reply
