### ISSUE TITLE
Native Mobile support - action/click callback for row titles 

### ISSUE THREAD

**Issue by lahirupintospt** [highcharts/highcharts#19949] opened 2023-10-17 09:26 UTC
# Description of the feature
Provide action/click support for row titles (make items clickable), action should be able to identify which item was clicked

# Library related to the feature
Highcharts Core -> X-Range

**You can vote for this feature by adding a thumbs-up reaction to this post.**

**Comment by karolkolodziej** [comment] 2023-10-19 10:51
Closing as a duplicate of: https://github.com/highcharts/highcharts/issues/13745

**Closed by karolkolodziej** 2023-10-19 10:51 UTC
Labels: Type: Feature Request
