### ISSUE TITLE
Heat Map does not allow custom color

### ISSUE THREAD

**Issue by pmfiebig** [highcharts/highcharts#13441] opened 2020-05-05 17:17 UTC
#### Expected behavior
In the past the heat map would allow a custom color to be passed in the series data.

#### Actual behaviour
Now all the custom color values are displayed as white

**Comment by sebastianbochan** [comment] 2020-05-06 08:08
Hi @pmfiebig,
Thank you for reporting. When I run a simple demo, I am not able to reproduce the problem. 

Demo:
- https://jsfiddle.net/BlackLabel/5y8kba2n/

Could you update my example with your simplified code ?

**Comment by pmfiebig** [comment] 2020-05-06 16:43
Hi Sebastian

Thanks for your help. I found the issue was when I had markers disabled on
plotOptions.

*"marker": {"enabled": false}*

This was certainly working earlier in the week.
Thanks

**Comment by sebastianbochan** [comment] 2020-05-07 08:01
Hi @pmfiebig,
Thank you for the feedback. Currently the heatmap allows you to set the custom marker of series. When you disable it, marker is not draw.

Should we consider the issue as a bug? @Denyllon

**Comment by pawelfus** [comment] 2020-05-07 08:10
Unrelated to the decision if this is a bug or not, we have two more issues:
- change is not listed in changelog: https://www.highcharts.com/blog/changelog/ (related PR: #12508)
- API docs don't state that feature is available since v8.1.0: https://api.highcharts.com/highcharts/plotOptions.heatmap.marker

Regarding `markers.enabled` option - I'm not sure if that makes sense to disable markers in a series that markers are crucial. It would be inconsistent with other series with markers though.

**Comment by pmfiebig** [comment] 2020-05-07 15:22
That makes sense. I'm not sure its a bug. It was just a change that took a
while to figure out.
The updated docs will certainly help.

Thank you :)

**Comment by Denyllon** [comment] 2020-05-08 08:26
Aside from the thing that @pawelfus mentioned above, I think that is not bug at all, because I really do not see any reason of why those markers might be disabled.
Furthermore, considering a `scatter` series, the `marker.enabled` option is also available in API, and setting it to `false` gives the same effect as described in this issue, so changing the way of how it works in heatmap might cause unnecessary confusion, and will be inconsistent.

Scatter example: https://jsfiddle.net/BlackLabel/7m698co3/1/

**Comment by Denyllon** [comment] 2020-05-08 09:09
Re-opened until the information about version will be added into the docs.

**Comment by Denyllon** [comment] 2020-05-15 07:46
Changelog information added in https://github.com/highcharts/highcharts/pull/13522

**Closed** 2020-05-15 11:53 UTC
Labels: Product: Docs, Type: Undecided
