### ISSUE TITLE
y Axis scale is messed up on zoom

### ISSUE THREAD

**Issue by suganya-suvadi** [highcharts/highcharts#6807] opened 2017-06-06 17:26 UTC
When there are few data points, on zooming along x axis, yAxis' scale reduces to display only a single tick, with the label of the only tick losing all formatting ("250M" expands to "249536636"). Subsequent zooming results in the plot area becoming entirely blank with a tooltip occasionally floating around without border or background.

This starts only from 5.0.10.

In the fiddles shared below, zoom along x-axis to see the issue. (The issue is quite prominent when zoomed to display one data point)

Using 5.0.10 - http://jsfiddle.net/uw1f3vx8/3/ 

For the sake of comparison, adding another fiddle using 5.0.9 , which does not have the issue - http://jsfiddle.net/s669eyr3/10/

**Comment by Izothep** [comment] 2017-06-07 14:08
Hi @suganya-suvadi!

Thank you for reporting your issue. 

I have prepared basic workaround for your issue, I hope it will help you with your problem until we find the proper fix.

Demo with a workaround:
http://jsfiddle.net/uw1f3vx8/6/

**Comment by suganya-suvadi** [comment] 2017-06-08 11:36
@Izothep thanks for the quick fix! I have overriden yAxis.getExtremes as suggested for now. Hope we get a fix in src in the next version!

**Comment by TorsteinHonsi** [comment] 2017-06-13 07:17
@Izothep Can you commit a fix too?

**Comment by Izothep** [comment] 2017-06-28 13:59
After some deeper research it looks that the issue is related to this GitHub topic:
https://github.com/highcharts/highcharts/issues/5956

I think that commit with a fix from above topic will solve formatting issue. 
http://jsfiddle.net/uw1f3vx8/10/

**Comment by KacperMadej** [comment] 2018-10-05 15:49
Unable to recreate using version 6.1.4
http://jsfiddle.net/BlackLabel/uw1f3vx8/20/

Closing as resolved

**Closed by KacperMadej** 2018-10-05 15:49 UTC
Labels: Bug, Regression
