### ISSUE TITLE
Boost module load error

### ISSUE THREAD

**Issue by AliceOJJm** [highcharts/highcharts#6376] opened 2017-02-15 10:57 UTC
Including highcharts/modules/boost after highstock (version 5.0.7, downloaded from website)

Uncaught TypeError: Cannot read property 'length' of undefined
    at m.hasExtremes (http://localhost:3000/assets/highcharts/modules/boost.self-edd05032a5fb53c0aab435d6a539c4348ebe55b4bf3f852c08d3d6d0ae4f1d62.js?body=1:14:66)

**Comment by pawelfus** [comment] 2017-02-15 11:26
Hi @AliceOJJm 

Could you recreate the issue in jsFiddle? Simple demo works fine, please take a look: http://jsfiddle.net/3txmmg1j/

Thanks!
Paweł

**Comment by AliceOJJm** [comment] 2017-02-20 08:38
The case was thah i did not set series data in options, had do add data: [] everywhere

**Comment by pawelfus** [comment] 2017-02-20 09:18
Thanks for the update! Demo: http://jsfiddle.net/3txmmg1j/1/

It's a duplicate of #5845

**Closed by pawelfus** 2017-02-20 09:18 UTC
Labels: Cant reproduce
