### ISSUE TITLE
Memory leak when leaving Chrome tab open at background

### ISSUE THREAD

**Issue by lightsam** [highcharts/highcharts#9749] opened 2018-12-22 00:43 UTC
#### Expected behaviour
Memory usage should remain constant whether the browser tab is active or not.
#### Actual behaviour
Memory usage slowly increases, but only when the browser tab is not active. 
#### Live demo with steps to reproduce

I observed the issue when I was working on a project using highcharts. Then I think that may be a bug of highcharts.

To reproduce the issue, follow the following steps:
1. Open the following demo link in a Chrome tab. I'm using Chrome 71.0.3578.98 on macOS High Sierra Version 10.13.6.
https://www.highcharts.com/stock/demo/dynamic-update

2. Open a new tab or switch to another tab.

3. Opened Chrome Task Manager to look at the memory footprint of the tab opened in step 1.

4. The memory usage of the tab keeps increasing. It may drop one or two MB at times but will increase even higher after a short drop. The memory usage increases over 40 MB in a period of 15 minutes.

5. After 15 minutes or more time, the memory usage should have increased a lot. Switch back to the tab and watch the memory usage of the tab. The usage drops significantly and finally arrives to the value of when the tab was first opened. Meanwhile, if I look at the graph in the demo, I can observe that the graph keeps appending points which should have been added during the period when the tab is inactive. The speed of appending points is faster than normal because there are a lot of missing points.  When the memory usage becomes normal, the speed of appending points resumes.

Note: 
1. The issue cannot be reproduced on my Firefox browser 64.0 (December 11, 2018) or Safari Version 11.1.2 (13605.3.8) on the same Mac.
2. https://github.com/highcharts/highcharts/issues/8750 seems the same but it got closed because of inactivity.

#### Product version

highcharts 6.1.1 and 7.0.0
#### Affected browser(s)
Chrome on Mac
I use Chrome 71.0.3578.98 on macOS High Sierra Version 10.13.6 but I first observed the issue a couple of months ago when the Chrome version was older.

**Comment by sebastianbochan** [comment] 2018-12-24 09:22
Hi @lightsam,
Thank you for reporting. It looks like duplicate of https://github.com/highcharts/highcharts/issues/9066. Could you confirm?

**Comment by lightsam** [comment] 2018-12-24 22:48
I don't think this is a duplicate of #9066. 
1. The live demos in #9066 add points without deleting old points. 
2. #9066 cannot be reproduced but this issue can.

**Comment by pawelfus** [comment] 2018-12-27 13:13
Hi @lightsam 

You are right, it looks exactly the same as #8750

> So either it's a bug in our implementation or something is broken in Chrome..

Since it works in other browsers then we should report this. It will take same time to prepare a standalone demo to report in to Chromium devs.. Possible workaround is to replace `rAF` with `setTimeout`, something like this (not tested):

```javascript
win.requestAnimationFrame = function (step) {
    setTimeout(step, 13);
};
```

But I'm afraid it may cause, in other libraries, unexpected errors.

It's interesting, I couldn't find a bug report in bugs.chromium.org - only similar complains about the issue here: https://news.ycombinator.com/item?id=13471543 (that's the reason you see increased speed of appending points until you are "in the right time").

@TorsteinHonsi It might be a good idea to skip animations when tab is hidden/inactive or use `setTimeout()`. Something like the snippet below, what do you think?

```
useRAF = !window.document[pick(
  window.document.hidden,
  window.document.msHidden,
  window.document.webkitHidden,
  true
)];

...

var requestAnimationFrame = useRAF && win.requestAnimationFrame || function (step) { ... };
```

**Comment by pawelfus** [comment] 2019-01-03 14:52
Hi @lightsam 

Sorry for the radio silence! We were a little understaffed during the holidays. Tomorrow I will pick this up and we will see what we can do.

**Comment by lightsam** [comment] 2019-01-03 19:20
I think the following info may help debugging the issue.
The project I am working on see much slower memory increase in the environment below
highcharts 5.0.14 with Chrome version 71.0.3578.98 (Official Build) (64-bit) on Windows 10
highcharts 5.0.14 with Chrome Version 71.0.3578.98 (Official Build) (64-bit) on macOS High Sierra Version 10.13.6

**Comment by pawelfus** [comment] 2019-01-04 14:08
@lightsam - `requestAnimationFrame` was introduced in v6. If you still see memory increase in v5, then we can only report this to Chrome devs and wait.. I will start preparing a bug report. Thanks for the details!

**Comment by TorsteinHonsi** [comment] 2019-01-04 14:09
Disabling animations for hidden pages is a great idea, there's no need to run this performance-intensive logic when no one is looking. I think we should add a filter at a lower level, effectively disabling all animations in hidden pages.

I would like to add this snippet inside the `SVGElement.animate` function:

```js
        if (pick(doc.hidden, doc.msHidden, doc.webkitHidden, false)) {
            animOptions.duration = 0;
        }
```

My preliminary tests show that
* The memory build-up is smaller than it was
* The accordion effect is gone.

Can you verify that @lightsam? You can try it live at http://jsfiddle.net/highcharts/jv7fdc20/ .

**Comment by lightsam** [comment] 2019-01-07 22:56
I tried http://jsfiddle.net/highcharts/jv7fdc20/ on my Chrome on my Mac and didn't see memory build-up.

**Closed** 2019-01-09 10:52 UTC
Labels: Pending reply
