### ISSUE TITLE
afterSetExtremes's userMin and userMax arguments are wrong on datetime axis

### ISSUE THREAD

**Issue by adasilva-gran** [highcharts/highcharts#22020] opened 2024-10-16 14:44 UTC
Hello, we recently tried to upgrade from highcharts 10 (10.3.3) to the last version available (11.4.8), unfortunately or charts zoom no longer works. We're using the `afterSetExtremes` method to request our api with new extremes value, so that we can display more detailed data than by using the built-in zoom (For example going down to hourly columns instead of daily columns)

#### Expected behaviour
afterSetExtremes provides correct extremes

Here is an example:
In the following userMax should be around "Tue Oct 02 2024 01:00:00 GMT+0200 (Central European Summer Time)"
Instead it is: "Tue Oct 01 2024 05:39:28 GMT+0200 (Central European Summer Time)"

![image](https://github.com/user-attachments/assets/d8877705-b639-4c46-ab0f-a558291fd5f2)

![image](https://github.com/user-attachments/assets/7b27e863-d6d3-4304-9daf-bf37254afdfb)

#### Actual behaviour
afterSetExtremes provides incoherent extremes

#### Live demo with steps to reproduce
https://jsfiddle.net/adasilva_gran/20ap6nqd/6/
Zoom in the charts and compare the zoomed-in area to the values logged in console.

#### Product version
Highcharts 11.4.8, also tested with `https://github.highcharts.com/master/highcharts.js`.

#### Affected browser(s)
At least Firefox 131.0.3 and Chrome 129.0.6668.101

**Comment by pawellysy** [comment] 2024-10-18 17:31
Hello @adasilva-gran, thanks for reaching out to us!

I've investigated the issue you are having, and in my opinion it is not a bug, but rather implemented solution to prevent users from zooming in to much into the space, where are no points. This is set by API option [xAxis.minRange](https://api.highcharts.com/highcharts/xAxis.minRange) that overwrites this default behavior.

Check this demo: https://jsfiddle.net/BlackLabel/m8aeoxfw/

Let me know if that solves it. If not, feel free to reopen the issue. For now, I'm closing it as `not a bug`. 

Thanks for making our library better!

**Closed by pawellysy** 2024-10-18 17:31 UTC

**Comment by adasilva-gran** [comment] 2024-10-21 12:47
Hello and thank you for your answer, unfortunatly I think we are not talking about the same thing. My issue is not about zoom visual result but about the call of `afterSetExtremes` function. Within this function we have access to a zoom event with `userMin` and `userMax` being the zoomed period but these are wrong or incoherent with the selected range. You can look at the console logs in the jsfiddle linked above. `minRange` doesn't seems to change anything here.

Here is a Highcharts 10 demo for a comparison: https://jsfiddle.net/adasilva_gran/ucn6vmpz/2/. It doesn't seems perfect too but stll better than v11

**Comment by pawellysy** [comment] 2024-10-22 17:45
Hey @adasilva-gran, I've investigated the demo and have some followup questions:

Does the same issue appear for you, when you are using a line series? (https://jsfiddle.net/BlackLabel/0r6to7hL/)

Does the same issue exist when you change the `series.pointPlacement` option to `on`(https://jsfiddle.net/BlackLabel/e4ogjs07/)?

I still think this might be a design choice, rather than an actual bug, and there might be an option that will work for you fine :)

**Comment by adasilva-gran** [comment] 2024-10-23 08:44
Thank you for your time and investigation 🙏 . Indeed using a line series or `series.pointPlacement: on` seems to make it better but it is still difficult to select a 24 hours range. 

I tried using categories instead of a datetime axis but I got a similar result:
- Highlighting the first column gives me => min: 0, max: 0.03532008830022082
- Highlighting the second column gives me => min: 0.9735099337748345, max: 1.024282560706402
I tried to start the second selection where I started the first one so the first max should be equal to the second min but they are completely different and range difference (max - min) is ~= 0.3 when I expect it to be 1

Using both categories and `pointPlacement:on' seems to work as expected but then I have to manually set min and max to fix the first and last columns + convert zoom min and max to datetimes. Do you have a better idea ?
https://jsfiddle.net/adasilva_gran/4ethd78a/27/

**Comment by pawellysy** [comment] 2024-10-25 15:32
Unfortunately, I don't think there is much we can do - Axis extremes calculations sometimes seem to be a bit off, especially with this amount of corner cases. but Just to double check - does it work fine for you, when using another series type, e.g. line? (https://jsfiddle.net/BlackLabel/0r6to7hL/)

**Comment by adasilva-gran** [comment] 2024-10-28 11:03
Hello, thank you for your time. I finally refactored our zoom using `chart.events.selection` instead of `xAxis.events.afterSetExtremes`. It fits perfectly our needs and the zoomRange (xAxis[0].min and max) is perfectly accurate unlike the one provided by afterSetExtremes. 

I think it could be worth mentioning this event in the afterSetExtremes's doc.

I think it is the end for this ticket, thank you for everything
