### ISSUE TITLE
Navigator outlineWidth causes scrollbar to ignore mouse events

### ISSUE THREAD

**Issue by Cyriuz** [highcharts/highcharts#2403] opened 2013-10-25 15:13 UTC
As seen here: http://jsfiddle.net/xQe5q/2/ when setting the outlineWidth of the navigator, in this case to get a space between the masterchart and the scrollbar, the scrollbar does not accept mouse events. 

I dug a bit in the code and found that the outline width is not included in the mouse position check at line 18714:

if (chartY > top && chartY < top + height + scrollbarHeight) { // we're vertically inside the navigator

Also as you can see in the example the handles does not get positioned correctly either but i was able to fix that by overloading the drawHandles function. I added some options for setting the size of the handles as well that can be found here: http://jsfiddle.net/4nkn8/ these would be some nice additional settings to have for the handles.

**Comment by sebastianbochan** [comment] 2016-11-24 14:47
Duplicate of #5800

Use [margin](http://api.highcharts.com/highstock/navigator.margin) option

**Closed by sebastianbochan** 2016-11-24 14:47 UTC
Labels: Highstock
