### ISSUE TITLE
Multiple-point solidgauge is off-center when on 100%

### ISSUE THREAD

**Issue by nulle** [highcharts/highcharts#21492] opened 2024-07-09 10:33 UTC
#### Expected behaviour
Multiple solidgauge points having the same center point and are aligned.

#### Actual behaviour
Solidgauge point with 100% value (full circle) is offset from the center. The background panes work as expected.
<img width="562" alt="Screenshot 2024-07-09 at 12 30 30" src="https://github.com/highcharts/highcharts/assets/373340/2d0087fd-3677-4c8e-80fa-536491244d00">
Also, when resizing such chart (setSize), a certain "twitching" is noticeable. I'm assuming it's connected to the positioning bug above, so not creating a seperate ticket for that.

#### Live demo with steps to reproduce
https://jsfiddle.net/uLg8qjk6/
You can see the "full" circle offset on the page load already.
You can see the above-mentioned "twitching" when pressing "Resize" and "Reset" buttons.

#### Product version
Highcharts v11.4.6 (currently latest)

#### Affected browser(s)
latest Chrome, latest Firefox & latest Safari (all on Mac) have the same issue

**Comment by hubertkozik** [comment] 2024-07-10 06:27
Hi @nulle! The last working version is Highcharts v11.4.1: https://jsfiddle.net/BlackLabel/snj04u9f/

This topic is a duplicate of https://github.com/highcharts/highcharts/issues/21429.

You can use the plugin from IIFE from the demo below as a workaround.
**Workaround:** https://jsfiddle.net/BlackLabel/sLgry9nd/

Closing as duplicate.

**Closed by hubertkozik** 2024-07-10 06:27 UTC
Labels: Duplicate
