### ISSUE TITLE
Stacked area chart is not properly drawing if the series do not have the same x values

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#8022] opened 2018-03-15 11:44 UTC
#### Expected behaviour
The chart should look like in V4.0.4:
http://jsfiddle.net/BlackLabel/gxnjy9bt/

#### Actual behaviour
Instead of drawing line directly from [1483592186000, 7716] to [1521077904000, 7716], Series1 goes down and comes up in between the data points [1483592186000, 7716] and [1521077904000, 7716] even Series1 does not have points in between [1483592186000, 7716] and [1521077904000, 7716]. The same series data is working as expected in V4.0.4.

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/xLncey6m/

#### Product version
Highcharts v6.0.7

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment] 2018-03-16 09:28
Related with topic https://github.com/highcharts/highcharts/issues/1041

@TorsteinHonsi should we consider it as separate bug or duplicate?

**Comment by TorsteinHonsi** [comment] 2018-03-19 14:50
I'm not sure it's a bug. The stacking logic looks at all used X position. If a series doesn't contain an X value that one of the others has, it is treated as `null`.  See http://jsfiddle.net/highcharts/gxnjy9bt/5/.  In version 4.0.4, Series 2 was completely ignorant of Series 1: http://jsfiddle.net/highcharts/gxnjy9bt/7/ . 

I think what we're missing (and it has been suggested before), is an option to set connectNulls to stack on top of an interpolated value. For the example above, it would produce two straight lines, since the missing value for "Series 2" would be interpolated. Is that what you would expect?

**Comment by TorsteinHonsi** [comment] 2018-03-20 07:46
Duplicate of #5169

**Closed by TorsteinHonsi** 2018-03-20 07:46 UTC
