### ISSUE TITLE
Only the first chart.reflow() executed when there are multiple consecutive chart.reflow() calls

### ISSUE THREAD

**Issue by soetji** [highcharts/highcharts#20576] opened 2024-02-01 18:44 UTC
#### Expected behaviour
chart.reflow() always executed when there are multiple

#### Actual behaviour
Only the first one

#### Live demo with steps to reproduce
https://jsfiddle.net/soetji/m8zadxev/

Click on the chart. It should fill up the chart-container which grows in size.

#### Product version
Latest as of today

#### Affected browser(s)
Chrome for sure. Maybe all.

**Comment by bm64** [comment] 2024-02-02 09:16
Hello @soetji 

It doesn't look like a Highcharts related issue. Most likely it behaves like that because browsers batch DOM updates and JavaScript execution for performance reasons. This causes multiple chart.reflow() calls within a single event listener to be effectively coalesced into a single update. To achieve the behaviour you're looking for you can try to wrap chart.reflow() with setTimeout which forces the browser to treat each operation as a separate task https://jsfiddle.net/BlackLabel/4Lgyswa9/

**Comment by soetji** [comment] 2024-02-02 18:11
@bm64 Thank you for your response. I don't think that it is a browser issue. Here's an example not using highcharts. Note that the third reflow() executes successfully.

https://jsfiddle.net/soetji/cowjxykv/

The one using highcharts below has only the 1st reflow() executes successfully.

https://jsfiddle.net/soetji/m8zadxev/

Let me know if I have missed anything.

**Comment by bm64** [comment] 2024-02-07 13:57
Hello @soetji 

I took a second look at the issue and you're right, the problem is on our side, sorry! It looks like it used to resize correctly in v11.1.0:  https://jsfiddle.net/BlackLabel/eay42z3k/
The issue is caused by `isResizing` property which was introduced in v11.2.0 and prevents in this case from reflowing the chart.
Here is a workaround with an overwritten reflow function:  https://jsfiddle.net/BlackLabel/w6kq03uo/

_Internal note_
Bisected to: https://github.com/highcharts/highcharts/commit/64610dec017bc8fec0021b1150c9625a8568a6ec

**Comment by hubertkozik** [comment] 2024-04-11 11:37
This issue is fixed in Highcharts v11.4.1 in 05db5e0e024520445281723df2a2b98e8258fb67. Closing as completed.

**Closed by hubertkozik** 2024-04-11 11:37 UTC
Labels: Product: Highcharts, Type: Regression, Status: Has workaround
