### ISSUE TITLE
Issue with last point in series.userOptions.data being an object (Series.update throws)

### ISSUE THREAD

**Issue by jonkafton** [highcharts/highcharts#4336] opened 2015-06-27 17:59 UTC
Having an issue that the last data item in series.userOptions.data is an object (with xohlc properties) rather than an array [x,o,h,l,c]. Stack trace below.

All data points are provided as arrays. Error is triggered by attempt to update series type to 'ohlc' (from 'candlestick')

At data is correct when series initialises (checked line 13229). Last item seems to get modified during render.

Can circumvent by doing following, but not ideal:

    var lastPoint = series.userOptions.data[series.userOptions.data.length - 1];
    if (lastPoint && lastPoint.x) {
        series.userOptions.data[series.userOptions.data.length - 1] = [lastPoint.x, lastPoint.open, lastPoint.high, lastPoint.low, lastPoint.close];
    }

Version 2.1.7:
Uncaught TypeError: pt.slice is not a functionSeries.setData @ highstock.src.js:13397
Series.init @ highstock.src.js:13055
(anonymous function) @ highstock.src.js:18603
Highcharts.wrap.obj.(anonymous function) @ highstock.src.js:391
seriesProto.init @ highstock.src.js:23231
extendClass.init @ highstock.src.js:16096
extend.update @ highstock.src.js:15594

**Comment by pawelfus** [comment] 2015-06-29 10:45
Could you follow [reporting steps](https://github.com/highslide-software/highcharts.com#reporting-issues)? 

For me it works perfectly fine: http://jsfiddle.net/zf5cosha/

**Comment by jon-a-nygaard** [comment] 2016-08-02 14:39
Closing this since we are unable to reproduce, and it is pending a reply. Should anyone have further information on the issue, please give us a comment.

**Closed by jon-a-nygaard** 2016-08-02 14:39 UTC
Labels: Cant reproduce, Pending reply
