### ISSUE TITLE
Highcharts.Net wrapper has incorrect data type for YAxisTitle.Margin and XAxisTitle.Margin

### ISSUE THREAD

**Issue by schutze** [highcharts/highcharts#6872] opened 2017-06-19 15:43 UTC
#### Expected behaviour

Using Highcharts.NET wrapper (Highcharts.Web.Mvc.dll) Version 5.0.6360.17139.

The online documentation (http://api.highcharts.com/highcharts/yAxis.title.margin) describes that the margin option is a number so the Highsoft.Web.Mvc.Charts.YAxisTitle.Margin property should be Double rather than String().  
http://dotnet.highcharts.com/Help/Highcharts/html/class_highsoft_1_1_web_1_1_mvc_1_1_charts_1_1_y_axis_title.html#a825747401f845bbae23e1072912d5d6e

The wrapper should also generate JSON that sets the margin to a number but it outputs a string.

JSON should be:
yAxis: { title: { margin: 60 } },

The same issue exists for XAxisTitle.Margin.

#### Actual behaviour

JSON that is generated, which does not work:
"yAxis":[{"title":{"margin":["60"]} }],

The margin setting should be a number rather than a string.

#### Affected browser(s)
Browser does not matter.

**Comment by sebastianbochan** [comment] 2017-06-20 09:30
Thank you for the reporting.

**Comment by schutze** [comment] 2017-07-05 14:09
@sebastianbochan It has been 15 days since you responded.  Any updates on this issue?

**Comment by sebastianbochan** [comment] 2017-07-07 08:08
The issue is already fixed in the newest 5.0.6397.2889 version. If problem will come again, please reopen the ticket.

**Closed by sebastianbochan** 2017-07-07 08:08 UTC

**Comment by schutze** [comment] 2017-07-07 13:51
@sebastianbochan This has been corrected!
