### ISSUE TITLE
first value of compare chart should not be the last of the previous range

### ISSUE THREAD

**Issue by juicelink** [highcharts/highcharts#5748] opened 2016-09-29 16:24 UTC
first value of compare chart should not be the last of the previous range
=> the last value of the range should be included in the range when using zoom buttons (reflected in input fields)
=> when setting the input fields, first value of compare chart should be the same than the setted one in min input field 

My financial consumers that use compare charts are desoriented, saying me that:
- when they set a start date , the first value should be at this date and should be 0% (First date and date in min input field should always correspond and first value should be always 0%)
- YTD should be from last december date to today (ex: the filter should be set from 31 dec to now)
- Same thing for the other period zooms. All the periods should start one value before
- When zooming the input fields should be correctly filled with the first and the last date values, the first value should be at 0%

It seems that financial users are used to set the previous date of a period when they want to see that period performance
#1613
#687

**Comment by TorsteinHonsi** [comment] 2016-09-30 07:24
Indeed, when looking at for example [Google Finance](https://www.google.com/finance?q=usdeur&ei=lRLuV5GAGoTrsgGzp5vIDQ), setting YTD actually starts the chart from Dec 31.

> Same thing for the other period zooms. All the periods should start one value before

Does that mean that if you click 1M, you actually load 1 month plus one extra day before it?

@pawelfus FYI.

**Comment by MircoRa** [comment] 2016-09-30 09:37
Hi, 

The chart should start at 0% with the day before the selected period. If you want to show the 1 month performance for September 29, the chart should start at August 28 with 0% and end September 29.

Hope this helps.
Best, Mirco

**Comment by pawelfus** [comment] 2016-09-30 09:39
Hi @juicelink and @MircoRa - thank your for your feedback!

I think that YTD should have an additional param, to determine first day of the year (calendar year or fiscal year, where one can use 31st of December, 1st of January or 1st of April etc.). 

As for periods like 1M it actually makes sense for compare mode. I remember when we had reports that 1M should return 1st - 31st, 1st - 1st etc. Actually, if we will just add **callback** options to range selector buttons, then every user can define it's own period behaviour. 

Regarding this point:

> When zooming the input fields should be correctly filled with the first and the last date values, the first value should be at 0%

Again, I think it should be configurable. We can change this, but we will get another reports that it's wrong. After all it's the opposite of #687 ticket.

**Comment by KacperMadej** [comment] 2017-04-03 13:40
+1 for making this configurable

**Comment by juicelink** [comment] 2017-08-15 09:51
https://github.com/highcharts/highcharts/issues/1613#issuecomment-322425490

**Comment by pawelfus** [comment] 2017-09-18 15:32
Closing this ticket as duplicate of #1613, please follow #1613 ticket.

**Closed by pawelfus** 2017-09-18 15:32 UTC
Labels: Highstock, Undecided
