### ISSUE TITLE
heatmap colorAxis.max - the max value is NOT automatically calculated as must

### ISSUE THREAD

**Issue by Daizz** [highcharts/highcharts#6656] opened 2017-04-27 14:19 UTC
#### Expected behaviour
According API  http://api.highcharts.com/highmaps/colorAxis.max

```
max: Number
        The maximum value of the axis in terms of map point values.
        If null, the max value is automatically calculated.
        If the endOnTick option is true, the max value might be rounded up.
```

#### Actual behaviour
**All area** filled by max of color value
![image](https://cloud.githubusercontent.com/assets/449665/25487491/0ab8a110-2b6d-11e7-866c-d09a2991dd4e.png)
PS: as a solution - additional calculate and set this colorAxis.max value before draw

#### Live demo with steps to reproduce
https://jsfiddle.net/jx2zcaha/

works if uncomment row  ( `max :100,` )
#### Affected browser(s)
Win 7, Chrome 57.* / 58.0.3029.81 (64-bit)

**Comment by pawelfus** [comment] 2017-04-27 14:39
Thank you for the report!

Please, set `turboThreshold`, demo: https://jsfiddle.net/jx2zcaha/1/

Duplicate of #6152

**Closed by pawelfus** 2017-04-27 14:39 UTC
Labels: Duplicate
