### ISSUE TITLE
Highcharts mouse pointer event displacement with transform: matrix

### ISSUE THREAD

**Issue by Llorx** [highcharts/highcharts#8618] opened 2018-07-13 09:10 UTC
#### Expected behaviour
Mouse pointer hover correctly over the points

#### Actual behaviour
Mouse pointer is shifted by the matrix properties (scale, translate)

#### Live demo with steps to reproduce
http://jsfiddle.net/tnprxch5/2/
Mouse hover the points.

#### Product version
Higcharts, latest.

To overcome this, I think that you can do getBoundingClientRect (which take into account the transformations) on each point after redrawing them, caching the result and using the cache as the bounding box to detect the collisions.

The other way will be to traverse through all the parents processing the getComputedStyle transforms of each element, and internally apply the scaling/translation to the mouse events. The problem here is to process the skew or 3d transformations.

And finally another performant way can be to getBoundingClientRect one time (on each redraw) the chart container and compare it to the actual chart size. With this you get the scale applied. Simply apply that scale to each mouse event. This method also don't takes into account skew or 3d transformations, but can be a fast partial fix for this problem, at least to have scaling covered.

**Comment by pawelfus** [comment] 2018-07-16 10:07
Hi @Llorx 

Thanks for reporting the issue. It's duplicate of #2405 - you can also try workaround posted there. 

Closing as duplicate of #2405.

**Closed by pawelfus** 2018-07-16 10:07 UTC
Labels: Duplicate

**Comment by Llorx** [comment] 2018-07-16 10:38
Weird. I've searched for `transform` on issues and not found nothing. Maybe I had a typo :-/

Thank you. Going to check it.
