### ISSUE TITLE
Meteogram is not working properly

### ISSUE THREAD

**Issue by zainrafique** [highcharts/highcharts#6564] opened 2017-04-04 12:54 UTC
#### Expected behaviour
Only show the weather icon on the temperature line

#### Actual behaviour
There are so may weather icon.
check the following link.
http://www.highcharts.com/demo/combo-meteogram#https://www.yr.no/place/United_Kingdom/England/London/forecast_hour_by_hour.xml
![meteogram](https://cloud.githubusercontent.com/assets/26251809/24657470/cc351172-195f-11e7-944d-067f3336676d.png)

**Comment by KacperMadej** [comment] 2017-04-04 14:26
Thank you for reporting about the problem - we are working on it.

**Comment by KacperMadej** [comment] 2017-04-04 14:27
Duplicate of https://github.com/highcharts/highcharts/issues/6550

**Closed by KacperMadej** 2017-04-04 14:27 UTC

**Comment by zainrafique** [comment] 2017-04-05 11:06
when would you done with this?

**Comment by KacperMadej** [comment] 2017-04-05 11:30
@zainrafique It already fixed and awaits next release - please see #6550
