### ISSUE TITLE
Fractional GridLineWidth results in uneven looking grid lines

### ISSUE THREAD

**Issue by TheGreatYamcha** [highcharts/highcharts#10035] opened 2019-01-31 18:47 UTC
#### Expected behaviour
equal width grid lines. Or at least the option to specify thinner grid lines (thinner than 1px).
We used to use flot and it did an excellent job at drawing grid lines thinner than 1px. 

#### Actual behaviour
The grid lines are uneven in width, when fractional specified. This is especially the case on mobile devices, where resolution isn't high. Some grid lines don't even show up there. See demo.

#### Live demo with steps to reproduce
https://jsfiddle.net/g3hyd1jo/3/

#### Product version
Latest

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment] 2019-02-01 10:42
Hi @TheGreatYamcha,
Thank you for reporting.
It looks like the duplicate of https://github.com/highcharts/highcharts/issues/5420

**Comment by TorsteinHonsi** [comment] 2019-02-04 10:42
I can't see the problem in Chrome, but in Safari the grid lines come out different.

I propose to render all lines in the middle of their pixel if the grid line width is less than 1. Does this look good to you @TheGreatYamcha ? https://jsfiddle.net/highcharts/epj3tx0a/6/

If so, I will commit the change.

**Comment by TheGreatYamcha** [comment] 2019-02-04 20:05
@TorsteinHonsi 
Even your example looks wrong (in chrome). It depends on your screens resolution.

**Comment by TorsteinHonsi** [comment] 2019-02-06 12:34
> It depends on your screens resolution.

It shouldn't.

* Can you share a screenshot with us?
* Are you using page zoom in the browser?

**Comment by sebastianbochan** [comment] 2019-04-18 11:30
Closed due to inactivity. Please reopen when new details will be available.

**Closed by sebastianbochan** 2019-04-18 11:30 UTC
Labels: Status: Pending reply
