### ISSUE TITLE
Not all data displayed on histogram

### ISSUE THREAD

**Issue by deferenty** [highcharts/highcharts#8519] opened 2018-06-23 14:46 UTC
#### Expected behaviour
Total height of columns in histogram should be equal to length of data array.

#### Actual behaviour
It is often (but not always) total height of bars in histogram is less then array size. It is easy to notice such behavior if number of elements in data array is not very big.

#### Live demo with steps to reproduce
Here are two examples. This is copy of original highcharts demo, only data array is a bit shorter.

[https://jsfiddle.net/chesterfield/ja84g1q7/2/](https://jsfiddle.net/chesterfield/ja84g1q7/2/) - Here are 12 elements in data array and 12 points on the scatter chart. But there are three bars on histogram with height 1, 4 and 5 - totally 10. Bar that should display two occurrences (3.7 and 3.9) is not displayed for some reason

[https://jsfiddle.net/chesterfield/L7x1yamj/](https://jsfiddle.net/chesterfield/L7x1yamj/) - is copy of previous fiddle with deleted element with value 3.9. Now is missing bar that should display 3 occurances of value 3.4.

#### Product version

Highcharts JS v6.1.0 (2018-04-13)

#### Affected browser(s)
Google Chrome Version 67.0.3396.87 (Official Build) (64-bit)
Firefox Quantum 60.0.02 (64bit)

**Comment by sebastianbochan** [comment] 2018-06-25 08:40
Hi @deferenty,
Im not sure if it is a bug. According to our docs:
```
A histogram is a column series which represents the distribution of the data set in the base series. Histogram splits data into bins and shows their frequencies

A preferable number of bins. It is a suggestion, so a histogram may have
a different number of bins. By default it is set to the square root of the base series' data length. Available options are: `square-root`, `sturges`, `rice`. You can also define a function which takes a
`baseSeries` as a parameter and should return a positive integer.
```

@morganfree any commencts?

**Comment by deferenty** [comment] 2018-06-25 10:03
Thank you for your unswer, @sebastianbochan ,

Let's examine my second example: [https://jsfiddle.net/chesterfield/L7x1yamj/](https://jsfiddle.net/chesterfield/L7x1yamj/)

Integer value of quare root of 11 is 3. Ok

But width of bins should be calculated in such way, that all data values should take part in some bin. Because, now we have some randomly deleted bin.

As for me, width of one bin shoud be : **beansWidth** >= (**maxBinVal** - **minBinVal**) / **binsNumber**
 **maxBinVal** is value of the right border of the rightest bin (in my example = 3.73), should be not less, that maximum value in dataset.
**maxVal** value of the left border of the leftest bin (in my example = 2.67), should be not bigger that minimum value in dataset.

But it looks like bins width is calculated incorrectly, that leads to data missing. So, it looks rather like a bag, than like a fiture)

**Comment by morganfree** [comment] 2018-06-25 11:04
Thank you for reporting and the analysis. This is a bug where some frequencies are not correctly placed into bins, possibly because of float correction. This is a duplicate of the bug which has been already reported so I currently close the issue. You can track the progress in #8506.

**Closed by morganfree** 2018-06-25 11:04 UTC
Labels: Undecided
