### ISSUE TITLE
Zoom with boost problem on Firefox

### ISSUE THREAD

**Issue by wojciechtryba-td** [highcharts/highcharts#17249] opened 2022-05-05 10:41 UTC
#### Expected behaviour
When zooming line chart with boost mode enabled, it is expected to display current zoom view.

#### Actual behaviour
When zooming line chart with boost mode enabled, it fails to redraw view correctly. The view from before zoom is display along with the current zoom view.

#### Live demo with steps to reproduce
The bug is present in official Highcharts demo 'Line chart with 500k points'. To reproduce, zoom the chart multiple times.
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/line-boost

#### Product version
Highcharts v10.1.0 with Boost Module

#### Affected browser(s)
Firefox 100.0

**Comment by raf18seb** [comment] 2022-05-05 15:19
Closing as a duplicate of https://github.com/highcharts/highcharts/issues/17182

**Closed by raf18seb** 2022-05-05 15:19 UTC
