### ISSUE TITLE
Touch scroll on mobile devices slides data points out of frame

### ISSUE THREAD

**Issue by gruuschesdevelopmenthq** [highcharts/highcharts#18599] opened 2023-03-01 17:43 UTC
#### Expected behaviour
Set followTouchMove to false in tooltip and open chart on a mobile device (or simulate via developer tools in browser) lets the user scroll the chart left and right with touch gestures. The data points stay in the chart box frame.

#### Actual behaviour
The data points move out of the chart box frame. On big screens like tablets or hybrid notebooks with big chart frames the data points move really far outside of the chart box frame.

#### Live demo with steps to reproduce
https://jsfiddle.net/wn3h29b8/5/
Either open it with a touch device or activate developer options in your browser and simulate a touch device. In Firefox it's called "Responsive Design Mode" and then on the top in the middle you can enable or disable touch simulation.
Reload the page if touch is not working. Then scroll the datapoints left and right and see the chart is moving out of the frame left and right. Seems to be a z-index issue.

#### Product version
├── highcharts-react-official@3.1.0
├── highcharts@10.3.3

#### Affected browser(s)
Firefox
Chromium
Chrome
Waterfox
Duckduckgo

**Comment by bm64** [comment] 2023-03-04 13:34
Hello @gruuschesdevelopmenthq and thanks for reporting the issue.

I've tried to reproduce it both in desktop browser and on my phone, but panning seems to work correctly. Could you provide me with a short screen recording showing the issue? Thanks in advance.

**Comment by gruuschesdevelopmenthq** [comment] 2023-03-04 13:53
hi @bm64 , sure! Check the left side of the video because there it can be noticed better. I also added another video of a chart I'm currently working on as I discovered the issue, because as I mentioned it's even more noticeable if the chart is bigger. Also you might notice that the scatter point on the chart disappear as they should but the line chart is breaking out of the frame. So maybe only line charts are affected.

[Screencast from 2023-03-04 14-47-09.webm](https://user-images.githubusercontent.com/48880339/222906028-7375afdb-4b21-4985-a4b7-ce7870be57e7.webm)
[Screencast from 2023-03-04 14-42-47.webm](https://user-images.githubusercontent.com/48880339/222906032-94a8f5da-7d3d-4961-ade4-24618fabee0a.webm)

**Comment by bm64** [comment] 2023-03-06 13:46
@gruuschesdevelopmenthq thanks for videos. This is how it currently behaves on mobile and the reason for such behaviour I have explained here: https://github.com/highcharts/highcharts/issues/18602#issuecomment-1454743948
Having said that, we're aware that it could be improved and I'll bring up the topic for team again. I'm closing this one as a duplicate of #5270. If there is anything you'd like to add feel free to continue in that ticket

**Closed by bm64** 2023-03-06 13:46 UTC
Labels: Status: Can't reproduce, Status: Pending reply
