### ISSUE TITLE
stacked areaspline

### ISSUE THREAD

**Issue by horstlaubenthal** [highcharts/highcharts#1041] opened 2012-06-12 15:02 UTC
Hi, 
if there is a stacked area, the fillcolor is stacked too. (the fillcolor of above series are not drawn to the bottom of the chart but to next serie beneath only)
But when using areaspline, the color is filled from bottom up for all series. Could be seen on stacked area demo in jsfiddle. when toggling the blue serie, the red area get more red (caused by blue colors absence)

this happens in highcharts and in highstocks.

**Comment by mitar** [comment] 2015-08-12 08:03
Hm, in my data we do have `nulls`, but they are or always null for all series, or it is not null for all series. Would this simplify things? Also, min/max is the same (we reuse the same y-axis).

**Comment by highslide-software** [comment] 2015-08-12 08:33
For the records: mitar's question is regarding support for null values in the `nosegment` branch. 

@mitar The problem can be seen here: http://jsfiddle.net/highcharts/38gvcavr/2/. The areas are not perfectly aligned next to a null point. You need to test if this is a problem for you particular case.

**Comment by mitar** [comment] 2015-08-12 08:35
Good, it seems it works well if nulls are matched: http://jsfiddle.net/9ksvskzf/

**Comment by mitar** [comment] 2015-08-12 08:36
Does `nosegment` branch add anything extra or is addressing only this issue?

**Comment by highslide-software** [comment] 2015-08-12 09:00
It is only addressing stacking of areas and area splines.

**Comment by mitar** [comment] 2015-08-13 07:37
`nosegments` branch does not merge cleanly anymore with current `master`. :-(

**Comment by highslide-software** [comment] 2015-08-13 08:04
I have merged the newest master into nosegments now and resolved the
conflicts. ​

**Comment by mitar** [comment] 2015-08-13 08:06
Thanks! You are awesome!

**Comment by mitar** [comment] 2015-08-13 08:28
It does not work correctly in my case. So blue series is correctly cut, but others are not. Maybe because I am loading them asynchronously?

<img width="1160" alt="untitled" src="https://cloud.githubusercontent.com/assets/585279/9245611/ccf57dce-41a5-11e5-9eec-03e8d842bb87.png">

**Comment by mitar** [comment] 2015-08-13 08:29
Old version (current master) for comparison:

<img width="1157" alt="untitled" src="https://cloud.githubusercontent.com/assets/585279/9245647/27290b30-41a6-11e5-938a-e9165002a5a5.png">

**Comment by highslide-software** [comment] 2015-08-13 08:33
Your gaps - are they null points or just large gaps in the data, determined by the `gapSize` option?

**Comment by mitar** [comment] 2015-08-13 08:38
The are nulls.This is why in the old version there is space in between. I do not use/set `gapSize` at all in my code.

**Comment by highslide-software** [comment] 2015-08-13 08:41
All right. I tried to reproduce it here, but it works: http://jsfiddle.net/hpz7edyr/. Can you help?

**Comment by mitar** [comment] 2015-08-13 08:52
I will take a look. I have to determine which parts of my [codebase](https://github.com/wlanslovenija/django-datastream/blob/master/django_datastream/static/datastream/js/datastream.js) is relevant to this. :-)

**Comment by mitar** [comment] 2015-08-19 18:16
I see the following exceptions in the web console once I switch to the `nosegment` branch.

![untitled2](https://cloud.githubusercontent.com/assets/585279/9364899/781b857e-4663-11e5-9306-e7b80d9c6aa5.png)

But it does not seem to be related, because I get those errors even when I do not render the stacked chart.

**Comment by mitar** [comment] 2015-08-19 19:32
I made a reproduction: http://jsfiddle.net/hpz7edyr/1/

**Comment by highslide-software** [comment] 2015-08-21 08:23
It doesn't reproduce for me... Using Chrome 44 on the Mac. Any steps
necessary for reproduction? Also try to set a specific with setting for the
chart, as it affects data grouping and other layout features.

Best regards,
*Torstein Hønsi*
CTO, Founder
Highsoft AS

2015-08-19 21:32 GMT+02:00 Mitar <notifications@github.com>:

**Comment by pawelfus** [comment] 2015-08-21 08:41
Tested also on Firefox - no errors.
However, when zooming in, graph is empty.

**Comment by mitar** [comment] 2015-08-22 21:18
OK, maybe we are looking at a different thing? Because for me it works (in the sense that the problem is there) both in Chrome and Firefox on Mac: http://jsfiddle.net/hpz7edyr/1/

So I get this:

![untitled](https://cloud.githubusercontent.com/assets/585279/9425919/9c132320-48d8-11e5-8f7e-2d2ad1aded4c.png)

But what it should be is that there is for both series nothing in the middle, not just for the blue one.

**Comment by mitar** [comment] 2015-08-22 21:21
Just to be clear, this is not a reproduction for error I reported in [this comment](https://github.com/highslide-software/highcharts.com/issues/1041#issuecomment-132729219), but problem I reported in [this comment](https://github.com/highslide-software/highcharts.com/issues/1041#issuecomment-130573576). The error comes from some of my other chart rendered at the same time (not even stacked ones). So there is some regression somewhere, but I did not investigate that yet. Does `nosegment` branch only change how things around stacked charts or also other things?

**Comment by highslide-software** [comment] 2015-08-24 08:31
It works when [initiated with data](http://jsfiddle.net/highcharts/hpz7edyr/2/), as generally recommended, and also when [deferring the chart redraw](http://jsfiddle.net/highcharts/hpz7edyr/3/), also as recommended when doing multiple updates.

**Comment by mitar** [comment] 2015-08-24 08:36
I cannot use it with initiated data because data is loading a bit longer from the server, but I would like to pre-create charts in advance to reserve DOM space.

It is strange that it works with deferring the redraw because in my original code I am doing that as well. So there might be some other difference in that case.

**Comment by highslide-software** [comment] 2015-08-24 08:39
> but I would like to pre-create charts in advance to reserve DOM space​

You mean like pixel space on screen? In that case you can set a height on
the container element using CSS.

**Comment by mitar** [comment] 2015-08-24 08:41
It is easier to create an empty chart and ask Highcharts to show "loading" message. :-) I would like that it is the same look as later on when data is loaded again after the extremes change.

**Comment by mitar** [comment] 2015-08-30 17:31
OK, I [reproduced here](http://jsfiddle.net/hpz7edyr/4/) something which I have in practice.

So notice again how the black one goes over the empty space, but it should not. Also, notice how in `nosegment` branch in navigator lines go the whole way, despite there being `null` values.

![highcharts_stock_demo_-_jsfiddle_-_2015-08-30_10 29 31](https://cloud.githubusercontent.com/assets/585279/9568559/054f10e0-4f02-11e5-9b47-ff5f68e69bf3.png)

With `master` branch things are rendered correctly, but of course the stacking goes the whole height there.

![highcharts_stock_demo_-_jsfiddle_-_2015-08-30_10 29 56](https://cloud.githubusercontent.com/assets/585279/9568563/33bc1040-4f02-11e5-9402-1217d28a728c.png)

**Comment by mitar** [comment] 2015-11-21 11:56
`nosegments` branch does not merge cleanly anymore with current `master`. :-(

**Comment by highslide-software** [comment] 2015-11-24 14:13
I've resolved conflicts now, see 3b66151be1a42f27774067ba89e82468afb172d3.

**Comment by mitar** [comment] 2015-11-24 20:05
Any point at which this will be merged into master?

**Comment by mitar** [comment] 2015-11-24 20:05
(And thanks!)

**Comment by mitar** [comment] 2015-11-24 20:05
(And thanks!)

**Comment by sebastianbochan** [comment] 2016-04-14 08:28
Seems that is still buggy. Lets compare:
- http://jsfiddle.net/rk7kf539/
- http://jsfiddle.net/9taw5L5a/

In the right side, stacking is incorrect.

**Comment by sebastianbochan** [comment] 2016-08-04 09:48
+1

**Comment by TorsteinHonsi** [comment] 2016-08-04 10:03
Regarding your comment from 14 Apr, you didn't apply stacking to the areaspline because you only provided `plotOptions.area`. Here's how it looks when applied: http://jsfiddle.net/highcharts/rk7kf539/1/

**Comment by TorsteinHonsi** [comment] 2016-08-04 10:11
I think the remaining fail case can be simplified to this: http://jsfiddle.net/highcharts/vkkhny8y/1/

**Closed** 2016-08-04 10:58 UTC
Labels: Enhancement

**Comment by mitar** [comment] 2016-08-04 11:03
So all this is now available in master? Great!
