### ISSUE TITLE
Grouped Boxplot with whiskers

### ISSUE THREAD

**Issue by vidhya123cse** [highcharts/highcharts#21345] opened 2024-06-19 09:54 UTC
Individual whiskers are not showing,  when we are grouping box plot using **highchart and react**
For each box , need to see its own whisker

https://jsfiddle.net/bs6n2x4m/14/

https://www.highcharts.com/forum/viewtopic.php?p=193352#p193352

expected chart  : [
![result](https://github.com/highcharts/highcharts/assets/37735729/743600b1-eefb-41bd-a45d-5ecb0976fdde)
](url)

but getting like this.
![sample](https://github.com/highcharts/highcharts/assets/37735729/84ff3eed-5c91-49f6-9e91-c043fbcdacb0)
(Dummy data)

**Comment by hubertkozik** [comment] 2024-06-20 06:52
Hi @vidhya123cse! The issue is already fixed on the master branch: https://jsfiddle.net/BlackLabel/q2g8m6ab/

Closing as duplicate of https://github.com/highcharts/highcharts/issues/21245.

**Closed by hubertkozik** 2024-06-20 06:52 UTC
Labels: Duplicate
