### ISSUE TITLE
Drilldown : Rendering issue on Firefox (Highcharts official demo)

### ISSUE THREAD

**Issue by mrp14** [highcharts/highcharts#9929] opened 2019-01-17 19:17 UTC
#### Expected behaviour
When hovering over column series with drilldown module, column should highlight properly.

#### Actual behaviour
With Firefox 64.0.2, using the Drilldown official demo, highlighting effect is not working properly. When hovering the first column (Animals), some area are not highlighted. Same thing happens on the first column of the Animals drilldown series (Cats). 
Google Chrome v71.0.3578.98 is not affected.

#### Live demo with steps to reproduce
Official demo : http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/drilldown/basic/

#### Product version
Highcharts JS v7.0.2 (2019-01-17)

#### Affected browser(s)
Firefox 64.0.2

**Comment by KacperMadej** [comment] 2019-01-17 20:56
Hi @mrp14 

Thank you for reporting about the problem.

It's probably one of many, similar, already reported SVG problems with Firefox 64 - this is probably a browser error and should be resolved in Firefox 65. Related issue with more info: https://github.com/highcharts/highcharts/issues/9745

**Comment by TorsteinHonsi** [comment] 2019-01-18 11:51
Yes, it's the same. Not related to drilldown. I'm closing this as a duplicate of #9745. The good news is that the Mozilla team has fixed it so it's coming up in a future Firefox release.

**Closed by TorsteinHonsi** 2019-01-18 11:51 UTC
Labels: Bug
