### ISSUE TITLE
Charts distorted after upgrading to 4.2.6

### ISSUE THREAD

**Issue by jentyk** [highcharts/highcharts#5653] opened 2016-09-02 17:45 UTC
#### Expected behaviour:
Charts not distorted

#### Actual behaviour:
Charts actually distorted. You hopefully see it when you compare the chart using below fiddle and Highcharts ver 4.2.5 and 4.2.6

#### Live demo with steps to reproduce:
http://jsfiddle.net/jentyk/ojov2vng/

#### Affected browser:
Chrome Version 52.0.2743.116 (64-bit).

**Comment by TorsteinHonsi** [comment] 2016-09-05 10:13
Thanks for reporting! It's a duplicate of #5607. It is caused by some point names being repeated. We'll come up with a fix ASAP.

**Closed by TorsteinHonsi** 2016-09-05 10:13 UTC

**Comment by TorsteinHonsi** [comment] 2016-09-05 11:14
Your demo with the fix applied: http://jsfiddle.net/highcharts/ojov2vng/1/

Note the new option, `xAxis.nameToX`.

**Comment by jentyk** [comment] 2016-09-05 13:07
Thanks! :-)
