### ISSUE TITLE
Black exported chart fill colour

### ISSUE THREAD

**Issue by amree** [highcharts/highcharts#18361] opened 2023-01-25 07:21 UTC
#### Expected behaviour

Exported PNG chart fill area should use gradient colour

#### Actual behaviour

Exported PNG chart fill area is using black as the background colour. FYI, I'm using the same sample from the [doc](https://www.highcharts.com/docs/chart-design-and-style/gradients-shadows-and-patterns)

![gradients-in-styled-mode (6)](https://user-images.githubusercontent.com/424392/214503120-6502d086-73c5-40e4-af9d-8a28ba79559d.png)

#### Live demo with steps to reproduce

1. Go to https://jsfiddle.net/fwroymbv/
2. Click the hamburger menu
3. Choose "Download PNG Image"

#### Product version
v10.3.3

#### Affected browser(s)
Brave [Version 1.47.171 Chromium: 109.0.5414.87 (Official Build) (x86_64)]

**Comment by amree** [comment] 2023-01-25 07:51
Found out that I need to define the style so that the generated SVG will have info about the gradient as the exported image doesn't have the CSS where the info about the gradient was defined.

```javascript
children: [{
  tagName: 'stop',
  offset: 0,
  style: "stop-color:#7cb5ec; stop-opacity:0.75"
}, {
  tagName: 'stop',
  offset: 1,
  style: "stop-color:#7cb5ec; stop-opacity:0"
}]
```

This worked on my local, but for some reason, it doesn't work in the [jsfiddle](https://jsfiddle.net/fwroymbv/2/)

**Comment by pawellysy** [comment] 2023-01-25 10:19
Duplicate of https://github.com/highcharts/highcharts/issues/17093

**Closed by pawellysy** 2023-01-25 10:19 UTC
