### ISSUE TITLE
Pie chart : Script error is seen in console on hovering legend item having data value -1

### ISSUE THREAD

**Issue by tejaspchordiya** [highcharts/highcharts#11757] opened 2019-08-23 11:05 UTC
#### Expected behaviour
I want to add extra data point to show rule satisfied items.
Following script error should not be seen on console when I hover on legend item defined for the rules.

> highcharts.src.js:38737 Uncaught TypeError: Cannot read property 'parentGroup' of undefined
>     at a.setState (highcharts.src.js:38737)
>     at SVGGElement.<anonymous> (highcharts.src.js:38239)

#### Actual behaviour
Error is seen on hovering legend item whose value is -1

#### Live demo with steps to reproduce
https://jsfiddle.net/Lc58mruo/6/

#### Affected browser(s)
All

**Comment by pawelfus** [comment] 2019-08-23 12:23
Hi @tejaspchordiya

Thanks for reporting the issue. To hide elements from a pie chart, but render them in legend, please use `y: null` instead of `y: -1`. Apart from the error (which should be fixed), `-1` is not a valid value for a pie chart :) Demo: https://jsfiddle.net/BlackLabel/rc3jak7z/

**Comment by sebastianbochan** [comment] 2020-01-03 10:43
The issue is not valid since v7.0.3

Demo:
- https://jsfiddle.net/BlackLabel/zpmjco6d/

**Closed by sebastianbochan** 2020-01-03 10:43 UTC
Labels: Type: Bug
