### ISSUE TITLE
Really small column widths for time series charts

### ISSUE THREAD

**Issue by ghost** [highcharts/highcharts#987] opened 2012-05-30 08:07 UTC
I saw lots of column widths issues opened but could not find anything similar so I am creating this issue. 

I have created column chart with datetime x-axis and 2 series. As you can see the widths of columns is extremely small/thin here.

https://jsfiddle.net/MrHunt/EarAJ/

If instead of two series, I only have one series with these two points the column widths are perfect. I believe it should look the same in the two column scenario too.
I saw this issue both in 2.2.2 and 2.2.3 versions.

Thanks.

**Comment by mrp14** [comment] 2020-02-19 16:47
I've encountered the same issue today, and solved it by setting `grouping: false` in series plotOptions, as described here : https://stackoverflow.com/a/44655504/2806497

**Comment by bre1470** [comment] 2020-02-20 08:13
The workaround of @mrp14 works for the original issue: https://jsfiddle.net/895hybp1/

If you have one series containing all extremes, you do not need a workaround at all: https://jsfiddle.net/895hybp1/1/

**Comment by dfenerski** [comment] 2021-01-18 14:34
any progress on this? when there are 10+ series the result is really bad
![image](https://user-images.githubusercontent.com/48520530/104928118-8ff98300-59a2-11eb-9347-438d96a6cd51.png)
(stacked column chart)

**Comment by bre1470** [comment] 2021-01-25 14:28
@dfenerski Thanks for your feedback! I am not sure, your issue is related. Does every series in your chart has only one point? If this is not the case, please create a new issue. In any case we need a jsfiddle demo that reproduces your issue.

**Comment by dfenerski** [comment] 2021-01-25 14:33
@bre1470 after some research I found out mine was caused by the boost module. The threshold was falsely set to a too low number so the module was kicking in too early and it made the columns 1px wide.

**Comment by hubertkozik** [comment] 2023-11-02 12:53
This issue has been fixed in https://github.com/highcharts/highcharts/pull/18897. Closing as complete.

**Closed by hubertkozik** 2023-11-02 12:53 UTC
Labels: Status: Won't fix, Status: Has workaround
