### ISSUE TITLE
Stock Tools - issue with saving simple annotations to localStorage

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#12054] opened 2019-09-24 14:14 UTC
An error occurs when trying to restore annotation from the localStorage.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/kv7m1ejt
1. Create simple annotation, let's say circle.
2. Click saveChart button to save annotation in localStorage
3. Remove annotation
4. Add annotation from localStorage using chart.addAnnotation() method - annotation shows up but isn't working fully

#### Product version
Highstock 7.2.0

**Comment by pawelfus** [comment] 2019-09-25 09:06
*Internal note:*
This happens only with simple annotations (labels, rectangles and circles) - and it's caused by defining a function for a control point's positioner. We don't store functions in localStorage so when recreating an annotation, we create a control point and try to call positioner which doesn't exist. 

For all other annotations it's not a problem - all of them are classes with default options, while simple annotations are just configs generated on the fly and used in `addAnnotation()`.

**Comment by baradwys** [comment] 2019-12-17 22:20
Hello,
Is any workaround available for that issue?

**Comment by sebastianbochan** [comment] 2019-12-18 10:24
Hi @baradwys,
At this moment it looks like simple annotations are broken and we need to refactor them. Currently we do not have ETA for that due to christmas time.

**Comment by pawelfus** [comment] 2019-12-30 12:24
To be picked up after #12574 PR merge.

**Comment by pawelfus** [comment] 2020-02-26 11:37
Solution:
Wrap basic annotations in classes-like objects that will be included in StockTools (not in Annotations to avoid bloating annotations code - it's StockTools-specific issue). Perhaps it's possible to use `H.extendAnnotation` with `CrookedLine` class as a base.

It might be a good moment to create `modules/stock-tools` directory and move there `bindings` and `gui`.

**Closed** 2020-04-16 10:39 UTC
Labels: Product: Highstock, Status: Backlog, Type: Bug

**Comment by hpzudo** [comment] 2023-10-18 15:41
Hi there, any update on this ?

> _Solution proposal:_ Wrap basic annotations in classes-like objects that will be included in StockTools (not in Annotations to avoid bloating annotations code - it's StockTools-specific issue). Perhaps it's possible to use `H.extendAnnotation` with `CrookedLine` class as a base.
> 
> It might be a good moment to create `modules/stock-tools` directory and move there `bindings` and `gui`.

I'm trying to preset some annotations (lines basically) during stock chart rendering and I cannot see them displayed.
The documentation is not very clear :(

**Comment by pawelfus** [comment] 2023-10-20 09:19
Oh, here is the second part of the question, kind of the first part answered already in https://github.com/highcharts/highcharts/pull/13318 

I recommend you contact our support, perhaps you didn't load the annotations module, or there is a mistake in the config.

Meanwhile, just tested the solution from #13318 - looks fine: https://jsfiddle.net/BlackLabel/L6s4fev0/
