### ISSUE TITLE
Line series sometimes show a fill in latest versions of chrome

### ISSUE THREAD

**Issue by rrajewski** [highcharts/highcharts#10514] opened 2019-04-08 12:55 UTC
#### Expected behaviour
- Line does not have a fill
![image](https://user-images.githubusercontent.com/3542486/55725439-52955280-59d3-11e9-9c1e-47efca3164e1.png)

#### Actual behaviour
![image](https://user-images.githubusercontent.com/3542486/55725432-4c06db00-59d3-11e9-83cf-a2ed928de586.png)
- Depending on where the line starts, it may or may not show the fill

#### Live demo with steps to reproduce
https://jsfiddle.net/g1ph4yfv/

* open in Chrome 73.0.3683.86+

#### Affected browser(s)
* Windows 10 - Chrome starting at version 73.0.3683.86, still a problem with 73.0.3683.103. It worked in prior versions.
* Looks fine in Firefox, Edge, IE

**Comment by pawelfus** [comment] 2019-04-08 14:17
Hi @rrajewski 

Thank you for reporting the issue. It looks like a bug in Chrome, SVG example without Highcharts: https://jsfiddle.net/BlackLabel/4fe9kznt/ - works fine in Firefox

Reported to Chrome devs: https://bugs.chromium.org/p/chromium/issues/detail?id=950508

**Comment by hawaiikaos** [comment] 2019-05-07 16:25
I can confirm that this is fixed in version 76 (current dev and canary), but not in 74 (I don't know about 75). I was trying to find the eta on when this will be out on stable but I can't find anything on it.

**Comment by pawelfus** [comment] 2019-05-08 08:42
The same here, just tested v74, issue is still there.

**Comment by pawelfus** [comment] 2019-06-04 09:11
Tested with v74.0.3729.169 - the issue is still here.

**Comment by pawelfus** [comment] 2019-06-13 10:12
Tested with v75.0.3770.80 - still broken. Most probably we need to wait for v76.

**Comment by pawelfus** [comment] 2019-07-31 10:41
Fixed in Chrome:
> Version 76.0.3809.87 (Official Build) (64-bit)

**Closed by pawelfus** 2019-07-31 10:41 UTC
Labels: Status: Inbox
