### ISSUE TITLE
Highchart - graph disappears from the axis after it was already drawn

### ISSUE THREAD

**Issue by litalch** [highcharts/highcharts#3522] opened 2014-10-20 08:27 UTC
I have a very strange problem using highchart. I'm using area graph, but sometimes, after it showing the graph, it disappears from the axis (after a few MS). In firebug, I saw that in highcharts-series, path elements have **display:none**.

Why does it happen?

Attached jsfiddle: http://jsfiddle.net/2s6kK/14/.

Here is the HTML of the highcharts-series when the path display:none:
` <g class="highcharts-series" visibility="visible" zIndex="0.1" transform="translate(66,10) scale(1 1)" clip-path="url(#highcharts-35)"><path fill="rgb(255,67,46)" d="M 88.625 300 L 265.875 279.6 L 443.125 300 L 620.375 297.6 L 797.625 292.2 L 974.875 300 L 1152.125 300 L 1329.375 288 L 1506.625 292.8 L 1683.875 285 L 1861.125 278.4 L 2038.375 292.2 L 2215.625 274.8 L 2392.875 195 L 2570.125 40.19999999999999 L 2747.375 267 L 2924.625 300 L 3101.875 298.2 L 3279.125 295.2 L 3456.375 300 L 3633.625 299.4 L 3810.875 298.2 L 3988.125 298.2 L 4165.375 297.6 L 4165.375 300 L 88.625 300" fill-opacity="0.75" zIndex="0" style="display: none;"></path><path fill="none" d="M 88.625 300 L 265.875 279.6 L 443.125 300 L 620.375 297.6 L 797.625 292.2 L 974.875 300 L 1152.125 300 L 1329.375 288 L 1506.625 292.8 L 1683.875 285 L 1861.125 278.4 L 2038.375 292.2 L 2215.625 274.8 L 2392.875 195 L 2570.125 40.19999999999999 L 2747.375 267 L 2924.625 300 L 3101.875 298.2 L 3279.125 295.2 L 3456.375 300 L 3633.625 299.4 L 3810.875 298.2 L 3988.125 298.2 L 4165.375 297.6" stroke="#ff432e" stroke-width="2" zIndex="1" stroke-linejoin="round" stroke-linecap="round" style="display: none;"></path><path fill="none" d="M 78.625 300 L 88.625 300 L 265.875 279.6 L 443.125 300 L 620.375 297.6 L 797.625 292.2 L 974.875 300 L 1152.125 300 L 1329.375 288 L 1506.625 292.8 L 1683.875 285 L 1861.125 278.4 L 2038.375 292.2 L 2215.625 274.8 L 2392.875 195 L 2570.125 40.19999999999999 L 2747.375 267 L 2924.625 300 L 3101.875 298.2 L 3279.125 295.2 L 3456.375 300 L 3633.625 299.4 L 3810.875 298.2 L 3988.125 298.2 L 4165.375 297.6 L 4175.375 297.6" stroke-linejoin="round" visibility="visible" stroke-opacity="0.0001" stroke="rgb(192,192,192)" stroke-width="22" zIndex="2" class=" highcharts-tracker" style="display: none;"></path></g>`

Please help us.

Thanks

**Comment by dianakk** [comment] 2016-03-04 08:22
Just fix the container height, on which you bind your chart.

**Comment by jon-a-nygaard** [comment] 2016-04-26 09:46
Closing this issue due to: We are not able to reproduce the issue, and it is pending reply. 
Should anyone have further information on this issue, please add a comment and reopen.

**Closed by jon-a-nygaard** 2016-04-26 09:46 UTC
Labels: Cant reproduce, Pending reply
