### ISSUE TITLE
Series update method() didn't update every series in chart.

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#6162] opened 2016-12-18 11:42 UTC
#### Expected behaviour
When iterating over chart series and updating them with new parameters, all series should be updated, not just some of them.

It looks to be working fine in Highstock 4.2.7 version:
http://jsfiddle.net/pv9rqduf/6/

#### Actual behaviour
It looks that not every series is updating its parameters.

#### Live demo with steps to reproduce
http://jsfiddle.net/pv9rqduf/7/

Steps to reproduce: click on 'aaa' button, then look on tooltip.

**Comment by pawelfus** [comment] 2016-12-19 10:19
**Workaround:**
Update series, starting from the last one, in a decrementing order: http://jsfiddle.net/pv9rqduf/8/

    function updateChartIterator(chart, options) {
      for (var i = chart.series.length - 1; i >= 0; i--) {
        chart.series[i].update(options, false);
      }
      chart.redraw();
    }

*Internal note:*
It's related to auto-updating navigator's series and something is wrong with indexes (note: update actually remove series and recreates it).

**Comment by TorsteinHonsi** [comment] 2016-12-19 10:24
See in [this modified demo](http://jsfiddle.net/pv9rqduf/9/) how we update Series 1, and the Navigator is re-inserted in the wrong place.

**Comment by pawelfus** [comment] 2016-12-19 16:05
*Internal note:*
It's caused by [this line](https://github.com/highcharts/highcharts/blob/14aca4921d548957f8717f0a37aedd46bdb986bb/js/parts/Dynamics.js#L599): when first series is updated then it's index is set to 0. Now, navigator takes index from that series and creates a navigator series with index=0 (options are extended/merged). Because of that, we have wrong order of series. Alternatively we can set `chart.series.length` as index, but I don't see any reason to add complicity.

**Closed** 2016-12-20 11:08 UTC
Labels: Bug
