### ISSUE TITLE
Export - incorrect data

### ISSUE THREAD

**Issue by vem-itsolution** [highcharts/highcharts#15426] opened 2021-03-30 15:04 UTC
in my data, some positions can be completely repeated (same value on the same date). I was able to use the stacking parameter to ensure that all the data was displayed on the graph. But when exporting to csv, xls or when viewing a table online, only unique data is displayed.

#### Expected behaviour
in the export data xls there will be a total of 300 rubles for unsuccessful transactions, 250 for successful transactions

#### Actual behaviour
in the export data xls there will be a total of 200 rubles for unsuccessful transactions, 150 for successful transactions

#### Live demo with steps to reproduce
https://jsfiddle.net/ea6nzh8u/

**Comment by KacperMadej** [comment] 2021-03-31 17:43
Hi @vem-itsolution 

Thank you for reporting the problem.

This could be resolved in `Highcharts.seriesTypes.column.prototype.requireSorting = false;`.
Demo: https://jsfiddle.net/BlackLabel/hqje8mrd/

Data for column type series is expected to have different x values - this is by design, so this is not a bug and I will be closing the issue. In case you would like to see this issue reopened please add a comment with more info.

**Closed by KacperMadej** 2021-03-31 17:43 UTC

**Comment by vem-itsolution** [comment] 2021-04-01 12:14
> Hi @vem-itsolution
> 
> Thank you for reporting the problem.
> 
> This could be resolved in `Highcharts.seriesTypes.column.prototype.requireSorting = false;`.
> Demo: https://jsfiddle.net/BlackLabel/hqje8mrd/
> 
> Data for column type series is expected to have different x values - this is by design, so this is not a bug and I will be closing the issue. In case you would like to see this issue reopened please add a comment with more info.

OMG, thank you very much! =)
