### ISSUE TITLE
IE8 Highstock 1.3.5 horizontal scrollbar is frozen

### ISSUE THREAD

**Issue by jimioh** [highcharts/highcharts#3061] opened 2014-05-15 09:40 UTC
We've encountered unexpected behaviour where the horizontal scrollbar appears but is frozen for charts viewed in IE8.

Looking into what was happening, it seems that in highstock.js (1.3.5) is getting to line 9067 as pageX is undefined which is expected in IE8 but the chartY measurement is getting set incorrectly ie. e.y refers to the distance from the viewport not the last positioned element. It should be the equivalent of e.pageY in a modern browser.

To verify inspect the values of e.y and e.clientY and then view this W3C documentation
http://www.w3.org/TR/cssom-view/#extensions-to-the-mouseevent-interface

and this erroneous Microsoft documentation:
http://msdn.microsoft.com/en-us/library/ie/ff974344(v=vs.85).aspx

The incorrect assignment of this variable is causing any mousedown events to fall outside the checking of bounds of the scrollbar on line 18490:

if (chartY > top && chartY < top + height + scrollbarHeight) 

However, I have tried to recreate this in a jsFiddle, but interestingly the mouse event contains pageX and pageY values so takes a different execution path entirely and works fine (IE8 emulation through IE Developer Tools). I'm not sure why.

So would someone be able to verify this is occuring?

Basic configuration is a column chart with no navigator, or range selector, but a scroll bar enabled.

**Comment by jon-a-nygaard** [comment] 2016-04-26 09:50
Closing this issue due to: We are not able to reproduce the issue, and it is pending reply. 
Should anyone have further information on this issue, please add a comment and reopen.

**Closed by jon-a-nygaard** 2016-04-26 09:50 UTC
Labels: Cant reproduce, Pending reply
