### ISSUE TITLE
Boost - line serie out of plotarea - zooming

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4832] opened 2015-12-11 10:37 UTC
Looks like canvas is not properly rendered.

Example: http://jsfiddle.net/bsdm7255/
To replicate, please zoom until markers level will appear. 

![zrzut ekranu 2015-12-11 o 11 37 24](https://cloud.githubusercontent.com/assets/2115686/11741801/951c1868-9ffb-11e5-90aa-52d31cd96edd.png)

**Comment by pawelfus** [comment] 2015-12-11 15:14
**Workaround:**
Set clipping rect in redraw event: http://jsfiddle.net/bsdm7255/1/

*Internal note:*
This is caused by using the same group for markers and line in boost module: https://github.com/highcharts/highcharts/blob/fcd69f5e0f833e1e705925b35b71c23ff2ed10dd/js/modules/boost.src.js#L361

**Comment by findoo** [comment] 2015-12-14 10:07
Related bug: If you have points going off the chart, you can mouseover near the Y axis line and display a marker highlight. This is present even when not using the boost module though. 
Using the jsfiddle posted by @pawelfus - 
![UI Bug](https://cloud.githubusercontent.com/assets/3541918/11778116/53fc3ac4-a24a-11e5-9ae3-d2e963cc1f34.png)

**Comment by pawelfus** [comment] 2015-12-14 10:09
Yes, we have bug reported for there as #3916

**Comment by jensaug** [comment] 2016-06-09 12:46
Clarification for the boost-zoom-bug-googlers: You have to apply above "clipping rec" workaround to each serie: http://jsfiddle.net/bsdm7255/3/

**Comment by KacperMadej** [comment] 2019-01-22 15:38
Works fine in v7.0.2
Closing as resolved

**Closed by KacperMadej** 2019-01-22 15:38 UTC
Labels: Bug
