### ISSUE TITLE
PlotBand border on on three out of four sides of rect

### ISSUE THREAD

**Issue by dbasner** [highcharts/highcharts#5909] opened 2016-10-31 14:51 UTC
Unsure if this is purposeful or not, but having plotBorder give a three sided border is a little confusing. It kind of gives the impression that the rectangle runs longer than the length of the chart and just isn't being rendered properly. I feel like the border should either run on all four sides, or alternatively, run on the sides related to the axis that the plot band runs on (x axis plot bands on "left" and "right" side, y axis plot bands on the "top" and "bottom" of the rectangle).
#### Expected behaviour
A plotBand on either the x or y axis would draw a rectangle, and adding a border would show a visible border on all four sides (or two of them to indicate the bounds of that area).

#### Actual behaviour
Border only appears on three sides

#### Live demo with steps to reproduce
http://jsfiddle.net/dbasner/vpkv81au/1/

**Comment by oysteinmoseng** [comment] 2016-11-01 08:44
Thank you for your feedback. Internally all four sides currently have a border, but because of z-indexing only three sides have visible borders.

**Comment by Izothep** [comment] 2017-09-28 14:16
Bug looks to be reintroduced in 5.0.10. Highcharts version. 

It is probably related to below commit: https://github.com/highcharts/highcharts/commit/2b98675ec83f275e76d84e8f9549c5d60c428777

**Comment by torstenlabs** [comment] 2017-09-28 15:26
Hey,
does anybody when it will be fixed?

Regards

Torsten

**Closed** 2017-10-03 09:02 UTC
Labels: Enhancement, Undecided

**Comment by KacperMadej** [comment] 2017-10-03 10:10
Hi Torsten,

The problem is fixed and will be published with next version release.
