### ISSUE TITLE
Chart gradient disappears after the query params change

### ISSUE THREAD

**Issue by shaharkazaz** [highcharts/highcharts#13984] opened 2020-08-02 15:12 UTC
#### Expected behavior
Setting gradient colors on a series should work even when the query params are changing.
Am I missing something?

#### Actual behaviour
The SVG's fill is losing reference after the query params change.

#### Live demo with steps to reproduce
https://codesandbox.io/s/thirsty-wescoff-r8vzk?fontsize=14&hidenavigation=1&theme=dark

#### Product version
8.1.2

**Comment by pawelfus** [comment] 2020-08-03 08:18
Thanks for reporting the issue @shaharkazaz 

Actually, it's already reported: https://github.com/highcharts/highcharts/issues/5244 - closing as duplicate of #5244.

**Closed by pawelfus** 2020-08-03 08:18 UTC
