### ISSUE TITLE
Feature Request for Graph

### ISSUE THREAD

**Issue by teraiyamayurcontact** [highcharts/highcharts#17125] opened 2022-03-24 13:04 UTC
Hello Team,

Example URL : https://ibb.co/YcvDr1q

i need this type of graph which high chart graph will help to implement this one.

Thanks in advance.

**Comment by raf18seb** [comment] 2022-03-24 14:15
Duplicate of https://github.com/highcharts/highcharts/issues/17124

**Closed by raf18seb** 2022-03-24 14:15 UTC
Labels: Type: Feature Request
