### ISSUE TITLE
Shared tooltip not updating on mouseover

### ISSUE THREAD

**Issue by websash** [highcharts/highcharts#6791] opened 2017-06-02 15:29 UTC
### Expected behaviour
Shared tooltip is supposed to update both when you mousemove in the area above columns and when you hover prev and next column

#### Actual behaviour
In the Pre-release version (https://github.highcharts.com/highcharts.js) it updates only when you mouse over columns  

#### Live demo with steps to reproduce
 #https://jsfiddle.net/d29oy9au/

**Comment by pawelfus** [comment] 2017-06-05 08:23
Hi @websash 

Thank you for reporting this issue.

**Comment by TorsteinHonsi** [comment] 2017-06-09 08:08
I can't reproduce this - I think this regression was fixed in v5.0.12, and I get the same result with the pre-release. Closing this, please reopen if new information comes along.

**Comment by websash** [comment] 2017-06-09 08:57
Well in the current https://github.highcharts.com/highcharts.js it can be reproduced if you move your cursor slowly over columns to the righthand side. If you move  fast enough it updates but it's not consistent and therefore is definitely a bug

ps: In my case I have 288 of these columns representing 5min in a day and I'd like my users could read values for every single column without hassle

**Comment by pawelfus** [comment] 2017-06-09 13:56
I was able to recreate issue (osx, chrome): 

![6kcccbjjox](https://user-images.githubusercontent.com/1453926/26978554-3511a4d0-4d2c-11e7-9b63-f0d26c53c610.gif)

**Closed** 2017-06-15 08:03 UTC
Labels: Bug, Fix suggested
