### ISSUE TITLE
Wrong data points selected on column/bar charts with shared tooltips [5.0.11]

### ISSUE THREAD

**Issue by Salet** [highcharts/highcharts#6745] opened 2017-05-18 12:52 UTC
It appears that in current (5.0.11) Highcharts version there's a bug with shared tooltips on column/bar charts with many data points. I couldn't find a matching issue here.

#### Expected behavior
On a column/bar chart with many data points and a shared tooltip, I expect that hovering the chart will select correct data points.

#### Actual behavior
On a column/bar chart with many data points and a shared tooltip wrong data points are selected when hovering over.

#### Live demo with steps to reproduce
Hover the mouse over the chart starting from the left side. When the first black column gets hovered over it appears that the blue column from the next data point is selected. This is behaving even worse on the 'bar' type chart, as it's selecting points from serie 1 randomly. This doesn't happen with the previous version of the library. It's also fine when the hover event is coming from the bottom of the chart.

Wrong behavior (5.0.11): http://jsfiddle.net/tsdg3Lqj/
Correct behavior (5.0.10): http://jsfiddle.net/hgrbgyc1/

#### Affected browser(s)
Chrome, Edge, probably all of them

**Comment by pawelfus** [comment] 2017-05-18 13:12
Thanks for reporting, it's already fixed on our master branch: http://jsfiddle.net/tsdg3Lqj/1/

Closing as duplicate of #6687.

**Closed by pawelfus** 2017-05-18 13:12 UTC
Labels: Duplicate
