### ISSUE TITLE
No 'Reset Zoom' button with multi level drilldown

### ISSUE THREAD

**Issue by amit1911** [highcharts/highcharts#6949] opened 2017-07-12 01:44 UTC
#### Expected behaviour
When i zoom go back from 3rd level drilldown series to second level drilldown then I should either see 'zoom out' option if it was zoomed in or I should see all the data.

#### Actual behaviour
If i zoom in second drilldown series, then go to 3rd drilldown series the 'reset zoom' button is now shown for the third drilldown whereas it should be shown when i return to the second drilldown. When i come back to the second drilldown, I cannot 'zoom out'. I will have to go to level 1 and start start all over.

#### Live demo with steps to reproduce
http://jsfiddle.net/amit1911/k0h5yhsL/1/.
1. Click on 'Animals' and go to level 2.
2. Zoom in on number '10'.
3. Click on '10' and go to level 3 data.
4. Click on 'reset zoom'.
5. Go back to level 2 data.
Now there is no 'Reset zoom' button and we cannot zoom out.

#### Affected browser(s)
All

**Comment by pawelfus** [comment] 2017-07-12 10:15
Hi @amit1911 

Isn't this a duplicate of #6103 ?

**Comment by amit1911** [comment] 2017-07-12 10:18
Oh yeah... Sorry... I guess we can close this.

**Closed** 2017-07-12 10:19 UTC
Labels: Duplicate
