### ISSUE TITLE
ometimes(particularly when zoomed out) uses the wrong data value for the point regardless of grouping

### ISSUE THREAD

**Issue by kailuowang** [highcharts/highcharts#3204] opened 2014-06-27 18:58 UTC
It sometimes(particularly when zoomed out) uses the wrong data value for the point regardless of grouping (i.e. it display the value of 7.31.2012 for a point representing 6.30.2012. This bug not perceivable through naked eye (because you can't really tell the exact date from the point position on xAxis. but you can if you inspect the data.

**Comment by jon-a-nygaard** [comment] 2016-04-26 09:48
Closing this issue due to: We are not able to reproduce the issue, and it is pending reply. 
Should anyone have further information on this issue, please add a comment and reopen.

**Closed by jon-a-nygaard** 2016-04-26 09:48 UTC
Labels: Cant reproduce, Pending reply
