### ISSUE TITLE
Missing series labels

### ISSUE THREAD

**Issue by OldBuddy** [highcharts/highcharts#16420] opened 2021-09-29 11:23 UTC
#### Expected behaviour
Series on left xAxis should have labels.

#### Actual behaviour
Series on left xAxis doesn't have labels (although series on right one has labels).

#### Live demo with steps to reproduce
https://jsfiddle.net/pg3h2bxL/

#### Product version
9.1.0+

#### Affected browser(s)
All

**Comment by raf18seb** [comment] 2021-09-30 08:19
Hi @OldBuddy, thanks for contacting us with your issue.

The series on the left doesn't have visible dataLabels because the points are outside of the plotArea. It is visible here in this simplified demo with a bordered plotArea: https://jsfiddle.net/BlackLabel/pv4k63rg/
This condition is `false`: https://github.com/highcharts/highcharts/blob/4c4770d81d953cd98a2148bfc0ca629a9ab863cc/ts/Core/Series/DataLabel.ts#L244

To force the dataLabels to be displayed, you can set e.g. `forceDL` flag to true on the Series class
```js
Highcharts.Series.prototype.forceDL = true;
```
Your updated demo: https://jsfiddle.net/BlackLabel/zg6aqkfc/

I'm closing the ticket as not a bug.

**Comment by raf18seb** [comment] 2021-10-14 09:54
@OldBuddy, I'm not sure, for now this is only an internal property. We can think about adding something similar in the future.

**Comment by TorsteinHonsi** [comment] 2023-11-03 08:20
For the records, the existing crop option does exactly this: https://api.highcharts.com/highcharts/series.line.dataLabels.crop

**Closed by TorsteinHonsi** 2023-11-03 08:20 UTC
Labels: Type: Not a bug
