### ISSUE TITLE
Export CSV does not work with boost module

### ISSUE THREAD

**Issue by thaihuutam** [highcharts/highcharts#7026] opened 2017-08-01 09:04 UTC
#### Expected behaviour
Exporting CSV successfully with huge data set.

#### Actual behaviour
Cannot export CSV with huge data set, which boost module included.

#### Live demo with steps to reproduce
Example: https://jsfiddle.net/ubytofud/
This chart includes boost module v5.0.14, where the seriesThreshold is set to 50. There are 50 series in the chart, then the boost module kick in. Try the function Download CSV file, the downloaded file is contains no data rather than the header.

#### Affected browser(s)
Firefox 52.2.0

**Comment by vutienthinh** [comment] 2017-08-01 10:19
I also have exact this issue. Could anyone help me out?

**Comment by sebastianbochan** [comment] 2017-08-01 10:20
The export module extracts points from series objects, but in the boost this reference is empty so you should extrac from userOptions.

**Workaround:**
- https://jsfiddle.net/fev7pwr1/

**Comment by thaihuutam** [comment] 2017-08-04 06:49
Thank @sebastianbochan for the workaround.
I just wonder if HighCharts has plan to fix this bug, or we have to live with the workaround.

**Comment by KacperMadej** [comment] 2017-08-04 11:57
@thaihuutam The issue is open and labeled bug, so we will be working on resolving the problem - we are planning to fix this bug. In case the workaround is not working for you please let us know - the more info we have the better the fix could be provided.

**Comment by TorsteinHonsi** [comment] 2017-08-07 10:06
Here is as far as I got now - this version passes all tests except one. Note that the most updated version of the module is https://github.com/highcharts/highcharts/blob/master/js/modules/export-data.src.js .

```js
Highcharts.Chart.prototype.getDataRows = function () {
    var options = (this.options.exporting || {}).csv || {},
        xAxis,
        xAxes = this.xAxis,
        rows = {},
        rowArr = [],
        dataRows,
        names = [],
        i,
        x,
        xTitle,
        // Options
        dateFormat = options.dateFormat || '%Y-%m-%d %H:%M:%S',
        columnHeaderFormatter = options.columnHeaderFormatter || function (item, key, keyLength) {
            if (item instanceof Highcharts.Axis) {
                return (item.options.title && item.options.title.text) ||
                    (item.isDatetimeAxis ? 'DateTime' : 'Category');
            }
            return item ?
                item.name + (keyLength > 1 ? ' (' + key + ')' : '') :
                'Category';
        },
        xAxisIndices = [];

    // Loop the series and index values
    i = 0;
    each(this.series, function (series) {
        var keys = series.options.keys,
            pointArrayMap = keys || series.pointArrayMap || ['y'],
            valueCount = pointArrayMap.length,
            requireSorting = series.requireSorting,
            categoryMap = {},
            xAxisIndex = Highcharts.inArray(series.xAxis, xAxes),
            j,
            // A series-like object that has its own X increment
            mockSeries = {
                options: series.options,
                autoIncrement: series.autoIncrement
            };

        // Map the categories for value axes
        each(pointArrayMap, function (prop) {
            categoryMap[prop] = (series[prop + 'Axis'] && series[prop + 'Axis'].categories) || [];
        });

        if (series.options.includeInCSVExport !== false && series.visible !== false) { // #55

            // Build a lookup for X axis index and the position of the first
            // series that belongs to that X axis. Includes -1 for non-axis
            // series types like pies.
            if (!Highcharts.find(xAxisIndices, function (index) {
                return index[0] === xAxisIndex;
            })) {
                xAxisIndices.push([xAxisIndex, i]);
            }

            // Add the column headers, usually the same as series names
            j = 0;
            while (j < valueCount) {
                names.push(columnHeaderFormatter(series, pointArrayMap[j], pointArrayMap.length));
                j++;
            }

            each(series.options.data, function (pointConfig, pIdx) {
                var point = series.pointClass.prototype
                        .applyOptions.call(
                            { series: mockSeries },
                            pointConfig
                        ),
                    key = requireSorting ? point.x : point.x + '|' + pIdx,
                    prop,
                    val;

                j = 0;

                if (!rows[key]) {
                    // Generate the row
                    rows[key] = [];
                    // Contain the X values from one or more X axes
                    rows[key].xValues = [];
                }
                rows[key].x = point.x;
                rows[key].xValues[xAxisIndex] = point.x;
                
                // Pies, funnels, geo maps etc. use point name in X row
                if (!series.xAxis || series.exportKey === 'name') {
                    rows[key].name = point.name;
                }

                while (j < valueCount) {
                    prop = pointArrayMap[j]; // y, z etc
                    val = point[prop];
					// Pick a Y axis category if present
                    rows[key][i + j] = pick(categoryMap[prop][val], val);
                    j++;
                }

            });
            i = i + j;
        }
    });

    // Make a sortable array
    for (x in rows) {
        if (rows.hasOwnProperty(x)) {
            rowArr.push(rows[x]);
        }
    }

    var xAxisIndex, column;
    dataRows = [names];

    i = xAxisIndices.length;
    while (i--) { // Start from end to splice in
        xAxisIndex = xAxisIndices[i][0];
        column = xAxisIndices[i][1];
        xAxis = xAxes[xAxisIndex];

        // Sort it by X values
        rowArr.sort(function (a, b) { // eslint-disable-line no-loop-func
            return a.xValues[xAxisIndex] - b.xValues[xAxisIndex];
        });

        // Add header row
        xTitle = columnHeaderFormatter(xAxis);
        //dataRows = [[xTitle].concat(names)];
        dataRows[0].splice(column, 0, xTitle);

        // Add the category column
        each(rowArr, function (row) { // eslint-disable-line no-loop-func
            var category = row.name;
            if (!category) {
                if (xAxis.isDatetimeAxis) {
                    if (row.x instanceof Date) {
                        row.x = row.x.getTime();
                    }
                    category = Highcharts.dateFormat(dateFormat, row.x);
                } else if (xAxis.categories) {
                    category = pick(
                        xAxis.names[row.x],
                        xAxis.categories[row.x],
                        row.x
                    );
                } else {
                    category = row.x;
                }
            }

            // Add the X/date/category
            row.splice(column, 0, category);
        });
    }
    dataRows = dataRows.concat(rowArr);

    return dataRows;
};
```

**Comment by thaihuutam** [comment] 2017-08-16 09:47
@KacperMadej FYI,  the workaround works for our case. Thanks a lot.
Still I will wait for the coming version of HighCharts where it is fixed.

**Comment by o3o** [comment] 2017-10-30 09:46
I also have this issue. I will wait for the new version that fix it.
Thank you

**Comment by sangvvan** [comment] 2018-01-30 03:05
Hi @KacperMadej : Do you have new version to fix this problems. It still happens on my side
Thank you

**Comment by sangvvan** [comment] 2018-01-30 03:40
Dear @ sebastianbochan  : your workaround make download PNg, JPEG not work.
Do you know about that and how to fix them?
Thanks

**Comment by KacperMadej** [comment] 2018-01-30 10:26
Hi @sangvvan 

The solutions presented in the thread are not passing all tests, that's why are not implemented.

**Closed** 2018-02-28 14:47 UTC
Labels: Bug

**Comment by sangvvan** [comment] 2018-03-12 08:10
Hi @TorsteinHonsi 
I saw this issue is closed by you.
Was this issue fixed?

**Comment by pawelfus** [comment] 2018-03-12 11:38
Hi @sangvvan 

Yes, the issue is fixed and will be included in the next release. You can see pre-release version using our `github.highcharts.com`: https://jsfiddle.net/BlackLabel/ubytofud/5/

**Comment by sangvvan** [comment] 2018-03-14 08:39
Hi @pawelfus 
Thanks for your anwser.
Can you tell me how to get how to get minified for release ? Because the link above which coding isnot minified.
Thanks

**Comment by TorsteinHonsi** [comment] 2018-03-14 09:50
You can minify it yourself at https://closure-compiler.appspot.com/home. 

Just be aware this is pre-release code.

**Comment by sangvvan** [comment] 2018-03-14 10:30
Thanks so much

**Comment by LeifBloomquist** [comment] 2018-11-09 19:03
I am running into this exact same issue.  I pointed my highcharts src to https://github.highcharts.com as per the jsfiddle above to try out the latest version, but now I get the following error with large data sets:

> Uncaught Failed to convert to blob
Highcharts.downloadURL @ export-data.js:216
Highcharts.Chart.downloadCSV @ export-data.js:1037
onclick @ export-data.js:1175
onclick @ exporting.js:1479

**Comment by TorsteinHonsi** [comment] 2018-11-12 08:58
This fix was released months ago, so you don't have to use github.highcharts.com. Here's the originally posted fiddle with newest official Highcharts version: https://jsfiddle.net/highcharts/ubytofud/10/.

**Comment by LeifBloomquist** [comment] 2018-11-12 15:11
Ah, OK thanks.  However the fiddle you posted doesn't seem to use boost (no boost: enabled: true?).

Here is a fiddle that shows my issue.  When I select Download CSV, I get Failed- Network Error in Chrome 70.0.3538.77

https://jsfiddle.net/LeifBloomquist/5nepwg4s/

**Comment by LeifBloomquist** [comment] 2018-11-13 14:14
OK thanks.  So how can I then resolve this, or work around it?   I was going to write my own CSV-exporter, but with boost enabled the data points are lost after rendering I believe.

**Comment by LeifBloomquist** [comment] 2018-12-03 20:21
> Has anyone been able to resolve this? I have the same issue with chrome.

I gave up and wrote my own CSV exporter that re-requests the data from my database,
