### ISSUE TITLE
Graph line in the navigator falls off the border -  if more than one chart

### ISSUE THREAD

**Issue by sarahrbs** [highcharts/highcharts#18550] opened 2023-02-21 14:59 UTC
#### Expected behavior
Graph line in the navigator (mini map) should fall inside the borders of the navigator, even if there are more than one chart to be displayed. 

#### Actual behavior
Graph line in the navigator goes off the border when there is more than one chart (or) if more than one chart is selected (https://jsfiddle.net/3vb4nxw1/12/). 
If I am not wrong the axis height update causes the issue - Another example: https://jsfiddle.net/BlackLabel/quxb4k3v/

#### Live demo with steps to reproduce
https://jsfiddle.net/3vb4nxw1/12/
Steps to reproduce:
1) Notice the graph line in the navigator, on load. (chart1 checkbox is selected by default) 
2) Click chart2 checkbox - graph line falls off the border 

#### Product version
High stock

#### Affected browser(s)
In all browsers (Chrome and Microsoft edge)

**Comment by pawellysy** [comment] 2023-02-23 08:57
Hello @sarahrbs, this is happening because you are manually updating the navigator axis as well, to have a bigger size. 
If you filter the navigator axis from the update, everything works in order: https://jsfiddle.net/BlackLabel/uhc2Ld64/

also in the another example: https://jsfiddle.net/BlackLabel/quxb4k3v/1/

Closing as `not a bug`.

**Closed by pawellysy** 2023-02-23 08:57 UTC
