### ISSUE TITLE
Log tick positions calculated incorrectly (leads to -Infinity position)

### ISSUE THREAD

**Issue by ibash** [highcharts/highcharts#2448] opened 2013-11-13 17:17 UTC
Hit this case in `getLogTickPositions`:
```
		// Third case: We are so deep in between whole logarithmic values that
		// we might as well handle the tick positions like a linear axis. For
		// example 1.01, 1.02, 1.03, 1.04.
```

We hit a case where this code was causing a problem:
```
			positions = map(axis.getLinearTickPositions(
				interval, 
				realMin,
				realMax	
			), log2lin);
```

getLinearTickPositions was returning `[0, 10000, 20000, ...` and then `log2lin` was doing a `log(0)` leading to `-Infinity` for a position.

Note: We were overriding the tick positioner, which lead to hitting the third case, but the user's tickPositioner code is not called from here. -- Also note that this was the case where it was calculating minor ticks.

**Comment by jon-a-nygaard** [comment] 2016-04-26 10:03
Closing this issue due to: We are not able to reproduce the issue, and it is pending reply. 
Should anyone have further information on this issue, please add a comment and reopen.

**Closed by jon-a-nygaard** 2016-04-26 10:03 UTC
Labels: Cant reproduce, Pending reply
