### ISSUE TITLE
Data label overlaps stack label

### ISSUE THREAD

**Issue by ypconstante** [highcharts/highcharts#7007] opened 2017-07-25 15:41 UTC
#### Expected behaviour
The data label shouldn't be shown or the stack label should be moved up or 

#### Actual behaviour
When creating a stacked column chart and the values of a category are too low, the data label overlaps the stack label.

A workaround that I found is to set the zIndex 5 in the data label, this way the stack label is shown over the data label. Maybe a zIndex for the stack label would be helpful too. 

#### Live demo with steps to reproduce
http://jsfiddle.net/zxnm02n3/1/

With the zIndex in the data label: http://jsfiddle.net/zxnm02n3/2/

**Comment by KacperMadej** [comment] 2017-07-26 10:07
Hi,

Thank you for reporting the issue. Logic for stack labels overlapping is added to the next release candidate, but it seems that it's not working as it should because some labels are overlapping each other still.

Demo: http://jsfiddle.net/2aLo04th/

(without the pre-release fix for comparison: http://jsfiddle.net/2aLo04th/1/)

**Comment by TorsteinHonsi** [comment] 2017-07-28 11:51
It is caused by differences in how the stack labels and data labels are align. Stack labels are currently `text` elements. So the overlapping algorithm is not able to correctly detect overlapping between them.

**Comment by KacperMadej** [comment] 2018-10-04 14:01
Duplicate of #9119 because fix for that issue seems to be resolving this one as well.
(the below demo won't work after PR will be merged into master)
http://jsfiddle.net/BlackLabel/2aLo04th/20/
(the below demo should work after PR will be merged into master)
http://jsfiddle.net/BlackLabel/2aLo04th/22/

If you feel like this issue shouldn't be closed please leave a comment with more info and this issue could be reopened.

**Closed by KacperMadej** 2018-10-04 14:01 UTC
Labels: Bug
