### ISSUE TITLE
Highcharts website bug with Firefox

### ISSUE THREAD

**Issue by roscofil** [highcharts/highcharts#16292] opened 2021-09-03 08:16 UTC
#### Expected behaviour
In the website "Get It menu", I expect to see the download list as shown with Chrome for instance

#### Actual behaviour
Whatever the 
![hc](https://user-images.githubusercontent.com/33526931/131973435-f72c15b7-0fcc-41f5-994a-be8f4a8c310f.jpg)
version of Firefox, no download list is displayed

#### Live demo with steps to reproduce

Using **Firefox 91.0.2 with embedded developer tools** 
Mentionned this issue a while back already. Do I have a particular configuration of Firefox? I don't think so but I can send you a config if need be.
Thx
Philippe

#### Product version

N/A

#### Affected browser(s)

Firefox

**Comment by raf18seb** [comment] 2021-09-03 12:32
Hi @roscofil, thanks for reporting the problem.

I am not able to reproduce it on the newest 91.0.2 Firefox. Could you clear your cache and double check, please? I'll try on different computers too.

**Comment by roscofil** [comment] 2021-09-03 14:02
Hi Rafal,

I did clear the cache as I do many times a day but I don’t see any change so far. 

Philippe

Envoyé de mon iPhone

**Comment by KacperMadej** [comment] 2021-09-06 18:14
Duplicate of https://github.com/highcharts/highcharts/issues/15895

**Closed by KacperMadej** 2021-09-06 18:14 UTC
Labels: Status: Can't reproduce, Status: Pending reply
