### ISSUE TITLE
RangeError: Maximum call stack size exceeded with highcharts-ng

### ISSUE THREAD

**Issue by PRADEEPKORRIYA** [highcharts/highcharts#10044] opened 2019-02-04 07:46 UTC
Hi All, I am updating old project which is in AngularJS 1.5

I am adding a chart into it using highcharts.

<script src="/bower_components/highcharts/Highcharts-7.0.2/code/highcharts.js"></script>
    <script src="/bower_components/highcharts/Highcharts-7.0.2/code/modules/stock.js"></script>
    <script src="/bower_components/highcharts/Highcharts-7.0.2/code/modules/gantt.js"></script>

    <script src="/bower_components/highcharts/Highcharts-7.0.2/code/modules/highcharts-more.js"></script>
    <script src="/bower_components/highcharts/Highcharts-7.0.2/code/modules/exporting.js"></script>
    <script src="/bower_components/highcharts/Highcharts-7.0.2/code/modules/offline-exporting.js"></script>

<script src="/bower_components/highcharts-ng/dist/highcharts-ng.min.js"></script>

Above is libraries import on index page. and following is implementation

<div class="col-lg-4">
         <highchart config="ideaChartView1_c1"></highchart>
</div>

It is giving me error as below
RangeError: Maximum call stack size exceeded
    at H.isObject (http://rtsexcalibur.com/bower_components/highcharts/Highcharts-7.0.2/code/highcharts.src.js:1061:65)
    at Object.<anonymous> (http://rtsexcalibur.com/bower_components/highcharts/Highcharts-7.0.2/code/highcharts.src.js:36261:15)
    at H.objectEach (http://rtsexcalibur.com/bower_components/highcharts/Highcharts-7.0.2/code/highcharts.src.js:2292:18)
    at Object.H.cleanRecursively (http://rtsexcalibur.com/bower_components/highcharts/Highcharts-7.0.2/code/highcharts.src.js:36257:7)
    at a.<anonymous> (http://rtsexcalibur.com/bower_components/highcharts/Highcharts-7.0.2/code/highcharts.src.js:36262:22)
    at H.objectEach (http://rtsexcalibur.com/bower_components/highcharts/Highcharts-7.0.2/code/highcharts.src.js:2292:18)
    at Object.H.cleanRecursively (http://rtsexcalibur.com/bower_components/highcharts/Highcharts-7.0.2/code/highcharts.src.js:36257:7)
    at Object.<anonymous> (http://rtsexcalibur.com/bower_components/highcharts/Highcharts-7.0.2/code/highcharts.src.js:36262:22)
    at H.objectEach (http://rtsexcalibur.com/bower_components/highcharts/Highcharts-7.0.2/code/highcharts.src.js:2292:18)

Please help me to solve it
Thanks

**Comment by pawelfus** [comment] 2019-02-04 16:19
Hi @PRADEEPKORRIYA 

Thanks for reporting the issue, but you should contact authors of highcharts-ng wrapper. If you think this is a bug in Highcharts library, then please recreate issue **without** highcharts-ng wrapper using for example jsfiddle.

**Comment by vpapadopou** [comment] 2019-02-12 12:22
It seems that something in the chart config is causing the chart.update function to call a specific `cleanRecursively` function again and again. 

I was not able to dive into particular details but I can provide you with a jsfiddle. From there perhaps you can see whether it is Highcharts or Highcharts-ng problem?

http://jsfiddle.net/gh/get/jquery/3.1.1/pablojim/highcharts-ng/tree/master/jsfiddles/polar/

**Comment by KacperMadej** [comment] 2019-02-12 18:15
@vpapadopou That something is the chart's container (here provided as an HTML DOM element) with looped reference making the `cleanRecursively` go into an infinite loop. This is not a bug in Highcharts as a default HTML DOM element doesn't have own properties (tested through `hasOwnProperty`), but in AngularJS environment this is not the case - additional properties are being added.

This is a problem with AngularJS altering HTML DOM element making, so the element passed is not the required type and is not supported. The problem should be resolved through AngularJS wrapper.

Not possible to recreate in pure JS - demo: http://jsfiddle.net/BlackLabel/7m0ya8jz/

As a **workaround** set chart's container using [string in renderTo](https://api.highcharts.com/highcharts/chart.renderTo) (or the same, buy through [the first argument of the used constructor](https://api.highcharts.com/class-reference/Highcharts#.chart))

**Comment by vpapadopou** [comment] 2019-02-20 07:59
It is a super-ugly fix but if anyone has the same problem you can try and monkey-patch `cleanRecursively`. When you see the `renderTo` key, simply assign the value and continue.

Code:

```javascript
var Highcharts = require('highcharts');
var each = require('underscore').each;
var isObject = require('underscore').isObject;

Highcharts.cleanRecursively = function (newer, older) {
  var result = {};

  each(newer, function (val, key) {
    var ob;

    // Dive into objects
    if (isObject(newer[key], true) && older[key]) {
      if (key === 'renderTo') {
        result[key] = val;
      }
      else {
        ob = Highcharts.cleanRecursively(newer[key], older[key]);
        if (Object.keys(ob).length) {
          result[key] = ob;
        }
      }

      // Arrays or primitives are copied directly
    }
    else if (isObject(newer[key]) || newer[key] !== older[key]) {
      result[key] = newer[key];
    }
  });

  return result;
};
```

**Comment by j-walker23** [comment] 2019-04-13 19:48
@vpapadopou You are a life saver. Thank you!
It's crazy this is a won't fix for all of angularjs on a pretty pricey product.

**Comment by TorsteinHonsi** [comment] 2019-04-23 12:01
> It's crazy this is a won't fix for all of angularjs on a pretty pricey product
As far as I can see, it is an issue with [highcharts-ng](https://www.npmjs.com/package/highcharts-ng), which is a free, third-party wrapper for Highcharts.

Our official wrapper can be found at https://www.npmjs.com/package/highcharts-angular.

**Comment by j-walker23** [comment] 2019-04-23 12:49
Thanks for the official wrapper link, but sadly we're talking about angularjs. It's good to know the magical day i can upgrade to Angular there is an offical wrapper. One day...

As for angularjs, it's 100% an issue with highcharts v7.x. v6 works with latest highcharts-ng(angularjs), 7 doesn't. But it's no biggie. The suggested workaround worked perfectly.

Highcharts v7 blows up if a dom element is passed to the constructor that is modified. ie. 100% of all angularjs jquery elements. 
That big of a breaking change and the following attitude just surprised me at first considering how much i pay for the package. Highcharts is a godsend overall and is worth every penny, easy add workaround and i'm happy.

**Comment by TorsteinHonsi** [comment] 2019-04-24 10:35
@j-walker23 Actually I agree with you it's a bug. It can be reproduced by letting the container point to itself: 

http://jsfiddle.net/highcharts/w74jsg5k/2/

**Comment by j-walker23** [comment] 2019-04-24 10:59
@TorsteinHonsi Very cool, nice job finding something applicable!

**Closed** 2019-04-25 07:42 UTC
Labels: Type: Bug, Type: Regression

**Comment by TorsteinHonsi** [comment] 2019-04-25 08:53
Demo with the fix applied: http://jsfiddle.net/highcharts/w74jsg5k/7/

@j-walker23 Please let us know if the fix also works well with your use case, otherwise I'm sure we can reproduce and resolve that case too.

**Comment by j-walker23** [comment] 2019-04-26 01:26
@TorsteinHonsi That was it. 100% fixes it! Thank you for doing it.

**Comment by TorsteinHonsi** [comment] 2019-04-26 11:42
You're welcome, thanks for your patience!
