### ISSUE TITLE
livedraw on panning is not correctly working on mobile browsers

### ISSUE THREAD

**Issue by bosseDev** [highcharts/highcharts#12561] opened 2019-12-04 12:46 UTC
#### Expected behaviour
The chart should livedraw the graph like the navigator/scrollbar on panning/scrolling.
It's workin fine in normal browsers but not in mobile browsers.

#### Actual behaviour
On touchstart/panning the graph overlaps with the y-axis.
![Screenshot 2019-12-04 at 12 18 37](https://user-images.githubusercontent.com/47507057/70142865-875cc500-169a-11ea-8d8f-3422547c3eb2.png)

And is redrawn after touchend.
![Screenshot 2019-12-04 at 12 08 19](https://user-images.githubusercontent.com/47507057/70142920-9fccdf80-169a-11ea-87d3-d9c4de73835a.png)

#### Product version
7.2.1

#### Affected browser(s)
mobile browsers

**Comment by sebastianbochan** [comment] 2019-12-05 10:37
Hi @bosseDev,
Do you mean that during panning, the line of chart is "outside" and "new line" is draw when your fingers are out of the screen?

If yes, its duplicate of the ticket https://github.com/highcharts/highcharts/issues/10824 and https://github.com/highcharts/highcharts/issues/5270

**Comment by bosseDev** [comment] 2019-12-19 13:54
Thx @sebastianbochan,
found the solution at #5270. https://github.com/highcharts/highcharts/issues/5270#issuecomment-342767958
I had to replace the pointer.pinch call with chart.pan.

`Highcharts.wrap(Highcharts.Pointer.prototype, 'pinch', function (proceed, e) {
	if (e.touches.length === 1 && e.type === 'touchmove') {
    	this.chart.pan(e, this.chart.options.panning);
    } else {
    	proceed.call(this, e);
        if (e.type === 'touchstart') {
           	this.chart.mouseDownX = this.pinchDown[0].chartX;
	    	this.chart.mouseDownY = this.pinchDown[0].chartY;
        }
    }
})`

**Comment by sebastianbochan** [comment] 2019-12-19 15:36
You're welcome.
So Im closing this ticket as duplicate.

**Closed by sebastianbochan** 2019-12-19 15:36 UTC
