### ISSUE TITLE
Incorrect word

### ISSUE THREAD

**Issue by Xnoyer** [highcharts/highcharts#7784] opened 2018-02-02 09:02 UTC
https://github.com/highcharts/highcharts/blob/9be60aa3c899d105071af92e43630c2f889fcc86/js/supplemental.docs.js#L1623-#L1633

Word "greater" must be changed to "less"

**Comment by pawelfus** [comment] 2018-02-02 10:16
Thanks for reporting. Duplicate of #7781

**Closed by pawelfus** 2018-02-02 10:16 UTC
