### ISSUE TITLE
pattern and visibility of series or sets for venndiagram

### ISSUE THREAD

**Issue by Surekaraja** [highcharts/highcharts#10797] opened 2019-05-22 16:50 UTC
Need pattern and visibility of series or sets for venndiagram

As I have given pattern option it s not supporting with proper output

https://jsfiddle.net/x7gwo8s1/5/

highcharts v7

**Comment by sebastianbochan** [comment] 2019-05-23 08:28
Hi @Surekaraja,
Thank you for reporting about the problem. Could you elaborate the bug in more details ? It will allow us to understand what exactly you expect.

**Comment by TorsteinHonsi** [comment] 2019-05-24 11:01
@Surekaraja 

First of all, there's a JavaScript in your jsFiddle, `none` is not defined.

If you want patterns on your overlapping areas, here's a POC: https://jsfiddle.net/highcharts/qbwp9tx6/

**Comment by Surekaraja** [comment] 2019-06-05 06:22
Is it feasible to apply pattern with the color feature as like u have given in the pie chart? If so kindly reply with the solution as soon as possible. Kindly refer the pattern feature of pie chart.


Kind Regards,

Sureka R

BI Developer - Trainee

[cid:278315ad-b3b4-49b3-9657-47561bfac785]

Look Forward. Think Ahead.

Main: +91-9710062203
Mobile: +91-8610845038

Innovation & Services Hub<http://visualbi.com/about-us/locations/>

________________________________

**Comment by sebastianbochan** [comment] 2019-06-05 12:20
HI @Surekaraja,
Does it mean excatly the same like in the thread https://github.com/highcharts/highcharts/issues/10889 ?

If yes, ploease post a mockup how it should be draw.

**Comment by sebastianbochan** [comment] 2019-06-07 09:40
Duplicate of https://github.com/highcharts/highcharts/issues/10889

**Closed by sebastianbochan** 2019-06-07 09:40 UTC
Labels: Type: Question
