### ISSUE TITLE
Chart does not restore display:none of container in Edge

### ISSUE THREAD

**Issue by JllyGrnGiant** [highcharts/highcharts#6889] opened 2017-06-21 18:21 UTC
#### Expected behaviour
Chart stays invisible

#### Actual behaviour
Chart is visible despite display:none style on parent

#### Live demo with steps to reproduce
1. Open the following JSFiddle in Edge
http://jsfiddle.net/8vs0oazq/1/

#### Affected browser(s)
- IE11
- Edge

Note: Does not repro in Chrome, Firefox.

**Comment by JllyGrnGiant** [comment] 2017-06-21 20:23
Style of parent seems to change to block after a call to chart.temporaryDisplay() and doesn't revert.

**Comment by JllyGrnGiant** [comment] 2017-06-21 20:29
Issue appears to have been introduced in v5.0.11 as it does not repro in v5.0.12.

**Comment by KacperMadej** [comment] 2017-06-22 09:23
Hi,

Thank you for reporting about the problem. The issue is already resolved on master github branch - next release candidate. Demo: http://jsfiddle.net/8vs0oazq/2/

Duplicate of #6803

**Closed by KacperMadej** 2017-06-22 09:23 UTC
