### ISSUE TITLE
Scatter 3d points are misplaced

### ISSUE THREAD

**Issue by morganfree** [highcharts/highcharts#6972] opened 2017-07-17 11:29 UTC
#### Actual behaviour
Points in scatter3d are incorrectly placed on a chart.

#### Live demo with steps to reproduce
http://jsfiddle.net/10177f8L/
y values  are 99.8, but the points are placed under 99.5. Also, the line exceeds the plot area.

**Comment by TorsteinHonsi** [comment] 2017-07-24 08:52
@pawelfus any idea?

**Comment by pawelfus** [comment] 2017-07-24 10:12
It's a regression after 6f84253 (version 5.0.10 is fine).

In DOM we can see `translate(100, 100)` is added twice for scatter series, but only once in v5.0.10. I guess it's caused by this wrap: https://github.com/highcharts/highcharts/commit/6f84253#diff-03f80dd5d89910b0ba3ef805f2c8ff6bR118 - 'main group' for columns is the same group as for all of the series.

@Izothep

**Comment by Izothep** [comment] 2017-08-23 11:19
It looks that the issue with 'point-translate' is solved by 36747fa 

example: 
http://jsfiddle.net/10177f8L/2/

**Comment by KacperMadej** [comment] 2018-10-08 13:28
Works fine in version 6.1.4
Closing as resolved

**Closed by KacperMadej** 2018-10-08 13:28 UTC
Labels: Regression
