### ISSUE TITLE
AngularJs Dynamic creating charts style undefined

### ISSUE THREAD

**Issue by raff77** [highcharts/highcharts#2138] opened 2013-08-13 15:01 UTC
Ln 341 of highstock.src.js 

Error: Uncaught TypeError: Cannot read property 'style' of undefined

Element is undefined as Highcharts is initialised before the the click up action propagated through the dom. It appears to add a mouse up action onto the document which iterates over a hash of elements, which can be undefined. A test should be added here is element is undefined or an alternative found.

Adding a one millisecond timeout to my code to fixed it but not ideal. Stopping the event bubbling did not fix it.

**Comment by jon-a-nygaard** [comment] 2016-04-26 10:58
Closing this issue due to: We are not able to reproduce it, please provide a live demo of the issue. To do this you can use [JSFiddle](https://jsfiddle.net)

Should anyone have further information on this issue, please add a comment and reopen.

**Closed by jon-a-nygaard** 2016-04-26 10:58 UTC
Labels: Cant reproduce, Pending reply
