### ISSUE TITLE
Label rotating: chart does not fit well the container

### ISSUE THREAD

**Issue by bitliner** [highcharts/highcharts#5176] opened 2016-04-01 15:04 UTC
![screen shot 2016-04-01 at 5 00 12 pm](https://cloud.githubusercontent.com/assets/1301838/14210987/ebda6276-f82b-11e5-9b43-85ed061f9975.png)
**Context** 

* column chart
* labels require big font-size (e.g. 25px)
* labels require to be rotated by 45'
* some label can be long (even 30 characters)

**Issue**

The first label on the left  is cutted. It is too long to fit the container, so part of it is not displayed.

I expect that Highcharts understands that some label is not going to fit the container, so it should reduce the size of the chart in order to make the label fit the container of the chart.

Is there any current solution for it?

A workaround would be to not rotate labels, but then - because some of them is quite long - they do not appear all on the same height of the page, but it is one higher than the closer ones, makeing the chart not good looking.

**Comment by TorsteinHonsi** [comment] 2016-04-04 08:25
Thanks for reporting!

The axis labels are supposed to get truncated and an ellipsis (...) added in this case, like you can see in this attempt at reproduction: http://jsfiddle.net/highcharts/trn3b81u/

Can you tweak my jsFiddle to demonstrate your issue?

**Comment by jon-a-nygaard** [comment] 2016-04-26 08:44
Closing this issue due to: We are not able to reproduce the issue, and it is pending reply. 
Should anyone have further information on this issue, please add a comment and reopen.

**Closed by jon-a-nygaard** 2016-04-26 08:44 UTC
Labels: Cant reproduce
