### ISSUE TITLE
startR undefined in highcharts

### ISSUE THREAD

**Issue by sachinmishra-gep** [highcharts/highcharts#12398] opened 2019-11-13 09:38 UTC
Stack Over flow Reference  : https://stackoverflow.com/questions/58833693/highchart-startr-is-undefined-under-nh-parts-pieseries-js-hparts-globals

#### Expected behaviour
If I load more than one instance of solid gauge component instance.It starts breaking.

#### Actual behaviour
All the Solid Gauge Instance should be loaded.

#### Live demo with steps to reproduce
 1. Added the multiple solid guage instance using angular components 
 2. Solid Guage does not load

#### Product version
1. Higcharts : 7.2.0

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment] 2019-11-13 11:48
Hi @sachinmishra-gep 

Thanks for reporting the issue. Could you please add **Live demo** of the issue? We will check this. Thanks!

**Comment by sachinmishra-gep** [comment] 2019-11-13 12:13
Hi @pawelfus,

if you could give me your id and quickly setup the meeting.

**Comment by pawelfus** [comment] 2019-11-13 12:17
@sachinmishra-gep - by live demo I mean demo for example in jsFiddle or stackblitz. Demo of the issue which we can actually debug, there's no need to setup any meeting.

**Comment by sachinmishra-gep** [comment] 2019-11-13 12:23
@pawelfus , I have already created those demo to stackblitz but could not able to reproduce on the same.The issue is bit weird some times it works properly sometime it gives me an error message of
i.e 
![image](https://user-images.githubusercontent.com/39190638/68763470-8659ea00-063e-11ea-82e9-85ab2ff1d17b.png)

**Comment by pawelfus** [comment] 2019-11-14 12:51
I'm sorry, but we need to understand the issue, so we can debug, fix and prepare regression tests. Without e.g. stackblitz demo, we can only guess what is wrong.

At this moment it seems something in your code, unrelated to Highcharts, is wrong, because your standalone demo works fine.

**Comment by sachinmishra-gep** [comment] 2019-11-15 08:31
Hi @pawelfus ,
Is there any way to pass that startR as a config value.I mean as Highcharts config.
Which is used in about animate function.

**Comment by pawelfus** [comment] 2019-11-15 10:11
`startR` is not used in pie series, no need to define this. It's not possible to define `startR` in Highcharts config, but a plugin can do this, for example:

```js
(function(H) {
  H.wrap(
    H.seriesTypes.pie.prototype,
    'translate',
    function (proceed) {
      proceed.apply(this, Array.prototype.slice.call(arguments, 1));

      this.points.forEach(function (point) {
        point.startR = 10;
      });
    }
})(Highcharts)
```

**Comment by sachinmishra-gep** [comment] 2019-11-15 12:13
Hi @pawelfus ,

Thanks for your feedback, could you please help me understand will this plugin work for gauge chart as well ?

~Regards

**Comment by pawelfus** [comment] 2019-11-15 14:50
Ah, my apologies, you use solid-gauge, not pie chart! In that case, use [series.radius](https://api.highcharts.com/highcharts/series.solidgauge.radius) option that sets later `startR`.

**Comment by sachinmishra-gep** [comment] 2019-11-15 15:19
Are you saying  to make below changes ?

function(H) {
  H.wrap(
    H.series.radius.prototype,
    'translate',
    function (proceed) {
      proceed.apply(this, Array.prototype.slice.call(arguments, 1));

      this.points.forEach(function (point) {
        point.startR = 10;
      });
    }
})(Highcharts)

**Comment by pawelfus** [comment] 2019-11-18 12:09
No, I mean to set in options `series.radius`, like this:
```js
Highcharts.chart('container', {
  ...
  series: [{
    radius: 100,
    data: [ ... ]
  }]
});
```

**Comment by Neelamkasle-gep** [comment] 2019-12-02 12:11
we are facing the same issue. 
https://github.com/highcharts/highcharts/issues/4182#issuecomment-128190293
had to comment out the series.center[3]. 

![image](https://user-images.githubusercontent.com/42963934/69958401-bc4a0a00-152a-11ea-9d34-707a78ec27a3.png)

**Comment by pawelfus** [comment] 2019-12-02 12:28
Hi @Neelamkasle-gep 

Thanks! So this ticket is a duplicate of #4182 and should be closed?

**Closed** 2019-12-02 14:42 UTC
Labels: Status: Can't reproduce, Status: Pending reply, Type: Duplicate

**Comment by sachinmishra-gep** [comment] 2019-12-03 09:05
Hi @PaulDalek ,

Could you please give the solution for the issue ?

**Comment by sebastianbochan** [comment] 2019-12-03 09:33
Lets stay on discussion in one topic (4182), instead of duplicate.
