### ISSUE TITLE
Voice Access A11y bug on Command Show numbers

### ISSUE THREAD

**Issue by ankita1412** [highcharts/highcharts#18807] opened 2023-04-11 13:29 UTC
#### Expected behaviour
When Voice command - Show numbers is given, Legend should show single number of each line 
#### Actual behaviour
Legend should show two numbers of each line 
Browser Edge - 
![image](https://user-images.githubusercontent.com/5310961/231177408-d979ad69-2b59-41c8-956f-ba4d712b8b91.png)

Browser chrome - 
![image](https://user-images.githubusercontent.com/5310961/231177929-59e1c357-02c0-47ac-86e9-1c25322e2433.png)

#### Live demo with steps to reproduce
https://www.highcharts.com/demo/line-basic

#### Product version

Latest on demo site
#### Affected browser(s)
Chrome, Edge

**Comment by ankita1412** [comment] 2023-08-07 06:39
Can we please have an update on this?

**Comment by oysteinmoseng** [comment] 2023-08-07 08:08
Hi @ankita1412, thanks for reporting. I don't think this is a bug with Highcharts, as the chart correctly only exposes one button for each legend item.

My suspicion is that in addition to the buttons, the SVG legend items are exposed to Voice Access. This would likely be because they have a click handler attached to them. These elements are within an `aria-hidden="true"` group, however, and should therefore be ignored.

I'm closing this as not a bug for now, as I don't think there is anything we can do from our side, but let me know if you have any additional info and I will reopen.

**Closed by oysteinmoseng** 2023-08-07 08:08 UTC
Labels: a11y
