### ISSUE TITLE
treemap

### ISSUE THREAD

**Issue by TurboAsteroid** [highcharts/highcharts#5578] opened 2016-08-10 11:14 UTC
#### Expected behaviour
Must work

#### Actual behaviour
Don`t work

#### Live demo with steps to reproduce
4.2.6 bug http://jsfiddle.net/yju6omh3/3/
4.2.5 its ok http://jsfiddle.net/yju6omh3/4/

#### Affected browser(s)
all browser(s)

**Comment by jon-a-nygaard** [comment] 2016-08-10 13:06
Duplicate of #5563. Please follow the mentioned issue number for more information and updates.

**Closed by jon-a-nygaard** 2016-08-10 13:06 UTC
