### ISSUE TITLE
Issue when using y-zoom function on multi-Axis that are on different y position

### ISSUE THREAD

**Issue by qinbx** [highcharts/highcharts#1451] opened 2013-01-14 09:06 UTC
Demo url:  http://jsfiddle.net/zM7yt/
Issue screenshot: 
![issue-yZoom](https://f.cloud.github.com/assets/836554/64049/44ddb4c2-5e29-11e2-8f15-92f8233005f1.png)

Even when i try to change the max and min by re-draw the chart.
http://jsfiddle.net/zM7yt/2/
![multi-axis-zoom](https://f.cloud.github.com/assets/836554/64055/83d55a18-5e29-11e2-818c-cf1b0af18ff1.png)

Hope to get the feedback, very thanks.

**Comment by pawelfus** [comment] 2015-06-18 12:31
Clipping issue is already fixed. Regarding zooming - I think that when you select part of the chart, then bottom axis is translating positions according to the it's position. So in the screenshot example it's around value `-100`

**Comment by KacperMadej** [comment] 2018-12-31 19:46
Remaining issues is a duplicate of #1289.
Closing as a duplicate.

**Closed by KacperMadej** 2018-12-31 19:46 UTC
