### ISSUE TITLE
Hovering over Pie chart breaks data labels' overlapping (allowOverlap)

### ISSUE THREAD

**Issue by arcdelta** [highcharts/highcharts#13983] opened 2020-08-02 13:53 UTC
#### Expected behaviour
Pie chart data labels shouldn't overlap when `allowOverlap` option is set to **false** even if you hover over a chart.

#### Actual behaviour
After initial rendering everything works just fine: some data labels are hidden (as expected). But when you hover over the chart, initially hidden data labels show up overlapped and stay like that.

#### Live demo with steps to reproduce
https://jsfiddle.net/exzrdsub/ — Simply hover over the chart. Note that the `distance` is set to **-40%**.

#### Product version
Highcharts JS v8.1.1 (2020-06-09)

#### Affected browser(s)
Chrome 84.0.4147.105 (macOS)

**Comment by sebastianbochan** [comment] 2020-08-03 08:53
Hi @arcdelta,
Thank you for reporting. The issue has been already reported.

Im closing as duplicate of https://github.com/highcharts/highcharts/issues/13846

**Closed by sebastianbochan** 2020-08-03 08:53 UTC
