### ISSUE TITLE
Dependency breaks when navigator + xAxis(min-max) applied

### ISSUE THREAD

**Issue by AnanditaP** [highcharts/highcharts#14231] opened 2020-09-15 15:44 UTC
#### Expected behaviour
Dependecy should be shown between 'third' and 'fourth' when navigator + xAxis(min-max) applied.

#### Actual behaviour
Not showing dependency between 'third' and 'fourth' because navigation and xAxis(min-max) applied. It shows dependency If navigator and xAxis(min-max) removed.

#### Live demo with steps to reproduce

Please run this below code -

Highcharts.ganttChart('container', {
    chart: {
        type: 'gantt'
    },

    xAxis: {
       
        min: Date.UTC(2014, 11, 8),
        max: Date.UTC(2014, 11, 14)
    },
 navigator: {
 	enabled: true
 },
 
 
    series: [{
        name: 'Project 1',
        data: [{
            start: Date.UTC(2014, 11, 1),
            end: Date.UTC(2014, 11, 2),
            name: 'first',
             id: 'id_first'
        }, {
            start: Date.UTC(2014, 11, 2),
            end: Date.UTC(2014, 11, 5),
            dependency: 'id_first',
            name: 'second',
            id: 'id_second',
            
        }, {
            start: Date.UTC(2014, 11, 7),
            end: Date.UTC(2014, 11, 9),
            dependency: 'id_second',
            name: 'third',
            id: 'id_third'
        }, {
            start: Date.UTC(2014, 11, 9),
            end: Date.UTC(2014, 11, 19),
            dependency: 'id_third',
        		name: 'fourth',
        
        }]
    }]
});

#### Product version
Gantt - 8.0,4

**Comment by PaulDalek** [comment] 2020-09-16 10:23
Hi @AnanditaP

Thank you for reporting this. The issue has already been reported.

Closing as a duplicate of the #12691.

**Closed by PaulDalek** 2020-09-16 10:23 UTC
