### ISSUE TITLE
nodeName property in highcharts.js gives error saying undefined is not an object

### ISSUE THREAD

**Issue by mayankm1911** [highcharts/highcharts#18233] opened 2023-01-03 11:16 UTC
TypeError: undefined is not an object (evaluating 'o.nodeName') (Most recent call first)

File webpack://cht-app-mdr/./node_modules/highcharts/highcharts.js:80:18 in [anonymous]
else if("text"===d.nodeName.toLowerCase()&&b.width)var a=this.textWidth=K(b.width);this.styles=b;...
File webpack://cht-app-mdr/./node_modules/highcharts/highcharts.js:359:424 in [anonymous]
(g?"point":"series")+"-active",k=d.chart.styledMode,h=function(a){d.allItems.forEach(function(c){...

**Comment by pawellysy** [comment] 2023-01-03 12:52
Hi @mayankm1911, thanks for reaching out to us.
Could share the chart configuration and the live demo, where the issue is reproduced? Thanks!

**Comment by pawellysy** [comment] 2023-01-25 11:23
Closing - No reproduction steps

**Closed by pawellysy** 2023-01-25 11:23 UTC
Labels: Status: Can't reproduce, Status: Pending reply
