### ISSUE TITLE
Cannot read property 'chart' of undefined

### ISSUE THREAD

**Issue by Hsinglin** [highcharts/highcharts#2231] opened 2013-09-05 15:30 UTC
when I use hightcharts to render my charts , I found it ofen get error like this:
````
Uncaught TypeError: Cannot read property 'chart' of undefined 
````
I make a breakpoint in it, I found in line 11250.
````
	var chart = this;
	var optionsChart = chart.options.chart;
````
I console the chart , it was undefined.
it happen a lots , when it has more than 3 chart in a page, i would be very frequently.

I try the lastst version , but it didnot help. 

when its ok:
![ok](http://ww1.sinaimg.cn/large/6f21d28cgw1e8c1gtw3r8j20g2055t9o.jpg)
when its wrong:
![error](http://ww3.sinaimg.cn/large/6f21d28cgw1e8c1fvnfe3j20fw04xt9e.jpg)

**Comment by jon-a-nygaard** [comment] 2016-04-26 10:07
Closing this issue due to: We are not able to reproduce the issue, please provide a live demo which showcases the issue. To do this you can use for instance [JSFiddle](jsfiddle.net).

Should anyone have further information on this issue, please add a comment and reopen.

**Closed by jon-a-nygaard** 2016-04-26 10:07 UTC
Labels: Cant reproduce

**Comment by machindra-rithe** [comment] 2017-05-08 05:49
This issue is reproduced on page resize.
If page contains single or multiple graphs and we resize page by changing width or height or resize page by zoom in or zoom out.

**Comment by pawelfus** [comment] 2017-05-08 09:13
Hi @machindra-rithe 

Could you recreate issue in jsfiddle? For me it works fine: http://jsfiddle.net/vysgfza2/
