### ISSUE TITLE
OBV indicator not finding the volumeSeriesID

### ISSUE THREAD

**Issue by youneskacel** [highcharts/highcharts#18409] opened 2023-01-31 13:10 UTC
#### Expected behaviour
adding the OBV indicator serie to options and specify the OHLC data and volume data in params , and have it plotted

#### Actual behaviour

Uncaught Error: Series volume not found! Check `volumeSeriesID`.

but the volume series id is correct and identical 
the others volume based indicators are working just fine such as VBP , but obv is throwing this error

#### Product version
Highcharts @10.3.3

**Comment by bm64** [comment] 2023-01-31 13:58
Hello @youneskacel.

Please recreate the issue in this demo: https://jsfiddle.net/BlackLabel/Lr9qyfp1/

**Comment by youneskacel** [comment] 2023-01-31 16:38
hello , thanks for answering 
so i recreated it here in :
https://jsfiddle.net/e2u8g4pn/
but it's working just fine in the jsfiddle
forgot to mention that i am using react 16.8.6 with highcharts-react-official 3.0.0

**Comment by bm64** [comment] 2023-02-01 10:07
Unfortunately without the reproduction of the issue we won't be able to do anything about that. Please visit one of our support channels and our developers will help you with finding what is the cause of the issue: https://www.highcharts.com/blog/support/. Until then I have to close this ticket.

**Closed by bm64** 2023-02-01 10:07 UTC
Labels: Status: Pending reply

**Comment by saeed-asghari** [comment] 2024-12-28 08:56
HI 
"volumeSeriesID: 'Volume' should be written with a lowercase 'v'."
