### ISSUE TITLE
Positive and Negative Non-Column type Series does not stack properly

### ISSUE THREAD

**Issue by simPod** [highcharts/highcharts#7195] opened 2017-09-27 10:31 UTC
#### Expected behaviour

Chart should stack when both negative and positive series are present. I expect it to stack like this http://jsfiddle.net/sx2cku4e/ (but this example works only with positive or negative values

#### Actual behaviour

Chart does not stack and Y values are somehow shifted on Y axis

#### Live demo with steps to reproduce

http://jsfiddle.net/59je3p2q/

Am I doing something wrong?

**Comment by simPod** [comment] 2017-09-27 10:51
It works properly when using column type chart http://jsfiddle.net/59je3p2q/1/ 🤔

**Comment by sebastianbochan** [comment] 2017-09-28 14:35
Duplicate of https://github.com/highcharts/highcharts/issues/5671

**Closed by sebastianbochan** 2017-09-28 14:35 UTC

**Comment by simPod** [comment] 2017-09-29 12:35
Thanks, @TorsteinHonsi's fiddle http://jsfiddle.net/highcharts/0o61t9cr/4/ solves it

**Comment by simPod** [comment] 2017-10-16 19:58
Ok not really, continuing in the thread
