### ISSUE TITLE
Column chart not working correctly when boost is enabled

### ISSUE THREAD

**Issue by rdp1414** [highcharts/highcharts#16698] opened 2021-11-24 07:19 UTC
#### Expected behaviour
With boost enabled, plotting greater than or equal to 50 column series, should render correctly i.e. columns shouldn't be extremely thin.

#### Actual behaviour
1. Plotting 49 column series works correctly.
2. But plotting greater than or equal to 50 column series, makes the columns extremely thin.
3. This problem happens only when [boost.enabled](https://api.highcharts.com/highcharts/boost.enabled) is `true`.

#### Live demo with steps to reproduce
Reproducer of above bug - See [fiddle](https://jsfiddle.net/ktfgdh5q/1/).

#### Product version
Highcharts version `9.1.2`

#### Affected browser(s)
Chrome

**Comment by KacperMadej** [comment] 2021-11-24 17:25
Hi @rdp1414 

Thank you for reporting the problem.

This is a known limitation.

> The largest caveat is that rectangles for column and bar charts are always drawn as a single 1 pixel wide line.
https://www.highcharts.com/docs/advanced-chart-features/boost-module#caveats

Closing as not a bug.

**Closed** 2021-11-24 17:25 UTC
Labels: Type: Not a bug
