### ISSUE TITLE
Stock Tools Full Screen module with multiple charts on the same page

### ISSUE THREAD

**Issue by laventnc** [highcharts/highcharts#11708] opened 2019-08-18 19:44 UTC
#### Expected behaviour
With multiple charts on the same page, full screen should only affect the chart bound by navigation.bindingsClassName (as is the case with other Stock Tools). This is a huge performance issue and basically renders the module unusable when dealing with multiple charts and large amounts of data on each.

#### Actual behaviour
When Full Screen on any chart gets triggered, every chart on the page gets redrawn. Worth mentioning that I didn't notice this issue until recently when I upgraded to 7.1.3, although I wasn't utilizing it on a page with this many charts until now.

#### Live demo with steps to reproduce
https://jsfiddle.net/nlaventis/vthqr5z4/6/
- Open the console and trigger full screen, you will notice that redraw is fired for the other two charts.

#### Product version
Highstock 7.1.3

#### Affected browser(s)
Chrome, Firefox, Edge

**Comment by sebastianbochan** [comment] 2019-08-19 13:24
Hi @laventnc,
Thank you for contacting us. By default the javascript "full screen" function resizes all divs / elements width to current view-port. 

Lets analyze non-highcharts demo:
- https://jsfiddle.net/BlackLabel/83ye5tfd/

When you click on full screen and verify size of divs, all of are resized.

In the Highcharts, when div is resized, the redraw event is called.

Im closing this issue as not a bug, due to default javascript functionality.

**Comment by laventnc** [comment] 2019-08-19 14:51
Ah that makes sense, sorry for the misunderstanding. Do you have any recommendations for how I would handle this though ? I know I could spoof the full screen by creating a modal window, however I really like the native full screen mode. I think I'm looking for something more along the lines of only resizing the targeted div/element.

Also, just to clarify I was under the impression that [highcharts does not trigger a reflow when the container changes size](https://www.highcharts.com/forum/viewtopic.php?t=9455).

**Comment by sebastianbochan** [comment] 2019-08-20 10:41
Hi @laventnc,
I find a really limited workaround which disables the setSize method by default and run only when fullscreen is activated. One of the biggest disadvantages is that it does not support reposonsive design.

Demo:
- https://jsfiddle.net/BlackLabel/k7gn60j9/

At this moment its only what comes to my mind.

**Closed by sebastianbochan** 2019-08-20 10:41 UTC
Labels: Status: Pending reply

**Comment by laventnc** [comment] 2019-08-21 13:44
I appreciate the insight... Is there any plan to address this in the future? Because on a site with many charts on the same page (where the full screen mode is most necessary), having to wait for each chart to redraw make this functionality borderline unusable.

**Comment by pawelfus** [comment] 2019-08-22 15:22
Just a word of explanation:
> I was under the impression that highcharts does not trigger a reflow when the container changes size.

That is correct. I think @sebastianbochan wnated to say that when `window.resize` event is fired, we reflow charts. We probably won't listen on container's resize until ResizeObserver will be supported, see this comment (with workaround): https://github.com/highcharts/highcharts/issues/6427#issuecomment-438212322

Alternatives:

1.
One possible solution you can implement at this moment (using official API) is to disable reflow in general, then attach your own `window.resize` event where you can check if browser is in full screen mode. Then determine which charts should reflow, for example: https://jsfiddle.net/BlackLabel/0g8r6k9z/ (tested for Chrome only, there are different `_something_IsFullScreen` flags for other browsers).

Snippet:
```js
Highcharts.addEvent(
  window,
  'resize',
  (e) => {
    Highcharts.charts.forEach(
      chart => {
        if (
          // Make sure chart wasn't destroyed
          chart &&
          (
            // In non-fullscreen mode, reflow all charts
            !document.webkitIsFullScreen ||
            // In full screen mode, reflow only current chart
            chart.renderTo === document.webkitFullscreenElement
          )
        ) {
          chart.reflow();
        }
      }
    );
  }
);
```

To disable reflow for a chart, set [`chart.reflow`](https://api.highcharts.com/highcharts/chart.reflow) flag to false.

2. 
Another alternative (that I think could be implemented in the FullScreen plugin) is to prevent every chart from reflowing when anything (literally anything, not necessary a chart) else is rendered in fullscreen. To improve overall performance we won't reflow charts in this case even when window resize event is fired (e.g. mobile's orientation change). We will only reflow charts when exiting the fullscreen mode.
Demo: https://jsfiddle.net/BlackLabel/90yr65ag/

Plugin:
```js
(function(H) {
  H.wrap(
    H.Chart.prototype,
    'reflow',
    function(proceed) {
      if (
        // In non-fullscreen mode, reflow all charts
        !document.webkitIsFullScreen ||
        // In full screen mode, reflow only current chart
        this.renderTo === document.webkitFullscreenElement
      ) {
        proceed.apply(this, Array.prototype.slice.call(arguments, 1));
      }
    }
  );
})(Highcharts);
```

*Internal note:*
@sebastianbochan - how about adding this functionality to the FullScreen module? Something like my second solution?

**Comment by laventnc** [comment] 2020-06-11 20:25
is there any plan to integrate this into the full screen module?

**Comment by raf18seb** [comment] 2020-06-12 08:20
Hi @laventnc, I will consider this next week and share more info.
