### ISSUE TITLE
Tooltip overflows out of viewport with `useHTML` and `outside` set to true

### ISSUE THREAD

**Issue by troyvassalotti** [highcharts/highcharts#21158] opened 2024-05-13 19:16 UTC
#### Expected behaviour

The tooltip box remains in view of the chart at all data points.

#### Actual behaviour

Tooltip inconsistently overflows out of the viewport. It seems like this is most common if you trigger the tooltip open from one of the far-right data points. If you trigger the tooltip on a series from the left and move one-by-one to the right, the tooltip won't overflow. It only happens if the tooltip first opens at a data point near the edge of the screen.

![image](https://github.com/highcharts/highcharts/assets/45142012/b0f5db7e-04d5-4942-b3e1-6da4ec594dc1)

#### Live demo with steps to reproduce

https://codepen.io/troyvassalotti/pen/gOJpYWd

#### Product version

Highcharts, Highstock, ^11.4.1

#### Affected browser(s)

Firefox, Chrome, Safari

**Comment by karolkolodziej** [comment] 2024-05-14 09:44
Hi @troyvassalotti! 

Please take a look at the `outside` [API documentation.](https://api.highcharts.com/highcharts/tooltip.outside)
> When true, a separate SVG element is created and overlaid on the page, allowing the tooltip to be aligned inside the page itself.

This is this option's primary purpose and is a desired behaviour. 
I am closing it as not a bug.

**Closed by karolkolodziej** 2024-05-14 09:44 UTC

**Comment by ItaiYosephi** [comment] 2024-05-30 16:17
@karolkolodziej Recently updated from version 9.3.3 to 11.4.3 and and started having this issue too.
It would be nice if `outside` tooltip will still be limited to be inside the viewport..
But if you're not planning on solving it, is there a way to get the final position in the `positoner()` option and act accordingly when that happens?
`tooltip.getPosition()` doesn't always return the position that actually used to show the tooltip...

**Comment by ItaiYosephi** [comment] 2024-05-30 16:28
checked version 10.3.3, seems it was working fine.
this issue started in version 11.0.0. might be related to on of these:
https://github.com/highcharts/highcharts/issues/18635
https://github.com/highcharts/highcharts/issues/17720

**Comment by karolkolodziej** [comment] 2024-05-31 08:01
@ItaiYosephi let's talk about it in the issue you've just created.
