### ISSUE TITLE
Chart is wrong size when container is scaled

### ISSUE THREAD

**Issue by dinubs** [highcharts/highcharts#10782] opened 2019-05-21 18:19 UTC
#### Expected behaviour
Chart is same width as it's container when no width is specified in the configuration.

#### Actual behaviour
Chart is the wrong width. As you can see below it should be the same width as where the border is, but it's half-width (since I scaled to 0.5, would be 30% if I scaled to 0.3). The really odd thing is that the height is correct, so something weird is happening with only width.

![image](https://user-images.githubusercontent.com/2745145/58120361-f0c32d80-7bb9-11e9-8d6d-28f42d34c72e.png)

#### Live demo with steps to reproduce

https://jsfiddle.net/5nrf1k78/

#### Product version

Highcharts 7.1.1

#### Affected browser(s)
Confirmed in Chrome, and Firefox

**Comment by sebastianbochan** [comment] 2019-05-22 08:16
Hi @dinubs,
Thank you for reporting about the bug. Could you update your jsfiddle with chart's code because seems to be missing.

**Comment by dinubs** [comment] 2019-05-22 17:55
Sorry about that, it didn't seem to save. Here's an updated one https://jsfiddle.net/5nrf1k78/

**Comment by sebastianbochan** [comment] 2019-05-23 14:12
Hi @dinubs,
Thank you for the demo.

**Workaround**
Set the width by the `chart.width` option.

_Internal note_
It looks like similar issue like here: https://github.com/highcharts/highcharts/issues/9871.

**Comment by Basts** [comment] 2019-05-30 15:55
@sebastianbochan user from forum noticed that this could be a regression. On 5.0.14 version chart is rendering properly. 

[Demo in 5.0.14 version](https://jsfiddle.net/g9483zpn//2)
[Demo in 7.1.1 version](https://jsfiddle.net/aLoydvz2/6/)

**Comment by lukeokane** [comment] 2019-06-04 11:02
Hi there,

I am the user from the forum that @Basts has mentioned. The `chart.width` option workaround appears to work with charts with only one yAxis. If there is more than one then the problem persists. 

[Example fiddle using the 'SMA volume by price' demo](https://jsfiddle.net/5kxsmpg0/1/)

**Comment by pawelfus** [comment] 2019-06-14 08:37
Closing as duplicate of #10498

**Closed by pawelfus** 2019-06-14 08:37 UTC
Labels: Type: Bug
