### ISSUE TITLE
Series with Id not updated correctly when oneToOne is true

### ISSUE THREAD

**Issue by LoganDupont** [highcharts/highcharts#9606] opened 2018-12-05 10:54 UTC
#### Expected behaviour
From what I understand and found in the documentation (https://api.highcharts.com/class-reference/Highcharts.Chart#update) about oneToOne the new series options will be matched by id, and the remaining ones removed.

The serie id 'John' shouldn't inherit the settings from serie 'avg' because I added an Id to both series.
#### Actual behaviour
The serie id 'John' inherit the settings from serie 'avg' like showInLegend and dataLabels.

#### Live demo with steps to reproduce
1) Click Remove John (wait 3sec)
2) Click Add John (wait 3sec)
You will see that serie with Id 'john' takes the showInLegend and dataLabels from serie 'avg'.
https://codepen.io/anon/pen/xQNmNb

#### Product version
Highcharts JS v6.2.0

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment] 2018-12-06 14:15
Thanks for reporting, this looks like a bug. 

Simplified demo: http://jsfiddle.net/highcharts/LLExL/13533/

**Comment by njifares** [comment] 2020-02-20 09:39
Any updates on this?

**Comment by pawelfus** [comment] 2020-02-20 11:47
Hi @njifares - no updates at this moment, we haven't had time to prioritise this issue.

**Comment by TorsteinHonsi** [comment] 2020-05-28 11:03
Duplicate of #13541 (or actually the other way around :)

**Closed by TorsteinHonsi** 2020-05-28 11:03 UTC
Labels: Type: Bug
