### ISSUE TITLE
xAxis.min and xAxis.max is not respected when URL changes via history.pushState

### ISSUE THREAD

**Issue by Oersnes** [highcharts/highcharts#12848] opened 2020-01-24 13:25 UTC
#### Expected behaviour
I am expecting the chart to only display the part of the series that is within the specified extremes (xAxis.min and xAxis.max). 
<img width="1269" alt="Skærmbillede 2020-01-24 kl  13 56 43" src="https://user-images.githubusercontent.com/60260606/73071618-86cef680-3eb3-11ea-8001-b9b1bcd7f620.png">

#### Actual behaviour
After URL update via history.pushState the series is re-rendered, but the series overflows the plotarea now.
<img width="1274" alt="Skærmbillede 2020-01-24 kl  13 57 02" src="https://user-images.githubusercontent.com/60260606/73071797-fe9d2100-3eb3-11ea-84b6-0b96ab708c50.png">

#### Live demo with steps to reproduce

https://stackblitz.com/edit/react-stghr9?file=index.js

#### Product version
Highcharts 8.0.0

#### Affected browser(s)
Seen in newest version of Chrome.

**Comment by pawelfus** [comment] 2020-01-27 11:49
Thanks for reporting this issue @Oersnes - this is actually a duplicate of #5244.

Closing as duplicate of #5244

**Closed by pawelfus** 2020-01-27 11:49 UTC

**Comment by Oersnes** [comment] 2020-01-27 12:15
Thank you so much @pawelfus :)
