### ISSUE TITLE
Data Grouping Turns off when you add a polygon series and custom dataGrouping units are applied

### ISSUE THREAD

**Issue by f1ghtingfalcons** [highcharts/highcharts#9693] opened 2018-12-17 16:29 UTC
#### Expected behaviour
Data grouping on line series should be enabled unless disabled in options.

#### Actual behaviour
When using custom dataGrouping units, adding a polygon in addition to a line series will disable the dataGrouping for the line series.

#### Live demo with steps to reproduce
https://jsfiddle.net/f1ghtingfalcons/ts47n6kh/26/

1) Just click the 'add polygon' button. The line series will redraw without dataGrouping.

#### Product version
Highstock JS v7.0.0 (2018-12-11)
Highcharts-more module JS v7.0.0 (2018-12-11)

#### Affected browser(s)
All

**Comment by KacperMadej** [comment] 2018-12-18 20:00
Hi @f1ghtingfalcons 

Thank you for reporting about the problem.
This is caused by setting `dataGrouping` options for all series while not all series has other default `dataGrouping` options. This could be resolved through adding those options (see second demo below), but I'm unable to find any documentation that would explain this and I think we can hardly expect users to guess this. IMO this should be resolved internally in Highstock code, so I'll label this issue as a bug.

**Workaround:** 
Set `dataGrouping` to `false` for the `polygon` series. 
Demo: https://jsfiddle.net/BlackLabel/xm65vL3d/

Or set `groupPixelWidth` in `plotOptions.series.dataGrouping`.
Demo: https://jsfiddle.net/BlackLabel/xm65vL3d/1/


_Internal note:_
Lack of default `dataGrouping` options forces `NaN` as `groupPixelWidth` in `Axis.prototype.getGroupPixelWidth`.

```js
		    while (i--) {
		        dgOptions = series[i].options.dataGrouping;
		        if (dgOptions) {
		            groupPixelWidth = Math.max(
		                groupPixelWidth,
		                dgOptions.groupPixelWidth
		            );

		        }
		    }
```
`dgOptions` exist for `polygon` or any series because of used `plotOptions.series.dataGrouping`, but `dgOptions.groupPixelWidth` is `undefined`, so `groupPixelWidth` becomes `NaN`.

Default `polygon` series [`groupPixelWidth`](https://api.highcharts.com/highstock/plotOptions.polygon.dataGrouping.groupPixelWidth) is wrong - I'll try to prepare a fix will make this option right in API docs and resolve the problem.

**Comment by KacperMadej** [comment] 2018-12-18 23:47
There's still (after above commit) a problem.
Please help decide a solution @TorsteinHonsi 

`dataGrouping` should be disabled for series like `scatter`, `polygon`, `bubble` through chart options in case any options of `dataGrouping` are set for `plotOptions.series`, but if a user doesn't do that:

1. A Highcharts error instead of fatal JS error would be nice. A user will get a clue in case something is off with his chart.

2. Use default values for missing options - that would match API info about all series having `dataGrouping.enabled: true`, but could lead to a strangely grouped scatter-like series.

3. Both (1 + 2) - make it work and provide info in console (or in a chart through debugger module)

**Comment by pawelfus** [comment] 2018-12-27 12:14
Wouldn't be a good idea to inherit options:
- `plotOptions.series.something` ->
- `plotOptions.<series-type>.something` ->
- `series.something`

instead of:
- `plotOptions.<series-type>.something` ->
- `plotOptions.series.something`  ->
- `series.something`

Just as described in #3881 - at this moment it's counterintuitive.

**Comment by KacperMadej** [comment] 2018-12-28 18:55
@pawelfus If the `something` is `dataGrouping` (plus another condition`*`) then specific plotOptions have higher priority over `plotOptions.series`:

https://github.com/highcharts/highcharts/blob/1a37c045270770251ac68b963614ebcca9b0f5d8/js/parts/DataGrouping.js#L923-L929

----------------------------
`*` the condition being: series type has defined [`specificOptions`](https://github.com/highcharts/highcharts/blob/1a37c045270770251ac68b963614ebcca9b0f5d8/js/parts/DataGrouping.js#L309-L336) or series has `useCommonDataGrouping` set to `true`.

**Closed** 2019-01-03 10:22 UTC
Labels: Bug, Highstock, In progress
