### ISSUE TITLE
Gantt: axis labels not visible on fast scrolling - axis scrollbar.

### ISSUE THREAD

**Issue by GerasimovDmitry** [highcharts/highcharts#15505] opened 2021-04-14 13:09 UTC
#### Expected behaviour
The entire chart is displayed while scrolling

#### Actual behaviour
Not all yAxis labels are displayed while scrolling fast

#### Live demo with steps to reproduce
template: https://jsfiddle.net/BlackLabel/L78mkans/

#### Product version
9.0.1

#### Affected browser(s)
All

**Comment by KacperMadej** [comment] 2021-04-19 10:41
Hi @GerasimovDmitry 

Thank you for reporting the problem.

I am unable to recreate the issue - if you zoom to the point position then all are visible. Some points are very small, so are not visible without a big zoom and precise scroll. To force visibility for small points you could use [`minPointLength`](https://api.highcharts.com/gantt/series.gantt.minPointLength).

Please add steps required to recreate the problem and/or more info about the problem.

**Comment by GerasimovDmitry** [comment] 2021-04-19 10:52
Hi @KacperMadej . Points are visible but labels are not rendering.
Step to reproduce.
1. Use my template
2. Scrolling fast
ER : All labels are rendering
AR: Not all labels are rendering
If you scroll slowly, then all labels will have time to draw.
![image](https://user-images.githubusercontent.com/44848842/115224776-5873b180-a11e-11eb-9542-d69161ff9549.png)

**Comment by KacperMadej** [comment] 2021-04-21 08:00
Axis labels are not visible when scrolling fast using the axis' scrollbar.

Alternative, although not a perfect solution for every case, could be to use scrollable plot are - details in https://github.com/highcharts/highcharts/issues/9378

**Comment by KacperMadej** [comment] 2021-04-21 08:04
Duplicate of https://github.com/highcharts/highcharts/issues/15453

**Closed by KacperMadej** 2021-04-21 08:04 UTC
Labels: Product: Highcharts Gantt, Type: Bug
