### ISSUE TITLE
Typescript definitions are not in sync.

### ISSUE THREAD

**Issue by annitya** [highcharts/highcharts#16236] opened 2021-08-20 16:21 UTC
#### Expected behaviour

Typescript-definitions are accurate.

![image](https://user-images.githubusercontent.com/727305/130263741-a6a9faad-b7c4-4bb3-aa17-af291ed72559.png)

#### Actual behaviour

They seem to be outdated.

![image](https://user-images.githubusercontent.com/727305/130263785-6645c017-b3a1-469a-9574-df8f4abd4cad.png)

#### Product version
9.2.1

**Comment by KacperMadej** [comment] 2021-08-23 15:25
Hi @annitya 

Please provide more info: demos, links, path for the properties in question, etc.

The definitions used within the repository's .ts code are not the same as the public API in release's .d.ts files, so if there are differences between those two then it's usually by design.

**Comment by annitya** [comment] 2021-08-23 15:51
The issue is that the released typescript-definitions does not match the API. To reproduce simply create a plotband and log "this" on clicke like [so](https://jsfiddle.net/k0yox3r5/1/). On line 120136 in the released highcharts.d.ts (please split up the definitions btw, my laptop has a fit every time I open the file), the type clearly specifies svgElem contrary to the TypeScript definition that says svgElement.

**Comment by KacperMadej** [comment] 2021-08-24 12:05
Thank you for the details.

This is a bug in docs - the name in the comment is wrong.
https://github.com/highcharts/highcharts/blob/fa929aa0273dea30e3ae9464c4fc4a71469a136a/ts/Core/Axis/PlotLineOrBand/PlotLineOrBand.ts#L204-L210

**Comment by annitya** [comment] 2021-08-24 12:21
Thanks for your quick replies! Whatever it is, I need to litter my code with ts-ignores now:
![image](https://user-images.githubusercontent.com/727305/130615419-b059265d-e156-4c3e-9c36-e06b37e6e761.png)

**Comment by olejorgenb** [comment] 2021-09-07 14:59
Not sure my issue is the same, but I observe that a number of properties are missing in the typedefinitions (I'm converting a JS project to TS). At first I thought that I was accessing private members, but when I look in the HC source code they're marked as public.

Examples:
`Highcharts.Chart.plotSizeY/X` (ts/Core/Chart/Chart.ts)
`Highcharts.Axis.plotLinesAndBands` (ts/Core/Axis/Axis.ts`)

Highcharts 9.2.2

**Comment by KacperMadej** [comment] 2021-09-08 14:28
Public or not in TS doesn't translate to being a part of API or not. For a property to be a part of public API it has to have a proper JSDoc comment like legend below:

https://github.com/highcharts/highcharts/blob/a6e375c7fa92fd8c816e648dc9f3106da1b2f260/ts/Core/Chart/Chart.ts#L2406-L2412

If there is a need for a prop to be a part of public API please open a new issue with a reason why it should be added. The public API is intended for general usage and not for extending Highcharts functionality, so not all properties are a part of public API.

**Comment by olejorgenb** [comment] 2021-09-08 14:44
Thanks - I guess I kinda highjacked this thread :flushed: (I've simply extended the interfaces (using the namespace mechanism) with the properties we need for now :))

**Comment by temka1234** [comment] 2021-09-13 22:27
What kind of properties can be public?  
Any custom module needs a lot of pirvate API properties.  

For example:
- Extend step line series to start and end of chart area without extra points. `Series.group` `Series.xData` `Series.yData`
- Render label for `first|last|mid` line series point on axis near ticks labels (also if series rendered outside viewport). `Series.opposite` `Series.color` `Series.colorIndex` `Axis.labelGroup` `Axis.linkedParent` `Axis.offset` `Axis.left` `Axis.width`

At this time i use `declare module` way to expose internal API.

**Comment by KacperMadej** [comment] 2021-09-14 15:21
> What kind of properties can be public?

All of them if there is a good enough reason and there is no better option of getting something done in an easier way.

I realize the issue topic is very general, but let's try to keep this issue for the identified problem (Highcharts.PlotLineOrBand#svgElement) and use available support channels for general questions - https://www.highcharts.com/blog/support/

**Closed** 2022-09-21 09:27 UTC
Labels: Type: Bug, Product: Docs, Type: Good for beginners
