### ISSUE TITLE
typo on Japan mapdata

### ISSUE THREAD

**Issue by ferrolive** [highcharts/highcharts#15844] opened 2021-06-05 13:34 UTC
#### Expected behaviour
On file https://code.highcharts.com/mapdata/countries/jp/jp-all.js , the correct prefecture name is "Hyōgo".

#### Actual behaviour
Currently it's showing "Hy?go".

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/jp/jp-all

#### Affected browser(s)
All

**Comment by raf18seb** [comment] 2021-06-14 12:53
Hi @ferrolive 

Closing as a duplicate of https://github.com/highcharts/map-collection-dist/issues/32

For the future, please use our map collection repo for reporting this kind of bugs :) https://github.com/highcharts/map-collection-dist/issues

**Closed by raf18seb** 2021-06-14 12:53 UTC
