### ISSUE TITLE
Cannot read vcEvents of null in highcharts.js 26

### ISSUE THREAD

**Issue by YeZhiqiuSev** [highcharts/highcharts#5386] opened 2016-06-07 07:52 UTC
I find it on [http://forum.highcharts.com/highcharts-usage/cannot-read-vcevents-of-null-in-highcharts-js-26-t35630/](http://forum.highcharts.com/highcharts-usage/cannot-read-vcevents-of-null-in-highcharts-js-26-t35630/),but it doesn't make any sence.

**Comment by pawelfus** [comment] 2016-06-07 09:38
The issue posted there was caused by requiring Highcharts multiple times. Highcharts library should be included only once. If you have exactly the same issue, then make sure you load Highcharts only once. If not, please recreate issue on jsFiddle, we will check this. Thanks!

**Comment by jon-a-nygaard** [comment] 2016-06-30 06:29
Closing this since we can not reproduce the issue, and it is pending a reply. Should anyone have further information about the issue, please comment and reopen.

**Closed by jon-a-nygaard** 2016-06-30 06:29 UTC
Labels: Cant reproduce, Pending reply
