### ISSUE TITLE
highcharts dashStyle option issues

### ISSUE THREAD

**Issue by ManeshM** [highcharts/highcharts#7701] opened 2018-01-20 04:44 UTC
I am using highcharts line chart. When we are trying to load data of some size (<mention size here>) then though the line shows up, we are not able to change the line to (dashStyle: 'dot'). Can you please let us know what might be wrong?

http://jsfiddle.net/btb5k54p/1/

**Comment by pawelfus** [comment] 2018-01-22 10:39
Hi @ManeshM 

Your demo looks fine. Could you specify what exactly is wrong?

**Comment by ManeshM** [comment] 2018-01-23 11:49
when cropTheshold is set to Infinity and boostThreshold is set to 100000 then we see the issue of dotted lines not showing up?

**Comment by pawelfus** [comment] 2018-01-23 12:11
Thank you for the details @ManeshM - dashStyle is not supported by boost: http://code.highcharts.com/modules/boost.src.js

>          * Notes for boost mode
>          * - Area lines are not drawn
>          * - Lines are not drawn on scatter charts
>          * - Zones and negativeColor don't work
>          * - Dash styles are not rendered on lines.
>          * - Columns are always one pixel wide. Don't set the threshold too low.
>          * - Disable animations
>          * - Marker shapes are not supported: markers will always be circles

**Comment by pawelfus** [comment] 2018-03-28 15:05
Closing as duplicate of #5264.

**Closed by pawelfus** 2018-03-28 15:05 UTC
Labels: Docs
