### ISSUE TITLE
Background overlap x-axis on hover on 3d columns

### ISSUE THREAD

**Issue by sntran** [highcharts/highcharts#5374] opened 2016-06-03 07:41 UTC
#### Expected behaviour
When hovering a series in a 3d column chart, the background color should change and be contained inside the chart.

#### Actual behaviour
The background color overlap the x-axis, like the screenshot below. Note the shape between `Feb` and `Mar` series.

<img width="305" alt="screen shot 2016-06-03 at 2 33 50 pm" src="https://cloud.githubusercontent.com/assets/973206/15771973/94085348-2998-11e6-9622-5385ea84e38d.png">

This is with `crosshair: true` on the `xAsis`.

#### Live demo with steps to reproduce
http://jsfiddle.net/mhgfc3z0/

#### Affected browser(s)
Chrome 50.0.2661.94 (64-bit) on Mac OS X

**Comment by pawelfus** [comment] 2016-06-03 10:23
Thank you for reporting. This is known issue, duplicate of #4578.

**Closed by pawelfus** 2016-06-03 10:23 UTC
Labels: Duplicate
