### ISSUE TITLE
TypeError: l is undefined Error in production Environment, Ok in local

### ISSUE THREAD

**Issue by ndethi** [highcharts/highcharts#17312] opened 2022-05-19 10:47 UTC
#### Expected behaviour
Should show a column chart with bars as usual 

#### Actual behaviour
It shows the categories but does not show the bars. Returns an error on the console:
TypeError l is undefined as shown below:

> TypeError: l is undefined
>     compose stock.js:94
>     d highcharts.js:19
>     d highcharts.js:19
>     generatePoints highcharts.js:426
>     generatePoints stock.js:106
>     translate highcharts.js:428
>     translate highcharts.js:504
>     redraw highcharts.js:447
>     redraw highcharts.js:352
>     redraw highcharts.js:352
>     update highcharts.js:386

#### Live demo with steps to reproduce
[[](http://jsfiddle.net/w6khzavx/22/)](http://jsfiddle.net/w6khzavx/22/)

#### Product version
Highstock, Highcharts 9

#### Affected browser(s)
All browsers for site in production.

**Comment by KacperMadej** [comment] 2022-05-19 13:35
Hi @ndethi 

I am unable to recreate the error.

Please provide a demo with the error and more details about the difference between production and local - how are you loading the library? is the same version used in both cases? etc.

**Comment by ndethi** [comment] 2022-05-20 11:13
Thank you @KacperMadej

Here are the versions used for production and local.

#### Production
***
 Highstock JS v9.0.0 (2021-02-02)

 Highstock as a plugin for Highcharts

#### Local
***
 Highstock JS v9.0.0 (2021-02-02)

 Highstock as a plugin for Highcharts

Bugsnag reports points to this section of the stock.js file if that helps:
`
h=[],f;for(f=0;f<e.length;f++)a.isInAnyBreak(e[f])||h.push(e[f]);this.tickPositions=h;this.tickPositions.info=c}});A(e,"afterSetOptions",function(){this.brokenAxis&&this.brokenAxis.hasBreaks&&(this.options.ordinal=!1)});A(l,"afterGeneratePoints",function(){var a=this.options.connectNulls,e=this.points,c=this.xAxis,h=this.yAxis;if(this.isDirty)for(var f=e.length;f--;){var l=e[f],d=!(null===l.y&&!1===a)&&(c&&c.brokenAxis&&c.brokenAxis.isInAnyBreak(l.x,!0)||h&&h.brokenAxis&&h.brokenAxis.isInAnyBreak(l.y,`

**Comment by pawellysy** [comment] 2022-05-23 08:08
@ndethi, sorry, but the demo that you shared does not throw any errors. Could you try to reproduce the issue once again? Thanks for sharing the versions, but as you can see, the minified code does not mean a lot, so you can try changing the extension of the included files from e.g. `highcharts.js` to `highcharts.src.js` which will use the un-minified code, which is much easier to read. Thanks!

**Comment by ndethi** [comment] 2022-05-23 09:14
@pawellysy @KacperMadej Thank you for your responses.

So I copied the json response from the production server for the affected api endpoint and used that as the source data for the chart in the local set up. Doing that reproduced the error in local.

Comparing the response in local and the response in production I found that the production data had more categories than local, likely because production is live but examining it further and console.logging it i found that the lengths of the series data array and the categories array were different! 

I checked the code again and found that I was extracting the series data using Lodash' map function, which returns an array of the same length as the input array, while inside this map function I was also using push to add elements into a categories array. This resulted in the discrepancies in length of the series data array and the categories array. 

While I cannot for certain say this is what was causing this error, resolving the series/category array length discrepancy seems to have resolved this issue.

**Comment by ndethi** [comment] 2022-05-23 09:17
@KacperMadej @pawellysy I have tried editing the fiddle here http://jsfiddle.net/w6khzavx/22/ to mimic the discrepancy in series and category data length but it does not throw any errors, it works just fine.

**Comment by ndethi** [comment] 2022-05-23 11:43
Now that I have understood part of the problem, I have been able to reproduce the error in this fiddle: http://jsfiddle.net/jLu3wcm2/

**Comment by pawellysy** [comment] 2022-05-26 10:41
Hi @ndethi, this is an issue connected to your usage of the `lodash` library and is not related to highcharts. 
Closing since this is not a bug.
You can seek answers on some more general forum like StackOverflow :)

**Closed by pawellysy** 2022-05-26 10:41 UTC
Labels: Status: Can't reproduce, Status: Pending reply
