### ISSUE TITLE
Tooltip header breaks when xDateTime is set

### ISSUE THREAD

**Issue by AndrzejBuleczka** [highcharts/highcharts#22371] opened 2024-12-13 13:32 UTC
#### Expected behaviour
In stock or with dataGrouping module added, xDateTime setting in tooltip set's the header format consistently

#### Actual behaviour
In stock or with dataGrouping module added, xDateTime setting in tooltip set's the header format for the first hover, afterwards it turns to undefined.

#### Live demo with steps to reproduce
Stock example: https://jsfiddle.net/BlackLabel/hc1qzmva/
Core with dataGrouping module: https://jsfiddle.net/BlackLabel/up8nztxL/

Hover over same points at least twice and note the tooltip header turns to undefined.

#### Product version
Highcharts Core

Regression, bisected to [a2efc7f](https://github.com/highcharts/highcharts/commit/a2efc7f760b27c7bbb6925a26fcdfb8feefe6a3a)

#### Affected browser(s)
all

**Comment by TorsteinHonsi** [comment] 2024-12-16 06:34
It's already fixed in the master, duplicate of #22316

**Closed by TorsteinHonsi** 2024-12-16 06:34 UTC
Labels: Priority: Blocker
