### ISSUE TITLE
Datepicker doesn't reopen 

### ISSUE THREAD

**Issue by errayhaniM** [highcharts/highcharts#10221] opened 2019-02-27 10:29 UTC
1. Open http://jsfiddle.net/gh/get/jquery/1.7.1/highslide-software/highcharts.com/tree/master/samples/stock/rangeselector/input-datepicker/ in Chrome
2. Click on "**From**" input so the datepicker is opened 
3. Click  outside the input anywhere in the chart, the datepicker is closed
4. Re-click on the From input, the datePicker is not opened

Result: No datePicker is opened
Expected: Open the datePicker

**Comment by pawelfus** [comment] 2019-02-27 13:20
Hi @errayhaniM 

Thanks for reporting the issue. Actually, it's a duplicate of #4606 

**Workaround:**
http://jsfiddle.net/BlackLabel/khto2xdf/

Closing as duplicate of #4606

**Closed by pawelfus** 2019-02-27 13:20 UTC
