### ISSUE TITLE
No tooltip Highstock Flag series

### ISSUE THREAD

**Issue by daannijkamp** [highcharts/highcharts#6941] opened 2017-07-10 07:17 UTC
#### Expected behaviour
A tooltip will show while hovering a flag from a flags series.

#### Actual behaviour
In Highcharts/Highstock no tooltip appears when hovering a flag

#### Live demo with steps to reproduce
http://jsfiddle.net/highcharts/XLKN5/1/
(just a generic example from #2573)  

#### Affected browser(s)
Tested on Chrome 58 (But it seems that this applies to all browsers)

**Comment by pawelfus** [comment] 2017-07-10 09:01
Hi @daannijkamp 

This is bug in the current version, already fixed on our master branch, please take a look: http://jsfiddle.net/h1tu8c9j/

Closing as duplicate of #6764

**Closed by pawelfus** 2017-07-10 09:01 UTC

**Comment by dandv** [comment] 2017-07-17 10:41
@pawelfus: flags remain dark after hovering out of them, not just during hover. Is that expected?

![image](https://user-images.githubusercontent.com/33569/28264868-ce240b6c-6aa1-11e7-9297-5b2ed6f40ee8.png)

**Comment by pawelfus** [comment] 2017-07-17 11:09
Hi @dandv 

It shouldn't happen, however I can not recreate issue using my fiddle above. Could you update my demo and let me know about your browser?

**Comment by dandv** [comment] 2017-07-17 21:43
Can no longer reproduce. Thanks!
