### ISSUE TITLE
4.2.5 release broke our charts

### ISSUE THREAD

**Issue by arnabk** [highcharts/highcharts#5301] opened 2016-05-10 05:50 UTC
#### Expected behaviour
Charts should work

#### Actual behaviour
Initial rendering does not work

#### Live demo of the issue

https://webtrader.binary.com/beta/v2.0.28/main.html

#### Steps to reproduce the behaviour
Visit https://webtrader.binary.com/beta/v2.0.27/main.html
You will see that charts are working. This is using highstocks#4.2.4

Visit https://webtrader.binary.com/beta/v2.0.28/main.html
You will see that charts are not working. This is using highstocks#4.2.5. If you select Chart Menu hambuerger> Refresh, it will refresh the chart and re-renders all data and everything works fine. The initial rendering is not working.

I have no idea what might have gone wrong. So I am unable to point to anything specific. 

#### Affected browser(s)
All

**Comment by pawelfus** [comment] 2016-05-10 09:12
It looks like a problem with the container. Do you use somewhere `setSize()` or other method to resize the chart? It's a bit hard to debug minified code.

The interesting thing is that `containerWidth = 0` and `containerHeight = 0`, so calling: `Highcharts.charts[0].setSize(340, 350)` resolves the issue. Maybe another manifestation of rendering chart in a hidden container?

**Comment by arnabk** [comment] 2016-05-13 01:46
I dont use `setSize` anywhere. Also there is nothing hidden.

However when series data is loaded(which we load async way after chart is rendered), we call `series.chart.redraw();`

**Comment by TorsteinHonsi** [comment] 2016-05-13 08:10
Are you able to reproduce it in jsFiddle?

**Comment by jon-a-nygaard** [comment] 2016-06-15 11:21
Closing this issue due to we are not able to reproduce the issue, and it is pending reply. 
Should anyone have further information on this issue, please add a comment and/or reopen.

**Closed by jon-a-nygaard** 2016-06-15 11:21 UTC
Labels: Cant reproduce, Pending reply
