### ISSUE TITLE
Zoom support for 3D graph

### ISSUE THREAD

**Issue by OndemandGroup** [highcharts/highcharts#19396] opened 2023-07-19 09:49 UTC
Hi,
zoom is not working well with 3D chart and area series type.
I found this topic (https://www.highcharts.com/forum/viewtopic.php?t=48554) inviting to create a new feature request.
I attach 2 images showing the malfunction of the zoom.
Thanks.

![AfterZoom](https://github.com/highcharts/highcharts/assets/139964236/c642bc30-b570-48e0-bc22-6d60c8f2f468)
![BeforeZoom](https://github.com/highcharts/highcharts/assets/139964236/bb70d231-78bb-4976-ba92-cf5851450394)

**Comment by bm64** [comment] 2023-07-19 23:15
Hello @OndemandGroup and thanks for sharing the idea. Feature request for 3D zooming already exists, so I'm closing this one as a duplicate of https://github.com/highcharts/highcharts/issues/17345

**Closed by bm64** 2023-07-19 23:15 UTC
Labels: Type: Feature Request
