### ISSUE TITLE
Problem with line series -> datapoints with same x value -> mouseover/tooltip/etc.

### ISSUE THREAD

**Issue by rikkert-jan** [highcharts/highcharts#6231] opened 2017-01-11 11:19 UTC
#### Expected behaviour
When two points in the same series of a line chart share the same X value, it should not matter for the mouse-over event. When hovering on one of the points on the same x-value, the datalabel or tooltip corresponding to that specific point would show.

#### Actual behaviour
When hovering on a point which shares the same x value as another point in the same series, it shows only the tooltip of the point with the highest y value.

#### Live demo with steps to reproduce

JSFiddle initial (from highcharts demo "Time data with irregular intervals"):
http://jsfiddle.net/gh/get/jquery/3.1.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/spline-irregular-time/

JSFiddle altered:
http://jsfiddle.net/gmeq1zL8/1/

1) Open highcharts demo "Time data with irregular intervals" in JSFiddle
2) Alter first point in data array to have the same date (and thus x-value) as the next point in the same series
3) Hover on both of the points that share the same X value/date
4) Notice how highcharts mouseover only applies to one of the two points

**Comment by oysteinmoseng** [comment] 2017-01-16 16:22
This is because the spline tooltip searches for the closest point along the X axis only. In most cases this makes it easier to browse the chart. To change the behavior you can set `kdDimensions`: [example](http://jsfiddle.net/highcharts/9c5ymg47/2).

This is also a duplicate of #5983. Should we consider adding an option in the API for this to make it more clear to users? @TorsteinHonsi

**Comment by TorsteinHonsi** [comment] 2017-01-18 08:44
> Should we consider adding an option in the API for this to make it more clear to users?

@oysteinmoseng Yes I think it's time for that. The current behaviour is that on scatter charts, the closest point in both x and y dimensions are picked, while in line-like charts, it only looks for the closest point in x dimension only. 

The rationale for the current behaviour can be seen below. If we searched for the nearest neighbour in two dimensions, a spike in the data set would attract tooltips, so if would be difficult ho hover along the graph to read values successively. 

The question is, what would be an intuitive name for this new option? `tooltip.nearestPointDimension`? `tooltip.searchDimensions`?

![skjermbilde 2017-01-18 kl 09 39 15](https://cloud.githubusercontent.com/assets/227836/22056850/60281382-dd62-11e6-89bc-a63e62b6f97f.png)

**Comment by pawelfus** [comment] 2017-01-18 10:00
Wouldn't be better to provide this setting for `series`, not `tooltip`? Just an idea.

**Comment by TorsteinHonsi** [comment] 2017-01-18 13:47
Yes, absolutely.

**Comment by rikkert-jan** [comment] 2017-03-02 09:24
Awesome! Thanks for the replies.
May I inquire as to when we might expect this change to be released?
We have developed a quick fix for the time being, but we like to change this as soon as possible.

Thanks in advance!

**Comment by oysteinmoseng** [comment] 2017-03-29 08:36
@rikkert-jan Example: http://jsfiddle.net/02mv9nb9/

**Closed** 2017-03-29 13:33 UTC
Labels: Enhancement, Fix suggested

**Comment by 1DMF** [comment] 2018-04-28 20:03
This still doesn't work, any i8dea when it will be fixed?

**Comment by pawelfus** [comment] 2018-04-30 09:00
Hi @1DMF - it looks fine in Highstock, take a look: http://jsfiddle.net/BlackLabel/02mv9nb9/4/ (note: `tooltip.split` and `tooltip.shared` options should be disabled - these options always use `x-distance` comparison).

**Comment by 1DMF** [comment] 2018-04-30 10:43
Thank you, it was `tooltip.split: false,` that solved it. Much appreciated!
