### ISSUE TITLE
Labels with attributes align: 'right', textAlign: 'left' and positive x are not displayed

### ISSUE THREAD

**Issue by alfonsomunozpomer** [highcharts/highcharts#18149] opened 2022-12-14 19:30 UTC
#### Expected behaviour
The label above the green line should be displayed 10px to the right of the chart.

#### Actual behaviour
The label above the green line is not displayed. If you inspect the generated document the text has been removed from the `<text>` element:
```svg
<text x="1288" text-anchor="start" class="highcharts-plot-line-label " data-z-index="0" transform="translate(0,0)" y="98"></text>
```

#### Live demo with steps to reproduce
https://jsfiddle.net/avnms825/

#### Product version
Highcharts JS v10.3.2 (2022-11-28)

#### Affected browser(s)
All

**Comment by karolkolodziej** [comment] 2022-12-15 08:13
Hi @alfonsomunozpomer!

The issue was introduced in version 9.2.0 by https://github.com/highcharts/highcharts/pull/15837
As a workaround, you might apply wrap from the [demo](https://jsfiddle.net/BlackLabel/xj65rmnt/) which sets the correct width of the label.

_Internal note:_ 
The issue is caused because the negative width set to the label.

**Comment by karolkolodziej** [comment] 2022-12-15 08:17
Actually it as a duplicate of: https://github.com/highcharts/highcharts/issues/17888

**Closed by karolkolodziej** 2022-12-15 08:17 UTC
Labels: Type: Regression, Status: Has workaround

**Comment by alfonsomunozpomer** [comment] 2022-12-15 09:21
Thanks for the pointers. I searched for duplicated but couldn’t find them. Sorry about that!
