### ISSUE TITLE
Pie chart - problem with connectors on gradient color

### ISSUE THREAD

**Issue by SergeyZadorozhniy** [highcharts/highcharts#2531] opened 2013-12-12 14:32 UTC
Connectors are not displayed if connector is completely flat, horizontal and the piece has a gradient color.

http://jsfiddle.net/sGzN8/

**Comment by oysteinmoseng** [comment] 2018-06-07 13:14
This is still relevant: http://jsfiddle.net/219fLsht/

**Comment by KacperMadej** [comment] 2018-06-14 15:35
Duplicate of #1677

**Closed by KacperMadej** 2018-06-14 15:35 UTC
Labels: Bug
