### ISSUE TITLE
Highstock: multiple column(range) series are compressed in middle of plot area

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4029] opened 2015-03-24 13:42 UTC
Example: http://jsfiddle.net/79q5c6bk/1/

Series have too much space on both sides. It applies to column, columnrange, bar.

As a workaround it is possible to set pointRange.
Example: http://jsfiddle.net/79q5c6bk/5/

**Comment by pawelfus** [comment] 2015-08-31 11:56
Another workaround: disable `ordinal` option: http://jsfiddle.net/79q5c6bk/6/

**Comment by TorsteinHonsi** [comment] 2015-11-27 19:57
Duplicate of #2822

**Closed by TorsteinHonsi** 2015-11-27 19:57 UTC
Labels: Duplicate
