### ISSUE TITLE
Columns chart, column hidden (outside chart)

### ISSUE THREAD

**Issue by affenuclear** [highcharts/highcharts#16418] opened 2021-09-29 09:45 UTC
In a Chart with columns, with only one x point in 0 for each column, one of the columns appears outside of the chart

#### Expected behaviour

when we have multiple x's for each series, there is a padding applied where we can see a column to the left of the 0 label

https://jsfiddle.net/hjeozrbs/

#### Actual behaviour

Here if we click in the series 2 legend and hide it, the series 1 blue column appears

https://jsfiddle.net/7xk1o3jn/

**Comment by raf18seb** [comment] 2021-09-29 13:58
Hi @affenuclear! Thanks for posting the ticket.

It's not a bug.
When you have 2 points defined in your series, then the [series.pointRange ](https://api.highcharts.com/highcharts/series.column.pointRange) is "computed as the distance between the two closest data points". In your case, that distance is `222000000`.

When there is only one column per series, the `pointRange` is calculated differently.
Please, see this simplified example (uncomment the `pointRange` to see a difference): https://jsfiddle.net/BlackLabel/adojur6s/

In your demo, you can set the `pointRange` to e.g. `86400000`.

I'm closing as not a but. Please let me know if you have any further concerns about this issue.

**Closed by raf18seb** 2021-09-29 13:58 UTC
