### ISSUE TITLE
Issue for click and scroll events on mobile

### ISSUE THREAD

**Issue by ashwini-appstute** [highcharts/highcharts#11786] opened 2019-08-27 10:31 UTC
Expected behaviour
Click event and scroll should behave separately in mobile for column chart. 

Actual behaviour
We have plotted column graph and showing tooltip of the values on click event in mobile. As values are more we have given scrollbar to the tooltip and this is working fine in desktop. But in mobile click event and scroll touch are overriding and while scrolling its opening the tooltip.

Live demo with steps to reproduce
https://jsfiddle.net/4ftq6jyk/1/

**Comment by sebastianbochan** [comment] 2019-08-27 13:30
Hi @ashwini-appstute,
Thank you for reporting about the problem. It is duplicate of https://github.com/highcharts/highcharts/issues/11787, so Im closing the issue.

**Closed by sebastianbochan** 2019-08-27 13:30 UTC
