### ISSUE TITLE
High chart zone color based on value is end up in displaying both the colors if the value is equal or if the value is .001 less or more

### ISSUE THREAD

**Issue by sivakma** [highcharts/highcharts#20074] opened 2023-11-06 06:54 UTC
#### Expected behaviour
Is it possible to display red color if the value is <= 10 

#### Actual behaviour
Even it display both the color until from 9.95 to 9.95  suppose to be red

#### Live demo with steps to reproduce
https://jsfiddle.net/sivakma/g2yLe1sw/4/

#### Product version

* Highcharts JS v11.2.0 (2023-10-30)
<script src="https://code.highcharts.com/highcharts.js"></script>
#### Affected browser(s)
All browsers

**Comment by bm64** [comment] 2023-11-07 17:52
Hello @sivakma

We have discussed that case some time ago, and came to conclusion that this behaviour is intended. For more details please see following issue: https://github.com/highcharts/highcharts/issues/19188

Closing as a duplicate of https://github.com/highcharts/highcharts/issues/19188

**Closed by bm64** 2023-11-07 17:52 UTC
