### ISSUE TITLE
Month xAxis has inconsistent space after February column

### ISSUE THREAD

**Issue by jjenzz** [highcharts/highcharts#9210] opened 2018-10-18 09:26 UTC
#### Expected behaviour

Plotting month columns on a `datetime` xAxis using `tickInterval` and/or `pointInterval` would render consistent width columns with consistent gutters.

#### Actual behaviour

There is an inconsistent (smaller) space between February and March even though I've used `tickInterval` so ensure all ticks are 28 days.

#### Live demo with steps to reproduce

http://jsfiddle.net/gfnw0xhy/

#### Product version

`highcharts@6.2.0`

**Comment by ppotaczek** [comment] 2018-10-18 10:56
Hi @jjenzz, Thank you for reporting this problem.

Datetime axes are based on milliseconds and not equal spaces result from a different time interval for months. The set `tickInterval` option is rounded, here you can see how ticks would look like with your fixed interval: http://jsfiddle.net/BlackLabel/vh4k05yx/

To align the spaces between the columns you can use:
- `ordinal` xAxis from Highstock: http://jsfiddle.net/BlackLabel/rkb51wd0/, 
- `broken-axis` module to remove spacing for days in months that have more than 28 days: http://jsfiddle.net/BlackLabel/L5ezt29q/
- `category` axis type: http://jsfiddle.net/BlackLabel/604ogcyx/

**Closed** 2018-10-19 08:42 UTC
Labels: Not a bug

**Comment by qazd** [comment] 2019-01-14 10:06
> To align the spaces between the columns you can use:
> * `pointIntervalUnit`as `month`: http://jsfiddle.net/BlackLabel/qeap27L6/

When `pointIntervalUnit` set to `month` the spaces between the columns still depend on the number of milliseconds in the month: http://jsfiddle.net/m3yrepLs/4. Is this behavior is intended?

**Comment by TorsteinHonsi** [comment] 2019-01-14 11:04
Yes, this is the expected behaviour. The `pointIntervalUnit` defines that we should have a month between each point. In turn, the width of each column is determined by the distance between the two closest points, so in this case all columns will span 28 days. The corresponding setting here is `pointRange`, but we don't currently support a variable point range.

To avoid this you would have to use a category axis.
