### ISSUE TITLE
Tooltip in scrollablePlotArea gets wong positioning when scrolling

### ISSUE THREAD

**Issue by MimmiArvidsson** [highcharts/highcharts#14493] opened 2020-11-05 11:10 UTC
When using scrollablePlotArea and minWidth > 800, the tooltip positioning is wrong
```
chart: {
        type: 'column',
                    backgroundColor: '#f1f5f5',
                    scrollablePlotArea: {
                        minWidth: 1000,
                        scrollPositionX: 0,
                        opacity: 0.85
                    },
                },
```
The tooltip works if I use minWidth:700

using highcharts 8.2.0

using chrome Version 86.0.4240.111

![tooltip](https://user-images.githubusercontent.com/26299489/98233819-d755a300-1f5f-11eb-95f4-8f70adcf2d60.gif)

**Comment by PaulDalek** [comment] 2020-11-05 18:18
Hi @MimmiArvidsson

Thank you for reporting this issue. This behavior was reported previously. As a workaround you can set the `tooltip.outside` to `false`.

Closing as a duplicate of the #12416.

**Closed** 2020-11-05 18:18 UTC
