### ISSUE TITLE
View in Full screen resizes chart when exiting

### ISSUE THREAD

**Issue by kai2468** [highcharts/highcharts#13469] opened 2020-05-08 09:31 UTC
#### Expected behaviour
View in full screen option in the export menu keeps the chart the same size when exiting out of full screen

#### Actual behaviour
View in full screen works fine, but after exiting full screen, the chart resizes itself.

#### Live demo with steps to reproduce
Can be seen in the demos:
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/line-basic/

1) Click the view in full screen option in the export menu
2) Exit out of full screen
3) Chart has now resized itself

#### Product version
Latest

**Comment by sebastianbochan** [comment] 2020-05-08 09:35
Hi @kai2468,
Thank you for reporting. The issue has been already reported.

Im closing the ticket as duplicate of https://github.com/highcharts/highcharts/issues/13222.

**Closed by sebastianbochan** 2020-05-08 09:35 UTC
