### ISSUE TITLE
yAxis.lineWidth = 1 not shown when chart.spacingLeft = 0

### ISSUE THREAD

**Issue by iweindesmedt** [highcharts/highcharts#2632] opened 2014-01-23 23:31 UTC
http://jsfiddle.net/LLExL/2350/
i think this is because the line is drawn from the center but starting on the left side
when setting `yAxis.opposite = true`, the line is indeed visible

**Comment by KacperMadej** [comment] 2018-12-30 00:37
Due to crisp rendering of the line one half of it will not be visible and the line's x position will be rounded to the left making 1 pixel width line not visible (clipped out), 2 pixel width - visible as 1 pixel. As a solution use 2 pixel width in such edge cases.

This doesn't look like a bug - more like a inconvenient, but logical consequence of the crisp rendering.
Closing as not a bug.
Please leave a comment if you disagree with more info about the issue and it could be reopened.

**Closed by KacperMadej** 2018-12-30 00:37 UTC
Labels: Undecided
