### ISSUE TITLE
Strange drawing in chrome

### ISSUE THREAD

**Issue by statickidz** [highcharts/highcharts#7739] opened 2018-01-27 16:50 UTC
#### Expected behaviour
![expected](https://i.gyazo.com/de5af1615558896debdf4191f09f2586.png)

#### Actual behaviour
![actual](https://i.gyazo.com/6c9b61b63d1f135ba66238d9a4e8371a.png)

#### Live demo with steps to reproduce
No

#### Product version
6.0.4

#### Affected browser(s)
Only Chrome

**Comment by sebastianbochan** [comment] 2018-01-29 11:13
Hi @statickidz 
Its duplicate of https://github.com/highcharts/highcharts/issues/7662

**Closed by sebastianbochan** 2018-01-29 11:13 UTC
