### ISSUE TITLE
Pattern Charts not showing in Download Options

### ISSUE THREAD

**Issue by VartikaGarg** [highcharts/highcharts#4969] opened 2016-01-28 12:31 UTC
I have generated a bar graph with pattern. When I click on Download PNG/Download JPEG etc options, the graph does not come at all

![image](https://cloud.githubusercontent.com/assets/16937592/12644438/e726f980-c5e8-11e5-8024-830f8768ea07.png)

![chart](https://cloud.githubusercontent.com/assets/16937592/12644469/0d4a78d0-c5e9-11e5-8d77-54ea46878b4e.png)

**Comment by pawelfus** [comment] 2016-01-28 12:39
Could you setup jsFiddle demo with that issue? I just tried this, and works fine for me: http://jsfiddle.net/ErU8H/730/

Note: path to pattern should be absolute path (starting with `http://`) so the exporting server can pick up the image.

**Comment by jon-a-nygaard** [comment] 2016-04-26 09:32
Closing this issue due to: We are not able to reproduce the issue, and it is pending reply. 
Should anyone have further information on this issue, please add a comment and reopen.

**Closed by jon-a-nygaard** 2016-04-26 09:32 UTC
Labels: Cant reproduce, Pending reply
