### ISSUE TITLE
Highcharts.merge goes into an infinite loop when used with a self-referencing object

### ISSUE THREAD

**Issue by sweko** [highcharts/highcharts#3031] opened 2014-05-08 07:09 UTC
If I call Highcharts.merge with an object that has a reference to itself, it goes into an infinite loop (the doCopy call), e.g.

```
        var original = {};
        var addition = { one: 1, two: 2, reference: {} };
        addition.reference = addition;

        var result = Highcharts.merge(original, addition);
```
Note that I do not call the `merge` directly, but it's called when I use the exportSvg call. I've attached an additional object reference to the highchart, which has some objects that have parent-child references, and it goes into a loop there.

**Comment by jon-a-nygaard** [comment] 2016-06-16 09:31
Closing this issue since we are unable to reproduce it, and it is pending a reply. If anyone should have any further information about this issue, please comment and/or reopen.

**Closed by jon-a-nygaard** 2016-06-16 09:31 UTC
Labels: Cant reproduce, Pending reply

**Comment by adigourdi** [comment] 2018-09-20 16:44
Just stumbled around this issue, here's a reproducible example case
```javascript
a = { b: {} }; // main object
m = { c: 3 }; // object to merge
r = Highcharts.merge(a, m); // r => {b: {}, c: 3}
a.b.a = a; // include recursive reference
r = Highcharts.merge(a, m); // => Uncaught RangeError: Maximum call stack size exceeded
```

I don't suppose this would occur with Highcharts options object,
but using the merge function with anything else might reproduce it

**Comment by KacperMadej** [comment] 2018-09-21 08:36
Thank you @adigourdi 
It's possible to write a code that will throw error, but does it happen when using Highcharts?
We need a problem in Highcharts to label this a bug.

The issue will remain closed, but please post a comment if you have a demo with the Highcharts bug to report in this topic and the issue could be reopened.

**Comment by khushahal-sharma** [comment] 2019-10-15 06:57
Whenever using the latest high chart version, merge method is causing maximum call stack to exceed error.

`window.Highcharts.merge(ChartConfig.ChartDefaults, options)`   


but in older version 4.12 it is working fine. 

As i am using high chart to add it in window object.

**Comment by jon-a-nygaard** [comment] 2019-10-15 12:39
Hi @khushahal-sharma, can you add an example that reproduces your issue to help us debug? [Codepen](https://codepen.io/) or [JSFiddle](https://jsfiddle.net/) works well for this purpose.
