### ISSUE TITLE
Hovering over Elements on Bar Graphs can prevent other Elements from displaying their Hovered Over tooltips

### ISSUE THREAD

**Issue by TheDarkMessiah** [highcharts/highcharts#3247] opened 2014-07-10 19:56 UTC
1) Login to nSight
2) Find a bar graph on the Demand or Conversion Pages
3) Hover over a portion of it so that the hover-over tool tip blocks some information
4) Let the hover over tool tip disappear

Expected Result: Portions of the Bar Graph that were under the tool tip before it faded do not display their own hover over tool tips.
![nsight error 1](https://cloud.githubusercontent.com/assets/8128353/3544361/3e8f55be-086c-11e4-8091-ae2a70e67f8a.png)
![nsight error 2](https://cloud.githubusercontent.com/assets/8128353/3544362/41b568b4-086c-11e4-9102-e4778c95ea2f.png)

**Comment by pawelfus** [comment] 2015-12-28 13:40
Duplicate of #3088.

**Closed by pawelfus** 2015-12-28 13:40 UTC
