### ISSUE TITLE
Wrong tooltip when setting useUTC to false 

### ISSUE THREAD

**Issue by tomsommer** [highcharts/highcharts#7038] opened 2017-08-03 09:51 UTC
http://jsfiddle.net/8u8ejyec/2/

When setting `useUTC` to `false` the tooltips on the chart are nolonger grouped by day (date without time), instead the time is added to the tooltip, when in fact it should still be only the day.

**Comment by KacperMadej** [comment] 2017-08-03 12:38
Hi @tomsommer,

In Highcharts there's no data grouping (this is Highstock exclusive feature). If you want your data to be grouped by day you should use Highstock with proper, probably forced, [data grouping](https://www.highcharts.com/docs/advanced-chart-features/data-grouping) options.

You are setting useUTC to false, so please let us know what is your timezone, so we could recreate the problem.

I am in time zone that has UTC+1 time during January and tooltip displays date with time (e.g. Monday, Jan 7, 1:00) and it correct.

**Comment by tomsommer** [comment] 2017-08-03 13:47
If you take the fiddle and set useUTC to true, then the tooltips do not have a time

My timezone is CEST

**Comment by KacperMadej** [comment] 2017-08-03 14:45
@tomsommer I am in the same time zone, so I will assume that you have UTC+2 now and UTC+1 in January, so for the series data in the demo tooltip shows date + time(1:00). This is correct because you are setting x - date for points in local time by setting useUTC to false. If you want to change tooltip's time display, then you could use [xDateFormat](http://api.highcharts.com/highcharts/tooltip.xDateFormat) setting.

This is not a bug, so I am closing the issue. Please feel free to continue the case here or move to [another support channel](https://www.highcharts.com/support) as we are trying to keep github only for bugs.

**Closed by KacperMadej** 2017-08-03 14:45 UTC
Labels: Pending reply

**Comment by tomsommer** [comment] 2017-08-04 12:38
I guess I will force xDateFormat then, I just wanted the 'magic' that happens when you have the time at 00:00:00 UTC, when not using useUTC.
