### ISSUE TITLE
Bubble Chart appends -1 when if chart is in certain width

### ISSUE THREAD

**Issue by gokulb9993** [highcharts/highcharts#21917] opened 2024-09-27 05:31 UTC
#### Expected behaviour

X-axis should plot the actual labels.

<img width="1393" alt="image" src="https://github.com/user-attachments/assets/1a657888-02ed-4080-b622-efb3b6e52e0d">

#### Actual behaviour

In certain width, X-Axis label starting with -1 which misleads the information in chart.

<img width="1310" alt="image" src="https://github.com/user-attachments/assets/e50c3fe4-3fde-4449-9764-938967c9c519">

#### Live demo with steps to reproduce

https://jsfiddle.net/bgokul9993/q70o5fys/22/

#### Product version
All versions

#### Affected browser(s)
All Browser

**Comment by hubertkozik** [comment] 2024-09-27 07:50
Hi @gokulb9993! Thank you for reporting the bug.

**SImplified demo:** https://jsfiddle.net/BlackLabel/5p2y3qd9/

The issue exists when the `bubble.maxSize` is set to a bigger value.

**Comment by oysteinmoseng** [comment] 2024-10-02 07:10
Seems fixed on master, probably a duplicate of #21530. 

Feel free to reopen if I misunderstood!

**Closed by oysteinmoseng** 2024-10-02 07:10 UTC
Labels: Type: Bug, Product: Highcharts

**Comment by gokulb9993** [comment] 2024-10-02 07:26
@oysteinmoseng Thanks! Yes seems like this is the duplicate of https://github.com/highcharts/highcharts/issues/21530. I could see this code in master but not in latest version(11.4.8) of highcharts. Do we have any tentative date of next version release.

**Comment by oysteinmoseng** [comment] 2024-10-02 10:22
Great! We are looking at releasing v12 soon, probably by end of month, and this would for sure make it in there.
