### ISSUE TITLE
Scatter marker symbol rotation on inverted chart

### ISSUE THREAD

**Issue by jakubjanuchta** [highcharts/highcharts#19288] opened 2023-07-04 07:54 UTC
#### Expected behaviour
When setting the `scatter.marker.symbol` to e.g. 'triangle', the marker should be drawn horizontally as it has been drawn in the previous versions when chart inverted.

#### Actual behaviour
When setting the `scatter.marker.symbol` to e.g. 'triangle',  the marker is drawn vertically when chart inverted. 

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/k639ztc4/

1) In v10.3.3, the triangle is drawn vertically.
2) Change the Highcharts version to v10.3.2, the triangle will rotate.

#### Product version
Highcharts v10.3.3

#### Affected browser(s)
All

**Comment by magdalena-gut** [comment] 2023-07-26 11:08
Bisected to commit f3f144619d , fixing #17880  ticket. 
@bm64 I'm not sure if we should consider it a bug. It seems to be an intended change.

**Comment by bm64** [comment] 2023-08-10 00:53
@magdalena-gut you're right. I discussed this with the author of the change, and it turns out it's an intended behavior, so I'm closing the issue. Thanks!

**Closed by bm64** 2023-08-10 00:53 UTC
Labels: Product: Highcharts, Type: Regression
