### ISSUE TITLE
stacking area chart connectNulls:true setting is not working

### ISSUE THREAD

**Issue by wy1713** [highcharts/highcharts#13304] opened 2020-04-13 20:33 UTC
#### Live demo with steps to reproduce
https://jsfiddle.net/q7omybph/1/

#### Product version
latest

#### Affected browser(s)
chrome

**Comment by sebastianbochan** [comment] 2020-04-14 08:27
Hi @wy1713,
Thank you for reporting about the problem. This bug is know and has been already reported in our repo.

Im closing the ticket as duplicate of https://github.com/highcharts/highcharts/issues/2069

**Closed by sebastianbochan** 2020-04-14 08:27 UTC

**Comment by pawelfus** [comment] 2020-11-12 10:53
Just a note: This was not a bug. In stacking, null points are treated as 0, when `connectNulls` is set to true.
