### ISSUE TITLE
pyramid 3d chart react typescript entegration

### ISSUE THREAD

**Issue by yunusyavuz16** [highcharts/highcharts#17024] opened 2022-02-21 18:45 UTC
Hello,

I am sorry if there is an issue about this subject but I did not find it so I have to ask to learn how to entegrate pyramid 3d chart to a project. I added some yarn package and put them into some functions that comes from funneld3d and highchart 3d. Could you please tell me where I did mistake. and I took this error : ×
Error: Highcharts error #17: www.highcharts.com/errors/17/?missingModuleFor=pyramid3d
 - missingModuleFor: pyramid3d

```
import React, {VFC} from "react";
import Highcharts from 'highcharts'
import HighchartsReact from 'highcharts-react-official'
import highcharts3d from "highcharts/highcharts-3d";
import funnel from "highcharts/modules/funnel.js";





highcharts3d(Highcharts);
funnel(Highcharts);



  
const PyramidCharts: VFC = () => {


const PyramidOptions: Highcharts.Options = {
    chart: {
        type: 'pyramid3d',
        options3d: {
            enabled: true,
            alpha: 10,
            depth: 50,
            viewDistance: 50
        }
    },
    title: {
        text: 'Müşteri Piramidi',
    },
    plotOptions: {
        series: {
            dataLabels: {
                allowOverlap: false,
                enabled: true,
                format: '{point.name}',
                inside: true,
                align: "center",
                verticalAlign: "middle",
            },
        }
    },
    legend: {
        enabled: true
    },
    series: [{
        type: "pyramid3d",
        data:[
            ['Website visits',      15654],
            ['Downloads',            4064],
            ['Requested price list', 1987],
            ['Invoice sent',          976],
            ['Finalized',             846]
        ],
        }
    ],
}
    return (
        <>
                 <HighchartsReact
                    highcharts={Highcharts}
                    options={PyramidOptions} /> 
        </>
    );
}

export default PyramidCharts





```

**Comment by raf18seb** [comment] 2022-02-21 21:25
Hi @yunusyavuz16, thanks for creating the ticket.

Error 17 clearly says that the `pyramid3d` module is missing.
Take a look at the HTML section of our official pyramid3d demo: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/pyramid3d
```html
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/highcharts-3d.js"></script>
<script src="https://code.highcharts.com/modules/cylinder.js"></script>
<script src="https://code.highcharts.com/modules/funnel3d.js"></script>
<script src="https://code.highcharts.com/modules/pyramid3d.js"></script>
```

Just import them the same as you imported `funnel`:
```js
import funnel from "highcharts/modules/funnel.js";
funnel(Highcharts);
```

Closing as resolved and not a bug.

**Closed by raf18seb** 2022-02-21 21:25 UTC
Labels: Type: Feature Request
