### ISSUE TITLE
Gantt: Updating collapsed tasks

### ISSUE THREAD

**Issue by FilipeCosta06** [highcharts/highcharts#11231] opened 2019-07-01 10:08 UTC
#### Expected behaviour
Updating collapsed tasks/subtaks should be possible.

#### Actual behaviour
First Fiddle:
When updating a Task/Subtask contained in a collapsed task, an **error is thrown**

> "highcharts-gantt.js:325 Uncaught TypeError: g.remove is not a function"

The task/subtask preceding the collapsed one bugs/disappears, and the **updated data isn't applied**.

Second Fiddle:
Thinking this issue (#10570) may fix it, I tried separating the collapsed task on a different series but, in this case, **the dates don't update** when collapsed (while the names do)

#### Live demo with steps to reproduce
All in the same series: https://jsfiddle.net/513ovfut/1/
Separated series:  https://jsfiddle.net/9vLzdphr/3/

#### Product version
Gantt Charts v7.1.2

#### Affected browser(s)
Chrome, Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by FilipeCosta06** [comment] 2019-07-02 10:14
I tried updating the "collapsed" data in the console and it works without problem ! 

But when I try to automate that ([either by looping with index or id](https://jsfiddle.net/j3swmotf/2/)), for some reason, the "hidden" datas return `undefined` (check the console). It is as if `chart.series[0].data[i]` and `chart.get(elem.id)` are only "searching" inside `series[0].points` which, indeed, only contains the visible datas.

This seems weird to me but I haven't searched the documentation enough to feel like calling it a bug. But yeah, I'd like to know if that's normal and if there is a way to update the datas that are "hidden" (obviously without updating all as it still causes an error).

**Comment by pawelfus** [comment] 2019-07-02 12:52
Thanks for reporting the issue. It seems to be the same as #9980 - do you agree? Different method (and error) is reported, but root of the problem is the same: updating data with collapsed tasks throws errors.

**Comment by FilipeCosta06** [comment] 2019-07-02 13:26
I cannot reproduce it in a demo but I also get that error `Cannot read property 'push'` or `'animate'` on specific scenarios and I also agree that, as shown in my second comment's demo, the problem seems to be linked to the fact that `series.points` is used instead of `series.data` for the updates. 

Anyway, judging by how old this issue is I suppose I'll have to find another way. 

As such: is there a good way to "redraw the whole graph, mainly yAxis/series" without destroying it ? I do a lot various dynamic edits on the graph (adding and removing categories but via `uniqueNames`, edit to/from `milestones`, stack both sub-tasks and inline ones etc...) and these errors just keep popping, especially when **removing an element**. Until now I was doing `chart.update({ yAxis, series})` and tried simply `chart.update({series})` but, evidently, the previous settings seem to create a whole bunch of issues. But at the same time, the whole point was to not have to update everything (with `Highcharts.ganttChart(options);`).

But maybe, since the removing is what causes most issues, I should do those with `point.remove()` (if it exists), I haven't tried yet, but then again, I don't know if this will correctly update/remove the yAxis categories etc... I still have a lot of experimenting to do

**Comment by FilipeCosta06** [comment] 2019-07-02 14:58
Here is a [demo](https://jsfiddle.net/pamo6c0v/9/) where removing any data (with `point.remove()`) causes a bunch of shenanigans... Either the graph makes no sense (whole different tasks disappear, some become milestones, etc...), or an error is thrown, etc... and it also happens when I'm not using sub-tasks.

Are there incompatible settings in my sketchy config ? I could add a button that removes data using `chart.update()` but this is what I was doing until now and the results are the same. Any form of help would be appreciated  @pawelfus. And if Gantt Chart isn't capable of "complex" (that's debatable, I'm sure I'm the one making mistakes here) dynamic editings, just let me know too ^^

I chose Gantt Chart because I was already familiar with HighCharts but also because I wanted to have both multiple tasks per line and sub-tasks, among other customisation options,  but the most important part is being able to dynamically edit the graph but, in the long run, I planned on creating a one from scratch (and that's where removing would be relatively important).

**Comment by FilipeCosta06** [comment] 2019-07-03 08:15
Additionally, it seems that updating the graph will always cause it to break when enabling `yAxis.uniqueNames`. In this [demo](https://jsfiddle.net/ubrxpd53/) (same as the previous one but without using `parent`), removing anything also causes similar visual problems. Would that constitute a different Issue @pawelfus ? I realise that using `uniqueNames` without `parent` kinda is missing the point but even updating in your [demo](https://jsfiddle.net/z08askyw/1/) different updates cause visual issues and I'd like to know if this attribute is usable with "drastic" updates and I'm just doing it wrong (maybe there is some "regenerate yAxis labels" function that I have to manually call or something) or not.

**Comment by jon-a-nygaard** [comment] 2019-07-03 13:38
Hi @FilipeCosta06, thanks again for reporting the issue.

At first sight this looks like a bug to me, but I will have to look through the code to be certain what may be going wrong, and if there is a viable workaround for the issue.

Since we are at the end of our work day in Norway I will not be able to do much today, but I will give you an update as soon as I know more during tomorrow.

**Comment by jon-a-nygaard** [comment] 2019-07-09 13:14
Hi @FilipeCosta06, 

Sorry for the delayed reply here.

The issue seems to be caused by `Series.updateData`, an internal function used in `Series.setData`, is not able to recognize that some Gantt points exists in the updated data set, and will therefore remove what is considered to be a "redundant" point.

I am not yet sure how to solve this issue, but I believe I have found a viable workaround for the mean time. It seems that by adding an `id` to all the points you will avoid this issue, please see the following [example of the workaround](https://jsfiddle.net/jon_a_nygaard/xgq93a8c/).

**Comment by FilipeCosta06** [comment] 2019-07-09 13:48
Hi @jon-a-nygaard,

No need to be sorry, I can't even grasp the amount of work you all must be having.

I have no idea why I had removed the `id` in the first place, sorry about that, but that does indeed fix the visual bug caused by the update. 👍 

Not trying to abuse of your time but the "collapsed" data still doesn't update (just like in the issue #9980 referenced by @pawelfus) as they seem to be `removed` when hidden (as @anarelion mentionned:
> Let me see if I can help.
> 
> Looks like when a breaker is added (with the toggleCollapse event), points are being deleted from the Series, not just hidden (https://github.com/highcharts/highcharts/blob/master/js/modules/broken-axis.src.js#L345).
> 
> But then, when updateData gets called, the comparison is between points and new data (https://github.com/highcharts/highcharts/blob/master/js/parts/Series.js#L3227).
> 
> Would the solution be to compare data with data, and not data with points? I don't know the codebase enough to be sure about this.

). 

I was hoping there would be some kind of event fired when a yAxis/treeGrid is collapsed to try and workaround this but I can't seem to find such event. Any idea on how to work around that too by any chance ^^' ?

**Comment by jon-a-nygaard** [comment] 2019-07-09 14:14
> but the "collapsed" data still doesn't update (just like in the issue #9980 referenced by @pawelfus)

Aha, I see now. That should be a relatively easy issue to fix, unfortunately it is not easy to provide a workaround for it.
I will start on a fix for this part of the issue first, then I will handle the `Series.setData` issue afterwards.

**Comment by jon-a-nygaard** [comment] 2019-07-11 06:46
I see now that I was a bit quick on the trigger with my last comment here.

> but the "collapsed" data still doesn't update (just like in the issue #9980 referenced by @pawelfus)

After looking more into this I remembered that there is a good reason to why the `collapsed` option has no affect anymore after initialization. This is because it should not temper with the collapsed/expanded state set by user interaction.
Please have a look at the following [example](https://jsfiddle.net/jon_a_nygaard/r46g80Lt/) which demonstrates how this would be inconvenient.

This is not documented well enough in the API for [series.gantt.data.collapsed](https://api.highcharts.com/gantt/series.gantt.data.collapsed), and is something I will fix. Also the alternative utility methods `Tick.collapse`, `Tick.expand` and `Tick.toggleCollapse` is also not documented well enough, and has to be solved.

I was wondering if maybe there is a possibility to use `Tick.(collapse|expand|toggleCollapse)` to solve your use case @FilipeCosta06? Please see the following [example](https://jsfiddle.net/jon_a_nygaard/hdjk5ywm/) to see how this could be achieved.

**Comment by FilipeCosta06** [comment] 2019-07-11 10:46
### Use Case
I tried fiddling around a bit with what you said but, before anything, I'd like to precise that, in my use case, I want the `collapsed` data to be updated while staying in the state (`collapsed`) it is in. Also, I do not allow a data to be initialized as collapsed. The user would be the one hiding the data when interacting with the graph.
### Failed attempt
At first I thought I could `toggleCollapse` without redrawing, `update` the data without redrawing and finally re-collapsing but it did not work. Even though, in the console, you can see that `update`, unlike `setData`, does change the `userOptions` yet isn't applied when finally calling `redraw` for some reason
### Semi OK
Based on your examples, I added an "empty" `update({}, false)` in the `beforeRedraw event` because, for some reason, the `userOptions` aren't applied (you can use the buttons to `update`/`setData` with/without redrawing in my [example](https://jsfiddle.net/v2e68w1h/5/)) and this helps but **only when expanding** and actually throws an error when **collapsing**.
### Ideas
For now, I can think of few ideas:

- Having some kind of tick `event` (`onExpand`/`onCollapse`/`onToggle`) if such thing exists
- _(somewhat similar)_ Being able to identify what action/event caused the redraw and if it's a "tick interaction", I then use `yAxis.nodes` to check if the tick is being collapsed or expanded
- Binding `onclick` events to "collapsable" ticks, ideally using BlackLabel's [custom events plugin](https://www.highcharts.com/products/plugin-registry/single/15/Custom-Events) on yAxis ticks but, since there is already a click event, maybe there is a way to override it (I just can't seem to find any reference about such event in the documentation). 

In the code I found this 
```
override(GridAxisTick.prototype, {
  [...]
```
![image](https://user-images.githubusercontent.com/25252573/61043146-d6e1e200-a3d5-11e9-9102-5bfda8a298dc.png)

And I think that could do it ! Some kind of 
```
// actually, it would probably be node.collapsed, and we do have this attribute too
if (tick.isCollapsed()) { 
    tick.toggleCollapse(false);
    point.update({}); 
} else 
    tick.toggleCollapse();
```
- Lastly, this'd be messy because I'm far from a pro, would be to keep track of all "collapsable" ticks and, each time the chart is updated, check if any of these ticks have changed to/from a collapsed state or something... Not a fan 👎 

And in all of these cases, I'd have to make sure the sub-sub-tasks don't interact weirdly.

Anyway, I think overriding may be a good idea and I'll have to watch out for ID reference updates (dynamically adding a dependence to/from a `hidden`/`collapsed` task would cause issues since it seems like `update` only checks "visible" data). What do you think @jon-a-nygaard ? And how can I override the `renderLabel` function ? I remember seeing something like `Highcharts.wrap` or something. Is that how it should be done (this seems like a more nested function so I don't know if it'd work) ?

**Comment by FilipeCosta06** [comment] 2019-07-17 15:10
Hi again @jon-a-nygaard, sorry for my absence.

As a quick recap, we previously determined (at least, it seems like, take it with a grain of salt):
- Updating a hidden point (hidden because its `parent` is `collapsed` at the moment of the update) wasn't taken into account while the point's `userOptions.data` were, in fact, updated (but only when using `.update()`, not `.setData()`).
- Calling for an empty `update({})` in the `beforeRedraw event ` fixed the problem but only when `expanding` and caused a bug when `collapsing`

I have yet to thoroughly test this (and I can't imagine the performance impact this must have but w/e, it's not like a Gantt is meant to be updated 50 times per second anyway... _hopefully_) but in my latest [demo](https://jsfiddle.net/fcb5k7x3/3/) I override the `Tick.prototype.toggleCollapse()` method and simply call `redraw({})` on the **whole** `chart` if the Tick **will be** `collapsed` after the click (I'm using `classList.contains("highcharts-treegrid-node-collapsed")` to determine if the Tick is collapsed; didn't check if there was already a method for that).
The demo is pretty messy but what you want to do is 
1) Open the console
2) click the 4th button (updates the chart, especially the "hidden" datas, and redraws it)
3) Check the console for the printed Datas (check which date you should be expecting for the last 2 points)
4) Toggle the "Develop" Tick and check using the xAxis/tooltip if the update correctly applied

It should update the hidden data without causing a bug when collapsing.

Again, I haven't tested it at all outside of this fiddle and will do that tomorrow but if you can already see why/when this'll cause problems I'd love a heads up :)

**Comment by jon-a-nygaard** [comment] 2019-07-18 09:29
Hi @FilipeCosta06,

Thanks for you input.

I realize now that my initial thought of updating the `collapsed` state of point was not of importance to you, but that updating the data on points that are children of a collapsed point was the main goal.
Sorry for my misunderstanding.

I have found what causes this issue, but unfortunately it seems to potentially be a complex problem, which I likely have to discuss with the rest of the team before we can apply a viable solution.


Good news is that I may have found a workaround that you can use in the mean time.
If we set the option `keys=true` when updating, it will cause `Series.update` to skip the logic that tries to reuse the existing points, which includes logic that causes the issue, and just create new points.

Please see the following [example of workaround](https://jsfiddle.net/jon_a_nygaard/3zn8f1sx/). I also applied this workaround to one of you examples, and it seems to work, please see following [example](https://jsfiddle.net/jon_a_nygaard/xgq93a8c/).

Let me know if this could work for you.

**Internal Note:** This is caused by `series.options.data` is not updated due to [`updateData` can not update points that does not exist in the `series.points` array](https://github.com/highcharts/highcharts/blob/91df181bb32a3d8235d9e83ea527893d55d9df17/ts/parts/Series.ts#L3345-L3375) and that [`options.data` is later set to `series.options.data`](https://github.com/highcharts/highcharts/blob/91df181bb32a3d8235d9e83ea527893d55d9df17/ts/parts/Dynamics.ts#L1417)

**Comment by FilipeCosta06** [comment] 2019-08-14 13:15
By the way @jon-a-nygaard, is there some kind of `onerror` event in HighCharts but for the uncaught exceptions ? (similar to [this](https://github.com/highcharts/highcharts/issues/3590))

Right now, I have a "hard reset" button that destroys and removes the graph and instantiates a whole new one. This is pretty fast and I don't mind it but I have to press the button manually. Ideally, I'd like for listen to any uncaught exception thrown by HighCharts and automatically destroy/redraw.

**Comment by jon-a-nygaard** [comment] 2019-08-14 14:21
@FilipeCosta06 As far as I know, we do not have an event for errors in Highcharts. You could [override the `Highcharts.error` function and listen to it](https://jsfiddle.net/jon_a_nygaard/e5mhLvgq/5/), but this would only be called for user configuration errors that Highcharts is catching.

I believe your mentioned suggestion with listening to `window.onerror` is probably a better solution for what you would like to achieve.

**Closed** 2019-11-19 11:46 UTC
Labels: Product: Highcharts Gantt, Status: Pending review, Type: Bug
