### ISSUE TITLE
data props changed after push into series HighMap

### ISSUE THREAD

**Issue by CaptainHoangLe** [highcharts/highcharts#16067] opened 2021-07-19 04:47 UTC
I am using highchart ver 9.1.2 and highchart react ver 3.0.0.
I have created a Highmap. This is my chartOptions in an async function
![image](https://user-images.githubusercontent.com/53038465/126104263-2f3ac498-e035-4a04-9c24-71b97068b851.png)
and return
![image](https://user-images.githubusercontent.com/53038465/126104295-ce0b6d36-b6da-4a31-9bc4-f0215fe0f1eb.png)
mapData is result when i read a geojson file.
This is my original data
![image](https://user-images.githubusercontent.com/53038465/126104314-4a888311-1a06-4ef8-b0e4-31799ab44be2.png)
By the magic way , after my data apply in highchart, it will be changed like that.
![image](https://user-images.githubusercontent.com/53038465/126104337-7151fb7b-c7ab-4406-ba6e-94ed2d3a36de.png)
Because of that reason, i think i can change map when apply a new map by select a dropdown which i have created before.
So, Please anyone can help me to slove my problem.
Thank you very much

**Comment by KacperMadej** [comment] 2021-07-19 12:54
Hi @CaptainHoangLe 

Highcharts are modifying the data provided, due to performance optimization, so if you need the original data try passing a copy to the chart constructor.

Duplicate of https://github.com/highcharts/highcharts/issues/4259 in the source of the problem.

**Closed by KacperMadej** 2021-07-19 12:54 UTC
