### ISSUE TITLE
disabling StickTracking doesn't work in boost mode

### ISSUE THREAD

**Issue by TheGreatYamcha** [highcharts/highcharts#9882] opened 2019-01-15 22:06 UTC
#### Expected behaviour
In this demo:
http://jsfiddle.net/tfbj9o4h/
hovering the mouse only on a series should reveal the tooltip, not when outside a series.
Here boost is disabled and it works properly:
http://jsfiddle.net/hzokdtjy/

#### Actual behaviour
explained above

#### Live demo with steps to reproduce
http://jsfiddle.net/tfbj9o4h/

#### Product version

latest: "https://code.highcharts.com/highcharts.js"
#### Affected browser(s)
tested in Chrome

**Comment by KacperMadej** [comment] 2019-01-15 22:39
Hi @TheGreatYamcha 

Thank you for reporting about the problem, but this is a known (not properly documented, but done by design) limitation.

When in boost mode series have forced options applied, namely:
```js
allowDG = false;
directTouch = false;
stickyTracking = true;
animate = null;
```

First part of resolving this problem should be to add info in docs about this as this is not mentioned in the top of the boost module as a comment, not in [general documentation](https://www.highcharts.com/docs/advanced-chart-features/boost-module), not in [API reference for stickyTracking](https://api.highcharts.com/highcharts/series.line.stickyTracking).

**Comment by TheGreatYamcha** [comment] 2019-01-15 22:55
If I disable tooltip, and override plotOptions.series.point.events.mouseOver and create my own tooltip, could I circumvent this problem in boost? or Does boost have problem with mouseOver too?

**Comment by KacperMadej** [comment] 2019-01-15 23:33
When stickyTracking will not be changed by boost tooltip will not be triggered as the required elements that would trigger it are not there (demo: http://jsfiddle.net/BlackLabel/4ta80d2w/). The problem is with series plot - it's just an image, so it doesn't have events for only some parts of it, like points.

**Closed** 2019-10-21 10:56 UTC
Labels: Product: Docs, Status: Pending review

**Comment by markzolotoy** [comment] 2024-12-16 14:02
Any chance that behavior with the Boost can be changed??

**Comment by KacperMadej** [comment] 2024-12-16 14:24
@markzolotoy 
Please open a feature request (a new issue of that type) and if it gets enough votes it will be implemented.
