### ISSUE TITLE
Legends overlapping on pie chart after click on drill down details

### ISSUE THREAD

**Issue by ifree92** [highcharts/highcharts#12817] opened 2020-01-21 12:06 UTC
Let's see on example from official site with browsers, but just enable legends:

`plotOptions.pie.showInLegend = true;`

Actual behaviour: https://jsfiddle.net/7rwgpqm6/
Please just click on any part of pie chart.

1. I'm expecting that the non shown legends after click should be hidden, but they still exist on legend block

2. I'm expecting that all legend items would be "friendly" to the position of each other.

Is it a real bug or some "unusual" way to use it?

Thank you!

**Comment by sebastianbochan** [comment] 2020-01-21 15:08
Hi @ifree92,
Thank you for reporting about the problem. The bug has been already fixed and should be merged in the next release.

Im closing the ticket as duplicate of https://github.com/highcharts/highcharts/issues/12627

**Closed by sebastianbochan** 2020-01-21 15:08 UTC
