### ISSUE TITLE
Highcharts react - Pie Chart does not render when the chartpoints size is very large (e.g. >1000 ) 

### ISSUE THREAD

**Issue by kartik6m** [highcharts/highcharts#19904] opened 2023-10-10 10:25 UTC
#### Expected behaviour
Pie chart should render with any length of the chartpoints array

#### Actual behaviour
It renders a blank screen.
![Did not work](https://github.com/highcharts/highcharts/assets/61024131/1ccdd883-a616-4795-a8a9-2af58a2b475d)

#### Live demo with steps to reproduce
[Link to codepen demo](https://codepen.io/kartikm06/pen/zYyeRyB)

#### Product version
Highcharts version 5.0.0

#### Affected browser(s)
tested on Google Chrome version Version 117.0.5938.134

**Comment by karolkolodziej** [comment] 2023-10-13 06:19
Hi @kartik6m!

If you take a look at the console there is an [error 12.](https://assets.highcharts.com/errors/12/)
You can add the [turboThreshold](https://api.highcharts.com/highcharts/plotOptions.series.turboThreshold) to change that, although the chart slows down significantly at this point- [demo](https://jsfiddle.net/BlackLabel/cq5um43g/).

I am closing it as not a bug.

**Closed by karolkolodziej** 2023-10-13 06:19 UTC
