### ISSUE TITLE
Multiple Y-Axis with scrollbars does not work as expected

### ISSUE THREAD

**Issue by samidabeast** [highcharts/highcharts#6453] opened 2017-03-10 15:56 UTC
#### Expected behaviour
You can scroll an individual Y-Axis while the chart maintains the others

#### Actual behaviour
I have the axis on the left side, but the scrollbars appear on the right, inside the chart. This causes it to create a zoom event when clicking on a scrollbar. Also, if you scroll up, it continuously scrolls up, but cannot go back to the original range

#### Live demo with steps to reproduce
http://jsfiddle.net/8EmeV/51/ 

If you zoom in on an axis and just scroll any of the yAxis you can see the behavior

#### Affected browser(s)
Chrome, IE

**Comment by pawelfus** [comment] 2017-03-10 16:23
Hi @samidabeast 

Thank you for reporting this. In fact we have two issues here:

- position of the scrollbar
- scrolling with [`chart.alignTicks`](http://api.highcharts.com/highcharts/chart.alignTicks) set to true

Position of the scrollbar of course should be fixed (it works as yAxis is on the left side: http://jsfiddle.net/8EmeV/52/ ). Regarding `alignTicks`, simply setting to false, resolves the issue:  http://jsfiddle.net/8EmeV/53/

**Comment by samidabeast** [comment] 2017-03-10 17:06
The alignTicks fixes the chart for the first one. But if you click the bottom button to re-create the chart, it does not work.

**Comment by pawelfus** [comment] 2017-03-10 17:09
It's caused by setting for the second chart, sorry I missed this. Setting for the second chart `alignTicks` works too: http://jsfiddle.net/8EmeV/54/

**Closed** 2017-03-15 13:05 UTC
Labels: Bug, Highstock

**Comment by samidabeast** [comment] 2017-03-17 17:36
How can I test to make sure this work? I tried with the JSFiddle from before but there are still issues with that.

**Comment by pawelfus** [comment] 2017-03-20 10:51
Hi @samidabeast 

Please, try our master branch: http://github.highcharts.com/highstock.js

**Comment by samidabeast** [comment] 2017-03-20 13:33
Thank you, it working in the JSFiddle as expected. When will this be available to http://code.highcharts.com/stock/highstock.js so that I can safely use it in my app?

**Comment by pawelfus** [comment] 2017-03-20 13:50
Next release should be ready within a few weeks.
