### ISSUE TITLE
Sankey 

### ISSUE THREAD

**Issue by vivekk123** [highcharts/highcharts#8503] opened 2018-06-20 12:36 UTC
#### Expected behaviour / #### Actual behaviour
https://jsfiddle.net/7xsdno0z/3/
In the example above there is no connection between any of the data in level 0, and England. This leads to England being moved back to level 0. Is it possible to make it so England remains on the same level as Portugal, France, Spain?

#### Live demo with steps to reproduce
https://jsfiddle.net/7xsdno0z/3/

#### Product version
v6.1.0

#### Affected browser(s)
All

**Comment by pawelfus** [comment] 2018-06-20 15:42
Hi @vivekk123 

It's not possible to skip columns at this moment. PoC for this is to provide `skipColumns` option, for example: https://jsfiddle.net/BlackLabel/7xsdno0z/5/

Closing as duplicate of #7354

**Closed by pawelfus** 2018-06-20 15:42 UTC

**Comment by TorsteinHonsi** [comment] 2018-06-21 07:16
Actually there is officiall support for this. You need to set the [nodes.column](https://api.highcharts.com/highcharts/series.sankey.nodes.column) option to 1. See https://jsfiddle.net/7xsdno0z/12/.

**Comment by vivekk123** [comment] 2018-06-22 06:58
Great, 

Thanks :)
