### ISSUE TITLE
Waterfall stack label misaligned

### ISSUE THREAD

**Issue by Sapana07** [highcharts/highcharts#17209] opened 2022-04-22 13:31 UTC
It looks that when we use two xAxes and one of them is moved the stackLabels are not being replaced according to the new position of xAxis. Probably it's a bug. 
​
That's how it looks like when we simplify the demo a little bit (still two xAxes): 
https://jsfiddle.net/BlackLabel/k8r19dL7/

And that's how it looks like with only one xAxis:
https://jsfiddle.net/BlackLabel/q8d5rgmn/

Here is my JsFiddle : https://jsfiddle.net/bdgn4a1s/

**Comment by Sapana07** [comment] 2022-04-25 08:51
Hey,
Any update on above?

**Comment by raf18seb** [comment] 2022-04-25 15:09
Hi @Sapana07,

it's already reported here: https://github.com/highcharts/highcharts/issues/16764
Unfortunately, we don't have any updates about this issue yet.

Closing as a duplicate of https://github.com/highcharts/highcharts/issues/16764

**Closed by raf18seb** 2022-04-25 15:09 UTC
