### ISSUE TITLE
Split tooltip in scrollablePlotArea is not updated on scrolling

### ISSUE THREAD

**Issue by jon-a-nygaard** [highcharts/highcharts#12416] opened 2019-11-15 10:33 UTC
#### Expected behaviour
The tooltip should be refreshed when the chart is scrolled.

See https://github.com/highcharts/highcharts/issues/11617 for more information

#### Actual behaviour
The positioning of the tooltip stays according to what it should be before the scrolling, and is not updated during the scroll.

#### Live demo with steps to reproduce
https://jsfiddle.net/Loepjy94/1/
1. Hover one of the points to see the split tooltip labels
2. Scroll down
3. The tooltip positions are not updated, and is wrongly displayed after the scrolling

#### Product version
Next version after v7.2.1

**Comment by wdrobinson** [comment] 2019-11-25 20:41
@jon-a-nygaard I'm seeing another bug from the recent tooltip updates. If you change the chart type to 'bar' in your above example the tooltip will appear outside of the chart container and cause lots of strange resizing and scrolling to occur. Let me know if I should create a separate ticket.

**Comment by jon-a-nygaard** [comment] 2019-11-26 09:34
Thanks for reporting @wdrobinson,

This seems to be an issue with the default tooltip. Because split tooltip is currently not supported on inverted charts, like the bar series, and it will fall back to the default tooltip.

I took the liberty to add a separate issue ticket for this, you can follow it at #12498

**Comment by TristanMouchet** [comment] 2020-01-29 15:10
Just to add that both examples in the API ref about [chart.scrollablePlotArea](https://api.highcharts.com/highcharts/chart.scrollablePlotArea) have the same type of issues with the tooltips when the charts are scrolled:

- [Scrollable plot area](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/chart/scrollable-plotarea),
- [Vertically scrollable plot area](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/chart/scrollable-plotarea-vertical),

**Comment by aglaganov** [comment] 2020-02-06 00:02
Any progress on this issue?

**Comment by pawelfus** [comment] 2020-02-06 09:17
Hi @aglaganov 
No, not yet, but it's one of the highest priority issues right now.

**Comment by AntonyJos** [comment] 2020-04-03 16:05
@pawelfus , @jon-a-nygaard , @TorsteinHonsi 

Still feel the issue is not yet fixed.
This might be a regression.
Kindly revisit the link to reproduce the defect once more

**Comment by sebastianbochan** [comment] 2020-04-06 08:12
@AntonyJos thank you for notification. You are right, its a regression.

_Internal note_
Bisect leads to https://github.com/highcharts/highcharts/commit/f13c4974708e5e303d642d740dc7e544afc50f82

**Comment by AntonyJos** [comment] 2020-04-09 08:58
#11493

**Comment by pawelfus** [comment] 2020-04-10 07:57
It seems that the fix does fix the tooltip position after scrolling, but still does not update tooltip's position upon scrolling. 

Works fine when `tooltip.outside=false`: https://jsfiddle.net/BlackLabel/tz4fL2wu/

**Comment by RamyapriyaKurapati** [comment] 2020-05-28 10:01
any progress on this issue with tooltip.outside=true

**Comment by sebastianbochan** [comment] 2020-05-29 06:51
Hi @RamyapriyaKurapati,
At this moment we do not have ETA for this ticket, but I labelled it by INBOX which means that its prioritized.

**Comment by AntonyJos** [comment] 2021-02-10 14:45
@TorsteinHonsi , @jon-a-nygaard , @pawelfus 
Drawing attention to this defect once again.

**Comment by KacperMadej** [comment] 2021-02-12 15:29
This looks like a general issue with a scrollable chart and any tooltip - tooltip is not refreshed after nor during the scroll.
The difference between `outside: true` and `false` is that the tooltip labels don't stick to the chart and don't scroll with the points that they are pointing to. Resolving the more general issue should also fix the problem with `outside`.

Minimal demo: https://jsfiddle.net/BlackLabel/dsnrbfgL/

**Closed** 2022-11-14 16:08 UTC
Labels: Type: Bug, Product: Highcharts, Flow: Review in progress
