### ISSUE TITLE
'showLastLabel' flag is not working

### ISSUE THREAD

**Issue by ramses10** [highcharts/highcharts#14956] opened 2021-01-20 07:34 UTC
#### Expected behaviour
If 'showLastLabel' flag on 'xAxis' is active the last label should always be shown.

#### Actual behaviour
Last label is not shown, see example in jsfiddle.

#### Live demo with steps to reproduce
https://jsfiddle.net/dgxz8Ln9/

The last label should be '19.01.21'.

#### Affected browser(s)
All

**Comment by KacperMadej** [comment] 2021-01-20 17:02
Hi @ramses10 

Thank you for reporting the problem.

`showLastLabel` hides the last label if set to `true` - please compare your demo with this one: https://jsfiddle.net/BlackLabel/ehy9Lord/

If you are interested in displaying ticks with labels you could check tick-related options that will help with getting the desired chart.
- https://api.highcharts.com/highcharts/xAxis.tickPositions
- https://api.highcharts.com/highcharts/xAxis.tickPositioner

Here's a demo based on your code: https://jsfiddle.net/BlackLabel/ehy9Lord/1/

The issue is not a bug and will be closed as such.
If you have any more questions please let me know.
For technical support please use any of the available support channels - https://www.highcharts.com/blog/support/

**Closed by KacperMadej** 2021-01-20 17:02 UTC
Labels: Type: Not a bug
