### ISSUE TITLE
Stacked column '0' point doesn't look great

### ISSUE THREAD

**Issue by rmetrich** [highcharts/highcharts#2385] opened 2013-10-21 15:38 UTC
When having a stacked column with 0 sum (all series return 0 for that point), the sum (0) above the column is printed in light grey compared to other points.

Example: look at 1st column ("Apples")

http://jsfiddle.net/mWeZV/

![capture d cran - 21102013 - 17 35 07](https://f.cloud.github.com/assets/1163635/1373771/97216af2-3a66-11e3-99a6-ba833e82b52a.png)

OS is Ubuntu 12.04/amd64 with Chromium or Firefox browser (same result).

**Comment by KacperMadej** [comment] 2018-05-02 18:35
Suggested solution can be used as a workaround. There's a duplicate of this problem, but is described more precisely and/or is more general, so I'm closing this issue as a duplicate of the #7007

**Closed by KacperMadej** 2018-05-02 18:35 UTC
