### ISSUE TITLE
Area redraw error

### ISSUE THREAD

**Issue by andrei4ik1997** [highcharts/highcharts#18293] opened 2023-01-13 10:17 UTC
Cannot read properties of undefined (reading '0' in **k ? **b[0]** : b[1]**) at h
 c.prototype.getGraphPath = function (a) {
        var c = G.prototype.getGraphPath,
            e = this.options,
            f = e.stacking,
            g = this.yAxis,
            l = [],
            t = [],
            r = this.index,
            A = g.stacking.stacks[this.stackKey],
            d = e.threshold,
            q = Math.round(g.getThreshold(e.threshold));
        e = n(e.connectNulls, "percent" === f);

        var h = function (b, c, e) {
          var h = a[b];
          b = f && A[h.x].points[r];
          var k = h[e + "Null"] || 0;
          e = h[e + "Cliff"] || 0;
          h = !0;

          if (e || k) {
            var m = (k ? b[0] : b[1]) + e;
            var n = b[0] + e;
            h = !!k;
          } else !f && a[c] && a[c].isNull && (m = n = d);

          "undefined" !== typeof m && (t.push({
            plotX: z,
            plotY: null === m ? q : g.getThreshold(m),
            isNull: h,
            isCliff: !0
          }), l.push({
            plotX: z,
            plotY: null === n ? q : g.getThreshold(n),
            doCurve: !1
          }));
        };

        a = a || this.points;
        f && (a = this.getStackPoints(a));

        for (var k = 0, b = a.length; k < b; ++k) {
          f || (a[k].leftCliff = a[k].rightCliff = a[k].leftNull = a[k].rightNull = void 0);
          var p = a[k].isNull;
          var z = n(a[k].rectPlotX, a[k].plotX);
          var w = f ? n(a[k].yBottom, q) : q;
          if (!p || e) e || h(k, k - 1, "left"), p && !f && e || (t.push(a[k]), l.push({
            x: k,
            plotX: z,
            plotY: w
          })), e || h(k, k + 1, "right");
        }

        h = c.call(this, t, !0, !0);
        l.reversed = !0;
        p = c.call(this, l, !0, !0);
        (w = p[0]) && "M" === w[0] && (p[0] = ["L", w[1], w[2]]);
        p = h.concat(p);
        p.length && p.push(["Z"]);
        c = c.call(this, t, !1, e);
        p.xMap = h.xMap;
        this.areaPath = p;
        return c;
      };

**Comment by pawellysy** [comment] 2023-01-13 10:55
Hello @andrei4ik1997, thanks for reporting the issue!
Could you share the demo, where the issue is reproduced? Here is the demo, where you can start: https://jsfiddle.net/BlackLabel/9b1p5vkn/

**Comment by pawellysy** [comment] 2023-01-25 11:22
Closing - No reproduction steps

**Closed** 2023-01-25 11:22 UTC
Labels: Status: Can't reproduce, Status: Pending reply
