### ISSUE TITLE
Pattern fill img distortion after changing the browser tab

### ISSUE THREAD

**Issue by mateuszkornecki** [highcharts/highcharts#13713] opened 2020-06-15 06:12 UTC
#### Expected behaviour
![Screenshot 2020-06-15 at 07 53 39](https://user-images.githubusercontent.com/50931078/84622702-eb7c0380-aedd-11ea-9af1-6d893431c050.png)

#### Actual behaviour
When I go back to the page where the chart containing pattern-fill (image) was located, the image is randomly distorted. After refreshing the page everything is back to normal. 

I observed the same behavior after scrolling to the bottom of the page so that the graph is not visible - after scrolling back to the chart it might be distorted (the chart needs to be out of the view for some time).

I was able to reproduce the issue on google chrome only.

![Screenshot 2020-06-15 at 07 53 20](https://user-images.githubusercontent.com/50931078/84622727-00f12d80-aede-11ea-99c0-a7f363937703.png)
![Screenshot 2020-06-15 at 07 52 48](https://user-images.githubusercontent.com/50931078/84622714-f6cf2f00-aedd-11ea-881a-643b3b2d97e6.png)

#### Live demo with steps to reproduce
1/ Open [this demo](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/series/pattern-fill-pie)
2/ Open another page in the new tab, spend some time (in my case 30sec is enough) there
3/ Go back to the tab with the chart, check pattern-fill with the image.

#### Product version
All

#### Affected browser(s)
Google Chrome Version 83.0.4103.97 (Official Build) (64-bit)

#### Operating system
macOS 10.15.5

**Comment by Izothep** [comment] 2020-06-15 06:21
It looks to be working well in Google Chrome Version 80.0.3987.163 (Official Build) (64-bit)

**Comment by sebastianbochan** [comment] 2020-06-15 10:58
_Interal note_
I was able to reproduce the issue. 

Chrome: 83.0.4103.97
MacOSX: 10.14.6 (18G103)

Setting the unique id of pattern, also does not solve the problem.

Demo:
- https://jsfiddle.net/BlackLabel/6bok5zg1/

@oysteinmoseng any ideas?

**Comment by oysteinmoseng** [comment] 2020-06-15 11:36
I was also able to reproduce this reliably. This is 100% a browser bug, there is no change in the SVG before/after focusing the other tab/scrolling. I suggest filing a bug report with Chrome.

**Comment by sebastianbochan** [comment] 2020-06-15 11:45
@oysteinmoseng Im not really sure, because when I run the demo: https://jsfiddle.net/BlackLabel/zr4wj5yu/ all works properly.

**Comment by oysteinmoseng** [comment] 2020-06-15 11:52
Pattern fills use `fill="url(#xyz)"` referencing `<pattern>` elements, so this is a different use case. The bug can even be reproduced by downloading the SVG and opening the pure SVG file in Chrome, so this is definitely not a Highcharts issue.

**Comment by oysteinmoseng** [comment] 2020-06-15 12:00
Pure SVG reproduction: https://jsfiddle.net/t03bz18s/

**Comment by pawelfus** [comment] 2020-06-18 11:09
Already reported: https://bugs.chromium.org/p/chromium/issues/detail?id=1095915&q=svg%20pattern&can=2

**Comment by oysteinmoseng** [comment] 2020-08-03 08:45
Closing, as this seems fixed in latest chrome.

**Closed by oysteinmoseng** 2020-08-03 08:45 UTC
Labels: Type: Bug
