### ISSUE TITLE
In histogram chart,the gap between the bar is different

### ISSUE THREAD

**Issue by ma1990213** [highcharts/highcharts#13237] opened 2020-04-01 06:07 UTC
#### Expected behaviour
The gap between the bar is same

#### Actual behaviour
The gap between the bar is different

#### Live demo with steps to reproduce
https://jshare.com.cn/temp/FIGT61

![image](https://user-images.githubusercontent.com/17824026/78104595-046a3200-7422-11ea-95a8-aba7cf282442.png)
![image](https://user-images.githubusercontent.com/17824026/78104623-1350e480-7422-11ea-90a0-f1c421ac5250.png)

#### Product version
"highcharts": "8.0.2",
    "highcharts-3d": "^0.1.7",
    "highcharts-grouped-categories": "^1.1.3",
    "highcharts-regression": "^2.0.1",
    "highcharts-vue": "^1.3.5"

#### Affected browser(s)
Chrome 80.0.3987.149

**Comment by pawelfus** [comment] 2020-04-02 12:35
Thanks for reporting the issue @ma1990213 

This is expected behaviour: to prevent antyaliasing, we render them at full pixel. You can prevent this using simple snippet, but columns are going to be blurred:
```js
Highcharts.seriesTypes.column.prototype.crispCol = function (x, y, w, h) {
	return {
    	x: x,
        y: y,
        width: w,
        height: h
    };
};
```

Demo: https://jsfiddle.net/BlackLabel/kv61aydL/

Closing as duplicate of #5755

**Closed by pawelfus** 2020-04-02 12:35 UTC
