### ISSUE TITLE
Tooltip`s stickOnContact param is not working when useHTML is enabled

### ISSUE THREAD

**Issue by stanvol** [highcharts/highcharts#13310] opened 2020-04-14 15:57 UTC
#### Expected behaviour
Tooltip should be shown while cursor is over tooltip.

#### Actual behaviour
Default tooltip`s behavior.

#### Product version
Highcharts 8.0.4

#### Affected browser(s)
All

**Comment by pawelfus** [comment] 2020-04-15 05:17
Thanks for reporting this issue @stanvol 

#### Live demo with steps to reproduce the issue
Demo: https://jsfiddle.net/BlackLabel/x8L0etcn/

Steps:
- mouse move from point (1, 1) to (1, 2)

FYI @bre1470

**Comment by Tom-E** [comment] 2021-07-21 19:45
It looks like this is regressed? I am able to reproduce the bug on the latest highcharts and the original repro demo above.

**Comment by raf18seb** [comment] 2021-07-22 11:06
Hi @Tom-E,

I am not able to reproduce the issue in the newest Highcharts. Could you double-check and provide the exact steps to reproduce it?

**Comment by Tom-E** [comment] 2021-07-22 17:59
![useHtmlBreaksStickOnContact](https://user-images.githubusercontent.com/36723427/126686595-bd3b7701-7ea7-4bd9-8e85-7320ab494772.gif)
this is what i'm seeing @raf18seb

**Comment by raf18seb** [comment] 2021-07-23 08:29
@Tom-E thanks for providing more info.

Indeed, it's a regression after https://github.com/highcharts/highcharts/commit/8d79d263b54b89b426c15d36aad82e822db1bc7a

As a workaround, you can bring back the old code, but it will probably brake #14110
Demo: https://jsfiddle.net/BlackLabel/7hdpfrc5/

Reopening. FYI @khlieng

**Comment by khlieng** [comment] 2021-07-23 09:08
This is getting fixed in #15960, I have now replaced the `useHTML` fix with just dealing with the regression, we can probably just close this again as its the same as #14143 (split is unrelated).

**Comment by raf18seb** [comment] 2021-07-23 09:57
I'd keep it open until we are sure it's fixed. If you are sure - feel free to close.

**Comment by khlieng** [comment] 2021-07-23 10:29
So `split` wasnt actually unrelated, the regression made it look like it was, `split` broke again after only fixing the regression 🤔, since that makes this issue less of a duplicate I will add it to the PR as well.

**Closed** 2021-08-13 08:31 UTC
Labels: Type: Regression, Status: Has workaround
