### ISSUE TITLE
container.ontouchmove will only be fired once under android

### ISSUE THREAD

**Issue by kaoshijuan** [highcharts/highcharts#4273] opened 2015-06-10 15:33 UTC
if the browser is under android, the touchmove event will only be fired onced until another touchstart event begins.

to fix this problem, maybe you should add one line code:
e.preventDefault(); 
after the code :   pointer.onContainerTouchMove(e);

**Comment by kaoshijuan** [comment] 2015-06-23 12:05
how about this problem ???

**Comment by pawelfus** [comment] 2018-08-28 12:06
Duplicate of #4606

**Closed by pawelfus** 2018-08-28 12:06 UTC
