### ISSUE TITLE
Cannot find module '../modules/stock' in file highcharts/highstock.d.ts

### ISSUE THREAD

**Issue by whoamix** [highcharts/highcharts#9750] opened 2018-12-22 13:04 UTC
#### Expected behaviour
Working highcharts package in Vue.js and Typescript project.

#### Actual behaviour
I've noticed that the path to StockModule in highstock.d.ts is invalid. When I've corrected the path by myself everything started works.
```
ERROR in /Frontend/node_modules/highcharts/highstock.d.ts
6:25 Cannot find module '../modules/stock'.
    4 |
    5 | import * as Highcharts from './highcharts';
    6 | import StockModule from '../modules/stock';
       |                         ^
    7 |
    8 | export = Highcharts;
    9 |
```

#### Product version

Highcharts version 7.0.1 
#### Affected browser(s)
All

**Comment by cebor** [comment] 2018-12-23 13:38
Same issue here, my library does not build for highcharts 7.

Highmaps does not have this issue.

**Comment by sebastianbochan** [comment] 2018-12-24 09:20
Hi @cebor,
Thank you for reporting.

**Internal note**
@bre1470 As I remember it has been already fixed, but cannot find a commit. Am I wrong?

**Comment by KacperMadej** [comment] 2018-12-27 10:21
It's reported here: https://github.com/highcharts/highcharts/issues/9705#issuecomment-448761081
so closing this issue as a duplicate of #9705

**Closed by KacperMadej** 2018-12-27 10:21 UTC
Labels: Bug
