### ISSUE TITLE
Axis Min and Max Cannot be Set while the Axis is in a 'zoomed' State.

### ISSUE THREAD

**Issue by Sakkyoku-Sha** [highcharts/highcharts#13384] opened 2020-04-28 00:35 UTC
#### Expected behaviour
The bounds of a graph should be able to be changed while it is zoomed. Updating an Axis's bounds manually should always work.

#### Actual behaviour
Changing the range of a Axis which is zoomed is not possible.

#### Live demo with steps to reproduce
https://jsfiddle.net/5jvxz9on/

Click the Change Range Button, it should work.

Zoom into the graph.
Click the "Change Range" button, notice how it no longer work. 

Furthermore clicking "Reset Zoom no longer properly resets the zoom". 

#### Product version
Highcharts Latest

**Comment by sebastianbochan** [comment] 2020-04-28 07:24
Hi @Sakkyoku-Sha,
Thank you for reporting about the problem. If you would like to set a range on the xAxis, you can use [setExtremes](https://api.highcharts.com/class-reference/Highcharts.Axis#setExtremes) function.

Demo:
- https://jsfiddle.net/BlackLabel/ayqmd38c/

Im closing the case as not a bug.

**Closed by sebastianbochan** 2020-04-28 07:24 UTC
Labels: Type: Not a bug
