### ISSUE TITLE
Automatically adjust datetime x axis to dates found in series data 

### ISSUE THREAD

**Issue by gitnik** [highcharts/highcharts#4120] opened 2015-04-21 13:15 UTC
When a user clicks on of the buttons inside rangeSelector, we load the according data for that period. What happens is when the user goes from 2 years to for example 3 years is that it will load the data for 3 years, but the x-axis will still show 2 years and only trough panning (which I actually want to disable), can I see that missing year of data. 
My question is whether it's possible to have the x-axis automatically adjust its min and  max according to the data I passed in

**Comment by highslide-software** [comment] 2015-04-22 06:35
See http://api.highcharts.com/highstock#navigator.adaptToUpdatedData.

If this doesn't resolve your problem, please set up a live demo.

**Comment by gitnik** [comment] 2015-04-22 08:00
I'm not even using the navigator so that doesn't really help. I'll try to get a demo up running in the next few days

**Comment by jon-a-nygaard** [comment] 2016-06-16 14:21
Closing this issue since we are unable to reproduce it, and it is pending a reply. If anyone should have further information about this issue, please comment and/or reopen.

**Closed by jon-a-nygaard** 2016-06-16 14:21 UTC
Labels: Cant reproduce, Pending reply

**Comment by gitnik** [comment] 2016-06-16 14:41
Fair enough. Sorry for never getting around to giving more info on this
