### ISSUE TITLE
Memory leak when trending raw data in high chart

### ISSUE THREAD

**Issue by abhik04** [highcharts/highcharts#5661] opened 2016-09-07 10:29 UTC
#### Expected behaviour
When we run the trend chart with 8 pens getting data every second the raw data is plotted for a time interval of 8 hrs there should not be any memory leak

#### Actual behaviour
When we run the trend chart with 8 pens getting data every second the raw data is plotted for a time interval of 8 hrs and i leave the trend plotting data for around 15 hrs, there is a memory leak and the application consumes around 1.35 GB of memory

#### Live demo with steps to reproduce
GE Digital - license ID is 100038820-1nk6g4

#### Affected browser(s)
Chrome

___
_Edit:_
The points are being added up until 8 hours. After that, points older than 8hr are removed, but the memory continues to grow.

**Comment by TorsteinHonsi** [comment] 2016-09-07 20:04
Thanks for report!

We take memory leaks very seriously and will give this top priority. However we need to see a live reproduction, otherwise we have nothing to debug on.

> When we run the trend chart with 8 pens

By _trend_ do you mean a Highcharts line chart? And what do you mean by _pen_?

I have tried to reproduce the bug by setting up an updating chart with 8 line series. Does this resemble what you have? http://jsfiddle.net/u56b7f1y/

**Comment by abhik04** [comment] 2016-09-08 05:46
Hi
  Thanks for the support, by trend we meant highchart line chart and by pens we meant line series. We saw your example and you have 8 pens.

In our application, we are trending 8 line series for a time period of 8 hours and during the entire 8 hours we are storing the data and the same is being displayed in the highchart.

In you example if you can trend data for 8 hours and also store the same you can observe the memory leak.

Note: The data is injected at a rate 1 sec.

**Comment by TorsteinHonsi** [comment] 2016-09-08 06:49
Can you make modifications to my jsFiddle example so that it demonstrates your setup as closely as possible?

> In you example if you can trend data for 8 hours and also store the same you can observe the memory leak.

If you store 1s data for 8 hours it will take up a lot of memory. Are you sure the memory build-up is related to the chart at all? I mean, if your browser holds 8 hours worth of 1s data across 8 series, it is `8 * 8 * 60 * 60 = 230,400` data points. 

Also you say that the same data is being displayed in the chart, does that mean that you're running addPoint without the `shift` parameter [like this](http://jsfiddle.net/u56b7f1y/1/)?

Again, a live reproduction of your setup would be invaluable, then I don't have to try to guess your setup, but can get started debugging right away.

**Comment by TorsteinHonsi** [comment] 2016-09-08 07:21
I did some experimenting based on [this fiddle](http://jsfiddle.net/u56b7f1y/2/).

The first snapshot shows memory allocation when [addPoint](http://api.highcharts.com/highcharts/Series.addPoint) is called with the `shift` parameter to true. As you can see there is no memory build-up after 3000 iterations:

![skjermbilde 2016-09-08 kl 09 07 09](https://cloud.githubusercontent.com/assets/227836/18340164/cb086142-75a3-11e6-8cb9-6c74406876e7.png)

The second shapshop shows the allocation when the `shift` parameter is false. As you can see (and as we can expect), the memory builds up as we add points to the chart, because the total number of points increases. You can see a garbage collection event at ~2.4 seconds.

![skjermbilde 2016-09-08 kl 09 19 01](https://cloud.githubusercontent.com/assets/227836/18340499/9b72df5a-75a5-11e6-829f-0ba8c3089431.png)

**Comment by abhik04** [comment] 2016-09-08 13:04
As per the project requirement, the user can select a time span of 5min, 30 min, 1hr, 4hr 8 hr or 24 hr and view the entire data of the selected time span in the chat at one instance.

For example, if the user have selected 8 hr time span, the data is plotted in the trend for 8 hrs without any shift and the user can view the entire 8 hr data in the trend in one view. For the entire 8 hr the data is stored in the chart. After elapsing the first 8 hr, there is a shift of 1 hr, now the chart shows the last 7 hr and then current incoming data.

**Comment by abhik04** [comment] 2016-09-08 15:22
In case you need a demo of our product and look into the issue, you can mail to the following mail address and set up a time and conference.

abhik.banerjee@ge.com
frankn.parker@ge.com

**Comment by TorsteinHonsi** [comment] 2016-09-09 06:55
Okay, I'll contact you for a conference so we can discuss how to set up the live demo.

**Comment by abhik04** [comment] 2016-09-12 08:59
I have just pre-poned the conference, can you please confirm if you are available for the new time?

**Comment by abhik04** [comment] 2016-09-12 09:39
Running a test with 8 pens configured to get data every second. Have the time series configured for 2 hr. Started the test with memory consumption of 160MB. After running the test for 1 hr, currently the memory consumption is 320 MB.

![1hrdata](https://cloud.githubusercontent.com/assets/12654725/18431458/9953b70a-78fa-11e6-952d-f4a2a5b8b4b4.png)

Will upload one more snapshot once 2 hr is elapsed.

**Comment by TorsteinHonsi** [comment] 2016-09-12 10:58
Thanks! The question is whether this is a "leak" at all - as noted above, as we continue to add points to the chart, all the points need to be kept in memory. So it is to be expected that the memory allocation of the browser grows. The question is how much. 

The raw data itself after eight hours will consist of 230,400 data points as per the calculation above. Let's assume that each of these data points have an x value and an y value, each of 8 bytes (X values are probably more, Y are less). So the raw data holds 230,400 x 16 = 3,686,400 = 3.6 MB. Which is far from what we see in your screen shot. 

So I think I see the same issue with http://jsfiddle.net/highcharts/u56b7f1y/6/. When I let it run 1000 iterations, the tab's memory usage typically increases by tens of MB. At the same time, when doing heap snapshots and comparing them, the heap only increases by a few MB. So the overall browser memory usage is significantly larger than the heap.

**Comment by abhik04** [comment] 2016-09-12 11:06
ok, can we get into a call now?

**Comment by TorsteinHonsi** [comment] 2016-09-12 11:29
The call cleared up a detail on the issue: The points are being added up until 8 hours. After that, points older than 8hr are removed through `series.removePoint`, but the memory continues to grow.

**Comment by TorsteinHonsi** [comment] 2016-09-12 12:28
I updated the test to match the description, with a couple of modifications:
* The updates are faster so we don't have to wait 8 hours for every iteration :)
* Start removing points after 1000 iterations for the same reason.

See http://jsfiddle.net/highcharts/u56b7f1y/7/. However, I am not sure I see the leak here. After 1000 iterations, I see 395 MB used, after 18k there is 402 MB and after 26k it's 400 MB. So it seems to stabilize. Will continue testing. 

@abhik04 How does my test perform comparing to your own issue report?

**Comment by abhik04** [comment] 2016-09-12 12:38
I see that the memory continue to increase, i have not reached any stabilize point yet.
25200 - 320 MB
50400 - 414 MB
201600 - 1GB
378000 - 1.3 GB

**Comment by TorsteinHonsi** [comment] 2016-09-12 13:13
Yes, I can see it too now. It creeps up to 1GB after 50k iterations.

**Comment by TorsteinHonsi** [comment] 2016-09-12 13:25
The interesting part now is that the browser tab's memory increases, but when taking heap snapshots, they don't increase. Are you seeing the same?

**Comment by abhik04** [comment] 2016-09-13 07:01
Since the team is currently out of office, i am unable to confirm you this finding. But it would be great if you can see why browser tab memory increases.

**Comment by abhik04** [comment] 2016-09-13 07:26
Just had a discussion with the developer, when there was 50K points, the browser memory was 400 MB and the heap memory was around 280 MB, so there seems to be a increase in heap snapshot as well.

**Comment by TorsteinHonsi** [comment] 2016-09-13 11:34
> Just had a discussion with the developer, when there was 50K points, the browser memory was 400 MB and the heap memory was around 280 MB, so there seems to be a increase in heap snapshot as well.

Was that with your original page or with my jsFiddle reproduction? If it was your original, please modify the jsFiddle so that it behaves the same.

See http://stackoverflow.com/questions/29550358/chrome-tab-memory-keeps-growing-heap-size-stays-the-same for a similar issue as I see, with a static heap.

**Comment by TorsteinHonsi** [comment] 2016-09-14 09:10
Today's meeting summary:
* The client's chart has _shared tooltip_, _one Y axis per series_ and _spline series_.
* After running the chart for 1hr, the client demonstrated how to reduce the time frame to 5 minutes. In this process, the points should be removed and memory be released. But the heap actually increased.
* The client will work on getting a live demo up and running.
* Meanwhile we will adapt our live demo to the new information and try to reproduce the heap memory issue.
* We will focus on heap memory first, as tab memory is more out of our control.

**Comment by abhik04** [comment] 2016-09-14 11:24
were you able to replicate our scenario with shared tooltip, one Y axis per series and spline series?

**Comment by TorsteinHonsi** [comment] 2016-09-14 11:29
I'm working on it. Meanwhile you can test yourself with http://jsfiddle.net/highcharts/aLndk2do/show.

**Comment by abhik04** [comment] 2016-09-14 11:47
it would be great if you can include one reset button, clicking on that it should reset the previously drawn trend and should start from fresh, this would help me to check if heap memory reduces when i hit reset - similar to when i moved from 1 hr to 5 min in our application

**Comment by TorsteinHonsi** [comment] 2016-09-14 12:11
> it would be great if you can include one reset button

You can add that yourself, that's the idea with jsFiddle. Just do your modifications to http://jsfiddle.net/highcharts/aLndk2do, click Save or Update and share the new URL here along with steps to reproduce.

**Comment by TorsteinHonsi** [comment] 2016-09-14 12:25
I have been running the sample for some hours now. Each iteration _i_ adds and removes one point to each of the eight series. The heap memory usage is as follows:

i = 1000: 14.2 MB
i = 18k: 14.2 MB
i = 37k: 16.4 MB
i = 52k: 16.4 MB

The memory usage goes up by 2 MB between 18k and 37k, but it's nowhere near what you see in your app. 

Next test, I implemented the reset button. See http://jsfiddle.net/highcharts/aLndk2do/1/.
When i = 0 (before adding points) the heap size is 8.9 MB. After running 2500 iterations, heap is 13.3MB as we should expect when there are 8000 data points in memory. After clicking reset, the heap is released and now shows 8.7 MB, less that we had when starting out.

**Comment by TorsteinHonsi** [comment] 2016-09-15 09:48
Any success in reproducing the leak yet?

**Comment by abhik04** [comment] 2016-09-15 10:31
can you please join the meeting, i have the webex and call up. we can show our progress and discuss

**Comment by TorsteinHonsi** [comment] 2016-09-15 11:13
Sorry, I was in a meeting all morning and didn't see your invitation. Please put the demo online so we can start debugging.

**Comment by abhik04** [comment] 2016-09-15 11:30
We have added our code into JSFiddle - https://jsfiddle.net/7b0gadua/11/

We have provided all the dependencies and functions that we are currently using for our application
The code in jsfiddle is currently not able to fetch data and plot the trend, if you can help us do that, it would great.

I am also sending you a mail for the our file that contains the code. Please use that as your reference.

**Comment by TorsteinHonsi** [comment] 2016-09-16 07:23
Thanks! There is so much going on here that is not directly related to Highcharts, so I think we need to isolate things a bit. But the first step is to get the fiddle to actually run with dummy data, so that we can measure the memory usage. For example, your `setupUpdateTimer` is never called. 

You can emulate the backend by inserting dummy data in the appropriate place of your application.

**Comment by abhik04** [comment] 2016-09-16 08:31
The team here is working hard to get the trend data running in JSfiddle, once we are successful, i will mail you the jsfiddle link and if required we can have a quick call.

**Comment by abhik04** [comment] 2016-09-16 09:49
We are now able to get the data in JSfiddle. I have sent you an invite to view and discuss the issue.
jsfiddle link:
https://jsfiddle.net/runw2w4g/1

**Comment by TorsteinHonsi** [comment] 2016-09-16 11:28
I've run this for an hour now, and see the memory slowly creeping up from 12.1 MB to 12.8 MB. See the snapshot.

<img width="986" alt="skjermbilde 2016-09-16 kl 13 27 46" src="https://cloud.githubusercontent.com/assets/227836/18584502/70115f86-7c11-11e6-9358-e65d41c7b625.png">

**Comment by TorsteinHonsi** [comment] 2016-09-16 12:55
After the edited jsFiddle, we are able to see some string values building up. Will continue to investigate on those.

**Comment by TorsteinHonsi** [comment] 2016-09-16 13:16
@abhik04 These strings piling up indicate that something is leaking either in the `getBBox` function or in the `xAxis.names` logic. Both of these areas have been modified since the latest release. Can you load https://github.highcharts.com/highstock.src.js and let your project run for a while and see if it helps on the memory issue? My preliminary, short-term tests show that the strings are no longer leaking...

**Comment by pawelfus** [comment] 2016-10-17 11:52
Closing as not related to Highcharts after all. Please, reopen if needed.

**Closed by pawelfus** 2016-10-17 11:52 UTC
Labels: Undecided
