### ISSUE TITLE
with bar chart ,the flag shape and it's title are not at same position

### ISSUE THREAD

**Issue by 21k** [highcharts/highcharts#6395] opened 2017-02-22 10:58 UTC
#### Expected behaviour
the flag shape and  it's title at the same position
#### Actual behaviour
![823086867684091312](https://cloud.githubusercontent.com/assets/13778916/23208908/d9dd3d0c-f931-11e6-9231-f228d6c34a12.png)

1. Both position-bases  （svg and dom）are relative to top-left.
2. while bar chart turns svg position-base from top-left to bottom-right
3. while dom position-base stays at top-left .

#### Affected browser(s)

chrome latest

**Comment by pawelfus** [comment] 2017-02-22 12:22
Hi @21k 

Could you recreate issue in jsFiddle, so we can check this? Thanks!

**Comment by 21k** [comment] 2017-03-02 04:17
@pawelfus  http://jsfiddle.net/se1Lu7fp/1/

**Comment by pawelfus** [comment] 2017-03-02 09:39
Thank you for the demo!

It looks like we have two issues in this place:

- `useHTML` label is not positioned at the same place as SVG element, without `useHTML` both items have the same place: http://jsfiddle.net/se1Lu7fp/4/
- flag position is wrong: flag should be placed on xAxis (vertical in this case)

**Comment by KacperMadej** [comment] 2017-03-03 11:21
Minimal demo: http://jsfiddle.net/dogj6c93/

**Comment by pawelfus** [comment] 2018-04-09 15:07
Duplicate of #4960 - should be fixed in the upcoming release: http://jsfiddle.net/BlackLabel/se1Lu7fp/5/

**Closed by pawelfus** 2018-04-09 15:07 UTC
Labels: Bug, Highstock
