### ISSUE TITLE
Cannot read property 'series' of null

### ISSUE THREAD

**Issue by hokletrain** [highcharts/highcharts#10303] opened 2019-03-12 23:01 UTC
#### Expected behaviour
Should be able to read series. 

#### Actual behaviour
Bug occurs when clicking range selector buttons, while using drag and drop , cant read series. 

#### Live demo with steps to reproduce
http://jsfiddle.net/juo2gcas/

#### Product version
Highstock 

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment] 2019-03-13 11:01
Hi @hokletrain,
Thank you for reporting about the problem. The problem is known bug and is already fixed in the master branch here:
- http://jsfiddle.net/BlackLabel/j5hz3suq/

Please be aware that this version is only beta.

If you find any issues, please reopen the ticket with details.

**Closed by sebastianbochan** 2019-03-13 11:01 UTC
