### ISSUE TITLE
Custom patterns not showing in Download or print option of charts

### ISSUE THREAD

**Issue by VartikaGarg** [highcharts/highcharts#5203] opened 2016-04-12 06:45 UTC
Highchart package provides total of 9 different patterns by default.
I have scenarios where approx 12 patterns are to be used - hence I have used custom patterns.

Now when I try to print or download the chart in png/jpeg or any other format, it shows a blank chart with no patterns.

Kindly suggest.

**Comment by pawelfus** [comment] 2016-04-12 10:58
Hi,

Thank you for reporting. Could you provide jsFiddle demo with the issue? We will check this. The problem may be with paths - exporting server requires **absolute** paths, to get access to the pattern.

**Comment by jon-a-nygaard** [comment] 2016-07-22 07:47
Closing this issue since we are unable to reproduce it, and it is pending a reply. Should anyone have further information on the issue, please comment and reopen.

**Closed by jon-a-nygaard** 2016-07-22 07:47 UTC
Labels: Cant reproduce, Pending reply
