### ISSUE TITLE
Tooltip showing wrong value on overlaying series 

### ISSUE THREAD

**Issue by trpriel** [highcharts/highcharts#5150] opened 2016-03-24 10:11 UTC
When a couple of series overlay  the tooltip doesn't show the most visible series but rather the first series that was added. The right behaviour is that the user will see the tooltip of the visible series.
See example: http://jsfiddle.net/7rprox05/1/

Even when adding a z-index to the series I want to be visible, the tooltip will still show the first added series.
See example: 
http://jsfiddle.net/7rprox05/2/

The problem lies in highcharts.src.js:10044
` // Find absolute nearest point
                each(kdpoints, function (p) {
                    pointDistance = !shared && p.series.kdDimensions === 1 ? p.dist : p.distX; // #4645

                    if (p && typeof pointDistance === 'number' && pointDistance < distance) {
                        distance = pointDistance;
                        kdpoint = p;
                    }
                `});``

When the first point comes in you set him as the nearest point. It should be pointDistance <= distance and that way you will get the last series rather then the first.
Also you don't check the point's series zIndex to see if there is a series overlaying the point.

**Comment by pawelfus** [comment] 2016-03-24 11:42
Thank you for reporting. This is duplicate of #4679.

**Closed by pawelfus** 2016-03-24 11:42 UTC
