### ISSUE TITLE
dataLabels on candleSticks are not shown correctly when  zoomed out

### ISSUE THREAD

**Issue by ourarash** [highcharts/highcharts#8454] opened 2018-06-11 16:57 UTC
#### Expected behaviour
In HighStock candlestick chart, dataLabels always shown as specified by the formatter function, no matter what the zoom level is.

#### Actual behaviour
When  zoomed out, dataLabels are not shown based on the formatter function, but they show the actual values. Let's say I set the formatter to show a text "Hi" on top of each candleStick. This works well when we zoom in. But when zoomed out, the formatter function is ignored and the actual close values are shown.

#### Live demo with steps to reproduce

https://jsfiddle.net/2Lg3wy87/1/

 **Zoom in "3m" to see the word "Hi" on each candle.**

#### Product version

6.1.0

This was not the case in previous versions.

**Comment by sebastianbochan** [comment] 2018-06-12 07:45
Hi @ourarash,
You should declare `dataLabels.formatter` in the series object, not point.

Fixed demo:
- https://jsfiddle.net/wk1Lsqt4/

**Comment by pawelfus** [comment] 2018-06-12 09:34
Just a word of explanation: 

This is caused by [dataGrouping](https://www.highcharts.com/docs/advanced-chart-features/data-grouping), where individual points' options are not applied to a grouped point (e.g. how to apply multiple dataLabels.formatter to one point?). When points are grouped, only y-values are calculated (according to the [`dataGrouping.approximation`](https://api.highcharts.com/highstock/plotOptions.series.dataGrouping.approximation) method). You can disable dataGrouping (but this may affect performance) or, as Sebastian said, use `series.dataLabels.formatter` instead of `point.dataLabels.formatter`.

> This was not the case in previous versions.

Could you point me to the version you have tried? I think this has always been working that way.

**Comment by ourarash** [comment] 2018-06-12 16:35
Thanks for the explanation.

I just rolled back to version 6.0.7 and noticed that the behavior was different and the labels were printed as I expected without applying Sebastian's suggestion. However, I  should mention that I do not assign anything to `dataGrouping` in my code. So it looks like the behavior has definitely changed between 6.0.7 and 6.1.0.

**Comment by pawelfus** [comment] 2018-06-13 08:55
Just tested your demo with v6.0.7: https://jsfiddle.net/BlackLabel/2Lg3wy87/8/ - looks the same for me. `dataGrouping` is enabled since.. I remember :) Probably from version Highstock v1. It's enabled by default in Highstock, not available in Highcharts. I think it's rather case where you have different amount of points, or width of the chart, so `dataGrouping` does not affect your chart.

**Comment by pawelfus** [comment] 2018-10-03 11:28
Works fine since v6.1.4 - closed as resolved in #8999 

Added in API details: https://api.highcharts.com/highstock/plotOptions.series.dataGrouping

> If data grouping is applied, the grouping information of grouped points can be read from the [`Point.dataGroup`](https://api.highcharts.com/class-reference/Highcharts.Point#.dataGroup). If point options other than the data itself are set, for example `name` or `color` or custom properties, the grouping logic doesn't know how to group it. In this case the options of the first point instance are copied over to the group point. This can be altered through a custom `approximation` callback function.

**Closed by pawelfus** 2018-10-03 11:28 UTC
Labels: Highstock, Undecided
