### ISSUE TITLE
Vertical stacked column chart with values on end

### ISSUE THREAD

**Issue by hakkim** [highcharts/highcharts#13192] opened 2020-03-24 12:33 UTC
Hi Guys,
Is there any way to create a chart something like this?
![crop](https://user-images.githubusercontent.com/7419977/77425928-6811b100-6dcb-11ea-9d35-1714d1f7b0c7.jpg)
I used vertical stacked column bar to create this. But I am not able to print the value after each bar. Can any one guide me how to do it? Thanks in advance.

**Comment by pawelfus** [comment] 2020-03-24 15:41
Hi @hakkim 

Yes, our support team can help you, see how to reach them: https://www.highcharts.com/blog/support/

Closing as not a bug/feature actually.

**Closed by pawelfus** 2020-03-24 15:41 UTC
Labels: Type: Feature Request
