### ISSUE TITLE
Waterfall Charts - when using negativeColor, the dashed line is not drawn.

### ISSUE THREAD

**Issue by rabishah** [highcharts/highcharts#7862] opened 2018-02-14 05:48 UTC
#### Expected behaviour
Should draw the outline between two column bars. 

#### Actual behaviour
No lines drawn. http://jsfiddle.net/x1qdq8sr/20/ 

If I change the api, negativeColor to upColor, you can see that the dashed line is drawn. Here is a jsFiddle link when using upColor : http://jsfiddle.net/d4w7nmbn/1/

#### Product version
Highcharts 6.0.2

**Comment by pawelfus** [comment] 2018-02-14 10:11
Hi @rabishah 

Thank you for reporting the issue!

**Workaround:**
Show lines in CSS:
```css
.highcharts-waterfall-series path {
  visibility: visible;
}
```

http://jsfiddle.net/BlackLabel/d4w7nmbn/8/

**Comment by pawelfus** [comment] 2018-02-16 16:10
Looks like a duplicate of #7344

**Closed** 2018-03-12 09:34 UTC
Labels: Bug
