### ISSUE TITLE
download and export of high charts leads to 400 error

### ISSUE THREAD

**Issue by Kbauer9** [highcharts/highcharts#20376] opened 2024-01-04 13:02 UTC
#### Expected behaviour
Download of chart is successful

#### Actual behaviour
https://export.highcharts.com/  400 error on our local site and from this export high charts link

**Comment by bm64** [comment] 2024-01-06 10:44
Hello @Kbauer9 

We had a minor problem with export server that should be fixed already. Could you check and confirm if the problem is resolved?

**Comment by cr1stimuresan** [comment] 2024-01-16 09:48
this is still reproducing intermittently 
https://www.highcharts.com/demo/highcharts/treegraph-chart 
![Screenshot 2024-01-16 at 11 47 11](https://github.com/highcharts/highcharts/assets/76202240/e9d6fc1e-56a5-451a-aa56-a939629bdc5b)

**Comment by Yi4l** [comment] 2024-01-16 17:59
There is an error when trying to export the graphic to SVG format, mark network error, with version 11.3.0
![image](https://github.com/highcharts/highcharts/assets/89667651/e9a1c42b-0975-4cb8-9f21-71f6a6c8075e)

Live demo [https://jsfiddle.net/u1hdkjct/](url)

**Comment by TorsteinHonsi** [comment] 2024-01-17 08:40
@cvasseng FYI

**Comment by oysteinmoseng** [comment] 2024-02-12 11:29
Closing this one as fixed now, feel free to comment to reopen if needed.

**Closed by oysteinmoseng** 2024-02-12 11:29 UTC
Labels: Type: Bug, Product: Highcharts
