### ISSUE TITLE
Ability to add and remove multiple points

### ISSUE THREAD

**Issue by priikone** [highcharts/highcharts#4724] opened 2015-11-08 19:32 UTC
Highcharts/Highstock should have ability to add multiple points at the same time instead of one at a time with addPoint().  It's too slow when updating existing chart with large amounts of data, even if chart update is disabled during addition.  It's especially bad when the points to be added are going to be inserted at the beginning of the x-axis and the data to be added is already sorted.  This means addPoint() will always "find" the beginning of the chart by going through the entire dataset; more data you add slower addPoint() gets.

It should be possible to add an array with addPoint() or better to have addPoints(), insertPoints() or addData() where 1) array can be given as argument, 2) insertion index can be given as argument in case the data is already sorted.  Or maybe have ability to splice new array to existing series.

I did quick testing where addPoint took an agument to specify whether to add to beginning instead of to end and that made it a faster with sorted data. Still, it would be better to be able to give the entire array as argument and tell that it's sorted.

Of course since the data is sorted in the chart already there's faster ways to find the correct slot to add to than going through the array linearly, so there's definitely room for optimization in addPoint() (e.g. binary search).

Same goes for removing points.  It should be possible to remove multiple points by giving a range to removePoint().

If there's some undocumented way to efficiently add lots of data to existing chart I'd like to hear about it...

**Comment by priikone** [comment] 2015-11-08 19:58
I did manage to update the chart also by splicing the chart.series[0].options.data to the new already sorted data to be added to the beginning of the chart and then call setData() but surprisingly it wasn't any faster than my modified addPoint()...  Should be faster with even more data points than I'm currently testing with but quite small a difference.

**Comment by highslide-software** [comment] 2015-11-09 08:27
Thanks for your suggestions!

The feature of adding a points in the middle of a sorted data series is a pretty new feature, and wasn't very frequently requested in the first place. I guess that explains why we haven't worked much on optimizing. 

The code for finding the insertion point takes place [here](https://github.com/highslide-software/highcharts.com/blob/v4.1.9/js/parts/Dynamics.js#L281-L288).

As you say, a binary search could perhaps speed things up. We already have a binary search engine for the tooltip, one idea could be to tap into that. But most likely the performance thief is the splicing of arrays, so if we could splice all the points in at once, it would probably be good.

**Comment by KacperMadej** [comment] 2018-10-09 13:15
To better track how popular is this idea the issue is on userVoice: https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/35667478-ability-to-add-and-remove-multiple-points
The most popular ideas are getting implemented.

Closing the issue for now and it might get reopened when the userVoice idea will begin implementation process.

**Closed by KacperMadej** 2018-10-09 13:15 UTC
Labels: Undecided
