### ISSUE TITLE
NoData-Message is displayed although data exists

### ISSUE THREAD

**Issue by devritter** [highcharts/highcharts#9843] opened 2019-01-09 10:34 UTC
#### Expected behaviour
Series with data is rendered, "no data" message should not be displayed

#### Actual behaviour
Series is rendered and "no data" message is visible at the same time.

#### Live demo with steps to reproduce
http://jsfiddle.net/68bxqyuL/4/
Bug only occurs with Boost module and when yAxis.max and yAxis.min is set.

#### Product version
+ Highcharts 7.0.1
+ NoData-Module
+ Boost-Module

#### Affected browser(s)
Chrome, Firefox, Edge

**Comment by sebastianbochan** [comment] 2019-01-09 11:07
Hi @devritter,
Thank you for reporting. The bug is duplicate of https://github.com/highcharts/highcharts/issues/9758 and has been already fixed in the master branch. Will be a part of next official release.

**Closed by sebastianbochan** 2019-01-09 11:07 UTC
