### ISSUE TITLE
Highcharts Graphs are not adapting Windows High contrast Theme.

### ISSUE THREAD

**Issue by msftedad** [highcharts/highcharts#17721] opened 2022-09-09 10:29 UTC
**User Impact**
User who use High Contrast theme will be impacted here as they will not grab information given in the Graphs as graphs are not adapting high Contrast Theme.

**Expected behaviour**
Graphs should adapt high contrast Theme.

**Actual behaviour**
Graphs are not adapting high contrast Theme.

**Test Environment:**
OS: Windows 10 Version Dev (OS Build 21343.1000)
Browser: Microsoft Edge Dev Build 91.0.864.1
URL: https://www.highcharts.com/demo/pie-legend

**Steps to reproduce**
1. Open https://www.highcharts.com/demo/pie-legend on browser.
2. Open Windows Settings app using 'Windows + i' Key.
3. Navigate to 'Ease of Access' menu item and activate it.
4. Then Navigate to 'High Contrast' tab and activate it.
5. Then switch ON 'Turn on high Contrast' toggle button.
6. Select White/Black theme from 'Choose a theme' combo box.
7. Verify that Graphs are adapting high contrast themes or not.

[Attachments.Files.zip](https://github.com/highcharts/highcharts/files/9534583/Attachments.Files.zip)

**Comment by pawellysy** [comment] 2022-09-09 10:49
Closing as a duplicate of #15567

**Closed by pawellysy** 2022-09-09 10:49 UTC
