### ISSUE TITLE
https://jshare.com.cn/temp/OpGGL6 数据这样的时候，图表显示不出来啦

### ISSUE THREAD

**Issue by weixingcai** [highcharts/highcharts#13079] opened 2020-03-04 09:11 UTC
#### Behaviour
桑基图的图表的下部分断开啦
数据这样的时候，图表显示不出来啦
---------------------
The bottom part of the Sankey diagram is broken
When the data is like this, the chart cannot be displayed

#### Live demo with steps to reproduce
https://jshare.com.cn/temp/OpGGL6

**Comment by sebastianbochan** [comment] 2020-03-04 09:54
Hi @weixingcai,
Thank you for reporting about the problem. The reason of issue is using negative value (-60). In my opinion its not a bug, because values in pie chart should be always positive.

_Internal note_
@KacperMadej what do you think?

**Comment by KacperMadej** [comment] 2020-03-04 09:59
Hi @weixingcai 

Thank you for reporting the problem.

The problem is visible when using Highcharts version 8.0.0 - https://jsfiddle.net/BlackLabel/a96chpy1/

The problem is not visible when using current Highcharts version (8.0.2) - https://jsfiddle.net/BlackLabel/a96chpy1/1/

As soon as the Chinese CDN will update Highcharts code to version 8.0.2 the problem should be resolved for you.

Closing as resolved as this is working fine in the current version of the code.

**Closed by KacperMadej** 2020-03-04 09:59 UTC
Labels: Product: Highcharts

**Comment by weixingcai** [comment] 2020-03-05 05:59
升级为了8.0.2还是有问题

**Comment by weixingcai** [comment] 2020-03-05 09:35
https://jsfiddle.net/j08zafg4/1/
It doesn't show

**Comment by pawelfus** [comment] 2020-03-05 10:45
Chest doesn't show @weixingcai because there's not enough space for links. Increase the height: https://jsfiddle.net/BlackLabel/a96chpy1/2/ 

You can try also `minLinkWidth`, but chart might be cut: https://jsfiddle.net/BlackLabel/a96chpy1/3/

**Comment by sebastianbochan** [comment] 2020-03-05 10:46
Ps. You can also use minLinkHeight.
