### ISSUE TITLE
Regression - text selection when zooming

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#13659] opened 2020-06-08 08:14 UTC
#### Expected behaviour
No text selection

#### Actual behaviour
Text get highlighted when drag-zooming

#### Live demo with steps to reproduce
https://jsfiddle.net/highcharts/5fg1kyLo/
* Start in the upper left corner inside the plot area, keep the mouse button pressed and do circular movements across the plot area

#### Product version
v8.1.0. Regression since https://github.com/highcharts/highcharts/commit/4d0f5ca8645417c1fd14705fb4fe5332b2d90eea

**Comment by sebastianbochan** [comment] 2020-06-08 08:19
Duplicate of https://github.com/highcharts/highcharts/issues/13503

**Closed** 2020-06-08 08:19 UTC
Labels: Type: Regression
