### ISSUE TITLE
Flag tooltips not showing

### ISSUE THREAD

**Issue by aliparlar** [highcharts/highcharts#6881] opened 2017-06-20 14:11 UTC
#### Expected behaviour

When hovering a flag, I should see the Text attribute of the flag

#### Actual behaviour

Nothing, the default tooltip is covering the flag

#### Live demo with steps to reproduce

This is actually live on
 https://www.highcharts.com/stock/demo/flags-general

http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/flags-general/

#### Affected browser(s)

Tested on Chrome and Safari

**Comment by sebastianbochan** [comment] 2017-06-21 11:14
Hi @aliparlar,
Thank you for the reporting. 

_Internal note_
In the 5.0.11 all worked properly: 
- http://jsfiddle.net/76fompfc/

**Comment by jon-a-nygaard** [comment] 2017-06-22 07:57
This issue will be fixed in the next maintenance release, v5.0.13. It is caused by the same issue as in #6764, so I am closing this as a duplicate. Please follow #6764 for more information on the issue.

**Closed by jon-a-nygaard** 2017-06-22 07:57 UTC
Labels: Duplicate, Regression
