### ISSUE TITLE
multiple linkedTo and legend hovering doesn't work well together

### ISSUE THREAD

**Issue by nr-mi** [highcharts/highcharts#16000] opened 2021-07-06 10:12 UTC
#### Expected behaviour
If I group multiple series into one (via linkedTo) and I hover over the legend of one series, I expect that all none relevant series are faded out.
This works perfectly fine with one linkedTo and two series, but I want to use it multiple times.

#### Actual behaviour
Only some of the none relevant lines are faded out.
![Bildschirmfoto von 2021-07-06 12-01-19](https://user-images.githubusercontent.com/56023431/124583208-17ed1f80-de53-11eb-9e64-0438b599aa78.png)
In this example the orange line should be faded out too.

#### Live demo with steps to reproduce
https://jsfiddle.net/26sr9xg7/
This is based on: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/series-id/
I just added two more series and the "linkedTo".

#### Product version
latest

#### Affected browser(s)
all

P.S.: Please fix this in 9, I don't want to pay again ;)

**Comment by khlieng** [comment] 2021-07-06 10:49
Fixed by #15941, duplicate of #12015: https://jsfiddle.net/zw1sxn6h/

**Closed by khlieng** 2021-07-06 10:49 UTC
Labels: Type: Duplicate
