### ISSUE TITLE
Percentage totals in Pie Charts might not equal 100 with 0 decimal places

### ISSUE THREAD

**Issue by rcdubya** [highcharts/highcharts#17117] opened 2022-03-23 00:01 UTC
#### Expected behaviour
When showing percentage values in Pie/Donut Charts with 0 decimal places, it's desirable to always have the visible % equal 100% exactly.

#### Actual behaviour
When showing percentage values in Pie/Donut Charts with 0 decimal places, it is sometimes possible that the percentage !== 100% exactly.

I'm assuming that is likely due to the fact that due to rounding the individual labels as a last step to 0 decimal places, which then results in inconsistencies with the values and whether they add up correctly, though it would be good to confirm if this is the case, and if so, is there anything further that could also be done to avoid this. By default, we typically show 2 decimal places, but it is possible for the user to configure 0, 1 or more.

#### Live demo with steps to reproduce

1. Open fiddle: https://jsfiddle.net/rcdubya/nuwt1shz/5/
2. Observe percentage values (21+6+74 = 101).

#### Product version
Latest

#### Affected browser(s)
Chromium

**Comment by pawellysy** [comment] 2022-03-23 09:27
Hello @rcdubya, thanks for creating this issue.
I don't really think this is a bug. If you would create such a demo, where there are 3 slices, and each one of them represents an equal value, then the label would state, that the value is `33%` (which adds up to `99%`). If you would change one of those values to `34%` that would implicate, that one of the slices is bigger than the others. 

Apart from that, if that is the case, the user can alter the `dataLabels` formatter to display the value he wants or increase the accuracy of the `dataLabels`. 

What do you think guys? @TorsteinHonsi @raf18seb?

**Comment by raf18seb** [comment] 2022-03-23 11:03
Duplicate of https://github.com/highcharts/highcharts/issues/16035

Simplified demo: https://jsfiddle.net/BlackLabel/tn91hzb4/

Quoting @KacperMadej's:
> Which one of the points in the above demo should be changed from 33 to 34 to get the sum to 100%?

**Comment by TorsteinHonsi** [comment] 2022-03-23 13:08
I agree with @pawellysy, that it is not a bug. In the example with three slices, the value of each slice is still 33.333333333... It is just the _label_ that shows a rounded value, the value itself is not altered. So the alternative would be to actually change the values in order to make the labels go up, which I don't think a desired solution.

As a workaround, if this is at all desired, I would recommend that you preprocess the data before it is fed into Highcharts.

**Comment by rcdubya** [comment] 2022-03-23 17:22
Thanks for the confirmation and replies, @TorsteinHonsi, @raf18seb, @pawellysy. Makes sense.

I'm not sure that there is a way that pre-processes the percentages such that the values add up to 100% but are still accurate. I think the example with 1/3 is a good one to illustrate this and for example if we have to pick one value to be 34% then I agree that's not really any better than allowing the rounding rules to kick-in and show 99%.

Ultimately, when you decrease the number of decimal places shown, you are reducing the accuracy of the label, while increasing the succinctness of the data label. On the other hand increasing the number of decimal places improves the label's accuracy but degrades the succinctness of the value.

**Comment by pawellysy** [comment] 2022-03-23 20:13
@rcdubya either way, I am closing the ticket, since this does not require any changes in the core.
For further support please contact us via our support channels, which are listed [here](https://www.highcharts.com/blog/support/), where our support engineers will help you out with adjusting the Chart to your needs. 
Thank you for understanding!

**Closed by pawellysy** 2022-03-23 20:13 UTC
Labels: Status: Pending reply, Type: Undecided, Type: Duplicate
