### ISSUE TITLE
Gantt: connectors are disappearing

### ISSUE THREAD

**Issue by madepiet** [highcharts/highcharts#13006] opened 2020-02-21 16:00 UTC
#### Actual behaviour
Steps to reproduce:
Scroll navigator, for example the connector between Prototype and Prototype done will be hidden, see demo: https://jsfiddle.net/BlackLabel/pe8Lfuwn/

#### Expected behavior
Connectors will stay in its place.

#### Product version
Highcharts 8.0.0

**Comment by sebastianbochan** [comment] 2020-02-24 09:01
Hi @madepiet,
Im closing this ticket as duplicate of https://github.com/highcharts/highcharts/issues/12691

**Closed by sebastianbochan** 2020-02-24 09:01 UTC
Labels: Product: Highcharts Gantt, Type: Bug, Type: Duplicate
