### ISSUE TITLE
Bar chart scrollbar is not rendered properly

### ISSUE THREAD

**Issue by sagargurtu** [highcharts/highcharts#6415] opened 2017-02-27 06:04 UTC
#### Expected behaviour
Bar Chart scroll bar should be rendered properly when enabled.

#### Actual behaviour
The scroll bar is not rendered at the correct position and bars are overlapping it.

#### Live demo with steps to reproduce
http://jsfiddle.net/dxhpzb81/

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment] 2017-02-27 09:27
Hi @sagargurtu 

We have already fixed this, you can test our master branch here: http://jsfiddle.net/dxhpzb81/1/

Duplicate of #6262

**Closed by pawelfus** 2017-02-27 09:27 UTC
