### ISSUE TITLE
Amount is not showing as K on Y axis

### ISSUE THREAD

**Issue by pankajd1990** [highcharts/highcharts#14076] opened 2020-08-18 13:42 UTC
#### Expected behaviour
On y axis,Amount should be displayed as 25K

#### Actual behaviour
On y axis,Amount should be displayed as 25K.but here Y axis value displayed as 25000

#### Live demo with steps to reproduce
https://jsfiddle.net/pankaj_durve/8ncukpxr/8/

#### Product version
latest version

**Comment by pawelfus** [comment] 2020-08-18 14:20
Hi @pankajd1990 

Thank you for reporting the issue. This is expected behaviour: numeric symbols (k, M etc) are displayed by default only  when `tickInterval` is higher or equal to 1000. Otherwise, full number is rendered. If your numbers should always render with numeric symbols, set for example [`yAxis.minTickInterval`](https://api.highcharts.com/highcharts/yAxis.minorTickInterval), demo: https://jsfiddle.net/BlackLabel/4e7kfdyL/1/

Alternatively, create your own [`yAxis.labels.formatter`](https://api.highcharts.com/highcharts/yAxis.labels.formatter).

Closing as not a bug, but expected behaviour.

**Closed by pawelfus** 2020-08-18 14:20 UTC

**Comment by pankajd1990** [comment] 2020-08-18 15:32
issue is not fieed, y axis values are showing if y axis value comes 1000 range **[[97376700000, 2500],
         [1597376701000, 2600]]**,..but in other case if value comes as 100 or 200,y axis value are not displaying.
kindly refer 
https://jsfiddle.net/pankaj_durve/m8zobfg2/4/

**Comment by sebastianbochan** [comment] 2020-08-19 08:11
The minTickInterval should be proper for you data. If you have points 100 and 200, setting minInterval as 1000 does not make sense. You should adapt to you data i.e set the param as 10.

Demo:
- https://jsfiddle.net/BlackLabel/5wdcs19o/

You can also control ticks by tickInterval or tickPositioner methods.

All of them are documented here:
- https://api.highcharts.com/highcharts/yAxis
