### ISSUE TITLE
yAxis: undesirable interaction between custom tickPositioner and 'showEmpty'

### ISSUE THREAD

**Issue by lassebn** [highcharts/highcharts#3784] opened 2015-02-03 15:57 UTC
If you have an yAxis with a custom tickPositioner, and you want to use`showEmpty` to hide the axis when you hide the series, by clicking on it in the legend, you will have to manually check if the series is visible, in the tickPositioner. See: http://jsfiddle.net/lassebn/0ytf7j2e/

This fiddle contains an example with a good and a bad tickPositioner. When using the bad tickPositioner, the yaxis will always be shown, regardless of the visibility of the series data, even though `showEmpty: false`.

I am aware that the documentation says:

> Whether to show the axis line and title when the axis has no data. Defaults to true.'

But I believe that this is not actually the behaviour desired when using custom tickPositioning. Could you make `showEmpty` always hide the axis if `showEmpty: false`?

**Comment by jflambert** [comment] 2015-03-18 13:51
I agree with this issue. It is affecting me. Highstock 2.1.4.

**Comment by highslide-software** [comment] 2015-03-23 11:55
The `showEmpty` flag currently refers to axes that have no min or max. The idea is that if there is no data, there is no automatic min or max, and subsequently it is empty. If however you set a min and max, either through options or the tickPositioner, it is no longer empty. So ultimately this is the same issue as #705.

**Comment by KacperMadej** [comment] 2017-03-23 14:54
Duplicate of #705.

**Closed by KacperMadej** 2017-03-23 14:54 UTC
Labels: Duplicate
