### ISSUE TITLE
Donut pie renders as pie in IE8 when difference between series values is big

### ISSUE THREAD

**Issue by mokasha01** [highcharts/highcharts#2112] opened 2013-08-07 09:38 UTC
I'm using Highcharts 3.1 to create a donut pie, there is an issue when one of the series values is much bigger than the others, for example [2700, 6, 2], the inner pie of the donut pie is not rendered correctly and not divided (works fine on chrome and firefox)
![capture](https://f.cloud.github.com/assets/5180980/923352/96300b1e-ff45-11e2-9492-f6eab399008f.JPG)

**Comment by jon-a-nygaard** [comment] 2016-04-26 10:59
Closing this issue due to: We are not able to reproduce the issue, and it is pending reply. 
Should anyone have further information on this issue, please add a comment and reopen.

**Closed by jon-a-nygaard** 2016-04-26 10:59 UTC
Labels: Cant reproduce, Pending reply
