### ISSUE TITLE
IE8 - column + mootols

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#2554] opened 2013-12-23 11:49 UTC
Columns are not printed if we you mootools.

IE8: 8.0.6001.18702

**Comment by jon-a-nygaard** [comment] 2016-04-26 10:02
Closing this issue due to: We are not able to reproduce the issue, and it is pending reply. 
Should anyone have further information on this issue, please add a comment and reopen.

**Closed by jon-a-nygaard** 2016-04-26 10:02 UTC
Labels: Cant reproduce, Pending reply
