### ISSUE TITLE
Print chart missing parts of chart 

### ISSUE THREAD

**Issue by toupilsner** [highcharts/highcharts#4780] opened 2015-11-30 13:11 UTC
Charts should resize. When I export images, the chart is resized. 

Example:

![image](https://cloud.githubusercontent.com/assets/3957966/11472243/8a27650e-976b-11e5-91e1-88b8e33a61ff.png)

Print result:

![image](https://cloud.githubusercontent.com/assets/3957966/11472266/a314bb48-976b-11e5-95f4-e0e26488be4e.png)

December and parts of November is missing when I print.

**Comment by pawelfus** [comment] 2015-11-30 15:47
But this depends on the browser size? I mean, when you have browser size, for example 10 000px, then of course, using `ctrl+p` or `Print chart` button will cut part of the chart, see simple demo: http://jsfiddle.net/ux74929j/16/show/ - try to print the page.

**Comment by TorsteinHonsi** [comment] 2016-05-02 09:57
Duplicate of #2088 (fixed).

**Closed by TorsteinHonsi** 2016-05-02 09:57 UTC
Labels: Duplicate
