### ISSUE TITLE
HighChart- When I use useUTC: false then x axis labels are not showing properly 

### ISSUE THREAD

**Issue by cupatil** [highcharts/highcharts#14824] opened 2020-12-17 10:52 UTC
**Expected behaviour**
The graph should display X-Axis labels correctly when we set
time: { useUTC: false }

**Actual behaviour**
The graph is not showing up X-Axis labels. It is showing blank

**Live demo with steps to reproduce**
https://jsfiddle.net/chetanpatil1993/8j56091d/2/

**Product version**
Highcharts JS v8.2.2 (2020-10-22)

**Affected browser(s)**
Google Chrome (Version 87.0.4280.88 (Official Build) (64-bit) )

I have already logged this issue on "highchart/highcharts-react-native" but the "Daniel Studencki (Denyllon)" suggested log issue here.

**Existing Issue From Github:** highcharts/highcharts-react-native#118

**Graph Output Screenshot:**

![graph4](https://user-images.githubusercontent.com/6263401/102481482-c8e2c700-4087-11eb-9eb3-f31a693aea23.png)

**Comment by Denyllon** [comment] 2020-12-17 12:19
I agree, the problem is definitely not related with `highcharts-react-native` package itself, as it is reproducible with pure Highcharts library, that's why I suggested to report it here. Unfortunately, I'm not able to reproduce it though, so it most probably noticeable in a specific region/timezone.

**Comment by khlieng** [comment] 2020-12-17 13:25
This is because of half-hour timezones (such as India) and it has been fixed here #14731.

**Comment by KacperMadej** [comment] 2020-12-17 15:45
Hi @cupatil 

Thank you for reporting the problem.

Please check the related issue linked above and let us know if the drop-in fix is working for you and if so, please use the workaround while waiting for the proper fix to be released and this will be closed as a duplicate. If the fix is not working for you please provide more details about your problem.

**Comment by cupatil** [comment] 2020-12-18 04:29
Hi @khlieng 

Thanks for the drop-in solution, But I do not understand how to use it in highcharts-react-native wrapper. @Denyllon Can you please suggest how to set "Highcharts.Time.prototype.set" function.

**Comment by Denyllon** [comment] 2020-12-21 07:31
It is not so easy to apply drop-in fixes like above using `highcharts-react-native`, because it requires editing package though, so the best way out of the problem would be to provide you with customized wrapper files and instruction which describes how to patch it. I will prepare the patch and let you know what to do till the end of the day.

**Comment by cupatil** [comment] 2020-12-22 14:15
@Denyllon Is there any update on customized wrapper files?

**Comment by sebastianbochan** [comment] 2020-12-28 11:23
@Denyllon will come to the office next week.

**Comment by Denyllon** [comment] 2021-01-04 16:33
@cupatil I sent you the email with patched file. Really apologize for being late in responding this ticket.

**Closed by Denyllon** 2021-01-04 16:33 UTC
Labels: Product: Highcharts, Status: Pending reply
