### ISSUE TITLE
HS 4.2.4 & Polar Chart: InvalidCharacterError when resizing window

### ISSUE THREAD

**Issue by GeoTob** [highcharts/highcharts#5224] opened 2016-04-18 09:02 UTC
#### Actual behaviour
When a polar chart is shown and the browser windows is resized, all plotted data disappears and the following error is produced:

    InvalidCharacterError: Failed to execute 'setAttribute' on 'Element': '0' is not a valid attribute name.
      at Object.R.redraw(/ajax/libs/highcharts/4.2.4/highcharts.js:272:127)
      at Object.R.render(/ajax/libs/highcharts/4.2.4/highcharts.js:271:86)
      at Object.oa.drawPoints(/ajax/libs/highcharts/4.2.4/highcharts.js:301:281)
      at o(/ajax/libs/highcharts/4.2.4/highcharts.js:25:410)
      at ? (/ajax/libs/highcharts/4.2.4/highcharts.js:302:20)
      at Object.P.animate(/ajax/libs/highcharts/4.2.4/highcharts.js:40:385)
      at Object.P.attr(/ajax/libs/highcharts/4.2.4/highcharts.js:45:3)
      at Object.P._defaultSetter(/ajax/libs/highcharts/4.2.4/highcharts.js:60:239)

There are no custom `onresize` handlers attached, handling is left entirely to HS.

#### Affected browser(s)
* Chromium 49
* Firefox 45.0.1

**Comment by oysteinmoseng** [comment] 2016-04-18 11:35
Duplicate of #5220

**Closed by oysteinmoseng** 2016-04-18 11:35 UTC
