### ISSUE TITLE
Flame chart - long dataLabels text overflow not working

### ISSUE THREAD

**Issue by bambooom** [highcharts/highcharts#12806] opened 2020-01-17 08:59 UTC
#### Expected behaviour
I'm playing with the new flame chart. It's cool. But I'd like to have the dataLabels inside the box, just like ordinary flame graph:
![Screenshot 2020-01-17 at 4 46 31 PM](https://user-images.githubusercontent.com/14840170/72597661-271f9b00-3949-11ea-8110-596d73a21cfd.png)

#### Actual behaviour
However, I tried to add `textOverflow: 'ellipsis'` in `dataLabels.style`, and set `overflow` to `justify`, it's not working. All the long data labels are not truncated with an ellipsis. They are out of the box.
Is there any way to fix this or any other solution to make long data labels truncated with an ellipsis?

![Screenshot 2020-01-17 at 4 50 38 PM](https://user-images.githubusercontent.com/14840170/72598057-0146c600-394a-11ea-9679-d0ae5fe91827.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/9zs73e8L/2/

#### Product version
v8.0.0 latest

**Comment by pawelfus** [comment] 2020-01-20 10:29
Thanks for sharing the idea @bambooom 

We agree with that, dataLabels should automatically apply ellipsis when text overflows the shape. We have plans to add that in future (no ETA, sorry).

You can watch progress of this feature in #12527 ticket.

Closing as duplicate of #12527

**Closed by pawelfus** 2020-01-20 10:29 UTC
