### ISSUE TITLE
Incorrect labels for xAxis for different zoom options

### ISSUE THREAD

**Issue by mkhlud** [highcharts/highcharts#4596] opened 2015-09-23 16:56 UTC
![image](https://cloud.githubusercontent.com/assets/2544772/10051897/89c11be2-622c-11e5-88c2-4781a156ddd5.png)
![image](https://cloud.githubusercontent.com/assets/2544772/10051965/ddde6b08-622c-11e5-8306-cc62a6a12b42.png)

Example: http://jsfiddle.net/mkhlud/rc61vg6g/2/

**Comment by pawelfus** [comment] 2015-09-24 09:17
Could you set fixed width for the chart? Also could you tell us which browser/os? On my side it works properly: 
![screen shot 2015-09-24 at 11 16 46 am](https://cloud.githubusercontent.com/assets/1453926/10069640/c903d412-62ad-11e5-8d20-a0adbb552745.png)

**Comment by jon-a-nygaard** [comment] 2016-04-26 09:35
Closing this issue due to: We are not able to reproduce the issue, and it is pending reply. 
Should anyone have further information on this issue, please add a comment and reopen.

**Closed by jon-a-nygaard** 2016-04-26 09:35 UTC
Labels: Cant reproduce, Pending reply
