### ISSUE TITLE
Highstock v2.0.4 set the passed in option's series as NULL

### ISSUE THREAD

**Issue by dreamershl** [highcharts/highcharts#4129] opened 2015-04-23 08:03 UTC
In the StockChart constructor, the options.series will be temporarily set as NULL. But it is set directly in the passed in options object. While the restoring is done on the cloned one. So the original option object series attribute will be NULL after creating the chart instance.

    Highcharts.StockChart = function (options, callback) {
                              ...
                              options.series = null;
	                      options = merge(...);
                              options.series = seriesOptions;

**Comment by PhilTheAir** [comment] 2016-08-11 03:43
I noticed this problem, too,,,

**Comment by pawelfus** [comment] 2016-09-12 14:17
Duplicate of #636

**Closed by pawelfus** 2016-09-12 14:17 UTC
