### ISSUE TITLE
HighChart stacked bar chart scrollbar issue

### ISSUE THREAD

**Issue by shashivardhan** [highcharts/highcharts#7944] opened 2018-03-01 20:20 UTC
When using highstock with stacked bar chart and scroll bar is enabled, which has 100 categories, I don't see the data on the chart when I start scrolling.
This works fine upto 50 categories

when I scroll back to initial position I'm getting this error "Cannot read property '0' of undefined" error when stacked column chart is resized" 

#### Expected behaviour
Expect it to work and display bars on the chart without any issue

#### Actual behaviour
I don't see the data on the chart when I start scrolling.

#### Live demo with steps to reproduce
https://jsfiddle.net/shashi3337/5xn92uht/1/

#### Product version
"highcharts": "^6.0.0"

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment] 2018-03-02 09:04
Hi @shashivardhan 
Thank you for the reporting. You should set [cropThreshold](https://api.highcharts.com/highcharts/plotOptions.series.cropThreshold) parameter.

Demo:
   - https://jsfiddle.net/BlackLabel/cbd39oLh/

Duplicate of https://github.com/highcharts/highcharts/issues/7688

**Closed by sebastianbochan** 2018-03-02 09:04 UTC
