### ISSUE TITLE
Firefox waterfall bar sometimes do not get the highlight color - the standard color partly remains 

### ISSUE THREAD

**Issue by DK-Unit4** [highcharts/highcharts#9967] opened 2019-01-22 17:43 UTC
#### Expected behaviour
waterfall bars has same color for the entire bar

#### Actual behaviour
waterfall bars sometimes has different colors inside same bar - on pointing it

#### Live demo with steps to reproduce
standard waterfall example
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/waterfall/

point to the second bar  - sometimes it partly remain green [standard color] (not light green - highlighted color)

#### Product version
Highcharts latest

#### Affected browser(s)
Firefox
![firefoxcolor](https://user-images.githubusercontent.com/38954233/51554353-c36da980-1e7d-11e9-99cf-91d29d16f1aa.png)

**Comment by sebastianbochan** [comment] 2019-01-23 08:54
Hi @DK-Unit4,
The Firefox v64 has a bug with correct rendering SVG. Probably the same as #9745, we are waiting for response from Mozilla.

Official report to Mozilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1517458

**Comment by DK-Unit4** [comment] 2019-01-24 18:35
Thank you. Hope they fix :)

**Comment by TorsteinHonsi** [comment] 2019-01-25 12:01
Closing as duplicate of #9745.

**Closed by TorsteinHonsi** 2019-01-25 12:01 UTC
Labels: Duplicate
