### ISSUE TITLE
no support for epoch length less than 13

### ISSUE THREAD

**Issue by vahidhiv** [highcharts/highcharts#4734] opened 2015-11-12 07:37 UTC
Hi, i' m working with highstock but there is a problem, when epoch time has length less than 13, it can't draw chart. For example this epoch 987363000000.
What can i do?

**Comment by highslide-software** [comment] 2015-11-12 08:24
I can't see a problem with that, see http://jsfiddle.net/highcharts/0w4b1er1/.

Please provide a more detailed description and live demonstration.

**Comment by vahidhiv** [comment] 2015-11-15 06:04
Sorry for my late answer, this is jsfiddle link but i couldn't resolve online data provider for it. I added google drive link for data.
https://jsfiddle.net/vahidhiv/41072agx/

**Comment by highslide-software** [comment] 2015-11-16 16:59
Getting cross-domain AJAX error now. Instead of linking to an online file, you can just paste the JSON result in the jsFiddle directly, for the sake of the demo.

**Comment by jon-a-nygaard** [comment] 2016-04-26 09:34
Closing this issue due to: We are not able to reproduce the issue, and it is pending reply. 
Should anyone have further information on this issue, please add a comment and reopen.

**Closed by jon-a-nygaard** 2016-04-26 09:34 UTC
Labels: Cant reproduce, Pending reply
