### ISSUE TITLE
Panning by Y/XY shrinks bars by Y axis instead of pan

### ISSUE THREAD

**Issue by KseniaD0x0** [highcharts/highcharts#21724] opened 2024-08-27 17:42 UTC
#### Expected behaviour
Panning works on Y axis when enabled.

#### Actual behaviour
When dragging the chart vertically it shrinks the bars until they are forming a line and then pan no longer does anything.

#### Live demo with steps to reproduce
[Fiddle](https://jsfiddle.net/stealkvas/j7k3rfhy/7/)

- Zoom the chart (it is more visible when Y axis range is larger), also without zoom nothing happens on pan.
- Drag the chart vertically

https://github.com/user-attachments/assets/03e76f0d-e853-4c8f-b2c1-153511c62a66

#### Product version
v.11.4.6

#### Affected browser(s)
Tested on Chrome

**Comment by bm64** [comment] 2024-09-02 08:32
Hi @KseniaD0x0 and thanks for reporting the issue.

Bisected to: c6a5fdde1a9578c43be99ddbd320fad003f4164b

**Comment by KacperMadej** [comment] 2024-09-03 07:36
The [docs](https://api.highcharts.com/highcharts/chart.panning.type) should be fixed from:
> When this option is set to y or xy, [yAxis.startOnTick](https://api.highcharts.com/highcharts/yAxis.startOnTick) and [yAxis.endOnTick](https://api.highcharts.com/highcharts/yAxis.endOnTick) are overwritten to false.

to something true - unless this change is not by design @TorsteinHonsi ?

The options quoted above need to be set manually to `false`.
Workaround with the options set to `false`: https://jsfiddle.net/BlackLabel/f4h23vt7/1/

**Comment by TorsteinHonsi** [comment] 2024-09-09 11:00
@KacperMadej Actually I have a hard time reproducing this, but here's what I know: 

In v11.4 we did the zoom refactor. Prior to this, as said in the docs, `startOnTick` and `endOnTick` were disabled altogether when panning an axis. As a consequence, the user could drag the axis to a state where it did not start or end on a tick: https://jsfiddle.net/highcharts/scg5vm9h/

Since v11.4, we changed this, so that `startOnTick` and `endOnTick` are only disabled during the panning operation itself, but after drop, the axis extremes animate to the closest ticks. 

Probably we should warn about this in the documentation of `chart.panning.type` and `chart.zooming.type`. It is also up for debate whether this is always the desired behavior, or maybe we should at least have an option to avoid the "after fit".

**Closed** 2024-09-17 06:57 UTC
Labels: Product: Highcharts, Product: Docs, Type: Undecided, Status: Has workaround
