### ISSUE TITLE
Y Axis labels is not getting displayed when pressing Reset Zoom Button

### ISSUE THREAD

**Issue by VBIManonmaniM** [highcharts/highcharts#10559] opened 2019-04-15 11:07 UTC
#### Expected behaviour
Y Axis labels is not getting displayed when pressing Reset Zoom Button

#### Actual behaviour
Y Axis labels ishould get displayed when pressing Reset Zoom Button after zooming.

#### Live demo with steps to reproduce
https://jsfiddle.net/xmuyg3kL/12/
![Screenshot (18)](https://user-images.githubusercontent.com/19260778/56128282-cbc91280-5f9c-11e9-968a-3ab1b51f50b5.png)
![Screenshot (19)](https://user-images.githubusercontent.com/19260778/56128285-cbc91280-5f9c-11e9-8f99-ec566f221a03.png)
![Screenshot (17)](https://user-images.githubusercontent.com/19260778/56128286-cbc91280-5f9c-11e9-96bc-daa4135e0e85.png)

**Comment by pawelfus** [comment] 2019-04-15 11:56
Hi @VBIManonmaniM 

Thanks for reporting the issue. It's actually a duplicate of #10516.

**Closed by pawelfus** 2019-04-15 11:56 UTC

**Comment by VBIManonmaniM** [comment] 2019-04-15 11:58
What is the fix for it??

**Comment by pawelfus** [comment] 2019-04-15 12:11
Issue is still open, it's a bug in Chrome engine. Most probably we will integrate a workaround in the core in the next release.

**Comment by VBIManonmaniM** [comment] 2019-04-15 12:11
Is there any work around??

**Comment by pawelfus** [comment] 2019-04-15 12:27
I suggest to set [`yAxis.minRange`](https://api.highcharts.com/highcharts/yAxis.minRange) so users won't be able to zoom below some threshold. This way you prevent labels from rendering far away from the viewport.

**Comment by VBIManonmaniM** [comment] 2019-04-15 12:32
If i set animation flag to false it is working

**Comment by pawelfus** [comment] 2019-04-15 12:37
@VBIManonmaniM - please read #10516 ticket. That's exactly the bug in Chrome - when animating SVG text elements out of the viewport, those elements are missing (even though those exists in DOM in a correct place). I have posted alternative workaround in #10516 ticket.
