### ISSUE TITLE
Plot Bands/Lines only appear for first axis

### ISSUE THREAD

**Issue by lumberg72** [highcharts/highcharts#9255] opened 2018-10-26 17:22 UTC
#### Expected behaviour
I would expect plot bands and plot lines to appear for each axis they are configured on.

#### Actual behaviour
Only the ones in the first axis appear.

#### Live demo with steps to reproduce
https://jsfiddle.net/91cw67uv/
Here you'll notice that the orange plot band on the 2nd y-axis does not render.

#### Product version
6.2

#### Affected browser(s)
Chrome

**Comment by TorsteinHonsi** [comment] 2018-10-29 12:04
Thanks for writing!

It works, but there were a couple of configuration issues:
* The missing plot band is on the third axis. The purple one on the second axis does show.
* The third axis had no series assigned to it, so it didn't show.
* When assigning a series to it, the plot band was outside the scope.
* When changing the plot band `from` and `to`, it works as intended: https://jsfiddle.net/highcharts/91cw67uv/2/

**Closed by TorsteinHonsi** 2018-10-29 12:04 UTC
