### ISSUE TITLE
3d - Negative column visible, when min:0

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5429] opened 2016-06-23 08:30 UTC
#### Expected behaviour
Negative column should not be visible

#### Actual behaviour
Negative value is printed, when min = 0

#### Live demo with steps to reproduce
http://jsfiddle.net/vohqccs3/

#### Affected browser(s)
All browsers

**Comment by pawelfus** [comment] 2016-06-27 13:55
Duplicate of #3131

**Closed by pawelfus** 2016-06-27 13:55 UTC
Labels: Duplicate
