### ISSUE TITLE
After series update null values show instead of actual data

### ISSUE THREAD

**Issue by primo14z** [highcharts/highcharts#11258] opened 2019-07-02 13:05 UTC
#### Expected behaviour
We have a Line chart graph with 3 series and nulls in between series, after 10 seconds we have a graph update with new series. The whole graph should shift left and show new lines, well new series.

#### Actual behaviour
For the first time the Graph show all 3 series with no errors, but after the 10 seconds update, the values at the end of the line where before the update were the null values, now show null values for the same TimeStamp as before where the actual values were present. A bit confusing i know, check the live Demo.

After research i found out that on the Highcharts version 7.0.4 the graph behaves as expected and it works as it should.

#### Live demo with steps to reproduce
https://codesandbox.io/s/angular-7h0eo

#### Product version
Higcharts: 7.1.2

#### Affected browser(s)
Firefox, chrome

**Comment by KacperMadej** [comment] 2019-07-04 08:57
Hi @primo14z 

Thank you for reporting about the error.

We have no version 7.0.4 and when I tested 7.0.3 the chart looked the same - could you check what version you were using for the expected behavior?

If the problem is not related to Angular please try creating a simple demo in pure JavaScript.

**Comment by primo14z** [comment] 2019-07-04 09:29
> 
> 
> Hi @primo14z
> 
> Thank you for reporting about the error.
> 
> We have no version 7.0.4 and when I tested 7.0.3 the chart looked the same - could you check what version you were using for the expected behavior?
> 
> If the problem is not related to Angular please try creating a simple demo in pure JavaScript.

Yea sorry version 7.0.3 worked fine, the version 7.1.2 is causing the unexpected behavior like is showed in the Live demo. You need to wait 10 seconds after the graph is shown, then the graph updates the series and check the last value on the left and you will see there is null value instead of actual data

**Comment by KacperMadej** [comment] 2019-07-05 09:53
This is a general issue that could be recreated in pure JavaScript like in this demo:
https://jsfiddle.net/BlackLabel/bL5pf7oq/

After 1 second check top point to see tooltip with nullFormat used while the points is clearly not a null value point.

The issue has been already resolved (thanks @pawelfus ).
Demo: https://jsfiddle.net/BlackLabel/bL5pf7oq/1/

The issue is a duplicate and will be closed as resolved.
To use fixed code in an Angular app you could manually change installed Highcharts package to contain code build based on current master branch code from this repo or you could wait for next version release that should contain the required fix.

**Closed** 2019-07-05 09:53 UTC
Labels: Type: Duplicate
