### ISSUE TITLE
Stock Tools Drawings shows wrong co-ordinates, moves wrongly and not able to draw when changing the "Zoom"

### ISSUE THREAD

**Issue by jackytanjq** [highcharts/highcharts#16111] opened 2021-07-28 03:44 UTC
#### Expected behaviour
Drawing objects _(eg. Lines, Labels, Circles, etc.)_ should have the following behaviour regardless of the chart's window size and "Zoom" option:
1. The drawn object's start and ending position should be on the actual cursor itself.
2. When moving the drawn objects, it will follow the cursor accordingly.
3. Able to draw objects regardless of the "Zoom" option used _(eg. From "6m" to "1m" and vice versa)_.

#### Actual behaviour
When the "Zoom" is "All" then the Drawing starts & ends at the correct co-ordinates and can be moved around without issues.

However, when the "Zoom" is set to either "1y", "YTD", "6m", "3m" or "1m", the issues are:
1. The starting and ending co-ordinate is 1 step to the left/behind the cursor.
2. Attempting to move the drawn object will make it move to the left only unless the mouse cursor is moved very quickly to the right side. 
Or in the worst case, it will disappear altogether.
3. Drawing in "1m" or "3m" first, then changing to "6m" or "YTD" or "1y" will cause the drawing tools not work at all and vice versa.

#### Live demo with steps to reproduce
Based on the [Stock Tools GUI](https://www.highcharts.com/demo/stock/stock-tools-gui) demo:
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/stock-tools-gui

Simple steps to replicate the issue:

1. Change the "Zoom" to "6m" and draw something _(eg. a line)_ while taking note of the start and end position.
2. Try to move the drawn object around.
3. Change the "Zoom" to "1m" and draw something _(eg. a line)_ while taking note of the start and end position again.
4. Not able to draw anything. _(Can refresh the page and do Step 3 first before Step 1 to see the opposite happen)_
5. Change the "Zoom" to "All" and draw something _(eg. a line)_ while taking note of the start and end position again.
6. Try to move the drawn object around.

Example Video:

https://user-images.githubusercontent.com/7489622/127259328-1a4d6ba2-e5b4-4f2f-8d31-5b8d5fdda247.mp4

#### Product version
Highstock JS v9.1.2 (2021-06-16)

#### Affected browser(s)
Tested on:
- Firefox 90.0.2 
- Edge 92.0.902.55
- Chrome 92.0.4515.107
- Opera 77.0.4054.277

**Comment by khlieng** [comment] 2021-07-28 07:18
Sounds like a duplicate of #16064 @karolkolodziej

**Comment by karolkolodziej** [comment] 2021-07-28 13:50
I've tested your scenario with the fixed PR #15987. 
Everything seems to work fine with that fix.
For now, you might use the 9.1.1 version as a workaround.

Demo: http://jsfiddle.net/BlackLabel/5yuhrp8s/

**Closed by karolkolodziej** 2021-07-28 13:50 UTC
