### ISSUE TITLE
Error in SVG files caused by the Accessibility module

### ISSUE THREAD

**Issue by PinkCoffee** [highcharts/highcharts#16767] opened 2021-12-08 08:48 UTC
#### Steps to reproduce:
1. Add the accessibility module.
2. Click the options button and "Download SVG Vector image".

#### Expected behaviour
The SVG image to be displayed when opening the svg file (opened in a web browser).

#### Actual behaviour
The svg image contain an error.

If you try opening the svg file in a chrome browser, an error is shown:
"error on line 1 at column 284: Extra content at the end of the document".
The incorrect svg image contains an additional div with the class `"highcharts-a11y-proxy-container-before"` in the svg file.
After removing this div element, the svg could be displayed.

#### Live demo with steps to reproduce

https://jsfiddle.net/7qtdnf3e/

#### Error:
![svg_error](https://user-images.githubusercontent.com/3929937/145177548-29e91d9d-ecdc-408b-87e3-bbf8fc48a2c6.png)

**Comment by raf18seb** [comment] 2021-12-08 11:10
Closing as duplicate of https://github.com/highcharts/highcharts/issues/16589

**Closed by raf18seb** 2021-12-08 11:10 UTC
