### ISSUE TITLE
Split y-axis breaks tooltip

### ISSUE THREAD

**Issue by roanoosenbrug** [highcharts/highcharts#16385] opened 2021-09-22 08:12 UTC
Expected behaviour
The tooltip should be shown on every point for a chart with 2 series, where one of the series is displayed above the second series.

Actual behaviour
The tooltip only works for the bottom series

Live demo with steps to reproduce
https://jsfiddle.net/7hp91r2q/1/

Product version
Highcharts 9.1.2

Affected browser(s)
N/A

**Comment by raf18seb** [comment] 2021-09-22 10:08
Duplicate of https://github.com/highcharts/highcharts/issues/16004
Fixed in https://github.com/highcharts/highcharts/pull/16005

Working demo (code pulled from master) with a fix applied: https://jsfiddle.net/BlackLabel/97m5ynj1/

**Closed by raf18seb** 2021-09-22 10:08 UTC
