### ISSUE TITLE
Highstock: Latest data point incorrect with grouping

### ISSUE THREAD

**Issue by historicbruno** [highcharts/highcharts#4971] opened 2016-01-28 22:47 UTC
This can be seen in one of the demos:
http://www.highcharts.com/stock/demo/data-grouping

Use the scrollbar to view an earlier time, then look at the latest point in that view (the rightmost point) and take note of its value. Now scroll forward again, so the point is somewhere in the middle of the chart, it will typically have a different (larger) value. It seems for the last point, not all of the data is being used when grouping.

I know there are other open issues about grouping, but I couldn't see that any of them describe this exact problem.

**Comment by pawelfus** [comment] 2016-02-11 13:56
Hi,

Thank you for reporting this! 

However, I am not sure if this is a bug. Correct me if I am wrong at some point, please:

  1. Change pane to the left (I also changed zoom range, for a better visibility), and hover last value in the range:
![first](https://cloud.githubusercontent.com/assets/1453926/12978037/db0cf80c-d0ce-11e5-8efb-160e77f6155a.png)


  2. Move the view to the right, so point will no longer be the last one:
![second](https://cloud.githubusercontent.com/assets/1453926/12978045/e1c3ec3c-d0ce-11e5-9b9c-62712641e7f3.png)


Of course, you are right: values are different for the same point. However, `dataGrouping` groups point only within visible range. When checking `rangeSelector`, you can see that last visible point in the first step is the same as last point. That means, next points from the original data are not used to the grouped point.

I think this is very similar (if not the same) to the #2957 issue.

*Internal note:*
Since it is another issue reported with a very similar use case, maybe we should consider this as a bug and tag these issues accordingly?

**Comment by historicbruno** [comment] 2016-02-13 00:37
I think your explanation is correct, but it's hard to tell precisely what I'm selecting with the range selector, especially with large data sets. I would argue that either the last group shouldn't be shown if it's incomplete, or the selected range end point should be adjusted to fit the group.

I wouldn't call it "fake data", but it _is_ misleading with certain data sets :)

**Comment by pawelfus** [comment] 2018-03-20 16:14
Related ticket: #5344 and PR: #8049

Closing as duplicate of #5344

**Closed by pawelfus** 2018-03-20 16:14 UTC
Labels: Highstock
