### ISSUE TITLE
Issue in indicator when we change linked series type

### ISSUE THREAD

**Issue by PrachiS2G** [highcharts/highcharts#17853] opened 2022-10-17 09:27 UTC
In this fiddle, some of the indicators are not working like ad, vbp, CCI etc when we change the type to line.
In this case, it becomes a straight line for ad when we change the type but in my code, it throws an error. I'm sending volumeSeriesID in the params of ad but when we change the type it goes missing. 

#### Expected behavior
It should create the series using ohlc but creates a straight line

#### Actual behaviour
It creates a straight line.

#### Live demo with steps to reproduce
https://jsfiddle.net/msfac6yr/11/

-> Apply ad indicator and change the series type to line, it becomes a straight line.

#### Affected browser(s)
Chrome

**Comment by raf18seb** [comment] 2022-10-17 13:24
Hi!

Closing as not a bug. It can be resolved by setting the `series.useOhlcData: true` on the main series, see demo: https://jsfiddle.net/BlackLabel/4x29jpo6/

API Reference: https://api.highcharts.com/highstock/series.line.useOhlcData

**Closed by raf18seb** 2022-10-17 13:24 UTC
