### ISSUE TITLE
Highstock Columnrange data grouping low/high values not consistent when changing range

### ISSUE THREAD

**Issue by adrian-c-petrescu** [highcharts/highcharts#6246] opened 2017-01-15 00:52 UTC
#### Expected behaviour
Highstock Columnrange data grouping low and high values should by consistent when changing the range. E.g. (see jsfiddle) for one month, max and min values should be the same.

#### Actual behaviour
However, they are changing. It even happens for column ranges that are not on the edge of the chart.

#### Live demo with steps to reproduce

https://jsfiddle.net/joe_the_bear/12o4e84v/

#### Affected browser(s)
Tested in Chrome 55.

**Comment by oysteinmoseng** [comment] 2017-01-16 15:39
Thank you for reporting, this definitely isn't expected behavior.

**Comment by oysteinmoseng** [comment] 2017-01-16 16:39
Looking at it closer it seems like you have a custom approximation function for the dataGrouping, and that this function causes the behavior. Using the default Highstock function the chart seems to be behaving correctly: https://jsfiddle.net/12o4e84v/10/.

Closing this as not a bug for now. Feel free to reopen if I misunderstood your problem.

**Closed by oysteinmoseng** 2017-01-16 16:39 UTC
Labels: Bug, Highstock
