### ISSUE TITLE
Zoom not working after downloading PNG image of the graph using exporting feature.

### ISSUE THREAD

**Issue by sameernimje** [highcharts/highcharts#15903] opened 2021-06-14 14:34 UTC
#### Expected behaviour
Zoom should work even after I download the PNG image

#### Actual behaviour
Dragging out an area for zooming is not working after I download the PNG image.

#### Live demo with steps to reproduce
1. Drag out a rectangle for zoom , it works,
2. Then Download the graph as PNG image
![Zoom Issue](https://user-images.githubusercontent.com/85886773/121909366-75f27f80-cd4b-11eb-93d3-ca234c5baaf2.PNG)

3. Now try to drag a rectangle for zooming, but it does not work.
![Zoom Issue 2](https://user-images.githubusercontent.com/85886773/121909326-6e32db00-cd4b-11eb-8b9b-a2fad765cf91.PNG)

[Live Example of the Issue](https://jsfiddle.net/3hqvpbao/)

#### Product version
"highcharts": "^9.0.1"

#### Affected browser(s)
Edge, Firefox, Chrome

**Comment by SilkReyn** [comment] 2021-06-14 15:01
I can confirm this issue. Got it after a call to getSVG() where zoomType: 'xy' and panning: true is set on the chart options.

**Comment by sameernimje** [comment] 2021-06-15 06:04
> I can confirm this issue. Got it after a call to getSVG() where zoomType: 'xy' and panning: true is set on the chart options.

Yes the issue occurs in the getSVG() flow as well.

**Comment by khlieng** [comment] 2021-06-15 06:57
Fixed by #15850, duplicate of #15845.

**Closed by khlieng** 2021-06-15 06:57 UTC
Labels: Type: Duplicate

**Comment by sameernimje** [comment] 2021-06-15 07:00
> Fixed by #15850, duplicate of #15845.

@khlieng It seems this issue is fixed recently, Can you please tell the approx. time when will will it be available ?

**Comment by TorsteinHonsi** [comment] 2021-06-15 10:40
@sameernimje We'll release it this week.

**Comment by sameernimje** [comment] 2021-06-16 05:06
> @sameernimje We'll release it this week.

Thanks a lot @TorsteinHonsi

**Comment by sameernimje** [comment] 2021-06-17 12:51
@TorsteinHonsi Thanks Highcharts Team. We have used the latest version in our app, the issue is fixed.
