### ISSUE TITLE
I can not get the first click event on iOS device!

### ISSUE THREAD

**Issue by AAChartModel** [highcharts/highcharts#7616] opened 2018-01-05 10:10 UTC
#### Expected behaviour
Get the every click event on iOS device.

#### Actual behaviour
Can not get the first click event on iOS device.

#### Live demo with steps to reproduce

https://code.hcharts.cn/highcharts/Zh5m1w

#### Affected browser(s)
Safari on iPhone. UIWebView on iOS.

**Comment by pawelfus** [comment] 2018-01-05 14:12
Hi @AAChartModel 

Thank you for reporting the issue. It looks like a duplicate of #6817 - could you try the workaround posted there?

**Comment by sebastianbochan** [comment] 2018-06-25 10:35
Closed due to inactivity. Please reopen if new details will appear.

**Closed by sebastianbochan** 2018-06-25 10:35 UTC
Labels: Pending reply
