### ISSUE TITLE
dataLabels not showing next to bar when overflow:"allow"

### ISSUE THREAD

**Issue by tkforce** [highcharts/highcharts#17325] opened 2022-05-25 09:35 UTC
#### Expected behaviour
According to the doc about `dataLabels.overflow`: https://api.highcharts.com/highcharts/plotOptions.series.dataLabels
>How to handle data labels that flow outside the plot area. The default is "justify", which aligns them inside the plot area. For columns and bars, this means it will be moved inside the bar. To display data labels outside the plot area, set crop to false and overflow to "allow".

So when bars are too long, the data labels are consider "outside the plot area",  the default behavior of `overflow: justify` is placing the data labels inside the bar. 

But what we‘re looking for is "no data label is allowed in the bar", if it's consider "outside the plot area", we want to simply hide it. So we change it to `overflow: allow` and expecting when it's consider "outside the plot area", `dataLabels.crop:true` will take effect and hide those labels.

#### Actual behaviour
Not only the first (long) bar label are hidden (expected),
![image](https://user-images.githubusercontent.com/7017984/170231073-210212f5-9bc9-4a40-a3f6-f5348a6d6aae.png)
 the last (short) is also hidden for some reason:
![image](https://user-images.githubusercontent.com/7017984/170230556-ffd2b8a6-7c4f-4de1-9236-0d4ae70d90ec.png)

How can I **only hide those labels that is going to be placed within the bar** ?

#### Live demo with steps to reproduce

https://codesandbox.io/s/elated-jones-i5y7qo

**Comment by karolkolodziej** [comment] 2022-05-26 07:54
Please note that the plot area is also at the top and bottom. [You can see it better with border enabled.](https://jsfiddle.net/BlackLabel/op2tdunj/)
In your example, the first and the last elements are not inside the plot hence the mechanism hides them.

Please find below part of that logic that checks if the label is inside the chart's plot area:
https://github.com/highcharts/highcharts/blob/e676712b119ba04542d55151e1d7743a1297f345/ts/Core/Series/DataLabel.ts#L366-L382

_**Workaround**_
To work around it, you can manually change the label's position. 
You can make it while creating the chart (in the config) or right after it is created.
Demo: https://jsfiddle.net/BlackLabel/k1tfrbc7/

This mechanism (hiding labels that are not inside the plot area) works repeatedly and correctly thus I'm closing this issue as not a bug.

**Closed by karolkolodziej** 2022-05-26 07:54 UTC
