### ISSUE TITLE
Tooltip and highlighted points do not respect data update

### ISSUE THREAD

**Issue by jonfreedman** [highcharts/highcharts#9570] opened 2018-11-30 14:58 UTC
#### Expected behaviour
As points move due to updates the tooltip and highlighted points should move too

#### Actual behaviour
Tooltip and points are stuck based on last mouse movement
![chart](https://user-images.githubusercontent.com/1092134/49296504-5c043080-f4b0-11e8-91a6-e9621a13e0ed.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/4neh85L2/

#### Product version
6.2.0

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment] 2018-12-05 15:23
Hi @jonfreedman 

My apologies for the late reply! You are right, it's broken. Without boost module it works as expected: http://jsfiddle.net/BlackLabel/4neh85L2/41/

@cvasseng

**Comment by KacperMadej** [comment] 2018-12-12 14:06
Closing as a duplicate of larger (more comments) issue #9572

**Closed by KacperMadej** 2018-12-12 14:06 UTC
Labels: Bug

**Comment by KacperMadej** [comment] 2018-12-12 18:14
Hi, @jonfreedman 

Let me give a full info here instead of my previous message (targeted mainly for internal company communication).

Thank you for reporting about the issue in first place.

After further investigating the issue it look like it is a part of another open issue. After fixing that problem this will be fixed as well. We'll be working on resolving the problem reported here as a part of a bigger solution that will close the mentioned issue.

There's currently no ETA for the fix. Please continue with this problem on the linked issue, so we could have all the important info in one place. Currently we are waiting for reply from (mentioned in both issues) Highcharts boost module expert. If he'll not leave any comments within next few days please feel free to trigger additional notification for him in the issue #9572 by using his used name.

Best Regards
