### ISSUE TITLE
When I customize the lineWidth and lineColor of the plotOptions markers on iOS 14, the Scatter Chart has strange lines

### ISSUE THREAD

**Issue by AAChartModel** [highcharts/highcharts#14424] opened 2020-10-26 06:22 UTC
#### Expected behaviour
Get a normal scatter chart with a custom plotOptions marker

#### Actual behaviour
the marker of Scatter Chart has a strange line

#### Live demo with steps to reproduce

```js
{
  "credits" : {
    "enabled" : false
  },
  "touchEventEnabled" : true,
  "chart" : {
    "polar" : false,
    "backgroundColor" : "#000000",
    "type" : "scatter",
    "inverted" : false,
    "pinchType" : "none",
    "panning" : true
  },
  "tooltip" : {
    "useHTML" : false,
    "followTouchMove" : true,
    "shadow" : true,
    "crosshairs" : true,
    "shared" : true,
    "enabled" : true,
    "animation" : true
  },
  "xAxis" : {
    "labels" : {
      "style" : {

      },
      "useHTML" : false,
      "enabled" : true
    },
    "reversed" : false,
    "startOnTick" : false,
    "opposite" : false,
    "endOnTick" : false,
    "tickmarkPlacement" : "on",
    "tickInterval" : 1,
    "visible" : true
  },
  "plotOptions" : {
    "series" : {
      "connectNulls" : false,
      "stacking" : "",
      "marker" : {
        "radius" : 9,
        "symbol" : "circle",
        "enabled" : true,
        "lineColor" : "",
        "fillColor" : "#ffffff",
        "lineWidth" : 3.6000000000000001
      }
    }
  },
  "series" : [
    {
      "name" : "男",
      "data" : [
        [
          161.19999999999999,
          51.600000000000001
        ],
        [
          167.5,
          59
        ],
        [
          159.5,
          49.200000000000003
        ],
        [
          157,
          63
        ],
        [
          155.80000000000001,
          53.600000000000001
        ],
        [
          170,
          59
        ],
        [
          159.09999999999999,
          47.600000000000001
        ],
        [
          166,
          69.799999999999997
        ],
        [
          176.19999999999999,
          66.799999999999997
        ],
        [
          160.19999999999999,
          75.200000000000003
        ],
        [
          172.5,
          55.200000000000003
        ],
        [
          170.90000000000001,
          54.200000000000003
        ],
        [
          172.90000000000001,
          62.5
        ],
        [
          153.40000000000001,
          42
        ],
        [
          160,
          50
        ]
      ],
      "showInLegend" : true,
      "allowPointSelect" : false,
      "visible" : true
    }
  ],
  "title" : {
    "style" : {

    },
    "useHTML" : false,
    "text" : "按性别划分的身高体重分布图"
  },
  "colors" : [
    "#c3b1fb",
    "#e70b2d",
    "#77ed00",
    "#00f3d2",
    "#83ddff"
  ],
  "yAxis" : {
    "labels" : {
      "style" : {

      },
      "useHTML" : false,
      "enabled" : true,
      "format" : "{value:.,0f}"
    },
    "reversed" : false,
    "title" : {
      "text" : "千克(kg)"
    },
    "startOnTick" : false,
    "allowDecimals" : true,
    "opposite" : false,
    "endOnTick" : false,
    "gridLineWidth" : 0,
    "visible" : true,
    "lineWidth" : 0.5
  },
  "legend" : {
    "enabled" : true,
    "floating" : false
  }
}
```

#### Product version

Highcharts v8.1.0 ~~~ v8.2.2 

#### Affected browser(s)
WKWebView on iOS 14 (It is normal on iOS 13)

**Comment by AAChartModel** [comment] 2020-10-26 06:24
The key content is 

```js
"marker" : {
        "radius" : 9,
        "symbol" : "circle",
        "enabled" : true,
        "lineColor" : "",
        "fillColor" : "#ffffff",
        "lineWidth" : 3.6000000000000001
      }
```

The strange lines will appear only if I customize the `Marker` of plotOptions

**Comment by AAChartModel** [comment] 2020-10-26 06:25
![96998044-6d073080-1565-11eb-8077-299adde312db](https://user-images.githubusercontent.com/11792633/97061064-0cf5a600-15c8-11eb-9585-b83501d79552.jpg)
![96998096-7e503d00-1565-11eb-8435-e03692710a79](https://user-images.githubusercontent.com/11792633/97061067-0ebf6980-15c8-11eb-837b-031363fdd930.jpg)

**Comment by pawelfus** [comment] 2020-10-26 11:47
Thanks for reporting the issue.

Standalone, without Highcharts, SVG produces the same artifacts: https://jsfiddle.net/BlackLabel/4b2nem3v/1

This seems to be a bug in iOS v14 or in SVG's engine. Reported to Chrome devs: https://bugs.chromium.org/p/chromium/issues/detail?id=1142409

Closing as it's not a bug in Highcharts.

**Closed by pawelfus** 2020-10-26 11:47 UTC

**Comment by pawelfus** [comment] 2020-10-26 13:07
Redirected issue to WebKit: https://bugs.webkit.org/show_bug.cgi?id=218181
