### ISSUE TITLE
addPoint animation in Highstock

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#2266] opened 2013-09-17 11:46 UTC
Highcharts example: http://jsfiddle.net/m2gxD/1/
Highstock  example: http://jsfiddle.net/m2gxD/

In Highstock animation isn't applied. In Highcharts it works correctly.

**Comment by llfister** [comment] 2015-06-18 09:28
+1

**Comment by highslide-software** [comment] 2015-06-22 13:24
Internal note:
It happens because Series.render is called twice in the same thread, because the navigator triggers a chart redraw through Axis.setExtremes. These lines seem to cause it:
* https://github.com/highslide-software/highcharts.com/blob/v4.1.6/js/parts/Scroller.js#L322
* https://github.com/highslide-software/highcharts.com/blob/v4.1.6/js/parts/Scroller.js#L1042

Setting the redraw parameter to false seems to help, but not consistently, and it may also affect other cases.

**Comment by Timppe** [comment] 2015-08-04 09:49
Having this problem and another one also pointed out in my SO Question http://stackoverflow.com/questions/31582968/highstock-update-with-animation-like-highcharts

**Comment by fgperianez** [comment] 2015-11-25 22:02
+1

Please give some love to this issue ;)

**Comment by sebastianbochan** [comment] 2016-04-08 12:25
+1

**Comment by borisyankov** [comment] 2016-04-09 10:40
I was trying to debug why animation stopped working when switching from Highcharts to Highstock.
I can't believe that animation it has never worked?!?
This should be reflected in the documentation, if it is not a bug that is going to be fixed.

**Comment by TorsteinHonsi** [comment] 2016-04-12 12:03
I had a serious fight with this today and the preliminary result is available in the `issue-2266` branch. The result can be viewed at http://jsfiddle.net/highcharts/m2gxD/4/.

This not only fixes this issue, but also refactors the navigator code to avoid the redundant redraws that have been a problem in many cases.

TODO:
- Fix `addPoint` with `shift` applied
- Test disabled navigator and scrollbar independently.
- Run all tests

**Comment by TorsteinHonsi** [comment] 2016-04-16 11:56
Closed by a5bd7001f8cf129e1da6b72d43b7c06afdc6efe5.

Original demo with the fix applied: http://jsfiddle.net/highcharts/m2gxD/8/

**Closed by TorsteinHonsi** 2016-04-16 11:56 UTC
Labels: Bug, Highstock
