### ISSUE TITLE
Column chart with gapped points displays incorrect

### ISSUE THREAD

**Issue by nizrix** [highcharts/highcharts#16699] opened 2021-11-24 09:53 UTC
#### Expected behaviour
Column chart should calculate the correct column and x-axis width and display them accordingly.

#### Actual behaviour
When I use tick positioner and place point on the graph with a gap between them the display of the chart is incorrect.
If I have at least 2 point on the chart without a gap between them, the chart displayed correctly.

#### Live demo with steps to reproduce
https://jsfiddle.net/nizrix/nawhbx8y/24/

No special action needed.

#### Product version
Highcharts JS v9.3.1 (2021-11-05)

#### Affected browser(s)
All

**Comment by raf18seb** [comment] 2021-11-30 11:18
Hi @nizrix, thanks for creating the ticket.

This is because of the space reserved for wide columns. You can disable this behavior by setting `series.pointRange: 0`, see demo: https://jsfiddle.net/BlackLabel/6tgLzp1f/

Closing as not a bug and resolved.

**Closed by raf18seb** 2021-11-30 11:18 UTC

**Comment by nizrix** [comment] 2021-12-12 13:54
Hi @raf18seb , thanks for your help.
Your answer did fixed the issue about the x-axis width but not the column width that is overlapping other x-axis labels.
In this next example:
https://jsfiddle.net/nizrix/nawhbx8y/25/
you can see that if i have at least 2 points that are following each other, the chart displays good without any parameter needed to be added.

**Comment by nizrix** [comment] 2021-12-15 08:24
Hi @raf18seb 
Thanks, now I know what is the parameter that effect this issue.
However, I did not understand how did you come up with the calculated value.
I understand that the value "777600000" stands for 9 days in milliseconds, that is the gap between the 2 points
but why did you divided it by 5?
I am trying to find the correct algorithm to make sure it will always shows the same for every situation.

To tell you the truth, I'm not sure why this isn't classified as bug, I don't think I'm asking for something special for a consumer point of view.
I just want the show a chart with a gap between columns.

Many thanks for your support.
