### ISSUE TITLE
pointPlacement isn't working if there is one data and xAxis.type = 'datetime'

### ISSUE THREAD

**Issue by niwococo** [highcharts/highcharts#16886] opened 2022-01-15 03:11 UTC
https://jsfiddle.net/mareon/L9q58w2x/17/

I just want to  make views and clicks between the date point, Can any one help me?

**Comment by raf18seb** [comment] 2022-01-17 09:57
Hi @niwococo, thank you for contacting us with your issue.

Since you have only one date defined: 1642032000000 which is **13 January 2022 00:00**, how the Highcharts should know what 2 dates should be used?
13 January and 14 January (1 day between ticks)? Maybe 00:00 and 01:00 (1 hour between ticks)?

To tell it to Highcharts, you can set `series.pointRange`. Additionally, if you set `xAxis.min` and `xAxis.max` together with `series.pointPlacement`, you'll get the columns between 2 date ticks, see demo: https://jsfiddle.net/BlackLabel/peamnfrL/

I'm closing the ticket as it's not a bug (`pointRange` must be set when there's one date only).

In case of any further questions, please contact us on one of our dedicated support channels (GitHub is our bugs and features tracker only). More info: https://www.highcharts.com/blog/support/

**Closed by raf18seb** 2022-01-17 09:57 UTC

**Comment by niwococo** [comment] 2022-01-18 00:56
@raf18seb Thx a lot, you save me a lot of time!
