### ISSUE TITLE
IE8 windows 7 32 bit rending issue

### ISSUE THREAD

**Issue by PrakashKularatnam** [highcharts/highcharts#3097] opened 2014-05-26 09:11 UTC
Kindly help me to resolve this issue.

**Comment by jon-a-nygaard** [comment] 2016-04-26 09:49
Closing this issue due to: We are not able to reproduce the issue, and it is pending reply. 
Should anyone have further information on this issue, please add a comment and reopen.

**Closed by jon-a-nygaard** 2016-04-26 09:49 UTC
Labels: Cant reproduce, Pending reply
