### ISSUE TITLE
Range Input Date: Not able to see date with sufficient space on click

### ISSUE THREAD

**Issue by sharathsg27** [highcharts/highcharts#18861] opened 2023-04-21 10:03 UTC
#### Expected behaviour
The date range input should be clearly visible on click

#### Actual behaviour
On clicking date range input, the date is not visible properly. Only half of the date is visible

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/rangeselector/styling/

#### Product version
9.2.2

#### Affected browser(s)
Chrome
<img width="1223" alt="Screenshot 2023-04-21 at 3 32 32 PM" src="https://user-images.githubusercontent.com/29069848/233608632-4fa11c36-44a8-48f6-9042-a6d99800eecf.png">

**Comment by bm64** [comment] 2023-04-22 17:24
Hello @sharathsg27 and thanks for contacting us. I'm closing this one as a duplicate of https://github.com/highcharts/highcharts/issues/18813
Please see workaround in the original issue.

**Closed by bm64** 2023-04-22 17:24 UTC
