### ISSUE TITLE
Standalone image in label

### ISSUE THREAD

**Issue by panickerr** [highcharts/highcharts#5527] opened 2016-07-25 06:43 UTC
#### Expected behaviour
The image appears as x-axis label

#### Actual behaviour
The image only renders only when there is 'this.value'  appended to image in the return statement of the formatter.
`  return '<img src="assets/images/img1.png" alt="new" style="vertical-align: middle; width: 102px; height: 102px"/>'; doesnt work unless we add +this.value;
                                   `

#### Affected browser(s)
Firefox, Chrome, Edge

**Comment by TorsteinHonsi** [comment] 2016-07-25 07:59
It works well for me, can you you provide a live demo? http://jsfiddle.net/highcharts/teo0zx4a/

**Comment by panickerr** [comment] 2016-07-25 10:25
Hi @TorsteinHonsi ,
In Jsfiddle when i tried to recreate then there it is working fine( http://jsfiddle.net/panickerr/34mo82tj/ ) , but still in my system i always need to put a this.value without which the label doesn't render. Also when i do put 'this.value' then the image size is being adjusted with the size of the label text, ie irrespective of the fact that all the images are of equal size, their sizes readjust depending upon the length of their respective this.value(categories). The image corresponding to india will appear small, canada will be bigger and of saudi arabia will the the biggest. 
I really cannot figure out why such a thing is happening. i'm using the v4.2.5.

**Comment by TorsteinHonsi** [comment] 2016-07-26 09:15
Okay, I'm not sure how to handle it, and without seeing it live it is hard to do anything about it. Let us know if you can reproduce it live.

**Comment by jon-a-nygaard** [comment] 2016-08-18 10:24
Closing this issue since we are unable to reproduce, and it is pending a reply. Should anyone have further information about the issue, please give us a comment.

**Closed by jon-a-nygaard** 2016-08-18 10:24 UTC
Labels: Cant reproduce, Pending reply
