### ISSUE TITLE
Incorrect coding of geographical names

### ISSUE THREAD

**Issue by jomar-honsi** [highcharts/highcharts#20563] opened 2024-01-31 17:28 UTC
#### Expected behaviour

Czech geographical names to be displayed correctly: **Jihočeský**.

#### Actual behaviour

Certain characters used in Central European languages are wrongly displayed: č, ř, ň, ž and perhaps more.

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/cz/cz-all

See https://code.highcharts.com/mapdata/ for other countries. These maps are verified to be affected: Czechia, Slovakia, Slovenia, Croatia, Serbia, and Lithuania.

#### Observation
The issue is present in the data source, for example https://code.highcharts.com/mapdata/countries/cz/cz-all.topo.json. Possible causes could be incorrect encoding when storing the files at the Highcharts server or even errors in the original data set from [Natural Earth](https://www.naturalearthdata.com/downloads/).

#### Product version
Highcharts Maps 11.3.0

#### Affected browser(s)
N.A.

**Comment by hubertkozik** [comment] 2024-02-01 08:20
Hi @jomar-honsi!

This issue has already been reported and resolved. The fix should be included in the next release of Highcharts Map-Collection.

Closing as a duplicate of https://github.com/highcharts/map-collection-dist/issues/118.

**Closed by hubertkozik** 2024-02-01 08:20 UTC
Labels: Type: Duplicate
