### ISSUE TITLE
The last point isn't visible when updating the marker symbol with the accessibility module attached

### ISSUE THREAD

**Issue by mfilipiec** [highcharts/highcharts#16235] opened 2021-08-20 15:17 UTC
#### Expected behaviour
All the points are visible.

#### Actual behaviour
Like in the title (its opacity is set to 0).

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/e0ngtwy8/

Workaround: fire additional `chart.redraw()` https://jsfiddle.net/BlackLabel/gnko9wst/

#### Product version
v9.2.1

**Comment by raf18seb** [comment] 2021-08-20 15:44
FYI @oysteinmoseng

**Comment by raf18seb** [comment] 2021-08-20 15:50
Closing as a probably duplicate of https://github.com/highcharts/highcharts/issues/15480 and https://github.com/highcharts/highcharts/issues/16052

**Closed by raf18seb** 2021-08-20 15:50 UTC
Labels: Type: Duplicate, a11y
