### ISSUE TITLE
HTML characters not encoded

### ISSUE THREAD

**Issue by MiroLiska** [highcharts/highcharts#7558] opened 2017-12-20 08:20 UTC
#### Expected behaviour
The tooltip on category axis is not properly HTML encoded.

#### Actual behaviour
If the category axis contains encoded HTML characters, the tooltip by mouse hover shows the text in a verbose form, without firstly HTML encoding the text.

#### Live demo with steps to reproduce
Position the mouse over 'Service Revenue', the tooltip will contain rubbish.
http://jsfiddle.net/pLwxvxs4/ 
![tooltipbug](https://user-images.githubusercontent.com/23024867/34197490-07acc0b4-e567-11e7-8521-4b2db71cca9b.png)

#### Affected browser(s)
Everywhere

**Comment by pawelfus** [comment] 2017-12-20 16:41
Hi @MiroLiska 

Thank you for reporting this bug. You can use one of the workarounds from #7179. Closing as a duplicate of #7179

**Closed by pawelfus** 2017-12-20 16:41 UTC
Labels: Duplicate

**Comment by TorsteinHonsi** [comment] 2017-12-21 10:46
Hi Miro, #7179 is now fixed. See [your demo with the fix applied](http://jsfiddle.net/highcharts/pLwxvxs4/2/).

**Comment by MiroLiska** [comment] 2017-12-21 10:50
Great work! I love working with you, guys!

**Comment by MiroLiska** [comment] 2017-12-22 10:59
Hi

Sorry to disturb you again. I have realized that the code is now removing the tags, but it is not OK.  My example was a bit misleading, imagine rather text like here: http://jsfiddle.net/pLwxvxs4/3/ - Service <Revenue>. The tooltip is now "Service" only, the word in 'special parentheses' is gone.

**Comment by MiroLiska** [comment] 2018-01-04 13:09
Thanks. now it is fine :thumbsup:
