### ISSUE TITLE
column series pointRange causes squished ticks after cropping

### ISSUE THREAD

**Issue by akovac** [highcharts/highcharts#2346] opened 2013-10-10 08:15 UTC
Hi,

If data grouping is disabled and data cropping takes place on column series in Series.processData() method then calculated closestPointRange after cropping can cause squished ticks.

See: http://jsfiddle.net/Z25rR/

Zoom in the middle of the chart problem will appear. If zoomed data range includes last two points then problem will not appear.
	
		if (options.pointRange === null) { // null means auto, as for columns, candlesticks and OHLC
			series.pointRange = closestPointRange || 1;
		}

I have observed that if cropping is mitigated by overriding cropThreshold value which defaults to (50 for column series) to the higher number (i.e. more then actual data points) then cropping will be skipped and closestPointRange will be calculated over all data points.

Calculated closestPointRange is then set to series.pointRange in the above code snippet. 

Workaround which appears to work for me is to just comment code that sets series.pointRange when options.pointRange is null.

Can you please take a look at this issue it goes from pre 1.3 version of Highstock.

Thanks!

**Comment by TorsteinHonsi** [comment] 2015-11-27 20:07
Duplicate of #2822

**Closed by TorsteinHonsi** 2015-11-27 20:07 UTC
Labels: Bug, Highstock
