### ISSUE TITLE
Inconsistent dataGrouping when set in rangeSelector

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#7121] opened 2017-09-01 15:47 UTC
#### Expected behaviour
dataGrouping should not change when set using rangeSelector and then navigator is moved.

#### Actual behaviour
dataGrouping is changing when set using rangeSelector and then navigator is moved.

#### Live demo with steps to reproduce
http://jsfiddle.net/b7oxmrkL/

Click on "M" rangeSelector button and then move navigator.

**Comment by pawelfus** [comment] 2018-06-21 13:37
Closing as duplicate of #8433

**Closed by pawelfus** 2018-06-21 13:37 UTC
Labels: Highstock
