### ISSUE TITLE
data 0 would be hidden by x axis

### ISSUE THREAD

**Issue by motoyannn** [highcharts/highcharts#17499] opened 2022-07-13 07:06 UTC
#### Expected behaviour

0 will display on the x axis.
Or any other solution, please let me know.

#### Actual behaviour

Data 0 would be hidden by x axis.

https://www.highcharts.com/demo/spline-plot-bands

<img width="935" alt="Screen Shot 2022-07-13 at 15 38 49" src="https://user-images.githubusercontent.com/38897355/178670575-938fa2cb-2f32-4655-9b67-bd2eecfb3e1f.png">

#### Product version

```
"highcharts": "^9.1.0",
"highcharts-react-official": "^3.0.0",
```

#### Affected browser(s)

Chrome 103.0.5060.114

**Comment by raf18seb** [comment] 2022-07-13 07:50
Hi @motoyannn, please get familiar with this article: https://highcharts.freshdesk.com/a/solutions/articles/44002324219

This is not a bug so I'm closing the ticket. For any further similar support questions, please contact us on one of our dedicated support channels listed here: https://www.highcharts.com/blog/support/ (GitHub is our bugs/features tracker only).

**Closed by raf18seb** 2022-07-13 07:50 UTC

**Comment by raf18seb** [comment] 2022-07-13 10:09
@motoyannn, I read it again and I think I misunderstood you in the first place, apologize for that.
You're not trying to show the 00:00 tick but you're trying to show the part of the series that have 0 value, right? You can do that by disabling [series clipping](https://api.highcharts.com/highcharts/plotOptions.series.clip), see demo: https://jsfiddle.net/BlackLabel/dz3x57yb/

**Comment by motoyannn** [comment] 2022-07-14 02:40
> you're trying to show the part of the series that have 0 value

Yes, and "series clipping" is what I really want. Thank you for your reply & demo.
If any questions come up, I will post question on the support channels.
