### ISSUE TITLE
Scrolling on desktop is not happening but scrollbar is not visible

### ISSUE THREAD

**Issue by rahulsingh806080** [highcharts/highcharts#17160] opened 2022-04-06 05:34 UTC
#### Expected behaviour
Scrollbar should appear when 'scrollablePlotArea' is added to highchart.
I need scrollbar to be visible. but this is not happening although scrolling is happening but scrollbar is not visible
#### Actual behaviour
The graph is getting scrolled but scrollbar is not visible. 

#### Product version
Highchartjs latest version.

#### Affected browser(s)

I am trying on chrome desktop.
<img width="836" alt="Screenshot 2022-04-06 at 11 01 56" src="https://user-images.githubusercontent.com/16794968/161902584-aa55c6f7-27c1-4bba-bd6c-fe347fda12eb.png">

**Comment by karolkolodziej** [comment] 2022-04-07 07:09
The `scrollablePlotArea` in Highcharts works the same as an `overflow` in the HTML.
If you scroll the chart, the scrollbar gets visible the same as it does in the HTML.
Please compare the two demos linked below.

[Demo in HTML.](https://jsfiddle.net/BlackLabel/ac1pnb0s/)
[Highcharts scrollablePlotArea demo.](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/chart/scrollable-plotarea-vertical)

![image](https://user-images.githubusercontent.com/57004120/162140117-dbc7d9a2-e111-4c10-928b-fc336635163f.png)

Closing as it is not a bug.

**Closed** 2022-04-07 07:10 UTC
Labels: Type: Not a bug
