### ISSUE TITLE
API and TS missing definition of level property in sunburst

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#14347] opened 2020-10-13 15:56 UTC
The sunburst series is missing API and TS definition of **sunburst.levels.level** property inherited from the treemap series: https://api.highcharts.com/highcharts/series.sunburst.levels

Demo showing this property: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/sunburst

#### Product version
8.2.2

**Comment by PaulDalek** [comment] 2020-10-14 10:46
Closing as a duplicate of the #14196.

**Closed** 2020-10-14 10:47 UTC
Labels: Product: Docs, Product: TypeScript, Type: Duplicate
