### ISSUE TITLE
Shared tooltip broken in IE

### ISSUE THREAD

**Issue by daviddebie** [highcharts/highcharts#7222] opened 2017-10-04 09:12 UTC
#### Expected behaviour
Shared tooltip showing all series

#### Actual behaviour
Tooltip not showing at all when shared tooltip is set to true

#### Live demo with steps to reproduce

http://jsfiddle.net/gh/get/jquery/2/highcharts/highcharts/tree/master/samples/highcharts/tooltip/formatter-shared/

#### Affected browser(s)
Internet Explorer 11.608.15063.0

**Comment by KacperMadej** [comment] 2017-10-04 10:20
Hi,

Thank you for reporting.

The visual problem is different, but source is the same as with #7223.
Duplicate of #7223

Workaround: add oldie module - http://jsfiddle.net/BlackLabel/rbo18x6d/

**Closed by KacperMadej** 2017-10-04 10:20 UTC
