### ISSUE TITLE
highstock issue with scrollbar and set data

### ISSUE THREAD

**Issue by alvarezguille** [highcharts/highcharts#9051] opened 2018-09-24 21:14 UTC
In my example a chart has 2 series, data is set for both at the same time either removing points or setting them.

It happens if the `Highcharts.chart` has scrollbar enabled https://jsfiddle.net/alvarezg/n9sc53av/
, or if the `Highcharts.stockChart` has navigator disabled https://jsfiddle.net/alvarezg/5arckguf/
To reproduce click `SHOW/HIDE 1`, `SHOW/HIDE 2` and `SHOW/HIDE 2` again and the xAxis min becomes "1969-12-02" instead of "2018-07-01" as it should

#### Product version
Highstock 6.1.x and also verified in Highstock 4.2.6

If there is a workaround compatible with 4.2.6 let us know.

**Comment by pawelfus** [comment] 2018-09-25 13:05
Hi @alvarezguille 

Thank you for reporting this issue. 

**Workaround:**
Use `chart.xAxis.scrollbar` instead of `chart.scrollbar`, demo: https://jsfiddle.net/BlackLabel/n9sc53av/10/

**Comment by pawelfus** [comment] 2018-10-02 13:01
Simplified demo: https://jsfiddle.net/BlackLabel/5arckguf/23/

**Comment by pawelfus** [comment] 2018-10-02 13:13
It'a a duplicate of #9075


Fixed demo using PR #9107 code: https://jsfiddle.net/BlackLabel/5arckguf/28/

**Closed by pawelfus** 2018-10-02 13:13 UTC
Labels: Bug, Highstock, In progress
