### ISSUE TITLE
Tooltip hover

### ISSUE THREAD

**Issue by nishanth-satmetrix** [highcharts/highcharts#6247] opened 2017-01-15 02:49 UTC
#### Actual behaviour
Here when hovering the column chart color is getting changed. the changed color is needed in the tooltip border.
Ex: intialy the bar having green . after hovering the color is changed to red. I need this red color for my tooltip border.
#### Expected behaviour
Ex: intialy the bar having green . after hovering the color is changed to red. I need this red color for my tooltip border.

please check the below fiddle.

Thanks In Advance
Nishanth

**Comment by oysteinmoseng** [comment] 2017-01-16 15:41
Closing as duplicate of #6240.

**Closed by oysteinmoseng** 2017-01-16 15:41 UTC
