### ISSUE TITLE
Problem with legend and page-scrolling

### ISSUE THREAD

**Issue by 2Cool4Usernames** [highcharts/highcharts#11788] opened 2019-08-27 11:21 UTC
**Expected behaviour**
Page-scrolling (on mobile devices) should not be locked by accidentally clicking chart legend items.

**Actual behaviour**
I’m using Highcharts.JS in an Ionic Framework app, and I’ve come across a problem. 

I have an areaspline chart with a legend under where you can switch on and off the stacked areaspline plots. 
This switching on and off is done by clicking the name of the series in the legend. In this app I also utilize scrolling up and down on the touchscreen. 
However, if I accidentally (or on purpose) start scrolling by clicking over/on the name of the plot in the legend, the event switching off the plot fires instead of allowing my app to scroll. 
It seems to me that the issue is that the switching off/on the plot is some sort of onclick event that “stays fired" until the touch is lifted and doesn’t allow the scrolling to be recognized by the app/device. 

I’ve illustrated the problem in the attached video, where you can see the scrolling functioning normally, but when the chart legend is pressed, the scrolling is suppressed or something like that.

This is not a problem when tapping on the spline series directly, only when tapping the legend series names.

**Product version**
Angular-Highcharts 7.2.0

**Affected browser(s)**
Mobile app (IOs, Android)

**Comment by KacperMadej** [comment] 2019-08-27 14:05
Hi @2Cool4Usernames 

Angular-Highcharts is not an official wrapper - this is not the correct repo to report problems with it.
If you have a general problem with code, please contact technical support.

Official and supported Highcharts wrapper for Angular is here: https://github.com/highcharts/highcharts-angular

**Comment by 2Cool4Usernames** [comment] 2019-08-28 14:19
Hi,

I sent an email to your support division a few days ago, and I got the response;

"I tested the flow you described (in pure JS - no Ionic) and it seems that there’s an inconsistency of how the legend click works on mobiles and PCs. On my Android, the legend item is activated (or deactivated) right after the screen touch and Highcharts doesn’t wait for finger release. However, on my PC the mouse up event is required to change the state of legend item.

It seems to be a bug. Could you report it in our github (https://github.com/highcharts/highcharts/issues)? I suppose that there’s no workaround for the problem - fixing it is the only (and the shortest) solution."

And so this seems to be a reproducible issue in pure JS as well.

**Comment by KacperMadej** [comment] 2019-08-28 14:44
@2Cool4Usernames 
Please add the name of the person that contacted you, so he will be able to add more info here.
If you have a live demo for pure JS then please add it.

From your initial comment, it looked to me as if the error was reproducible only in the environment you have specified and is based on an unsupported third-party library. Because of that, I have decided to close the issue, but now it will be reopened.

**Comment by 2Cool4Usernames** [comment] 2019-08-29 06:52
The mail from support came from Kamil Kulig

**Comment by KacperMadej** [comment] 2019-08-29 10:48
@2Cool4Usernames 
Thank you for the info. Kamil explained the problem. This issue is a duplicate of https://github.com/highcharts/highcharts/issues/9682

**Closed by KacperMadej** 2019-08-29 10:48 UTC
Labels: Status: Can't reproduce, Status: Pending reply
