### ISSUE TITLE
How to show 5 minute in stockchart  

### ISSUE THREAD

**Issue by yantrab** [highcharts/highcharts#7605] opened 2018-01-03 05:56 UTC
#### Expected behaviour
add point to start chart, and keep the empty space .

#### Actual behaviour
the navigator show only the points that added to chart

#### Live demo with steps to reproduce
http://jsfiddle.net/yym9z6jc/1/

**Comment by pawelfus** [comment] 2018-01-03 12:12
Hi @yantrab 

Thank you for letting us know about the issue. Do you mean [`xAxis.overscroll`](https://api.highcharts.com/highstock/xAxis.overscroll) option? Take a look: http://jsfiddle.net/yym9z6jc/2/

**Comment by yantrab** [comment] 2018-01-03 12:35
Tanks, this is what i neeb.
without the scroll bar, there is another benefit of using  stockchart under highchart?

**Comment by yantrab** [comment] 2018-01-03 12:35
Tanks, this is what i need. 
without the scroll bar, there is another benefit of using  stockchart under highchart?

**Comment by pawelfus** [comment] 2018-01-03 12:46
Hi @yantrab 

You can find description of Highstock on our [product page](https://www.highcharts.com/products/highstock/). Some of the options are available only for Highstock (dataGrouping, navigator, scrollbars, `overscroll`, rangeSelector etc.). I suggest to contact with us if you have more product-related questions: https://shop.highsoft.com/contact - we use github as bug reports.

Closing as not a bug.

**Closed by pawelfus** 2018-01-03 12:46 UTC
Labels: Pending reply

**Comment by yantrab** [comment] 2018-01-08 05:48
thanks.
It is possible to add overscroll to the start?
in reset zoom, when the serie is very long, it is take time to render all points, and i wont to add only what we see, and after that, when user do scroll back, add series dynamically.

**Comment by pawelfus** [comment] 2018-01-08 10:46
Hi @yantrab 

Please read about our lazy-loading solution: https://www.highcharts.com/blog/news/48-loading-millions-of-points-in-highcharts/
