### ISSUE TITLE
Align labels to the left without overlapping on the bar chart

### ISSUE THREAD

**Issue by RaulRicondo** [highcharts/highcharts#20599] opened 2024-02-07 08:32 UTC
#### Expected behaviour
Possibility to align category labels in an inverse bar chart (x-axis in vertical position).

#### Actual behaviour
In the case of an inverted bar chart, the x-axis category labels overlap the chart.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/kg3v1j0u/

#### Product version
Highcharts JS v11.3.0 (2024-01-10)

#### Affected browser(s)
Chrome, Safari, Edge. At least.

**Comment by hubertkozik** [comment] 2024-02-07 09:15
Hi @RaulRicondo!
I think the label should be fully visible if `xAxis.labels.align` option is set to `left`. For `right` and `center` it works correctly.

As a workaround for now, you can change the `xAxis.offset` and `xAxis.left` to move axis and show the labels.
**Live demo with workaround:** https://jsfiddle.net/BlackLabel/0kgxbn1c/

**Comment by hubertkozik** [comment] 2024-02-09 08:28
@RaulRicondo thank you for a detailed explanation. Here's another workaround, which will fully help you achieve the display labels to the left.

**Live demo with a workaround:** https://jsfiddle.net/BlackLabel/fvjo60dc/

**Comment by RaulRicondo** [comment] 2024-02-14 08:40
Hi @hubertkozik.

Thanks for the solution, it works perfectly.

However, I understand that it is still a bug and that the correct functionality should be the one achieved with the solution you have indicated.

**Comment by hubertkozik** [comment] 2024-02-14 08:44
Yes, this is a bug and it will be fixed by one of our developers. When the fix is applied to one of the new versions of Highcharts you won't need to use the workaround, but until then, I suggest using the workaround with the current version of Highcharts.

**Comment by MarkusBarstad** [comment] 2024-06-18 13:05
This is not a bug, @RaulRicondo . 

What you need to do is set 'reserveSpace' to true for the labels on the `yAxis` like so: https://jsfiddle.net/mkb93/caqzxojv/

When you have a left-aligned `yAxis` and you want left-aligned labels as well, it is necessary to set this property to `true`.

Same goes for the opposite case when you have a right-aligned `yAxis` and you want to reserve space for right-aligned labels.

**Closed** 2024-06-18 13:05 UTC
Labels: Type: Bug, Product: Highcharts, Status: Has workaround
