### ISSUE TITLE
fill in reversed

### ISSUE THREAD

**Issue by maxlibin** [highcharts/highcharts#7967] opened 2018-03-07 10:19 UTC
I set reversed: true for yAxis, however I want to keep the plotOption fillColor.
Below is a screen of chart when i set to reversed: true, the fill area become on top, but i want to keep at below in the white area. 

<img width="276" alt="screen shot 2018-03-07 at 6 16 16 pm" src="https://user-images.githubusercontent.com/1277038/37086958-e649cc78-2233-11e8-9010-e80b05657244.png">

**Comment by pawelfus** [comment] 2018-03-07 12:08
Hi @maxlibin 

Thank you for using Highcharts! It is a duplicate of #6170 - please try my solution posted there.

**Closed by pawelfus** 2018-03-07 12:08 UTC
