### ISSUE TITLE
An yAxis on the right of the chart adds an x offset to the rangeSelector on the left

### ISSUE THREAD

**Issue by ysavary** [highcharts/highcharts#7393] opened 2017-11-12 12:14 UTC
#### Expected behaviour
rangeSelector should be positioned related to the chart area and should not depend on how many yAxis we have

#### Actual behaviour
Adding a new yAxis on the RIGHT of the chart is adding an xOffset to the rangeSelector on the LEFT of the chart (in red) in the jsfiddle

#### Live demo with steps to reproduce
http://jsfiddle.net/16a6m3ny/6/

#### Affected browser(s)
Chome, Firefox with Highstock 6.0.2 (latest)

In mobile devices we loose a lot of space when, like in my chart2 example, the rangeSelector has an xOffset equal to the size of the yAxis labels!

**Comment by pawelfus** [comment] 2017-11-14 11:18
Hi @ysavary 

Thank you for reporting. You are right, it should work like in v5: http://jsfiddle.net/16a6m3ny/7/

FYI @sebastianbochan

**Comment by pawelfus** [comment] 2017-11-14 11:34
Needed to remove previous message, it could confuse.

Thank you for reporting this @ysavary 

It looks like a regression since 6.0.1, v6.0.0 was consistent: http://jsfiddle.net/sb8ycbue/ - however in your case you want exactly the opposite effect. 

@sebastianbochan could you take a look? I think `floating` should be a nice solution here, but something is off: http://jsfiddle.net/t9pyu88t/

**Comment by TorsteinHonsi** [comment] 2017-11-16 11:37
This change in v6.0.1 also happened to the inputs. In 6.0.0 they aligned to the chart area (`spacingBox`), but since v6.0.1 they align to the `plotBox`.

**Comment by jimousse** [comment] 2018-12-06 10:40
Any update on this issue?

**Comment by pawelfus** [comment] 2018-12-06 13:50
Hi @jimousse - are you sure your demo is correct? I see your `rangeSelector` is disabled.

*Internal note:*
In v6.2.0 regression is fixed (it works the same for v6.0.0 and v6.2.0).

**Comment by pawelfus** [comment] 2018-12-06 14:55
Thanks @jimousse for clarification! Yes, that's something different. Remember that [`startOnTick`](https://api.highcharts.com/highcharts/xAxis.startOnTick) works with [`minPadding`](https://api.highcharts.com/highcharts/xAxis.minPadding) and [`endOnTick`](https://api.highcharts.com/highcharts/xAxis.endOnTick) with [`maxPadding`](https://api.highcharts.com/highcharts/xAxis.maxPadding). Simply disable padding on xAxis and you will get the desired chart: http://jsfiddle.net/BlackLabel/pqxd50g1/

From docs:
> endOnTick: boolean
> Whether to force the axis to end on a tick. Use this option with the `maxPadding` option to control the axis end.
>
> Defaults to false.

Closing the issue since it's a separate issue and the original regression works fine in v6.2.0.

**Closed by pawelfus** 2018-12-06 14:55 UTC
Labels: Highstock, Regression
