### ISSUE TITLE
Tooltip with `stickOnContact` and `outside` freezes when moving to another chart

### ISSUE THREAD

**Issue by orenklein** [highcharts/highcharts#20983] opened 2024-04-10 09:54 UTC
https://github.com/highcharts/highcharts/assets/21295634/5910716a-6f18-4624-85f3-9884a8e637b0

In a scenario where there are two sibling charts one next to the other, moving the cursor from the first chart through the tooltip to the second chart causes the tooltip to to freeze. It is more prone to occur when the tooltip is wide and spread on the other chart area. In the demo, `useHtml` and `shared` are also turned to true but the issue occur without these props as well

Related PRs: #18842, #15960 

#### Expected behaviour
Tooltip should disappear when moving from one chart to another

#### Actual behaviour
Tooltip freezes

#### Live demo with steps to reproduce
https://jsfiddle.net/bza3fku5/2/

#### Product version
Latest version - 11.4.0

#### Affected browser(s)
Chrome

**Comment by hubertkozik** [comment] 2024-04-11 10:34
Hi @orenklein!

Thank you for reporting the bug! I am able to reproduce the issue on my machine, but sadly I cannot provide you with any workaround at this moment.

**Comment by hubertkozik** [comment] 2024-06-12 11:15
Closing as duplicate of https://github.com/highcharts/highcharts/issues/20969.

**Closed by hubertkozik** 2024-06-12 11:15 UTC
Labels: Duplicate
