### ISSUE TITLE
x-range disappears on zooming (sometimes)

### ISSUE THREAD

**Issue by berlinger-rarents** [highcharts/highcharts#6577] opened 2017-04-07 14:14 UTC
#### Expected behaviour
x-range point (cq bar) is still displayed when zooming in on any part

#### Actual behaviour
x-range point (cq bar) disappears when zooming in on last part

#### Live demo with steps to reproduce
Dual panes. Check this jsFiddle: https://jsfiddle.net/boerl/exrbaevr/
* zoom in anywhere in the yellow xrange: it will disappear
* zoom in on yellow+blue area together: it shows correctly

#### Affected browser(s)
tested in:
* Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
* Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:52.0) Gecko/20100101 Firefox/52.0

#### Hints
I could get as far as that the x-range point.pointY becomes NaN due to [axis.translate](https://github.com/highcharts/highcharts/blob/862628f33c834f8d3b5d408e9a6347fc9ea66762/js/parts/Axis.js#L623).

**Comment by berlinger-dmaley** [comment] 2017-04-10 07:31
Also there is another problem. 

**Expected behaviour**

Only the selected data labels remain on the screen.

**Actual behaviour**

First, last and selected data labels remain on the screen.

**Steps to reproduce**

[The same jsFiddle](https://jsfiddle.net/boerl/exrbaevr/)

If you select a small section of the graph within one area (for example, only within the second x-range), then the name of the first remains on the screen.

**Comment by berlinger-dmaley** [comment] 2017-04-10 09:23
Another [example](http://jsfiddle.net/4jkrbvn3/) with the same problems: the graph disappears and outside data labels remain on the screen when zoom in

**Comment by larsac07** [comment] 2017-04-20 07:34
Thanks for the report!
Looks like a problem with the `trimTicks()` override in XRangeSeries. Taking a look.

**Comment by larsac07** [comment] 2017-04-20 08:34
Related: #6169

**Comment by KacperMadej** [comment] 2017-08-03 15:32
X-range is planned for Highcharts 6.0 and we are working on resolving all pre-release issue before HC 6.0

https://www.highcharts.com/support/roadmap

**Comment by berlinger-dmaley** [comment] 2017-08-04 07:44
Thank you!

**Comment by berlinger-dmaley** [comment] 2017-10-06 15:47
Dear Highcharts team, hi!
Was this issue fixed in Highcharts 6.0?

Thanks in advance!

**Comment by oysteinmoseng** [comment] 2017-10-10 09:17
@berlinger-dmaley Hi, this issue has not been fixed yet, I will take a look at it.

**Comment by oysteinmoseng** [comment] 2017-10-10 11:26
@berlinger-dmaley Actually this issue is fixed in HC6 but you are loading the old module in your demo. Include `modules/xrange.js` instead of `modules/xrange-series.js`. Example: https://jsfiddle.net/exrbaevr/2/

**Closed by oysteinmoseng** 2017-10-10 11:26 UTC
Labels: Bug, Highcharts Gantt, Pre-release
