### ISSUE TITLE
Incorrect render in highstock 6.1.4

### ISSUE THREAD

**Issue by Tantacula** [highcharts/highcharts#9142] opened 2018-10-09 06:36 UTC
Hi, I have an error with a candlestick. Candles are disappearing when I try to zoom my graph. This error comes with 6.1.4 version, but 6.1.3 works fine in this case (but I can't use 6.1.3 because it has other errors). If div container has full width (in 1366 display resolution) - all works fine, but with 50% width candles work buggy.

http://recordit.co/5WKjAX7uuR - there is a demonstration.

I tried to reproduce this bug in jsfiddle, but I meet other error - graph doesn't render correctly if parent block has style "display: grid" (if you'll remove this style from ".trading-first-container", then graph renders correctly in 1366 display resolution). Also if block "candle-container" has width 80% or less it doesn't render correctly in chrome in 1366 display even if parent block has property "display:block".

#### Live demo with steps to reproduce
http://jsfiddle.net/zstjab5x/3/

#### Product version
Highstock 6.1.4, with vuejs

#### Affected browser(s)
Chrome, firefox

**Comment by KacperMadej** [comment] 2018-10-09 12:33
Hi @Tantacula 

Please try to recreate the problem without Vue to be sure that the problem is not caused by it.
You are using a third party vue-highcharts - if the error is in the code please report this to the wrapper authors / maintainers. Official Highcharts wrapper for Vue is here: https://github.com/highcharts/highcharts-vue

**Comment by Tantacula** [comment] 2018-10-09 13:06
@KacperMadej There's demo with the second bug without vuejs. http://jsfiddle.net/rhd3opLa/ Data is invisible inside small width container, but if you'll comment "display:flex" then it will be visible.

**Comment by KacperMadej** [comment] 2018-10-09 14:49
@Tantacula I have removed all files that were not required (or even where required not to be loaded) and the demo works fine (as far as I can see): http://jsfiddle.net/BlackLabel/mwsxozb1/ When using Highstock there's no need to load stock module, so it was removed. Also the third party wrapper was removed, but I'm not sure if this is relevant.

**Comment by Tantacula** [comment] 2018-10-09 15:12
@KacperMadej Could you try to shrink and expand navigator block in chrome on windows 10 with screen resolution 1366x768 as I did this in my video in the first message? I have the same bug in your code example as in my video (red sticks disappears after those actions).

**Comment by KacperMadej** [comment] 2018-10-10 08:42
It seems to be a problem with dataGrouping, but it is resolved on master branch (next version release candidate), so until next version is released you could use the master branch version - demo: http://jsfiddle.net/BlackLabel/6dk14hb2/
or you could wait for next release when the fixed code will be published.

If next version will fail we could reopen this issue, but now closing as resolved, because master works fine.

**Closed by KacperMadej** 2018-10-10 08:42 UTC
Labels: Pending reply
