### ISSUE TITLE
annotation afterUpdate event fires just on click, despite of docs says it is for resize/drag only

### ISSUE THREAD

**Issue by pylnata** [highcharts/highcharts#17450] opened 2022-06-28 16:12 UTC
#### Expected behaviour
afterUpdate shouldn't fire on click. For click we have another event.

#### Actual behaviour
afterUpdate fires on click annotation

#### Live demo with steps to reproduce

https://jsfiddle.net/9mp758jr/

click on any annotation -> alert appear

#### Product version

Highcharts 9.3.3

#### Affected browser(s)
all

**Comment by raf18seb** [comment] 2022-06-29 08:03
Hi @pylnata, thanks for reporting the issue!

Simplified demo: https://jsfiddle.net/BlackLabel/d49qtns3/

**Comment by karolkolodziej** [comment] 2022-07-04 13:24
As said in this PR: https://github.com/highcharts/highcharts/pull/15954, `afterUpdate` event should be fired when clicking the control point.

Should we change the documentation or rather apply a fix like the one bellow to check if the annotation has moved: 
```TS
                if (emitter.hasDragged) { // #17450
                    // ControlPoints vs Annotation:
                    fireEvent(pick(
                        annotation, // #15952
                        emitter
                    ), 'afterUpdate');
                }
```
@pawelfus

**Comment by raf18seb** [comment] 2022-07-05 09:53
I don't agree. I saw that PR (sorry for not providing more info).

Previously, without the above `fireEvent`, the `afterUpdate` event was fired only on firing `annotation.update()` (see my above demo, line 87).

Since that `fireEvent` has been added, the `afterUpdate` event fires on:
1. `annotation.update()`
2. update caused by e.g. dragging - this is what has been fixed by #15954
3. annotation click - this is a regression caused by #15954

In my opinion, the `afterUpdate` event should not be fired on action 3.

**Comment by pawelfus** [comment] 2022-07-26 09:08
Yes, we should fix it. The event should be fired only when the drag action actually did happen.

**Comment by pylnata** [comment] 2024-02-02 07:23
Hi highcharts team, we still need this to be fixed.

**Comment by pawelfus** [comment] 2024-02-02 10:10
We still plan to fix it. It was missing the correct product tag, so we missed it.

**Comment by PadWorks** [comment] 2024-03-28 15:28
@pawelfus, may you have already a workaround for this, till it is fixed?

**Comment by pawelfus** [comment] 2024-03-29 09:39
Hi @PadWorks 

It is hard to workaround it with a plugin, but using options, it is possible. For example: [demo](https://jsfiddle.net/BlackLabel/vypug976/)

Config:
```ts
    events: {
      mousedown: function(e) {
        // Store the timestamp
        this.mouseDownTime = e.timeStamp;
      },
      mouseup: function(e) {
      	// 50ms = drag means click, it is an arbitrary number
        if (e.timeStamp - this.mouseDownTime < 50) {
             // We have click 
            this.itWasClick = true;
        } else {
            this.itWasClick = false;
        }
      },
      click: function() {
        // Click callback
        console.log('click');
      },
      afterUpdate: function() {
        if (this.itWasClick) {
        	return;
        }
        this.itWasClick = void 0;
        console.log('afterUpdate');
        // The rest of code 
      }
    }
```

We can get better results for example by checking also `event.pageX` and `event.pageY`, if the mouse was moved between `mousedown` and `mouseup`. For example:
```ts
      mousedown: function(e) {
        // Store the timestamp
        this.mouseDownTime = e.timeStamp;
        this.mousedownEvent = e; // store the event
      },
      mouseup: function(e) {
      	// 50ms = drag means click, it is an arbitrary number
        if (
          e.timeStamp - this.mouseDownTime < 50 &&
          Math.sqrt(
              Math.pow(this.mousedownEvent.pageX - e.pageX, 2) +
              Math.pow(this.mousedownEvent.pageY - e.pageY, 2)
          ) > 5 // 5 pixels
        ) {
             // We have click 
            this.itWasClick = true;
        } else {
            this.itWasClick = false;
        }
      },
```

**Closed** 2024-05-07 06:52 UTC
Labels: Type: Bug, Product: Highcharts Stock, Priority: Normal, Type: Good for beginners
