### ISSUE TITLE
Synchronise Charts not working properly when charts are next to each other

### ISSUE THREAD

**Issue by harshan355** [highcharts/highcharts#14822] opened 2020-12-17 05:15 UTC
#### Expected behaviour

1. Charts should synchronize not matter the position of the chart (one below the other or one next to other)

#### Actual behaviour
.In the below provided fiddle,
1. Initially the charts are stacked one over the other, in this scenario the cross hair is working fine and charts are in sync with each other.
2.  When we resize the fiddle widthwise, we can see charts coming side by side, in this scenario, when we try to hover on one chart, the cross hair on other charts are not in sync.
3. When we resize it back, we face the similar issue, the charts are not in sync

The requirement i have contains charts sit adjacent to each other and are to be with synchronized cross hair across all charts.
Please help me in providing a solution for this issue.

Thanks in advance

#### Live demo with steps to reproduce
https://jsfiddle.net/3cjts7L1/

#### Affected browser(s)
Chrome

**Comment by KacperMadej** [comment] 2020-12-17 15:39
Hi @harshan355 ,

You have written on our bug tracker. For technical support please see: https://www.highcharts.com/blog/support/
I will close this issue as this is not a bug.

This is a quite popular question about modifying the synchronized charts demo with regards to different layouts, different data ranges, changing tooltip properties, or a number of series in a chart. The answers should be possible to find in our forum and if there is no related topic there then you could open a new one.

Here's a demo you are probably looking for: https://jsfiddle.net/BlackLabel/z7nm6dof/
(It's based on a previous version of the synchronized charts demo - this is why it includes jQuery, but you could adapt this solution to the newer code easily - if not, please contact technical support with the questions.)

**Closed by KacperMadej** 2020-12-17 15:39 UTC
