### ISSUE TITLE
Accessibility module: chart.update

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#6491] opened 2017-03-21 12:12 UTC
#### Expected behaviour
Possible to update accessibility module options through `chart.update()`

#### Actual behaviour
Not possible, but should this be an enhancement suggestion or a bug?

#### Live demo with steps to reproduce
http://jsfiddle.net/6yj098cx/

Steps:
1. Use buttons to update the chart options. 
2. Check through tab + arrow keys if the a11y is enabled or not.

**Comment by ddotlic** [comment] 2017-03-21 13:02
We would be very interested to have this working as a11y (at the moment) interferes with quite a bit of basic chart functionality.

That said, if a11y didn't regress anything, we'd be fine with it being "on" all the time.

**Comment by TorsteinHonsi** [comment] 2017-03-22 10:36
@ddotlic Can you share some specific problems where it interferes with basic chart functionality?

**Comment by ddotlic** [comment] 2017-03-22 10:43
@TorsteinHonsi There are multiple bugs already open, no need to open new ones 😃 I've communicated details with @KacperMadej over (support) email. Fixes only seem to introduce new issues.

We initially asked about (when a11y enabled) crosshair not being drawn even though the position of the "current" bar moves when one uses keyboard.

The fix for this introduced another regression where now one must hover exactly over the bar for the tooltip to show up (using a mouse). This would be "basic chart functionality" - I clearly exaggerated with "quite a bit", I apologize.

On top of these two issues, we've had to work around a problem where due to a11y module stopping the propagation of keyboard events one of our add-ons stopped working (while this is "basic functionality" for us, it's not for the product).

IOW, it has been a small but steady stream of issues ever since we've introduced a11y module, which has lead to some frustration on our part.

**Comment by TorsteinHonsi** [comment] 2017-03-22 10:49
Okay, thanks for sharing!

**Comment by oysteinmoseng** [comment] 2017-03-22 11:10
@ddotlic Is the crosshair issue reported on GitHub? It sounds like a bug with the a11y module.

Also note that you can [disable](http://api.highcharts.com/highcharts/accessibility.keyboardNavigation.enabled) keyboard navigation for the module.

**Comment by ddotlic** [comment] 2017-03-22 11:12
@oysteinmoseng Yes, the crosshair issue is already on GitHub, might have even been fixed in the meantime.
Good to know about keyboard navigation, though we've worked around the issue in a more direct way, thanks for the pointer!

**Closed** 2019-02-21 15:53 UTC
Labels: Backlog, Bug, Priority:High
