### ISSUE TITLE
minPointLength does not show when all data points are 0

### ISSUE THREAD

**Issue by jasonheine** [highcharts/highcharts#7365] opened 2017-11-06 20:44 UTC
#### Expected behaviour
When all data points in a series are 0 it should still set the min height

#### Actual behaviour
It's not showing the columns.

#### Live demo with steps to reproduce
https://jsfiddle.net/0f82w2hy/

**Comment by pawelfus** [comment] 2017-11-07 09:58
Hi @jasonheine 

Thank you for reporting this bug. It's a duplicate of #7311 - let me close this issue.

**Closed by pawelfus** 2017-11-07 09:58 UTC
