### ISSUE TITLE
Highstock Legend overflow entries stacks.

### ISSUE THREAD

**Issue by garybrain** [highcharts/highcharts#11123] opened 2019-06-21 15:29 UTC
#### Expected behaviour
When the graph height exceeds the legend height the bottom entries should be added to a overflow scroll down , 1 of 2 etc

#### Actual behaviour
Bottom legend entries are stacked at top of the graph.

using `"layout":"proximate"`

#### Live demo with steps to reproduce
https://jsfiddle.net/garybrain/d08svw6r/3/

Looking at the code the last two legend items are placed at `transform="translate(8,0)"`

Also the more series you add eventually there will be a 1/2 option appear but they still stack at the top of the page.

https://jsfiddle.net/garybrain/d08svw6r/6/

#### Product version
Highstock 7.1.2

#### Affected browser(s)
All

**Comment by pawelfus** [comment] 2019-06-24 08:24
Hi @garybrain 

Thanks for reporting, but you already did that, see #9104

Closing as duplicate of #9104

**Closed by pawelfus** 2019-06-24 08:24 UTC
