### ISSUE TITLE
Boost zoom issues

### ISSUE THREAD

**Issue by callumacrae** [highcharts/highcharts#7108] opened 2017-08-29 16:23 UTC
Zooming is acting weirdly on some sets of data: when you zoom in and out, the previous line remains visible.

http://jsfiddle.net/LLExL/7949/

Steps to replicate:

- Attempt to zoom in on a section of the chart
- Note that both the zoomed in and non-zoomed in chart are now displaying over each other

Happening in all the browsers I've tested it in on OS X.

It doesn't happen with all sets of data. Nearly every time I generated dummy data, it worked as expected - I have no idea what makes this data different to the rest, but it happens every time with this data.

**Comment by cvasseng** [comment] 2017-09-18 09:53
This is working as expected in `solbrest`: http://jsfiddle.net/LLExL/8044/

**Comment by TorsteinHonsi** [comment] 2018-01-09 14:08
It fails in v6.0.4, but is fixed in master after that: http://jsfiddle.net/LLExL/8350/

Probably fixed by https://github.com/highcharts/highcharts/commit/370c1d09862bd08f51202d38a442c84b750efabf#diff-81e5c427a1b17e82cad4b67e16249a75.

**Closed by TorsteinHonsi** 2018-01-09 14:08 UTC
Labels: Bug, Fix suggested

**Comment by lnunno** [comment] 2018-01-11 16:40
Is a release with this fix available in npm?

**Comment by KacperMadej** [comment] 2018-01-15 14:19
@lnunno The fix will be available with next release. To get more info about how to avoid the issue in v6.0.4 you could check the mentioned above commit. Manually adding the fix to the boost.js that you are using should help if the problem is really fixed there.
