### ISSUE TITLE
Highcharts tooltip placement when hidden

### ISSUE THREAD

**Issue by marcwhitbread** [highcharts/highcharts#3241] opened 2014-07-09 14:20 UTC
Steps to reproduce:
1. tooltip { enabled: true }
2. hover over data point
3. hover out so tooltip disappears
4. view source, tooltip translate(x,y) stays in same position but hidden.

The problem is that the hidden tooltip is now sitting on top of other data points, breaking their tooltip hover because there is a opacity=0 element sitting on top of them preventing the hover. The tooltip stays there until the tooltip is triggered again and moved to another data point.

Fix: after tooltip is hidden, translate(x,y) should be reset so the tooltip is not sitting on top of data points while hidden (opacity=0).

**Comment by pawelfus** [comment] 2015-12-28 13:40
Duplicate of #3088.

**Closed by pawelfus** 2015-12-28 13:40 UTC
