### ISSUE TITLE
Gantt: unable to trigger ellipsis in dataLabels without setting a certain width

### ISSUE THREAD

**Issue by matsomo** [highcharts/highcharts#9775] opened 2019-01-02 12:46 UTC
#### Expected behaviour
Each point handles overflow in its dataLabel based on whether or not the actual label is longer than the point.

#### Actual behaviour
To trigger ellipsis, one must set a certain width in the dataLabel style property.

#### Live demo with steps to reproduce
I tried returning a styled span from the formatter and getting the label-width from the point itself, but it didn't work out.

https://stackblitz.com/edit/react-bijgrs

#### Product version
highcharts: 7.0.1
highcharts-react-official: 2.0.0
react: 16.5.0

#### Affected browser(s)
Chrome, FireFox

**Comment by pawelfus** [comment] 2019-01-03 15:20
Hi @matsomo 

Thank you for reporting the issue! You are right, at this moment, to trigger ellipsis you need to set fixed width. I agree, that would be handy if ellipsis could be bound to the size of the background rectangle underneath.

*Internal note:*
We could consider this feature for all rectangle-based series (column, bar, columnrange, xrange etc.) when `dataLabels.inside` is supported and set to `true`. Just like for a heatmap series.

**Comment by matsomo** [comment] 2019-01-04 08:48
I see. Is it possible to hide the datalabel all together if it overflows?

**Comment by jon-a-nygaard** [comment] 2019-01-04 09:58
Hi @matsomo,

You could add a workaround like in the following example: https://stackblitz.com/edit/react-kvy7d2?file=index.js

This should set the width automatically and trigger the ellipsis when the text overflows. You can probably modify this workaround to hide the datalabel instead should you want to.

Here is the code from the workaround:
```javascript
// Add this after loading Highcharts and before constructing the chart.
Highcharts.wrap(
  Highcharts.seriesTypes.gantt.prototype,
  'alignDataLabel',
  function () {
    // Get list of arguments
    var args = Array.prototype.slice.call(arguments);
    // Retrieve and remove original function from arguments list.
    var proceed = args.shift();
    // Variables
    var point = args[0];
    var dataLabel = args[1];
    var style = args[2].style;

    if (
      // Check that width is not explicitly set
      typeof style.width === 'undefined' &&
      // Check if shapeArgs exists
      point.shapeArgs &&
      // Check if dataLabel exists
      dataLabel
    ) {
      dataLabel.css({
        width: point.shapeArgs.width + 'px'
      });
    }

    // Continue with the original alignDataLabel functionality
    proceed.apply(this, args);
  }
);
```

**Comment by matsomo** [comment] 2019-01-04 12:08
@jon-a-nygaard This is great, thanks. 

I thought about comparing the label width and the point width and changing the visibility to hide the datalabel, but I can't get whiteSpace: "nowrap" to work. It will be visible again when it wraps.

https://stackblitz.com/edit/react-4tikrn

Any ideas?

```
Highcharts.wrap(
  Highcharts.seriesTypes.gantt.prototype,
  'alignDataLabel',
  function () {
    // Get list of arguments
    var args = Array.prototype.slice.call(arguments);
    // Retrieve and remove original function from arguments list.
    var proceed = args.shift();
    // Variables
    var point = args[0];
    var dataLabel = args[1];
    var style = args[2].style;

    var labelWidth = point.dataLabel.width;
    // console.log("label width", point.dataLabel.width);

    if (
      // Check that width is not explicitly set
      typeof style.width === 'undefined' &&
      // Check if shapeArgs exists
      point.shapeArgs &&
      // Check if dataLabel exists
      dataLabel
    ) {
      dataLabel.css({
        width: point.shapeArgs.width + 'px',
        visibility: point.shapeArgs.width < labelWidth ? "hidden" : "visible",
      });
    }

    // Continue with the original alignDataLabel functionality
    proceed.apply(this, args);
  }
);
```

```
plotOptions: {
            series: {
              dataLabels: {
                inside: true,
                format: `{point.label}`,
                style: {
                  whiteSpace: "nowrap"
                }
              }
            }
          },
```

**Comment by pawelfus** [comment] 2019-01-04 14:04
Hi @matsomo 

I think this should be `styles`, not `style` and simply remove `width: point.shapeArgs.width + 'px',`. Demo: https://stackblitz.com/edit/react-bq7gov?file=index.js

**Comment by matsomo** [comment] 2019-01-04 14:08
Okay, thanks for the help

**Comment by pawelfus** [comment] 2020-01-20 10:30
Closing as duplicate of #12527

**Closed by pawelfus** 2020-01-20 10:30 UTC
Labels: Product: Highcharts Gantt, Type: Enhancement
