### ISSUE TITLE
chart panning - selecting outer elements while panning

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#13566] opened 2020-05-20 12:32 UTC
#### Expected behaviour

Last properly working version is 8.0.4: https://jsfiddle.net/BlackLabel/d69r1zok/

#### Actual behaviour

Outer elements from plot area like, labels, range selector etc are selecting while panning the chart, for example when the user has mouse over the tooltip. 

Video for better understanding: https://screencast-o-matic.com/watch/cYhqbnkAJ7

#### Live demo with steps to reproduce

https://jsfiddle.net/BlackLabel/wgm1cz5k/

#### Product version

Highcharts JS v8.1.0 (2020-05-05)

**Comment by sebastianbochan** [comment] 2020-05-21 07:38
Closed as duplicate of https://github.com/highcharts/highcharts/issues/13503

**Closed by sebastianbochan** 2020-05-21 07:38 UTC
Labels: Product: Highcharts Stock, Type: Regression
