### ISSUE TITLE
Highcharts lineWidth and color options are not working

### ISSUE THREAD

**Issue by Deimos620** [highcharts/highcharts#7535] opened 2017-12-14 00:29 UTC
I am contacting again because of I found the reason of issue #7500 correctly.
I've installed highcharts with bower, with this command

> bower install highcharts

In the "highcharts" directory, I've found two highcharts.js files.
One is : bower_components/highcharts/highcharts.js
Another one is: bower_componetns/highcharts/js/highcharts.js
They have same version mark like below.
>  ( Highcharts JS v6.0.3 (2017-11-14)
> 
>  (c) 2009-2016 Torstein Honsi
> 
>  License: www.highcharts.com/license

And the issue, I mentioned (issue #7500) is occured when I use "js/highcharts.js", instead of highcharts.js in root directory.
I've updated highcharts lib from "js/highcharts.js" to "highcharts.js", and it worked correctly.

Which one is true version of highcharts? "js/highcharts.js" or "highcharts.js"? What is different between two versions of library?

**Comment by pawelfus** [comment] 2017-12-14 10:56
Hi @Deimos620 

Please, check my answer in the previous ticket: https://github.com/highcharts/highcharts/issues/7500#issuecomment-351666620 - Closing as a duplicate. We can reopen previous ticket if you are not convinced that it's not a bug..

**Closed by pawelfus** 2017-12-14 10:56 UTC
