### ISSUE TITLE
XRange chart: y axis grid lines placed differently for ca

### ISSUE THREAD

**Issue by PohlodSlavik** [highcharts/highcharts#11558] opened 2019-08-05 08:54 UTC
#### Expected behaviour
In case when y axis contain only single category grid lines should be rendered the same way as for multiple categories (one on the top of the axis and one on the bottom).

#### Actual behaviour
There is only single grid line on the middle of the axis.

#### Live demo with steps to reproduce
https://jsfiddle.net/7jq951bp/

#### Product version
Highcharts - 7.1.2

#### Affected browser(s)
All (tested on IE11, Edge, Chrome v75)

**Comment by pawelfus** [comment] 2019-08-05 09:28
Thank you for reporting the issue, but I'm not able to reproduce the issue, see attached screenshots:

Single:
![Screen Shot 2019-08-05 at 11 27 56](https://user-images.githubusercontent.com/1453926/62454175-22d53c00-b774-11e9-9da9-95e1b1389d41.png)
Multiple:
![Screen Shot 2019-08-05 at 11 27 47](https://user-images.githubusercontent.com/1453926/62454176-22d53c00-b774-11e9-888c-6286ba297587.png)

**Comment by PohlodSlavik** [comment] 2019-08-05 09:42
Oups, I've posted wrong link(with my custom workaround). Here is the right one: https://jsfiddle.net/eobxfdqs/1/

**Comment by pawelfus** [comment] 2019-08-05 12:16
Ah, thanks! For the demo and the workaround ;) It's actually a duplicate of #11199 - it's not limited to the xrange series, the same happens with other series, for example scatter: https://jsfiddle.net/qu1pc5z2/

**Closed by pawelfus** 2019-08-05 12:16 UTC
Labels: Status: Can't reproduce
