### ISSUE TITLE
Pie chart data labels - allowOverlap is not working

### ISSUE THREAD

**Issue by tejaspchordiya** [highcharts/highcharts#8330] opened 2018-05-14 10:12 UTC
#### Actual Behaviour
Pie Chart data labels are overlapping even when I set allowOverlap as false.

JSFiddle: https://jsfiddle.net/tejaspchordiya/vdonaL7L/

#### Expected Behaviour
Data labels should not overlap or at least ellipsis should appear for long data labels.

**Comment by sebastianbochan** [comment] 2018-05-14 10:52
Hi @tejaspchordiya,
Thank you for the reporting. It is regression, in the v6.0.7 worked well.

Workaround:
Set useHTML parameter as true:
- https://jsfiddle.net/BlackLabel/ch37jcwp/

Related topic:
https://github.com/highcharts/highcharts/issues/7975

**Internal note**
The textOverflow option seems to not working properly:
- https://jsfiddle.net/BlackLabel/hn3ssfmb/

**Comment by sebastianbochan** [comment] 2018-05-16 08:34
Hi @tejaspchordiya 
You can set the [center](https://api.highcharts.com/highcharts/series.pie.center) parameter:
- https://jsfiddle.net/BlackLabel/whrdcLay/

Set width parameter for ellipsis:
- https://jsfiddle.net/BlackLabel/jbayjpv8/

**Comment by tejaspchordiya** [comment] 2018-05-16 10:34
Hi @sebastianbochan 

After playing for some time with examples you shared, here are my few observations:
- Issue of positioning ring seem to have resolved with center attribute.
- But issue of ring size still persist. The ring size is not relative to the plot size, in other words, irrespective of the plot size the ring size remains unchanged (try resizing the output frame in fiddle):
https://jsfiddle.net/tejaspchordiya/whrdcLay/1/
- The width parameter seem to be not behaving properly, try changing width (to 100) in example that you shared:
https://jsfiddle.net/BlackLabel/jbayjpv8/
We are using Ring chart in an environment where data keeps changing dynamically. Hence, asking user to set width attribute each time for data labels does not seem an ideal solution to me. I would expect Highcharts to apply intellegence once textOverflow parameter is set to ellipsis.

**Comment by sebastianbochan** [comment] 2018-05-17 08:28
Hi @tejaspchordiya,
You can control size by the option `plotOptions.pie.size` and set the value in percentage.
Demo:
- https://jsfiddle.net/BlackLabel/jqe2jwxg/

Regarding to the width, indeed it is a little bit buggy.

**Comment by pawanvjadhav** [comment] 2018-05-17 08:33
Sebastianbochan,

We really can't put buggy solution at this time in main Product branch. We really need a solution which is full proof and will work on all cases (User inputs). We don't have much time to test all scenarios.

How much time it will take for you to fix this issue in library itself? Or This is not possible?

**Comment by KacperMadej** [comment] 2018-05-17 11:18
We do not have an ETA for the fix for now, but we will be working on resolving the issue - it's possible to fix the problem.

Since this is a regression then you could use last working version until a new version with fix will be released, so version 6.0.7. https://jsfiddle.net/BlackLabel/vdonaL7L/1/

**Comment by pawelfus** [comment] 2018-05-29 15:11
**Note:**
It looks like a problem with `rem` for fonts. I don't see any failing case when fontSize is set in pixels: https://jsfiddle.net/vdonaL7L/2/

**Comment by TorsteinHonsi** [comment] 2018-05-30 11:42
The regression is a consequence of a change we did to prevent the data labels to be drawn too far away from the pie slice. Two commits affect this issue:

* bcb146c26 - Labels were moved into better positions: https://jsfiddle.net/vdonaL7L/3/
* d5a13f022 - Trying to improve the word-wrap, we now accidentally caused overlapping: https://jsfiddle.net/vdonaL7L/4/

**Closed** 2018-05-30 13:11 UTC
Labels: Regression
