### ISSUE TITLE
column chart 1st point cut off (clipped) (single point)

### ISSUE THREAD

**Issue by nizrix** [highcharts/highcharts#16660] opened 2021-11-16 15:15 UTC
#### Expected behaviour
When working with tick positioner on column chart with datetime type with only 1 data point on the first tick, the chart should set the correct position of the ticks and column width should not be cut off. 

#### Actual behaviour
The tick position are on the edge of x-axis so the point is cut off in the middle (only when using tick positioner and the chart have only 1 point that set on the first tick.

#### Live demo with steps to reproduce
Example: https://jsfiddle.net/nizrix/zxemwdg9/2/

No action needed,
To see the correct behavior you can remove the remark from the 2`nd point in the example.

#### Product version
Highcharts, v9.3.1

#### Affected browser(s)
All

**Comment by raf18seb** [comment] 2021-11-19 13:39
Hi @nizrix, thanks for reporting the issue!

Simplified demo: https://jsfiddle.net/BlackLabel/t24b83ej/

I think it's not a bug. This happens because the series is clipped exactly from a place where the xAxis starts - you moved the xAxis to the right by setting `xAxis.left`.
It's visible here in this demo: https://jsfiddle.net/BlackLabel/85xpguzj/

If you want the series not being cut (clipped), set [series.clip](https://api.highcharts.com/highcharts/series.column.clip) to false
Demo: https://jsfiddle.net/BlackLabel/520wnb6L/

Closing as not a bug and resolved, but feel free to share any insights.

**Closed by raf18seb** 2021-11-19 13:39 UTC

**Comment by nizrix** [comment] 2021-11-23 10:37
Hi @raf18seb , thanks for your help.
Using the "clip:false" parameter you suggested does the work for me.
Even doe, I still cant understand the different behavior when there is only one point on the chart (first line is cut off) and two or more point (first point not cuts off).

1 point cuts off: https://jsfiddle.net/BlackLabel/t24b83ej/ (your simplify example)
2+ points not cut off: https://jsfiddle.net/nizrix/nawhbx8y/1/ (based on your simplify example)

**Comment by raf18seb** [comment] 2021-11-23 14:05
@nizrix,

Because with only one point, the `series.pointRange` is not calculated. By definition, [pointRange](https://api.highcharts.com/highcharts/series.column.pointRange) is the distance between the two closest data points.

You can set manually `pointRange: 1` - the columns will be displayed correctly without disabling the clip.
