### ISSUE TITLE
Dependency wheel node label style with connectorAllowed option not working

### ISSUE THREAD

**Issue by vadherdhaval** [highcharts/highcharts#14430] opened 2020-10-27 04:17 UTC
#### Expected behaviour
[https://user-images.githubusercontent.com/527578/59928190-30c13e80-940c-11e9-86df-4899b8eabfe0.png](url)

Node labels should look like as per above image. 

#### Actual behaviour
As per issue "11115" the labels are not readable if its too long.

**Comment by vadherdhaval** [comment] 2020-10-27 04:18
![59928190-30c13e80-940c-11e9-86df-4899b8eabfe0](https://user-images.githubusercontent.com/109577/97256620-87792c80-1839-11eb-965b-c46c7ea4319e.png)

**Comment by pawelfus** [comment] 2020-10-27 09:13
Hi @vadherdhaval 

Thank you for reporting the issue. The `dependencyWheel.label` option does not work dependency wheel series because this series does not have graph or area. You can observe how `series-label` plugin works for example here: https://www.highcharts.com/demo/line-basic - series labels inside the plotting area are the ones configured using this option.

What you have on your image are `dataLabels`, not `label`. The feature you request has already it's own ticket, take a look: #11115

Closing ticket as a duplicate of #11115.

**Closed by pawelfus** 2020-10-27 09:13 UTC
Labels: Type: Duplicate
