### ISSUE TITLE
Chart Sankey marginBottom or spacing Bottom cuts off Offset

### ISSUE THREAD

**Issue by imjeffp** [highcharts/highcharts#8644] opened 2018-07-18 20:37 UTC
#### Expected behaviour:
Using marginBottom or spacingBottom to add space at the bottom of a Sankey to allow for an offset node.

#### Actual behaviour: 
Node and link get cut off at margin.

#### Live demo with steps to reproduce
https://codepen.io/imjeffp/pen/KBgqNQ
Change line 77 (offset value) to see the link and node being cut off.

#### Product version
Highcharts JS v6.1.1 (2018-06-27)

#### Affected browser(s)
Safari, Chrome, Firefox

**Comment by sebastianbochan** [comment] 2018-07-19 07:57
Hi @imjeffp,
Thank you for contacting us.
Let me compare both scenarios:
#1 `offset: 60`
![zrzut ekranu 2018-07-19 o 09 55 13](https://user-images.githubusercontent.com/2115686/42929351-1770ebbe-8b3a-11e8-9e76-c045763d1a8c.png)

#2 without offset
![zrzut ekranu 2018-07-19 o 09 55 23](https://user-images.githubusercontent.com/2115686/42929368-1e1c6614-8b3a-11e8-9d41-8688bb0dad47.png)

In both cases Im not able to find a cut edge. Could you take a screenshot and mark the issue?

**Comment by imjeffp** [comment] 2018-07-19 18:06
`offset: 60` should look like this (minus the black line, of course).

![untitled-1](https://user-images.githubusercontent.com/25798597/42961449-65b07a1e-8b54-11e8-9cd6-388cb49d7996.png)

**Comment by imjeffp** [comment] 2018-07-19 18:11
You can also see how the "Stock Change" label is pushed above the center of its node, since it seems to think it's too close to the edge of the chart.

**Comment by sebastianbochan** [comment] 2018-07-20 06:59
Hi @imjeffp,
In all scenarios (enabled / disasabled offset or margin) the label is not vertically centered. 

The solution is disable padding.
**Demo:**
- https://codepen.io/Blacklabel/pen/JBbaWY

Please confirm if it is only the bug with vertical center or something more?

**Comment by imjeffp** [comment] 2018-07-20 15:17
Consider this version: https://codepen.io/imjeffp/pen/KBgqNQ
You can see that the nodes in columns 1 & 4 are completely cut off.
![screen-shot-2018-07-20-at-9 59 06-am](https://user-images.githubusercontent.com/25798597/43009916-a0a636d0-8c04-11e8-9888-416e5863116a.png)

**Comment by imjeffp** [comment] 2018-07-20 15:20
My goal is to make this:
![screen shot 2018-07-20 at 10 17 59 am](https://user-images.githubusercontent.com/25798597/43010510-45b0feca-8c06-11e8-9259-2942ca807466.png)

Look like this:
![unknown](https://user-images.githubusercontent.com/25798597/43010546-559a6858-8c06-11e8-9ecf-772dae67e2cc.png)

And I can't do that using offset because things get cut off.

**Comment by pawelfus** [comment] 2018-07-23 10:06
@imjeffp 

Is this a duplicate of #8653 ? If you set offset to high, then it will be rendered outside the container. I see you try to increase available space artificially by setting margin and spacing options. It can work, but you also need to set `series.clip` to false: https://codepen.io/anon/pen/pZeKWX

**Comment by imjeffp** [comment] 2018-07-23 13:08
Hi Pawel 

Maybe not a duplicate, but the same issue, yes. Sorry about the spam. 

seriesClip looks like the answer here, except for the node labels. Setting the padding to 0 isn’t great. 

Thanks for your help!

**Comment by pawelfus** [comment] 2018-07-24 08:32
Ok, closing the issue then.

Regarding dataLabels, options like `crop` and `overflow` should resolve the issue: https://codepen.io/anon/pen/pZeKWX

**Closed by pawelfus** 2018-07-24 08:32 UTC
Labels: Pending reply

**Comment by imjeffp** [comment] 2018-07-25 17:53
A chart with everything working:
https://codepen.io/imjeffp/pen/KBgqNQ

`spacingBottom` makes room for the offset nodes. (Could also use `spacingTop`.)
`offset` moves nodes out of the plot area.
`seriesClip: false` allows the offset nodes to appear outside the plot area.
`dataLabels.overflow: "none"` moves the data labels out of the plot area. _Do this per node or all of the labels will break out of the plot area._
`y` realigns the data labels with the nodes.

**Comment by imjeffp** [comment] 2018-07-25 20:13
Another chart with everything working: https://codepen.io/imjeffp/pen/pZrvOr?editors=0010

Compare to: https://codepen.io/imjeffp/pen/Epyvzw
