### ISSUE TITLE
Xrange: Tooltip dates are not 

### ISSUE THREAD

**Issue by Miced** [highcharts/highcharts#9351] opened 2018-11-07 21:36 UTC
#### Expected behaviour
Tooltip in x-range series with dates should display date range.

#### Actual behaviour
Tooltip displays a date's microseconds

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/x-range/

#### Product version
Highcharts 6.2.0
Version 6.1.x was functional.

#### Affected browser(s)
Chrome, Firefox tested.

**Comment by TorsteinHonsi** [comment] 2018-11-08 14:02
Thanks for reporting! This is a duplicate of #9301 (fixed).

Your demo with the fix applied: https://jsfiddle.net/highcharts/cg6e3m8a/

**Closed by TorsteinHonsi** 2018-11-08 14:02 UTC
Labels: Duplicate

**Comment by Miced** [comment] 2018-11-08 20:14
Thanks for mentioning, I did not manage to find anything related myself.
