### ISSUE TITLE
DataLabels issue on stacked column

### ISSUE THREAD

**Issue by kaotoby** [highcharts/highcharts#4118] opened 2015-04-20 18:06 UTC
It happens when clicking on the legend which the series contains all null datas. (Maybe)
And the strange thing happens...

Example: http://jsfiddle.net/kaotoby/hebb98xq/

**Comment by stephanevanraes** [comment] 2015-04-21 06:47
Slighly simplified: http://jsfiddle.net/hebb98xq/1/

**Comment by kaotoby** [comment] 2015-04-21 13:54
Even without a null series, it'll still trigger this bug.
A frok from stephanevanraes without the null series:
 https://jsfiddle.net/kaotoby/noqLa467/

Notice when x = 3,4,5,10
![qq 20150421214955](https://cloud.githubusercontent.com/assets/5140411/7253619/8c0005a2-e870-11e4-8914-b0b8c8c9a6c9.png)
http://jsfiddle.net/kaotoby/noqLa467/

**Comment by highslide-software** [comment] 2015-04-22 06:52
What exactly do you mean by "strange things happens"?

In [Stephane's sample](http://jsfiddle.net/hebb98xq/1/), I see data labels appearing and disappearing when enabling or disabling the "None Null" series.

In [your latest sample](http://jsfiddle.net/kaotoby/noqLa467/), I see data labels overlapping the stack labels in the initial view.

**Comment by kaotoby** [comment] 2015-04-22 07:46
In Stephane's sample, it'll trigger some overlapping and "label display on minor data instead on major data"  when enabling or disabling "All null" series.
On my latest sample, I noticed this will also happened even with out "All Null" series.

The data labels display should be controlled by plotOptions.column.dataLabels.padding (I guess it's what designed for). When the column  height is less than certain calculated value base on plotOptions, the label should not show up. Instead, labels visibility are all messed up.

So, on my latest sample, the data label shouldn't be displayed when x = 3,4,5,9(black),10(blue), and data label should be displayed when x = 10(black), base on data label(black) is not display when x=8.

**Comment by highslide-software** [comment] 2015-04-22 08:42
There is no logic today that hides the data label if the column itself is not high enough. The logic that hides the labels is a simple anti-collision algorithm, that loops over the labels. If a label is overlapping with one previously drawn, it is hidden. It doesn't take the value into consideration, hence we may have cases where a label for the value 1 hides a label with the value 10. The commit above fixes that issue. 

Another issue with your demo is that the stack labels are not taken into consideration when doing anti collision.

**Comment by KacperMadej** [comment] 2018-05-02 18:47
In short: two problems, 1st resolved, 2nd is a duplicate of #7007, so closing this issue.

**Closed by KacperMadej** 2018-05-02 18:47 UTC
Labels: Bug
