### ISSUE TITLE
Line annotations (i.e., Ray) change their direction as base points go out of viewport

### ISSUE THREAD

**Issue by drbeep** [highcharts/highcharts#10097] opened 2019-02-08 12:05 UTC
#### Expected behaviour
I paint a Ray annotation (by placing 2 base points). Next, I use Navigator to change my viewport (take a closer look on particular piece of a chart) . I expect Ray to keep its line direction the same (i.e., still having approx. the same Y value for give X values)  

#### Actual behaviour
Ray changes its direction quite often. Take a look to pics below (red area added to focus your attention on where do I see direction changing).

Before zooming:
![screenshot from 2019-02-08 06-53-43](https://user-images.githubusercontent.com/4726037/52477389-b46e4300-2b6f-11e9-9cc7-72162652be1c.png)

After zooming:
![screenshot from 2019-02-08 06-53-48](https://user-images.githubusercontent.com/4726037/52477362-99033800-2b6f-11e9-98c2-2c89b420f7bf.png)

#### Live demo with steps to reproduce
Your official demo https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/stock-tools-custom-gui/

1. Paint a Ray figure
2. Use Navigator to zoom closer and see your Ray changing, even when Data Grouping does not add new candles. 

#### Product version
Highstock 7.0.3, as for today

#### Affected browser(s)
I'm using Chrome 71.0.3578.98 (Official Build) (64-bit)

**Comment by pawelfus** [comment] 2019-02-08 15:21
Hi @drbeep 

Thank you for reporting. You are right, it's broken.

We can workaround this by setting [`series.getExtremesFromAll`](https://api.highcharts.com/highstock/plotOptions.series.getExtremesFromAll), demo: https://jsfiddle.net/BlackLabel/7021bqov/ but we will now have always extremes on yAxis fixed to the whole dataset, instead of dynamic ones according to the viewing part of data. 

This issue originates from `xAxis.ordinal` (with disabled it's also fine: https://jsfiddle.net/BlackLabel/7021bqov/3/) - where xAxis has irregular interval between ticks. Because of the performance, we don't calculate all possible ticks, but only visible ones, so we are not able to guess where the first (and second) control point of the annotation should be rendered on xAxis.

This is a duplicate of #2406 - issue was not that popular before Annotations and StockTools module, we should prioritize that issue now.

Closing as duplicate of #2406.

**Closed by pawelfus** 2019-02-08 15:21 UTC
