### ISSUE TITLE
columnrange and stacking: TypeError: num.toPrecision is not a function

### ISSUE THREAD

**Issue by vasild** [highcharts/highcharts#2798] opened 2014-03-11 16:32 UTC
Using columnrange and stacking could result in Highcharts code trying to call toPrecision() on a string like "null10,20".

This is because of this line in Series.prototype.setStackedPoints:

stack.total = correctFloat(stack.total + (y || 0));

where stack.total is null and y is an array like e.g. [10, 20].

Reproduce (enable the "stacking: 'normal'," line): http://jsfiddle.net/vasild/P4r2Z/

What I am trying to do is to put those two columns on top of each other, but using stacking: 'normal' leads me to the above mentioned bug.

**Comment by nollybear** [comment] 2018-03-15 23:42
I just used a workaround of checking/deleting null values that are stacked

**Comment by KacperMadej** [comment] 2019-01-24 23:04
Unable to recreate the problem with error.
Stacked columnrange series type doesn't make sense as points have ranges and not a stackable value.

I'm closing the issue as resolved, but if you would like to see it reopened and have more info (a live demo showing the problem, description about how should columnrange be stacked) please leave a comment and the issue could be reopened.

**Closed by KacperMadej** 2019-01-24 23:04 UTC

**Comment by oldmansutton** [comment] 2021-05-04 13:31
I had the same problem, using a stacked column (not columnrange) chart with dataGrouping.  I would error out on the exact same line, but because stack.total was null (y was a valid number).  My problem was I would call a chart update to change my xAxis datetime grouping from daily to weekly, and changing the datagrouping approximation from sum to average.  For me, I had set the the approximation to 'averages' rather than 'average'.  Took me quite a while to figure out it was that typo that was causing the correctFloat() function to error by leaving stack.total = null, so posting this here in case anyone else comes here looking for answers (like I did).

Regardless if it could be reproduced at the time or not, I think it would be good practice to sanity check stack.total and y before passing them to correctFloat(), because this error CAN (and does) happen.
