### ISSUE TITLE
React Bar labels hover bars

### ISSUE THREAD

**Issue by BaymaxGroot** [highcharts/highcharts#10799] opened 2019-05-23 02:58 UTC
Hi all,
  Lately I use highchart in react, but there are some issue when render horizontal bar chart!

Here is the bar chart config object:

 `Highcharts.chart({
			chart: {
				type: "bar",
				height: "480px"
			},
			title: {
				text: "Left aligned X axis labels"
			},
			xAxis: {
				categories: ["Apples", "Oranges", "Pears", "Grapes", "Bananas"],
				labels: {
					align: "left",
					reserveSpace: true
				}
			},
			yAxis: {
				min: 0,
				title: {
					text: "Total fruit consumption"
				}
			},
			legend: {
				reversed: true
			},
			plotOptions: {
				series: {
					stacking: "normal"
				}
			},
			series: [{
				name: "John",
				data: [5, 3, 4, 7, 2]
			}]
		});`

Here is the screenshot:
![image](https://user-images.githubusercontent.com/30405676/58222726-948f1380-7d49-11e9-83d5-09121bbed3cd.png)

Waiting for your help urgent! 

Thk/Lele

**Comment by sebastianbochan** [comment] 2019-05-23 09:02
Hi @BaymaxGroot,
Thank you for reporting. I created the live demo of your chart here: https://jsfiddle.net/BlackLabel/Lsqyz24f/ but I was not able to reproduce the issue. 

Could you update my demo with your full code for the further debugging?

**Comment by sebastianbochan** [comment] 2019-07-03 11:06
Im closing this ticket due to inactvitation.

Please reopen if live demo and additional details will be available.

**Closed by sebastianbochan** 2019-07-03 11:06 UTC
Labels: Status: Can't reproduce
