### ISSUE TITLE
line plot with scrollbars enabled on a min+max constrained axis shows scrollbar with null point

### ISSUE THREAD

**Issue by ochristensen** [highcharts/highcharts#16405] opened 2021-09-24 22:43 UTC
#### Expected behaviour
a line plot with a gap in the data to be displayed without a scrollbar, respecting the min and max for the scrollable axis

#### Actual behaviour
putting a null value in the data a) causes error 15 (Highcharts expects the data to be sorted) and b) causes a scrollbar to appear and the offscreen region that is scrollable has no tick labels

#### Live demo with steps to reproduce
https://jsfiddle.net/zenzizen/b09aqf8j/28/

moving the null point to first in the data, causes error 15 to disappear but is obviously different data.

#### Product version
Highcharts + Highstock latest

#### Affected browser(s)
All

This feels like the null point is being normalized to x=0?

**Comment by ochristensen** [comment] 2021-09-24 23:47
an example without the scrollbars shows the x axis being given a range that is simply wrong for the non-null data:
https://jsfiddle.net/zenzizen/b09aqf8j/31/

**Comment by raf18seb** [comment] 2021-09-27 15:34
Hi @ochristensen, thanks for creating the ticket!

The reason for this behavior is that (as the error 15 clearly states) your data is not sorted by x.
When defining points as `[x, y]` arrays (or objects `{ x: x, y: y }`), you need all points to be in the same format. But your null value is not.
Please take a look at this sample data:
```js
[
    [150, 7],
    null,
    [151, 7.1],
    [153, 6.8],
    null,
    [154, 7]
]
```

Here, the null values have no `x` defined so Highcharts interprets it like this:
```js
[
    [150, 7],
    [0, null],
    [151, 7.1],
    [153, 6.8],
    [1, null],
    [154, 7]
]
```

As you can see, the data is not sorted by `x` escending. That's why the error 15 is thrown into the console and some unexpected issues occur.

To make it work properly, you can define your data like this:
```js
[
    [150, 7],
    [150, null],
    [151, 7.1],
    [153, 6.8],
    [153, null],
    [154, 7]
]
```

Let me know if you have any further concerns. For now, I'm closing this ticket as not a bug.

**Closed by raf18seb** 2021-09-27 15:34 UTC
