### ISSUE TITLE
Missing connector in gantt with dependency and navigation

### ISSUE THREAD

**Issue by NordicLight** [highcharts/highcharts#12691] opened 2019-12-30 11:27 UTC
#### Expected behaviour
The dependency link between bars shall not disappear when dragging the navigation (please see picture below) 

#### Actual behaviour
Dependency link disappears once navigation is dragged

#### Live demo with steps to reproduce
https://jsfiddle.net/JohanBrodin/4mkgsu8y/9/

#### Product version
Copy from your demo on you homepage today

#### Affected browser(s)
Did test on Chrome

Dependency link shown when navigation is full
<img width="300" alt="Screenshot 2019-12-30 at 12 24 37" src="https://user-images.githubusercontent.com/9700899/71580091-897e3c00-2aff-11ea-8089-92dda79f1f46.png">

Dependency link is not seen once navigation is used
<img width="300" alt="Screenshot 2019-12-30 at 12 24 54" src="https://user-images.githubusercontent.com/9700899/71580111-a450b080-2aff-11ea-95f5-1c2518773e9d.png">

**Comment by pawelfus** [comment] 2019-12-31 10:37
Thanks for reporting this issue @NordicLight 

We actually have two bugs here:
- missing connector when left side of the point is outside the extremes
- animation after navigator's resize

The first one can be workarounded this way: https://jsfiddle.net/BlackLabel/vf5xcsyb/ 
Snippet:
```js
(function(H) {
  H.addEvent(
    H.Series,
    'afterTranslate',
    function() {
      const yAxis = this.yAxis;
      const xAxis = this.xAxis;

      this.points.forEach(
        function(point) {
          const shapeArgs = point.shapeArgs,
            plotX = point.plotX,
            plotY = point.plotY;

          point.isInside = typeof plotY !== 'undefined' &&
            typeof shapeArgs !== 'undefined' &&
            plotY >= 0 &&
            plotY <= yAxis.len &&
            shapeArgs.x + shapeArgs.width >= 0 &&
            plotX <= xAxis.len
        }
      );
    }
  );
})(Highcharts);
```
The second one is caused by picking up initial animation of the series, instead of the global one: https://jsfiddle.net/BlackLabel/e4gmjL1r/ (disabled initial `series.animation`)

**Comment by NordicLight** [comment] 2020-01-01 22:06
Thank you for your answer! We are using the gantt charts in an Angular 8 project and you cannot simple drag in a script into the html page. So I do not know how to apply your code snippet. Do you have a suggestion? Also I did try them both and no-one seems to fix the problem.

Can I expect these two bugs to be corrected in a future version and if so do I keep track of the progress here?

**Comment by pawelfus** [comment] 2020-01-02 09:33
> We are using the gantt charts in an Angular 8 project and you cannot simple drag in a script into the html page. So I do not know how to apply your code snippet. Do you have a suggestion?

Yes, please create a separate file and put there my snippet. Then load this file as any other Highcharts plugin (e.g. exporting).

> Can I expect these two bugs to be corrected in a future version and if so do I keep track of the progress here?

Yes, these bugs should be fixed in a future version and all updates you will see in this ticket.

**Closed** 2021-02-04 14:06 UTC
Labels: Product: Highcharts Gantt, Status: In progress, Type: Bug
