### ISSUE TITLE
Chart.update() in 7.0 override config.series

### ISSUE THREAD

**Issue by monopieces** [highcharts/highcharts#9722] opened 2018-12-19 07:31 UTC
#### Expected behaviour
Change chart type but keep series name

#### Actual behaviour
Previous series name disappeared.
`chart.update()` function override config series value. All keys in `config.series` get lost except `data`.

#### Live demo with steps to reproduce
https://jsfiddle.net/2a6by3mk/1/
Click **Update** button, change the chart type, you can see the series name changed.

#### Product version
7.0.0

**Comment by SBoudrias** [comment] 2018-12-19 07:55
I think the **Expected behaviour** is for Highcharts to not mutate any objects we pass to `update()`.

**Comment by sebastianbochan** [comment] 2018-12-19 09:46
Hi @monopieces,
Thank you for reporting. It looks like regression bug, because in the 6.2 it worked properly.

**Workaround**
Use `series.update` instead of `chart.update`.
- https://jsfiddle.net/BlackLabel/1abzxmL6/

**Internal note**
v6.2.0
- https://jsfiddle.net/BlackLabel/ysbwhtrm/

**Comment by KacperMadej** [comment] 2018-12-19 22:43
Duplicate of #9711
Resolved in v7.0.1 - demo: https://jsfiddle.net/BlackLabel/2x76ynes/

**Closed by KacperMadej** 2018-12-19 22:43 UTC
Labels: Regression
