### ISSUE TITLE
Navigator causes on of the y axis to be wrongly displayed

### ISSUE THREAD

**Issue by PhilippeCourtemanche** [highcharts/highcharts#11204] opened 2019-06-27 17:59 UTC
#### Expected behaviour
![image](https://user-images.githubusercontent.com/15952147/60288811-fad7fa80-98e2-11e9-842d-152586e72a6b.png)
These two y-axes are correctly positioned when navigator is disabled

#### Actual behaviour
![image](https://user-images.githubusercontent.com/15952147/60289029-7b96f680-98e3-11e9-91b3-cab7d4a1a58c.png)
The second y-axis is positioned beside the navigator when navigator is enabled

#### Product version
    "highcharts": "^7.1.1",
    "highcharts-react-official": "^2.1.3",

**Comment by sebastianbochan** [comment] 2019-06-28 07:53
Hi @PhilippeCourtemanche,
Thank you for reporting about the problem. Could you isolate your chart (from your application) and reproduce as live demo in any sandbox? It will allow us to debug and find a solution.

**Comment by PhilippeCourtemanche** [comment] 2019-07-02 16:01
Hi, here's an example with React-Highcharts official

The problem seems to occur when adding a y-axis from an initial state where there are none

https://stackblitz.com/edit/react-op9awl

**Comment by pawelfus** [comment] 2019-07-03 08:43
Thanks for the demo! This is the same issue as #9671

Closing as duplicate of #9671

**Closed by pawelfus** 2019-07-03 08:43 UTC
Labels: Status: Pending reply
