### ISSUE TITLE
chart.update() with scrollPositionX: 1 repositions Y axis incorrectly

### ISSUE THREAD

**Issue by jareware** [highcharts/highcharts#12784] opened 2020-01-14 12:14 UTC
#### Expected behaviour

When calling `chart.update()` on the [official demo of `scrollPositionX: 1`](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/chart/scrollable-plotarea), with unchanged options, the chart should stay the same. 

#### Actual behaviour

When calling `chart.update()`, the Y-axis jumps to a position where it'd be rendered were it not for the scroll offset:

![Peek 2020-01-14 14-13](https://user-images.githubusercontent.com/560055/72343696-246a3f00-36d8-11ea-92b4-51013c383f0c.gif)

#### Live demo with steps to reproduce

https://jsfiddle.net/ubdpj8te/1/

This is the [official demo of `scrollPositionX: 1`](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/chart/scrollable-plotarea), with only a `chart.update()` call added after a few seconds' timeout.

#### Product version

`v8.0.0 (2019-12-10)` served from https://code.highcharts.com/highcharts.js

#### Affected browser(s)

Verified on:

* Latest Firefox and Chrome on Ubuntu

**Comment by pawelfus** [comment] 2020-01-15 10:26
Thanks for reporting the issue @jareware 

It's actually a duplicate of #8862 - simplified demo to call `yAxis.update()`: https://jsfiddle.net/BlackLabel/6xj82dpg/

**Closed by pawelfus** 2020-01-15 10:26 UTC
