### ISSUE TITLE
Incorrect maker highlighted on hover and wrong value displayed. Chart Height affects bug

### ISSUE THREAD

**Issue by iisfaq** [highcharts/highcharts#6727] opened 2017-05-15 19:38 UTC
While hovering over a 2 series chart using ToolTip Shared the last data point for the Average Series does not show the correct data point value. It shows the previous points value. It also highlights the previous marker. 

This is only applicable when the chart height is > 300  pixels high. If the chart height is 300 pixles the fault is not shown, but a height of 600 shows the bug.

If you hover over the marker on the last column directly the correct data is displayed, but moving the mouse up/down will show the value from another column.

#### Expected behaviour

The tooltip should display the correct data from the column it is hovered over. The highlight should highlight the correct marker.

#### Actual behaviour

The tool tip and the highlight of the marker can use the value from another column. 

![bug](https://cloud.githubusercontent.com/assets/5828178/26075781/9a22d176-3a0a-11e7-826a-548aed021793.gif)

#### Live demo with steps to reproduce
https://jsfiddle.net/iisfaq/5u7q0Lzt/2/

Change the css height from 600 to 300 and then hover over the last item to see the issue gone.

#### Affected browser(s)

Chrome - Version 58.0.3029.110 (64-bit)

**Comment by pawelfus** [comment] 2017-05-16 08:52
Hi @iisfaq 

Thank you for reporting this issue. It's already fixed on our master branch and fix will be included in the next release, please take a look: http://jsfiddle.net/5u7q0Lzt/3/

Duplicate of #6687

**Closed by pawelfus** 2017-05-16 08:52 UTC
