### ISSUE TITLE
Chart not responsively reducing when in Grid layout.

### ISSUE THREAD

**Issue by kdavidenkovmware** [highcharts/highcharts#18009] opened 2022-11-21 19:08 UTC
#### Expected behaviour
When resizing the viewport or window while in a css grid, the chart adjusts accordingly while expanding or contracting.

#### Actual behaviour
When resizing the viewport or window while in a CSS grid, the chart will expand to fill the space when a breakpoint is reached, but it will not shrink back down. 

#### Live demo with steps to reproduce
https://jsfiddle.net/kdavidenkovmware/hzj5vnwL/
- expand the width of the viewport: the chart will expand to fill responsively.
- reduce the width of the viewport: the chart will not reduce in size responsively.

#### Product version
highcharts v10.0.0 and v10.3.1
highcharts-react-official v3.1.0 
react v18
react-dom v18

#### Affected browser(s)
Chrome Version 105.0.5195.102 (Official Build) (x86_64) - in the jsfiddle
Firefox 103.0 (64-bit) - in jsfiddle and in our application

**Comment by bm64** [comment] 2022-11-22 15:33
Hello @kdavidenkovmware. I'm closing it as a duplicate of #9491. As a workaround you can set `position: absolute` for chart's container or its direct parent: https://jsfiddle.net/BlackLabel/s0vL98q7/

**Closed by bm64** 2022-11-22 15:33 UTC
