### ISSUE TITLE
8.2.0 Loading NavigationBindings

### ISSUE THREAD

**Issue by laventnc** [highcharts/highcharts#14204] opened 2020-09-09 21:23 UTC
I recently updated Highcharts from v7.2.1 and am now getting errors that indicate Highcharts.NavigationBindings is not being imported.  As of right now I am loading Highcharts as a CommonJS module, and bundling my modules with Webpack.
```
var Highcharts = require( 'highcharts/highstock' );
require( 'highcharts/highcharts-more' )( Highcharts );
require( 'highcharts/modules/annotations' )( Highcharts );
require( 'highcharts/modules/annotations-advanced' )( Highcharts );
...
```
It seems as though the annotations module was previously loading NavigationBindings, and this is no longer happening. I looked around in the library and couldn't find a way to load it without changing over to es-modules. Any help would be greatly appreciated.

Thanks

#### Product version
8.2.0

#### Affected browser(s)
all

**Comment by KacperMadej** [comment] 2020-09-10 12:40
Hi @laventnc 

Thank you for contacting us.

The `annotations` and `annotations-advanced` both have the `NavigationBindings` part.
You could compare the files you are loading and check if the versions are correct for the modules to avoid loading the files from different releases. Currently available code on our CDN and the code in the repository have the part in both modules.

- https://github.com/highcharts/highcharts/blob/master/js/masters/modules/annotations.src.js
- https://github.com/highcharts/highcharts/blob/master/js/masters/modules/annotations-advanced.src.js

Additionally, there is no point in loading  `annotations` if you are loading `annotations-advanced` because the advanced version contains all code from the standard one.

I am unable to recreate your problem - please add more info and a live demo for the issue.

**Comment by laventnc** [comment] 2020-09-10 18:04
sorry for the late reply, here's a minimal example: https://codesandbox.io/s/nice-payne-n2jlh?file=/src/index.js

**Comment by pawelfus** [comment] 2020-09-14 11:27
Hi @laventnc 

Since v8.1.0 `H.NavigationBindings` is no longer available - this is an internal object that changed it's place. It's available now here:
```js
(function (H) {
  H._modules['Extensions/Annotations/NavigationBindings.js'].prototype.utils.manageBenchmarks = {};
})(Highcharts);
```

**Comment by pawelfus** [comment] 2020-09-25 15:46
Closing as not a bug.

**Closed by pawelfus** 2020-09-25 15:46 UTC
Labels: Product: Highcharts Stock, Type: Not a bug
