### ISSUE TITLE
Annotations customization not working

### ISSUE THREAD

**Issue by amargautam** [highcharts/highcharts#10199] opened 2019-02-22 20:38 UTC
#### Expected behaviour
Annotation options should be able to customize the annotation outputs

E.g. 👇 doesn't work

```
annotations: [{
          fibonacci: {
            labelOptions:{
              style: {
                color: '#ff0000'
              }
            }
          }
        }]
```

#### Actual behaviour
Irrespective of what options are set, it takes the default values.

#### Live demo with steps to reproduce
[https://jsfiddle.net/amargautam/f2tamw41/4/](https://jsfiddle.net/amargautam/f2tamw41/4/)

Steps -
1. Click on the Fibonacci tool from stocktools
2. Draw Fibonacci on the candlesticks

#### Affected browser(s)

**Comment by pawelfus** [comment] 2019-02-25 14:30
It's a duplicate of #9938 

Just a word of explanation, this:
```
annotations: [{
          fibonacci: {
            labelOptions:{
              style: {
                color: '#ff0000'
              }
            }
          }
        }]
```
**Adds** new annotation to the chart, it has nothing to do with default options for GUI.

**Closed by pawelfus** 2019-02-25 14:30 UTC
