### ISSUE TITLE
rotate tooltip not display

### ISSUE THREAD

**Issue by emidev98** [highcharts/highcharts#10495] opened 2019-04-05 07:05 UTC
Dear support,

When the **line chart rotate -45deg** on hover, the tooltip is not displayed correctly. I have deduced that the hover event is not calculated correctly and that causes the tooltip not to show up in the right place.
But when I use the same configuration for **column chart**, tooltip behaviour is correct.

- [Line chart demo](https://jsfiddle.net/emiDev98/9vq0bhy6/4/)
- [Column chart](https://jsfiddle.net/emiDev98/obzqv70c/1/)

Someone know any workarround to rotate the chart and display the toolitp correctly?

Thanks

**Comment by pawelfus** [comment] 2019-04-05 08:48
Hi @emidev98 

Thanks for reporting the issue. Actually it's a duplicate of #3617.

To answer why `column` series works fine: in column series, we show tooltip according to direct `mouseover` event on the rect shape. In line/spline etc. series, we search for the closest point in dataset according to the mouse position. That searching algorithm does not support CSS rotations.

**Closed by pawelfus** 2019-04-05 08:48 UTC
