### ISSUE TITLE
Stock Tools: Draggable annotation dragged to the right edge

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#16370] opened 2021-09-20 13:53 UTC
#### Expected behaviour
Just a regular drag & drop

#### Actual behaviour
Dragging an annotation to the right edge (left probably too), places annotation in the initial (?) x-position. Probably related to the ordinal Axis. Steps (see gif):
- add an annotation (circle in this case)
- zoom in (e.g. 1M or 3M)
- try dragging annotation to the right edge
![circle-drag](https://user-images.githubusercontent.com/1453926/134014020-9da5e75e-fb71-4025-9ed1-b301a4728148.gif)

#### Live demo with steps to reproduce
https://www.highcharts.com/demo/stock/stock-tools-gui

#### Product version
Highcharts Stock v9.2.2

#### TO DO
Check if it's not a regression

**Comment by pawellysy** [comment] 2021-09-22 11:51
These are next reproduction steps: 

![drag](https://user-images.githubusercontent.com/1453926/134168170-f0cccd5c-9c3b-4e55-8b6e-b56e1a4479db.gif)

1. Create annotation (circle, rectangle, ellipse)
2. Drag the navigator, so that one of the points leaves the plot Area from the right side.
3. Drag the annotation, so that this point comes back to the plot area
4. Notice, that the point, that is coming back to the plotArea changes its place to the left edge of the plotArea.

_Originally posted by @pawelfus in https://github.com/highcharts/highcharts/pull/16207#pullrequestreview-759662199_

**Comment by karolkolodziej** [comment] 2021-10-06 11:56
The issue will be resolved by #16410 PR.

PS.
I was not able to reproduce that issue with ellipse either.

**Closed** 2021-10-06 13:07 UTC
Labels: Type: Bug, Product: Highcharts Stock, Status: Done
