### ISSUE TITLE
Zero value data label positioning inconsistent when specifying font size

### ISSUE THREAD

**Issue by liepa** [highcharts/highcharts#17523] opened 2022-07-20 09:02 UTC
#### Expected behaviour
All data labels should be positioned consistently.

#### Actual behaviour
When setting `plotOptions.series.dataLabels.style.fontSize`, then data label for zero value is positioned different than other values.
![inconsistent_data_label_positioning](https://user-images.githubusercontent.com/1221718/179942559-dae47d15-a87f-4c9b-bc3e-a9252b3096d6.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/8b2spya6/
Here you can see that zero value are way higher. 
But if you change "0" to "0.1" than both data labels are positioned correcly, also if you change fontSize to 16px, than it works on macOS:

#### Product version
Highcharts JS 10.2.0

#### Affected browser(s)
On windows:
- Chrome 103.0.5060.114
- Edge 103.0.1264.62

On macbook:
- Chrome 103.0.5060.53
- Safari 15.5 (17613.2.7.1.8)

**Comment by raf18seb** [comment] 2022-07-21 08:44
Hi @liepa,

By setting the `varticalAligh: 'top'` you moved the dataLabels down, below the points. As a result, the dataLabel for a bottom point went out of the plotarea so **Highcharts moved it top to fit it into the plotarea** `case 1.`. Then, you moved it top even more by setting `y: -24` - that's why the dataLabels is that high `(case 2.)`.

As a solution, depending on what exactly you want to achieve:
- you can remove your dataLabels placement options and trust Highcharts when it comes to placing them: https://jsfiddle.net/BlackLabel/qa7uvjcp/
- `case 2.` you can remove `y: -24` from the bottom dataLabel because it's already moved by `case 1.`: https://jsfiddle.net/BlackLabel/gfzLcu47/
- or you can disable `case 1.` (the best solution and I think this is what you're looking for) - stop Highcharts from moving the dataLabels when Highcharts thinks they are out of the plotarea (by disabling `dataLabels.crop` and setting `dataLabels.overflow: 'allow'`): https://jsfiddle.net/BlackLabel/7nLm48ze/

https://api.highcharts.com/highcharts/series.line.dataLabels.crop
https://api.highcharts.com/highcharts/series.line.dataLabels.overflow

This is the correct behavior so I'm closing the ticket as "not a bug" and resolved, but feel free to reopen if you have any further questions or concerns.

**Closed by raf18seb** 2022-07-21 08:44 UTC

**Comment by liepa** [comment] 2022-07-21 11:21
Thank you @raf18seb for your response.

The third option really is what I was looking for :) 

Have a great day.
