### ISSUE TITLE
Legends: getting overlapped with each other

### ISSUE THREAD

**Issue by Ajudiya13** [highcharts/highcharts#14036] opened 2020-08-12 14:13 UTC
#### Expected behaviour
Legends should take the width not greater than given `itemWIdth` prop.

#### Actual behaviour
When `labelFormatter` is given for legends and if `labelFormatterr` renders two parallel `span` then legend is taking width more than given `itemWidth` option. That's why the legends are getting overlapped with each other.

#### Live demo with steps to reproduce
[https://jsfiddle.net/ajudiya_13/fmgyv15w/6/](https://jsfiddle.net/ajudiya_13/fmgyv15w/6/)

#### Product version
Highcharts JS v8.0.0

#### Affected browser(s)
Google Chrome

**Comment by sebastianbochan** [comment] 2020-08-13 09:07
Hi @Ajudiya13,
Thank you for contacting. By default the HTML tags are converted to SVG elements. You can disable this functionality (when you use custom HTML) by the [useHTML](https://api.highcharts.com/highcharts/legend.useHTML) flag.

Demo:
- https://jsfiddle.net/BlackLabel/8mw2d0qj/

Im closing the issue as not a bug.

**Closed by sebastianbochan** 2020-08-13 09:07 UTC
