### ISSUE TITLE
Additional options for Xaxis and Yaxis are not applied in "getSVG" method

### ISSUE THREAD

**Issue by MajidSh854** [highcharts/highcharts#14382] opened 2020-10-20 10:59 UTC
#### Expected behaviour
See red in the "getSVG" output instead of green

#### Actual behaviour
See green in the "getSVG" output

#### Live demo with steps to reproduce
https://jsfiddle.net/MajidSh/qxza57pL/1/

#### Product version
highcharts 7.1.2

**Comment by MajidSh854** [comment] 2020-10-21 05:14
Thanks @PaulDalek

**Comment by mulanxia** [comment] 2021-06-09 16:11
Hmmm it looks like after https://github.com/highcharts/highcharts/pull/15250/ was merged, this workaround no longer works? Or am I missing something?

**Comment by KacperMadej** [comment] 2021-06-18 14:01
The problem is no longer visible making the workaround look like not working.
Closing as resolved.

(If the problem is still visible please add a live demo and the issue could be reopened.)

**Closed by KacperMadej** 2021-06-18 14:01 UTC
Labels: Type: Bug
