### ISSUE TITLE
Chart in flex box has height issue

### ISSUE THREAD

**Issue by frapontillo** [highcharts/highcharts#1758] opened 2013-04-24 08:17 UTC
When putting a chart inside a flexbox (latest spec, tested on Chrome stable, [demo here](http://jsfiddle.net/frapontillo/fk4Jr/)) the chart correctly resizes when its container is expanded in height, but **does not** when it is shrinked.

Might be related to #1752.

**Comment by jsturgis** [comment] 2015-09-16 20:04
The demo still shows this issue with the latest version of chrome Version 45.0.2454.93 (64-bit).

**Comment by antonpod** [comment] 2015-10-11 09:20
same problem when changing width and flex-direction: row
http://jsfiddle.net/fk4Jr/9/

**Comment by antonpod** [comment] 2015-10-11 09:25
Same problem when there's more than one element inside the flex container.
http://jsfiddle.net/fk4Jr/13/

**Comment by akisma** [comment] 2015-11-19 01:18
can also confirm issue with with flex rows. SO suggested hack of using $(window).resize() doesn't work, either.

**Comment by akisma** [comment] 2015-11-19 01:18
http://stackoverflow.com/questions/16182935/responsive-highcharts-not-sizing-correctly-until-window-resize

**Comment by highslide-software** [comment] 2015-11-24 08:40
@akisma Is your problem reproduceable with http://jsfiddle.net/fk4Jr/13/?

**Comment by akisma** [comment] 2015-11-24 20:25
@highslide-software it is not - that seems to be a separate issue. When I load that fiddle, the chart is the appropriate size for the containing box, is fully visible, and does not snap into view after resizing (since it's already visible).

**Comment by akisma** [comment] 2015-11-24 20:26
my particular issue is with three flex items within a flex row; the chart doesn't fit fully in the individual flex items, and with overflow:hidden set, is partially hidden. once the browser window is resized, it snap into place, but is then off-centered within the item. i'll post code and screenshot asap.

**Comment by dfmiller** [comment] 2016-01-25 21:42
Why was this bug closed?  This bug is very much alive.  Also has problem with width.  Two fiddles above show the problem. http://jsfiddle.net/frapontillo/fk4Jr/ http://jsfiddle.net/fk4Jr/13/

**Comment by jsturgis** [comment] 2016-01-30 07:09
This issue can be fixed by setting position relative on the parent and position absolute, height 100%, width 100% on the chart container:

dfmiller's first example working:
http://jsfiddle.net/adfcbok1/

**Comment by TorsteinHonsi** [comment] 2016-02-01 08:27
Thanks!

**Comment by inad9300** [comment] 2016-08-09 12:25
The trick proposed by @jsturgis is valid if you want to have a flex value of 1, if you want something more... _flex_ible, this won't help you. In fact, there is no point at all in using any flexbox properties in his example: getting rid of all of them has no effect.

Are there any plans for performing this "enhancement" soon?

**Comment by kyleicebreaker** [comment] 2016-08-09 23:08
I work around this by calling `setTimeout(window.dispatchEvent(new Event('resize')));` immediately after inserting into DOM

**Comment by inad9300** [comment] 2016-08-10 07:16
Not sure about what you really achieved by doing this, but it didn't work for me.

**Closed** 2018-11-05 13:46 UTC
Labels: Enhancement
