### ISSUE TITLE
Colours of the candles are reversed

### ISSUE THREAD

**Issue by Rahul-advait** [highcharts/highcharts#17708] opened 2022-09-07 12:04 UTC
#### Expected behaviour
When stocks are going high for example on this screenshot stocks opened at 145.76 and closed at 145.86 then colour of the candle should be green
#### Actual behaviour
When stock price closed at high price as compare to the price it opened it is displaying red.
When stock price closed at lower price as compare to the price it opened it is displaying green.

#### Live demo with steps to reproduce

![image](https://user-images.githubusercontent.com/95920001/188873055-33818436-3cc4-4215-837e-7dba0d038135.png)

**Comment by pawellysy** [comment] 2022-09-08 10:09
Hi @Rahul-advait, could you share the demo, where the issue is reproduced?
In the default behavior the colors are like this: https://jsfiddle.net/BlackLabel/ecbx59ky/

**Comment by pawellysy** [comment] 2023-01-28 11:57
Closing - No reproduction steps

**Closed by pawellysy** 2023-01-28 11:57 UTC
Labels: Status: Can't reproduce, Status: Pending reply
