### ISSUE TITLE
Map zoomTo break map navigation

### ISSUE THREAD

**Issue by mikimoresi** [highcharts/highcharts#20698] opened 2024-02-22 13:18 UTC
#### Expected behaviour
Using  `this.get('xx').zoomTo();` should not break the map navigation, I should be able to drag map with mouse and zoom with mousewheel.

#### Actual behaviour
It happens that you cannot move the map, you cannnot zoom in or zoom out even using navigation buttons.
In the following jsfiddle navigation totally breaks, in my project it happens an elastic behaviour while dragging causing the zoomed id to return in focus after drag end and zoom gets totally disabled.

#### Live demo with steps to reproduce
[https://jsfiddle.net/bhteqy9u/2/](https://jsfiddle.net/bhteqy9u/2/)

#### Product version
Highmaps JS v11.3.0 (2024-01-10)

#### Affected browser(s)
Google Chrome all latest versions

**Comment by hubertkozik** [comment] 2024-02-23 14:47
Hi @mikimoresi!

You are firing the `zoomTo` method during the chart render event. `zoomTo` redraws the charts and fires the chart `render` events -> which means, that you are creating an infinite loop, you can check the console, where you can find the Maximum call stack error.

If you use the `zoomTo` method correctly, everything works as expected and map navigation works. Please, check the demo below to see an example.
**Live demo:** https://jsfiddle.net/BlackLabel/6gnk1hr5/

Closing as not a bug.

**Closed by hubertkozik** 2024-02-23 14:47 UTC
Labels: Type: Not a bug
