### ISSUE TITLE
highcharts.js v4.2.2 'mouseIsDown' undefined 

### ISSUE THREAD

**Issue by LithMage** [highcharts/highcharts#5003] opened 2016-02-05 09:38 UTC
Hi,

as of 4.2.2 highcharts.js throws

> Uncaught TypeError: Cannot read property 'mouseIsDown' of undefined

if the chart is reloaded.

**Comment by sebastianbochan** [comment] 2016-02-05 09:56
Demo: http://jsfiddle.net/kz03adpt/

**Comment by pawelfus** [comment] 2016-02-05 10:53
Fixed on master: http://jsfiddle.net/kz03adpt/1/

**Closed by pawelfus** 2016-02-05 10:53 UTC

**Comment by TorsteinHonsi** [comment] 2016-02-05 11:13
Duplicate of #4998
