### ISSUE TITLE
When I rotate the chart 90 degrees, the click event doesn't work in some areas

### ISSUE THREAD

**Issue by zhangyu0218** [highcharts/highcharts#10612] opened 2019-04-25 06:03 UTC
When I rotate the chart 90 degrees, the click event doesn't work in some areas

**Comment by sebastianbochan** [comment] 2019-04-25 08:26
Hi @zhangyu0218,
Thank you for reporting about the problem. Could you elaborate your issue and let me know which "some areas" do not catch click event? A live demo on the jsfiddle will be really useful for us for the further debugging.

**Comment by zhangyu0218** [comment] 2019-04-26 02:05
@sebastianbochan OK Thank you for your reply to my question。
 When I rotate 90deg this DOM,Like the picture below。
You may try on the jsfiddle。
![image](https://user-images.githubusercontent.com/33249149/56778590-8a8cfa00-6809-11e9-8a1f-ae3351d95be8.png)
The click event cannot be triggered within the red line region。
![image](https://user-images.githubusercontent.com/33249149/56778668-0c7d2300-680a-11e9-82a5-6fe8064d0606.png)

**Comment by zhangyu0218** [comment] 2019-04-26 02:08
When I wrote mobile I wanted it to rotate 90 degrees.
So I really hope you can work this out.
Thanks.

**Comment by pawelfus** [comment] 2019-04-26 15:56
Hi @zhangyu0218 

Could you please share jsFiddle you are talking about? Thanks! :)

**Comment by zhangyu0218** [comment] 2019-04-27 03:39
Hi @pawelfus 
https://jsfiddle.net/zzytest/pazLhv91/1
When I rotate this dom, what happens is that some regions can't be clicked.
Because I had to rotate it 90 degrees to show it on the mobile side，
So Please help me with this problem Thanks.

**Comment by zhangyu0218** [comment] 2019-04-27 03:41
@pawelfus 
https://jsfiddle.net/zzytest/pazLhv91/4

**Comment by pawelfus** [comment] 2019-04-29 11:37
Thanks! It's a general issue with rotation of a chart via CSS `transform`. Mouse events are not properly handled. You can see that tooltip is not properly displayed either.

Closing as duplicate of #3617 (issue's name is a bit different, but under the hood it's the same problem - mouse events).

**Closed by pawelfus** 2019-04-29 11:37 UTC
Labels: Status: Pending reply
