### ISSUE TITLE
Highstock - Last column changes size and displays fake data with dataGrouping enabled

### ISSUE THREAD

**Issue by gizioo** [highcharts/highcharts#2957] opened 2014-04-24 11:01 UTC
Here is the fiddle:
http://jsfiddle.net/6E27G/
1. Try extending the selected range until the data groups into months.
2. Move the scrollbar around and watch the last column change size and value

**Comment by kamilkulig** [comment] 2017-08-10 13:22
+1

**Comment by shameersn** [comment] 2017-08-11 07:17
+1

**Comment by pratapgowda007** [comment] 2018-02-27 20:43
+1 i am also facing the same issue

**Comment by pawelfus** [comment] 2018-03-20 16:13
Related ticket: #5344 and PR: #8049

Working OP demo: http://jsfiddle.net/BlackLabel/6E27G/2/

Closing as duplicate of #5344

**Closed by pawelfus** 2018-03-20 16:13 UTC
Labels: Highstock
