### ISSUE TITLE
Negative values are not hidden on the graph if yAxis min is set to 0 and yAxis max is a large number

### ISSUE THREAD

**Issue by dianajibotean** [highcharts/highcharts#13938] opened 2020-07-21 13:15 UTC
#### Expected behaviour
Negative values should be hidden on the graph if the yAxis min is set to 0

#### Actual behaviour
A line is drawn at 0, if the negative value is close to the yAxis min and the max value is a large number.
Example :
- yAxis min  : 0
- yAxis max :  70000
- value which should be hidden : -1
If the negative value is lower (-1000 for example) then the value is hidden.

#### Live demo with steps to reproduce
https://jsfiddle.net/dianaj/psqz92hL/1/

#### Product version
latest version

#### Affected browser(s)
all

**Comment by pawelfus** [comment] 2020-07-22 09:19
Hi @dianajibotean 

Thanks for reporting the issue. This is kind of a rendering limitation. Value -1 in scale of 80 000 means a translation of ~0.0035px. When you have 1px line width for series, and you translate it by less than 1px then line will be partially visible.

You said -1000 is fine, but with your data, -300 is enough (so translation is 0.0035 * 300 -> 1.05 which is greater than 1px). But again, increasing line width will show the issue again: https://jsfiddle.net/BlackLabel/m756tdyq/

**Comment by TorsteinHonsi** [comment] 2020-10-01 08:30
I agree with Pawel's conclusion above, so marking this as not a bug.

**Closed by TorsteinHonsi** 2020-10-01 08:30 UTC
Labels: Type: Undecided
