### ISSUE TITLE
Touch events and tooltip followTouchMove on IE10 

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#2453] opened 2013-11-14 14:07 UTC
Example: http://jsfiddle.net/Dv2qv/2/show/

Try to click or hover bars when moving finger. Some gray tracker in wrong place is displayed, and it's not possible to have `followTouchMove` working properly.

**Comment by ajaybmishra25** [comment] 2016-02-29 12:19
Hello,

I working on highchart on ipad device.
While dragging the two fingers on ipad device, zoom functionality is working fine but it does not show the selection area on ipad device like it shows on desktop or laptop system.

Please help if anybody knows the solution.

**Comment by TorsteinHonsi** [comment] 2016-03-01 11:28
Hi, the touch zooming is working differently on the ipad. On touch devices the chart zooms real-time, so the selection area would be misleading.

PS: For general tech questions, please see www.highcharts.com/support.

**Comment by KacperMadej** [comment] 2019-08-13 12:00
Closing as the issue is based on outdated code that is no longer used. If you have a similar problem with current code, please open a new issue.

**Closed by KacperMadej** 2019-08-13 12:00 UTC
