### ISSUE TITLE
heatmap does not work with xAxis categories count large size

### ISSUE THREAD

**Issue by alklid** [highcharts/highcharts#8208] opened 2018-04-19 05:14 UTC
#### Expected behaviour
1. use heatmap
2. xAxis categories count about 500 over
3. yAxis categories count 3
4. expect to work well.

#### Actual behaviour
but, 
1. xAxis categories count <= 333 - work
2. xAxis categories count > 333 - not work

#### Live demo with steps to reproduce
1. xAxis categories count <= 333  : http://jsfiddle.net/3vn9u8n0/1/
2. xAxis categories count > 333 : http://jsfiddle.net/v2qupxk7/1/

#### Product version

Highcharts JS v6.1.0

**Comment by pawelfus** [comment] 2018-04-19 10:13
Hi @alklid 

Thank you for reporting this bug. This is caused by [`heatmap.turboThreshold`](https://api.highcharts.com/highcharts/plotOptions.heatmap.turboThreshold) - when disabled works fine: http://jsfiddle.net/BlackLabel/v2qupxk7/2/

Closing as duplicate of #3765

**Closed by pawelfus** 2018-04-19 10:13 UTC

**Comment by alklid** [comment] 2018-04-20 01:02
Hi @pawelfus 

I'm sorry, I had to look for similar cases in problem, but I don't.
This was a big problem for me, but it worked out well because your comment.

thank you so much.
