### ISSUE TITLE
Labels for the edges of a dependencywheel appear at the wrong place

### ISSUE THREAD

**Issue by baderj** [highcharts/highcharts#16007] opened 2021-07-07 13:01 UTC
#### Expected behaviour
The ``format`` option for ``dependencywheel`` should add edge-labels somewhere inside the corresponding edges of the diagram, as it does for the sankey diagram.

#### Actual behaviour
Labels are placed all the way to the left, although potentially at the right height:

![image](https://user-images.githubusercontent.com/5196024/124763074-de401580-df33-11eb-8be8-02006efc3a23.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/aLxhuqmy/11/

#### Product version
Highcharts JS v9.1.2 (2021-06-16)

#### Affected browser(s)
All of them.

**Comment by raf18seb** [comment] 2021-07-08 10:24
Looks like a duplicate of https://github.com/highcharts/highcharts/issues/10334

**Closed by raf18seb** 2021-07-08 10:24 UTC
