### ISSUE TITLE
Chart renders larger than its container (default sizing) depending on when the container was added to the page after v5.0.10

### ISSUE THREAD

**Issue by JllyGrnGiant** [highcharts/highcharts#6883] opened 2017-06-20 23:22 UTC
If you render the chart in a JQuery Element in memory, then add that element to the page, there's an issue with automatic chart sizing post v5.0.10.

#### Expected behaviour (v5.0.10)
http://jsfiddle.net/5dg1ojft/2/

#### Actual behaviour (v5.0.12 - current as of this writing)
http://jsfiddle.net/nws9oo9L/3/

Important to note, in the repro, if you resize the browser, the chart then sizes itself correctly for some reason.

**Comment by sebastianbochan** [comment] 2017-06-21 10:59
Duplicate of: https://github.com/highcharts/highcharts/issues/5783

**Closed by sebastianbochan** 2017-06-21 10:59 UTC
