### ISSUE TITLE
Using ES6 modules column type with series stacking seems to be broken.

### ISSUE THREAD

**Issue by K-Thompson** [highcharts/highcharts#17483] opened 2022-07-08 11:53 UTC
#### Expected behaviour

Column charts with **series stacking** seem to be broken when using the **CDN ES6 module** implementation.

#### Actual behaviour

All the values for Series 1 are not displayed.

#### Live demo with steps to reproduce

Not sure if I can import your ES6 modules into jsfiddle, but the problem is very easy to reproduce by making the following modifications to your column example found here [Installation with ES6 Modules](https://www.highcharts.com/docs/getting-started/installation-with-esm)

	<script type="module">
	// mychart.js
	import Chart from 'https://code.highcharts.com/es-modules/Core/Chart/Chart.js';
	import ColumnSeries from 'https://code.highcharts.com/es-modules/Series/Column/ColumnSeries.js';
	// Example to create a simple stacked column chart in a div#container:
	const myChart = new Chart('container', {
		plotOptions: {
			series: {
				stacking: 'normal'
			}
		},
		series: [{
				type: 'column',
				data: [1, 2, 3]
			},
			{
				type: 'column',
				data: [3, 2, 1]
			}
		]
	});
	</script>

No errors are shown in the console. 

For me, the chart only shows one of the Series 1 values - the third one.

Additionally, when I click on 'Series 1' in the legend, I see this error:

`Chart.js:535 Uncaught TypeError: chart.getStacks is not a function`

**Perhaps I need another import?**

#### Product version

Whatever the current version is on the CDN.

#### Affected browser(s)

Chrome v103.0.5060.66

**Comment by K-Thompson** [comment] 2022-07-08 13:25
I added one more import **before** `Chart`:

	`import StackItem from 'https://code.highcharts.com/es-modules/Extensions/Stacking.js';`

That resolved the problem.

**Comment by pawellysy** [comment] 2022-07-09 08:03
Hi @K-Thompson, I guess, that the issue was with insufficient imports :) Good to hear, that you managed to solve the issue on your own. Closing this issue, since this is not a bug.

**Closed by pawellysy** 2022-07-09 08:03 UTC
