### ISSUE TITLE
Tooltip throwing error on deleted points which are still visible in chart

### ISSUE THREAD

**Issue by monstersintokyo** [highcharts/highcharts#4695] opened 2015-10-28 13:45 UTC
Zoom into chart, add some new points and shift old ones, but do not redraw chart.
Depending on `tooltip.shared` option, different errors are thrown when you move the mouse over the chart.

Tooltip shared is:
* `true`: Uncaught TypeError: Cannot read property 'noSharedTooltip' of null
* `false`: Uncaught TypeError: Cannot read property 'tooltipOptions' of null

Fiddles
* http://jsfiddle.net/zctdoeLh/2/
* http://jsfiddle.net/et003zsy/1/

First case seems to be caused by the collection of all nearby points in the `runPointActions` function. Destroyed points are added, too:

```javascript
if (kdpointT) {
    kdpoints.push(kdpointT);
}
```

**Comment by pawelfus** [comment] 2015-10-30 16:00
*Internal note:* 
Remove **all** points from the current zoom to get errors.

Indeed, condition like this resolves the issue:

    if (kdpointT && kdpointT.options) {
        kdpoints.push(kdpointT);
    }

But can we assume that `options` are always available? Or it is better to add flag `isRemoving` in `point,destroy()` method and later check that method there? Or `point.destroy()` should remove corresponding point from kdTree (it may require rebuilding kdTree, but sounds unreasonable to do it twice - second one would be in the redraw).

**Comment by pawelfus** [comment] 2016-10-17 12:57
It looks like a duplicate of #5197 - it's fixed then.

**Closed by pawelfus** 2016-10-17 12:57 UTC
