### ISSUE TITLE
Panning on touch devices doesn't move the axis and data

### ISSUE THREAD

**Issue by fapaul** [highcharts/highcharts#5270] opened 2016-04-29 13:10 UTC
When panning on touch screens devices I expected to see a moving axis and data.

Actually I see a not moving static axis until touchEnd Event and white Space instead of data

http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/chart/pankey/

On touch and non-touch devices I use Chrome.

**Comment by TorsteinHonsi** [comment] 2016-04-29 13:54
Thanks for writing! The axis behaviour is by design. Some processing power is required to compute the axis layout and place tick marks, labels etc. So in order to get a smooth panning experience on touch devices we just translate the actual series data (line graph, columns etc.) in order to give the user feedback on the panning, but we we don't do the full translation until it is dropped. 

When you say "white space instead of data", what do you mean? You are supposed to see the graph itself and the markers moving. That is what I see in iPhone 6.

**Comment by mockingbird2** [comment] 2016-04-29 14:03
The touch device I use is big touch screen connected to a normal PC, so is it possbile to disable this translation? 

I hope the following image descibes the problem. This is what I get before releasing the touch. Don't mind the red bar.
![pasted image at 2016_04_29 04_00 pm](https://cloud.githubusercontent.com/assets/7405553/14918330/9886578e-0e23-11e6-8598-ef931be7ae6c.png)

**Comment by TorsteinHonsi** [comment] 2016-04-29 14:17
Oh, I see, it's the graph that is clipped outside the "current" zoomed area. For one single finger pan it should be possible to work around it by emulating the same behaviour as mouse-pan, but for two-finger pinch/zoom it is different altogether...

**Comment by mockingbird2** [comment] 2016-04-29 15:30
Ok, thanks for your fast reply. In my case it would only be necessary to translate single-finger pan as I don't need pinch and zoom moves.

Do you have any idea on how I can achieve this translation, maybe catching it in highcharts itself? (I also tried translating touch events on the object, but then there was no panning at all)

**Comment by axlerk** [comment] 2017-04-06 11:30
+1.

Sebastian Bochan form Helpdesk wrote I have the same trouble as you have.

I use Hightstock and my charts redraw only on touchEnd.
Example: http://jsfiddle.net/z4zmthkj/3/
Video: [2017-04-04 18-44-03.MOV.zip](https://github.com/highcharts/highcharts/files/902347/2017-04-04.18-44-03.MOV.zip)

But in Highcharts chart redraw "live" every second when I moving my finger:
Example: http://jsfiddle.net/z4zmthkj/2/

iPhone SE, Android 5. Highstock 5.0.9.

**Comment by axlerk** [comment] 2017-04-17 16:35
@sebastianbochan, can you write your opinion about this bug in highstock?

**Comment by sebastianbochan** [comment] 2017-04-18 11:08
Only what I can add is that I was able to replicate it on Android 6.0 and iOS.

**Comment by Kinka** [comment] 2017-11-06 01:11
Same problem here. Cannot find an option to do this, I wanna drag the graph on touch devices as it performs on the PC browsers. Checking out source code of highstock, finding out touch devices do not react to drag/dragStart events like PC do. So that navigator or scrollbar scrolls the chart smoothly on touch devices, dragging(or one-finger panning) should too.

**Comment by TorsteinHonsi** [comment] 2017-11-08 09:58
I experimented a little with this and it seems like we can quite easily replace the `pointer.pinch` call with `chart.pan`, with a few optimizations. This is something we could incorporate in the API. Right now there is a problem with panning outside the axis though:

http://jsfiddle.net/highcharts/j8kq6gxc/

**Comment by Kinka** [comment] 2017-11-09 00:49
@TorsteinHonsi Thank you so much. Your code enlightens so much, and works like a charm.

**Comment by ourabio** [comment] 2019-07-08 14:36
@TorsteinHonsi  I used your solution and it did make the scroll better but not great, sometimes it works just fine and sometimes it freezes or scroll not for long.
Check these videos:

- before adding your solution:

Navigator disabled: https://streamable.com/5hzic
Navigator enabled: https://streamable.com/xgtht

- After adding your solution:
https://streamable.com/peb33
Any suggestions? Thanks!

**Comment by pawelfus** [comment] 2019-07-09 13:37
Hi @ourabio 

Thanks for the details! Could you recreate issue in jsFiddle? We will take a look. Demo posted by @TorsteinHonsi works without problems you have in your vides.

**Comment by ourabio** [comment] 2019-07-15 14:53
Hey @pawelfus 

I am sorry for the late response! I couldn't recreate the issue in jsFiddle, I suppose the problem is related to touch devices webView. I did found what is causing the issue but I didn't get to a solution to fix it so I hope that you can help! when I scroll out of the chart points it works fine but when I scroll on the chart points it is not working so I am guessing an event related to the chart is blocking the scroll. Check the video:
https://streamable.com/m04yw
PS: in my configs plotOptions.column.enableMouseTracking = false to disable data click and display tooltip I am displaying it programatically. Thanks!

**Comment by pawelfus** [comment] 2019-07-16 09:39
Hi @ourabio 

Thank you for the details. Sorry, but nothing comes to my mind in your case. Maybe you have some errors in JS console that is causing this issue?

**Comment by ourabio** [comment] 2019-07-16 09:52
@pawelfus I checked JS console but no errors , Thanks for your help!

**Comment by ourabio** [comment] 2019-07-16 16:00
I logged the event object on the pinch wrap and the only difference is the target element so as I already said it is working when the target is background and not when it is point. Is there a way to make the points completely invisible to any click / touch event or to forward the target from point to background ? Thanks!

**Comment by pawelfus** [comment] 2019-07-17 08:18
Yes, you can @ourabio - try `.highcharts-point { pointer-events: none; }` in CSS.

**Comment by ourabio** [comment] 2019-07-17 08:32
@pawelfus works like charm. Thanks for your support!

**Comment by oloflandahl** [comment] 2020-03-25 10:20
The solution (https://github.com/highcharts/highcharts/issues/5270#issuecomment-342767958) works fine for one finger panning. How about two finger panning? I use one finger drag for tooltip.

**Comment by geesoon** [comment] 2020-10-20 09:34
> I experimented a little with this and it seems like we can quite easily replace the `pointer.pinch` call with `chart.pan`, with a few optimizations. This is something we could incorporate in the API. Right now there is a problem with panning outside the axis though:
> 
> http://jsfiddle.net/highcharts/j8kq6gxc/

Thank you for the awesome code! I am using it for highchart but now it can only pan x axis. I have set my pinchType to 'xy'. Any idea how to make it pan xy?

**Comment by PaulDalek** [comment] 2020-10-20 10:54
Hi @geesoon 

Thank you for contacting us. This is a support question, so please next time consider contacting us via one of the available support channels first (more info here: https://www.highcharts.com/blog/support/). As for the answer, you need to set `panning.type` to `'xy'`. Also, having set the `followTouchMove` to `false` while having zooming on will enable one-finger panning.

**Demo**
http://jsfiddle.net/BlackLabel/ec6qofau/

**Comment by geesoon** [comment] 2020-10-22 01:06
Thanks! @PaulDalek  I managed to make it pan xy but it is currently affecting the pan experience since the function is called every time a touch event occured that includes the process of panning. The overall panning become laggy. Is there any optimization that can be done? Else I will need to accept the axis and data not moving. =(

**Comment by PaulDalek** [comment] 2020-10-22 13:59
@geesoon

The issue is still open so at the moment there is no optimal solution for this other than the workaround provided some time ago.

**Comment by pawellysy** [comment] 2022-04-28 08:36
unstale

**Comment by runfaj** [comment] 2022-12-16 21:19
definitely unstale and still a problem (see video here: https://github.com/highcharts/highcharts/issues/14820)

**Comment by TorsteinHonsi** [comment] 2023-11-06 14:43
The OP issue in this post (axis and data not moving until dropping the touch), will be covered by #20077.

After that there seem to be various related issues and problems. At least some are fixed by https://api.highcharts.com/highcharts/chart.zooming.singleTouch. 

Also there seems to be a for single touch panning. This is already supported and achieved by setting `followTouchMove` to false, see https://api.highcharts.com/highcharts/chart.panning.

**Closed** 2024-02-06 08:17 UTC
Labels: Type: Undecided
