### ISSUE TITLE
yAxis does not honour min/floor, if max/ceiling is not assigned (when yAxis contains array of multiple axes)

### ISSUE THREAD

**Issue by terjesnarby** [highcharts/highcharts#17407] opened 2022-06-20 08:23 UTC
#### Expected behaviour
The y axis should start from the assigned min value (20 in my demo).

#### Actual behaviour
The y axis starts from an automatically calculated value based on the data (0 in my demo), and does not honour the assigned min option value.

#### Live demo with steps to reproduce
https://jsfiddle.net/83qvhz2u/11/

Uncomment max on line 30 and rerun to verify that the min/max values are honoured and the chart is drawn as expected.

#### Product version
 Highcharts JS v10.1.0 (2022-04-29)

#### Affected browser(s)
All

**Comment by pawellysy** [comment] 2022-06-20 09:27
Hello @terjesnarby, thanks for creating this issue!

This has nothing to do with `max` value being defined, or the array of axes in the config. Check out this example: https://jsfiddle.net/BlackLabel/hbvjyp8o/1/

This is connected to the fact, that the ticks are calculated in such a way that a tick interval is an even number, and so that the axis starts and ends on the tick. You can overwrite this default behavior by either defining option `axis.startOnTick: false` or by changing the positions of the ticks using one of the options available: https://jsfiddle.net/BlackLabel/hbvjyp8o/2/

You can read more here: https://support.highcharts.com/a/solutions/articles/44002324219

and if you still have some questions, please contact us via our support channels [which are listed here](https://www.highcharts.com/blog/support/)

Closing since this is not a bug

**Closed by pawellysy** 2022-06-20 09:27 UTC
