### ISSUE TITLE
Can't show only selected markers in spline chart

### ISSUE THREAD

**Issue by zykadelic** [highcharts/highcharts#2811] opened 2014-03-13 12:57 UTC
Disabling the markers for a spline chart with `enabled: false` still allows for markers on the hover state, but not for the selected state. It seems odd that this should be by design. I think the best configuration for this would be to let the hover and selected states inherit `enabled` directly from the `marker` object, with options to override it within each state individually.

See [this StackOverflow question](http://stackoverflow.com/questions/14407838/highcharts-display-marker-on-selected-point-only) for examples.

**Comment by oysteinmoseng** [comment] 2018-06-07 13:44
This is still relevant: http://jsfiddle.net/z9gfo5b1/

Workaround using radius (from SO): http://jsfiddle.net/n9jyg2ux/

**Comment by KacperMadej** [comment] 2019-03-04 11:09
Marking as a duplicate of #4367 
(that issue has more info and a workaround)

**Closed by KacperMadej** 2019-03-04 11:09 UTC
Labels: Bug
