### ISSUE TITLE
Category axis introduces new unexpected ticks on resize

### ISSUE THREAD

**Issue by achekh** [highcharts/highcharts#17365] opened 2022-06-07 15:16 UTC
#### Expected behaviour
xAxis with type: 'category' must not display tick labels other than the ones specified in the xAxis.categories array.

#### Actual behaviour
The xAxis displays "-1" label when the axis redraws with fewer items

#### Live demo with steps to reproduce
https://jsfiddle.net/zvua1tm6/3/
1. Click "London" legend item to hide second series
    Observe "-1" label in the chart
2. Click "London" legend item again
    Observe "-1" label remains

#### Product version
Highcharts 10.1.0

#### Affected browser(s)
At least Chrome 102.0.5005.63

**Comment by raf18seb** [comment] 2022-06-08 07:43
Hi @achekh, thanks for writing to us about this behavior.

The reason for this is `xAxis.minRange`: https://api.highcharts.com/highcharts/xAxis.minRange which by default is five times the distance between the 2 closest data points which in your chart is 5.

When you have "more than 5 points" or, being more precise, the distance between some points is greater than 5, the axis and ticks are displayed naturally. But when you hide the "London" series, you get the series with 5 points only which gives you 5 ticks with 2 additional padded ticks (-1 and 5).

A simple solution is to set a smaller `minRange`, e.g. 1: https://jsfiddle.net/BlackLabel/uoryqsLz/

Closing as not a bug and resolved.

**Closed by raf18seb** 2022-06-08 07:43 UTC
Labels: Type: Not a bug

**Comment by achekh** [comment] 2022-06-08 08:22
Well, I'm glad that there's a workaround for the issue. But I do believe that the fact that system introduces new labels for category axis is fundamentally wrong.

**Comment by raf18seb** [comment] 2022-06-08 08:27
@achekh this is how the categorized axis works. If you'd like to stay with a linear axis, you can use `xAxis.labels.formatter` to format your labels similar to the categorized axis, but without its functionality: https://jsfiddle.net/BlackLabel/r37sk21x/

**Comment by achekh** [comment] 2022-06-08 13:25
I can see that it works this way. And I think that it shouldn't work this way. That's why I think this is a bug. Because I don't understand why "-1" _should_ appear in my apples/oranges/pears categories, even though now I understand how it _does_ appear there.
