### ISSUE TITLE
3D Scatter Chart - Doesn't like lines

### ISSUE THREAD

**Issue by balupton** [highcharts/highcharts#5212] opened 2016-04-14 05:09 UTC
Lines do not position themselves correctly on the graph:

https://jsfiddle.net/balupton/1zcne6Ln/1/

**Comment by jon-a-nygaard** [comment] 2016-04-14 09:17
Hi @balupton, the reason why you are experiencing this issue is because Highcharts does not support 3D line charts. If you would like to combine scatter with lines, you will have to go with 2D as in this example: http://www.highcharts.com/demo/combo-regression

**Comment by KacperMadej** [comment] 2016-04-14 12:32
Scatter with positive lineWidth will work in 3D instead of line - https://jsfiddle.net/1zcne6Ln/2/

**Comment by KacperMadej** [comment] 2018-10-10 15:22
To better track how popular the enhancement idea is please use userVoice.
https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/14921250-support-more-3d-chart-types

Closing the issue for now, but it could get reopened when implementation of the feature will be started.

**Closed by KacperMadej** 2018-10-10 15:22 UTC
Labels: Enhancement, Not a bug
