### ISSUE TITLE
The label saying 'Russia' is being displayed over Belarus in highmaps

### ISSUE THREAD

**Issue by maxevilmind** [highcharts/highcharts#18243] opened 2023-01-04 14:44 UTC
#### Expected behaviour
The label that says 'Russia' should be displayed over the Russian territory.

#### Actual behaviour
Supposedly, due to the fact that Russia has it's part in Western Europe (the city of Kaliningrad) the label saying 'Russia' is misplaced and displayed over Belarusian territory

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/custom/world-highres3
<img width="490" alt="Screen Shot 2023-01-04 at 3 42 59 PM" src="https://user-images.githubusercontent.com/9032848/210580045-24877ced-a8f7-4755-892c-664a51304ab9.png">

#### Product version
Current

#### Affected browser(s)
All

**Comment by hubertkozik** [comment] 2023-01-09 08:39
Closing as duplicate of [#18004](https://github.com/highcharts/highcharts/issues/18004).

**Closed by hubertkozik** 2023-01-09 08:39 UTC
Labels: Type: Bug, Product: Highcharts Maps
