### ISSUE TITLE
Faulty rendering of area /step series in stockChart

### ISSUE THREAD

**Issue by wvhn** [highcharts/highcharts#17973] opened 2022-11-14 18:35 UTC
#### Expected behaviour
two datetime series are shown in one chart, both with type: area and step: left. One can assume values of 0 and 1 (boolean) and has only few data, the other can assume float values and has a large data set.  
Expected behaviour: the boolean series should only show values of 0 and 1, as represented in the data set.

#### Actual behaviour
In normal chart, rendering is Okay. In stockChart (with navigator) the boolean series (in blue color) is shown incorrectly with values of e.g 0.5
![grafik](https://user-images.githubusercontent.com/17801971/201738536-7f7904bc-66c0-4dde-857b-78faf4bf0c95.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/wvhn_/wqcyr2s0/34/
play with zoom level to see the effect changing

#### Product version
Highstock v10.3.1

#### Affected browser(s)
Firefox, Edge (both actual versions)

**Comment by pawellysy** [comment] 2022-11-16 06:46
Hi @wvhn, thanks for reaching out to us. 
This is expected behavior because of the [dataGrouping](https://api.highcharts.com/highstock/series.line.dataGrouping).
You can read more in the API. Closing since this is not a bug.

**Closed by pawellysy** 2022-11-16 06:46 UTC
Labels: Type: Not a bug

**Comment by wvhn** [comment] 2022-11-16 09:01
Hi @pawellysy,

thanks for the quick answer. 

I don’t think it can be expected behaviour that the plot shows data that are not available in the data set. Of course, grouping must have the effect that some points get eliminated in order to make the plot readable under the conditions of zoom level and screen resolution. But then the plot must stick to real data at both ends of the groups and not just interpolate. Maybe plots with a „step“ attribute need a different approach here.

Best regards 
Wolfram 

 

Von: pawellysy ***@***.***> 
Gesendet: Mittwoch, 16. November 2022 07:47
An: highcharts/highcharts ***@***.***>
Cc: wvhn ***@***.***>; Mention ***@***.***>
Betreff: Re: [highcharts/highcharts] Faulty rendering of area /step series in stockChart (Issue #17973)

 

Hi @wvhn <https://github.com/wvhn> , thanks for reaching out to us.
This is expected behavior because of the dataGrouping <https://api.highcharts.com/highstock/series.line.dataGrouping> .
You can read more in the API. Closing since this is not a bug.
