### ISSUE TITLE
Bubble chart shows extra category index numbers

### ISSUE THREAD

**Issue by alons1** [highcharts/highcharts#7793] opened 2018-02-04 15:14 UTC
Please see the following JSfiddle:
http://jsfiddle.net/sectioni/9kvkfprm/1/

The Y axis is showing -1 and 9 when the "z" value of the data is large.
If you change the "z" value to "1" on any of the 2 datapoints, the extra "categories" will dissappear

**Comment by sebastianbochan** [comment] 2018-02-05 10:39
Hi @alons1 
This case is duplicate of  https://github.com/highcharts/highcharts/issues/2762

**Workaround:**
- http://jsfiddle.net/BlackLabel/09mw2hgr/

**Closed by sebastianbochan** 2018-02-05 10:39 UTC
