### ISSUE TITLE
Highmaps: joinBy "region-wb" or "subregion" is not plotting the world map correctly

### ISSUE THREAD

**Issue by amruta30** [highcharts/highcharts#11083] opened 2019-06-18 12:47 UTC
#### Expected behaviour
On comparing the input data objects with those in world map geojson, it was observed that the region-wb/subregion values are matching with those in the world map geojson.
So it was expected that world map for given input data with joinBy region-wb/subregion should be rendered correctly.
Or is it that for this example, "region-wb" is not the valid joinBy?
What is the criteria for valid joinBy values for any particular map?

#### Actual behaviour
For world map, using the joinBy as "name" shows the map with applicable filled values correctly.
JS fiddle: https://jsfiddle.net/amrutaJgtp/a0Loyze8/
However, joinBy "region-wb" is showing only few locations on map resolved and the map appears broken. 
JS fiddle: https://jsfiddle.net/amrutaJgtp/a0Loyze8/2
I am not able to understand how joinBy "region-wb" will work.
I tried another joinBy "subregion", which also did not render the complete world map.
JS fiddle: https://jsfiddle.net/amrutaJgtp/a0Loyze8/1

#### Product version
Highmaps v7.1.2

#### Affected browser(s)
All

**Comment by pawelfus** [comment] 2019-06-19 09:19
Hi @amruta30 

I think the map is rendered kind of expected. `joinBy` expects one-to-one matching (ID to ID, where ID should be unique), while `region-wb` and `subregion` are duplicated in the datasets (both for the map and for the data). For example `East Asia ...` is defined multiple times in `data`, the same for `mapData`. 

@oysteinmoseng - did I miss something?

**Comment by oysteinmoseng** [comment] 2019-06-19 10:13
@pawelfus is correct, `joinBy` is designed for one-to-one mapping. If you want to set the value for each continent you would have to loop through the map data

**Comment by amruta30** [comment] 2019-06-20 05:34
Thanks for replying @pawelfus and @oysteinmoseng 

I have understood that joinBy works for one-to-one mapping. I also referred the Highmaps demo that shows examples with joinBy defined on name, hc-key, iso-a2,etc 
There are no examples on other location types like region-wb, subregion. ( Basically I was thinking that all properties from the map jsons can be used in "joinBy".) 

You suggested to loop through the map data, but I didn't get it. Could you please share an example of Highmap with joinBy as region-wb/subregion for input datasets containing multiple countries belonging to same region??

**Comment by oysteinmoseng** [comment] 2019-06-20 12:46
Sure, take a look at this: https://jsfiddle.net/smqgkLf6/1/

What we are doing in this example, is we are generating data for every country in the map (and joining this by `hc-key`), but we are generating the same value for all countries that share the same continent value. This means that all countries with the same continent will have the same value.

But note that a continent map is also avilable, which makes it easier: http://jsfiddle.net/gh/get/library/pure/highslide-software/highcharts.com/tree/master/samples/mapdata/custom/world-continents

I am closing this issue as not a bug, but let us know if you need further help. You can also contact us directly for support: https://www.highcharts.com/blog/support

**Closed by oysteinmoseng** 2019-06-20 12:46 UTC
Labels: Type: Not a bug
