### ISSUE TITLE
Modify multi line tool in StockTools

### ISSUE THREAD

**Issue by markzolotoy** [highcharts/highcharts#18297] opened 2023-01-13 13:11 UTC
We need to draw polygons on scatter and other charts to create selection areas. This feature is critical for our Predictive Analytics commercial software sold to the largest energy companies in the World.

**Comment by hubertkozik** [comment] 2023-01-13 15:04
Closing as duplicate of #18279.

**Closed by hubertkozik** 2023-01-13 15:04 UTC
Labels: Type: Feature Request
