### ISSUE TITLE
Need scroll bar for HighStock advanced indicators 

### ISSUE THREAD

**Issue by rkarlberg** [highcharts/highcharts#10403] opened 2019-03-24 17:52 UTC
#### Expected behaviour
On this stock demo, the advanced indicators dialog has many indicators to choose from, but you can only see a few listed - there needs to be a scrollbar here.

#### Actual behaviour
List gets cut off

#### Live demo with steps to reproduce
https://www.highcharts.com/stock/demo/stock-tools-gui

#### Product version
Highstock 7.0

#### Affected browser(s)
Chrome

**Comment by rkarlberg** [comment] 2019-03-24 20:12
I tried to create both a Codepen and Fiddle from this demo, but they show up blank, which is also strange...

**Comment by sebastianbochan** [comment] 2019-03-25 09:09
Hi @rkarlberg,
Thank you for reporting. The bug is known issue and has been already fixed in our master branch.

Im closing the issue as duplicate of https://github.com/highcharts/highcharts/issues/9988

**Closed by sebastianbochan** 2019-03-25 09:09 UTC

**Comment by rkarlberg** [comment] 2019-03-25 14:56
Ok, great to know, thanks!
