### ISSUE TITLE
ganntchart with lefttaxis as a table cannot delete the row

### ISSUE THREAD

**Issue by servetzeybek** [highcharts/highcharts#14144] opened 2020-08-31 08:55 UTC
#### Expected behaviour
I have a ganntchart with lefttaxis as a table. IT is based on your official example but i changed it a little. I just want to have milestones. https://jsfiddle.net/wvg6Lxu0/
And when i delete the milestone i want all row to be deleted. (we want to buy ganntchart license as well after fixing the issue)
(my license number 
Your LicenseID
- LicenseID: 100055278-1nkj5a)
[License Statement.pdf](https://github.com/highcharts/highcharts/files/5149346/License.Statement.pdf)

#### Actual behaviour
After deleting the point, the row is left there. IS this a bug ? 
how can i delete the whole row?
i use the following method to delete the row: 
this.chart.series[0].data[1].remove(true);
and the behaviour is as it is in following images
![step1](https://user-images.githubusercontent.com/27151622/91707465-83f25d80-eb88-11ea-98d9-d865f5fbd3e5.jpg)
![step2](https://user-images.githubusercontent.com/27151622/91707470-85238a80-eb88-11ea-8e85-2ec1b1353541.jpg)
![step3](https://user-images.githubusercontent.com/27151622/91707473-85bc2100-eb88-11ea-8277-bf6e8747d9f8.jpg)

#### Live demo with steps to reproduce
https://jsfiddle.net/wvg6Lxu0/

#### Product version
latest

**Comment by pawelfus** [comment] 2020-09-01 11:15
Hi @servetzeybek 

Thank you for reporting the issue. This is expected behaviour, removing a point with `y=1` does not remove space between points with `y=0` and `y=2`. If you want to achieve that, then you should change y-values for all points: https://jsfiddle.net/BlackLabel/go2qvt3f/ (series is destroyed and added back, because left side axis needs to be recreated).

**Comment by servetzeybek** [comment] 2020-09-10 08:41
Hi Pawel,

Thanks a lot for the solution.



Now i have 2 other problems with ganntchart.

1. As you see in the pictures, When i delete the last point (it doesnt have data in last 3 columns of the left table), the last 3 columns stay there with their titles and it looks ugly. I want to be able to remove last 3 columns when the points in the graph dont have data in those last 3 columns . (1st 2 columns have always data)

![1](https://user-images.githubusercontent.com/27151622/92702744-38933880-f35a-11ea-9922-2636fe0fc2cc.jpg)
![2](https://user-images.githubusercontent.com/27151622/92702750-39c46580-f35a-11ea-8be5-45a0647b6eb9.jpg)
![3](https://user-images.githubusercontent.com/27151622/92702756-3af59280-f35a-11ea-87a3-ba7005e66dae.jpg)
![4](https://user-images.githubusercontent.com/27151622/92702761-3c26bf80-f35a-11ea-805f-7221855aac86.jpg)


2. another point is that, how can click the rows of the left table?


3. finally, we have the license for highcharts but ganntcharts requires additional license i guess or?

**Comment by pawelfus** [comment] 2020-09-14 11:33
Hi @servetzeybek 

Thanks for reporting other issues. Could you send 1. and 2. to our Support team? See: https://www.highcharts.com/blog/support/

Regarding the third issue, please contact our Sales team: https://shop.highsoft.com/contact/ 

Closing this ticket as originally posted issue is not a bug and we keep GitHub issues only for bugs and feature requests.

**Closed by pawelfus** 2020-09-14 11:33 UTC
Labels: Product: Highcharts Gantt
