### ISSUE TITLE
stacked grouped column - legend defect?

### ISSUE THREAD

**Issue by Martin-Eckleben** [highcharts/highcharts#16617] opened 2021-11-09 09:11 UTC
#### Expected behaviour
Hovering over a legend item marks correct linked stacks and hides them when clicked.

#### Actual behaviour
Hovering over a legend  item marks pseudo-random stacks (even unlinked ones) and hides other ones when clicked.

#### Live demo with steps to reproduce
https://jsfiddle.net/bliss/qswyh7dp/2/

#### Product version
highcharts >= 9.2

#### Affected browser(s)
Tested in Firefox but seems Browser independent.

Can reproduce with adapted series data in highcharts example fiddle:
https://jsfiddle.net/bliss/pg3xyj7s/4/
(added a John on the female line)

Maybe or even probably I did link them wrong (name vs id etc. etc.)?
If so and you tell me I will help to improve the documentation in that direction.

**Comment by raf18seb** [comment] 2021-11-10 11:13
Hi @Martin-Eckleben, thanks for creating the ticket!

It's already reported, you can find a workaround in the ticket below.

Closing as a duplicate of https://github.com/highcharts/highcharts/issues/11810

**Closed by raf18seb** 2021-11-10 11:13 UTC
