### ISSUE TITLE
Y Axis of a scrollablePlotArea chart becomes part of the scroll when it is updated

### ISSUE THREAD

**Issue by darckoune** [highcharts/highcharts#12786] opened 2020-01-14 13:09 UTC
#### Expected behaviour

Calling Axis.setTitle or Axis.update when using scrollablePlotArea shouldn't make the axis become a part of the scrollable area

#### Actual behaviour

The updated axis becomes a part of the scrollable area

#### Live demo with steps to reproduce
https://jsfiddle.net/no54yckj/2/

#### Product version
v8.0.0

#### Affected browser(s)
At least Chrome & Firefox

Probably related to #11966

**Comment by pawelfus** [comment] 2020-01-15 10:28
Not related to #11966 - there was `chart.setTitle`, not `axis.setTitle`/`update`. This is duplicate of #8862.

**Closed by pawelfus** 2020-01-15 10:28 UTC
