### ISSUE TITLE
Series overflow/broken rendering - Angular

### ISSUE THREAD

**Issue by dominikbaranapp** [highcharts/highcharts#15048] opened 2021-02-03 15:39 UTC
#### Expected behaviour
Chart should render properly, series should be within chart area

#### Actual behaviour
Chart series overflow when yAxis extremes are updated or data zoomed in 

#### Live demo with steps to reproduce
https://codesandbox.io/s/snowy-shape-yh1ky

In order to break the chart you have to add a query params to the url - trigger navigate function.

Example.
Click "ChangeParams" -> zoom in -> series overflow
Click "ChangeParams" -> click "Update yAxis extremes" -> series overflow

IMPORTANT: When reproducing the error, ensure no query params exist in url to be sure navigate has been triggered

#### Product version
Highcharts 9.0.0

#### Affected browser(s)
Tested on Chrome 88.0.4324.104, but probably all browsers are affected

![Angular-Google-Chrome-2021-02-03-17-04-41](https://user-images.githubusercontent.com/56918506/106774198-2a63f280-6642-11eb-9cc7-04890c80ee3f.gif)

**Comment by KacperMadej** [comment] 2021-02-03 16:49
Hi @dominikbaranapp 

Thank you for reporting the problem.

The series' clip rect used in the demo has a wrong URL caused by history or [routing](https://github.com/highcharts/highcharts/issues/5244#issuecomment-450110633).
Closing as a duplicate of https://github.com/highcharts/highcharts/issues/5244

Please check the issue above for available workaround(s).
If you would like to check the fix linked in that issue, before it will be merged and later released as a part of the next version of Highcharts, then you could download the code from the branch (see loading specific commit -> https://code.highcharts.com/) and replace in your node_modules directory in the Highcharts package.

**Closed by KacperMadej** 2021-02-03 16:49 UTC

**Comment by dominikbaranapp** [comment] 2021-02-04 11:44
Do you know when will be the next release (including bufix for this case) ?

**Comment by KacperMadej** [comment] 2021-02-04 12:40
The next release is not yet secluded but could be expected within the next few weeks.
You could test the fix using the demo linked in the PR - https://github.com/highcharts/highcharts/pull/14874#issuecomment-773235929

**Comment by dominikbaranapp** [comment] 2021-02-04 13:09
@KacperMadej thanks for answering. Can you tell me how can I implement this fix in my project while waiting for an official patched release ? I've tried to import Highcharts like in the comment, but it doesn't work somehow.

**Comment by KacperMadej** [comment] 2021-02-04 13:54
Instead of installing the Highcharts Node package from NPM use the GitHub repo URL like shown in the comment stackblitz example. Please make sure that your project allows loading files like that. TS definitions are not provided for the GitHub URLs or the CDN (code.highcharts.com).

In case of any problems please describe what is wrong and if you could create a minimal example that we could debug then it would be great. You could contact technical support via e-mail if you don't want to make your code publicly available - support@highcharts.com
