### ISSUE TITLE
Wrong data points are highlighted by cursor after a chart reflow

### ISSUE THREAD

**Issue by dk1m** [highcharts/highcharts#14579] opened 2020-11-17 00:21 UTC
#### Expected behaviour
After the chart is manually reflowed, the cursor should highlight the correct data points and the correct tooltips should appear.

#### Actual behaviour
The data points at some offset to the cursor are highlighted instead of the the ones underneath the cursor.

#### Live demo with steps to reproduce
https://jsfiddle.net/pcmhsgkn/3/

#### Product version
8.2.2. This wasn't a problem in v6.1.4.

#### Affected browser(s)
Chrome 86.0.4240.198 and Safari 13.0.4. Does not happen in Firefox 82.0.2.

To repro the problem:
1. Load up the fiddle
2. Click the export button
3. Click "Full-window mode"
4. Without moving the cursor outside the chart, move the cursor around the data points. You should see that the wrong data points get highlighted.
5. Move cursor outside of chart and back in. Move the cursor around the data points and you'll see that the bug corrects itself.

The problem seems to be related to how much the chart is pushed away from the sides, whether by padding, margin, or positioning. In the fiddle, you'll see my comments about the left/right positioning inside the modal. When the values are small, the offset is barely noticeable, but if you increase it to 5em like I have it in the fiddle, it's much more obvious. 

Our company has an active Advantage membership. We were told by support to post the problem here for an expedited resolution. This bug is blocking us from upgrading our Highcharts version from 6.1.4 to 8.2.2. Any help on this would be greatly appreciated!

**Comment by PaulDalek** [comment] 2020-11-17 12:41
Hi @dk1m

Thank you for reporting this issue. This behavior occurs since `v7.2.1` (more precisely since the 8359afc2223b24508cb039bb7ad4ced7b2517923). That’s when the `getChartPosition` function was introduced. In a nutshell, it is responsible for returning the cached chart position if available (calling the `offset` function each time to generate a correct position is expensive). In your case the cached position is wrong (because of the `left` property is set to 5em and it is not taken under consideration, just as you noticed), therefore the position of the tooltip is wrong. As a workaround for now you can overwrite the `getChartPosition` function to calculate the position every time and not use the cached value.

**Workaround**
https://jsfiddle.net/BlackLabel/1qdy5s3f/

Bisected to 8359afc2223b24508cb039bb7ad4ced7b2517923

**Comment by PaulDalek** [comment] 2020-11-17 13:16
It looks like it was already reported some time ago.

Closing as a duplicate of the #12489.

**Closed** 2020-11-17 13:16 UTC
Labels: Type: Duplicate

**Comment by dk1m** [comment] 2020-11-17 16:57
Thanks for the detailed technical explanation, @PaulDalek! The workaround does indeed work for us. Thank you! I appreciate the quick response!
