### ISSUE TITLE
axis label issue when tickInterval is around minute

### ISSUE THREAD

**Issue by akash18m** [highcharts/highcharts#14797] opened 2020-12-13 19:52 UTC
Hi,
When we have tickInterval set to 60000 and we have applied a custom timezone, axis labels are not shown for few dataPoints.

<img width="873" alt="Screenshot 2020-12-14 at 1 12 51 AM" src="https://user-images.githubusercontent.com/28988972/102021939-94ca8600-3da9-11eb-88b3-22fa02507b5b.png">
As you can see axis labels are missing for starting points.

#### Expected behaviour
<img width="844" alt="Screenshot 2020-12-14 at 1 14 17 AM" src="https://user-images.githubusercontent.com/28988972/102021964-b75c9f00-3da9-11eb-9759-ba41f41d679e.png">
It should Show labels for all the points.

#### Live demo with steps to reproduce
http://jsfiddle.net/pvcdwr6a/3/ - This is where issue is happening.
http://jsfiddle.net/kho1edz6/ - This is where labels are working fine.

Both the charts have same timezone applied of Asia/Kolkata (GMT +5:30). Only difference in both the charts is first chart is rendered with min value of xAxis set to 1607883000000 (i.e. 23 Hours and 40 Mins). In second chart value of xAxis is set to 1607881800000 (i.e 23 Hours and 20 Mins).

My observation is with above config of timezone and tickInterval, when mix value for xAxis is past 30 mins for the hour, issue is seen.

**Comment by akash18m** [comment] 2020-12-13 19:57
I was trying to debug the issue and was able to conclude that issue is with **Time.prototype.getTimeTicks** Method. **tickPositions** calculated by this function are incorrect. It is starting from exactly 30 mins after the min value of xAxis for case where labels are missing.

**Comment by khlieng** [comment] 2020-12-14 07:33
Fixed in #14731, duplicate of #13961. And just a heads up, `useUTC` needs to be `true` for `timezone` or `timezoneOffset` to work (this probably wasn't visible to you due to being in the same timezone).

**Closed by khlieng** 2020-12-14 07:33 UTC
Labels: Type: Duplicate

**Comment by akash18m** [comment] 2020-12-14 10:35
Thanks @khlieng , Please let me know when the fix will be released?

**Comment by khlieng** [comment] 2020-12-14 11:00
It will be in the next release, most likely January.

**Comment by akash18m** [comment] 2020-12-14 11:09
Is there any possibility of an early patch/release? We can't delay the fix for this issue from our side as the issue is highly escalated. Let me know if there is anything you can do.

**Comment by khlieng** [comment] 2020-12-14 11:13
@TorsteinHonsi

**Comment by TorsteinHonsi** [comment] 2020-12-14 11:34
Hi @akash18m, you can use a drop-in fix while waiting for the release. Please see http://jsfiddle.net/highcharts/1b7woqam/ .

**Comment by akash18m** [comment] 2020-12-14 19:39
Thanks @TorsteinHonsi, it worked.
