### ISSUE TITLE
Styled mode gradient export issue

### ISSUE THREAD

**Issue by iherbak** [highcharts/highcharts#16411] opened 2021-09-28 07:58 UTC
#### Expected behaviour
When i set gradient in styled mode, for items eg. columns and export the chart the gradient colors are applied to the exported format.

#### Actual behaviour
The gradients are applied to the UI, but become black on export.

#### Live demo with steps to reproduce
https://jsfiddle.net/z4qntvLp/

#### Product version
Highcharts 9.2.2

**Comment by KacperMadej** [comment] 2021-09-30 15:37
Hi @iherbak 

Thank you for reporting the problem,

Workaround:
set the gradient in `defs` after adding attributes to AST
Demo:
https://jsfiddle.net/BlackLabel/gu08paqv/

_Internal note:_
Looks like the style calculated through `getComputedStyle` in `inlineStyles` in exporting module is only setting the reference and the colors from the CSS tab in the original demo are not included.

**Comment by iherbak** [comment] 2021-10-01 08:59
Hi!

Thanks for the feedback. 
It is good to know there is workaround at least, however this forces me to move the style partly into the code from the stylesheet.

Hopefully a fix will be coming.

**Comment by RostVY** [comment] 2022-03-15 09:50
Workaround does not help with the PDF export.

**Comment by pawellysy** [comment] 2022-03-18 12:20
Closing as a duplicate of  https://github.com/highcharts/node-export-server/issues/328

**Closed by pawellysy** 2022-03-18 12:20 UTC
Labels: Type: Bug
