### ISSUE TITLE
sankey nodes vertical alignment top

### ISSUE THREAD

**Issue by weber110** [highcharts/highcharts#10483] opened 2019-04-03 11:29 UTC
#### Expected behaviour
The same issue like #8653, i didn't found any configure on api document to support node vertical alignment, as i use react-highcharts, i've no idea to revise highcharts source to support this feature.
![image](https://user-images.githubusercontent.com/52900/55475307-29c53400-5646-11e9-9e1e-6ad5494ba69e.png)

#### Actual behaviour
![image](https://user-images.githubusercontent.com/52900/55475321-377ab980-5646-11e9-96b9-2c70bdacb41b.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/weber110/wpby8dux/1/

#### Product version
Highcharts 5.0
react-highcharts 16.0

**Comment by pawelfus** [comment] 2019-04-03 13:16
Hi @weber110 

Thanks for your input, but ticket #8653 is still open, so it's not implemented. No API to change that behaviour. 

I'm closing this ticket as duplicate of #8653.

**Closed by pawelfus** 2019-04-03 13:16 UTC
