### ISSUE TITLE
Selected point is deleted on hover in the line chart

### ISSUE THREAD

**Issue by balkarov** [highcharts/highcharts#8028] opened 2018-03-16 08:22 UTC
Line chart. Select a point with `chart.series[0].data[0].select(true, true);`. Hover on the points.

![desapire_dot](https://user-images.githubusercontent.com/6030335/37510527-70a8e942-290c-11e8-9d0c-e95068cb4ca4.gif)

#### Expected behaviour
Selected point leave selected

#### Actual behaviour
Selected point is deleted

#### Live demo with steps to reproduce
http://jsfiddle.net/gthr9nyx/

#### Product version
Highcharts version 6.0.7

#### Affected browser(s)
Chrome 65.0.3325.146

**Comment by sebastianbochan** [comment] 2018-03-16 09:25
Hi @balkarov 
Thank you for the reporting.

**Comment by pawelfus** [comment] 2018-03-16 11:34
*Internal note:*
Automated demo: http://jsfiddle.net/BlackLabel/gthr9nyx/5/ - it's interesting that in old versions, selecting point with disabled marker did not render marker at all. We can not select multiple points too: http://jsfiddle.net/BlackLabel/gthr9nyx/6/  - probably `stateMarkerGraphic` is used when selecting, but shouldn't like we did in v4: http://jsfiddle.net/BlackLabel/gthr9nyx/8/

**Comment by balkarov** [comment] 2018-05-10 08:42
Hello. Any news?

**Comment by pawelfus** [comment] 2018-05-10 10:50
Hi @balkarov 

The longer I debug the issue, the more I think it's not a bug. I mean, it is a bug that selected point shows up. this shouldn't be displayed at all, like in v4 versions. I tried to add manually marker: http://jsfiddle.net/BlackLabel/jbL4vhL1/1/ - it works, but it's hard to guess what can go wrong..

**Comment by balkarov** [comment] 2018-05-10 11:32
@pawelfus thank you but we need it for our project. Your workround does not suitable for us.
We want use native API for it.
And this is bug. Becuase in column chart chart does not replace selected column color when you hover it. But in chart line change.

**Comment by pawelfus** [comment] 2018-05-10 11:49
@balkarov - column series does not have markers so we can not compare these two series. There's no setting like `marker.enabled` for column. 

I suggest to keep markers enabled, but with a very small radius, for example 0.1px, see demo: http://jsfiddle.net/BlackLabel/gthr9nyx/12/

**Comment by balkarov** [comment] 2018-05-11 07:35
@pawelfus this is hack, but works. I hope you can fix it in highcharts :relaxed:

**Comment by KacperMadej** [comment] 2018-06-14 15:42
Duplicate of #2811

**Closed by KacperMadej** 2018-06-14 15:42 UTC
Labels: Bug
