### ISSUE TITLE
Heatmap w/ boost-canvas not centered on chart

### ISSUE THREAD

**Issue by arondaniel** [highcharts/highcharts#8873] opened 2018-09-01 20:00 UTC
#### Expected behavior
Heatmap canvas centered in chart area

#### Actual behavior
Heatmap canvas shifted left/up and clipped

#### Live demo with steps to reproduce
Your own heatmap demo shows this problem (at least for me it does...)
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/heatmap-canvas/

Remove the boost-canvas include and it draws fine.

#### Product version
Highcharts 6.x although, oddly, switching to latest highcharts 5 didn't seem to make any difference.

#### Affected browser(s)
Experience this on Safari 11.0.3 & Chrome 68.0.whatever

**Comment by arondaniel** [comment] 2018-09-03 11:37
Chrome Version 68.0.3440.106 (Official Build) (64-bit) on OS X 10.11.6

<img width="986" alt="screen shot 2018-09-03 at 7 34 37 am" src="https://user-images.githubusercontent.com/3535137/44984824-38caf300-af4c-11e8-911e-dac11d5aaabf.png">

**Comment by pawelfus** [comment] 2018-09-03 14:43
Thanks for the screenshot! 

Just tested on OS X 10.11.6 and 10.13.6, for both I have the same result - nothing is cut off. Could you check if it's not a problem with cache (e.g. test in incognito mode)? v6.1.2 was just released, maybe it's connected.

**Comment by arondaniel** [comment] 2018-09-03 16:32
Incognito is disabled on my system but I did enable developer tools and reload the page with "Empty Cache and Hard Reload" and still see the problem. I also still see the problem w/ Safari private window.

Anyway I think I found the problem:

<img width="501" alt="screen shot 2018-09-03 at 12 18 50 pm" src="https://user-images.githubusercontent.com/3535137/44996320-4c3e8400-af75-11e8-9edc-2c07e67d9621.png">

If I modify the image x and y attributes to the translate values (50 and 60) it draws in the correct place.

-Aron

**Comment by pawelfus** [comment] 2018-09-04 09:28
Thanks. This is strange. I was hoping for incognito mode, maybe it's caused by a plugin? It looks the same for me:

![screen shot 2018-09-04 at 11 27 17](https://user-images.githubusercontent.com/1453926/45022878-94bd7680-b035-11e8-8539-84cb8ef507d7.png)
And clip-paths:
![screen shot 2018-09-04 at 11 27 35](https://user-images.githubusercontent.com/1453926/45022868-9129ef80-b035-11e8-9dc5-144521ed11e3.png)


I'm out of ideas, @TorsteinHonsi ?

**Comment by pawelfus** [comment] 2018-09-04 14:45
It's not how the image should look like, take a look (offset applied already in the image): 

![screen shot 2018-09-04 at 16 38 58](https://user-images.githubusercontent.com/1453926/45038221-17a7f680-b061-11e8-92a1-d8c2adfb3331.png)

**Comment by TorsteinHonsi** [comment] 2018-09-05 06:39
No issue here... I have no idea too. And it's very strange that it appears in both Safari and Chrome.

**Comment by cvasseng** [comment] 2018-09-14 10:30
I'm also unable to reproduce both on chrome 67 and 69.0.3497.92, both on OSX 10.11.6.

**Comment by pawelfus** [comment] 2018-10-10 11:06
It was caused by disabled webgl in browser. Closing as duplicate of #9150

**Closed by pawelfus** 2018-10-10 11:06 UTC
Labels: Cant reproduce
