### ISSUE TITLE
In scatter plots, tooltips are not visible when tooltip.outside and tooltip.split are enabled

### ISSUE THREAD

**Issue by cchengt** [highcharts/highcharts#18593] opened 2023-02-28 15:39 UTC
#### Expected behaviour
Tooltips are shown when hovering over the chart points

#### Actual behaviour
Tooltips are not shown when hovering over the chart points

#### Live demo with steps to reproduce
https://jsfiddle.net/haejd45k/

#### Product version
10.3.3

#### Affected browser(s)
Edge

**Comment by bm64** [comment] 2023-02-28 19:03
Hello @cchengt. I'm closing this ticket as a duplicate of #17720. Feel free to leave your feedback in the original ticket.

**Closed by bm64** 2023-02-28 19:03 UTC
