### ISSUE TITLE
First and last columns not visible in boost mode with certain datasets

### ISSUE THREAD

**Issue by vitaliy-kretsul** [highcharts/highcharts#17814] opened 2022-10-03 09:27 UTC
#### Expected behaviour
All columns, that are visible in non-boosted mode, are visible in boost mode as well, no matter the data in dataset.

#### Actual behaviour
First and last columns are not visible in boosted mode with some specific datasets.

#### Live demo with steps to reproduce
https://jsfiddle.net/Cortez/empkuc1r/

#### Product version
Highstock v10.2.1

#### Affected browser(s)
Google Chrome v106.0.5249.61

**Comment by karolkolodziej** [comment] 2022-10-04 07:53
When you are planning to use the boost module, please remember to declare the data as an array of arrays.
Right now in the console, you have an[ error 12](https://assets.highcharts.com/errors/12/) which indicates that your data is not right for the boost.

Closing it as not a bug.

**Comment by vitaliy-kretsul** [comment] 2022-10-04 08:54
@karolkolodziej 
With data configured as array of arrays the problem is still there:
https://jsfiddle.net/Cortez/g0b9osn8/

**Comment by karolkolodziej** [comment] 2022-10-05 08:51
Hi! You are right the issue is still visible and it's data specific.

As a workaround, you can disable the `ordinal` on the xAxis- [demo](https://jsfiddle.net/BlackLabel/wgLzt1k0/).

**Comment by vitaliy-kretsul** [comment] 2022-10-05 09:02
@karolkolodziej 
Thank you very much for the workaround!

**Closed** 2022-10-07 06:54 UTC
Labels: Type: Bug, Product: Highcharts Stock, Flow: Review in progress
