### ISSUE TITLE
point.events.click does not trigger in bubble chart after clicking in the center of a bubble

### ISSUE THREAD

**Issue by stpoa** [highcharts/highcharts#6074] opened 2016-12-01 16:18 UTC
#### Expected behaviour
After clicking in a center of a bubble an alert box should pop up.
https://jsfiddle.net/t0hvzf6x/1/
(Works ok in 5.0.4)

#### Actual behaviour
After clicking in a center of a bubble an alert box does not pop up.
https://jsfiddle.net/t0hvzf6x/

#### Live demo with steps to reproduce
https://jsfiddle.net/t0hvzf6x/

**Comment by sebastianbochan** [comment] 2016-12-02 10:23
The issue is caused by halo.

You can disable it by the option plotOptions.series.states.hover.

Demo:
- https://jsfiddle.net/jtugju1s/

**Comment by pawelfus** [comment] 2016-12-02 11:01
Duplicate of #6054 

The same workaround works: https://jsfiddle.net/t0hvzf6x/2/

**Closed by pawelfus** 2016-12-02 11:01 UTC
