### ISSUE TITLE
route switching causes fillColor to fail

### ISSUE THREAD

**Issue by zChanges** [highcharts/highcharts#14580] opened 2020-11-17 07:07 UTC
route switching causes fillColor to fail
```ts
  ngOnInit() {
    const fillColor = {
      linearGradient: [0, 0, 0, 80],
      stops: [
        [
          0,
          Highcharts.color("red")
            .setOpacity(0.2)
            .get("rgba")
        ],
        [
          1,
          Highcharts.color("red")
            .setOpacity(0)
            .get("rgba")
        ]
      ]
    };
    const datas: any = [
      {
        name: "1",
        data: data.map(item => ({ x: +item[0] * 1000, y: +item[1] })),
        type: "areaspline",
        fillColor
      },
      {
        name: "2",
        data: data.map(item => ({ x: +item[0] * 1000, y: +item[1] })),
        type: "areaspline",
        fillColor
      }
    ];
    this.chartOptions.series = datas;
  }

  selectedIndexChange(index: number) {
    this.activeIndex = index;
    this.changeTabIndex(index);
  }

  changeTabIndex = (index: number) => {
    this.updateFlag = true;
    this.router.navigate(["."], {
      relativeTo: this.activatedRoute,
      queryParams: {
        ...this.activatedRoute.snapshot.queryParams,
        tabIndex: index
      }
    });
  };
```
path fill record the current route url ?
![image](https://user-images.githubusercontent.com/16421725/99357182-72e2fe00-28e6-11eb-9dda-95ce01cdcc7a.png)

#### Live demo with steps to reproduce

https://stackblitz.com/edit/angular-ivy-mbykwn?file=src/app/chart/chart.component.ts
#### Affected browser(s)
    "highcharts": "^8.2.2",
    "highcharts-angular": "^2.8.2",

**Comment by pawelfus** [comment] 2020-11-17 10:41
Hi @zChanges 

Thank you for reporting the issue. This is the same issue as #5244 - gradient fill/clip path reference is lost/incorrect after modifying URL.

**Workaround:**
https://stackblitz.com/edit/angular-ivy-bkppqz?file=src%2Fapp%2Fchart%2Fchart.component.ts

Closing as duplicate of #5244

**Closed by pawelfus** 2020-11-17 10:41 UTC
