### ISSUE TITLE
Highcharts reload problem after sorting the data ?

### ISSUE THREAD

**Issue by bhushangniit** [highcharts/highcharts#3336] opened 2014-08-11 15:11 UTC
.
We have taken the data from database through Ajax method and data display in graphical form(pie and column) and Table form .
We have many tables and graphs on a single page in a separated html div controls (not server side). we want to  sort order each and every div. 
It's working but highcharts are reload . 
If any fault in my code so table should be reload but only on graph reload . Please solve this thing.

**Comment by jon-a-nygaard** [comment] 2016-04-26 09:47
Closing this issue due to: We are not able to reproduce the issue, and it is pending reply. 
Should anyone have further information on this issue, please add a comment and reopen.

**Closed by jon-a-nygaard** 2016-04-26 09:47 UTC
Labels: Cant reproduce, Pending reply
