### ISSUE TITLE
Heatmap hover tooltip when y-axis labels have custom html (such as a link)

### ISSUE THREAD

**Issue by IrisGlazeRTI** [highcharts/highcharts#17028] opened 2022-02-23 18:32 UTC
#### Expected behaviour
The hover tooltip view should not be obstructed by the y-axis labels, even when the y-axis labels have custom HTML.
<img width="396" alt="heatmap_w_hover_no_overlay_axis" src="https://user-images.githubusercontent.com/69362224/155379936-9ad1a366-cda6-4c21-a5db-972b05cc4e60.png">

#### Actual behaviour
When the y-axis has custom HTML, such as a link to another page, the hover tooltip appears to be under it.
<img width="396" alt="heatmap_w_hover_overlay_axis" src="https://user-images.githubusercontent.com/69362224/155379895-36c5718f-a831-4b4f-99c5-def9a6c8e07f.png">

#### Live demo with steps to reproduce
https://jsfiddle.net/rx1g0nmf/
Notice that yAxis.labels.useHTML is set to true. When set to false, the problem does not persist.

#### Product version
Highcharts JS v9.0.1 (2021-02-15)

#### Affected browser(s)
Google Chrome, Version 98.0.4758.102 (Official Build) (x86_64)

**Comment by raf18seb** [comment] 2022-02-24 15:27
Hi @IrisGlazeRTI, thanks for creating a ticket!

Simplified demo: https://jsfiddle.net/BlackLabel/akqoheup/

It's not a bug. When setting `useHTML` on any chart's element, that element is rendered as HTML outside of SVG chart's container. It means that it's no longer an SVG and can be placed "below" or "above" the chart's container (by setting `zIndex`).
That's why the yAxis' labels are displayed above a tooltip. It's intended behavior.

As a solution, you can create a fully [HTML tooltip](https://api.highcharts.com/highcharts/tooltip.useHTML) - then both yAxis' labels and tooltip will be HTML elements not integrated with the main SVG chart, and you'll be able to set `zIndex` on them.
Demo: https://jsfiddle.net/BlackLabel/6p9nyhw2/

Closing as not a bug, but feel free to share any thoughts and concerns.

**Closed by raf18seb** 2022-02-24 15:27 UTC

**Comment by raf18seb** [comment] 2022-05-09 10:19
Also, a duplicate of https://github.com/highcharts/highcharts/issues/12236

Another solution is to set `tooltip.outside: true`
