### ISSUE TITLE
New property needed to alter Minor Grid Lines Count

### ISSUE THREAD

**Issue by SanjanaPriya** [highcharts/highcharts#13624] opened 2020-06-02 12:46 UTC
Hi,
      Using 'tickAmount' property, it is possible to mention the number of major gridlines needed. But there is no such property available to mention the number of minor gridlines needed. It would be convenient if there exists some handy property similar to 'tickAmount' for minor gridlines too.  

**Expected Behaviour**
      Need a new property minorTickAmount which is used to mention the number of minor gridlines needed in between major gridlines.

**Actual Behaviour:**
     No handy property to customise minor gridline count.

**Demo:**
    https://jsfiddle.net/BlackLabel/grLwh42j/ 
    This jsFiddle link is shared by one of the Highcharts Support members. Here the same behaviour is achieved with minorTickIntervalProperty. But it would be better if there is an independent property to handle minor gridlines count

**Product version**
8.1.0

**Comment by pawelfus** [comment] 2020-06-09 07:58
See discussion and plugin in #13336 - and let's continue discussion there. Thanks!

Closing as duplicate of #13336.

**Closed** 2020-09-14 05:04 UTC
Labels: Type: Duplicate, Type: Feature Request
