### ISSUE TITLE
Gantt chart y-axis grid columns do not respect the `width` property

### ISSUE THREAD

**Issue by jamesonhill** [highcharts/highcharts#20279] opened 2023-12-07 17:26 UTC
When using the multi-column left grid on gantt charts, I want to be able to configure the width of each column. The interface used for `yAxis.grid.columns` is `XAxisOptions`, which contains a `width` property. Additionally, the `XAxisOptions` interface has a `labels` interface of `XAxisLabelsOptions`. That interface contains a `style` property which lists `width` as an option. However, neither of these options seems to work when setting the width of each column. Is it a bug that these properties are seemingly being ignored? Or is there another way in which to customize the width of each grid column?

Steps to reproduce:
1. Go to [this codesandbox](https://codesandbox.io/p/sandbox/hidden-platform-sdqt4c?file=%2Fsrc%2FApp.tsx%3A38%2C20&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpvfxvah00063b6ik3eso40j%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpvfxvah00023b6i1d0eg22u%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpvfxvah00033b6iesud0aik%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpvfxvah00053b6ix62lznzz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B47.85968824522181%252C52.14031175477819%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpvfxvah00023b6i1d0eg22u%2522%253A%257B%2522id%2522%253A%2522clpvfxvah00023b6i1d0eg22u%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpvgxnen00023b6otornq69e%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A38%252C%2522startColumn%2522%253A20%252C%2522endLineNumber%2522%253A38%252C%2522endColumn%2522%253A20%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpvgxnen00023b6otornq69e%2522%257D%252C%2522clpvfxvah00053b6ix62lznzz%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpvfxvah00043b6i44vwglc5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clpvfxvah00053b6ix62lznzz%2522%252C%2522activeTabId%2522%253A%2522clpvfxvah00043b6i44vwglc5%2522%257D%252C%2522clpvfxvah00033b6iesud0aik%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clpvfxvah00033b6iesud0aik%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Afalse%252C%2522sidebarPanelSize%2522%253A0%257D)
2. Observe the width of each column
3. Refer to the `columns` variable within `opts` to see the set widths.

**Comment by ppotaczek** [comment] 2023-12-08 10:16
Closed as duplicate of https://github.com/highcharts/highcharts/issues/20277

**Closed by ppotaczek** 2023-12-08 10:16 UTC
