### ISSUE TITLE
Chart renders outside container on initial load

### ISSUE THREAD

**Issue by thecontstruct** [highcharts/highcharts#2547] opened 2013-12-19 23:31 UTC
This is in Chrome 31 on a MBP with Mavericks

When you create a chart which will result in the scroll bar appearing after the render, the chart will overflow it's containers width since it has based its width on the containers' width before the scrollbar appeared.

You can see if here http://jsfiddle.net/Q5EGX/30/ if you shrink your window till the bottom of the chart causes the scrollbar to appear. Hit run to refresh it and the chart will overflow on the right.

I've found a work around for now by deferring a triggered resize event right after the chart's creation with this:

_.defer(function() {
  return $(window).trigger('resize');
});

I'm sure there's a better way to do this from your side then me having to add this after every chart creation.

**Comment by kevin-coelho** [comment] 2018-02-02 22:57
^ I am still having this issue and I am setting the height on my chart's containing tag with css.

Before resize window:
![image](https://user-images.githubusercontent.com/13863650/35758496-347f572a-0829-11e8-8a2d-2e0bb700c7f2.png)

After resize window:
![image](https://user-images.githubusercontent.com/13863650/35758509-45476de0-0829-11e8-8d27-fa47c7658afb.png)

CSS:
`
#custom-chart {
    height: 600px;    
    border-style: dotted;
    border-width: 1px;
    border-color: green;
}

.highcharts-container {
    width:100% !important;
    height:100% !important;
}
`

**Comment by sebastianbochan** [comment] 2018-02-05 10:31
Hi @kevin-coelho 
Could you replicate your example as live demo in the jsfiddle? It will allow us to debug your specific case.

**Comment by HarishSha** [comment] 2019-01-23 14:20
Same thing happening with Bar and column graph. which can be replicated by reloading the page and during reloading switch the tab. Then come back to the original tab once you noticed that the page loaded completely. you will see the chart rendered outside.

I'm attaching a video to reproduce the same and temporary fix [**here**](https://drive.google.com/file/d/1CpGdldZ5Cr7FVTlHj4Gikfe6WU9Fe_50/view?usp=sharing)

[JsFiddle](http://jsfiddle.net/harishk3499/htmkmoh5/37/)

**Comment by KacperMadej** [comment] 2019-01-23 22:14
Based on provided demo the issue is no longer possible to be recreated using Highcharts v7.0.2
Closing as resolved

**Closed by KacperMadej** 2019-01-23 22:14 UTC
