### ISSUE TITLE
Not able to scroll using touchpad on charts

### ISSUE THREAD

**Issue by tsfahmed** [highcharts/highcharts#6297] opened 2017-01-25 11:01 UTC
I am not able to scroll the chart from touchpad scroll.

http://jsfiddle.net/f5mmhxnf/

**Comment by sebastianbochan** [comment] 2017-01-25 12:57
Duplicate of https://github.com/highcharts/highcharts/issues/6276#issuecomment-275097709

**Closed by sebastianbochan** 2017-01-25 12:57 UTC
