### ISSUE TITLE
Scatter - column not aligned

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#3002] opened 2014-05-02 11:51 UTC
See the example http://jsfiddle.net/4LjA9/2/ which introduce that scatter serie is not aligned to column.

**Comment by pawelfus** [comment] 2015-06-16 12:35
With `pointWidth: 21` looks properly: http://jsfiddle.net/3W43u/3/ - I guess it's connected to the crisp lines and correction +0.5px for Chrome (Tested with Chrome v.43.0)

**Comment by KacperMadej** [comment] 2018-08-10 10:33
Closing as a duplicate - in favor of the issue with more information about the problem.
Duplicate of #1843

**Closed by KacperMadej** 2018-08-10 10:33 UTC
