### ISSUE TITLE
unexpected yAxis category

### ISSUE THREAD

**Issue by hotohoto** [highcharts/highcharts#6063] opened 2016-12-01 08:27 UTC
#### Expected behaviour
There should not be a 22 at the top of yAxis

#### Actual behaviour
There is 22 at the top of yAxis.

#### Live demo with steps to reproduce
http://jsfiddle.net/hotohoto/jnatbb4t/

#### Affected browser(s)
I have tested it with chrome.

**Comment by sebastianbochan** [comment] 2016-12-01 09:33
Duplicate of #4385

**Closed by sebastianbochan** 2016-12-01 09:33 UTC
