### ISSUE TITLE
[Highstock] Multiple series with empty data freezed on zoom

### ISSUE THREAD

**Issue by temka1234** [highcharts/highcharts#16603] opened 2021-11-05 20:43 UTC
#### Live demo with steps to reproduce
Browser freezed if zoomed on empty place too close (multiple times)
https://jsfiddle.net/temka1234/dcnpjs3x/1/

#### Product version
Highstock JS v9.3.1

**Comment by KacperMadej** [comment] 2021-11-08 13:14
Hi @temka1234 

Thank you for reporting the problem.

I am able to recreate the problem only if the navigator handles overlap each other over the time range with no data points.

As a workaround, [minRange](https://api.highcharts.com/highstock/xAxis.minRange) could be set.
Minimal demo with the workaround applied: https://jsfiddle.net/BlackLabel/wk5r4v0e/1/

**Comment by pawelfus** [comment] 2021-11-09 15:19
It's a regression. There was no frozen chart in v9.1, it is broken since v9.2.0

Bisected to commit 2f23d6afab (because it freezes the bisect tool, I might be wrong)

**Comment by kamil-musialowski** [comment] 2023-05-24 08:35
I have tried to reproduce the issue, but is seems to work completely fine in latest Highstock version (11.0.1).
Demo: https://jsfiddle.net/BlackLabel/03efkbLh/

Looks like it got fixed with the 10.1.0 update.

@pawelfus Before I close this issue as fixed, could you please confirm that it works fine on your side?

**Comment by pawelfus** [comment] 2023-05-24 13:41
Confirmed @kamil-musialowski, closing the issue. Thanks!

**Closed by pawelfus** 2023-05-24 13:41 UTC
Labels: Type: Bug, Product: Highcharts Stock, Type: Regression, Status: Has workaround
