### ISSUE TITLE
Data grouping by buttons not woking when you update the chart

### ISSUE THREAD

**Issue by mosijava** [highcharts/highcharts#14068] opened 2020-08-18 06:24 UTC
#### Expected behavior
there is a sample in Highstock documentation which implement data grouping via rangeSelector buttons.
[link to this sample](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/rangeselector/datagrouping/)

#### Actual behavior
for some reason I have to use `update()` function after every time I get new data from server. 
as you can see [in this fiddle](https://jsfiddle.net/BlackLabel/b5p1ymxg/)  the chart doesn't update.

 just an extra, probably impractical fact: if you click a couple of times on -for example- `week` button it gets to work.

**Comment by pawelfus** [comment] 2020-08-18 08:33
Thanks for reporting the issue @mosijava. It's already fixed on our master branch: https://jsfiddle.net/BlackLabel/b5p1ymxg/1/ and will be part of the next release.

Closing as duplicate of #13788

**Closed by pawelfus** 2020-08-18 08:34 UTC
