### ISSUE TITLE
Filenames are not used when exporting to image

### ISSUE THREAD

**Issue by reeses1** [highcharts/highcharts#20370] opened 2024-01-03 21:01 UTC
#### Expected behaviour
When exporting to an image when I provide a filename I expect that filename to be present.

#### Actual behaviour
Exports do not respect provided filenames.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/1qyL0sej/
Download a png and observe it disregards the provided filename. This is unexpected. 

#### Product version
11.2.0, it appears prior versions are doing exactly the same thing for 11 in general it appears. 

#### Affected browser(s)
N / A, I'm using Edge and Chrome for what its worth.

**Comment by karolkolodziej** [comment] 2024-01-05 08:30
Hi @reeses1!

Thank you for reporting the issue! 

_Internal note:_
Looks like the filename is correct till posting the options on the export server.
![image](https://github.com/highcharts/highcharts/assets/57004120/7103240a-cb1e-4827-8d4f-a5d2247de102)
When using offline exporting, everything works as expected- [demo](https://jsfiddle.net/BlackLabel/ehLqr83s/).
@PaulDalek Could you please confirm that the issue is on the export server end?

**Comment by vishal-Sharma-netomi** [comment] 2024-01-07 13:16
Hi Team 
I am also facing same issue. Any update on this ? How to overcome with this issue.
Giving filename did not consider it  . it is giving by default name **chart** after downloading the any type of file.
@karolkolodziej @PaulDalek 
**Version**
    "vue-highcharts": "0.0.10",
      "highcharts": "^10.3.2",

**Comment by PaulDalek** [comment] 2024-01-08 10:37
Hi @reeses1 and @vishal-Sharma-netomi

I can confirm that this is a minor issue in the export server side that is ignoring the provided filename. We will take care of this and it should be fixed soon.

**Comment by vishal-Sharma-netomi** [comment] 2024-01-15 06:41
Hi @PaulDalek @jakubSzuminski  In which version I can get this fixed ?

**Comment by jakubSzuminski** [comment] 2024-01-16 09:38
@vishal-Sharma-netomi the _exporting_ module sends a request to our _Highcharts Export Server_, where the chart is being exported and returned in an HTTP response.

This issue is related to the Export Server we currently have deployed on _export.highcharts.com_. 

The good news is that I've already created a pull request fixing this problem: https://github.com/highcharts/node-export-server/pull/462 and this will be a part of our next deployment.

**Comment by jakubSzuminski** [comment] 2024-01-16 10:14
There is nothing wrong with your code @vishal-Sharma-netomi :)

We've redeployed our server and the _filename_ option should work as expected now. Please check it out and let me know.

Also, please keep in mind that even though this has been fixed, we're still encountering minor issues related to exporting, which we're trying to fix as soon as possible. Do not hesitate to ask on our [support channels](https://www.highcharts.com/blog/support/) in case you have any questions.

---
Closing as completed via https://github.com/highcharts/node-export-server/pull/462

**Closed by jakubSzuminski** 2024-01-16 10:14 UTC
Labels: Type: Bug, Product: Highcharts
