### ISSUE TITLE
Data is not shown when scrollbar is added

### ISSUE THREAD

**Issue by sajeetharan** [highcharts/highcharts#7688] opened 2018-01-17 19:31 UTC
#### Expected behaviour
Data should be shown on the charts when scrollbar is moved

#### Actual behaviour
It does not show the data below the scroll bar

#### Live demo with steps to reproduce
https://jsfiddle.net/sajeetharan/7boap47r/

#### Product version
v6.0.4 

#### Affected browser(s)

Chrome

**Comment by sebastianbochan** [comment] 2018-01-18 09:09
Hi @sajeetharan,
Thank you for the reporting. It looks like a bug.

@pawelfus

**Comment by pawelfus** [comment] 2018-01-18 10:40
It's another example for `category` type xAxis bug. Setting `cropThreshold` for series resolves the issue: https://jsfiddle.net/BlackLabel/7boap47r/1/

Closing as duplicate of #6926 and #5857

**Closed by pawelfus** 2018-01-18 10:40 UTC
Labels: Bug
