### ISSUE TITLE
Bar should start plotting from given base value tick and not from min value

### ISSUE THREAD

**Issue by PurvaK17** [highcharts/highcharts#18829] opened 2023-04-14 10:40 UTC
#### Expected behaviour
Bar should start plotting from given tick and not from min value
![waterfall chart with base value](https://user-images.githubusercontent.com/101875334/232021891-85b019a7-8d97-4265-87ad-6da8d1811dbe.png)
As per above image, min value is 1.0 but bars start plotting from base value i.e. 2.059

#### Actual behaviour
Bars are started from min value
![image](https://user-images.githubusercontent.com/101875334/232022043-d92864fb-2dd1-4814-a368-a5b53fd506d9.png)
Bar started plotting from min value i.e. 100K

#### Product version
latest version - 10.3.3

#### Affected browser(s)
Chrome, firefix

**Comment by pawellysy** [comment] 2023-04-15 08:45
Duplicate of #18828

**Closed by pawellysy** 2023-04-15 08:45 UTC
