### ISSUE TITLE
Chart selection event does not work if another chart is destroyed on page

### ISSUE THREAD

**Issue by anajavi** [highcharts/highcharts#15884] opened 2021-06-10 17:32 UTC
#### Expected behaviour
Unrelated chart.destroy() should not alter behavior of chart selection event.

#### Actual behaviour
destroying unrelated chart prevents chart selection event from firing.

#### Live demo with steps to reproduce
https://jsfiddle.net/1Lxp9y30/

Selection event does not fire on chart2 when selecting with mouse. When ```chart1.destroy()``` is removed from code, chart2 selection fires normally.

#### Product version
Highcharts 9.1.1

#### Affected browser(s)
Chrome 91

**Comment by khlieng** [comment] 2021-06-11 06:33
Fixed by #15850, duplicate of #15845.

**Closed by khlieng** 2021-06-11 06:33 UTC
Labels: Type: Duplicate
