### ISSUE TITLE
Synchronized charts not syncing if they are not aligned in the x or y axis

### ISSUE THREAD

**Issue by jordigagomerino** [highcharts/highcharts#18302] opened 2023-01-16 08:19 UTC
#### Expected behaviour
When I want to syncronice charts I want the sync independently of the charts layout or chat position. So for example I  want a layout with 3 charts two on top and one more wide at the bottom and with this case is not worknig.
This is the official doc example: https://www.highcharts.com/demo/synchronized-charts/brand-light

#### Actual behaviour
Actually if you move a chart out of the same x/y position than other chart it doesn't sync well. For example with the example above it will sync the first chart and half of the bottom chart or the second chart and the other half of the bottom chart.

#### Live demo with steps to reproduce
[
](https://www.highcharts.com/demo/synchronized-charts/brand-light)
1. Go to the official demo
2. Move one chart to be not aligned with other charts for example with this CSS class 
.chart:nth-child(1) {
  margin-left: 100vh;
}

3. The aligned chart will sync but the other one will not except if you put the cursor in some positon that have all de Y axis aligned
#### Product version

Above version 10
#### Affected browser(s)
All, but I'm using firefox

**Comment by pawellysy** [comment] 2023-01-17 09:26
Hello @jordigagomerino, thanks for reaching out to us!
The demo, which you can see on our docs page is a PoC, that can be achieved, and is not guaranteed to work for every example. When you want to adjust the chart to your needs and implement the synchronization for your use case, please reach out to us via [our available support channels](https://www.highcharts.com/blog/support/), where our support engineers will help you to suit the charts to your needs. Thanks!
Closing, because it is not a bug.

**Closed by pawellysy** 2023-01-17 09:26 UTC
