### ISSUE TITLE
Drop down menu partly visible

### ISSUE THREAD

**Issue by gizmocuz** [highcharts/highcharts#8860] opened 2018-08-30 05:35 UTC
#### Expected behaviour
Menu overlaps chart/page

#### Actual behaviour
Menu gets chopped at the bottom of the chart

#### Live demo with steps to reproduce
https://jsfiddle.net/0zbs765u/

If you make the chart small (in height) the drop down menu (to export the chart as PNG for example) gets chopped at the bottom of the chart.
This is specially noticeably on mobile devices as all charts seem to have less height here, or the font is larger.
Would be great if the Z-Order of the menu could be higher so it floats above the chart

#### Product version
6.1.1

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment] 2018-08-30 06:26
Hi @gizmocuz,
Thank you for reporting. The issue is duplicate of https://github.com/highcharts/highcharts/issues/7671

**Closed by sebastianbochan** 2018-08-30 06:26 UTC
