### ISSUE TITLE
Annotation with measure type "y" does not work as expected

### ISSUE THREAD

**Issue by felipejacobsexternal** [highcharts/highcharts#16132] opened 2021-08-03 08:29 UTC
Hi there!

#### Expected behaviour
I'm expected the below behaviour as shown in the documentation
https://jsfiddle.net/Lindus93/jxm17dnz/
![image](https://user-images.githubusercontent.com/62137150/127981895-07a6934d-6aa7-476e-ad00-b463a31b0d62.png)

and if you drag and move over the chart, the measure working fine.

#### Actual behaviour
But for my configuration, I have some weird behaviours: the legend for the Y measure seems to be out of the chart bounding and needs to move the navigator to the left:
![image](https://user-images.githubusercontent.com/62137150/127982710-4fbb4b7d-f529-4283-b362-35102d9af9d9.png)

when I move a little to the left the navigation:
![image](https://user-images.githubusercontent.com/62137150/127982758-1ea89f50-0695-477c-a9c3-ee339ec6ba46.png)

And also a weird behaviour when I'm doing a drag&move event over the measure tools: the box for the measure is moving from right to left instead of top to bottom or bottom to top.
#### Live demo with steps to reproduce
https://jsfiddle.net/mu3k2wjv/61/

#### Product version
Highcharts/ Highstock 9.1.2

#### Affected browser(s)
Chrome

Thanks in advance!

**Comment by khlieng** [comment] 2021-08-03 10:39
@karolkolodziej the measure in this one gets flattened when ran on #15970: https://jsfiddle.net/dx7b20qv/

**Comment by felipejacobsexternal** [comment] 2021-08-09 07:34
Sorry to insist, but I don't know why this problem has been closed, but the problem is still there.
https://jsfiddle.net/mu3k2wjv/61/
Thanks in advance!

**Comment by raf18seb** [comment] 2021-08-09 08:16
This issue is already fixed and waiting for merging to master and will be available in the next release. I am reopening and linking PR - the issue will be closed as soon as the PR is merged.

**Comment by felipejacobsexternal** [comment] 2021-08-11 12:17
Great @raf18seb! thanks so much for your response.
Regards!

**Closed** 2021-08-13 09:04 UTC
Labels: Type: Duplicate

**Comment by khlieng** [comment] 2021-08-23 07:45
This one doesnt look fixed, am I missing something? 🤔

**Comment by raf18seb** [comment] 2021-08-23 15:13
@khlieng it's been fixed since `9.2.0`. Can you double check? If some issue exists, please share a GIF or ad the exact steps to reproduce

**Comment by khlieng** [comment] 2021-08-24 07:49
Hmm, yes, must have been a cache thing.
