### ISSUE TITLE
Sankey: do not apply minLinkWidth on the weight 0 link?

### ISSUE THREAD

**Issue by nodew** [highcharts/highcharts#12474] opened 2019-11-22 06:13 UTC
#### Expected behavior
I want to hide the link of Sankey which's weight is 0 and at the same time, set the min link width of other small numbers.

#### Actual behaviour
the 0 weight link is applied to the min link width too.

**Comment by pawelfus** [comment] 2019-11-22 10:28
Hi @nodew 

Thanks for reporting this issue. You simply need to filter out links that you don't want to render.

**Comment by nodew** [comment] 2019-11-22 10:33
Yes, it is. The feature I want is level size, currently, I use 0 weight data to create invisible layers.

**Comment by pawelfus** [comment] 2019-11-22 11:05
I'm not sure what you exactly need to achieve, but did you contact our [support](https://www.highcharts.com/blog/support/)? Perhaps what you need is already possible via other options?

Closing this ticket as not a bug.

**Closed by pawelfus** 2019-11-22 11:05 UTC
Labels: Type: Not a bug
