### ISSUE TITLE
Data table is visible under chart even if it is not configured in options (accessibility)

### ISSUE THREAD

**Issue by urvesh86** [highcharts/highcharts#13455] opened 2020-05-07 06:55 UTC
Hi, 

I am using exporting module in my chart. I have not configured `showTable` property as I do not want to show table in chart area. 

As per API documentation of highchart (https://api.highcharts.com/highcharts/exporting.showTable) default value of `showTable` configuration is `false`.

#### Expected behaviour
Table would not be seen under chart while read using accessibility if `showTable `property is not set.

#### Actual behaviour
Chart in my tool is behaving fine on normal page load. But when I read the chart using screen reader tool(NVDA accessibility), it requests for a command from user to show table. When user press enter on request of that command, table is automatically visible under chart area.

#### Product version
Highstock 8.0.4

#### Affected browser(s)
All browsers / all devices (only while read through accessibility).

**Comment by pawelfus** [comment] 2020-05-07 07:58
Thanks for reporting the issue @urvesh86 

Could you check this @oysteinmoseng ?

**Comment by oysteinmoseng** [comment] 2020-05-07 09:08
@urvesh86 This is intended behavior, as `showTable` only controls the initial visibility of the table. You can remove the table shortcut for screen reader users with the [beforeChartFormat](https://api.highcharts.com/highcharts/accessibility.screenReaderSection.beforeChartFormat) option. Example: https://jsfiddle.net/oysteinmoseng/r56bgxma/

Closing this as not a bug, but feel free to comment if you have further issues or questions.

**Closed by oysteinmoseng** 2020-05-07 09:08 UTC
Labels: Type: Not a bug

**Comment by urvesh86** [comment] 2020-05-14 11:00
Hi @oysteinmoseng,  

Thank you very much for your reply. I have tried to resolve the issues as per your suggestion and api reference of highchart. But I am still facing the issue. I am checking with NVDA screen reader. Do I miss anything to configured? 

I am using the highchart version 8.0.4.

**Comment by pawelfus** [comment] 2020-05-15 09:38
> Do I miss anything to configured?

We don't know, did you configure your chart like in the demo above? https://jsfiddle.net/oysteinmoseng/r56bgxma/ 

If you still encounter the issue, please recreate this in jsFiddle.

**Comment by urvesh86** [comment] 2020-06-01 07:00
@pawelfus Thanks for your help. Earlier I was trying without the upgraded version (8.0.4). It is working fine after upgrading the latest version (8.1.0).

Thanks again!!

**Comment by sebastianbochan** [comment] 2020-06-01 08:03
Thank you for the feedaback!
