### ISSUE TITLE
Click event on colum serie does not work in boost mode

### ISSUE THREAD

**Issue by trinelisekvastad** [highcharts/highcharts#21054] opened 2024-04-23 11:47 UTC
#### Expected behaviour
I expect that the click event should be working in my charts when there are many (thousands) columns shown in a series in boost mode

#### Actual behaviour

I have different series with of type scatter and columns
I have implemented the halo as I have seen suggested elsewhere and it works for scatter chart but not columns
mouseOver: function () {
            if (this.series.halo) {
              this.series.halo.attr({
                class: 'highcharts-tracker'
              }).toFront()
            }
          }

Debugging the code I see that this.series.halo is undefined for series of type column

#### Live demo with steps to reproduce
I think I have reproduced it on this fiddle
https://jsfiddle.net/daniel_s/s32tu76m/ by setting type: 'column'

when doing so the click event is not triggered

#### Affected browser(s)
Chrome, Edge etc

#### Example of UI in my application
This is showing data within a pipeline with clock position (0-12) using scatter plot. If no clock position available I create a column with point 12 to show a vertical line. In the example I am struggeling with I have 72000 scatter points where the click event works and 19000 column points where it does not work. Tooltip works on all and the mouseOver event works but this.series.halo is undefined for column point

![image](https://github.com/highcharts/highcharts/assets/124041764/9096356c-7b18-486a-8f3e-513bf3ee7d21)

**Comment by karolkolodziej** [comment] 2024-04-25 06:55
Hi @trinelisekvastad! 
You can bypass the `series.events` and use the chart events together with `hoverPoint`.

Code snippet:
```js
  chart: {
    events: {
      click: function() {
        const point = this.hoverPoint;

        if (point) {
          alert(`Clicked on point with x: ${point.x} and y: ${point.y}`)
        }
      }
    }
```
[Live demo.](https://jsfiddle.net/BlackLabel/8vsn6oja/)

Closing this as a duplicate of https://github.com/highcharts/highcharts/issues/14067.

**Closed** 2024-04-25 06:57 UTC
Labels: Duplicate
