### ISSUE TITLE
Highcharts 7.0.3 src breaks a tooltip with error cannot create 'tooltip' on boolean 'false'

### ISSUE THREAD

**Issue by tnrn9b** [highcharts/highcharts#10343] opened 2019-03-18 22:33 UTC
#### Expected behaviour
Changing 
<script src="https://code.highcharts.com/7.0.3/highcharts.js"></script>
to  
<script src="https://code.highcharts.com/7.0.3/highcharts.src.js"></script>
shouldn't break the graph
#### Actual behaviour
It does.

#### Live demo with steps to reproduce

[Codepen](https://codepen.io/TommyTank/pen/JzBRNg)
#### Product version

7.0.3
#### Affected browser(s)
Chrome

This is probably somehow related to issue #8766

**Comment by sebastianbochan** [comment] 2019-03-19 09:30
Hi @tnrn9b,
Thank you for reporting about the problem. It is duplicate of mentioned ticket, so Im closing this one and reopen the main thread. It will allow us to keep all informations in the same thread.

**Closed by sebastianbochan** 2019-03-19 09:30 UTC
