### ISSUE TITLE
Calling update with setExtremes adds callback rather than replacing

### ISSUE THREAD

**Issue by rmacsween** [highcharts/highcharts#14751] opened 2020-12-03 16:54 UTC
I'm not sure if this is a bug or not; if it is the expected behaviour I would appreciate advice on how to change it.

#### Expected behaviour
After doing
```
chart.update({
          xAxis: {
            type: 'datetime',
            events: {
              setExtremes: function(event) {
                console.log("foo")
              }
            }
          }});
```
when the `setExtremes` event occurs, only the callback from this update should be executed, not previous ones.

#### Actual behaviour
Callbacks added in all updates are executed.

#### Live demo with steps to reproduce
https://jsfiddle.net/ntew501m/

#### Product version
7.0.0

**Comment by pawelfus** [comment] 2020-12-04 13:13
Hi @rmacsween 

Thank you for reporting the issue! Please check this issue #6943 - it's the same as you reported. This still has the status of undecided.

> I would appreciate advice on how to change it

See my comment here: https://github.com/highcharts/highcharts/issues/6943#issuecomment-333493579

Marking and closing as a duplicate of #6943.

**Closed by pawelfus** 2020-12-04 13:13 UTC
