### ISSUE TITLE
Slow panning when zoomed out on highstock

### ISSUE THREAD

**Issue by jurasofish** [highcharts/highcharts#15198] opened 2021-02-23 04:35 UTC
#### Expected behaviour
Chart panning follows the mouse cursor on zoomed out stock chart.

#### Actual behaviour
Panning is slow, such that the mouse moves much faster than the underlying graph.

#### Live demo with steps to reproduce
jsfiddle: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/chart/panning/
Zoom almost all the way out and then hold alt to pan. Panning will be very slow.
(Panning works fine when zoomed far in)

#### Product version
Highstock v9.0.1

#### Affected browser(s)
Chrome and Firefox

Sure, you can use the slider down the bottom of the chart - but I want to turn that slider off and click and drag on the graph itself to pan.

**Comment by KacperMadej** [comment] 2021-02-23 13:57
Hi @jurasofish 

Thank you for reporting the problem.

When panning is faster than the chart's ability to redraw itself then some panning steps are lost. Try setting the zoom to about half of the navigator and compare fast and very slow panning - it gives different results, different amount of panned axis range.

It looks like the default `ordinal:true` in xAxis is causing the lag. With `ordinal:false` I am not able to recreate the problem.
**Workaround** with `ordinal:false`: https://jsfiddle.net/BlackLabel/5k6mfsqe/

**Comment by jurasofish** [comment] 2021-02-23 22:18
thanks heaps @KacperMadej, that workaround does the trick for me

**Comment by pawelfus** [comment] 2021-03-03 15:42
Duplicate of #3825

It will be fixed in the upcoming releases, preview: https://jsfiddle.net/BlackLabel/84smerd7/

**Closed by pawelfus** 2021-03-03 15:42 UTC
Labels: Product: Highcharts Stock, Status: Has workaround, Type: Bug
