### ISSUE TITLE
Highcharts resize issue in iPad device.

### ISSUE THREAD

**Issue by nileshbarai** [highcharts/highcharts#7870] opened 2018-02-15 14:16 UTC
#### Expected behaviour
The charts should resize (fit to container) properly in iPad device after orientation change.

#### Actual behaviour
The charts not resize (fit to container) properly in iPad device after orientation change.

#### Live demo with steps to reproduce
Earlier it was working fine, but I have replaced old version highstock.js with latest version (Highstock JS v6.0.4).

#### Product version
Highstock JS v6.0.4

#### Affected browser(s)
iPad: On page load it's working fine but when we will change the orientation then the chart not to fit with container. When we refresh the page then it's working fine.

Thanks in advance,
Nilesh

**Comment by pawelfus** [comment] 2018-02-16 12:00
Hi @nileshbarai 

Thank you for reporting the issue. Could you recreate issue in jsFiddle? Does it happen with any of our demos: https://www.highcharts.com/demo/ ?

**Comment by sebastianbochan** [comment] 2018-02-27 10:15
Hi @nileshbarai 
Let me know which version of iOS you have.

**Comment by KevinShiCA** [comment] 2018-05-31 12:55
I am experiencing this on iOS 11.2.2, it happens on the `chart.reflow` demo: http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/chart/reflow-true/

Steps to reproduce
1. Open the fiddle on an iPad
2. Increase the width of the result panel, reflow works here
3. Decrease the width of the result panel, reflow fails here

**Comment by sebastianbochan** [comment] 2018-06-04 10:34
Hi @KevinShiCA,
Thank you for the steps and version.
It looks like a problem with jsFiddle only, because when I run the demo: http://jsfiddle.net/k6q90jj8/ all works properly. Could you confirm? If problem is still valid in your environment (static page, not jsfiddle), please send me an example (i.e by email support@highchart.com)

**Comment by KevinShiCA** [comment] 2018-06-27 15:14
Update: it was caused by iOS not working with wrapping elements, nothing to do with Highcharts.

**Comment by pawelfus** [comment] 2018-06-27 15:17
Thank you for the info! Closing the issue, please let us know if someone will be able to recreate the issue - we will reopen this issue.

**Closed by pawelfus** 2018-06-27 15:17 UTC
Labels: Pending reply

**Comment by arunavasumathi** [comment] 2019-02-14 07:40
I face this issue in iPhone Simulator. I use 2 charts on the same page, strangely one of which is not fitting to the container with all constraints being same for both charts.
Can someone suggest what could be wrong?

**Comment by pawelfus** [comment] 2019-02-14 13:52
Hi @arunavasumathi 

Only one chart is broken? This is strange, hard to say without seeing a live demo. Could you setup one, please? Thanks!

**Comment by arunavasumathi** [comment] 2019-02-15 05:21
This happened after upgrading the library. Maybe I will have to revert back to 6.1.4 which I used previously and check.

**Comment by arunavasumathi** [comment] 2019-02-15 06:46
The problem was with my chartload function. I will have to check it. 👍

**Comment by jobinsjohn** [comment] 2023-11-23 20:22
I am facing the same issue now with version 11.1.0.

I have 3 charts which are shown in a collection view and each cell has a chart. The third one goes out of the area, but the first 2 stays inside the collection View cell.

**Comment by ihnatmoisieiev** [comment] 2023-11-28 08:59
Hello @jobinsjohn,
could you please prepare a small demo in iOS with a collection view where we can reproduce the issue?
It's hard to suggest something without reproducing at the moment.
Thank you!
