### ISSUE TITLE
Hidden element is defined under headings.

### ISSUE THREAD

**Issue by anubhutisaini12** [highcharts/highcharts#15092] opened 2021-02-10 05:51 UTC
Expected behaviour
"Chart Title" defined under heading tag should be visible on the page.

Actual behaviour
"Chart Title" is defined under heading tag but is not visible on the page. It is hidden element.

Link to repo
https://www.highcharts.com/demo/line-basic

MAS Reference:
MAS 2.4.6 - Headings and Labels (27A)

![highchart hidden](https://user-images.githubusercontent.com/76141946/107470813-00568700-6b92-11eb-96d2-8fcdc3e01d9f.png)

**Comment by KacperMadej** [comment] 2021-02-12 16:37
Hi @anubhutisaini12 

Thank you for contacting us.
Please add a link for the `MAS Reference` you have mentioned, so it will be a useful reference and/or provide more details about the problem - what is wrong, what rule seems to be broken, etc.

The element is not visible as it is for a screen reader to read as a part of accessibility support.

fyi (a11y) @oysteinmoseng

**Comment by anubhutisaini12** [comment] 2021-02-15 05:18
MAS Reference:
MAS 2.4.6 - Headings and Labels (27A)

**Comment by oysteinmoseng** [comment] 2021-02-15 09:27
Hi @anubhutisaini12, this is by design. The MAS guidelines map to WCAG 2.1 to my knowledge, and there is no specific requirement in WCAG that headings must be visible on the page. It can also be argued that this heading maps to the chart title, which is visible on the page. The heading is added by default as a result of user testing with screen reader users, as a usability feature.

If your guidelines require you to change this, the section can be configured using the [accessibility.screenReaderSection.beforeChartFormat](https://api.highcharts.com/highcharts/accessibility.screenReaderSection.beforeChartFormat) option - and the heading tag can be changed to something else.

I am closing this, but feel free to comment and we can reopen if necessary.

**Closed by oysteinmoseng** 2021-02-15 09:27 UTC
Labels: Status: Pending reply
