### ISSUE TITLE
Stack height issue when boost is enabled

### ISSUE THREAD

**Issue by ifree92** [highcharts/highcharts#12380] opened 2019-11-09 12:49 UTC
Expected chart (when we have 49 series points): https://jsfiddle.net/this_self/r0ksgbdp/8/
We see here normal height, all good.

Issued chart (when we have 50 series points): https://jsfiddle.net/this_self/r0ksgbdp/9/
We see here that all stack line now showing just like one thin line without normal height.

Highcharts version: 7.2.1 (latest at the moment when I was posting this issue)

**Comment by raf18seb** [comment] 2019-11-12 09:57
Hi,

The boost turns on when you have 50 series, see https://api.highcharts.com/highcharts/boost.seriesThreshold

When the boost is on, the column's width is always 1px. See general documentation: https://www.highcharts.com/docs/advanced-chart-features/boost-module

This is not a bug so I am closing the ticket. In case of any further questions, please use other support channels: https://www.highcharts.com/blog/support

**Closed** 2019-11-12 09:57 UTC
Labels: Type: Not a bug
