### ISSUE TITLE
Tooltip's opacity (and backgroundColor) are not respected

### ISSUE THREAD

**Issue by rdp1414** [highcharts/highcharts#17260] opened 2022-05-06 11:20 UTC
#### Actual behavior
1. We have a use-case where `title`, `subtitle` and `tooltip`'s html rendering is required, so, we enabled their `useHTML` options. But after that, we are seeing that tooltip is transparent and it overlaps with text outside chart's plot-area like `title` and `subtitle` making the texts unreadable.
2. So, we tried setting [tooltip.style.opacity](https://api.highcharts.com/highcharts/tooltip.style) to `1`, but this option was not respected.
3. Then, we tried [tooltip.backgroundColor](https://api.highcharts.com/highcharts/tooltip.backgroundColor) to `rgba(255, 255, 255, 1`, but this option was also not respected.

#### Expected behavior
Options `tooltip.style.opacity` and `tooltip.backgroundColor` should be respected.

#### Live demo with steps to reproduce
See reproducer fiddle https://jsfiddle.net/457Lhnu9/

#### Product version
10.0.0

#### Affected browser(s)
Google Chrome

**Comment by raf18seb** [comment] 2022-05-09 10:22
Closing as a duplicate of https://github.com/highcharts/highcharts/issues/17028 and https://github.com/highcharts/highcharts/issues/12236 (very similar problem)

As a solution, style your tooltip using CSS as shown in [our official tooltip.useHTML demo](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/tooltip/fullhtml/), or even a simpler solution: set `tooltip.outside: true`
Demo: https://jsfiddle.net/BlackLabel/q9puzny0/

**Closed by raf18seb** 2022-05-09 10:22 UTC

**Comment by raf18seb** [comment] 2022-05-13 13:31
@rdp1414 
You can find the zip files here in our changelog: https://www.highcharts.com/changelog/
and click this icon: 
![image](https://user-images.githubusercontent.com/23310742/168294584-f297bb07-54e3-46d3-9800-30f8fb8238da.png)

https://code.highcharts.com/zips/Highcharts-Stock-9.1.2.zip
