### ISSUE TITLE
[Highcharts v6.2.0] Shadow doesn't work

### ISSUE THREAD

**Issue by ar41bald** [highcharts/highcharts#17031] opened 2022-02-24 12:21 UTC
#### Expected behavior
Chart with a shadow should be visible when `highchart` is imported from the root of the module (`import { chart, Options } from 'highcharts';`)

#### Actual behaviour
The whole chart is not visible when `highchart` is imported from the root for the module `import { chart, Options } from 'highcharts';`

As I can see, when importing from the root, the shadow definition doesn't exist in the HTML.

#### Live demo with steps to reproduce
[The whole chart is not visible](https://stackblitz.com/edit/angular-ivy-rwbvg4?file=src%2Fapp%2Fapp.component.ts)

```
// With the below import the chart bars are visible
// import { chart, Options } from 'highcharts/js/highcharts';

// With the below import the chart bars are not visible
import { chart, Options } from 'highcharts';

```

To make the chart visible, uncomment the first `highchart` import and comment the second one

![Highcharts_import_issue](https://user-images.githubusercontent.com/12528704/155523005-a9d9e719-9f44-4872-9e0d-38a6f28a84bb.jpg)

#### Product version
Highcharts v6.2.0

#### Affected browser(s)
Chrome

**Comment by raf18seb** [comment] 2022-02-28 10:11
Hi @ar41bald, thank you for creating a ticket.

The filter you are trying to apply work only in styled mode.
It worked in 6.2.0 because, to enable the styledMode, the core files should be loaded from the `code.highcharts.com/js` folder. It changed in 7.0.0. Now, you need to set `chart.styledMode` to `true`, see a changelog: https://www.highcharts.com/blog/changelog/#highcharts-v7.0.0 (Upgrade notes)

Working JS demo: https://jsfiddle.net/BlackLabel/r71d8egL/

I'm closing this ticket as not a bug.

**Closed by raf18seb** 2022-02-28 10:11 UTC
