### ISSUE TITLE
The hidden HTML elements of the chart should be accessible via both non Narrator mode and Narrator mode.

### ISSUE THREAD

**Issue by siddarthkanted** [highcharts/highcharts#14443] opened 2020-10-28 06:11 UTC
#### Expected behaviour
The hidden HTML elements of the chart should be accessible via both non Narrator mode and Narrator mode.
Need a way to change the tab index of the HTML elements provided in the image.

#### Actual behaviour
Currently, the hidden elements of the chart are accessible only via scan mode.

#### Live demo with steps to reproduce
https://www.highcharts.com/samples/highcharts/accessibility/accessible-pie

1.  The below HTML elements are accessible during scan mode.
2. The below HTML elements are not accessible using non Narrator mode. 

An element if accessible in Narrator mode should also be accessible in non Narrator mode.
Need a way to change the tab index of the HTML elements provided in the image.

![image](https://user-images.githubusercontent.com/13218256/97398420-3b012000-1911-11eb-83d9-ac07904a771b.png)

#### Product version
        "highcharts": "8.1.1"

#### Affected browser(s)
Chrome, edge, opera

**Comment by PaulDalek** [comment] 2020-10-28 09:13
Hi @siddarthkanted

Thank you for reporting this issue. 

FYI @oysteinmoseng

**Comment by oysteinmoseng** [comment] 2020-10-28 11:40
Hi @siddarthkanted, this is by design after user testing. This hidden information is specifically tailored to non-visual screen reader users. Other users have access to the same information visually.

It is possible to configure the contents of the region using the [beforeChartFormat](https://api.highcharts.com/highcharts/accessibility.screenReaderSection.beforeChartFormat) and [beforeChartFormatter](https://api.highcharts.com/highcharts/accessibility.screenReaderSection.beforeChartFormatter) options. This means that you can remove the contents and display your own if this is preferred in your use case.

Note that we always recommend the text description of the chart to be visible, see https://api.highcharts.com/highcharts/accessibility.linkedDescription.

I am closing this issue as not a bug, but feel free to comment with any questions and we can reopen as needed.

**Closed by oysteinmoseng** 2020-10-28 11:40 UTC
Labels: Type: Not a bug
