### ISSUE TITLE
onContainerMouseLeave is undefined 

### ISSUE THREAD

**Issue by K009** [highcharts/highcharts#21833] opened 2024-09-13 08:29 UTC
#### Actual behaviour
There are a lot of log messages in the Chrome console when hovering over time series charts, particularly when using the click-and-drag to zoom feature. This issue breaks the zoom functionality after refreshing charts dynamically.

Unfortunately the issue can't be reproduced in jsFiddle, as the problem doesn't occur in static environments.

This happens when charts are dynamically rendered and swapped with new ones on refresh cycles.  The click and drag works the first time and when the charts are refreshed with a new one the click and drag does not work due to the exception.
We cannot send you our product to look at and hence we have to go by the description of the problem and highstock code involved.
 
The exception is clearly coming from the setHoverChartIndex() function in the Highstock code as shown below:
![image](https://github.com/user-attachments/assets/b91243c5-dcb0-4010-ac28-ffde39da7904)
The exception will occur if the hoverChart.pointer is undefined.
A simple fix is to guard against the property being undefined to prevent the exception. 
![image](https://github.com/user-attachments/assets/1192a227-f2b9-4531-befe-419e4fd8457d)

This pollyfill worked fine since Highstock version 8.2.2.  After upgrading to Highstock 10.3.3 the polyfill broke because the Highstock API changed.

#### Product version
Highstock v10.3.3

**Comment by pawelfus** [comment] 2024-09-13 10:21
The code comes from Core, changing the product

**Comment by KacperMadej** [comment] 2024-09-16 10:08
@K009 
If the charts are refreshed correctly then they should be in the Highcharts.charts array listed as either a correct chart or undefined. Maybe the charts are not refreshed/updated correctly? Without a way to recreate this it will be hard to fix and almost impossible to find the source of the problem. Please add the way to recreate the problem.

**Comment by zzr994** [comment] 2024-09-16 15:49
Hello KacperMadej,
The issue is not about chart refresh.  It is about re-creating the charts in the same space in the UI.  We have a number of tiles in which line charts are shown.  The user can refresh these charts using different start/end times.  We do not refresh the charts. Instead we destroy all the charts and they are recreated with the new data from the server.  

It is very difficult to recreate this scenario in static environments such as jsfiddle. Instead we should focus on the exception coming from the Highchart API and how it could be made better by preventing such exceptions. We are not asking for much except a small additional check to prevent the exception.

This simple fix has helped us for many years using a pollyfill.  The pollyfill breaks when the chart version change. In our case we were going from 8.2.2 to 10.3.3.  This simple fix will help us and other users who may be facing the same issue, but do not have a way to address it.

Hope this helps. 

Thanks.

**Comment by zzr994** [comment] 2024-09-17 18:47
@KacperMadej 
If it is resolved it is ok to close the issue. 
We will test it when we upgrade to 11.4.0.
Thanks.

**Comment by KacperMadej** [comment] 2024-09-18 07:26
@zzr994 
Feel free to let us know if your tests will come back not the way you expect so we could reopen this issue or open a new one.

Closing as a duplicate and already fixed.

**Closed by KacperMadej** 2024-09-18 07:26 UTC
Labels: Type: Bug, Product: Highcharts, Status: Pending reply
