### ISSUE TITLE
Missing focus on inputs, when create chart in hidden DIV

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5231] opened 2016-04-20 11:00 UTC
#### Expected behaviour
Working inputs

#### Actual behaviour
Missing focus on the input

#### Live demo of the issue
http://jsfiddle.net/0m6qxm41/

#### Steps to reproduce the behaviour
1. Click Show Parent Div button
2. Click Show chart Div button

#### Affected browser(s)
All

**Comment by oysteinmoseng** [comment] 2016-04-21 10:01
Simplified jsFiddle without jQuery: http://jsfiddle.net/0m6qxm41/1/

To reproduce, click "Show chart div", and try to focus on input elements.

**Comment by KacperMadej** [comment] 2016-08-23 09:19
Looks like the bug is fixed only on bugfix branch and the commit didn't make it to the master.

**Comment by TorsteinHonsi** [comment] 2016-08-24 08:49
Yes, looks like something went wrong when cherry-picking, it is fixed now.

**Closed** 2016-08-24 08:49 UTC
Labels: Bug, Fix suggested, Highstock
