### ISSUE TITLE
Missing types for Exporting button states theme

### ISSUE THREAD

**Issue by w0pp** [highcharts/highcharts#22085] opened 2024-10-30 11:01 UTC
#### Expected behaviour
`exporting.buttons.contextButton.theme` should have a `states` property for customizing hover and select theme. See https://api.highcharts.com/highcharts/exporting.buttons.contextButton.theme

#### Actual behaviour
It doesn't have a `states` property - I get this error: `Object literal may only specify known properties, and states does not exist in type ExportingButtonsContextButtonThemeOptions`

#### Product version

Highcharts Core 11.4.8

**Comment by hubertkozik** [comment] 2024-10-31 08:57
Hi @w0pp! This issue is a duplicate of https://github.com/highcharts/highcharts/issues/21898.

**Closed by hubertkozik** 2024-10-31 08:57 UTC
Labels: Duplicate
