### ISSUE TITLE
updateContainerScaling not working when mouse is already over the Chart

### ISSUE THREAD

**Issue by Llorx** [highcharts/highcharts#12489] opened 2019-11-25 10:49 UTC
#### Expected behaviour
Detect mouse position correctly without needing to go out the Chart

#### Actual behaviour
Mouse pointer detection is wrong, unless you go out the Chart and go in again

#### Live demo with steps to reproduce
http://jsfiddle.net/tbzmokL9/
Steps:
- Mouse over the Chart.
- After 3 seconds, scale will be updated, along with `updateContainerScaling()`.
- You will notice weird mouse detection.
- If you go out the Chart and in again, it works as expected.

GIF:
![2019-11-25_11-50-57](https://user-images.githubusercontent.com/702490/69534355-e96e4980-0f79-11ea-98ee-2810e9531586.gif)

#### Product version
Highcharts latest from CDN

#### Affected browser(s)
Chrome?

**Comment by Llorx** [comment] 2019-11-25 12:16
Found the problem. Is because f the `chart.pointer.chartPosition` cached property.

If I clean the `chart.pointer.chartPosition = undefined;` when calling `updateContainerScaling()`, it works.

**Comment by pawelfus** [comment] 2019-11-26 11:17
Thanks for reporting the issue and sharing the workaround @Llorx! 

FYI @oysteinmoseng

**Comment by oysteinmoseng** [comment] 2019-11-26 11:58
`updateContainerScaling` is definitely an internal thing, and does not deal with `pointer`.

I think this should be handled by `chart.reflow` instead, and `chart.reflow` could clear the pointer position & update the scaling.

**Comment by Llorx** [comment] 2019-11-26 12:16
Hm, but if you have defined `width` and `height`, `reflow()` won't work (`hasUserSize` variable).

Also it just calls `setSize` internally, nothing more. And `setSize` is really really expensive to just calculate new pointer positions.

With `pointer.normalize` was pretty easy to achieve (as you can see here: https://github.com/highcharts/highcharts/pull/8634), with no tooltip scaling bugs. Now is a bit more complex, which leads to more complex code, as now there are different sections where the `containerScaling` is checked/applied, and appeared some bugs and problems.

Can we discuss the PoC a bit or is too late?

**Comment by oysteinmoseng** [comment] 2019-11-26 12:37
Yes, my idea with using `reflow` is just to harmonize the API for the user so that there is only one function that has to be called if the container changes (whether size or in this case - scaling). We can certainly look at optimizations to avoid unnecessary computations in the case of a specified `width/height`

**Comment by EPurpl3** [comment] 2020-07-10 08:16
Anything on this bug yet, officially?


> Found the problem. Is because of the `chart.pointer.chartPosition` cached property.
> 
> If I clean the `chart.pointer.chartPosition = undefined;` when calling `updateContainerScaling()`, it works. I guess that `updateContainerScaling()` is more an internal thing, but by the way, I would suggest to clean `pointer.chartPosition` when is called. It feels like a dirty hack to clean it "from the outside". I can do a PR if you want.


Can you please provide JSFiddle with the workaround? Thanks

**Comment by pawelfus** [comment] 2020-07-13 11:22
It seems to be a duplicate of #11975 - we are still looking for the best solution here.

**Comment by EPurpl3** [comment] 2020-07-13 11:46
As a workaround, this did the trick for me perfectly (almost). https://github.com/highcharts/highcharts/issues/12031

**Comment by pawelfus** [comment] 2020-11-19 09:29
*Internal note:*
Agreed on https://github.com/highcharts/highcharts/issues/12489#issuecomment-558609784 - simply remove cached position and scale on when calling `chart.reflow()`.

**Closed** 2021-01-05 14:15 UTC
Labels: Status: Inbox, Type: Bug
