### ISSUE TITLE
Maximum of yAxis for percent stacking column chart rendered as 150% (container.height dependent?)

### ISSUE THREAD

**Issue by valichek** [highcharts/highcharts#5148] opened 2016-03-23 14:32 UTC
Here is a fiddle:
http://jsfiddle.net/mv6cr911/1/

When I set  container.height <= 310px it renders not 100% but 150% maximum

**Comment by pawelfus** [comment] 2016-03-24 11:45
Looks like duplicate of #1850 (or #4580) - could you try the workaround posted there? Works for me fine: http://jsfiddle.net/mv6cr911/2/

**Comment by pawelfus** [comment] 2016-07-04 11:37
Closing due to inactivity. If this bug is different, please reopen this ticket.

**Closed** 2016-07-04 11:36 UTC
Labels: Duplicate, Pending reply
