### ISSUE TITLE
Bar chart, It can not zoom in some case

### ISSUE THREAD

**Issue by idscene** [highcharts/highcharts#18451] opened 2023-02-07 10:49 UTC
#### Expected behaviour
I expected that we can zoom in any place in bar chart after I click zoom.

#### Actual behaviour
In fact, I found a bug that when I zoom I got no response after that on tha bar chart even it's just a basic action.

#### Live demo with steps to reproduce

I got review from the board highchart : https://www.highcharts.com/forum/viewtopic.php?f=9&t=50281
example :  [Bar chart, It can not zoom in some case](https://jsfiddle.net/hLt7vykq/)

#### Product version

Latest version via https://code.highcharts.com/highcharts.js of today.

#### Affected browser(s)
Firefox, Chrome

**Comment by bm64** [comment] 2023-02-07 11:12
Hello @idscene and thanks for contacting us.

I'm closing this issue as a duplicate of #18103. If there is anything you'd like to add feel free to comment in the original ticket.

**Closed by bm64** 2023-02-07 11:12 UTC
