### ISSUE TITLE
Area chart does not interpolate line to the next available value

### ISSUE THREAD

**Issue by totszwai** [highcharts/highcharts#9131] opened 2018-10-05 00:28 UTC
#### Expected behaviour
The area chart should interpolate between the data points like the line chart when a data point is missing within the series. 

#### Actual behaviour
The area chart does not interpolate between the data points

#### Live demo with steps to reproduce
https://jsfiddle.net/totszwai/gkyn16h7/

#### Product version
6.1

#### Affected browser(s)
All

Currently with the line chart, we have a placeholder/dummy series that contains all the timestamp slot to be display on the highcharts, then we supply the rest of the data series with specific timestamp and value. It worked perfectly as the line chart would interpolate the line to the next dot.

However, it is not the case for the area chart.

**Comment by pawelfus** [comment] 2018-10-05 08:40
Hi @totszwai 

Thank you for reporting this issue. Actually it's a duplicate of #6204 

The problem is that `connectNulls` is missing implementation for stacked charts (https://jsfiddle.net/BlackLabel/gkyn16h7/16/ - `connectNulls=true` and `=false` does not change the chart).

Closing as duplicate of #6204

**Closed by pawelfus** 2018-10-05 08:40 UTC
