### ISSUE TITLE
Map of France is not up to date

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#7659] opened 2018-01-12 09:34 UTC
#### Expected behaviour
The administrative boundaries of France should be drawn according to the
https://en.wikipedia.org/wiki/ISO_3166-2:FR (Admin level 1 regions).

#### Actual behaviour
Maps of France available in the repository doesn't reflect official boundaries.

**Comment by KacperMadej** [comment] 2018-03-30 09:49
I'm marking this as a duplicate of a newer issue, because we have more info there and @PaulDalek started work there.

Closing as duplicate of #8086

**Closed by KacperMadej** 2018-03-30 09:49 UTC
Labels: Map collection
