### ISSUE TITLE
Hover issue on Bar/Column chart (Firefox only)

### ISSUE THREAD

**Issue by sruchot** [highcharts/highcharts#9797] opened 2019-01-04 14:10 UTC
I just discover a quite unpleasant issue running some charts on Firefox (v64.0) and firefox only (tested the same example on Edge and Chrome).

When you hover, you can see that the color is not uniform and it looks weird.

![image](https://user-images.githubusercontent.com/37374003/50691861-53b08f80-1032-11e9-9d5d-7a270b4bacce.png)

I first thought that was something to do with the tooltip so I tried disabling it and got:
![image](https://user-images.githubusercontent.com/37374003/50691960-a1c59300-1032-11e9-87b3-937243e62c79.png)

Only happening on long bars/columns. For example while hovering Africa and America, everything seems fine, and it starts failing on Asia.

I used an official Highcharts JsFiddle to reproduce the issue (so it should mean that it's happening on the live version):
[https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/bar-basic/](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/bar-basic/)

Any idea if I can do something on my hand to fix that?

Thanks,
Sylvain RUCHOT.

**Comment by pawelfus** [comment] 2019-01-04 14:18
Hi @sruchot 

Thanks for reporting the issue. We are aware of this issue in FF64, it's already reported: #9745 - these artefacts come from browser directly. Issue has been reported to mozilla developers.

Closing as duplicate of #9745

**Closed by pawelfus** 2019-01-04 14:18 UTC
