### ISSUE TITLE
xAxis dateTime doesn't work in case categories are defined

### ISSUE THREAD

**Issue by HuXiKa** [highcharts/highcharts#14974] opened 2021-01-22 11:27 UTC
#### Expected behaviour
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/line-time-series

This is the documented behavior, which seem to work when the series data contains the xAxis category values.

#### Actual behaviour

If we try to define the categories on the xAxis they will no longer be rendered as datetime. From the documentation of [`categories`](https://api.highcharts.com/highcharts/xAxis.categories) this should be used in case there are multiple series, is there a way to force the datetime [`type`](https://api.highcharts.com/highcharts/xAxis.type) in this case?

#### Live demo with steps to reproduce
https://jsfiddle.net/pLayhtbn/

#### Product version
8.1.2 & Latest

#### Affected browser(s)
Tested in Chrome.

**Comment by KacperMadej** [comment] 2021-01-22 12:15
Hi @HuXiKa 

Thank you for contacting us.

We are using GitHub issues as our bug tracker (and also for enhancement suggestions). For technical support please see https://www.highcharts.com/blog/support/

If you want to change the format of datetime axis labels you could use on of the below options:
- https://api.highcharts.com/highcharts/xAxis.dateTimeLabelFormats
- https://api.highcharts.com/highcharts/xAxis.labels.formatter
- https://api.highcharts.com/highcharts/xAxis.labels.format

> From the documentation of categories this should be used in case there are multiple series, is there a way to force the datetime type in this case?

This ("this should be used in case there are multiple series") applies only if you want to have categories, so the type of the axis will be `category`.

Closing as not a bug.
In case of further questions feel free to continue here or contact our technical support.

**Closed by KacperMadej** 2021-01-22 12:15 UTC
Labels: Type: Not a bug
