### ISSUE TITLE
Heat map x axis datetime type bug

### ISSUE THREAD

**Issue by pliasetski** [highcharts/highcharts#7582] opened 2017-12-27 13:27 UTC
Hello highcharts team,
This issue reproduced when I set xAxis type to datetime.
When I've got only two points, heat map builds correct, but xAxis labels looks broken (http://jsfiddle.net/Pashe4ka/tuxnyxhp/2/)
But when I have more then two points xAxis labels looks great, but heat map cells doesn't fill with color (http://jsfiddle.net/Pashe4ka/q2e439vq/1/)

#### Live demo with steps to reproduce
http://jsfiddle.net/Pashe4ka/tuxnyxhp/2/
http://jsfiddle.net/Pashe4ka/q2e439vq/1/

#### Affected browser(s)
Chrome latest version

**Comment by pawelfus** [comment] 2017-12-27 14:19
Hi @pliasetski 

Thank you for reporting this issue. "Missing" colors are caused by not setting [heatmap.colsize](https://api.highcharts.com/highcharts/plotOptions.heatmap.colsize) - by default it's set to one unit. For a datetime axis it's 1ms. For example, in your case setting `colsize: 31536000000,` (one year) shows correct heatmap: http://jsfiddle.net/q2e439vq/2/ I said "missing" colors, because shapes with colors are there, but the width of each one is 0px. Without setting `colsize` chart assumes you have 94694400000 points on a ~400px chart and reserves space for each point.

Regarding the issue with only one x-value, we are unable to guess what time exatly you want to show, for example:
> new Date(1417381200000)
> Sun Nov 30 2014 22:00:00 GMT+0100

We don't know that you want to show xAxis' labels as years. We display the lowest granularity we can assume from a single point (or rather a single x-value in this case). For example 1st Jan of 2014 ( 1388534400000 ) will display labels as daily data: http://jsfiddle.net/tuxnyxhp/3/

Let us know if you have any questions.

PS: You have duplicated data for 2014 (x=1417381200000).

**Comment by pliasetski** [comment] 2017-12-27 15:16
Hi @pawelfus ,
Thanks a lot, you helped me a lot.

**Comment by pawelfus** [comment] 2017-12-27 15:59
I'm happy to hear that :) Let me close the issue then.

**Closed by pawelfus** 2017-12-27 15:59 UTC
Labels: Not a bug
