### ISSUE TITLE
Data grouping doesn't adjust to show full resolution when zooming in

### ISSUE THREAD

**Issue by ransoing** [highcharts/highcharts#16473] opened 2021-10-07 19:15 UTC
#### Expected behaviour
The data grouping feature should group points when zoomed out far enough, and show data at full resolution when zoomed in enough.

#### Actual behaviour
In some cases, data grouping gets stuck in a state where it always groups data, no matter how far you zoom in. This seems to be the case if all of the following conditions are true:
* The cadence between points on the x-axis is < 1
* There are enough points in the series for data grouping to turn on
* There are multiple series on the chart

#### Live demo with steps to reproduce
http://jsfiddle.net/4nsmzfkt/1/

The first chart demonstrates the bug - the other charts are slightly different than the first and work as expected.

The bug is present with line series as well as arearange series - the fiddle uses arearange because it's easier to notice the bug when using arearange.

#### Product version
Highstock 9.2.2
This issue was not present in Highstock version 8.
See the following fiddle which uses 8.2.2 - the issue is not reproducible with that version.
http://jsfiddle.net/4nsmzfkt/2/

#### Affected browser(s)
All

**Comment by ransoing** [comment] 2023-01-10 18:49
@pawelfus 's workaround causes errors in the latest Highstock (10.3.2), but this doesn't matter because I can't reproduce the original issue in that version! 🎉

**Comment by pawelfus** [comment] 2023-01-11 08:46
Thank you for pointing this out @ransoing !
Fixed in #17141 - the first fixed version: v10.1.0

Closing as duplicate of #17141

**Closed by pawelfus** 2023-01-11 08:46 UTC
Labels: Type: Bug, Product: Highcharts Stock, Type: Duplicate, Status: Has workaround, Flow: Done
