### ISSUE TITLE
XAxis type='category' for drilldown graph is not working for large data

### ISSUE THREAD

**Issue by Pradeepg21** [highcharts/highcharts#8118] opened 2018-04-04 09:59 UTC
Expected Behavior : 
XAxis type='category' for drilldown graph should shows point names of the chart's series on xaxis. this behaviour is working fine for small data but rendering incorrect values(showing numbers) on xaxis when large data(> 50 approx) is provided.  

Actual Behavior:
XAxis type='category' for drilldown graph showing numbers instead of point names on xaxis when large data is provided.

#### Live demo with steps to reproduce
https://jsfiddle.net/prateeekp/r50s0qrp/7/

Steps:
1. click on the above fiddler link for live demo.
2. click on the "chrome column" bar for drilldown 
3. check the xaxis is not rendered correctly.

#### Product version
latest version

Google Chrome

**Comment by sebastianbochan** [comment] 2018-04-04 10:13
Hi @Pradeepg21 
Thank you for the reporting. 

Duplicate of https://github.com/highcharts/highcharts/issues/5857

**Closed by sebastianbochan** 2018-04-04 10:13 UTC

**Comment by Pradeepg21** [comment] 2018-04-04 10:41
Thanks sebastainbochan for the quick response and help.

The solution of #5857 works perfectly.

Thanks a lot
