### ISSUE TITLE
Line connecting data label to pie slice is invisible sometimes

### ISSUE THREAD

**Issue by eltonjude** [highcharts/highcharts#17009] opened 2022-02-17 15:04 UTC
#### Expected behaviour
The line should show

#### Actual behaviour
Line is not showing up for 2 of the 7 data labels

#### Live demo with steps to reproduce
https://jsfiddle.net/3gtd1y05/1/
In the fiddle you will see that the lines for Tue and Fri do not show up.
Support pointed me to this issue https://github.com/highcharts/highcharts/issues/16947 that demonstrates that it is an issue with SVG. The solution suggested was to manipulate the data such that we do not end up with an exactly straight line. In the fiddle there is a comment which tells you which value to change and to what. While this solution works in a static demo scenario, it does not scale to real usecases inside an app as we would need to figure out if we should be manipulating the data; and the fact that we are manipulating the data itself won't fly.

My request is for the label placement algo to realize that the line to the label is going to be a horizontal line and to position the label 1px off so as to not generate a horizontal line.

#### Product version
Highcharts latest

#### Affected browser(s)
Tested in Chrome v97

**Comment by raf18seb** [comment] 2022-02-18 13:41
Closing as a duplicate of https://github.com/highcharts/highcharts/issues/1677

**Closed by raf18seb** 2022-02-18 13:41 UTC
