### ISSUE TITLE
issue is not fixed, y axis values are showing if y axis value comes 1000 range **[[97376700000, 2500],

### ISSUE THREAD

**Issue by pankajd1990** [highcharts/highcharts#14079] opened 2020-08-18 15:32 UTC
issue is not fieed, y axis values are showing if y axis value comes 1000 range **[[97376700000, 2500],
         [1597376701000, 2600]]**,..but in other case if value comes as 100 or 200,y axis value are not displaying.
kindly refer 
https://jsfiddle.net/pankaj_durve/m8zobfg2/4/

_Originally posted by @pankajd1990 in https://github.com/highcharts/highcharts/issues/14076#issuecomment-675550844_

**Comment by sebastianbochan** [comment] 2020-08-19 07:15
Hi @pankajd1990,
Im closing as duplicate of https://github.com/highcharts/highcharts/issues/14079

**Closed by sebastianbochan** 2020-08-19 07:15 UTC
