### ISSUE TITLE
Highstock scrolling bar issue

### ISSUE THREAD

**Issue by pliasetski** [highcharts/highcharts#3239] opened 2014-07-08 13:51 UTC
Hello,

I have in chart more then one line and on of them starts no from the beginning.
First issue is that there is one extra “Vertical line” that  is displaying outside of “Scrolling Bar with Zoom”. (https://www.dropbox.com/s/o8x6yj15ww1nxst/first%20issue.png)

Second issue is when I start scrolling some series are disappears. (https://www.dropbox.com/s/t8nanr1bb1o8iwy/Second%20Issue.png)

Here is JsFiddle: http://jsfiddle.net/Pashe4ka/kUC6F/

Thanks.

**Comment by pawelfus** [comment] 2016-11-22 11:08
I'm looking into the older issues, but the demo and screenshots don't work. @pliasetski - is there any chance to recreate issue once again?

First issue should be resolved as I remember.

The second issue also should be fixed: now navigator takes into account all series, not only the base series.

**Comment by KacperMadej** [comment] 2017-07-31 10:54
Please reopen if needed and the problem is recreated.

**Closed by KacperMadej** 2017-07-31 10:54 UTC
Labels: Cant reproduce, Pending reply
