### ISSUE TITLE
Point.update does not update point color

### ISSUE THREAD

**Issue by aaronogan** [highcharts/highcharts#4932] opened 2016-01-18 15:45 UTC
When calling Point.update with a color, the point color does not change.  When hovering over the point, it does change colors.

http://jsfiddle.net/aaronogan/Ljazh8mb/

**Comment by sebastianbochan** [comment] 2016-01-18 15:47
This bug is fixed in the bugfix branch. 

http://jsfiddle.net/75jc2fqv/

Duplicate of #4622

**Closed by sebastianbochan** 2016-01-18 15:47 UTC
