### ISSUE TITLE
Regression: legend names overlap with highcharts 8 + drilldown + showInLegend

### ISSUE THREAD

**Issue by d3stroyahh** [highcharts/highcharts#12734] opened 2020-01-07 20:05 UTC
#### Expected behaviour
When using drilldown labels should not overlap. working in highcharts 7

#### Actual behaviour
Labels overlap.
The issue has to do with showInLegend: true. I think it's not meant to be this way.

#### Live demo with steps to reproduce
https://jsfiddle.net/2hs9z3cq/

#### Product version
highcharts 8.0.0

#### Affected browser(s)
chrome, i suppose others

Please fix :(

**Comment by sebastianbochan** [comment] 2020-01-08 10:00
Hi @d3stroyahh,
Thank you for reporting about the problem. I agree that is the regression and marked this case properly.

_Internal note_
Bisect leads me to https://github.com/highcharts/highcharts/commit/b05785120e5e53572d06eb35372005ec2a0b599b

FYI @ppotaczek

**Comment by ppotaczek** [comment] 2020-01-08 10:55
Duplicate of: https://github.com/highcharts/highcharts/issues/12627

Already fixed on the master branch: https://jsfiddle.net/BlackLabel/zdkjxwt0/1/

**Closed** 2020-01-08 10:55 UTC
Labels: Product: Highcharts, Type: Duplicate, Type: Regression
