### ISSUE TITLE
issue: use csv data which has space

### ISSUE THREAD

**Issue by cs0511** [highcharts/highcharts#5204] opened 2016-04-12 07:40 UTC
HI Hightcharts

Here is  my page. As the image shows, the Y Axis shows `Jan '01` and `Jul '01`, instead of `r 3` `test 8` `r 5` `r 2`.

I works when I remove space in it. 

=========

I tried it in Safari, Firefox, and Chrome. Only Chrome got incorrect graph. Safari and Firefox work fine. My jsfiddle http://jsfiddle.net/oucqddf4/

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<script src="https://code.jquery.com/jquery-2.2.3.js" integrity="sha256-laXWtGydpwqJ8JA+X9x2miwmaiKhn8tVmOVEigRNtP4=" crossorigin="anonymous"></script>

<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/data.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>



  </head>
  <body>
   <div class="chart-test"></div>

  </body>

<script>
    $('.chart-test').highcharts({
        chart: {
            type: 'bar'
        },
        data: {
            csv: "priority,yy\nr 3,1\ntest 8,1\nr 5,1\nr 2,1"
        }
    });

</script>
</html>
```
<img width="1255" alt="screen shot 2016-04-12 at 3 37 48 pm" src="https://cloud.githubusercontent.com/assets/2774879/14452985/9e185c4a-00c4-11e6-9bd6-8294d49e3cf0.png">

**Comment by pawelfus** [comment] 2016-04-12 11:02
Workaround: set `xAxis.type = "category"` and it will work fine: http://jsfiddle.net/oucqddf4/1/

**Comment by cs0511** [comment] 2016-04-13 02:41
thank you @pawelfus 

Why did it work Safari and Firefox without this setting?

**Comment by pawelfus** [comment] 2016-04-13 09:27
It's caused by `Date` parser in Chrome browser, consider an example:

     > new Date("r 3");
     > Thu Mar 01 2001 00:00:00 GMT+0100 (CET)

While all other browsers return `Invalid Date`. That's the reason why Highcharts use `datetime` axis in Chrome. I guess Chrome just skips all letters in the beginning, and parses `new Date('3')` ->
`Thu Mar 01 2001 00:00:00 GMT+0100 (CET)`.

**Comment by cs0511** [comment] 2016-04-14 03:23
Thank you @pawelfus , appreciate.

One more question here, 

If I have two xAxis, one is string which we need to set `type` to `category`, but another is `Date'.

How could we set these two xAxes?

**Comment by pawelfus** [comment] 2016-04-14 08:58
Something like this:

     xAxis: [{ 
       type: 'category'
     }, { 
       type: 'datetime'
     }]

Then in series: 

     series: [{
       xAxis: 0
     }, {
       xAxis: 1
     }]

But for questions, please use our support channels, [more info](www.highcharts.com/support).

**Comment by cs0511** [comment] 2016-04-14 09:03
thank you, @pawelfus , just know this channel, will do

**Comment by cs0511** [comment] 2016-04-15 00:15
Hi @pawelfus , I asked question in hightcharts forum, but no one reply, could you take a look if you have time? :apple:

**Comment by jon-a-nygaard** [comment] 2016-04-22 11:09
I am closing this issue since it appears to not be a bug. Further support questions will continue in the Highcharts forum.

**Closed by jon-a-nygaard** 2016-04-22 11:09 UTC
