### ISSUE TITLE
Sankey chart tooltip.valuePrefix property is confusing because works only with y value (which is not usually used in sankey chart)

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#8650] opened 2018-07-19 10:51 UTC
#### Expected behaviour
I want to use tooltip.valuePrefix or tooltip.valueSuffix property in **sankey** chart to format displaying value in tooltip.

#### Actual behaviour
Prefix and suffix are not displayed because they only concern y value. The problem is that in **sankey** chart we do not usually use y value but weight value.
To work around this problem we need to use pointFormat property (or any format or formatter) but then valuePrefix and valueSuffix are useless and confusing.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/s04x5Lkg/

#### Product version
Highcharts 6.1.1

**Comment by sebastianbochan** [comment] 2018-07-19 11:30
Duplicate of https://github.com/highcharts/highcharts/issues/8645

**Closed by sebastianbochan** 2018-07-19 11:30 UTC
