### ISSUE TITLE
getting error while implementing the dependency wheel 

### ISSUE THREAD

**Issue by ashrafmansuri7272** [highcharts/highcharts#14850] opened 2020-12-27 17:01 UTC
Type '[string, string, number]' has no properties in common with type 'SeriesSankeyPointOptionsObject'.ts(2559)

![image](https://user-images.githubusercontent.com/60643228/103175652-90b26400-4891-11eb-8812-fd61f538d83f.png)

![image](https://user-images.githubusercontent.com/60643228/103175665-aaec4200-4891-11eb-9655-44df8afe13e2.png)

**Comment by sebastianbochan** [comment] 2020-12-28 08:06
Hi @ashrafmansuri7272,
I'm closing the ticket as a duplicate of https://github.com/highcharts/highcharts/issues/14849

**Closed by sebastianbochan** 2020-12-28 08:06 UTC
