### ISSUE TITLE
Drilldown chart with scrollbar fails when the number of bars reaches 51

### ISSUE THREAD

**Issue by gianglv** [highcharts/highcharts#6816] opened 2017-06-09 04:05 UTC
#### Expected behaviour
I tried to create a drilldown chart with scrollbar enabled, it works well if the number of bars less than or equal 50.
#### Actual behaviour
When the number of bars reaches 51, the chart fails to render correctly. If I scroll to the right, the bars will be missing.

#### Live demo with steps to reproduce
http://jsfiddle.net/gianglv/kvok0p8q/5/

#### Affected browser(s)
Chrome
Microsoft Edge
Opera

**Comment by sebastianbochan** [comment] 2017-06-09 08:28
Thank you for reporting.

**Comment by pawelfus** [comment] 2017-06-09 08:31
It's a duplicate of #5857

**Workaround:**
Set `cropThreshold`, demo: http://jsfiddle.net/kvok0p8q/6/

**Closed by pawelfus** 2017-06-09 08:31 UTC
Labels: Bug
