### ISSUE TITLE
Why don't Chinese titles wrap

### ISSUE THREAD

**Issue by 99899899998** [highcharts/highcharts#16715] opened 2021-11-30 03:18 UTC
#### Expected behaviour
I want to wrap it

#### Actual behaviour
Chinese doesn't wrap, but English does

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/ndf5te62/

![image](https://user-images.githubusercontent.com/45654766/143979584-7dbc48d0-8fe5-48a2-85bd-8d2bab653a64.png)

#### Product version
Highcharts 9.3.2

Hope to recover soon,  thanks

**Comment by raf18seb** [comment] 2021-12-01 20:55
Hi @99899899998! Thanks for creating a ticket.

Latin alphabet isn't being wrapped as well when there's no space, see demo: https://jsfiddle.net/BlackLabel/Lzhgs6tx/
Chinese is being wrapped when spaced or `<br> are added: https://jsfiddle.net/BlackLabel/jndf8txk/

As an alternative, you could use these title styles:
```js
style: {
    'word-break': 'break-word',
    whiteSpace: 'normal'
}
```
but it's not working as expected, see a demo: https://jsfiddle.net/BlackLabel/vm29ky36/
This bug is already reported here: https://github.com/highcharts/highcharts/issues/14234

Closing as a duplicate of https://github.com/highcharts/highcharts/issues/14234

**Closed by raf18seb** 2021-12-01 20:55 UTC
