### ISSUE TITLE
https://github.com/highcharts/highcharts/issues/6308

### ISSUE THREAD

**Issue by brandontineo** [highcharts/highcharts#6329] opened 2017-02-01 22:46 UTC
Hi, I would like to see if there is an response for the issue above. It is a bug but I can't seem to figure out how to label it as such:

https://github.com/highcharts/highcharts/issues/6308

**Comment by TorsteinHonsi** [comment] 2017-02-02 08:53
Thanks for writing! Only the admins can label it a bug. If we don't respond quickly, please add comments to the issue.

Duplicate of #6308.

**Closed by TorsteinHonsi** 2017-02-02 08:53 UTC
