### ISSUE TITLE
t.getAttribute is not a function

### ISSUE THREAD

**Issue by abpardal** [highcharts/highcharts#18859] opened 2023-04-20 13:00 UTC
#### Expected behaviour
Don't know how to reproduce

#### Actual behaviour
Somehow we are getting the error 't.getAttribute is not a function' that cames from highcharts.js

`q=b.getAttribute(c))||"class"!==c`

![Captura de ecrã de 2023-04-20 13-54-04](https://user-images.githubusercontent.com/121935876/233373935-1bf9b92f-4129-4615-9673-3bc9829f77bb.png)

#### Live demo with steps to reproduce
-

#### Product version
10.2.0

#### Affected browser(s)
All

**Comment by pawellysy** [comment] 2023-04-21 08:43
Hi! @abpardal,
Without the demo, or any steps, we are unable to investigate the issue. Could you share your configuration of the chart?

**Comment by abpardal** [comment] 2023-04-28 09:39
Hello,

Our last log with this error was on pie-chart. The config for the chart is:

` {
        chart: {
            plotBackgroundColor: any;
            plotBorderWidth: any;
            plotShadow: boolean;
            type: string;
        };
        title: {
            text: string;
        };
        tooltip: {
            formatter: () => string;
        };
        plotOptions: {
            series: {
                dataLabels: {
                    enabled: boolean;
                    format: string;
                    style: {
                        fontWeight: string;
                    };
                };
                showInLegend: boolean;
                states: {
                    inactive: {
                        opacity: number;
                    };
                };
            };
        };
        series: any[];
        credits: {
            enabled: boolean;
        };
        legend: {
            enabled: boolean;
            align: string;
            layout: string;
            verticalAlign: string;
            x: number;
            y: number;
            labelFormatter: () => string;
        };`

We still aren't able to reproduce the problem.

**Comment by pawellysy** [comment] 2023-05-01 08:23
@abpardal, this config is just a TypeScript type, not a chart configuration (There are no values in the config)

If you are not able to reproduce the chart, I can't investigate a problem. For now, I'll close the issue, but when you manage to reproduce the issue, and share the reproduced demo, feel free to post it here, and reopen the issue. Thanks!

**Closed by pawellysy** 2023-05-01 08:23 UTC
