### ISSUE TITLE
client side export fails with boost module if more than 5K points

### ISSUE THREAD

**Issue by VKB2612** [highcharts/highcharts#10243] opened 2019-03-04 13:05 UTC
#### Expected behaviour
The cleint-side-export functionality works for PNG/JPEG/PDF/SVG types with or without images in Firefox and Chrome browsers even when fallbackToExportServer is false

#### Actual behaviour
When boost module is included, the client-side export functionality fails when one or more series is disabled and if fallbackToExportServer is set to false
- Firefox/Chrome for all PNG/JPEG/PDF/SVG types 
- IE 11 for SVG type

According to the browser compatibility table, even when the boost module converts SVG representation of a series into an image to improve the responsiveness of the chart in case of large number of points, 
- download for SVG/PNG/JPEG should work with or without images along with PDF for Firefox and Chrome browsers
- download for SVG should work with or without images for IE 11 

#### Live demo with steps to reproduce
[http://jsfiddle.net/km1sv43e/1/]

- data points greater than 5K, boost module referred, fallbackToExportServer set to false
- disable any series
- export 

Note: If the number of data points is less than 5K (default boostThreshold value) or if boost.js is excluded, the issue does not occur

#### Product version
Highcharts JS v7.0.3

#### Affected browser(s)
Firefox, Chrome, IE 11

**Comment by KacperMadej** [comment] 2019-03-04 13:09
Hi @VKB2612 

Thank you for contacting us about the problem.

I'm unable to recreate the issue using your demo - exports fine in Chrome. I have tested PNG and JPEG.

Are you getting the error set in the chart options or any other error?

**Comment by VKB2612** [comment] 2019-03-04 13:12
Hi @KacperMadej 

Did you try disabling any series and then exporting?

**Comment by KacperMadej** [comment] 2019-03-04 13:55
@VKB2612 
No, but I should. Looks like a bug. Thank you again for reporting.

_Internal note:_
fyi @cvasseng boost

**Comment by TorsteinHonsi** [comment] 2019-03-05 14:18
Live demo: https://jsfiddle.net/highcharts/akuorbhv/3/

**Comment by VKB2612** [comment] 2019-03-27 14:31
Thank you. It works perfectly.

**Comment by VKB2612** [comment] 2019-04-15 09:14
Hello, 

I just found an issue with the fix provided here. I observed this issue while downloading PDF only in Firefox. Sorry for the lately found issue.

It is shown in the download window that the file is exported from 'https://export.highcharts.com' though the property fallbackToExportServer is set to false. We do not intend to send the chart configs and data to Highsoft's servers and hence using offline-exporting module. 

You can reproduce the issue in the fiddlehttp://jsfiddle.net/f951joyx/1/

Please help. Let me know if I am missing something here and if I need to open a new issue for this.
Thanks.

**Comment by KacperMadej** [comment] 2019-04-15 10:22
Hi @VKB2612 

Looks like the offline-exporting is not loaded (at least I have that error) - `The resource from “https://raw.githubusercontent.com/highcharts/highcharts/a87fef84a975d5da9a8bc50aa406528e609a5457/js/modules/offline-exporting.src.js” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff)`.

With correct path from CDN (`https://code.highcharts.com/stock/modules/offline-exporting.js`) the error for failed download is being displayed.

@TorsteinHonsi 
Looks like offline export to PDF is not working for Chrome or Firefox when boost is loaded and enabled - https://jsfiddle.net/BlackLabel/d1mrf3pa/

**Comment by VKB2612** [comment] 2019-04-23 15:45
Hi @KacperMadej , @TorsteinHonsi 
Could you please let me know if there are any updates on this?
Thanks

**Comment by VKB2612** [comment] 2019-05-07 12:01
Hi @TorsteinHonsi , @KacperMadej 

Still the same error showing the file is exported from 'https://export.highcharts.com' exists with using offline-exportin.src.js from commit 5a32eb6. Please refer [https://jsfiddle.net/1yut3x4a/](https://jsfiddle.net/1yut3x4a/).

**Comment by KacperMadej** [comment] 2019-05-09 08:41
@TorsteinHonsi 
It looks like the problem is caused by the lack of the jspdf.js on our CDN.

The missing file: https://code.highcharts.com/master/lib/jspdf.js

The path is from the error on PDF export in this demo: https://jsfiddle.net/BlackLabel/9xw6Lsdh/

**Comment by TorsteinHonsi** [comment] 2019-05-10 08:10
Working demo: https://jsfiddle.net/highcharts/t1vdkfby/

@VKB2612 
Your fiddle doesn't work in Firefox because you're loading the raw ES6 module into Firefox. 

@KacperMadej 
> It looks like the problem is caused by the lack of the jspdf.js on our CDN.

Highcharts insertes the version in the [libURL]. When loading from `github.highcharts.com` the version is bogus. So by setting the `libURL` option it works.

**Comment by KacperMadej** [comment] 2019-05-13 07:59
Thank you for explaining.
Closing.

**Closed by KacperMadej** 2019-05-13 07:59 UTC
Labels: Type: Bug

**Comment by VKB2612** [comment] 2019-05-15 14:59
Hi @KacperMadej @TorsteinHonsi 

In case of large data, the issue still persists in both Firefox and Chrome browsers. Please refer fiddle 
http://jsfiddle.net/wcx39g87/1/

No of data points -> 20000
1. Dowload PDF -> error
2. Disable a series and PNG/JPEG/SVG download -> first error then file downloaded
3. Disable a series and PDF download -> multiple errors
Please have a look. Let me know if I am missing something.
Thanks.

**Comment by KacperMadej** [comment] 2019-05-16 10:39
The problem seems to be caused by the script not being able to create a blob because the Regexp used in code doesn't match `data:application/pdf;filename=generated.pdf;base64,JVB...` - the `filename=generated.pdf;` is the problem.

Here's a short demo for testing with that part removed: http://jsfiddle.net/BlackLabel/5pmdhrgv/1/
(Tested on Chrome / Win10)

Please give it a try @VKB2612

**Comment by VKB2612** [comment] 2019-05-16 14:27
Hi @KacperMadej
Thank you for the workaround.

**Comment by dscrimshaw** [comment] 2020-08-10 21:46
@KacperMadej I'm having the same issue, caused by the lack of regex match because of the filename=generated.pdf portion. How do we work around that when we're simply calling the exportChartLocal function and the rest seems to be handled by the HighCharts library?

**Comment by pawelfus** [comment] 2020-08-11 11:22
Updated Kacper's demo with random data: http://jsfiddle.net/BlackLabel/5pmdhrgv/3/

Workaround is to include plugin, just like any other Highcharts plugin (e.g. `exporting.js`): 
```js
(function(H) {

  var win = H.win,
    nav = win.navigator,
    doc = win.document,
    domurl = win.URL || win.webkitURL || win,
    isEdgeBrowser = /Edge\/\d+/.test(nav.userAgent);

  H.dataURLtoBlob = function(dataURL) {
    dataURL = dataURL.replace('filename=generated.pdf;', ''); // added

    var parts = dataURL.match(/data:([^;]*)(;base64)?,([0-9A-Za-z+/]+)/);

    if (
      parts &&
      parts.length > 3 &&
      win.atob &&
      win.ArrayBuffer &&
      win.Uint8Array &&
      win.Blob &&
      domurl.createObjectURL
    ) {
      // Try to convert data URL to Blob
      var binStr = win.atob(parts[3]),
        buf = new win.ArrayBuffer(binStr.length),
        binary = new win.Uint8Array(buf),
        blob;

      for (var i = 0; i < binary.length; ++i) {
        binary[i] = binStr.charCodeAt(i);
      }

      blob = new win.Blob([binary], {
        'type': parts[1]
      });
      return domurl.createObjectURL(blob);
    }
  };
}(Highcharts));
```

Alternative workaround (plugin, but not tested in IE): http://jsfiddle.net/BlackLabel/5pmdhrgv/4/

**Comment by timminss** [comment] 2020-10-14 10:01
@pawelfus Thanks for the workaround mentioned above. When I step through offline-export.src.js in Chrome Devtools and manually take this step (removing filename=generated.pdf;) - my PDF downloads no problem.

I haven't been able to get a custom plugin like your examples above to 'attach' to Highcharts however. The old / unchanged version of the function is called, rather than the one I've supplied. Any ideas what I might be doing wrong?

Thanks!

**Comment by pawelfus** [comment] 2020-10-14 11:14
Oh, since new modules import, wrapping `dataURLtoBlob` does no longer fix the issue..

Could you please createa bug report for this issue? We should properly fix this in the core. Thanks @timminss !

**Comment by timminss** [comment] 2020-10-14 11:33
Will do @pawelfus . Thanks for your response!
