### ISSUE TITLE
Highcharts.numberFormat rounding issue

### ISSUE THREAD

**Issue by xdestiny** [highcharts/highcharts#4852] opened 2015-12-16 08:30 UTC
Just ran into this behavior where a tooltip valueDecimal is set to 2 but a value of 29.115 will not result in 29.12 in the output but 29.11.

Here is an example that shows the issue: http://jsfiddle.net/wxhsmqrs/

The problem basically goes back all the way to Highcharts.numberFormat(29.115, 2). 

This obviously has to do with a typical problem in computer calculations where the number is represented as 29.11499999 internally. As this is a share price I cannot just add a 1 at the end to ensure correct calculation when the value is shown complete somewhere else, too.

Don't know if there is a real solution here. I'd reckon this should be done in the numberFormat function, though. If a number has more decimals than the target decimal number add 1 after the last official decimal to prohibit rounding errors from happening.

**Comment by pawelfus** [comment] 2015-12-16 11:14
Duplicate of #4573.

*Internal note:*
It should work like in [this case](https://github.com/kvz/phpjs/blob/master/functions/strings/number_format.js#L35-L36).

**Comment by TorsteinHonsi** [comment] 2015-12-21 14:26
Closed #4573.

**Closed by TorsteinHonsi** 2015-12-21 14:26 UTC
