### ISSUE TITLE
Exporting: Styled mode CSS variables are lost

### ISSUE THREAD

**Issue by wjaspers** [highcharts/highcharts#21142] opened 2024-05-08 18:48 UTC
#### Expected behaviour
When exporting a chart whose style choices are utilizing CSS variables, the variable values should be used.

#### Actual behaviour
Exporting a chart with CSS variables yields invalid values, which turn black.

#### Live demo with steps to reproduce
https://jsfiddle.net/bru0dm7q/1/

### Example code
```
/* styles */
:root {
  --hc-color-0: #FF0000;
}
```

```
// chart options
  "series": [{
      "data": [{
        "x": 1,
        "y": 9,
        "name": "Point2",
        "color": "var(--hc-color-0)"
      }],
      "type": "column"
    },
```

#### Product version
Highcharts 11.4.1

#### Affected browser(s)
Chrome, Chromium 124.0

_not tested on Safari or Edge_

#### Attached exported screenshot
__As shown to the user__
![browser-view](https://github.com/highcharts/highcharts/assets/598148/54779ed6-2889-4a15-9f91-76ee6f47f188)

__As exported__
![styled-mode-color-loss](https://github.com/highcharts/highcharts/assets/598148/d6ccc8ec-26dc-4e3e-a799-fe9b7f4ebd21)

**Comment by hubertkozik** [comment] 2024-05-09 06:37
Closing as duplicate of https://github.com/highcharts/highcharts/issues/16400.

**Closed by hubertkozik** 2024-05-09 06:37 UTC
Labels: Duplicate
