### ISSUE TITLE
Time stamps overlapping  #5163 reopen 

### ISSUE THREAD

**Issue by sanjaykanani** [highcharts/highcharts#7036] opened 2017-08-03 07:19 UTC
I am getting issue in highstock date type chart. its overlaping x-axis label at the end.

check below link;
  ```
  Highcharts.stockChart('container', {
        chart: {
            alignTicks: false
        },

        rangeSelector: {
            selected: 1
        },

        title: {
            text: 'AAPL Stock Volume'
        },
 yAxis: {
                                        offset: 0,
                                        opposite: false
                                    },
        series: [{
            type: 'column',
            name: 'AAPL Stock Volume',
            data: [[992908800000,3],[993427200000,1],[993513600000,1],[993600000000,4],[994291200000,1],[994636800000,2],[994723200000,1],[995328000000,4],[995500800000,1],[995587200000,1],[995846400000,1],[996019200000,3],[996796800000,2],[996883200000,1],[997660800000,2],[997747200000,6],[997920000000,1],[998611200000,1],[999043200000,3],[999648000000,1],[999734400000,2],[999820800000,1],[1000080000000,2],[1000252800000,1],[1001376000000,2],[1001548800000,1]],
            dataGrouping: {
                units: [[
                    'week', // unit name
                    [1] // allowed multiples
                ], [
                    'month',
                    [1, 2, 3, 4, 6]
                ]]
            }
        }]
    });
});
```
[http://jsfiddle.net/o04fh8kq/1/](http://jsfiddle.net/o04fh8kq/1/
)
after load change zoom button you will get overlapped label.
![overlap](https://user-images.githubusercontent.com/29813892/28910319-ee1a2d92-7849-11e7-82b6-449e6faac691.png)

**Comment by KacperMadej** [comment] 2017-08-03 12:12
Thank you for the demo @sanjaykanani

Here's a minimal and automated demo: http://jsfiddle.net/t4kqfmrq/

**Comment by sanjaykanani** [comment] 2017-08-25 05:49
Hi,
any update for this bug ? 
Please provide solution for this issue if any.

**Comment by pawelfus** [comment] 2017-08-30 08:18
It looks like `xAxis.ordinal` is the culprit here. When disabled it works fine: http://jsfiddle.net/t4kqfmrq/1/ 

Possible workaround it to use `xAxis.minTickInterval`, for example: http://jsfiddle.net/o04fh8kq/3/

**Comment by TorsteinHonsi** [comment] 2017-08-31 12:28
It's a duplicate of #5163, fixed earlier this week.

**Closed by TorsteinHonsi** 2017-08-31 12:28 UTC
Labels: Bug
