### ISSUE TITLE
Multiple Axes with series boosting draw outside axis extents when zooming

### ISSUE THREAD

**Issue by ochristensen** [highcharts/highcharts#17237] opened 2022-05-02 14:44 UTC
#### Expected behaviour
series data does not draw outside the axes with which the series is associated, regardless of boost being enabled

#### Actual behaviour
series data renders outside the expected "clip region" for the axis pair.  turning off boost fixes this issue.

#### Live demo with steps to reproduce
https://jsfiddle.net/zenzizen/o18u4svg/20/

1. zoom any x-y axis pair to get the data to render - this is a related issue (and turning off boost also resolves this)
2. reset zoom
3. in the upper-right "panel", zoom on the 4 central points like so: 
![image](https://user-images.githubusercontent.com/1668393/166252899-28d49059-eef3-4c6b-a5b3-667076c855ed.png)
4. note the data associated with the last x-axis that is _not_ associated with the zoomed y-axis is now drawing outside the axis extents:
![image](https://user-images.githubusercontent.com/1668393/166253433-1ac6cfb3-eaad-491b-bf14-73aeb4143ca3.png)

The same occurs in the y-axes if you pick a region in, say, the third row from the top and the third column as the data will be drawn above (and below) the row.

#### Product version
Highstock latest

#### Affected browser(s)
Chrome, probably others.

**Comment by raf18seb** [comment] 2022-05-04 13:02
Closing as a duplicate of https://github.com/highcharts/highcharts/issues/12554

**Closed** 2022-05-04 13:03 UTC
Labels: Type: Duplicate
