### ISSUE TITLE
Price indicator doesn't work with yAxis crosshair label

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#12025] opened 2019-09-19 12:20 UTC
yAxis.crosshair.label doesn't work together with series.lastPrice (current price indicator).

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/8vrxonpm

#### Product version
7.2.0

#### Affected browser(s)
All

**Comment by pawelfus** [comment] 2019-09-19 12:22
Duplicate of #11480

**Closed by pawelfus** 2019-09-19 12:22 UTC
Labels: Product: Highstock, Type: Bug
