### ISSUE TITLE
ColumnRange chart stacking no longer works since 9.0.0 upgrade

### ISSUE THREAD

**Issue by debrasaunders** [highcharts/highcharts#16657] opened 2021-11-16 12:04 UTC
#### Expected behaviour
Stacked column range columns
http://jsfiddle.net/debra_s/52pw4euv/2/

#### Actual behaviour
Columns are no longer stacked
http://jsfiddle.net/debra_s/x5zyfvk4/8/

#### Live demo with steps to reproduce
Simply update the referenced version of highcharts from 8,2,2 to the latest version and you will see that the stacked column range no longer works.

#### Product version
This worked in 8.2.2 and starts to break after upgrading to 9.0.0

#### Affected browser(s)
All browsers

**Comment by raf18seb** [comment] 2021-11-18 11:07
Hi @debrasaunders!

Closing as a duplicate of https://github.com/highcharts/highcharts/issues/16148, you can find an explanation there and a workaround reverting the changes.

Another solution is to use `series.pointPlacement` along with `series.grouping`, `series.groupPadding` and `series.pointPadding`. Obviously, your columns will not be stacked, but I don't see any difference between your chart in 8.2.2 (seems like your data is already precalculated).
Demo: https://jsfiddle.net/BlackLabel/092v5qnh/

**Closed by raf18seb** 2021-11-18 11:07 UTC
