### ISSUE TITLE
Boost + noData + yChart.max + some data = some data + noData's label 

### ISSUE THREAD

**Issue by nicolomonili** [highcharts/highcharts#9877] opened 2019-01-15 10:56 UTC
With **boost** and **no-data** modules.

#### Expected behaviour

If i set a yChart.max and i have some data on the chart, the "No data to display" label should not appear

#### Actual behaviour

If i set a yChart.max and i have some data on the chart, the "No data to display" appear

#### Live demo with steps to reproduce
[https://jsfiddle.net/6gv7Lbt0/4/](https://jsfiddle.net/6gv7Lbt0/4/)

#### Product version
tested on Highcharts 6.2.0 and with the latest version

#### Affected browser(s)
tested on latest version of Google Chrome

**Comment by nicolomonili** [comment] 2019-01-15 10:57
Something similar to [https://github.com/highcharts/highcharts/issues/9052(9052) and
[https://github.com/highcharts/highcharts/issues/6664](6664)

**Comment by sebastianbochan** [comment] 2019-01-15 11:33
Hi @nicolomonili,
Thank you for reporting. The issue is already fixed in the master branch:
- https://jsfiddle.net/BlackLabel/19mcrpaL/

This is the duplicate of https://github.com/highcharts/highcharts/issues/9758

**Closed by sebastianbochan** 2019-01-15 11:33 UTC
