### ISSUE TITLE
Highstock : stacked area chart does not render on regions of intersection among series

### ISSUE THREAD

**Issue by suganya-sk** [highcharts/highcharts#6765] opened 2017-05-25 10:41 UTC
* Chart type - area
* Stacking - normal
* Highstock version used - 5.0.11

https://jsfiddle.net/Lx3jum2n/2/

In the fiddle above, the portion of the chart in which all 3 series intersect is not rendered

(Series 'Three' starts at the left edge of the un-rendered portion; series 'One' and 'Two' end at the right edge of the un-rendered portion)

When connectNulls is true, the region of intersection shows up distorted.

https://jsfiddle.net/6bk6pemq/1/

Similar issues open - https://github.com/highcharts/highcharts/issues/1991, https://github.com/highcharts/highcharts/issues/3327

**Comment by sebastianbochan** [comment] 2017-05-26 09:30
Thank you for the reporting. When we zoom in "empty" space or hover there, points are visible.

Updated:
- https://jsfiddle.net/2kxdfm8L/
- https://jsfiddle.net/rdmgyzz1/

![series](https://cloud.githubusercontent.com/assets/2115686/26489206/bff987c4-4206-11e7-90d1-60de426b7101.gif)

**Comment by suganya-suvadi** [comment] 2017-05-30 07:21
@sebastianbochan, thanks for the quick response! Unfortunately, "percent" stacking does not work out too great for my usecase; any chance this can be fixed in the near future?

**Comment by pawelfus** [comment] 2017-06-09 15:03
It is directly connected to the `dataGrouping` feature, when disabled works fine: https://jsfiddle.net/2kxdfm8L/1/

Minimized example: https://jsfiddle.net/2db1os4h/2/

I think it's the same issue as #4874 - one of the series has dataGrouping turned on (left) and the second one doesn't have (right). If we reverse series (series with more points is now the first one) it works fine: https://jsfiddle.net/2db1os4h/3/

**Comment by SebaEnaMor** [comment] 2017-09-06 11:16
Hi,
in Highstock JS v5.0.14 (2017-07-28) this issue is still occurs.
Initial loaded data - on some range the ploted area is missing (from 5 to 10 Aug.):
![1](https://user-images.githubusercontent.com/28860652/30108738-c05dee78-9303-11e7-830e-6a9f229f1a45.PNG)

When I zoom in some range, the area is not filled coninously (white bars shouldn't be there):
![2](https://user-images.githubusercontent.com/28860652/30108845-4f063e28-9304-11e7-92f2-a4fafb7a87fb.PNG)

After setExtremes chart is loading more detailed data by getJSON. 
Note: the datetime axis have data with some interval (ie. 3 minutes, depends on range time). When I disable stacking "normal" or change series type from "area" to "line", the problem isn't occuring.

I need `stacking "normal"` functionality, so it would be great if somebody provide me some workaroud or solve issue (mostly expected).

**Comment by SebaEnaMor** [comment] 2017-09-06 13:18
It looks that method `connectNulls: true` solved my issue. But I'm wondering why? The data comes from getJSON is continous and in place where was rendered a gap there wasn't be null's.

**Comment by pawelfus** [comment] 2017-09-07 08:54
Hi @SebaEnaMor 

It is hard to guess what is wrong with your case without seeing it live. Have you tried to disable `dataGrouping` to make sure if it is the same issue?

Thank you for sharing the workaround!

**Comment by SebaEnaMor** [comment] 2017-09-08 09:05
Well... My hapiness has gone. Of course when one problem has been solved the another one has become.
The `connectNulls: true` is ... connecting the nulls, so here is what I am expecting:
![1](https://user-images.githubusercontent.com/28860652/30159942-a5c92c2c-93ca-11e7-8396-19e1c153a6f9.PNG)

And here is what I am getting, when the `connectNulls` is set to `true`:
![2](https://user-images.githubusercontent.com/28860652/30159967-b9ba51a2-93ca-11e7-9e74-69e6299d58fa.PNG)

The method `dataGrouping` isn't changing anythig. Actually it is set `enabled: false`.

I've made jsfiddle (https://jsfiddle.net/0ga7ju9d/) with code where You can see this issue. Please use buttons below chart:
Zoom-1: you can see a thin white holes in area chart. The blue line is continous - this prove that issue occures on `area` chart type only.
Zoom-2: again some thin white holes in area with blue line continous.
Click again in 'Zoom-1' - now the white holes disapeared, but there is a new bigest one between 9th and 10th of August. Move your mouse pointer into this area and you can see the tooltip with data points.

In JS code snippet you can find the data values given to the chart.

**Comment by pawelfus** [comment] 2017-09-08 10:38
Thank your for the demo!

Just a side note: when using `setData()` multiple times, redraw the chart only once on the last `setData()`. For example:

```
series[0].setData(data1, false);
series[1].setData(data2, false);
...
series[N].setData(dataN);
```

Actually, it fixes issue in your demo: https://jsfiddle.net/0ga7ju9d/1/ - could you confirm?

**Comment by SebaEnaMor** [comment] 2017-09-08 11:17
Works like a charm! :rocket: :thumbsup:
:beer: for You :smile:

**Comment by Gunyon** [comment] 2020-02-20 15:12
in my case the problem was because of summertime
![highchart-summertime](https://user-images.githubusercontent.com/15362486/74947777-08a73680-5404-11ea-99f4-dc201a405720.png)

**Comment by pawelfus** [comment] 2020-02-21 09:53
Could you attach a demo of the issue @Gunyon ? Thanks!

**Comment by Gunyon** [comment] 2020-02-22 13:11
Here is the demo: 
[https://jsfiddle.net/nyon/h3s5kpad/40/](url)

**Comment by pawelfus** [comment] 2020-02-24 10:02
Thanks for the demo @Gunyon 
I think this is expected behaviour. Your generated dataset has different x-values for the given range, so we can not stack those. For example `1598310000000` is available in first dataset, while the second one has only `1598306400000` and `1598392800000`. 

In your case, forcing dataGrouping resolves the issue, for example if hour details are not that important, group points into one day timespans: https://jsfiddle.net/BlackLabel/m7f9w1yx/

**Comment by raf18seb** [comment] 2021-05-04 22:56
+1

**Comment by kaeruB** [comment] 2021-05-05 06:05
In my case, forcing dataGrouping resolves the issue but the performance on zoomed data is too bad (I have multiple series with a huge number of data points to display). Is there a different solution?

Problem is shown here [https://github.com/highcharts/highcharts/issues/15609] (I'm sorry for duplicating the issue!) but I put there only 3 series so you won't see the performance problem.

I understand that the problem occurs in a scenerio described on the picture
![holes](https://user-images.githubusercontent.com/33574996/117100919-509a4b00-ad75-11eb-8ed7-cfc1c5330587.jpg)
so both series have to have exactly same timestamps to avoid the holes. 
Indeed, if I modify the series as follows: 
_if there is a missing timestamp in a series that is present in another series - add a fake datapoint with 0 value_ 
it also solves the issue but fakes the data (thus, I cannot use it in my case but it might be useful for someone else:)

 I would be grateful for a better solution idea than forcing dataGrouping or faking the data.

**Comment by raf18seb** [comment] 2021-05-05 11:16
@kaeruB seems like `dataGrouping.forced` doesn't always resolve the issue: 
![dataGrouping forced area](https://user-images.githubusercontent.com/23310742/117133008-f82e7200-ada3-11eb-995a-7d2756d443e0.gif)

Unfortunately, we don't have any workaround for it at this moment.

**Comment by kaeruB** [comment] 2021-05-05 13:25
@raf18seb thanks for your assistance!
Is there a small chance that the issue will be resolved in the near future?

**Comment by raf18seb** [comment] 2021-05-05 13:31
@kaeruB we'll discuss it at our next prioritization meeting.

**Comment by raf18seb** [comment] 2021-05-05 14:44
It seems the issue is gone when we set the same `dataGrouping.units` for all the series: https://jsfiddle.net/BlackLabel/qy1zLo8d/

**Closed** 2021-06-17 09:26 UTC
Labels: E: 20, Product: Highcharts Stock, Status: Reviewer Approved, Type: Bug
