### ISSUE TITLE
【v8.0.4,v8.1.0,v8.1.2bug】:line reflow wrong，when change chart width or height

### ISSUE THREAD

**Issue by wjhcc2018** [highcharts/highcharts#13968] opened 2020-07-29 08:14 UTC
#### Expected behaviour
when change chart width or height,line can render right
![image](https://user-images.githubusercontent.com/6789138/88773007-24cdb180-d1b4-11ea-9211-fe056ddfabb6.png)

### **but it's works fine with v8.0.2** 

**right picture**
![image](https://user-images.githubusercontent.com/6789138/88773043-33b46400-d1b4-11ea-86dc-8f95f31a44c3.png)
**wrong picture**
![image](https://user-images.githubusercontent.com/6789138/88773081-43cc4380-d1b4-11ea-9f95-811c4b38840c.png)
![image](https://user-images.githubusercontent.com/6789138/88774251-ca355500-d1b5-11ea-80ca-a0bd2f05f8e7.png)
![image](https://user-images.githubusercontent.com/6789138/88774270-ce617280-d1b5-11ea-9092-2ac44fbcec62.png)
![image](https://user-images.githubusercontent.com/6789138/88774319-dc16f800-d1b5-11ea-9302-caad0d14b82a.png)
![image](https://user-images.githubusercontent.com/6789138/88774340-e0431580-d1b5-11ea-9925-31129352909a.png)

#### Product version

   **"highcharts": "8.1.0",
    "highcharts-3d": "^0.1.7",
    "highcharts-grouped-categories": "^1.1.3",
    "highcharts-regression": "^2.0.1",
    "highcharts-vue": "^1.3.5",**
#### Affected browser(s)
正在更新 Google Chrome
版本 83.0.4103.116（正式版本） （64 位）

**Comment by pawelfus** [comment] 2020-07-29 10:38
Hi @wjhcc2018 

Thanks for reporting the issue. This is duplicate of #13751 

PS: `"highcharts-3d": "^0.1.7",` -> This package is deprecated and we are not the authors, please don't use it.

PS2: Please, always include `Live demo with steps to reproduce`.

**Closed by pawelfus** 2020-07-29 10:38 UTC
