### ISSUE TITLE
Bug in stackLabels position

### ISSUE THREAD

**Issue by balkarov** [highcharts/highcharts#8314] opened 2018-05-10 08:30 UTC
Wrong stackLabels  position when chart title disable.
Screenshot:
![wrong2](https://user-images.githubusercontent.com/6030335/39860292-76132e60-5445-11e8-8527-1fe483e3d041.png)

#### Expected behaviour
Position in center

#### Actual behaviour
Wrong position

#### Live demo with steps to reproduce
https://jsfiddle.net/zp17wvox/

#### Product version
Highcharts version 6.1.0

#### Affected browser(s)
Chrome 66.0.3359.139

**Comment by pawelfus** [comment] 2018-05-10 10:54
Hi @balkarov 

Thanks for reporting! This is bug, already fixed on our master branch: https://jsfiddle.net/BlackLabel/zp17wvox/1/

Closing as duplicate of #8187

**Closed by pawelfus** 2018-05-10 10:54 UTC

**Comment by balkarov** [comment] 2018-05-10 11:04
@pawelfus thank you!
Tell me please when you release new version?

**Comment by pawelfus** [comment] 2018-05-10 11:44
@balkarov - we don't have ETA for v6.1.1. Releases are every month or two, so I would expect next release within a few weeks.
