### ISSUE TITLE
Font not rendered in the exprted server

### ISSUE THREAD

**Issue by agaddale** [highcharts/highcharts#5398] opened 2016-06-13 14:34 UTC
![image](https://cloud.githubusercontent.com/assets/12751264/16011167/e5e2b652-31a1-11e6-9964-7ac5c834a8ad.png)

Can somebody please help why is this exported chart not rendered properly for the labels, legends ....

**Comment by KacperMadej** [comment] 2016-06-13 15:19
Please add a demo in JSFiddle. Could you provide information about what font / language / character set is this?

**Comment by jon-a-nygaard** [comment] 2016-06-30 06:29
Closing this since we can not reproduce the issue, and it is pending a reply. Should anyone have further information about the issue, please comment and reopen.

**Closed by jon-a-nygaard** 2016-06-30 06:29 UTC
Labels: Cant reproduce, Pending reply
