### ISSUE TITLE
Heatmap: Append new data rows breaks chart after 1000 cells added

### ISSUE THREAD

**Issue by andi1984** [highcharts/highcharts#6214] opened 2017-01-06 12:25 UTC
#### Expected behaviour
Appending new data rows should also work for more than 1000 cells in the heatmap.

#### Actual behaviour
Chart gets completely broken and some weird numbers appearing as labels and the chart is completely gone.

This isn't happening when I prepend my data rows at the beginning. So I assume there is definitely some issue in Highcharts there.

#### Live demo with steps to reproduce
http://codepen.io/andi1984/pen/ygNyay

So when you add in the codepen more than _250_ data rows with _4_ columns you can see the chart is broken.

#### Affected browser(s)
All

**Comment by andi1984** [comment] 2017-01-06 12:45
It seems to be related to #5568 as disabling `turboThreshold` fixes the issue for me, so I guess this is a bug also?

**Comment by pawelfus** [comment] 2017-01-10 11:51
Thank you for reporting this issue. It's a duplicate of #3765 - as you found out, it's caused by `turboThreshold` limitation.

**Closed by pawelfus** 2017-01-10 11:51 UTC
