### ISSUE TITLE
Min/Max yAxis not working correctly in Highcharts

### ISSUE THREAD

**Issue by hoangthau** [highcharts/highcharts#4773] opened 2015-11-26 04:07 UTC
I've 2 yAxis in demo, I set min/max value for both yAxis is min of 0, max of 200. But they don't work correctly. They are applied 250 for both.

Here is the demo: http://jsfiddle.net/t04b3gjj/7/

**Comment by pawelfus** [comment] 2015-11-26 10:25
This is specific case, when `alignTicks` fails, so workaround is to set `alignTicks: false`, see: http://jsfiddle.net/t04b3gjj/8/

Duplicate of #4580

**Closed by pawelfus** 2015-11-26 10:25 UTC

**Comment by hoangthau** [comment] 2015-11-26 11:04
Hi @pawelfus,

I think I want to set `alignTicks: true`. We only resolve this problem by `alignTicks: false`, right ?
Could you give me some workarounds when I still want to `alignTicks: true`, please ? 

 Thanks so much.

**Comment by pawelfus** [comment] 2015-11-26 11:19
I think for that one certain case, when both axes have exactly the same min and max, you can disable `alignTicks` option. Or disable `alignTicks` option always, but additionally disable grids on one of the yAxis.
