### ISSUE TITLE
Pie charts with hover disable trying to highlight some slice

### ISSUE THREAD

**Issue by Cligor** [highcharts/highcharts#17317] opened 2022-05-23 19:51 UTC
#### Expected behaviour

If hover is disabled on a pie chart, when hovering a piece, nothing happens

#### Actual behaviour
If hover is disabled on a pie chart, the slice option is false, and the selected option is false, when hovering a piece, the entire chart will be opaque like that:

![image](https://user-images.githubusercontent.com/22886741/169894483-94d60064-3f46-4857-a695-ee3005cf33b8.png)

Before the upgrade to 10.1.0, I used 6.2.0 and was ok.

#### Live demo with steps to reproduce

https://jsfiddle.net/cligor/4Lgqn982/7/

#### Product version

Highcharts Version: 10.1.0

#### Affected browser(s)
Chrome v101.0.4951.54
Firefox v100.0.2
Edge 101.0.1210.53

**Comment by karolkolodziej** [comment] 2022-05-24 12:00
Thank you for contacting us!

Nothing happens because the hover state is disabled by this:
```            
            states: {
            	hover: {
              	enabled: false
              }
            }        
```

Please check how it works with that state enabled- [demo](https://jsfiddle.net/BlackLabel/v2je4pmy/)

**Comment by karolkolodziej** [comment] 2022-05-24 12:03
There is also one additional state called `inactive`. 
When you disable it you get the desired effect. 
Is that what you have been looking for or am I missing something?

Demo: https://jsfiddle.net/BlackLabel/ek523079/

**Comment by karolkolodziej** [comment] 2022-05-24 14:07
Great! 
Closing as it is not a bug ;)

**Closed** 2022-05-25 12:46 UTC
Labels: Type: Not a bug
