### ISSUE TITLE
TreeMap chart is not formatting the tooltip properly

### ISSUE THREAD

**Issue by xavierfourrage** [highcharts/highcharts#18292] opened 2023-01-13 10:12 UTC
#### Expected behaviour
In the tooltip box, the text should break a line when reaching the defined width of the tooltip div tag.
useHTML:true

#### Actual behaviour

the text goes out of the div tag and ignores the width of the div that it's part of. 

#### Live demo with steps to reproduce
[Large tree map - JSFiddle - Code Playground](https://protect-eu.mimecast.com/s/BXaOC1W6WHM0WD4upQcM1?domain=jsfiddle.net)

#### Product version
Highcharts-9.0.1

#### Affected browser(s)
All browsers
![2023-01-13 11_11_12-Window](https://user-images.githubusercontent.com/81828582/212294875-f4219901-2967-4a88-9340-012786b44bc3.png)

**Comment by pawellysy** [comment] 2023-01-13 18:33
Hello, @xavierfourrage, thanks for reaching out to us!
This is not a bug, just the way, that HTML works. The CSS property [overflow](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow)  describes what happen, in this example. 
Here is the demo, with `overflow: hidden`

Closing, as `not a bug`.

**Closed by pawellysy** 2023-01-13 18:34 UTC
Labels: Type: Not a bug
