### ISSUE TITLE
Wordcloud reflow is extremely slow

### ISSUE THREAD

**Issue by Delboyeire** [highcharts/highcharts#7932] opened 2018-02-27 12:31 UTC
We are using wordcloud with react and are utilising parentResized function to trigger reflow() on a wordcloud.
#### Expected behaviour
we would expect the words to just resize with the container

#### Actual behaviour
Seems the word positioning is being recalculated each time this function is called which is causing a serious lag. it would be great to disable this somehow. 

Have also tried using setSize which is every bit as bad

#### Product version
highcharts@^6.0.7

**Comment by KacperMadej** [comment] 2018-02-27 15:31
Hi @Delboyeire 

Word cloud chart works fine when used without React.
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/wordcloud/
Resize is handled well and there's no lag.

Please add a live demo showing your problem.
This might be caused by your data (it's size) and / or by the used React components.

**Comment by jon-a-nygaard** [comment] 2018-06-18 11:59
Closing this issue as we are unable to reproduce. Should anyone have more information on the subject please give us a comment.

**Closed by jon-a-nygaard** 2018-06-18 11:59 UTC
Labels: Cant reproduce, Pending reply
