### ISSUE TITLE
Column series doesn't exit boost mode when whole chart is boosted with `seriesThreshold`

### ISSUE THREAD

**Issue by ravindUwU** [highcharts/highcharts#21787] opened 2024-09-05 05:16 UTC
#### Expected behaviour

The SVG renderer takes over from boost when zoomed in close enough.

#### Actual behaviour

When the whole chart is boosted (`seriesThreshold` met) instead of the individual series, the SVG render doesn't seem to take over when zoomed in.

I'm unsure if this is an expected side effect of using chart-level boosting, of it's a bug. It doesn't seem to be documented at https://www.highcharts.com/docs/advanced-chart-features/boost-module so I'm assuming the latter 💁.

#### Live demo with steps to reproduce

https://stackblitz.com/edit/ravinduwu-misc-2024-09-05-highcharts-zoom-unboosting?file=index.html

Notice how,
- ✅ The 2nd chart (series-level boosted & zoomed in) is not boosted because the SVG renderer has taken over.
- ❎ The 3rd chart (chart-level boosted & zoomed in) is still being boosted .
- 
  <details>
  <summary>Screenshot</summary>
  
  ![](https://github.com/user-attachments/assets/327ae611-c0e3-4e20-83cb-2aec6345e65d)
  
  </details>

#### Product version

Highcharts `11.4.8`

#### Affected browser(s)

Firefox 130, Edge 128

**Comment by hubertkozik** [comment] 2024-09-05 07:27
Hi @ravindUwU! This behaviour is documented under "Caveats" header: https://www.highcharts.com/docs/advanced-chart-features/boost-module#caveats:

> The largest caveat is that rectangles for column and bar charts are always drawn as a single 1 pixel wide line. This will likely not be the desired outcome when zoomed in to the level where each column/bar is visible as an individual entity. Thus, column and bar charts are more suited to series-level boosting.

Unfortunately, at this moment there is nothing we can do with it, so I'll close it as not a bug.

**Closed by hubertkozik** 2024-09-05 07:27 UTC
Labels: Type: Not a bug

**Comment by ravindUwU** [comment] 2024-09-05 07:29
Thanks for confirming @hubertkozik; not sure how I missed that 😅.
