### ISSUE TITLE
Firefox chart redraw issue with boost module 

### ISSUE THREAD

**Issue by mcsgdtest** [highcharts/highcharts#17184] opened 2022-04-14 10:00 UTC
#### Expected behaviour
Using Firefox chart should redraw normally after zoom on X axis when using boost module and more than 5000 points

#### Actual behaviour
when configuring a line series with more than 5000 points and using boost module, after zoom on X remain artefacts on the chart with multiple series.
Problems occur only with Firefox (we use version 99.0.1)
Problem can be shown in the attachment image and replicated on highcharts live webpage 
https://www.highcharts.com/blog/tutorials/highcharts-high-performance-boost-module/
zooming on X after 2-3 levels of zoom

#### Live demo with steps to reproduce

https://www.highcharts.com/blog/tutorials/highcharts-high-performance-boost-module/
https://jsfiddle.net/5bvLgs5w/1/

![immagine](https://user-images.githubusercontent.com/41287829/163362049-58e563a5-0d60-4001-8c61-1f011952be5f.png)

#### Affected browser(s)
FIREFOX

**Comment by raf18seb** [comment] 2022-04-14 14:33
Closing as a duplicate of https://github.com/highcharts/highcharts/issues/17182

**Closed by raf18seb** 2022-04-14 14:33 UTC
