### ISSUE TITLE
xAxis labels overlap the tooltip when xAxis.labels.useHTML is true

### ISSUE THREAD

**Issue by omnibrain** [highcharts/highcharts#14086] opened 2020-08-19 12:41 UTC
#### Expected behaviour

Tooltip always overlaps the axis labels. Like this:

![image](https://user-images.githubusercontent.com/2551508/90634931-d0ed4000-e228-11ea-8d04-3baa3f117ad0.png)

#### Actual behaviour

Axis labels overlap the tooltip when xAxis.labels.useHTML is true. Like this:

![image](https://user-images.githubusercontent.com/2551508/90634999-e4001000-e228-11ea-9a6d-14d2d23a6bc7.png)

#### Live demo with steps to reproduce

Reproduction of the bug: https://jsfiddle.net/wuczy57a/33/

You will notice the bug when hovering over the bar at "16.67% - 33.33%" (the largest bar). If you change xAxis.labels.useHTML to `false` the tooltip works as expected and overlaps the axis label.

#### Product version

Highcharts v8.1.2 (2020-06-16)

#### Affected browser(s)

Tested in current Versions of Chrome, Firefox and Safari. All browsers are affected.

**Comment by sebastianbochan** [comment] 2020-08-20 08:21
Hi @omnibrain,
This is expected result when some elements are rendered in SVG (e.g. tooltip's background) and others in HTML (dataLabel). See docs: https://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting

Im closing as duplicate of https://github.com/highcharts/highcharts/issues/12236

**Closed by sebastianbochan** 2020-08-20 08:21 UTC
Labels: Type: Duplicate

**Comment by omnibrain** [comment] 2020-08-20 09:45
But this also happens when I use HTML tooltips:

**Comment by pawelfus** [comment] 2020-08-20 10:25
See my response in #12236

**Comment by arpit-0310** [comment] 2024-02-19 06:49
Add tooltip.outside to true, It will fix the issue.
