### ISSUE TITLE
gapSize of 1 in series connects data that it shouldn't

### ISSUE THREAD

**Issue by karolyi** [highcharts/highcharts#5276] opened 2016-05-02 11:36 UTC
Hey,

I have a chart setup with `gapSize` 1, and it connects points in the series where it shouldn't. I created a jsfiddle to show how it's reproducible. If you move the navigator around, you'll see that the series that contains 1 point in the present, and lots in the past, connects the points with those in the present, being out of the view. Also, moving the navigator around will show you how it's completely broken.

Hoping to get a quick fix for that.
#### Expected behaviour

Don't connect points that are not visible with `gapSize` 1 and not adjacent.
#### Actual behaviour

Described above.
#### Live demo of the issue

http://jsfiddle.net/3Lzd7wq9/1/
#### Steps to reproduce the behaviour

Use a series where you have 1 point in the present (but only one), and lots in the past, not in viewport.
#### Affected browser(s)

Chrome, FF, not tested with other ones but probably it's browser irrelevant.

**Comment by pawelfus** [comment] 2016-05-05 09:12
Thank you for reporting. It looks like connected to #4747.

**Comment by TorsteinHonsi** [comment] 2016-07-22 11:07
Thanks. Apparently the new data set has data for sundays, so we need to set the gapSize to 1 in order to display.

**Comment by pawelfus** [comment] 2018-03-28 16:00
This issue is resolved by setting [`gapUnit`](https://api.highcharts.com/highstock/series.line.gapUnit), demo: http://jsfiddle.net/BlackLabel/3Lzd7wq9/2/

Actually it's a duplicate of #6645

**Closed by pawelfus** 2018-03-28 16:00 UTC
Labels: Highstock
