### ISSUE TITLE
No explanation of how to get a chart object in the series.events in the Highcharts docs.

### ISSUE THREAD

**Issue by jakubSzuminski** [highcharts/highcharts#18304] opened 2023-01-16 11:34 UTC
#### Expected behaviour
There should be a clear explanation how a user can get to `chart` with `this.chart` in `series.events` functions.

#### Actual behaviour
In the Highcharts API, there is no explanation about the context of the `series.events` functions like `series.events.legendItemClick`. Users on forum often ask about, for example, how to get data from series 1 after a legend has been clicked on series 0. 

#### Product version
Highcharts 10.3.2

**Comment by pawellysy** [comment] 2023-01-17 09:43
Hello @jakubSzuminski, 
When you visit [the API page of `legendItemClick`](https://api.highcharts.com/highcharts/series.line.events.legendItemClick), you can see the interface [`SerlesLegendItemClickCallbackFunction`](https://api.highcharts.com/class-reference/Highcharts#.SeriesLegendItemClickCallbackFunction), which specifies, that `this` is a `Highcharts.Series`, so it is specified. 

Closing since this is not a bug.

**Closed by pawellysy** 2023-01-17 09:43 UTC
