### ISSUE TITLE
Chart extremes affected by series with no data

### ISSUE THREAD

**Issue by gasnier** [highcharts/highcharts#5058] opened 2016-02-18 14:38 UTC
I have 2 y axis and one of them is linked to a serie that has no data.
in that case the extremes of the first axis is not correctly calculated.

see :
http://jsfiddle.net/83ko0bp0/

In this jsfiddle you can see that axis 1 goes from -10 to 40 when the last serie (linked to the axis 2) is present.
if you remove the last serie (click remove last serie button), the axis 1 goes from -5 to 30 which is what is expected.
the last serie that has no data should not impact the extremes calculation.

**Comment by oysteinmoseng** [comment] 2016-02-19 09:55
Thank you for reporting. This only seems to be an issue with vertical legends aligned to the sides of the chart.

**Comment by gasnier** [comment] 2016-02-19 14:34
No, it is not only linked to the legend.
I can reproduce this without the legend on the right if I change the data :
http://jsfiddle.net/vdz604L7/1/

**Comment by TorsteinHonsi** [comment] 2016-02-26 10:18
It is because of the `chart.alignTicks` default option. The existance of a seconday Y axis makes the tick layout different, because it is now fixed at a certain number of ticks. See [connected tickAmount issues](https://github.com/highcharts/highcharts/search?q=alignTicks&type=Issues&utf8=%E2%9C%93).

**Comment by gasnier** [comment] 2016-02-29 08:47
I know it is because of align ticks but would it be possible to ignore the axis when it has no serie with data ?

**Comment by TorsteinHonsi** [comment] 2016-02-29 11:32
Yes, it should. We discussed that in #4442. I'm closing this thread, it's actually a duplicate of what we discuss in the end.

**Closed by TorsteinHonsi** 2016-02-29 11:32 UTC
Labels: Bug

**Comment by gasnier** [comment] 2016-04-13 14:43
If someone is interested, here is a patch for my problem:
http://jsfiddle.net/vdz604L7/3/

In getSeriesExtremes I set axis.hasVisibleSeries to false if there is no data
In alignToOthers I don't process axis if it has no data

**Comment by TorsteinHonsi** [comment] 2016-04-14 07:37
Thanks for the contribution, this is very interesting. I'll test it as soon as we've got the next maintenance out.
