### ISSUE TITLE
[Bug]Flag label occurs when other content's tooltip 

### ISSUE THREAD

**Issue by champion688** [highcharts/highcharts#10822] opened 2019-05-27 06:55 UTC
#### Expected behaviour
Flag label content should be under tooltip

#### Actual behaviour
Flag label content appears above the tooltip and visible

#### Live demo with steps to reproduce

https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/flags-general/
#### Product version

V7.1.1
#### Affected browser(s)
Chrome

**Comment by champion688** [comment] 2019-05-27 06:57
![image](https://user-images.githubusercontent.com/20540386/58401147-a9441200-808f-11e9-8835-1b1324a3d9fe.png)

**Comment by champion688** [comment] 2019-05-27 07:06
Is it a bug?

**Comment by sebastianbochan** [comment] 2019-05-27 08:06
Hi @champion688,
When I run our default demo, flags are hidden when tooltip is visible. Could you update the demo with your current code to show the problem? I guess that it can be a problem with using HTML, but need to ensure.

**Comment by champion688** [comment] 2019-05-27 08:33
Hi @sebastianbochan,
Thanks, yes, I set the value useHTML to true.
https://jsfiddle.net/1pn52akv/

**Comment by sebastianbochan** [comment] 2019-05-27 12:26
Hi @champion688,
Thank you for your feedback. This is not a bug. HTML is rendered on top of the SVG, so tooltip will be below the HTML images. You can read details in our [docs](https://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting)

Im closing this bug as a duplicate of https://github.com/highcharts/highcharts/issues/7172

**Closed by sebastianbochan** 2019-05-27 12:26 UTC
Labels: Status: Pending reply

**Comment by champion688** [comment] 2019-05-28 01:53
@sebastianbochan,
Thanks.
