### ISSUE TITLE
Zones border after call of setExtremes function

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#5811] opened 2016-10-10 15:36 UTC
#### Behaviour
In situation when series data is set after chart creation and before yAxis.setExtremes() function call, border color of all zones is the same as the color of the last zone border.

#### Live demo with steps to reproduce
http://jsfiddle.net/a5gmj3ex/2/

**Comment by oysteinmoseng** [comment] 2016-10-11 10:11
Duplicate of #5810

**Closed by oysteinmoseng** 2016-10-11 10:11 UTC
Labels: Bug, Duplicate
