### ISSUE TITLE
Titles starting with `<` and ending with `>` are not shown

### ISSUE THREAD

**Issue by ipavlic** [highcharts/highcharts#12701] opened 2020-01-01 16:51 UTC
#### Expected behaviour

Titles starting with `<` and ending with `>` are properly shown

#### Actual behaviour

Titles are not shown, likely due to some escaping/sanitizing

#### Live demo with steps to reproduce
https://jsfiddle.net/h74et1cx/4/

#### Product version
Highcharts 8.0.0

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment] 2020-01-02 08:47
Hi @ipavlic ,
Thank you for reporting about the problem.

**Workaround**
You can use the HTML entities `&lt`; or `&gt;` instead of < >.

**Demo:**
- https://jsfiddle.net/BlackLabel/7h01sbad/

_Internal note_
Similar to the topic: #8892 / https://github.com/highcharts/highcharts/issues/10581

**Comment by pawelfus** [comment] 2020-03-19 10:42
Actually it's a duplicate of #10581 - please check the explanation and solution in the ticket.

**Closed by pawelfus** 2020-03-19 10:42 UTC
Labels: Status: Has workaround, Type: Bug

**Comment by sebastianbochan** [comment] 2020-03-19 14:37
I missed that! Thanks Pawel!
