### ISSUE TITLE
Chart should be rendered without any white borders/patches inside charts

### ISSUE THREAD

**Issue by apal-apttus** [highcharts/highcharts#7765] opened 2018-01-31 10:34 UTC
#### Expected behaviour
Chart should be rendered without any white borders/patches inside charts

#### Actual behaviour
Some white borders/patches are coming up for pie and column chart after resizing the chart's container. I used following function .redraw() after resizing chart's container height and width but still this issue is present.

#### Live demo with steps to reproduce

![image](https://user-images.githubusercontent.com/35995133/35617806-1fff1ac8-069f-11e8-8aef-c5fb1f77f9c7.png)

![image](https://user-images.githubusercontent.com/35995133/35617880-58605490-069f-11e8-9ee2-20c5d026494a.png)

#### Product version
Highcharts 6.0.2

#### Affected browser(s)
Any browsers, mainly Google Chrome v63.0

**Comment by pawelfus** [comment] 2018-01-31 10:43
Hi @apal-apttus 

Thank you for reporting these issues. Pie chart issue should be already fixed on our master branch: http://github.highcharts.com/highcharts.src.js (duplicate of #7681)

Regarding columns, please recreate issue in jsFiddle, simple example works fine: http://jsfiddle.net/eu59etvo/

**Comment by pawelfus** [comment] 2018-03-16 15:11
Closing due to inactivity. @apal-apttus if you will be able to recreate the issue, let us know we will reopen this ticket.

**Closed by pawelfus** 2018-03-16 15:11 UTC
Labels: Cant reproduce, Pending reply
