### ISSUE TITLE
Stacked Column Chart - the total value calculated wrongly.

### ISSUE THREAD

**Issue by renardkabza** [highcharts/highcharts#16619] opened 2021-11-09 10:36 UTC
#### Expected behaviour
Your original demo of the stacked column chart taken from 
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/column-stacked
cumulates correctly samples.

#### Actual behaviour
It ignores the negavite values e.g. the 1st series has 5,  the 2nd one has -2 and the total value is still 5 instead of 3
I have checked the following charts in a stacked mode:
- spline - works, 
- areaspline - works ,
- column - does not work.

#### Live demo with steps to reproduce - a column stacked chart.
https://jsfiddle.net/RenardKabza/qc07Lf8y/2/ 

#### Product version
 Highcharts JS v9.3.1 (2021-11-05) available publicly from https://code.highcharts.com/highcharts.js

#### Affected browser(s)
Chrome Version 95.0.4638.69 (Official Build) (32-bit)

**Comment by raf18seb** [comment] 2021-11-15 16:42
Closing as a duplicate of https://github.com/highcharts/highcharts/issues/5671

**Closed by raf18seb** 2021-11-15 16:42 UTC
