### ISSUE TITLE
waterfall - stacking

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#2280] opened 2013-09-24 12:59 UTC
Stacked waterfall seems to not working.

Example: http://jsfiddle.net/AFjAG/7/

HC 3.0.5

**Comment by sebastianbochan** [comment] 2015-05-13 09:36
+1

**Comment by dmitrygorbenko** [comment] 2016-11-23 11:28
I faced the same issue:
https://jsfiddle.net/DimaGorbenko/rdg5j45h/1/
It's connected to stacking.
Try to remove key
   stacking: "normal"
and you'll get chart.
But I'd like to have stacked version :)

The funny thing is what this chart was working in HC version 4.1.8, but stopped working in 4.2.1.
At least these versions I have and I tested them.
I can do more testing to find exact version which stopped supporting this feature.

What do you think, is it a bug, or broken feature ? Are you going to fix it ? Any plans ? I just need to understand what to do.

Thanks,
Dima

**Comment by pawelfus** [comment] 2016-11-23 12:03
Hi @dmitrygorbenko 

The issue is caused by this commit: 8d8cbee - where stack-indicator was introduced, and we missed this functionality in waterfall. It's not the same issue as the one originally posted. I created a separate issue for it: #6022

Thanks for reporting! Of course, we will fix this.

**Comment by dmitrygorbenko** [comment] 2016-11-23 14:56
hi @pawelfus 

Thank you !
Great to know you are working on this :+1: 
Meanwhile I'll try to use some other chart type.

Dima

**Comment by pawelfus** [comment] 2017-03-24 14:27
Example with the commit above: http://jsfiddle.net/2jLsLwnz/

**Comment by bendenois** [comment] 2017-06-21 09:26
Hi,

Do you know when the fix will be released ?

Thank you.

Benjamin

**Comment by sebastianbochan** [comment] 2017-06-21 11:09
@TorsteinHonsi 
It seems that the commit is only on hc5-fixes and is not merged with master yet. Do we have any plans to do that or is still bugged?

**Comment by TorsteinHonsi** [comment] 2017-06-22 09:11
It is on the master too...

**Comment by sebastianbochan** [comment] 2017-06-22 09:16
You are right, I run my local files which was not up to date.

**Comment by RenaldasK** [comment] 2018-02-28 10:45
Any update on this?

**Comment by TorsteinHonsi** [comment] 2018-03-05 14:33
@pawelfus ?

**Comment by pawelfus** [comment] 2018-03-05 15:18
Basic support for stacking is implemented: negative/positive points are fine: http://jsfiddle.net/2jLsLwnz/

What me miss is support for different amount of points, for example in the original demo, we have only one point for the first series, without isSum/isIntermediate points. That case breaks stacking as we don't create any extra points. Simplified demos with the same amount of points: http://jsfiddle.net/BlackLabel/AFjAG/63/  (replaced with 0-values) and http://jsfiddle.net/BlackLabel/AFjAG/65/ (missing points, problem with lines).

**Comment by TorsteinHonsi** [comment] 2018-03-06 10:29
I added a sample for this, so people can see it can be done: 7ef966fa0b35ca58cecc352244d95f60db61a0b9.

There's also a problem with data labels positions.

**Comment by RenaldasK** [comment] 2018-03-06 19:25
Thanks!

**Comment by RenaldasK** [comment] 2018-04-12 10:51
@pawelfus the charts breaks if you change the first value in the first series to a negative. Go to your JSFiddle [http://jsfiddle.net/2jLsLwnz/](http://jsfiddle.net/2jLsLwnz/) and change the first data value in the first series from 20 to -20. The chart will throw an error and fail to render:

`highcharts.js:25418 Uncaught TypeError: Cannot read property '0' of undefined
    at object.translate (VM86 highcharts.js:25418)
    at object.<anonymous> (VM87 highcharts-more.js:4756)
    at object.obj.(/2jLsLwnz/anonymous function) [as translate] (https://github.highcharts.com/hc5-fixes/highcharts.js:923:16)
    at object.translate (VM86 highcharts.js:29806)
    at object.<anonymous> (VM87 highcharts-more.js:4942)
    at object.obj.(/2jLsLwnz/anonymous function) [as translate] (https://github.highcharts.com/hc5-fixes/highcharts.js:923:16)
    at object.translate (VM87 highcharts-more.js:3380)
    at VM86 highcharts.js:21329
    at Array.forEach (<anonymous>)
    at H.each (VM86 highcharts.js:1698)`

**Comment by pawelfus** [comment] 2018-04-12 10:58
Thanks! I will check this today/tomorrow.

**Comment by RenaldasK** [comment] 2018-04-12 16:20
After a lot trial and error here is what I found: 
it's unable to render the chart if the sum or intermediate sum in the series adds up to a negative total.

Example:
Stacked waterfall with the following data in one of the series will render the chart fine:
`
[
  -20,
  20,
  { isIntermediateSum: true }, 
  30,
  -30,
  { isSum: true }
]
`
Notice how the values before `intermediateSum` add up to 0, as well as the values before isSum add up to 0. However if the negative values are increased even by 1, the library throws an error and fails to render the chart, e.g.:
`
[
  -21,
  20,
  { isIntermediateSum: true }, 
  30,
  -30,
  { isSum: true }
]
`
However if the positive values are increased too, the chart will render fine again, e.g.:
`
[
  -21,
  21,
  { isIntermediateSum: true }, 
  30,
  -30,
  { isSum: true }
]
`

I need to get this working for a client, and any workaround will do. If this cannot be fixed/workaround, I will have to resort to using some "hacky" approach with stacked bar charts to recreate stacked waterfall using invisible bars or something (if that is even possible).

Any help is much appreciated! Thanks!

**Comment by pawelfus** [comment] 2018-04-13 14:56
@RenaldasK Workaround: columnrange is good for this case, simply calculate high+low for each point before rendering series: http://jsfiddle.net/BlackLabel/2jLsLwnz/172/

Still, questionable is position for negative stacks - what should happen to intermediateSum/Sum when values within a series sums up to 0? Should we display just a bar without height (0pixels) or should we render two stacks within one column (one negative and one positive)? Both are reasonable.

*Internal note:*
Issue is a bit more complicated than is seems.. Demos: http://jsfiddle.net/BlackLabel/2jLsLwnz/157/ or http://jsfiddle.net/BlackLabel/2jLsLwnz/156/ - this is result of having two separate stacks (negative and positive) which works fine for all types (and makes sense) but not for waterfall. Honestly, I don't know how stack with points [5, 10, -15] should be rendered. Probably should start from the previous point state and render separate stacks then?

In general, within a stack (stack=points on the same x-position, the same category) values should have the same sign: for example category on a waterfall "taxes" is always negative, the same for "cost of X". If we require this, then we could improve stacking in waterfall.

**Comment by RenaldasK** [comment] 2018-04-13 16:29
@pawelfus Thanks a lot for the workaround! I believe it should suffice for my needs. 

Regarding rendering stacks with negative points, we had the same discussion in our team and it's not clear to us either how they should be rendered, so we ended up asking the client for more details/examples on how those charts should look like. 

I will update the issue if there is a "right" way of rendering them, but to me it sounds like it's a limitation with stacked waterfall charts.

Thanks again for being so prompt!

**Comment by pawelfus** [comment] 2018-04-16 09:32
Thanks! I think the "right" solution is to provide only negative/positive values within a stack.

**Comment by pawelfus** [comment] 2018-04-19 13:42
*Internal note:*
Debugged issue with negative values:

- `point.y` is set for sums after stacks are calculated
- when stacking, `point.y` is used to determine stack positive/negative. However it's undefined, so we use positive stack..

**Comment by pawelfus** [comment] 2018-04-19 14:15
**Workaround:**
Demo: http://jsfiddle.net/BlackLabel/2jLsLwnz/197/

```javascript
(function(H) {
  H.seriesTypes.waterfall.prototype.generatePoints = function() {
    var previousIntermediate = this.options.threshold,
      point,
      len,
      i,
      y;
    // Parent call:
    H.seriesTypes.column.prototype.generatePoints.apply(this);

    for (i = 0, len = this.points.length; i < len; i++) {
      point = this.points[i];
      y = this.processedYData[i];
      // override point value for sums
      // #3710 Update point does not propagate to sum
      if (point.isSum) {
        point.y = H.correctFloat(y);
      } else if (point.isIntermediateSum) {
        point.y = H.correctFloat(y - previousIntermediate); // #3840
        previousIntermediate = y;
      }
    }
  };
})(Highcharts)
```

**Comment by PaulDalek** [comment] 2019-03-25 15:17
A new stacking option (overlap) is available for stacked waterfall series now (https://api.highcharts.com/highcharts/series.waterfall.stacking).

**Closed by PaulDalek** 2019-03-25 15:17 UTC
Labels: Enhancement, In progress
