### ISSUE TITLE
Blank block in the X Axis 

### ISSUE THREAD

**Issue by SMH110** [highcharts/highcharts#16991] opened 2022-02-14 10:46 UTC
Hi 👋,

#### Expected behaviour
Correct weeks numbering 

#### Actual behaviour
Blank block 

#### Live demo with steps to reproduce
![image](https://user-images.githubusercontent.com/16171515/153849483-9d17b6bd-9b8d-4f3a-a7d8-734e0fb70a6a.png)
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/gantt/demo/with-navigation
#### Product version
Highcharts Gantt latest version

#### Affected browser(s)
All

**Comment by karolkolodziej** [comment] 2022-02-14 12:50
Thank you for reporting!

Closing as a duplicate of https://github.com/highcharts/highcharts/issues/15720

**Closed by karolkolodziej** 2022-02-14 12:50 UTC
