### ISSUE TITLE
chart.update fails when hiding navigator and removing series with showInNavigator

### ISSUE THREAD

**Issue by ebencollins** [highcharts/highcharts#21584] opened 2024-07-26 15:49 UTC
#### Expected behaviour
The navigator is hidden and the second line series is removed.

#### Actual behaviour
Error in console, second line series is still visible. Navigator is hidden, but resize does not complete.

```
Uncaught TypeError: t is null
    erase https://code.highcharts.com/stock/highstock.js:8
    addBaseSeriesEvents https://code.highcharts.com/stock/highstock.js:8
    C https://code.highcharts.com/stock/highstock.js:8
    C https://code.highcharts.com/stock/highstock.js:8
    remove https://code.highcharts.com/stock/highstock.js:8
    update https://code.highcharts.com/stock/highstock.js:8
    update https://code.highcharts.com/stock/highstock.js:8
    <anonymous> https://fiddle.jshell.net/_display/?editor_console=true:153
    setTimeout handler* https://fiddle.jshell.net/_display/?editor_console=true:150
[highstock.js:8:4937](https://code.highcharts.com/stock/highstock.js)
    erase https://code.highcharts.com/stock/highstock.js:8
    addBaseSeriesEvents https://code.highcharts.com/stock/highstock.js:8
    C https://code.highcharts.com/stock/highstock.js:8
    forEach self-hosted:157
    C https://code.highcharts.com/stock/highstock.js:8
    remove https://code.highcharts.com/stock/highstock.js:8
    update https://code.highcharts.com/stock/highstock.js:8
    forEach self-hosted:157
    update https://code.highcharts.com/stock/highstock.js:8
    <anonymous> https://fiddle.jshell.net/_display/?editor_console=true:153
    (Async: setTimeout handler)
    <anonymous> https://fiddle.jshell.net/_display/?editor_console=true:150
```

#### Live demo with steps to reproduce
https://jsfiddle.net/9wokn12x/10/

Note: Works as expected when   `showInNavigator: false` on the removed series or if the navigator is already hidden.

#### Product version
Highstock 11.4.6

#### Affected browser(s)
Observed on both Firefox 127 & Chrome 126

**Comment by karolkolodziej** [comment] 2024-07-29 06:34
Hi @ebencollins! 
Thank you for reporting the issue! 

Internal note:
The last working version 11.4.3
Bisected to commit 757f744c93

When [`oneToOne`](https://api.highcharts.com/class-reference/Highcharts.Chart#update) is set to false the issue is not visible- [demo](https://jsfiddle.net/BlackLabel/tkays2ue/)

**Comment by pablorm296** [comment] 2024-07-31 17:10
Downgrading to `11.4.1` solved the issue for me (I tried using `11.4.3`). We're using NextJS and `highcharts-react-official@3.2.1`. I noted the issue last night when upgrading to `11.4.6`.

```
Uncaught TypeError: t is null
    erase highstock.js:8
    destroy highstock.js:8
    destroy highstock.js:8
    destroyElements highstock.js:8
    destroyElements highstock.js:8
    n highstock.js:8
    setTimeout handler*syncTimeout highstock.js:8
    destroy highstock.js:8
    destroy highstock.js:8
    destroy highstock.js:8
    d highcharts-react.min.js:1
    safelyCallDestroy react-dom.development.js:20869
    commitHookEffectListUnmount react-dom.development.js:21051
    invokeLayoutEffectUnmountInDEV react-dom.development.js:24001
    invokeEffectsInDev react-dom.development.js:26852
    legacyCommitDoubleInvokeEffectsInDEV react-dom.development.js:26826
    commitDoubleInvokeEffectsInDEV react-dom.development.js:26816
    flushPassiveEffectsImpl react-dom.development.js:26514
    flushPassiveEffects react-dom.development.js:26438
    commitRootImpl react-dom.development.js:26172
    workLoop scheduler.development.js:256
    flushWork scheduler.development.js:225
    performWorkUntilDeadline scheduler.development.js:534
    EventHandlerNonNull* scheduler.development.js:569
    <anonymous> scheduler.development.js:630
```

**Comment by gamotmohitRELX** [comment] 2024-08-20 07:38
Hi @karolkolodziej 

Downgrade high chart version to 11.4.3 is working in my project. I did try to use version 11.4.7 latest version but facing same issue mansion in above jsfiddle example.

without solving this issue, we can't upgrade high chart latest version. Request for please resolve this issue.

Thank you.

**Comment by karolkolodziej** [comment] 2024-08-20 10:22
This issue is one of the top items on our to-do list. It should be fixed before the next release.

**Closed** 2024-09-30 09:51 UTC
Labels: Product: Highcharts Stock, Type: Regression
