### ISSUE TITLE
tooltip followtouchmove does not work on treemap & other similar series on mobile

### ISSUE THREAD

**Issue by anoosurf** [highcharts/highcharts#19403] opened 2023-07-20 03:05 UTC
Expected behaviour
tooltip.followTouchMove : true  should make the bahaviour of tooltip to follow the finger as the user swipes /drags across the plot area of heatmap/scatter/treemap/bubble series  

Actual behaviour :
Nothing happens, and the tooltip sticks to the previously selected/clicked series item .. until the user clicks another item

Live demo with steps to reproduce

try on a touch device with finger :
ive modified a simple codepen of your demo to include this setting :
https://codepen.io/anuraags/pen/GRwGjqv

Product version
Highhcharts version 11.1

**Comment by karolkolodziej** [comment] 2023-07-21 06:55
Hi @anoosurf! 

Thank you for reporting this issue! 
I was able to recreate it in the XCode simulator with the 10th-generation iPad. 

https://github.com/highcharts/highcharts/assets/57004120/57039e63-6e59-4462-a0ca-091fa40caa8d

**Comment by anoosurf** [comment] 2023-07-21 10:03
thanks for getting back @karolkolodziej  :)

if you noticed the tooltip does not update while dragging /swiping along different items on a heatmap / scatter / treemap/ bubbles series 
and to refresh one has to lift the finger & again tap on the other item to get its own specific tooltip

is there a temporary workaround for this ? or by when could this be rectified ?
thanks a lot

**Comment by karolkolodziej** [comment] 2023-07-25 06:01
Hi @anoosurf!

Unfortunately, for now, I haven't found any workaround. This needs a deeper investigation.

**Comment by anoosurf** [comment] 2023-07-26 05:18
so any idea by when this could be resolved ? it is very important bug to make proper on touch devices.. else we cant use these series types properly.
thank u :)

**Comment by anoosurf** [comment] 2023-07-31 02:13
hi .. any solution on this ? 
it's quite a critical bug.. which makes series scatter / bubbles / heatmaps / treemaps .. etc charts quite unusable on touch devices.. as the user has to click every point individually to se a tooltip rather than an easy dragging along the chart.
please someone assist ASAP
thank u

**Comment by karolkolodziej** [comment] 2023-08-01 06:37
Apologies but we are in the middle of the holiday so we are a little short-staffed but let me try to prioritize it.

**Comment by anoosurf** [comment] 2023-08-01 08:04
Thank u for considering.. really appreciate it :)

**Comment by karolkolodziej** [comment] 2023-08-01 08:15
There is a similar issue that we are planning to investigate in the nearest future: https://github.com/highcharts/highcharts/issues/18940
We will also test this one, perhaps they are related.

**Comment by anoosurf** [comment] 2023-08-02 02:11
apparently it works on 'scatter' series.. 
but something like a bubbles/ heatmap/treemap it does not
could that be a clue ? 
some settings difference maybe ?

**Comment by karolkolodziej** [comment] 2023-08-02 06:12
yes! that is a very good hint, we are going test that 😉

**Comment by TorsteinHonsi** [comment] 2023-08-04 08:33
Off the top of my head (I don't have time to investigate properly for now): The `followTouchMove` probably works only with series using k-d-tree search for detecting the closest point to the pointer. Heatmap, along with other series types like column (unless shared tooltip) and geo maps, use [direct touch](https://github.com/highcharts/highcharts/blob/6d8b460e6665743fbf8a1b6b11c70a7980a0921b/ts/Series/Column/ColumnSeries.ts#L942-L944) on the SVG elements to determine what point to highlight. 

So this may not be trivial. We do use k-d-tree for the heatmap when in interpolation or boost mode though, so there is a possibility we could enable it by a simple switch for that particular series type.

**Comment by karolkolodziej** [comment] 2023-08-04 08:51
I've tested the column series and everything seems to be fine.

https://github.com/highcharts/highcharts/assets/57004120/e0971800-925f-48d2-9ced-422c85004746

**Comment by anoosurf** [comment] 2023-08-04 09:10
i think one best way to see is the difference in settings of scatter vs bubble series.. both are similar but only the bubble series has the issue.. and im assuming similar case is that with heatmap & treemap

**Comment by anoosurf** [comment] 2023-08-04 10:22
Also it works on heat map but does not work in treemap … is the difference in size of the item giving any clue ?? Because is scatter and heat so the item size is same so it works … but in bubble and treemap each point item is different size .. some logic to give a clue ??

**Comment by anoosurf** [comment] 2023-08-07 05:47
any findings or solution ? 
thanks

**Comment by KacperMadej** [comment] 2023-08-11 16:12
Here's a simple workaround that is based on changing default heatmap series internal option:
https://jsfiddle.net/BlackLabel/xaz9osb0/1/

@anoosurf Could you check if this demo and this solution work for you case? The additional line of code is on the 1st line of JS code in the demo linked above.

**Comment by anoosurf** [comment] 2023-08-12 05:24
it does not work for treemap or bubble series :(

https://jsfiddle.net/anoosurf/rLwy10kz/15/
https://jsfiddle.net/anoosurf/d2ej3h6q/3/

**Comment by anoosurf** [comment] 2023-08-16 03:27
any solution or clue on how to resolve this important issue ?
looking forward to some help .. thank u so much :)

**Comment by anoosurf** [comment] 2023-08-17 04:34
came across this setting in the docs .. is there a clue to a possible in this ?
![image](https://github.com/highcharts/highcharts/assets/4696146/3e72a7af-5f82-44ff-a2f2-5d3d51795e24)

**Comment by KacperMadej** [comment] 2023-08-21 09:10
> it does not work for treemap or bubble series :(

The bubble series have a different ticket and its fix is in progress - https://github.com/highcharts/highcharts/issues/18940

For treemap the problem is more complex as the layout is taken not directly from data. Existing `buildKDTree` function doesn't solve the problem for this series type.

I will look into this.

**Comment by anoosurf** [comment] 2023-08-29 13:34
any solution to the treemap ?

**Comment by anoosurf** [comment] 2023-09-27 15:08
any solution on the treemap as yet ?

**Comment by KacperMadej** [comment] 2023-10-06 16:03
At this moment there is no easy solution to the problem. I'll try to check more on Monday.

**Comment by KacperMadej** [comment] 2023-10-10 10:58
@anoosurf 
Here's a workaround that should work for treemap series type: https://jsfiddle.net/BlackLabel/bpse0tcg/1/
Please let me know if you could test this and if this works in your case.

**Comment by anoosurf** [comment] 2023-10-10 12:43
thanks a lot @KacperMadej .. it worked like a charm !
ill do with manually copying this code for now.. when would it be incorporated in the next release ?

also when we slide our finger on a highchart on touch device.. the page also scrolls if we move up down slightly .. we want the page to hold steady when moving finger over a chart. how to prevent the mouse event form being propagated to the main page .... any setting on this ? thanks a lot

**Comment by KacperMadej** [comment] 2023-10-16 09:00
@anoosurf 
There is no ETA at this moment but there should be more info by the end of this week - a new comment in this thread will be added.

Could you edit [my demo](https://jsfiddle.net/BlackLabel/bpse0tcg/1/) to show the scroll problem? I am not sure how to recreate this behavior to match your case.

**Comment by anoosurf** [comment] 2023-10-16 09:04
https://jsfiddle.net/anoosurf/oz8bry4k/1/

i just added some dummy div with big height to force a scroll

**Comment by KacperMadej** [comment] 2023-10-19 09:56
@anoosurf 
This could be prevented on a level higher than Highcharts. Demo: https://jsfiddle.net/BlackLabel/aknsp93x/3/
```js
document.getElementById('container').addEventListener('touchmove', function (e) {
  e.preventDefault();
}, { passive: false });
```

**Comment by Xillez** [comment] 2024-04-04 15:53
Fixed in this PR => https://github.com/highcharts/highcharts/pull/20552, closing.

**Closed by Xillez** 2024-04-04 15:53 UTC
Labels: Type: Bug, Product: Highcharts
