### ISSUE TITLE
spline chart creating additional straight horizontal bar

### ISSUE THREAD

**Issue by albsaad** [highcharts/highcharts#14964] opened 2021-01-21 08:36 UTC
#### Expected behaviour
It should display a single bar against each series

![Expected Result](https://user-images.githubusercontent.com/77774614/105324626-7730dd80-5bed-11eb-8b52-c8de2cf3b2e3.png)

#### Actual behaviour
Sometimes it adds additional straight bar with expected or actual bar.
![Behavior](https://user-images.githubusercontent.com/77774614/105324674-857ef980-5bed-11eb-9d95-b3b2e70c7b14.png)

Here is my JS Code
`var chart = Highcharts.chart('container', {
chart: {
type: 'spline'
},
title: {
text: 'Total Pool Overview'
},
subtitle: {
text: 'Total work force capacity in contract hours per Week'
},
xAxis: {
type: 'datetime',
dateTimeLabelFormats: { // don't display the dummy year
month: '%e. %b',
year: '%b'
},
title: {
text: 'Date'
}
},
yAxis: {
title: {
text: 'Hours'
},
min: 0
},
tooltip: {
headerFormat: '{series.name}
',
pointFormat: '{point.x:%e. %b}: {point.y:.2f}'
},
legend: {
layout: 'vertical',
align: 'right',
verticalAlign: 'middle'
},
plotOptions: {
series: {
marker: {
enabled: true
},
pointInterval: 7 * 24 * 3600 * 1000,
point: {
events: {
mouseOver: function () {

                                    console.log(this);
                                    var index = this.index;
                                    UpdateHeaderValuesWeeklyBased(index);
                                },
                                mouseOut: function () {
                                    
                                    console.log(this);
                                    var index = this.index;
                                    ResetHeaderValues();
                                }
                            }
                        }
                    }
                },
                series: [{
                    name: 'Total Maximum Hours',
                    data: maxArray,
                    color: '#0000ff'
                },
                {
                    name: 'Total Minimum Hours',
                    data: minArray,
                    color: '#00ff00'
                },
                {
                    name: 'Capacity',
                    data: CapacityArray,
                    color: '#ff0000'
                }
                ],
                responsive: {
                    rules: [{
                        condition: {
                            maxWidth: 500
                        },
                        chartOptions: {
                            plotOptions: {
                                series: {
                                    marker: {
                                        radius: 2.5
                                    }
                                }
                            }
                        }
                    }]
                }
            });`

**Comment by PaulDalek** [comment] 2021-01-21 13:16
Closing as a duplicate of the #14963.

**Closed** 2021-01-21 13:16 UTC
Labels: Type: Duplicate
