### ISSUE TITLE
Highchart modules are not defined as functions in Highcharts 12.0.1 when imported from npm

### ISSUE THREAD

**Issue by fgordillo** [highcharts/highcharts#22255] opened 2024-11-29 10:14 UTC
#### Expected behaviour
I'm using exporting, export-data and accessibility modules together with Highcharts.
I'm expecting to be able to load them using the following code:
```
import Highcharts from "highcharts"
import exportingInit from "highcharts/modules/exporting"
import exportDataInit from "highcharts/modules/export-data"
import accessibilityInit from "highcharts/modules/accessibility"

accessibilityInit(Highcharts)
exportingInit(Highcharts)
exportDataInit(Highcharts)
Highcharts.setOptions({
    exporting: {
        enabled: false, // Hides the button, but API methods are still available. We implement our own export menu.
    },
})
```
(as described in the [docs](https://www.highcharts.com/docs/getting-started/installation-with-esm#babel))

#### Actual behaviour
I get the following errors when I load the application:
```
staticInit.js:15 Uncaught TypeError: exportingInit is not a function
staticInit.js:16 Uncaught TypeError: exportDataInit is not a function
staticInit.js:17 Uncaught TypeError: accessibilityInit is not a function
```

#### Live demo with steps to reproduce
[https://codesandbox.io/p/sandbox/restless-currying-kxndnh?workspaceId=4cea7340-b0cd-4f03-981e-f6d1068382c2](Demo in codesandbox)

#### Product version
Highcharts 12.0.1

#### Affected browser(s)
Tried in Chrome

**Comment by hubertkozik** [comment] 2024-11-29 10:17
Hi @fgordillo! This ticket is a duplicate of https://github.com/highcharts/highcharts/issues/22251. In Highcharts v12 you do not have to call module factories. We will update the docs.

**Closed by hubertkozik** 2024-11-29 10:17 UTC
Labels: Duplicate
