### ISSUE TITLE
4.2.2 runtime errors onContainerMouseMove throwing erros

### ISSUE THREAD

**Issue by onemenny** [highcharts/highcharts#4998] opened 2016-02-04 19:26 UTC
It seems that today's new release is causing runtime errors with the new addition of onContainerMouseMove - "cannot read property 'mouseIsDown' of undefined". It is caused when hovering the chart with the mouse while the charts loads

**Comment by TorsteinHonsi** [comment] 2016-02-05 07:51
Fixed by https://github.com/highcharts/highcharts/commit/c17dc193ee6f786c8cb1b265c40babdb09f7a077

**Closed by TorsteinHonsi** 2016-02-05 07:51 UTC
Labels: Regression

**Comment by maxname** [comment] 2016-02-05 17:38
when this fix in release?

**Comment by TorsteinHonsi** [comment] 2016-02-08 08:27
We will publish a new maintenance release within a few days. Sorry for the inconvenience.

**Comment by onemenny** [comment] 2016-02-10 14:01
There are still errors on 4.2.3 
![screen shot 2016-02-10 at 15 58 10](https://cloud.githubusercontent.com/assets/1677449/12949269/979094ae-d00f-11e5-8175-b7f8bf86cefa.png)

**Comment by arnabk** [comment] 2016-02-17 03:45
I dont think the issue is fixed. Trackjs reported somewhere around 90K issues just with these two - 

Cannot read property 'mouseIsDown' of undefined
Ja[kb] is undefined
![image](https://cloud.githubusercontent.com/assets/446864/13099277/04b3253c-d4ee-11e5-9647-6b4998485d4a.png)


![image](https://cloud.githubusercontent.com/assets/446864/13099289/1e2a59c2-d4ee-11e5-98e5-db202738211f.png)
