### ISSUE TITLE
When legend is vertically top aligned, it overlaps title text

### ISSUE THREAD

**Issue by sagargurtu** [highcharts/highcharts#7444] opened 2017-11-22 09:01 UTC
#### Expected behaviour
Legend should not overlap title text when vertically top aligned.

#### Actual behaviour
Legend is overlapping title text when top aligned.

#### Live demo with steps to reproduce
http://jsfiddle.net/f1a5y0t4/

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment] 2017-11-22 12:23
Hi @sagargurtu 

Thank you for reporting the issue. Actually, it's a duplicate of #7428 - closing the issue then.

**Closed by pawelfus** 2017-11-22 12:23 UTC
