### ISSUE TITLE
When accessibility enabled, legendItemClick returning event with target as text instead of tspan

### ISSUE THREAD

**Issue by AviralVarshney123** [highcharts/highcharts#13297] opened 2020-04-10 13:29 UTC
#### Expected behaviour
When clicked on any legend, event.target should be the tag where it is clicked.

#### Actual behaviour
Currently its returning the parent of the legend element

#### Product version
Latest 8.0.0

#### Affected browser(s)
chrome

**Comment by AviralVarshney123** [comment] 2020-04-10 13:30
Can someone check this ? Or suggest any workaround would be appreciated

**Comment by AviralVarshney123** [comment] 2020-04-12 21:00
@circleci-mu can someone check this please ? our workflow has been heavly impacted because of this change.

**Comment by sebastianbochan** [comment] 2020-04-14 07:39
Hi @AviralVarshney123,
Thank you for reporting about the problem. I apologize for late reply, but we had the Eastern time.

I have passed your case to our A11 (accessibility) developer, who will investigate it as soon as possible.

FYI @oysteinmoseng

**Comment by oysteinmoseng** [comment] 2020-04-14 08:58
@AviralVarshney123 With accessibility enabled the legend items are proxied with HTML elements, so the event target will change. It is debatable if we should fake this, as it could be useful to access the proxy element as well in certain situations. Are you able to use the `this` reference to access the information you need? In this event handler `this` will refer to the series. Example: https://codepen.io/oysteinmoseng/pen/JjYYRgO

**Comment by AviralVarshney123** [comment] 2020-04-20 14:34
So in the example above @oysteinmoseng 
Either i click on icon or text, it returns same element.
In previous releases, we were able to differentiate the position of click.
We need to open two different things, one on clicking icon and one on clicking text

**Comment by oysteinmoseng** [comment] 2020-04-21 08:46
@AviralVarshney123 I see. One solution could be to look at the click position and compare it to the position of the icon. This would let you calculate whether or not the user clicked the icon. Example: https://codepen.io/oysteinmoseng/pen/JjYYRgO

**Comment by AviralVarshney123** [comment] 2020-04-21 09:00
@oysteinmoseng let me check if we are able to fix using this solution. Thank you
Will revert back

**Comment by AviralVarshney123** [comment] 2020-04-22 13:51
@oysteinmoseng 
clickX < legendIconBBox.maxX && clickX > legendIconBBox.minX
this is giving true in all cases for us.
Also for any click, all the elements returned are legendGroup, legendIcon, legendItem
Why we changed the normal behaviour of click, it should return the element it was clicked on

**Comment by oysteinmoseng** [comment] 2020-04-22 16:28
@AviralVarshney123 Are you able to reproduce the issue in a jsFiddle? In the demo I posted above, checking against the legendIcon position is working for me.

The change is because with the accessibility module loaded you are no longer clicking the individual SVG elements, you are clicking an HTML button element. Highcharts does not differentiate between clicking the icon or the text, so the button element covers both cases. This is due to compatibility concerns with screen readers.

**Comment by AviralVarshney123** [comment] 2020-04-24 14:15
@oysteinmoseng Above solution worked for line chart only
Legends comes for bar, column, bubble. `legendLine` wont work. Is there a common sol to this ?
Also hitting performance issue while toggling the legends.

**Comment by oysteinmoseng** [comment] 2020-04-24 19:54
@AviralVarshney123 I think for your use case the best approach would be to circumvent the proxy click by adding the following code before creating the chart(s):
```js
Highcharts.wrap(Highcharts.AccessibilityComponent.prototype, 'setProxyButtonStyle', function (proceed, btn) {
  proceed.apply(this, Array.prototype.slice.call(arguments, 1));
  btn.style.pointerEvents = 'none';
});
```

Example: https://codepen.io/oysteinmoseng/pen/JjYYRgO?editors=0010

Please comment if you are still encountering issues and we will help out. I am closing this issue as not a bug since the default behavior is behaving as expected, but you should still be able to comment.

**Closed by oysteinmoseng** 2020-04-24 19:54 UTC
Labels: Status: Pending reply
