### ISSUE TITLE
Highstock doesn't respect all series to determine the available range

### ISSUE THREAD

**Issue by weltall** [highcharts/highcharts#13521] opened 2020-05-14 12:58 UTC
#### Expected behaviour
If several series are added to the Highstock chart, of which one is line, I'd expect all the ranges of the series to be considered, when deciding the area which can be viewed/scrolled in the Highstock chart.

Instead it seems that, as soon as a line series is added, that's the only series considered for the decision, regardless of its position in the series array.

In the specific case a flags series + a line series.

#### Actual behaviour
If a line series is added only that series is considered to determine the available range which can be viewed/scrolled. 

If it's removed the other series are considered. 

This means that if a line series is shorter than the flags series it won't show that series flag beyond the line series end.

Previously on 1.3.1, we could set max in the x-axis to work around this, but it seems that's not working anymore and causing additional glitches if set.

#### Live demo with steps to reproduce
The chart in the container shows the issue. 

We have two series a line series ending on 30 September 2019 and a flags series with a data point on 27 April 2020. The flag series last point is not visible at all and there is no way to make it visible by using the navigator.

https://jsfiddle.net/47Lz9k6t/

The chart in container2 contains a way to work around the issue by placing a "fake" point in the line series to cover the data point of the flag series. 

This way it's possible to see that part. (originating from this old question on StackOverflow https://stackoverflow.com/questions/46032041/highcharts-show-x-axis-for-missing-data-but-ignoring-certain-area )

#### Product version
Highstock on 8.1.0

#### Affected browser(s)
We tested Chrome  81.0.4044.138 and firefox 76.0

**Comment by sebastianbochan** [comment] 2020-05-15 08:33
Hi @weltall,
Thank you for reporting. Let me explain two problems here:
1) Navigator
By default the navigator uses range from the main series, but you can change it by  the [`showInNavigator`](https://api.highcharts.com/highstock/series.line.showInNavigator) param.

2) Space on the right side
Your data of flags has not regular gaps, so you should declare the [`ordinal`](https://api.highcharts.com/highstock/xAxis.ordinal) param.

ps. you can control the space on the "right side" also by the [`overscroll`](https://api.highcharts.com/highstock/xAxis.overscroll) option.

Fixed your demo:
- https://jsfiddle.net/BlackLabel/scq1yLja/

Im closing the ticket as a not a bug.

**Closed by sebastianbochan** 2020-05-15 08:33 UTC
Labels: Type: Not a bug

**Comment by weltall** [comment] 2020-05-15 08:52
Hi @sebastianbochan,

thanks for the help!
