### ISSUE TITLE
Gantt - collapsed parent is still showing children

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#12617] opened 2019-12-11 14:13 UTC
Is it a bug... or a feature?

Let's take an official Gantt demo: https://www.highcharts.com/gantt/demo/project-management
When collapsing parents, the children points are still visible. When you collapse the last bottom parent, children are not visible.

I haven't found anything in the changelog.

#### Product version
Gantt 8.0.0 (works differently in 7.2.1)

**Comment by pawelfus** [comment] 2019-12-12 09:40
It's a regression, v7 used to work fine: https://jsfiddle.net/BlackLabel/j8017a9m/ (children are hidden).

*Internal note:*
Most probably caused by 3fdb2d9f194429fc8780a728cc73be0a18fe95ad or 70282ff13c0b7c93340bacb8421e65f9ed677bdb - I'm not able to bisect correctly, some builds are broken.

**Comment by cawkie** [comment] 2019-12-18 10:48
Any schedule for resolving this?
Or is there a workaround?
8.0.0 fixed issue with dragging when categories are collapsed so reverting to 7.2.1 is not a good option.

**Comment by sebastianbochan** [comment] 2019-12-18 10:50
@cawkie, in case of working demo in 8.0.0, could I close the ticket?

**Comment by cawkie** [comment] 2019-12-18 11:00
Demo (https://www.highcharts.com/gantt/demo/project-management) still failing for me...
If it was working, and the fix was portable to my app, I'd be happy for the ticket to be closed.

**Comment by sebastianbochan** [comment] 2019-12-18 11:16
Im sorry, but I misunderstood you when you said that it works in 8.0.0 when categories are collapsed.

The issue is still valid, also in the v8.0.0

**Comment by cawkie** [comment] 2019-12-18 11:21
Sorry I wasn't clear.
This issue is still valid.
However I am unable to revert to previous version, so I have a broken app.

**Comment by TorsteinHonsi** [comment] 2020-01-09 13:53
I bisected it to 65d82368ddc19a1e45579e1c78c8d6ee3e3d2226.

**Closed** 2020-01-10 07:59 UTC
Labels: Product: Highcharts Gantt, Status: Backlog, Type: Regression
