### ISSUE TITLE
navigation.buttonOptions.align: wrong in RTL page

### ISSUE THREAD

**Issue by pajooh** [highcharts/highcharts#2731] opened 2014-02-21 15:46 UTC
in right to left page, ```left``` is right and ```right``` is left

**Comment by jon-a-nygaard** [comment] 2016-04-26 09:53
Closing this issue due to: We are not able to reproduce the issue, and it is pending reply. 
Should anyone have further information on this issue, please add a comment and reopen.

**Closed by jon-a-nygaard** 2016-04-26 09:53 UTC
Labels: Cant reproduce, Pending reply
