### ISSUE TITLE
Lines and fill areas misaligned on areasplinerange

### ISSUE THREAD

**Issue by frasern** [highcharts/highcharts#5225] opened 2016-04-18 10:45 UTC
#### Expected behaviour
The lines and fill area of graphs with type `areasplinerange` should align correctly.

#### Actual behaviour
The lines and fill areas seem to be drawn using different logic, so they don't align correctly. This leads to unsightly bulges:

![image](https://cloud.githubusercontent.com/assets/891092/14601558/a0df63b6-055a-11e6-9a3c-2bea8c89b299.png)

Note that it only seems to affect the first and last points in a series.

#### Live demo of the issue

https://jsfiddle.net/4wh9cqax/

**Comment by TorsteinHonsi** [comment] 2016-04-18 11:25
@jon-a-nygaard This is a duplicate, right?

**Comment by jon-a-nygaard** [comment] 2016-04-18 11:36
@TorsteinHonsi Yes, this is a duplicate of #5186

**Closed by jon-a-nygaard** 2016-04-18 11:36 UTC
