### ISSUE TITLE
highcharts.js:54 Error: <path> attribute d: Expected number...

### ISSUE THREAD

**Issue by jlouazel** [highcharts/highcharts#5836] opened 2016-10-18 08:38 UTC
#### Expected behaviour

Not throwing any error.

#### Actual behaviour

While working with live updating charts, I noticed highcharts was throwing some errors like this one:
![image](https://cloud.githubusercontent.com/assets/2803310/19470097/70efc494-951e-11e6-826e-45a72cb2cc7b.png)

It seems to happen when switching tabs on my browser. It doesn't happen every time but I have the impression it appears if I arrive on the tab at the exact moment an animation is starting. 

#### Live demo with steps to reproduce

I was able to reproduce it in on of the Highcharts official demo pages: http://www.highcharts.com/demo/dynamic-update

#### Affected browser(s)

At least on `Chrome 53.x`.

**Comment by pawelfus** [comment] 2016-10-18 09:09
Thanks for reporting! Duplicate of #5788 (the same errors caused by animation).

**Closed by pawelfus** 2016-10-18 09:09 UTC
