### ISSUE TITLE
Flags series: never get focused

### ISSUE THREAD

**Issue by arthoul** [highcharts/highcharts#6867] opened 2017-06-19 12:31 UTC
#### Expected behaviour
When I click on a flag,  click event must be triggered and tooltip must be shown

#### Actual behaviour
Flags series never get focused (tooltip never shown, click event not triggered)

#### Live demo with steps to reproduce
https://www.highcharts.com/stock/demo/flags-general

#### Affected browser(s)
All

**Comment by KacperMadej** [comment] 2017-06-19 13:51
Thank you for reporting about the problem. This is a duplicate of #6764. The problem is resolved on master - demo: http://jsfiddle.net/tyxw61xp/

**Closed by KacperMadej** 2017-06-19 13:51 UTC
Labels: Duplicate
