### ISSUE TITLE
Broken link in .dateFormat docs

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#8808] opened 2018-08-19 07:56 UTC
https://api.highcharts.com/class-reference/Highcharts#dateFormat

> Formats a JavaScript date timestamp (milliseconds since Jan 1st 1970) into a human readable date string. The format is a subset of the formats for PHP's strftime">www.php.net/manual/en/function.strftime.php} function.

**Comment by dandv** [comment] 2018-08-19 08:00
Also, can you please document the "subset of the formats"? `%R` doesn't work, for example.

**Comment by sebastianbochan** [comment] 2018-08-20 08:27
Hi @dandv,
Thank you for reporting!

**Comment by pawelfus** [comment] 2018-08-20 08:32
Duplicate of #6737

**Closed by pawelfus** 2018-08-20 08:32 UTC
Labels: Docs, Duplicate
