### ISSUE TITLE
[Accessibility] [Highcharts] duplicate-id: id attribute value must be unique

### ISSUE THREAD

**Issue by tanvimathur** [highcharts/highcharts#11348] opened 2019-07-09 09:44 UTC
#### Expected behaviour
id attribute value must be unique for all Highcharts components, even if there are multiple charts rendered on a single page.

#### Actual behaviour
For some chart elements, id attribute values are not unique for some static elements

#### Product version
Highcharts v6.1.2

#### Affected browser(s)
Chrome

#### Detected Using
Accessibility Insights for Web plugin

**Comment by pawelfus** [comment] 2019-07-09 11:23
Hi @tanvimathur 

Thanks for reporting. Could you add a demo for this issue? Thank you.

@oysteinmoseng - FYI

**Comment by oysteinmoseng** [comment] 2019-07-09 11:38
Internal note: Could be a duplicate of #10510? I think all other elements should have unique IDs now.

**Comment by pawelfus** [comment] 2019-07-09 12:21
I'm afraid not, @oysteinmoseng - commit seems to be affecting only pattern-fill plugin: https://github.com/highcharts/highcharts/commit/56e5e37f6e16ce86b2a58e29c498692fe6307c12

**Comment by oysteinmoseng** [comment] 2019-07-10 11:33
@pawelfus But are there any other IDs in Highcharts that get duplicated with multiple charts? I could not find any when taking a quick look.

**Comment by pawelfus** [comment] 2019-07-10 12:40
Hard to say, that's why I asked @tanvimathur for a live demo, so we can debug - report in the title says it's about accessibility.. As you said, this might be just a duplicate for pattern-fill plugin.

**Comment by tanvimathur** [comment] 2019-07-11 09:45
Hi @pawelfus @oysteinmoseng 

Thanks for your responses! I am working on a demo for this, in the mean time, I thought I could share my analysis with you.

We have multiple charts on a single page, and when I checked the DOM, I can see that the below IDs (marked in bold) are repeated, which is why we are seeing a duplicate-id issue on Accessibility Insights for Web 

Code Snippets:
1. <title id="**highcharts-title-0**">Chart</title>

2. <title id="**highcharts-title-1**">Chart</title>

3. <div id="**highcharts-information-region-0**" role="region" aria-label="Chart screen reader information." style="position: absolute; left: -9999px; top: auto; width: 1px; height: 1px; overflow: hidden;">

4. <div id="**highcharts-information-region-1**" role="region" aria-label="Chart screen reader information." style="position: absolute; left: -9999px; top: auto; width: 1px; height: 1px; overflow: hidden;">

**Comment by oysteinmoseng** [comment] 2019-07-11 13:21
Ah I see, no need for a further demo, as this is a known issue. We will have to consider what would be the best UX for screen reader users here, but we might simply append the chart title to these strings by default.

**Comment by tanvimathur** [comment] 2019-07-16 06:50
@oysteinmoseng I have a request - is it possible the for IDs to be made unique even if the title field is not set? We currently do not use the chart title, and it would be of great help to us if the IDs were made unique.

Also, by when will this change be live? It would be great if this can be resolved at the earliest

**Comment by oysteinmoseng** [comment] 2019-07-16 13:08
@tanvimathur Let me just clarify, is the issue the actual ID attribute value, or is it the content of the elements ("Chart", "Chart screen reader information")?

**Comment by tanvimathur** [comment] 2019-07-23 07:05
The issues in the actual ID attribute value in all the 4 mentioned scenarios

1. ID highcharts-title-0 repeated for multiple charts
`<title id="highcharts-title-0">Chart</title>`

2. ID highcharts-title-1 repeated for multiple charts
`<title id="highcharts-title-1">Chart</title>`

3. ID highcharts-information-region-0 repeated for multiple charts
`<div id="highcharts-information-region-0" role="region" aria-label="Chart screen reader information." style="position: absolute; left: -9999px; top: auto; width: 1px; height: 1px; overflow: hidden;">`

4. ID highcharts-information-region-1 repeated for multiple charts
`<div id="highcharts-information-region-1" role="region" aria-label="Chart screen reader information." style="position: absolute; left: -9999px; top: auto; width: 1px; height: 1px; overflow: hidden;">`

**Comment by oysteinmoseng** [comment] 2019-07-23 10:27
@tanvimathur I see, but these IDs are not identical? "highcharts-title-**0**" vs "highcharts-title-**1**". Do you have a demo where the IDs are identical? I am not able to reproduce this with multiple charts in the same page on my end.

**Comment by tanvimathur** [comment] 2019-07-26 11:15
The duplicate id="highcharts-information-region-1" issue is coming when we import the HC_accessibility module. If you use that, you will be able to reproduce it. If not, I'll provide some snapshots of the same.

Also, these IDs I mentioned are getting repeated in the DOM, for example, out of 5 charts that we have, 2 have id="highcharts-information-region-0" and 3 have id="highcharts-information-region-1"

**Comment by oysteinmoseng** [comment] 2019-07-26 12:47
@tanvimathur It sounds like you have multiple instances of Highcharts running on the same page. Could this be the issue? Highcharts should be incrementing the index for each chart, as long as you are running the same instance of the library.

**Comment by tanvimathur** [comment] 2019-07-29 17:13
@oysteinmoseng yes, we are using multiple instances of Highcharts on the same page. Is it possible for us to explicitly set the value of this information region? That way, we can make the value unique.

**Comment by pawelfus** [comment] 2019-07-30 10:04
@tanvimathur - could you update your Highcharts to v7 and test again? Issue with loading multiple modules was resolved in v7.

**Comment by tanvimathur** [comment] 2019-07-31 10:13
We are already using highcharts v7.1.2 and highcharts-react-official v1.5.2.

Is it possible for us to explicitly set the value of this information region? That way, we can make the value unique.

**Comment by pawelfus** [comment] 2019-07-31 10:26
Oh, ok - sorry, in the first post it's written `v6.1.2`.

You can workaround regions issue by something like this (not tested because of missing live demo):

```js
(function(H) {
  H.wrap(
    H.ContainerComponent.protototype,
    'onChartUpdate',
    function (proceed) {
      proceed.apply(this, Array.prototype.slice.call(arguments, 1);
      if (this.screenReaderRegion) {
        this.screenReaderRegion.setAttribute('id', generateUniqueID()); // set new ID
      }
    }
  );
})(Highcharts);
```

**Comment by oysteinmoseng** [comment] 2019-08-07 12:09
I am closing this as not a bug, as running multiple instances of Highcharts on the same page is not technically supported. We would recommend using a single instance per page, and creating multiple charts from the same instance.

@tanvimathur Feel free to contact us through [support](https://www.highcharts.com/blog/support/) if you need further help with this specific issue.

**Closed by oysteinmoseng** 2019-08-07 12:09 UTC
Labels: Status: Can't reproduce, Status: Inbox, Status: Pending reply, Type: Enhancement

**Comment by siddarthkanted** [comment] 2020-04-27 04:50
Even I am getting the same issue, we have multiple high charts "new Highcharts.Chart(chartOptions)" in the same page. Due to which highcharts-information-region-0 id is created multiple times.
And using accessibility tool we are getting error highcharts-information-region-0 id is duplicate id.

**Comment by oysteinmoseng** [comment] 2020-04-27 07:44
@siddarthkanted Can you verify that you are only loading the Highcharts library once? Are you able to reproduce your issue in a jsFiddle/Codepen?

**Comment by siddarthkanted** [comment] 2020-06-08 13:58
We are loading 2 instances of highchart in a single page.
First chart is rendered using Highstock.chart(chartOptions)
Second chart is rendered using Highcharts.chart(chartOptions)

**Comment by oysteinmoseng** [comment] 2020-06-09 08:59
@siddarthkanted Loading multiple instances of the Highcharts library is not supported, and should be avoided. By loading Highcharts with the "stock" module added, you will be able to create both regular charts and stock charts from the same instance. Please reach out to our [customer support](https://www.highcharts.com/blog/support/) if you experience further issues, and we can help you with your specific case.

**Comment by robfentress** [comment] 2021-02-25 01:24
I wonder if the problem is not the `id` attribute, but rather the `aria-label` attribute.  It is a violation of accessibility best practice to give more than one landmark region of the same type the same `aria-label` value.  It is ironic that a region whose `aria-label` value is "Chart screen reader information" would trigger this violation, as it does when I use the [Axe browser extension](https://www.deque.com/axe/devtools/) on a page of mine that uses more than one chart (which I can't believe is not a relatively common use case).  Specifically, it violates the Axe rule `landmark-unique`, ["Landmarks must have a unique role or role/label/title (i.e. accessible name) combination"](https://dequeuniversity.com/rules/axe/4.1/landmark-unique?application=AxeChrome).  Even if that is not the same problem that triggered this particular issue, it would be great if it could be fixed, because the makers of HighCharts appear to have devoted a great deal of effort to make their product accessible.

**Comment by KacperMadej** [comment] 2021-02-25 12:15
Hi @robfentress 

If your problem doesn't require loading multiple instances of Highcharts please open a new issue with a live demo - a minimal demo in a sandbox, like JSFiddle, would be great.

**Comment by oysteinmoseng** [comment] 2021-02-25 16:27
@robfentress Just to chime in, the easy fix for this is to append e.g. the title of each chart to these labels by default: https://jsfiddle.net/wktusdrL/. This is assuming I understood you correctly.

We should make a note to change this internally as well, so feel free to log a bug, or let me know and I can do it.

**Comment by robfentress** [comment] 2021-02-25 17:19
@oysteinmoseng Excellent!  That did the trick, although there was a similar issue that was also flagged by Axe that I was able to fix by setting `lang.accessibility.exporting.exportRegionLabel` to `"Chart menu, {chart.options.title.text}"`.  Thanks for the help!

**Comment by oysteinmoseng** [comment] 2021-02-26 08:56
I have logged an issue here: https://github.com/highcharts/highcharts/issues/15229
