### ISSUE TITLE
MathJax not parsed while exporting chart

### ISSUE THREAD

**Issue by vivekvenkris** [highcharts/highcharts#8764] opened 2018-08-11 13:19 UTC
#### Expected behaviour
if use HTML is true and the string contains latex, parse MathJax before saving chart as PDF or JPEG or PNG

#### Actual behaviour
It saves a PDF without parsing. I could take screenshots for JPEG and PNG but there is no way to obtain a vector graphic format chart like a PDF with the Math rendered.

#### Live demo with steps to reproduce
http://jsfiddle.net/e4urL07k/

1. see that the live output has MathJax rendered. 
2. Try exporting the chart as PDF or JPEG or PNG.
3. Notice that the MathJax commands are not parsed. 

#### Affected browser(s)
Chrome, Safari, Firefox

**Comment by sebastianbochan** [comment] 2018-08-13 09:08
Hi @vivekvenkris,
Thank you for the reporting. 

**Internal note**
@cvasseng can we add this library to our exporting server?

**Comment by TorsteinHonsi** [comment] 2018-08-22 07:41
A simpler approach would be to use our offline-export.js module. To do this, we need to have MathJax process the copied chart before exported it. It seems to do that correctly when calling it from an event handler, though it still doesn't look correct: http://jsfiddle.net/highcharts/e4urL07k/6/. Probably the missing piece is the CSS from MathJax, that is not passed to the exported SVG.

**Comment by mantydze** [comment] 2019-03-25 14:41
Any progress on this?

**Comment by sebastianbochan** [comment] 2019-03-27 11:06
Hi @mantydze,
I have passed this issue to our exporting developer, he will answer as soon as possible.

FYI @cvasseng

**Comment by cvasseng** [comment] 2019-03-27 12:59
Adding the library to the export server is possible with the `resources` option that accepts an object with a`js` key containing raw JavaScript in the export HTTP API. However, this would only work when exporting based on a JSON configuration, and not with SVG (which the export module on the Highcharts side utilizes).

Making this work with the export menu on charts and the official server requires, as far as I can tell, adding MathJax parsing when building the SVG that's passed to the export server. This would have to be done in a general way however as we want to avoid introducing loose dependencies in Highcharts itself, i.e. we would likely have to add additional hooks that could do pre-processing on text fields when exporting. @TorsteinHonsi do you have any insights on how we could potentially handle that?

**Comment by yszhang95** [comment] 2022-04-12 12:06
> Adding the library to the export server is possible with the `resources` option that accepts an object with a`js` key containing raw JavaScript in the export HTTP API. However, this would only work when exporting based on a JSON configuration, and not with SVG (which the export module on the Highcharts side utilizes).
> 

Could you please provide an example? `MathJax 2.7` works like `<scripts>src=/path/to/MathJax.js?config=TeX-AMS_CHTML.js</scripts>` in HTML. The config is necessary. Is it possible to execute the whole using `resources` like
`{"files": "/path/to/MathJax.js?config=TeX-AMS_CHTML.js"}`. I attempted and failed.

It seems `MathJax 3` does not need configuration but it conflicts with the export server because of the lack of `Map`?

**Comment by hubertkozik** [comment] 2024-09-03 10:33
This GitHub issue will be fixed in https://github.com/highcharts/highcharts/pull/21712. 

If you would like to use MathJax Latex with the Offline Exporting module here's the demo for you: https://jsfiddle.net/BlackLabel/36amu9ks/ The code is taken directly from the branch, after merging into the master it will work natively.

**Comment by nishikantparmariam** [comment] 2024-09-04 09:32
@hubertkozik thanks for the response!

We decided to use [KaTeX](https://katex.org) internally as MathJax is having lots of platform dependent issues.

We're facing below problems even upon try some alternatives, can you please help:

### Approach 1

Using [renderMathInElement](https://katex.org/docs/autorender#api) typesetting function -
   
Reproducer: https://jsfiddle.net/gv8mxq67/

- Notice that how that y-axis title is overlapping with plot area because it is rendered as normal text initially and then after typesetting, the chart does not adjust over their sizes.
- Download is still broken after using code from your branch.

### Approach 2

Using [renderToString](https://katex.org/docs/api#server-side-rendering-or-rendering-to-a-string) function and convert text into HTML beforehand.
 
Reproducer: https://jsfiddle.net/kzj0d3qn/

- As you can notice that y-axis title isn't overlapping with plot area as compared to above approach (that's the behavior we want) but `\sqrt{x}` is rendering without the root. It renders fine at other place on the page but not inside chart's title.
    
- Download is still broken after using code from your branch.

Can you please help us in making it work by resolving both issues in either of the above approaches?

---

_FWIW, overlapping issue + sqrt broken in download are happening  when using MathJax also: https://jsfiddle.net/dnj5Lyz4/_ (Run the code again and notice it is overlapping)

**Comment by hubertkozik** [comment] 2024-09-04 10:41
@nishikantparmariam Here's the demo for you: https://jsfiddle.net/BlackLabel/5dswxc6k/ Now, you don't need to use code directly from the branch, everything is already working with the current version of Highcharts. I would suggest staying with **Approach 1** and firing some additional redraws/title positioning methods after the KaTeX replacement logic.

**Comment by nishikantparmariam** [comment] 2024-09-05 07:55
Thanks @hubertkozik, this is much helpful!

I've facing another issue that sqrt does not work in y-axis title: https://jsfiddle.net/1tu3cfp9/1/ it works fine in exporting now.

Also, do I have to copy options into exporting.chartOptions? If yes then should I copy just the xAxis/yAxis title and not title/subtitle?

**Comment by nishikantparmariam** [comment] 2024-09-05 11:35
Also exporting this broken for this example: https://jsfiddle.net/j1ys3xup/

**Comment by hubertkozik** [comment] 2024-09-06 08:49
@nishikantparmariam I feel, that this is more of adapting an external library to work with Highcharts. The main problem is that Katex is replacing the DOM elements after the Highcharts logic, that's why the Katex elements are wrongly positioned. Highcharts logic for positioning labels worked for strings like `\\( \\frac{a}{b} \\)` and after chart load those strings are replaced with different elements with different dimensions.

In this demo: https://jsfiddle.net/2b31fmqp/1/ there is a lot of errors in the console not related to Highcharts.

> Sqrt still does not work in y-axis title, it works fine in exporting though

Now, I think it would be better to remove an extra update of the axis title from chart load: https://jsfiddle.net/BlackLabel/Lofup8z5/ 

> Do I have to copy options into exporting.chartOptions? If yes then should I copy just the xAxis/yAxis title and not title/subtitle?

Actually, after rethink, we shouldn't set anything in `exporting.chartOptions` option.

> LaTeX does not work in axis label format or plotLines' text - low priority.

I think it's related to errors in the console. I am not a specialist in Katex, can you check if the Katex string for labels is good?

> Also exporting is broken for this example: https://jsfiddle.net/j1ys3xup/

It seems to me, that Katex is using some extra elements, which are not removed from copy of the chart during offline exporting, I've checked the unnecessary classes and remove those elements in 7 and 8 lines in this demo: https://jsfiddle.net/BlackLabel/recxu8zn/

**Comment by nishikantparmariam** [comment] 2024-09-07 12:38
Thanks @hubertkozik all reported issues seem to be resolved, except below:

> I think it's related to errors in the console. I am not a specialist in Katex, can you check if the Katex string for labels is good?

I got the issue, it is related to Highcharts treating `{}` for templating. Is there a way to escape it? e.g. I was able to do this via formatter function that does not apply templating - https://jsfiddle.net/6gz70xLe/.

Usually our Highchart options come from let's say a backend that are serializable, so using JS functions does not work, we would prefer if we can escape `{}` somehow.

**Closed** 2024-09-09 08:16 UTC
Labels: Type: Not a bug, Type: Question

**Comment by hubertkozik** [comment] 2024-09-09 13:34
Hi @nishikantparmariam! The official way to disable templating is described here: https://www.highcharts.com/docs/chart-concepts/templating under _Limitations_ header.

> In cases where helpers are not sufficient to reach the desired formatting, it is better to preprocess the data set. Use [the custom option](https://api.highcharts.com/highcharts/series.line.custom) for series and points, and access that from the format string.

Here's the demo: https://jsfiddle.net/r4ouxv8s/ Sadly, after few hours of debugging, I am not able to position those labels correctly, the logic of axis labels doesn't support changing the content of labels after the load. The easiest solution would be to disable `reserveSpace` and set some margins and x position manually: https://jsfiddle.net/BlackLabel/zd3v41sx/
