### ISSUE TITLE
Axis label hidden in break also showing up

### ISSUE THREAD

**Issue by govinda18** [highcharts/highcharts#16909] opened 2022-01-21 12:53 UTC
#### Expected behaviour
In the below reproducer, Jan 1 axis label should not show up as it should be hidden with breaks.

#### Actual behaviour
Jan 1 axis label shows up

#### Live demo with steps to reproduce
http://jsfiddle.net/b1wgkear/

#### Product version
Highstock

#### Affected browser(s)
Chrome

**Comment by raf18seb** [comment] 2022-01-24 08:27
Hi @govinda18, thank you for creating the ticket!

Some of users will say that this label should not be shown up, but another group of users will want this label to be displayed, so I don't think it's a bug. Everything works fine.
If you want to hide that label, you can do it in many ways, e.g. set `xAxis.showFirstLabel: false`.

I'm closing the ticket as not a bug, but feel free to share any insights and further feedback if you disagree.

**Closed by raf18seb** 2022-01-24 08:27 UTC
