### ISSUE TITLE
Highstock - DataGrouping not enabled unless explicitly specified?

### ISSUE THREAD

**Issue by josh-byster** [highcharts/highcharts#8751] opened 2018-08-09 04:09 UTC
I've been running into some inconsistencies when working with dataGrouping. The [API ](https://api.highcharts.com/highstock/plotOptions.series.dataGrouping.enabled) says that Data Grouping is by default enabled, and works differently in Highcharts and Highstock.

If this is indeed an issue and not something I'm just misunderstanding, I will look into also reproducing #8711, which is similar - keys aren't respected with dataGrouping. Thank you.

#### Expected behaviour
See . I generate 10000 length 3 arrays of numbers in the form [x,z,y]. I specify this key and have the series set to "area". Since "y" is the last value, it should plot the "y" value when `dataGrouping` is `true`, like the default value. However, if you uncomment the dataGrouping attribute in the series options (lines 51-53), you get a different result.

#### Actual behaviour
Highstock has a different output depending on if you comment out lines 51-53, the `dataGrouping` options. Also, if you change the script source to Highcharts, it seems to act as expected - just an issue with Highstock. 

#### Live demo with steps to reproduce

https://jsfiddle.net/9gn12Lo7/42/

By uncommenting out lines 51-53, you will get a different result
#### Product version

Commenting out `dataGrouping` will produce a different result despite it being listed as the default vaule. Also it's inconsistent with Highcharts, since only happens when loading Highstock rather than Highcharts JS.
#### Affected browser(s)
Chrome 68

**Comment by sebastianbochan** [comment] 2018-08-09 07:50
Hi @josh-byster,
Thank you for the reporting. It looks like that `keys` requires to enabled datagrouping by the option and does not extract defaulf value.

Demo:
- https://jsfiddle.net/BlackLabel/24dgynb3/

**Comment by josh-byster** [comment] 2018-08-10 04:32
@sebastianbochan thanks for the response! However, in addition, I don't believe the dataGrouping is functioning correctly. If you take a look at the first few lines, I set the second value to be a constant 300 and the third value (index 2) a random number. So when I map the keys to be ["z","y"], you should get the graph to look like random lines, since it should be reading index 2 to be y. This works correctly with using highcharts.js but not with highstock.src.js. If you change the HTML in the fiddle to be `<script src="https://code.highcharts.com/highcharts.js"></script>`, this should work.

**Comment by pawelfus** [comment] 2018-08-10 09:40
This is a duplicate of #8544

Setting `turboThreshold` resolves the issue: https://jsfiddle.net/BlackLabel/9gn12Lo7/50/

Closing as duplicate.

**Closed by pawelfus** 2018-08-10 09:40 UTC
Labels: Pending reply
