### ISSUE TITLE
Lazy - loading - problem with loading bigger range than current

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#3876] opened 2015-02-24 13:41 UTC
1) http://jsfiddle.net/f170k5t9/
2) change the to date to '2011-07-20', works
3) change it to '2011-05-20', works
4) Try to change to range from point 2), it doens't work.

**Comment by pawelfus** [comment] 2016-05-04 10:01
Duplicate of #3228

**Closed by pawelfus** 2016-05-04 10:01 UTC
