### ISSUE TITLE
Bug with events.load setSize()

### ISSUE THREAD

**Issue by cgahmann** [highcharts/highcharts#15400] opened 2021-03-25 09:18 UTC
#### Expected behaviour
Show me all bars

#### Actual behaviour
When I calculate the height of the chart dynamically, it shows me only the last bars in the bar chart. The others come sometime later or when I change the height of the page so it has to recalculate the chart.
It works if I take the highchart.js (https://code.highcharts.com/highcharts.js) instead of highstocks.js (https://code.highcharts.com/stock/highstock.js)

#### Live demo with steps to reproduce
http://jsfiddle.net/wmys9xkc/

#### Product version
Latest stable Highstock

#### Affected browser(s)
Google Chrome, Firefox in MacOS

**Comment by khlieng** [comment] 2021-03-25 09:34
This was a clipping bug in stock that has been fixed on master (#15200): http://jsfiddle.net/9fzqx0ne/

**Comment by cgahmann** [comment] 2021-05-04 16:37
@khlieng I guess it looks like the fix is out again? http://jsfiddle.net/9fzqx0ne/

**Comment by khlieng** [comment] 2021-05-04 17:26
Hmm, seems so, you can work around it for now by running the `setSize` in a rAF or zero `setTimeout`: http://jsfiddle.net/n1bgah78/

**Comment by khlieng** [comment] 2021-05-04 17:37
Its a regression since #15516.

**Closed** 2021-05-06 09:23 UTC
Labels: Status: Review in progress, Type: Regression
