### ISSUE TITLE
Allow Series.setState to take 'inactive' as a value

### ISSUE THREAD

**Issue by nzayatz14** [highcharts/highcharts#12120] opened 2019-10-02 17:56 UTC
#### Expected behaviour

Can we add the ability to set a series to the "inactive" state via the `setState()` function.

**Current Situation:** I have multiple series showing in a chart. When I hover over any series in the chart, I wish to highlight the series that are "related" to the series I am hovering, and make the rest of the series inactive.

#### Actual behaviour

Currently the state in setState "Can be either `hover` or `undefined` to set to normal state." It does not allow for programmatically setting a series to "inactive"

#### Live demo with steps to reproduce

https://api.highcharts.com/class-reference/Highcharts.Series#setState

**Comment by pawelfus** [comment] 2019-10-03 11:44
Hi @nzayatz14 

Thanks for reporting the issue. It's actually a bug in docs, calling `series.setState("inactive")` does work: https://jsfiddle.net/9bmuj8sL/

**Comment by nzayatz14** [comment] 2019-10-03 13:31
@pawelfus ok thanks for the quick response!

I updated your fiddle to show you the issue I was running into. I added `mouseOver` and `mouseOut` events to each of the series so that, when any of the series get hovered, I'd like to also highlight the first series. But the first series does not go to the "hover" state and instead goes to the inactive state (maybe due to default behavior?): https://jsfiddle.net/4ajrcsk8/

**Comment by pawelfus** [comment] 2019-10-03 14:05
Yes, this is the default behaviour. All series except currently hovered are dimmed. This happens after `mouseOver` event is fired, take a look: https://jsfiddle.net/thjcrwb4/1/ - (I postponed `setState()` to be called after default logic is executed).

There's alternative solution: use `series.linkedTo` option to link series. When hovering one series all linked (and parent) series aren't dimmed: https://jsfiddle.net/thjcrwb4/2/ (except legend items).

**Comment by nzayatz14** [comment] 2019-10-04 15:53
@pawelfus ok cool, I think `linkedTo` is what I am looking for. Is there a way to link multiple series via `linkedTo`? The docs say its just a single string

https://api.highcharts.com/highcharts/plotOptions.series.linkedTo

Also is there a way to turn off the default behavior for making series `inactive` when hovering over another series? I would still like to use the `inactive` state programmatically, just not the default behavior. The changelog mentioned adding this block to the `plotOptions`

```
states: {
    inactive: {
        opacity: 1
    }
}
```

But this just updates the styling of the inactive state, not disabling the default behavior of it

**Comment by pawelfus** [comment] 2019-10-07 07:23
You can link multiple series to one parent series. You can't link one series to multiple parents.

Regarding styles, `opacity` is the only option applied to series, so setting to 1 "disables" it. I agree, an option to disable default behaviour (e.g. `series.states.inactive.enabled`) and letting developers control it via `series.setState()` would be a nice solution.

**Comment by nzayatz14** [comment] 2019-10-07 13:30
@pawelfus ok thanks!

Is there any way we can make an official request for being able to add an option like `series.states.inactive.enabled`? I'm pretty swamped with work right now so I'm not sure I'd be able to dig in to this myself.

**Comment by pawelfus** [comment] 2019-10-07 13:58
Could you create a separate ticket for that? I will mark this accordingly. Thanks!

**Comment by nzayatz14** [comment] 2019-10-07 14:09
@pawelfus https://github.com/highcharts/highcharts/issues/12156

**Comment by bre1470** [comment] 2019-11-07 10:47
@pawelfus This reads like an implementation issue and not like an issue with documentation. Or is it related to issue #11759?

**Comment by pawelfus** [comment] 2019-11-07 12:48
Implementation issue was moved to #12156

The main issue in this ticket a duplicate of #11759, can be closed than, thanks!

**Closed by pawelfus** 2019-11-07 12:48 UTC
Labels: Product: Docs
