### ISSUE TITLE
packbubble chart dataLabels misplaced in responsive

### ISSUE THREAD

**Issue by mark-leblanc-moodys** [highcharts/highcharts#20122] opened 2023-11-13 13:00 UTC
#### Expected behaviour
if the legend is moved in responsive, the bubbles and their dataLabels should be rerendered in their new locations.

#### Actual behaviour
when the legend is moved in responsive, the dataLabels maintain their previous location and don't move with their bubbles.

#### Live demo with steps to reproduce

https://jsfiddle.net/yto3mkfd/

#### Product version

11.2.0

#### Affected browser(s)
Chrome, Edge, Firefox

**Comment by bm64** [comment] 2023-11-13 13:14
Hello @mark-leblanc-moodys and thanks for reporting the issue.

The ticket has already been created for that problem so I'm closing this one as a duplicate of https://github.com/highcharts/highcharts/issues/20120

If there is anything you'd like to add about the issue feel free to continue in the original ticket.

**Closed by bm64** 2023-11-13 13:14 UTC
