### ISSUE TITLE
Marker clusters on Highcharts maps did'nt work (check official documentation)

### ISSUE THREAD

**Issue by Agillmann** [highcharts/highcharts#16555] opened 2021-10-27 12:45 UTC
When click on marker cluster we should have a rerender of all markers cluster but nothing happened. I use this feature on my personal project and did not work anymore. Same from your official documentation it did not work.

https://www.highcharts.com/demo/maps/marker-clusters

**Comment by raf18seb** [comment] 2021-10-30 17:00
Hi @Agillmann,

Closing as a duplicate of https://github.com/highcharts/highcharts/issues/16534
It's already fixed on master. Will be working fine in the next Highcharts release.

Workaround with a fix applied: https://jsfiddle.net/BlackLabel/07fuke1q/

**Closed by raf18seb** 2021-10-30 17:00 UTC
