### ISSUE TITLE
How to arrange the legend and navigation horizontally?

### ISSUE THREAD

**Issue by webpig** [highcharts/highcharts#15672] opened 2021-05-07 05:42 UTC
#### Expected behaviour
legend and navigation are arranged horizontally. 
Like Echarts:

![image](https://user-images.githubusercontent.com/24989439/117414219-79733980-af49-11eb-9d1f-a5b8795c8f99.png)

#### Actual behaviour
![image](https://user-images.githubusercontent.com/24989439/117402992-09a98280-af3a-11eb-9663-1f133dfb9e08.png)

#### Product version

"highcharts": "^9.0.1",
 "highcharts-vue": "^1.3.5",
#### Affected browser(s)
Chrome  90.0.4430.93

**Comment by KacperMadej** [comment] 2021-05-13 11:59
Duplicate of https://github.com/highcharts/highcharts/issues/7513

**Closed by KacperMadej** 2021-05-13 11:59 UTC
