### ISSUE TITLE
Gap shown inconsistently for second series

### ISSUE THREAD

**Issue by meteorpublish** [highcharts/highcharts#11771] opened 2019-08-26 01:42 UTC
I have two series, a stock, and a study. I'm trying to reliably always show gaps around `null` points in the study.

In https://jsfiddle.net/0bed27ur, the gap in the study series is shown only when that series is displayed by itself. When both series are displayed, the gap in the study is not shown.

![Gap shown inconsistently](https://user-images.githubusercontent.com/10043369/63659737-b51b9f00-c778-11e9-9358-f158aeda9156.gif)

**Comment by KacperMadej** [comment] 2019-08-26 08:04
Hi @meteorpublish 

Thank you for reporting the problem.

This is caused by dataGrouping.
You could disable dataGrouping for the study (line series) to keep the gap: https://jsfiddle.net/BlackLabel/9ajy8ehL/

Please let me know if this resolves your problem.

**Comment by KacperMadej** [comment] 2019-08-27 14:30
This is because grouped points in the candlestick series do not have points in the same x position as the line points, so minimal point distance is relatively small causing candles to be thin. This could be resolved by using a second, hidden xAxis for the line series. Demo: https://jsfiddle.net/BlackLabel/9ajy8ehL/1/

The case is resolved and this is becoming more a technical support case, so I will close the issue.
If you have a short follow up about the issue we could continue here, but if you have a new question for technical support please use any of the available technical support channels. https://www.highcharts.com/blog/support/

**Closed by KacperMadej** 2019-08-27 14:30 UTC
Labels: Product: Highstock, Status: Pending reply
