### ISSUE TITLE
Column data labels are not contrasted with respect to plot background in case of Stacking and text outline is set to 0px.

### ISSUE THREAD

**Issue by tanmayshah95** [highcharts/highcharts#21001] opened 2024-04-12 10:39 UTC
#### Expected behaviour
Data labels for Normal stacking series should also be contrasted considering label's background and not only Series(Column) background when label is displayed outside (inside: false) and textOutline is removed.
Similar issue is filled #14014  but with different expected outcome and without mention of textOutline.
One more issue  #8472 found for Pie chart with similar expected outcome but seems fixed for respective chart. 

#### Actual behaviour
Data labels are getting contrasted as per Series color and are not visible due to same color as of Plot. For darker shades of color, data labels becomes white and are not visible due to white plot background.
This works correctly when stacking is not present. 

#### Live demo with steps to reproduce
[https://jsfiddle.net/tanmayshah95/ta3g7zn5/2/](url)
to make it simple i have only used single series even with stacking. Removing Stacking attribute solves the issue. But i have a case of multiple series being stacked and having dark shades of series color.

#### Product version
Highcharts 11.1.0

#### Affected browser(s)
All

**Comment by hubertkozik** [comment] 2024-04-15 07:32
Hi @tanmayshah95!
Thanks for bringing our attention to this bug, but sadly this a duplicate of https://github.com/highcharts/highcharts/issues/14014. I'll close your issue and let's continue the discussion in the original thread, because it is exactly the same problem as yours.

**Closed by hubertkozik** 2024-04-15 07:32 UTC
Labels: Duplicate
