### ISSUE TITLE
Datalabel issue with stacked column chart on logarithmic yaxis

### ISSUE THREAD

**Issue by susmithavenkatachalam** [highcharts/highcharts#16835] opened 2021-12-28 15:03 UTC
#### Expected behaviour
Data labels for stacked column should be visible even with logarithmic y-axis.When the first stack value is huge,it should automatically adjust the  data labels for the topmost stack and data labels for the topmost stack should be visible.

#### Actual behaviour
I am using stacked column chart and facing issue with data labels for the stacks on logarithmic y-axis. It is getting hidden when the stack size get auto adjusted based on logarithmic value.In the below link,topmost stack for the column 'Tactic3' is having a count:9, but since the stack size got shrink-ed due to value of the first stack(count:54) because of logarithmic axis,it makes the top most stack having  data label:9  invisible.

#### Live demo with steps to reproduce
https://jsfiddle.net/3ocd6xg5/3/

#### Product version
Highcharts Version:5.0.14

**Comment by raf18seb** [comment] 2021-12-29 09:24
Hi @susmithavenkatachalam, thank you for creating the ticket!

Note that this happens not only with a logarithmic axis, but with a linear axis as well. Hiding dataLabels is not related to axis' type, but available space for them.

For example, here the labels are visible on a logarithmic axis:
![image](https://user-images.githubusercontent.com/23310742/147646538-5c6e5cf7-496a-4c08-a742-b87dbc41f4b6.png)


But here, on a linear axis, some of the dataLabels are hidden because there is no space for them:
![image](https://user-images.githubusercontent.com/23310742/147646600-d7376568-c09d-4d6e-9536-a009cb3caebc.png)


The solution is simple:
- you can set [plotOptions.series.dataLabels.allowOverlap](https://api.highcharts.com/highcharts/plotOptions.series.dataLabels.allowOverlap) property to `true`, see demo: https://jsfiddle.net/BlackLabel/hy8fj52L/
- or you can move them manually (so they don't overlap) using [dataLabels.x](https://api.highcharts.com/highcharts/series.column.data.dataLabels.x) and [dataLabels.y](https://api.highcharts.com/highcharts/series.column.data.dataLabels.y) properties (per each point separately)

I'm closing the ticket as not a bug, but feel free to reopen or share any further insights.

**Closed by raf18seb** 2021-12-29 09:24 UTC
