### ISSUE TITLE
Chart axis labeled range changes when series toggled off then on

### ISSUE THREAD

**Issue by GaryGen** [highcharts/highcharts#6710] opened 2017-05-10 12:38 UTC
#### Expected behaviour

On a chart with a yAxis min set to a negative and a yAxis max set to a positive, toggling the series off then on should result in the displayed yAxis to be the same as the initial state.

#### Actual behaviour

On a chart with a yAxis min set to a negative and a yAxis max set to a positive, toggling the series off then on results in the maximum displayed value changing on some systems.

#### Live demo with steps to reproduce
http://jsfiddle.net/GaryGen/LLExL/7502/

1. Observe y axis. On my system, the initial state is that the tick range is from -250 to 500. (See "Affected browers" note below if this is not the case for your observation.)
2. Click on the series in the legend to hide it. The y axis will expand to take up the space of the hidden x axis, but the ticks will remain the same.
3. Click on the series in the legend to redisplay it. The x axis will redisplay causing the y axis to shrink and the ticks will modify to a range of -200 to 600.
4. Click on the series in the legend to hide it again. The y axis will expand and return to the -250 to 500 range.

#### Affected browser(s)

This was observed on Chrome Version 59.0.3071.36 (Official Build) beta (64-bit) on a Windows 10 computer.
Highcharts developer Sławomir Stypuła was unable to reproduce the problem using Chrome 58.0.3029.96 (64-bit) on MacOS Sierra stating that the maximum was always 600 for him.

**Comment by TorsteinHonsi** [comment] 2017-05-11 09:47
It depends on how the systems and browsers handle fonts and box sizes. Here's a demo that works on Chrome for Mac: http://jsfiddle.net/highcharts/LLExL/7510/

Anyway, this is a known behaviour in Highcharts. As stated under http://api.highcharts.com/highcharts/yAxis.tickPixelInterval, this option sets the _approximate_ pixel interval of the tick marks. Small variations may occur depending on if the axis is new, what size it had before etc.

**Comment by pawelfus** [comment] 2017-05-11 09:49
Related/duplicate of #4925

**Comment by TorsteinHonsi** [comment] 2017-05-12 10:11
Closed as duplicate.

**Closed by TorsteinHonsi** 2017-05-12 10:11 UTC
Labels: Undecided
