### ISSUE TITLE
 index of the last element on axis

### ISSUE THREAD

**Issue by gavristis** [highcharts/highcharts#17234] opened 2022-04-29 20:56 UTC
#### Expected behaviour
When chart has too many categories in limited space, it creates groups of n elements, displaying caption of every nth category. If the last group does not have all n categories in it, there should be no caption in the last group or this group should end on the last existing category.

#### Actual behaviour
Last caption represents index of the last tick in the dataset (245 in current example)

#### Live demo with steps to reproduce
http://jsfiddle.net/dq6s5eoa/
Try to resize browser window to reproduce.
#### Product version
latest

#### Affected browser(s)
all

**Comment by pawellysy** [comment] 2022-05-02 08:40
Hello @gavristis, thanks for creating the issue!

When you are defining the categories array for xAxis, each category starting from the index of 0 up to the last element replaces the numerical values. When there are no more categories, the labels ticks on the xAxis are numbers again.

There is a better solution to your problem. Instead of creating the categories array, you can use the `datetime` type: https://api.highcharts.com/highcharts/xAxis.type

Here is an example: http://jsfiddle.net/BlackLabel/8g3qr2m1/

Closing since this is not a bug.

PS: I strongly recommend you to contact with our support first, so that they could advice you to customize the chart to your needs.

**Closed** 2022-05-05 17:37 UTC
Labels: Type: Question
