### ISSUE TITLE
`stickOnContact` has confilct with `useHTML`

### ISSUE THREAD

**Issue by imrickywong** [highcharts/highcharts#13313] opened 2020-04-15 08:24 UTC
#### Expected behaviour
`stickOnContact` can still function well when the toolip is built with `useHTML`

#### Actual behaviour
If turn `useHTML` on, the `stickOnContact` works weriedly

#### Live demo with steps to reproduce

https://jsfiddle.net/Rickyyyyyyyyy/e7th9a4g/17/

#### Product version

v8.0.4

#### Affected browser(s)
All

**Comment by pawelfus** [comment] 2020-04-15 08:55
Thanks for reporting, but it's already reported: #13310

Closing as duplicate of #13310

**Closed by pawelfus** 2020-04-15 08:55 UTC
