### ISSUE TITLE
Set marker symbol doesn't work in column chart

### ISSUE THREAD

**Issue by softninja** [highcharts/highcharts#7340] opened 2017-11-01 03:10 UTC
#### Expected behaviour
The marker symbol set should be shown in legend

#### Actual behaviour
It always shows circle

#### Live demo with steps to reproduce
http://jsfiddle.net/3jyLbLoL/

#### Affected browser(s)
Chrome, etc

**Comment by pawelfus** [comment] 2017-11-02 10:13
Hi @softninja 

Thank you for reporting this bug. Column series doesn't have `marker` property, it's a bug in docs, which will be fixed in the next release

Closing as duplicate of #7315.

**Closed by pawelfus** 2017-11-02 10:13 UTC
