### ISSUE TITLE
Sankey, generatePoints crash

### ISSUE THREAD

**Issue by dusankocurek** [highcharts/highcharts#9109] opened 2018-10-02 19:29 UTC
#### Expected behaviour
The Sankey chart doesn't behave the same way, it crashes in some situations. I can't find how to display chart or fix the structure of my page/style to display Sankey properly.

#### Actual behaviour
I tried a couple of examples in my app, but in some cases (different structure of the page), the chart just crashes with the following error. 

If I display the same chart in a dialog, it displays properly. The problem is in the following function as the value of  **this.points** is undefined:

render: function() {
                var c = this.points;
                this.points = **this.points.**concat(this.nodes);
                e.seriesTypes.column.prototype.render.call(this);
                this.points = c
            }

TypeError: Cannot read property 'concat' of undefined
    at e.destroy (eval at 1066 (vendors.bundle.js:394), <anonymous>:19:255)
    at f (eval at 31 (vendors.bundle.js:579), <anonymous>:343:392)
    at e.remove (eval at 31 (vendors.bundle.js:579), <anonymous>:344:18)
    at e.remove (eval at 31 (vendors.bundle.js:579), <anonymous>:363:172)
    at e.update (eval at 31 (vendors.bundle.js:579), <anonymous>:345:90)
    at eval (eval at 31 (vendors.bundle.js:579), <anonymous>:339:354)
    at Array.forEach (<anonymous>)
    at a.each (eval at 31 (vendors.bundle.js:579), <anonymous>:28:379)
    at a.Chart.update (eval at 31 (vendors.bundle.js:579), <anonymous>:339:329)
    at HighChartNGController.$doCheck (eval at 102 (vendors.bundle.js:170), <anonymous>:128:20)

#### Product version
HighCharts v6.1.4

**Comment by dusankocurek** [comment] 2018-10-02 19:36
When I export the chart, it is displayed properly in the exported picture.

**Comment by pawelfus** [comment] 2018-10-03 08:39
Hi @dusankocurek 

Thanks for reporting this! Please, create a live demo with this issue. I see you use Angular, so please make sure it's not a bug in Angular (or Angular wrapper for Highcharts you use). If you don't use official wrapper for Highcharts in Angular, then please report issue to the author of that plugin, or recreate issue without this wrapper. Thanks!

**Comment by dusankocurek** [comment] 2018-10-24 19:17
Hi Pawel,
unfortunately, I am not able to share the source file.

Here is the config:

       var valueChartConfig = {
            title: {
                text: null
            },
            chart: {
                type: 'sankey',
                backgroundColor: 'transparent',
                animation: {
                    duration: 50
                }
            },
            legend: {
                enabled: false
            },
            exporting: {
                enabled: true
            },
            credits: {
                enabled: false
            },
            loading: {
                style: {
                    position: 'absolute',
                    backgroundColor: 'transparent',
                    opacity: 1,
                    textAlign: 'center'
                }
            },
        };

and here is an example of data I use:
0: ["3rd apps", "done", 5]
1: ["3rd apps", "in_progress", 109]
2: ["3rd apps", "todo", 0]
3: ["Backlog management", "done", 42]
4: ["Backlog management", "todo", 0]

I assume that problem is related to the update of the chart drawing.  When I display browser console there is relayout and that leads to suddenly displayed chart. Also, when I press Export or Print in local chart menu, the chart displays suddenly.

I tried even some demo data from samples, but the behavior is incorrect. Highchart which I have is  v6.2.0 (2018-10-17).

**Comment by pawelfus** [comment] 2018-10-25 12:04
Could you try to recreate issue in any sandbox? Your config looks fine. Without a live demo we can not debug and fix the issue.

**Comment by anajavi** [comment] 2018-11-06 21:03
#9300 is probably related.

**Comment by TorsteinHonsi** [comment] 2018-11-07 09:46
Most likely the same issue as #9300 that is now fixed. Closing this, please reopen if necessary.

**Closed by TorsteinHonsi** 2018-11-07 09:46 UTC
Labels: Cant reproduce, Pending reply
