### ISSUE TITLE
https://jshare.com.cn/temp/YeGTkj    Overlapping problems

### ISSUE THREAD

**Issue by weixingcai** [highcharts/highcharts#13324] opened 2020-04-16 06:38 UTC
#### Actual behaviour

The envelope overlaps the line of the next level corresponding to the chair, so that it is not clear which one corresponds to the envelope and which one corresponds to the chair
![issure](https://user-images.githubusercontent.com/48822299/79422672-dffc8100-7fef-11ea-9efe-887ef6509a7f.png)

#### Live demo with steps to reproduce
https://jshare.com.cn/temp/YeGTkj

**Comment by pawelfus** [comment] 2020-04-16 07:20
Thanks for reporting @weixingcai 

It's a duplicate of #11009. Closing as a duplicate.

**Closed by pawelfus** 2020-04-16 07:20 UTC

**Comment by weixingcai** [comment] 2020-04-16 08:14
The results given do not solve this problem, because we do not know the order of the data in the data, so there will be my question, the order of the data made by myself is better, may not appear, please see the link I submitted, there is a chair directly between the envelope and the envelope
![1](https://user-images.githubusercontent.com/48822299/79431578-37edb480-7ffd-11ea-80f0-db2d6dd4743b.png)

**Comment by pawelfus** [comment] 2020-04-16 08:25
@weixingcai - issue #11009 is still open and classified as a bug.
