### ISSUE TITLE
Scrolling issue since version 8 when overflow is set to scroll and custom height is set

### ISSUE THREAD

**Issue by MarkJungeblut** [highcharts/highcharts#13182] opened 2020-03-23 11:55 UTC
#### Expected behaviour
Tooltip of the point should be shown if the mouse is over it after scrolling

#### Actual behaviour
When we scroll down, the mouseover position is not calculated correctly and the tooltip of the wrong point is shown.
When leaving the container and hovering again it is working. 
It just fails directly after the scroll action while the mouse is positioned on the chart. 

![Screenshot jsfiddle](https://user-images.githubusercontent.com/50106912/77314178-739aa480-6d05-11ea-80bc-f83c03adbc42.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/zt5g4102/1/

- create div and place chart-container in it
- set style of div to overflow: scroll and height to any value 

#### Product version
Version 7.2.1, 8.0.*

### Notes: 
[EDIT]
**With version 7.2.0 everything works fine.
The problem came with version 7.2.1!** 

#### Affected browser(s)
Chrome
Firefox
Safari

**Comment by sebastianbochan** [comment] 2020-03-23 14:38
Hi @MarkJungeblut,
Thank you for reporting. It looks like as known bug, reported here: https://github.com/highcharts/highcharts/issues/12657.

Im closing the ticket as duplicate of https://github.com/highcharts/highcharts/issues/12657

**Comment by KacperMadej** [comment] 2020-09-07 11:55
The issue marked as a duplicated was checked as resolved, but this issue is not.

> The issue was closed as duplicate to this here but the error still persist with v.8.0.1
> 
> https://jsfiddle.net/bm5ycuve/7/
> The issue is present since v7.2.1, v8.0.*
> 
> We also got an alert that cross side scripting is possible since v.7.2.0 but we cannot upgrade until the problem is fixed.

_Internal note:_
Still doesn't work in 8.2.0 nor GitHub's master branch code (aka the next release candidate) - at the time of writing this comment.

**Comment by pawelfus** [comment] 2020-10-19 08:38
Tried to recreate this, failed:

![scroll](https://user-images.githubusercontent.com/1453926/96421411-08f80b80-11f7-11eb-9675-31a55bff7956.gif)

Tested on:
Chrome: Version 86.0.4240.80
OSX: 10.13.6

**Comment by khlieng** [comment] 2021-01-11 14:06
Fixed on master (#14768).

**Closed by khlieng** 2021-01-11 14:06 UTC
Labels: Product: Highcharts, Type: Regression
