### ISSUE TITLE
Datetime series on Xaxis: Distance between the bars increases and tick labels are also not clearly seen on scrolling

### ISSUE THREAD

**Issue by amruta30** [highcharts/highcharts#13709] opened 2020-06-13 11:59 UTC
#### Expected behaviour
Its expected that the intermediate tick labels as seen on the first run should be retained after scrolling.

#### Actual behaviour
Steps to reproduce:
1)	Hit the JS fiddle shared below
2)	Resize the result window towards left (I did it till about 958px)
3)	Intermediate tick labels are seen on the 1st run
4)	On scroll event, the tick labels disappear
Please refer the attached screenshots
![On scroll intermediate tick labels disappear](https://user-images.githubusercontent.com/7830487/84568199-5f61c300-ad9b-11ea-9ecd-ef7e5365cf8b.png)
![Intermediate tick labels](https://user-images.githubusercontent.com/7830487/84568200-612b8680-ad9b-11ea-9b64-564fd8c3cd95.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/amrutaJgtp/nqke23mr/6/

#### Product version
Tested on v6.1.1
But also reproduced on latest version v8.1.1

#### Affected browser(s)
All

**Comment by pawelfus** [comment] 2020-06-15 13:57
Thanks for reporting @amruta30 

This is expected behaviour: initial rendering and all subsequent ones (e.g. scrolling, hiding/showing series from legend) might vary. Full explanation why it works that way can be found in this answer: https://github.com/highcharts/highcharts/issues/13451#issuecomment-625734460 (see "longer explanation" part). In your case, initial rendering reserves for xAxis 938px, while after rendering 871px is available. For yAxis, initial size=280px, after rendering size=239px. In your case, I recommend to check `tickPixelInterval` option.

Marking as duplicate of #13451

**Comment by pawelfus** [comment] 2020-06-25 08:01
Closing as duplicate of #13451

**Closed by pawelfus** 2020-06-25 08:01 UTC
Labels: Type: Duplicate
