### ISSUE TITLE
In line charts, duration does not work when dynamically adding values ​​to the series since v8.0.3.

### ISSUE THREAD

**Issue by nakagawata** [highcharts/highcharts#14423] opened 2020-10-26 02:13 UTC
#### Expected behaviour
Even if the value of series changes dynamically, duration should work properly.

#### Actual behaviour
After upgrading from v8.0.2 to v8.0.3,
If the value of series changes dynamically, duration will not work.

#### Live demo with steps to reproduce
v8.0.2
[https://codesandbox.io/s/line-chart-duration-working-v802-hmc9s](https://codesandbox.io/s/line-chart-duration-working-v802-hmc9s)
![802](https://user-images.githubusercontent.com/54659043/97127143-322b1580-177c-11eb-9e63-741fa2e10933.gif)

v8.0.3
[https://codesandbox.io/s/line-chart-duration-not-working-v803-ov704?file=/src/main.js](https://codesandbox.io/s/line-chart-duration-not-working-v803-ov704?file=/src/main.js)
![803](https://user-images.githubusercontent.com/54659043/97127145-33f4d900-177c-11eb-961c-c8c91013d506.gif)

#### Product version
highcharts: 8.0.3
highcharts-vue: 1.3.5
※ The same symptom appears in the latest highcharts v8.2.2.
※ The same symptom appears in the "type:area , spline".
※ duration works even after v8.0.3 for the other types such as pie and bar.

#### Affected browser(s)
Chrome 86.0.4240.111

**Comment by nakagawata** [comment] 2020-10-26 04:14
Duration works if there is data in the series from the beginning.
but duration is not working even if I add data to a series that has data from the beginning.

#### v8.0.2 ( Duration is working)
[https://codesandbox.io/s/line-chart-duration-not-working-initial-series-v802-zei0k](https://codesandbox.io/s/line-chart-duration-not-working-initial-series-v802-zei0k)

#### v8.0.3 (Duration is not working)
[https://codesandbox.io/s/line-chart-duration-not-working-initial-series-v803-zx6hr](https://codesandbox.io/s/line-chart-duration-not-working-initial-series-v803-zx6hr)

**Comment by pawelfus** [comment] 2020-10-26 10:06
Thank you for reporting this bug @nakagawata 

Under the hood, this is duplicate of #14362 (the same regression). Closing as duplicate of #14362

**Closed by pawelfus** 2020-10-26 10:06 UTC
