### ISSUE TITLE
Datalabel incorrectly appears over tooltip when html mode is used for datalabel and tooltip

### ISSUE THREAD

**Issue by ollivih** [highcharts/highcharts#21404] opened 2024-06-26 08:26 UTC
#### Expected behaviour
Tooltips should appear over all other content in the chart, so that the tooltips are readable.

#### Actual behaviour
As shown by this screenshot, the datalabel text appears over the tooltip text and thus the tooltip text is not readable.

![image](https://github.com/highcharts/highcharts/assets/86189287/616a33bc-8869-4993-b3ae-f199ebc9bd0a)

#### Live demo with steps to reproduce
https://jsfiddle.net/xe8oupfh/

Following configuration is used:
```
{
	"tooltip": {
		"useHTML": true,
		"format":  "custom tooltip"
	},
	"plotOptions": {
		"series": {
			"dataLabels": {
				"enabled": true,
				"useHTML": true,
				"format": "custom datalabel"
			}
		}
	},
	"series": [
		{
			"type": "bar",
			"data": [
				{
					"y": 1
				},
				{
					"y": 2
				}
			]
		}
	]
}
```

#### Product version
Highcharts JS v11.4.3

#### Affected browser(s)
At least Google Chrome.

**Comment by hubertkozik** [comment] 2024-06-26 13:12
Hi @ollivih! This is how the `useHTML` flag works. When using HTML over the SVG, then all SVG elements are below HTML tags. In that case, create an HTML tooltip too.

**Live demo**: https://jsfiddle.net/BlackLabel/hL7f5uzn/

Closing as duplicate of https://github.com/highcharts/highcharts/issues/2158.

**Closed by hubertkozik** 2024-06-26 13:12 UTC
Labels: Duplicate
