### ISSUE TITLE
Boost mode retina support (high DPI displays)

### ISSUE THREAD

**Issue by 52flutter** [highcharts/highcharts#16760] opened 2021-12-06 10:50 UTC
#### Expected behaviour
Boost mode retina support (high DPI displays)

#### Actual behaviour
not support

#### Live demo with steps to reproduce

https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/boost/column

#### Product version

9.3.2
#### Affected browser(s)
all

**Comment by 52flutter** [comment] 2021-12-06 10:51
Similar problems.
https://github.com/highcharts/highcharts/issues/10096
 But it didn't solve

**Comment by raf18seb** [comment] 2021-12-06 14:44
Hi @52flutter!
Let's reopen the original ticket.

Closing as a duplicate of https://github.com/highcharts/highcharts/issues/10096

**Closed by raf18seb** 2021-12-06 14:44 UTC
