### ISSUE TITLE
HighChart Could not found in build.gradle

### ISSUE THREAD

**Issue by saravanakumarRamraj** [highcharts/highcharts#16142] opened 2021-08-03 21:30 UTC
#### Expected behaviour
"implementation (name: 'highcharts-release', ext:'aar')" , using android compile sdk 30 and arcticfox studio implement highchart library, get highchart graph 

#### Actual behaviour
its build fine but runtime error will be occur ,the error message following, 
"Could not find :highcharts-release:.
Required by:
    project :app
Search in build.gradle files"

but earlier its working fine

#### Product version
using .aar lib

**Comment by pawelfus** [comment] 2021-08-12 07:44
Closing as duplicate of #16167

**Closed by pawelfus** 2021-08-12 07:44 UTC
