### ISSUE TITLE
Legend enable/disable not working properly with responsive rules

### ISSUE THREAD

**Issue by mynameiswhat1** [highcharts/highcharts#6310] opened 2017-01-27 17:19 UTC
Hello,
Please check the following fiddle

https://jsfiddle.net/g0ryva91/5/

And follow these steps:

**Run -> click 500px -> click 400px -> click 200 px -> click 500 px**

After all these step you will notice that the legend is disable, which is not according to the rules since, for the condition of maxHeight: 3000, the legend was supposed to be enabled and the 500px click falls under this rule.
Why is this happening?
Is this a bug?
Is it related somehow to :  

https://github.com/highcharts/highcharts/issues/6291

or

http://forum.highcharts.com/post131726.html#p131726

Thank you very much for your help.

**Comment by mynameiswhat1** [comment] 2017-01-30 11:28
Hello,
Any news on this subject?
Thank you very much.

**Comment by sergiomcunha** [comment] 2017-01-30 18:18
I'm also having this issue..

**Comment by TorsteinHonsi** [comment] 2017-01-31 09:34
Duplicate of #6291 (fixed).

Here's a demo with the fix applied: http://jsfiddle.net/highcharts/g0ryva91/6/

**Closed by TorsteinHonsi** 2017-01-31 09:34 UTC
Labels: Duplicate
