### ISSUE TITLE
Export PDF with russian words (offline-exporting)

### ISSUE THREAD

**Issue by magistr4815** [highcharts/highcharts#16058] opened 2021-07-16 10:28 UTC
Hello everybody.
I have a problem.
I am using the graph in Russian. I export a pdf file and get artifacts in it instead of Russian symbols.
English characters are working correctly.
**I use module - offline-exporting.js, but if i disable this module, i don't have this error.**
But **i must use this module** (offline-exporting.js), because i have big charts and otherwise I will get error 413 (large and heavy request to the server).

A live example can be found here - https://jsfiddle.net/6p4egy27/
A live example without offline-exporting.js (no errors) - https://jsfiddle.net/BlackLabel/hk1b5qzr/

I think this is a bug in the module, or you can show me how to fix it.
Thank you!
![ksnip_20210714-141909](https://user-images.githubusercontent.com/8629826/125934120-942b8b30-9244-4e52-9872-ef19c292063f.png)
![ksnip_20210714-141914](https://user-images.githubusercontent.com/8629826/125934136-e7ef371b-488f-4416-9138-8802ed201605.png)

**Comment by khlieng** [comment] 2021-07-16 11:07
This sounds like a duplicate of #6417, you can find some more discussion and suggested solutions there.

**Closed by khlieng** 2021-07-16 11:07 UTC
Labels: Type: Duplicate
