### ISSUE TITLE
Histogram chart, xAxis is missing maximum value

### ISSUE THREAD

**Issue by ma1990213** [highcharts/highcharts#13105] opened 2020-03-07 09:28 UTC
#### Expected behaviour
xAxis shows the maximum value

#### Actual behaviour
xAxis is missing maximum value

#### Live demo with steps to reproduce
https://jshare.com.cn/temp/UIGGwg
![01](https://user-images.githubusercontent.com/17824026/76140794-e4508880-6098-11ea-9f3f-174d3f689c72.png)
In this set of data, the maximum value is 4.4, which is not shown on the xAxis

#### Product version
"highcharts": "8.0.2",
"highcharts-vue": "^1.3.5"

#### Affected browser(s)
Google Chrome 80.0.3987.12

**Comment by sebastianbochan** [comment] 2020-03-09 09:34
Hi @ma1990213,
Thank you for reporting. You can use a few options (tickInterval, tickPositions, tickPositioner) which allows you to control ticks on an axis.

Docs:
- https://api.highcharts.com/highcharts/xAxis

Im closing this ticket as not a bug.

**Closed by sebastianbochan** 2020-03-09 09:34 UTC
