### ISSUE TITLE
Drill down from bar chart

### ISSUE THREAD

**Issue by royigoldi** [highcharts/highcharts#6061] opened 2016-11-30 16:18 UTC
Hi,

I implemented bar chart with 2 plugins: GROUPED CATEGORIES, CUSTOM EVENTS:
I want to implement drilldown to pie chart when user click on the grouped catagory(x axis label)
I got the clicked event on the relevant sub category but it is avg element and i don't know how to get the chart itself:

![image](https://cloud.githubusercontent.com/assets/20413250/20760624/32ce19b8-b729-11e6-8ca2-02179826bc4f.png)

can you help me, please?

![image](https://cloud.githubusercontent.com/assets/20413250/20760709/5a9803be-b729-11e6-9183-c4adbcac164e.png)

**Comment by jon-a-nygaard** [comment] 2016-12-01 10:41
Hi @royigoldi , if you could supply a simple replication of you issue, for instance in [JSFiddle](https://jsfiddle.net/)? That would make it much easier for us to pinpoint what you need.

**Comment by royigoldi** [comment] 2016-12-01 13:34
I working in angular 2 project... 
here is the link...

http://jsfiddle.net/TFhd7/1063/

but I couldn't success to load the custom event plugin, can you help with this and test the example...

Thanks,
Royi

**Comment by jon-a-nygaard** [comment] 2016-12-05 08:47
@royigoldi You can access the chart either by storing it as a variable beforehand, or collect it from `Highcharts.charts` property, like in [this example](http://jsfiddle.net/jon_a_nygaard/8cxw345c/2/)

**Comment by jon-a-nygaard** [comment] 2017-06-06 06:16
Closing this as it is considered not a bug.  Should anyone have further information on the issue, please give a comment.

**Closed by jon-a-nygaard** 2017-06-06 06:16 UTC
Labels: Not a bug, Pending reply
