### ISSUE TITLE
Charts with multiaxes and big numbers not showing correctly

### ISSUE THREAD

**Issue by Llorx** [highcharts/highcharts#5710] opened 2016-09-20 16:24 UTC
#### Expected behaviour
The chart will be rendered without "blank" spaces

#### Actual behaviour
Half of the chart is empty, without values.

#### Live demo with steps to reproduce
http://jsfiddle.net/voqxkb3m/1/

#### Affected browser(s)
Any, I guess

**Comment by pawelfus** [comment] 2016-09-21 08:27
Could you elaborate these "blank" spaces? This is how the chart is rendered in Chrome (osx): 
![screen shot 2016-09-21 at 10 19 13](https://cloud.githubusercontent.com/assets/1453926/18703126/def1001a-7fe4-11e6-8e82-5f8d42a3fed8.png)

If you refer to the top half of the chart, then it may be changed by setting `yAxis.maxPadding`, demo for you: http://jsfiddle.net/voqxkb3m/4/

Alternatively, you can set `chart.alignTicks` to false: http://jsfiddle.net/voqxkb3m/5/

*Internal note:*
Chart with just one axis: http://jsfiddle.net/yLhwg8oL/ I guess this is an another duplicate of #4773 or at least related to #4580.

**Comment by Llorx** [comment] 2016-09-22 07:48
Yes, I'm talking about top half. This is not the behaviour I expect when using padding of 0.05 (default). This is notably more than 0.05 padding. Maybe the paddings of all axes are combined? Because with one axis (and multiple series) the padding is correct. I don't like to not have any padding, or not have the ticks aligned to solve this.

**Comment by TorsteinHonsi** [comment] 2016-09-22 10:10
@pawel When multiple axes are present, the chart pre-computes a matching `tickAmount` in order to find the best way to align the axes.

Another way to resolve it is to set a lower `tickPixelInterval` for all Y axes. It gives the tick logic more options to find a set of ticks that matches the data: http://jsfiddle.net/voqxkb3m/7/

**Comment by Llorx** [comment] 2016-09-23 07:29
Still showing a gap of multiple ticks: http://jsfiddle.net/voqxkb3m/8/

**Comment by TorsteinHonsi** [comment] 2016-09-23 09:32
Yes, it first computes how many ticks it should lay out, then it figures out how to best lay out the data with that number of ticks. 

Broken down, say that you have a column chart where the max data is 6, and you have a reqirement of eleven ticks. Now the best fit would be to lay out the ticks on 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 and 10. But in this case we will get a top padding of 4, which seems too much. But if we try to lay out the ticks on every half, we only get to 5. We could lay out ticks at 0, 0.7, 1.4, 2.1 etc., but that doesn't really look good...

**Comment by Llorx** [comment] 2016-09-24 09:36
And how can I tell it to have a requirement of enough ticks (6 in this case) to fit the data and still be a goodlooking axis?

**Comment by TorsteinHonsi** [comment] 2016-09-26 07:42
You can use the [tickAmount](http://api.highcharts.com/highcharts/yAxis.tickAmount) option if you have control of the data up front.

**Comment by Llorx** [comment] 2016-09-29 07:38
Hm, tickAmount is a good solution too. Will look into it.

**Comment by TorsteinHonsi** [comment] 2016-10-28 11:56
Duplicate of #4580

**Closed by TorsteinHonsi** 2016-10-28 11:56 UTC
Labels: Bug
