### ISSUE TITLE
Heat map in horizontal way

### ISSUE THREAD

**Issue by Hamzakhann** [highcharts/highcharts#14994] opened 2021-01-26 12:50 UTC
![image](https://user-images.githubusercontent.com/32258466/105847028-e1d38600-5ffe-11eb-955b-f06d26886821.png)

I wanna create this type of heapmap how can I achieve this

**Comment by KacperMadej** [comment] 2021-01-26 13:48
Hi @Hamzakhann 

You could get this layout through the series data: https://jsfiddle.net/BlackLabel/896s3xqa/

Another option could be to use stacked bar series: https://jsfiddle.net/BlackLabel/wjsyfzL9/

Through styling of dataLabels or adding [custom rendered elements](https://www.highcharts.com/docs/advanced-chart-features/freeform-drawing) you could get closed to the desired design.

The issue is more about getting a chart look and style than adding anything new, so this is not a valid feature request and for help with chart styling through API you could reach out to our technical support: https://www.highcharts.com/blog/support/

Closing as the issue should be resolved through the support but could be reopened in case further information about the requested feature will be provided.

**Closed by KacperMadej** 2021-01-26 13:48 UTC
Labels: Type: Feature Request
