### ISSUE TITLE
Impossible to select point if the series is in boots mode

### ISSUE THREAD

**Issue by jk171505** [highcharts/highcharts#12074] opened 2019-09-26 14:45 UTC
If the boost mode is applied, the point doesn't have a `select` method. How such point can be selected so its marker becomes visually distinguishable?

**Comment by sebastianbochan** [comment] 2019-09-26 15:05
Hi @jk171505,
Thank you for contacting us. Im closing this topic as duplicate of https://github.com/highcharts/highcharts/issues/9004

**Closed by sebastianbochan** 2019-09-26 15:05 UTC
