### ISSUE TITLE
Gantt: render incorrect plot view when collapsing

### ISSUE THREAD

**Issue by dcaudillo99** [highcharts/highcharts#18477] opened 2023-02-10 23:15 UTC
#### Expected behaviour
When collapsing or expanding series the plot area shows the data corectly

#### Actual behaviour
When collapsing, the view of the charts breaks

#### Live demo with steps to reproduce
https://jsfiddle.net/anLgh9mw/4/

- Collapse the first series ('New offices')

![gantt-collapse-issue](https://user-images.githubusercontent.com/98132916/218220079-36cc6ffd-b490-4893-afca-a01228939699.gif)

**Comment by bm64** [comment] 2023-02-13 21:46
Hello @dcaudillo99 and thanks for contacting us.

I'm closing this issue as a duplicate of #13884. Feel free to leave your feedback in the original ticket.

**Closed by bm64** 2023-02-13 21:46 UTC

**Comment by hihajdus** [comment] 2023-02-15 08:51
Hi @dcaudillo99,
After investigating the issue, the problem was the scroll used in [yAxis](https://api.highcharts.com/gantt/yAxis) which is undocumented in the API, and overwrited options set in [chart.scrollablePlotArea](https://api.highcharts.com/gantt/chart.scrollablePlotArea). 

[Demo](http://jsfiddle.net/BlackLabel/xtfdysre/)
