### ISSUE TITLE
Dynamic chart height with svg patterns causes multiple load animation

### ISSUE THREAD

**Issue by erdihu** [highcharts/highcharts#16789] opened 2021-12-15 12:22 UTC
#### Expected behaviour
A bar chart with dynamic height, when used together with pattern fill module which renders a patterned bar, should show the loading animation only once.

#### Actual behaviour
A bar chart with dynamic height, when used together with pattern fill module which renders a patterned bar, shows loading animation two times.

#### Live demo with steps to reproduce

http://jsfiddle.net/dxa6sbze/

#### Product version

Highcharts v9.3.2

#### Affected browser(s)
All browsers

**Comment by raf18seb** [comment] 2021-12-16 11:34
Hi @erdihu, thank you for writing to us with your issue.

You can disable the update animation, see the API (4th update argument): https://api.highcharts.com/class-reference/Highcharts.Chart#update
```js
this.update({
    chart: {
        height: categoryHeight * this.pointCount + (this.chartHeight - this.plotHeight)
    }
}, null, null, false)
```

Demo: http://jsfiddle.net/BlackLabel/aofw1evz/

I'm closing the ticket as not a bug, but feel free to share any further thoughts or comments.

**Closed by raf18seb** 2021-12-16 11:34 UTC
