### ISSUE TITLE
plotLines are not limited to axis in Highstock

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#8630] opened 2018-07-16 19:59 UTC
#### Expected behaviour
Plot lines should look like in Highcharts: http://jsfiddle.net/BlackLabel/dLkcm1bh/

#### Actual behaviour
Plot lines occupy the entire height of plot area: http://jsfiddle.net/BlackLabel/8dhL90st/

#### Product version
Highstock v6.1.1

#### Affected browser(s)
All

**Comment by pawelfus** [comment] 2018-07-17 08:37
Closing as duplicate of #6644

**Closed by pawelfus** 2018-07-17 08:37 UTC
Labels: Bug, Highstock
