### ISSUE TITLE
findNearestPointBy is ignored when using a shared pointer on mixed series type

### ISSUE THREAD

**Issue by RobertJohnston** [highcharts/highcharts#6702] opened 2017-05-09 10:46 UTC
#### Expected behaviour

When having a chart with mixed series type (column and line), setting findNearestPointBy to 'x' for the line series (it is set to 'x' by default for column) should make highcharts only using the 'x' mouse position to determine the nearest position on the line series.

This problem only seems to occur on column/line combination, it doesn't occurs with only lines series.

#### Actual behaviour

The 'y' mouse position is also taken into account for determining the nearest point for the line series.

#### Live demo with steps to reproduce

On [this official example](http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/tooltip/shared-true-mixed-types/) put your mouse at the top bar of the April bar, the highlighted point will be the one of March. If you move down your mouse of the bar close to the April point, the April point will be highlighted.

In [this modified version](http://jsfiddle.net/0hvu2gyu/1/) of the official example, I've added the findNearestPointBy series option and set it to 'x' for both series and the previously described behavior hasn't changed while it should have.

But if I change the column series type to line type as [shown here](http://jsfiddle.net/0hvu2gyu/2/), the behavior is has expected. [Even when removing findNearestPoint](http://jsfiddle.net/0hvu2gyu/3/).

This problem really seems related to mixed series type.

#### Affected browser(s)

Firefox (latest) and Chrome (latest). It doesn't seems browser related.

**Comment by TorsteinHonsi** [comment] 2017-05-10 09:18
@jon: Shared tooltip is broken again also. Should respond to hovering outside the columns.

**Comment by jon-a-nygaard** [comment] 2017-05-12 10:38
Caused by the same issue as in #6687, which will be fixed in next maintenance release. Take a look at mentioned issue for potential workaround.

**Closed by jon-a-nygaard** 2017-05-12 10:38 UTC
