### ISSUE TITLE
Series is cut if tickAmount is set

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#9841] opened 2019-01-09 08:59 UTC
#### Expected behaviour
The chart should look like in version: 6.0.3:

http://jsfiddle.net/BlackLabel/19Lr5ovp/

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/bmgwcv6z/

#### Product version
Highcharts 7.0.1

#### Affected browser(s)
All

**Comment by KacperMadej** [comment] 2019-01-10 22:50
The problem is caused by xAxis having by default `startOnTick` and `endOnTick` set to `false`, but after using `tickAmount` both options will not be respected as new min and max for the axis are being set that are based on ticks.

There's still a problem with series cut on the min side: http://jsfiddle.net/BlackLabel/bmgwcv6z/6/

_Internal note:_
Maybe choosing smaller one out of new and old min (and similar for max) in case start/endOnTick is false would be enough? In code:

https://github.com/highcharts/highcharts/blob/fab9826847ff3e2cce3dcff38bebcb77d4175445/js/parts/Axis.js#L4821-L4822

I could run some tests tomorrow to confirm. Right now, the above demo forces me to reopen.

**Comment by TorsteinHonsi** [comment] 2019-01-11 08:41
Thanks! I don't fully understand how we end up with cropped tickPositions in the first place.

**Comment by KacperMadej** [comment] 2019-01-14 14:18
It's been like this since the very beginning (endOnTick ignored) - [demo for v4.1.0](http://jsfiddle.net/BlackLabel/tLq62byx/) and my commit played along with the used logic (making startOnTick ignored). Nevertheless, time to fix this - PR with the fix committed below.

**Closed** 2019-01-16 07:54 UTC
Labels: Regression
