### ISSUE TITLE
Chart.update() modifies original data

### ISSUE THREAD

**Issue by soetji** [highcharts/highcharts#13415] opened 2020-05-01 17:03 UTC
#### Expected behaviour
Original data should stay the same.

#### Actual behaviour
Original data changed.

#### Live demo with steps to reproduce

https://jsfiddle.net/soetji/k507z8rh/

Open Chrome Console.
Run the fiddle.
Console log shows the original data "29.9".
Click on the "Test" button.
Console log shows the original data "99.9".

#### Product version

Latest

#### Affected browser(s)
Chrome and most probably other browsers

**Comment by Arut42** [comment] 2020-05-01 17:38
the same behavier happens on chart.series[0].setData( Newdata );

Im using the workaround chart.series[0].setData( $.extend(true, [],Newdata) );
and initalize series.data with empty array like
chart:{
 series: [
  {
   data:[]
  }
]}

**Comment by sebastianbochan** [comment] 2020-05-04 10:38
Hi @soetji,
Thank you for reporting the issue. It's a duplicate of #4259 - see discussion there.

**Closed by sebastianbochan** 2020-05-04 10:38 UTC
