### ISSUE TITLE
Grouping by year creates an extra column 

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#7132] opened 2017-09-07 15:45 UTC
#### Expected behaviour

Grouping doesn't create unnecessary columns.

#### Actual behaviour

After data grouping ( yearly ), additional column is created on the right side of chart.

#### Live demo with steps to reproduce
http://jsfiddle.net/kkulig/gpg9d4es/

Click on the "Annual" button.

#### Workaround:

Manualy set tick positions
Live working: http://jsfiddle.net/gmmq2r7y/

**Comment by pawelfus** [comment] 2017-09-08 09:36
Closing as duplicate of #5692

**Closed by pawelfus** 2017-09-08 09:36 UTC
Labels: Bug, Highstock
