### ISSUE TITLE
"Invalid negative value for <rect> attribute width" on Navigator when updating time-series chart with live data

### ISSUE THREAD

**Issue by rafaeljegundo** [highcharts/highcharts#5041] opened 2016-02-15 12:21 UTC
We are using Highstock to display time-series data, from historical data with granularity of a day, to real-time data with one minute granularity.

Recently we noticed we were being affected by https://github.com/highcharts/highcharts/issues/4935, so we upgraded our Highstock version from 2.1.10 to 4.2.3. However this update brought another issue:

When realtime data is received after the first chart loading, datapoints will generate the following error while being added to the data series:

`Error: Invalid negative value for <rect> attribute width="-22"`

That `<rect>` element belongs to the navigator. The effects can be visible in some cases:

![captura de ecra 2016-02-15 as 12 14 45](https://cloud.githubusercontent.com/assets/51695/13048492/1744790a-d3de-11e5-9c45-8d370778cce4.png)

Here is a fiddle where the problem can be reproduced: http://jsfiddle.net/eesd0fro/6/

Any suggestions on how can we handle this are very much welcome, as we are now having to pick between the lesser of two issues.

**Comment by jon-a-nygaard** [comment] 2016-02-15 14:21
Thanks for reporting. We will look into this, and get back to you with a fix as soon as possible.

_Internal note: Issue caused by the zoomedMin is greater than zoomedMax in Scroller.render._

**Comment by jon-a-nygaard** [comment] 2016-02-15 15:19
This issue will be fixed in the upcoming maintenance release 4.2.4. For those in need of an immediate workaround, can try the suggested fix below.

**Workaround:**
In the highstock.src.js look for the function Scroller.render around line 21982 and do the following replacement:
```javascript
// Replace the following
scroller.zoomedMin = mathMax(scroller.fixedWidth ? scroller.zoomedMax - scroller.fixedWidth : mathMin(pxMin, pxMax), 0);

// With this
scroller.zoomedMin = mathMin(mathMax(scroller.fixedWidth ? scroller.zoomedMax - scroller.fixedWidth : mathMin(pxMin, pxMax), 0), navigatorWidth);
```

**Comment by rafaeljegundo** [comment] 2016-02-15 16:33
@jon-a-nygaard Thanks very much for the quick response. I was able to test the workaround and it works nicely. :+1:

**Comment by jon-a-nygaard** [comment] 2016-02-16 09:37
@rafaeljegundo Glad the fix worked out for you.

**Closed** 2016-02-26 12:52 UTC
Labels: Bug, Fix suggested, Highstock

**Comment by qingweibinary** [comment] 2016-04-13 01:33
Hi, can I know when would this fix be release?

**Comment by TorsteinHonsi** [comment] 2016-04-13 06:58
It will be released probably within a week.

**Comment by marco25d** [comment] 2017-10-16 08:26
Error: Error: <rect> attribute width: A negative value is not valid. ("-150")
It worked for a while without showing any problems then it starded to not producing the bar chert and showing this error. May someone help me? I'm a beginner in this field. Thank you very much.
Code D3:
                                        var data = respose; //file json
                                        console.log(data); 
                                                                       
                                        var chartDiv = document.getElementById("chart1");
                                        var svg = d3.select(chartDiv).append("svg");
                                         
                                        function redraw(){
                                        d3.selectAll('svg > g > *').remove();
                                        var width = chartDiv.clientWidth;
                                        var height = chartDiv.clientHeight;

                                        svg
                                          .attr("width", width)
                                          .attr("height", 400);
                                            
                                        var margin = {top: 0, right: 50, bottom: 0, left: 100},
                                               width = +svg.attr("width") - margin.left - margin.right,
                                               height = +svg.attr("height") - margin.top - margin.bottom;

                                        var tooltip = d3.select("body").append("div").attr("class", "toolTip");

                                        var x = d3.scaleLinear().range([0, width]);
                                        var y = d3.scaleBand().range([height, 0]);

                                        var g = svg.append("g")
                                                .attr("transform", "translate(" + margin.left + "," + margin.top + ")");
                                         
                                         data.sort(function(a, b) { return a.value - b.value; });
  
                                        x.domain([0, d3.max(data, function(d) { return d.value; })]);
                                        y.domain(data.map(function(d) { return d.area; })).padding(0.1);

                                        g.append("g")
                                            .attr("class", "x axis")
                                            .attr("transform", "translate(0," + height + ")")
                                            .call(d3.axisBottom(x).ticks(5).tickFormat(function(d) { return parseInt(d); }).tickSizeInner([-height]));

                                        g.append("g")
                                            .attr("class", "y axis")
                                            .call(d3.axisLeft(y));

                                        g.selectAll(".bar")
                                            .data(data)
                                          .enter().append("rect")
                                            .attr("class", "bar")
                                            .attr("x", 0)
                                            .attr("height", y.bandwidth())
                                            .attr("y", function(d) { return y(d.area); })
                                            .attr("width", function(d) { return x(d.value); })
                                            .on("mousemove", function(d){

                                                tooltip
                                                  .style("left", d3.event.pageX - 50 + "px")
                                                  .style("top", d3.event.pageY - 90 + "px")
                                                  .style("display", "inline-block")
                                                  .html((d.area) + "<br><span>" + (d.value) + " post " + "</span>");
                                            })
                                                .on("mouseout", function(d){ tooltip.style("display", "none");});
                                        }
                                        redraw();

                                        window.addEventListener("resize", redraw);

**Comment by jon-a-nygaard** [comment] 2017-10-16 08:41
Hi @marco25d 
It seems that your issue is with D3, which we can not provide support on. I suggest that you create an issue on https://github.com/d3/d3/issues

**Comment by shreyashkaushal** [comment] 2019-11-14 05:52
having the same issue with my react app , trying to figure it out but didn't get any solution yet. please help me out in this.
[sample.docx](https://github.com/highcharts/highcharts/files/3844801/sample.docx)

**Comment by jon-a-nygaard** [comment] 2019-11-14 10:11
Hi @shreyashkaushal, from the sample code you posted it looks like you are using a package named [react-google-charts](https://www.npmjs.com/package/react-google-charts), which is not related to Highcharts JS.
I advice you to contact the maintainers of the package to get qualified help on your issue.
