### ISSUE TITLE
Stockchart mouse scroll to zoom

### ISSUE THREAD

**Issue by williamwongys** [highcharts/highcharts#17090] opened 2022-03-15 10:38 UTC
In most stock chart application, zooming can be achieved using mouse scroll, i.e., by scrolling the mouse, more or less bars will be shown within the same window. 

[https://www.highcharts.com/forum/viewtopic.php?f=12&t=48321](url)

**Comment by pawellysy** [comment] 2022-03-15 11:49
Closing as a duplicate of https://github.com/highcharts/highcharts/issues/16658

**Closed by pawellysy** 2022-03-15 11:49 UTC
Labels: Type: Feature Request
