### ISSUE TITLE
Reflow(null) error out after chrome and edge upgrade for print, but working in firefox

### ISSUE THREAD

**Issue by karthikn2406** [highcharts/highcharts#21459] opened 2024-07-03 12:28 UTC
#### Expected behaviour

The below method will be called on print this will accomdate chart without truncating
   export function reflowCharts() {
     charts.filter(c => c).forEach(c => c.reflow(null));
   }

#### Actual behaviour
Print preview itself not launching, showing error when the reflow code called
 
Chrome showing : error_code : status_breakpoint

#### Product version
8.3.2 we tried with latest version too

#### Affected browser(s)
Version 126.0.6478.127 (Official Build) (64-bit)

**Comment by karolkolodziej** [comment] 2024-07-05 13:10
Hi @karthikn2406! 

Thank you for taking the time to report the issue! It looks like a duplicate of: https://github.com/highcharts/highcharts/issues/16931

**Closed by karolkolodziej** 2024-07-05 13:10 UTC
