### ISSUE TITLE
LineWidth on Hover

### ISSUE THREAD

**Issue by 45kicks** [highcharts/highcharts#4257] opened 2015-06-02 21:08 UTC
You can set a plotOptions.series.lineWidth of zero to a line chart to make the line invisible, but you cannot set the plotOptions.series.states.hover.lineWidth value to zero, instead you have to use a workaround of .001 or some other really small number.

http://jsfiddle.net/et80rmL1/1/

If you uncomment out the "lineWidth: 0.001" and run it you can see the line stays invisible on however, while if it has a value of zero it is visible on hover.

**Comment by highslide-software** [comment] 2015-06-03 11:58
A cleaner workaround is to use the `lineWidthPlus` option: http://jsfiddle.net/highcharts/et80rmL1/2/

**Comment by 45kicks** [comment] 2015-06-03 13:24
Thanks for the info, hadn't considered that.

**Comment by KacperMadej** [comment] 2018-10-03 16:00
The option resolving the problem is documented - https://api.highcharts.com/highcharts/series.line.states.hover.lineWidthPlus
This doesn't look like a bug.
Closing as resolved.

If you want for this issue to be reopened please leave a comment with more info about the issue.

**Closed by KacperMadej** 2018-10-03 16:00 UTC
Labels: Bug, Priority:Low
