### ISSUE TITLE
When a series with a large scale is zoomed in and the zooming is reset the X-Axis doesn't display the labels properly.

### ISSUE THREAD

**Issue by gayanj** [highcharts/highcharts#7903] opened 2018-02-22 10:51 UTC
#### Expected behaviour
X-Axis labels and values should be displayed properly after zooming is reset.

#### Actual behaviour
When a series with a large scale is zoomed in and the zooming is reset the X-Axis doesn't display the labels properly.

#### Live demo with steps to reproduce

![image](https://user-images.githubusercontent.com/5906152/36534335-4613eb9a-17ec-11e8-926b-e497823d5bed.png)

#### Product version
Highcharts JS v4.1.8 (2015-08-20)

#### Affected browser(s)
All browsers

**Comment by pawelfus** [comment] 2018-02-23 11:47
Hi @gayanj 

Thank you for letting us know about the issue. Could you recreate issue in jsfiddle? Thank you.

**Comment by pawelfus** [comment] 2018-03-28 11:48
Closing due to inactivity.

**Comment by pherenzi** [comment] 2018-07-12 21:01
[https://jsfiddle.net/pherenzi/z04aud71/](url)
When zooming all the way in, the x-axis labels turn into numbers. Also, lower values do not appear on the chart. When zooming out, the numbers are still present on the x-axis and the area that was previously zoomed into is sometimes missing. Toggling the series off and back on seems to make things look normal again. This happens with bar and column, but doesn't appear to occur with line charts.

**Comment by KacperMadej** [comment] 2018-07-13 08:58
Hi @pherenzi 

Thank you for providing the live demo.

_Internal note:_
Demo: https://jsfiddle.net/BlackLabel/z04aud71/4/
Steps: zoom and pan

**Comment by pawelfus** [comment] 2018-07-13 12:31
It's a duplicate of #5857 - workaround is to set `series.cropThreshold`. Closing as duplicate.

**Closed by pawelfus** 2018-07-13 12:31 UTC
Labels: Bug
