### ISSUE TITLE
Highchart Maps; India has a new state - Telangana

### ISSUE THREAD

**Issue by ghost** [highcharts/highcharts#3277] opened 2014-07-21 14:07 UTC
It would be nice to see this updated in highmaps.

![image](https://cloud.githubusercontent.com/assets/4233828/3644424/4b3ec5a2-10e0-11e4-852b-af2f8b7141b0.png)

**Comment by roydondsouza** [comment] 2015-02-11 19:27
@oysteinmoseng  Do highmaps use something like TopoJSON to store all source data for maps? Where can we look at this?

**Comment by oysteinmoseng** [comment] 2015-02-12 08:15
@roydondsouza The source data is stored as shapefiles, but is not publicly available. Our data for India currently comes from [Natural Earth](http://www.naturalearthdata.com). If you have suggestions for better sources, please let us know. If you would prefer to edit our India map yourself, see [this article]( http://www.highcharts.com/docs/maps/custom-geojson-maps).

**Comment by roydondsouza** [comment] 2015-02-12 11:43
@oysteinmoseng  Thanks, right now I don't have the time, I will look into it and let you know.

**Comment by roydondsouza** [comment] 2015-02-12 11:48
@oysteinmoseng  Thanks for the information. I will check other sources and share the information if I find anything useful. Right now I don't have the time to take up the task, will let you when I can.

**Comment by oysteinmoseng** [comment] 2017-09-22 16:13
Internal note: http://projects.datameet.org/maps/ this could be a useful source for India data, if licensing checks out

**Comment by KacperMadej** [comment] 2018-03-26 09:51
Demo map based on the source linked above for India with disputed areas: http://jsfiddle.net/BlackLabel/jyhLxfb4/

_Internal note:_ Licensing looks good (https://creativecommons.org/licenses/by/2.5/in/), but the source has a lot of small islands and because of that it takes over 2 hours to render the final map, so maybe some simplifications could be done - similar as done for Canada? @oysteinmoseng .

In `custom_maps.py` added:
```
	# New India w/disputed areas
	Map(
		"in-all-disputed3", 
		resdir.countries + 'in/custom/', 
		sources.india_disputed3.admin1, 
		'',
		description = "India3",
		complexity = 1.5, # was 1.1
	 	prepend_javascript = custom_prepend_javascript(dirs = 3),
	 	to_reference_file = custom_to_ref_file("Countries", dirs = 3),		
	),
```
In `sources.py` added:
```
# New India with disputed areas
class india_disputed3:
	admin1 = Source(
		"Admin2",
		adm_level = "admin1",
		name_field = "ST_NM",
		fields = { 
			'code' : 'ST_NM'
		},
		id_field = "ST_NM",
		failsafe_id_field = "ST_NM",
		copyright_addition = Source.Copyright(
			"Based on http://projects.datameet.org/maps/states/", 
			"projects.datameet.org", 
			"https://creativecommons.org/licenses/by/2.5/in/",
			True # Credits required
		),
	)
```
Map taken from `http://projects.datameet.org/maps/states/` --> `maps-master\maps-master\States` --> `Admin2`

Additionally: map source has only names of the states, so maybe it would be possible to merge data with old source and manually add properties for the new and changed regions.

**Comment by KacperMadej** [comment] 2018-10-24 16:30
@akhilj64 Thank you for adding this info here.

_Interna note:_ The above comment is a duplicate of #9236

**Comment by jon-a-nygaard** [comment] 2018-11-20 10:21
We have created a seperate repository for the map collection, and we are transfering the issues related to the map collection to this new repository.

Please continue the discussion and follow the future development of this issue at https://github.com/highcharts/map-collection-dist/issues/1

**Closed by jon-a-nygaard** 2018-11-20 10:21 UTC
Labels: Highmaps, Map collection
