### ISSUE TITLE
Drilldown categories

### ISSUE THREAD

**Issue by lesrpo** [highcharts/highcharts#7138] opened 2017-09-11 07:50 UTC
#### Expected behaviour
Drilldown shows the categories 

#### Actual behaviour
Drilldown is showing the first category names and then the rest only number, in the image you will see there are space to fit the dates

#### Live demo with steps to reproduce
http://jsfiddle.net/zfq5edmq/ (click on IE)

![image](https://user-images.githubusercontent.com/11498186/30263751-4005bf70-96e7-11e7-8475-aa5d4e0fcb64.png)

**Comment by pawelfus** [comment] 2017-09-11 08:54
Hi @lesrpo 

Thank you for reporting this issue. It's a duplicate of #5857

See workaround in action: http://jsfiddle.net/zfq5edmq/1/

**Closed by pawelfus** 2017-09-11 08:54 UTC
