### ISSUE TITLE
Xaxis labels grouping

### ISSUE THREAD

**Issue by Nvservicing** [highcharts/highcharts#8471] opened 2018-06-13 20:01 UTC
#### Expected behaviour
![image](https://user-images.githubusercontent.com/7690285/41375014-fdca45dc-6f11-11e8-88c2-2d25553a1024.png)

I want to be able of have xaxis labels grouped like in the attached img

#### Product version
Highcharts 4.2.5

#### Affected browser(s)
All browsers

**Comment by sebastianbochan** [comment] 2018-06-14 08:37
Hi @Nvservicing ,
For general support questions, please use forum / stackoverflow or email.

ps. you can use grouped-categories plugin.

Duplicate of https://github.com/highcharts/highcharts/issues/8452

**Closed by sebastianbochan** 2018-06-14 08:37 UTC
Labels: Not a bug

**Comment by Nvservicing** [comment] 2018-06-14 13:45
Hi @sebastianbochan excuse me for posting this here, and thank you very much, best regards
