### ISSUE TITLE
When using HC in Angular application, the charts are VERY slow

### ISSUE THREAD

**Issue by violetVo** [highcharts/highcharts#13400] opened 2020-04-30 06:54 UTC
#### Expected behaviour
The charts should be responsive

#### Actual behaviour
When using charts with a lot of data points in Angular application, the portal gets stuck.
I see A LOT of these violations in Chrome:
![image](https://user-images.githubusercontent.com/17854021/80679894-75a31080-8ac6-11ea-957b-44e2a2666a6b.png)
The violations are for the 'touchstart' and 'touchmove' events:
![image](https://user-images.githubusercontent.com/17854021/80679981-a2efbe80-8ac6-11ea-9d8d-2151ff3c121b.png)

#### Live demo with steps to reproduce
Go to:
https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_Azure_Monitoring_Logs/DemoLogsBlade/resourceId/%2FDemo/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA%252FPMK85Mzygp9k0tKcpMLuaqUcjJzM0sUTA0MDAAcopS81JSixQKMlOTMxKLSrgACtxS4C8AAAA%253D/timespan/P1D

In Chrome dev tools, change top to "DemoLogsBlade.en" (to see the relevant logs):
![image](https://user-images.githubusercontent.com/17854021/80680797-1cd47780-8ac8-11ea-9a35-856c1e91f835.png)

Click on "Split by" selector above the chart and click on "Select all"
![image](https://user-images.githubusercontent.com/17854021/80680893-42fa1780-8ac8-11ea-88e6-8064b3f3e871.png)

![image](https://user-images.githubusercontent.com/17854021/80680914-4ee5d980-8ac8-11ea-9afd-d538df8bf8ac.png)

Click outside of the drop box to apply the selection. You'll see that the number next to the Violation will keep growing. This causes the charts be very slow and sometimes the browser even crushes. 

#### Product version
Highcharts 8.0.4

#### Affected browser(s)
Chrome: Version 81.0.4044.122 (Official Build) (64-bit)
Edge also stuck

**Comment by sebastianbochan** [comment] 2020-04-30 09:23
Hi @violetVo,
Thank you for reporting. It looks like duplicate of https://github.com/highcharts/highcharts/issues/11353. But Im not sure if its causes your performance issue. Could you share your live demo for the further debugging? The link requires account, but we would prefer to public access. 

ps. If its not possible, could you contact with us by email?

**Comment by violetVo** [comment] 2020-04-30 09:41
Sure, What email can I contact?

Thanks,
Violet.

**Comment by sebastianbochan** [comment] 2020-04-30 13:35
Hi @violetVo 
Our official support email: support@highcharts.com

**Comment by violetVo** [comment] 2020-04-30 14:27
Thanks Sebastian.
Wrote an email.

Violet.

**Closed** 2020-05-04 14:39 UTC
Labels: Status: Pending reply
