### ISSUE TITLE
Highcharts 9 added strict mode

### ISSUE THREAD

**Issue by alons1** [highcharts/highcharts#16687] opened 2021-11-21 17:00 UTC
#### Expected behaviour
'Use strict' will affect only Highcharts functions

#### Actual behaviour
It affects the entire code of the customer, such as assignment of values to an undeclared variable.
Difficult to identify the cause of the problems and track it down to Highcharts.

#### Product version
9.2.2

#### Affected browser(s)
All

**Comment by raf18seb** [comment] 2021-11-22 16:04
Hi @alons1! Thanks for contacting us and creating a ticket.

Could you describe your issue more precisely and provide a live demo showing the case? Highcharts has always been in a strict mode and you should be able to write your own code in a normal mode.

**Comment by KacperMadej** [comment] 2021-11-23 10:28
There was a build issue that removed `'use strict'` from some builds, but the intention was to have this always.
The strict mode applies only to the script that has it set, so this should not affect any code outside of the Highcharts library (core + modules).

More info (in comments) and an example in the demo below:
Demo: https://jsfiddle.net/BlackLabel/9y2v7fr8/
(See an error in developer tools console)

We are still waiting for a reply from you @alons1 about the demo, details, or comments. However, IMO this is not a bug and I would like to close the issue as resolved.

**Comment by alons1** [comment] 2021-11-23 10:43
Your demo loads the Highchart scripts separately.
Most websites would combine all static resources into 1 request using some dynamic handler. At that point your 'use strict' would affect their code. 
And since it was just added suddenly in version 9 without any mention as a 'breaking change', when upgrading from Highcharts 8 it's hard to pinpoint why you start having all these problems.

**Comment by KacperMadej** [comment] 2021-11-24 17:33
The intention was to have 'use strict' always in code for un-minified code and for minified.
This was fixed here: https://github.com/highcharts/highcharts/pull/15762

> Most websites would combine all static resources into 1 request using some dynamic handler or some combiner during the build of their project. At that point your 'use strict' would affect their code.

We have not received other problem reports like this so this would suggest that what most websites are doing is not really that huge problem, but still, we will investigate this.

@TorsteinHonsi 
Maybe `use sctrict` could be placed in the function(s) scope of the file to avoid this problem? Are there any other limitations that we should look out for here?

**Comment by alons1** [comment] 2021-11-24 17:53
I almost didn't bother reporting it myself after removing it from your code, but I know that 6 months from now another dev from my company will run into this again after upgrading to Highcharts 10...

**Comment by TorsteinHonsi** [comment] 2021-11-25 08:34
@bre1470 Any thoughts? ☝️

**Comment by bre1470** [comment] 2021-11-25 08:45
I see the problem with bundling and Kacper's suggestion is a good compromise. It should be neglectable whether the UMD factory runs in strict mode or not.

**Closed** 2022-01-04 09:48 UTC
Labels: Type: Feature Request, Status: In progress
