### ISSUE TITLE
Treemap dalatabels in drilldown are incorrect

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#7093] opened 2017-08-23 08:18 UTC
#### Expected behaviour
Like in 5.0.12.

#### Actual behaviour
When you click on a node, datalabels is not updated.

#### Live demo with steps to reproduce
Let's compare:
- 5.0.12 http://jsfiddle.net/ntxo515t/24/  -> works properly
- 5.0.14 http://jsfiddle.net/Ishwarya/ntxo515t/1/ -> works incorrectly

#### Affected browser(s)
All

**Comment by pawelfus** [comment] 2017-08-23 08:32
Regression after effdece @jon-a-nygaard

**Comment by jon-a-nygaard** [comment] 2017-10-10 11:11
The #7233 is a duplicate of this issue, but since the referenced issue is closed and tagged with a fix, then I am closing this issue as a duplicate.

For more information about the issue. please look at #7233

**Closed by jon-a-nygaard** 2017-10-10 11:11 UTC
Labels: Regression
