### ISSUE TITLE
Bad performance on chrome-lastest version on mobile

### ISSUE THREAD

**Issue by BatelAyala** [highcharts/highcharts#12662] opened 2019-12-19 07:12 UTC
I have chart with 5 graphs every graph has 700-800 points (total: about 4000 points) but the chart is working very slow on mobile-and in some device it cause chrome crash.
It happened to me with all device with the lastest chrome update.
I opened an issue on highchart forum and they checked it and said that this is a bug.
https://www.highcharts.com/forum/viewtopic.php?f=9&t=43029
I will be glad if you can take care on that and give me a notification as soon as the problem is resolved.

**Comment by KacperMadej** [comment] 2019-12-19 10:42
Hi @BatelAyala 

If you will set up the boost related options to enable boosting in your chart then it opens fine on a mobile Chrome: https://jsfiddle.net/BlackLabel/3ongdp50/

**Comment by BatelAyala** [comment] 2019-12-19 12:06
Thanks for your comment,
We checked the boost module-it working fine, but it have many disadvantages-like disabling the animation...
Moreover the data on this chart is 4000 points-it is not an amount that require boost module.
So I would like to solve this problem without using boost module.

**Comment by KacperMadej** [comment] 2019-12-20 12:22
The same problem could be recreated using one of our default demos.
https://www.highcharts.com/demo/line-time-series
The tooltip is not showing up,
the site is not responding,
the browser tab freezes.

Tested on:
Chrome 79.0.3945.93 / Android 7.0

**Comment by berko127** [comment] 2019-12-26 14:00
Hi,  @KacperMadej, the bug means that all users with updated chrome (which is automatically updated in mobiles) will cause a serious performance impact. can you tell please when can we expect a fix? thanks.

**Comment by sebastianbochan** [comment] 2019-12-27 10:11
Hi @berko127,
At this moment we do not have an ETA (due to Christmas time period), but we will debug the issue as soon as possible.

Meantime, as workaround you can try to disable animations or use the boost module.

**Comment by berko127** [comment] 2020-01-12 15:38
Hi,

Is there any updates regarding the ETA?

Thanks,
Shlomi

**Comment by pawelfus** [comment] 2020-01-13 09:58
This issue seems to be a duplicate of #12283 - could you confirm @BatelAyala / @berko127 ?

**Comment by berko127** [comment] 2020-01-13 13:49
yes it seems they are duplicate. thanks!

**Comment by pawelfus** [comment] 2020-01-13 15:27
Thanks! Then it's reported to Chrome developers 👍

**Closed by pawelfus** 2020-01-13 15:27 UTC
Labels: Product: Highcharts, Type: Bug
