### ISSUE TITLE
`minPointLength` is overlapping other stack if `stacking: normal` in column chart

### ISSUE THREAD

**Issue by yogeshhrathod** [highcharts/highcharts#21178] opened 2024-05-16 11:34 UTC
# Description of the feature

I am trying to use `minPointLength` but after using it, its overlapping the stack in the chart 

```js
Highcharts.chart('container', {
    chart: {
        type: 'column'
    },
    title: {
        text: 'Stacked Column Chart with Minimum Size'
    },
    xAxis: {
        categories: ['A', 'B', 'C', 'D']
    },
    yAxis: {
        title: {
            text: 'Total Fruit Count'
        }
    },
    plotOptions: {
        column: {
            stacking: 'normal',
            minPointLength: 15 // Minimum height of each stacked column in pixels
        }
    },
    series: [{
        name: 'Apples',
        data: [100, 2, 1, 2]
    }, {
        name: 'Oranges',
        data: [2, 1, 3, 1]
    }, {
        name: 'Bananas',
        data: [2, 1, 1, 1]
    }]
});

```
blue stack is overlapped because of minPointLength is more than the actual blue stack.
![image](https://github.com/highcharts/highcharts/assets/46518134/c42a3bee-f496-49af-9f79-2dcdc1a2f6eb)

example:

https://jsfiddle.net/y2a9bo7s/
----

**Comment by bm64** [comment] 2024-05-16 11:44
Hi @yogeshhrathod 

There's already a ticket with detailed explanations of the problem and possible solutions. Please refer to the topic and continue the discussion there: https://github.com/highcharts/highcharts/issues/1776

Closing as a duplicate of #1776

**Closed by bm64** 2024-05-16 11:44 UTC
Labels: Type: Feature Request
