### ISSUE TITLE
Unable to drag parent element on mouseDown `preventDefault`

### ISSUE THREAD

**Issue by ppcano** [highcharts/highcharts#4078] opened 2015-04-08 14:18 UTC
The following [preventDefault call](https://github.com/highslide-software/highcharts.com/blob/d228fa0af315d6bc60069e509b31d8c9b44592a4/js/parts/Pointer.js#L504) removes the the ability to drag the parent element.

A possible workaround is to reset the listener as:

```
    this.highchart.container.onmousedown = null;

```

**Comment by pawelfus** [comment] 2018-08-28 12:06
Closing as duplicate of #4606

**Closed by pawelfus** 2018-08-28 12:06 UTC
