### ISSUE TITLE
Enabling scroll bar on the y-axis of the heatmap showing up some additional y-axis labels

### ISSUE THREAD

**Issue by rajiqxf2** [highcharts/highcharts#8798] opened 2018-08-17 09:24 UTC
Actual behaviour
Enabling scroll bar on the y-axis of the heatmap showing up some additional y-axis labels
Additional Notes
I tried to generate heat map for the large set of series data with same x and y-axis 
categories and scrollbars enabled for both x & y-axis. Problem is y-axis is showing up some additional labels with an empty plot area which did not get solved by setting endOnTicket to false

Expected behaviour
the y-axis of the heatmap should not show additional y-axis labels when endOnTicket is set to false

Live demo with steps to reproduce
[http://jsfiddle.net/graji/mdu37kq8/9/](url)

Product version
Latest Stable

Affected browser(s)
All

**Comment by pawelfus** [comment] 2018-08-17 14:35
Hi  @rajiqxf2 

Thanks for reporting this bug. It's not connected to scrollbars, disabled scrollbars look the same: http://jsfiddle.net/BlackLabel/mdu37kq8/33/

It's actually duplicate of #6152 (the same issue, a bit different manifestation). 

**Workaround:**
Disable `turboThreshold`: http://jsfiddle.net/BlackLabel/mdu37kq8/31/

**Closed by pawelfus** 2018-08-17 14:35 UTC
Labels: Duplicate
