### ISSUE TITLE
Multiple datalabels on a piechart doesn't work

### ISSUE THREAD

**Issue by avshyz** [highcharts/highcharts#11761] opened 2019-08-24 01:01 UTC
#### Expected behaviour
Adding a list of dataLabels to the piechart will show multiple data labels as seen [here](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/series-datalabels-multiple) (example copied from the official docs' demo)

#### Actual behaviour
Highchart doesn't display any data labels as seen [here](https://jsfiddle.net/wu3d0bt5/)

#### Live demo with steps to reproduce

Interestingly, when I change the chart type to a bar chart, (and change the dataLabel format a bit (from `distance` to `align`)) it actually works as seen [here](https://jsfiddle.net/wu3d0bt5/1/).

#### Product version
Highcharts 7.1.3

#### Affected browser(s)
Chrome 76, OSX 10.14

**Comment by sebastianbochan** [comment] 2019-08-26 09:53
Hi @avshyz,
Thank you for reporting about the issue.

_Internal note_
It looks like multiple datalabels have never been supported by pie chart.

v6.2.0 - https://jsfiddle.net/BlackLabel/0g7emr1d/
v7.0.0 - https://jsfiddle.net/BlackLabel/f7sLwat4/

**Comment by pawelfus** [comment] 2019-11-08 14:25
Closing as duplicate of #10976

**Closed by pawelfus** 2019-11-08 14:25 UTC
Labels: Type: Duplicate
