### ISSUE TITLE
Solid Gauge does not always respect max value

### ISSUE THREAD

**Issue by ggrillone** [highcharts/highcharts#7973] opened 2018-03-07 20:51 UTC
#### Expected behaviour
I expect when I set the max value for the Solid Gauge chart that it uses the value I provide.

#### Actual behaviour
It (sometimes) increases the max.

#### Live demo with steps to reproduce
you can see under `yAxis` I have set the `max` value to `75`. But when I run it, the chart renders with a max of `80` instead. If I change the `max` to `80` then it is fine. Seems to only respect my `max` when it is divisible by 4.

fiddle: https://jsfiddle.net/4mtexy8z/9/

#### Product version
latest

#### Affected browser(s)
all

**Comment by pawelfus** [comment] 2018-03-08 11:25
Hi @ggrillone 

Thank you for reporting this issue. It's caused by ticks distribution when `yAxis.tickAmount < 4`. In this case we compute five ticks, and filter out unnecessary ones. This way we can force extremes to be very close the dataset. 

In your case, when you want to show exact extremes, with only two ticks, it's better to use `tickPositions` instead of `tickAmount`, for example: 

```javascrtipt
    yAxis: {
    	min: 0,
    	max: 75,
        tickPositions: [0, 75],
        title: {
            text: 'Speed'
        }
    },
```

Demo: https://jsfiddle.net/BlackLabel/4mtexy8z/11/

**Comment by KacperMadej** [comment] 2018-05-23 15:18
Also explained in documentation: https://api.highcharts.com/highcharts/yAxis.max

> ... If a tickAmount is set, the axis may be extended beyond the set max in order to reach the given number of ticks. ...

Closing as the problem is explained and is not a bug.

**Closed by KacperMadej** 2018-05-23 15:18 UTC
