### ISSUE TITLE
Same-name `series` event handlers override `plotOptions` event handlers

### ISSUE THREAD

**Issue by AleksueiR** [highcharts/highcharts#7914] opened 2018-02-23 15:48 UTC
#### Expected behaviour
Both event handlers set on `series` and `plotOptions` are executed - `series` handlers are called first; `plotOptions`, after that.

#### Actual behaviour
`series` event handlers seem to take precedence and none of the `plotOptions` event handlers with the same names get called.

Is this the intended behaviour?
I would expect specific `series` event handlers to be executed before generic `plotOptions` event handlers, not completely overriding them.

#### Live demo with steps to reproduce
https://jsfiddle.net/ouroborosDragon/wqddrduc/12/

- toggle the `Series 1` series
- observe `series.events.show` firing but not `plotOptions.series.events.show`
- comment out `series.events.show`
- toggle the series again
- observe `plotOptions.series.events.show` now firing

#### Product version
Highcharts: 6.0.7

#### Affected browser(s)
All.

Thank you.

**Comment by pawelfus** [comment] 2018-02-23 16:34
Hi @AleksueiR 

> `series` event handlers seem to take precedence and none of the plotOptions event handlers with the same names get called.
> Is this the intended behaviour?

Yes, this is intended behaviour. We don't propagate events, simply replace them. For example `series.color` has precedence over `plotOptions.series.color` - event callbacks work the same way.

**Comment by AleksueiR** [comment] 2018-02-23 17:11
Okay, thank you. 

I understand replacing properties like `color` which can have one value anyway, but it's conceivable you might want to have multiple event handlers - a series-specific ones and a generic handler that apply to all series.

Is there a chance you will consider event "bubbling" in the future? If not, maybe you can add a note to the API docs to clarify this point.

**Comment by pawelfus** [comment] 2018-02-23 17:18
You can create this idea on our UserVoice: https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api - we are trying to implement the most popular ideas to the core (or as modules).

Regarding docs it's a general description about overwriting `plotOptions`: https://api.highcharts.com/highcharts/plotOptions

> The plotOptions is a wrapper object for config objects for each series type. The config objects for each series can also be **overridden** for each series item as given in the series array.

**Comment by AleksueiR** [comment] 2018-02-23 18:26
Thank you. I think this can be closed now.

**Comment by oysteinmoseng** [comment] 2018-02-24 09:06
Closing for now, note that by using named functions you can of course call the generic handler from your specific handler manually: https://jsfiddle.net/8bhwfrx1/

**Closed by oysteinmoseng** 2018-02-24 09:06 UTC
Labels: Not a bug
