### ISSUE TITLE
Disabling inactive state is not honored in styled mode

### ISSUE THREAD

**Issue by Lukas0907** [highcharts/highcharts#21325] opened 2024-06-14 08:04 UTC
#### Expected behaviour

The opacity of "inactive" parts of the chart should not be changed (reduced). No matter if styled mode is active or not. If this doesn't work for technical reasons, the documentation should be updated to reflect this.

#### Actual behaviour

The opacity is changed even though the "inactive" state is disabled.

See also: https://stackoverflow.com/questions/61693818/disabling-inactive-state-in-highcharts-styled-mode

#### Live demo with steps to reproduce

* Actual: https://jsfiddle.net/vy4fLr9k/3/
* Expected: https://jsfiddle.net/vy4fLr9k/2/

#### Product version

v11.4.3

#### Affected browser(s)

Chromium 125.0.6422.112

**Comment by hubertkozik** [comment] 2024-06-14 09:23
Hi @Lukas0907! Thanks for reporting the issue. Sadly, this topic was already discussed and it is not a bug.

Closing as a duplicate of https://github.com/highcharts/highcharts/issues/13518.

**Closed by hubertkozik** 2024-06-14 09:23 UTC
Labels: Duplicate
