### ISSUE TITLE
Chart becomes unresponsive when you zoom below minutes

### ISSUE THREAD

**Issue by slawekkolodziej** [highcharts/highcharts#707] opened 2012-01-18 00:32 UTC
1. Open this demo: http://jsfiddle.net/hfrntt/QPCDq
2. Zoom to 10 Nov, there are two points for this day
3. You should notice that when you zoom below minutes, chart becomes unresponsive for a while.

**Comment by oysteinmoseng** [comment] 2018-04-30 08:02
Can't reproduce this in latest, so closing for now. http://jsfiddle.net/QPCDq/5/

**Closed by oysteinmoseng** 2018-04-30 08:02 UTC
Labels: Highcharts
