### ISSUE TITLE
Cannot create label annotation below the first Y axis in a chart

### ISSUE THREAD

**Issue by johnsonkoshy** [highcharts/highcharts#15574] opened 2021-04-26 01:20 UTC
#### Expected behaviour
Should be able to create labels anywhere in the graph. 
Other annotaitons such as circle and rectangles work properly, you can create a shape anywhere in the graph but not a label.

#### Actual behaviour
labels disappear when they are created below the first Y axis. interestingly, you can drag the label to outside the Y axis after it was create above the first Y axis

#### Live demo with steps to reproduce

https://v934j.csb.app/

#### Product version

9.0.1

#### Affected browser(s)
Any

**Comment by khlieng** [comment] 2021-04-26 12:09
I think this has been fixed on master (#15209).

**Comment by raf18seb** [comment] 2021-04-26 12:26
Correct. It will be available in the next 9.0.2 (or 9.1.0) version which will be released this week or next week at the latest.

**Comment by raf18seb** [comment] 2021-04-26 12:28
Closing as a duplicate of #12268

**Closed** 2021-04-26 12:28 UTC
