### ISSUE TITLE
rendering issues on line graphs

### ISSUE THREAD

**Issue by pdeva** [highcharts/highcharts#7916] opened 2018-02-25 06:19 UTC
#### Expected behaviour
Line charts should show as lines

#### Actual behaviour
Line charts highlight the area underneath them (almost like area graphs).

Video showing the issue:
https://www.screencast.com/t/CTlYRfBz

#### Live demo with steps to reproduce
Cant find an easy way to reproduce.
Though it started happening after upgrading to v6. didnt happen in v5.

#### Product version
Highcharts 6.0.7

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment] 2018-02-26 10:22
Hi @pdeva 

Thank you for reporting this bug. It's a duplicate of #7662 - could you try the workaround posted there? Thank you.

**Closed** 2018-02-26 10:22 UTC
Labels: Duplicate

**Comment by pdeva** [comment] 2018-02-27 04:32
the 'workaround' of disabling graphics acceleration is not a real workaround...
is there any eta to fix this? it seems we will have to revert back to v5 due to this

**Comment by pawelfus** [comment] 2018-02-27 12:45
My apologies, workaround I was talking about is posted in a different issue: #7528 I will add the workaround in #7662 too.
