### ISSUE TITLE
Incorect rendering of points with large number for yAxis coordinate

### ISSUE THREAD

**Issue by jimylja** [highcharts/highcharts#17329] opened 2022-05-26 09:43 UTC
#### Expected behavior
Points should have correct coordinates for the Y position

#### Actual behaviour
Coordinates for points that should have a 'y' coordinate bigger than 100 000 pixels are incorrect.  (<= 100000px)

#### Live demo with steps to reproduce
https://codepen.io/jimylja/pen/xxYXLWR

#### Product version
Highcharts 6.2, Highcharts 10.1

#### Affected browser(s)
Chrome (v.101), Firefox (v. 100)

**Comment by pawellysy** [comment] 2022-05-27 16:30
Hi @jimylja, thanks for creating this ticket!
This is intended behavior. As you can read here: https://github.com/highcharts/highcharts/blob/bf487fca8d058b170710014ab4c94667b7626513/ts/Core/Series/Series.ts#L2170-L2178

There are some issues with rendering elements too far outside the viewport. 
Closing, since this is intended, and we won't fix that.

**Closed by pawellysy** 2022-05-27 16:30 UTC
