### ISSUE TITLE
Bar chart boost.js #6602 workaround not working in iPad

### ISSUE THREAD

**Issue by SrinivasGit049** [highcharts/highcharts#6788] opened 2017-06-02 06:50 UTC
We tried the work around for provided in #6602  loading bar charts in iPad web view. The issue of #6602 is resolved but we are observing the performance issue after this changes.The chart is taking too long time to load in iPad after adding below configuration
boost: {
seriesThreshold: 50
}
Without this configuration it is taking around 35 secs to load charts with more than 25 series.
Same it is taking 2 mins with configuration

**Comment by cvasseng** [comment] 2017-06-02 09:32
When setting `seriesThreshold` to `50`, you're telling boost to activate once there are more than 50 series in the chart. That's why it's faster when you disable it; presumably you have less than 50 but more than the default value of 20. Meaning that when you remove that part of the configuration, boost is activated for your chart.

Your original issue was with bars not displaying as you expected when boost is disabled. So:

To have your cake and eat it too, you need to set `seriesThreshold` to a higher number than the amount of series in your chart, and then set `boostThreshold` on the `series` configuration objects to something that makes sense for the number of points you have. `boostTreshold` on the series level is the number of points that must exist in the series for the boost to activate. It takes zoom into consideration, which means that when you zoom in and the point density decreases, it will deactivate the boost and switch back to SVG rendering when the point count goes below the number you set. The number depends on your dataset, but try setting it to 1000 or so and increase it as necessary until you're happy with the appearance and the performance.

**Comment by pawelfus** [comment] 2017-06-02 09:41
Closing as duplicate of #6602. Let's keep one issue in one ticket, otherwise it will harder to track the issues.

**Closed by pawelfus** 2017-06-02 09:41 UTC
