### ISSUE TITLE
Export Menu FontAwesome Does Not Show

### ISSUE THREAD

**Issue by wergeld** [highcharts/highcharts#15470] opened 2021-04-08 15:20 UTC
#### Expected behaviour
Expanding the export menu built into highhcarts should show:
![image](https://user-images.githubusercontent.com/133511/114051806-6e01f500-985b-11eb-98f9-fa36f341afe4.png)

#### Actual behaviour
![image](https://user-images.githubusercontent.com/133511/114052299-ec5e9700-985b-11eb-8792-bfb080161c5a.png)

#### Live demo with steps to reproduce
We have a license to FontAwesome on our sites.
Code used:
```
        exporting: {
            chartOptions: {
                title: { text: unescape(encodeURI(exportChartTitle)) }
            },
            filename: 'TrendChart',
            url: exportURL,
            menuItemDefinitions: {
                noCompareButton: {
                    text: '<i class="fas fa-minus-circle" title="No Compare"></i> No Comparison',
                    onclick: function () {
                        this.showLoading();

                        this.update({
                            plotOptions: {
                                series: {
                                    compare: undefined
                                }
                            }
                        }, false);

                        this.yAxis[0].setCompare('none', false);
                        this.yAxis[0].setTitle({ text: '' }, true);
                        this.hideLoading();
                        ATMAcompare = 0;
                    }
                },
                numCompareButton: {
                    text: '<i class="fas fa-hashtag" title="Compare Numeric Change"></i> Numeric Comparison',
                    onclick: function () {
                        this.showLoading();

                        this.update({
                            plotOptions: {
                                series: {
                                    compare: 'value'
                                }
                            }
                        }, false);

                        this.yAxis[0].setCompare('value', false);
                        this.yAxis[0].setTitle({ text: 'Numeric Change' }, true);
                        this.hideLoading();
                        ATMAcompare = 1;
                    }
                },
                pctCompareButton: {
                    text: '<i class="fa fa-percent" title="Compare Percent Change"></i> Percent Comparison',
                    onclick: function () {
                        this.showLoading();

                        this.update({
                            plotOptions: {
                                series: {
                                    compare: 'percent'
                                }
                            }
                        }, false);

                        this.yAxis[0].setCompare('percent', false);
                        this.yAxis[0].setTitle({ text: 'Percent Change' }, true);
                        this.hideLoading();
                        ATMAcompare = 2;
                    }
                },
                GoFullScreenButton: {
                    text: '<i class="fa fa-expand" title="Show Full Screen"></i> Show Full Screen',
                    onclick: function () {
                        Highcharts.FullScreen.prototype.init(this.renderTo);
                    }
                }
            },
            buttons: {
                contextButton: {
                    menuItems: ['noCompareButton', 'numCompareButton', 'pctCompareButton']
                }
            }
        },
```

#### Product version
Highstock 9.0.1 has this issue
Highstock 8.2.0 does **not** have this issue.

#### Affected browser(s)
Chrome is only one tested.

**Comment by khlieng** [comment] 2021-04-08 17:16
Duplicate of #15449.

**Closed by khlieng** 2021-04-08 17:16 UTC
Labels: Type: Duplicate
