### ISSUE TITLE
Cannot load errorbar series when boost is enabled

### ISSUE THREAD

**Issue by manu-st** [highcharts/highcharts#7672] opened 2018-01-16 00:27 UTC
#### Expected behaviour
Display errorbars in a rendered graph.

#### Actual behaviour
Failure at line 1790 of highstock.src.js with
```
Uncaught TypeError: Array.prototype.forEach called on null or undefined
    at forEach (native)
    at H.each (webpack-internal:///411:1790:67)
    at object.translate (webpack-internal:///415:2863:17)
    at object.redraw (webpack-internal:///411:26771:24)
```
As far as I can tell, `series.points` is undefined. So clearly I'm not feeding the data properly but cannot find out why. Where could I figure out if the data is provided in the proper format?

#### Live demo with steps to reproduce
Could not reproduce it on a small example.

#### Product version
Using Highstock 6.0.4.

#### Affected browser(s)
Under Electron 1.7.9.

**Comment by pawelfus** [comment] 2018-01-16 11:31
Hi @manu-st 

Thank you for reporting the issue. Without a live demo it's hard to say what is wrong, it may be connected to the data config - could you show your format? Simple demos work fine: http://jsfiddle.net/mxw6wvma/

**Comment by manu-st** [comment] 2018-01-16 18:00
Here is the `series` entry for the chart options I'm using when creating the graph:

```
[
   {
      "animation":false,
      "color":"#000000",
      "data":[
         [
            0.08929947265388823,
            0.000002922835749567747
         ],
         [
            0.13300625080730205,
            0.000002949939430344764
         ],
         [
            0.18904328831986883,
            0.000002967214633401977
         ],
         [
            0.24971597418238933,
            0.0000029702606336197753
         ],
         [
            0.32356955295820833,
            0.0000029685237669407115
         ],
         [
            0.4106851626214993,
            0.0000029722753594136506
         ],
         [
            0.5000000000000001,
            0.000002971795204118137
         ],
         [
            0.5893148373785008,
            0.000002974434191572674
         ],
         [
            0.6764304470417917,
            0.0000029738555920808267
         ],
         [
            0.7592017535598305,
            0.000002973194363564304
         ],
         [
            0.8355906526639258,
            0.0000029692123185992075
         ],
         [
            0.8966088890654854,
            0.000002964013901129366
         ]
      ],
      "events":{

      },
      "id":"data0PeakNumber1",
      "name":"data, Peak Number 1",
      "type":"scatter",
      "visible":false,
      "yAxis":0,
      "zIndex":0
   },
   {
      "animation":false,
      "color":"#000000",
      "data":[
         [
            0.08929947265388823,
            0.000002922835749567747,
            0.0000029461076679624776
         ],
         [
            0.13300625080730205,
            0.000002949939430344764,
            0.0000029628658508844375
         ],
         [
            0.18904328831986883,
            0.000002967214633401977,
            0.000002972389985540423
         ],
         [
            0.24971597418238933,
            0.0000029702606336197753,
            0.000002973919548736005
         ],
         [
            0.32356955295820833,
            0.0000029685237669407115,
            0.0000029712321906366623
         ],
         [
            0.4106851626214993,
            0.0000029722753594136506,
            0.000002974261983251592
         ],
         [
            0.5000000000000001,
            0.000002971795204118137,
            0.0000029732553522638057
         ],
         [
            0.5893148373785008,
            0.000002974434191572674,
            0.0000029755567303070773
         ],
         [
            0.6764304470417917,
            0.0000029738555920808267,
            0.000002974711588942473
         ],
         [
            0.7592017535598305,
            0.000002973194363564304,
            0.0000029743535262762996
         ],
         [
            0.8355906526639258,
            0.0000029692123185992075,
            0.0000029706738793262877
         ],
         [
            0.8966088890654854,
            0.000002964013901129366,
            0.0000029664591894159317
         ]
      ],
      "linkedTo":"data0PeakNumber1",
      "type":"errorbar",
      "yAxis":0,
      "zIndex":0
   }
]
```

**Comment by manu-st** [comment] 2018-01-16 19:07
If I change the type from `errorbar` to `line` then a line is displayed.

**Comment by pawelfus** [comment] 2018-01-17 10:16
Thank you for the details. Unfortunately, it works fine for me: http://jsfiddle.net/BlackLabel/0tp7c15u/2/

**Comment by manu-st** [comment] 2018-01-17 17:31
I was able to reproduce it. It seems to be due to our usage of boost for this. You can see it at:

http://jsfiddle.net/5ybju9w4/

**Comment by manu-st** [comment] 2018-01-17 17:32
I update the above link. You will see no error bars and if you inspect the console you will see the exception I initially reported.

**Comment by manu-st** [comment] 2018-01-17 17:36
I've simplified to the smaller example possible:
http://jsfiddle.net/0b8u3smd/

The culprit seems to be the `seriesThershold` setting.

**Comment by pawelfus** [comment] 2018-01-18 12:46
Ahh.. thank you for the demo, now it's clear. Let me change the labels.

**Comment by cvasseng** [comment] 2018-01-19 11:25
Hi,

this has been fixed in master:
http://jsfiddle.net/nuzd0rc6/

The bug was caused by the boost module being activated for series inheriting/extending column series, regardless of whether or not boost was supported for the actual series type (in this case, errorbar is not supported by boost, but the boost module still tried to boost it).

**Comment by manu-st** [comment] 2018-01-19 18:22
Thanks! What is the timeline on the next version will be available with the fix in?

**Comment by sebastianbochan** [comment] 2018-01-23 09:36
We release new version of Highcharts, within next few weeks.

**Closed** 2018-01-24 12:03 UTC
Labels: Bug, Fix suggested
