### ISSUE TITLE
Scatter3D Tooltip Not Displaying in Google Chrome

### ISSUE THREAD

**Issue by JosephGalante** [highcharts/highcharts#21654] opened 2024-08-12 15:57 UTC
#### Expected behavior
On a Scatter3D plot, the tooltip should appear when hovering over points in the graph for any and all major internet browsers (i.e. Chrome, Firefox, Safari, Edge, etc.)

#### Actual behavior
The tooltip does not appear when hovering over points in the Scatter3D plot graph in the Google Chrome browser.

#### Live demo with steps to reproduce
1. Open link in Google Chrome, and then hover over some points to observe the tooltip **_does not_** appear.
2. Open link in any other browser (Safari, Firefox, etc.), hover over some points, and observe tooltip **_does_** appear.  

[CodeSandbox link with minimal reproduction code](https://codesandbox.io/p/sandbox/fervent-dream-rly8z5?file=%2Fsrc%2FThreeDScatterPlot.tsx%3A16%2C1)

#### Product version

- Latest `highcharts` version - (currently using v11.4.6)
- Latest `highcharts-react-official` version - (currently using v3.2.1)

#### Affected browser(s)
Google Chrome - version 127.0.6533.100 (Official Build) (arm64)

**Comment by JosephGalante** [comment] 2024-08-12 15:59
From the codesandbox link, one can see that the Tooltip does appear upon user hover while using Safari:
![Screenshot 2024-08-12 at 10 58 19 AM](https://github.com/user-attachments/assets/24729e2c-a222-4620-80f2-fa8a6e243674)


However, this is not the case when using Google Chrome: ![Screenshot 2024-08-12 at 10 58 37 AM](https://github.com/user-attachments/assets/bfc20977-905b-4ea7-a575-e92b724a2e42)

**Comment by hubertkozik** [comment] 2024-08-13 06:53
Hi @JosephGalante! This issue is a duplicate of https://github.com/highcharts/highcharts/issues/21639. The fix is merged into the master branch, we will release a new version soon :)

**Closed by hubertkozik** 2024-08-13 06:53 UTC
Labels: Duplicate
