### ISSUE TITLE
A zone incorrectly applies to vertical stepped line.

### ISSUE THREAD

**Issue by Llorx** [highcharts/highcharts#13130] opened 2020-03-12 17:27 UTC
#### Expected behaviour
To apply the zone only if the line fits inside the zone values.

#### Actual behaviour
The zone semi-applies. Something weird.

#### Live demo with steps to reproduce
https://jsfiddle.net/aL2qs0fj/  
![image](https://user-images.githubusercontent.com/702490/76548456-08dca400-648f-11ea-84f8-e6d3e0ce3a6a.png)  
If I zoom in, it works as expected, so I can't add a hack like `now + 10100` instead of `now + 10001` because it will be more noticeable at first sight.

#### Product version
Latest

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment] 2020-03-13 14:50
Thanks for reporting. It's actually a duplicate of #4503 - please check the explanation there.

Closing as a duplicate of #4503.

**Closed by pawelfus** 2020-03-13 14:50 UTC

**Comment by Llorx** [comment] 2020-03-13 16:37
I've searched and found nothing. Sorry.
