### ISSUE TITLE
Given enough series / points, clicking a point is treated as if the background was clicked.

### ISSUE THREAD

**Issue by bkerzner** [highcharts/highcharts#16177] opened 2021-08-10 21:50 UTC
#### Expected behaviour
If a user mouses over a point and sees the tooltip for that point and then clicks that point, then the `plotOptions.series.point.events.click` event handler should be invoked.

#### Actual behaviour
The `charts.events.click` event handler is invoked, even though `plotOptions.series.point.events.click` is defined. `charts.events.click` fires when clicking on the plot background... For some reason, HighCharts think the background is being clicked.

#### Live demo with steps to reproduce
https://jsfiddle.net/o75kwndx/1/

#### Product version
highcharts 8.1.2

#### Affected browser(s)
Firefox v.90

**Comment by raf18seb** [comment] 2021-08-11 17:13
Closing as a duplicate of https://github.com/highcharts/highcharts/issues/14067

**Closed by raf18seb** 2021-08-11 17:13 UTC
