### ISSUE TITLE
Bug : encountered inconsistencies when exporting our charts to PNG or PDF formats.

### ISSUE THREAD

**Issue by Nikhilraopeechara1** [highcharts/highcharts#21823] opened 2024-09-11 15:59 UTC
#### Expected behaviour
I have taken highcharts to our project. So initially When we download Heat Map is downloading correctly. Suddenly it is changing the behavior.
#### Actual behaviour
We encountered inconsistencies when exporting our charts to PNG or PDF formats. Specifically, we have observed that:
![us-states-and-territorie](https://github.com/user-attachments/assets/f38124f1-4dbe-4ad2-879a-d1724985f244)
The export sometimes produces the correct image or PDF as expected.

#### Product version

   "highcharts": "^11.4.0",
    "highcharts-pattern-fill": "^3.0.3",
    "highcharts-react-official": "^3.2.1",

**Comment by Nikhilraopeechara1** [comment] 2024-09-11 15:59
Expected
<img width="1149" alt="Screenshot 2024-09-11 at 10 59 46 AM" src="https://github.com/user-attachments/assets/726933cb-b65d-4818-a7f6-1101c3dd92ca">

**Comment by KacperMadej** [comment] 2024-09-12 11:56
Hi @Nikhilraopeechara1 

Please add a live demo with a minimal code example of the problem. I can recreate some issues but not exactly what you have reported. It will help us narrow down if the problem is in the Highcharts Maps, the pattern-fill plugin or exporting (module or server).

**Comment by Nikhilraopeechara1** [comment] 2024-09-12 14:51
I am using this packages for highhcarts 
//    "highcharts": "^11.4.0",
    "highcharts-pattern-fill": "^3.0.3",
    "highcharts-react-official": "^3.2.1",

**Comment by KacperMadej** [comment] 2024-09-13 08:39
One thing to start with could be to update the pattern-fill from the separate package that is no longer updated to the module (loaded and added like e.g. exporting module you already have). You could see the HMTL section of this demo in JSFiddle or Codepen for a reference: https://www.highcharts.com/demo/maps/pattern-fill-map

Unfortunately I am unable to debug the code or check the chart configuration through a video so it is not helpful to resolving the problem.

Is the problem persistent - happens every time?
Is it related to the pattern-fill - doesn't happen without it?
Do you have any errors in the developer tools console?
Have you tried with a map that doesn't have a separator or insets - like e.g. Australia?

**Comment by Nikhilraopeechara1** [comment] 2024-10-04 15:48
Is the problem persistent - happens every time? Yes It is downloading correctly for 5 to 6 time then it is not downloading the exact
Is it related to the pattern-fill - doesn't happen without it? It happens for pattern as well as heat map
Do you have any errors in the developer tools console? No
Have you tried with a map that doesn't have a separator or insets - like e.g. Australia? 

//code
exporting: {
      enabled: true,
      sourceWidth: 900, // Increased source width for exporting
      sourceHeight: 900, // Increased source height for exporting
      chartOptions: {
        legend: {
          maxHeight: null, // Disable max height for export
          navigation: {
            enabled: false, // Disable pagination in export
          },
          itemStyle: {
            fontSize: '10px', // Keep the font size small
          },
        },
        chart: {
          marginBottom: 300, // Increase margin bottom for export to accommodate all legends
        },
      },
      buttons: {
        contextButton: {
          menuItems: [
            'downloadPNG',
            'downloadJPEG',
            'downloadPDF',
            'downloadSVG',
            'separator',
            'downloadCSV',
            'downloadXLS',
          ],
        },
      },
    },

**Comment by Nikhilraopeechara1** [comment] 2024-10-06 02:56
I have got the issue it is because of this particular code 
    // this.series.chart.update({
                  //   mapView: {
                  //     zoom: 0,
                  //   },
                  // });

**Comment by KacperMadej** [comment] 2024-10-07 10:40
Downloaded 8 times correctly using https://jsfiddle.net/BlackLabel/ewmLcdrj/1/

> I have got the issue it is because of this particular code

Where is that code?

**Comment by KacperMadej** [comment] 2024-12-24 10:42
Closing due to inactivity. In case this or something similar happens again (and preferably, there is a stable way to recreate the problem) feel free to open a new issue (and optionally mention this issue if it feels like relevant).

**Closed by KacperMadej** 2024-12-24 10:42 UTC
Labels: Status: Can't reproduce, Status: Pending reply, Product: Highcharts Maps
