### ISSUE TITLE
showEmpty doesn't work when min and max are defined

### ISSUE THREAD

**Issue by slawekkolodziej** [highcharts/highcharts#705] opened 2012-01-17 21:54 UTC
As in title - when axis min and max are defined, axis doesn't hide. However, it hides when you set just min, or just max. See the demo: http://jsfiddle.net/c92Zn/

**Comment by alexcohaniuc** [comment] 2015-04-14 12:42
Can you elaborate please on how this is not a bug?

**Comment by highslide-software** [comment] 2015-04-14 12:49
Empty in this case means that the axis does not have information that defines how it should draw labels. Once you set min and max, it does have that information.

But from your comment I assume that you consider an empty axis an axis that has no populated data series?

**Comment by alexcohaniuc** [comment] 2015-04-14 12:59
Hi,
Yes, makes sense now.
Would be very useful to have a showEmptyData or something.

Is that something you might consider adding?
As I've seen a couple of threads having the same issue.

**Comment by pawanvjadhav** [comment] 2015-06-19 09:46
+1 are you going to add this configuration?

**Comment by highslide-software** [comment] 2015-06-24 11:49
I am a bit concerned about creating new issues, but I did a small refactoring that makes this accessible from the outside, so we can now override the `Axis.prototype.hasData` method like this:

```js
Highcharts.Axis.prototype.hasData = function () {
    return this.hasVisibleSeries;
};
```


[View it live on jsFiddle](http://jsfiddle.net/highcharts/ychgtrk2/)

**Comment by hon2a** [comment] 2017-04-12 13:23
I'd also appreciate a second flag `showWithoutSeries` to act as a stronger version of `showEmpty`. In our current project, we need to set `min` and `max` in almost all cases (to keep the plot area in sync between multiple charts), but showing axes without series makes no sense in our case. It's especially unhelpful in multi-axis charts where hiding a series could greatly increase the ammount of available space if its axis was hidden as well.

@TorsteinHonsi Thanks for the work-around though, that's sufficient for us as we don't have any use for the current version of `showEmpty`.

**Comment by KacperMadej** [comment] 2018-10-10 15:12
In case you want to show no-data message with custom conditions then no-data-to-display module supports showing message about lack of data on function call as presented in [a demo](http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/no-data-to-display/no-data-line) from API reference: 
https://api.highcharts.com/highcharts/noData

Closing this issue as this is not a bug.

**Closed by KacperMadej** 2018-10-10 15:12 UTC
Labels: Not a bug
