### ISSUE TITLE
Preserve xAxis labels after zooming in rangeSelector

### ISSUE THREAD

**Issue by Madhu94** [highcharts/highcharts#9056] opened 2018-09-26 05:51 UTC
#### Expected behaviour
Clicking different buttons on the rangeSelector, should not cut off xAxis labels.

#### Actual behaviour
Only part of the first xAxis label is shown.

#### Live demo with steps to reproduce
To reproduce, click `YTD` in the rangeSelector in this [fiddle](http://jsfiddle.net/p6jrdvw3/9/)

#### Product version
Highstock - 6.x.x

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment] 2018-09-26 08:51
Hi @Madhu94,
Thank you for reporting. I run your demo in a few resolutions and was not able to reproduce the issue. I also hardcoded width as 600px and still no luck.

![ytd](https://user-images.githubusercontent.com/2115686/46068681-02168000-c17a-11e8-80f1-3d137ee572da.gif)


http://jsfiddle.net/BlackLabel/t1q0mg2v/

Could you point me out about your resolution of chart's div?

Chrome:  69.0.3497.92 
MacOSX: Sierra

**Comment by Madhu94** [comment] 2018-09-26 13:04
@sebastianbochan In my example, a dateformatter for the xAxis labels that formats to YYYYMMDD, I am not sure if that has to do with it.

**Comment by pawelfus** [comment] 2018-09-26 13:14
Hi @Madhu94  - your demo has YYYYMM format, changed to YYYYMMDD: http://jsfiddle.net/BlackLabel/p6jrdvw3/11/ - looks fine. Could you set fixed width in the demo? Thanks!

**Comment by pawelfus** [comment] 2018-09-27 10:30
@Madhu94 - by setting `overflow: false` you stricte allow labels to be cut off. You can disable ellipsis by setting [`xAxis.labels.style.textOverflow`](https://api.highcharts.com/highcharts/xAxis.labels.style), demo: http://jsfiddle.net/BlackLabel/xk8ab7sz/

**Comment by KacperMadej** [comment] 2019-01-24 21:34
Looks like the problem was explained and was not a bug
Closing as resolved

**Closed by KacperMadej** 2019-01-24 21:34 UTC
Labels: Cant reproduce, Opened, Pending reply
