### ISSUE TITLE
JSDoc does not support property names with dash

### ISSUE THREAD

**Issue by cosycode** [highcharts/highcharts#8260] opened 2018-04-30 11:54 UTC
JSDoc converts property name of

- rangeSelector.buttonTheme.stroke-width (RangeSelector.js)
- mapNavigation.buttonOptions.theme.stroke-width (Map.js)
- mapNavigation.buttonOptions.theme.text-align (Map.js)
- mapNavigation.buttons.[unknown] (Map.js)

into undefined or empty string.

**Comment by KacperMadej** [comment] 2018-10-05 14:52
@sophiebremer 
There's `Won't fix` label here, but the issue is open.
Is the issue resolved? (there are some related commits)

**Comment by sophiebremer** [comment] 2018-10-05 15:36
@KacperMadej
I partially solved it with a workaround, but there are some problems, that can not be fixed by using JSDoc at all. So it can be closed, but is not solved. We just have to get rid of dash names in longterm (or JSDoc addresses the issue).

**Closed by sophiebremer** 2018-10-05 15:36 UTC
Labels: Docs, Won't fix
