### ISSUE TITLE
Label for axis plot lines is not fully visible

### ISSUE THREAD

**Issue by harshad-kumbhar** [highcharts/highcharts#16376] opened 2021-09-21 12:17 UTC
Hi

I am trying to plot plotlines on y-axis with a data label. But data label is not fully visible when we set align to 'right' or 'center'. Its position is not proper.
I had used useHTML: true, for applying background color and border to the data label. Please refer the below jsfiddle.
https://jsfiddle.net/kv3b8o0L/1/

So how I can fix this issue of alignment? (I want to give background color and border as well)

**Comment by raf18seb** [comment] 2021-09-21 14:58
Closing as a duplicate of https://github.com/highcharts/highcharts/issues/16376

**Closed by raf18seb** 2021-09-21 14:58 UTC
