### ISSUE TITLE
Panning does not work with inverted axes

### ISSUE THREAD

**Issue by pghilardi** [highcharts/highcharts#4902] opened 2016-01-06 16:52 UTC
I have a plot that is inverted and the pan operation does not works, returning totally wrong values when panning.

**Comment by KacperMadej** [comment] 2016-01-07 12:02
Same issue as #4077 (Duplicate of #4123)

**Closed by KacperMadej** 2016-01-07 12:02 UTC
Labels: Duplicate

**Comment by TorsteinHonsi** [comment] 2016-01-07 14:47
@pghilardi Issue #4077 has now been fixed.
