### ISSUE TITLE
Tick interval should be updated after chart.getAxisMargins() during rendering

### ISSUE THREAD

**Issue by xuebinsu** [highcharts/highcharts#14340] opened 2020-10-13 09:31 UTC
#### Expected behaviour
Tick interval should be updated after `chart.getAxisMargins()` in `chart.render()`

#### Actual behaviour
Tick interval only gets updated in `axis.setScale()` in `chart.render()`. After that, in `chart.getAxisMargins()`, `axis.len` will be updated and the tick interval of the axis depends on `axis.len` due to normalization. However, the tick interval does not get updated.

#### Product version

latest, also checked in the master branch

**Comment by PaulDalek** [comment] 2020-10-13 12:01
Hi @xuebinsu

Thank you for reporting this issue. Please provide us with a simplified live example along with the explanation of what doesn’t work and with steps to reproduce the problem. Thanks.

**Comment by xuebinsu** [comment] 2020-10-13 14:13
This issue would cause chart inconsistency when calling chart.reflow() immediately after the first rendering. It is not easy to come up with a case to reproduce the inconsistency but that can certainly happen. Could you please confirm that this is a bug of Highcharts by simply reviewing the code (e.g., [Chart.ts](https://github.com/highcharts/highcharts/blob/master/ts/Core/Chart/Chart.ts) ?

**Comment by xuebinsu** [comment] 2020-10-13 14:52
As an example, the following two pieces of code produces different charts:
`Highcharts.chart('container', {
		chart: {
    	height: 236
    },
    series: [{
        data: [0.3, 0.4, 0.5, 0.6, 0.8]
    }]
});`

`Highcharts.chart('container', {
		chart: {
    	height: 236
    },
    series: [{
        data: [0.3, 0.4, 0.5, 0.6, 0.8]
    }]
}).reflow();`

This should not happen since the window does not change at all.

**Comment by pawelfus** [comment] 2020-10-14 11:23
Just tested, works fine: https://jsfiddle.net/BlackLabel/njsLtqpw/

Anyway, this a bit more complicated than what you described in the issue. Initial rendering might be slightly different from any subsequent rendering. See short explanation in #14216 and for a longer one check #13451

**Comment by xuebinsu** [comment] 2020-10-14 13:21
@pawelfus Thanks for your reply. This is what the charts look like on my screen. The figure looks incomplete since if I resize the window, the two charts would both reflow and the initial config would be overridden.
![image](https://user-images.githubusercontent.com/12034000/95994102-735d2480-0e62-11eb-9a4f-eb6d19f0deae.png)

To be precise, In order to reproduce the bug, you can tweak the height of the chart such that axis.tickInterval falls into different ranges when calling normalizeTickInterval() in the two cases (with and without `reflow()`).

**Comment by xuebinsu** [comment] 2020-10-14 13:58
@pawelfus I read your reply in #13451 but I dont think the argument applies here because the x-axis remains exactly the same in the two cases. I think this issue may be caused by the fact that someone forgot both that chart.getAxisMargins() would change axis.len and that axis.tickInterval depends on axis.len at the same time.

**Comment by pawelfus** [comment] 2020-10-15 13:50
Every additional iteration takes a toll in performance- that's something we are very strict about. Even if we decide to do that, we have multiple other issues that might make even worse results. Let's start with a possibility of an infinite loop. This may happen and if something may happen, it will eventually happen to someone. We can avoid this infinite loop by limiting number of iterations (a) and/or setting a threshold where difference would be small (b) - for example 1px.

Solution (a) - again, there will be an edge cases where it will fail and we will decrease the performance. Not good at all.
Solution (b) - again, there will be another edge case where some chart config may produce different results after reflowing (because we start from different state of a chart, we may end up in yAxis wider by 1px than initially rendered). And we will see the performance decrease.

Actually, we have both, (a) and (b) implemented with a maximum of two iterations. You are already in the edge case with a very specific height, width and the dataset. From the end-user perspective, there might be no difference between rendered `yAxis.max` at 1 or 0.75.

If your chart has a very basic config, we are trying our best to find what you want to display. But only you know what kind of dataset you want to render. Configure chart, by setting options like `tickAmount` or `tickInterval` to give chart more information. There are more options to use, ending on `xAxis.width` and `yAxis.height` which can force chart to render with fixed size of a plotting area.

Just to be on the same page, I'm not saying it can't be improved, or we don't want to. And I understand this is problematic in your test suite. But why in the first place you expect to have exactly the same `tickInterval` on the chart before and after reflowing? Does it matter for the test? If yes, then I would recommend setting fixed `tickInterval` instead of using auto calculated one.

**Comment by xuebinsu** [comment] 2020-10-16 11:57
Thanks for your explanation. I have no better solution for now and I think this issue can be closed.

**Comment by pawelfus** [comment] 2020-10-16 14:08
Closing the issue as duplicate of #13451

**Closed by pawelfus** 2020-10-16 14:08 UTC
Labels: Type: Undecided
