### ISSUE TITLE
Scatter plot with regression line, regression line not showing up

### ISSUE THREAD

**Issue by MuhmdRaouf** [highcharts/highcharts#18346] opened 2023-01-23 22:41 UTC
#### Expected behaviour
Both Scatter plots with regression line show.

#### Actual behaviour
only the Scatter plot point showing, regression line not showing.
the red dots are the regression line points

<img width="663" alt="Screenshot 2023-01-24 at 12 32 54 AM" src="https://user-images.githubusercontent.com/10425180/214165618-21b0b9c5-5339-4696-846d-f551f89249ff.png">

#### Live demo with steps to reproduce
here's the very same code and values I am using for this graph,
the weird thing is it's showing in the jsfiddle
but not in my project 😢, I also included bootstap and font imports in the jsfiddle in case of anyone wonder if i am importing anything else.
https://jsfiddle.net/vgmf3hd5/

#### Product version

Highcharts latest 10.3.3

#### Affected browser(s)
Chrome
Safari
So far all my browsers

**Comment by pawellysy** [comment] 2023-01-24 10:33
Sorry, but we can't investigate the issue if we can't reproduce it. The demo you sent us are 2 simple series - scatter, and line, and there is nothing wrong with this demo. It looks to me like you might have something wrong with the config. Please either share the demo, where the demo is reproduced or reach out to us via [our available support channels](https://www.highcharts.com/blog/support/)

**Comment by MuhmdRaouf** [comment] 2023-01-25 14:52
@pawellysy I have found the issue while investigating 
here's a reproducible link for the issue https://jsfiddle.net/rqo8s7y6/
it only happens if you add this CSS class, if you remove it it works normally
```css
*,
html *,
body * {
    width: auto;
    height: auto;
}
```

**Comment by pawellysy** [comment] 2023-01-26 11:14
@MuhmdRaouf the `*` selector selects all items on the whole page, so this is certainly an Antipattern. I'd suggest completely deleting this item, or using more specific selectors. Closing since this is not a bug.

**Closed** 2023-01-26 11:14 UTC
Labels: Status: Can't reproduce, Status: Pending reply
