### ISSUE TITLE
Meteogram example broken

### ISSUE THREAD

**Issue by rogut** [highcharts/highcharts#6624] opened 2017-04-21 11:57 UTC
The example at 

http://www.highcharts.com/demo/combo-meteogram#https://www.yr.no/place/United_Kingdom/England/London/forecast_hour_by_hour.xml

is broken

**Comment by pawelfus** [comment] 2017-04-21 11:58
Thanks for the report! It's a duplicate of #6550

**Closed by pawelfus** 2017-04-21 11:58 UTC
