### ISSUE TITLE
Additional series appearing in Gantt Chart

### ISSUE THREAD

**Issue by Sreejithga** [highcharts/highcharts#17304] opened 2022-05-17 17:43 UTC
#### Expected behaviour
Plot the provided the series data into Gantt chart and show the bars proper

#### Actual behaviour
Gantt Chart is giving additional row item which is unexpected

#### Live demo with steps to reproduce

Kindly check this fiddle where the issue is reproduced
https://jsfiddle.net/sreejithga/y1pqeh35/2/
Please help us with the reason why this issue is happening, also please help resolve the same. Thanking you !

![image](https://user-images.githubusercontent.com/53110553/168876679-502dc426-a712-4574-a7ec-8ed909c81206.png)

#### Product version

Highcharts Gantt JS v10.1.0 (2022-04-29)

**Comment by pawellysy** [comment] 2022-05-18 13:18
Hello @Sreejithga, thanks for reporting this issue!
This is expected behavior. The Axis' extremes depend on the max and min values that are displayed on the given axis. You are defining data, where the max value is 2.6, which makes the category axis display values from 0-2.6 and the max value is rounded to the closest higher integer, which is 3. What you could do is manually set the extremes. 


Here is the demo: https://jsfiddle.net/BlackLabel/b18n74kx/1/

Closing, since this is not a bug.


PS: instead of translating each point to fit into the chart, wouldn't you like to just set its correct y value?

**Closed** 2022-05-18 13:18 UTC
Labels: Type: Not a bug

**Comment by Sreejithga** [comment] 2022-05-19 05:50
Thanks @pawellysy for your quick response, yes I will do that and will check asap. 

But as an alternate approach, I'm now trying to overlap my bars as in the below fiddle, one bar with Width 35 and inner bar with Width 20
https://jsfiddle.net/sreejithga/zqc1f0uL/22/

But for some reason the Formatter is showing undefined even though I've a value 75, I've raised an other ticket for this issue, which we can discuss in the below ticket, if you can help me with the reason for this issue.
https://github.com/highcharts/highcharts/issues/17308

Thanking you in advance

**Comment by pawellysy** [comment] 2022-05-19 15:13
Hi again! I replied in the referenced topic. In case of any further problems with highcharts configuration, please reach out to us via our support channels: https://www.highcharts.com/blog/support/ Thanks!
