### ISSUE TITLE
chrome 62, highchart v4.2.5 , Uncaught TypeError: Cannot use 'in' operator to search for '0' in arguments_marker

### ISSUE THREAD

**Issue by daring123** [highcharts/highcharts#7349] opened 2017-11-03 02:22 UTC
#### Expected behaviour
No javascript errors

#### Actual behaviour
highcharts.unminified.js:25 Uncaught TypeError: Cannot use 'in' operator to search for '0' in arguments_marker
at forEach (<anonymous>)
at s (highcharts.unminified.js:25)
at c.drawTrackerGraph [as drawTracker] (highcharts.unminified.js:330)
at c.render (highcharts.unminified.js:271)
at highcharts.unminified.js:232
at Array.forEach (<anonymous>)
at s (highcharts.unminified.js:25)
at C.Chart.renderSeries (highcharts.unminified.js:231)
at C.Chart.render (highcharts.unminified.js:233)
at C.Chart.firstRender (highcharts.unminified.js:236)

#### Live demo with steps to reproduce

[jsfiddle deom](https://jsfiddle.net/phbLL3q8/)
this demo works fine.My data is very large.In the demo , I only give a sample of the data. when the chrome version is up to 62.0.3202.62, It goes wrong. 
#### Affected browser(s)

google chrome 62.0.3202.62

**Comment by pawelfus** [comment] 2017-11-03 09:54
Hi @daring123 

Thank you for reporting the issue, it's a duplicate of #7298

PS: For me it looks fine: 

![screen shot 2017-11-03 at 10 51 37](https://user-images.githubusercontent.com/1453926/32368208-4aabfc7e-c085-11e7-8765-4eca8c457aff.png)

**Closed by pawelfus** 2017-11-03 09:54 UTC
Labels: Duplicate
