### ISSUE TITLE
Update of scrollablePlotArea.minWidth doesn't work (chart doesn't reflow)

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#14487] opened 2020-11-04 12:31 UTC
Updating `chart.scrollablePlotArea.minWidth` doesn't work. `chart.reflow()` helps with the first update, but doesn't help with next ones.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/xazyr2h1/ 

#### Product version
Highcharts 8.2.2

**Comment by PaulDalek** [comment] 2020-11-04 13:53
Here’s the [comment](https://github.com/highcharts/highcharts/issues/14277#issuecomment-700711811) with a workaround.

Closing as a duplicate of the #14277.

**Closed** 2020-11-04 13:53 UTC
Labels: Type: Duplicate
