### ISSUE TITLE
HighStock annotation dragging issue

### ISSUE THREAD

**Issue by moryakovdv** [highcharts/highcharts#18871] opened 2023-04-25 07:06 UTC
Hello. Probably there is a bug in annotation dragging mechanism when line serie is added to plot

#### Expected behaviour
1. Plot the `candlestick` chart. 
2. Set extremes with navigator
3. add the `segment` annotation to it.
4. Drag any control point of the annotation line to new position. Point should follow mouse cursor.
5. Add indicator `Acceleration Band`.
6. Dragging any control point of the annotation line should work as usual.

#### Actual behaviour
After Acceleration Band series appear on the plot dragged control point stops obey cursor position and behaves weird.
Seems, this behavior appears not only if you add Acceleration Bands, but if any other line serie presents in the plot (even on a different YAxis).
Also other types of annotations (Basic, Fibo...) are dragged with the same issue.

#### Live demo with steps to reproduce
[js-fiddle](https://jsfiddle.net/n0fy45sx/6/)
Probably setting the extremes is essential to reproduce.

#### Product version
Highstock current

#### Affected browser(s)
FF

Thanks in advance

**Comment by karolkolodziej** [comment] 2023-04-25 13:01
Hi @moryakovdv! Thank you for reporting that.

Closing as duplicate of: https://github.com/highcharts/highcharts/issues/18459

**Closed by karolkolodziej** 2023-04-25 13:01 UTC
