### ISSUE TITLE
resizeYAxes did not reposition the adjacent Y-axis to reoccupy the removed Y-axis properly

### ISSUE THREAD

**Issue by jackytanjq** [highcharts/highcharts#16969] opened 2022-02-08 01:08 UTC
#### Expected behaviour
After removing an indicator with a separate Y-axis among other indicators with separate Y-axis in the Indicator's edit tab, the removed indicator's Y-axis area will be reused by adjacent indicators.

#### Actual behaviour
Removing an indicator with a separate Y-axis among other indicators with separate Y-axis in the Indicator's edit tab, did not reposition the adjacent indicators properly.

#### Live demo with steps to reproduce
Steps to reproduce in the [demo](https://www.highcharts.com/demo/stock/stock-tools-gui):
1) Upon loading the demo for the first time, add 5 indicators with a separate Y-axis (eg. ATR).
2) Open up the "Indicators" window and **remove any of the indicators from the 2nd Y-axis onwards**.
    Meaning if there are ATR(11), ATR(24), ATR(36), ATR(48) and ATR(55) indicators in the chart.
    Then remove any indicators from ATR(24) to ATR(55) to see the issue as shown in the GIF below:
![Highcharts resizeYAxes issue](https://user-images.githubusercontent.com/7489622/152898191-ab626419-0795-4848-a62c-4ef14815f475.gif)

#### Product version
Highstock Chart v9.3.3 

#### Affected browser(s)
N/A

**Comment by raf18seb** [comment] 2022-02-08 09:53
Closing as a duplicate of https://github.com/highcharts/highcharts/issues/15735

**Closed by raf18seb** 2022-02-08 09:53 UTC
