### ISSUE TITLE
Highstock + boost: Problems with xy-zoom

### ISSUE THREAD

**Issue by till-koppers** [highcharts/highcharts#6865] opened 2017-06-19 11:23 UTC
#### Expected behaviour
All series are displayed inside the plotarea after zooming.

#### Actual behaviour
![image](https://user-images.githubusercontent.com/22466242/27282750-a189dad4-54f1-11e7-84ce-964b77e22a83.png)

#### Live demo with steps to reproduce
Demo: http://jsfiddle.net/r2q820yf/

#### Affected browser(s)
Chrome: Version 58.0.3029.110 (64-bit)
Firefox: Version 54.0 (32-Bit)
IE: Version 11.0.9600.18665

**Comment by sebastianbochan** [comment] 2017-06-19 13:53
Hi @till-koppers,
Thank you for the reporting.

Duplicate of https://github.com/highcharts/highcharts/issues/6594

**Closed by sebastianbochan** 2017-06-19 13:53 UTC
