### ISSUE TITLE
Panning while zoomed causes markers to disappear

### ISSUE THREAD

**Issue by bbass-deloitte** [highcharts/highcharts#6649] opened 2017-04-26 17:40 UTC
#### Expected behaviour
When panning while zoomed, markers that are rendered at the extremes of the chart should not disappear when they are panned out of and back into the viewport.

#### Actual behaviour
At any level of zoom, with panning enabled and configured with a pan key (shift in the example below), when data points at the extremes of the chart are panned out of and back into the view port, the markers are lost. The data is still present. Resetting the zoom restores the marker. 

Please see this forum post for details, screenshots, jsfiddle and a response from Paweł Dalek: https://forum.highcharts.com/highcharts-usage/zoom-panning-losing-markers-t38695/

#### Affected browser(s)
IE 11+
Chrome (latest)
Others not tested

**Comment by pawelfus** [comment] 2017-04-27 12:49
Hi @bbass-deloitte 

Thank you for reporting this. It's a duplicate of #5863.

**Closed by pawelfus** 2017-04-27 12:49 UTC
