### ISSUE TITLE
tooltip useHTML=true not working on HighStock in 6.0.1

### ISSUE THREAD

**Issue by primerano** [highcharts/highcharts#7238] opened 2017-10-06 13:29 UTC
#### Expected behaviour
useHtml: true should result in a html tooltip

#### Actual behaviour
SVG is always returned on highstock 6.0.1

#### Live demo with steps to reproduce

HTML tooltip works in 5.x

http://jsfiddle.net/primerano/0grm1vro/

HTML tooltip does not work  in 6.x

http://jsfiddle.net/primerano/Lf4qyt8t/

#### Affected browser(s)

all

**Comment by pawelfus** [comment] 2017-10-06 14:32
Hi @primerano 

This is caused by change in v6: in v6 `tooltip.split` is set to true by default, without useHTML support. You can get previous tooltip with `useHTML` by disabling `split`, demo: http://jsfiddle.net/0grm1vro/2/

**Comment by bazineta** [comment] 2017-10-09 15:51
While at least in our usage, setting setting `split: false` does rectify the issue, the documentation indicates that the default is false:

http://api.highcharts.com/highcharts/tooltip.split

Is this a temporary bug that we need to workaround for the moment, or a permanent change? If it's permanent, then the documentation for useHTML should also be modified to indicate the requirement.

**Comment by primerano** [comment] 2017-10-10 11:30
Setting this to false fixed my problem.  Thanks.

It seems that this default of true only applies to highstock and not highmaps or the base highcharts.

Perhaps the default should be put back to false for consistency?

**Comment by pawelfus** [comment] 2017-10-10 11:57
This is expected change, just docs are not updated, we will fix that, thank you for letting us know!

@TorsteinHonsi - what do you think about `split` + `useHTML`?

**Comment by TorsteinHonsi** [comment] 2017-10-17 11:59
> the documentation indicates that the default is false

You are linking to the Highcharts documentation. Highstock has a different default: http://api.highcharts.com/highstock/tooltip.split

Under any circumstance, `useHTML` is fixed now.

**Closed** 2017-10-17 11:58 UTC

**Comment by anthonyjlmorel** [comment] 2017-10-18 13:32
I just ran into this issue and just saw you provided a fix. Do you have an idea of when are you gonna release this (in a 6.0.2 for instance) ?

**Comment by pawelfus** [comment] 2017-10-18 14:51
Hi, v6.0.2 should be released this week.
