### ISSUE TITLE
Legend pagination arrow buttons sometimes don't work

### ISSUE THREAD

**Issue by violetVo** [highcharts/highcharts#12883] opened 2020-02-02 09:23 UTC
#### Expected behaviour
Clicking on the pagination arrow buttons should move the the next/previous legend page

#### Actual behaviour
There are cases where we have a lot of series in the legend, and when clicking on the arrow down, instead of going to the next page, the chart acts as I clicked on one of the legend series so I can't navigate to the next page.

I contacted the support center and recieved the following response:
"It looks like the accessibility module is responsible for that behavior. When I inspected the area where clicking results in switching series' visibility, I found out that there is a hidden button that belongs to a div element with '**highcharts-a11y-proxy-container**' class which indicates the accessibility module. Without it, it seems everything works correctly. If you want, you can report it as an issue here: https://github.com/highcharts/highcharts/issues.
​
Example:
https://jsfiddle.net/BlackLabel/9x8jsuom/​

#### Live demo with steps to reproduce
https://jsfiddle.net/stco3nLp/1/

This isn't always reproduced. In my nachine, it's reproduces all the time. I see in the legend 6 pages instead of 8. So my guess is that there is another hidden line in each legend page, and when clicking on the arrow, the click is caoght by the series button instead of the arrow.

#### Product version
7.0.0

#### Affected browser(s)
Chrome, Edge

**Comment by pawelfus** [comment] 2020-02-03 09:56
Thanks for reporting @violetVo 

@oysteinmoseng - could you take a look? Thanks!

**Comment by oysteinmoseng** [comment] 2020-02-03 12:28
This looks like a duplicate of #12090 which has been fixed in more recent versions of Highcharts.

@violetVo Would you be able to test with the latest version and report back if the issue persists?

**Comment by violetVo** [comment] 2020-02-04 11:55
Hi,
I checked with the most recent version v8.0.0 (2019-12-10) and this issue wasn't resolved.

Thanks,
Violet.

**Comment by oysteinmoseng** [comment] 2020-02-05 09:27
I can't seem to reproduce this on my machine. I get 6 pages as well, but all of the series seem to be there? Are you able to reproduce @pawelfus?

**Comment by pawelfus** [comment] 2020-02-05 11:04
I get 6 (most of the time) or 5 (sometimes) pages. Tested with https://jsfiddle.net/8xyn4b02/ (changes names for better readability) in Chrome incognito mode (Version 79.0.3945.130). It seems that the size of scrolling window differs. Sometimes we scroll ~5 lines, sometimes ~6 lines. It doesn't seem to be related to accessibility, demo without works the same way: https://jsfiddle.net/bg4xf3dm/ - note: sometimes you need to refresh page multiple times.

Some screenshots:

- 6 pages:
![Screen Shot 2020-02-05 at 11 57 03](https://user-images.githubusercontent.com/1453926/73836150-ecee3e80-480e-11ea-9403-3261f5038079.png)
![Screen Shot 2020-02-05 at 11 57 12](https://user-images.githubusercontent.com/1453926/73836144-ebbd1180-480e-11ea-8b0b-d46f1bfca788.png)
- 5 pages:
![Screen Shot 2020-02-05 at 11 56 31](https://user-images.githubusercontent.com/1453926/73836154-ee1f6b80-480e-11ea-9b37-315bbf4ec21b.png)
![Screen Shot 2020-02-05 at 11 56 45](https://user-images.githubusercontent.com/1453926/73836152-ed86d500-480e-11ea-98b1-72bdc5d8b025.png)

**Comment by oysteinmoseng** [comment] 2020-02-05 12:48
Okay, removing a11y in title and assigning to team in general

**Comment by Izothep** [comment] 2020-03-13 15:35
The issue with legend pagination looks to be solved with my last commit, however, solving issue with number of pages is much more complicated, as it is related directly to how getBBox method is calculated in Chrome (80.0.3987.132). 

Simplified example: http://jsfiddle.net/BlackLabel/4avbgmoj/1/

On retina displays getBBox height sometimes returns 14 and sometimes 15px.

**Closed** 2020-03-19 08:31 UTC
Labels: Status: In progress, Type: Bug

**Comment by violetVo** [comment] 2020-06-24 07:02
Hi,
What is the version of Highchartsthat contains the fix?
Is it 8.1.2?
![image](https://user-images.githubusercontent.com/17854021/85511701-b0768000-b601-11ea-9252-e70f05e0efb9.png)

@Izothep - What do you mean by "solving issue with number of pages" ?

Thanks,
Violet.

**Comment by oysteinmoseng** [comment] 2020-06-24 07:37
@violetVo This fix has been included since v8.1.0

**Comment by Izothep** [comment] 2020-06-24 09:26
@violetVo thanks for the message! There is an additional issue related to number of legend pages displayed on Retina devices - sometimes there are 5 and sometimes 6 pages visible on the same chart. However, the fix for legend pagination is fixed.
